# -*- coding: utf-8 -*-
"""Contenu Bimestre 1 — Séances 1 à 6. Manuel SVT 8e J-Learn.
Conventions : **mot** = mot clé (bleu+gras dans la leçon, bordeaux dans les corrigés).
Niveau : 8e (~9 ans), phrases courtes, vocabulaire simple. Aucune date calendaire.
Source : Répartition annuelle 8e (Connaissances Usuelles / SVT), Bimestre 1 :
le corps humain, les articulations, les muscles, l'os, les organes des sens.
"""

SEANCES_A = [
{
"n": 1, "titre": "Les trois parties du corps", "theme": "Le corps humain",
"objectif": "citer les trois grandes parties du corps humain",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma du corps humain affiché au tableau",
"image": ("svt8e_corps_parties.png", "Schéma : les trois grandes parties du corps : la tête, le tronc et les membres."),
"revision": [
    ("Comment t'appelles-tu et quel âge as-tu ?", "Je m'appelle ... et j'ai ... ans."),
    ("Montre ta main droite, puis montre ton pied gauche.", "L'élève montre sa main droite, puis son pied gauche."),
],
"situation": "Ce matin, Rija se regarde dans le miroir avant d'aller à l'école. Il voit sa tête, son ventre et ses bras. La maîtresse lui demande : quelles sont les trois grandes parties du corps ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les trois grandes parties du corps humain.",
    "Je lis le titre au tableau : Les trois parties du corps.",
],
"observation": [
    "Regardez le schéma du corps humain affiché au tableau.",
    "Montrez sur vous-même : la tête, le tronc, puis les membres.",
],
"analyse": [
    ("Quelle partie du corps se trouve en haut ?", "En haut du corps se trouve la tête."),
    ("Quelle partie du corps se trouve au milieu ?", "Au milieu du corps se trouve le tronc."),
    ("Que trouve-t-on de chaque côté du tronc et en bas ?", "De chaque côté du tronc on trouve les bras, et en bas on trouve les jambes : ce sont les membres."),
],
"synthese": "Notre corps a trois grandes parties : la tête, le tronc et les membres. Les membres sont les deux bras et les deux jambes.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le corps a trois grandes parties.", "2. La tête se trouve en bas du corps.", "3. Les bras et les jambes sont les membres.", "4. Le tronc se trouve au milieu du corps."],
     "cor": ["1. **Vrai** : le corps a trois grandes parties.", "2. **Faux** : la tête se trouve en haut du corps.", "3. **Vrai** : les bras et les jambes sont les membres.", "4. **Vrai** : le tronc se trouve au milieu du corps."]},
    {"c": "Complète avec les mots suivants : tête, tronc, membres.",
     "items": ["1. En haut du corps, il y a la ...", "2. Au milieu du corps, il y a le ...", "3. Les bras et les jambes sont les ...", "4. Les trois grandes parties du corps sont la ..., le ... et les ...."],
     "cor": ["1. En haut du corps, il y a la **tête**.", "2. Au milieu du corps, il y a le **tronc**.", "3. Les bras et les jambes sont les **membres**.", "4. Les trois grandes parties sont la **tête**, le **tronc** et les **membres**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Combien le corps a-t-il de grandes parties ? A. Deux B. Trois C. Quatre", "2. Quelle partie est en haut ? A. Le tronc B. Les membres C. La tête", "3. Quelle partie est au milieu ? A. La tête B. Le tronc C. Le bras", "4. Que sont les bras et les jambes ? A. Le tronc B. Les membres C. La tête"],
     "cor": ["1. **B. Trois** : le corps a trois grandes parties.", "2. **C. La tête** : elle est en haut.", "3. **B. Le tronc** : il est au milieu.", "4. **B. Les membres** : les bras et les jambes."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quelles sont les trois grandes parties du corps ?", "2. Où se trouve la tête ?", "3. Où se trouve le tronc ?", "4. De quoi sont formés les membres ?"],
     "cor": ["1. Les trois grandes parties du corps sont la **tête**, le **tronc** et les **membres**.", "2. La **tête** se trouve en haut du corps.", "3. Le **tronc** se trouve au milieu du corps.", "4. Les **membres** sont formés des deux bras et des deux jambes."]},
],
"lecon": [
    (None, ["Notre **corps** est formé de trois grandes parties : la **tête**, le **tronc** et les **membres**."]),
    ("1. La tête", ["La **tête** est en haut du corps. Elle porte les yeux, le nez, la bouche et les oreilles."]),
    ("2. Le tronc", ["Le **tronc** est au milieu du corps. Il comprend la poitrine, le ventre et le dos."]),
    ("3. Les membres", ["Les **membres** sont attachés au tronc : les deux **bras** en haut et les deux **jambes** en bas."]),
],
"mots_cles": ["corps", "tête", "tronc", "membres"],
},
{
"n": 2, "titre": "Les articulations", "theme": "Le corps humain",
"objectif": "citer quelques articulations du corps et expliquer leur rôle",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma des articulations affiché au tableau",
"image": ("svt8e_articulations.png", "Schéma : l'articulation permet de plier le bras et la jambe."),
"revision": [
    ("Quelles sont les trois grandes parties du corps ?", "Les trois grandes parties du corps sont la tête, le tronc et les membres."),
    ("Montre le tronc, puis montre les membres.", "L'élève montre le tronc, puis montre les bras et les jambes."),
],
"situation": "Pendant la récréation, Hery plie le bras pour lancer le ballon, puis il plie la jambe pour courir. À quels endroits son corps plie-t-il ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre ce qu'est une articulation.",
    "Je lis le titre au tableau : Les articulations.",
],
"observation": [
    "Regardez le schéma des articulations affiché au tableau.",
    "Pliez votre bras au coude, puis pliez votre jambe au genou.",
],
"analyse": [
    ("À quel endroit le bras plie-t-il ?", "Le bras plie au niveau du coude."),
    ("À quel endroit la jambe plie-t-elle ?", "La jambe plie au niveau du genou."),
    ("Qu'est-ce qu'une articulation ?", "Une articulation est l'endroit où deux os se rencontrent et où le corps peut plier."),
],
"synthese": "Une articulation est l'endroit où deux os se rencontrent. Elle permet de plier et de bouger. Les principales articulations sont l'épaule, le coude, le poignet, la hanche, le genou et la cheville.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le coude est une articulation.", "2. L'articulation empêche de bouger.", "3. Le genou permet de plier la jambe.", "4. Les os se rencontrent au niveau de l'articulation."],
     "cor": ["1. **Vrai** : le coude est une articulation.", "2. **Faux** : l'articulation permet de bouger.", "3. **Vrai** : le genou plie la jambe.", "4. **Vrai** : deux os se rencontrent à l'articulation."]},
    {"c": "Complète avec les mots suivants : articulation, coude, genou, os.",
     "items": ["1. L'endroit où le corps plie s'appelle une ...", "2. Le bras plie au niveau du ...", "3. La jambe plie au niveau du ...", "4. À l'articulation, deux ... se rencontrent."],
     "cor": ["1. L'endroit où le corps plie s'appelle une **articulation**.", "2. Le bras plie au niveau du **coude**.", "3. La jambe plie au niveau du **genou**.", "4. À l'articulation, deux **os** se rencontrent."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Qu'est-ce qu'une articulation ? A. Un muscle B. Un os C. L'endroit où deux os se rencontrent", "2. Où le bras plie-t-il ? A. Au coude B. Au genou C. Au poignet", "3. Quelle articulation plie la jambe ? A. L'épaule B. Le genou C. Le coude", "4. À quoi sert une articulation ? A. À respirer B. À bouger C. À manger"],
     "cor": ["1. **C. L'endroit où deux os se rencontrent**.", "2. **A. Au coude** : le bras plie au coude.", "3. **B. Le genou** : il plie la jambe.", "4. **B. À bouger** : l'articulation permet de bouger."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce qu'une articulation ?", "2. Cite deux articulations du corps.", "3. À quoi servent les articulations ?", "4. Qu'est-ce qui se rencontre au niveau d'une articulation ?"],
     "cor": ["1. Une **articulation** est l'endroit où deux **os** se rencontrent.", "2. Le **coude** et le **genou** (ou l'épaule, le poignet, la hanche, la cheville).", "3. Les **articulations** servent à plier et à bouger le corps.", "4. Deux **os** se rencontrent au niveau d'une articulation."]},
],
"lecon": [
    (None, ["Une **articulation** est l'endroit où deux **os** se rencontrent. C'est là que le corps plie."]),
    ("1. Qu'est-ce qu'une articulation ?", ["L'**articulation** est l'endroit où deux **os** se rencontrent. Grâce à elle, le corps peut plier, tourner et bouger."]),
    ("2. Les principales articulations", ["Les principales articulations sont l'**épaule**, le **coude**, le **poignet**, la **hanche**, le **genou** et la **cheville**. Le coude plie le bras, le genou plie la jambe."]),
    ("3. Le rôle des articulations", ["Les **articulations** permettent tous les mouvements du corps : marcher, courir, lancer, écrire et sauter."]),
],
"mots_cles": ["articulation", "os", "coude", "genou", "épaule"],
},
{
"n": 3, "titre": "Les muscles", "theme": "Le corps humain",
"objectif": "expliquer que les muscles font bouger le corps",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma du bras plié affiché au tableau",
"image": ("svt8e_muscles.png", "Schéma : le muscle du bras se gonfle quand on plie le bras."),
"revision": [
    ("Qu'est-ce qu'une articulation ?", "Une articulation est l'endroit où deux os se rencontrent."),
    ("Où le bras plie-t-il ?", "Le bras plie au niveau du coude."),
],
"situation": "Lala soulève son cartable plein de livres. Elle sent que son bras devient dur. Pourquoi son bras devient-il dur quand elle le plie ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre ce qu'est un muscle.",
    "Je lis le titre au tableau : Les muscles.",
],
"observation": [
    "Regardez le schéma du bras plié affiché au tableau.",
    "Pliez votre bras et touchez-le : que sentez-vous sous la peau ?",
],
"analyse": [
    ("Que sentez-vous sous la peau quand vous pliez le bras ?", "Sous la peau, on sent une partie molle qui devient dure : c'est le muscle."),
    ("Que fait le muscle quand il se raccourcit ?", "Quand le muscle se raccourcit, il tire sur l'os et le bras se plie."),
    ("Le cœur est-il un muscle ?", "Oui, le cœur est un muscle qui bat sans s'arrêter."),
],
"synthese": "Les muscles sont des parties molles sous la peau. En se raccourcissant, ils tirent sur les os et font bouger le corps. Le cœur est aussi un muscle.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les muscles sont sous la peau.", "2. Les muscles sont durs comme les os.", "3. Les muscles font bouger les os.", "4. Le cœur est un muscle."],
     "cor": ["1. **Vrai** : les muscles sont sous la peau.", "2. **Faux** : les muscles sont des parties molles.", "3. **Vrai** : les muscles font bouger les os.", "4. **Vrai** : le cœur est un muscle."]},
    {"c": "Complète avec les mots suivants : muscles, os, peau, cœur.",
     "items": ["1. Les ... sont des parties molles sous la peau.", "2. Les muscles tirent sur les ... pour faire bouger le corps.", "3. Les muscles se trouvent sous la ...", "4. Le ... est un muscle qui bat toujours."],
     "cor": ["1. Les **muscles** sont des parties molles sous la peau.", "2. Les muscles tirent sur les **os** pour faire bouger le corps.", "3. Les muscles se trouvent sous la **peau**.", "4. Le **cœur** est un muscle qui bat toujours."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Où se trouvent les muscles ? A. Sur les os B. Sous la peau C. Dans les cheveux", "2. Que font les muscles quand ils se raccourcissent ? A. Ils tirent sur les os B. Ils dorment C. Ils grandissent", "3. Quel organe est un muscle ? A. L'œil B. L'oreille C. Le cœur", "4. Qu'est-ce qui fait bouger le corps ? A. Les cheveux B. Les muscles C. Les ongles"],
     "cor": ["1. **B. Sous la peau**.", "2. **A. Ils tirent sur les os**.", "3. **C. Le cœur** : c'est un muscle.", "4. **B. Les muscles** : ils font bouger le corps."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que sont les muscles ?", "2. Où se trouvent les muscles ?", "3. Comment les muscles font-ils bouger le corps ?", "4. Quel muscle bat sans s'arrêter ?"],
     "cor": ["1. Les **muscles** sont des parties molles du corps.", "2. Les **muscles** se trouvent sous la **peau**.", "3. Les **muscles** se raccourcissent et tirent sur les **os**.", "4. Le **cœur** est le muscle qui bat sans s'arrêter."]},
],
"lecon": [
    (None, ["Les **muscles** sont des parties molles qui se trouvent sous la **peau**. Ils font bouger le corps."]),
    ("1. Qu'est-ce qu'un muscle ?", ["Un **muscle** est une partie molle du corps, placée sous la **peau** et attachée aux **os**. Quand on plie le bras, on sent le muscle devenir dur."]),
    ("2. Comment les muscles font-ils bouger le corps ?", ["Le **muscle** se raccourcit et tire sur l'**os** : alors le corps bouge. Le muscle se relâche ensuite et l'os revient à sa place."]),
    ("3. Les muscles travaillent sans arrêt", ["Les **muscles** travaillent toute la journée : pour marcher, courir, écrire et parler. Le **cœur** est un muscle qui bat jour et nuit."]),
],
"mots_cles": ["muscle", "peau", "os", "cœur", "bouger"],
},
{
"n": 4, "titre": "L'hygiène des muscles et des articulations", "theme": "Le corps humain",
"objectif": "appliquer les règles d'hygiène des muscles et des articulations",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "les affiches d'hygiène affichées au tableau",
"image": None,
"revision": [
    ("Que sont les muscles ?", "Les muscles sont des parties molles sous la peau."),
    ("Que font les muscles quand ils se raccourcissent ?", "Ils tirent sur les os et le corps bouge."),
],
"situation": "Avant le sport, le maître fait courir doucement les élèves. Voavy demande : pourquoi faut-il s'échauffer avant de jouer ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les règles d'hygiène des muscles et des articulations.",
    "Je lis le titre au tableau : L'hygiène des muscles et des articulations.",
],
"observation": [
    "Observez les affiches d'hygiène affichées au tableau.",
    "Regardez votre position assise : votre dos est-il droit ?",
],
"analyse": [
    ("Que faut-il faire avant de faire du sport ?", "Avant le sport, il faut s'échauffer doucement."),
    ("Que faut-il faire quand on est fatigué ?", "Quand on est fatigué, il faut se reposer et bien dormir."),
    ("Comment faut-il s'asseoir pour protéger son dos ?", "Il faut s'asseoir le dos droit, sans se pencher."),
],
"synthese": "Pour garder des muscles et des articulations en bonne santé : s'échauffer avant l'effort, se reposer, bien dormir, se tenir droit et ne pas porter de charges trop lourdes.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut s'échauffer avant le sport.", "2. On peut porter des charges très lourdes.", "3. Il faut bien dormir pour reposer les muscles.", "4. Il faut s'asseoir le dos penché."],
     "cor": ["1. **Vrai** : l'échauffement prépare les muscles.", "2. **Faux** : les charges trop lourdes abîment le dos.", "3. **Vrai** : le sommeil repose les muscles.", "4. **Faux** : il faut s'asseoir le dos droit."]},
    {"c": "Complète avec les mots suivants : échauffer, reposer, droit, lourdes.",
     "items": ["1. Avant le sport, il faut s'...", "2. Quand on est fatigué, il faut se ...", "3. Pour écrire, on s'assoit le dos ...", "4. Il ne faut pas porter de charges trop ...."],
     "cor": ["1. Avant le sport, il faut s'**échauffer**.", "2. Quand on est fatigué, il faut se **reposer**.", "3. Pour écrire, on s'assoit le dos **droit**.", "4. Il ne faut pas porter de charges trop **lourdes**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que faut-il faire avant le sport ? A. S'échauffer B. Manger beaucoup C. Dormir", "2. Comment faut-il s'asseoir ? A. Penché en avant B. Le dos droit C. Couché", "3. Que faut-il faire quand on est fatigué ? A. Courir B. Se reposer C. Sauter", "4. Pourquoi faut-il s'échauffer ? A. Pour préparer les muscles B. Pour dormir C. Pour manger"],
     "cor": ["1. **A. S'échauffer**.", "2. **B. Le dos droit**.", "3. **B. Se reposer**.", "4. **A. Pour préparer les muscles** à l'effort."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faut-il faire avant de faire du sport ?", "2. Pourquoi faut-il se tenir le dos droit ?", "3. Cite deux règles d'hygiène des muscles.", "4. Que faut-il éviter de porter ?"],
     "cor": ["1. Avant le sport, il faut s'**échauffer** doucement.", "2. Il faut se tenir le **dos droit** pour protéger le dos et les muscles.", "3. S'**échauffer** avant l'effort et se **reposer** (bien dormir).", "4. Il faut éviter de porter des charges trop **lourdes**."]},
],
"lecon": [
    (None, ["Pour garder des **muscles** et des **articulations** en bonne santé, il faut suivre des règles d'hygiène."]),
    ("1. Avant et après l'effort", ["Avant le sport, il faut s'**échauffer** doucement. Après l'effort, il faut se **reposer**. La nuit, un bon **sommeil** repose les muscles."]),
    ("2. Les bonnes positions", ["Pour écrire ou lire, on s'assoit le **dos droit**. Il ne faut pas porter de charges trop **lourdes**, car elles abîment le dos et les articulations."]),
    ("3. Les règles à retenir", ["Faire un peu d'**exercice** chaque jour, s'**échauffer** avant le sport, bien **dormir**, se tenir **droit** et éviter les faux mouvements."]),
],
"mots_cles": ["échauffer", "reposer", "dos droit", "sommeil", "exercice"],
},
{
"n": 5, "titre": "L'os et le squelette", "theme": "Le corps humain",
"objectif": "expliquer que les os forment le squelette et soutiennent le corps",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma du squelette affiché au tableau",
"image": ("svt8e_squelette.png", "Schéma : le squelette est formé de tous les os du corps."),
"revision": [
    ("Que faut-il faire avant le sport ?", "Avant le sport, il faut s'échauffer doucement."),
    ("Comment faut-il s'asseoir pour écrire ?", "Il faut s'asseoir le dos droit."),
],
"situation": "Nirina a vu un squelette au centre de santé. Il demande : de quoi le corps est-il soutenu à l'intérieur ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre ce qu'est un os et ce qu'est le squelette.",
    "Je lis le titre au tableau : L'os et le squelette.",
],
"observation": [
    "Regardez le schéma du squelette affiché au tableau.",
    "Touchez votre front, vos genoux et vos doigts : vous sentez les os sous la peau.",
],
"analyse": [
    ("Les os sont-ils durs ou mous ?", "Les os sont durs."),
    ("Comment s'appelle l'ensemble de tous les os ?", "L'ensemble de tous les os s'appelle le squelette."),
    ("Quel os protège le cerveau ?", "Le crâne protège le cerveau."),
],
"synthese": "Les os sont des parties dures du corps. Tous les os forment le squelette. Le squelette soutient le corps et protège les organes : le crâne protège le cerveau, les côtes protègent le cœur et les poumons.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les os sont des parties dures.", "2. Le squelette est formé de tous les os.", "3. Le crâne protège le ventre.", "4. Les côtes protègent le cœur et les poumons."],
     "cor": ["1. **Vrai** : les os sont durs.", "2. **Vrai** : le squelette est l'ensemble des os.", "3. **Faux** : le crâne protège le cerveau.", "4. **Vrai** : les côtes protègent le cœur et les poumons."]},
    {"c": "Complète avec les mots suivants : os, squelette, crâne, côtes.",
     "items": ["1. Les ... sont des parties dures du corps.", "2. Tous les os forment le ...", "3. Le ... protège le cerveau.", "4. Les ... protègent le cœur et les poumons."],
     "cor": ["1. Les **os** sont des parties dures du corps.", "2. Tous les os forment le **squelette**.", "3. Le **crâne** protège le cerveau.", "4. Les **côtes** protègent le cœur et les poumons."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que sont les os ? A. Des parties molles B. Des parties dures C. Des cheveux", "2. Comment s'appelle l'ensemble des os ? A. La peau B. Le squelette C. Le muscle", "3. Que protège le crâne ? A. Le cerveau B. Le cœur C. L'estomac", "4. À quoi sert le squelette ? A. À goûter B. À soutenir le corps C. À entendre"],
     "cor": ["1. **B. Des parties dures**.", "2. **B. Le squelette**.", "3. **A. Le cerveau**.", "4. **B. À soutenir le corps**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que sont les os ?", "2. Qu'est-ce que le squelette ?", "3. Quel est le rôle du squelette ?", "4. Que protègent les côtes ?"],
     "cor": ["1. Les **os** sont des parties **dures** du corps.", "2. Le **squelette** est l'ensemble de tous les **os**.", "3. Le **squelette** soutient le corps et protège les organes.", "4. Les **côtes** protègent le **cœur** et les **poumons**."]},
],
"lecon": [
    (None, ["Les **os** sont des parties dures du corps. Tous les **os** forment le **squelette**."]),
    ("1. Qu'est-ce qu'un os ?", ["Un **os** est une partie **dure** du corps. On sent les os en touchant le front, les genoux et les doigts. L'os est vivant : il grandit avec l'enfant."]),
    ("2. Le squelette", ["Tous les **os** du corps forment le **squelette**. Il donne au corps sa forme et le soutient."]),
    ("3. Le rôle du squelette", ["Le **squelette** soutient le corps et protège les organes : le **crâne** protège le **cerveau**, les **côtes** protègent le **cœur** et les **poumons**."]),
],
"mots_cles": ["os", "squelette", "crâne", "côtes", "cerveau"],
},
{
"n": 6, "titre": "La constitution et la composition de l'os", "theme": "Le corps humain",
"objectif": "décrire simplement la constitution et la composition de l'os",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma de l'os coupé affiché au tableau",
"image": ("svt8e_os_coupe.png", "Schéma : l'os coupé montre la partie dure dehors et la moelle dedans."),
"revision": [
    ("Qu'est-ce que le squelette ?", "Le squelette est l'ensemble de tous les os."),
    ("Que protège le crâne ?", "Le crâne protège le cerveau."),
],
"situation": "À la cuisine, maman coupe un os de zébu pour la soupe. Fara regarde l'intérieur de l'os et demande : qu'y a-t-il dedans ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre de quoi l'os est constitué et composé.",
    "Je lis le titre au tableau : La constitution et la composition de l'os.",
],
"observation": [
    "Regardez le schéma de l'os coupé affiché au tableau.",
    "Observez la partie dure de l'extérieur et la partie molle de l'intérieur.",
],
"analyse": [
    ("Comment est l'extérieur de l'os ?", "L'extérieur de l'os est dur : c'est l'os compact."),
    ("Qu'y a-t-il à l'intérieur de l'os ?", "À l'intérieur de l'os, il y a la moelle, une partie molle."),
    ("Qu'est-ce qui rend l'os dur ?", "Le calcium rend l'os dur et solide."),
],
"synthese": "L'extérieur de l'os est dur : c'est l'os compact. L'intérieur contient la moelle. L'os est formé de calcium qui le rend dur. L'os est vivant : du sang circule dedans.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'extérieur de l'os est mou.", "2. La moelle se trouve à l'intérieur de l'os.", "3. Le calcium rend l'os dur.", "4. L'os est une partie morte du corps."],
     "cor": ["1. **Faux** : l'extérieur de l'os est dur (os compact).", "2. **Vrai** : la moelle est à l'intérieur.", "3. **Vrai** : le calcium rend l'os dur.", "4. **Faux** : l'os est vivant, le sang circule dedans."]},
    {"c": "Complète avec les mots suivants : compact, moelle, calcium, vivant.",
     "items": ["1. L'extérieur de l'os est l'os ...", "2. L'intérieur de l'os contient la ...", "3. Le ... rend l'os dur.", "4. L'os est un organe ...."],
     "cor": ["1. L'extérieur de l'os est l'os **compact**.", "2. L'intérieur de l'os contient la **moelle**.", "3. Le **calcium** rend l'os dur.", "4. L'os est un organe **vivant**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Comment est l'extérieur de l'os ? A. Mou B. Dur C. Liquide", "2. Que contient l'intérieur de l'os ? A. La moelle B. Les cheveux C. La sueur", "3. Qu'est-ce qui rend l'os dur ? A. Le sucre B. L'eau C. Le calcium", "4. L'os est-il vivant ? A. Oui B. Non C. Parfois"],
     "cor": ["1. **B. Dur** : c'est l'os compact.", "2. **A. La moelle**.", "3. **C. Le calcium**.", "4. **A. Oui** : l'os est vivant, le sang circule dedans."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Comment est l'extérieur de l'os ?", "2. Que trouve-t-on à l'intérieur de l'os ?", "3. Qu'est-ce qui rend l'os dur ?", "4. Pourquoi dit-on que l'os est vivant ?"],
     "cor": ["1. L'extérieur de l'os est **dur** : c'est l'os **compact**.", "2. À l'intérieur de l'os, on trouve la **moelle**.", "3. Le **calcium** rend l'os dur et solide.", "4. L'os est **vivant** parce que le **sang** circule dedans et qu'il grandit."]},
],
"lecon": [
    (None, ["L'**os** est dur à l'extérieur et il contient la **moelle** à l'intérieur. Le **calcium** le rend dur."]),
    ("1. L'extérieur de l'os", ["L'extérieur de l'os est **dur** : c'est l'**os compact**. Il protège l'intérieur de l'os."]),
    ("2. L'intérieur de l'os", ["À l'intérieur de l'os, il y a une partie **molle** : la **moelle**. Du **sang** circule dans l'os."]),
    ("3. De quoi l'os est-il formé ?", ["L'os contient du **calcium**, une matière qui le rend **dur** et solide. C'est pourquoi il faut manger des aliments riches en calcium."]),
],
"mots_cles": ["os compact", "moelle", "calcium", "sang", "dur"],
},
]
