# -*- coding: utf-8 -*-
"""Contenu Bimestre 1 — Séances 7 à 12 + Révision + Examen. Manuel SVT 8e J-Learn.
Conventions : **mot** = mot clé (bleu+gras dans la leçon, bordeaux dans les corrigés).
"""

SEANCES_B = [
{
"n": 7, "titre": "Les fractures des os et les accidents des articulations", "theme": "Le corps humain",
"objectif": "expliquer ce qu'est une fracture et citer des accidents des articulations",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "les affiches des accidents affichées au tableau",
"image": None,
"revision": [
    ("Comment est l'extérieur de l'os ?", "L'extérieur de l'os est dur : c'est l'os compact."),
    ("Qu'est-ce qui rend l'os dur ?", "Le calcium rend l'os dur."),
],
"situation": "En jouant au ballon, Mamy tombe et son bras lui fait très mal. Il ne peut plus le bouger. La maîtresse dit que son os est peut-être cassé. Comment appelle-t-on un os cassé ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre ce qu'est une fracture et les accidents des articulations.",
    "Je lis le titre au tableau : Les fractures des os et les accidents des articulations.",
],
"observation": [
    "Observez les affiches des accidents affichées au tableau.",
    "Regardez le bras blessé : il est gonflé et on ne peut plus le bouger.",
],
"analyse": [
    ("Comment appelle-t-on un os cassé ?", "Un os cassé s'appelle une fracture."),
    ("Qu'est-ce qu'une entorse ?", "Une entorse est une articulation qui se tord : un ligament est blessé."),
    ("Qu'est-ce qu'une luxation ?", "Une luxation est un os qui sort de son articulation."),
],
"synthese": "Une fracture est un os cassé. L'entorse est une articulation tordue et la luxation est un os sorti de son articulation. Signes : douleur, gonflement, on ne peut plus bouger.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Une fracture est un os cassé.", "2. Une entorse est un os sorti de son articulation.", "3. Après une fracture, on ne peut plus bouger le membre.", "4. La douleur et le gonflement sont des signes d'accident."],
     "cor": ["1. **Vrai** : la fracture est un os cassé.", "2. **Faux** : l'entorse est une articulation tordue ; l'os sorti est la luxation.", "3. **Vrai** : le membre blessé ne bouge plus bien.", "4. **Vrai** : douleur et gonflement sont des signes."]},
    {"c": "Complète avec les mots suivants : fracture, entorse, luxation, douleur.",
     "items": ["1. Un os cassé s'appelle une ...", "2. Une articulation tordue s'appelle une ...", "3. Un os sorti de son articulation s'appelle une ...", "4. Après un accident, on ressent de la ...."],
     "cor": ["1. Un os cassé s'appelle une **fracture**.", "2. Une articulation tordue s'appelle une **entorse**.", "3. Un os sorti de son articulation s'appelle une **luxation**.", "4. Après un accident, on ressent de la **douleur**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Qu'est-ce qu'une fracture ? A. Un muscle coupé B. Un os cassé C. Une peau rouge", "2. Qu'est-ce qu'une entorse ? A. Une articulation tordue B. Un os cassé C. Un muscle fatigué", "3. Qu'est-ce qu'une luxation ? A. Un os sorti de son articulation B. Un os cassé C. Une peau coupée", "4. Quels sont les signes d'un accident ? A. Douleur et gonflement B. Faim et soif C. Sommeil et rire"],
     "cor": ["1. **B. Un os cassé**.", "2. **A. Une articulation tordue**.", "3. **A. Un os sorti de son articulation**.", "4. **A. Douleur et gonflement**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce qu'une fracture ?", "2. Qu'est-ce qu'une entorse ?", "3. Qu'est-ce qu'une luxation ?", "4. Cite deux signes d'un accident des os ou des articulations."],
     "cor": ["1. Une **fracture** est un **os cassé**.", "2. Une **entorse** est une **articulation tordue**.", "3. Une **luxation** est un **os sorti** de son articulation.", "4. La **douleur** et le **gonflement** (on ne peut plus bouger)."]},
],
"lecon": [
    (None, ["Une **fracture** est un os cassé. L'**entorse** et la **luxation** sont des accidents des articulations."]),
    ("1. La fracture", ["Une **fracture** est un **os cassé**. Elle arrive après une chute, un coup ou un accident. Le membre blessé fait mal et on ne peut plus le bouger."]),
    ("2. L'entorse", ["L'**entorse** est une **articulation** qui se tord brusquement. L'articulation **gonfle** et fait mal."]),
    ("3. La luxation", ["La **luxation** est un **os** qui sort de son articulation. Il faut aller vite au centre de santé."]),
],
"mots_cles": ["fracture", "entorse", "luxation", "douleur", "gonflement"],
},
{
"n": 8, "titre": "Les soins et l'hygiène de l'os", "theme": "Le corps humain",
"objectif": "citer les soins des fractures et les règles d'hygiène de l'os",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "l'affiche des soins et des bons aliments affichée au tableau",
"image": None,
"revision": [
    ("Qu'est-ce qu'une fracture ?", "Une fracture est un os cassé."),
    ("Qu'est-ce qu'une entorse ?", "Une entorse est une articulation tordue."),
],
"situation": "Le docteur a mis un plâtre sur le bras de Mamy. Mamy demande : que faut-il faire pour que l'os se répare et pour avoir des os solides ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les soins des fractures et l'hygiène de l'os.",
    "Je lis le titre au tableau : Les soins et l'hygiène de l'os.",
],
"observation": [
    "Observez l'affiche des soins et des bons aliments affichée au tableau.",
    "Regardez le bras de Mamy : il est immobilisé dans un plâtre.",
],
"analyse": [
    ("Que fait-on quand un os est cassé ?", "On va au centre de santé : le docteur immobilise l'os avec un plâtre."),
    ("Que faut-il manger pour avoir des os solides ?", "Il faut manger des aliments riches en calcium : le lait et le fromage."),
    ("Pourquoi faut-il jouer dehors au soleil ?", "Le soleil aide le corps à fabriquer la vitamine D, bonne pour les os."),
],
"synthese": "En cas de fracture : immobiliser le membre et aller au centre de santé. Pour des os solides : manger du lait et du fromage (calcium), jouer au soleil et faire de l'exercice.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. En cas de fracture, il faut courir très vite.", "2. Le plâtre immobilise l'os cassé.", "3. Le lait est bon pour les os.", "4. Le soleil aide à avoir des os solides."],
     "cor": ["1. **Faux** : il faut immobiliser le membre blessé.", "2. **Vrai** : le plâtre tient l'os immobile.", "3. **Vrai** : le lait apporte du calcium.", "4. **Vrai** : le soleil aide le corps à fabriquer la vitamine D."]},
    {"c": "Complète avec les mots suivants : plâtre, lait, calcium, soleil.",
     "items": ["1. Pour soigner une fracture, on met un ...", "2. Le ... est un aliment riche en calcium.", "3. Le ... rend les os solides.", "4. Jouer au ... est bon pour les os."],
     "cor": ["1. Pour soigner une fracture, on met un **plâtre**.", "2. Le **lait** est un aliment riche en calcium.", "3. Le **calcium** rend les os solides.", "4. Jouer au **soleil** est bon pour les os."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que fait le docteur pour une fracture ? A. Il met un plâtre B. Il coupe l'os C. Il donne des bonbons", "2. Quel aliment est riche en calcium ? A. Le lait B. Le riz C. Le sucre", "3. Qu'est-ce qui aide le corps à fabriquer la vitamine D ? A. La pluie B. Le soleil C. La nuit", "4. Que faut-il faire chaque jour pour des os solides ? A. Rester couché B. Faire de l'exercice C. Manger des sucreries"],
     "cor": ["1. **A. Il met un plâtre**.", "2. **A. Le lait**.", "3. **B. Le soleil**.", "4. **B. Faire de l'exercice**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faut-il faire quand un os est cassé ?", "2. Que met le docteur pour immobiliser l'os ?", "3. Cite deux aliments bons pour les os.", "4. Pourquoi faut-il jouer au soleil ?"],
     "cor": ["1. Il faut **immobiliser** le membre et aller au **centre de santé**.", "2. Le docteur met un **plâtre**.", "3. Le **lait** et le **fromage** (riches en calcium).", "4. Le **soleil** aide le corps à fabriquer la **vitamine D**, bonne pour les os."]},
],
"lecon": [
    (None, ["Pour soigner une **fracture**, on immobilise l'os avec un **plâtre**. Pour des os solides, il faut du **calcium** et du **soleil**."]),
    ("1. Les soins de la fracture", ["Quand un os est cassé, il ne faut pas bouger le membre blessé. On va au **centre de santé** et le docteur met un **plâtre** qui tient l'os immobile pendant qu'il se répare."]),
    ("2. Les soins de l'entorse et de la luxation", ["Pour une **entorse**, on met du repos et une bande. Pour une **luxation**, le docteur remet l'os dans son articulation."]),
    ("3. L'hygiène de l'os", ["Pour avoir des os solides : manger du **lait** et du **fromage** (riches en **calcium**), jouer au **soleil** et faire de l'**exercice** chaque jour."]),
],
"mots_cles": ["plâtre", "calcium", "lait", "soleil", "repos"],
},
{
"n": 9, "titre": "L'œil et la vue", "theme": "Les organes des sens",
"objectif": "décrire l'œil et expliquer comment il nous fait voir",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": ("svt8e_oeil.png", "Schéma : l'œil, l'organe de la vue, avec sa pupille et son iris."),
"revision": [
    ("Qu'est-ce qu'une fracture ?", "Une fracture est un os cassé."),
    ("Que faut-il manger pour avoir des os solides ?", "Il faut manger du lait et du fromage, riches en calcium."),
],
"situation": "Voara regarde le tableau noir de loin, puis il regarde son cahier de près. Avec quel organe voit-il ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'œil et la vue.",
    "Je lis le titre au tableau : L'œil et la vue.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Regardez l'œil de votre voisin : voyez-vous la partie colorée ?",
],
"analyse": [
    ("Quel organe sert à voir ?", "L'œil est l'organe de la vue."),
    ("Comment s'appelle la partie colorée de l'œil ?", "La partie colorée de l'œil s'appelle l'iris."),
    ("Par quel petit trou la lumière entre-t-elle dans l'œil ?", "La lumière entre dans l'œil par la pupille."),
],
"synthese": "L'œil est l'organe de la vue. La lumière entre par la pupille. L'iris est la partie colorée. Les paupières et les cils protègent l'œil.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'œil est l'organe de la vue.", "2. La lumière entre dans l'œil par la pupille.", "3. L'iris est la partie blanche de l'œil.", "4. Les paupières protègent l'œil."],
     "cor": ["1. **Vrai** : l'œil sert à voir.", "2. **Vrai** : la lumière passe par la pupille.", "3. **Faux** : l'iris est la partie colorée.", "4. **Vrai** : les paupières et les cils protègent l'œil."]},
    {"c": "Complète avec les mots suivants : œil, pupille, iris, paupières.",
     "items": ["1. L'organe de la vue est l'...", "2. La lumière entre par la ...", "3. La partie colorée de l'œil est l'...", "4. Les ... se ferment pour protéger l'œil."],
     "cor": ["1. L'organe de la vue est l'**œil**.", "2. La lumière entre par la **pupille**.", "3. La partie colorée de l'œil est l'**iris**.", "4. Les **paupières** se ferment pour protéger l'œil."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel organe sert à voir ? A. L'oreille B. L'œil C. Le nez", "2. Quelle partie de l'œil est colorée ? A. La pupille B. L'iris C. Le cil", "3. Par où entre la lumière ? A. Par la pupille B. Par le sourcil C. Par la paupière", "4. Que font les paupières ? A. Elles protègent l'œil B. Elles voient C. Elles écoutent"],
     "cor": ["1. **B. L'œil**.", "2. **B. L'iris**.", "3. **A. Par la pupille**.", "4. **A. Elles protègent l'œil**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quel est l'organe de la vue ?", "2. Comment s'appelle la partie colorée de l'œil ?", "3. Par où la lumière entre-t-elle dans l'œil ?", "4. Cite deux parties qui protègent l'œil."],
     "cor": ["1. L'organe de la vue est l'**œil**.", "2. La partie colorée s'appelle l'**iris**.", "3. La lumière entre par la **pupille**.", "4. Les **paupières** et les **cils** protègent l'œil."]},
],
"lecon": [
    (None, ["L'**œil** est l'organe de la **vue**. La lumière entre par la **pupille**."]),
    ("1. L'œil et ses parties", ["L'**œil** est l'organe de la **vue**. La partie colorée s'appelle l'**iris** et le petit trou noir au milieu s'appelle la **pupille**. Les **paupières** et les **cils** protègent l'œil."]),
    ("2. Comment l'œil nous fait voir", ["La **lumière** entre dans l'œil par la **pupille**. C'est grâce à la lumière que nous voyons les objets, les couleurs et les visages."]),
    ("3. L'hygiène de l'œil", ["Il ne faut pas se frotter les yeux avec des mains sales, ne pas regarder le **soleil** en face et lire avec une bonne lumière."]),
],
"mots_cles": ["œil", "vue", "pupille", "iris", "lumière"],
},
{
"n": 10, "titre": "L'oreille et l'ouïe", "theme": "Les organes des sens",
"objectif": "décrire l'oreille et expliquer comment elle nous fait entendre",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma de l'oreille affiché au tableau",
"image": ("svt8e_oreille.png", "Schéma : l'oreille, l'organe de l'ouïe, reçoit les sons."),
"revision": [
    ("Quel organe sert à voir ?", "L'œil est l'organe de la vue."),
    ("Par où la lumière entre-t-elle dans l'œil ?", "La lumière entre par la pupille."),
],
"situation": "Au marché, Naina entend le coq chanter et la cloche de l'école sonner. Avec quel organe entend-il tous ces sons ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'oreille et l'ouïe.",
    "Je lis le titre au tableau : L'oreille et l'ouïe.",
],
"observation": [
    "Regardez le schéma de l'oreille affiché au tableau.",
    "Touchez doucement votre oreille : la partie visible s'appelle le pavillon.",
],
"analyse": [
    ("Quel organe sert à entendre ?", "L'oreille est l'organe de l'ouïe."),
    ("Comment s'appelle la partie visible de l'oreille ?", "La partie visible de l'oreille s'appelle le pavillon."),
    ("Qu'est-ce qui entre dans l'oreille ?", "Les sons entrent dans l'oreille."),
],
"synthese": "L'oreille est l'organe de l'ouïe. Sa partie visible est le pavillon. Les sons entrent par le pavillon et nous entendons. Il faut protéger ses oreilles des bruits trop forts.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'oreille est l'organe de l'ouïe.", "2. Le pavillon est la partie visible de l'oreille.", "3. Il faut mettre des objets pointus dans l'oreille.", "4. Les bruits trop forts abîment les oreilles."],
     "cor": ["1. **Vrai** : l'oreille sert à entendre.", "2. **Vrai** : le pavillon est visible.", "3. **Faux** : c'est interdit et dangereux.", "4. **Vrai** : les bruits forts abîment l'oreille."]},
    {"c": "Complète avec les mots suivants : oreille, pavillon, sons, bruits.",
     "items": ["1. L'organe de l'ouïe est l'...", "2. La partie visible de l'oreille est le ...", "3. Les ... entrent dans l'oreille.", "4. Les ... trop forts abîment les oreilles."],
     "cor": ["1. L'organe de l'ouïe est l'**oreille**.", "2. La partie visible de l'oreille est le **pavillon**.", "3. Les **sons** entrent dans l'oreille.", "4. Les **bruits** trop forts abîment les oreilles."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel organe sert à entendre ? A. L'œil B. L'oreille C. La langue", "2. Comment s'appelle la partie visible de l'oreille ? A. Le pavillon B. L'iris C. La pupille", "3. Qu'est-ce qui entre dans l'oreille ? A. La lumière B. Les sons C. Les odeurs", "4. Que faut-il éviter pour protéger l'oreille ? A. Les bruits trop forts B. Le silence C. La musique douce"],
     "cor": ["1. **B. L'oreille**.", "2. **A. Le pavillon**.", "3. **B. Les sons**.", "4. **A. Les bruits trop forts**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quel est l'organe de l'ouïe ?", "2. Comment s'appelle la partie visible de l'oreille ?", "3. Qu'est-ce qui entre dans l'oreille ?", "4. Cite une règle d'hygiène de l'oreille."],
     "cor": ["1. L'organe de l'ouïe est l'**oreille**.", "2. La partie visible s'appelle le **pavillon**.", "3. Les **sons** entrent dans l'oreille.", "4. Ne pas mettre d'objets pointus dans l'oreille (ou éviter les bruits trop forts)."]},
],
"lecon": [
    (None, ["L'**oreille** est l'organe de l'**ouïe**. Les sons entrent par le **pavillon**."]),
    ("1. L'oreille et ses parties", ["L'**oreille** est l'organe de l'**ouïe**. La partie visible s'appelle le **pavillon**. L'oreille continue à l'intérieur de la tête."]),
    ("2. Comment l'oreille nous fait entendre", ["Les **sons** entrent dans l'oreille par le **pavillon**. C'est ainsi que nous entendons la voix, la cloche, le chant des oiseaux."]),
    ("3. L'hygiène de l'oreille", ["Il ne faut jamais mettre d'objets pointus dans l'**oreille**. Il faut aussi éviter les **bruits** trop forts qui abîment l'oreille."]),
],
"mots_cles": ["oreille", "ouïe", "pavillon", "sons", "bruits"],
},
{
"n": 11, "titre": "La langue et le goût", "theme": "Les organes des sens",
"objectif": "expliquer que la langue est l'organe du goût",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma de la langue affiché au tableau",
"image": ("svt8e_langue.png", "Schéma : la langue, l'organe du goût, porte les papilles."),
"revision": [
    ("Quel organe sert à entendre ?", "L'oreille est l'organe de l'ouïe."),
    ("Comment s'appelle la partie visible de l'oreille ?", "La partie visible de l'oreille s'appelle le pavillon."),
],
"situation": "Au goûter, Koto mange une mangue bien sucrée, puis il goûte un citron très acide. Avec quel organe reconnaît-il les saveurs ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre la langue et le goût.",
    "Je lis le titre au tableau : La langue et le goût.",
],
"observation": [
    "Regardez le schéma de la langue affiché au tableau.",
    "Tirez doucement la langue devant un miroir : voyez-vous les petites bosses ?",
],
"analyse": [
    ("Quel organe sert à goûter ?", "La langue est l'organe du goût."),
    ("Comment s'appellent les petites bosses sur la langue ?", "Les petites bosses sur la langue s'appellent les papilles."),
    ("Quelles saveurs la langue reconnaît-elle ?", "La langue reconnaît le sucré, le salé, l'acide et l'amer."),
],
"synthese": "La langue est l'organe du goût. Les papilles reconnaissent les saveurs : le sucré, le salé, l'acide et l'amer. La langue aide aussi à parler et à avaler.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La langue est l'organe du goût.", "2. Les papilles sont sur la langue.", "3. La langue reconnaît le sucré et le salé.", "4. La langue sert seulement à goûter."],
     "cor": ["1. **Vrai** : la langue sert à goûter.", "2. **Vrai** : les papilles sont sur la langue.", "3. **Vrai** : sucré, salé, acide et amer.", "4. **Faux** : la langue aide aussi à parler et à avaler."]},
    {"c": "Complète avec les mots suivants : langue, papilles, goût, saveurs.",
     "items": ["1. L'organe du goût est la ...", "2. Les ... sont les petites bosses de la langue.", "3. La langue sert à reconnaître les ...", "4. La langue est l'organe du ...."],
     "cor": ["1. L'organe du goût est la **langue**.", "2. Les **papilles** sont les petites bosses de la langue.", "3. La langue sert à reconnaître les **saveurs**.", "4. La langue est l'organe du **goût**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel organe sert à goûter ? A. Le nez B. La langue C. L'œil", "2. Que portent les papilles ? A. La langue B. L'oreille C. La peau", "3. Le sucre a un goût ... A. salé B. sucré C. amer", "4. Le citron a un goût ... A. acide B. sucré C. salé"],
     "cor": ["1. **B. La langue**.", "2. **A. La langue** : les papilles sont dessus.", "3. **B. Sucré**.", "4. **A. Acide**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quel est l'organe du goût ?", "2. Que sont les papilles ?", "3. Cite deux saveurs que la langue reconnaît.", "4. À quoi d'autre la langue sert-elle ?"],
     "cor": ["1. L'organe du goût est la **langue**.", "2. Les **papilles** sont les petites bosses de la langue.", "3. Le **sucré** et le **salé** (ou l'acide, l'amer).", "4. La **langue** aide aussi à **parler** et à **avaler**."]},
],
"lecon": [
    (None, ["La **langue** est l'organe du **goût**. Les **papilles** reconnaissent les saveurs."]),
    ("1. La langue, organe du goût", ["La **langue** est dans la **bouche**. C'est elle qui reconnaît le goût des aliments."]),
    ("2. Les papilles et les saveurs", ["La langue porte de petites bosses : les **papilles**. Elles reconnaissent quatre saveurs : le **sucré**, le **salé**, l'**acide** et l'**amer**."]),
    ("3. Les autres rôles de la langue", ["La **langue** aide aussi à **parler** et à **avaler** les aliments. Il faut bien la brosser en se lavant les dents."]),
],
"mots_cles": ["langue", "goût", "papilles", "sucré", "salé"],
},
{
"n": 12, "titre": "Le nez et l'odorat", "theme": "Les organes des sens",
"objectif": "expliquer que le nez est l'organe de l'odorat",
"doc": "Répartition annuelle 8e, Connaissances Usuelles (SVT), Bimestre 1",
"support_obs": "le schéma du nez affiché au tableau",
"image": ("svt8e_nez.png", "Schéma : le nez, l'organe de l'odorat, sent les odeurs."),
"revision": [
    ("Quel organe sert à goûter ?", "La langue est l'organe du goût."),
    ("Que reconnaissent les papilles ?", "Les papilles reconnaissent le sucré, le salé, l'acide et l'amer."),
],
"situation": "Devant la maison, Nivo sent l'odeur du jasmin, puis l'odeur du pain qui sort du four. Avec quel organe sent-elle toutes ces odeurs ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre le nez et l'odorat.",
    "Je lis le titre au tableau : Le nez et l'odorat.",
],
"observation": [
    "Regardez le schéma du nez affiché au tableau.",
    "Montrez les deux narines : c'est par elles que l'air entre dans le nez.",
],
"analyse": [
    ("Quel organe sert à sentir ?", "Le nez est l'organe de l'odorat."),
    ("Par quels trous l'air entre-t-il dans le nez ?", "L'air entre dans le nez par les narines."),
    ("Le nez sert-il seulement à sentir ?", "Non, le nez sert aussi à respirer."),
],
"synthese": "Le nez est l'organe de l'odorat. L'air entre par les narines et le nez reconnaît les odeurs, bonnes ou mauvaises. Le nez sert aussi à respirer.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le nez est l'organe de l'odorat.", "2. L'air entre dans le nez par les narines.", "3. Le nez reconnaît les odeurs.", "4. Le nez ne sert pas à respirer."],
     "cor": ["1. **Vrai** : le nez sert à sentir.", "2. **Vrai** : l'air passe par les narines.", "3. **Vrai** : bonnes ou mauvaises odeurs.", "4. **Faux** : le nez sert aussi à respirer."]},
    {"c": "Complète avec les mots suivants : nez, narines, odeurs, respirer.",
     "items": ["1. L'organe de l'odorat est le ...", "2. L'air entre par les ...", "3. Le nez reconnaît les ...", "4. Le nez sert aussi à ...."],
     "cor": ["1. L'organe de l'odorat est le **nez**.", "2. L'air entre par les **narines**.", "3. Le nez reconnaît les **odeurs**.", "4. Le nez sert aussi à **respirer**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel organe sert à sentir ? A. L'œil B. Le nez C. L'oreille", "2. Par où l'air entre-t-il dans le nez ? A. Par les narines B. Par les papilles C. Par la pupille", "3. Que reconnaît le nez ? A. Les saveurs B. Les odeurs C. Les sons", "4. À quoi d'autre le nez sert-il ? A. À respirer B. À goûter C. À entendre"],
     "cor": ["1. **B. Le nez**.", "2. **A. Par les narines**.", "3. **B. Les odeurs**.", "4. **A. À respirer**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quel est l'organe de l'odorat ?", "2. Par où l'air entre-t-il dans le nez ?", "3. Que reconnaît le nez ?", "4. Cite une règle d'hygiène du nez."],
     "cor": ["1. L'organe de l'odorat est le **nez**.", "2. L'air entre dans le nez par les **narines**.", "3. Le **nez** reconnaît les **odeurs**, bonnes ou mauvaises.", "4. Se **moucher** régulièrement (et ne pas mettre les doigts dans le nez)."]},
],
"lecon": [
    (None, ["Le **nez** est l'organe de l'**odorat**. L'air entre par les **narines**."]),
    ("1. Le nez, organe de l'odorat", ["Le **nez** est l'organe de l'**odorat**. L'air entre par les deux **narines** et le nez reconnaît les odeurs."]),
    ("2. Les odeurs", ["Le nez reconnaît les bonnes odeurs : la **fleur**, le **pain** chaud. Il reconnaît aussi les mauvaises odeurs : la **fumée**, les **ordures**."]),
    ("3. Le nez sert aussi à respirer", ["Le **nez** sert à **respirer** : l'air entre et sort par les narines. Il faut se **moucher** régulièrement pour garder le nez propre."]),
],
"mots_cles": ["nez", "odorat", "narines", "odeurs", "respirer"],
},
]

REVISION_B1 = {
"titre": "Révision — Bimestre 1",
"tableau": [
    ("Le corps humain", "Trois grandes parties : la tête, le tronc et les membres."),
    ("Les membres", "Les deux bras et les deux jambes."),
    ("L'articulation", "L'endroit où deux os se rencontrent et où le corps plie."),
    ("Les articulations", "L'épaule, le coude, le poignet, la hanche, le genou et la cheville."),
    ("Les muscles", "Des parties molles sous la peau qui tirent sur les os et font bouger le corps."),
    ("Le cœur", "Un muscle qui bat sans s'arrêter."),
    ("L'hygiène des muscles", "S'échauffer avant l'effort, se reposer, bien dormir, se tenir droit."),
    ("Les os", "Des parties dures qui forment le squelette."),
    ("Le squelette", "Il soutient le corps ; le crâne protège le cerveau, les côtes protègent le cœur et les poumons."),
    ("L'intérieur de l'os", "L'os compact dehors, la moelle dedans ; le calcium rend l'os dur."),
    ("La fracture", "Un os cassé, après une chute ou un coup."),
    ("L'entorse et la luxation", "L'entorse : articulation tordue ; la luxation : os sorti de son articulation."),
    ("Les soins", "Le plâtre immobilise l'os cassé ; repos et centre de santé."),
    ("L'hygiène de l'os", "Manger du lait et du fromage (calcium), jouer au soleil, faire de l'exercice."),
    ("L'œil", "L'organe de la vue ; la lumière entre par la pupille, l'iris est coloré."),
    ("L'oreille", "L'organe de l'ouïe ; les sons entrent par le pavillon."),
    ("La langue", "L'organe du goût ; les papilles reconnaissent le sucré, le salé, l'acide et l'amer."),
    ("Le nez", "L'organe de l'odorat ; l'air entre par les narines ; il sert aussi à respirer."),
],
"questions": [
    ("Quelles sont les trois grandes parties du corps ?", "La tête, le tronc et les membres."),
    ("Qu'est-ce qu'une articulation ?", "C'est l'endroit où deux os se rencontrent et où le corps plie."),
    ("Comment les muscles font-ils bouger le corps ?", "Ils se raccourcissent et tirent sur les os."),
    ("Que faut-il faire avant le sport ?", "Il faut s'échauffer doucement."),
    ("Qu'est-ce que le squelette ?", "C'est l'ensemble de tous les os du corps."),
    ("Que protège le crâne ?", "Le crâne protège le cerveau."),
    ("Qu'est-ce qu'une fracture ?", "Une fracture est un os cassé."),
    ("Que met le docteur pour immobiliser un os cassé ?", "Le docteur met un plâtre."),
    ("Quel est l'organe de la vue ?", "L'œil est l'organe de la vue."),
    ("Quel est l'organe du goût ?", "La langue est l'organe du goût."),
    ("Quel est l'organe de l'odorat ?", "Le nez est l'organe de l'odorat."),
    ("Cite une règle d'hygiène de l'oreille.", "Ne pas mettre d'objets pointus dans l'oreille."),
],
}

EXAMEN_B1 = {
"titre": "Sujet d'examen 8e — Bimestre 1",
"duree": "30 min",
"total": 20,
"parties": [
    {"c": "Réponds par Vrai (V) ou Faux (F). (4 points)",
     "items": ["1. Le corps a trois grandes parties.", "2. Les muscles sont durs comme les os.", "3. Le genou est une articulation.", "4. Le nez est l'organe du goût."],
     "cor": ["1. **Vrai** (1 pt) : la tête, le tronc et les membres.", "2. **Faux** (1 pt) : les muscles sont des parties molles.", "3. **Vrai** (1 pt) : le genou plie la jambe.", "4. **Faux** (1 pt) : le nez est l'organe de l'odorat."]},
    {"c": "Complète avec les mots suivants : squelette, plâtre, pupille, pavillon. (4 points)",
     "items": ["1. Tous les os forment le ...", "2. Pour soigner une fracture, on met un ...", "3. La lumière entre dans l'œil par la ...", "4. La partie visible de l'oreille est le ...."],
     "cor": ["1. Le **squelette** (1 pt).", "2. Un **plâtre** (1 pt).", "3. Par la **pupille** (1 pt).", "4. Le **pavillon** (1 pt)."]},
    {"c": "Entoure la bonne réponse. (4 points)",
     "items": ["1. Quel organe protège le crâne ? A. Le cerveau B. Le cœur C. L'estomac", "2. Que faut-il manger pour avoir des os solides ? A. Du lait B. Des bonbons C. Des boissons sucrées", "3. Quel organe reconnaît les odeurs ? A. La langue B. Le nez C. L'oreille", "4. Que font les muscles pour bouger le corps ? A. Ils tirent sur les os B. Ils poussent les cheveux C. Ils dorment"],
     "cor": ["1. **A. Le cerveau** (1 pt) : le crâne le protège.", "2. **A. Du lait** (1 pt) : riche en calcium.", "3. **B. Le nez** (1 pt) : organe de l'odorat.", "4. **A. Ils tirent sur les os** (1 pt)."]},
    {"c": "Réponds par une phrase complète. (8 points)",
     "items": ["1. Cite les trois grandes parties du corps.", "2. À quoi sert une articulation ?", "3. Que faut-il faire quand un os est cassé ?", "4. Cite deux règles d'hygiène de l'œil."],
     "cor": ["1. La **tête**, le **tronc** et les **membres** (2 pts).", "2. L'**articulation** permet de **plier** et de **bouger** (2 pts).", "3. Il faut **immobiliser** le membre et aller au **centre de santé** (2 pts).", "4. Ne pas se frotter les yeux avec des mains sales ; ne pas regarder le **soleil** en face (2 pts)."]},
],
}
