// Sary faha-2 isaky ny seho (apetraka ao amin'ny LESONA, aorian'ny votoaty) — Tantara T5
module.exports = {
  1:  { image: "images/img2_s01.png", legende: "Ireo karazana zava-mitranga : eo an-toerana sy eo amin'ny firenena" },
  2:  { image: "images/img2_s02.png", legende: "Inona no manavaka ny zava-mitranga sy ny tranga ara-tantara ?" },
  4:  { image: "images/img2_s04.png", legende: "Ny an-tanan-tohatra teo amin'ny fiarahamonina sy ny fivoaran'ny foko ho fanjakana" },
  5:  { image: "images/img2_s05.png", legende: "Sari-tany : ireo fanjakana efatra vaventy sy ny taonjato nijoroany" },
  7:  { image: "images/img2_s07.png", legende: "Ireo antony telo nivarotan'ny mpanjaka andevo" },
  8:  { image: "images/img2_s08.png", legende: "Sari-tany : ny lalan'ny varotra andevo" },
  9:  { image: "images/img2_s09.png", legende: "Ny fiantraikan'ny varotra andevo : mizana roa" },
  11: { image: "images/img2_s11.png", legende: "Frizy : ireo mpanjaka enina nifandimby (1810-1897)" },
  13: { image: "images/img2_s13.png", legende: "Ny vokatry ny orinasan'i Mantasoa" },
  15: { image: "images/img2_s15.png", legende: "Frizy : ireo mpanjakavavy telo farany (1863-1897)" },
  16: { image: "images/img2_s16.png", legende: "Ireo soatoavina malagasy tokony hotandrovana" },
  18: { image: "images/img2_s18.png", legende: "Frizy : ireo satan'i Madagasikara (1895-1960)" },
  19: { image: "images/img2_s19.png", legende: "Ny rafi-pitantanan'ny mpanjanaka : avy amin'ny governora jeneraly ka hatramin'ny fokontany" },
  20: { image: "images/img2_s20.png", legende: "Ny « économie de traite » : toekarena natao ho an'ny mpanjanaka" },
  22: { image: "images/img2_s22.png", legende: "Ny SMOTIG amin'ny isa" },
  23: { image: "images/img2_s23.png", legende: "Frizy : ireo hetsika fanoherana ny fanjanahantany" },
  24: { image: "images/img2_s24.png", legende: "Ny lanjan'ny fanjanahantany : zava-bita sy fiantraikany ratsy" },
  26: { image: "images/img2_s26.png", legende: "Ireo karazana vakoka : hita maso sy tsy hita maso" },
  27: { image: "images/img2_s27.png", legende: "Ireo tombontsoa azo amin'ny fikolokoloana ny harem-pirenena" },
  28: { image: "images/img2_s28.png", legende: "Ny fiarovana ny vakoka : lalàna sy fepetra" },
  29: { image: "images/img2_s29.png", legende: "Ny anjara asan'ny tsirairay amin'ny fiarovana ny vakoka" },
};
