// ============================================================
// Unité II — Organisation des êtres vivants (RAS : différencier les
// modes de reproduction des animaux et des végétaux) — 15 h
// ============================================================

const U = {
  num: "II",
  titre: "Organisation des êtres vivants",
  ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
  valeurs: "Responsabilité, respect de la vie",
  themes: ["La viviparité chez les animaux", "L'oviparité chez les animaux", "L'ovoviviparité chez les animaux",
    "Comparer les trois modes de reproduction", "La fleur et la pollinisation", "De la graine à la plante",
    "Importance et inconvénients de la reproduction sexuée", "Le bouturage", "Le greffage",
    "Le marcottage et le choix d'une technique"],
  topics: [
    {
      type: "cours",
      titre: "La viviparité chez les animaux",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer la viviparité et citer des animaux vivipares",
      supportMeta: "Images ou photos d'une femelle et de son petit (zébu, chien, humain)",
      revision: [
        ["Comment un être vivant donne-t-il naissance à de nouveaux êtres ?", "Par la reproduction : les parents donnent naissance à des petits."],
        ["Cite un animal qui donne naissance à des petits.", "La vache (zébu), la chienne, la chatte…"],
      ],
      mise: ["Observe la photo d'une vache et de son veau : où le veau s'est-il développé avant sa naissance ?", "Dans le ventre de sa mère."],
      observation: "les images ou photos présentant une femelle et son petit",
      observationSupport: "Photos : vache et veau, chienne et chiots, femme et bébé",
      qa: [
        ["Que montrent ces photos ?", "Une mère et son petit, juste après ou peu après la naissance."],
        ["Où le petit s'est-il développé ?", "Dans le corps de sa mère, avant de naître."],
        ["Comment appelle-t-on ce mode de reproduction ?", "La viviparité : le petit se développe dans le corps de la mère."],
        ["Le petit doit-il se nourrir seul dès la naissance ?", "Non : après la naissance, la mère le nourrit souvent (lait, soins) jusqu'à ce qu'il soit autonome."],
      ],
      synthese: "Donc, chez les animaux vivipares, l'embryon se développe dans le corps de la mère jusqu'à la naissance. Le petit naît déjà formé et la mère le nourrit et le protège. La vache, la chienne, la chatte et l'être humain sont des animaux vivipares.",
      motsCles: ["reproduction", "viviparité", "embryon", "naissance"],
      contenu: [
        { sousTitre: "1. Qu'est-ce que la reproduction ?", texte: "La reproduction est le phénomène par lequel les êtres vivants donnent naissance à de nouveaux êtres de la même espèce. Elle assure la survie de l'espèce. Chez les animaux, il existe plusieurs modes de reproduction." },
        { sousTitre: "2. La viviparité", texte: "La viviparité est un mode de reproduction dans lequel l'embryon se développe à l'intérieur du corps de la mère, jusqu'à la naissance. Le petit naît vivant, déjà formé, et se développe grâce aux soins de sa mère.", liste: ["L'embryon se développe dans l'utérus (ou le ventre) de la mère.","Le petit naît vivant.","La mère nourrit et protège son petit après la naissance."] },
        { sousTitre: "3. Exemples d'animaux vivipares", texte: "Beaucoup de mammifères sont vivipares.", liste: ["Le zébu (la vache) et son veau.","Le chien et ses chiots.","Le chat et ses chatons.","L'être humain.","Le mouton, le porc, le cheval…"] },
        { sousTitre: "4. Avantages de la viviparité", texte: "Le petit est protégé et nourri par la mère, ce qui augmente ses chances de survie. Il quitte le corps de la mère déjà capable de vivre.", liste: ["Protection du petit avant la naissance.","Soins et nourriture après la naissance.","Meilleure survie des jeunes."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "La viviparité est un mode de reproduction où…", opts: ["le petit se développe dans un œuf déposé dehors", "l'embryon se développe dans le corps de la mère", "le petit naît de la bouche de la mère"], ok: 1, expl: "Chez les vivipares, le petit grandit dans le corps de la mère." },
          { q: "Lequel de ces animaux est vivipare ?", opts: ["La poule", "Le zébu", "Le poisson pondeur"], ok: 1, expl: "Le zébu est un mammifère vivipare." },
          { q: "Un animal vivipare donne naissance à un petit…", opts: ["déjà formé", "dans un œuf", "qui ne peut pas vivre"], ok: 0, expl: "Le petit naît vivant et déjà formé." },
          { q: "L'embryon d'un mammifère vivipare se développe…", opts: ["dans le nid", "dans le ventre de la mère", "dans un œuf de la coquille"], ok: 1, expl: "Il se développe dans l'utérus de la mère." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "La reproduction permet aux espèces de continuer à exister.", rep: true, expl: "Elle assure la naissance de nouveaux individus de la même espèce." },
          { txt: "Le veau se développe dans un œuf déposé au sol.", rep: false, expl: "Le veau se développe dans le corps de la vache (viviparité)." },
          { txt: "La vache est un animal vivipare.", rep: true, expl: "La vache met bas un veau vivant et le nourrit." },
          { txt: "Chez les vivipares, la mère ne s'occupe jamais de son petit.", rep: false, expl: "La mère nourrit et protège son petit après la naissance." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce que la viviparité ?", r: "La viviparité est un mode de reproduction où l'embryon se développe dans le corps de la mère jusqu'à la naissance." },
          { q: "Cite deux animaux vivipares.", r: "Le zébu et le chien sont deux animaux vivipares (ou le chat, la chèvre, l'être humain…)." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "L'embryon vivipare se développe dans le corps de", suite: "la mère" },
          { debut: "Le petit vivipare naît", suite: "vivant" },
          { debut: "Après la naissance, la mère nourrit et", suite: "protège son petit" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "L'oviparité chez les animaux",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer l'oviparité et citer des animaux ovipares",
      supportMeta: "Œufs (de poule) et images d'animaux pondeurs (poule, poisson, papillon)",
      revision: [
        ["Qu'est-ce que la viviparité ?", "Un mode de reproduction où l'embryon se développe dans le corps de la mère."],
        ["Cite un animal vivipare.", "Le zébu (ou le chien, la chatte…)."],
      ],
      mise: ["D'où vient le poussin que tu as vu chez toi ?", "Il sort d'un œuf pondu par la poule."],
      observation: "l'œuf de poule et les images de la poule, du poisson et du papillon",
      observationSupport: "Œuf de poule, images d'une poule et de ses poussins, de poissons, de papillons",
      qa: [
        ["Que possède la poule pour se reproduire ?", "Elle pond des œufs ; le poussin sort de l'œuf après un certain temps."],
        ["Où l'embryon se développe-t-il chez la poule ?", "Dans l'œuf, en dehors du corps de la mère."],
        ["Comment appelle-t-on ce mode de reproduction ?", "L'oviparité."],
        ["Le poisson et le papillon pondent-ils aussi ?", "Oui, la femelle pond des œufs et les petits en sortent : ils sont ovipares."],
      ],
      synthese: "Donc, chez les animaux ovipares, la femelle pond des œufs et l'embryon se développe dans l'œuf, en dehors du corps de la mère. La poule, le poisson, le papillon, le canard, la tortue et le crocodile sont des animaux ovipares.",
      motsCles: ["oviparité", "œuf", "ponte", "éclosion", "embryon"],
      contenu: [
        { sousTitre: "1. Qu'est-ce que l'oviparité ?", texte: "L'oviparité est un mode de reproduction dans lequel la femelle pond des œufs et où l'embryon se développe à l'intérieur de l'œuf, en dehors du corps de la mère. Quand le moment arrive, l'œuf éclôt et le petit sort : c'est l'éclosion." },
        { sousTitre: "2. Le développement dans l'œuf", liste: ["La femelle pond des œufs.","L'embryon se développe dans l'œuf, à l'abri de la coquille ou de l'enveloppe.","L'œuf est souvent couvé ou surveillé (poule, canard, tortue).","À l'éclosion, le petit sort de l'œuf."] },
        { sousTitre: "3. Exemples d'animaux ovipares", liste: ["La poule et le canard (oiseaux).","Le poisson, qui pond des œufs dans l'eau.","Le papillon, qui pond des œufs sur les feuilles.","La tortue, qui pond ses œufs dans le sable.","Le crocodile, la grenouille, le lézard…"] },
        { sousTitre: "4. Le rôle de l'œuf", texte: "L'œuf contient tout ce dont l'embryon a besoin pour se développer : les réserves (le jaune, le blanc) et une protection (la coquille ou le frai). Certains œufs sont protégés par une coquille dure (poule), d'autres sont mous (poisson) et pondus dans l'eau." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "L'oviparité est un mode de reproduction où…", opts: ["le petit naît vivant", "la femelle pond des œufs", "le petit se développe dans la bouche"], ok: 1, expl: "La femelle pond des œufs et le petit sort par éclosion." },
          { q: "La poule est un animal…", opts: ["vivipare", "ovipare", "ovovivipare"], ok: 1, expl: "La poule pond des œufs." },
          { q: "Le poussin sort de l'œuf grâce…", opts: ["à l'éclosion", "à la mue", "à la nage"], ok: 0, expl: "L'éclosion est le moment où le petit sort de l'œuf." },
          { q: "Lequel de ces animaux est ovipare ?", opts: ["Le chien", "Le zébu", "Le poisson"], ok: 2, expl: "Le poisson pond des œufs dans l'eau." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Chez les ovipares, l'embryon se développe dans l'œuf.", rep: true, expl: "Le développement a lieu dans l'œuf, hors du corps de la mère." },
          { txt: "Le papillon est un animal vivipare.", rep: false, expl: "Le papillon pond des œufs : il est ovipare." },
          { txt: "L'éclosion est le moment où le petit sort de l'œuf.", rep: true, expl: "À l'éclosion, le petit quitte l'œuf." },
          { txt: "La coquille de l'œuf sert à protéger l'embryon.", rep: true, expl: "La coquille protège l'embryon et laisse passer l'air." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce que l'oviparité ?", r: "L'oviparité est un mode de reproduction où la femelle pond des œufs dans lesquels l'embryon se développe." },
          { q: "Cite deux animaux ovipares.", r: "La poule et le poisson sont deux animaux ovipares (ou le papillon, la tortue…)." },
          { q: "Que se passe-t-il à l'éclosion ?", r: "À l'éclosion, le petit sort de l'œuf et commence sa vie en dehors." },
        ]},
        { type: "appariement", consigne: "Relie chaque animal à son mode de reproduction.", pointsPar: 1, items: [{ g: ["La poule", "Le zébu", "Le poisson", "Le papillon"], d: ["Ovipare (œufs dans l'eau)", "Vivipare", "Ovipare (ponte sur les feuilles)", "Ovipare (œuf avec coquille)"], pairs: [[0, 3], [1, 1], [2, 0], [3, 2]] }] },
      ],
    },
    {
      type: "cours",
      titre: "L'ovoviviparité chez les animaux",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer l'ovoviviparité et la distinguer de l'oviparité et de la viviparité",
      supportMeta: "Images de poissons vivants, d'un serpent, d'un requin",
      revision: [
        ["Qu'est-ce que l'oviparité ?", "Un mode de reproduction où la femelle pond des œufs et où le petit se développe dans l'œuf."],
        ["Cite un animal ovipare.", "La poule (ou le poisson, le papillon…)."],
      ],
      mise: ["Certains poissons donnent naissance à des petits déjà vivants, sans pondre d'œufs dehors. Comment est-ce possible ?", "Les œufs se développent dans le corps de la femelle ; les petits naissent vivants."],
      observation: "les images de poissons et de serpents donnant naissance à des petits vivants",
      observationSupport: "Images de guppys, d'un serpent, d'un requin avec ses petits",
      qa: [
        ["Où se développent les œufs chez ces animaux ?", "Dans le corps de la femelle."],
        ["Les petits naissent-ils dans un œuf posé dehors ?", "Non : ils naissent vivants, après avoir grandi dans les œufs gardés dans le corps de la mère."],
        ["Comment appelle-t-on ce mode de reproduction ?", "L'ovoviviparité."],
        ["En quoi est-ce différent de la viviparité ?", "En ovoviviparité, le petit se développe dans un œuf (qui reste dans le corps) ; en viviparité, il se développe directement dans le corps de la mère, sans œuf."],
      ],
      synthese: "Donc, l'ovoviviparité est un mode de reproduction où les œufs se développent dans le corps de la femelle, puis les petits naissent vivants. On la rencontre chez certains poissons, certains requins et certains serpents.",
      motsCles: ["ovoviviparité", "œufs internes", "naissance vivante"],
      contenu: [
        { sousTitre: "1. Qu'est-ce que l'ovoviviparité ?", texte: "L'ovoviviparité est un mode de reproduction intermédiaire : la femelle forme des œufs, mais elle les garde dans son corps jusqu'à l'éclosion. Les petits naissent alors vivants, sans avoir été pondus dehors." },
        { sousTitre: "2. Comment cela se passe-t-il ?", texte: "Les œufs restent à l'intérieur du corps de la femelle. L'embryon se nourrit grâce aux réserves de l'œuf, puis éclôt. La femelle met alors au monde des petits vivants." },
        { sousTitre: "3. Exemples d'animaux ovovivipares", texte: "On rencontre l'ovoviviparité chez certains animaux aquatiques et certains reptiles.", liste: ["certains poissons d'aquarium, comme le guppy ;","certains requins ;","certains serpents."] },
        { sousTitre: "4. Comparaison simple", liste: ["Ovipare : œufs pondus dehors, éclosion dehors.","Vivipare : embryon dans le corps, naissance vivante, sans œuf.","Ovovivipare : œufs gardés dans le corps, éclosion dans le corps, naissance vivante."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "En ovoviviparité, les œufs se développent…", opts: ["dans un nid", "dans le corps de la femelle", "dans l'eau uniquement"], ok: 1, expl: "Les œufs sont gardés dans le corps de la femelle jusqu'à l'éclosion." },
          { q: "Un animal ovovivipare donne naissance à des petits…", opts: ["dans des œufs pondus dehors", "vivants", "sans vie"], ok: 1, expl: "Les petits naissent vivants." },
          { q: "Lequel de ces animaux peut être ovovivipare ?", opts: ["Le guppy", "La poule", "Le papillon"], ok: 0, expl: "Le guppy est un poisson souvent ovovivipare." },
          { q: "L'ovoviviparité est un mode…", opts: ["identique à la viviparité", "intermédiaire entre l'oviparité et la viviparité", "réservé aux oiseaux"], ok: 1, expl: "Les œufs se développent dans le corps, mais sans pondre dehors." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "En ovoviviparité, la femelle pond ses œufs à l'extérieur.", rep: false, expl: "Les œufs restent dans le corps de la femelle." },
          { txt: "Les petits ovovivipares naissent vivants.", rep: true, expl: "Ils naissent vivants après éclosion interne." },
          { txt: "Certains serpents sont ovovivipares.", rep: true, expl: "Certains serpents gardent leurs œufs dans leur corps." },
          { txt: "La poule est un animal ovovivipare.", rep: false, expl: "La poule pond ses œufs dehors : elle est ovipare." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce que l'ovoviviparité ?", r: "L'ovoviviparité est un mode de reproduction où les œufs se développent dans le corps de la femelle, puis les petits naissent vivants." },
          { q: "Quelle est la différence entre oviparité et ovoviviparité ?", r: "En oviparité, les œufs sont pondus à l'extérieur ; en ovoviviparité, les œufs restent dans le corps de la femelle jusqu'à l'éclosion." },
          { q: "Cite un animal ovovivipare.", r: "Le guppy (ou certains requins, certains serpents) est un animal ovovivipare." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "Les œufs ovovivipares se développent dans le corps de", suite: "la femelle" },
          { debut: "Les petits ovovivipares naissent", suite: "vivants" },
          { debut: "L'ovoviviparité est un mode de reproduction", suite: "intermédiaire" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Comparer les trois modes de reproduction",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "comparer la viviparité, l'oviparité et l'ovoviviparité",
      supportMeta: "Tableau comparatif au tableau, images",
      revision: [
        ["Cite les trois modes de reproduction des animaux.", "La viviparité, l'oviparité et l'ovoviviparité."],
        ["Que signifie « naître vivant » ?", "Le petit sort déjà formé du corps de la mère, sans œuf pondu dehors."],
      ],
      mise: ["Une poule, une chienne et un guppy : leurs petits naissent-ils tous de la même façon ?", "Non : la poule pond des œufs, la chienne met bas des petits vivants, le guppy garde ses œufs dans son corps."],
      observation: "le tableau comparatif des trois modes de reproduction affiché au tableau",
      observationSupport: "Tableau comparatif (oviparité / viviparité / ovoviviparité) + images",
      qa: [
        ["Que montre la première colonne du tableau ?", "Le mode de reproduction : oviparité, viviparité, ovoviviparité."],
        ["Où se développe l'embryon dans chaque cas ?", "Dans l'œuf dehors (oviparité), dans le corps de la mère (viviparité), dans l'œuf gardé dans le corps (ovoviviparité)."],
        ["Comment les petits naissent-ils ?", "Par éclosion (oviparité), vivants (viviparité et ovoviviparité)."],
        ["Peut-on classer tous les animaux dans un de ces trois groupes ?", "Oui, chaque animal a un mode de reproduction qui lui est propre."],
      ],
      synthese: "Donc, les trois modes de reproduction des animaux se distinguent par l'endroit où l'embryon se développe : dans un œuf pondu (oviparité), dans le corps de la mère (viviparité) ou dans un œuf gardé dans le corps (ovoviviparité).",
      motsCles: ["oviparité", "viviparité", "ovoviviparité", "embryon", "éclosion"],
      contenu: [
        { sousTitre: "1. Le tableau comparatif", texte: "Voici les trois modes de reproduction des animaux et leurs caractéristiques principales.", liste: ["Oviparité : la femelle pond des œufs ; l'embryon se développe dans l'œuf, dehors ; le petit sort par éclosion.","Viviparité : l'embryon se développe directement dans le corps de la mère ; le petit naît vivant.","Ovoviviparité : les œufs restent dans le corps de la femelle ; le petit naît vivant après éclosion interne."] },
        { sousTitre: "2. Des exemples pour chaque mode", liste: ["Ovipares : poule, canard, poisson, papillon, tortue, grenouille.","Vivipares : zébu, chien, chat, cheval, être humain.","Ovovivipares : guppy, certains requins, certains serpents."] },
        { sousTitre: "3. Pourquoi ces différences ?", texte: "Chaque mode de reproduction est adapté au milieu de vie de l'animal. Un poisson pond beaucoup d'œufs dans l'eau car peu survivent ; une vache porte un seul veau à la fois mais le protège bien. La nature a ainsi plusieurs solutions pour assurer la survie des espèces." },
        { sousTitre: "4. Comment retenir ?", texte: "Pense à trois mots : ponte (œufs dehors), ventre (embryon chez la mère), œufs au ventre (œufs gardés dans le corps)." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "La poule est un animal…", opts: ["ovipare", "vivipare", "ovovivipare"], ok: 0, expl: "La poule pond des œufs." },
          { q: "Le zébu est un animal…", opts: ["ovipare", "vivipare", "ovovivipare"], ok: 1, expl: "La vache met bas un veau vivant." },
          { q: "Le guppy peut être…", opts: ["ovipare", "vivipare", "ovovivipare"], ok: 2, expl: "Le guppy garde ses œufs dans son corps." },
          { q: "En oviparité, le petit sort de l'œuf par…", opts: ["l'éclosion", "la nage", "l'envol"], ok: 0, expl: "L'éclosion est la sortie du petit de l'œuf." },
        ]},
        { type: "appariement", consigne: "Relie chaque animal à son mode de reproduction.", pointsPar: 1, items: [{ g: ["Poule", "Vache", "Guppy", "Papillon"], d: ["Ovipare", "Ovovivipare", "Vivipare", "Ovipare"], pairs: [[0, 0], [1, 2], [2, 1], [3, 0]] }] },
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Où se développe l'embryon chez un animal ovipare ?", r: "Il se développe dans l'œuf pondu, en dehors du corps de la mère." },
          { q: "Quelle est la différence entre viviparité et ovoviviparité ?", r: "En viviparité, l'embryon se développe directement dans le corps de la mère ; en ovoviviparité, il se développe dans un œuf gardé dans le corps de la femelle." },
          { q: "Cite un exemple pour chacun des trois modes.", r: "Ovipare : la poule ; vivipare : la vache ; ovovivipare : le guppy." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "La femelle ovipare pond des", suite: "œufs" },
          { debut: "Le petit vivipare naît", suite: "vivant" },
          { debut: "L'ovoviviparité combine des œufs et une naissance", suite: "vivante" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "La fleur et la pollinisation",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "identifier les organes de la fleur et expliquer la pollinisation",
      supportMeta: "Fleur réelle (ou schéma légendé de la fleur), images d'insectes",
      revision: [
        ["Cite les trois modes de reproduction des animaux.", "Oviparité, viviparité, ovoviviparité."],
        ["Donne un exemple d'animal ovipare.", "La poule (ou le poisson, le papillon…)."],
      ],
      mise: ["Comment une fleur devient-elle un fruit avec des graines ?", "Grâce à la pollinisation et à la fécondation : la fleur doit être visitée par le pollen."],
      observation: "la fleur réelle ou le schéma légendé de la fleur",
      observationSupport: "Fleur réelle (hibiscus, bougainvillier), schéma légendé de la fleur",
      qa: [
        ["Que voit-on sur la fleur ?", "Des pétales, des sépales, des étamines et le pistil."],
        ["Quelle partie produit le pollen ?", "Les étamines (organes mâles de la fleur)."],
        ["Quelle partie contient les ovules ?", "Le pistil, en particulier l'ovaire, à la base de la fleur."],
        ["Comment le pollen arrive-t-il au pistil ?", "Il est transporté par le vent ou par les insectes (abeilles, papillons) : c'est la pollinisation."],
      ],
      synthese: "Donc, la fleur est l'organe de reproduction sexuée de la plante. Elle contient des étamines (pollen) et un pistil (ovules). La pollinisation transporte le pollen vers le pistil, grâce au vent ou aux insectes, pour permettre la fécondation.",
      motsCles: ["fleur", "étamines", "pistil", "pollen", "pollinisation", "ovules", "fécondation"],
      contenu: [
        { sousTitre: "1. Les organes de la fleur", texte: "La fleur est l'organe de la reproduction sexuée des plantes à fleurs. Elle possède plusieurs parties.", liste: ["Les sépales : petites feuilles vertes qui protègent la fleur avant l'ouverture.","Les pétales : parties colorées qui attirent les insectes.","Les étamines : organes mâles qui produisent le pollen.","Le pistil : organe femelle, formé du stigmate, du style et de l'ovaire qui contient les ovules."] },
        { sousTitre: "2. La pollinisation", texte: "La pollinisation est le transport du pollen des étamines vers le pistil. Elle peut se faire grâce au vent, à l'eau ou aux animaux, en particulier les insectes (abeilles, papillons). Les pétales colorés et le nectar attirent les insectes qui transportent le pollen." },
        { sousTitre: "3. La fécondation", texte: "Après la pollinisation, le pollen féconde les ovules contenus dans l'ovaire. L'ovule fécondé se transforme en graine, et l'ovaire se développe en fruit. C'est ainsi qu'une fleur peut donner un fruit contenant des graines." },
        { sousTitre: "4. L'importance des insectes", texte: "Les abeilles et les papillons sont des pollinisateurs très utiles : sans eux, beaucoup de plantes ne pourraient pas se reproduire. Les protéger, c'est protéger les cultures et les plantes de notre région." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Les organes mâles de la fleur sont…", opts: ["les pétales", "les étamines", "les sépales"], ok: 1, expl: "Les étamines produisent le pollen." },
          { q: "Le pistil contient…", opts: ["le nectar", "les ovules", "le pollen"], ok: 1, expl: "L'ovaire du pistil contient les ovules." },
          { q: "La pollinisation est…", opts: ["le transport du pollen vers le pistil", "la chute des feuilles", "la germination de la graine"], ok: 0, expl: "Le pollen est transporté des étamines au pistil." },
          { q: "Qui transporte souvent le pollen ?", opts: ["Le vent et les insectes", "L'eau de pluie seulement", "Les racines"], ok: 0, expl: "Le vent et les insectes (abeilles, papillons) transportent le pollen." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Les pétales attirent les insectes.", rep: true, expl: "Leur couleur et le nectar attirent les pollinisateurs." },
          { txt: "Le pollen est produit par le pistil.", rep: false, expl: "Le pollen est produit par les étamines." },
          { txt: "L'ovaire se transforme en fruit après la fécondation.", rep: true, expl: "L'ovaire devient le fruit et les ovules deviennent les graines." },
          { txt: "Une fleur peut se reproduire sans fleurir.", rep: false, expl: "La fleur est l'organe de reproduction sexuée des plantes à fleurs." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Quelles sont les deux parties principales de la fleur ?", r: "Les deux parties principales de la fleur sont les étamines (organes mâles) et le pistil (organe femelle)." },
          { q: "Qu'est-ce que la pollinisation ?", r: "La pollinisation est le transport du pollen des étamines vers le pistil, grâce au vent ou aux insectes." },
          { q: "Que devient l'ovaire après la fécondation ?", r: "L'ovaire se transforme en fruit et les ovules fécondés deviennent des graines." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "Les étamines produisent le", suite: "pollen" },
          { debut: "Le pistil contient les", suite: "ovules" },
          { debut: "Les abeilles et les papillons sont des", suite: "pollinisateurs" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "De la graine à la plante",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "décrire les étapes du développement de la graine à la plante",
      supportMeta: "Graines de haricot, schéma de germination, jeunes plants",
      revision: [
        ["Qu'est-ce que la pollinisation ?", "Le transport du pollen des étamines vers le pistil."],
        ["Que devient l'ovule fécondé ?", "Il devient une graine ; l'ovaire devient le fruit."],
      ],
      mise: ["As-tu déjà vu une graine de haricot donner une plante ? Quelles sont les étapes ?", "La graine germe, la racine sort, puis la tige et les feuilles, et la plante grandit."],
      observation: "les graines et le schéma de germination",
      observationSupport: "Graines de haricot, schéma de germination, jeunes plants",
      qa: [
        ["Que faut-il à une graine pour germer ?", "De l'eau, de l'air (oxygène) et une température convenable."],
        ["Que sort-il d'abord de la graine ?", "La racine (la radicule), puis la tige et les feuilles."],
        ["Que devient la jeune plante ?", "Elle grandit, fleurit, produit des fleurs, puis des fruits avec de nouvelles graines."],
        ["Comment appelle-t-on ce cycle ?", "Le cycle de développement de la plante, qui recommence avec la reproduction sexuée."],
      ],
      synthese: "Donc, le développement de la plante suit plusieurs étapes : la graine germe grâce à l'eau et à la chaleur, la racine et la tige sortent, la plante grandit, fleurit et produit des fruits contenant de nouvelles graines. C'est le cycle de reproduction de la plante.",
      motsCles: ["graine", "germination", "racine", "tige", "cycle de développement"],
      contenu: [
        { sousTitre: "1. La germination", texte: "La germination est le début de la vie d'une nouvelle plante : la graine, dans un sol humide et tiède, gonfle puis se fend. Une petite racine sort d'abord, puis la tige et les jeunes feuilles." },
        { sousTitre: "2. Les conditions de la germination", liste: ["De l'eau : la graine doit être humide.","De l'air : l'oxygène est nécessaire.","Une température convenable : ni trop froid, ni trop chaud.","Un sol ou un support adapté."] },
        { sousTitre: "3. La croissance de la plante", texte: "La jeune plante développe ses racines dans le sol, sa tige et ses feuilles vers la lumière. Elle grandit, puis fleurit : c'est la plante adulte." },
        { sousTitre: "4. Le cycle complet", texte: "La plante adulte produit des fleurs. Après la pollinisation et la fécondation, la fleur donne un fruit contenant des graines. Ces graines pourront germer à leur tour : le cycle recommence.", liste: ["Graine → germination → jeune plante → plante adulte → fleur → fruit et graines → nouvelle graine."] },
        { sousTitre: "Exemple", texte: "En plantant une graine de haricot dans un sol humide, on observe :", liste: ["la sortie de la racine ;","la sortie de la tige et des feuilles ;","la croissance de la plante ;","la floraison puis la formation de gousses contenant de nouvelles graines."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "La germination de la graine a besoin…", opts: ["d'eau, d'air et de chaleur", "de sable sec seulement", "d'obscurité totale"], ok: 0, expl: "L'eau, l'air et une température convenable sont nécessaires." },
          { q: "Quel organe sort d'abord de la graine ?", opts: ["La fleur", "La racine", "Le fruit"], ok: 1, expl: "La racine sort en premier (radicule)." },
          { q: "Un fruit contient…", opts: ["des feuilles", "des graines", "du pollen"], ok: 1, expl: "Le fruit protège les graines issues des ovules fécondés." },
          { q: "Le cycle complet d'une plante se termine par…", opts: ["la production de nouvelles graines", "la pourriture des racines", "la chute des pétales seulement"], ok: 0, expl: "Les graines produites assurent un nouveau cycle." },
        ]},
        { type: "completion", consigne: "Complète la suite du cycle.", pointsPar: 1, items: [
          { debut: "Graine → germination → jeune plante → plante adulte → fleur →", suite: "fruit et graines" },
          { debut: "La graine gonfle et se fend, c'est la", suite: "germination" },
          { debut: "La nouvelle plante naît d'une", suite: "graine" },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Cite les trois conditions de la germination.", r: "Les trois conditions sont l'eau, l'air (oxygène) et une température convenable." },
          { q: "Décris le cycle de développement d'une plante.", r: "La graine germe, la racine puis la tige sortent, la plante grandit, fleurit et produit un fruit contenant de nouvelles graines." },
          { q: "Pourquoi dit-on que la reproduction des plantes est un cycle ?", r: "Parce que les graines produites par la plante donnent de nouvelles plantes, qui produisent à leur tour des graines." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "La graine a besoin d'eau pour germer.", rep: true, expl: "L'eau est une condition indispensable de la germination." },
          { txt: "La fleur apparaît avant la racine chez une graine.", rep: false, expl: "La racine apparaît d'abord, la fleur beaucoup plus tard." },
          { txt: "Les graines sont contenues dans le fruit.", rep: true, expl: "Le fruit protège les graines issues de la fécondation." },
          { txt: "Une plante meurt toujours sans avoir de graines.", rep: false, expl: "Beaucoup de plantes produisent des graines avant de mourir ; mais certaines se reproduisent autrement." },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Importance et inconvénients de la reproduction sexuée",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer l'importance et les inconvénients de la reproduction sexuée chez les plantes",
      supportMeta: "Planches de plantes issues de graines, schémas",
      revision: [
        ["Quelles sont les étapes du cycle de la plante ?", "Graine, germination, jeune plante, plante adulte, fleur, fruit et graines."],
        ["Qu'est-ce que la pollinisation ?", "Le transport du pollen des étamines vers le pistil."],
      ],
      mise: ["Pourquoi les agriculteurs sèment-ils des graines plutôt que de couper des branches ?", "Parce que les graines donnent de nouvelles plantes, et souvent des plantes variées."],
      observation: "les planches de plantes issues de graines",
      observationSupport: "Planches de jeunes plantes issues de graines, schémas de fleurs",
      qa: [
        ["Comment une graine donne-t-elle une nouvelle plante ?", "Par la germination, puis la croissance de la plante."],
        ["Les plantes issues de graines sont-elles toutes identiques ?", "Non, elles présentent souvent des variations (taille, couleur, résistance)."],
        ["Quel est l'avantage de cette variété ?", "Elle permet à la plante de mieux s'adapter aux conditions du milieu."],
        ["Quels sont les inconvénients de la reproduction par graines ?", "Elle dépend du pollen, des insectes ou du vent et elle peut être lente ou échouer."],
      ],
      synthese: "Donc, la reproduction sexuée des plantes présente des avantages (variété, adaptation, nouvelles plantes nombreuses) et des inconvénients (dépendance à la pollinisation, lenteur, risque d'échec). Les graines assurent le renouvellement des plantes.",
      motsCles: ["reproduction sexuée", "variété", "adaptation", "pollinisation", "graines"],
      contenu: [
        { sousTitre: "1. Qu'est-ce que la reproduction sexuée chez les plantes ?", texte: "La reproduction sexuée fait intervenir les organes de la fleur : le pollen (étamines) et les ovules (pistil). Après la pollinisation et la fécondation, la fleur produit un fruit et des graines. La graine, en germant, donne une nouvelle plante." },
        { sousTitre: "2. Les avantages", liste: ["Les plantes issues de graines sont nombreuses.","Elles présentent une variété : chaque graine peut donner une plante un peu différente.","Cette variété permet une meilleure adaptation au milieu (climat, sol, maladies).","Les graines peuvent être conservées, transportées et semées.","Le fruit qui contient les graines protège le développement des jeunes plantes."] },
        { sousTitre: "3. Les inconvénients ou limites", liste: ["La plante doit être pollinisée : sans insectes ou sans vent, pas de graines.","La reproduction sexuée est souvent plus lente que la multiplication végétative.","Les jeunes plants sont parfois fragiles et doivent être soignés.","Les plantes issues de graines ne sont pas garanties identiques aux parents (ce qui peut être un problème pour les variétés choisies)."] },
        { sousTitre: "4. Conclusion", texte: "La reproduction sexuée est le mode naturel de renouvellement des plantes à fleurs. Elle est très importante dans la nature et en agriculture, malgré ses limites." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "La reproduction sexuée des plantes utilise…", opts: ["les feuilles", "la fleur (pollen et ovules)", "les racines"], ok: 1, expl: "Le pollen et les ovules de la fleur permettent la fécondation." },
          { q: "Un avantage de la reproduction sexuée est…", opts: ["la variété des plantes", "la lenteur", "la dépendance aux insectes"], ok: 0, expl: "Les graines donnent des plantes variées, mieux adaptées." },
          { q: "Un inconvénient de la reproduction sexuée est…", opts: ["la production de graines", "la dépendance à la pollinisation", "la germination"], ok: 1, expl: "Sans pollinisation, la plante ne produit pas de graines." },
          { q: "Les graines permettent de…", opts: ["semer de nouvelles plantes", "fabriquer du pollen", "enlever les feuilles"], ok: 0, expl: "En germant, les graines donnent des nouvelles plantes." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Les plantes issues de graines sont toutes identiques.", rep: false, expl: "Elles présentent souvent des variations." },
          { txt: "La reproduction sexuée dépend des pollinisateurs.", rep: true, expl: "Le pollen doit être transporté vers le pistil." },
          { txt: "La reproduction sexuée est souvent rapide.", rep: false, expl: "Elle est généralement plus lente que la multiplication végétative." },
          { txt: "Le fruit protège les graines.", rep: true, expl: "Le fruit se forme autour des graines et les protège." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Cite deux avantages de la reproduction sexuée des plantes.", r: "Elle produit de nombreuses plantes et donne une variété qui permet une meilleure adaptation au milieu." },
          { q: "Cite un inconvénient de la reproduction sexuée.", r: "Elle dépend de la pollinisation : sans insectes ni vent, il n'y a pas de graines." },
          { q: "Pourquoi les graines sont-elles importantes en agriculture ?", r: "Parce qu'elles permettent de semer de nouvelles plantes, de les transporter et de conserver les variétés." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "La fleur permet la ", suite: "pollinisation" },
          { debut: "La variété des plantes améliore leur", suite: "adaptation" },
          { debut: "La reproduction sexuée dépend du transport du", suite: "pollen" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Le bouturage",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer la technique du bouturage et donner des exemples de plantes bouturées",
      supportMeta: "Boutures de plantes (manioc, géranium, bougainvillier), terreau, image",
      revision: [
        ["Quels sont les avantages de la reproduction sexuée ?", "Elle produit beaucoup de plantes, variées et adaptées."],
        ["Quel est son inconvénient principal ?", "Elle dépend de la pollinisation et peut être lente."],
      ],
      mise: ["Comment obtient-on un nouveau plant de manioc sans graine ?", "En plantant un morceau de tige dans le sol : c'est le bouturage."],
      observation: "les boutures et le plant de manioc ou de géranium",
      observationSupport: "Boutures de manioc, de géranium, de bougainvillier, terreau, godets",
      qa: [
        ["Que voit-on sur les boutures ?", "Un morceau de tige (parfois avec des feuilles) qui peut donner des racines."],
        ["Comment fait-on une bouture ?", "On coupe un morceau de tige, on le plante dans un sol humide et on attend les racines."],
        ["La nouvelle plante vient-elle d'une graine ?", "Non : elle vient d'une partie de la plante mère : c'est une reproduction asexuée."],
        ["Quelles plantes peut-on bouturer facilement ?", "Le manioc, le géranium, le bougainvillier, la plante de la patience…"],
      ],
      synthese: "Donc, le bouturage est une technique de multiplication végétative : on plante un morceau de tige (bouture) qui développe des racines et donne une nouvelle plante, identique à la plante mère. Le manioc, le géranium et le bougainvillier se bouturent facilement.",
      motsCles: ["bouturage", "bouture", "multiplication végétative", "reproduction asexuée"],
      contenu: [
        { sousTitre: "1. La multiplication végétative", texte: "Certaines plantes peuvent se reproduire sans graine, à partir d'une partie d'elles-mêmes (tige, feuille, racine) : c'est la reproduction asexuée, aussi appelée multiplication végétative. Le bouturage est l'une de ces techniques." },
        { sousTitre: "2. Le bouturage", texte: "Le bouturage consiste à prélever un morceau de tige (la bouture), le planter dans un sol humide et attendre qu'il développe des racines. La bouture devient alors une nouvelle plante, identique à la plante mère.", liste: ["On coupe une tige saine avec quelques feuilles.","On plante la bouture dans un sol humide (terreau, sable).","On arrose régulièrement.","Des racines apparaissent, puis la plante grandit."] },
        { sousTitre: "3. Exemples de plantes bouturées", liste: ["Le manioc : les tiges sont coupées en morceaux et plantées.","Le géranium : les tiges donnent des plants.","Le bougainvillier : il se multiplie par boutures.","La patate douce, la canne à sucre, certains arbustes d'ornement."] },
        { sousTitre: "4. Avantages et limites du bouturage", texte: "Le bouturage est rapide et donne des plantes identiques à la mère. Mais il ne crée pas de variété, et une maladie de la plante mère peut se transmettre aux jeunes plants." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Le bouturage utilise une partie de…", opts: ["la graine", "la plante mère", "la fleur"], ok: 1, expl: "On prélève un morceau de tige de la plante mère." },
          { q: "Une bouture développe d'abord…", opts: ["des fleurs", "des racines", "des fruits"], ok: 1, expl: "Les racines apparaissent dans le sol humide." },
          { q: "La plante issue d'une bouture est…", opts: ["identique à la mère", "toujours différente", "stérile"], ok: 0, expl: "La multiplication végétative reproduit la plante mère." },
          { q: "Lequel de ces végétaux se bouture facilement ?", opts: ["Le manioc", "Le riz par graine", "La mousse"], ok: 0, expl: "Le manioc se multiplie par boutures de tiges." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Le bouturage est une reproduction asexuée.", rep: true, expl: "Il ne fait pas intervenir de graine ni de fécondation." },
          { txt: "La bouture a besoin d'un sol humide.", rep: true, expl: "L'eau permet l'apparition des racines." },
          { txt: "Une bouture donne une plante différente de la mère.", rep: false, expl: "La plante est identique à la plante mère." },
          { txt: "Le bouturage est plus rapide que la germination.", rep: true, expl: "Il permet d'obtenir un plant en peu de temps." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce que le bouturage ?", r: "Le bouturage est une technique qui consiste à planter un morceau de tige d'une plante pour obtenir une nouvelle plante." },
          { q: "Que faut-il faire pour réussir une bouture ?", r: "Il faut couper un morceau de tige sain, le planter dans un sol humide et l'arroser régulièrement." },
          { q: "Cite deux plantes que l'on bouture.", r: "Le manioc et le géranium sont deux plantes qui se bouturent (ou le bougainvillier)." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "Le bouturage est une technique de multiplication", suite: "végétative" },
          { debut: "La bouture donne une plante", suite: "identique" },
          { debut: "Le manioc se multiplie par", suite: "bouturage" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Le greffage",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer la technique du greffage et son intérêt",
      supportMeta: "Schéma du greffage, outils (greffoir), images d'arbres fruitiers",
      revision: [
        ["Qu'est-ce que le bouturage ?", "Une technique de multiplication végétative à partir d'un morceau de tige."],
        ["Quel avantage a-t-il ?", "Il est rapide et donne des plantes identiques à la mère."],
      ],
      mise: ["Un agriculteur veut avoir un manguier qui donne des fruits sucrés, mais dont les racines résistent à la sécheresse. Que peut-il faire ?", "Il peut greffer une branche d'un manguier à fruits sucrés sur un pied aux racines résistantes."],
      observation: "le schéma du greffage et les images d'arbres fruitiers",
      observationSupport: "Schéma du greffage, images de manguiers et d'agrumes, greffoir",
      qa: [
        ["Que montre le schéma ?", "Deux parties de plantes unies ensemble : le greffon et le porte-greffe."],
        ["Quelle partie donnera les fruits ?", "Le greffon (branche de la variété choisie) donne les fruits."],
        ["Quelle partie fournit les racines ?", "Le porte-greffe fournit les racines et le tronc."],
        ["Pourquoi greffer plutôt que semer ?", "Pour obtenir une variété précise (fruits sucrés) sur un pied résistant."],
      ],
      synthese: "Donc, le greffage consiste à unir une partie d'une plante (le greffon, qui donnera les fruits de la variété choisie) sur une autre plante (le porte-greffe, qui fournit les racines et la résistance). On greffe souvent les agrumes et les manguiers.",
      motsCles: ["greffage", "greffon", "porte-greffe", "variété"],
      contenu: [
        { sousTitre: "1. Qu'est-ce que le greffage ?", texte: "Le greffage est une technique de multiplication végétative qui consiste à unir deux parties de plantes pour qu'elles ne forment plus qu'une seule plante." },
        { sousTitre: "2. Le greffon et le porte-greffe", liste: ["Le greffon : partie prélevée sur la plante choisie (variété à fruits sucrés, belle floraison…).","Le porte-greffe : plante ou pied qui fournit les racines et le tronc (souvent plus résistant au sol, à la sécheresse ou aux maladies)."] },
        { sousTitre: "3. Comment se fait la greffe ?", texte: "On coupe le porte-greffe, on y insère le greffon, puis on maintient les deux parties en contact (ligature, cire). Les deux parties se soudent et la plante greffée grandit.", liste: ["Choisir un porte-greffe sain et adaptable.","Prélever un greffon de la variété souhaitée.","Unir les deux parties avec un outil propre (greffoir).","Ligaturer et protéger, puis laisser la plante pousser."] },
        { sousTitre: "4. Exemples et intérêt", texte: "On greffe beaucoup d'arbres fruitiers : agrumes (orangers, citronniers), manguiers, arbres à litchi, pommiers… Le greffage donne une variété précise et des arbres plus résistants, et il permet de multiplier une plante sans graine." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Dans une greffe, le greffon est…", opts: ["la partie qui donne les racines", "la partie de la plante choisie qui donnera les fruits", "le sol"], ok: 1, expl: "Le greffon apporte la variété souhaitée." },
          { q: "Le porte-greffe fournit…", opts: ["les racines et le tronc", "les fruits", "les graines"], ok: 0, expl: "Le porte-greffe apporte la résistance et les racines." },
          { q: "Le greffage est une technique de…", opts: ["reproduction sexuée", "multiplication végétative", "pollinisation"], ok: 1, expl: "Il unit deux parties de plantes, sans graine." },
          { q: "Quel arbre greffe-t-on souvent ?", opts: ["Le manguier", "Le riz", "Le blé"], ok: 0, expl: "Le manguier et les agrumes sont souvent greffés." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Le greffon donne les fruits de la variété choisie.", rep: true, expl: "C'est la partie qui porte la variété désirée." },
          { txt: "Le greffage utilise des graines.", rep: false, expl: "Le greffage unit deux parties de plantes, sans graine." },
          { txt: "Le porte-greffe peut rendre l'arbre plus résistant.", rep: true, expl: "Il apporte ses racines et sa robustesse." },
          { txt: "Toutes les plantes se greffent facilement.", rep: false, expl: "Seules certaines plantes (arbres fruitiers, rosiers…) se greffent bien." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce que le greffage ?", r: "Le greffage est une technique de multiplication végétative qui unit un greffon à un porte-greffe pour former une seule plante." },
          { q: "Quel est le rôle du porte-greffe ?", r: "Le porte-greffe fournit les racines et le tronc, et donne sa résistance à la plante greffée." },
          { q: "Pourquoi greffe-t-on les arbres fruitiers ?", r: "Pour obtenir une variété précise de fruits sur un pied résistant, sans passer par la graine." },
        ]},
        { type: "appariement", consigne: "Relie chaque partie de la greffe à son rôle.", pointsPar: 1, items: [{ g: ["Greffon", "Porte-greffe", "Greffoir"], d: ["Fournit les racines", "Donne la variété de fruits", "Outil pour couper"], pairs: [[0, 1], [1, 0], [2, 2]] }] },
      ],
    },
    {
      type: "cours",
      titre: "Le marcottage et le choix d'une technique",
      theme: "Organisation des êtres vivants",
      ras: "Différencier les différents modes de reproduction des êtres vivants animaux et végétaux",
      valeurs: "Responsabilité, respect de la vie",
      objectif: "expliquer le marcottage et choisir une technique adaptée à une plante locale",
      supportMeta: "Schéma du marcottage, images de jeunes plants, exemples locaux",
      revision: [
        ["Qu'est-ce que le greffon ?", "La partie de la plante choisie qui donnera les fruits de la variété souhaitée."],
        ["Que fournit le porte-greffe ?", "Les racines et le tronc, ainsi que la résistance."],
      ],
      mise: ["Certains arbres ne produisent pas de boutures faciles. Comment un jardinier peut-il les multiplier ?", "Il peut coucher une branche dans la terre : c'est le marcottage."],
      observation: "le schéma du marcottage et les exemples locaux",
      observationSupport: "Schéma du marcottage, images de plants de mûrier ou de litchi (exemples)", // exemples prudents
      qa: [
        ["Que montre le schéma du marcottage ?", "Une branche de la plante mère est couchée et enterrée, sans être coupée."],
        ["Que se passe-t-il sur la partie enterrée ?", "Des racines se forment sur la branche, encore attachée à la plante mère."],
        ["Que fait-on ensuite ?", "On coupe la branche enracinée : elle devient une nouvelle plante indépendante."],
        ["Comment choisir entre bouturage, greffage et marcottage ?", "Selon la plante et le but : bouture = rapide et simple ; greffe = variété précise + résistance ; marcotte = pour les plantes difficiles à bouturer."],
      ],
      synthese: "Donc, le marcottage consiste à faire pousser des racines sur une branche encore attachée à la plante mère, puis à la séparer pour obtenir une nouvelle plante. Pour choisir une technique, on tient compte de la plante, de la rapidité, de la variété voulue et de la résistance du pied.",
      motsCles: ["marcottage", "marcotte", "plante mère", "choix de la technique"],
      contenu: [
        { sousTitre: "1. Le marcottage", texte: "Le marcottage est une technique de multiplication végétative : on couche une branche de la plante mère dans le sol, on la fixe et on la recouvre de terre. Des racines apparaissent sur la partie enterrée, puis on sépare la branche enracinée de la plante mère : c'est la marcotte." },
        { sousTitre: "2. Les étapes du marcottage", liste: ["Choisir une branche souple et saine.","La coucher dans un sol humide (ou l'entourer de terre).","Attendre l'apparition des racines (quelques semaines ou mois).","Couper la branche enracinée et la repiquer."] },
        { sousTitre: "3. Exemples", texte: "Le marcottage est pratiqué sur des plantes où le bouturage est difficile : mûrier, litchi, certains arbres fruitiers, certaines plantes d'ornement. Au jardin, on peut aussi marcotter des plantes grimpantes ou des arbustes." },
        { sousTitre: "4. Choisir la bonne technique", texte: "Voici comment choisir selon le but :", liste: ["Bouturage : rapide et simple, pour le manioc, le géranium, le bougainvillier.","Greffage : pour avoir une variété précise de fruits sur un pied résistant (agrumes, manguier).","Marcottage : pour les plantes qui se bouturent mal, avec des racines plus sûres.","La graine (reproduction sexuée) : pour obtenir de la variété et beaucoup de plants."] },
        { sousTitre: "5. Comparaison rapide", texte: "Toutes ces techniques sont des reproductions asexuées, sauf la graine : la nouvelle plante est égale à la plante mère, ce qui est utile pour garder une bonne variété. La graine, elle, donne de la diversité." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "En marcottage, la branche reste…", opts: ["attachée à la plante mère", "coupée immédiatement", "dans la fleur"], ok: 0, expl: "La branche développe ses racines avant d'être séparée." },
          { q: "La marcotte est…", opts: ["la graine", "la branche enracinée séparée de la mère", "le pollen"], ok: 1, expl: "La marcotte est la jeune plante obtenue." },
          { q: "Le marcottage convient aux plantes…", opts: ["qui se bouturent difficilement", "qui n'ont pas de racines", "aquatiques uniquement"], ok: 0, expl: "Il est utilisé quand le bouturage est difficile." },
          { q: "Quelle technique donne une variété précise sur un pied résistant ?", opts: ["Le marcottage", "Le greffage", "Le semis"], ok: 1, expl: "Le greffage unit le greffon de la variété au porte-greffe résistant." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "La marcotte est séparée de la plante mère après l'apparition des racines.", rep: true, expl: "On coupe la branche enracinée pour obtenir un nouveau plant." },
          { txt: "Le marcottage fait intervenir le pollen.", rep: false, expl: "Le marcottage est une reproduction asexuée." },
          { txt: "Le semis permet d'obtenir des plantes variées.", rep: true, expl: "Les graines donnent une diversité de plantes." },
          { txt: "Le greffage est toujours plus simple que la bouture.", rep: false, expl: "Le bouturage est souvent plus simple et rapide." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce que le marcottage ?", r: "Le marcottage consiste à faire pousser des racines sur une branche encore attachée à la plante mère, puis à la séparer." },
          { q: "Quelles sont les étapes du marcottage ?", r: "On couche une branche dans le sol, on attend les racines, puis on coupe la branche enracinée et on la repique." },
          { q: "Comment choisir entre semis, bouturage, greffage et marcottage ?", r: "On choisit selon la plante et le but : le semis donne de la variété, la bouture est rapide, la greffe donne une variété résistante, le marcottage convient aux plantes difficiles à bouturer." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "La branche marcottée développe des", suite: "racines" },
          { debut: "La marcotte est ensuite séparée de la", suite: "plante mère" },
          { debut: "Le greffage unit un greffon et un", suite: "porte-greffe" },
        ]},
      ],
    },
  ],
};

module.exports = U;
