// ============================================================
// Unité V — Environnement (RAS : moyens d'approvisionnement en eau,
// bassins versants, vases communicants) — 11 h
// ============================================================

const U = {
  num: "V",
  titre: "Environnement",
  ras: "Distinguer les différents moyens d'approvisionnement en eau · Expliquer l'importance des bassins versants · Démontrer l'importance du principe des vases communicants",
  valeurs: "Responsabilité, autonomie",
  themes: ["Les moyens d'approvisionnement en eau", "Avantages et inconvénients des sources d'eau",
    "Les problèmes d'accès à l'eau", "Le bassin versant : origine et circulation de l'eau",
    "Rôle et protection des bassins versants", "Le principe des vases communicants",
    "La distribution de l'eau dans la ville et les champs"],
  topics: [
    {
      type: "cours",
      titre: "Les moyens d'approvisionnement en eau",
      theme: "Environnement",
      ras: "Distinguer les différents moyens d'approvisionnement en eau",
      valeurs: "Responsabilité, autonomie",
      objectif: "identifier les différents moyens d'approvisionnement en eau de la région",
      supportMeta: "Images ou photos (source, fontaine, rivière, lac, puits), carte de la localité",
      revision: [
        ["D'où vient l'eau que nous buvons ?", "Elle vient des sources, des rivières, des lacs ou des nappes souterraines."],
        ["Qu'est-ce que l'eau ?", "Un liquide indispensable à la vie ; le corps humain en a besoin chaque jour."],
      ],
      mise: ["Chez toi, d'où vient l'eau que la famille utilise ?", "Du puits, de la fontaine, de la rivière, du robinet (selon les régions)."],
      observation: "les images des différents moyens d'approvisionnement en eau",
      observationSupport: "Photos : source, fontaine, rivière, lac, puits, robinet",
      qa: [
        ["Quels moyens d'approvisionnement voyez-vous ?", "Une source, une fontaine, une rivière, un lac, un puits, un robinet."],
        ["Qu'est-ce qu'une source ?", "Un endroit où l'eau souterraine sort naturellement du sol."],
        ["Qu'est-ce qu'un puits ?", "Un trou creusé pour atteindre l'eau d'une nappe souterraine."],
        ["Pourquoi existe-t-il plusieurs moyens ?", "Parce que les régions n'ont pas les mêmes ressources en eau (rivières, lacs, nappes souterraines…)."],
      ],
      synthese: "Donc, on s'approvisionne en eau de plusieurs manières : source naturelle, fontaine, rivière, lac, puits (nappe souterraine) ou réseau de distribution. Le choix dépend des ressources de la région.",
      motsCles: ["approvisionnement en eau", "source", "fontaine", "rivière", "lac", "puits", "nappe souterraine"],
      contenu: [
        { sousTitre: "1. Pourquoi l'eau est-elle précieuse ?", texte: "L'eau est indispensable à la vie : boire, cuisiner, se laver, arroser les cultures, abreuver les animaux. Dans une maison, l'eau sert à beaucoup d'usages ; il faut donc savoir d'où elle vient et ne pas la gaspiller." },
        { sousTitre: "2. Les moyens d'approvisionnement", liste: ["La source : l'eau souterraine jaillit naturellement du sol.","La fontaine : point d'eau aménagé, souvent public.","La rivière : cours d'eau qui coule à la surface.","Le lac : étendue d'eau douce à la surface du sol.","Le puits : excavation creusée jusqu'à la nappe souterraine.","Le forage : puits équipé d'une pompe pour puiser l'eau en profondeur.","Le réseau d'eau (robinet) : eau traitée et distribuée par un château d'eau."] },
        { sousTitre: "3. La nappe souterraine", texte: "Sous le sol se trouvent des réserves d'eau appelées nappes souterraines (nappes phréatiques). L'eau de pluie s'infiltre et s'y accumule. Les puits et les forages permettent de l'utiliser." },
        { sousTitre: "4. L'eau dans la vie quotidienne", texte: "En ville comme au village, il faut une eau propre pour boire et cuisiner. Si l'eau vient d'une rivière ou d'un puits non protégé, il faut la filtrer ou la faire bouillir avant de la boire." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Une source est…", opts: ["un endroit où l'eau sort naturellement du sol", "un lac artificiel", "un robinet"], ok: 0, expl: "La source est un jaillissement naturel d'eau souterraine." },
          { q: "Un puits sert à…", opts: ["atteindre l'eau d'une nappe souterraine", "stocker le riz", "arroser uniquement"], ok: 0, expl: "Le puits est creusé jusqu'à la nappe." },
          { q: "Les nappes souterraines se remplissent grâce…", opts: ["à l'eau de pluie qui s'infiltre", "aux déchets", "au vent"], ok: 0, expl: "L'eau de pluie s'infiltre dans le sol." },
          { q: "Avant de boire l'eau d'une rivière, il faut…", opts: ["la filtrer ou la faire bouillir", "la saler", "la chauffer seulement une minute"], ok: 0, expl: "L'eau de surface doit être traitée avant consommation." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "L'eau est indispensable à la vie.", rep: true, expl: "Elle sert à boire, cuisiner, se laver et à l'agriculture." },
          { txt: "Un lac est une nappe souterraine.", rep: false, expl: "Le lac est une étendue d'eau de surface." },
          { txt: "Un forage est un puits équipé d'une pompe.", rep: true, expl: "Le forage permet de puiser l'eau en profondeur." },
          { txt: "Toutes les régions ont les mêmes sources d'eau.", rep: false, expl: "Les ressources en eau varient selon les régions." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Cite trois moyens d'approvisionnement en eau.", r: "La source, la rivière et le puits sont trois moyens d'approvisionnement en eau (ou la fontaine, le lac, le robinet…)." },
          { q: "Qu'est-ce qu'une nappe souterraine ?", r: "C'est une réserve d'eau accumulée sous le sol, que l'on atteint avec des puits ou des forages." },
          { q: "Comment protège-t-on la santé quand l'eau vient d'une rivière ?", r: "On filtre ou on fait bouillir l'eau avant de la boire." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "L'eau qui jaillit du sol est une", suite: "source" },
          { debut: "On creuse un puits pour atteindre la", suite: "nappe souterraine" },
          { debut: "Avant de boire l'eau de surface, on la", suite: "filtre" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Avantages et inconvénients des sources d'eau",
      theme: "Environnement",
      ras: "Distinguer les différents moyens d'approvisionnement en eau",
      valeurs: "Responsabilité, autonomie",
      objectif: "comparer les avantages et les inconvénients des différentes sources d'eau",
      supportMeta: "Tableau comparatif, photos des sources locales, documents",
      revision: [
        ["Cite deux moyens d'approvisionnement en eau.", "La source et le puits (ou la rivière, le lac…)."],
        ["Qu'est-ce qu'une nappe souterraine ?", "Une réserve d'eau sous le sol."],
      ],
      mise: ["Certains villages ont une rivière mais pas de robinet. Est-ce facile de se procurer de l'eau ?", "Non : il faut aller chercher l'eau, parfois loin, et elle doit être traitée avant d'être bue."],
      observation: "le tableau comparatif et les photos des sources d'eau locales",
      observationSupport: "Tableau avantages/inconvénients, photos de la rivière, du puits, de la fontaine du village",
      qa: [
        ["Quel est l'avantage d'une fontaine ?", "Elle donne de l'eau près des maisons, souvent plus propre et plus facile à ramasser."],
        ["Quel est l'inconvénient d'une rivière ?", "Elle peut être loin, polluée ou à sec en saison sèche."],
        ["Le puits est-il toujours sûr ?", "Non, s'il n'est pas couvert ou protégé, il peut être pollué."],
        ["Pourquoi certaines sources disparaissent-elles en saison sèche ?", "Parce que la réserve d'eau souterraine baisse quand il ne pleut pas."],
      ],
      synthese: "Donc, chaque source d'eau a des avantages (proximité, quantité, qualité) et des inconvénients (distance, pollution, risque de tarissement). Le choix dépend du milieu, de la saison et des aménagements disponibles.",
      motsCles: ["avantages", "inconvénients", "proximité", "qualité de l'eau", "tarissement", "pollution"],
      contenu: [
        { sousTitre: "1. Comparer les sources d'eau", texte: "Pour choisir un moyen d'approvisionnement, on compare : la proximité (où se trouve l'eau ?), la quantité (y a-t-il assez d'eau toute l'année ?), la qualité (l'eau est-elle propre ?) et le coût (faut-il payer, marcher loin, pomper ?)." },
        { sousTitre: "2. Le tableau des avantages et inconvénients", liste: ["Source naturelle : avantages : eau souvent propre, gratuite ; inconvénients : parfois loin, peut tarir en saison sèche.","Fontaine : avantages : près des habitants, protégée ; inconvénients : file d'attente, entretien nécessaire, eau parfois limitée.","Rivière : avantages : grande quantité, utile pour l'irrigation ; inconvénients : peut être polluée, moins sûre pour boire, peut déborder ou tarir.","Lac : avantages : réserve importante ; inconvénients : souvent plus loin, pollution possible, évaporation en saison sèche.","Puits/forage : avantages : eau proche du village, disponible toute l'année si la nappe est bonne ; inconvénients : installation coûteuse, besoin d'entretien et de protection.","Robinet (réseau) : avantages : pratique, eau traitée ; inconvénients : coût, indisponible partout."] },
        { sousTitre: "3. Les problèmes liés à l'eau dans les villages", texte: "Dans beaucoup de régions, les habitants marchent longtemps pour chercher de l'eau. En saison sèche, les sources tarissent, les rivières baissent et les puits doivent être approfondis. Il faut alors économiser l'eau et protéger les points d'eau." },
        { sousTitre: "4. Le bon usage", texte: "Quelle que soit la source, on doit : protéger le point d'eau (clôture, couvercle), éviter de jeter les déchets dedans ou autour, et traiter l'eau de boisson (filtration, ébullition)." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Un avantage de la fontaine est…", opts: ["sa proximité des maisons", "son coût élevé", "son éloignement"], ok: 0, expl: "La fontaine est souvent proche du village." },
          { q: "Un inconvénient de la rivière est…", opts: ["qu'elle peut être polluée", "qu'elle est gratuite", "qu'elle donne beaucoup d'eau"], ok: 0, expl: "L'eau de rivière peut être contaminée." },
          { q: "En saison sèche, une source peut…", opts: ["tarir", "déborder", "devenir salée"], ok: 0, expl: "Le niveau des réserves baisse." },
          { q: "Pour choisir une source d'eau, on tient compte…", opts: ["de la proximité, de la quantité et de la qualité", "seulement de la couleur", "du nombre de poissons"], ok: 0, expl: "Ces critères permettent le meilleur choix." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Le robinet donne une eau traitée.", rep: true, expl: "Le réseau de distribution traite l'eau avant de la livrer." },
          { txt: "Tous les points d'eau sont protégés.", rep: false, expl: "Beaucoup de puits et de rivières ne sont pas protégés." },
          { txt: "Il faut marcher loin pour chercher de l'eau dans certains villages.", rep: true, expl: "C'est un problème fréquent d'accès à l'eau." },
          { txt: "La rivière est toujours plus propre que le puits.", rep: false, expl: "La rivière peut être polluée ; le puits protégé est souvent plus sûr." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Cite un avantage et un inconvénient de la rivière.", r: "Avantage : grande quantité d'eau ; inconvénient : elle peut être polluée ou tarir en saison sèche." },
          { q: "Quels critères utilise-t-on pour comparer les sources d'eau ?", r: "On utilise la proximité, la quantité, la qualité de l'eau et le coût." },
          { q: "Comment protéger un point d'eau ?", r: "Il faut le protéger par une clôture ou un couvercle, et ne pas jeter de déchets autour." },
        ]},
        { type: "appariement", consigne: "Relie chaque source à son avantage.", pointsPar: 1, items: [{ g: ["Fontaine", "Rivière", "Puits", "Robinet"], d: ["Eau traitée et pratique", "Grande quantité pour l'irrigation", "Proche du village", "Eau souterraine disponible"], pairs: [[0, 2], [1, 1], [2, 3], [3, 0]] }] },
      ],
    },
    {
      type: "cours",
      titre: "Les problèmes d'accès à l'eau",
      theme: "Environnement",
      ras: "Distinguer les différents moyens d'approvisionnement en eau",
      valeurs: "Responsabilité, autonomie",
      objectif: "identifier les problèmes d'accès à l'eau dans la région",
      supportMeta: "Photos de la saison sèche, documents sur les inégalités d'accès à l'eau",
      revision: [
        ["Quels critères utilise-t-on pour choisir une source d'eau ?", "La proximité, la quantité, la qualité et le coût."],
        ["Cite un inconvénient du puits.", "Il peut être pollué s'il n'est pas protégé."],
      ],
      mise: ["Dans certains villages, l'eau manque en saison sèche. Pourquoi ?", "Parce que les rivières baissent, les sources tarissent et les puits se vident."],
      observation: "les photos montrant la difficulté d'accès à l'eau",
      observationSupport: "Photos de saison sèche, de femmes et d'enfants portant des bidons d'eau",
      qa: [
        ["Que montrent ces photos ?", "Des personnes qui vont chercher de l'eau, parfois de très loin, et des points d'eau à sec."],
        ["Quelles sont les causes de ce manque d'eau ?", "La saison sèche, le manque de pluie, la pollution, le manque d'aménagements et la déforestation."],
        ["Quelles sont les conséquences ?", "Fatigue, temps perdu, maladies, cultures en manque d'eau, scolarité perturbée."],
        ["Comment peut-on améliorer la situation ?", "En protégeant les points d'eau, en construisant des puits et des citernes, en économisant l'eau et en reboisant."],
      ],
      synthese: "Donc, l'accès à l'eau pose plusieurs problèmes : éloignement, pénurie en saison sèche, pollution, coût, manque d'infrastructures. Ces problèmes touchent surtout les villages et ont des conséquences sur la santé, l'agriculture et l'école.",
      motsCles: ["accès à l'eau", "pénurie", "pollution", "saison sèche", "éloignement", "reboisement"],
      contenu: [
        { sousTitre: "1. Qu'est-ce que l'accès à l'eau ?", texte: "Avoir accès à l'eau, c'est pouvoir obtenir une eau propre, en quantité suffisante, près de chez soi et à un coût supportable. Quand une de ces conditions manque, l'accès à l'eau est difficile." },
        { sousTitre: "2. Les problèmes d'accès", liste: ["L'éloignement : il faut marcher longtemps pour atteindre le point d'eau.","La pénurie saisonnière : en saison sèche, les sources tarissent et les rivières baissent.","La pollution : déchets, animaux, produits chimiques peuvent contaminer l'eau.","Le manque d'infrastructures : pas de puits, de forages ni de réseau dans beaucoup de villages.","Le coût : l'eau du réseau ou les forages sont chers pour certaines familles."] },
        { sousTitre: "3. Les conséquences", liste: ["Santé : maladies liées à l'eau sale (diarrhées, choléra, typhoïde).","Temps et fatigue : les familles perdent du temps à chercher l'eau.","Agriculture : les cultures manquent d'eau, les récoltes baissent.","École : les enfants, surtout les filles, vont moins souvent à l'école.","Économie : les activités diminuent faute d'eau."] },
        { sousTitre: "4. Les solutions", liste: ["Protéger les sources et les puits.","Construire ou réhabiliter des points d'eau.","Économiser l'eau au quotidien.","Traiter l'eau de boisson (filtration, ébullition).","Reboiser pour que l'eau de pluie s'infiltre mieux.","Créer des comités de gestion de l'eau dans les villages."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Un problème d'accès à l'eau est…", opts: ["l'éloignement du point d'eau", "la proximité du marché", "l'abondance de pluie"], ok: 0, expl: "L'éloignement rend l'accès difficile." },
          { q: "En saison sèche, les sources…", opts: ["tarissent", "débordent", "se remplissent"], ok: 0, expl: "Les réserves baissent quand il ne pleut pas." },
          { q: "L'eau contaminée provoque…", opts: ["des maladies", "des récoltes abondantes", "moins de fatigue"], ok: 0, expl: "Les maladies hydriques sont fréquentes." },
          { q: "Une solution est…", opts: ["de protéger les points d'eau", "de jeter les déchets dans la rivière", "de consommer plus d'eau"], ok: 0, expl: "Protéger et aménager les points d'eau améliore l'accès." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Le manque d'eau en saison sèche est un problème d'accès à l'eau.", rep: true, expl: "La pénurie saisonnière limite l'accès." },
          { txt: "Les déchets jetés dans la rivière n'ont aucun effet.", rep: false, expl: "Ils polluent l'eau et nuisent à la santé." },
          { txt: "Le reboisement aide à garder l'eau dans le sol.", rep: true, expl: "Les racines favorisent l'infiltration de l'eau de pluie." },
          { txt: "Toutes les familles du pays ont un robinet chez elles.", rep: false, expl: "Le réseau d'eau n'est pas disponible partout." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Cite deux problèmes d'accès à l'eau.", r: "L'éloignement des points d'eau et la pénurie en saison sèche (ou la pollution, le coût…)." },
          { q: "Quelle est la conséquence de l'eau contaminée ?", r: "Elle peut provoquer des maladies comme la diarrhée ou le choléra." },
          { q: "Cite deux solutions pour améliorer l'accès à l'eau.", r: "Construire des puits et protéger les sources ; économiser l'eau et reboiser." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "En saison sèche, les sources peuvent", suite: "tarir" },
          { debut: "L'eau sale peut provoquer des", suite: "maladies" },
          { debut: "Le reboisement aide l'eau de pluie à s'", suite: "infiltrer" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Le bassin versant : origine et circulation de l'eau",
      theme: "Environnement",
      ras: "Expliquer l'importance des bassins versants",
      valeurs: "Responsabilité, autonomie",
      objectif: "expliquer l'origine de l'eau et sa circulation dans un bassin versant",
      supportMeta: "Schéma légendé d'un bassin versant, maquette simple, carte de la région",
      revision: [
        ["D'où vient l'eau des rivières ?", "De la pluie qui ruisselle sur le sol et des sources souterraines."],
        ["Qu'est-ce qu'une nappe souterraine ?", "Une réserve d'eau sous le sol."],
      ],
      mise: ["La rivière qui passe près du village ne tarit pas tout de suite après la pluie. Où toute cette eau est-elle allée ?", "Elle a été retenue et drainée par le bassin versant, qui collecte l'eau de pluie vers la rivière."],
      observation: "le schéma légendé du bassin versant",
      observationSupport: "Schéma légendé du bassin versant (crête, versants, rivière, vallée)",
      qa: [
        ["Que montre le schéma ?", "Un bassin versant : une zone de terre où l'eau de pluie est collectée et s'écoule vers une seule rivière."],
        ["Qu'est-ce qui limite le bassin versant ?", "Les crêtes ou les collines qui l'entourent (lignes de partage des eaux)."],
        ["Comment l'eau circule-t-elle ?", "La pluie tombe sur les versants, ruisselle, s'infiltre en partie et rejoint la rivière, puis continue vers la mer ou un lac."],
        ["D'où vient donc l'eau de la rivière ?", "De la pluie tombée dans le bassin versant, et des sources alimentées par l'eau infiltrée."],
      ],
      synthese: "Donc, un bassin versant est une zone délimitée par des crêtes où toute l'eau de pluie est collectée et s'écoule vers une même rivière. La pluie ruisselle sur les versants, s'infiltre en partie et alimente la rivière, qui draine le bassin vers la mer ou un lac.",
      motsCles: ["bassin versant", "crête", "versant", "ruissellement", "infiltration", "rivière"],
      contenu: [
        { sousTitre: "1. Qu'est-ce qu'un bassin versant ?", texte: "Un bassin versant est un territoire dont toutes les eaux de pluie s'écoulent vers un même cours d'eau (rivière) ou une même étendue (lac, mer). Il est limité par les crêtes ou les collines, appelées lignes de partage des eaux." },
        { sousTitre: "2. Les parties d'un bassin versant", liste: ["Les crêtes ou lignes de partage : les hauteurs qui séparent deux bassins.","Les versants : les pentes où l'eau ruisselle.","La rivière ou le cours d'eau principal : l'axe qui collecte l'eau.","La vallée : la zone basse où coule la rivière."] },
        { sousTitre: "3. La circulation de l'eau", texte: "Quand il pleut dans le bassin versant, l'eau prend plusieurs chemins :", liste: ["Une partie ruisselle sur les pentes vers la rivière.","Une partie s'infiltre dans le sol et alimente les nappes souterraines.","Les sources font remonter une partie de cette eau infiltrée.","La rivière collecte toute cette eau et l'emporte vers la mer ou un lac."] },
        { sousTitre: "4. L'origine de l'eau", texte: "L'eau d'un bassin versant vient de la pluie. Quand la réserve du bassin est bonne (sols, forêts), la rivière coule toute l'année ; quand elle est dégradée, les crues et les étiages (basses eaux) sont plus marqués." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Un bassin versant est…", opts: ["une zone dont l'eau s'écoule vers une même rivière", "un type de pompe", "un lac artificiel"], ok: 0, expl: "Toute l'eau du bassin rejoint le même cours d'eau." },
          { q: "Les crêtes délimitent…", opts: ["le bassin versant", "le puits", "la nappe"], ok: 0, expl: "Ce sont les lignes de partage des eaux." },
          { q: "L'eau de pluie qui tombe sur les versants…", opts: ["ruisselle vers la rivière", "reste toujours en haut", "ne sert à rien"], ok: 0, expl: "Elle ruisselle et alimente la rivière." },
          { q: "L'eau infiltrée alimente…", opts: ["les nappes souterraines", "les nuages", "la mer uniquement"], ok: 0, expl: "Elle rejoint les nappes puis les sources." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "La rivière collecte l'eau du bassin versant.", rep: true, expl: "Elle draine toute l'eau du bassin." },
          { txt: "Un bassin versant n'a pas de limites.", rep: false, expl: "Il est délimité par les crêtes." },
          { txt: "L'eau de pluie s'infiltre en partie dans le sol.", rep: true, expl: "Une partie de l'eau rejoint les nappes." },
          { txt: "La rivière provient uniquement de la mer.", rep: false, expl: "Elle provient de la pluie du bassin versant." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Qu'est-ce qu'un bassin versant ?", r: "Un bassin versant est une zone délimitée par des crêtes où toute l'eau de pluie s'écoule vers une même rivière." },
          { q: "Décris la circulation de l'eau dans un bassin versant.", r: "La pluie ruisselle sur les versants, une partie s'infiltre, les sources alimentent la rivière, qui draine le bassin vers la mer ou un lac." },
          { q: "D'où vient l'eau d'une rivière ?", r: "Elle vient de la pluie tombée dans le bassin versant et des sources alimentées par l'eau infiltrée." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "Le bassin versant est limité par les", suite: "crêtes" },
          { debut: "L'eau de pluie ruisselle sur les", suite: "versants" },
          { debut: "La rivière collecte l'eau du", suite: "bassin versant" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Rôle et protection des bassins versants",
      theme: "Environnement",
      ras: "Expliquer l'importance des bassins versants",
      valeurs: "Responsabilité, autonomie",
      objectif: "expliquer le rôle des bassins versants et l'importance de les protéger",
      supportMeta: "Schéma du bassin versant, images de reboisement et de barrage, documents",
      revision: [
        ["Qu'est-ce qu'un bassin versant ?", "Une zone où toute l'eau de pluie s'écoule vers une même rivière."],
        ["Comment l'eau circule-t-elle dans le bassin ?", "Par ruissellement et infiltration, puis vers la rivière."],
      ],
      mise: ["Pourquoi les forêts sont-elles importantes autour des rivières ?", "Elles retiennent l'eau, freinent le ruissellement et protègent le bassin versant."],
      observation: "le schéma du bassin versant et les photos de reboisement et de barrage",
      observationSupport: "Schéma du bassin versant, photos : forêt, brûlis, barrage, irrigation",
      qa: [
        ["Quel est le rôle du bassin versant ?", "Collecter l'eau de pluie, la diriger vers la rivière et réguler son écoulement."],
        ["Que se passe-t-il si on coupe les forêts du bassin ?", "L'eau ruisselle vite, la terre part avec l'eau (érosion), les crues et les sécheresses augmentent."],
        ["À quoi sert l'eau retenue par le bassin ?", "À boire, irriguer les cultures, produire de l'électricité (barrage hydroélectrique)."],
        ["Pourquoi faut-il protéger les bassins versants ?", "Pour garder de l'eau toute l'année, éviter l'érosion et les inondations, et protéger les cultures et la santé."],
      ],
      synthese: "Donc, le bassin versant collecte, dirige et régule l'écoulement de l'eau. Il fournit l'eau potable, l'eau d'irrigation et l'énergie hydroélectrique. Le protéger (reboisement, lutte contre les brûlis et la pollution) protège la vie des habitants.",
      motsCles: ["collecte", "régulation", "érosion", "inondations", "reboisement", "hydroélectricité"],
      contenu: [
        { sousTitre: "1. Les rôles du bassin versant", liste: ["Collecter : il reçoit toute l'eau de pluie de son territoire.","Diriger : il oriente l'eau vers la rivière principale.","Réguler : il retient une partie de l'eau (sols, forêts, nappes) et évite les écoulements trop rapides."] },
        { sousTitre: "2. L'importance économique et sociale", texte: "Le bassin versant fournit de l'eau pour la consommation (boire, cuisine, hygiène), pour l'agriculture (irrigation des champs, rizières) et parfois pour l'énergie (centrales hydroélectriques, comme celles de Madagascar). Il nourrit aussi les rivières, les poissons et la végétation." },
        { sousTitre: "3. Les dangers pour le bassin versant", liste: ["La déforestation et les brûlis : le sol se dégrade, l'eau ruisselle vite.","L'érosion : la terre fertile part avec l'eau de pluie.","La pollution : déchets et produits chimiques atteignent la rivière.","Les inondations : sans protection, l'eau déborde et détruit les cultures et les maisons.","La sécheresse : les sources tarissent quand le bassin est dégradé."] },
        { sousTitre: "4. Comment protéger le bassin versant ?", liste: ["Reboiser les pentes et protéger les forêts.","Ne pas brûler la végétation.","Planter en courbes de niveau pour retenir l'eau.","Ne pas jeter de déchets dans les rivières.","Économiser l'eau.","Construire des barrages et des retenues d'eau bien planifiés."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Le bassin versant régule l'écoulement de l'eau en…", opts: ["la retenant dans les sols et les forêts", "l'envoyant vite à la mer", "la faisant évaporer"], ok: 0, expl: "La régulation évite les crues et garde l'eau plus longtemps." },
          { q: "Un danger pour le bassin versant est…", opts: ["la déforestation", "le reboisement", "l'irrigation"], ok: 0, expl: "La déforestation accélère le ruissellement et l'érosion." },
          { q: "L'eau retenue par le bassin verse sert…", opts: ["à boire, irriguer et produire de l'électricité", "uniquement au lavage", "à rien"], ok: 0, expl: "Elle a plusieurs usages importants." },
          { q: "Pour protéger le bassin, il faut…", opts: ["reboiser les pentes", "brûler la végétation", "jeter les déchets à la rivière"], ok: 0, expl: "La végétation retient l'eau et le sol." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Les forêts aident à réguler l'écoulement de l'eau.", rep: true, expl: "Elles retiennent l'eau et freinent le ruissellement." },
          { txt: "L'érosion apporte de la fertilité aux rivières.", rep: false, expl: "L'érosion emporte la terre fertile et dégrade le bassin." },
          { txt: "Un barrage peut produire de l'électricité.", rep: true, expl: "L'hydroélectricité utilise la force de l'eau retenue." },
          { txt: "Les brûlis protègent le bassin versant.", rep: false, expl: "Les brûlis dégradent les sols et le bassin." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Cite les trois rôles du bassin versant.", r: "Le bassin versant collecte l'eau de pluie, la dirige vers la rivière et régule son écoulement." },
          { q: "Pourquoi la déforestation est-elle dangereuse pour le bassin versant ?", r: "Parce que l'eau ruisselle plus vite, le sol s'érode et les crues ou sécheresses s'aggravent." },
          { q: "Cite deux moyens de protéger un bassin versant.", r: "Reboiser les pentes et éviter les brûlis (ou ne pas jeter de déchets, économiser l'eau)." },
        ]},
        { type: "appariement", consigne: "Relie chaque problème à sa conséquence.", pointsPar: 1, items: [{ g: ["Déforestation", "Pollution", "Érosion", "Reboisement"], d: ["Eau contaminée", "Ruissellement rapide", "Protège le bassin", "Perte de terre fertile"], pairs: [[0, 1], [1, 0], [2, 3], [3, 2]] }] },
      ],
    },
    {
      type: "cours",
      titre: "Le principe des vases communicants",
      theme: "Environnement",
      ras: "Démontrer l'importance du principe des vases communicants dans la vie quotidienne",
      valeurs: "Responsabilité, autonomie",
      objectif: "énoncer le principe des vases communicants et l'illustrer par une expérience",
      supportMeta: "Récipients reliés par un tuyau (vases communicants), eau, colorant",
      revision: [
        ["Quel est le rôle du bassin versant ?", "Collecter, diriger et réguler l'eau."],
        ["Pourquoi reboiser les pentes ?", "Pour retenir l'eau et protéger le sol."],
      ],
      mise: ["Pourquoi l'eau arrive-t-elle chez toi quand on ouvre le robinet, alors que le château d'eau est en haut de la colline ?", "Parce que l'eau cherche toujours le même niveau : c'est le principe des vases communicants."],
      observation: "l'expérience des vases communicants (deux récipients reliés par un tuyau)",
      observationSupport: "Deux bouteilles reliées par un tuyau transparent, eau, colorant",
      qa: [
        ["Que se passe-t-il quand on penche un des récipients ?", "L'eau circule dans le tuyau jusqu'à ce que les deux niveaux soient égaux."],
        ["Pourquoi l'eau s'arrête-t-elle au même niveau ?", "Parce que la gravité attire l'eau et qu'elle cherche l'équilibre : les vases sont communicants."],
        ["Comment appelle-t-on ce principe ?", "Le principe des vases communicants."],
        ["À quoi sert-il dans la vie quotidienne ?", "À distribuer l'eau (château d'eau, canalisations, irrigation)."],
      ],
      synthese: "Donc, dans des récipients reliés entre eux (vases communicants), le liquide s'établit au même niveau dans tous les récipients : c'est le principe des vases communicants, dû à la gravité. Il est utilisé pour distribuer l'eau dans les villes et les champs.",
      motsCles: ["vases communicants", "niveau", "gravité", "équilibre", "distribution de l'eau"],
      contenu: [
        { sousTitre: "1. L'expérience", texte: "On prend deux bouteilles ou deux récipients reliés par un tuyau. On verse de l'eau dans le premier : l'eau passe dans le tuyau et monte dans le second, jusqu'à ce que la surface de l'eau soit au même niveau dans les deux récipients." },
        { sousTitre: "2. Le principe", texte: "Quand des récipients sont reliés entre eux, le liquide s'établit au même niveau dans tous. Ce phénomène s'appelle le principe des vases communicants. Il est dû à la gravité : l'eau est attirée vers le bas et cherche l'équilibre. Plus le récipient est haut, plus l'eau peut remonter loin." },
        { sousTitre: "3. Les applications", liste: ["Le château d'eau : l'eau stockée en hauteur descend dans les canalisations des maisons.","L'irrigation des champs : l'eau des canaux arrive aux parcelles par des tuyaux ou des rigoles.","Les canalisations d'eaux usées et d'eaux de pluie : elles évacuent l'eau vers les égouts ou les fossés.","Les réservoirs des fontaines et les citernes."] },
        { sousTitre: "4. Pourquoi c'est important", texte: "Le principe des vases communicants permet de distribuer l'eau sans pompe, par simple gravité : on place le réservoir en hauteur et l'eau descend toute seule vers les habitations et les champs. C'est un principe simple mais fondamental pour l'approvisionnement en eau." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Dans des vases communicants, l'eau s'établit…", opts: ["au même niveau", "plus haute dans le petit vase", "à des niveaux différents"], ok: 0, expl: "L'eau cherche l'équilibre." },
          { q: "Ce principe est dû à…", opts: ["la gravité", "la chaleur", "le vent"], ok: 0, expl: "La gravité attire l'eau vers le bas." },
          { q: "Le château d'eau fonctionne grâce…", opts: ["au principe des vases communicants", "à l'électricité uniquement", "à la pompe à bras seulement"], ok: 0, expl: "L'eau du réservoir en hauteur descend dans les canalisations." },
          { q: "Si on élève un récipient relié à un autre, l'eau…", opts: ["remonte jusqu'au même niveau", "reste immobile", "disparaît"], ok: 0, expl: "Le niveau s'égalise dans les deux récipients." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Les vases communicants sont reliés entre eux.", rep: true, expl: "Le tuyau les fait communiquer." },
          { txt: "L'eau reste toujours à des niveaux différents.", rep: false, expl: "Elle s'établit au même niveau." },
          { txt: "La gravité joue un rôle dans ce principe.", rep: true, expl: "C'est elle qui attire l'eau vers l'équilibre." },
          { txt: "Ce principe est inutile pour la distribution de l'eau.", rep: false, expl: "Il est à la base du château d'eau et des canalisations." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Énonce le principe des vases communicants.", r: "Dans des récipients reliés entre eux, le liquide s'établit au même niveau dans tous les récipients." },
          { q: "Pourquoi ce principe est-il dû à la gravité ?", r: "Parce que la gravité attire l'eau vers le bas et la pousse à chercher l'équilibre." },
          { q: "Donne une application du principe des vases communicants.", r: "Le château d'eau qui distribue l'eau dans les maisons par les canalisations." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "Les vases communicants sont des récipients", suite: "reliés" },
          { debut: "L'eau s'établit au même", suite: "niveau" },
          { debut: "Le château d'eau utilise le principe des", suite: "vases communicants" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "La distribution de l'eau dans la ville et les champs",
      theme: "Environnement",
      ras: "Démontrer l'importance du principe des vases communicants dans la vie quotidienne",
      valeurs: "Responsabilité, autonomie",
      objectif: "expliquer le fonctionnement de la distribution de l'eau en ville et dans les champs",
      supportMeta: "Schéma du château d'eau, images de canalisations et d'irrigation, maquette",
      revision: [
        ["Énonce le principe des vases communicants.", "Dans des récipients reliés, le liquide s'établit au même niveau."],
        ["Cite une application de ce principe.", "Le château d'eau."],
      ],
      mise: ["Comment l'eau du réservoir en haut de la colline arrive-t-elle dans toutes les maisons ?", "Par des canalisations qui descendent ; l'eau circule grâce à la gravité et au principe des vases communicants."],
      observation: "le schéma du château d'eau et les images d'irrigation et de canalisations",
      observationSupport: "Schéma : réservoir en hauteur → canalisations → maisons ; images de rigoles d'irrigation",
      qa: [
        ["Que montre le schéma ?", "Un réservoir en hauteur (château d'eau) alimenté par une source, qui distribue l'eau vers les maisons par des canalisations."],
        ["Pourquoi mettre le réservoir en hauteur ?", "Pour que l'eau descende naturellement dans toutes les maisons, sans pompe."],
        ["Comment les champs reçoivent-ils de l'eau ?", "Par des canaux, rigoles ou tuyaux qui amènent l'eau de la rivière ou du réservoir vers les parcelles (irrigation)."],
        ["Que deviennent les eaux usées et l'eau de pluie ?", "Elles sont évacuées par des canalisations vers les égouts, les fossés ou les bassins."],
      ],
      synthese: "Donc, dans les villes, l'eau du château d'eau descend par des canalisations jusqu'aux maisons grâce au principe des vases communicants et à la gravité. Dans les champs, l'eau est amenée par des canaux et des rigoles pour l'irrigation ; les eaux usées et les eaux de pluie sont évacuées par d'autres canalisations.",
      motsCles: ["distribution de l'eau", "château d'eau", "canalisations", "irrigation", "eaux usées", "gravité"],
      contenu: [
        { sousTitre: "1. La distribution dans les villes", texte: "L'eau est pompée ou captée, puis stockée dans un réservoir placé en hauteur : le château d'eau. De là, elle descend par des canalisations vers les habitations. Quand on ouvre un robinet, l'eau sort parce que le réservoir est plus haut : c'est la gravité et le principe des vases communicants." },
        { sousTitre: "2. L'irrigation des champs", texte: "L'eau de la rivière ou du réservoir est amenée aux champs par des canaux, des rigoles ou des tuyaux. Elle coule par gravité, arrose les rizières, les cultures maraîchères et les plantations. Un bon système d'irrigation économise l'eau et améliore les récoltes." },
        { sousTitre: "3. L'évacuation des eaux usées et des eaux de pluie", texte: "Les eaux usées (cuisine, toilette) et les eaux de pluie sont collectées par des canalisations et conduites vers les égouts, les fossés ou les bassins d'épuration. Cela évite l'accumulation d'eau sale et protège la santé." },
        { sousTitre: "4. Le rôle de chacun", texte: "Pour que la distribution fonctionne, il faut entretenir les canalisations, fermer les robinets, réparer les fuites et éviter de jeter des déchets dans les canaux. Économiser l'eau, c'est aussi protéger les réserves du bassin versant." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Le château d'eau est placé…", opts: ["en hauteur", "sous terre", "dans les champs"], ok: 0, expl: "L'eau doit être en hauteur pour descendre par gravité." },
          { q: "L'eau arrive aux maisons…", opts: ["par des canalisations", "par les racines", "par les sources directement"], ok: 0, expl: "Le réseau de canalisations distribue l'eau." },
          { q: "L'irrigation sert à…", opts: ["arroser les champs", "pomper l'eau de mer", "chauffer l'eau"], ok: 0, expl: "Elle apporte l'eau aux cultures." },
          { q: "Les eaux usées doivent être…", opts: ["évacuées par des canalisations", "jetées dans la cour", "bues"], ok: 0, expl: "L'évacuation protège la santé et l'environnement." },
        ]},
        { type: "vf", consigne: "Écris V si l'affirmation est vraie, F si elle est fausse.", pointsPar: 1, items: [
          { txt: "Le château d'eau utilise la gravité.", rep: true, expl: "L'eau descend du réservoir vers les maisons." },
          { txt: "L'irrigation apporte de l'eau aux cultures.", rep: true, expl: "Les canaux et rigoles arrosent les champs." },
          { txt: "Une fuite d'eau est sans importance.", rep: false, expl: "Les fuites gaspillent l'eau et endommagent le réseau." },
          { txt: "Les eaux de pluie sont toujours potables.", rep: false, expl: "Elles doivent souvent être collectées et traitées avant usage." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds par une phrase complète.", pointsPar: 2, items: [
          { q: "Explique comment l'eau arrive aux maisons.", r: "L'eau est stockée dans un château d'eau en hauteur et descend par des canalisations jusqu'aux maisons, grâce à la gravité." },
          { q: "Comment les champs sont-ils arrosés ?", r: "Les champs sont arrosés par des canaux ou rigoles qui apportent l'eau de la rivière ou du réservoir (irrigation)." },
          { q: "Pourquoi faut-il économiser l'eau ?", r: "Pour protéger les réserves du bassin versant, éviter le gaspillage et assurer l'accès à l'eau pour tous." },
        ]},
        { type: "completion", consigne: "Complète les phrases.", pointsPar: 1, items: [
          { debut: "Le réservoir en hauteur s'appelle le", suite: "château d'eau" },
          { debut: "L'eau est conduit vers les maisons par des", suite: "canalisations" },
          { debut: "L'arrosage des champs s'appelle l'", suite: "irrigation" },
        ]},
      ],
    },
  ],
};

module.exports = U;
