// Progression V2 : 47 séances V1 (ordre conservé) + 10 séances issues du guide pédagogique 8e (insérées)
// Chaque entrée : { v1: numéro V1 | null, id: clé de contenu V2, titre (V2, corrigé si besoin) }
const PROGRESSION = [
  // ---------------- TRIMESTRE 1 ----------------
  { v1: 1, id: "num10000", titre: "Les nombres jusqu'à 10 000" },
  { v1: 2, id: "addition", titre: "L'addition" },
  { v1: 3, id: "soustraction", titre: "La soustraction" },
  { v1: null, id: "pb_choisir_op", titre: "Problèmes : choisir l'opération (situations additives et soustractives)", trimestre: 1 },
  { v1: 4, id: "droites", titre: "Droite, demi-droite et segment de droite" },
  { v1: 5, id: "longueur", titre: "Les mesures de longueur (1) : instruments et conversions" },
  { v1: null, id: "longueur2", titre: "Les mesures de longueur (2) : multiples du mètre et distances" },
  { v1: 6, id: "num1000000", titre: "Les nombres jusqu'à 1 000 000 (1)" },
  { v1: 7, id: "multiplication", titre: "La multiplication" },
  { v1: 8, id: "division", titre: "La division (1) : un chiffre au diviseur" },
  { v1: null, id: "division2", titre: "La division (2) : deux chiffres au diviseur" },
  { v1: 9, id: "rectangle_carre", titre: "Le rectangle et le carré" },
  { v1: null, id: "aires_unites", titre: "Les unités d'aire et les mesures agraires" },
  { v1: 10, id: "masse", titre: "Les mesures de masse" },
  { v1: 11, id: "num1000000b", titre: "Les nombres jusqu'à 1 000 000 (2)" },
  { v1: 12, id: "decimaux", titre: "Les nombres décimaux" },
  { v1: 13, id: "decimaux_addsous", titre: "Opérations sur les nombres décimaux : addition et soustraction" },
  { v1: 14, id: "triangle", titre: "Le triangle" },
  { v1: 15, id: "paralleles", titre: "Droites parallèles, perpendiculaires et sécantes" },
  // ---------------- TRIMESTRE 2 ----------------
  { v1: 16, id: "num10000000", titre: "Les nombres jusqu'à 10 000 000" },
  { v1: 17, id: "decimaux_multdiv", titre: "Opérations sur les nombres décimaux : multiplication et division" },
  { v1: null, id: "pb_multiplicatifs", titre: "Problèmes : situations multiplicatives et de partage" },
  { v1: 18, id: "fractions", titre: "Les fractions" },
  { v1: 19, id: "echanges1", titre: "Les échanges (1) : prix d'achat, frais, prix de revient" },
  { v1: 20, id: "parallelogramme_losange", titre: "Le parallélogramme et le losange" },
  { v1: 21, id: "angles", titre: "Mesurer et comparer les angles" },
  { v1: 22, id: "capacite1", titre: "Les mesures de capacité (1) : le litre et ses sous-multiples" },
  { v1: 23, id: "num100000000", titre: "Les nombres jusqu'à 100 000 000 (1)" },
  { v1: 24, id: "fractions_comparer", titre: "Comparer et ranger des fractions" },
  { v1: 25, id: "echanges2", titre: "Les échanges (2) : prix de vente, bénéfice et perte" },
  { v1: 26, id: "trapeze", titre: "Le trapèze" },
  { v1: 27, id: "capacite2", titre: "Les mesures de capacité (2) : les multiples du litre" },
  { v1: 28, id: "num100000000b", titre: "Les nombres jusqu'à 100 000 000 (2)" },
  { v1: 29, id: "fractions_comparer2", titre: "Comparer et ranger des fractions (2)" },
  { v1: 30, id: "cercle", titre: "Le cercle et le disque" },
  { v1: 31, id: "capacite3", titre: "Les mesures de capacité (3) : problèmes" },
  // ---------------- TRIMESTRE 3 ----------------
  { v1: 32, id: "num1000000000", titre: "Les nombres jusqu'à 1 000 000 000 (1)" },
  { v1: 33, id: "budget", titre: "Le budget familial" },
  { v1: 34, id: "fractions_op", titre: "Opérations sur les fractions (1)" },
  { v1: null, id: "fractions_decimales", titre: "Les fractions décimales" },
  { v1: 35, id: "proportionnalite", titre: "La proportionnalité (1)" },
  { v1: 36, id: "pave", titre: "Le parallélépipède rectangle" },
  { v1: null, id: "temps1", titre: "La mesure du temps (1) : jour, semaine, mois, année" },
  { v1: 37, id: "temps2", titre: "Les nombres sexagésimaux et la mesure du temps (2) : heure, minute, seconde" },
  { v1: 38, id: "num1000000000b", titre: "Les nombres jusqu'à 1 000 000 000 (2)" },
  { v1: 39, id: "fractions_op2", titre: "Opérations sur les fractions (2)" },
  { v1: 40, id: "proportionnalite2", titre: "La proportionnalité (2)" },
  { v1: 41, id: "epargne1", titre: "L'épargne et le placement (1)" },
  { v1: 42, id: "cube", titre: "Le cube" },
  { v1: 43, id: "temps3", titre: "Opérations sur les nombres sexagésimaux (1)" },
  { v1: 44, id: "partages", titre: "Les partages inégaux" },
  { v1: 45, id: "epargne2", titre: "L'épargne et le placement (2)" },
  { v1: 46, id: "revision_solides", titre: "Révision : cube et parallélépipède rectangle" },
  { v1: null, id: "volume_capacite_masse", titre: "Volume, capacité et masse : 1 dm³ = 1 L = 1 kg" },
  { v1: 47, id: "temps4", titre: "Opérations sur les nombres sexagésimaux (2)" },
  { v1: null, id: "pb_synthese", titre: "Problèmes de synthèse" },
  { v1: null, id: "pb_geometrie", titre: "Problèmes de géométrie" },
];
const TRIMESTRES = [{ num: 1, de: 1, a: 19 }, { num: 2, de: 20, a: 36 }, { num: 3, de: 37, a: 57 }];
module.exports = { PROGRESSION, TRIMESTRES };
