// data-theme4.js — Unité 4 « L'école » (séances 41 à 52)
// Sources : FRA 10ème (T2 semaines 2-4 : école, sons ch, s/c, on) + PDF CP2 unité IV (12 séances).
// sd par séance : EO s41-46 & s52, Lecture s47-49, Écriture s50-51. Barème 8+6+6 = 20 partout.

const theme4 = {
 numero: 4,
 nom: "L'école",
 sousDiscipline: "Expression Orale",
 notions: "Le vocabulaire de l'école (classe, cartable, cahier, maîtresse) et les sons ch, s/c et on.",
 competences: [
  "Nommer les objets de la classe et du cartable.",
  "Demander poliment un objet : « Prête-moi..., s'il te plaît ».",
  "Reconnaître et prononcer les sons ch, s (s, c, ç) et on.",
  "Écrire des mots simples avec ch et on.",
 ],
 seances: [
  {
   n: 41,
   titre: "Le vocabulaire de la classe",
   titreFiche: "Les objets de la classe",
   sd: "Expression Orale",
   objectif: "Nommer les objets de la classe : le cahier, le crayon, la gomme, la règle, le tableau, la craie.",
   supportFiche: "Objets réels (cahier, crayon, gomme, règle), tableau noir.",
   revision: {
    ens: ["Le grand tri : cite 2 mots avec le son an (2 élèves)."],
    app: ["R.A. : ", { t: "lampe, banane, dent, canard, pantalon, maman...", r: true }, "."],
    technique: ["Question / réponse"],
   },
   miseEnSituation: {
    ens: ["« Regardez autour de vous : où sommes-nous ? » — « Qu'est-ce qui est dans notre classe ? »"],
    app: ["Répondent : nous sommes à l'école, dans la classe ; il y a des tables, des chaises, le tableau..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots de la classe : cahier, crayon, gomme, règle, tableau, craie."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Regardez bien ces objets. Qui connaît leur nom ? » Montrez chaque objet."],
    app: ["Observent et nomment : le cahier, le crayon, la gomme, la règle, le tableau, la craie."],
    technique: ["Observation guidée"],
    support: "Objets réels",
   },
   analyse: {
    ens: { paras: [["1) Avec quoi écrivons-nous dans le cahier ?"], ["2) Avec quoi efface-t-on ?"], ["3) Avec quoi trace-t-on une ligne droite ?"], ["4) Avec quoi la maîtresse écrit-elle au tableau ?"]] },
    app: { paras: [["R.A. : Le ", { t: "crayon", r: true }, "."], ["R.A. : La ", { t: "gomme", r: true }, "."], ["R.A. : La ", { t: "règle", r: true }, "."], ["R.A. : La ", { t: "craie", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Objets réels",
   },
   synthese: {
    ens: ["Donc : dans la classe, il y a le cahier, le crayon, la gomme, la règle, le tableau et la craie."],
    app: ["Répètent les 6 mots en chœur en levant chaque objet."],
    technique: ["Répétition collective"],
    support: "Objets réels",
   },
   application: {
    ens: ["Chacun votre tour : montrez un objet de la classe et dites son nom."],
    app: ["Montrent et disent : « C'est le cahier », « C'est la règle »..."],
    technique: ["Chaîne parlée"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : je nomme un objet, vous le montrez et le nommez."],
    app: ["R.A. : ", { t: "cahier, crayon, gomme, règle, tableau, craie", r: true }, " (3 mots corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "41. LE VOCABULAIRE DE LA CLASSE",
    subs: [
     { t: "A. Les objets de la classe", paras: [[{ t: "le cahier", k: true }, " — ", { t: "le crayon", k: true }, " — ", { t: "la gomme", k: true }, " — ", { t: "la règle", k: true }, " — ", { t: "le tableau", k: true }, " — ", { t: "la craie", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "J'écris dans mon cahier avec mon crayon.", k: true }, " »"]] },
    ],
    retenir: ["Dans ma classe : ", { t: "le cahier, le crayon, la gomme, la règle, le tableau, la craie", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les objets de la classe :"], items: [["le cahier"], ["le savon"], ["le crayon"], ["la serviette"], ["la gomme"], ["le canard"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) J'écris avec mon ....... (crayon)"], ["2) J'efface avec ma ....... (gomme)"], ["3) La maîtresse écrit avec la ....... (craie)"], ["4) Je trace une ligne avec ma ....... (règle)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène : demande poliment un crayon à ton camarade."], items: [["1) « S'il te plaît, ....... -moi ton crayon. » (prête)"], ["2) « Voilà, merci ! » — Tu réponds : ....... (« de rien »)"], ["3) Comment appelle-t-on la personne qui enseigne ? ....... (la maîtresse)"], ["4) Où écris-tu ? Dans mon ....... (cahier)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Objets entourés : ", { t: "le cahier, le crayon, la gomme", r: true }, " (2 pts chacun) — savon, serviette (toilette) et canard (animal) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "crayon", r: true }, " — 2) ", { t: "gomme", r: true }, " — 3) ", { t: "craie", r: true }, " — 4) ", { t: "règle", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "prête", r: true }, " — 2) ", { t: "de rien", r: true }, " — 3) ", { t: "la maîtresse", r: true }, " — 4) ", { t: "cahier", r: true }, "."]] },
   ],
  },
  {
   n: 42,
   titre: "Mon cartable",
   titreFiche: "Qu'est-ce qu'il y a dans mon cartable ?",
   sd: "Expression Orale",
   objectif: "Nommer le cartable et son contenu : « Dans mon cartable, il y a... ».",
   supportFiche: "Cartable réel ou image « le cartable », tableau noir.",
   revision: {
    ens: ["Montre et nomme 3 objets de la classe (chaîne parlée)."],
    app: ["R.A. : ", { t: "le cahier, le crayon, la gomme...", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Ouvrez votre cartable (ou regardez le mien). Qu'est-ce qu'il y a dedans ? »"],
    app: ["Proposent : le cahier, le crayon, la gomme, la règle, la boîte à images..."],
    technique: ["Question ouverte"],
    support: "Cartable réel",
   },
   presentation: {
    ens: ["Aujourd'hui, nous disons ce qu'il y a dans notre cartable : « Dans mon cartable, il y a... »"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez ce cartable : » je sors les objets un à un, les élèves les nomment."],
    app: ["Observent et nomment : un cahier, deux crayons, une gomme, une règle."],
    technique: ["Observation guidée"],
    support: "Cartable réel",
   },
   analyse: {
    ens: { paras: [["1) Où rangeons-nous nos cahiers ?"], ["2) Combien de crayons as-tu ?"], ["3) Que mets-tu d'autre dans ton cartable ?"], ["4) Où est ton cartable à la maison ?"]] },
    app: { paras: [["R.A. : Dans le ", { t: "cartable", r: true }, "."], ["R.A. : ", { t: "Un / deux...", r: true }, " (réponse personnelle)."], ["R.A. : Ma ", { t: "gomme, ma règle, ma boîte à images...", r: true }, "."], ["R.A. : ", { t: "Sous mon lit, sur une chaise...", r: true }, " (réponse personnelle)."]] },
    technique: ["Question / réponse"],
    support: "Cartable, image « le cartable »",
   },
   synthese: {
    ens: ["Donc : mon cartable — « Dans mon cartable, il y a mon cahier, mon crayon, ma gomme et ma règle. »"],
    app: ["Répètent la phrase complète en chœur, puis chacun la dit avec ses objets."],
    technique: ["Répétition collective"],
    support: "Cartable",
   },
   application: {
    ens: ["Le jeu du cartable magique : un objet est caché, retrouvez lequel manque !"],
    app: ["Observeront 4 objets, fermeront les yeux, devineront l'objet caché et le nommeront."],
    technique: ["Jeu de mémoire"],
    support: "Objets réels",
   },
   evaluation: {
    ens: ["3 élèves : dis 2 objets de ton cartable."],
    app: ["R.A. : ", { t: "mon cahier, mon crayon, ma gomme, ma règle", r: true }, " (2 corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "42. MON CARTABLE",
    subs: [
     { t: "A. Ma phrase", paras: [["« ", { t: "Dans mon cartable, il y a mon cahier, mon crayon, ma gomme et ma règle.", k: true }, " »"]] },
     { t: "B. Le jeu", paras: [["« ", { t: "Qu'est-ce qui manque ?", k: true }, " » : je retrouve l'objet caché !"]] },
    ],
    retenir: ["« Dans mon ", { t: "cartable", k: true }, ", il y a mon ", { t: "cahier, mon crayon, ma gomme et ma règle", k: true }, ". »"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les mots dans la phrase (écoute et numérote) :"], items: [["....... cartable"], ["....... cahier"], ["....... crayon"], ["....... gomme"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète : « Dans mon cartable, il y a... »"], items: [["1) mon ....... (cahier)"], ["2) mon ....... (crayon)"], ["3) ma ....... (gomme)"], ["4) ma ....... (règle)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Jeu : que manque-t-il ? (la maîtresse cache un objet, 4 tours)"], items: [["1) Tour 1 : l'objet caché : ....... (réponse libre : le crayon)"], ["2) Tour 2 : l'objet caché : ....... (la gomme)"], ["3) Tour 3 : l'objet caché : ....... (le cahier)"], ["4) Tour 4 : l'objet caché : ....... (la règle)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre écouté et numéroté : ", { t: "1 cartable — 2 cahier — 3 crayon — 4 gomme", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "cahier", r: true }, " — 2) ", { t: "crayon", r: true }, " — 3) ", { t: "gomme", r: true }, " — 4) ", { t: "règle", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Réponses du jeu : ", { t: "les objets cachés correctement nommés", r: true }, " (1,5 pt par tour)."]] },
   ],
  },
  {
   n: 43,
   titre: "Le dialogue : prête-moi...",
   titreFiche: "Demander poliment un objet",
   sd: "Expression Orale",
   objectif: "Jouer un dialogue de classe : « Prête-moi ta gomme, s'il te plaît. — Tiens, merci ! ».",
   supportFiche: "Objets réels, tableau noir.",
   revision: {
    ens: ["Dis ta phrase du cartable (2 élèves)."],
    app: ["R.A. : « ", { t: "Dans mon cartable, il y a...", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Ta gomme est perdue. Que dis-tu à ton camarade ? »"],
    app: ["Proposent : il me prête sa gomme, je dis s'il vous plaît..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous jouons le dialogue du prêt d'objet en classe."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez le dialogue : » je le joue avec un élève."],
    app: ["Écoutent : « — Prête-moi ta règle, s'il te plaît. — Tiens ! — Merci ! — De rien. »"],
    technique: ["Écoute active"],
    support: "Objets réels",
   },
   analyse: {
    ens: { paras: [["1) Que demande le premier élève ?"], ["2) Que dit-il pour être poli ?"], ["3) Que répond le camarade quand il donne ?"], ["4) Que dit-on après « merci » ?"]] },
    app: { paras: [["R.A. : ", { t: "Prête-moi ta règle", r: true }, "."], ["R.A. : ", { t: "S'il te plaît", r: true }, "."], ["R.A. : ", { t: "Tiens !", r: true }, "."], ["R.A. : ", { t: "De rien", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : « Prête-moi..., s'il te plaît. — Tiens ! — Merci ! — De rien. » : les mots polis de la classe."],
    app: ["Répètent les répliques par moitiés de classe avec les gestes."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Par 2 : jouez le dialogue avec 2 objets différents, puis échangez les rôles."],
    app: ["Jouent : crayon, gomme, cahier... ; 2 binômes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Objets réels",
   },
   evaluation: {
    ens: ["1 binôme : jouez le dialogue complet."],
    app: ["R.A. : répliques correctes : ", { t: "« Prête-moi..., s'il te plaît. — Tiens ! — Merci ! »", r: true }, "."],
    technique: ["Binôme"],
   },
   lecon: {
    titre: "43. LE DIALOGUE : PRÊTE-MOI...",
    subs: [
     { t: "A. Le dialogue", paras: [["« — ", { t: "Prête-moi ta règle, s'il te plaît.", k: true }, " — ", { t: "Tiens !", k: true }, " »"], ["« — ", { t: "Merci !", k: true }, " — ", { t: "De rien.", k: true }, " »"]] },
    ],
    retenir: ["Les mots polis de la classe : ", { t: "s'il te plaît — tiens — merci — de rien", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les répliques dans l'ordre (1, 2, 3, 4) :"], items: [["....... — Merci !"], ["....... — Prête-moi ta gomme, s'il te plaît."], ["....... — De rien."], ["....... — Tiens !"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète le dialogue :"], items: [["1) « ....... -moi ton crayon. » (prête)"], ["2) « S'il te ....... ! » (plaît)"], ["3) « ....... ! » (en donnant : tiens)"], ["4) « Merci ! » — « De ....... » (rien)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue avec ton camarade (demande puis donne) :"], items: [["1) Demande la gomme : ....... (« Prête-moi ta gomme, s'il te plaît. »)"], ["2) Donne-la en disant : ....... (« Tiens ! »)"], ["3) Remercie : ....... (« Merci ! »)"], ["4) Réponds : ....... (« De rien. »)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "3 — 1 — 4 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "prête", r: true }, " — 2) ", { t: "plaît", r: true }, " — 3) ", { t: "tiens", r: true }, " — 4) ", { t: "rien", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "« Prête-moi ta gomme, s'il te plaît. »", r: true }, " — 2) ", { t: "« Tiens ! »", r: true }, " — 3) ", { t: "« Merci ! »", r: true }, " — 4) ", { t: "« De rien. »", r: true }, "."]] },
   ],
  },
  {
   n: 44,
   titre: "Qu'est-ce que c'est ?",
   titreFiche: "Je questionne et je réponds",
   sd: "Expression Orale",
   objectif: "Poser la question « Qu'est-ce que c'est ? » et répondre « C'est... » avec un objet de classe.",
   supportFiche: "Objets réels ou image « la classe », tableau noir.",
   revision: {
    ens: ["Jouez le dialogue du prêt d'objet (1 binôme)."],
    app: ["R.A. : ", { t: "« Prête-moi..., s'il te plaît. — Tiens ! — Merci ! »", r: true }, "."],
    technique: ["Binôme"],
   },
   miseEnSituation: {
    ens: ["« Je cache un objet derrière mon dos : qu'est-ce que c'est ? »"],
    app: ["Devinent : c'est le crayon ! c'est la gomme !..."],
    technique: ["Jeu de devinettes"],
    support: "Objets réels",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons à questionner : « Qu'est-ce que c'est ? » et à répondre : « C'est... »"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » je montre un objet, je pose la question, un élève répond ; on répète avec 3 objets."],
    app: ["Observent le modèle : « Qu'est-ce que c'est ? — C'est le cahier. »"],
    technique: ["Observation guidée"],
    support: "Objets réels",
   },
   analyse: {
    ens: { paras: [["1) Comment pose-t-on la question pour un objet ?"], ["2) Comment répond-on ?"], ["3) Ma voix monte-t-elle ou descend-elle à la fin de la question ?"], ["4) Et pour une personne, que demande-t-on ?"]] },
    app: { paras: [["R.A. : « ", { t: "Qu'est-ce que c'est ?", r: true }, " »"], ["R.A. : « ", { t: "C'est...", r: true }, " » + le nom."], ["R.A. : Ma voix ", { t: "monte", r: true }, "."], ["R.A. : « ", { t: "Qui est-ce ?", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : objet → « Qu'est-ce que c'est ? — C'est... » ; personne → « Qui est-ce ? — C'est... »."],
    app: ["Répètent les deux questions en chœur, avec le geste de la voix qui monte."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Par 2 : l'un montre un objet et questionne, l'autre répond ; puis on échange."],
    app: ["Jouent 4 objets chacun ; je corrige l'intonation."],
    technique: ["Travail en binômes"],
    support: "Objets réels",
   },
   evaluation: {
    ens: ["3 élèves : pose la question et réponds pour cet objet."],
    app: ["R.A. : « ", { t: "Qu'est-ce que c'est ? — C'est la règle.", r: true }, " » (objet correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "44. QU'EST-CE QUE C'EST ?",
    subs: [
     { t: "A. La question et la réponse", paras: [["« — ", { t: "Qu'est-ce que c'est ?", k: true }, " — ", { t: "C'est le cahier.", k: true }, " » : ma voix ", { t: "monte", k: true }, " !"]] },
     { t: "B. Objet ou personne", paras: [["Objet : « ", { t: "Qu'est-ce que c'est ?", k: true }, " » — personne : « ", { t: "Qui est-ce ?", k: true }, " ». Réponse : « ", { t: "C'est...", k: true }, " »"]] },
    ],
    retenir: ["Objet : « ", { t: "Qu'est-ce que c'est ? — C'est...", k: true }, " » — personne : « ", { t: "Qui est-ce ? — C'est...", k: true }, " »."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Choisis la bonne question (dis-la) :"], items: [["1) Un crayon : Qu'est-ce que c'est ? / Qui est-ce ?"], ["2) Ta maîtresse : Qu'est-ce que c'est ? / Qui est-ce ?"], ["3) Une gomme : Qu'est-ce que c'est ? / Qui est-ce ?"], ["4) Ton camarade : Qu'est-ce que c'est ? / Qui est-ce ?"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) « — ....... que c'est ? — C'est la craie. » (qu'est-ce)"], ["2) « — Qui est-....... ? — C'est Koto. » (ce)"], ["3) « — C'est la ....... : j'efface avec ! » (gomme)"], ["4) « — Ma voix ....... à la fin de la question. » (monte)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Jeu : cache un objet, ton camarade questionne et devine (4 tours) :"], items: [["1) Tour 1 : la question : ....... ; la réponse : ......."], ["2) Tour 2 : la question : ....... ; la réponse : ......."], ["3) Tour 3 : la question : ....... ; la réponse : ......."], ["4) Tour 4 : la question : ....... ; la réponse : ......."]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "Qu'est-ce que c'est ?", r: true }, " — 2) ", { t: "Qui est-ce ?", r: true }, " — 3) ", { t: "Qu'est-ce que c'est ?", r: true }, " — 4) ", { t: "Qui est-ce ?", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "qu'est-ce", r: true }, " — 2) ", { t: "ce", r: true }, " — 3) ", { t: "gomme", r: true }, " — 4) ", { t: "monte", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Chaque tour : « ", { t: "Qu'est-ce que c'est ? — C'est...", r: true }, " » (objet correct)."]] },
   ],
  },
  {
   n: 45,
   titre: "La comptine de l'école",
   titreFiche: "Ma comptine : à l'école j'apprends",
   sd: "Expression Orale",
   objectif: "Réciter la comptine de l'école avec les gestes.",
   supportFiche: "Comptine au tableau, image « la classe ».",
   revision: {
    ens: ["Question-réponse rapide : je montre 3 objets, vous dites « C'est... »."],
    app: ["R.A. : ", { t: "C'est le cahier / la gomme / la règle.", r: true }, "."],
    technique: ["Répétition collective"],
   },
   miseEnSituation: {
    ens: ["« La famille, la toilette ont leurs comptines... Et l'école alors ? »"],
    app: ["Écoutent, curieux."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons la comptine de l'école."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez : » je récite deux fois avec les gestes."],
    app: ["Écoutent : « Cahier, crayon, gomme et règle, / dans ma classe j'apprends mon rôle : / je lis, j'écris, je compte aussi, / à l'école j'apprends, c'est ainsi ! »"],
    technique: ["Écoute active"],
    support: "Comptine au tableau",
   },
   analyse: {
    ens: { paras: [["1) Cite les 4 objets de la comptine."], ["2) Que fait l'élève dans la comptine ?"], ["3) Où apprend-il ?"], ["4) Répète le dernier vers."]] },
    app: { paras: [["R.A. : ", { t: "cahier, crayon, gomme, règle", r: true }, "."], ["R.A. : Il lit, il écrit, il ", { t: "compte", r: true }, "."], ["R.A. : À ", { t: "l'école", r: true }, ", dans sa classe."], ["R.A. : ", { t: "À l'école j'apprends, c'est ainsi !", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Comptine au tableau",
   },
   synthese: {
    ens: ["Donc : ma comptine — à l'école, je lis, j'écris, je compte : j'apprends !"],
    app: ["Répètent les 4 vers ligne par ligne avec les gestes."],
    technique: ["Répétition collective"],
    support: "Comptine au tableau",
   },
   application: {
    ens: ["Par 2 : récite la comptine avec les gestes."],
    app: ["Récitent en binômes ; 2 groupes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Comptine au tableau",
   },
   evaluation: {
    ens: ["2 élèves : récite la comptine."],
    app: ["R.A. : au moins 3 vers corrects : ", { t: "cahier-crayon-gomme-règle / je lis, j'écris, je compte / j'apprends", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "45. LA COMPTINE DE L'ÉCOLE",
    subs: [
     { t: "A. La comptine", paras: [["« ", { t: "Cahier, crayon, gomme et règle,", k: true }, " » — « ", { t: "dans ma classe j'apprends mon rôle :", k: true }, " »"], ["« ", { t: "je lis, j'écris, je compte aussi,", k: true }, " » — « ", { t: "à l'école j'apprends, c'est ainsi !", k: true }, " »"]] },
    ],
    retenir: ["Ma comptine : « ", { t: "À l'école j'apprends, c'est ainsi !", k: true }, " » — je la connais par cœur !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les vers dans l'ordre (1, 2, 3, 4) :"], items: [["....... à l'école j'apprends, c'est ainsi !"], ["....... Cahier, crayon, gomme et règle,"], ["....... je lis, j'écris, je compte aussi,"], ["....... dans ma classe j'apprends mon rôle :"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la comptine :"], items: [["1) Cahier, ......., gomme et règle (crayon)"], ["2) Dans ma ....... j'apprends mon rôle (classe)"], ["3) Je lis, ......., je compte aussi (j'écris)"], ["4) À l'....... j'apprends (école)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Récite avec les gestes (2 élèves, 2 vers chacun) :"], items: [["1) Vers 1 : montre tes ....... (4 objets : cahier, crayon, gomme, règle)"], ["2) Vers 2 : pointe la ....... (classe)"], ["3) Vers 3 : mime ......., écrire, compter (lire)"], ["4) Vers 4 : le pouce levé : ....... (j'apprends)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "4 — 1 — 3 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "crayon", r: true }, " — 2) ", { t: "classe", r: true }, " — 3) ", { t: "j'écris", r: true }, " — 4) ", { t: "école", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Gestes corrects : ", { t: "objets, classe, lire, j'apprends", r: true }, "."]] },
   ],
  },
  {
   n: 46,
   titre: "Qu'y a-t-il dans ma classe ?",
   titreFiche: "Énumérer : je fais ma liste",
   sd: "Expression Orale",
   objectif: "Énumérer plusieurs objets : « Dans ma classe, il y a..., ..., et... ».",
   supportFiche: "Image « la classe », tableau noir.",
   revision: {
    ens: ["Récite ta comptine de l'école (2 élèves)."],
    app: ["R.A. : les 4 vers de la ", { t: "comptine", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Dans ma famille, il y a... : vous connaissez ! Et dans ma classe, qu'y a-t-il ? »"],
    app: ["Proposent : les tables, les chaises, le tableau, les élèves, la maîtresse..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous faisons notre liste : « Dans ma classe, il y a..., ..., et... »"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez l'image de la classe et écoutez ma liste : » je nomme 5 choses en les montrant."],
    app: ["Observent : dans ma classe, il y a le tableau, les tables, les chaises, les livres et mes camarades."],
    technique: ["Observation guidée"],
    support: "Image « la classe »",
   },
   analyse: {
    ens: { paras: [["1) Avec quel mot commence ma liste ?"], ["2) Quel mot se répète entre chaque chose ?"], ["3) Avant la dernière chose, quel mot utilise-t-on ?"], ["4) Ajoute une chose à ma liste."]] },
    app: { paras: [["R.A. : « ", { t: "Dans ma classe, il y a...", r: true }, " »"], ["R.A. : ", { t: "il y a", r: true }, "."], ["R.A. : ", { t: "Et", r: true }, "."], ["R.A. : ", { t: "le porte-plume, la carte...", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Image « la classe »",
   },
   synthese: {
    ens: ["Donc : pour énumérer — « Dans ma classe, il y a..., ..., et... » : je fais ma liste sans oublier « et »."],
    app: ["Répètent le modèle de liste en chœur, puis ajoutent chacun un mot."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Chacun votre tour : fais ta liste de 3 choses de la classe."],
    app: ["Disent leur liste complète (avec « il y a » et « et »)."],
    technique: ["Chaîne parlée"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : liste de 3 objets du cartable ou de la classe."],
    app: ["R.A. : liste correcte avec ", { t: "« il y a » et « et »", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "46. QU'Y A-T-IL DANS MA CLASSE ?",
    subs: [
     { t: "A. Ma liste", paras: [["« ", { t: "Dans ma classe, il y a le tableau, les tables, les chaises et mes camarades.", k: true }, " »"]] },
     { t: "B. Le secret de la liste", paras: [["Je répète ", { t: "il y a", k: true }, " et je termine avec ", { t: "et", k: true }, " !"]] },
    ],
    retenir: ["Je fais ma liste : « ", { t: "Dans ma classe, il y a..., ..., et...", k: true }, " »."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écoute la liste et coche les objets entendus :"], items: [["1) le tableau : oui / non"], ["2) le savon : oui / non"], ["3) les chaises : oui / non"], ["4) le canard : oui / non"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la liste :"], items: [["1) Dans ma ......., il y a le tableau (classe)"], ["2) Il ....... les tables (y a)"], ["3) Il y a les ....... (chaises)"], ["4) ....... mes camarades (et)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Fais ta liste (3 choses de la classe) :"], items: [["1) Première chose : ....... (libre : le tableau)"], ["2) Deuxième chose : ....... (les tables)"], ["3) Troisième chose avec « et » : ....... (et les chaises)"], ["4) Ton mot magique au début : ....... (« Dans ma classe, il y a »)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entendus : ", { t: "le tableau et les chaises (oui)", r: true }, " — savon et canard (non)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "classe", r: true }, " — 2) ", { t: "y a", r: true }, " — 3) ", { t: "chaises", r: true }, " — 4) ", { t: "et", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Liste personnelle correcte : ", { t: "« il y a » au début, « et » avant la dernière chose", r: true }, "."]] },
   ],
  },
  {
   n: 47,
   titre: "Le son ch — découverte",
   titreFiche: "Je découvre le son ch",
   sd: "Lecture",
   objectif: "Reconnaître et prononcer le son ch dans des mots connus.",
   supportFiche: "Image « le son ch », étiquettes mots, tableau noir.",
   revision: {
    ens: ["Fais ta liste de la classe (2 élèves)."],
    app: ["R.A. : « ", { t: "Dans ma classe, il y a..., ..., et...", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Répétez après moi : ch, ch, ch... comme la machine à vapeur : tchouuu ! »"],
    app: ["Répètent le son ch en poussant les lèvres en avant : ch, ch, ch !"],
    technique: ["Répétition articulée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son ch : chat, chapeau, chaussure, mouche."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Image « le son ch »",
   },
   observation: {
    ens: ["« Observez les images et écoutez : le CHAT, le CHAPEAU, la MOUCHE. Entendez-vous ch ? »"],
    app: ["Observent et entendent ch au début (chat, chapeau) et à la fin (mouche)."],
    technique: ["Observation guidée"],
    support: "Image « le son ch »",
   },
   analyse: {
    ens: { paras: [["1) Pousse tes lèvres : quel son entends-tu dans « chat » ?"], ["2) Où est le son ch dans « mouche » : au début ou à la fin ?"], ["3) Avec combien de lettres écrit-on ch ?"], ["4) Cite un animal avec le son ch."]] },
    app: { paras: [["R.A. : Le son ", { t: "ch", r: true }, "."], ["R.A. : À ", { t: "la fin", r: true }, " (mou-che)."], ["R.A. : ", { t: "Deux lettres : c et h", r: true }, "."], ["R.A. : Le ", { t: "chat", r: true }, " (réponses libres)."]] },
    technique: ["Question / réponse"],
    support: "Image « le son ch », étiquettes",
   },
   synthese: {
    ens: ["Donc : le son ch s'entend dans chat, chapeau, chaussure, mouche — deux lettres c-h, lèvres en avant !"],
    app: ["Répètent les 4 mots en chœur avec le geste des lèvres."],
    technique: ["Répétition collective"],
    support: "Image « le son ch »",
   },
   application: {
    ens: ["Le jeu du tam-tam : je dis des mots, vous frappez des mains quand vous entendez ch."],
    app: ["Frappent : chat, chapeau, mouche, chaussure ; ne frappent pas : papa, savon, jupe."],
    technique: ["Jeu d'écoute"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : prononce « chat, chapeau, mouche » avec le son ch bien fort."],
    app: ["R.A. : ", { t: "chat, chapeau, mouche", r: true }, " (son ch correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "47. LE SON CH",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "ch", k: true }, " s'écrit avec ", { t: "deux lettres : c-h", k: true }, " — lèvres en avant !"]] },
     { t: "B. Les mots", paras: [[{ t: "le chat", k: true }, " — ", { t: "le chapeau", k: true }, " — ", { t: "la chaussure", k: true }, " — ", { t: "la mouche", k: true }]] },
    ],
    retenir: ["Le son ", { t: "ch", k: true }, " : ", { t: "chat, chapeau, chaussure, mouche", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son ch :"], items: [["chat"], ["papa"], ["chapeau"], ["savon"], ["mouche"], ["jupe"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entends-tu ch ? Dis oui ou non :"], items: [["1) chaussure : oui / non"], ["2) banane : oui / non"], ["3) mouche : oui / non"], ["4) tortue : oui / non"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Répète avec les lèvres en avant :"], items: [["1) ch... ch... — ....... (chat)"], ["2) ch... ch... — ....... (chapeau)"], ["3) ch... ch... — ....... (chaussure)"], ["4) mou... — ....... (mouche)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "chat, chapeau, mouche", r: true }, " (2 pts chacun) — papa, savon, jupe : pas de ch."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oui", r: true }, " — 2) ", { t: "non", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "non", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Prononciation correcte : ", { t: "chat, chapeau, chaussure, mouche", r: true }, "."]] },
   ],
  },
  {
   n: 48,
   titre: "Le son s : s, c, ç",
   titreFiche: "Le son s s'écrit s, c ou ç",
   sd: "Lecture",
   objectif: "Lire des mots avec le son s écrit s (salade), c (citron) et ç (garçon).",
   supportFiche: "Étiquettes mots, image « le marché » (fruits), tableau noir.",
   revision: {
    ens: ["Cite 2 mots avec le son ch (chaîne parlée)."],
    app: ["R.A. : ", { t: "chat, chapeau, chaussure, mouche...", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Salade, citron, garçon : ces mots ont le même son au début ou au milieu. Lequel ? »"],
    app: ["Écoutent et repèrent le son sss : le son s !"],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son s : il s'écrit s (salade), c (citron) et ç (garçon)."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Étiquettes mots",
   },
   observation: {
    ens: ["« Observez les étiquettes : » montre les mots un à un ; les élèves lisent, puis ensemble."],
    app: ["Lisent : la salade, le radis, le citron, le garçon ; ils repèrent s, c, ç."],
    technique: ["Lecture individuelle puis collective"],
    support: "Étiquettes mots",
   },
   analyse: {
    ens: { paras: [["1) Quelle lettre écrit le son s dans « salade » ?"], ["2) Quelle lettre l'écrit dans « citron » ?"], ["3) Et dans « garçon », que remarques-tu sous le c ?"], ["4) Dis un mot de la classe avec le son s."]] },
    app: { paras: [["R.A. : La lettre ", { t: "s", r: true }, "."], ["R.A. : La lettre ", { t: "c", r: true }, " (devant i)."], ["R.A. : Une ", { t: "petite queue : ç", r: true }, "."], ["R.A. : ", { t: "la classe, le savon...", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Étiquettes mots",
   },
   synthese: {
    ens: ["Donc : le son s s'écrit s (salade, radis), c devant i ou e (citron) et ç (garçon) — même son !"],
    app: ["Relisent les 4 mots en montrant s, c ou ç avec le doigt."],
    technique: ["Répétition collective"],
    support: "Étiquettes mots",
   },
   application: {
    ens: ["Par 2 : lisez les étiquettes chacun votre tour ; ton camarade vérifie le son sss."],
    app: ["Lisent les 4 mots en binômes."],
    technique: ["Travail en binômes"],
    support: "Étiquettes mots",
   },
   evaluation: {
    ens: ["3 élèves : lis 2 étiquettes au choix."],
    app: ["R.A. : lecture correcte : ", { t: "salade, radis, citron, garçon", r: true }, " (au moins 2)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "48. LE SON S : S, C, Ç",
    subs: [
     { t: "A. Trois écritures, un seul son", paras: [[{ t: "s", k: true }, " : ", { t: "salade, radis", k: true }, " — ", { t: "c", k: true }, " devant i : ", { t: "citron", k: true }, " — ", { t: "ç", k: true }, " : ", { t: "garçon", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Le garçon mange une salade.", k: true }, " » (trois fois le son s !)"]] },
    ],
    retenir: ["Le son ", { t: "s", k: true }, " s'écrit ", { t: "s, c (devant i, e) ou ç", k: true }, " : même son !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son s :"], items: [["salade"], ["chat"], ["citron"], ["jupe"], ["garçon"], ["radis"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Comment s'écrit le son s ? Choisis s, c ou ç :"], items: [["1) la ...alade (s)"], ["2) le ...itron (c)"], ["3) le gar?on (ç)"], ["4) le radi... (s)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis les mots à ton camarade (4 mots) :"], items: [["1) la salade"], ["2) le radis"], ["3) le citron"], ["4) le garçon"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "salade, citron, garçon, radis", r: true }, " (2 pts chacun) — chat (ch) et jupe (u) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "s", r: true }, " — 2) ", { t: "c", r: true }, " — 3) ", { t: "ç", r: true }, " — 4) ", { t: "s", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Lecture correcte : ", { t: "salade, radis, citron, garçon", r: true }, "."]] },
   ],
  },
  {
   n: 49,
   titre: "Le son on — découverte",
   titreFiche: "Je découvre le son on",
   sd: "Lecture",
   objectif: "Reconnaître et prononcer le son on dans des mots connus.",
   supportFiche: "Image « le son on », étiquettes mots, tableau noir.",
   revision: {
    ens: ["Lis ces 2 mots : citron, garçon (2 élèves)."],
    app: ["R.A. : ", { t: "citron, garçon", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Répétez : on, on, on... comme quand vous êtes étonnés : on ! »"],
    app: ["Répètent le son on : bouche ronde."],
    technique: ["Répétition articulée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son on : maison, ballon, bonbon, pantalon, mouton."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Image « le son on »",
   },
   observation: {
    ens: ["« Observez les images et écoutez : la MAISON, le BALLON, le PANTALON. Entendez-vous on ? »"],
    app: ["Observent et entendent on à la fin de chaque mot ; ils le répètent."],
    technique: ["Observation guidée"],
    support: "Image « le son on »",
   },
   analyse: {
    ens: { paras: [["1) Fais ta bouche ronde : quel son entends-tu dans « ballon » ?"], ["2) Où est le son on dans ces mots : au début, au milieu ou à la fin ?"], ["3) Avec quelles lettres écrit-on on ?"], ["4) Cite un mot avec on."]] },
    app: { paras: [["R.A. : Le son ", { t: "on", r: true }, "."], ["R.A. : À ", { t: "la fin", r: true }, " (bal-lon)."], ["R.A. : ", { t: "O et n", r: true }, "."], ["R.A. : ", { t: "bonbon, mouton, maison...", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Image « le son on », étiquettes",
   },
   synthese: {
    ens: ["Donc : le son on s'entend dans maison, ballon, bonbon, pantalon, mouton — souvent à la fin, bouche ronde !"],
    app: ["Répètent les 5 mots en chœur en rond avec les mains (ronde)."],
    technique: ["Répétition collective"],
    support: "Image « le son on »",
   },
   application: {
    ens: ["Le jeu du tam-tam : frappez des mains quand vous entendez on."],
    app: ["Frappent : ballon, maison, bonbon ; ne frappent pas : chat, papa, gomme."],
    technique: ["Jeu d'écoute"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : prononce « maison, ballon, pantalon » avec le son on bien rond."],
    app: ["R.A. : ", { t: "maison, ballon, pantalon", r: true }, " (son on correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "49. LE SON ON",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "on", k: true }, " s'écrit avec ", { t: "o et n", k: true }, " — bouche ronde !"]] },
     { t: "B. Les mots", paras: [[{ t: "la maison", k: true }, " — ", { t: "le ballon", k: true }, " — ", { t: "le bonbon", k: true }, " — ", { t: "le pantalon", k: true }, " — ", { t: "le mouton", k: true }]] },
    ],
    retenir: ["Le son ", { t: "on", k: true }, " : ", { t: "maison, ballon, bonbon, pantalon, mouton", k: true }, " — souvent à la fin !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son on :"], items: [["maison"], ["chat"], ["ballon"], ["gomme"], ["bonbon"], ["salade"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entends-tu on ? Dis oui ou non :"], items: [["1) pantalon : oui / non"], ["2) tortue : oui / non"], ["3) mouton : oui / non"], ["4) citron : oui / non"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Répète avec la bouche ronde :"], items: [["1) on... on... — ....... (maison)"], ["2) on... on... — ....... (ballon)"], ["3) on... on... — ....... (bonbon)"], ["4) on... on... — ....... (pantalon)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "maison, ballon, bonbon", r: true }, " (2 pts chacun) — chat, gomme, salade : pas de on."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oui", r: true }, " — 2) ", { t: "non", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "oui", r: true }, " (citron : on à la fin !)."]] },
    { titre: "Exercice 3", lines: [["Prononciation correcte : ", { t: "maison, ballon, bonbon, pantalon", r: true }, "."]] },
   ],
  },
  {
   n: 50,
   titre: "Écrire ch",
   titreFiche: "J'écris les mots avec ch",
   sd: "Expression Écrite",
   objectif: "Écrire des mots simples avec ch : chat, chapeau, mouche.",
   supportFiche: "Tableau noir, ardoises, cahiers.",
   revision: {
    ens: ["Cite 2 mots avec on (chaîne parlée)."],
    app: ["R.A. : ", { t: "maison, ballon, bonbon...", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Nous savons dire ch ; maintenant nous allons l'ÉCRIRE. Avec quelles lettres ? »"],
    app: ["Proposent : avec c et h."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons le son ch : d'abord le c, puis le h — ch."],
    app: ["Écoutent et observent l'écriture au tableau."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » j'écris ch en l'air, puis au tableau : d'abord la lettre c, puis la lettre h."],
    app: ["Observent le geste : c-h = ch ; ils le tracent dans l'air avec le doigt."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Quelles lettres écrivent le son ch ?"], ["2) Écris « chat » sur ton ardoise : où est ch ?"], ["3) Écris « chapeau » : vérifie le ch !"], ["4) Qui peut écrire « mouche » ?"]] },
    app: { paras: [["R.A. : ", { t: "c et h", r: true }, "."], ["R.A. : Au ", { t: "début", r: true }, " : ", { t: "chat", r: true }, "."], ["R.A. : ", { t: "chapeau", r: true }, " : c-h bien collés."], ["R.A. : mou-", { t: "ch", r: true }, "-e : ", { t: "mouche", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Ardoises",
   },
   synthese: {
    ens: ["Donc : le son ch s'écrit avec c et h : chat, chapeau, mouche."],
    app: ["Répètent en écrivant dans l'air : ch, ch, ch."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Sur ton ardoise, écris : chat, chapeau ; vérifie avec le tableau."],
    app: ["Écrivent sur ardoise, comparent, corrigent."],
    technique: ["Écriture individuelle"],
    support: "Ardoises",
   },
   evaluation: {
    ens: ["2 élèves : écris « chat » au tableau."],
    app: ["R.A. : ", { t: "chat", r: true }, " bien écrit (c-h)."],
    technique: ["Individuel écrit"],
   },
   lecon: {
    titre: "50. ÉCRIRE CH",
    subs: [
     { t: "A. Les lettres", paras: [[{ t: "ch", k: true }, " : d'abord ", { t: "c", k: true }, ", puis ", { t: "h", k: true }, " — lèvres en avant pour le dire !"]] },
     { t: "B. La dictée", paras: [["J'écris : ", { t: "chat, chapeau, mouche", k: true }, " sans oublier le ch !"]] },
    ],
    retenir: ["J'écris le son ", { t: "ch", k: true }, " avec ", { t: "c et h", k: true }, " : chat, chapeau, mouche."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris le mot qui manque (copie depuis le tableau) :"], items: [["1) le ....... (chat)"], ["2) le ....... (chapeau)"], ["3) la ....... (chaussure)"], ["4) la ....... (mouche)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entoure ch dans ces mots :"], items: [["1) chat"], ["2) chapeau"], ["3) chaussure"], ["4) mouche"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Petite dictée sur le cahier (4 mots) :"], items: [["1) chat"], ["2) chapeau"], ["3) chaussure"], ["4) mouche"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "chat", r: true }, " — 2) ", { t: "chapeau", r: true }, " — 3) ", { t: "chaussure", r: true }, " — 4) ", { t: "mouche", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["Le ch entouré : ", { t: "chat, chapeau, chaussure, mouche", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Dictée correcte : ", { t: "chat, chapeau, chaussure, mouche", r: true }, " (1,5 pt par mot)."]] },
   ],
  },
  {
   n: 51,
   titre: "Écrire on",
   titreFiche: "J'écris les mots avec on",
   sd: "Expression Écrite",
   objectif: "Écrire des mots simples avec on : ballon, maison, bonbon.",
   supportFiche: "Tableau noir, ardoises, cahiers.",
   revision: {
    ens: ["Dictée éclair : chat, mouche (2 élèves au tableau)."],
    app: ["R.A. : ", { t: "chat, mouche", r: true }, "."],
    technique: ["Individuel écrit"],
   },
   miseEnSituation: {
    ens: ["« Vous savez écrire ch. Et on, comment l'écrit-on ? »"],
    app: ["Proposent : avec o et n."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons le son on : d'abord le o, puis le n — on."],
    app: ["Écoutent et observent l'écriture au tableau."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » j'écris on en l'air, puis au tableau : le o rond, puis le n."],
    app: ["Observent le geste : o-n = on ; ils le tracent dans l'air."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Quelles lettres écrivent le son on ?"], ["2) Écris « ballon » sur ton ardoise : où est on ?"], ["3) Écris « maison » : vérifie le on !"], ["4) Qui peut écrire « bonbon » ?"]] },
    app: { paras: [["R.A. : ", { t: "o et n", r: true }, "."], ["R.A. : À ", { t: "la fin", r: true }, " : ", { t: "ballon", r: true }, "."], ["R.A. : mais-", { t: "on", r: true }, " : ", { t: "maison", r: true }, "."], ["R.A. : bon-", { t: "bon", r: true }, " : ", { t: "bonbon", r: true }, " (deux fois on !)."]] },
    technique: ["Question / réponse"],
    support: "Ardoises",
   },
   synthese: {
    ens: ["Donc : le son on s'écrit avec o et n : ballon, maison, bonbon."],
    app: ["Répètent en écrivant dans l'air : on, on, on."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Sur ton ardoise, écris : ballon, maison ; vérifie avec le tableau."],
    app: ["Écrivent sur ardoise, comparent, corrigent."],
    technique: ["Écriture individuelle"],
    support: "Ardoises",
   },
   evaluation: {
    ens: ["2 élèves : écris « ballon » au tableau."],
    app: ["R.A. : ", { t: "ballon", r: true }, " bien écrit (o-n)."],
    technique: ["Individuel écrit"],
   },
   lecon: {
    titre: "51. ÉCRIRE ON",
    subs: [
     { t: "A. Les lettres", paras: [[{ t: "on", k: true }, " : d'abord ", { t: "o", k: true }, ", puis ", { t: "n", k: true }, " — bouche ronde pour le dire !"]] },
     { t: "B. La dictée", paras: [["J'écris : ", { t: "ballon, maison, bonbon", k: true }, " sans oublier le on !"]] },
    ],
    retenir: ["J'écris le son ", { t: "on", k: true }, " avec ", { t: "o et n", k: true }, " : ballon, maison, bonbon."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris le mot qui manque (copie depuis le tableau) :"], items: [["1) le ....... (ballon)"], ["2) la ....... (maison)"], ["3) le ....... (bonbon)"], ["4) le ....... (pantalon)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entoure on dans ces mots :"], items: [["1) ballon"], ["2) maison"], ["3) bonbon"], ["4) mouton"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Petite dictée sur le cahier (4 mots) :"], items: [["1) ballon"], ["2) maison"], ["3) bonbon"], ["4) pantalon"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "ballon", r: true }, " — 2) ", { t: "maison", r: true }, " — 3) ", { t: "bonbon", r: true }, " — 4) ", { t: "pantalon", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["Le on entouré : ", { t: "ballon, maison, bonbon, mouton", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Dictée correcte : ", { t: "ballon, maison, bonbon, pantalon", r: true }, " (1,5 pt par mot)."]] },
   ],
  },
  {
   n: 52,
   titre: "Bilan de l'unité 4",
   titreFiche: "L'école : grand bilan",
   sd: "Expression Orale",
   objectif: "Réutiliser le vocabulaire de l'école et les sons ch, s, on : bilan de l'unité.",
   supportFiche: "Images de l'unité, tableau noir.",
   revision: {
    ens: ["Dis ta liste de la classe (2 élèves)."],
    app: ["R.A. : « ", { t: "Dans ma classe, il y a..., ..., et...", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« L'unité 4 est finie ! L'école, le cartable, les sons ch, s et on : tout est appris ! »"],
    app: ["Écoutent, fiers de leur travail."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, le grand bilan : je joue et je dis tout ce que j'ai appris."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez les images de l'unité : » classe, cartable, dialogue, comptine, sons ch, s, on."],
    app: ["Passent en revue : cahier, crayon, gomme, règle, cartable, chat, chapeau, salade, citron, garçon, maison, ballon, bonbon."],
    technique: ["Observation guidée"],
    support: "Images de l'unité",
   },
   analyse: {
    ens: { paras: [["1) Cite 3 objets de la classe."], ["2) Que dis-tu pour demander poliment ?"], ["3) Cite un mot avec ch et un mot avec on."], ["4) Récite un bout de ta comptine."]] },
    app: { paras: [["R.A. : ", { t: "cahier, crayon, gomme...", r: true }, "."], ["R.A. : ", { t: "« S'il te plaît... Merci ! »", r: true }, "."], ["R.A. : ", { t: "chat / ballon", r: true }, " (ou autres)."], ["R.A. : ", { t: "« À l'école j'apprends, c'est ainsi ! »", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Images de l'unité",
   },
   synthese: {
    ens: ["Donc : unité 4 réussie — l'école, les mots polis, la comptine et les sons ch, s, on !"],
    app: ["Récitent la comptine de l'école une dernière fois, avec les gestes."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le grand jeu : un élève mime un mot de l'unité, la classe devine et dit le son qu'il contient."],
    app: ["Miment et devinent : chat, chapeau, ballon, maison, crayon..."],
    technique: ["Jeu de mimes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : dis une phrase sur l'école avec un mot en ch ou en on."],
    app: ["R.A. : phrase libre avec un mot en ", { t: "ch", r: true }, " ou en ", { t: "on", r: true }, " (ex. : « J'ai un ballon. »)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "52. BILAN DE L'UNITÉ 4",
    subs: [
     { t: "A. Ce que je sais dire", paras: [[{ t: "le cahier, le crayon, la gomme, la règle", k: true }, " — « ", { t: "S'il te plaît... Merci !", k: true }, " » — « ", { t: "Qu'est-ce que c'est ? — C'est...", k: true }, " »"]] },
     { t: "B. Ce que je sais lire et écrire", paras: [["Le son ", { t: "ch", k: true }, " : ", { t: "chat, chapeau, mouche", k: true }, " — le son ", { t: "s", k: true }, " : ", { t: "salade, citron, garçon", k: true }, " — le son ", { t: "on", k: true }, " : ", { t: "ballon, maison, bonbon", k: true }]] },
    ],
    retenir: ["Unité 4 réussie : ", { t: "l'école, les mots polis et les sons ch, s, on", k: true }, " !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Coche ce que tu sais faire (ou dis-le) :"], items: [["1) Nommer 5 objets de la classe : oui / non"], ["2) Demander poliment un objet : oui / non"], ["3) Réciter la comptine de l'école : oui / non"], ["4) Lire des mots avec ch et on : oui / non"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Le grand tri : entoure les mots du son on :"], items: [["maison"], ["chat"], ["bonbon"], ["gomme"], ["ballon"], ["salade"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Dicte-toi : écris 1 mot avec ch, 1 mot avec on, 1 objet de classe :"], items: [["1) un mot avec ch : ....... (chat, chapeau...)"], ["2) un mot avec on : ....... (ballon, maison...)"], ["3) un objet de classe : ....... (cahier, crayon...)"], ["4) une phrase : « Papa a un ballon. » (copie)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Bilan oral : l'élève coche ", { t: "oui", r: true }, " quand il maîtrise (auto-évaluation guidée)."]] },
    { titre: "Exercice 2", lines: [["Mots avec on : ", { t: "maison, bonbon, ballon", r: true }, " (2 pts chacun) — chat, gomme, salade : non."]] },
    { titre: "Exercice 3", lines: [["Réponses libres : 1 mot en ", { t: "ch", r: true }, " + 1 mot en ", { t: "on", r: true }, " + 1 objet de ", { t: "classe", r: true }, " + phrase copiée."]] },
   ],
  },
 ],
};

module.exports = { theme4 };
