// data-theme3.js — Unité 3 « Les termes relatifs à la toilette » (séances 29 à 40)
// Sources : FRA 10ème (T1 semaines 8-9 : toilette, L/EE son an) + PDF CP2 unité III (12 séances).
// sd par séance : EO s29-34 & s40, Lecture s35-37, Écriture s38-39. Barème 8+6+6 = 20 partout.

const theme3 = {
 numero: 3,
 nom: "Les termes relatifs à la toilette",
 sousDiscipline: "Expression Orale",
 notions: "Le vocabulaire de la toilette (savon, serviette, lavabo, bain, douche, dents) et le son an.",
 competences: [
  "Nommer les objets et les gestes de la toilette.",
  "Dire ce qu'on fait pour être propre : « je me lave », « je me brosse les dents ».",
  "Reconnaître et prononcer le son an dans des mots et des phrases.",
  "Écrire des mots simples avec an (dent, lampe, banane, pantalon).",
 ],
 seances: [
  {
   n: 29,
   titre: "Le vocabulaire de la toilette",
   titreFiche: "Les objets de la toilette",
   sd: "Expression Orale",
   objectif: "Nommer les objets de la toilette : le savon, la serviette, le lavabo, l'eau, la brosse, le peigne.",
   supportFiche: "Image « la toilette », savon, serviette réelles, tableau noir.",
   revision: {
    ens: ["Présente ta famille en 2 phrases : « Voici ma famille... » (2 élèves)."],
    app: ["R.A. : « ", { t: "Voici ma famille. Voici mon papa, ma maman...", r: true }, " »"],
    technique: ["Question / réponse"],
   },
   miseEnSituation: {
    ens: ["« Ce matin, avant de venir à l'école, que fait-on pour être propre ? »"],
    app: ["Proposent librement : on se lave, on met des habits propres..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots de la toilette : savon, serviette, lavabo, eau, brosse, peigne."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Regardez bien ces objets. Qui connaît leur nom ? » Montrez chaque objet."],
    app: ["Observent et nomment : le savon, la serviette, le lavabo, la brosse, le peigne."],
    technique: ["Observation guidée"],
    support: "Objets réels, image « la toilette »",
   },
   analyse: {
    ens: { paras: [["1) Avec quoi lavons-nous nos mains ?"], ["2) Avec quoi séchons-nous notre visage ?"], ["3) Où y a-t-il de l'eau à la maison ?"], ["4) Avec quoi arrangeons-nous nos cheveux ?"]] },
    app: { paras: [["R.A. : Le ", { t: "savon", r: true }, " et ", { t: "l'eau", r: true }, "."], ["R.A. : La ", { t: "serviette", r: true }, "."], ["R.A. : Au ", { t: "lavabo", r: true }, "."], ["R.A. : Avec le ", { t: "peigne", r: true }, " ou la ", { t: "brosse", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Objets réels, image « la toilette »",
   },
   synthese: {
    ens: ["Donc : pour la toilette, il y a le savon, la serviette, le lavabo, l'eau, la brosse et le peigne."],
    app: ["Répètent les 6 mots en chœur en montrant les objets."],
    technique: ["Répétition collective"],
    support: "Objets réels",
   },
   application: {
    ens: ["Chacun votre tour : dites un objet de la toilette que vous avez à la maison."],
    app: ["Disent : « Chez nous, il y a... » (un objet au moins)."],
    technique: ["Chaîne parlée"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : je nomme un objet, vous le montrez et le nommez."],
    app: ["R.A. : ", { t: "le savon, la serviette, le lavabo", r: true }, " (3 mots corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "29. LE VOCABULAIRE DE LA TOILETTE",
    subs: [
     { t: "A. Les objets de la toilette", paras: [[{ t: "le savon", k: true }, " — ", { t: "la serviette", k: true }, " — ", { t: "le lavabo", k: true }, " — ", { t: "l'eau", k: true }, " — ", { t: "la brosse", k: true }, " — ", { t: "le peigne", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Je me lave les mains avec du savon et de l'eau.", k: true }, " »"]] },
    ],
    retenir: ["Pour la toilette : ", { t: "le savon, la serviette, le lavabo, l'eau", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les objets de la toilette :"], items: [["le savon"], ["la gomme"], ["la serviette"], ["le cahier"], ["le lavabo"], ["le vélo"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète : « Je me lave les mains avec du ....... et de l'....... »"], items: [["1) ....... (savon)"], ["2) ....... (eau)"], ["3) Je sèche mon visage avec la ....... (serviette)"], ["4) J'arrange mes cheveux avec le ....... (peigne)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène : demande à ton camarade de te donner le savon."], items: [["1) « S'il te plaît, donne-moi le ....... (savon) »"], ["2) « Merci ! » — Tu réponds : ....... (« de rien »)"], ["3) Montre où tu te laves : au ....... (lavabo)"], ["4) Dis ta phrase : « Je me lave les mains avec ....... (du savon) »"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Objets entourés : ", { t: "le savon, la serviette, le lavabo", r: true }, " (2 pts chacun) — les autres non (gomme, cahier, vélo : objets d'école)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "savon", r: true }, " — 2) ", { t: "eau", r: true }, " — 3) ", { t: "serviette", r: true }, " — 4) ", { t: "peigne", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "savon", r: true }, " — 2) ", { t: "de rien", r: true }, " — 3) ", { t: "lavabo", r: true }, " — 4) ", { t: "du savon", r: true }, "."]] },
   ],
  },
  {
   n: 30,
   titre: "Le bain et la douche",
   titreFiche: "Je prends mon bain",
   sd: "Expression Orale",
   objectif: "Dire les gestes du bain : se laver, se rincer, se sécher ; employer « je prends mon bain ».",
   supportFiche: "Image « le bain », mimes, tableau noir.",
   revision: {
    ens: ["Nommez 3 objets de la toilette (chaîne parlée)."],
    app: ["R.A. : ", { t: "le savon, la serviette, le lavabo, l'eau, la brosse, le peigne", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Qui prend son bain le matin ? Qui le prend le soir ? »"],
    app: ["Répondent : le matin / le soir, avec de l'eau du seau ou à la douche..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous disons les gestes du bain : je me lave, je me rince, je me sèche."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Regardez l'image. Que fait l'enfant ? » Faites mimer chaque geste."],
    app: ["Observent : l'enfant prend son bain, se savonne, se rince, se sèche avec la serviette."],
    technique: ["Observation guidée"],
    support: "Image « le bain »",
   },
   analyse: {
    ens: { paras: [["1) Que dit-on quand on entre dans l'eau ?"], ["2) Avec quoi se savonne-t-on ?"], ["3) Que fait-on après s'être rincé ?"], ["4) Comment est-on après le bain ?"]] },
    app: { paras: [["R.A. : ", { t: "Je prends mon bain", r: true }, "."], ["R.A. : Avec le ", { t: "savon", r: true }, "."], ["R.A. : On se ", { t: "sèche", r: true }, " avec la serviette."], ["R.A. : On est ", { t: "propre", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Image « le bain »",
   },
   synthese: {
    ens: ["Donc : je prends mon bain, je me savonne, je me rince, je me sèche : je suis propre !"],
    app: ["Répètent la chaîne des gestes en la mimant."],
    technique: ["Répétition collective"],
    support: "Image « le bain »",
   },
   application: {
    ens: ["Chacun votre tour : mimez un geste du bain, les autres le disent."],
    app: ["Miment et disent : « je me savonne », « je me rince », « je me sèche »..."],
    technique: ["Jeu de mimes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["2 élèves : racontez votre bain en 3 gestes."],
    app: ["R.A. : ", { t: "je me savonne, je me rince, je me sèche", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "30. LE BAIN ET LA DOUCHE",
    subs: [
     { t: "A. Les gestes du bain", paras: [["« ", { t: "Je prends mon bain.", k: true }, " » — ", { t: "je me savonne", k: true }, " — ", { t: "je me rince", k: true }, " — ", { t: "je me sèche", k: true }, "."]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Après le bain, je suis propre.", k: true }, " »"]] },
    ],
    retenir: ["Je prends mon bain : ", { t: "je me savonne, je me rince, je me sèche", k: true }, " — je suis ", { t: "propre", k: true }, " !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les gestes du bain dans le bon ordre (numérote 1, 2, 3, 4) :"], items: [["....... se sécher"], ["....... se savonner"], ["....... se laver"], ["....... se rincer"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) « Je ....... mon bain. » (prends)"], ["2) « Je me ....... avec du savon. » (savonne)"], ["3) « Je me ....... avec la serviette. » (sèche)"], ["4) « Je suis ....... ! » (propre)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Mime et dis (2 gestes chacun, 3 élèves) :"], items: [["1) Le geste de se savonner : ....... (je me savonne)"], ["2) Le geste de se sécher : ....... (je me sèche)"], ["3) Le geste de se rincer : ....... (je me rince)"], ["4) Le geste de prendre l'eau : ....... (je prends mon bain)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "2 se savonner — 3 se rincer — 1 se sécher", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "prends", r: true }, " — 2) ", { t: "savonne", r: true }, " — 3) ", { t: "sèche", r: true }, " — 4) ", { t: "propre", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Gestes et phrases corrects : ", { t: "je me savonne, je me sèche, je me rince, je prends mon bain", r: true }, "."]] },
   ],
  },
  {
   n: 31,
   titre: "Les dents",
   titreFiche: "Je me brosse les dents",
   sd: "Expression Orale",
   objectif: "Nommer la brosse à dents, le dentifrice ; dire « je me brosse les dents ».",
   supportFiche: "Brosse à dents réelle, image « les dents », tableau noir.",
   revision: {
    ens: ["Mime un geste du bain, les autres devinent."],
    app: ["R.A. : ", { t: "je me savonne / je me rince / je me sèche", r: true }, "."],
    technique: ["Jeu de mimes"],
   },
   miseEnSituation: {
    ens: ["« Montrez vos dents ! Qui s'est brossé les dents ce matin ? »"],
    app: ["Montrent leurs dents et répondent : oui / non."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons : la brosse à dents, le dentifrice, se brosser les dents."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez ma brosse à dents. Où met-on le dentifrice ? » Faites mimer le brossage."],
    app: ["Observent : le dentifrice va sur la brosse ; on frotte les dents en haut et en bas."],
    technique: ["Observation guidée"],
    support: "Brosse à dents réelle",
   },
   analyse: {
    ens: { paras: [["1) Avec quoi se brosse-t-on les dents ?"], ["2) Combien de fois par jour se brosse-t-on les dents ?"], ["3) Que met-on sur la brosse ?"], ["4) Pourquoi se brosse-t-on les dents ?"]] },
    app: { paras: [["R.A. : Avec la ", { t: "brosse à dents", r: true }, "."], ["R.A. : Le matin et le ", { t: "soir", r: true }, "."], ["R.A. : Du ", { t: "dentifrice", r: true }, "."], ["R.A. : Pour avoir des dents ", { t: "blanches et solides", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Brosse à dents, image « les dents »",
   },
   synthese: {
    ens: ["Donc : matin et soir, je me brosse les dents avec la brosse et le dentifrice."],
    app: ["Répètent en miment : « je me brosse les dents »."],
    technique: ["Répétition collective"],
    support: "Brosse à dents",
   },
   application: {
    ens: ["Chacun votre tour : mime le brossage des dents et dis la phrase."],
    app: ["Miment : « Je me brosse les dents avec du dentifrice. »"],
    technique: ["Jeu de mimes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : que met-on sur la brosse à dents ?"],
    app: ["R.A. : ", { t: "du dentifrice", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "31. LES DENTS",
    subs: [
     { t: "A. Les mots des dents", paras: [[{ t: "la brosse à dents", k: true }, " — ", { t: "le dentifrice", k: true }, " — ", { t: "se brosser les dents", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Matin et soir, je me brosse les dents avec du dentifrice.", k: true }, " »"]] },
    ],
    retenir: ["Matin et soir : ", { t: "je me brosse les dents", k: true }, " avec ", { t: "la brosse et le dentifrice", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure ce qui sert aux dents :"], items: [["la brosse à dents"], ["le savon"], ["le dentifrice"], ["le peigne"], ["la serviette"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète : « Je me brosse les dents ....... et ....... »"], items: [["1) ....... (matin)"], ["2) ....... (soir)"], ["3) Je mets du ....... sur ma brosse. (dentifrice)"], ["4) Je me brosse les ....... . (dents)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Réponds en jouant : « Que fait-on pour avoir de belles dents ? »"], items: [["1) Je me ....... les dents. (brosse)"], ["2) Le matin et le ....... . (soir)"], ["3) Avec de la ....... à dents. (brosse)"], ["4) Avec du ....... . (dentifrice)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entourés : ", { t: "la brosse à dents, le dentifrice", r: true }, " (2 pts chacun) — savon, peigne, serviette : autre toilette."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "matin", r: true }, " — 2) ", { t: "soir", r: true }, " — 3) ", { t: "dentifrice", r: true }, " — 4) ", { t: "dents", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "brosse", r: true }, " — 2) ", { t: "soir", r: true }, " — 3) ", { t: "brosse", r: true }, " — 4) ", { t: "dentifrice", r: true }, "."]] },
   ],
  },
  {
   n: 32,
   titre: "Propre ou sale ?",
   titreFiche: "Je reconnais propre et sale",
   sd: "Expression Orale",
   objectif: "Distinguer « propre » et « sale » ; dire « il est propre », « elle est sale ».",
   supportFiche: "Deux images (enfant propre / enfant sale), tableau noir.",
   revision: {
    ens: ["Que met-on sur la brosse à dents ? (2 élèves)"],
    app: ["R.A. : ", { t: "du dentifrice", r: true }, "."],
    technique: ["Question / réponse"],
   },
   miseEnSituation: {
    ens: ["« Après avoir joué au foot, comment sont tes mains ? Et après la toilette ? »"],
    app: ["Répondent : les mains sont sales après le jeu, propres après la toilette."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons deux mots contraires : propre et sale."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Regardez les deux images : ces enfants sont différents. Comment ? »"],
    app: ["Observent : l'un est propre (visage lavé, habits nets), l'autre est sale (mains sales, habits tachés)."],
    technique: ["Observation guidée"],
    support: "Deux images",
   },
   analyse: {
    ens: { paras: [["1) Comment est l'enfant qui s'est lavé ?"], ["2) Comment est l'enfant qui a joué dans la boue ?"], ["3) Que fait l'enfant sale pour devenir propre ?"], ["4) Montre quelque chose de propre dans la classe."]] },
    app: { paras: [["R.A. : Il est ", { t: "propre", r: true }, "."], ["R.A. : Il est ", { t: "sale", r: true }, "."], ["R.A. : Il ", { t: "se lave", r: true }, " avec du savon."], ["R.A. : Le ", { t: "tableau, le sol, mon cahier", r: true }, " sont propres."]] },
    technique: ["Question / réponse"],
    support: "Deux images",
   },
   synthese: {
    ens: ["Donc : propre = lavé et net ; sale = plein de poussière ou de boue. Le contraire de propre est sale."],
    app: ["Répètent la paire : « propre — sale » en gestes."],
    technique: ["Répétition collective"],
    support: "Deux images",
   },
   application: {
    ens: ["Le jeu : je montre une image ou je mime, vous dites « propre ! » ou « sale ! »."],
    app: ["Disent vite : propre / sale selon la situation montrée."],
    technique: ["Jeu rapide"],
    support: "Images, mimes",
   },
   evaluation: {
    ens: ["3 élèves : complétez « Après le bain, je suis ....... ; après le foot, mes mains sont ....... »"],
    app: ["R.A. : ", { t: "propre", r: true }, " ; ", { t: "sale", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "32. PROPRE OU SALE ?",
    subs: [
     { t: "A. Deux mots contraires", paras: [[{ t: "propre", k: true }, " ≠ ", { t: "sale", k: true }, " : après la toilette, je suis propre."]] },
     { t: "B. Mes phrases", paras: [["« ", { t: "Il est propre.", k: true }, " » — « ", { t: "Elle est propre.", k: true }, " » — « Mes mains sont sales. »"]] },
    ],
    retenir: [{ t: "Propre", k: true }, " = lavé et net — ", { t: "sale", k: true }, " = le contraire."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Coche la bonne réponse (ou dis-la) : l'enfant qui s'est lavé est ......."], items: [["1) propre / sale"], ["2) L'enfant qui a joué dans la boue est : propre / sale"], ["3) Le contraire de sale est : propre / lavabo"], ["4) Après le bain, je suis : propre / sale"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète par propre ou sale :"], items: [["1) Mes mains sont ....... après la toilette. (propres)"], ["2) Mes mains sont ....... après le jardinage. (sales)"], ["3) Ma robe est ....... : elle est neuve ! (propre)"], ["4) Mes chaussures sont ....... : il y a de la boue ! (sales)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue le vrai / faux : lève la main si c'est VRAI :"], items: [["1) Je me lave pour être propre. (vrai)"], ["2) Je me roule dans la boue pour être propre. (faux)"], ["3) La serviette me sèche. (vrai)"], ["4) Le savon me rend sale. (faux)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "propre", r: true }, " — 2) ", { t: "sale", r: true }, " — 3) ", { t: "propre", r: true }, " — 4) ", { t: "propre", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "propres", r: true }, " — 2) ", { t: "sales", r: true }, " — 3) ", { t: "propre", r: true }, " — 4) ", { t: "sales", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Vrai : ", { t: "1 et 3", r: true }, " — Faux : ", { t: "2 et 4", r: true }, "."]] },
   ],
  },
  {
   n: 33,
   titre: "La comptine de la toilette",
   titreFiche: "La comptine : je suis propre et content",
   sd: "Expression Orale",
   objectif: "Réciter la comptine de la toilette avec les gestes.",
   supportFiche: "Comptine au tableau, image « la toilette », tableau noir.",
   revision: {
    ens: ["Le contraire de « propre » ? (chaîne parlée rapide)"],
    app: ["R.A. : ", { t: "sale", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Vous connaissez déjà la comptine de la famille. Aujourd'hui, la toilette a aussi sa comptine ! »"],
    app: ["Écoutent, curieux."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons la comptine de la toilette."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez d'abord : » Je récite la comptine deux fois avec les gestes."],
    app: ["Écoutent : « Je me lave, je me lave, / avec du savon ; / je me rince, je me sèche, / je suis propre et content ! »"],
    technique: ["Écoute active"],
    support: "Comptine au tableau",
   },
   analyse: {
    ens: { paras: [["1) Avec quoi se lave-t-on dans la comptine ?"], ["2) Que fait-on après s'être rincé ?"], ["3) Comment est-on à la fin ?"], ["4) Répète le dernier vers."]] },
    app: { paras: [["R.A. : Avec du ", { t: "savon", r: true }, "."], ["R.A. : On ", { t: "se sèche", r: true }, "."], ["R.A. : ", { t: "Propre et content", r: true }, "."], ["R.A. : ", { t: "Je suis propre et content !", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Comptine au tableau",
   },
   synthese: {
    ens: ["Donc : la comptine raconte la toilette : je me lave, je me rince, je me sèche, je suis propre et content !"],
    app: ["Répètent les 4 vers ligne par ligne avec les gestes."],
    technique: ["Répétition collective"],
    support: "Comptine au tableau",
   },
   application: {
    ens: ["Par 2 : récitez la comptine en entier avec les gestes."],
    app: ["Récitent en binômes, puis quelques groupes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Comptine au tableau",
   },
   evaluation: {
    ens: ["2 élèves : récite la comptine toute seule."],
    app: ["R.A. : les 4 vers, au moins 3 corrects : ", { t: "je me lave / savon / je me rince, je me sèche / propre et content", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "33. LA COMPTINE DE LA TOILETTE",
    subs: [
     { t: "A. La comptine", paras: [["« ", { t: "Je me lave, je me lave,", k: true }, " » — « ", { t: "avec du savon ;", k: true }, " »"], ["« ", { t: "je me rince, je me sèche,", k: true }, " » — « ", { t: "je suis propre et content !", k: true }, " »"]] },
    ],
    retenir: ["Ma comptine : ", { t: "« Je suis propre et content ! »", k: true }, " — je la connais par cœur !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les vers dans le bon ordre (1, 2, 3, 4) :"], items: [["....... je suis propre et content !"], ["....... Je me lave, je me lave,"], ["....... je me rince, je me sèche,"], ["....... avec du savon ;"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la comptine :"], items: [["1) Je me lave, je me lave, avec du ....... (savon)"], ["2) Je me rince, je me ....... (sèche)"], ["3) Je suis ....... et content ! (propre)"], ["4) Je me lave avec du savon et de l'....... (eau)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Récite avec les gestes (2 élèves, 2 vers chacun) :"], items: [["1) Vers 1 avec le geste de ....... (se laver)"], ["2) Vers 2 avec le geste du ....... (savon)"], ["3) Vers 3 avec les gestes de ....... (rincer / sécher)"], ["4) Vers 4 avec le sourire : ....... (propre et content)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "4 — 1 — 3 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "savon", r: true }, " — 2) ", { t: "sèche", r: true }, " — 3) ", { t: "propre", r: true }, " — 4) ", { t: "eau", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Gestes corrects : ", { t: "se laver, savon, rincer / sécher, propre et content", r: true }, "."]] },
   ],
  },
  {
   n: 34,
   titre: "Le dialogue : tu es propre !",
   titreFiche: "Le dialogue de la toilette",
   sd: "Expression Orale",
   objectif: "Jouer un dialogue sur la toilette : « Tu es propre ? — Oui, je suis propre ! ».",
   supportFiche: "Image « la toilette », tableau noir.",
   revision: {
    ens: ["Récitez la comptine de la toilette (toute la classe)."],
    app: ["R.A. : les 4 vers de la ", { t: "comptine", r: true }, "."],
    technique: ["Récitation collective"],
   },
   miseEnSituation: {
    ens: ["« Ce matin, ta maman te demande : tu es propre ? Que réponds-tu ? »"],
    app: ["Proposent : oui maman, je me suis lavé !"],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous jouons le dialogue de la toilette."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez le dialogue : » Je le joue avec un élève."],
    app: ["Écoutent : « — Rova, tu es propre ? — Oui, maman, je me suis lavé avec du savon ! — Montre tes mains... Elles sont propres, bravo ! »"],
    technique: ["Écoute active"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Que demande la maman à Rova ?"], ["2) Comment s'est-il lavé ?"], ["3) Que fait la maman à la fin ?"], ["4) Comment répond-on quand on est propre ?"]] },
    app: { paras: [["R.A. : ", { t: "Tu es propre ?", r: true }, "."], ["R.A. : Avec du ", { t: "savon", r: true }, "."], ["R.A. : Elle ", { t: "regarde ses mains", r: true }, " et dit bravo."], ["R.A. : ", { t: "Oui, je suis propre !", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : le dialogue — « Tu es propre ? — Oui, je suis propre ! » — et on montre ses mains."],
    app: ["Répètent les répliques par moitiés de classe."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Par 2 : jouez le dialogue complet, puis échangez les rôles."],
    app: ["Jouent le dialogue en binômes ; 2 binômes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["1 binôme : jouez le dialogue."],
    app: ["R.A. : répliques correctes : ", { t: "« Tu es propre ? — Oui, je suis propre ! »", r: true }, "."],
    technique: ["Binôme"],
   },
   lecon: {
    titre: "34. LE DIALOGUE : TU ES PROPRE ?",
    subs: [
     { t: "A. Le dialogue", paras: [["« — ", { t: "Tu es propre ?", k: true }, " — ", { t: "Oui, je suis propre !", k: true }, " »"], ["« — Montre tes mains... — ", { t: "Regarde, elles sont propres !", k: true }, " »"]] },
    ],
    retenir: ["Le dialogue : « ", { t: "Tu es propre ? — Oui, je suis propre !", k: true }, " »"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les répliques du dialogue dans l'ordre (1, 2, 3, 4) :"], items: [["....... — Oui, je suis propre !"], ["....... — Rova, tu es propre ?"], ["....... — Montre tes mains..."], ["....... — Regarde, elles sont propres !"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète le dialogue :"], items: [["1) « Tu es ....... ? » (propre)"], ["2) « Oui, je suis ....... ! » (propre)"], ["3) « Montre tes ....... ! » (mains)"], ["4) « Je me suis lavé avec du ....... » (savon)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue avec ton camarade (question puis réponse) :"], items: [["1) La question de la maman : ....... (« Tu es propre ? »)"], ["2) Ta réponse : ....... (« Oui, je suis propre ! »)"], ["3) Ce que tu montres : mes ....... (mains)"], ["4) Ce que dit la maman à la fin : ....... (« bravo ! »)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "2 — 1 — 3 — 4", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "propre", r: true }, " — 2) ", { t: "propre", r: true }, " — 3) ", { t: "mains", r: true }, " — 4) ", { t: "savon", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "« Tu es propre ? »", r: true }, " — 2) ", { t: "« Oui, je suis propre ! »", r: true }, " — 3) ", { t: "mains", r: true }, " — 4) ", { t: "« bravo ! »", r: true }, "."]] },
   ],
  },
  {
   n: 35,
   titre: "Le son an — découverte",
   titreFiche: "Je découvre le son an",
   sd: "Lecture",
   objectif: "Reconnaître et prononcer le son an dans des mots connus.",
   supportFiche: "Image « le son an », étiquettes mots, tableau noir.",
   revision: {
    ens: ["Jouez le dialogue : « Tu es propre ? » (1 binôme)."],
    app: ["R.A. : ", { t: "« Tu es propre ? — Oui, je suis propre ! »", r: true }, "."],
    technique: ["Binôme"],
   },
   miseEnSituation: {
    ens: ["« Répétez après moi : aaan, aaan, aaan ! Ouvrez bien la bouche ! »"],
    app: ["Répètent le son : bouche ouverte, mâchoire baissée : aaan !"],
    technique: ["Répétition articulée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son an : lampe, banane, canard, pantalon, dent, maman."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Image « le son an »",
   },
   observation: {
    ens: ["« Observez les images et écoutez : la LAMPE, la BANANE, le CANARD. Entendez-vous an ? »"],
    app: ["Observent et entendent an dans chaque mot ; ils le disent : lam(p), ban(ane), can(ard)."],
    technique: ["Observation guidée"],
    support: "Image « le son an »",
   },
   analyse: {
    ens: { paras: [["1) Ouvre la bouche : quel son entends-tu dans la lampe ?"], ["2) Où est le son an dans « banane » : au début, au milieu ou à la fin ?"], ["3) Et dans « dent » ?"], ["4) Cite un mot de la classe avec le son an."]] },
    app: { paras: [["R.A. : Le son ", { t: "an", r: true }, "."], ["R.A. : Au ", { t: "milieu", r: true }, " (ba-nane)."], ["R.A. : À ", { t: "la fin", r: true }, "."], ["R.A. : ", { t: "le banc, le plancher", r: true }, "... (réponses libres)."]] },
    technique: ["Question / réponse"],
    support: "Image « le son an », étiquettes",
   },
   synthese: {
    ens: ["Donc : le son an s'entend dans lampe, banane, canard, pantalon, dent, maman — bouche ouverte !"],
    app: ["Répètent les 6 mots en chœur, puis en chanson : aaan !"],
    technique: ["Répétition collective"],
    support: "Image « le son an »",
   },
   application: {
    ens: ["Le jeu du panier : je dis des mots, vous frappez des mains quand vous entendez an."],
    app: ["Frappent des mains : banane, dent, maman... ; ne frappent pas : savon, papa, vélo."],
    technique: ["Jeu d'écoute"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : prononce « lampe, banane, dent » avec le son an bien ouvert."],
    app: ["R.A. : ", { t: "lampe, banane, dent", r: true }, " (son an correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "35. LE SON AN",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "an", k: true }, " : j'ouvre la bouche et je dis « aaan ! »"]] },
     { t: "B. Les mots", paras: [[{ t: "la lampe", k: true }, " — ", { t: "la banane", k: true }, " — ", { t: "le canard", k: true }, " — ", { t: "le pantalon", k: true }, " — ", { t: "la dent", k: true }, " — ", { t: "maman", k: true }]] },
    ],
    retenir: ["Le son ", { t: "an", k: true }, " : ", { t: "lampe, banane, canard, pantalon, dent, maman", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son an :"], items: [["lampe"], ["savon"], ["banane"], ["papa"], ["dent"], ["vélo"], ["canard"], ["jupe"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entends-tu an ? Coche oui ou non (ou dis-le) :"], items: [["1) maman : oui / non"], ["2) serviette : oui / non"], ["3) pantalon : oui / non"], ["4) tortue : oui / non"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Répète avec la bouche bien ouverte :"], items: [["1) aaan — ....... (lampe)"], ["2) aaan — ....... (banane)"], ["3) aaan — ....... (canard)"], ["4) aaan — ....... (pantalon)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "lampe, banane, dent, canard", r: true }, " (2 pts chacun) — savon (on), papa, vélo, jupe : pas de an."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oui", r: true }, " — 2) ", { t: "non", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "non", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Prononciation correcte : ", { t: "lampe, banane, canard, pantalon", r: true }, "."]] },
   ],
  },
  {
   n: 36,
   titre: "Le son an — lire des mots",
   titreFiche: "Je lis des mots avec an",
   sd: "Lecture",
   objectif: "Lire des mots avec le son an ; repérer sa place (début, milieu, fin).",
   supportFiche: "Étiquettes mots, image « le son an », tableau noir.",
   revision: {
    ens: ["Cite 2 mots avec le son an (chaîne parlée)."],
    app: ["R.A. : ", { t: "lampe, banane, canard, pantalon, dent, maman...", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Aujourd'hui, les mots avec an arrivent dans la classe. Qui saura les lire ? »"],
    app: ["Écoutent, motivés."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons des mots avec an : banc, planche, plante, manteau?... — restons simples : banc, dent, lampe, banane, canard, pantalon."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Étiquettes mots",
   },
   observation: {
    ens: ["« Observez les étiquettes : » montre les mots un à un ; les élèves lisent d'abord seuls, puis ensemble."],
    app: ["Lisent : le banc, la dent, la lampe, la banane, le canard, le pantalon."],
    technique: ["Lecture individuelle puis collective"],
    support: "Étiquettes mots",
   },
   analyse: {
    ens: { paras: [["1) Où est le son an dans « banc » : au début ou à la fin ?"], ["2) Où est-il dans « banane » ?"], ["3) Lis « pantalon » : où entends-tu an ?"], ["4) Quel mot a an à la fin : dent ou papa ?"]] },
    app: { paras: [["R.A. : À ", { t: "la fin", r: true }, " (ban(c))."], ["R.A. : Au ", { t: "milieu", r: true }, "."], ["R.A. : À ", { t: "la fin", r: true }, " (panta-lon)."], ["R.A. : ", { t: "dent", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Étiquettes mots",
   },
   synthese: {
    ens: ["Donc : le son an peut être au début (ancre... ici : banc, dent, pantalon à la fin ; banane, lampe au milieu)."],
    app: ["Relisent les 6 mots en montrant la place de an avec le doigt."],
    technique: ["Répétition collective"],
    support: "Étiquettes mots",
   },
   application: {
    ens: ["Par 2 : lisez les étiquettes chacun votre tour ; ton camarade vérifie."],
    app: ["Lisent les 6 mots en binômes."],
    technique: ["Travail en binômes"],
    support: "Étiquettes mots",
   },
   evaluation: {
    ens: ["3 élèves : lis 3 étiquettes au choix."],
    app: ["R.A. : lecture correcte d'au moins 2 mots : ", { t: "dent, lampe, banane, canard, banc, pantalon", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "36. LE SON AN — LES MOTS",
    subs: [
     { t: "A. Les mots", paras: [[{ t: "le banc", k: true }, " — ", { t: "la dent", k: true }, " — ", { t: "la lampe", k: true }, " — ", { t: "la banane", k: true }, " — ", { t: "le canard", k: true }, " — ", { t: "le pantalon", k: true }]] },
     { t: "B. Sa place", paras: [["Le son an peut être au ", { t: "milieu", k: true }, " (banane, lampe, canard) ou à ", { t: "la fin", k: true }, " (banc, dent, pantalon)."]] },
    ],
    retenir: ["Je lis : ", { t: "banc, dent, lampe, banane, canard, pantalon", k: true }, " — le son an est partout !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Lis et entoure les mots avec an à la fin :"], items: [["la dent"], ["la banane"], ["le pantalon"], ["le banc"], ["la lampe"], ["le canard"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète avec an :"], items: [["1) la .......e → la banne... ; écris : ban(ane) → la b.......ane (banane)"], ["2) la l...mpe (lampe)"], ["3) le c...nard (canard)"], ["4) le p...talon (pantalon)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis les mots à ton camarade (4 mots) :"], items: [["1) le banc"], ["2) la dent"], ["3) le canard"], ["4) la banane"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots avec an à la fin : ", { t: "la dent, le pantalon, le banc", r: true }, " — banane, lampe, canard : an au milieu."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "banane", r: true }, " — 2) ", { t: "lampe", r: true }, " — 3) ", { t: "canard", r: true }, " — 4) ", { t: "pantalon", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Lecture correcte : ", { t: "banc, dent, canard, banane", r: true }, "."]] },
   ],
  },
  {
   n: 37,
   titre: "Le son an — lire des phrases",
   titreFiche: "Je lis des phrases avec an",
   sd: "Lecture",
   objectif: "Lire des phrases simples contenant des mots avec an.",
   supportFiche: "Phrases au tableau, image « le son an ».",
   revision: {
    ens: ["Lis ces 3 mots : banc, dent, pantalon (3 élèves)."],
    app: ["R.A. : ", { t: "banc, dent, pantalon", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Les mots an se mettent maintenant en phrases. Prêts à lire ? »"],
    app: ["Écoutent, motivés."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons des phrases avec an."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez les phrases au tableau. » Je lis d'abord chaque phrase, les élèves suivent du doigt."],
    app: ["Suivent du doigt : « Papa a un pantalon. » « La dent de Fara bouge. » « Le canard boit à la mare. » « Maman allume la lampe. »"],
    technique: ["Observation guidée"],
    support: "Phrases au tableau",
   },
   analyse: {
    ens: { paras: [["1) Lis la première phrase : qui a un pantalon ?"], ["2) Où boit le canard ?"], ["3) Qui allume la lampe ?"], ["4) Montre les mots avec an dans la 2e phrase."]] },
    app: { paras: [["R.A. : ", { t: "Papa", r: true }, "."], ["R.A. : À ", { t: "la mare", r: true }, "."], ["R.A. : ", { t: "Maman", r: true }, "."], ["R.A. : ", { t: "dent, Fara", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Phrases au tableau",
   },
   synthese: {
    ens: ["Donc : dans chaque phrase, je cherche les mots avec an et je les lis bien."],
    app: ["Relisent les 4 phrases en chœur, puis individuellement."],
    technique: ["Répétition collective"],
    support: "Phrases au tableau",
   },
   application: {
    ens: ["Par 2 : lisez les 4 phrases chacun votre tour."],
    app: ["Lisent en binômes ; le camarade suit et corrige."],
    technique: ["Travail en binômes"],
    support: "Phrases au tableau",
   },
   evaluation: {
    ens: ["2 élèves : lis une phrase de ton choix."],
    app: ["R.A. : lecture correcte : ", { t: "« Papa a un pantalon. »", r: true }, " ou une autre phrase."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "37. LE SON AN — LES PHRASES",
    subs: [
     { t: "A. Les phrases", paras: [["« ", { t: "Papa a un pantalon.", k: true }, " » — « ", { t: "La dent de Fara bouge.", k: true }, " »"], ["« ", { t: "Le canard boit à la mare.", k: true }, " » — « ", { t: "Maman allume la lampe.", k: true }, " »"]] },
     { t: "B. Je repère", paras: [["Dans chaque phrase, je cherche ", { t: "les mots avec an", k: true }, " !"]] },
    ],
    retenir: ["Je lis des phrases et je repère les mots avec ", { t: "an", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Lis et entoure les mots avec an :"], items: [["« Papa a un pantalon. » → entoure : ....... (papa, pantalon)"], ["« La dent de Fara bouge. » → entoure : ....... (dent, Fara)"], ["« Le canard boit à la mare. » → entoure : ....... (canard, mare)"], ["« Maman allume la lampe. » → entoure : ....... (maman, lampe)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète les phrases avec : dent, pantalon, lampe, canard :"], items: [["1) Le ....... nage dans la mare. (canard)"], ["2) J'allume la ....... . (lampe)"], ["3) Papa met son ....... . (pantalon)"], ["4) La ....... de Soa bouge. (dent)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis une phrase à ton camarade ; il lit la suivante :"], items: [["1) « Papa a un pantalon. »"], ["2) « La dent de Fara bouge. »"], ["3) « Le canard boit à la mare. »"], ["4) « Maman allume la lampe. »"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "papa, pantalon", r: true }, " — 2) ", { t: "dent, Fara", r: true }, " — 3) ", { t: "canard, mare", r: true }, " — 4) ", { t: "maman, lampe", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "canard", r: true }, " — 2) ", { t: "lampe", r: true }, " — 3) ", { t: "pantalon", r: true }, " — 4) ", { t: "dent", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Lecture fluide des 4 phrases : ", { t: "oui", r: true }, " (avec aide si besoin)."]] },
   ],
  },
  {
   n: 38,
   titre: "Écrire an",
   titreFiche: "J'écris les mots avec an",
   sd: "Expression Écrite",
   objectif: "Écrire des mots simples avec an : dent, lampe, banane, pantalon.",
   supportFiche: "Tableau noir, ardoises, cahiers.",
   revision: {
    ens: ["Dis le son an et un mot avec an (chaîne parlée)."],
    app: ["R.A. : ", { t: "aaan — lampe, banane, dent...", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Nous savons dire an ; maintenant nous allons l'ÉCRIRE. Comment écrit-on an ? »"],
    app: ["Proposent : avec les lettres a et n."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons le son an : a puis n — an."],
    app: ["Écoutent et observent l'écriture au tableau."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » j'écris an en l'air, puis au tableau : d'abord la lettre a, puis la lettre n."],
    app: ["Observent le geste : a-n = an ; ils le tracent dans l'air avec le doigt."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Quelles lettres écrivent le son an ?"], ["2) Écris « dent » sur ton ardoise : où est an ?"], ["3) Écris « lampe » : vérifie le an !"], ["4) Qui peut écrire « banane » ?"]] },
    app: { paras: [["R.A. : ", { t: "a et n", r: true }, "."], ["R.A. : À ", { t: "la fin", r: true }, " : den-t... le an s'entend : den(t)."], ["R.A. : l-", { t: "an", r: true }, "-pe : ", { t: "lampe", r: true }, "."], ["R.A. : b-", { t: "an", r: true }, "-ane : ", { t: "banane", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Ardoises",
   },
   synthese: {
    ens: ["Donc : le son an s'écrit avec a et n : dent, lampe, banane, pantalon."],
    app: ["Répètent en écrivant dans l'air : an, an, an."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Sur ton ardoise, écris : dent, lampe ; vérifie avec le tableau."],
    app: ["Écrivent sur ardoise, comparent, corrigent."],
    technique: ["Écriture individuelle"],
    support: "Ardoises",
   },
   evaluation: {
    ens: ["2 élèves : écris « dent » au tableau."],
    app: ["R.A. : ", { t: "dent", r: true }, " bien écrit (a-n)."],
    technique: ["Individuel écrit"],
   },
   lecon: {
    titre: "38. ÉCRIRE AN",
    subs: [
     { t: "A. Les lettres", paras: [[{ t: "an", k: true }, " : d'abord ", { t: "a", k: true }, ", puis ", { t: "n", k: true }, " — bouche ouverte pour le dire !"]] },
     { t: "B. La dictée", paras: [["J'écris : ", { t: "dent, lampe, banane, pantalon", k: true }, " sans oublier le an !"]] },
    ],
    retenir: ["J'écris le son ", { t: "an", k: true }, " avec ", { t: "a et n", k: true }, " : dent, lampe, banane, pantalon."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris le mot qui manque (copie depuis le tableau) :"], items: [["1) la ....... (lampe)"], ["2) la ....... (dent)"], ["3) la b.......e → la ....... (banane)"], ["4) le p.......n → le ....... (pantalon)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entoure le son an dans ces mots :"], items: [["1) lampe"], ["2) dent"], ["3) banane"], ["4) canard"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Petite dictée sur le cahier (4 mots) :"], items: [["1) dent"], ["2) lampe"], ["3) banane"], ["4) pantalon"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "lampe", r: true }, " — 2) ", { t: "dent", r: true }, " — 3) ", { t: "banane", r: true }, " — 4) ", { t: "pantalon", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["Le son an entouré : 1) l", { t: "an", r: true }, "pe — 2) d", { t: "en", r: true }, "t (dans dent, le son an s'écrit en) — 3) b", { t: "an", r: true }, "ane — 4) c", { t: "an", r: true }, "ard."]] },
    { titre: "Exercice 3", lines: [["Dictée correcte : ", { t: "dent, lampe, banane, pantalon", r: true }, " (1,5 pt par mot)."]] },
   ],
  },
  {
   n: 39,
   titre: "Écrire an — les phrases",
   titreFiche: "J'écris des phrases avec an",
   sd: "Expression Écrite",
   objectif: "Copier puis écrire une courte phrase avec des mots en an.",
   supportFiche: "Tableau noir, cahiers.",
   revision: {
    ens: ["Dictée éclair : dent, lampe (2 élèves au tableau)."],
    app: ["R.A. : ", { t: "dent, lampe", r: true }, "."],
    technique: ["Individuel écrit"],
   },
   miseEnSituation: {
    ens: ["« Vous savez écrire les mots avec an. On les met maintenant dans des phrases ! »"],
    app: ["Écoutent, motivés."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons une phrase avec des mots en an."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez la phrase au tableau : » Papa a un pantalon. Je la lis, je la découpe à l'oral : Papa / a / un / pantalon."],
    app: ["Observent et répètent les mots de la phrase."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Quel mot de la phrase a le son an ?"], ["2) Avec quoi commence la phrase ? Avec quoi finit-elle ?"], ["3) Écris « Le canard boit. » : où est an ?"], ["4) Combien de mots dans « Papa a un pantalon » ?"]] },
    app: { paras: [["R.A. : ", { t: "pantalon", r: true }, " (et papa)."], ["R.A. : Une ", { t: "majuscule", r: true }, " ; un ", { t: "point", r: true }, "."], ["R.A. : ", { t: "canard", r: true }, "."], ["R.A. : ", { t: "4 mots", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : pour écrire une phrase, majuscule au début, point à la fin, et je cherche les mots avec an."],
    app: ["Répètent la règle en la montrant sur la phrase du tableau."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Copie la phrase « Papa a un pantalon. » dans ton cahier, soigneusement."],
    app: ["Copient la phrase ; je vérifie 3 cahiers."],
    technique: ["Copie individuelle"],
    support: "Cahiers",
   },
   evaluation: {
    ens: ["2 élèves : écris « Le canard boit. » au tableau."],
    app: ["R.A. : phrase correcte avec majuscule, point et ", { t: "canard", r: true }, "."],
    technique: ["Individuel écrit"],
   },
   lecon: {
    titre: "39. ÉCRIRE AN — LES PHRASES",
    subs: [
     { t: "A. La phrase", paras: [["« ", { t: "Papa a un pantalon.", k: true }, " » — ", { t: "majuscule", k: true }, " au début, ", { t: "point", k: true }, " à la fin."]] },
     { t: "B. Je repère", paras: [["Dans la phrase, je cherche les mots avec ", { t: "an", k: true }, " : papa, pantalon."]] },
    ],
    retenir: ["J'écris des phrases avec ", { t: "an", k: true }, " : majuscule, point, et des mots comme ", { t: "pantalon, canard", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Copie les phrases (2 phrases) :"], items: [["1) « Papa a un pantalon. »"], ["2) « La lampe est allumée. »"], ["3) « Le canard boit à la mare. »"], ["4) « La dent de Soa bouge. »"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Remets la phrase en ordre (numérote les mots) :"], items: [["....... pantalon"], ["....... a"], ["....... Papa"], ["....... un"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Dictée de phrases (1 phrase pour tous, 2 items de vérification) :"], items: [["1) « Le canard boit. » (canard correct)"], ["2) Majuscule au début : oui / non"], ["3) Point à la fin : oui / non"], ["4) Le mot avec an : ....... (canard)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Copie soignée : ", { t: "majuscule, point, mots avec an bien écrits", r: true }, " (2 pts par phrase)."]] },
    { titre: "Exercice 2", lines: [["Ordre : ", { t: "4 — 2 — 3 — 1", r: true }, " → « Papa a un pantalon. »"]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "canard", r: true }, " — 2) ", { t: "oui", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "canard", r: true }, "."]] },
   ],
  },
  {
   n: 40,
   titre: "Bilan de l'unité 3",
   titreFiche: "La toilette : grand bilan",
   sd: "Expression Orale",
   objectif: "Réutiliser le vocabulaire de la toilette et les mots avec an : bilan de l'unité.",
   supportFiche: "Images de l'unité, tableau noir.",
   revision: {
    ens: ["Lis une phrase avec an (2 élèves)."],
    app: ["R.A. : ", { t: "« Papa a un pantalon. »", r: true }, " ou autre phrase de la séance 37."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« L'unité 3 est finie ! La toilette, les dents, la comptine, le son an : tout est appris ! »"],
    app: ["Écoutent, fiers de leur travail."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, le grand bilan : je joue et je dis tout ce que j'ai appris."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez les images de l'unité : » objets de la toilette, bain, dents, propre/sale, son an."],
    app: ["Passent en revue : savon, serviette, lavabo, bain, brosse à dents, dentifrice, propre, sale, an."],
    technique: ["Observation guidée"],
    support: "Images de l'unité",
   },
   analyse: {
    ens: { paras: [["1) Cite 3 objets de la toilette."], ["2) Que fais-tu matin et soir pour tes dents ?"], ["3) Le contraire de propre ?"], ["4) Cite 2 mots avec an."]] },
    app: { paras: [["R.A. : ", { t: "savon, serviette, lavabo", r: true }, "..."], ["R.A. : ", { t: "Je me brosse les dents", r: true }, "."], ["R.A. : ", { t: "sale", r: true }, "."], ["R.A. : ", { t: "lampe, banane, dent, canard, pantalon, maman...", r: true }, " (2 au moins)."]] },
    technique: ["Question / réponse"],
    support: "Images de l'unité",
   },
   synthese: {
    ens: ["Donc : unité 3 réussie — la toilette, les dents, la comptine, le dialogue et le son an !"],
    app: ["Récitent la comptine de la toilette une dernière fois, avec les gestes."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le grand jeu : un élève mime un mot de l'unité, la classe devine et épelle le son an s'il y est."],
    app: ["Miment et devinent : savon, brosse à dents, lampe, banane, canard..."],
    technique: ["Jeu de mimes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : dis une phrase sur la toilette avec un mot en an."],
    app: ["R.A. : « Je me lave la ", { t: "maman", r: true }, "... » — phrase libre contenant un mot en ", { t: "an", r: true }, " (ex. : « Maman me donne le savon. »)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "40. BILAN DE L'UNITÉ 3",
    subs: [
     { t: "A. Ce que je sais dire", paras: [[{ t: "le savon, la serviette, le lavabo", k: true }, " — ", { t: "je prends mon bain", k: true }, " — ", { t: "je me brosse les dents", k: true }, " — ", { t: "propre / sale", k: true }]] },
     { t: "B. Ce que je sais lire et écrire", paras: [["Le son ", { t: "an", k: true }, " : ", { t: "lampe, banane, canard, pantalon, dent, maman", k: true }, " — « ", { t: "Papa a un pantalon.", k: true }, " »"]] },
    ],
    retenir: ["Unité 3 réussie : ", { t: "la toilette, les dents, la comptine et le son an", k: true }, " !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Coche ce que tu sais faire (ou dis-le) :"], items: [["1) Nommer 3 objets de la toilette : oui / non"], ["2) Dire la comptine de la toilette : oui / non"], ["3) Jouer « Tu es propre ? » : oui / non"], ["4) Lire 3 mots avec an : oui / non"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Le grand tri : entoure les mots du son an :"], items: [["maman"], ["savon"], ["dent"], ["jupe"], ["canard"], ["propre"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Dicte-toi : écris 2 mots avec an et 1 mot de la toilette :"], items: [["1) un mot avec an : ....... (dent, banane...)"], ["2) un autre mot avec an : ....... (lampe, canard...)"], ["3) un mot de la toilette : ....... (savon, serviette...)"], ["4) une phrase : « Maman allume la lampe. » (copie)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Bilan oral : l'élève coche ", { t: "oui", r: true }, " quand il maîtrise (auto-évaluation guidée)."]] },
    { titre: "Exercice 2", lines: [["Mots avec an : ", { t: "maman, dent, canard", r: true }, " (2 pts chacun) — savon, jupe, propre : pas de an."]] },
    { titre: "Exercice 3", lines: [["Réponses libres : 2 mots en ", { t: "an", r: true }, " + 1 mot de la ", { t: "toilette", r: true }, " + phrase copiée."]] },
   ],
  },
 ],
};

module.exports = { theme3 };
