// data-theme5.js — Unité 5 « Les cadeaux et les vêtements » (séances 53 à 65)
// Sources : FRA 10ème (T2 semaines 5-7 : cadeaux/vêtements, sons eil/ail, j, z) + PDF CP2 unité V (13 séances).
// sd par séance : EO s53-59, Lecture s60-63, Écriture s64-65. Barème 8+6+6 = 20 partout.

const theme5 = {
 numero: 5,
 nom: "Les cadeaux et les vêtements",
 sousDiscipline: "Expression Orale",
 notions: "Le vocabulaire des vêtements et des cadeaux, la politesse du cadeau, et les sons eil/ail, j et z.",
 competences: [
  "Nommer les vêtements : pantalon, robe, chemise, chapeau, chaussures.",
  "Dire ce qu'on porte : « Je mets..., je porte... » ; remercier pour un cadeau.",
  "Reconnaître et prononcer les sons eil/ail, j et z.",
  "Écrire des mots simples avec j et z.",
 ],
 seances: [
  {
   n: 53,
   titre: "Le vocabulaire des vêtements",
   titreFiche: "Les vêtements que je connais",
   sd: "Expression Orale",
   objectif: "Nommer les vêtements : le pantalon, la robe, la chemise, le chapeau, les chaussures.",
   supportFiche: "Image « les vêtements », vêtements réels ou dessins, tableau noir.",
   revision: {
    ens: ["Le grand bilan de l'école : dis ta phrase du cartable (2 élèves)."],
    app: ["R.A. : « ", { t: "Dans mon cartable, il y a...", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Ce matin, qu'avez-vous mis pour venir à l'école ? Montrez ! »"],
    app: ["Montrent et essaient : un pantalon, une robe, une chemise, des chaussures..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots des vêtements : pantalon, robe, chemise, chapeau, chaussures."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez l'image et les vêtements : » je montre chaque vêtement, les élèves le nomment."],
    app: ["Observent et nomment : le pantalon, la robe, la chemise, le chapeau, les chaussures."],
    technique: ["Observation guidée"],
    support: "Image « les vêtements », vêtements réels",
   },
   analyse: {
    ens: { paras: [["1) Qu'est-ce que tu portes sur tes jambes ?"], ["2) Qu'est-ce que Fara porte sur la tête ?"], ["3) Qu'est-ce que tu mets sur tes pieds ?"], ["4) Et ta maman, que porte-t-elle sur son corps ?"]] },
    app: { paras: [["R.A. : Un ", { t: "pantalon", r: true }, " (ou une robe)."], ["R.A. : Un ", { t: "chapeau", r: true }, "."], ["R.A. : Des ", { t: "chaussures", r: true }, "."], ["R.A. : Une ", { t: "robe", r: true }, " ou une ", { t: "chemise", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Image « les vêtements »",
   },
   synthese: {
    ens: ["Donc : les vêtements — le pantalon, la robe, la chemise, le chapeau, les chaussures."],
    app: ["Répètent les 5 mots en chœur en se touchant la partie du corps correspondante."],
    technique: ["Répétition collective"],
    support: "Image « les vêtements »",
   },
   application: {
    ens: ["Le jeu : je mime un vêtement, vous le nommez ; puis un élève mime à son tour."],
    app: ["Devinent et nomment : le chapeau ! les chaussures !..."],
    technique: ["Jeu de mimes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : nomme 3 vêtements."],
    app: ["R.A. : ", { t: "pantalon, robe, chemise, chapeau, chaussures", r: true }, " (3 mots corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "53. LE VOCABULAIRE DES VÊTEMENTS",
    subs: [
     { t: "A. Les vêtements", paras: [[{ t: "le pantalon", k: true }, " — ", { t: "la robe", k: true }, " — ", { t: "la chemise", k: true }, " — ", { t: "le chapeau", k: true }, " — ", { t: "les chaussures", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Je mets un pantalon et une chemise.", k: true }, " »"]] },
    ],
    retenir: ["Les vêtements : ", { t: "le pantalon, la robe, la chemise, le chapeau, les chaussures", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les vêtements :"], items: [["le pantalon"], ["le cahier"], ["la robe"], ["la gomme"], ["le chapeau"], ["le ballon"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Je mets un ....... sur mes jambes. (pantalon)"], ["2) Je mets des ....... sur mes pieds. (chaussures)"], ["3) Fara met une jolie ....... (robe)"], ["4) Sous le soleil, je mets un ....... (chapeau)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Mime et devine (4 tours) :"], items: [["1) Mime n°1 : le vêtement : ....... (réponse libre : le chapeau)"], ["2) Mime n°2 : le vêtement : ....... (les chaussures)"], ["3) Mime n°3 : le vêtement : ....... (le pantalon)"], ["4) Mime n°4 : le vêtement : ....... (la robe ou la chemise)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Vêtements entourés : ", { t: "le pantalon, la robe, le chapeau", r: true }, " (2 pts chacun) — cahier, gomme (école), ballon (jouet) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "pantalon", r: true }, " — 2) ", { t: "chaussures", r: true }, " — 3) ", { t: "robe", r: true }, " — 4) ", { t: "chapeau", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Vêtements correctement devinés : ", { t: "mimes bien interprétés", r: true }, " (1,5 pt par tour)."]] },
   ],
  },
  {
   n: 54,
   titre: "Je m'habille",
   titreFiche: "Les gestes de l'habillage",
   sd: "Expression Orale",
   objectif: "Dire les gestes de l'habillage : je mets, j'enlève, je boutonne, j'attache.",
   supportFiche: "Vêtements réels, mimes, tableau noir.",
   revision: {
    ens: ["Nomme 3 vêtements (chaîne parlée)."],
    app: ["R.A. : ", { t: "pantalon, robe, chemise, chapeau, chaussures", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Le matin, qui sait s'habiller tout seul ? Que faites-vous d'abord ? »"],
    app: ["Proposent : je mets la chemise, puis le pantalon, puis les chaussures..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous disons les gestes de l'habillage : je mets, j'enlève, je boutonne, j'attache."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » je mets le chapeau, puis je l'enlève ; je boutonne ma chemise, j'attache mes chaussures — je mime chaque geste en le nommant."],
    app: ["Observent : « je mets le chapeau », « j'enlève le chapeau », « je boutonne ma chemise », « j'attache mes chaussures »."],
    technique: ["Observation guidée"],
    support: "Vêtements réels",
   },
   analyse: {
    ens: { paras: [["1) Que fais-tu de ta veste quand tu as chaud ?"], ["2) Que fais-tu des boutons de ta chemise ?"], ["3) Que fais-tu des lacets de tes chaussures ?"], ["4) Que fais-tu de ton chapeau quand il pleut ?"]] },
    app: { paras: [["R.A. : Je l'", { t: "enlève", r: true }, "."], ["R.A. : Je les ", { t: "boutonne", r: true }, "."], ["R.A. : Je les ", { t: "attache", r: true }, "."], ["R.A. : Je le ", { t: "mets", r: true }, ". (ou : je le garde !)"]] },
    technique: ["Question / réponse"],
    support: "Vêtements réels",
   },
   synthese: {
    ens: ["Donc : je mets, j'enlève, je boutonne, j'attache — je sais m'habiller !"],
    app: ["Répètent les 4 gestes en les mimant en chœur."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Par 2 : l'un mime un geste d'habillage, l'autre le dit ; puis on échange."],
    app: ["Miment et disent : je mets / j'enlève / je boutonne / j'attache."],
    technique: ["Travail en binômes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["2 élèves : mime et dis « je boutonne ma chemise »."],
    app: ["R.A. : geste et phrase : ", { t: "je boutonne", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "54. JE M'HABILLE",
    subs: [
     { t: "A. Les gestes", paras: [[{ t: "je mets", k: true }, " — ", { t: "j'enlève", k: true }, " — ", { t: "je boutonne", k: true }, " — ", { t: "j'attache", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Je mets ma chemise, je boutonne et j'attache mes chaussures.", k: true }, " »"]] },
    ],
    retenir: ["Pour m'habiller : ", { t: "je mets, j'enlève, je boutonne, j'attache", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Choisis le bon mot et dis-le :"], items: [["1) Il fait chaud : je mets / j'enlève ma veste."], ["2) Je ....... mes chaussures (les lacets). : boutonne / attache"], ["3) Je ....... ma chemise (les boutons). : boutonne / enlève"], ["4) Le matin, je ....... mes vêtements. : mets / enlève"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Je ....... mon chapeau. (mets)"], ["2) Je ....... ma veste, il fait chaud. (enlève)"], ["3) Je ....... ma chemise. (boutonne)"], ["4) J'....... mes chaussures. (attache)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Ordonne ton habillage (1, 2, 3, 4) :"], items: [["....... j'attache mes chaussures"], ["....... je mets ma chemise"], ["....... je boutonne ma chemise"], ["....... je mets mon pantalon"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "j'enlève", r: true }, " — 2) ", { t: "attache", r: true }, " — 3) ", { t: "boutonne", r: true }, " — 4) ", { t: "mets", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "mets", r: true }, " — 2) ", { t: "enlève", r: true }, " — 3) ", { t: "boutonne", r: true }, " — 4) ", { t: "attache", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Ordre possible : ", { t: "4 je mets le pantalon — 2 la chemise — 3 je boutonne — 1 j'attache les chaussures", r: true }, "."]] },
   ],
  },
  {
   n: 55,
   titre: "Merci pour ton cadeau",
   titreFiche: "Le cadeau et la politesse",
   sd: "Expression Orale",
   objectif: "Dire ce qu'est un cadeau et remercier : « Merci pour ton beau cadeau ! ».",
   supportFiche: "Un cadeau emballé réel ou image « le cadeau », tableau noir.",
   revision: {
    ens: ["Mime un geste d'habillage, les autres devinent."],
    app: ["R.A. : ", { t: "je mets / j'enlève / je boutonne / j'attache", r: true }, "."],
    technique: ["Jeu de mimes"],
   },
   miseEnSituation: {
    ens: ["« Qui a déjà reçu un cadeau ? Qu'est-ce que tu as dit ? »"],
    app: ["Racon tent : un jouet, un habit... ; « merci » !"],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots du cadeau et la politesse du merci."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez ce paquet : » je montre le cadeau emballé, je le déballe en mimant la surprise et le merci."],
    app: ["Observent : un paquet avec un beau ruban ; à l'intérieur, un cadeau ; on dit merci !"],
    technique: ["Observation guidée"],
    support: "Cadeau emballé",
   },
   analyse: {
    ens: { paras: [["1) Comment s'appelle le paquet qu'on offre ?"], ["2) Que dit-on quand on reçoit un cadeau ?"], ["3) Que dit la personne qui donne ?"], ["4) Quand offre-t-on des cadeaux ?"]] },
    app: { paras: [["R.A. : Un ", { t: "cadeau", r: true }, "."], ["R.A. : « ", { t: "Merci pour ton beau cadeau !", r: true }, " »"], ["R.A. : « ", { t: "Tiens, c'est pour toi !", r: true }, " »"], ["R.A. : À une ", { t: "fête, à un anniversaire...", r: true }, " (réponses libres)."]] },
    technique: ["Question / réponse"],
    support: "Cadeau emballé",
   },
   synthese: {
    ens: ["Donc : cadeau — « Tiens, c'est pour toi ! — Merci pour ton beau cadeau ! » : les mots polis du cadeau."],
    app: ["Répètent les répliques en chœur avec le geste d'offrir."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Par 2 : l'un offre un cadeau imaginaire, l'autre remercie ; puis on échange."],
    app: ["Jouent la scène ; 2 binômes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["2 élèves : joue la scène du cadeau."],
    app: ["R.A. : « ", { t: "Tiens, c'est pour toi ! — Merci pour ton beau cadeau !", r: true }, " »"],
    technique: ["Binôme"],
   },
   lecon: {
    titre: "55. MERCI POUR TON CADEAU",
    subs: [
     { t: "A. Les mots du cadeau", paras: [[{ t: "le cadeau", k: true }, " — ", { t: "le paquet", k: true }, " — ", { t: "le ruban", k: true }, " — ", { t: "offrir", k: true }]] },
     { t: "B. Le dialogue", paras: [["« — ", { t: "Tiens, c'est pour toi !", k: true }, " — ", { t: "Merci pour ton beau cadeau !", k: true }, " »"]] },
    ],
    retenir: ["Quand je reçois un cadeau, je dis : « ", { t: "Merci !", k: true }, " »"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les répliques dans l'ordre (1, 2, 3, 4) :"], items: [["....... — Merci pour ton beau cadeau !"], ["....... — Tiens, c'est pour toi !"], ["....... — De rien, mon ami !"], ["....... — Oh ! Un beau cadeau, merci !"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le paquet avec un ruban : c'est un ....... (cadeau)"], ["2) « ......., c'est pour toi ! » (tiens)"], ["3) « Merci pour ton beau ....... ! » (cadeau)"], ["4) J'offre, tu réponds : ....... (merci)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène du cadeau avec ton camarade :"], items: [["1) Celui qui donne dit : ....... (« Tiens, c'est pour toi ! »)"], ["2) Celui qui reçoit dit : ....... (« Merci pour ton beau cadeau ! »)"], ["3) On répond à merci par : ....... (« de rien »)"], ["4) Le cadeau est dans un ....... (paquet)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "3 — 1 — 4 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "cadeau", r: true }, " — 2) ", { t: "tiens", r: true }, " — 3) ", { t: "cadeau", r: true }, " — 4) ", { t: "merci", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "« Tiens, c'est pour toi ! »", r: true }, " — 2) ", { t: "« Merci pour ton beau cadeau ! »", r: true }, " — 3) ", { t: "« de rien »", r: true }, " — 4) ", { t: "paquet", r: true }, "."]] },
   ],
  },
  {
   n: 56,
   titre: "Le dialogue : qu'est-ce que tu mets ?",
   titreFiche: "Je questionne sur les vêtements",
   sd: "Expression Orale",
   objectif: "Jouer un dialogue : « Qu'est-ce que tu mets aujourd'hui ? — Je mets ma robe rouge. ».",
   supportFiche: "Vêtements réels, tableau noir.",
   revision: {
    ens: ["Joue la scène du cadeau (1 binôme)."],
    app: ["R.A. : « ", { t: "Tiens, c'est pour toi ! — Merci !", r: true }, " »"],
    technique: ["Binôme"],
   },
   miseEnSituation: {
    ens: ["« Ta maman te demande ce matin : qu'est-ce que tu mets aujourd'hui ? Que réponds-tu ? »"],
    app: ["Proposent : je mets mon pantalon bleu, ma chemise..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous jouons le dialogue des vêtements : « Qu'est-ce que tu mets ? — Je mets... »"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez le dialogue : » je le joue avec un élève."],
    app: ["Écoutent : « — Qu'est-ce que tu mets aujourd'hui, Soa ? — Je mets ma robe rouge et mes chaussures noires. — C'est très joli ! »"],
    technique: ["Écoute active"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Que demande la maman à Soa ?"], ["2) Que répond Soa ?"], ["3) Que dit la maman à la fin ?"], ["4) Repose la question à ton tour."]] },
    app: { paras: [["R.A. : « ", { t: "Qu'est-ce que tu mets aujourd'hui ?", r: true }, " »"], ["R.A. : « ", { t: "Je mets ma robe rouge...", r: true }, " »"], ["R.A. : « ", { t: "C'est très joli !", r: true }, " »"], ["R.A. : « ", { t: "Qu'est-ce que tu mets ?", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : « Qu'est-ce que tu mets ? — Je mets... » + une couleur : c'est joli !"],
    app: ["Répètent les répliques par moitiés de classe."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Par 2 : jouez le dialogue avec vos vrais vêtements, puis échangez les rôles."],
    app: ["Jouent : robe, pantalon, chemise + couleur ; 2 binômes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["1 binôme : jouez le dialogue."],
    app: ["R.A. : répliques correctes : ", { t: "« Qu'est-ce que tu mets ? — Je mets... »", r: true }, "."],
    technique: ["Binôme"],
   },
   lecon: {
    titre: "56. LE DIALOGUE : QU'EST-CE QUE TU METS ?",
    subs: [
     { t: "A. Le dialogue", paras: [["« — ", { t: "Qu'est-ce que tu mets aujourd'hui ?", k: true }, " — ", { t: "Je mets ma robe rouge.", k: true }, " »"], ["« — ", { t: "C'est très joli !", k: true }, " »"]] },
    ],
    retenir: ["« ", { t: "Qu'est-ce que tu mets ? — Je mets...", k: true }, " » + la couleur."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les répliques dans l'ordre (1, 2, 3, 4) :"], items: [["....... — C'est très joli !"], ["....... — Qu'est-ce que tu mets aujourd'hui, Soa ?"], ["....... — Je mets ma robe rouge et mes chaussures noires."], ["....... — Ma robe rouge et mes chaussures noires ? Oui, regarde !"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) « Qu'est-ce que tu ....... aujourd'hui ? » (mets)"], ["2) « Je ....... ma robe rouge. » (mets)"], ["3) « C'est très ....... ! » (joli)"], ["4) « Ma robe est ....... » (une couleur : rouge)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue avec ton camarade :"], items: [["1) La question : ....... (« Qu'est-ce que tu mets aujourd'hui ? »)"], ["2) La réponse avec ton vrai vêtement : ....... (« Je mets... »)"], ["3) Le compliment : ....... (« C'est très joli ! »)"], ["4) Une couleur que tu connais : ....... (rouge, bleu, jaune...)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "4 — 1 — 3 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "mets", r: true }, " — 2) ", { t: "mets", r: true }, " — 3) ", { t: "joli", r: true }, " — 4) ", { t: "rouge", r: true }, " (ou autre couleur)."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "« Qu'est-ce que tu mets aujourd'hui ? »", r: true }, " — 2) ", { t: "« Je mets... »", r: true }, " — 3) ", { t: "« C'est très joli ! »", r: true }, " — 4) ", { t: "une couleur correcte", r: true }, "."]] },
   ],
  },
  {
   n: 57,
   titre: "La comptine des vêtements",
   titreFiche: "Ma comptine : je m'habille et je suis content",
   sd: "Expression Orale",
   objectif: "Réciter la comptine des vêtements avec les gestes.",
   supportFiche: "Comptine au tableau, image « les vêtements ».",
   revision: {
    ens: ["Joue le dialogue des vêtements (1 binôme)."],
    app: ["R.A. : « ", { t: "Qu'est-ce que tu mets ? — Je mets...", r: true }, " »"],
    technique: ["Binôme"],
   },
   miseEnSituation: {
    ens: ["« La famille, la toilette, l'école ont leurs comptines. Et les vêtements ? Écoutez ! »"],
    app: ["Écoutent, curieux."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons la comptine des vêtements."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez : » je récite deux fois avec les gestes."],
    app: ["Écoutent : « Pantalon, robe et chemise, / quand je m'habille, tout me plaît ; / chapeau, chaussures et gilet, / je suis beau, je suis à l'aise ! »"],
    technique: ["Écoute active"],
    support: "Comptine au tableau",
   },
   analyse: {
    ens: { paras: [["1) Cite les 3 vêtements du premier vers."], ["2) Cite les 3 choses du troisième vers."], ["3) Comment est l'enfant à la fin ?"], ["4) Répète le dernier vers."]] },
    app: { paras: [["R.A. : ", { t: "pantalon, robe, chemise", r: true }, "."], ["R.A. : ", { t: "chapeau, chaussures, gilet", r: true }, "."], ["R.A. : ", { t: "Beau et à l'aise", r: true }, "."], ["R.A. : ", { t: "Je suis beau, je suis à l'aise !", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Comptine au tableau",
   },
   synthese: {
    ens: ["Donc : ma comptine — pantalon, robe, chemise, chapeau, chaussures, gilet : je suis à l'aise !"],
    app: ["Répètent les 4 vers ligne par ligne avec les gestes."],
    technique: ["Répétition collective"],
    support: "Comptine au tableau",
   },
   application: {
    ens: ["Par 2 : récite la comptine avec les gestes."],
    app: ["Récitent en binômes ; 2 groupes devant la classe."],
    technique: ["Travail en binômes"],
    support: "Comptine au tableau",
   },
   evaluation: {
    ens: ["2 élèves : récite la comptine."],
    app: ["R.A. : au moins 3 vers corrects : ", { t: "pantalon-robe-chemise / chapeau-chaussures-gilet / à l'aise", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "57. LA COMPTINE DES VÊTEMENTS",
    subs: [
     { t: "A. La comptine", paras: [["« ", { t: "Pantalon, robe et chemise,", k: true }, " » — « ", { t: "quand je m'habille, tout me plaît ;", k: true }, " »"], ["« ", { t: "chapeau, chaussures et gilet,", k: true }, " » — « ", { t: "je suis beau, je suis à l'aise !", k: true }, " »"]] },
    ],
    retenir: ["Ma comptine : « ", { t: "Je suis beau, je suis à l'aise !", k: true }, " » — je la connais par cœur !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les vers dans l'ordre (1, 2, 3, 4) :"], items: [["....... je suis beau, je suis à l'aise !"], ["....... Pantalon, robe et chemise,"], ["....... chapeau, chaussures et gilet,"], ["....... quand je m'habille, tout me plaît ;"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la comptine :"], items: [["1) ......., robe et chemise (pantalon)"], ["2) Quand je m'......., tout me plaît (habille)"], ["3) Chapeau, ....... et gilet (chaussures)"], ["4) Je suis beau, je suis à l'....... (aise)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Récite avec les gestes (2 élèves, 2 vers chacun) :"], items: [["1) Vers 1 : touche ....... (pantalon, chemise)"], ["2) Vers 2 : le sourire : ....... (tout me plaît)"], ["3) Vers 3 : touche ta tête et tes pieds : ....... (chapeau, chaussures)"], ["4) Vers 4 : le pouce levé : ....... (je suis à l'aise)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "4 — 1 — 3 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "pantalon", r: true }, " — 2) ", { t: "habille", r: true }, " — 3) ", { t: "chaussures", r: true }, " — 4) ", { t: "aise", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Gestes corrects : ", { t: "vêtements, sourire, chapeau-chaussures, pouce levé", r: true }, "."]] },
   ],
  },
  {
   n: 58,
   titre: "Je porte ma belle tenue",
   titreFiche: "Énumérer ma tenue",
   sd: "Expression Orale",
   objectif: "Énumérer sa tenue : « Je porte..., ..., et... ».",
   supportFiche: "Image « les vêtements », tableau noir.",
   revision: {
    ens: ["Récite ta comptine des vêtements (2 élèves)."],
    app: ["R.A. : les 4 vers de la ", { t: "comptine", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Dans ma classe, il y a..., vous connaissez ! Et vous, que portez-vous aujourd'hui ? »"],
    app: ["Essaient : je porte un pantalon, une chemise, des chaussures..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous faisons notre liste : « Je porte..., ..., et... »"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez ma liste : » je nomme ma tenue complète en la montrant."],
    app: ["Écoutent : je porte une chemise, un pantalon, un chapeau et des chaussures."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Avec quel mot commence ma liste ?"], ["2) Quel mot met-on avant la dernière chose ?"], ["3) Fara porte une robe : quelle est sa liste ?"], ["4) Ajoute un vêtement à ma liste."]] },
    app: { paras: [["R.A. : « ", { t: "Je porte...", r: true }, " »"], ["R.A. : ", { t: "Et", r: true }, "."], ["R.A. : « ", { t: "Je porte une robe et des chaussures.", r: true }, " »"], ["R.A. : ", { t: "et un chapeau", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : ma tenue — « Je porte..., ..., et... » : je fais ma liste sans oublier « et »."],
    app: ["Répètent le modèle en chœur, puis chacun ajoute un vêtement."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Chacun votre tour : dis ta tenue complète (3 vêtements au moins)."],
    app: ["Disent leur liste avec « je porte » et « et »."],
    technique: ["Chaîne parlée"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : liste de 3 vêtements."],
    app: ["R.A. : liste correcte avec ", { t: "« je porte » et « et »", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "58. JE PORTE MA BELLE TENUE",
    subs: [
     { t: "A. Ma liste", paras: [["« ", { t: "Je porte une chemise, un pantalon et des chaussures.", k: true }, " »"]] },
     { t: "B. Le secret", paras: [["Je répète ", { t: "je porte", k: true }, " et je termine avec ", { t: "et", k: true }, " !"]] },
    ],
    retenir: ["Ma tenue : « ", { t: "Je porte..., ..., et...", k: true }, " »."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écoute la liste et coche les vêtements entendus :"], items: [["1) une chemise : oui / non"], ["2) une robe : oui / non"], ["3) un pantalon : oui / non"], ["4) des chaussures : oui / non"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la liste :"], items: [["1) Je ....... une chemise (porte)"], ["2) Je porte un ....... (pantalon)"], ["3) Je porte un chapeau ....... des chaussures (et)"], ["4) Le mot du début : ....... (je porte)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Fais ta liste (3 vêtements) :"], items: [["1) Premier vêtement : ....... (libre)"], ["2) Deuxième vêtement : ....... (libre)"], ["3) Troisième avec « et » : ....... (et des chaussures)"], ["4) Tes mots magiques : ....... (« je porte » et « et »)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entendus : ", { t: "une chemise, un pantalon, des chaussures (oui)", r: true }, " — la robe (non)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "porte", r: true }, " — 2) ", { t: "pantalon", r: true }, " — 3) ", { t: "et", r: true }, " — 4) ", { t: "je porte", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Liste personnelle correcte : ", { t: "« je porte » au début, « et » avant le dernier", r: true }, "."]] },
   ],
  },
  {
   n: 59,
   titre: "Mon beau cadeau",
   titreFiche: "Décrire son cadeau",
   sd: "Expression Orale",
   objectif: "Décrire un cadeau reçu : « C'est un jouet. Il est bleu. Je l'aime bien. ».",
   supportFiche: "Jouet ou image « le cadeau », tableau noir.",
   revision: {
    ens: ["Dis ta tenue complète (2 élèves)."],
    app: ["R.A. : « ", { t: "Je porte..., ..., et...", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Rova a reçu un cadeau : un jouet. Comment peut-il le décrire à son cousin ? »"],
    app: ["Proposent : dire sa couleur, sa taille, si on l'aime..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous décrivons un cadeau : ce que c'est, sa couleur, si on l'aime."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez mon jouet et écoutez : » je décris un jouet en 3 phrases."],
    app: ["Écoutent : c'est un ballon. Il est rouge et blanc. Je l'aime bien, merci papa !"],
    technique: ["Observation guidée"],
    support: "Jouet réel ou image",
   },
   analyse: {
    ens: { paras: [["1) Par quoi commence la description ? (« C'est... »)"], ["2) Après, que dit-on du cadeau ? (sa couleur)"], ["3) Comment termine-t-on ?"], ["4) Décris ce jouet en une phrase."]] },
    app: { paras: [["R.A. : « ", { t: "C'est...", r: true }, " »"], ["R.A. : ", { t: "Il est...", r: true }, " (la couleur)."], ["R.A. : « ", { t: "Je l'aime bien.", r: true }, " »"], ["R.A. : ", { t: "« C'est une poupée. Elle est rose. »", r: true }, " (libre)"]] },
    technique: ["Question / réponse"],
    support: "Jouet, tableau noir",
   },
   synthese: {
    ens: ["Donc : je décris mon cadeau — « C'est... Il/Elle est... (couleur). Je l'aime bien. »"],
    app: ["Répètent le modèle en chœur, puis chacun décrit un cadeau imaginaire."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Chacun votre tour : décris ton cadeau rêvé en 3 phrases."],
    app: ["Décrivent : c'est..., il/elle est..., je l'aime bien."],
    technique: ["Chaîne parlée"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : décris ton cadeau en 3 phrases."],
    app: ["R.A. : description complète : ", { t: "c'est... / il-elle est... / je l'aime bien", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "59. MON BEAU CADEAU",
    subs: [
     { t: "A. Ma description", paras: [["« ", { t: "C'est un ballon. Il est rouge et blanc. Je l'aime bien.", k: true }, " »"]] },
     { t: "B. Le secret", paras: [[{ t: "C'est...", k: true }, " + ", { t: "Il / Elle est...", k: true }, " (couleur) + ", { t: "Je l'aime bien.", k: true }]] },
    ],
    retenir: ["Je décris mon cadeau : « ", { t: "C'est... Il est... Je l'aime bien.", k: true }, " »"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets la description dans l'ordre (1, 2, 3, 4) :"], items: [["....... Je l'aime bien, merci maman !"], ["....... C'est une poupée."], ["....... Elle est rose et blanche."], ["....... Elle a un joli chapeau rose."]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) « ....... un ballon. » (c'est)"], ["2) « Il est ....... » (une couleur : rouge)"], ["3) « Je l'....... bien. » (aime)"], ["4) « ....... pour ton cadeau ! » (merci)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Décris ton cadeau rêvé (3 phrases) :"], items: [["1) C'est... : ....... (libre : un jouet)"], ["2) Il / Elle est... : ....... (une couleur)"], ["3) Je l'aime bien / merci : ....... (phrase complète)"], ["4) Le mot de politesse : ....... (merci)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "4 — 1 — 3 — 2", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "c'est", r: true }, " — 2) ", { t: "rouge", r: true }, " (ou autre couleur) — 3) ", { t: "aime", r: true }, " — 4) ", { t: "merci", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Description personnelle complète : ", { t: "c'est... / il-elle est... / je l'aime bien", r: true }, "."]] },
   ],
  },
  {
   n: 60,
   titre: "Le son eil — découverte",
   titreFiche: "Je découvre le son eil",
   sd: "Lecture",
   objectif: "Reconnaître et prononcer le son eil : soleil, oreille, réveil, pareille.",
   supportFiche: "Image « le son eil », étiquettes mots, tableau noir.",
   revision: {
    ens: ["Décris ton cadeau rêvé (2 élèves)."],
    app: ["R.A. : « ", { t: "C'est... Il est... Je l'aime bien.", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Répétez : eil, eil, eil... appuyez votre langue un peu de côté et souriez ! »"],
    app: ["Répètent le son eil : soleil, oreille..."],
    technique: ["Répétition articulée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son eil : soleil, oreille, réveil, pareille."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Image « le son eil »",
   },
   observation: {
    ens: ["« Observez les images et écoutez : le SOLEIL, l'OREILLE, le RÉVEIL. Entendez-vous eil ? »"],
    app: ["Observent et entendent eil à la fin de chaque mot ; ils le répètent."],
    technique: ["Observation guidée"],
    support: "Image « le son eil »",
   },
   analyse: {
    ens: { paras: [["1) Quel son entends-tu à la fin de « soleil » ?"], ["2) Avec combien de lettres écrit-on eil ?"], ["3) Où est le son eil dans ces mots ?"], ["4) Cite un mot avec eil."]] },
    app: { paras: [["R.A. : Le son ", { t: "eil", r: true }, "."], ["R.A. : ", { t: "Trois lettres : e-i-l", r: true }, "."], ["R.A. : À ", { t: "la fin", r: true }, "."], ["R.A. : ", { t: "le réveil, pareille", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Image « le son eil », étiquettes",
   },
   synthese: {
    ens: ["Donc : le son eil s'écrit e-i-l, à la fin : soleil, oreille, réveil, pareille."],
    app: ["Répètent les 4 mots en chœur en pointant la fin du mot."],
    technique: ["Répétition collective"],
    support: "Image « le son eil »",
   },
   application: {
    ens: ["Le jeu du tam-tam : frappez des mains quand vous entendez eil."],
    app: ["Frappent : soleil, oreille, réveil ; ne frappent pas : ballon, chat, gomme."],
    technique: ["Jeu d'écoute"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : prononce « soleil, oreille, réveil »."],
    app: ["R.A. : ", { t: "soleil, oreille, réveil", r: true }, " (son eil correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "60. LE SON EIL",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "eil", k: true }, " s'écrit avec ", { t: "trois lettres : e-i-l", k: true }, ", à la fin du mot."]] },
     { t: "B. Les mots", paras: [[{ t: "le soleil", k: true }, " — ", { t: "l'oreille", k: true }, " — ", { t: "le réveil", k: true }, " — ", { t: "pareille", k: true }]] },
    ],
    retenir: ["Le son ", { t: "eil", k: true }, " : ", { t: "soleil, oreille, réveil, pareille", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son eil :"], items: [["soleil"], ["ballon"], ["oreille"], ["chat"], ["réveil"], ["gomme"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entends-tu eil ? Dis oui ou non :"], items: [["1) pareille : oui / non"], ["2) chaussure : oui / non"], ["3) soleil : oui / non"], ["4) maison : oui / non"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Répète avec le sourire :"], items: [["1) eil... eil... — ....... (soleil)"], ["2) eil... eil... — ....... (oreille)"], ["3) eil... eil... — ....... (réveil)"], ["4) eil... eil... — ....... (pareille)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "soleil, oreille, réveil", r: true }, " (2 pts chacun) — ballon (on), chat, gomme : non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oui", r: true }, " — 2) ", { t: "non", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "non", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Prononciation correcte : ", { t: "soleil, oreille, réveil, pareille", r: true }, "."]] },
   ],
  },
  {
   n: 61,
   titre: "Le son ail — lecture",
   titreFiche: "Le son eil et le son ail",
   sd: "Lecture",
   objectif: "Lire des mots et des phrases avec eil et ail : travail, soleil ; distinguer les deux.",
   supportFiche: "Étiquettes mots, phrases au tableau, image « le son eil ».",
   revision: {
    ens: ["Cite 2 mots avec eil (chaîne parlée)."],
    app: ["R.A. : ", { t: "soleil, oreille, réveil, pareille", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Soleil... travail : le son de la fin est-il pareil ? Écoutez bien ! »"],
    app: ["Écoutent : eil et ail se ressemblent ; le a change un peu le son."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons eil et ail : le soleil, mon oreille ; le travail, l'ail."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Étiquettes mots",
   },
   observation: {
    ens: ["« Observez les étiquettes : » montre les mots ; les élèves lisent d'abord seuls, puis ensemble."],
    app: ["Lisent : le soleil, l'oreille, le réveil ; le travail, l'ail, le portefeuille? (non : le travail, l'ail)."],
    technique: ["Lecture individuelle puis collective"],
    support: "Étiquettes mots",
   },
   analyse: {
    ens: { paras: [["1) Lis « soleil » : quel son à la fin ?"], ["2) Lis « travail » : quel son à la fin ?"], ["3) Quelle est la différence entre les deux fins ?"], ["4) Lis : « Je lève le bras et je travaille. » : où sont eil et ail ?"]] },
    app: { paras: [["R.A. : ", { t: "eil", r: true }, "."], ["R.A. : ", { t: "ail", r: true }, "."], ["R.A. : ", { t: "e ou a devant i-l", r: true }, "."], ["R.A. : ", { t: "travaille (ail), bras... (non)", r: true }, " — le son ail dans travaille."]] },
    technique: ["Question / réponse"],
    support: "Étiquettes, phrases au tableau",
   },
   synthese: {
    ens: ["Donc : eil (soleil, oreille) et ail (travail, ail) — deux sons cousins, je lis bien les deux !"],
    app: ["Relisent les mots en alternant eil / ail avec le doigt."],
    technique: ["Répétition collective"],
    support: "Étiquettes mots",
   },
   application: {
    ens: ["Par 2 : lisez les mots chacun votre tour ; ton camarade dit eil ou ail."],
    app: ["Lisent et classent les mots en binômes."],
    technique: ["Travail en binômes"],
    support: "Étiquettes mots",
   },
   evaluation: {
    ens: ["3 élèves : lis 2 mots au choix."],
    app: ["R.A. : lecture correcte : ", { t: "soleil, oreille, réveil, travail, ail", r: true }, " (au moins 2)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "61. LE SON EIL ET LE SON AIL",
    subs: [
     { t: "A. Les mots", paras: [[{ t: "le soleil", k: true }, " — ", { t: "l'oreille", k: true }, " — ", { t: "le réveil", k: true }, " / ", { t: "le travail", k: true }, " — ", { t: "l'ail", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Sous le soleil, je travaille avec le sourire.", k: true }, " » (eil et ail !)"]] },
    ],
    retenir: [{ t: "eil", k: true }, " : soleil, oreille — ", { t: "ail", k: true }, " : travail, ail."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Lis et classe : coche la bonne fin (eil ou ail) :"], items: [["1) sole.... (eil)"], ["2) trav.... (ail)"], ["3) ore.... (eil)"], ["4) l'a.... → l'ail (ail)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entoure les mots avec eil ou ail :"], items: [["le réveil"], ["la gomme"], ["le travail"], ["le bonbon"], ["pareille"], ["le chapeau"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis les phrases à ton camarade :"], items: [["1) « Le soleil brille. » (brille : il!)"], ["2) « Mon oreille entend. »"], ["3) « Papa va au travail. »"], ["4) « J'aime l'ail dans la salade. »"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "eil", r: true }, " — 2) ", { t: "ail", r: true }, " — 3) ", { t: "eil", r: true }, " — 4) ", { t: "l'ail", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["Entourés : ", { t: "le réveil, le travail, pareille", r: true }, " (2 pts chacun) — gomme, bonbon, chapeau : non."]] },
    { titre: "Exercice 3", lines: [["Lecture fluide : ", { t: "soleil/brille, oreille, travail, ail", r: true }, "."]] },
   ],
  },
  {
   n: 62,
   titre: "Le son j — découverte",
   titreFiche: "Je découvre le son j",
   sd: "Lecture",
   objectif: "Reconnaître et prononcer le son j : jardin, jaune, jouet, jambon.",
   supportFiche: "Image « le son j », étiquettes mots, tableau noir.",
   revision: {
    ens: ["Lis : soleil, travail (2 élèves)."],
    app: ["R.A. : ", { t: "soleil (eil), travail (ail)", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Répétez : j, j, j... comme quand tu dis déjà ! »"],
    app: ["Répètent le son j : la langue près du palais, le son doux : jjj."],
    technique: ["Répétition articulée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son j : jardin, jaune, jouet, jambon."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Image « le son j »",
   },
   observation: {
    ens: ["« Observez les images et écoutez : le JARDIN, le JOUET, le JAMBON. Entendez-vous j au début ? »"],
    app: ["Observent et entendent j au début de chaque mot ; ils le répètent."],
    technique: ["Observation guidée"],
    support: "Image « le son j »",
   },
   analyse: {
    ens: { paras: [["1) Quel son entends-tu au début de « jardin » ?"], ["2) Avec quelle lettre écrit-on ce son ici ?"], ["3) Où est le son j dans « jouet » ?"], ["4) Cite un mot avec j."]] },
    app: { paras: [["R.A. : Le son ", { t: "j", r: true }, "."], ["R.A. : La lettre ", { t: "j", r: true }, "."], ["R.A. : Au ", { t: "début", r: true }, "."], ["R.A. : ", { t: "jaune, jambon, jouet", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Image « le son j », étiquettes",
   },
   synthese: {
    ens: ["Donc : le son j s'écrit avec la lettre j, au début : jardin, jaune, jouet, jambon."],
    app: ["Répètent les 4 mots en chœur avec le geste du jjj doux."],
    technique: ["Répétition collective"],
    support: "Image « le son j »",
   },
   application: {
    ens: ["Le jeu du tam-tam : frappez des mains quand vous entendez j."],
    app: ["Frappent : jardin, jouet, jaune ; ne frappent pas : soleil, chat, gomme."],
    technique: ["Jeu d'écoute"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : prononce « jardin, jouet, jambon »."],
    app: ["R.A. : ", { t: "jardin, jouet, jambon", r: true }, " (son j correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "62. LE SON J",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "j", k: true }, " s'écrit avec la lettre ", { t: "j", k: true }, " — un son doux, au début du mot."]] },
     { t: "B. Les mots", paras: [[{ t: "le jardin", k: true }, " — ", { t: "jaune", k: true }, " — ", { t: "le jouet", k: true }, " — ", { t: "le jambon", k: true }]] },
    ],
    retenir: ["Le son ", { t: "j", k: true }, " : ", { t: "jardin, jaune, jouet, jambon", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son j :"], items: [["jardin"], ["soleil"], ["jouet"], ["gomme"], ["jaune"], ["pantalon"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entends-tu j ? Dis oui ou non :"], items: [["1) jambon : oui / non"], ["2) réveil : oui / non"], ["3) jouet : oui / non"], ["4) maison : oui / non"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Répète doucement :"], items: [["1) jjj... — ....... (jardin)"], ["2) jjj... — ....... (jouet)"], ["3) jjj... — ....... (jaune)"], ["4) jjj... — ....... (jambon)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "jardin, jouet, jaune", r: true }, " (2 pts chacun) — soleil, gomme, pantalon : non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oui", r: true }, " — 2) ", { t: "non", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "non", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Prononciation correcte : ", { t: "jardin, jouet, jaune, jambon", r: true }, "."]] },
   ],
  },
  {
   n: 63,
   titre: "Le son z — lecture",
   titreFiche: "Le son z : le zèbre et le zébu",
   sd: "Lecture",
   objectif: "Reconnaître et prononcer le son z : zèbre, zébu ; lire des phrases.",
   supportFiche: "Image « le son z » (zèbre, zébu), tableau noir.",
   revision: {
    ens: ["Cite 2 mots avec j (chaîne parlée)."],
    app: ["R.A. : ", { t: "jardin, jaune, jouet, jambon", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Répétez : z, z, z... comme l'abeille : zzzz ! »"],
    app: ["Répètent le son z : zzzz, comme un bourdonnement."],
    technique: ["Répétition articulée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son z : le zèbre, le zébu — les animaux rayés !"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Image « le son z »",
   },
   observation: {
    ens: ["« Observez les images : » je montre le zèbre et le zébu ; les élèves décrivent les rayures puis lisent les mots."],
    app: ["Observent et lisent : le zèbre (rayures noires et blanches), le zébu (la bosse)."],
    technique: ["Observation guidée"],
    support: "Image « le son z »",
   },
   analyse: {
    ens: { paras: [["1) Quel son entends-tu au début de « zèbre » ?"], ["2) Avec quelle lettre écrit-on ce son ici ?"], ["3) Le zébu vit dans les champs de Madagascar : répète « zébu »."], ["4) Cite un mot avec z."]] },
    app: { paras: [["R.A. : Le son ", { t: "z", r: true }, "."], ["R.A. : La lettre ", { t: "z", r: true }, "."], ["R.A. : ", { t: "zébu", r: true }, "."], ["R.A. : ", { t: "zèbre, zébu", r: true }, " (libre)."]] },
    technique: ["Question / réponse"],
    support: "Image « le son z »",
   },
   synthese: {
    ens: ["Donc : le son z s'écrit avec la lettre z : zèbre, zébu — zzzz !"],
    app: ["Répètent les mots en chœur avec le bourdonnement zzzz."],
    technique: ["Répétition collective"],
    support: "Image « le son z »",
   },
   application: {
    ens: ["Le jeu du tam-tam : frappez des mains quand vous entendez z."],
    app: ["Frappent : zèbre, zébu ; ne frappent pas : jardin, soleil, chat."],
    technique: ["Jeu d'écoute"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["2 élèves : prononce « zèbre, zébu »."],
    app: ["R.A. : ", { t: "zèbre, zébu", r: true }, " (son z correct)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "63. LE SON Z",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "z", k: true }, " s'écrit avec la lettre ", { t: "z", k: true }, " — comme l'abeille : zzzz !"]] },
     { t: "B. Les mots", paras: [[{ t: "le zèbre", k: true }, " — ", { t: "le zébu", k: true }, " (l'animal des champs de Madagascar)"]] },
    ],
    retenir: ["Le son ", { t: "z", k: true }, " : ", { t: "zèbre, zébu", k: true }, " — zzzz !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots avec le son z :"], items: [["zèbre"], ["jardin"], ["zébu"], ["jouet"], ["zigzag"], ["soleil"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entends-tu z ? Dis oui ou non :"], items: [["1) zèbre : oui / non"], ["2) jambon : oui / non"], ["3) zébu : oui / non"], ["4) gomme : oui / non"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Répète comme l'abeille :"], items: [["1) zzzz... — ....... (zèbre)"], ["2) zzzz... — ....... (zébu)"], ["3) Une phrase : « Le zèbre a des rayures. »"], ["4) Une phrase : « Le zébu est grand. »"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "zèbre, zébu, zigzag", r: true }, " (2 pts chacun) — jardin, jouet (j !), soleil : non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oui", r: true }, " — 2) ", { t: "non", r: true }, " — 3) ", { t: "oui", r: true }, " — 4) ", { t: "non", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Prononciation et phrases correctes : ", { t: "zèbre, zébu", r: true }, "."]] },
   ],
  },
  {
   n: 64,
   titre: "Écrire j",
   titreFiche: "J'écris les mots avec j",
   sd: "Expression Écrite",
   objectif: "Écrire des mots simples avec j : jardin, jouet, jaune.",
   supportFiche: "Tableau noir, ardoises, cahiers.",
   revision: {
    ens: ["Cite 2 mots avec z (chaîne parlée)."],
    app: ["R.A. : ", { t: "zèbre, zébu", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Nous savons dire j ; maintenant nous allons l'ÉCRIRE. À quoi ressemble la lettre j ? »"],
    app: ["Proposent : un crochet avec un point en dessous."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons la lettre j : une canne avec un point en dessous."],
    app: ["Écoutent et observent l'écriture au tableau."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » j'écris j en l'air, puis au tableau : la canne qui descend sous la ligne et le point."],
    app: ["Observent le geste ; ils tracent j dans l'air avec le doigt."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Qu'est-ce qui ne faut pas oublier sur la lettre j ?"], ["2) Écris « jouet » sur ton ardoise : où est j ?"], ["3) Écris « jardin » : vérifie le j !"], ["4) Qui peut écrire « jaune » ?"]] },
    app: { paras: [["R.A. : Le ", { t: "point", r: true }, " en dessous."], ["R.A. : Au ", { t: "début", r: true }, " : ", { t: "jouet", r: true }, "."], ["R.A. : ", { t: "jardin", r: true }, " : j bien écrit."], ["R.A. : ", { t: "jaune", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Ardoises",
   },
   synthese: {
    ens: ["Donc : la lettre j — le crochet et le point : jardin, jouet, jaune."],
    app: ["Répètent en écrivant dans l'air : j, j, j."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Sur ton ardoise, écris : jouet, jardin ; vérifie avec le tableau."],
    app: ["Écrivent sur ardoise, comparent, corrigent."],
    technique: ["Écriture individuelle"],
    support: "Ardoises",
   },
   evaluation: {
    ens: ["2 élèves : écris « jouet » au tableau."],
    app: ["R.A. : ", { t: "jouet", r: true }, " bien écrit (j avec point)."],
    technique: ["Individuel écrit"],
   },
   lecon: {
    titre: "64. ÉCRIRE J",
    subs: [
     { t: "A. La lettre", paras: [[{ t: "j", k: true }, " : un crochet qui descend sous la ligne et un ", { t: "point", k: true }, " en dessous !"]] },
     { t: "B. La dictée", paras: [["J'écris : ", { t: "jardin, jouet, jaune", k: true }, " sans oublier le point du j !"]] },
    ],
    retenir: ["J'écris la lettre ", { t: "j", k: true }, " : ", { t: "jardin, jouet, jaune", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris le mot qui manque (copie depuis le tableau) :"], items: [["1) le ....... (jardin)"], ["2) le ....... (jouet)"], ["3) ....... (jaune)"], ["4) le ....... (jambon)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Entoure la lettre j dans ces mots :"], items: [["1) jardin"], ["2) jouet"], ["3) jaune"], ["4) jambon"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Petite dictée sur le cahier (4 mots) :"], items: [["1) jardin"], ["2) jouet"], ["3) jaune"], ["4) jambon"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "jardin", r: true }, " — 2) ", { t: "jouet", r: true }, " — 3) ", { t: "jaune", r: true }, " — 4) ", { t: "jambon", r: true }, "."]] },
    { titre: "Exercice 2", lines: [["La lettre j entourée : ", { t: "jardin, jouet, jaune, jambon", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Dictée correcte : ", { t: "jardin, jouet, jaune, jambon", r: true }, " (1,5 pt par mot)."]] },
   ],
  },
  {
   n: 65,
   titre: "Écrire z — bilan de l'unité",
   titreFiche: "J'écris z ; bilan cadeaux et vêtements",
   sd: "Expression Écrite",
   objectif: "Écrire des mots avec z (zèbre, zébu) et faire le bilan de l'unité 5.",
   supportFiche: "Tableau noir, cahiers, images de l'unité.",
   revision: {
    ens: ["Dictée éclair : jouet, jardin (2 élèves au tableau)."],
    app: ["R.A. : ", { t: "jouet, jardin", r: true }, "."],
    technique: ["Individuel écrit"],
   },
   miseEnSituation: {
    ens: ["« L'unité 5 est finie ! Les vêtements, les cadeaux, les sons eil, j et z : tout est appris ! »"],
    app: ["Écoutent, fiers de leur travail."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons z et nous faisons le grand bilan."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez : » j'écris z au tableau : une ligne en bas, une diagonale, une ligne en haut — comme un zigzag."],
    app: ["Observent le zigzag ; ils tracent z dans l'air."],
    technique: ["Observation guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) À quoi ressemble la lettre z ?"], ["2) Écris « zébu » sur ton ardoise."], ["3) Cite 3 vêtements de l'unité."], ["4) Que dis-tu quand on t'offre un cadeau ?"]] },
    app: { paras: [["R.A. : Un ", { t: "zigzag", r: true }, "."], ["R.A. : ", { t: "zébu", r: true }, "."], ["R.A. : ", { t: "pantalon, robe, chemise...", r: true }, "."], ["R.A. : « ", { t: "Merci !", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Ardoises, images de l'unité",
   },
   synthese: {
    ens: ["Donc : unité 5 réussie — les vêtements, le cadeau et son merci, les sons eil, j et z !"],
    app: ["Récitent la comptine des vêtements une dernière fois, avec les gestes."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Sur ton cahier, écris : zèbre, zébu ; puis le grand jeu des mimes de l'unité."],
    app: ["Écrivent zèbre, zébu ; miment et devinent les mots de l'unité."],
    technique: ["Écriture + jeu de mimes"],
    support: "Cahiers",
   },
   evaluation: {
    ens: ["3 élèves : dis une phrase de l'unité (vêtement, cadeau ou son)."],
    app: ["R.A. : phrase correcte avec un mot de l'unité : ", { t: "je mets / merci / soleil / jardin / zébu...", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "65. ÉCRIRE Z — BILAN DE L'UNITÉ 5",
    subs: [
     { t: "A. La lettre", paras: [[{ t: "z", k: true }, " : comme un ", { t: "zigzag", k: true }, " — j'écris : zèbre, zébu."]] },
     { t: "B. Bilan de l'unité", paras: [[{ t: "Les vêtements", k: true }, " + ", { t: "le cadeau et merci", k: true }, " + les sons ", { t: "eil, ail, j, z", k: true }, " : tout est appris !"]] },
    ],
    retenir: ["Unité 5 réussie : ", { t: "les vêtements, les cadeaux et les sons eil, j, z", k: true }, " !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Coche ce que tu sais faire (ou dis-le) :"], items: [["1) Nommer 5 vêtements : oui / non"], ["2) Remercier pour un cadeau : oui / non"], ["3) Lire des mots avec eil : oui / non"], ["4) Écrire des mots avec j : oui / non"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Le grand tri : entoure les mots du son z :"], items: [["zèbre"], ["jardin"], ["zébu"], ["jouet"], ["soleil"], ["pareille"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Dicte-toi : écris 1 mot avec z, 1 mot avec j, 1 vêtement :"], items: [["1) un mot avec z : ....... (zèbre, zébu)"], ["2) un mot avec j : ....... (jardin, jouet...)"], ["3) un vêtement : ....... (pantalon, robe...)"], ["4) une phrase : « Le zébu est grand. » (copie)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Bilan oral : l'élève coche ", { t: "oui", r: true }, " quand il maîtrise (auto-évaluation guidée)."]] },
    { titre: "Exercice 2", lines: [["Mots avec z : ", { t: "zèbre, zébu", r: true }, " (2 pts chacun) — jardin, jouet (j !), soleil, pareille : non."]] },
    { titre: "Exercice 3", lines: [["Réponses libres : 1 mot en ", { t: "z", r: true }, " + 1 mot en ", { t: "j", r: true }, " + 1 ", { t: "vêtement", r: true }, " + phrase copiée."]] },
   ],
  },
 ],
};

module.exports = { theme5 };
