// data-theme8.js — Unité 8 « La ferme » (séances 100 à 120)
// Sources : FRA 10ème (T3 : ferme, sons œu, ou) + PDF CP2 unité VIII (21 séances)
// + RAPE T2 2025-2026 P1 (agriculture : semer, planter, récolter) et P3 (lexique des activités).
// sd par séance : EO s100-112, Lecture s113-116, Écriture s117-120. Barème 8+6+6 = 20 partout.

const theme8 = {
 numero: 8,
 nom: "La ferme",
 sousDiscipline: "Expression Orale",
 notions: "Le vocabulaire de la ferme et des animaux, les cris et les produits, les activités des champs, et les sons ou et œu.",
 competences: [
 "Nommer les animaux de la ferme : la vache, le zébu, la poule, le canard, le cochon, la chèvre.",
 "Dire les cris des animaux et leurs produits : « La vache meugle. Elle donne du lait. »",
 "Reconnaître et prononcer les sons ou et œu.",
 "Écrire des mots simples avec ou et œu.",
 ],
 seances: [
 {
  n: 100,
  titre: "Le vocabulaire de la ferme",
  titreFiche: "Les animaux de la ferme",
  sd: "Expression Orale",
  objectif: "Nommer les animaux de la ferme : la vache, le zébu, la poule, le canard, le cochon, la chèvre.",
  supportFiche: "Image « la ferme », figurines ou dessins d'animaux, tableau noir.",
  revision: {
  ens: ["Le grand bilan des repas : récite la comptine des repas (2 élèves)."],
  app: ["R.A. : « ", { t: "Le matin, je bois du lait... bon appétit, je grandis !", r: true }, " »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Qui a visité une ferme ? Quels animaux y a-t-il chez votre grand-père ? »"],
  app: ["Proposent : le zébu, les poules, le canard, le cochon..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les animaux de la ferme : la vache, le zébu, la poule, le canard, le cochon, la chèvre."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image de la ferme : » je montre chaque animal, les élèves le nomment."],
  app: ["Observent et nomment : la vache, le zébu, la poule, le canard, le cochon, la chèvre."],
  technique: ["Observation guidée"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Quel grand animal à bosse garde-t-on à Madagascar ?"], ["2) Quel animal donne des œufs ?"], ["3) Quel animal rose vit dans la boue ?"], ["4) Quels animaux avez-vous chez vous ?"]] },
  app: { paras: [["R.A. : Le ", { t: "zébu", r: true }, "."], ["R.A. : La ", { t: "poule", r: true }, " (et le canard)."], ["R.A. : Le ", { t: "cochon", r: true }, "."], ["R.A. : ", { t: "Le zébu, les poules, le canard...", r: true }, " (réponse personnelle)."]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : la ferme — la vache, le zébu, la poule, le canard, le cochon, la chèvre."],
  app: ["Répètent les 6 mots en chœur en mimant les gestes de chaque animal."],
  technique: ["Répétition collective"],
  support: "Image « la ferme »",
  },
  application: {
  ens: ["Le jeu de l'animal mystère : je mime un animal, vous devinez son nom."],
  app: ["Devinent et nomment : le canard ! la chèvre ! le zébu !"],
  technique: ["Jeu de mimes"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : nomme 3 animaux de la ferme."],
  app: ["R.A. : ", { t: "la vache, le zébu, la poule, le canard, le cochon, la chèvre", r: true }, " (3 mots corrects)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "100. LE VOCABULAIRE DE LA FERME",
  subs: [
   { t: "A. Les animaux", paras: [[{ t: "la vache", k: true }, " — ", { t: "le zébu", k: true }, " — ", { t: "la poule", k: true }, " — ", { t: "le canard", k: true }, " — ", { t: "le cochon", k: true }, " — ", { t: "la chèvre", k: true }]] },
   { t: "B. Ma phrase", paras: [["« ", { t: "Dans la ferme, il y a une vache, un zébu et des poules.", k: true }, " »"]] },
  ],
  retenir: ["Les animaux de la ferme : ", { t: "la vache, le zébu, la poule, le canard, le cochon, la chèvre", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les animaux de la ferme :"], items: [["la vache"], ["le cahier"], ["la poule"], ["le panier"], ["le cochon"], ["la chèvre"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le grand animal à bosse : le ....... (zébu)"], ["2) La ....... donne des œufs. (poule)"], ["3) Le ....... vit dans la boue. (cochon)"], ["4) La ....... donne du lait. (vache)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Mime un animal et devine (4 tours) :"], items: [["1) Mime n°1 : ....... (réponse libre : le canard)"], ["2) Mime n°2 : ....... (réponse libre : le zébu)"], ["3) Mime n°3 : ....... (réponse libre : la poule)"], ["4) Mime n°4 : ....... (réponse libre : le cochon)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Animaux entourés : ", { t: "la vache, la poule, le cochon, la chèvre", r: true }, " (2 pts chacun) — cahier (école) et panier (marché) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "zébu", r: true }, " — 2) ", { t: "poule", r: true }, " — 3) ", { t: "cochon", r: true }, " — 4) ", { t: "vache", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Mimes bien interprétés : ", { t: "1,5 pt par tour", r: true }, "."]] },
  ],
 },
 {
  n: 101,
  titre: "Les animaux et leurs petits",
  titreFiche: "La poule et le poussin",
  sd: "Expression Orale",
  objectif: "Nommer les petits des animaux : le veau, le poussin, le caneton, le chaton, le chiot.",
  supportFiche: "Image « la ferme », dessins animaux + petits, tableau noir.",
  revision: {
  ens: ["Nomme 3 animaux de la ferme (chaîne parlée)."],
  app: ["R.A. : ", { t: "la vache, le zébu, la poule, le canard, le cochon, la chèvre", r: true }, "."],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Comment s'appelle le bébé de la vache ? Et le bébé de la poule ? »"],
  app: ["Proposent : le poussin ! le petit de la vache..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les petits des animaux : le veau, le poussin, le caneton, le chaton, le chiot."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image et écoutez : » la vache a un veau, la poule a des poussins, le canard a des canetons, la chatte a des chatons."],
  app: ["Observent, répètent chaque paire mère-petit."],
  technique: ["Observation guidée"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Comment s'appelle le petit de la vache ?"], ["2) Comment s'appelle le petit de la poule ?"], ["3) Et le petit du canard ?"], ["4) Et le petit de la chienne ?"]] },
  app: { paras: [["R.A. : Le ", { t: "veau", r: true }, "."], ["R.A. : Le ", { t: "poussin", r: true }, "."], ["R.A. : Le ", { t: "caneton", r: true }, "."], ["R.A. : Le ", { t: "chiot", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : les petits — le veau, le poussin, le caneton, le chaton, le chiot."],
  app: ["Répètent les paires en chœur : la poule et le poussin, la vache et le veau..."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu des familles : je nomme la mère, vous dites le petit — la chatte ? le chaton !"],
  app: ["Répondent : la vache (le veau), la poule (le poussin), la chienne (le chiot)..."],
  technique: ["Jeu question-réponse"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : relie la mère et son petit (3 paires)."],
  app: ["R.A. : ", { t: "vache-veau, poule-poussin, canard-caneton", r: true }, " (3 paires)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "101. LES ANIMAUX ET LEURS PETITS",
  subs: [
   { t: "A. Les paires", paras: [[{ t: "la vache", k: true }, " → ", { t: "le veau", k: true }, " — ", { t: "la poule", k: true }, " → ", { t: "le poussin", k: true }, " — ", { t: "le canard", k: true }, " → ", { t: "le caneton", k: true }]] },
   { t: "B. À la maison", paras: [[{ t: "la chatte", k: true }, " → ", { t: "le chaton", k: true }, " — ", { t: "la chienne", k: true }, " → ", { t: "le chiot", k: true }]] },
  ],
  retenir: ["Les petits : ", { t: "le veau, le poussin, le caneton, le chaton, le chiot", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les petits des animaux :"], items: [["le poussin"], ["la poule"], ["le veau"], ["le zébu"], ["le caneton"], ["le chaton"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le petit de la vache : le ....... (veau)"], ["2) Le petit de la poule : le ....... (poussin)"], ["3) Le petit du canard : le ....... (caneton)"], ["4) Le petit de la chienne : le ....... (chiot)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Jeu des familles : réponds vite (4 tours) :"], items: [["1) La chatte ? ....... (le chaton)"], ["2) La poule ? ....... (le poussin)"], ["3) La vache ? ....... (le veau)"], ["4) Le canard ? ....... (le caneton)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Petits entourés : ", { t: "le poussin, le veau, le caneton, le chaton", r: true }, " (2 pts chacun) — la poule et le zébu : les mères, non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "veau", r: true }, " — 2) ", { t: "poussin", r: true }, " — 3) ", { t: "caneton", r: true }, " — 4) ", { t: "chiot", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Réponses rapides justes : ", { t: "1,5 pt par tour", r: true }, "."]] },
  ],
 },
 {
  n: 102,
  titre: "Les travaux des champs",
  titreFiche: "Je sème, je plante",
  sd: "Expression Orale",
  objectif: "Dire les travaux des champs : labourer, semer, planter, arroser, récolter.",
  supportFiche: "Image « la ferme », angady (bêche) ou dessins, tableau noir.",
  revision: {
  ens: ["Relie : la vache ? le veau ! (réponse rapide)."],
  app: ["R.A. : ", { t: "veau, poussin, caneton, chaton, chiot", r: true }, "."],
  technique: ["Jeu rapide"],
  },
  miseEnSituation: {
  ens: ["« Que fait papa dans le champ avant de planter le riz ? Qui utilise l'angady ? »"],
  app: ["Proposent : il creuse, il laboure, il sème..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les travaux des champs : labourer, semer, planter, arroser, récolter."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et mimez avec moi : » je laboure la terre, je sème les graines, je plante, j'arrose, puis je récolte !"],
  app: ["Observent, miment chaque geste en le nommant."],
  technique: ["Observation guidée"],
  support: "Angady ou dessins",
  },
  analyse: {
  ens: { paras: [["1) Que fait-on avant de semer ?"], ["2) Que met-on dans la terre ?"], ["3) Que fait-on quand les plantes ont soif ?"], ["4) Que fait-on à la fin, quand le riz est mûr ?"]] },
  app: { paras: [["R.A. : On ", { t: "laboure", r: true }, " la terre."], ["R.A. : On ", { t: "plante", r: true }, "."], ["R.A. : On ", { t: "arrose", r: true }, "."], ["R.A. : On ", { t: "récolte", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : les travaux — labourer, semer, planter, arroser, récolter, dans cet ordre !"],
  app: ["Répètent les 5 verbes en chœur en mimant chaque geste, dans l'ordre."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu de l'ordre : je dis un verbe, vous mimez ; puis un élève mimes toute l'année du champ."],
  app: ["Miment : labourer → semer → planter → arroser → récolter."],
  technique: ["Jeu de mimes enchaînés"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : mime et nomme 3 travaux des champs."],
  app: ["R.A. : ", { t: "labourer, semer, planter, arroser, récolter", r: true }, " (3 verbes corrects)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "102. LES TRAVAUX DES CHAMPS",
  subs: [
   { t: "A. Les verbes", paras: [[{ t: "labourer", k: true }, " — ", { t: "semer", k: true }, " — ", { t: "planter", k: true }, " — ", { t: "arroser", k: true }, " — ", { t: "récolter", k: true }]] },
   { t: "B. Ma phrase", paras: [["« ", { t: "Papa laboure la terre, sème et récolte le riz.", k: true }, " »"]] },
  ],
  retenir: ["Les travaux des champs : ", { t: "labourer, semer, planter, arroser, récolter", k: true }, " — dans l'ordre !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les travaux des champs :"], items: [["semer"], ["la marmite"], ["planter"], ["le poussin"], ["récolter"], ["arroser"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Remets les travaux en ordre (1, 2, 3, 4) :"], items: [["récolter (4)"], ["labourer (1)"], ["planter (3)"], ["semer (2)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Complète :"], items: [["1) Papa ....... la terre avec l'angady. (laboure)"], ["2) Il ....... les graines. (sème)"], ["3) Maman ....... le jardin. (arrose)"], ["4) Quand le riz est mûr, on le ....... (récolte)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Verbes entourés : ", { t: "semer, planter, récolter, arroser", r: true }, " (2 pts chacun) — marmite (cuisine) et poussin (animal) non."]] },
  { titre: "Exercice 2", lines: [["Ordre : ", { t: "labourer → semer → planter → récolter", r: true }, " (2 pts par numéro)."]] },
  { titre: "Exercice 3", lines: [["1) ", { t: "laboure", r: true }, " — 2) ", { t: "sème", r: true }, " — 3) ", { t: "arrose", r: true }, " — 4) ", { t: "récolte", r: true }, "."]] },
  ],
 },
 {
  n: 103,
  titre: "À la rizière",
  titreFiche: "Le riz de Madagascar",
  sd: "Expression Orale",
  objectif: "Décrire la rizière : le paysan, la rizière, l'eau, planter le riz, récolter le riz.",
  supportFiche: "Image « la rizière », tableau noir.",
  revision: {
  ens: ["Mime les travaux des champs dans l'ordre (1 élève)."],
  app: ["R.A. : ", { t: "labourer → semer → planter → arroser → récolter", r: true }, " (mimes)."],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Qui a vu une rizière ? De quelle couleur est-elle ? Qu'y a-t-il dedans ? »"],
  app: ["Proposent : verte, avec de l'eau, du riz..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous parlons de la rizière : le paysan y plante le riz, avec de l'eau."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image : » le paysan marche dans la rizière pleine d'eau ; il plante les jeunes plants de riz, ligne après ligne."],
  app: ["Observent, répètent : la rizière, l'eau, le paysan, les plants de riz."],
  technique: ["Observation guidée"],
  support: "Image « la rizière »",
  },
  analyse: {
  ens: { paras: [["1) Où plante-t-on le riz ?"], ["2) Qu'est-ce qu'il y a dans la rizière ?"], ["3) Qui travaille dans la rizière ?"], ["4) Que devient le riz quand il est mûr ?"]] },
  app: { paras: [["R.A. : Dans la ", { t: "rizière", r: true }, "."], ["R.A. : De l'", { t: "eau", r: true }, "."], ["R.A. : Le ", { t: "paysan", r: true }, " (et la paysanne)."], ["R.A. : On le ", { t: "récolte", r: true }, " — du riz pour manger !"]] },
  technique: ["Question / réponse"],
  support: "Image « la rizière »",
  },
  synthese: {
  ens: ["Donc : la rizière — le paysan, l'eau, les plants de riz ; on plante, on récolte."],
  app: ["Répètent les mots en chœur en mimant la marche dans l'eau de la rizière."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["La phrase des rizières : chacun complète « Dans la rizière, je vois... »"],
  app: ["Enchaînent : je vois l'eau, je vois le paysan, je vois les collines vertes..."],
  technique: ["Jeu de phrases enchaînées"],
  support: "Image « la rizière »",
  },
  evaluation: {
  ens: ["3 élèves : dis ta phrase « Dans la rizière... » (3 mots)."],
  app: ["R.A. : « ", { t: "Dans la rizière, je vois le paysan, l'eau et le riz.", r: true }, " » (3 mots)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "103. À LA RIZIÈRE",
  subs: [
   { t: "A. Les mots", paras: [[{ t: "la rizière", k: true }, " — ", { t: "le paysan", k: true }, " — ", { t: "l'eau", k: true }, " — ", { t: "les plants de riz", k: true }]] },
   { t: "B. Ma phrase", paras: [["« ", { t: "Le paysan plante le riz dans la rizière.", k: true }, " » — « ", { t: "Il récolte le riz quand il est mûr.", k: true }, " »"]] },
  ],
  retenir: ["À Madagascar : ", { t: "le paysan plante le riz dans la rizière", k: true }, " — l'eau, la boue, les collines vertes."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure ce qu'on trouve à la rizière :"], items: [["le paysan"], ["le poussin"], ["l'eau"], ["le chaton"], ["les plants de riz"], ["la boue"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le ....... plante le riz. (paysan)"], ["2) La ....... est pleine d'eau. (rizière)"], ["3) Quand le riz est ......., on le récolte. (mûr)"], ["4) On mange le ....... tous les jours. (riz)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Décris la rizière en 3 mots (4 élèves) :"], items: [["1) Je vois ....... (réponse libre)"], ["2) Je vois ....... (réponse libre)"], ["3) Je vois ....... (réponse libre)"], ["4) J'aime ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le paysan, l'eau, les plants de riz, la boue", r: true }, " (2 pts chacun) — poussin et chaton (petits) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "paysan", r: true }, " — 2) ", { t: "rizière", r: true }, " — 3) ", { t: "mûr", r: true }, " — 4) ", { t: "riz", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Descriptions avec mots de la rizière : ", { t: "1,5 pt par mot", r: true }, "."]] },
  ],
 },
 {
  n: 104,
  titre: "Le dialogue de la ferme",
  titreFiche: "Qu'est-ce que tu vois ?",
  sd: "Expression Orale",
  objectif: "Jouer le dialogue de la ferme : « Qu'est-ce que tu vois ? — Je vois la vache et les poules. »",
  supportFiche: "Image « la ferme », figurines d'animaux, tableau noir.",
  revision: {
  ens: ["Dis ta phrase de la rizière (2 élèves)."],
  app: ["R.A. : « ", { t: "Dans la rizière, je vois le paysan, l'eau et le riz.", r: true }, " »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Tu arrives à la ferme de ton grand-père. Que vois-tu d'abord ? Comment le dire à ton copain ? »"],
  app: ["Proposent : je vois le zébu, les poules..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous jouons le dialogue de la ferme : la question « qu'est-ce que tu vois ? » et la réponse « je vois... »."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez le dialogue : » — Qu'est-ce que tu vois, Fara ? — Je vois la vache, le zébu et les poules. — Et moi, je vois les canetons !"],
  app: ["Écoutent, puis répètent chaque réplique."],
  technique: ["Modèle oral"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Que demande Fara à son copain ?"], ["2) Que voit-elle ?"], ["3) Que voit l'autre enfant ?"], ["4) Pose-moi la question de la ferme !"]] },
  app: { paras: [["R.A. : « ", { t: "Qu'est-ce que tu vois ?", r: true }, " »"], ["R.A. : ", { t: "La vache, le zébu et les poules", r: true }, "."], ["R.A. : ", { t: "Les canetons", r: true }, "."], ["R.A. : « ", { t: "Qu'est-ce que tu vois ?", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : « Qu'est-ce que tu vois ? — Je vois..., ..., et... »"],
  app: ["Répètent le dialogue en chœur, puis par deux."],
  technique: ["Répétition par deux"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu de la ferme : par deux, un élève montre un animal sur l'image, l'autre fait la question et la réponse."],
  app: ["Jouent : qu'est-ce que tu vois ? — je vois le cochon et la chèvre !"],
  technique: ["Jeu de rôle par deux"],
  support: "Image « la ferme »",
  },
  evaluation: {
  ens: ["3 paires : joue le dialogue complet avec 3 animaux."],
  app: ["R.A. : ", { t: "question + réponse avec 3 animaux", r: true }, " (dialogue complet)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "104. LE DIALOGUE DE LA FERME",
  subs: [
   { t: "A. Le dialogue", paras: [["« — ", { t: "Qu'est-ce que tu vois ?", k: true }, " — ", { t: "Je vois la vache, le zébu et les poules.", k: true }, " »"], ["« — ", { t: "Et moi, je vois les canetons !", k: true }, " »"]] },
  ],
  retenir: ["« ", { t: "Qu'est-ce que tu vois ? — Je vois...", k: true }, " » — et j'énumère avec ", { t: "et", k: true }, " !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots du dialogue de la ferme :"], items: [["tu vois"], ["je vois"], ["le café"], ["la vache"], ["la cuillère"], ["les poules"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète le dialogue :"], items: [["1) Qu'est-ce que ....... vois ? (tu)"], ["2) Je ....... le zébu. (vois)"], ["3) Je vois la vache, le zébu ....... les poules. (et)"], ["4) Et ......., je vois les canetons ! (moi)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène avec un camarade (4 répliques) :"], items: [["1) La question : ......."], ["2) La réponse (2 animaux) : ......."], ["3) La relance : ......."], ["4) La réponse (1 animal) : ......."]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Entourés : ", { t: "tu vois, je vois, la vache, les poules", r: true }, " (2 pts chacun) — café (repas) et cuillère (table) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "tu", r: true }, " — 2) ", { t: "vois", r: true }, " — 3) ", { t: "et", r: true }, " — 4) ", { t: "moi", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Scènes jouées : ", { t: "répliques complètes", r: true }, " (1,5 pt par réplique)."]] },
  ],
 },
 {
  n: 105,
  titre: "Les cris des animaux",
  titreFiche: "Cocorico ! Meuh !",
  sd: "Expression Orale",
  objectif: "Dire les cris des animaux : le coq chante, la poule glousse, la vache meugle, le chien aboie.",
  supportFiche: "Image « la ferme », figurines, tableau noir.",
  revision: {
  ens: ["Joue le dialogue de la ferme avec ton voisin (30 secondes)."],
  app: ["R.A. : « Qu'est-ce que tu vois ? — Je vois... »"],
  technique: ["Jeu de rôle express"],
  },
  miseEnSituation: {
  ens: ["« Comment fait le coq le matin ? Et la vache ? Faites le bruit ! »"],
  app: ["Imitent : cocorico ! meuh ! cot cot !"],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les cris des animaux : chanter, glousser, meugler, aboyer."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez : » le coq chante : cocorico ! la poule glousse : cot, cot ! la vache meugle : meuh ! le chien aboie : ouaf, ouaf ! le chat miaule : miaou !"],
  app: ["Écoutent, imitent chaque cri en montrant l'animal."],
  technique: ["Observation guidée"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Que fait le coq ?"], ["2) Que fait la vache ?"], ["3) Que fait le chien ?"], ["4) Quel animal dit miaou ?"]] },
  app: { paras: [["R.A. : Il ", { t: "chante", r: true }, " : cocorico !"], ["R.A. : Elle ", { t: "meugle", r: true }, " : meuh !"], ["R.A. : Il ", { t: "aboie", r: true }, " : ouaf, ouaf !"], ["R.A. : Le ", { t: "chat", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : les cris — le coq chante, la poule glousse, la vache meugle, le chien aboie, le chat miaule."],
  app: ["Répètent les cris en chœur, puis chacun choisit son animal."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu des cris : je nomme un animal, vous faites son cri ; puis un élève ferme les yeux et devine l'animal."],
  app: ["Imitent et devinent : cocorico (le coq !), meuh (la vache !), coin-coin (le canard !)."],
  technique: ["Jeu d'écoute"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : dis le cri de 3 animaux."],
  app: ["R.A. : ", { t: "cocorico, meuh, ouaf, miaou, cot cot", r: true }, " (3 cris corrects)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "105. LES CRIS DES ANIMAUX",
  subs: [
   { t: "A. Les cris", paras: [["Le coq ", { t: "chante", k: true }, " (cocorico !) — la poule ", { t: "glousse", k: true }, " (cot, cot !) — la vache ", { t: "meugle", k: true }, " (meuh !)"]] },
   { t: "B. À la maison", paras: [["Le chien ", { t: "aboie", k: true }, " (ouaf !) — le chat ", { t: "miaule", k: true }, " (miaou !) — le canard ", { t: "cancane", k: true }, " (coin-coin !)"]] },
  ],
  retenir: ["Les cris : ", { t: "cocorico, cot cot, meuh, ouaf, miaou, coin-coin", k: true }, " — écoute la ferme !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Relie l'animal à son cri (entoure le bon cri) :"], items: [["le coq : cocorico / coin-coin"], ["la vache : meuh / ouaf"], ["le chat : miaou / cot cot"], ["le canard : coin-coin / meuh"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le coq ....... : cocorico ! (chante)"], ["2) La vache ....... : meuh ! (meugle)"], ["3) Le chien ....... : ouaf ! (aboie)"], ["4) Le chat ....... : miaou ! (miaule)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Fais le cri, les autres devinent (4 tours) :"], items: [["1) Cri n°1 : ....... (l'animal : .......)"], ["2) Cri n°2 : ....... (l'animal : .......)"], ["3) Cri n°3 : ....... (l'animal : .......)"], ["4) Cri n°4 : ....... (l'animal : .......)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["1) ", { t: "cocorico", r: true }, " — 2) ", { t: "meuh", r: true }, " — 3) ", { t: "miaou", r: true }, " — 4) ", { t: "coin-coin", r: true }, " (2 pts chacun)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "chante", r: true }, " — 2) ", { t: "meugle", r: true }, " — 3) ", { t: "aboie", r: true }, " — 4) ", { t: "miaule", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Cris + animaux devinés : ", { t: "1,5 pt par tour", r: true }, "."]] },
  ],
 },
 {
  n: 106,
  titre: "La comptine de la ferme",
  titreFiche: "Dans la ferme de mon grand-père",
  sd: "Expression Orale",
  objectif: "Réciter la comptine de la ferme en rythme, avec les cris.",
  supportFiche: "Comptine au tableau, image « la ferme ».",
  revision: {
  ens: ["Dis les cris des animaux (chaîne parlée rapide)."],
  app: ["R.A. : ", { t: "cocorico, cot cot, meuh, ouaf, miaou, coin-coin", r: true }, "."],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Voici la comptine de la ferme de J-Learn : écoutez les cris dedans ! »"],
  app: ["Écoutent, tapent le rythme des mains."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons la comptine de la ferme : écoutez d'abord, puis répétez."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez la comptine : » Dans la ferme de mon grand-père, / le coq chante cocorico ; / la poule glousse : cot, cot, cot ! / et la vache meugle : meuh, meuh, meuh !"],
  app: ["Écoutent en suivant sur le tableau."],
  technique: ["Modèle oral"],
  support: "Comptine au tableau",
  },
  analyse: {
  ens: { paras: [["1) Où se passe la comptine ?"], ["2) Que fait le coq ?"], ["3) Que fait la poule ?"], ["4) Comment finit la comptine ?"]] },
  app: { paras: [["R.A. : Dans la ", { t: "ferme de mon grand-père", r: true }, "."], ["R.A. : Il ", { t: "chante", r: true }, " : cocorico !"], ["R.A. : Elle ", { t: "glousse", r: true }, " : cot, cot, cot !"], ["R.A. : « ", { t: "La vache meugle : meuh, meuh, meuh !", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Comptine au tableau",
  },
  synthese: {
  ens: ["Donc : la comptine de la ferme, avec le coq, la poule et la vache."],
  app: ["Répètent la comptine en chœur, deux fois, avec les cris bien forts."],
  technique: ["Répétition collective"],
  support: "Comptine au tableau",
  },
  application: {
  ens: ["La comptine par groupe : chaque groupe récite une ligne avec son animal et son cri."],
  app: ["Récitent en groupes puis en chœur."],
  technique: ["Récitation par groupes"],
  support: "Comptine au tableau",
  },
  evaluation: {
  ens: ["3 élèves : récite la comptine complète."],
  app: ["R.A. : comptine ", { t: "récitée sans oubli", r: true }, " (cris bien placés)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "106. LA COMPTINE DE LA FERME",
  subs: [
   { t: "A. La comptine", paras: [["« ", { t: "Dans la ferme de mon grand-père,", k: true }, " / ", { t: "le coq chante cocorico ;", k: true }, " »"], ["« ", { t: "la poule glousse : cot, cot, cot !", k: true }, " / ", { t: "et la vache meugle : meuh, meuh, meuh !", k: true }, " »"]] },
  ],
  retenir: ["Ma comptine : « ", { t: "Dans la ferme de mon grand-père...", k: true }, " » — avec les cris cocorico, cot cot, meuh !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Remets les lignes de la comptine en ordre (1, 2, 3, 4) :"], items: [["et la vache meugle : meuh, meuh, meuh ! (4)"], ["Dans la ferme de mon grand-père, (1)"], ["la poule glousse : cot, cot, cot ! (3)"], ["le coq chante cocorico ; (2)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète la comptine :"], items: [["1) Dans la ....... de mon grand-père (ferme)"], ["2) le coq ....... cocorico (chante)"], ["3) la ....... glousse : cot, cot, cot ! (poule)"], ["4) et la vache ....... : meuh ! (meugle)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Ajoute un vers : « le/la ....... fait ....... » (4 élèves) :"], items: [["1) Vers n°1 : ....... (réponse libre)"], ["2) Vers n°2 : ....... (réponse libre)"], ["3) Vers n°3 : ....... (réponse libre)"], ["4) Vers n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Ordre : ", { t: "Dans la ferme... → le coq chante → la poule glousse → la vache meugle !", r: true }, " (2 pts par numéro)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "ferme", r: true }, " — 2) ", { t: "chante", r: true }, " — 3) ", { t: "poule", r: true }, " — 4) ", { t: "meugle", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Vers corrects (animal + cri, rythme tenu) : ", { t: "1,5 pt par vers", r: true }, "."]] },
  ],
 },
 {
  n: 107,
  titre: "Je compte les animaux",
  titreFiche: "Il y a... un, deux, trois",
  sd: "Expression Orale",
  objectif: "Compter et dire : « Il y a un zébu, deux poules et trois canards. »",
  supportFiche: "Image « la ferme », figurines à compter, tableau noir.",
  revision: {
  ens: ["Récite la comptine de la ferme avec ton voisin."],
  app: ["R.A. : « Dans la ferme de mon grand-père... »"],
  technique: ["Répétition par deux"],
  },
  miseEnSituation: {
  ens: ["« Combien de poules y a-t-il chez vous ? Et combien de zébus ? Comptez et dites ! »"],
  app: ["Comptent et proposent : il y a deux poules, un zébu..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous comptons les animaux : « Il y a un..., deux..., trois... »"],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image et comptez avec moi : » il y a une vache, deux veaux, trois poules, cinq poussins, quatre canards."],
  app: ["Comptent en pointant : un, deux, trois... puis répètent les phrases."],
  technique: ["Observation guidée"],
  support: "Image « la ferme », figurines",
  },
  analyse: {
  ens: { paras: [["1) Combien de vaches dans l'image ?"], ["2) Combien de poules ?"], ["3) Quel petit mot commence chaque phrase ?"], ["4) Compte les canetons et dis la phrase !"]] },
  app: { paras: [["R.A. : ", { t: "Une", r: true }, "."], ["R.A. : ", { t: "Trois", r: true }, "."], ["R.A. : ", { t: "Il y a", r: true }, "."], ["R.A. : « ", { t: "Il y a quatre canetons.", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : pour compter, je dis « Il y a » + le nombre + l'animal — un zébu, deux poules, trois canards."],
  app: ["Répètent le modèle en chœur avec 3 phrases de comptage."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu du comptage : je cache des figurines, vous comptez et dites la phrase complète."],
  app: ["Comptent : il y a deux chèvres et quatre poussins !"],
  technique: ["Jeu de comptage"],
  support: "Figurines",
  },
  evaluation: {
  ens: ["3 élèves : compte 2 sortes d'animaux et dis les 2 phrases."],
  app: ["R.A. : « ", { t: "Il y a... et il y a...", r: true }, " » (2 phrases avec nombres)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "107. JE COMPTE LES ANIMAUX",
  subs: [
   { t: "A. Mes phrases", paras: [["« ", { t: "Il y a un zébu, deux poules et trois canards.", k: true }, " » — ", { t: "un, deux, trois, quatre, cinq", k: true }]] },
   { t: "B. Le modèle", paras: [["« ", { t: "Il y a + nombre + animal", k: true }, " » — attention à ", { t: "un / une", k: true }, " et aux ", { t: "s", k: true }, " du pluriel !"]] },
  ],
  retenir: ["Pour compter : ", { t: "« Il y a un..., deux..., trois... »", k: true }, " — je compte et je dis !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les nombres :"], items: [["deux"], ["la vache"], ["cinq"], ["le poussin"], ["quatre"], ["meuh"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Il ....... un zébu. (y a)"], ["2) Il y a ....... poules. (deux)"], ["3) Il y a trois ....... (canards)"], ["4) Il y a ....... poussins. (cinq)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Compte et dis (4 comptages) :"], items: [["1) Les figurines n°1 : ....... (il y a...)"], ["2) Les figurines n°2 : ....... (il y a...)"], ["3) Les figurines n°3 : ....... (il y a...)"], ["4) Les figurines n°4 : ....... (il y a...)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Nombres entourés : ", { t: "deux, cinq, quatre", r: true }, " (2 pts chacun) — vache (animal) et meuh (cri) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "y a", r: true }, " — 2) ", { t: "deux", r: true }, " — 3) ", { t: "canards", r: true }, " — 4) ", { t: "cinq", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Comptages justes : ", { t: "1,5 pt par phrase", r: true }, "."]] },
  ],
 },
 {
  n: 108,
  titre: "Je décris un animal",
  titreFiche: "La vache est noire et blanche",
  sd: "Expression Orale",
  objectif: "Décrire un animal : couleur, nourriture, produit — « La vache est noire et blanche. Elle mange de l'herbe. »",
  supportFiche: "Image « la ferme », figurines, tableau noir.",
  revision: {
  ens: ["Compte : il y a trois chèvres et cinq poules (2 élèves)."],
  app: ["R.A. : « ", { t: "Il y a trois chèvres et cinq poules.", r: true }, " »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Décrivez le zébu : sa couleur, ses cornes, ce qu'il mange. »"],
  app: ["Proposent : gris, des cornes, il broute l'herbe..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous décrivons les animaux : la couleur, ce qu'il mange, ce qu'il donne."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » la vache est noire et blanche, elle mange de l'herbe, elle donne du lait ; la poule est blanche, elle picore les graines, elle pond des œufs."],
  app: ["Observent, répètent les deux descriptions."],
  technique: ["Observation guidée"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) De quelle couleur est la vache ?"], ["2) Que mange-t-elle ?"], ["3) Que fait la poule ?"], ["4) Décris le cochon !"]] },
  app: { paras: [["R.A. : Elle est ", { t: "noire et blanche", r: true }, "."], ["R.A. : De l'", { t: "herbe", r: true }, "."], ["R.A. : Elle ", { t: "picore", r: true }, " et elle ", { t: "pond des œufs", r: true }, "."], ["R.A. : ", { t: "Le cochon est rose, il mange tout, il vit dans la boue.", r: true }, ""]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : pour décrire un animal — « Il/Elle est... (couleur). Il/Elle mange... Il/Elle donne... »"],
  app: ["Répètent le modèle en chœur avec 3 animaux."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["La devinette décrite : je décris un animal sans le nommer, vous devinez."],
  app: ["Devine : il est gris, il a une bosse et des cornes — le zébu !"],
  technique: ["Jeu de devinette"],
  support: "Figurines",
  },
  evaluation: {
  ens: ["3 élèves : décris un animal (couleur + nourriture + produit)."],
  app: ["R.A. : « ", { t: "La vache est noire et blanche. Elle mange de l'herbe. Elle donne du lait.", r: true }, " » (3 éléments)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "108. JE DÉCRIS UN ANIMAL",
  subs: [
   { t: "A. Les couleurs et la nourriture", paras: [[{ t: "noir", k: true }, ", ", { t: "blanc", k: true }, ", ", { t: "gris", k: true }, ", ", { t: "rose", k: true }, " / l'", { t: "herbe", k: true }, ", les ", { t: "graines", k: true }, ", le ", { t: "riz", k: true }]] },
   { t: "B. Mes phrases", paras: [["« ", { t: "La vache est noire et blanche. Elle mange de l'herbe. Elle donne du lait.", k: true }, " »"]] },
  ],
  retenir: ["Pour décrire : ", { t: "« Il/Elle est... Il/Elle mange... Il/Elle donne... »", k: true }],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots pour décrire un animal :"], items: [["blanche"], ["le genou"], ["mange"], ["l'herbe"], ["coin-coin"], ["pond"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) La vache est noire et ....... (blanche)"], ["2) Elle ....... de l'herbe. (mange)"], ["3) Elle ....... du lait. (donne)"], ["4) La poule ....... des œufs. (pond)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Décris ton animal préféré en 3 phrases (4 élèves) :"], items: [["1) Animal n°1 : ....... (réponse libre)"], ["2) Animal n°2 : ....... (réponse libre)"], ["3) Animal n°3 : ....... (réponse libre)"], ["4) Animal n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "blanche, mange, l'herbe, pond", r: true }, " (2 pts chacun) — genou (corps) et coin-coin (cri) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "blanche", r: true }, " — 2) ", { t: "mange", r: true }, " — 3) ", { t: "donne", r: true }, " — 4) ", { t: "pond", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Descriptions complètes (3 éléments) : ", { t: "1,5 pt par description", r: true }, "."]] },
  ],
 },
 {
  n: 109,
  titre: "Les produits de la ferme",
  titreFiche: "Ce que la ferme nous donne",
  sd: "Expression Orale",
  objectif: "Nommer les produits de la ferme : du lait, des œufs, du riz, des légumes, de la viande.",
  supportFiche: "Image « la ferme », produits réels (œufs, lait), tableau noir.",
  revision: {
  ens: ["Décris un animal en 3 phrases (2 élèves)."],
  app: ["R.A. : « Il/Elle est... mange... donne... »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Que mangez-vous qui vient de la ferme ? Qui a mangé un œuf ce matin ? »"],
  app: ["Proposent : le riz, les œufs, le lait, la viande, les légumes..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les produits de la ferme : du lait, des œufs, du riz, des légumes, de la viande."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » la vache donne du lait, la poule donne des œufs, le champ donne du riz et des légumes, les animaux donnent de la viande."],
  app: ["Observent, répètent chaque produit avec sa source."],
  technique: ["Observation guidée"],
  support: "Produits réels",
  },
  analyse: {
  ens: { paras: [["1) Que donne la vache ?"], ["2) Que donne la poule ?"], ["3) Que donne le champ ?"], ["4) Que donnent le zébu et le cochon ?"]] },
  app: { paras: [["R.A. : Du ", { t: "lait", r: true }, "."], ["R.A. : Des ", { t: "œufs", r: true }, "."], ["R.A. : Du ", { t: "riz et des légumes", r: true }, "."], ["R.A. : De la ", { t: "viande", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : les produits — du lait, des œufs, du riz, des légumes, de la viande."],
  app: ["Répètent les 5 produits en chœur en mimant le geste de porter le panier."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu des sources : je nomme un produit, vous nommez l'animal ou le champ qui le donne."],
  app: ["Répondent : le lait (la vache !), les œufs (la poule !), le riz (le champ !)."],
  technique: ["Jeu question-réponse"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : nomme 3 produits de la ferme et leur source."],
  app: ["R.A. : ", { t: "lait, œufs, riz, légumes, viande", r: true }, " (3 produits + sources)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "109. LES PRODUITS DE LA FERME",
  subs: [
   { t: "A. Les produits", paras: [[{ t: "du lait", k: true }, " — ", { t: "des œufs", k: true }, " — ", { t: "du riz", k: true }, " — ", { t: "des légumes", k: true }, " — ", { t: "de la viande", k: true }]] },
   { t: "B. Mes phrases", paras: [["« ", { t: "La vache donne du lait.", k: true }, " » — « ", { t: "La poule donne des œufs.", k: true }, " » — « ", { t: "Le champ donne du riz.", k: true }, " »"]] },
  ],
  retenir: ["Les produits : ", { t: "du lait, des œufs, du riz, des légumes, de la viande", k: true }, " — merci la ferme !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les produits de la ferme :"], items: [["du lait"], ["le coq"], ["des œufs"], ["la chèvre"], ["du riz"], ["des légumes"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) La vache donne du ....... (lait)"], ["2) La poule donne des ....... (œufs)"], ["3) Le champ donne du ....... et des légumes. (riz)"], ["4) Le zébu donne de la ....... (viande)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Produit et source : réponds (4 tours) :"], items: [["1) Les œufs ? ....... (la poule)"], ["2) Le lait ? ....... (la vache)"], ["3) Les légumes ? ....... (le champ / le jardin)"], ["4) La viande ? ....... (le zébu, le cochon, le poulet)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Produits entourés : ", { t: "du lait, des œufs, du riz, des légumes", r: true }, " (2 pts chacun) — coq et chèvre : animaux, non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "lait", r: true }, " — 2) ", { t: "œufs", r: true }, " — 3) ", { t: "riz", r: true }, " — 4) ", { t: "viande", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Sources justes : ", { t: "1,5 pt par tour", r: true }, "."]] },
  ],
 },
 {
  n: 110,
  titre: "Le dialogue des produits",
  titreFiche: "Qu'est-ce qu'elle donne ?",
  sd: "Expression Orale",
  objectif: "Jouer le dialogue des produits : « Qu'est-ce que la vache donne ? — Elle donne du lait. — Et la poule ? — Elle pond des œufs. »",
  supportFiche: "Image « la ferme », produits réels, tableau noir.",
  revision: {
  ens: ["Produit et source : le lait ? les œufs ? (réponse rapide)."],
  app: ["R.A. : ", { t: "le lait (la vache), les œufs (la poule)", r: true }, "."],
  technique: ["Jeu rapide"],
  },
  miseEnSituation: {
  ens: ["« Ton petit copain ne connaît pas la ferme. Comment lui demander ce que donne la vache ? »"],
  app: ["Proposent : qu'est-ce que la vache donne ?..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous jouons le dialogue des produits : la question « qu'est-ce que... donne ? » et la réponse."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez le dialogue : » — Qu'est-ce que la vache donne ? — Elle donne du lait. — Et la poule ? — Elle pond des œufs. — Merci, je connais la ferme !"],
  app: ["Écoutent, puis répètent chaque réplique."],
  technique: ["Modèle oral"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Que demande le premier enfant ?"], ["2) Que répond l'autre ?"], ["3) Et la poule, que donne-t-elle ?"], ["4) Demande-moi ce que donne le champ !"]] },
  app: { paras: [["R.A. : « ", { t: "Qu'est-ce que la vache donne ?", r: true }, " »"], ["R.A. : « ", { t: "Elle donne du lait.", r: true }, " »"], ["R.A. : ", { t: "Des œufs", r: true }, "."], ["R.A. : « ", { t: "Qu'est-ce que le champ donne ?", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : « Qu'est-ce que... donne ? — Il/Elle donne... — Et... ? — Il/Elle... »"],
  app: ["Répètent le dialogue en chœur, puis par deux avec d'autres animaux."],
  technique: ["Répétition par deux"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu des produits : par deux, avec les figurines — question, réponse, relance."],
  app: ["Jouent : qu'est-ce que la chèvre donne ? — elle donne du lait..."],
  technique: ["Jeu de rôle par deux"],
  support: "Figurines, produits réels",
  },
  evaluation: {
  ens: ["3 paires : joue le dialogue complet (2 produits)."],
  app: ["R.A. : ", { t: "question + réponse + relance + réponse", r: true }, " (dialogue complet)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "110. LE DIALOGUE DES PRODUITS",
  subs: [
   { t: "A. Le dialogue", paras: [["« — ", { t: "Qu'est-ce que la vache donne ?", k: true }, " — ", { t: "Elle donne du lait.", k: true }, " »"], ["« — ", { t: "Et la poule ?", k: true }, " — ", { t: "Elle pond des œufs.", k: true }, " »"]] },
  ],
  retenir: ["« ", { t: "Qu'est-ce que... donne ? — Il/Elle donne...", k: true }, " » — la ferme nous donne tout !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les questions du dialogue :"], items: [["Qu'est-ce que la vache donne ?"], ["Elle donne du lait."], ["Et la poule ?"], ["Le panier est plein."], ["La poule pond des œufs."], ["Qu'est-ce que tu vois ?"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Qu'est-ce que la ....... donne ? (vache)"], ["2) Elle donne du ....... (lait)"], ["3) Et la poule ? — Elle ....... des œufs. (pond)"], ["4) Le champ ....... du riz. (donne)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène avec un camarade (4 répliques) :"], items: [["1) La question (animal 1) : ......."], ["2) La réponse : ......."], ["3) La relance (animal 2) : ......."], ["4) La réponse : ......."]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Questions entourées : ", { t: "Qu'est-ce que la vache donne ? / Et la poule ? / Qu'est-ce que tu vois ?", r: true }, " (2 pts chacun) — les autres sont des réponses ou des phrases descriptives."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "vache", r: true }, " — 2) ", { t: "lait", r: true }, " — 3) ", { t: "pond", r: true }, " — 4) ", { t: "donne", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Scènes jouées : ", { t: "répliques complètes", r: true }, " (1,5 pt par réplique)."]] },
  ],
 },
 {
  n: 111,
  titre: "Bienvenue à la ferme !",
  titreFiche: "Je présente la ferme",
  sd: "Expression Orale",
  objectif: "Présenter la ferme à un visiteur : « Bienvenue ! Voici le zébu. Il y a..., ... et... »",
  supportFiche: "Image « la ferme », figurines, tableau noir.",
  revision: {
  ens: ["Joue le dialogue des produits avec ton voisin (30 secondes)."],
  app: ["R.A. : « Qu'est-ce que la vache donne ? — Elle donne du lait. »"],
  technique: ["Jeu de rôle express"],
  },
  miseEnSituation: {
  ens: ["« Un copain de la ville visite votre ferme pour la première fois. Que lui dites-vous d'abord ? »"],
  app: ["Proposent : bienvenue ! voici notre ferme..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous présentons la ferme à un visiteur : bienvenue, voici..., il y a..., et..."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez la présentation : » Bienvenue à la ferme ! Voici le zébu, il est tranquille. Il y a des poules, des canards et deux chèvres. Et là, la rizière de papa !"],
  app: ["Écoutent, puis répètent chaque phrase de présentation."],
  technique: ["Modèle oral"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Que dit-on d'abord au visiteur ?"], ["2) Comment présente-t-on le zébu ?"], ["3) Quels animaux sont dans la ferme ?"], ["4) Présente-moi la poule !"]] },
  app: { paras: [["R.A. : « ", { t: "Bienvenue !", r: true }, " »"], ["R.A. : « ", { t: "Voici le zébu.", r: true }, " »"], ["R.A. : ", { t: "Des poules, des canards et deux chèvres", r: true }, "."], ["R.A. : « ", { t: "Voici la poule, elle pond des œufs.", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : pour présenter — bienvenue, voici..., il y a..., et..."],
  app: ["Répètent le modèle en chœur, puis chacun présente un animal."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["La visite de la ferme : par deux, le guide présente, le visiteur pose des questions."],
  app: ["Jouent : bienvenue ! — qu'est-ce que c'est ? — c'est le cochon, il est rose !"],
  technique: ["Jeu de rôle par deux"],
  support: "Figurines",
  },
  evaluation: {
  ens: ["3 élèves : présente la ferme en 3 phrases (bienvenue + voici + il y a)."],
  app: ["R.A. : ", { t: "« Bienvenue ! Voici... Il y a... »", r: true }, " (3 phrases)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "111. BIENVENUE À LA FERME !",
  subs: [
   { t: "A. Mes phrases", paras: [["« ", { t: "Bienvenue à la ferme !", k: true }, " » — « ", { t: "Voici le zébu.", k: true }, " » — « ", { t: "Il y a des poules, des canards et deux chèvres.", k: true }, " »"]] },
   { t: "B. Le modèle", paras: [["Bienvenue + ", { t: "voici...", k: true }, " + ", { t: "il y a...", k: true }, " — comme pour présenter un ami !"]] },
  ],
  retenir: ["Pour présenter : ", { t: "« Bienvenue ! Voici... Il y a... »", k: true }, " — je suis le guide de la ferme !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots pour présenter :"], items: [["bienvenue"], ["la meuh"], ["voici"], ["il y a"], ["cot cot"], ["et"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) ....... à la ferme ! (Bienvenue)"], ["2) ....... la vache. (Voici)"], ["3) Il ....... trois poules. (y a)"], ["4) Il y a des poules, des canards ....... deux chèvres. (et)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Présente un animal au visiteur (4 élèves) :"], items: [["1) Présentation n°1 : ....... (réponse libre)"], ["2) Présentation n°2 : ....... (réponse libre)"], ["3) Présentation n°3 : ....... (réponse libre)"], ["4) Présentation n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Entourés : ", { t: "bienvenue, voici, il y a, et", r: true }, " (2 pts chacun) — meuh (cri) et cot cot (cri) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "Bienvenue", r: true }, " — 2) ", { t: "Voici", r: true }, " — 3) ", { t: "y a", r: true }, " — 4) ", { t: "et", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Présentations complètes : ", { t: "1,5 pt par élève", r: true }, "."]] },
  ],
 },
 {
  n: 112,
  titre: "Ma ferme idéale",
  titreFiche: "Le mini-exposé de l'année",
  sd: "Expression Orale",
  objectif: "Faire un mini-exposé : présenter ma ferme idéale (3 phrases : animaux, produits, avis).",
  supportFiche: "Image « la ferme », tableau noir.",
  revision: {
  ens: ["Présente la ferme : bienvenue, voici... (chaîne parlée)."],
  app: ["R.A. : « Bienvenue ! Voici... Il y a... »"],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Imagine ta ferme idéale : quels animaux ? quels champs ? C'est ta ferme à toi ! »"],
  app: ["Proposent : ma ferme a un zébu, des poules, un champ de riz..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, chacun présente sa ferme idéale en 3 phrases : il y a..., ça donne..., j'aime..."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez mon exemple : » Dans ma ferme idéale, il y a un zébu, cinq poules et deux canards. Ma ferme donne du lait, des œufs et du riz. J'aime ma ferme !"],
  app: ["Écoutent, repèrent les 3 phrases : il y a / ça donne / j'aime."],
  technique: ["Modèle oral"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Quelle est la première phrase de l'exposé ?"], ["2) La deuxième phrase parle de quoi ?"], ["3) Comment finit l'exposé ?"], ["4) Prépare ta première phrase !"]] },
  app: { paras: [["R.A. : « ", { t: "Dans ma ferme idéale, il y a...", r: true }, " »"], ["R.A. : Des ", { t: "produits", r: true }, " (ça donne...)."], ["R.A. : « ", { t: "J'aime ma ferme !", r: true }, " »"], ["R.A. : préparation individuelle ", { t: "à voix basse", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : mon mini-exposé — il y a... / ça donne... / j'aime..."],
  app: ["Répètent le plan en chœur : trois phrases, trois étapes."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Répète ton exposé avec ton voisin, puis présente-le à la classe."],
  app: ["Répètent à deux, puis présentent chacun leur ferme."],
  technique: ["Mini-exposé"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["4 élèves : présente ta ferme idéale (3 phrases complètes)."],
  app: ["R.A. : ", { t: "il y a / ça donne / j'aime", r: true }, " (3 phrases, 1,5 pt par phrase)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "112. MA FERME IDÉALE",
  subs: [
   { t: "A. Mon plan", paras: [["1. « ", { t: "Dans ma ferme, il y a...", k: true }, " » — 2. « ", { t: "Ma ferme donne...", k: true }, " » — 3. « ", { t: "J'aime ma ferme !", k: true }, " »"]] },
  ],
  retenir: ["Mon exposé : ", { t: "il y a / ça donne / j'aime", k: true }, " — trois phrases bien construites !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Remets les phrases de l'exposé en ordre (1, 2, 3) + intrus :"], items: [["J'aime ma ferme ! (3)"], ["Ma ferme donne du lait et des œufs. (2)"], ["Le café est chaud. (intrus)"], ["Dans ma ferme, il y a un zébu et des poules. (1)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Dans ma ferme, il ....... un zébu. (y a)"], ["2) Ma ferme ....... du riz. (donne)"], ["3) J'....... ma ferme ! (aime)"], ["4) Il y a ....... poules et deux canards. (cinq)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Écris tes 3 phrases au brouillon et prépare ton exposé (4 élèves présentent) :"], items: [["1) Exposé n°1 : ....... (réponse libre)"], ["2) Exposé n°2 : ....... (réponse libre)"], ["3) Exposé n°3 : ....... (réponse libre)"], ["4) Exposé n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Ordre : ", { t: "il y a → donne → j'aime", r: true }, " — la phrase du café est l'intrus (non placée)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "y a", r: true }, " — 2) ", { t: "donne", r: true }, " — 3) ", { t: "aime", r: true }, " — 4) ", { t: "cinq", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Exposés en 3 phrases complètes : ", { t: "1,5 pt par exposé", r: true }, "."]] },
  ],
 },
 {
  n: 113,
  titre: "Le son ou",
  titreFiche: "J'entends ou",
  sd: "Lecture",
  objectif: "Reconnaître et lire le son ou : la poule, le poulet, la roue, le genou, le pou.",
  supportFiche: "Image « la ferme », syllabes au tableau, ardoises.",
  revision: {
  ens: ["Présente ta ferme idéale en 3 phrases (2 élèves)."],
  app: ["R.A. : « Il y a... ça donne... j'aime... »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Écoutez : o-u, ou ! La poule ! La roue ! Répétez ! »"],
  app: ["Répètent : ou, ou — la poule, la roue !"],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons le son ou : o-u font « ou », comme dans la poule et le genou."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image et écoutez : » la POULE, le POULET, la ROUE, le GENOU, le POU. Entendez-vous ou ?"],
  app: ["Observent, écoutent, répondent : oui, on entend ou partout !"],
  technique: ["Observation guidée"],
  support: "Image « la ferme », syllabes au tableau",
  },
  analyse: {
  ens: { paras: [["1) Avec quelles lettres écrit-on le son ou ?"], ["2) Que dit o-u ensemble ?"], ["3) Cite un mot avec ou."], ["4) Dans « genou », où est ou ?"]] },
  app: { paras: [["R.A. : Avec ", { t: "o et u", r: true }, "."], ["R.A. : ", { t: "ou", r: true }, " !"], ["R.A. : ", { t: "la poule, le poulet, la roue, le genou, le pou", r: true }, " (réponse libre)."], ["R.A. : À la fin : ", { t: "genou", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Syllabes au tableau",
  },
  synthese: {
  ens: ["Donc : le son ou s'écrit o-u — la poule, le poulet, la roue, le genou, le pou."],
  app: ["Lisent les 5 mots en chœur, puis la phrase : la poule picore dans la cour."],
  technique: ["Lecture collective"],
  support: "Syllabes au tableau",
  },
  application: {
  ens: ["Lecture flash : je montre un mot, vous lisez vite (poule, poulet, roue, genou, cour)."],
  app: ["Lisent vite, en chœur et individuellement."],
  technique: ["Lecture flash"],
  support: "Ardoises, mots au tableau",
  },
  evaluation: {
  ens: ["3 élèves : lis 3 mots avec ou."],
  app: ["R.A. : ", { t: "la poule, le poulet, la roue, le genou, le pou", r: true }, " (3 mots lus correctement)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "113. LE SON OU",
  subs: [
   { t: "A. Le son", paras: [["Le son ", { t: "ou", k: true }, " s'écrit avec ", { t: "deux lettres : o-u", k: true }, " — les lèvres rondes comme un petit tunnel !"]] },
   { t: "B. Les mots", paras: [[{ t: "la poule", k: true }, " — ", { t: "le poulet", k: true }, " — ", { t: "la roue", k: true }, " — ", { t: "le genou", k: true }, " — ", { t: "le pou", k: true }]] },
  ],
  retenir: ["Le son ", { t: "ou", k: true }, " : ", { t: "la poule, le poulet, la roue, le genou", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son ou :"], items: [["la poule"], ["le riz"], ["la roue"], ["le pain"], ["le genou"], ["le poulet"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec ou :"], items: [["1) la p...le (poule)"], ["2) la r...e (roue)"], ["3) le gen... (genou)"], ["4) le p...let (poulet)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis ta phrase avec ou à haute voix (4 élèves) :"], items: [["1) La poule picore dans la cour. (lecture)"], ["2) Le poulet a un petit bec. (lecture)"], ["3) La roue de la charrette tourne. (lecture)"], ["4) J'ai mal au genou. (lecture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "la poule, la roue, le genou, le poulet", r: true }, " (2 pts chacun) — le riz et le pain : pas de ou."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "ou", r: true }, " — 2) ", { t: "ou", r: true }, " — 3) ", { t: "ou", r: true }, " — 4) ", { t: "ou", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Phrases lues sans hésitation : ", { t: "1,5 pt par phrase", r: true }, "."]] },
  ],
 },
 {
  n: 114,
  titre: "Le son ou (2)",
  titreFiche: "Le loup, le hibou, la cour",
  sd: "Lecture",
  objectif: "Lire des mots et des phrases avec ou : le loup, le hibou, la cour, le bisou, doux.",
  supportFiche: "Image « la ferme », syllabes au tableau, ardoises.",
  revision: {
  ens: ["Lis : poule, poulet, roue, genou, pou (lecture flash)."],
  app: ["Lisent : poule, poulet, roue, genou, pou."],
  technique: ["Lecture flash"],
  },
  miseEnSituation: {
  ens: ["« Qui connaît d'autres mots avec ou ? Le loup des histoires ! Le hibou de la nuit ! »"],
  app: ["Proposent : le loup, le hibou, la cour..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons encore des mots avec ou : le loup, le hibou, la cour, le bisou, doux."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » le LOUP hurle, le HIBOU vole la nuit, la POULE picore dans la COUR, maman fait un BISOU doux."],
  app: ["Observent, répètent chaque mot en le mimant."],
  technique: ["Observation guidée"],
  support: "Image « la ferme », syllabes au tableau",
  },
  analyse: {
  ens: { paras: [["1) Qui hurle la nuit dans les histoires ?"], ["2) Quel oiseau vole la nuit ?"], ["3) Où picore la poule ?"], ["4) Cite un mot avec ou que tu connais."]] },
  app: { paras: [["R.A. : Le ", { t: "loup", r: true }, "."], ["R.A. : Le ", { t: "hibou", r: true }, "."], ["R.A. : Dans la ", { t: "cour", r: true }, "."], ["R.A. : ", { t: "le bisou, doux, le genou...", r: true }, " (réponse libre)."]] },
  technique: ["Question / réponse"],
  support: "Syllabes au tableau",
  },
  synthese: {
  ens: ["Donc : encore des mots avec ou — le loup, le hibou, la cour, le bisou, doux."],
  app: ["Lisent les 5 mots en chœur, puis la phrase : le hibou doux dort sur le toit."],
  technique: ["Lecture collective"],
  support: "Syllabes au tableau",
  },
  application: {
  ens: ["Le tri ou / pas ou : je dis un mot, vous montrez la carte ou si vous entendez ou (loup, riz, cour, poule, nuit, doux)."],
  app: ["Lèvent la carte ou : loup, cour, poule, doux (pas riz, pas nuit)."],
  technique: ["Jeu de tri avec cartes"],
  support: "Ardoises",
  },
  evaluation: {
  ens: ["3 élèves : lis 3 nouveaux mots avec ou."],
  app: ["R.A. : ", { t: "le loup, le hibou, la cour, le bisou, doux", r: true }, " (3 mots lus correctement)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "114. LE SON OU (2)",
  subs: [
   { t: "A. Les nouveaux mots", paras: [[{ t: "le loup", k: true }, " — ", { t: "le hibou", k: true }, " — ", { t: "la cour", k: true }, " — ", { t: "le bisou", k: true }, " — ", { t: "doux", k: true }]] },
   { t: "B. Ma phrase", paras: [["« ", { t: "Le hibou doux dort sur le toit.", k: true }, " »"]] },
  ],
  retenir: ["Le son ", { t: "ou", k: true }, " partout : ", { t: "loup, hibou, cour, bisou, doux", k: true }, " !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son ou :"], items: [["le loup"], ["la nuit"], ["le hibou"], ["la cour"], ["le riz"], ["doux"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec ou :"], items: [["1) le l...p (loup)"], ["2) le hib... (hibou)"], ["3) la c...r (cour)"], ["4) le bis... (bisou)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis la phrase à haute voix (4 élèves) :"], items: [["1) Le loup hurle dans la forêt. (lecture)"], ["2) Le hibou vole la nuit. (lecture)"], ["3) La poule picore dans la cour. (lecture)"], ["4) Maman fait un bisou doux. (lecture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le loup, le hibou, la cour, doux", r: true }, " (2 pts chacun) — la nuit (ui) et le riz non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "ou", r: true }, " — 2) ", { t: "ou", r: true }, " — 3) ", { t: "ou", r: true }, " — 4) ", { t: "ou", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Phrases lues sans hésitation : ", { t: "1,5 pt par phrase", r: true }, "."]] },
  ],
 },
 {
  n: 115,
  titre: "Le son œu",
  titreFiche: "Le œuf et le bœuf",
  sd: "Lecture",
  objectif: "Reconnaître et lire le son œu : l'œuf, le bœuf, le nœud (les deux lettres œ collées).",
  supportFiche: "Image « la ferme », œuf réel, syllabes au tableau, ardoises.",
  revision: {
  ens: ["Lis : loup, hibou, cour, bisou, doux (lecture flash)."],
  app: ["Lisent : loup, hibou, cour, bisou, doux."],
  technique: ["Lecture flash"],
  },
  miseEnSituation: {
  ens: ["« Regardez cette lettre bizarre : œ ! C'est un o et un e collés ensemble ! Le œuf ! Le bœuf ! »"],
  app: ["Observent la lettre œ, répètent : œuf, bœuf, nœud !"],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons le son œu : il s'écrit œ, un o et un e collés — l'œuf, le bœuf, le nœud."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » l'ŒUF de la poule, le BŒUF qui tire la charrette, le NŒUD de la corde. Voyez-vous les deux lettres collées ?"],
  app: ["Observent, répondent : oui, o et e sont collés dans œ !"],
  technique: ["Observation guidée"],
  support: "Image « la ferme », œuf réel",
  },
  analyse: {
  ens: { paras: [["1) Avec quelles lettres collées écrit-on œ ?"], ["2) Que donne la poule ? (le mot avec œ)"], ["3) Que tire le bœuf ?"], ["4) Cite un mot avec œ."]] },
  app: { paras: [["R.A. : ", { t: "o et e", r: true }, "."], ["R.A. : L'", { t: "œuf", r: true }, "."], ["R.A. : La ", { t: "charrette", r: true }, "."], ["R.A. : ", { t: "l'œuf, le bœuf, le nœud", r: true }, " (réponse libre)."]] },
  technique: ["Question / réponse"],
  support: "Syllabes au tableau",
  },
  synthese: {
  ens: ["Donc : le son œu s'écrit œ (o-e collés) — l'œuf, le bœuf, le nœud."],
  app: ["Lisent les 3 mots en chœur, puis la phrase : la poule pond un œuf, le bœuf tire la charrette."],
  technique: ["Lecture collective"],
  support: "Syllabes au tableau",
  },
  application: {
  ens: ["Lecture en écho : je lis un mot, vous le relisez comme un écho (œuf, bœuf, nœud, les œufs)."],
  app: ["Relisent en écho, puis individuellement."],
  technique: ["Lecture en écho"],
  support: "Ardoises, mots au tableau",
  },
  evaluation: {
  ens: ["3 élèves : lis 3 mots avec œ."],
  app: ["R.A. : ", { t: "l'œuf, le bœuf, le nœud", r: true }, " (3 mots lus correctement)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "115. LE SON ŒU",
  subs: [
   { t: "A. La lettre collée", paras: [["Le son ", { t: "œu", k: true }, " s'écrit ", { t: "œ", k: true }, " : un ", { t: "o et un e collés ensemble", k: true }, " !"]] },
   { t: "B. Les mots", paras: [[{ t: "l'œuf", k: true }, " — ", { t: "le bœuf", k: true }, " — ", { t: "le nœud", k: true }, " — ", { t: "les œufs", k: true }]] },
  ],
  retenir: ["Le son ", { t: "œu", k: true }, " : ", { t: "l'œuf, le bœuf, le nœud", k: true }, " — avec la lettre collée œ !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent la lettre œ :"], items: [["l'œuf"], ["le pou"], ["le bœuf"], ["la roue"], ["le nœud"], ["le genou"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec œ :"], items: [["1) l'...uf (œuf)"], ["2) le b...uf (bœuf)"], ["3) le n...ud (nœud)"], ["4) les ...ufs (œufs)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis ta phrase avec œ à haute voix (4 élèves) :"], items: [["1) La poule pond un œuf. (lecture)"], ["2) Le bœuf tire la charrette. (lecture)"], ["3) La corde a un nœud. (lecture)"], ["4) Le panier est plein d'œufs. (lecture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "l'œuf, le bœuf, le nœud", r: true }, " (2 pts chacun) — pou, roue, genou : son ou, non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "œ", r: true }, " — 2) ", { t: "œ", r: true }, " — 3) ", { t: "œ", r: true }, " — 4) ", { t: "œ", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Phrases lues sans hésitation : ", { t: "1,5 pt par phrase", r: true }, "."]] },
  ],
 },
 {
  n: 116,
  titre: "Lecture — ou et œu ensemble",
  titreFiche: "Le petit texte de la ferme",
  sd: "Lecture",
  objectif: "Lire un petit texte avec ou et œu : « La poule picore dans la cour. Elle pond un œuf. Le bœuf boit. »",
  supportFiche: "Texte au tableau, image « la ferme », ardoises.",
  revision: {
  ens: ["Lis : œuf, bœuf, nœud, les œufs (lecture flash)."],
  app: ["Lisent : œuf, bœuf, nœud, les œufs."],
  technique: ["Lecture flash"],
  },
  miseEnSituation: {
  ens: ["« Aujourd'hui, nous lisons un vrai petit texte de la ferme, avec tous les mots que nous connaissons ! »"],
  app: ["Se préparent, suivent sur le tableau."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons le petit texte de la ferme : trois phrases avec ou et œu."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Texte au tableau",
  },
  observation: {
  ens: ["« Écoutez d'abord le texte : » La poule picore dans la cour. Elle pond un œuf. Le bœuf boit à la mare. — Maintenant lisez avec moi."],
  app: ["Écoutent, puis lisent phrase par phrase avec l'enseignant."],
  technique: ["Lecture en écho"],
  support: "Texte au tableau",
  },
  analyse: {
  ens: { paras: [["1) Qui picore dans la cour ?"], ["2) Que pond la poule ?"], ["3) Que fait le bœuf ?"], ["4) Souligne les mots avec ou et les mots avec œ !"]] },
  app: { paras: [["R.A. : La ", { t: "poule", r: true }, "."], ["R.A. : Un ", { t: "œuf", r: true }, "."], ["R.A. : Il ", { t: "boit", r: true }, " à la mare."], ["R.A. : ", { t: "poule, cour, picore / œuf, bœuf", r: true }, " (au tableau)."]] },
  technique: ["Question / réponse"],
  support: "Texte au tableau",
  },
  synthese: {
  ens: ["Donc : je sais lire ou et œu dans un vrai texte — poule, cour, œuf, bœuf."],
  app: ["Relisent le texte complet en chœur, puis par deux."],
  technique: ["Lecture collective"],
  support: "Texte au tableau",
  },
  application: {
  ens: ["Chaque élève lit une phrase à voix haute, puis un volontaire lit tout le texte."],
  app: ["Lisent à tour de rôle, puis le volontaire lit le texte entier."],
  technique: ["Lecture individuelle"],
  support: "Texte au tableau",
  },
  evaluation: {
  ens: ["3 élèves : lis le texte complet sans aide."],
  app: ["R.A. : texte ", { t: "lu correctement", r: true }, " (ou et œu bien prononcés)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "116. LECTURE — OU ET ŒU ENSEMBLE",
  subs: [
   { t: "A. Mon texte", paras: [["« ", { t: "La poule picore dans la cour.", k: true }, " » — « ", { t: "Elle pond un œuf.", k: true }, " » — « ", { t: "Le bœuf boit à la mare.", k: true }, " »"]] },
   { t: "B. Les mots du texte", paras: [[{ t: "ou", k: true }, " : ", { t: "poule, cour, picore", k: true }, " — ", { t: "œu", k: true }, " : ", { t: "œuf, bœuf", k: true }]] },
  ],
  retenir: ["Je lis ", { t: "ou", k: true }, " et ", { t: "œu", k: true }, " dans un vrai texte — je lis comme un grand !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Relis le texte et réponds :"], items: [["1) Qui picore dans la cour ? (la poule)"], ["2) Que pond la poule ? (un œuf)"], ["3) Que fait le bœuf ? (il boit)"], ["4) Où boit le bœuf ? (à la mare)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Classe les mots du texte (ou ou œu) :"], items: [["1) poule : ....... (ou)"], ["2) œuf : ....... (œu)"], ["3) cour : ....... (ou)"], ["4) bœuf : ....... (œu)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis le texte entier à haute voix (4 volontaires) :"], items: [["1) Lecture n°1 : ......."], ["2) Lecture n°2 : ......."], ["3) Lecture n°3 : ......."], ["4) Lecture n°4 : ......."]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["1) ", { t: "la poule", r: true }, " — 2) ", { t: "un œuf", r: true }, " — 3) ", { t: "il boit", r: true }, " — 4) ", { t: "à la mare", r: true }, " (2 pts chacun)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "ou", r: true }, " — 2) ", { t: "œu", r: true }, " — 3) ", { t: "ou", r: true }, " — 4) ", { t: "œu", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Lectures complètes fluides : ", { t: "1,5 pt par lecture", r: true }, "."]] },
  ],
 },
 {
  n: 117,
  titre: "Écrire ou",
  titreFiche: "J'écris ou",
  sd: "Écriture",
  objectif: "Écrire proprement des mots avec ou : poule, poulet, roue, genou.",
  supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
  revision: {
  ens: ["Relis le texte de la ferme (lecture collective)."],
  app: ["Relisent : la poule picore dans la cour..."],
  technique: ["Lecture collective"],
  },
  miseEnSituation: {
  ens: ["« Nous savons lire ou ; maintenant nous allons l'écrire : le o rond, puis le u avec son crochet. »"],
  app: ["Tracent ou dans l'air avec le doigt."],
  technique: ["Tracé dans l'air"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous écrivons ou : le o rond et fermé, le u qui descend et remonte."],
  app: ["Écoutent et observent le modèle au tableau."],
  technique: ["Annonce orale"],
  support: "Lignes d'écriture au tableau",
  },
  observation: {
  ens: ["« Observez mon tracé : » j'écris ou trois fois — le o bien rond, le u bien droit, collés ensemble."],
  app: ["Observent les lettres, disent : o rond, u avec son crochet !"],
  technique: ["Modèle d'écriture"],
  support: "Tableau noir",
  },
  analyse: {
  ens: { paras: [["1) Quelles lettres pour ou ?"], ["2) Le o : comment est-il ?"], ["3) Épelle « poule »."], ["4) Épelle « genou »."]] },
  app: { paras: [["R.A. : ", { t: "o et u", r: true }, "."], ["R.A. : ", { t: "Rond et fermé", r: true }, "."], ["R.A. : ", { t: "p-o-u-l-e", r: true }, "."], ["R.A. : ", { t: "g-e-n-o-u", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : ou = o rond + u crochet ; j'écris poule, poulet, roue, genou."],
  app: ["Écrivent ou deux fois sur l'ardoise avant le cahier."],
  technique: ["Écriture guidée"],
  support: "Ardoises",
  },
  application: {
  ens: ["Au cahier : écris ou, poule, poulet, roue, genou — beaux o ronds et u droits."],
  app: ["Écrivent les 5 mots sur leurs cahiers."],
  technique: ["Copie individuelle"],
  support: "Cahiers",
  },
  evaluation: {
  ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
  app: ["R.A. : ", { t: "poule, poulet, roue, genou", r: true }, " écrits sans faute."],
  technique: ["Vérification des cahiers"],
  },
  lecon: {
  titre: "117. ÉCRIRE OU",
  subs: [
   { t: "A. Les lettres", paras: [["Le son ", { t: "ou", k: true }, " : ", { t: "o rond", k: true }, " + ", { t: "u avec son crochet", k: true }, " — collés ensemble !"]] },
   { t: "B. Mes mots", paras: [[{ t: "la poule", k: true }, " — ", { t: "le poulet", k: true }, " — ", { t: "la roue", k: true }, " — ", { t: "le genou", k: true }]] },
  ],
  retenir: ["J'écris ", { t: "o-u", k: true }, " ensemble : ", { t: "poule, poulet, roue, genou", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Écris ou deux fois sur l'ardoise :"], items: [["1) ou n°1 (tracé)"], ["2) ou n°2 (tracé)"], ["3) o rond bien fermé (1 pt)"], ["4) u avec son crochet (1 pt)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) poule (copie)"], ["2) poulet (copie)"], ["3) roue (copie)"], ["4) genou (copie)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Complète en écrivant ou :"], items: [["1) la p...le (poule)"], ["2) la r...e (roue)"], ["3) le gen... (genou)"], ["4) le p...let (poulet)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "o rond, u crochet", r: true }, " (2 pts par ou réussi)."]] },
  { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["1) ", { t: "ou", r: true }, " — 2) ", { t: "ou", r: true }, " — 3) ", { t: "ou", r: true }, " — 4) ", { t: "ou", r: true }, " (1,5 pt par mot complété)."]] },
  ],
 },
 {
  n: 118,
  titre: "Écrire œu",
  titreFiche: "J'écris le œ collé",
  sd: "Écriture",
  objectif: "Écrire proprement des mots avec œ : œuf, bœuf, nœud.",
  supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
  revision: {
  ens: ["Épelle poule et genou (2 élèves)."],
  app: ["R.A. : ", { t: "p-o-u-l-e", r: true }, " ; ", { t: "g-e-n-o-u", r: true }, "."],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Nous écrivons la lettre collée œ : un petit o, et dedans un e — comme un œil dans l'œuf ! »"],
  app: ["Tracent œ dans l'air avec le doigt."],
  technique: ["Tracé dans l'air"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous écrivons œ : le o et le e se touchent, collés pour toujours."],
  app: ["Écoutent et observent le modèle au tableau."],
  technique: ["Annonce orale"],
  support: "Lignes d'écriture au tableau",
  },
  observation: {
  ens: ["« Observez mon tracé : » j'écris œ trois fois — le o rond d'abord, puis le e qui vient se coller contre lui."],
  app: ["Observent la lettre, disent : le o et le e collés !"],
  technique: ["Modèle d'écriture"],
  support: "Tableau noir",
  },
  analyse: {
  ens: { paras: [["1) Quelles lettres forment œ ?"], ["2) Épelle « œuf »."], ["3) Épelle « bœuf »."], ["4) Épelle « nœud »."]] },
  app: { paras: [["R.A. : ", { t: "o et e", r: true }, "."], ["R.A. : ", { t: "œ-u-f", r: true }, "."], ["R.A. : ", { t: "b-œ-u-f", r: true }, "."], ["R.A. : ", { t: "n-œ-u-d", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : j'écris œ (o-e collés) — œuf, bœuf, nœud."],
  app: ["Écrivent œ deux fois sur l'ardoise avant le cahier."],
  technique: ["Écriture guidée"],
  support: "Ardoises",
  },
  application: {
  ens: ["Au cahier : écris œ, œuf, bœuf, nœud — des o et des e bien collés."],
  app: ["Écrivent les 4 mots sur leurs cahiers."],
  technique: ["Copie individuelle"],
  support: "Cahiers",
  },
  evaluation: {
  ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
  app: ["R.A. : ", { t: "œuf, bœuf, nœud", r: true }, " écrits sans faute (œ bien collés)."],
  technique: ["Vérification des cahiers"],
  },
  lecon: {
  titre: "118. ÉCRIRE ŒU",
  subs: [
   { t: "A. La lettre collée", paras: [["J'écris ", { t: "œ", k: true }, " : le ", { t: "o", k: true }, " et le ", { t: "e", k: true }, " ", { t: "collés ensemble", k: true }, " — jamais séparés !"]] },
   { t: "B. Mes mots", paras: [[{ t: "l'œuf", k: true }, " — ", { t: "le bœuf", k: true }, " — ", { t: "le nœud", k: true }]] },
  ],
  retenir: ["J'écris ", { t: "œ", k: true }, " collé : ", { t: "œuf, bœuf, nœud", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Écris œ deux fois sur l'ardoise :"], items: [["1) œ n°1 (tracé)"], ["2) œ n°2 (tracé)"], ["3) o bien rond (1 pt)"], ["4) e bien collé au o (1 pt)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) œuf (copie)"], ["2) bœuf (copie)"], ["3) nœud (copie)"], ["4) les œufs (copie)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Complète en écrivant œ :"], items: [["1) l'...uf (œuf)"], ["2) le b...uf (bœuf)"], ["3) le n...ud (nœud)"], ["4) les ...ufs (œufs)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "o et e bien collés", r: true }, " (2 pts par œ réussi)."]] },
  { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["1) ", { t: "œ", r: true }, " — 2) ", { t: "œ", r: true }, " — 3) ", { t: "œ", r: true }, " — 4) ", { t: "œ", r: true }, " (1,5 pt par mot complété)."]] },
  ],
 },
 {
  n: 119,
  titre: "Dictée — ou et œu",
  titreFiche: "Je dicte et j'écris",
  sd: "Écriture",
  objectif: "Écrire sous la dictée des mots avec ou et œu.",
  supportFiche: "Tableau noir, cahiers de dictée.",
  revision: {
  ens: ["Relis au tableau : poule, roue, œuf, bœuf (lecture collective)."],
  app: ["Relisent et épellent ou, œu."],
  technique: ["Lecture collective"],
  },
  miseEnSituation: {
  ens: ["« Aujourd'hui, grande dictée des sons de la ferme : ou et œu. Écoutez, répétez, puis écrivez. »"],
  app: ["Se préparent : cahier ouvert, crayon en main."],
  technique: ["Rituel de dictée"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous écrivons sous la dictée : d'abord des mots, puis une phrase."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Relisez les modèles avant la dictée : » poule, poulet, roue, genou, œuf, bœuf, nœud."],
  app: ["Relisent chaque mot, épellent ou, œu."],
  technique: ["Relecture guidée"],
  support: "Tableau noir",
  },
  analyse: {
  ens: { paras: [["1) Dans « poule », quelles lettres font le son ou ?"], ["2) Dans « œuf », quelle lettre collée ?"], ["3) Dans « genou », où est ou ?"], ["4) Répétez la phrase : la poule pond un œuf dans la cour."]] },
  app: { paras: [["R.A. : ", { t: "o-u", r: true }, "."], ["R.A. : ", { t: "œ", r: true }, "."], ["R.A. : À la fin : ", { t: "genou", r: true }, "."], ["R.A. : ", { t: "la poule pond un œuf dans la cour", r: true }, " (répétition exacte)."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : j'écoute le son — ou ou œu — puis j'écris les bonnes lettres."],
  app: ["Répètent la stratégie : j'écoute, je trouve le son, j'écris."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Dictée : poule, œuf, bœuf — puis la phrase : la poule pond un œuf dans la cour."],
  app: ["Écrivent sous la dictée, mot par mot, puis la phrase."],
  technique: ["Dictée"],
  support: "Cahiers de dictée",
  },
  evaluation: {
  ens: ["Correction collective au tableau, puis 3 cahiers vérifiés."],
  app: ["Corrigent avec le modèle : ", { t: "poule, œuf, bœuf + la phrase", r: true }, "."],
  technique: ["Correction collective"],
  },
  lecon: {
  titre: "119. DICTÉE — OU ET ŒU",
  subs: [
   { t: "A. Ma dictée", paras: [["Mots : ", { t: "poule, œuf, bœuf", k: true }, " — phrase : ", { t: "la poule pond un œuf dans la cour", k: true }, "."]] },
   { t: "B. Ma méthode", paras: [["J'écoute le son → ", { t: "ou ou œu", k: true }, " → j'écris les ", { t: "bonnes lettres", k: true }, "."]] },
  ],
  retenir: ["Dictée réussie : ", { t: "ou et œu bien écrits", k: true }, " et majuscule + point pour la phrase."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Dictée de mots (4 mots) :"], items: [["1) poule (dictée)"], ["2) roue (dictée)"], ["3) œuf (dictée)"], ["4) bœuf (dictée)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Dictée de la phrase :"], items: [["1) La poule pond un œuf dans la cour. (dictée)"], ["2) Majuscule au début (1,5 pt)"], ["3) Point à la fin (1,5 pt)"], ["4) ou et œu bien écrits (3 pts)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Auto-correction : je relis et je répare (4 élèves) :"], items: [["1) Mon mot n°1 : ....... (relecture)"], ["2) Mon mot n°2 : ....... (relecture)"], ["3) Mon mot n°3 : ....... (relecture)"], ["4) Ma phrase : ....... (relecture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots exacts : ", { t: "poule, roue, œuf, bœuf", r: true }, " (2 pts chacun)."]] },
  { titre: "Exercice 2", lines: [["Phrase exacte : ", { t: "La poule pond un œuf dans la cour.", r: true }, " — majuscule, point, ou et œu justes."]] },
  { titre: "Exercice 3", lines: [["Relectures avec corrections : ", { t: "fautes réparées", r: true }, " (1,5 pt par relecture)."]] },
  ],
 },
 {
  n: 120,
  titre: "Bilan de l'unité 8 et du manuel",
  titreFiche: "Le grand bilan du CP2",
  sd: "Écriture",
  objectif: "Faire le bilan de l'unité 8 (ferme, ou, œu) et le grand bilan de l'année.",
  supportFiche: "Image « la ferme », tableau noir, cahiers.",
  revision: {
  ens: ["Relis les mots de la dictée : poule, roue, œuf, bœuf."],
  app: ["Relisent et épellent les sons ou, œu."],
  technique: ["Lecture collective"],
  },
  miseEnSituation: {
  ens: ["« Voici le grand bilan de la ferme... et de toute votre année de CP2 : 120 séances, 8 unités ! »"],
  app: ["Écoutent, se rappellent toutes les unités."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, le bilan final : la ferme, les sons ou et œu, et tout ce que nous avons appris cette année !"],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Regardez l'image de la ferme et souvenez-vous : » les animaux, les travaux des champs, la rizière, les cris, les produits."],
  app: ["Observent l'image et énumèrent les acquis de l'unité 8."],
  technique: ["Observation guidée"],
  support: "Image « la ferme »",
  },
  analyse: {
  ens: { paras: [["1) Cite 4 animaux de la ferme."], ["2) Que donne la vache ? Et la poule ?"], ["3) Cite un mot avec ou et un mot avec œ."], ["4) Nomme les 8 unités de l'année !"]] },
  app: { paras: [["R.A. : ", { t: "vache, zébu, poule, canard...", r: true }, " (4 animaux)."], ["R.A. : Du ", { t: "lait", r: true }, " / des ", { t: "œufs", r: true }, "."], ["R.A. : ", { t: "poule / œuf", r: true }, " (2 mots avec les sons)."], ["R.A. : ", { t: "présentation, famille, toilette, école, vêtements, marché, repas, ferme", r: true }, " !"]] },
  technique: ["Question / réponse"],
  support: "Image « la ferme »",
  },
  synthese: {
  ens: ["Donc : la ferme, les sons ou et œu — et l'année complète : 120 séances, 8 unités, bravo !"],
  app: ["Récitent la comptine de la ferme une dernière fois en chœur, très fort."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Dictée finale : poule, œuf, bœuf — la poule pond un œuf dans la cour."],
  app: ["Écrivent sous la dictée, mot par mot, puis la phrase."],
  technique: ["Dictée"],
  support: "Cahiers de dictée",
  },
  evaluation: {
  ens: ["Correction collective, puis grande évaluation orale de fin d'année."],
  app: ["Corrigent avec le modèle : ", { t: "poule, œuf, bœuf + la phrase", r: true }, " — année réussie !"],
  technique: ["Correction collective"],
  },
  lecon: {
  titre: "120. BILAN DE L'UNITÉ 8 ET DU MANUEL",
  subs: [
   { t: "A. La dictée", paras: [["J'écris : ", { t: "poule, œuf, bœuf", k: true }, " — ", { t: "la poule pond un œuf dans la cour", k: true }]] },
   { t: "B. Bilan de l'année", paras: [[{ t: "8 unités", k: true }, " : présentation, famille, toilette, école, vêtements, marché, repas, ferme — ", { t: "120 séances, tout est appris !", k: true }]] },
  ],
  retenir: ["Unité 8 réussie : ", { t: "la ferme et les sons ou, œu", k: true }, " — et le CP2 terminé, bravo !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Dictée finale :"], items: [["1) poule (dictée)"], ["2) genou (dictée)"], ["3) œuf (dictée)"], ["4) la poule pond un œuf dans la cour (dictée)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Classe les sons (ou ou œu) :"], items: [["1) la r...e : ....... (roue : ou)"], ["2) le b...uf : ....... (bœuf : œu)"], ["3) le hib... : ....... (hibou : ou)"], ["4) le n...ud : ....... (nœud : œu)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Dis ta phrase de fin d'année : « Cette année, j'ai appris... » (4 élèves) :"], items: [["1) Élève n°1 : ....... (réponse libre)"], ["2) Élève n°2 : ....... (réponse libre)"], ["3) Élève n°3 : ....... (réponse libre)"], ["4) Élève n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Dictée exacte : ", { t: "poule, genou, œuf", r: true }, " (2 pts chacun) + phrase complète (2 pts)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "ou", r: true }, " — 2) ", { t: "œu", r: true }, " — 3) ", { t: "ou", r: true }, " — 4) ", { t: "œu", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Phrases de fin d'année : ", { t: "1,5 pt par élève", r: true }, "."]] },
  ],
 },
 ],
};

module.exports = { theme8 };
