// data-theme6.js — Unité 6 « Le marché » (séances 66 à 83)
// Sources : FRA 10ème (T3 : marché, sons oi, ui, ph) + PDF CP2 unité VI (18 séances)
// + RAPE T2 2025-2026 P3 (activités quotidiennes, lexique du commerce, indicateurs temporels).
// sd par séance : EO s66-75, Lecture s76-78, Écriture s79-83. Barème 8+6+6 = 20 partout.

const theme6 = {
 numero: 6,
 nom: "Le marché",
 sousDiscipline: "Expression Orale",
 notions: "Le vocabulaire du marché (fruits, légumes, prix), le dialogue de l'achat, et les sons oi, ui et ph.",
 competences: [
  "Nommer les fruits et les légumes du marché malgache.",
  "Jouer le dialogue de l'achat : « Combien coûte... ? — Ça coûte... ariary. »",
  "Reconnaître et prononcer les sons oi, ui et ph.",
  "Écrire des mots simples avec oi, ui et ph.",
 ],
 seances: [
  {
   n: 66,
   titre: "Le vocabulaire des fruits",
   titreFiche: "Les fruits que je connais",
   sd: "Expression Orale",
   objectif: "Nommer les fruits du marché : la banane, la mangue, l'ananas, l'orange, le citron, la pomme.",
   supportFiche: "Image « le marché », fruits réels ou dessins, tableau noir.",
   revision: {
    ens: ["Le grand bilan de l'unité 5 : dis la comptine des vêtements (2 élèves)."],
    app: ["R.A. : « ", { t: "Pantalon, robe et chemise...", r: true }, " »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Ce matin, qui a mangé un fruit ? Lequel ? Qu'avez-vous vu au marché ? »"],
    app: ["Proposent : la banane, la mangue, l'orange..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots des fruits : la banane, la mangue, l'ananas, l'orange, le citron, la pomme."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez l'image du marché : » je montre chaque fruit, les élèves le nomment."],
    app: ["Observent et nomment : la banane, la mangue, l'ananas, l'orange, le citron, la pomme."],
    technique: ["Observation guidée"],
    support: "Image « le marché », fruits réels",
   },
   analyse: {
    ens: { paras: [["1) Quel fruit est long et jaune ?"], ["2) Quel fruit a des piquants ?"], ["3) Quel fruit est rond et orange ?"], ["4) Quel fruit aimez-vous le plus ?"]] },
    app: { paras: [["R.A. : La ", { t: "banane", r: true }, "."], ["R.A. : L'", { t: "ananas", r: true }, "."], ["R.A. : L'", { t: "orange", r: true }, "."], ["R.A. : ", { t: "La mangue, la banane...", r: true }, " (réponse personnelle)."]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : les fruits — la banane, la mangue, l'ananas, l'orange, le citron, la pomme."],
    app: ["Répètent les 6 mots en chœur en les mimant avec les mains."],
    technique: ["Répétition collective"],
    support: "Image « le marché »",
   },
   application: {
    ens: ["Le panier magique : je cache un fruit, vous devinez lequel a disparu."],
    app: ["Observent, ferment les yeux, devinent : c'est la mangue !"],
    technique: ["Jeu du panier magique"],
    support: "Fruits réels ou dessins",
   },
   evaluation: {
    ens: ["3 élèves : nomme 3 fruits."],
    app: ["R.A. : ", { t: "banane, mangue, ananas, orange, citron, pomme", r: true }, " (3 mots corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "66. LE VOCABULAIRE DES FRUITS",
    subs: [
     { t: "A. Les fruits", paras: [[{ t: "la banane", k: true }, " — ", { t: "la mangue", k: true }, " — ", { t: "l'ananas", k: true }, " — ", { t: "l'orange", k: true }, " — ", { t: "le citron", k: true }, " — ", { t: "la pomme", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "J'aime la mangue et la banane.", k: true }, " »"]] },
    ],
    retenir: ["Les fruits : ", { t: "la banane, la mangue, l'ananas, l'orange, le citron, la pomme", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les fruits :"], items: [["la banane"], ["la tomate"], ["la mangue"], ["le chou"], ["l'orange"], ["le crayon"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le fruit long et jaune : la ....... (banane)"], ["2) Le fruit aux piquants : l'....... (ananas)"], ["3) Le fruit rond et orange : l'....... (orange)"], ["4) Le fruit jaune et sucré : la ....... (mangue)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Dessine ton fruit préféré et dis son nom (4 élèves) :"], items: [["1) Fruit n°1 : ....... (réponse libre)"], ["2) Fruit n°2 : ....... (réponse libre)"], ["3) Fruit n°3 : ....... (réponse libre)"], ["4) Fruit n°4 : ....... (réponse libre)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Fruits entourés : ", { t: "la banane, la mangue, l'orange", r: true }, " (2 pts chacun) — la tomate et le chou (légumes), le crayon (école) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "banane", r: true }, " — 2) ", { t: "ananas", r: true }, " — 3) ", { t: "orange", r: true }, " — 4) ", { t: "mangue", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Dessins + noms corrects : ", { t: "présentations réussies", r: true }, " (1,5 pt par élève)."]] },
   ],
  },
  {
   n: 67,
   titre: "Le vocabulaire des légumes",
   titreFiche: "Les légumes du marché",
   sd: "Expression Orale",
   objectif: "Nommer les légumes du marché : la tomate, l'oignon, la carotte, le chou, la pomme de terre, le brède.",
   supportFiche: "Image « le marché », légumes réels ou dessins, tableau noir.",
   revision: {
    ens: ["Nomme 3 fruits (chaîne parlée)."],
    app: ["R.A. : ", { t: "banane, mangue, ananas, orange, citron, pomme", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Que met-on dans le riz ? Qui mange des brèdes ce soir ? »"],
    app: ["Proposent : la tomate, l'oignon, les brèdes..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots des légumes : la tomate, l'oignon, la carotte, le chou, la pomme de terre, le brède."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez l'étal de légumes : » je montre chaque légume, les élèves le nomment."],
    app: ["Observent et nomment : la tomate, l'oignon, la carotte, le chou, la pomme de terre, le brède."],
    technique: ["Observation guidée"],
    support: "Image « le marché », légumes réels",
   },
   analyse: {
    ens: { paras: [["1) Quel légume est rouge et rond ?"], ["2) Quel légume fait pleurer quand on le coupe ?"], ["3) Quel légume pousse sous la terre ?"], ["4) Quels légumes mange-t-on avec le riz ?"]] },
    app: { paras: [["R.A. : La ", { t: "tomate", r: true }, "."], ["R.A. : L'", { t: "oignon", r: true }, "."], ["R.A. : La ", { t: "carotte", r: true }, ", la ", { t: "pomme de terre", r: true }, "."], ["R.A. : Les ", { t: "brèdes, le chou, la tomate", r: true }, "..."]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : les légumes — la tomate, l'oignon, la carotte, le chou, la pomme de terre, le brède."],
    app: ["Répètent les 6 mots en chœur ; fruits = sucrés, légumes = pour le repas."],
    technique: ["Répétition collective"],
    support: "Image « le marché »",
   },
   application: {
    ens: ["Le jeu du marché : un élève est le marchand, il montre un légume, vous nommez."],
    app: ["Nomment à tour de rôle : la carotte ! le chou ! l'oignon !"],
    technique: ["Jeu de rôle"],
    support: "Légumes réels ou dessins",
   },
   evaluation: {
    ens: ["3 élèves : nomme 3 légumes."],
    app: ["R.A. : ", { t: "tomate, oignon, carotte, chou, pomme de terre, brède", r: true }, " (3 mots corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "67. LE VOCABULAIRE DES LÉGUMES",
    subs: [
     { t: "A. Les légumes", paras: [[{ t: "la tomate", k: true }, " — ", { t: "l'oignon", k: true }, " — ", { t: "la carotte", k: true }, " — ", { t: "le chou", k: true }, " — ", { t: "la pomme de terre", k: true }, " — ", { t: "le brède", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "Maman achète des tomates et des brèdes.", k: true }, " »"]] },
    ],
    retenir: ["Les légumes : ", { t: "la tomate, l'oignon, la carotte, le chou, la pomme de terre, le brède", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les légumes :"], items: [["l'oignon"], ["la mangue"], ["le chou"], ["la banane"], ["la carotte"], ["l'ananas"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Le légume rouge et rond : la ....... (tomate)"], ["2) Le légume qui fait pleurer : l'....... (oignon)"], ["3) Le légume orange de la terre : la ....... (carotte)"], ["4) On mange les ....... avec le riz. (brèdes)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Fruits ou légumes ? Coche la bonne case (4 mots) :"], items: [["1) la tomate : fruit / légume"], ["2) la mangue : fruit / légume"], ["3) l'oignon : fruit / légume"], ["4) l'orange : fruit / légume"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Légumes entourés : ", { t: "l'oignon, le chou, la carotte", r: true }, " (2 pts chacun) — mangue, banane, ananas (fruits) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "tomate", r: true }, " — 2) ", { t: "oignon", r: true }, " — 3) ", { t: "carotte", r: true }, " — 4) ", { t: "brèdes", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "légume", r: true }, " — 2) ", { t: "fruit", r: true }, " — 3) ", { t: "légume", r: true }, " — 4) ", { t: "fruit", r: true }, " (1,5 pt par bonne case)."]] },
   ],
  },
  {
   n: 68,
   titre: "J'achète au marché",
   titreFiche: "Le verbe acheter",
   sd: "Expression Orale",
   objectif: "Dire ce qu'on achète : « J'achète du riz, des tomates, des bananes... »",
   supportFiche: "Image « le marché », panier, produits réels ou dessins.",
   revision: {
    ens: ["Fruit ou légume : je montre, tu réponds (rapide)."],
    app: ["Répondent : la tomate (légume), la banane (fruit)..."],
    technique: ["Jeu rapide"],
   },
   miseEnSituation: {
    ens: ["« Qui accompagne maman au marché ? Que porte-t-elle ? Qu'achète-t-elle ? »"],
    app: ["Proposent : le panier ; elle achète du riz, des légumes..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous disons ce qu'on achète : « J'achète... ». Acheter, c'est prendre contre de l'argent."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez et observez : » maman achète du riz, des tomates, des bananes, de l'huile."],
    app: ["Observent et répètent : elle achète du riz, des tomates, des bananes, de l'huile."],
    technique: ["Observation guidée"],
    support: "Image « le marché »",
   },
   analyse: {
    ens: { paras: [["1) Qu'est-ce que maman achète au marché ?"], ["2) Et toi, qu'est-ce que tu achètes à la récréation ?"], ["3) Où achète-t-on le riz ?"], ["4) Papa achète des mangues : répite la phrase."]] },
    app: { paras: [["R.A. : Elle achète ", { t: "du riz, des tomates, des bananes", r: true }, "."], ["R.A. : J'achète ", { t: "des bonbons, un cahier...", r: true }, " (réponse personnelle)."], ["R.A. : Au ", { t: "marché", r: true }, "."], ["R.A. : « ", { t: "Papa achète des mangues.", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : « J'achète du... / de la... / des... » — du riz, de l'huile, des tomates, des bananes."],
    app: ["Répètent les modèles en chœur, puis chacun donne sa phrase."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le panier de la maison : chacun ajoute un mot — « J'achète... et... »"],
    app: ["Enchaînent : j'achète du riz et des tomates ; ...et des bananes..."],
    technique: ["Jeu de mémoire enchaîné"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : dis ta phrase « J'achète... » avec 3 mots."],
    app: ["R.A. : « ", { t: "J'achète du riz, des tomates et des bananes.", r: true }, " » (phrase complète)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "68. J'ACHÈTE AU MARCHÉ",
    subs: [
     { t: "A. Le verbe", paras: [["Acheter : ", { t: "j'achète", k: true }, " — maman ", { t: "achète", k: true }, " — nous ", { t: "achetons", k: true }]] },
     { t: "B. Mes phrases", paras: [["« ", { t: "J'achète du riz.", k: true }, " » — « ", { t: "J'achète de l'huile.", k: true }, " » — « ", { t: "J'achète des tomates.", k: true }, " »"]] },
    ],
    retenir: ["« ", { t: "J'achète du... / de la... / des...", k: true }, " » — du riz, de la viande, des légumes."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure ce qu'on achète au marché :"], items: [["du riz"], ["un cahier"], ["des tomates"], ["une gomme"], ["des bananes"], ["de l'huile"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète avec du, de la ou des :"], items: [["1) J'achète ....... riz."], ["2) J'achète ....... viande."], ["3) J'achète ....___ bananes. (des)"], ["4) J'achète ....... huile."]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Complète ta liste de courses (4 mots) :"], items: [["1) J'achète du ....... (réponse libre)"], ["2) J'achète de la ....... (réponse libre)"], ["3) J'achète des ....... (réponse libre)"], ["4) J'achète et je dis merci à la ....... (marchande)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entourés : ", { t: "du riz, des tomates, des bananes, de l'huile", r: true }, " (2 pts chacun) — cahier et gomme (école) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "du", r: true }, " — 2) ", { t: "de la", r: true }, " — 3) ", { t: "des", r: true }, " — 4) ", { t: "de l'", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Listes personnelles correctes : ", { t: "du/de la/des bien employés", r: true }, " (1,5 pt par mot juste)."]] },
   ],
  },
  {
   n: 69,
   titre: "Au marché",
   titreFiche: "Les mots du marché",
   sd: "Expression Orale",
   objectif: "Nommer les mots du marché : le marché, l'étal, la marchande, la cliente, le panier, l'argent.",
   supportFiche: "Image « le marché », panier réel, tableau noir.",
   revision: {
    ens: ["Dis ta phrase « J'achète... » (chaîne parlée)."],
    app: ["R.A. : « J'achète du riz, des tomates... »"],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Décrivez le marché de notre village : qu'est-ce qu'on y voit ? »"],
    app: ["Proposent : des étals, des gens, des paniers, de l'argent..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons les mots du marché : l'étal, la marchande, la cliente, le panier, l'argent."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez la grande image du marché : » je montre l'étal, la marchande, la cliente, le panier, l'argent."],
    app: ["Observent et nomment chaque mot en montrant l'image."],
    technique: ["Observation guidée"],
    support: "Image « le marché »",
   },
   analyse: {
    ens: { paras: [["1) Qui vend les fruits ?"], ["2) Qui achète les légumes ?"], ["3) Où pose-t-on les tomates et les brèdes ?"], ["4) Avec quoi paie-t-on ?"]] },
    app: { paras: [["R.A. : La ", { t: "marchande", r: true }, "."], ["R.A. : La ", { t: "cliente", r: true }, "."], ["R.A. : Sur l'", { t: "étal", r: true }, "."], ["R.A. : Avec de l'", { t: "argent", r: true }, " (les ariary)."]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : le marché, l'étal, la marchande, la cliente, le panier, l'argent."],
    app: ["Répètent les 6 mots en chœur en les montrant sur l'image."],
    technique: ["Répétition collective"],
    support: "Image « le marché »",
   },
   application: {
    ens: ["La balance vrai/faux : je dis une phrase, vous répondez vrai ou faux."],
    app: ["Répondent : la marchande vend (vrai) ; le panier vend (faux)..."],
    technique: ["Jeu vrai/faux"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : montre et nomme 3 mots du marché sur l'image."],
    app: ["R.A. : ", { t: "l'étal, la marchande, la cliente, le panier, l'argent", r: true }, " (3 mots corrects)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "69. LES MOTS DU MARCHÉ",
    subs: [
     { t: "A. Les mots", paras: [[{ t: "le marché", k: true }, " — ", { t: "l'étal", k: true }, " — ", { t: "la marchande", k: true }, " — ", { t: "la cliente", k: true }, " — ", { t: "le panier", k: true }, " — ", { t: "l'argent", k: true }]] },
     { t: "B. Ma phrase", paras: [["« ", { t: "À l'étal de la marchande, il y a des fruits et des légumes.", k: true }, " »"]] },
    ],
    retenir: ["Au marché : ", { t: "l'étal, la marchande, la cliente, le panier, l'argent", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Relie chaque mot à sa place :"], items: [["1) La marchande vend : les fruits / l'école"], ["2) La cliente met ses courses : dans le panier / dans le ciel"], ["3) On paie avec : l'argent / la craie"], ["4) Les tomates sont posées : sur l'étal / sous le lit"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) La ....... vend les légumes. (marchande)"], ["2) Le client met le riz dans son ....... (panier)"], ["3) On paie en ....... (argent / ariary)"], ["4) Le marché du village a dix ....... (étals)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Décris l'image du marché avec 3 mots (4 élèves) :"], items: [["1) Je vois ....... (réponse libre)"], ["2) Je vois ....... (réponse libre)"], ["3) Je vois ....... (réponse libre)"], ["4) J'entends ....... (réponse libre : le bruit, les prix...)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["1) ", { t: "les fruits", r: true }, " — 2) ", { t: "dans le panier", r: true }, " — 3) ", { t: "l'argent", r: true }, " — 4) ", { t: "sur l'étal", r: true }, " (2 pts chacun)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "marchande", r: true }, " — 2) ", { t: "panier", r: true }, " — 3) ", { t: "argent", r: true }, " — 4) ", { t: "étals", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Descriptions avec mots du thème : ", { t: "mots du marché corrects", r: true }, " (1,5 pt par mot)."]] },
   ],
  },
  {
   n: 70,
   titre: "Le dialogue du marché",
   titreFiche: "Bonjour, Madame !",
   sd: "Expression Orale",
   objectif: "Jouer le dialogue de l'achat : « Bonjour, Madame. — Qu'est-ce que tu veux ? — Je voudrais des bananes, s'il vous plaît. »",
   supportFiche: "Image « le marché », panier et fruits réels, tableau noir.",
   revision: {
    ens: ["Montre et nomme : étal, panier, argent (3 élèves)."],
    app: ["R.A. : ", { t: "l'étal, le panier, l'argent", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Quand tu arrives au marché, que dis-tu à la marchande ? Et elle, que répond-elle ? »"],
    app: ["Proposent : bonjour ! ..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous jouons le dialogue du marché : le bonjour, la demande, le merci."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez le dialogue : » — Bonjour, Madame ! — Bonjour, Rova ! Qu'est-ce que tu veux ? — Je voudrais des bananes, s'il vous plaît. — Voilà. — Merci, au revoir !"],
    app: ["Écoutent, puis répètent chaque réplique."],
    technique: ["Modèle oral"],
    support: "Image « le marché »",
   },
   analyse: {
    ens: { paras: [["1) Que dit Rova en arrivant ?"], ["2) Que demande-t-il ?"], ["3) Quel mot poli accompagne la demande ?"], ["4) Que dit la cliente à la fin ?"]] },
    app: { paras: [["R.A. : « ", { t: "Bonjour, Madame !", r: true }, " »"], ["R.A. : « ", { t: "Je voudrais des bananes.", r: true }, " »"], ["R.A. : « ", { t: "S'il vous plaît", r: true }, ". »"], ["R.A. : « ", { t: "Merci, au revoir !", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : bonjour — qu'est-ce que tu veux ? — je voudrais..., s'il vous plaît — voilà — merci, au revoir !"],
    app: ["Répètent le dialogue complet en chœur, puis par deux."],
    technique: ["Répétition par deux"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le jeu du marché : deux élèves jouent la scène avec de vrais fruits."],
    app: ["Jouent : bonjour, je voudrais des mangues, s'il vous plaît ; voilà, merci !"],
    technique: ["Jeu de rôle"],
    support: "Fruits réels, panier",
   },
   evaluation: {
    ens: ["3 paires : joue la scène complète."],
    app: ["R.A. : ", { t: "bonjour — je voudrais..., s'il vous plaît — merci, au revoir", r: true }, " (dialogue complet)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "70. LE DIALOGUE DU MARCHÉ",
    subs: [
     { t: "A. Le dialogue", paras: [["« — ", { t: "Bonjour, Madame !", k: true }, " — ", { t: "Bonjour ! Qu'est-ce que tu veux ?", k: true }, " »"], ["« — ", { t: "Je voudrais des bananes, s'il vous plaît.", k: true }, " — ", { t: "Voilà. — Merci, au revoir !", k: true }, " »"]] },
    ],
    retenir: ["Au marché je dis : ", { t: "bonjour, je voudrais..., s'il vous plaît, merci, au revoir", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets le dialogue en ordre (numérote 1, 2, 3, 4) :"], items: [["Voilà. (3)"], ["Bonjour, Madame ! (1)"], ["Merci, au revoir ! (4)"], ["Je voudrais des bananes, s'il vous plaît. (2)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète le dialogue :"], items: [["1) ......., Madame ! (Bonjour)"], ["2) Je ....... des tomates, s'il vous plaît. (voudrais)"], ["3) S'il vous ....... (plaît)"], ["4) ......., au revoir ! (Merci)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène avec un camarade (4 répliques chacun) :"], items: [["1) La cliente dit bonjour : ......."], ["2) La marchande répond : ......."], ["3) La cliente demande : ......."], ["4) La marchande donne et dit : ......."]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "Bonjour, Madame ! → Je voudrais des bananes, s'il vous plaît. → Voilà. → Merci, au revoir !", r: true }, " (2 pts par numéro juste)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "Bonjour", r: true }, " — 2) ", { t: "voudrais", r: true }, " — 3) ", { t: "plaît", r: true }, " — 4) ", { t: "Merci", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Scènes jouées : ", { t: "répliques polies et complètes", r: true }, " (1,5 pt par réplique)."]] },
   ],
  },
  {
   n: 71,
   titre: "Combien ça coûte ?",
   titreFiche: "Les prix au marché",
   sd: "Expression Orale",
   objectif: "Demander et dire un prix : « Combien coûte le kilo de tomates ? — Cinq cents ariary. »",
   supportFiche: "Image « le marché », étiquettes de prix dessinées, tableau noir.",
   revision: {
    ens: ["Joue le dialogue du marché avec ton voisin (30 secondes)."],
    app: ["R.A. : « Bonjour ! — Je voudrais..., s'il vous plaît. — Voilà. — Merci ! »"],
    technique: ["Jeu de rôle express"],
   },
   miseEnSituation: {
    ens: ["« Quand maman achète des tomates, que demande-t-elle avant de payer ? »"],
    app: ["Proposent : le prix, combien ça coûte..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous demandons les prix : « Combien coûte... ? » et nous répondons en ariary."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez : » — Combien coûte le kilo de tomates ? — Cinq cents ariary. — Voilà cinq cents ariary. — Merci !"],
    app: ["Écoutent, puis répètent chaque réplique."],
    technique: ["Modèle oral"],
    support: "Image « le marché »",
   },
   analyse: {
    ens: { paras: [["1) Que demande la cliente ?"], ["2) Combien coûte le kilo de tomates ?"], ["3) Avec quelle monnaie paie-t-on à Madagascar ?"], ["4) Demande-moi le prix du riz !"]] },
    app: { paras: [["R.A. : « ", { t: "Combien coûte le kilo de tomates ?", r: true }, " »"], ["R.A. : ", { t: "Cinq cents ariary", r: true }, "."], ["R.A. : L'", { t: "ariary", r: true }, "."], ["R.A. : « ", { t: "Combien coûte le kilo de riz ?", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : « Combien coûte... ? — ... ariary. » — je demande poliment, je remercie."],
    app: ["Répètent le dialogue du prix en chœur, puis par deux."],
    technique: ["Répétition par deux"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le jeu des prix : la marchande affiche un prix, la cliente demande et paie."],
    app: ["Jouent : combien coûte la mangue ? — Trois cents ariary !"],
    technique: ["Jeu de rôle"],
    support: "Étiquettes de prix dessinées",
   },
   evaluation: {
    ens: ["3 paires : demande et donne un prix."],
    app: ["R.A. : « ", { t: "Combien coûte... ? — ... ariary.", r: true }, " » (échange complet)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "71. COMBIEN ÇA COÛTE ?",
    subs: [
     { t: "A. La question du prix", paras: [["« — ", { t: "Combien coûte le kilo de tomates ?", k: true }, " — ", { t: "Cinq cents ariary.", k: true }, " »"]] },
     { t: "B. Je paie", paras: [["« — ", { t: "Voilà l'argent. — Merci ! — Au revoir !", k: true }, " »"]] },
    ],
    retenir: ["« ", { t: "Combien coûte... ?", k: true }, " » — « ", { t: "Ça coûte... ariary.", k: true }, " »"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots pour demander un prix :"], items: [["Combien"], ["Bonjour"], ["coûte"], ["panier"], ["ariary"], ["étal"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) ....... coûte le kilo de riz ? (Combien)"], ["2) Ça ....... cinq cents ariary. (coûte)"], ["3) Voilà l'....... (argent)"], ["4) Merci, au ....... ! (revoir)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Jeu du marchand : lis le prix et dis la phrase (4 tours) :"], items: [["1) 200 ariary — la banane : ......."], ["2) 500 ariary — le kilo de riz : ......."], ["3) 300 ariary — les tomates : ......."], ["4) 1000 ariary — l'huile : ......."]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entourés : ", { t: "Combien, coûte, ariary", r: true }, " (2 pts chacun) — bonjour (politesse), panier et étal (mots du lieu) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "Combien", r: true }, " — 2) ", { t: "coûte", r: true }, " — 3) ", { t: "argent", r: true }, " — 4) ", { t: "revoir", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["« Ça coûte ... ariary » correct : ", { t: "4 phrases complètes", r: true }, " (1,5 pt par tour)."]] },
   ],
  },
  {
   n: 72,
   titre: "Je pèse au marché",
   titreFiche: "Lourd ou léger",
   sd: "Expression Orale",
   objectif: "Utiliser les mots de la pesée : le kilo, la balance, lourd, léger.",
   supportFiche: "Balance réelle ou image, fruits réels, tableau noir.",
   revision: {
    ens: ["Demande-moi le prix des bananes (2 élèves)."],
    app: ["R.A. : « Combien coûte le kilo de bananes ? »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Qui a déjà porté le panier de maman ? Le riz est-il lourd ou léger ? »"],
    app: ["Proposent : lourd ! léger ! selon le panier..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous pesons au marché : le kilo, la balance, lourd, léger."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez et touchez : » je pèse un kilo de riz sur la balance ; je fais comparer une plume et une pierre."],
    app: ["Observent, portent, disent : lourd ! léger ! un kilo !"],
    technique: ["Observation guidée"],
    support: "Balance, fruits réels",
   },
   analyse: {
    ens: { paras: [["1) Avec quoi pèse-t-on au marché ?"], ["2) Que pèse-t-on avec le kilo ?"], ["3) Le riz est-il lourd ou léger ?"], ["4) La banane est-elle lourde ou légère ?"]] },
    app: { paras: [["R.A. : Avec la ", { t: "balance", r: true }, "."], ["R.A. : Le ", { t: "riz, les tomates, l'huile", r: true }, "..."], ["R.A. : ", { t: "Lourd", r: true }, "."], ["R.A. : ", { t: "Légère", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Balance, fruits réels",
   },
   synthese: {
    ens: ["Donc : la balance pèse en kilos ; le riz est lourd, la banane est légère."],
    app: ["Répètent les 4 mots en chœur en mimant le geste de peser."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le jeu des bras : je nomme un objet, vous montrez s'il est lourd (bras pliés) ou léger (paumes hautes)."],
    app: ["Miment : le sac de riz (lourd), la plume (léger), le panier de mangues (lourd)..."],
    technique: ["Jeu de mimes"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : pèse et dis : « Le kilo de... est lourd/léger. »"],
    app: ["R.A. : « ", { t: "Le kilo de riz est lourd.", r: true }, " » (phrase complète)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "72. JE PÈSE AU MARCHÉ",
    subs: [
     { t: "A. Les mots", paras: [[{ t: "le kilo", k: true }, " — ", { t: "la balance", k: true }, " — ", { t: "lourd", k: true }, " — ", { t: "léger", k: true }]] },
     { t: "B. Mes phrases", paras: [["« ", { t: "Un kilo de tomates, s'il vous plaît.", k: true }, " » — « ", { t: "Le riz est lourd, la banane est légère.", k: true }, " »"]] },
    ],
    retenir: ["Au marché on pèse avec ", { t: "la balance", k: true }, " : ", { t: "un kilo", k: true }, " de riz, de tomates — ", { t: "lourd", k: true }, " ou ", { t: "léger", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure ce qui sert à peser :"], items: [["la balance"], ["le panier"], ["le kilo"], ["l'étal"], ["l'argent"], ["la marchande"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète avec lourd ou léger :"], items: [["1) Le sac de riz est ....... (lourd)"], ["2) La plume est ....... (légère)"], ["3) Un ....... de tomates, s'il vous plaît. (kilo)"], ["4) La ....... dit : un kilo juste ! (balance)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lourd ou léger ? Montre et dis (4 objets) :"], items: [["1) Le cartable plein : ....... (lourd)"], ["2) La craie : ....... (légère)"], ["3) Le kilo de riz : ....... (lourd)"], ["4) La banane : ....... (légère)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entouré : ", { t: "la balance", r: true }, " (et ", { t: "le kilo", r: true }, " unité de pesée) — panier, étal, argent, marchande : mots du lieu, non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "lourd", r: true }, " — 2) ", { t: "légère", r: true }, " — 3) ", { t: "kilo", r: true }, " — 4) ", { t: "balance", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Gestes + mots justes : ", { t: "4 réponses correctes", r: true }, " (1,5 pt par objet)."]] },
   ],
  },
  {
   n: 73,
   titre: "La comptine du marché",
   titreFiche: "Mon panier est plein",
   sd: "Expression Orale",
   objectif: "Réciter la comptine du marché en rythme.",
   supportFiche: "Comptine au tableau, image « le marché ».",
   revision: {
    ens: ["Dis les mots du marché : étal, balance, kilo (chaîne parlée)."],
    app: ["R.A. : ", { t: "l'étal, la balance, le kilo", r: true }, "."],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Qui connaît une chanson du marché ? Nous allons apprendre la comptine de J-Learn ! »"],
    app: ["Écoutent, proposent des rythmes en tapant des mains."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous apprenons la comptine du marché : écoutez d'abord, puis répétez."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez la comptine : » Au marché de mon village, / j'achète riz et tomates ; / bananes, mangues et oranges, / mon panier est plein, quel matin !"],
    app: ["Écoutent en suivant sur le tableau."],
    technique: ["Modèle oral"],
    support: "Comptine au tableau",
   },
   analyse: {
    ens: { paras: [["1) Où est le marché de la comptine ?"], ["2) Qu'achète-t-on d'abord ?"], ["3) Quels fruits sont dans le panier ?"], ["4) Comment finit la comptine ?"]] },
    app: { paras: [["R.A. : Dans ", { t: "mon village", r: true }, "."], ["R.A. : ", { t: "Du riz et des tomates", r: true }, "."], ["R.A. : ", { t: "Des bananes, des mangues et des oranges", r: true }, "."], ["R.A. : « ", { t: "Mon panier est plein, quel matin !", r: true }, " »"]] },
    technique: ["Question / réponse"],
    support: "Comptine au tableau",
   },
   synthese: {
    ens: ["Donc : la comptine du marché, avec les fruits et le panier plein."],
    app: ["Répètent la comptine en chœur, deux fois, en tapant le rythme."],
    technique: ["Répétition collective"],
    support: "Comptine au tableau",
   },
   application: {
    ens: ["La comptine par groupe : chaque groupe récite une ligne, tous ensemble pour la fin."],
    app: ["Récitent en groupes puis en chœur."],
    technique: ["Récitation par groupes"],
    support: "Comptine au tableau",
   },
   evaluation: {
    ens: ["3 élèves : récite la comptine complète."],
    app: ["R.A. : comptine ", { t: "récitée sans oubli", r: true }, " (rythme régulier)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "73. LA COMPTINE DU MARCHÉ",
    subs: [
     { t: "A. La comptine", paras: [["« ", { t: "Au marché de mon village,", k: true }, " / ", { t: "j'achète riz et tomates ;", k: true }, " »"], ["« ", { t: "bananes, mangues et oranges,", k: true }, " / ", { t: "mon panier est plein, quel matin !", k: true }, " »"]] },
    ],
    retenir: ["Ma comptine : « ", { t: "Mon panier est plein, quel matin !", k: true }, " » — et mes achats : ", { t: "riz, tomates, fruits", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Remets les lignes de la comptine en ordre (1, 2, 3, 4) :"], items: [["mon panier est plein, quel matin ! (4)"], ["Au marché de mon village, (1)"], ["bananes, mangues et oranges, (3)"], ["j'achète riz et tomates ; (2)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la comptine :"], items: [["1) Au ....... de mon village (marché)"], ["2) j'achète ....... et tomates (riz)"], ["3) ......., mangues et oranges (bananes)"], ["4) mon ....... est plein (panier)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Ajoute un vers : « j'achète... » avec un mot du thème (4 élèves) :"], items: [["1) j'achète ....... (réponse libre)"], ["2) j'achète ....... (réponse libre)"], ["3) j'achète ....... (réponse libre)"], ["4) j'achète ....... (réponse libre)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Ordre : ", { t: "Au marché... → j'achète riz et tomates ; → bananes, mangues et oranges, → mon panier est plein !", r: true }, " (2 pts par numéro)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "marché", r: true }, " — 2) ", { t: "riz", r: true }, " — 3) ", { t: "bananes", r: true }, " — 4) ", { t: "panier", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Vers corrects (mots du marché, rythme tenu) : ", { t: "1,5 pt par vers", r: true }, "."]] },
   ],
  },
  {
   n: 74,
   titre: "J'énumère mes achats",
   titreFiche: "Ma liste de courses",
   sd: "Expression Orale",
   objectif: "Énumérer : « J'achète..., ..., et... » (une liste de 4 produits).",
   supportFiche: "Image « le marché », liste de courses dessinée, tableau noir.",
   revision: {
    ens: ["Récite la comptine du marché avec ton voisin."],
    app: ["R.A. : « Au marché de mon village... »"],
    technique: ["Répétition par deux"],
   },
   miseEnSituation: {
    ens: ["« Maman oublie toujours quelque chose ! Comment faire une liste pour se souvenir ? »"],
    app: ["Proposent : on écrit, on dit tout ce qu'il faut acheter..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous énumérons nos achats : « J'achète..., ..., et... »"],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Écoutez ma liste : » j'achète du riz, de l'huile, des tomates et des bananes — j'énumère avec ma voix qui continue."],
    app: ["Écoutent, répètent la liste complète."],
    technique: ["Modèle oral"],
    support: "Liste de courses dessinée",
   },
   analyse: {
    ens: { paras: [["1) Quel est le premier mot de la liste ?"], ["2) Combien de produits dans ma liste ?"], ["3) Quel petit mot avant le dernier produit ?"], ["4) Refais ma liste dans l'ordre !"]] },
    app: { paras: [["R.A. : « ", { t: "J'achète", r: true }, " »"], ["R.A. : ", { t: "Quatre", r: true }, "."], ["R.A. : ", { t: "Et", r: true }, "."], ["R.A. : ", { t: "du riz, de l'huile, des tomates et des bananes", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Liste de courses dessinée",
   },
   synthese: {
    ens: ["Donc : pour énumérer, je dis « J'achète » puis chaque produit, et « et » avant le dernier."],
    app: ["Répètent le modèle en chœur : j'achète..., ..., et..."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Le jeu de la liste qui grandit : chacun ajoute un produit en répétant la liste de son camarade."],
    app: ["Enchaînent : j'achète du riz et du sel ; j'achète du riz, du sel et des oignons..."],
    technique: ["Jeu de mémoire enchaîné"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["3 élèves : énumère 4 achats."],
    app: ["R.A. : « ", { t: "J'achète..., ..., et...", r: true }, " » (4 produits, ordre tenu)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "74. J'ÉNUMÈRE MES ACHATS",
    subs: [
     { t: "A. Ma liste", paras: [["« ", { t: "J'achète du riz, de l'huile, des tomates et des bananes.", k: true }, " »"]] },
     { t: "B. Le modèle", paras: [["« ", { t: "J'achète..., ..., et...", k: true }, " » — le mot ", { t: "et", k: true }, " avant le dernier !"]] },
    ],
    retenir: ["Pour énumérer : ", { t: "« J'achète..., ..., et... »", k: true }, " — et ma voix continue jusqu'au dernier produit."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les produits qu'on peut mettre dans une liste de courses :"], items: [["du riz"], ["des tomates"], ["un banc"], ["de l'huile"], ["des mangues"], ["un nuage"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète la liste avec et :"], items: [["1) J'achète du riz, du sel ....... des oignons."], ["2) J'achète des bananes, des mangues ....... des oranges."], ["3) J'achète de l'huile ....... du savon."], ["4) J'achète des tomates, des brèdes ....... du chou."]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Fais ta liste de 4 produits (4 élèves) :"], items: [["1) Liste n°1 : ....... (réponse libre)"], ["2) Liste n°2 : ....... (réponse libre)"], ["3) Liste n°3 : ....... (réponse libre)"], ["4) Liste n°4 : ....... (réponse libre)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entourés : ", { t: "du riz, des tomates, de l'huile, des mangues", r: true }, " (2 pts chacun) — banc et nuage non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "et", r: true }, " — 2) ", { t: "et", r: true }, " — 3) ", { t: "et", r: true }, " — 4) ", { t: "et", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Listes personnelles de 4 produits : ", { t: "énumération complète", r: true }, " (1,5 pt par liste)."]] },
   ],
  },
  {
   n: 75,
   titre: "Je décris les fruits",
   titreFiche: "Il est jaune, elle est sucrée",
   sd: "Expression Orale",
   objectif: "Décrire un fruit : « La mangue est jaune. Elle est sucrée. Je l'aime bien. »",
   supportFiche: "Fruits réels ou image « le marché », tableau noir.",
   revision: {
    ens: ["Énumère 4 achats (chaîne parlée)."],
    app: ["R.A. : « J'achète du riz, de l'huile, des tomates et des bananes. »"],
    technique: ["Chaîne parlée"],
   },
   miseEnSituation: {
    ens: ["« Décrivez la banane : sa couleur, son goût, sa forme. »"],
    app: ["Proposent : jaune, sucrée, longue..."],
    technique: ["Question ouverte"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous décrivons les fruits : la couleur, le goût, et si on l'aime."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez et goûtez : » la mangue est jaune, elle est sucrée ; le citron est jaune, il est acide ; la banane est longue, elle est sucrée."],
    app: ["Observent, goûtent, répètent les phrases de description."],
    technique: ["Observation guidée"],
    support: "Fruits réels",
   },
   analyse: {
    ens: { paras: [["1) De quelle couleur est la mangue ?"], ["2) Quel goût a le citron ?"], ["3) Comment est la banane ?"], ["4) Décris l'orange !"]] },
    app: { paras: [["R.A. : Elle est ", { t: "jaune", r: true }, "."], ["R.A. : Il est ", { t: "acide", r: true }, "."], ["R.A. : Elle est ", { t: "longue et sucrée", r: true }, "."], ["R.A. : ", { t: "L'orange est orange, elle est sucrée et juteuse.", r: true }, ""]] },
    technique: ["Question / réponse"],
    support: "Fruits réels ou image",
   },
   synthese: {
    ens: ["Donc : pour décrire, je dis la couleur et le goût : « Il/Elle est..., je l'aime bien. »"],
    app: ["Répètent le modèle en chœur avec 3 fruits."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["La devinette décrite : je décris un fruit sans le nommer, vous devinez."],
    app: ["Devine : c'est long, c'est jaune, c'est sucré — la banane !"],
    technique: ["Jeu de devinette"],
    support: "Fruits réels",
   },
   evaluation: {
    ens: ["3 élèves : décris un fruit (couleur + goût + avis)."],
    app: ["R.A. : « ", { t: "La mangue est jaune. Elle est sucrée. Je l'aime bien.", r: true }, " » (3 éléments)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "75. JE DÉCRIS LES FRUITS",
    subs: [
     { t: "A. Les couleurs et les goûts", paras: [[{ t: "jaune", k: true }, " — ", { t: "orange", k: true }, " — ", { t: "vert", k: true }, " — ", { t: "sucré", k: true }, " — ", { t: "acide", k: true }]] },
     { t: "B. Mes phrases", paras: [["« ", { t: "La mangue est jaune. Elle est sucrée. Je l'aime bien.", k: true }, " » — « ", { t: "Le citron est acide.", k: true }, " »"]] },
    ],
    retenir: ["Pour décrire : ", { t: "« Il est / Elle est... (couleur, goût). Je l'aime bien. »", k: true }],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui décrivent le goût ou la couleur :"], items: [["sucré"], ["panier"], ["acide"], ["jaune"], ["kilo"], ["juteux"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) La mangue est ....... (jaune)."], ["2) Le citron est ....... (acide)."], ["3) La banane est longue et ....... (sucrée)."], ["4) L'orange est ....... (orange / juteuse)."]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Décris ton fruit préféré en 3 phrases (4 élèves) :"], items: [["1) Fruit n°1 : ....... (réponse libre)"], ["2) Fruit n°2 : ....... (réponse libre)"], ["3) Fruit n°3 : ....... (réponse libre)"], ["4) Fruit n°4 : ....... (réponse libre)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Entourés : ", { t: "sucré, acide, jaune, juteux", r: true }, " (2 pts chacun) — panier et kilo (mots du lieu) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "jaune", r: true }, " — 2) ", { t: "acide", r: true }, " — 3) ", { t: "sucrée", r: true }, " — 4) ", { t: "orange", r: true }, " / ", { t: "juteuse", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Descriptions complètes (couleur + goût + avis) : ", { t: "1,5 pt par description", r: true }, "."]] },
   ],
  },
  {
   n: 76,
   titre: "Le son oi",
   titreFiche: "J'entends oi",
   sd: "Lecture",
   objectif: "Reconnaître et lire le son oi : l'oie, la voiture, le toit, la poire.",
   supportFiche: "Image « le son oi », syllabes au tableau, ardoises.",
   revision: {
    ens: ["Décris un fruit en 3 phrases (2 élèves)."],
    app: ["R.A. : « La mangue est jaune. Elle est sucrée. Je l'aime bien. »"],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Écoutez : o-i, oi ! Une oie ! Une voiture ! Répétez ! »"],
    app: ["Répètent : oi, oi — une oie, une voiture !"],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son oi : o-i font « oi », comme dans l'oie et le toit."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez l'image et écoutez : » l'OIE, la VOITURE, le TOIT, la POIRE. Entendez-vous oi ?"],
    app: ["Observent, écoutent, répondent : oui, on entend oi !"],
    technique: ["Observation guidée"],
    support: "Image « le son oi »",
   },
   analyse: {
    ens: { paras: [["1) Avec quelles lettres écrit-on le son oi ?"], ["2) Que dit o-i ensemble ?"], ["3) Cite un mot avec oi."], ["4) Le mot « trois » : où est oi ?"]] },
    app: { paras: [["R.A. : Avec ", { t: "o et i", r: true }, "."], ["R.A. : ", { t: "oi", r: true }, " !"], ["R.A. : ", { t: "l'oie, le toit, la poire, la voiture", r: true }, " (réponse libre)."], ["R.A. : Au milieu : ", { t: "tr-oi-s", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Image « le son oi », syllabes au tableau",
   },
   synthese: {
    ens: ["Donc : le son oi s'écrit o-i — l'oie, la voiture, le toit, la poire, trois."],
    app: ["Lisent les 5 mots en chœur, puis individuellement."],
    technique: ["Lecture collective"],
    support: "Syllabes au tableau",
   },
   application: {
    ens: ["Lecture flash : je montre un mot, vous lisez vite (oie, toit, poire, trois, voiture)."],
    app: ["Lisent vite, en corps et individuellement."],
    technique: ["Lecture flash"],
    support: "Ardoises, mots au tableau",
   },
   evaluation: {
    ens: ["3 élèves : lis 3 mots avec oi."],
    app: ["R.A. : ", { t: "l'oie, le toit, la poire, la voiture, trois", r: true }, " (3 mots lus correctement)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "76. LE SON OI",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "oi", k: true }, " s'écrit avec ", { t: "deux lettres : o-i", k: true }, " — la bouche passe de o à i !"]] },
     { t: "B. Les mots", paras: [[{ t: "l'oie", k: true }, " — ", { t: "la voiture", k: true }, " — ", { t: "le toit", k: true }, " — ", { t: "la poire", k: true }, " — ", { t: "trois", k: true }]] },
    ],
    retenir: ["Le son ", { t: "oi", k: true }, " : ", { t: "l'oie, la voiture, le toit, la poire", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son oi :"], items: [["l'oie"], ["la robe"], ["le toit"], ["la poire"], ["le riz"], ["trois"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète avec oi :"], items: [["1) l'.... (oie)"], ["2) le t... (toi / toit)"], ["3) la p...re (poire)"], ["4) la voit...re (voiture)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis tes 4 mots avec oi à haute voix (4 élèves) :"], items: [["1) Mot n°1 : ....... (lecture)"], ["2) Mot n°2 : ....... (lecture)"], ["3) Mot n°3 : ....... (lecture)"], ["4) Mot n°4 : ....... (lecture)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "l'oie, le toit, la poire, trois", r: true }, " (2 pts chacun) — la robe et le riz : pas de oi."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oie", r: true }, " — 2) ", { t: "toit", r: true }, " — 3) ", { t: "poire", r: true }, " — 4) ", { t: "voiture", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Lectures correctes : ", { t: "1,5 pt par mot bien lu", r: true }, "."]] },
   ],
  },
  {
   n: 77,
   titre: "Le son ui",
   titreFiche: "J'entends ui",
   sd: "Lecture",
   objectif: "Reconnaître et lire le son ui : le fruit, la nuit, la pluie, cuit.",
   supportFiche: "Image « le marché », syllabes au tableau, ardoises.",
   revision: {
    ens: ["Lis : oie, toit, poire, trois (lecture flash)."],
    app: ["Lisent : oie, toit, poire, trois."],
    technique: ["Lecture flash"],
   },
   miseEnSituation: {
    ens: ["« Écoutez : u-i, ui ! Le fruit ! La nuit ! Répétez ! »"],
    app: ["Répètent : ui, ui — le fruit, la nuit !"],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son ui : u-i font « ui », comme dans le fruit et la pluie."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez et écoutez : » le FRUIT, la NUIT, la PLUIE, le RIZ CUIT. Entendez-vous ui ?"],
    app: ["Observent, écoutent, répondent : oui, on entend ui !"],
    technique: ["Observation guidée"],
    support: "Image « le marché », syllabes au tableau",
   },
   analyse: {
    ens: { paras: [["1) Avec quelles lettres écrit-on le son ui ?"], ["2) Que dit u-i ensemble ?"], ["3) Cite un mot avec ui."], ["4) Que devient le fruit quand il est mûr puis cuit ?"]] },
    app: { paras: [["R.A. : Avec ", { t: "u et i", r: true }, "."], ["R.A. : ", { t: "ui", r: true }, " !"], ["R.A. : ", { t: "le fruit, la nuit, la pluie, cuit", r: true }, " (réponse libre)."], ["R.A. : Il est ", { t: "cuit", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Syllabes au tableau",
   },
   synthese: {
    ens: ["Donc : le son ui s'écrit u-i — le fruit, la nuit, la pluie, cuit."],
    app: ["Lisent les 4 mots en chœur, puis la phrase : la nuit, la pluie arrose le fruit."],
    technique: ["Lecture collective"],
    support: "Syllabes au tableau",
   },
   application: {
    ens: ["Lecture en écho : je lis un mot, vous le relisez comme un écho (fruit, nuit, pluie, cuit, lui)."],
    app: ["Relisent en écho, puis individuellement."],
    technique: ["Lecture en écho"],
    support: "Ardoises, mots au tableau",
   },
   evaluation: {
    ens: ["3 élèves : lis 3 mots avec ui."],
    app: ["R.A. : ", { t: "le fruit, la nuit, la pluie, cuit", r: true }, " (3 mots lus correctement)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "77. LE SON UI",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "ui", k: true }, " s'écrit avec ", { t: "deux lettres : u-i", k: true }, " — les lèvres rondes puis souriantes !"]] },
     { t: "B. Les mots", paras: [[{ t: "le fruit", k: true }, " — ", { t: "la nuit", k: true }, " — ", { t: "la pluie", k: true }, " — ", { t: "cuit", k: true }]] },
    ],
    retenir: ["Le son ", { t: "ui", k: true }, " : ", { t: "le fruit, la nuit, la pluie, cuit", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son ui :"], items: [["le fruit"], ["le toit"], ["la pluie"], ["la nuit"], ["le riz"], ["cuit"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète avec ui :"], items: [["1) le fr...t (fruit)"], ["2) la n...t (nuit)"], ["3) la pl...e (pluie)"], ["4) le riz c...t (cuit)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis la phrase à haute voix (4 élèves) :"], items: [["1) La pluie tombe la nuit. (lecture)"], ["2) Le fruit est cuit. (lecture)"], ["3) La nuit, la pluie arrose le fruit. (lecture)"], ["4) J'aime le fruit et la pluie. (lecture)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le fruit, la pluie, la nuit, cuit", r: true }, " (2 pts chacun) — le toit (oi) et le riz non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "ui", r: true }, " — 2) ", { t: "ui", r: true }, " — 3) ", { t: "ui", r: true }, " — 4) ", { t: "ui", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Phrases lues sans hésitation : ", { t: "1,5 pt par phrase", r: true }, "."]] },
   ],
  },
  {
   n: 78,
   titre: "Le son ph",
   titreFiche: "Ph se prononce f",
   sd: "Lecture",
   objectif: "Reconnaître et lire le son ph : le phare, l'éléphant, le dauphin, la photo.",
   supportFiche: "Image « le son ph », syllabes au tableau, ardoises.",
   revision: {
    ens: ["Lis : fruit, nuit, pluie, cuit (lecture flash)."],
    app: ["Lisent : fruit, nuit, pluie, cuit."],
    technique: ["Lecture flash"],
   },
   miseEnSituation: {
    ens: ["« Écoutez : p-h, ph ! Ça se prononce f ! Le phare ! L'éléphant ! Répétez ! »"],
    app: ["Répètent : ph = f ! le phare, l'éléphant !"],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous lisons le son ph : p-h font le son f, comme dans le phare et l'éléphant."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Observez l'image et écoutez : » le PHARE, l'ÉLÉPHANT, le DAUPHIN, la PHOTO. Entendez-vous f ?"],
    app: ["Observent, écoutent, répondent : oui, on entend f !"],
    technique: ["Observation guidée"],
    support: "Image « le son ph »",
   },
   analyse: {
    ens: { paras: [["1) Avec quelles lettres écrit-on ph ?"], ["2) Comment se prononce ph ?"], ["3) Cite un mot avec ph."], ["4) L'éléphant : où est ph dans le mot ?"]] },
    app: { paras: [["R.A. : Avec ", { t: "p et h", r: true }, "."], ["R.A. : Comme ", { t: "f", r: true }, "."], ["R.A. : ", { t: "le phare, l'éléphant, le dauphin, la photo", r: true }, " (réponse libre)."], ["R.A. : À la fin : ", { t: "é-lé-p-hant", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Image « le son ph », syllabes au tableau",
   },
   synthese: {
    ens: ["Donc : ph s'écrit p-h et se prononce f — le phare, l'éléphant, le dauphin, la photo."],
    app: ["Lisent les 4 mots en chœur, puis individuellement."],
    technique: ["Lecture collective"],
    support: "Syllabes au tableau",
   },
   application: {
    ens: ["Le tri ph/f : je dis un mot, vous montrez f si le ph se prononce f (toujours !) et vous épellez p-h."],
    app: ["Épellent : phare, photo, dauphin, éléphant — p-h à chaque fois."],
    technique: ["Jeu d'épellation"],
    support: "Ardoises",
   },
   evaluation: {
    ens: ["3 élèves : lis 3 mots avec ph et dis le son."],
    app: ["R.A. : ", { t: "le phare, l'éléphant, le dauphin, la photo", r: true }, " (3 mots lus, ph = f)."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "78. LE SON PH",
    subs: [
     { t: "A. Le son", paras: [["Le son ", { t: "ph", k: true }, " s'écrit ", { t: "p-h", k: true }, " et se prononce ", { t: "f", k: true }, " — deux lettres, un seul son !"]] },
     { t: "B. Les mots", paras: [[{ t: "le phare", k: true }, " — ", { t: "l'éléphant", k: true }, " — ", { t: "le dauphin", k: true }, " — ", { t: "la photo", k: true }]] },
    ],
    retenir: ["Le son ", { t: "ph = f", k: true }, " : ", { t: "le phare, l'éléphant, le dauphin, la photo", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son ph :"], items: [["le phare"], ["la fleur"], ["l'éléphant"], ["la photo"], ["le fruit"], ["le dauphin"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Complète avec ph :"], items: [["1) le ...are (phare)"], ["2) l'élé...ant (éléphant)"], ["3) le dau...in (dauphin)"], ["4) la ...oto (photo)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Lis ton mot avec ph et épelle p-h (4 élèves) :"], items: [["1) Mot n°1 : ....... (lecture + épellation)"], ["2) Mot n°2 : ....... (lecture + épellation)"], ["3) Mot n°3 : ....... (lecture + épellation)"], ["4) Mot n°4 : ....... (lecture + épellation)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le phare, l'éléphant, la photo, le dauphin", r: true }, " (2 pts chacun) — la fleur (f simple) et le fruit (ui) non."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "ph", r: true }, " — 2) ", { t: "ph", r: true }, " — 3) ", { t: "ph", r: true }, " — 4) ", { t: "ph", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["Lectures + épellations correctes : ", { t: "1,5 pt par élève", r: true }, "."]] },
   ],
  },
  {
   n: 79,
   titre: "Écrire oi",
   titreFiche: "J'écris oi",
   sd: "Écriture",
   objectif: "Écrire proprement des mots avec oi : oie, toit, poire, trois.",
   supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
   revision: {
    ens: ["Lis : oie, voiture, toit, poire, trois (lecture collective)."],
    app: ["Lisent les 5 mots avec oi."],
    technique: ["Lecture collective"],
   },
   miseEnSituation: {
    ens: ["« Nous savons lire oi ; maintenant nous allons l'écrire : d'abord le o rond, puis le i avec son point. »"],
    app: ["Tracent oi dans l'air avec le doigt."],
    technique: ["Tracé dans l'air"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons oi : le o rond, le i pointu — attention au point du i !"],
    app: ["Écoutent et observent le modèle au tableau."],
    technique: ["Annonce orale"],
    support: "Lignes d'écriture au tableau",
   },
   observation: {
    ens: ["« Observez mon tracé : » j'écris oi trois fois — le o rond et fermé, le i droit avec son point au-dessus."],
    app: ["Observent les lettres, disent : o rond, i droit et son point !"],
    technique: ["Modèle d'écriture"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Comment commence-t-on oi ?"], ["2) Que met-on au-dessus du i ?"], ["3) Épelle « toit »."], ["4) Épelle « trois »."]] },
    app: { paras: [["R.A. : Par le ", { t: "o rond", r: true }, "."], ["R.A. : Son ", { t: "point", r: true }, "."], ["R.A. : ", { t: "t-o-i-t", r: true }, "."], ["R.A. : ", { t: "t-r-o-i-s", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : oi = o rond + i pointu ; j'écris oie, toit, poire, trois."],
    app: ["Écrivent oi deux fois sur l'ardoise avant le cahier."],
    technique: ["Écriture guidée"],
    support: "Ardoises",
   },
   application: {
    ens: ["Au cahier : écris oi, oie, toit, poire, trois — une ligne bien ronde pour chaque mot."],
    app: ["Écrivent les 5 mots sur leurs cahiers."],
    technique: ["Copie individuelle"],
    support: "Cahiers",
   },
   evaluation: {
    ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
    app: ["R.A. : ", { t: "oie, toit, poire, trois", r: true }, " écrits sans faute (o ronds, points sur les i)."],
    technique: ["Vérification des cahiers"],
   },
   lecon: {
    titre: "79. ÉCRIRE OI",
    subs: [
     { t: "A. Les lettres", paras: [["Le son ", { t: "oi", k: true }, " : ", { t: "o rond", k: true }, " + ", { t: "i avec son point", k: true }, " — pas d'espace entre les deux !"]] },
     { t: "B. Mes mots", paras: [[{ t: "l'oie", k: true }, " — ", { t: "le toit", k: true }, " — ", { t: "la poire", k: true }, " — ", { t: "trois", k: true }]] },
    ],
    retenir: ["J'écris ", { t: "o-i", k: true }, " ensemble : ", { t: "oie, toit, poire, trois", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris oi deux fois sur l'ardoise :"], items: [["1) oi n°1 (tracé)"], ["2) oi n°2 (tracé)"], ["3) o rond bien fermé (1 pt)"], ["4) i avec son point (1 pt)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) oie (copie)"], ["2) toit (copie)"], ["3) poire (copie)"], ["4) trois (copie)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Complète en écrivant oi :"], items: [["1) l'... (oie)"], ["2) la p...re (poire)"], ["3) le t... (toit)"], ["4) t...s (trois)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "o rond fermé, i pointé", r: true }, " (2 pts par oi réussi)."]] },
    { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "oi", r: true }, " — 2) ", { t: "oi", r: true }, " — 3) ", { t: "oi", r: true }, " — 4) ", { t: "oi", r: true }, " (1,5 pt par mot complété)."]] },
   ],
  },
  {
   n: 80,
   titre: "Écrire ui",
   titreFiche: "J'écris ui",
   sd: "Écriture",
   objectif: "Écrire proprement des mots avec ui : fruit, nuit, pluie, cuit.",
   supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
   revision: {
    ens: ["Épelle toit et trois (2 élèves)."],
    app: ["R.A. : ", { t: "t-o-i-t", r: true }, " ; ", { t: "t-r-o-i-s", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Nous écrivons maintenant ui : le u avec son crochet, le i avec son point, collés ensemble. »"],
    app: ["Tracent ui dans l'air avec le doigt."],
    technique: ["Tracé dans l'air"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons ui : u puis i, sans espace — le fruit, la nuit."],
    app: ["Écoutent et observent le modèle au tableau."],
    technique: ["Annonce orale"],
    support: "Lignes d'écriture au tableau",
   },
   observation: {
    ens: ["« Observez mon tracé : » j'écris ui trois fois — le u descend et remonte, le i suit avec son point."],
    app: ["Observent les lettres, disent : u puis i avec son point !"],
    technique: ["Modèle d'écriture"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Quelles lettres pour ui ?"], ["2) Épelle « fruit »."], ["3) Épelle « nuit »."], ["4) Quel point attention au tableau ?"]] },
    app: { paras: [["R.A. : ", { t: "u puis i", r: true }, "."], ["R.A. : ", { t: "f-r-u-i-t", r: true }, "."], ["R.A. : ", { t: "n-u-i-t", r: true }, "."], ["R.A. : Le ", { t: "point du i", r: true }, " !"]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : ui = u + i collés ; j'écris fruit, nuit, pluie, cuit."],
    app: ["Écrivent ui deux fois sur l'ardoise avant le cahier."],
    technique: ["Écriture guidée"],
    support: "Ardoises",
   },
   application: {
    ens: ["Au cahier : écris ui, fruit, nuit, pluie, cuit — beaux u ronds et i pointés."],
    app: ["Écrivent les 5 mots sur leurs cahiers."],
    technique: ["Copie individuelle"],
    support: "Cahiers",
   },
   evaluation: {
    ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
    app: ["R.A. : ", { t: "fruit, nuit, pluie, cuit", r: true }, " écrits sans faute."],
    technique: ["Vérification des cahiers"],
   },
   lecon: {
    titre: "80. ÉCRIRE UI",
    subs: [
     { t: "A. Les lettres", paras: [["Le son ", { t: "ui", k: true }, " : ", { t: "u", k: true }, " + ", { t: "i avec son point", k: true }, " — deux lettres collées !"]] },
     { t: "B. Mes mots", paras: [[{ t: "le fruit", k: true }, " — ", { t: "la nuit", k: true }, " — ", { t: "la pluie", k: true }, " — ", { t: "cuit", k: true }]] },
    ],
    retenir: ["J'écris ", { t: "u-i", k: true }, " ensemble : ", { t: "fruit, nuit, pluie, cuit", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris ui deux fois sur l'ardoise :"], items: [["1) ui n°1 (tracé)"], ["2) ui n°2 (tracé)"], ["3) u bien arrondi (1 pt)"], ["4) i avec son point (1 pt)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) fruit (copie)"], ["2) nuit (copie)"], ["3) pluie (copie)"], ["4) cuit (copie)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Complète en écrivant ui :"], items: [["1) le fr...t (fruit)"], ["2) la pl...e (pluie)"], ["3) la n...t (nuit)"], ["4) c...t (cuit)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "u arrondi, i pointé", r: true }, " (2 pts par ui réussi)."]] },
    { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "ui", r: true }, " — 2) ", { t: "ui", r: true }, " — 3) ", { t: "ui", r: true }, " — 4) ", { t: "ui", r: true }, " (1,5 pt par mot complété)."]] },
   ],
  },
  {
   n: 81,
   titre: "Écrire ph",
   titreFiche: "J'écris ph",
   sd: "Écriture",
   objectif: "Écrire proprement des mots avec ph : phare, éléphant, dauphin, photo.",
   supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
   revision: {
    ens: ["Épelle fruit et nuit (2 élèves)."],
    app: ["R.A. : ", { t: "f-r-u-i-t", r: true }, " ; ", { t: "n-u-i-t", r: true }, "."],
    technique: ["Individuel oral"],
   },
   miseEnSituation: {
    ens: ["« Nous écrivons ph : le p avec sa queue qui descend, le h avec sa bosse — deux lettres, un son f ! »"],
    app: ["Tracent ph dans l'air avec le doigt."],
    technique: ["Tracé dans l'air"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons ph : p descend sous la ligne, h monte avec sa bosse."],
    app: ["Écoutent et observent le modèle au tableau."],
    technique: ["Annonce orale"],
    support: "Lignes d'écriture au tableau",
   },
   observation: {
    ens: ["« Observez mon tracé : » j'écris ph trois fois — le p descend sous la ligne, le h a une bosse et reste sur la ligne."],
    app: ["Observent les lettres, disent : p sous la ligne, h avec sa bosse !"],
    technique: ["Modèle d'écriture"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Quelles lettres pour ph ?"], ["2) Comment se prononce ph ?"], ["3) Épelle « phare »."], ["4) Épelle « dauphin »."]] },
    app: { paras: [["R.A. : ", { t: "p et h", r: true }, "."], ["R.A. : Comme ", { t: "f", r: true }, "."], ["R.A. : ", { t: "p-h-a-r-e", r: true }, "."], ["R.A. : ", { t: "d-a-u-p-h-i-n", r: true }, "."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : ph = p + h, ça se prononce f ; j'écris phare, éléphant, dauphin, photo."],
    app: ["Écrivent ph deux fois sur l'ardoise avant le cahier."],
    technique: ["Écriture guidée"],
    support: "Ardoises",
   },
   application: {
    ens: ["Au cahier : écris ph, phare, éléphant, dauphin, photo — beaux p qui descendent sous la ligne."],
    app: ["Écrivent les 5 mots sur leurs cahiers."],
    technique: ["Copie individuelle"],
    support: "Cahiers",
   },
   evaluation: {
    ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
    app: ["R.A. : ", { t: "phare, éléphant, dauphin, photo", r: true }, " écrits sans faute (p-h partout)."],
    technique: ["Vérification des cahiers"],
   },
   lecon: {
    titre: "81. ÉCRIRE PH",
    subs: [
     { t: "A. Les lettres", paras: [["Le son ", { t: "ph", k: true }, " : ", { t: "p qui descend", k: true }, " + ", { t: "h avec sa bosse", k: true }, " — ça se prononce ", { t: "f", k: true }, " !"]] },
     { t: "B. Mes mots", paras: [[{ t: "le phare", k: true }, " — ", { t: "l'éléphant", k: true }, " — ", { t: "le dauphin", k: true }, " — ", { t: "la photo", k: true }]] },
    ],
    retenir: ["J'écris ", { t: "p-h", k: true }, " ensemble : ", { t: "phare, éléphant, dauphin, photo", k: true }, "."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Écris ph deux fois sur l'ardoise :"], items: [["1) ph n°1 (tracé)"], ["2) ph n°2 (tracé)"], ["3) p qui descend sous la ligne (1 pt)"], ["4) h avec sa bosse (1 pt)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) phare (copie)"], ["2) éléphant (copie)"], ["3) dauphin (copie)"], ["4) photo (copie)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Complète en écrivant ph :"], items: [["1) le ...are (phare)"], ["2) l'élé...ant (éléphant)"], ["3) le dau...in (dauphin)"], ["4) la ...oto (photo)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "p sous la ligne, h à bosse", r: true }, " (2 pts par ph réussi)."]] },
    { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
    { titre: "Exercice 3", lines: [["1) ", { t: "ph", r: true }, " — 2) ", { t: "ph", r: true }, " — 3) ", { t: "ph", r: true }, " — 4) ", { t: "ph", r: true }, " (1,5 pt par mot complété)."]] },
   ],
  },
  {
   n: 82,
   titre: "Dictée — oi, ui, ph",
   titreFiche: "Je dicte et j'écris",
   sd: "Écriture",
   objectif: "Écrire sous la dictée des mots avec oi, ui et ph.",
   supportFiche: "Tableau noir, cahiers de dictée.",
   revision: {
    ens: ["Relis au tableau : oie, fruit, phare (lecture collective)."],
    app: ["Lisent : oie (oi), fruit (ui), phare (ph)."],
    technique: ["Lecture collective"],
   },
   miseEnSituation: {
    ens: ["« Aujourd'hui, grande dictée des sons du marché : oi, ui, ph. Écoutez, répétez, puis écrivez. »"],
    app: ["Se préparent : cahier ouvert, crayon en main."],
    technique: ["Rituel de dictée"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, nous écrivons sous la dictée : d'abord des mots, puis une phrase."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Relisez les modèles avant la dictée : » oie, toit, fruit, nuit, pluie, phare, photo."],
    app: ["Relisent chaque mot, épellent oi, ui, ph."],
    technique: ["Relecture guidée"],
    support: "Tableau noir",
   },
   analyse: {
    ens: { paras: [["1) Dans « oie », quelles lettres font le son oi ?"], ["2) Dans « pluie », quelles lettres font ui ?"], ["3) Dans « phare », quelles lettres font f ?"], ["4) Répétez la phrase : la pluie tombe sur le toit."]] },
    app: { paras: [["R.A. : ", { t: "o-i", r: true }, "."], ["R.A. : ", { t: "u-i", r: true }, "."], ["R.A. : ", { t: "p-h", r: true }, "."], ["R.A. : ", { t: "la pluie tombe sur le toit", r: true }, " (répétition exacte)."]] },
    technique: ["Question / réponse"],
    support: "Tableau noir",
   },
   synthese: {
    ens: ["Donc : j'écoute le son — oi, ui ou ph — puis j'écris les bonnes lettres."],
    app: ["Répètent la stratégie : j'écoute, je trouve le son, j'écris."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Dictée : oie, fruit, phare — puis la phrase : la pluie tombe sur le toit."],
    app: ["Écrivent sous la dictée, mot par mot, puis la phrase."],
    technique: ["Dictée"],
    support: "Cahiers de dictée",
   },
   evaluation: {
    ens: ["Correction collective au tableau, puis 3 cahiers vérifiés."],
    app: ["Corrigent avec le modèle : ", { t: "oie, fruit, phare + la phrase", r: true }, "."],
    technique: ["Correction collective"],
   },
   lecon: {
    titre: "82. DICTÉE — OI, UI, PH",
    subs: [
     { t: "A. Ma dictée", paras: [["Mots : ", { t: "oie, fruit, phare", k: true }, " — phrase : ", { t: "la pluie tombe sur le toit", k: true }, "."]] },
     { t: "B. Ma méthode", paras: [["J'écoute le son → ", { t: "oi, ui ou ph", k: true }, " → j'écris les ", { t: "bonnes lettres", k: true }, "."]] },
    ],
    retenir: ["Dictée réussie : ", { t: "oi, ui, ph bien écrits", k: true }, " et majuscule + point pour la phrase."],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Dictée de mots (4 mots) :"], items: [["1) toit (dictée)"], ["2) nuit (dictée)"], ["3) phare (dictée)"], ["4) fruit (dictée)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Dictée de la phrase :"], items: [["1) La pluie tombe sur le toit. (dictée)"], ["2) Majuscule au début (1,5 pt)"], ["3) Point à la fin (1,5 pt)"], ["4) oi et ui bien écrits (3 pts)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Auto-correction : je relis et je répare (4 élèves) :"], items: [["1) Mon mot n°1 : ....... (relecture)"], ["2) Mon mot n°2 : ....... (relecture)"], ["3) Mon mot n°3 : ....... (relecture)"], ["4) Ma phrase : ....... (relecture)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Mots exacts : ", { t: "toit, nuit, phare, fruit", r: true }, " (2 pts chacun)."]] },
    { titre: "Exercice 2", lines: [["Phrase exacte : ", { t: "La pluie tombe sur le toit.", r: true }, " — majuscule, point, oi et ui justes."]] },
    { titre: "Exercice 3", lines: [["Relectures avec corrections : ", { t: "fautes réparées", r: true }, " (1,5 pt par relecture)."]] },
   ],
  },
  {
   n: 83,
   titre: "Bilan de l'unité 6",
   titreFiche: "Le grand bilan du marché",
   sd: "Écriture",
   objectif: "Faire le bilan : vocabulaire du marché, dialogue, sons oi, ui et ph.",
   supportFiche: "Image « le marché », tableau noir, cahiers.",
   revision: {
    ens: ["Relis les mots de la dictée : toit, nuit, phare, fruit."],
    app: ["Relisent et épellent les sons oi, ui, ph."],
    technique: ["Lecture collective"],
   },
   miseEnSituation: {
    ens: ["« Voici le grand bilan du marché : tout ce que nous avons appris dans l'unité 6 ! »"],
    app: ["Écoutent, se rappellent les séances."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   presentation: {
    ens: ["Aujourd'hui, le grand bilan : les fruits, les légumes, le dialogue du marché, les prix et les sons oi, ui, ph."],
    app: ["Écoutent."],
    technique: ["Annonce orale"],
    support: "Tableau noir",
   },
   observation: {
    ens: ["« Regardez l'image du marché et souvenez-vous : » les fruits, les légumes, la marchande, le panier, les ariary."],
    app: ["Observent l'image et énumèrent les acquis."],
    technique: ["Observation guidée"],
    support: "Image « le marché »",
   },
   analyse: {
    ens: { paras: [["1) Cite 3 fruits."], ["2) Cite 3 légumes."], ["3) Joue : « Combien coûte... ? — ... ariary. »"], ["4) Cite un mot avec oi, un avec ui, un avec ph."]] },
    app: { paras: [["R.A. : ", { t: "banane, mangue, orange...", r: true }, " (3 fruits)."], ["R.A. : ", { t: "tomate, oignon, carotte...", r: true }, " (3 légumes)."], ["R.A. : « ", { t: "Combien coûte le riz ? — Cinq cents ariary.", r: true }, " »"], ["R.A. : ", { t: "oie / fruit / phare", r: true }, " (3 mots avec les sons)."]] },
    technique: ["Question / réponse"],
    support: "Image « le marché »",
   },
   synthese: {
    ens: ["Donc : le marché — les produits, le dialogue, les prix, la pesée, la comptine, et les sons oi, ui, ph."],
    app: ["Récitent la comptine du marché une dernière fois en chœur."],
    technique: ["Répétition collective"],
    support: "Tableau noir",
   },
   application: {
    ens: ["Mini-exposé : chacun présente « mon marché » avec 3 phrases (produits, prix, avis)."],
    app: ["Présentent : au marché, j'achète... ; ça coûte... ; j'aime le marché !"],
    technique: ["Mini-exposé"],
    support: "Tableau noir",
   },
   evaluation: {
    ens: ["Grande évaluation : 3 élèves par tableau — vocabulaire, dialogue, sons."],
    app: ["R.A. : bilan complet de l'unité 6 ", { t: "réussi", r: true }, "."],
    technique: ["Individuel oral"],
   },
   lecon: {
    titre: "83. BILAN DE L'UNITÉ 6",
    subs: [
     { t: "A. La dictée", paras: [["J'écris : ", { t: "oie, fruit, phare", k: true }, " — ", { t: "la pluie tombe sur le toit", k: true }]] },
     { t: "B. Bilan de l'unité", paras: [[{ t: "Le marché", k: true }, " (fruits, légumes, dialogue, prix) + les sons ", { t: "oi, ui, ph", k: true }, " : tout est appris !"]] },
    ],
    retenir: ["Unité 6 réussie : ", { t: "le marché, les fruits et légumes, le dialogue de l'achat et les sons oi, ui, ph", k: true }, " !"],
   },
   exercices: [
    { titre: "Exercice 1", pts: 8, consigne: ["Dictée bilan :"], items: [["1) oie (dictée)"], ["2) fruit (dictée)"], ["3) phare (dictée)"], ["4) la pluie tombe sur le toit (dictée)"]] },
    { titre: "Exercice 2", pts: 6, consigne: ["Classe les sons (oi, ui ou ph) :"], items: [["1) l'....... (oie : oi)"], ["2) la n....... (nuit : ui)"], ["3) l'élé....... (éléphant : ph)"], ["4) la ph... (photo : ph)"]] },
    { titre: "Exercice 3", pts: 6, consigne: ["Présente « mon marché » en 3 phrases (4 élèves) :"], items: [["1) J'achète ....... (réponse libre)"], ["2) Ça coûte ....... (réponse libre)"], ["3) J'aime ....... (réponse libre)"], ["4) Au revoir ....... (réponse libre : la marchande)"]] },
   ],
   corrige: [
    { titre: "Exercice 1", lines: [["Dictée exacte : ", { t: "oie, fruit, phare", r: true }, " (2 pts chacun) + phrase complète (2 pts)."]] },
    { titre: "Exercice 2", lines: [["1) ", { t: "oi", r: true }, " — 2) ", { t: "ui", r: true }, " — 3) ", { t: "ph", r: true }, " — 4) ", { t: "ph", r: true }, " (photo)."]] },
    { titre: "Exercice 3", lines: [["Présentations complètes (3 phrases) : ", { t: "1,5 pt par élève", r: true }, "."]] },
   ],
  },
 ],
};

module.exports = { theme6 };
