// data-theme7.js — Unité 7 « Les repas » (séances 84 à 99)
// Sources : FRA 10ème (T3 : repas, sons in, g/gu, k/c) + PDF CP2 unité VII (16 séances)
// + RAPE T2 2025-2026 P3 (indicateurs temporels matin/midi/soir) et P1 (hygiène : se laver les mains).
// sd par séance : EO s84-93, Lecture s94-96, Écriture s97-99. Barème 8+6+6 = 20 partout.

const theme7 = {
 numero: 7,
 nom: "Les repas",
 sousDiscipline: "Expression Orale",
 notions: "Le vocabulaire des repas malgaches (riz, laoka, brèdes), les moments de la journée, la politesse du repas, et les sons in, g/gu et k/c.",
 competences: [
 "Nommer les repas de la journée et les aliments : riz, laoka, brèdes, soupe, pain.",
 "Dire ce qu'on mange : « Je mange du riz. » ; dire ce qu'on aime : « J'aime / Je n'aime pas. »",
 "Reconnaître et prononcer les sons in, g/gu et k/c.",
 "Écrire des mots simples avec in, g et k.",
 ],
 seances: [
 {
  n: 84,
  titre: "Le vocabulaire des repas",
  titreFiche: "Les repas que je connais",
  sd: "Expression Orale",
  objectif: "Nommer les repas et les aliments : le riz, le laoka, la viande, les brèdes, la soupe, le pain.",
  supportFiche: "Image « le repas », aliments réels ou dessins, tableau noir.",
  revision: {
  ens: ["Le grand bilan du marché : joue le dialogue de l'achat (2 paires)."],
  app: ["R.A. : « ", { t: "Bonjour ! — Je voudrais..., s'il vous plaît. — Voilà. — Merci !", r: true }, " »"],
  technique: ["Jeu de rôle"],
  },
  miseEnSituation: {
  ens: ["« Qu'avez-vous mangé ce matin ? Et hier soir ? Qui mange du riz tous les jours ? »"],
  app: ["Proposent : du riz, du pain, des brèdes, de la soupe..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les mots des repas : le riz, le laoka, la viande, les brèdes, la soupe, le pain."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image du repas : » je montre le plat de riz, le laoka, les brèdes, la soupe, le pain."],
  app: ["Observent et nomment : le riz, le laoka, la viande, les brèdes, la soupe, le pain."],
  technique: ["Observation guidée"],
  support: "Image « le repas »",
  },
  analyse: {
  ens: { paras: [["1) Quel est l'aliment principal des repas malgaches ?"], ["2) Comment appelle-t-on ce qui accompagne le riz ?"], ["3) Quels légumes mange-t-on avec le riz ?"], ["4) Quel aliment mange-t-on au petit-déjeuner ?"]] },
  app: { paras: [["R.A. : Le ", { t: "riz", r: true }, "."], ["R.A. : Le ", { t: "laoka", r: true }, "."], ["R.A. : Les ", { t: "brèdes", r: true }, "."], ["R.A. : Le ", { t: "pain", r: true }, " (ou la banane)."]] },
  technique: ["Question / réponse"],
  support: "Image « le repas »",
  },
  synthese: {
  ens: ["Donc : les repas — le riz, le laoka, la viande, les brèdes, la soupe, le pain."],
  app: ["Répètent les 6 mots en chœur en mimant le geste de manger."],
  technique: ["Répétition collective"],
  support: "Image « le repas »",
  },
  application: {
  ens: ["Le jeu du panier : je nomme un mot, crie « au repas ! » si c'est un aliment, silence sinon."],
  app: ["Répondent : le riz (au repas !), le cahier (silence), la soupe (au repas !)..."],
  technique: ["Jeu de tri oral"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : nomme 3 aliments du repas."],
  app: ["R.A. : ", { t: "riz, laoka, viande, brèdes, soupe, pain", r: true }, " (3 mots corrects)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "84. LE VOCABULAIRE DES REPAS",
  subs: [
   { t: "A. Les repas", paras: [[{ t: "le petit-déjeuner", k: true }, " (le matin) — ", { t: "le déjeuner", k: true }, " (à midi) — ", { t: "le dîner", k: true }, " (le soir)"]] },
   { t: "B. Les aliments", paras: [[{ t: "le riz", k: true }, " — ", { t: "le laoka", k: true }, " — ", { t: "la viande", k: true }, " — ", { t: "les brèdes", k: true }, " — ", { t: "la soupe", k: true }, " — ", { t: "le pain", k: true }]] },
  ],
  retenir: ["Les repas malgaches : ", { t: "le riz avec le laoka — brèdes, viande, soupe, pain", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les aliments :"], items: [["le riz"], ["le cahier"], ["les brèdes"], ["le panier"], ["la soupe"], ["le pain"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Je mange du ....... avec du laoka. (riz)"], ["2) Maman prépare la ....... (soupe)"], ["3) Les ....... accompagnent le riz. (brèdes)"], ["4) Le matin, je mange du ....... (pain)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Nomme 3 aliments que tu as mangés hier (4 élèves) :"], items: [["1) Aliment n°1 : ....... (réponse libre)"], ["2) Aliment n°2 : ....... (réponse libre)"], ["3) Aliment n°3 : ....... (réponse libre)"], ["4) Ton aliment préféré : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Aliments entourés : ", { t: "le riz, les brèdes, la soupe, le pain", r: true }, " (2 pts chacun) — cahier (école) et panier (marché) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "riz", r: true }, " — 2) ", { t: "soupe", r: true }, " — 3) ", { t: "brèdes", r: true }, " — 4) ", { t: "pain", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Aliments correctement nommés : ", { t: "1,5 pt par aliment", r: true }, "."]] },
  ],
 },
 {
  n: 85,
  titre: "Le petit-déjeuner",
  titreFiche: "Le matin : pain et lait",
  sd: "Expression Orale",
  objectif: "Dire ce qu'on mange et boit au petit-déjeuner : « Je mange du pain et je bois du lait. »",
  supportFiche: "Image « le repas », pain et fruits réels, tableau noir.",
  revision: {
  ens: ["Nomme 3 aliments du repas (chaîne parlée)."],
  app: ["R.A. : ", { t: "riz, laoka, brèdes, soupe, pain", r: true }, "."],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Ce matin, qui a mangé du pain ? Qui a bu du lait ou du thé ? »"],
  app: ["Lèvent la main, proposent : du pain, du lait, du thé, une banane..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous parlons du petit-déjeuner : je mange..., je bois..."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez et observez : » Soa mange du pain et boit du lait ; Lanto mange une banane et boit du thé."],
  app: ["Observent, répètent : je mange du pain, je bois du lait, je mange une banane, je bois du thé."],
  technique: ["Observation guidée"],
  support: "Image « le repas »",
  },
  analyse: {
  ens: { paras: [["1) Que mange Soa ?"], ["2) Que boit-elle ?"], ["3) Que mange Lanto ?"], ["4) Et toi, que manges-tu au petit-déjeuner ?"]] },
  app: { paras: [["R.A. : Du ", { t: "pain", r: true }, "."], ["R.A. : Du ", { t: "lait", r: true }, "."], ["R.A. : Une ", { t: "banane", r: true }, "."], ["R.A. : « ", { t: "Je mange... et je bois...", r: true }, " » (réponse personnelle)."]] },
  technique: ["Question / réponse"],
  support: "Image « le repas »",
  },
  synthese: {
  ens: ["Donc : au petit-déjeuner — « je mange du pain, je bois du lait » (manger = manger, boire = boire)."],
  app: ["Répètent les deux modèles en chœur, puis individuellement."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["La chaîne du petit-déjeuner : chacun ajoute « et » puis un aliment — je mange du pain et une banane et..."],
  app: ["Enchaînent : je mange du pain et une banane ; ...et un œuf..."],
  technique: ["Jeu de mémoire enchaîné"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : dis ta phrase du petit-déjeuner (manger + boire)."],
  app: ["R.A. : « ", { t: "Je mange du pain et je bois du lait.", r: true }, " » (manger + boire)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "85. LE PETIT-DÉJEUNER",
  subs: [
   { t: "A. Les mots", paras: [[{ t: "le pain", k: true }, " — ", { t: "le lait", k: true }, " — ", { t: "le thé", k: true }, " — ", { t: "la banane", k: true }, " — ", { t: "l'œuf", k: true }, " — ", { t: "la goyave", k: true }]] },
   { t: "B. Ma phrase", paras: [["« ", { t: "Je mange du pain et je bois du lait.", k: true }, " »"]] },
  ],
  retenir: ["Au petit-déjeuner : « ", { t: "Je mange..., je bois...", k: true }, " » — pain, lait, thé, banane."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure ce qu'on boit :"], items: [["le lait"], ["le pain"], ["le thé"], ["la banane"], ["l'eau"], ["la soupe"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec mange ou bois :"], items: [["1) Je ....... du pain. (mange)"], ["2) Je ....... du lait. (bois)"], ["3) Il ....... une banane. (mange)"], ["4) Elle ....... du thé. (boit)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Dis ta phrase du petit-déjeuner (4 élèves) :"], items: [["1) Élève n°1 : ....... (réponse libre)"], ["2) Élève n°2 : ....... (réponse libre)"], ["3) Élève n°3 : ....... (réponse libre)"], ["4) Élève n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Boissons entourées : ", { t: "le lait, le thé, l'eau", r: true }, " (2 pts chacun) — pain, banane, soupe : à manger, non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "mange", r: true }, " — 2) ", { t: "bois", r: true }, " — 3) ", { t: "mange", r: true }, " — 4) ", { t: "boit", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Phrases complètes (manger + boire) : ", { t: "1,5 pt par phrase", r: true }, "."]] },
  ],
 },
 {
  n: 86,
  titre: "Le déjeuner et le dîner",
  titreFiche: "Le matin, à midi, le soir",
  sd: "Expression Orale",
  objectif: "Placer les repas dans la journée : le matin, à midi, le soir — « À midi, je mange du riz. »",
  supportFiche: "Image « le repas », horloge dessinée, tableau noir.",
  revision: {
  ens: ["Dis ta phrase du petit-déjeuner (2 élèves)."],
  app: ["R.A. : « ", { t: "Je mange du pain et je bois du lait.", r: true }, " »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Quand mangez-vous le gros repas de riz ? Le matin, à midi ou le soir ? Et la soupe ? »"],
  app: ["Proposent : à midi le riz ; le soir la soupe..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous plaçons les repas dans la journée : le matin, à midi, le soir."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'horloge et écoutez : » le matin, pain et lait ; à midi, riz et brèdes ; le soir, soupe et banane."],
  app: ["Observent, répètent les trois moments de la journée."],
  technique: ["Observation guidée"],
  support: "Horloge dessinée",
  },
  analyse: {
  ens: { paras: [["1) Quand mange-t-on le petit-déjeuner ?"], ["2) Quand mange-t-on le déjeuner ?"], ["3) Quand mange-t-on le dîner ?"], ["4) Que mange-t-on à midi ?"]] },
  app: { paras: [["R.A. : ", { t: "Le matin", r: true }, "."], ["R.A. : ", { t: "À midi", r: true }, "."], ["R.A. : ", { t: "Le soir", r: true }, "."], ["R.A. : Du ", { t: "riz et des brèdes", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Horloge dessinée",
  },
  synthese: {
  ens: ["Donc : le matin — petit-déjeuner ; à midi — déjeuner ; le soir — dîner."],
  app: ["Répètent les 3 moments en chœur en montrant le soleil qui monte, le soleil haut, la lune."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu des moments : je nomme un repas, vous dites le moment — le dîner ? le soir !"],
  app: ["Répondent : le petit-déjeuner (le matin), le déjeuner (à midi), le dîner (le soir)."],
  technique: ["Jeu question-réponse"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : dis la phrase complète — « À midi, je mange... »"],
  app: ["R.A. : « ", { t: "À midi, je mange du riz et des brèdes.", r: true }, " » (moment + repas)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "86. LE DÉJEUNER ET LE DÎNER",
  subs: [
   { t: "A. Les moments", paras: [[{ t: "le matin", k: true }, " — ", { t: "à midi", k: true }, " — ", { t: "le soir", k: true }]] },
   { t: "B. Mes phrases", paras: [["« ", { t: "Le matin, je mange du pain.", k: true }, " » — « ", { t: "À midi, je mange du riz et des brèdes.", k: true }, " » — « ", { t: "Le soir, je mange de la soupe.", k: true }, " »"]] },
  ],
  retenir: ["Les 3 repas : ", { t: "le matin", k: true }, " (petit-déjeuner), ", { t: "à midi", k: true }, " (déjeuner), ", { t: "le soir", k: true }, " (dîner)."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les moments de la journée :"], items: [["le matin"], ["le panier"], ["à midi"], ["la cuillère"], ["le soir"], ["le riz"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Relie le repas au moment :"], items: [["1) Le petit-déjeuner : le matin / le soir"], ["2) Le déjeuner : à midi / la nuit"], ["3) Le dîner : le soir / le matin"], ["4) Le goûter : l'après-midi / à midi"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Complète :"], items: [["1) ......., je mange du pain. (Le matin)"], ["2) À ......., je mange du riz. (midi)"], ["3) Le ......., je mange de la soupe. (soir)"], ["4) À midi, je mange du riz et des ....... (brèdes)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Moments entourés : ", { t: "le matin, à midi, le soir", r: true }, " (2 pts chacun) — panier (marché), cuillère (table), riz (aliment) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "le matin", r: true }, " — 2) ", { t: "à midi", r: true }, " — 3) ", { t: "le soir", r: true }, " — 4) ", { t: "l'après-midi", r: true }, " (2 pts chacun)."]] },
  { titre: "Exercice 3", lines: [["1) ", { t: "Le matin", r: true }, " — 2) ", { t: "midi", r: true }, " — 3) ", { t: "soir", r: true }, " — 4) ", { t: "brèdes", r: true }, "."]] },
  ],
 },
 {
  n: 87,
  titre: "Le dialogue du repas",
  titreFiche: "Qu'est-ce que tu manges ?",
  sd: "Expression Orale",
  objectif: "Jouer le dialogue du repas : « Qu'est-ce que tu manges ? — Je mange du riz et des brèdes. — C'est bon ! »",
  supportFiche: "Image « le repas », bol et cuillère réels, tableau noir.",
  revision: {
  ens: ["Les 3 moments de la journée (réponse rapide)."],
  app: ["R.A. : ", { t: "le matin, à midi, le soir", r: true }, "."],
  technique: ["Jeu rapide"],
  },
  miseEnSituation: {
  ens: ["« À la maison, quand maman a fini de cuisiner, que vous demande-t-elle ? »"],
  app: ["Proposent : de manger, de venir manger..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous jouons le dialogue du repas : la question, la réponse, le compliment."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez le dialogue : » — Qu'est-ce que tu manges, Rova ? — Je mange du riz et des brèdes. — C'est bon ? — Oui, c'est très bon !"],
  app: ["Écoutent, puis répètent chaque réplique."],
  technique: ["Modèle oral"],
  support: "Image « le repas »",
  },
  analyse: {
  ens: { paras: [["1) Que demande la maman à Rova ?"], ["2) Que mange Rova ?"], ["3) Que répond-il quand on lui demande si c'est bon ?"], ["4) Pose-moi la question du repas !"]] },
  app: { paras: [["R.A. : « ", { t: "Qu'est-ce que tu manges ?", r: true }, " »"], ["R.A. : Du ", { t: "riz et des brèdes", r: true }, "."], ["R.A. : « ", { t: "Oui, c'est très bon !", r: true }, " »"], ["R.A. : « ", { t: "Qu'est-ce que tu manges ?", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « le repas »",
  },
  synthese: {
  ens: ["Donc : « Qu'est-ce que tu manges ? — Je mange... — C'est bon ! »"],
  app: ["Répètent le dialogue en chœur, puis par deux."],
  technique: ["Répétition par deux"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu du repas : deux élèves jouent la scène avec le bol et la cuillère."],
  app: ["Jouent : qu'est-ce que tu manges ? — je mange du riz et de la viande — c'est très bon !"],
  technique: ["Jeu de rôle"],
  support: "Bol et cuillère réels",
  },
  evaluation: {
  ens: ["3 paires : joue le dialogue complet."],
  app: ["R.A. : ", { t: "question + réponse + compliment", r: true }, " (dialogue complet)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "87. LE DIALOGUE DU REPAS",
  subs: [
   { t: "A. Le dialogue", paras: [["« — ", { t: "Qu'est-ce que tu manges ?", k: true }, " — ", { t: "Je mange du riz et des brèdes.", k: true }, " »"], ["« — ", { t: "C'est bon ?", k: true }, " — ", { t: "Oui, c'est très bon !", k: true }, " »"]] },
  ],
  retenir: ["« ", { t: "Qu'est-ce que tu manges ? — Je mange...", k: true }, " » — et je complimente : ", { t: "c'est très bon !", k: true }],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots du dialogue du repas :"], items: [["manges"], ["le panier"], ["je mange"], ["c'est bon"], ["l'étal"], ["le riz"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète le dialogue :"], items: [["1) Qu'est-ce que tu ....... ? (manges)"], ["2) Je ....... du riz. (mange)"], ["3) Je mange du riz et des ....... (brèdes)"], ["4) C'est très ....... ! (bon)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Joue la scène avec un camarade (4 répliques) :"], items: [["1) La question : ......."], ["2) La réponse : ......."], ["3) La demande « c'est bon ? » : ......."], ["4) Le compliment : ......."]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Entourés : ", { t: "manges, je mange, c'est bon, le riz", r: true }, " (2 pts chacun) — panier et étal (marché) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "manges", r: true }, " — 2) ", { t: "mange", r: true }, " — 3) ", { t: "brèdes", r: true }, " — 4) ", { t: "bon", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Scènes jouées : ", { t: "répliques complètes", r: true }, " (1,5 pt par réplique)."]] },
  ],
 },
 {
  n: 88,
  titre: "Bon appétit !",
  titreFiche: "La politesse du repas",
  sd: "Expression Orale",
  objectif: "Dire les mots polis du repas : je me lave les mains, bon appétit, merci c'est bon, encore s'il te plaît.",
  supportFiche: "Image « le repas », savon et bidon d'eau, tableau noir.",
  revision: {
  ens: ["Joue le dialogue du repas avec ton voisin (30 secondes)."],
  app: ["R.A. : « Qu'est-ce que tu manges ? — Je mange... — C'est très bon ! »"],
  technique: ["Jeu de rôle express"],
  },
  miseEnSituation: {
  ens: ["« Que fait-on AVANT de manger ? Et que dit-on quand on sert le plat à un camarade ? »"],
  app: ["Proposent : on se lave les mains ; bon appétit ! merci !"],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons la politesse du repas : se laver les mains, bon appétit, merci."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Regardez et écoutez : » avant de manger, je me lave les mains ; je dis « bon appétit » ; si je veux encore, je dis « encore, s'il te plaît » ; à la fin, « merci, c'était très bon ! »"],
  app: ["Observent, miment le lavage des mains, répètent chaque formule."],
  technique: ["Observation guidée"],
  support: "Savon et bidon d'eau",
  },
  analyse: {
  ens: { paras: [["1) Que fait-on avant de manger ?"], ["2) Que dit-on à ceux qui mangent avec nous ?"], ["3) Que dit-on pour avoir encore du riz ?"], ["4) Que dit-on à la fin du repas ?"]] },
  app: { paras: [["R.A. : Je ", { t: "me lave les mains", r: true }, "."], ["R.A. : « ", { t: "Bon appétit !", r: true }, " »"], ["R.A. : « ", { t: "Encore, s'il te plaît.", r: true }, " »"], ["R.A. : « ", { t: "Merci, c'était très bon !", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « le repas »",
  },
  synthese: {
  ens: ["Donc : la politesse du repas — mains propres, bon appétit, s'il te plaît, merci."],
  app: ["Répètent les 4 formules en chœur en mimant chaque geste."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le repas imaginé : je distribue du riz imaginaire, chacun demande poliment et remercie."],
  app: ["Jouent : encore du riz, s'il te plaît ! — voilà ! — merci, c'est très bon !"],
  technique: ["Jeu de rôle"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : montre et dis les 4 moments polis du repas."],
  app: ["R.A. : ", { t: "se laver les mains, bon appétit, s'il te plaît, merci", r: true }, " (4 formules)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "88. BON APPÉTIT !",
  subs: [
   { t: "A. Les formules", paras: [["« ", { t: "Bon appétit !", k: true }, " » — « ", { t: "Encore, s'il te plaît.", k: true }, " » — « ", { t: "Merci, c'était très bon !", k: true }, " »"]] },
   { t: "B. Le geste propre", paras: [["Avant de manger : ", { t: "je me lave les mains", k: true }, " avec de l'eau propre et du savon."]] },
  ],
  retenir: ["Au repas : ", { t: "mains lavées, bon appétit, s'il te plaît, merci", k: true }, " — propre et poli !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les formules polies du repas :"], items: [["bon appétit"], ["donne vite"], ["s'il te plaît"], ["merci"], ["je me lave les mains"], ["enlève-toi"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Je me lave les ....... avant de manger. (mains)"], ["2) ....... appétit ! (Bon)"], ["3) Encore, s'il te ....... (plaît)"], ["4) ......., c'était très bon ! (Merci)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Mime et dis la formule (4 tours) :"], items: [["1) Mime n°1 : le lavage des mains (formule : .......)"], ["2) Mime n°2 : servir un camarade (formule : .......)"], ["3) Mime n°3 : demander encore (formule : .......)"], ["4) Mime n°4 : la fin du repas (formule : .......)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Entourés : ", { t: "bon appétit, s'il te plaît, merci, je me lave les mains", r: true }, " (2 pts chacun) — « donne vite » et « enlève-toi » : pas polis, non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "mains", r: true }, " — 2) ", { t: "Bon", r: true }, " — 3) ", { t: "plaît", r: true }, " — 4) ", { t: "Merci", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Mimes + formules justes : ", { t: "1,5 pt par tour", r: true }, "."]] },
  ],
 },
 {
  n: 89,
  titre: "La comptine des repas",
  titreFiche: "Je mange bien, je grandis",
  sd: "Expression Orale",
  objectif: "Réciter la comptine des repas en rythme.",
  supportFiche: "Comptine au tableau, image « le repas ».",
  revision: {
  ens: ["Dis les 4 formules polies du repas (chaîne parlée)."],
  app: ["R.A. : ", { t: "mains lavées, bon appétit, s'il te plaît, merci", r: true }, "."],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Qui aime les comptines ? Voici la comptine des repas de J-Learn : écoutez le rythme ! »"],
  app: ["Écoutent, tapent le rythme des mains."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons la comptine des repas : écoutez d'abord, puis répétez."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez la comptine : » Le matin, je bois du lait, / à midi, je mange du riz ; / le soir, une soupe et une banane — / bon appétit, je grandis !"],
  app: ["Écoutent en suivant sur le tableau."],
  technique: ["Modèle oral"],
  support: "Comptine au tableau",
  },
  analyse: {
  ens: { paras: [["1) Que bois-je le matin ?"], ["2) Que mange-je à midi ?"], ["3) Que mange-je le soir ?"], ["4) Comment finit la comptine ?"]] },
  app: { paras: [["R.A. : Du ", { t: "lait", r: true }, "."], ["R.A. : Du ", { t: "riz", r: true }, "."], ["R.A. : Une ", { t: "soupe et une banane", r: true }, "."], ["R.A. : « ", { t: "Bon appétit, je grandis !", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Comptine au tableau",
  },
  synthese: {
  ens: ["Donc : la comptine des repas — lait le matin, riz à midi, soupe le soir, je grandis !"],
  app: ["Répètent la comptine en chœur, deux fois, en tapant le rythme."],
  technique: ["Répétition collective"],
  support: "Comptine au tableau",
  },
  application: {
  ens: ["La comptine par groupe : chaque groupe récite une ligne, tous ensemble pour la fin."],
  app: ["Récitent en groupes puis en chœur."],
  technique: ["Récitation par groupes"],
  support: "Comptine au tableau",
  },
  evaluation: {
  ens: ["3 élèves : récite la comptine complète."],
  app: ["R.A. : comptine ", { t: "récitée sans oubli", r: true }, " (rythme régulier)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "89. LA COMPTINE DES REPAS",
  subs: [
   { t: "A. La comptine", paras: [["« ", { t: "Le matin, je bois du lait,", k: true }, " / ", { t: "à midi, je mange du riz ;", k: true }, " »"], ["« ", { t: "le soir, une soupe et une banane —", k: true }, " / ", { t: "bon appétit, je grandis !", k: true }, " »"]] },
  ],
  retenir: ["Ma comptine : « ", { t: "Bon appétit, je grandis !", k: true }, " » — et mes 3 repas bien ordonnés."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Remets les lignes de la comptine en ordre (1, 2, 3, 4) :"], items: [["bon appétit, je grandis ! (4)"], ["Le matin, je bois du lait, (1)"], ["le soir, une soupe et une banane — (3)"], ["à midi, je mange du riz ; (2)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète la comptine :"], items: [["1) Le matin, je bois du ....... (lait)"], ["2) à midi, je mange du ....... (riz)"], ["3) le soir, une ....... et une banane (soupe)"], ["4) bon appétit, je ....... (grandis)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Ajoute un vers : « à [moment], je mange... » (4 élèves) :"], items: [["1) Vers n°1 : ....... (réponse libre)"], ["2) Vers n°2 : ....... (réponse libre)"], ["3) Vers n°3 : ....... (réponse libre)"], ["4) Vers n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Ordre : ", { t: "Le matin, je bois du lait, → à midi, je mange du riz ; → le soir, une soupe et une banane — → bon appétit !", r: true }, " (2 pts par numéro)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "lait", r: true }, " — 2) ", { t: "riz", r: true }, " — 3) ", { t: "soupe", r: true }, " — 4) ", { t: "grandis", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Vers corrects (moment + aliment, rythme tenu) : ", { t: "1,5 pt par vers", r: true }, "."]] },
  ],
 },
 {
  n: 90,
  titre: "J'énumère mes repas",
  titreFiche: "Ma journée bien remplie",
  sd: "Expression Orale",
  objectif: "Énumérer : « Au petit-déjeuner, je mange..., ..., et... » (une liste de 3 aliments).",
  supportFiche: "Image « le repas », liste des 3 repas dessinée, tableau noir.",
  revision: {
  ens: ["Récite la comptine des repas avec ton voisin."],
  app: ["R.A. : « Le matin, je bois du lait... »"],
  technique: ["Répétition par deux"],
  },
  miseEnSituation: {
  ens: ["« Maman demande ce que tu veux manger aujourd'hui : comment tout dire d'un coup ? »"],
  app: ["Proposent : on dit tout ce qu'on veut, une liste..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous énumérons : « Au petit-déjeuner, je mange..., ..., et... »"],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Écoutez : » au petit-déjeuner, je mange du pain, une banane et un œuf — j'énumère avec ma voix qui continue."],
  app: ["Écoutent, répètent la liste complète."],
  technique: ["Modèle oral"],
  support: "Liste des 3 repas dessinée",
  },
  analyse: {
  ens: { paras: [["1) Quel repas est énuméré ?"], ["2) Combien d'aliments dans la liste ?"], ["3) Quel petit mot avant le dernier aliment ?"], ["4) Refais la liste dans l'ordre !"]] },
  app: { paras: [["R.A. : Le ", { t: "petit-déjeuner", r: true }, "."], ["R.A. : ", { t: "Trois", r: true }, "."], ["R.A. : ", { t: "Et", r: true }, "."], ["R.A. : ", { t: "du pain, une banane et un œuf", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Liste des 3 repas dessinée",
  },
  synthese: {
  ens: ["Donc : je commence par le moment — « au petit-déjeuner » — puis j'énumère avec et avant le dernier."],
  app: ["Répètent le modèle en chœur, puis chacun avec un autre repas."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu de la liste qui grandit : chacun ajoute un aliment en répétant la liste de son camarade."],
  app: ["Enchaînent : au déjeuner, je mange du riz et des brèdes ; ...et de la viande..."],
  technique: ["Jeu de mémoire enchaîné"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : énumère 3 aliments d'un repas de la journée."],
  app: ["R.A. : « ", { t: "À midi, je mange..., ..., et...", r: true }, " » (moment + 3 aliments)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "90. J'ÉNUMÈRE MES REPAS",
  subs: [
   { t: "A. Ma liste", paras: [["« ", { t: "Au petit-déjeuner, je mange du pain, une banane et un œuf.", k: true }, " »"]] },
   { t: "B. Le modèle", paras: [["« ", { t: "Au..., je mange..., ..., et...", k: true }, " » — le mot ", { t: "et", k: true }, " avant le dernier !"]] },
  ],
  retenir: ["Pour énumérer : ", { t: "« Au..., je mange..., ..., et... »", k: true }, " — et ma voix continue jusqu'au dernier aliment."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les aliments de la liste :"], items: [["du pain"], ["une banane"], ["le cahier"], ["un œuf"], ["du lait"], ["la lune"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète la liste avec et :"], items: [["1) Au petit-déjeuner, je mange du pain, du lait ....... un œuf."], ["2) À midi, je mange du riz, des brèdes ....... de la viande."], ["3) Le soir, je mange de la soupe, du pain ....... une banane."], ["4) Au goûter, je mange une goyave ....... une mangue."]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Fais ta liste pour un repas (4 élèves) :"], items: [["1) Liste n°1 (le matin) : ....... (réponse libre)"], ["2) Liste n°2 (à midi) : ....... (réponse libre)"], ["3) Liste n°3 (le soir) : ....... (réponse libre)"], ["4) Liste n°4 (au goûter) : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Entourés : ", { t: "du pain, une banane, un œuf, du lait", r: true }, " (2 pts chacun) — cahier (école) et lune (ciel) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "et", r: true }, " — 2) ", { t: "et", r: true }, " — 3) ", { t: "et", r: true }, " — 4) ", { t: "et", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Listes complètes (moment + 3 aliments) : ", { t: "1,5 pt par liste", r: true }, "."]] },
  ],
 },
 {
  n: 91,
  titre: "J'aime, je n'aime pas",
  titreFiche: "Dire mes goûts",
  sd: "Expression Orale",
  objectif: "Dire ses goûts poliment : « J'aime la banane. Je n'aime pas le citron. Et toi ? »",
  supportFiche: "Aliments réels ou image « le repas », tableau noir.",
  revision: {
  ens: ["Énumère tes aliments du déjeuner (chaîne parlée)."],
  app: ["R.A. : « À midi, je mange du riz, des brèdes et de la viande. »"],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Qui aime la soupe ? Qui n'aime pas le citron ? Chacun a ses goûts : comment le dire ? »"],
  app: ["Lèvent la main, proposent : j'aime / je n'aime pas..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous disons nos goûts : j'aime..., je n'aime pas..., et toi ?"],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » Fara aime la banane, elle ne dit rien du citron ; Koto n'aime pas le citron mais il aime le riz — chacun ses goûts, on le dit poliment."],
  app: ["Observent, répètent : j'aime..., je n'aime pas..."],
  technique: ["Observation guidée"],
  support: "Aliments réels ou image",
  },
  analyse: {
  ens: { paras: [["1) Comment dit-on qu'un aliment nous plaît ?"], ["2) Comment dit-on qu'un aliment ne nous plaît pas ?"], ["3) Quelle question pose-t-on à l'autre ?"], ["4) N'aime-t-on pas les mêmes aliments ?"]] },
  app: { paras: [["R.A. : « ", { t: "J'aime...", r: true }, " »"], ["R.A. : « ", { t: "Je n'aime pas...", r: true }, " »"], ["R.A. : « ", { t: "Et toi ?", r: true }, " »"], ["R.A. : ", { t: "Non, chacun ses goûts", r: true }, " — on respecte sans se moquer."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : mes goûts — « j'aime / je n'aime pas » + la question « et toi ? »"],
  app: ["Répètent le modèle en chœur avec 3 aliments."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu des goûts : par deux, chacun donne son goût puis pose la question."],
  app: ["Jouent : j'aime la goyave, je n'aime pas le citron, et toi ? — moi, j'aime..."],
  technique: ["Jeu de rôle par deux"],
  support: "Aliments réels",
  },
  evaluation: {
  ens: ["3 élèves : dis deux goûts (j'aime + je n'aime pas)."],
  app: ["R.A. : « ", { t: "J'aime la banane. Je n'aime pas le citron.", r: true }, " » (2 phrases)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "91. J'AIME, JE N'AIME PAS",
  subs: [
   { t: "A. Mes goûts", paras: [["« ", { t: "J'aime la banane.", k: true }, " » — « ", { t: "Je n'aime pas le citron.", k: true }, " »"]] },
   { t: "B. La question", paras: [["« ", { t: "Et toi ?", k: true }, " » — chacun ses goûts, on le dit poliment !"]] },
  ],
  retenir: ["Dire mes goûts : ", { t: "« J'aime... / Je n'aime pas... — Et toi ? »", k: true }],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les phrases qui disent un goût :"], items: [["J'aime le riz."], ["Le panier est plein."], ["Je n'aime pas le citron."], ["Et toi ?"], ["La soupe est chaude."], ["J'aime les brèdes."]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) J'....... la banane. (aime)"], ["2) Je n'....... pas le citron. (aime)"], ["3) J'aime le riz. ....... toi ? (Et)"], ["4) Chacun ses ....... (goûts)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Dis tes goûts et pose la question (4 élèves) :"], items: [["1) Élève n°1 : ....... (réponse libre)"], ["2) Élève n°2 : ....... (réponse libre)"], ["3) Élève n°3 : ....... (réponse libre)"], ["4) Élève n°4 : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Phrases-goûts entourées : ", { t: "J'aime le riz, Je n'aime pas le citron, J'aime les brèdes (et la question « Et toi ? »)", r: true }, " — panier et soupe chaude : descriptions, non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "aime", r: true }, " — 2) ", { t: "aime", r: true }, " — 3) ", { t: "Et", r: true }, " — 4) ", { t: "goûts", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Goûts + question posée : ", { t: "1,5 pt par élève", r: true }, "."]] },
  ],
 },
 {
  n: 92,
  titre: "Je sers la table",
  titreFiche: "La table est prête",
  sd: "Expression Orale",
  objectif: "Nommer les objets de la table : l'assiette, la cuillère, le verre, la fourchette, le bol, la nappe.",
  supportFiche: "Image « le repas », vaisselle réelle, tableau noir.",
  revision: {
  ens: ["Dis tes goûts avec « et toi ? » (2 élèves)."],
  app: ["R.A. : « J'aime... je n'aime pas... et toi ? »"],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Avant de manger, que pose-t-on sur la table ? Comptez ce qu'il y a chez vous ! »"],
  app: ["Proposent : des assiettes, des cuillères, des verres, des bols..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous apprenons les mots de la table : l'assiette, la cuillère, le verre, la fourchette, le bol, la nappe."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez la table et écoutez : » je pose la nappe, les assiettes, les cuillères, les verres, les bols — la table est prête !"],
  app: ["Observent et nomment chaque objet en le montrant."],
  technique: ["Observation guidée"],
  support: "Vaisselle réelle",
  },
  analyse: {
  ens: { paras: [["1) Avec quoi mange-t-on le riz ?"], ["2) Dans quoi boit-on l'eau ?"], ["3) Où pose-t-on le bol de riz ?"], ["4) Qu'est-ce qui couvre la table ?"]] },
  app: { paras: [["R.A. : Avec la ", { t: "cuillère", r: true }, "."], ["R.A. : Dans le ", { t: "verre", r: true }, "."], ["R.A. : Sur l'", { t: "assiette", r: true }, "."], ["R.A. : La ", { t: "nappe", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Vaisselle réelle",
  },
  synthese: {
  ens: ["Donc : la table — la nappe, l'assiette, la cuillère, le verre, la fourchette, le bol."],
  app: ["Répètent les 6 mots en chœur en mimant le geste d'installer la table."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu de la table : je nomme un objet, vous mimez son usage — la cuillère (on goûte), le verre (on boit)..."],
  app: ["Miment chaque objet à tour de rôle."],
  technique: ["Jeu de mimes"],
  support: "Vaisselle réelle",
  },
  evaluation: {
  ens: ["3 élèves : montre et nomme 3 objets de la table."],
  app: ["R.A. : ", { t: "l'assiette, la cuillère, le verre, la fourchette, le bol, la nappe", r: true }, " (3 mots corrects)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "92. JE SERS LA TABLE",
  subs: [
   { t: "A. Les objets", paras: [[{ t: "l'assiette", k: true }, " — ", { t: "la cuillère", k: true }, " — ", { t: "le verre", k: true }, " — ", { t: "la fourchette", k: true }, " — ", { t: "le bol", k: true }, " — ", { t: "la nappe", k: true }]] },
   { t: "B. Ma phrase", paras: [["« ", { t: "La table est prête : assiettes, cuillères et verres.", k: true }, " »"]] },
  ],
  retenir: ["Sur la table : ", { t: "la nappe, l'assiette, la cuillère, le verre, la fourchette, le bol", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les objets de la table :"], items: [["l'assiette"], ["le zébu"], ["la cuillère"], ["le verre"], ["le lapin"], ["la nappe"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Je mange le riz avec une ....... (cuillère)"], ["2) Je bois l'eau dans un ....... (verre)"], ["3) Le bol de riz est posé sur l'....... (assiette)"], ["4) La ....... couvre la table. (nappe)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Mime l'objet et dis son nom (4 tours) :"], items: [["1) Mime n°1 : ....... (réponse libre : la cuillère)"], ["2) Mime n°2 : ....... (réponse libre : le verre)"], ["3) Mime n°3 : ....... (réponse libre : la nappe)"], ["4) Mime n°4 : ....... (réponse libre : l'assiette)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Objets entourés : ", { t: "l'assiette, la cuillère, le verre, la nappe", r: true }, " (2 pts chacun) — zébu (ferme) et lapin (animal) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "cuillère", r: true }, " — 2) ", { t: "verre", r: true }, " — 3) ", { t: "assiette", r: true }, " — 4) ", { t: "nappe", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Mimes bien interprétés : ", { t: "1,5 pt par tour", r: true }, "."]] },
  ],
 },
 {
  n: 93,
  titre: "La cuisine de la maison",
  titreFiche: "Ça sent bon !",
  sd: "Expression Orale",
  objectif: "Décrire la cuisine : la marmite, le feu, la casserole, maman cuisine, ça sent bon !",
  supportFiche: "Image « la cuisine », tableau noir.",
  revision: {
  ens: ["Nomme 3 objets de la table (chaîne parlée)."],
  app: ["R.A. : ", { t: "l'assiette, la cuillère, le verre, la fourchette, le bol, la nappe", r: true }, "."],
  technique: ["Chaîne parlée"],
  },
  miseEnSituation: {
  ens: ["« Qui aide maman à cuisiner ? Que fait-elle d'abord ? Comment est le riz quand ça cuit ? »"],
  app: ["Proposent : elle lave le riz, elle allume le feu, ça sent bon..."],
  technique: ["Question ouverte"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous décrivons la cuisine : la marmite, le feu, et « ça sent bon ! »"],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image et écoutez : » dans la cuisine, maman allume le feu, elle met le riz dans la marmite, la casserole chante — ça sent bon !"],
  app: ["Observent, répètent : la marmite, le feu, la casserole, ça sent bon !"],
  technique: ["Observation guidée"],
  support: "Image « la cuisine »",
  },
  analyse: {
  ens: { paras: [["1) Dans quoi met-on le riz pour cuire ?"], ["2) Sur quoi pose-t-on la marmite ?"], ["3) Qui cuisine chez vous ?"], ["4) Que dit-on quand c'est bon à sentir ?"]] },
  app: { paras: [["R.A. : Dans la ", { t: "marmite", r: true }, "."], ["R.A. : Sur le ", { t: "feu", r: true }, "."], ["R.A. : ", { t: "Maman (ou papa, grand-mère...)", r: true }, " (réponse personnelle)."], ["R.A. : « ", { t: "Ça sent bon !", r: true }, " »"]] },
  technique: ["Question / réponse"],
  support: "Image « la cuisine »",
  },
  synthese: {
  ens: ["Donc : la cuisine — le feu, la marmite, la casserole, et « ça sent bon ! »"],
  app: ["Répètent les mots en chœur en mimant le remuage de la marmite."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Le jeu de la cuisine : je mime la cuisinière, vous décrivez — elle allume le feu, elle remue la marmite..."],
  app: ["Décrivent chaque geste : elle allume le feu, elle lave le riz, elle goûte la soupe..."],
  technique: ["Jeu de mimes"],
  support: "Tableau noir",
  },
  evaluation: {
  ens: ["3 élèves : décris la cuisine en 3 mots ou phrases."],
  app: ["R.A. : ", { t: "le feu, la marmite, la casserole — ça sent bon !", r: true }, " (3 éléments)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "93. LA CUISINE DE LA MAISON",
  subs: [
   { t: "A. Les mots", paras: [[{ t: "la cuisine", k: true }, " — ", { t: "le feu", k: true }, " — ", { t: "la marmite", k: true }, " — ", { t: "la casserole", k: true }]] },
   { t: "B. Mes phrases", paras: [["« ", { t: "Maman allume le feu et met le riz dans la marmite.", k: true }, " » — « ", { t: "Ça sent bon !", k: true }, " »"]] },
  ],
  retenir: ["Dans la cuisine : ", { t: "le feu, la marmite, la casserole", k: true }, " — et le compliment : ", { t: "« Ça sent bon ! »", k: true }],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les objets de la cuisine :"], items: [["la marmite"], ["l'assiette"], ["le feu"], ["la casserole"], ["le verre"], ["la cendre"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète :"], items: [["1) Maman met le riz dans la ....... (marmite)"], ["2) Elle allume le ....... (feu)"], ["3) La ....... chante sur le feu. (casserole)"], ["4) Ça ....... bon ! (sent)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Décris la cuisine de ta maison en 3 phrases (4 élèves) :"], items: [["1) Phrase n°1 : ....... (réponse libre)"], ["2) Phrase n°2 : ....... (réponse libre)"], ["3) Phrase n°3 : ....... (réponse libre)"], ["4) Ton compliment préféré : ....... (réponse libre)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Objets entourés : ", { t: "la marmite, le feu, la casserole", r: true }, " (2 pts chacun) — assiette et verre (table) non, cendre (mot piège) non."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "marmite", r: true }, " — 2) ", { t: "feu", r: true }, " — 3) ", { t: "casserole", r: true }, " — 4) ", { t: "sent", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Descriptions complètes : ", { t: "1,5 pt par élève", r: true }, "."]] },
  ],
 },
 {
  n: 94,
  titre: "Le son in",
  titreFiche: "J'entends in",
  sd: "Lecture",
  objectif: "Reconnaître et lire le son in : la main, le pain, le lapin, le vin, le jardin.",
  supportFiche: "Image « le son in », syllabes au tableau, ardoises.",
  revision: {
  ens: ["Décris la cuisine en 3 mots (2 élèves)."],
  app: ["R.A. : ", { t: "le feu, la marmite — ça sent bon !", r: true }, ""],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Écoutez : i-n, in ! La main ! Le pain ! Répétez ! »"],
  app: ["Répètent : in, in — la main, le pain !"],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons le son in : i-n font « in », comme dans la main et le pain."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez l'image et écoutez : » la MAIN, le PAIN, le LAPIN, le JARDIN. Entendez-vous in ?"],
  app: ["Observent, écoutent, répondent : oui, on entend in !"],
  technique: ["Observation guidée"],
  support: "Image « le son in »",
  },
  analyse: {
  ens: { paras: [["1) Avec quelles lettres écrit-on le son in ?"], ["2) Que dit i-n ensemble ?"], ["3) Cite un mot avec in."], ["4) Dans « jardin », où est in ?"]] },
  app: { paras: [["R.A. : Avec ", { t: "i et n", r: true }, "."], ["R.A. : ", { t: "in", r: true }, " !"], ["R.A. : ", { t: "la main, le pain, le lapin, le vin, le jardin", r: true }, " (réponse libre)."], ["R.A. : À la fin : ", { t: "jardin", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Image « le son in », syllabes au tableau",
  },
  synthese: {
  ens: ["Donc : le son in s'écrit i-n — la main, le pain, le lapin, le vin, le jardin."],
  app: ["Lisent les 5 mots en chœur, puis la phrase : je lave mes mains avant de manger le pain."],
  technique: ["Lecture collective"],
  support: "Syllabes au tableau",
  },
  application: {
  ens: ["Lecture flash : je montre un mot, vous lisez vite (main, pain, lapin, vin, jardin)."],
  app: ["Lisent vite, en chœur et individuellement."],
  technique: ["Lecture flash"],
  support: "Ardoises, mots au tableau",
  },
  evaluation: {
  ens: ["3 élèves : lis 3 mots avec in."],
  app: ["R.A. : ", { t: "la main, le pain, le lapin, le vin, le jardin", r: true }, " (3 mots lus correctement)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "94. LE SON IN",
  subs: [
   { t: "A. Le son", paras: [["Le son ", { t: "in", k: true }, " s'écrit avec ", { t: "deux lettres : i-n", k: true }, " — la voix passe par le nez !"]] },
   { t: "B. Les mots", paras: [[{ t: "la main", k: true }, " — ", { t: "le pain", k: true }, " — ", { t: "le lapin", k: true }, " — ", { t: "le vin", k: true }, " — ", { t: "le jardin", k: true }]] },
  ],
  retenir: ["Le son ", { t: "in", k: true }, " : ", { t: "la main, le pain, le lapin, le jardin", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son in :"], items: [["le pain"], ["le riz"], ["la main"], ["le verre"], ["le lapin"], ["le jardin"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec in :"], items: [["1) la ma... (main)"], ["2) le pa... (pain)"], ["3) le lapi... (lapin)"], ["4) le jard... (jardin)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis ta phrase avec in à haute voix (4 élèves) :"], items: [["1) Je me lave les mains. (lecture)"], ["2) Le lapin mange le pain. (lecture)"], ["3) Le jardin est joli. (lecture)"], ["4) Je mange du pain avec la main. (lecture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le pain, la main, le lapin, le jardin", r: true }, " (2 pts chacun) — le riz et le verre : pas de in."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "in", r: true }, " — 2) ", { t: "in", r: true }, " — 3) ", { t: "in", r: true }, " — 4) ", { t: "in", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Phrases lues sans hésitation : ", { t: "1,5 pt par phrase", r: true }, "."]] },
  ],
 },
 {
  n: 95,
  titre: "Le son g (g, gu)",
  titreFiche: "J'entends g",
  sd: "Lecture",
  objectif: "Reconnaître et lire le son g : le gâteau, la goyave, la guitare, la langue.",
  supportFiche: "Image « les repas », syllabes au tableau, ardoises.",
  revision: {
  ens: ["Lis : main, pain, lapin, jardin (lecture flash)."],
  app: ["Lisent : main, pain, lapin, jardin."],
  technique: ["Lecture flash"],
  },
  miseEnSituation: {
  ens: ["« Écoutez : g comme dans gâteau ! Et gu comme dans langue ! Répétez ! »"],
  app: ["Répètent : g, g — le gâteau, la langue !"],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons le son g : la lettre g, et g-u qui garde le son g devant e et i."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » le GÂTEAU, la GOYAVE, la GUITARE, la LANGUE. Entendez-vous g ?"],
  app: ["Observent, écoutent, répondent : oui, on entend g !"],
  technique: ["Observation guidée"],
  support: "Image « les repas », syllabes au tableau",
  },
  analyse: {
  ens: { paras: [["1) Comment s'appelle le son de gâteau ?"], ["2) Dans « langue », quelles lettres font le son g ?"], ["3) Cite un mot avec g."], ["4) Gâteau : où est le son g ?"]] },
  app: { paras: [["R.A. : Le son ", { t: "g", r: true }, "."], ["R.A. : Avec ", { t: "g-u", r: true }, "."], ["R.A. : ", { t: "le gâteau, la goyave, la guitare, la langue", r: true }, " (réponse libre)."], ["R.A. : Au début : ", { t: "gâteau", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Syllabes au tableau",
  },
  synthese: {
  ens: ["Donc : le son g — la lettre g (gâteau, goyave) et g-u (langue) qui garde le son g."],
  app: ["Lisent les 4 mots en chœur, puis individuellement."],
  technique: ["Lecture collective"],
  support: "Syllabes au tableau",
  },
  application: {
  ens: ["Le tri g/d : je dis un mot, vous montrez à droite si le son est g, à gauche sinon (gâteau, riz, langue, pain, goyave)."],
  app: ["Se déplacent : gâteau (g !), riz (d), langue (g !)..."],
  technique: ["Jeu de tri en mouvement"],
  support: "Ardoises",
  },
  evaluation: {
  ens: ["3 élèves : lis 3 mots avec g ou gu."],
  app: ["R.A. : ", { t: "le gâteau, la goyave, la guitare, la langue", r: true }, " (3 mots lus correctement)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "95. LE SON G (G, GU)",
  subs: [
   { t: "A. Le son", paras: [["Le son ", { t: "g", k: true }, " s'écrit ", { t: "g", k: true }, " (gâteau) ou ", { t: "g-u", k: true }, " devant e et i (langue)."]] },
   { t: "B. Les mots", paras: [[{ t: "le gâteau", k: true }, " — ", { t: "la goyave", k: true }, " — ", { t: "la guitare", k: true }, " — ", { t: "la langue", k: true }]] },
  ],
  retenir: ["Le son ", { t: "g", k: true }, " : ", { t: "gâteau, goyave, guitare, langue", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son g :"], items: [["le gâteau"], ["le riz"], ["la goyave"], ["la main"], ["la langue"], ["la guitare"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec g ou gu :"], items: [["1) le ...âteau (gâteau)"], ["2) la ...oyave (goyave)"], ["3) la lan...ue (langue)"], ["4) la ...uitare (guitare)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis tes 4 mots avec g à haute voix (4 élèves) :"], items: [["1) Mot n°1 : ....... (lecture)"], ["2) Mot n°2 : ....... (lecture)"], ["3) Mot n°3 : ....... (lecture)"], ["4) Mot n°4 : ....... (lecture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le gâteau, la goyave, la langue, la guitare", r: true }, " (2 pts chacun) — le riz et la main : pas de g."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "g", r: true }, " — 2) ", { t: "g", r: true }, " — 3) ", { t: "gu", r: true }, " — 4) ", { t: "gu", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Lectures correctes : ", { t: "1,5 pt par mot bien lu", r: true }, "."]] },
  ],
 },
 {
  n: 96,
  titre: "Le son k (k, c, qu)",
  titreFiche: "Trois écritures pour k",
  sd: "Lecture",
  objectif: "Reconnaître et lire le son k : le café, la carotte, le coq, le kilo, quatre.",
  supportFiche: "Image « le repas », syllabes au tableau, ardoises.",
  revision: {
  ens: ["Lis : gâteau, goyave, langue, guitare (lecture flash)."],
  app: ["Lisent : gâteau, goyave, langue, guitare."],
  technique: ["Lecture flash"],
  },
  miseEnSituation: {
  ens: ["« Écoutez : le café ! la carotte ! le coq ! Ces mots font le même son : k ! Répétez ! »"],
  app: ["Répètent : k, k — le café, la carotte, le coq !"],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous lisons le son k : il s'écrit k, c ou qu — trois écritures, un seul son !"],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Observez et écoutez : » le CAFÉ (c), le KILO (k), le COQ (qu), la CAROTTE (c). Entendez-vous k ?"],
  app: ["Observent, écoutent, répondent : oui, on entend k partout !"],
  technique: ["Observation guidée"],
  support: "Image « le repas », syllabes au tableau",
  },
  analyse: {
  ens: { paras: [["1) Comment s'écrit le k de kilo ?"], ["2) Comment s'écrit le k de café ?"], ["3) Comment s'écrit le k de coq ?"], ["4) Cite un mot avec le son k."]] },
  app: { paras: [["R.A. : Avec la lettre ", { t: "k", r: true }, "."], ["R.A. : Avec la lettre ", { t: "c", r: true }, "."], ["R.A. : Avec ", { t: "q-u", r: true }, "."], ["R.A. : ", { t: "le café, la carotte, le coq, le kilo, quatre", r: true }, " (réponse libre)."]] },
  technique: ["Question / réponse"],
  support: "Syllabes au tableau",
  },
  synthese: {
  ens: ["Donc : le son k s'écrit k (kilo), c (café) ou qu (coq) — trois écritures, un seul son."],
  app: ["Lisent les 5 mots en chœur, puis individuellement."],
  technique: ["Lecture collective"],
  support: "Syllabes au tableau",
  },
  application: {
  ens: ["Le jeu des trois familles : je montre un mot, vous dites si son k s'écrit k, c ou qu (kiwi, carotte, coq, kilo, café)."],
  app: ["Classent : kiwi (k), carotte (c), coq (qu), kilo (k), café (c)."],
  technique: ["Jeu de classement"],
  support: "Ardoises, mots au tableau",
  },
  evaluation: {
  ens: ["3 élèves : lis 3 mots avec k et dis son écriture."],
  app: ["R.A. : ", { t: "le café (c), le kilo (k), le coq (qu)", r: true }, " (3 mots lus + écritures)."],
  technique: ["Individuel oral"],
  },
  lecon: {
  titre: "96. LE SON K (K, C, QU)",
  subs: [
   { t: "A. Le son", paras: [["Le son ", { t: "k", k: true }, " s'écrit ", { t: "k", k: true }, " (kilo), ", { t: "c", k: true }, " (café) ou ", { t: "q-u", k: true }, " (coq) — trois écritures, un seul son !"]] },
   { t: "B. Les mots", paras: [[{ t: "le café", k: true }, " — ", { t: "la carotte", k: true }, " — ", { t: "le coq", k: true }, " — ", { t: "le kilo", k: true }, " — ", { t: "quatre", k: true }]] },
  ],
  retenir: ["Le son ", { t: "k", k: true }, " s'écrit ", { t: "k, c ou qu", k: true }, " : ", { t: "kilo, café, coq", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Entoure les mots qui contiennent le son k :"], items: [["le café"], ["le pain"], ["la carotte"], ["le coq"], ["la marmite"], ["le kilo"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Complète avec k, c ou qu :"], items: [["1) le ...ilo (kilo)"], ["2) le ...afé (café)"], ["3) le co... (coq)"], ["4) la ...arotte (carotte)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Lis ton mot et dis son écriture de k (4 élèves) :"], items: [["1) Mot n°1 : ....... (lecture + écriture)"], ["2) Mot n°2 : ....... (lecture + écriture)"], ["3) Mot n°3 : ....... (lecture + écriture)"], ["4) Mot n°4 : ....... (lecture + écriture)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Mots entourés : ", { t: "le café, la carotte, le coq, le kilo", r: true }, " (2 pts chacun) — le pain et la marmite : pas de k."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "k", r: true }, " — 2) ", { t: "c", r: true }, " — 3) ", { t: "q", r: true }, " — 4) ", { t: "c", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Lectures + écritures justes : ", { t: "1,5 pt par élève", r: true }, "."]] },
  ],
 },
 {
  n: 97,
  titre: "Écrire in",
  titreFiche: "J'écris in",
  sd: "Écriture",
  objectif: "Écrire proprement des mots avec in : main, pain, lapin, jardin.",
  supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
  revision: {
  ens: ["Lis : main, pain, lapin, vin, jardin (lecture collective)."],
  app: ["Lisent les 5 mots avec in."],
  technique: ["Lecture collective"],
  },
  miseEnSituation: {
  ens: ["« Nous savons lire in ; maintenant nous allons l'écrire : d'abord le i avec son point, puis le n avec ses deux bosses. »"],
  app: ["Tracent in dans l'air avec le doigt."],
  technique: ["Tracé dans l'air"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous écrivons in : le i pointu, le n à deux bosses — collés ensemble !"],
  app: ["Écoutent et observent le modèle au tableau."],
  technique: ["Annonce orale"],
  support: "Lignes d'écriture au tableau",
  },
  observation: {
  ens: ["« Observez mon tracé : » j'écris in trois fois — le i droit avec son point, le n qui monte et descend deux fois."],
  app: ["Observent les lettres, disent : i pointu, n à deux bosses !"],
  technique: ["Modèle d'écriture"],
  support: "Tableau noir",
  },
  analyse: {
  ens: { paras: [["1) Quelles lettres pour in ?"], ["2) Que met-on au-dessus du i ?"], ["3) Épelle « pain »."], ["4) Épelle « jardin »."]] },
  app: { paras: [["R.A. : ", { t: "i et n", r: true }, "."], ["R.A. : Son ", { t: "point", r: true }, "."], ["R.A. : ", { t: "p-a-i-n", r: true }, "."], ["R.A. : ", { t: "j-a-r-d-i-n", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : in = i pointu + n à deux bosses ; j'écris main, pain, lapin, jardin."],
  app: ["Écrivent in deux fois sur l'ardoise avant le cahier."],
  technique: ["Écriture guidée"],
  support: "Ardoises",
  },
  application: {
  ens: ["Au cahier : écris in, main, pain, lapin, jardin — beaux i pointés et n bien bossus."],
  app: ["Écrivent les 5 mots sur leurs cahiers."],
  technique: ["Copie individuelle"],
  support: "Cahiers",
  },
  evaluation: {
  ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
  app: ["R.A. : ", { t: "main, pain, lapin, jardin", r: true }, " écrits sans faute (points sur les i)."],
  technique: ["Vérification des cahiers"],
  },
  lecon: {
  titre: "97. ÉCRIRE IN",
  subs: [
   { t: "A. Les lettres", paras: [["Le son ", { t: "in", k: true }, " : ", { t: "i avec son point", k: true }, " + ", { t: "n à deux bosses", k: true }, " — pas d'espace entre les deux !"]] },
   { t: "B. Mes mots", paras: [[{ t: "la main", k: true }, " — ", { t: "le pain", k: true }, " — ", { t: "le lapin", k: true }, " — ", { t: "le jardin", k: true }]] },
  ],
  retenir: ["J'écris ", { t: "i-n", k: true }, " ensemble : ", { t: "main, pain, lapin, jardin", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Écris in deux fois sur l'ardoise :"], items: [["1) in n°1 (tracé)"], ["2) in n°2 (tracé)"], ["3) i avec son point (1 pt)"], ["4) n à deux bosses (1 pt)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) main (copie)"], ["2) pain (copie)"], ["3) lapin (copie)"], ["4) jardin (copie)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Complète en écrivant in :"], items: [["1) la ma... (main)"], ["2) le pa... (pain)"], ["3) le lapi... (lapin)"], ["4) le jard... (jardin)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "i pointé, n à deux bosses", r: true }, " (2 pts par in réussi)."]] },
  { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["1) ", { t: "in", r: true }, " — 2) ", { t: "in", r: true }, " — 3) ", { t: "in", r: true }, " — 4) ", { t: "in", r: true }, " (1,5 pt par mot complété)."]] },
  ],
 },
 {
  n: 98,
  titre: "Écrire g et k",
  titreFiche: "J'écris g et k",
  sd: "Écriture",
  objectif: "Écrire proprement des mots avec g (gâteau) et k (café, kilo).",
  supportFiche: "Lignes d'écriture au tableau, cahiers, ardoises.",
  revision: {
  ens: ["Épelle pain et jardin (2 élèves)."],
  app: ["R.A. : ", { t: "p-a-i-n", r: true }, " ; ", { t: "j-a-r-d-i-n", r: true }, "."],
  technique: ["Individuel oral"],
  },
  miseEnSituation: {
  ens: ["« Nous écrivons le g : une boucle et une queue qui descend sous la ligne — et le k : une canne et deux jambes ! »"],
  app: ["Tracent g et k dans l'air avec le doigt."],
  technique: ["Tracé dans l'air"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, nous écrivons g et k : le g descend sous la ligne, le k a une canne et deux jambes."],
  app: ["Écoutent et observent le modèle au tableau."],
  technique: ["Annonce orale"],
  support: "Lignes d'écriture au tableau",
  },
  observation: {
  ens: ["« Observez mon tracé : » j'écris g trois fois — la boucle et la queue sous la ligne ; puis k — la canne droite et deux jambes qui touchent."],
  app: ["Observent les lettres, disent : g avec sa queue, k avec sa canne !"],
  technique: ["Modèle d'écriture"],
  support: "Tableau noir",
  },
  analyse: {
  ens: { paras: [["1) Le g : où va sa queue ?"], ["2) Le k : combien de jambes ?"], ["3) Épelle « gâteau »."], ["4) Épelle « café »."]] },
  app: { paras: [["R.A. : ", { t: "Sous la ligne", r: true }, "."], ["R.A. : ", { t: "Deux", r: true }, "."], ["R.A. : ", { t: "g-â-t-e-a-u", r: true }, "."], ["R.A. : ", { t: "c-a-f-é", r: true }, "."]] },
  technique: ["Question / réponse"],
  support: "Tableau noir",
  },
  synthese: {
  ens: ["Donc : j'écris g (queue sous la ligne) et k (canne et deux jambes) — gâteau, goyave, café, kilo."],
  app: ["Écrivent g et k deux fois sur l'ardoise avant le cahier."],
  technique: ["Écriture guidée"],
  support: "Ardoises",
  },
  application: {
  ens: ["Au cahier : écris gâteau, goyave, café, kilo — belles queues de g sous la ligne."],
  app: ["Écrivent les 4 mots sur leurs cahiers."],
  technique: ["Copie individuelle"],
  support: "Cahiers",
  },
  evaluation: {
  ens: ["3 cahiers : les mots sont-ils propres et bien orthographiés ?"],
  app: ["R.A. : ", { t: "gâteau, goyave, café, kilo", r: true }, " écrits sans faute (queues de g sous la ligne)."],
  technique: ["Vérification des cahiers"],
  },
  lecon: {
  titre: "98. ÉCRIRE G ET K",
  subs: [
   { t: "A. Les lettres", paras: [["Le ", { t: "g", k: true }, " : une boucle et une ", { t: "queue sous la ligne", k: true }, " — le ", { t: "k", k: true }, " : une canne et ", { t: "deux jambes", k: true }, "."]] },
   { t: "B. Mes mots", paras: [[{ t: "le gâteau", k: true }, " — ", { t: "la goyave", k: true }, " — ", { t: "le café", k: true }, " — ", { t: "le kilo", k: true }]] },
  ],
  retenir: ["J'écris ", { t: "g et k", k: true }, " proprement : ", { t: "gâteau, goyave, café, kilo", k: true }, "."],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Écris g et k sur l'ardoise :"], items: [["1) g n°1 (tracé)"], ["2) k n°1 (tracé)"], ["3) g avec sa queue sous la ligne (1 pt)"], ["4) k avec sa canne (1 pt)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Écris au cahier :"], items: [["1) gâteau (copie)"], ["2) goyave (copie)"], ["3) café (copie)"], ["4) kilo (copie)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Complète :"], items: [["1) le ...âteau (gâteau)"], ["2) la ...oyave (goyave)"], ["3) le ...afé (café)"], ["4) le ...ilo (kilo)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Tracés propres : ", { t: "queue de g sous la ligne, canne de k", r: true }, " (2 pts par lettre réussie)."]] },
  { titre: "Exercice 2", lines: [["Mots copiés sans faute : ", { t: "1,5 pt par mot", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["1) ", { t: "g", r: true }, " — 2) ", { t: "g", r: true }, " — 3) ", { t: "c", r: true }, " — 4) ", { t: "k", r: true }, " (1,5 pt par mot complété)."]] },
  ],
 },
 {
  n: 99,
  titre: "Dictée et bilan de l'unité 7",
  titreFiche: "Le grand bilan des repas",
  sd: "Écriture",
  objectif: "Écrire sous la dictée (in, g, k) et faire le bilan des repas.",
  supportFiche: "Image « le repas », tableau noir, cahiers.",
  revision: {
  ens: ["Relis : main, gâteau, café (lecture collective)."],
  app: ["Relisent et épellent in, g, k."],
  technique: ["Lecture collective"],
  },
  miseEnSituation: {
  ens: ["« Voici le grand bilan des repas : la dictée des sons in, g, k, et tout ce que nous avons appris ! »"],
  app: ["Écoutent, se rappellent les séances."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  presentation: {
  ens: ["Aujourd'hui, la dictée bilan puis le grand bilan : les repas, la politesse, les sons in, g, k."],
  app: ["Écoutent."],
  technique: ["Annonce orale"],
  support: "Tableau noir",
  },
  observation: {
  ens: ["« Relisez les modèles avant la dictée : » main, pain, gâteau, goyave, café, kilo."],
  app: ["Relisent chaque mot, épellent in, g, k."],
  technique: ["Relecture guidée"],
  support: "Tableau noir",
  },
  analyse: {
  ens: { paras: [["1) Cite 3 repas ou aliments."], ["2) Que dit-on avant de manger ?"], ["3) Joue : « Qu'est-ce que tu manges ? — Je mange... »"], ["4) Cite un mot avec in, un avec g, un avec k."]] },
  app: { paras: [["R.A. : ", { t: "riz, brèdes, soupe, pain...", r: true }, " (3 mots)."], ["R.A. : « ", { t: "Bon appétit !", r: true }, " » (+ mains lavées)."], ["R.A. : « ", { t: "Qu'est-ce que tu manges ? — Je mange du riz.", r: true }, " »"], ["R.A. : ", { t: "pain / gâteau / café", r: true }, " (3 mots avec les sons)."]] },
  technique: ["Question / réponse"],
  support: "Image « le repas »",
  },
  synthese: {
  ens: ["Donc : les repas — les aliments, les moments, la politesse, la table, la cuisine, et les sons in, g, k."],
  app: ["Récitent la comptine des repas une dernière fois en chœur."],
  technique: ["Répétition collective"],
  support: "Tableau noir",
  },
  application: {
  ens: ["Dictée : pain, gâteau, café — puis la phrase : je lave mes mains avant de manger."],
  app: ["Écrivent sous la dictée, mot par mot, puis la phrase."],
  technique: ["Dictée"],
  support: "Cahiers de dictée",
  },
  evaluation: {
  ens: ["Correction collective au tableau, puis 3 cahiers vérifiés."],
  app: ["Corrigent avec le modèle : ", { t: "pain, gâteau, café + la phrase", r: true }, "."],
  technique: ["Correction collective"],
  },
  lecon: {
  titre: "99. DICTÉE ET BILAN DE L'UNITÉ 7",
  subs: [
   { t: "A. La dictée", paras: [["Mots : ", { t: "pain, gâteau, café", k: true }, " — phrase : ", { t: "je lave mes mains avant de manger", k: true }, "."]] },
   { t: "B. Bilan de l'unité", paras: [[{ t: "Les repas", k: true }, " (aliments, moments, politesse, table) + les sons ", { t: "in, g, k", k: true }, " : tout est appris !"]] },
  ],
  retenir: ["Unité 7 réussie : ", { t: "les repas malgaches, la politesse du repas et les sons in, g, k", k: true }, " !"],
  },
  exercices: [
  { titre: "Exercice 1", pts: 8, consigne: ["Dictée bilan :"], items: [["1) pain (dictée)"], ["2) gâteau (dictée)"], ["3) café (dictée)"], ["4) je lave mes mains avant de manger (dictée)"]] },
  { titre: "Exercice 2", pts: 6, consigne: ["Classe les sons (in, g ou k) :"], items: [["1) la ma... : ....... (in)"], ["2) le ...âteau : ....... (g)"], ["3) le ...ilo : ....... (k)"], ["4) le lapi... : ....... (in)"]] },
  { titre: "Exercice 3", pts: 6, consigne: ["Présente « mon repas préféré » en 3 phrases (4 élèves) :"], items: [["1) Je mange ....... (réponse libre)"], ["2) Je bois ....... (réponse libre)"], ["3) J'aime / Je n'aime pas ....... (réponse libre)"], ["4) Bon appétit ....... (réponse libre : et merci !)"]] },
  ],
  corrige: [
  { titre: "Exercice 1", lines: [["Dictée exacte : ", { t: "pain, gâteau, café", r: true }, " (2 pts chacun) + phrase complète (2 pts)."]] },
  { titre: "Exercice 2", lines: [["1) ", { t: "in", r: true }, " — 2) ", { t: "g", r: true }, " — 3) ", { t: "k", r: true }, " — 4) ", { t: "in", r: true }, "."]] },
  { titre: "Exercice 3", lines: [["Présentations complètes (3 phrases) : ", { t: "1,5 pt par élève", r: true }, "."]] },
  ],
 },
 ],
};

module.exports = { theme7 };
