/* UNITÉ 4 — GÉOMÉTRIE (13 séances / 11 leçons + révision + examen).
   RAS PE (TABLE) : figures usuelles ; triangles particuliers (illustration, construction) ;
   droite graduée + repère orthogonal ; angles et sécante ; droites remarquables
   (médiatrices → cercle circonscrit, médianes → centre de gravité,
    hauteurs → orthocentre, bissectrices → cercle inscrit). */
const {title,p,trace,correction,figCaption,prep,revisionSec,examSec,loadScene,buildDoc} = require('./lib');
const N = n => 'assets/math-t7/figs/t7u4s'+n+'.png';
const U = {num:'IV', title:'Géométrie', fiche:'fiche-t7-u4.html',
    desc:'figures usuelles, triangles, repérage, angles, droites remarquables',
    notePE:'Conforme au PE T7 (Géométrie).'};
const L = [];

/* ---------- Séance 1 / Leçon 1 ---------- */
L.push({tag:'L1',
 obj:'Savoir nommer un triangle par ses sommets ; illustrer les trois familles de triangles particuliers avant de les construire.',
 ras:['Identifier des triangles particuliers et les illustrer'],
 prereq:'Lignes, segments et vocabulaire de base du dessin géométrique (classe précédente).',
 minutes:['10 min — Observation et questions','20 min — Notions','15 min — Exercices','5 min — Synthèse'],
 got:'Maîtrise des noms rectangle, isocèle, équilatéral ; lecture des marques d’égalité sur un dessin.',
 scene:'t7_scene_u4_mur',
 teaser:'Avec un angle droit, deux côtés égaux ou trois côtés égaux, un triangle gagne un nom particulier.',
 bul:[
 'Un triangle se nomme par ses trois sommets, écrits en majuscules : le triangle ABC.',
 'Triangle rectangle : un angle droit (90°) ; le côté devant cet angle, l’hypoténuse, est le plus long.',
 'Triangle isocèle : deux côtés égaux, et deux angles égaux face à ces côtés.',
 'Triangle équilatéral : trois côtés égaux, trois angles de 60° chacun.',
 'Sur un dessin, les marques d’égalité (petits traits, petits arcs) signalent les mesures égales.',
 'L’angle droit se marque d’un petit carré tracé au sommet.',
 'À l’oral : nommer ces figures d’après les marques visibles au tableau.',
 ],
 trace:trace(
  '<> a trois côtés et trois <>.',3,
  'On peut toujours <>, même sans connaître les angles.',
  'Rectangle : <> et son côté (le plus long) <> ; isocèle : <> et <> à la base ; équilatéral : <> et <> mesurant 60°.',
  'Sur la figure, les <> partagés se lisent par des marques identiques.',
  'Un triangle peut être à la fois rectangle et isocèle ; il n’est jamais contradictoire de posséder deux qualités.' ,
  P=>figCaption(N('1_trois'),'Fig. 1 — Les trois familles de triangles particuliers.',P),
  P=>figCaption(N('1_vocab'),'Fig. 2 — Sommets, côtés et angles d’un triangle.',P),
  P=>figCaption(N('1_valide'),'Fig. 3 — Marquer les égalités sur un triangle.',P)),
 exo:['Entourer le nom complet du triangle dont les sommets sont A, B, C.',
   'Compléter : un triangle rectangle a exactement ______ angle droit.',
   'Faire entraîner oralement : donner la liste des noms des figures portant trois côtés.',
   'Valider ou corriger : « le triangle isocèle contient deux côtés égaux ».',
   'Valider ou corriger : « rectangle » se prononce « rectangle », et son long côté s’appelle hypoténuse.'],
 corr:[correction('1','✓ le triangle ABC','On cite les trois sommets en majuscules : le triangle ABC.'),
   correction('2','un','Un triangle rectangle contient exactement un angle droit.'),
   correction('3','triangle rectangle, isocèle, équilatéral','Les trois noms à retenir, dans l’ordre voulu.'),
   correction('4','validation','Vrai : deux côtés égaux, et deux angles égaux en face.'),
   correction('5','validation','Vrai sur les deux points.')]});

/* ---------- Séance 2 / Leçon 2 ---------- */
L.push({tag:'L2',
 obj:'Construire les trois triangles particuliers avec la règle et le compas, à partir des propriétés vues à la leçon 1.',
 ras:['Construire les triangles particuliers (règle, compas)'],
 prereq:'Leçon 1 — familles de triangles particuliers.',
 minutes:['10 min — Rappel des marques d’égalité','20 min — Constructions guidées','15 min — Constructions autonomes','5 min — Synthèse'],
 got:'Savoir livrer les trois constructions et les justifier par les propriétés.',
 scene:'t7_scene_u4_pirogue',
 teaser:'Avec une règle et une équerre comme avec un compas ouvert à l’écart voulu, chaque triangle se construit pas à pas.',
 bul:[
 'Triangle rectangle : tracer un angle droit à l’équerre, placer les sommets sur les côtés, joindre le dernier segment.',
 'Triangle isocèle : tracer la base, reporter au compas une même longueur depuis chaque extrémité ; les arcs se croisent.',
 'Triangle équilatéral : tracer un segment, reporter sa longueur au compas depuis les deux sommets ; les arcs se croisent.',
 'Finir chaque construction en marquant les égalités.',
 'À l’oral : expliquer ce qu’assure chaque étape (angle droit, longueur égale).',
 ],
 trace:trace(
  'Construire, c’est matérialiser les propriétés : <> pour le rectangle, <> pour l’isocèle, <> pour l’équilatéral.',3,
  'La vérification se fait à la règle et à l’équerre une fois le dessin terminé.',
  P=>figCaption(N('2_rect'),'Fig. 1 — Construire un triangle rectangle en trois gestes.',P),
  P=>figCaption(N('2_iso'),'Fig. 2 — Construire un triangle isocèle au compas.',P),
  P=>figCaption(N('2_equi'),'Fig. 3 — Construire un triangle équilatéral au compas.',P)),
 exo:['Construction : ABC rectangle en A, AB = 4 cm, AC = 3 cm.',
   'Construction : DEF isocèle en E, base DF = 5 cm, DE = EF = 4 cm.',
   'Construction : GHI équilatéral, GH = 6 cm.',
   'Question orale : comment vérifier le triangle rectangle produit à la question 1 ?',
   'Compléter : dans un triangle équilatéral, l’angle de chaque sommet vaut ______.'],
 corr:[correction('1','construction réalisée : deux tracés perpendiculaires','Matériaux : équerre et règle ; joindre [BC] à la fin ; ABC est rectangle en A.'),
   correction('2','arcs tracés de rayon 4 cm','Piquer le compas en D puis en F, rayon 4 cm ; le croisement donne E.'),
   correction('3','arcs tracés de rayon 6 cm','Rayon égal à GH depuis G puis H ; croisement = dernier sommet.'),
   correction('4','à l’équerre vérifiée en A + règle sur les mesures','Le contrôle des deux appareils ferme la preuve.'),
   correction('5','60°','Trois angles égaux, 180° ÷ 3 = 60°.')]});

/* ---------- Séance 3 / Leçon 3 ---------- */
L.push({tag:'L3 ex.',
 obj:'Se repérer sur une droite graduée : voir l’origine, l’unité, les nombres positifs et négatifs ; placer un point d’abscisse donnée.',
 ras:['Se repérer sur une droite graduée'],
 prereq:'Comptage positif et négatif ; sens de la lecture habituelle.',
 minutes:['10 min — Découverte de la ligne','20 min — Lecture et placement','15 min — Exercices','5 min — Synthèse'],
 got:'Placement correct d’abscisses entières et décimales simples ; notions d’origine et d’unité acquises.',
 scene:'t7_scene_u4_jete',
 teaser:'Une ligne graduée comme une jetée : une origine, des pas identiques, des départs en signe.',
 bul:[
 'Une droite graduée porte une origine O (zéro) et une unité (le pas) ; les nombres rangés dans le sens croissant.',
 'À droite de O : les positifs (+) ; à gauche : les négatifs (−).',
 'L’abscisse d’un point, c’est le nombre qui porte son nom : M (+2), P (−3).',
 'Placer un nombre : partir de O, choisir le côté selon le signe, avancer la valeur.',
 'Entre deux graduations, les parties se comptent : −1,5 vit au milieu de −1 et −2.',
 ],
 trace:trace(
  'Sur une droite graduée : <>, <> ; les nombres positifs à <>, les négatifs à <>.',
  'L’abscisse d’un point est le nombre qui le repère : A(−2), B(+1).',
  'On place un nombre en pensant : <> puis <>.',
  P=>figCaption(N('3_adj'),'Fig. 1 — Origine, unité et points placés.',P),
  P=>figCaption(N('3_placer'),'Fig. 2 — Placer un nombre décimal entre deux graduations.',P),
  P=>figCaption(N('3_marche'),'Fig. 3 — Avancer de 4 pas depuis −3.',P)),
 exo:['Sur une droite graduée d’origine O : placer les points A(+3), B(−4), C(+1), D(−2,5).',
   'Lire sur votre droite : l’abscisse du point placé à trois pas à droite de O.',
   'Le point E se déplace de −3 vers +1 : combien de pas dans le sens du compte ?',
   'Compléter : l’abscisse de l’origine vaut ______.',
   'Oral : ranger du plus petit au plus grand : +2, −4, 0, −1,5.'],
 corr:[correction('1','traces placées selon le signe','+3 : 3 pas à droite ; −4 : 4 pas à gauche ; +1 : 1 pas à droite ; −2,5 : au milieu de −2 et −3.'),
   correction('2','+3','Trois pas à droite de l’origine : abscisse +3.'),
   correction('3','4 pas','Le trajet −3 → +1 compte 4 pas vers la droite.'),
   correction('4','0','L’origine porte l’abscisse 0 par définition.'),
   correction('5','−4 < −1,5 < 0 < +2','Ordre du plus petit au plus grand.')]});

/* ---------- Séance 4 / Leçon 4 ---------- */
L.push({tag:'L4 ex.',
 obj:'Se repérer dans un repère orthogonal : abscisse puis ordonnée ; placer un point à coordonnées données (cas positifs).',
 ras:['Se repérer dans un repère orthogonal'],
 prereq:'Leçon 3 — droite graduée.',
 minutes:['10 min — Deux droites croisées','20 min — Lecture des coordonnées','15 min — Exercices','5 min — Synthèse'],
 got:'Écrire les coordonnées dans le bon ordre ; placer un point sans hésiter.',
 scene:'t7_scene_u4_carte',
 teaser:'Deux lignes croisées comme sur une carte : l’abscisse sur le chemin large, l’ordonnée vers le haut.',
 bul:[
 'Un repère orthogonal croise deux droites graduées à angle droit, qui partagent l’origine O.',
 'L’axe horizontal (Ox) donne l’abscisse ; l’axe vertical (Oy) donne l’ordonnée.',
 'Un point se nomme M (x ; y) : abscisse d’abord, ordonnée ensuite.',
 'Pour lire : poser une règle verticale vers (Ox), puis horizontale vers (Oy).',
 'Pour placer : tracer le guide vertical de l’abscisse, le guide horizontal de l’ordonnée ; le point vit au croisement.',
 ],
 trace:trace(
  'Repère orthogonal : <> graduées et perpendiculaires, même origine O.',
  'M (x ; y) : x = <> sur (Ox), y = <> sur (Oy), dans cet ordre.',
  'Lecture et placement passent par les <>.',
  P=>figCaption(N('4_repere'),'Fig. 1 — Le repère orthogonal et le point M (3 ; 2).',P),
  P=>figCaption(N('4_lire'),'Fig. 2 — Lire les coordonnées des points A, B, C.',P),
  P=>figCaption(N('4_placer'),'Fig. 3 — Placer N (4 ; 2) avec les guides.',P)),
 exo:['Dans un repère orthogonal : lire les coordonnées des points donnés par l’enseignant (croix au tableau).',
   'Placer P(2 ; 3), Q(5 ; 1), R(0 ; 4).',
   'Donner la différence entre (2 ; 5) et (5 ; 2) en une phrase.',
   'Compléter : le premier nombre d’un couple est l’______.',
   'Placer S d’abscisse 3 et d’ordonnée 0 : où se trouve-t-il ?'],
 corr:[correction('1','lecture des couples selon les croix','Abscisse en premier, ordonnée ensuite, séparées par un point-virgule.'),
   correction('2','guides tracés puis points posés','Vertical x = 2 et horizontal y = 3 pour P, etc.'),
   correction('3','points différents','(2 ; 5) monte à 5 au-dessus de x = 2 ; (5 ; 2) s’arrête à 2 au-dessus de x = 5 : ce ne sont pas les mêmes points.'),
   correction('4','abscisse','Le couple s’écrit (abscisse ; ordonnée).'),
   correction('5','sur l’axe (Ox), à 3 pas de O','L’ordonnée nulle place le point sur l’axe horizontal.')]});

/* ---------- Séance 5 / Leçon 5 ---------- */
L.push({tag:'L5 ex.',
 obj:'Nommer et reconnaître les sortes d’angles ; ordonner selon l’ouverture ; mesurer au rapporteur en degrés.',
 ras:['Connaître les sortes d’angles','Mesurer au rapporteur'],
 prereq:'Angle droit déjà rencontré ; équerre.',
 minutes:['10 min — Ouvertures autour du sommet','20 min — Les noms et les repères','15 min — Exercices','5 min — Synthèse'],
 got:'Noms retenus avec les bornes (0°, 90°, 180°, 360°) ; rangement correct d’angles dessinés.',
 scene:'t7_scene_u4_voile',
 teaser:'Le rapporteur comme une voile tendue : un sommet, deux côtés, une ouverture qui a un nom.',
 bul:[
 'Un angle a un sommet et deux côtés ; on note xÔy l’angle de sommet O.',
 'nul 0° ; aigu : entre 0° et 90° ; droit : exactement 90° ; obtus : entre 90° et 180°.',
 'plat : 180° (ligne droite) ; rentrant : entre 180° et 360° ; plein : 360° (tour complet).',
 'Unité : le degré (°) ; appareil : le rapporteur.',
 'Pour ranger des angles, on compare d’abord au droit puis au plat.',
 ],
 trace:trace(
  'Un angle : <>, deux <>, mesuré en <>.',
  'Table des noms : <> < <>, l’angle droit = 90°, le plat = 180°, le plein = 360°.',
  'Le rentrant dépasse le <> mais reste sous le <>.',
  P=>figCaption(N('5_occ'),'Fig. 1 — Aigu, obtus, rentrant : les trois ouvertures.',P),
  P=>figCaption(N('5_24'),'Fig. 2 — Les quatre angles de référence.',P),
  P=>figCaption(N('5_mesure'),'Fig. 3 — Mesurer 40° au rapporteur.',P)),
 exo:['Dessiner puis nommer : un angle de 30°, un angle de 120°, un angle droit.',
   'Ranger par grandeur croissante : 45°, 170°, 90°, 5°.',
   'Choisir la famille de chaque angle : 80° / 95° / 180°.',
   'Compléter : l’angle plein vaut ______°.',
   'Oral : donner un objet de la classe montrant un angle droit, un angle aigu.'],
 corr:[correction('1','tracés d’ouvertures cohérentes','30° < 90° : aigu ; 120° > 90° : obtus ; le droit se vérifie à l’équerre.'),
   correction('2','5° < 45° < 90° < 170°','Aigu, aigu, droit, obtus : dans l’ordre croissant.'),
   correction('3','aigu / obtus / plat','80° sous le droit ; 95° entre droit et plat ; 180° exactement la ligne droite.'),
   correction('4','360','Le tour complet compte 360°.'),
   correction('5','angles de table, pages ouvertes…','Le droit se contrôle à l’équerre posée.')]});

/* ---------- Séance 6 / Leçon 6 ---------- */
L.push({tag:'L6 ex.',
 obj:'Relier les angles entre eux : complémentaires (90°), supplémentaires (180°), opposés par le sommet (égaux).',
 ras:['Connaître les couples d’angles'],
 prereq:'Leçon 5 — familles d’angles ; début de calcul sur les degrés.',
 minutes:['10 min — Deux angles qui se rejoignent','20 min — Les trois couples','15 min — Calculs','5 min — Synthèse'],
 got:'Savoir nommer le couple et livrer le calcul associé (90 ou 180).',
 scene:'t7_scene_u4_barque',
 teaser:'Deux angles qui se complètent comme deux quais tournés l’un vers l’autre, ou le double du même au carrefour.',
 bul:[
 'Complémentaires : deux angles dont la somme vaut exactement 90°.',
 'Supplémentaires : deux angles dont la somme vaut exactement 180°.',
 'Adjacent + supplémentaire : les deux angles occupent ensemble une ligne droite.',
 'Deux droites qui se croisent forment des angles opposés par le sommet : ils sont égaux.',
 'Vérifier toujours le total : 90° ou 180° selon le couple.',
 ],
 trace:trace(
  '<> : somme 90° ; <> : somme 180° ; <> : angles égaux.',
  'Avec deux droites sécantes, la somme des quatre angles formés vaut <>.',
  'L’angle opposé d’un angle de 40° mesure <>.',
  P=>figCaption(N('6_90'),'Fig. 1 — Complémentaires : 35° + 55° = 90°.',P),
  P=>figCaption(N('6_180'),'Fig. 2 — Supplémentaires : 70° + 110° = 180°.',P),
  P=>figCaption(N('6_opp'),'Fig. 3 — Opposés par le sommet.',P)),
 exo:['Angle de 64° : l’angle qui le complète à 90° est ______°.',
   'Angle de 123° : l’angle qui le complète à 180° est ______°.',
   'Deux droites sécantes forment un angle de 72° : les trois autres sont ______, ______, ______.',
   'Vrai ou faux : « deux angles aigus peuvent être supplémentaires » — justifier.',
   'Un angle rentrant de 300° et l’angle qui lui est joint : lequel avec lui ?'],
 corr:[correction('1','26','90° − 64° = 26° : couple complémentaire.'),
   correction('2','57','180° − 123° = 57° : couple supplémentaire.'),
   correction('3','108°, 72°, 108°','Opposés égaux ; un supplémentaire vaut 180° − 72° = 108°.'),
   correction('4','faux','Deux aigus restent sous 90° chacun : la somme ne peut pas atteindre 180°.'),
   correction('5','l’aigu de 60°','300° + 60° = 360° : le plein, joint par construction.')]});

/* ---------- Séance 7 / Leçon 7 ---------- */
L.push({tag:'L7 ex.',
 obj:'Dans une configuration de deux droites et d’une sécante : reconnaître les angles, nommer les paires (alternes-internes, alternes-externes, correspondants) et prédire l’égalité.',
 ras:['Reconnaître angles à la sécante et leurs paires'],
 prereq:'Leçon 6 — couples d’angles ; leçon 5.',
 minutes:['10 min — La sécante coupe deux droites','20 min — Les paires nommées','15 min — Repérages','5 min — Synthèse'],
 got:'Les noms de paires et la règle « angles de la paire = angles égaux » comprises.',
 scene:'t7_scene_u4_piroso',
 teaser:'Une route (la sécante) croise deux rives (les droites) : les mêmes ouvertures reviennent de part et d’autre.',
 bul:[
 'Une sécante croise deux droites : huit angles apparaissent, en deux familles.',
 'À l’intérieur des droites : paires alternes−internes (en vis-à-vis) ; à l’extérieur : alternes−externes.',
 'Correspondants : même côté de la sécante, même place sur chaque droite.',
 'Les angles d’une même paire sont égaux (et égaux aussi aux opposés par le sommet).',
 'On vérifiera à la leçon suivante : droites parallèles, et ces égalités deviennent la clé des constructions.',
 ],
 trace:trace(
  'Une sécante forme <> angles avec deux droites ; on distille les paires utiles :',
  '<>, <>, <> : les angles d’une même paire sont <>.',
  'Les <>, les <>, les <> peuvent croiser les paires et prédire l’égalité de sortie.',
  P=>figCaption(N('7_altint'),'Fig. 1 — Alternes−internes en vis-à-vis, 55° chacun.',P),
  P=>figCaption(N('7_corr'),'Fig. 2 — Correspondants à la même place, 55° chacun.',P),
  P=>figCaption(N('7_huit'),'Fig. 3 — Les huit angles numérotés.',P)),
 exo:['Sur la figure 3 : citer la paire alterne−interne de l’angle 5.',
   'Sur la figure 3 : citer la paire correspondante de l’angle 2.',
   'Prédiction : si l’angle 2 mesure 55°, écrire la valeur de l’angle 6.',
   'Citer deux paires d’angles extérieurs dans la figure.',
   'Compléter : les angles d’une même paire sont ______.'],
 corr:[correction('1','l’angle 3','Angles 3 et 5 : à l’intérieur, en vis-à-vis de la sécante.'),
   correction('2','l’angle 6','Même côté de la sécante, même place sur chaque droite.'),
   correction('3','55°','Correspondants : angles d’une paire, donc égaux.'),
   correction('4','1 et 8 (alternes-externes), 2 et 7 (alternes-externes)','Elles vivent de part et d’autre des deux droites, côtés opposés de la sécante.'),
   correction('5','égaux','Propriété de la leçon : paire = égalité.')]});

/* ---------- Séance 8 / Leçon 8 ---------- */
L.push({tag:'L8 ex.',
 obj:'Compléter la collection : triangle, quadrilatères (carré, rectangle, losange, parallélogramme, trapèze), pentagone, hexagone… ; les reconnaître et les nommer.',
 ras:['Identifier les figures de la géométrie plane'],
 prereq:'Trace écrite du dessin géométrique élémentaire (classes passées) ; leçon 1.',
 minutes:['10 min — Dénombrement des côtés','20 min — Galerie des polygones','15 min — Jeux de reconnaissance','5 min — Synthèse'],
 got:'Noms et comptes de côtés corrects pour les polygones d’usage.',
 scene:'t7_scene_u4_maison',
 teaser:'Une maison, une clôture, un lavabo : partout des polygones qui portent le nom de leur nombre de côtés.',
 bul:[
 'Polygone : figure fermée faite de segments ; son nom vient du nombre de côtés.',
 '3 → triangle ; 4 → quadrilatère ; 5 → pentagone ; 6 → hexagone ; 7 → heptagone ; 8 → octogone.',
 'Quadrilatères de référence : carré, rectangle, losange, parallélogramme, trapèze.',
 'Le carré est à la fois un rectangle et un losange.',
 '2 → impossible : un polygone demande au minimum trois segments.',
 ],
 trace:trace(
  'Un polygone est une ligne brisée <> faite de <>.',
  'Triangle : 3, quadrilatère : 4, pentagone : 5, hexagone : <>, heptagone : <>, octogone : <>.',
  'Parmi les quadrilatères, le <> a 4 côtés égaux et 4 angles droits.',
  P=>figCaption(N('8_galerie'),'Fig. 1 — Galerie des polygones par nombre de côtés.',P),
  P=>figCaption(N('8_quadri'),'Fig. 2 — Les cinq quadrilatères de référence.',P),
  P=>figCaption(N('8_props'),'Fig. 3 — Tableau des particularités.',P)),
 exo:['Compter les côtés et nommer : figure à 5 segments.',
   'Citer trois polygones à 4 côtés vus à la leçon.',
   'Vrai ou faux : « un carré est un trapèze » — justifier brièvement.',
   'Nommer le polygone à 8 côtés.',
   'Compléter : un polygon à 2 côtés ______ exister.'],
 corr:[correction('1','pentagone','5 côtés → pentagone.'),
   correction('2','carré, rectangle, losange (parallélogramme, trapèze)','Trois au choix parmi les cinq vus.'),
   correction('3','faux','Le trapèze n’a qu’un seul couple de côtés parallèles ; le carré en a deux.'),
   correction('4','octogone','8 côtés → octogone.'),
   correction('5','ne peut pas','Deux segments ne ferment pas une figure : trois au minimum.')]});

/* ---------- Séance 9 / Leçon 9 ---------- */
L.push({tag:'L9 ex.',
 obj:'Tracer et nommer : médiatrice d’un segment, hauteur d’un triangle, orthocentre ; relier médiatrice et points à égale distance.',
 ras:['Reconnaître médiatrice et hauteur'],
 prereq:'Perpendiculaires ; milieux ; compas.',
 minutes:['10 min — La perpendiculaire au milieu','20 min — Tracés guidés','15 min — Tracés autonomes','5 min — Synthèse'],
 got:'Définitions claires ; tracé au compas de la médiatrice ; pied de hauteur placé correctement.',
 scene:'t7_scene_u4_puits',
 teaser:'Positionner le puits à égale distance de deux cases : la médiatrice tranche l’énigme ; la hauteur mesure la falaise.',
 bul:[
 'La médiatrice d’un segment est la droite perpendiculaire à ce segment passant par son milieu.',
 'Tout point de la médiatrice est à égale distance des deux extrémités.',
 'Construction : deux arcs de même rayon (plus grand que la moitié du segment) qui se croisent.',
 'La hauteur d’un triangle est la perpendiculaire issue d’un sommet au côté opposé.',
 'Un triangle a trois hauteurs : elles se rencontrent en un point, l’orthocentre H.',
 ],
 trace:trace(
  'Médiatrice : droite <>, passant par le <>.',
  'Propriété : tout point de la médiatrice est <> des extrémités.',
  'Hauteur : perpendiculaire issue <>, de pied sur le <>.',
  'Les trois hauteurs du triangle se coupent en <>.',
  P=>figCaption(N('9_med'),'Fig. 1 — La médiatrice, et la propriété PA = PB.',P),
  P=>figCaption(N('9_haut'),'Fig. 2 — La hauteur issue de C, pied H sur [AB].',P),
  P=>figCaption(N('9_trois'),'Fig. 3 — Les trois hauteurs : l’orthocentre.',P)),
 exo:['Tracer [AB] = 6 cm puis sa médiatrice au compas.',
   'Placer un point M sur la médiatrice : mesurer MA et MB, noter l’égalité.',
   'Tracer la hauteur issue de C dans le triangle ABC.',
   'Dans un triangle rectangle en A : où se trouve l’orthocentre ?',
   'Compléter : la médiatrice coupe le segment en son ______.'],
 corr:[correction('1','arcs de rayon > 3 cm de part et d’autre','Rayon fixe des deux côtés ; joindre les deux croisements.'),
   correction('2','MA = MB','Tout point de la médiatrice est à égale distance de A et B.'),
   correction('3','perpendiculaire à (AB) passant par C','Le pied se nomme souvent H ; vérifier l’angle droit.'),
   correction('4','au sommet A','Dans un triangle rectangle, l’orthocentre est le sommet de l’angle droit.'),
   correction('5','milieu','Définition même de la médiatrice.')]});

/* ---------- Séance 10 / Leçon 10 ---------- */
L.push({tag:'L10 ex.',
 obj:'Tracer et nommer : médiane (sommet → milieu), bissectrice (partage l’angle en deux), centre de gravité G.',
 ras:['Reconnaître médiane et bissectrice'],
 prereq:'Leçon 9 — perpendiculaires dans le triangle.',
 minutes:['10 min — Le milieu et la moitié d’angle','20 min — Tracés','15 min — Exercices','5 min — Synthèse'],
 got:'Les quatre droites remarquables bien distinguées.',
 scene:'t7_scene_u4_partage',
 teaser:'Partager la plaque en deux par la médiane, l’angle du toit en deux par la bissectrice.',
 bul:[
 'La médiane joint un sommet au milieu du côté opposé.',
 'La bissectrice partage l’angle en deux angles égaux.',
 'Les trois médianes se rencontrent en G, le centre de gravité du triangle.',
 'Trois bissectrices se rencontrent en I, lié au cercle inscrit vu à la leçon suivante.',
 'Médiatrice, hauteur, médiane, bissectrice : chacune a son rôle, aucune confusion.',
 ],
 trace:trace(
  'Médiane : segment d’un <> au <> du côté opposé ; point commun G : <>.',
  'Bissectrice : partage <> en <>.',
  'Les trois bissectrices se rencontrent en <>.',
  P=>figCaption(N('10_median'),'Fig. 1 — La médiane vers le milieu M.',P),
  P=>figCaption(N('10_bissec'),'Fig. 2 — La bissectrice et ses deux angles égaux.',P),
  P=>figCaption(N('10_trois'),'Fig. 3 — Les trois médianes et le centre de gravité.',P)),
 exo:['Tracer [EF] = 7 cm, placer le milieu K ; tracer la médiane issue du sommet D.',
   'Tracer la bissectrice d’un angle de 64° : les deux angles obtenus valent ______°.',
   'Tracer les trois médianes d’un triangle ; nommer le point de rencontre.',
   'Associer : médiane / bissectrice / médiatrice / hauteur ↔ milieu / moitié d’angle / perpendiculaire au milieu / perpendiculaire d’un sommet.',
   'Compléter : le triangle de référence a ______ médianes.'],
 corr:[correction('1','K à 3,5 cm de E','7 ÷ 2 = 3,5 ; la médiane [DK] part du sommet D.'),
   correction('2','32°','64 ÷ 2 = 32 : la bissectrice coupe exactement en deux.'),
   correction('3','G, le centre de gravité','Les trois médianes se rencontrent toujours en un seul point.'),
   correction('4','médiane↔milieu ; bissectrice↔moitié d’angle ; médiatrice↔perpendiculaire au milieu ; hauteur↔perpendiculaire d’un sommet','Le quatuor, rôle par rôle.'),
   correction('5','trois','Une par sommet.')]});

/* ---------- Séance 11 / Leçon 11 ---------- */
L.push({tag:'L11 ex.',
 obj:'Distinguer le cercle circonscrit (médiatrices, par les trois sommets) du cercle inscrit (bissectrices, tangent aux trois côtés) ; construire les deux.',
 ras:['Distinguer cercle circonscrit et inscrit','Construire ces cercles'],
 prereq:'Leçons 9 et 10 — médiatrices, bissectrices.',
 minutes:['10 min — Deux cercles autour des sommets','20 min — Constructions guidées','15 min — Constructions','5 min — Synthèse'],
 got:'Les deux centres (O, I) placés correctement ; cercles ajustés (aux sommets / aux côtés).',
 scene:'t7_scene_u4_roue',
 teaser:'Une roue posée sur un cadre et une roue juste dedans : le circonscrit contre l’inscrit.',
 bul:[
 'Cercle circonscrit = le cercle qui passe par les trois sommets ; son centre O est le point commun des trois médiatrices.',
 'Cercle inscrit = le cercle à l’intérieur qui touche les trois côtés ; son centre I est le point commun des trois bissectrices.',
 'Rayon du circonscrit : OA = OB = OC ; rayon de l’inscrit : distance perpendiculaire de I à chaque côté.',
 'Construction : tracer deux médiatrices (suffit pour O) ou deux bissectrices (suffit pour I).',
 'Le circonscrit contient le triangle ; l’inscrit est contenu dans le triangle.',
 ],
 trace:trace(
  'Circonscrit : passe par les <> ; centre <>, rencontre des <>.',
  'Inscrit : touche les <> ; centre <>, rencontre des <>.',
  'Le circonscrit <> le triangle ; l’inscrit est <>.',
  P=>figCaption(N('11_circ'),'Fig. 1 — Le cercle circonscrit, centre O.',P),
  P=>figCaption(N('11_insc'),'Fig. 2 — Le cercle inscrit, centre I, tangent aux côtés.',P),
  P=>figCaption(N('11_bilan'),'Fig. 3 — Bilan : qui donne quel centre.',P)),
 exo:['Tracer un triangle ABC ; deux médiatrices ; placer O ; tracer le cercle de centre O passant par A.',
   'Vérifier : le cercle passe-t-il aussi par B et C ?',
   'Tracer deux bissectrices ; placer I ; dessiner le cercle de centre I qui touche [AB].',
   'Compléter : le centre du cercle inscrit est le point commun des trois ______.',
   'Oral : pourquoi l’inscrit ne peut-il pas sortir du triangle ?'],
 corr:[correction('1','croisement des médiatrices = O ; rayon OA','La médiatrice garantit OA = OB = OC.'),
   correction('2','oui, par construction','Trois sommets à égale distance de O.'),
   correction('3','rayon = distance perpendiculaire de I à [AB]','Poser l’équerre : le rayon de l’inscrit est perpendiculaire au côté.'),
   correction('4','bissectrices','Définition du centre I.'),
   correction('5','il est tangent aux trois côtés, donc arrêté juste au bord','Chaque côté barre la sortie.')]});

/* ---------- Séance 12 : Révision ---------- */
const REV = revisionSec({
 titleShort:'Révision de l’unité IV', scene:'t7_scene_u4_quai',
 got:'Je sais nommer les figures, les angles, les paires d’angles, les droites remarquables, et je les dessine correctement.',
 summary:[['Figures usuelles','L1, L8','polygones par côtés ; triangles de collection : rectangles, isocèles, équilatéraux.'],
   ['Repères','L3, L4','droite graduée (origine, unité, abscisse) puis repère orthogonal (x ; y).'],
   ['Angles','L5, L6, L7','types nul → plein ; couples complémentaires, supplémentaires, opposés ; paires à la sécante.'],
   ['Droites du triangle','L9, L10','médiatrice, hauteur, médiane, bissectrice — quatre rôles bien distincts.'],
   ['Cercles du triangle','L11','centre O des médiatrices (circonscrit), centre I des bissectrices (inscrit).']],
 qa:[['Un triangle à 3 côtés égaux s’appelle ?','équilatéral (et ses angles font 60°)'],
   ['La somme des angles d’un couple supplémentaire :','180°'],
   ['Deux droites sécantes forment un angle de 35° : l’angle opposé ?','35° (opposés par le sommet : égaux)'],
   ['Le point où se coupent les médianes :','G, le centre de gravité'],
   ['Placer M(3 ; 2) dans le repère : on lit d’abord ?','l’abscisse x = 3 sur l’axe horizontal, puis y = 2 à la verticale'],
   ['La droite perpendiculaire au milieu d’un segment :','la médiatrice'],
   ['Deux angles qui valent ensemble 90° :','complémentaires'],
   ['Le centre du cercle circonscrit se trouve avec :','les médiatrices'],
   ['Un polygone à 6 côtés :','un hexagone']],
 error:'Confusion des quatre droites remarquables du triangle.',
 meth:'Fiche-mémo : nom + rôle + construction, pour médiatrice / hauteur / médiane / bissectrice.'});

/* ---------- Séance 13 : Examen ---------- */
const EX = examSec({num:'IV', titleShort:'Examen de l’unité IV — Géométrie', mins:60,
 parts:[{t:'Exercice 1 — Figures et polygones',pts:4,
   cons:'(a) Nommer le polygone à 5 côtés. (b) Deux noms de quadrilatères à côtés opposés égaux. (c) Le triangle qui possède trois angles de 60°. (d) Le polygone à 8 côtés.',
   markings:['(a) pentagone (1 pt)','(b) rectangle, parallélogramme (0,5 pt × 2)','(c) équilatéral (1 pt)','(d) octogone (1 pt)']},
  {t:'Exercice 2 — Sur la droite graduée',pts:4,
   cons:"Droite graduée d'origine O. (a) Placer A(+3) et B(−2). (b) Donner l'abscisse du point à cinq pas à gauche de O. (c) Calculer les pas de −2 jusqu'à +3. (d) Ranger : +1, −3, 0, +2 dans l'ordre croissant.",
   markings:['(a) abscisses placées selon les signes (1 pt)','(b) −5 (1 pt)','(c) 5 pas (1 pt)','(d) −3 < 0 < +1 < +2 (1 pt)']},
  {t:'Exercice 3 — Dans le repère orthogonal',pts:4,
   cons:'(a) Donner les coordonnées de M si x = 2 et y = 4. (b) Placer P(5 ; 1). (c) (3 ; 3) et (6 ; 3) : ce qui les distingue. (d) Q d’ordonnée 0 : sur quel axe ?',
   markings:['(a) M (2 ; 4) (1 pt)','(b) guides à 5 puis 1, point au croisement (1 pt)','(c) même ordonnée, abscisses différentes (1 pt)','(d) sur l’axe horizontal (Ox) (1 pt)']},
  {t:'Exercice 4 — Angles',pts:4,
   cons:'(a) Un angle de 90° s’appelle… (b) Le complémentaire de 30°. (c) Le supplémentaire de 65°. (d) Deux droites sécantes, un angle 110° : les trois autres ?',
   markings:['(a) angle droit (1 pt)','(b) 60° (1 pt)','(c) 115° (1 pt)','(d) 70°, 110°, 70° (1 pt)']},
  {t:'Exercice 5 — Droites remarquables',pts:4,
   cons:'(a) Rôle de la médiatrice. (b) Rôle de la médiane. (c) Le centre du cercle inscrit s’obtient avec… (d) Nom du point où se coupent les hauteurs.',
   markings:['(a) perpendiculaire au segment passant par son milieu (1 pt)','(b) relie un sommet au milieu du côté opposé (1 pt)','(c) les bissectrices (1 pt)','(d) orthocentre H (1 pt)']}]});

module.exports = {U,L,REV,EX,
 build:()=>buildDoc({file:'Manuel-Mathematiques-T7-UNITE4-GEOMETRIE.docx', U, L, REV, EX,
   couverture:{unit:'UNITE IV', cap:'GÉOMÉTRIE', sous:'13 séances — 11 leçons + révision + examen',
     motifs:['🔺','📐','📏','⭕','🧭'],
     pitch:'La géométrie T7 côte à côte : identifier, construire, nommer ; repères et angles ; les quatre droites remarquables, leurs points et leurs cercles.',
     scene:loadScene('t7_scene_u4_mur')}})};
