// Annexes du manuel : mémento et sujets de composition périodique.
module.exports = {
  memento: {
    titre: "MÉMENTO DU PROGRAMME DE 6e",
    intro: "Ce mémento rassemble en quelques pages toutes les définitions, règles et formules étudiées au cours de l'année. L'élève y trouvera l'essentiel à savoir avant une évaluation ; l'enseignant, un support de révision rapide en fin de période.",
    sections: [
      {
        nom: "1. Nombres entiers et décimaux",
        lignes: [
          ["Valeur de position", "Dans 3 254 108, le chiffre 5 vaut 50 000 : sa valeur dépend de la colonne qu'il occupe."],
          ["Arrondi", "On observe le chiffre situé juste à droite du rang choisi : de 0 à 4 on descend, de 5 à 9 on monte."],
          ["Nombre décimal", "Partie entière et partie décimale séparées par une virgule ; après la virgule : dixièmes, centièmes, millièmes."],
          ["Écritures équivalentes", "Les zéros inutiles ne changent rien : 3,5 = 3,50 = 03,5."],
          ["Comparer", "On compare les parties entières, puis les décimales rang par rang, en complétant par des zéros."],
          ["Addition et soustraction", "On aligne les virgules, on complète par des zéros, on calcule en partant de la droite."],
          ["Multiplication", "On calcule sans les virgules ; le produit reçoit autant de décimales que les deux facteurs réunis."],
          ["Multiplier par 10, 100, 1 000", "La virgule se déplace vers la droite d'autant de rangs qu'il y a de zéros."],
          ["Multiplier par 0,1 ; 0,01", "La virgule se déplace vers la gauche ; le nombre diminue."],
        ],
      },
      {
        nom: "2. Divisions et divisibilité",
        lignes: [
          ["Division euclidienne", "dividende = diviseur × quotient + reste, avec un reste toujours inférieur au diviseur."],
          ["Multiple et diviseur", "Si la division de a par b tombe juste, a est un multiple de b et b un diviseur de a."],
          ["Divisible par 2", "Le nombre se termine par 0, 2, 4, 6 ou 8."],
          ["Divisible par 5", "Le nombre se termine par 0 ou 5."],
          ["Divisible par 10", "Le nombre se termine par 0."],
          ["Divisible par 3", "La somme des chiffres est un multiple de 3."],
          ["Divisible par 9", "La somme des chiffres est un multiple de 9."],
          ["Diviser un décimal par un entier", "On divise comme pour les entiers et l'on place la virgule au quotient dès qu'on abaisse le premier chiffre décimal."],
          ["Diviser par un décimal", "On multiplie dividende et diviseur par 10, 100 ou 1 000 pour rendre le diviseur entier."],
          ["Diviser par 10, 100, 1 000", "La virgule se déplace vers la gauche ; le nombre diminue."],
        ],
      },
      {
        nom: "3. Fractions",
        lignes: [
          ["Sens", "Le dénominateur indique en combien de parts égales on partage, le numérateur combien de parts on prend."],
          ["Fractions égales", "On ne change pas la valeur en multipliant ou en divisant les deux termes par un même nombre non nul."],
          ["Simplifier", "On divise les deux termes par un même nombre jusqu'à obtenir une fraction irréductible."],
          ["Comparer", "À dénominateur égal, le plus grand numérateur l'emporte ; à numérateur égal, le plus petit dénominateur l'emporte ; sinon on réduit au même dénominateur."],
          ["Additionner et soustraire", "À même dénominateur, on opère sur les numérateurs et l'on conserve le dénominateur."],
          ["Fraction d'une quantité", "On divise par le dénominateur, puis on multiplie par le numérateur."],
          ["Fraction et décimal", "On divise le numérateur par le dénominateur : <<3/4>> = 0,75 ; <<2/5>> = 0,4 ; <<1/8>> = 0,125."],
        ],
      },
      {
        nom: "4. Proportionnalité et pourcentages",
        lignes: [
          ["Proportionnalité", "On passe d'une grandeur à l'autre en multipliant toujours par un même nombre, le coefficient."],
          ["Règle de trois", "On calcule la valeur pour une unité par une division, puis on multiplie par la quantité voulue."],
          ["Échelle", "Du plan au réel on multiplie par le nombre de l'échelle ; du réel au plan on divise."],
          ["Pourcentage", "p % d'une quantité : on multiplie par p et l'on divise par 100. 50 % = <<1/2>> ; 25 % = <<1/4>> ; 20 % = <<1/5>> ; 10 % = <<1/10>>."],
          ["Remise", "On calcule le montant puis on le soustrait ; une remise de 20 % laisse 80 % à payer."],
          ["Hausse", "On calcule le montant puis on l'ajoute ; une hausse de 10 % donne 110 % du prix."],
          ["Exprimer une part", "On divise la part par le total, puis on multiplie par 100."],
        ],
      },
      {
        nom: "5. Géométrie plane",
        lignes: [
          ["Notations", "(AB) droite, [AB] segment, [AB) demi-droite, AB longueur, ⊥ perpendiculaire, // parallèle, ∈ appartient."],
          ["Droites", "Deux droites sécantes se coupent en un point ; perpendiculaires si l'angle est droit ; parallèles si elles ne se coupent jamais."],
          ["Médiatrice", "Perpendiculaire à un segment en son milieu ; tout point de la médiatrice est à égale distance des extrémités."],
          ["Cercle", "Ensemble des points à égale distance du centre. Corde : segment joignant deux points ; diamètre : corde passant par le centre, égale à deux fois le rayon."],
          ["Triangles", "Isocèle : deux côtés égaux. Équilatéral : trois côtés égaux. Rectangle : un angle droit."],
          ["Construction d'un triangle", "Possible seulement si le plus grand côté est inférieur à la somme des deux autres."],
          ["Quadrilatères", "Parallélogramme : côtés opposés parallèles. Rectangle : quatre angles droits. Losange : quatre côtés égaux. Carré : les deux."],
          ["Symétrie axiale", "Un pliage le long de l'axe superpose les deux figures ; elle conserve longueurs et angles et retourne la figure."],
          ["Axes de symétrie", "Rectangle 2, losange 2, carré 4, triangle équilatéral 3, triangle isocèle 1, cercle une infinité, parallélogramme quelconque aucun."],
          ["Angles", "Nul 0°, aigu moins de 90°, droit 90°, obtus entre 90° et 180°, plat 180°, tour complet 360°."],
          ["Somme des angles d'un triangle", "Toujours 180° ; chaque angle d'un triangle équilatéral vaut 60°."],
          ["Complémentaires et supplémentaires", "Somme de 90° pour les premiers, de 180° pour les seconds."],
        ],
      },
      {
        nom: "6. Périmètres, aires et volumes",
        lignes: [
          ["Périmètre du carré", "4 × côté"],
          ["Périmètre du losange", "4 × côté"],
          ["Périmètre du rectangle", "2 × (Longueur + largeur)"],
          ["Périmètre du triangle", "somme des trois côtés"],
          ["Circonférence du cercle", "2 × π × rayon, ou π × diamètre, avec π environ égal à 3,14"],
          ["Aire du carré", "côté × côté"],
          ["Aire du rectangle", "Longueur × largeur"],
          ["Aire du triangle", "(base × hauteur) ÷ 2, la hauteur étant perpendiculaire à la base"],
          ["Aire du disque", "π × rayon × rayon"],
          ["Aire totale du pavé droit", "2 × (L × l + L × h + l × h)"],
          ["Aire totale du cube", "6 × côté × côté"],
          ["Volume du pavé droit", "Longueur × largeur × hauteur, ou aire de la base × hauteur"],
          ["Volume du cube", "arête × arête × arête"],
        ],
      },
      {
        nom: "7. Solides",
        lignes: [
          ["Pavé droit", "6 faces rectangulaires, 12 arêtes, 8 sommets ; faces opposées identiques deux à deux."],
          ["Cube", "Pavé droit dont les 6 faces sont des carrés égaux."],
          ["Cylindre", "Deux bases circulaires identiques reliées par une surface courbe."],
          ["Patron du pavé", "Six rectangles identiques deux à deux."],
          ["Patron du cube", "Six carrés égaux."],
          ["Patron du cylindre", "Deux disques et un rectangle dont la longueur est la circonférence de la base et la largeur la hauteur."],
          ["Perspective", "Face avant en vraie grandeur, fuyantes parallèles, arêtes cachées en pointillés."],
          ["Somme des arêtes du pavé", "4 × (Longueur + largeur + hauteur)"],
        ],
      },
      {
        nom: "8. Grandeurs et conversions",
        lignes: [
          ["Longueurs", "km, hm, dam, m, dm, cm, mm : chaque unité vaut 10 fois la suivante. 1 km = 1 000 m ; 1 m = 100 cm."],
          ["Aires", "Chaque unité vaut 100 fois la suivante. 1 m² = 100 dm² = 10 000 cm². 1 are = 100 m² ; 1 hectare = 10 000 m²."],
          ["Volumes", "Chaque unité vaut 1 000 fois la suivante. 1 m³ = 1 000 dm³ = 1 000 000 cm³."],
          ["Capacités", "1 dm³ = 1 litre ; 1 m³ = 1 000 litres ; 1 cm³ = 1 millilitre."],
          ["Masses", "Chaque unité vaut 10 fois la suivante. 1 kg = 1 000 g ; 1 tonne = 1 000 kg."],
          ["Masse brute, nette et tare", "masse brute = masse nette + tare ; c'est la masse nette qui est facturée."],
          ["Durées", "1 minute = 60 secondes ; 1 heure = 60 minutes ; 1 jour = 24 heures. La retenue vaut 60."],
          ["Vitesse moyenne", "distance ÷ durée ; distance = vitesse × durée ; durée = distance ÷ vitesse."],
        ],
      },
      {
        nom: "9. Organisation de données",
        lignes: [
          ["Effectif", "Nombre d'individus d'une catégorie ; la somme des effectifs donne l'effectif total."],
          ["Diagramme en bâtons", "Chaque bâton a la même largeur ; sa hauteur représente l'effectif ; la graduation commence à zéro."],
          ["Fréquence", "effectif ÷ effectif total × 100, exprimée en pourcentage ; la somme des fréquences vaut 100 %."],
          ["Diagramme circulaire", "Angle du secteur = 360 × fréquence ÷ 100. 25 % donnent 90°, 50 % donnent 180°."],
          ["Moyenne", "Somme des valeurs divisée par leur nombre ; elle est comprise entre le minimum et le maximum."],
          ["Étendue", "Différence entre la plus grande et la plus petite valeur."],
        ],
      },
    ],
  },

  compositions: [
    {
      id: "C1",
      titre: "Sujet de composition — Premier trimestre",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties indépendantes. Toutes les réponses doivent être justifiées par un calcul et accompagnées de leur unité. Il porte sur les Périodes I et II.",
      parties: [
        {
          nom: "Première partie — Nombres et opérations (8 points)",
          exos: [
            { pts: 2, c: "Calcule 3 456 + 1 287, puis 45,6 − 12,85.",
              r: "3 456 + 1 287 = [[4 743]]. 45,6 − 12,85 = [[32,75]] : on aligne les virgules et l'on complète 45,6 en 45,60." },
            { pts: 2, c: "Calcule 12,5 × 8 et donne un ordre de grandeur de ce produit.",
              r: "12,5 × 8 = [[100]]. Ordre de grandeur : 12 × 8 = [[96]], proche du résultat exact." },
            { pts: 2, c: "Effectue la division euclidienne de 750 par 12 et écris l'égalité correspondante.",
              r: "Quotient [[62]], reste [[6]] : 12 × 62 + 6 = 750. Le reste est bien inférieur au diviseur." },
            { pts: 2, c: "Le nombre 4 320 est-il divisible par 9 ? Et par 5 ? Justifie par les critères.",
              r: "Par 9 : 4 + 3 + 2 + 0 = 9, donc [[oui]]. Par 5 : le nombre se termine par 0, donc [[oui]]." },
          ],
        },
        {
          nom: "Deuxième partie — Géométrie et mesures (8 points)",
          exos: [
            { pts: 2, c: "Calcule 63,9 ÷ 1,5 en expliquant ta démarche.",
              r: "On multiplie les deux nombres par 10 : 639 ÷ 15 = [[42,6]]. Le quotient ne change pas." },
            { pts: 2, c: "Un champ rectangulaire mesure 24 m sur 16 m. Calcule son périmètre.",
              r: "2 × (24 + 16) = 2 × 40 = [[80 m]]." },
            { pts: 2, c: "Convertis 3,2 km en mètres, puis calcule la circonférence d'un cercle de 6 cm de rayon.",
              r: "3,2 km = [[3 200 m]]. Circonférence : 2 × 3,14 × 6 = [[37,68 cm]]." },
            { pts: 2, c: "Explique la différence entre deux droites parallèles et deux droites perpendiculaires.",
              r: "Deux droites [[parallèles]] ne se coupent jamais et gardent le même écartement ; deux droites [[perpendiculaires]] se coupent en formant un [[angle droit]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème (8 points)",
          exos: [
            { pts: 2, c: "Une commerçante achète 18 kg de riz à 2 500 ariary le kilogramme. Quelle somme dépense-t-elle ?",
              r: "18 × 2 500 = [[45 000 ariary]]." },
            { pts: 2, c: "Elle paie avec un billet de 50 000 ariary. Combien lui rend-on ?",
              r: "50 000 − 45 000 = [[5 000 ariary]]." },
            { pts: 2, c: "Elle répartit ensuite ce riz dans des sacs de 4 kg. Combien de sacs pleins obtient-elle et que reste-t-il ?",
              r: "18 ÷ 4 donne un quotient de [[4]] et un reste de [[2]] : elle obtient 4 sacs pleins et il reste 2 kg." },
            { pts: 2, c: "Vérifie la vraisemblance de la somme dépensée par un ordre de grandeur.",
              r: "On estime 20 × 2 500 = [[50 000 ariary]], proche des 45 000 ariary trouvés : le calcul est [[vraisemblable]]." },
          ],
        },
      ],
    },
    {
      id: "C2",
      titre: "Sujet de composition — Deuxième trimestre",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties indépendantes. Les constructions doivent laisser apparaître les traits de construction. Il porte sur les Périodes III et IV.",
      parties: [
        {
          nom: "Première partie — Fractions (8 points)",
          exos: [
            { pts: 2, c: "Simplifie <<42/56>> au maximum et explique ta démarche.",
              r: "On divise les deux termes par [[14]] : <<42/56>> = [[<<3/4>>]], qui est irréductible." },
            { pts: 2, c: "Calcule <<3/8>> + <<1/4>>.",
              r: "On réduit au dénominateur 8 : <<3/8>> + <<2/8>> = [[<<5/8>>]]." },
            { pts: 2, c: "Un producteur récolte 1 050 kg de manioc et en vend <<2/3>>. Quelle masse a-t-il vendue ?",
              r: "1 050 ÷ 3 = 350, puis 350 × 2 = [[700 kg]]." },
            { pts: 2, c: "Écris <<5/8>> en nombre décimal et compare-le à 0,6.",
              r: "<<5/8>> = [[0,625]]. Comme 0,625 > 0,6, la fraction est [[supérieure]] à 0,6." },
          ],
        },
        {
          nom: "Deuxième partie — Aires et angles (8 points)",
          exos: [
            { pts: 2, c: "Calcule l'aire d'un rectangle de 32 m sur 18 m.",
              r: "32 × 18 = [[576 m²]]." },
            { pts: 2, c: "Calcule l'aire d'un triangle de base 14 cm et de hauteur 9 cm, puis celle d'un disque de rayon 6 cm.",
              r: "Triangle : (14 × 9) ÷ 2 = [[63 cm²]]. Disque : 3,14 × 6 × 6 = [[113,04 cm²]]." },
            { pts: 2, c: "Un triangle a deux angles de 48 et 72 degrés. Calcule le troisième et précise la nature du triangle.",
              r: "180 − 48 − 72 = [[60 degrés]]. Le triangle est [[quelconque]], car ses trois angles diffèrent." },
            { pts: 2, c: "Combien d'axes de symétrie possèdent un carré, un rectangle et un cercle ?",
              r: "Carré : [[4]] ; rectangle : [[2]] ; cercle : une [[infinité]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème (8 points)",
          exos: [
            { pts: 2, c: "Trois kilogrammes de vanille coûtent 7 500 ariary. Quel est le prix de 11 kg au même tarif ?",
              r: "Un kilogramme : 7 500 ÷ 3 = 2 500 Ar. Onze kilogrammes : [[27 500 ariary]]." },
            { pts: 2, c: "Un article coûte 64 000 ariary. Le vendeur accorde 15 % de remise. Quel est le montant de la remise ?",
              r: "64 000 × 15 ÷ 100 = [[9 600 ariary]]." },
            { pts: 2, c: "Quel prix le client paie-t-il ? Retrouve ce résultat par un second calcul.",
              r: "64 000 − 9 600 = [[54 400 ariary]]. Autre méthode : 64 000 × 85 ÷ 100 = [[54 400 ariary]]." },
            { pts: 2, c: "Un élève a obtenu 11, 14, 9 et 18. Calcule sa moyenne et l'étendue de ses notes.",
              r: "Moyenne : (11 + 14 + 9 + 18) ÷ 4 = [[13]]. Étendue : 18 − 9 = [[9]]." },
          ],
        },
      ],
    },
    {
      id: "C3",
      titre: "Sujet de composition — Troisième trimestre",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties indépendantes. Il porte sur la Période V et reprend, dans la troisième partie, des notions de l'ensemble de l'année.",
      parties: [
        {
          nom: "Première partie — Solides et volumes (8 points)",
          exos: [
            { pts: 2, c: "Un pavé droit mesure 12 cm, 8 cm et 5 cm. Calcule son volume.",
              r: "12 × 8 × 5 = [[480 cm³]]." },
            { pts: 2, c: "Calcule l'aire totale de ses faces.",
              r: "2 × (96 + 60 + 40) = 2 × 196 = [[392 cm²]]." },
            { pts: 2, c: "Calcule le volume d'un cube de 6 cm d'arête et donne le nombre de ses arêtes.",
              r: "Volume : 6 × 6 × 6 = [[216 cm³]]. Il possède [[12 arêtes]] égales." },
            { pts: 2, c: "De quoi se compose le patron d'un cylindre ? Précise les dimensions du rectangle.",
              r: "De [[deux disques]] et d'un [[rectangle]] dont la longueur est la [[circonférence de la base]] et la largeur la [[hauteur]] du cylindre." },
          ],
        },
        {
          nom: "Deuxième partie — Capacités, masses et durées (8 points)",
          exos: [
            { pts: 2, c: "Une citerne mesure 4 m sur 2,5 m sur 1,2 m. Calcule son volume en mètres cubes puis en litres.",
              r: "4 × 2,5 × 1,2 = [[12 m³]], soit [[12 000 litres]]." },
            { pts: 2, c: "Combien de bidons de 30 litres peut-on remplir avec cette citerne ?",
              r: "12 000 ÷ 30 = [[400 bidons]]." },
            { pts: 2, c: "Un camion charge 42 sacs de 45 kg. Quelle masse totale, en kilogrammes puis en tonnes ?",
              r: "42 × 45 = [[1 890 kg]], soit [[1,89 tonne]]." },
            { pts: 2, c: "Calcule 8 h 20 + 4 h 55 en expliquant la retenue.",
              r: "12 h 75 ; comme 75 dépasse 60, on convertit 60 minutes en une heure : [[13 h 15]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème de synthèse (8 points)",
          exos: [
            { pts: 2, c: "Un camion parcourt 560 km à la vitesse moyenne de 70 km par heure. Quelle est la durée du trajet ?",
              r: "560 ÷ 70 = [[8 heures]]." },
            { pts: 2, c: "Il part à 6 h. À quelle heure arrive-t-il ?",
              r: "6 h + 8 h = [[14 heures]]." },
            { pts: 2, c: "Il transporte des caisses pesant 32 kg brut, la tare étant de 2,5 kg. Quelle est la masse nette d'une caisse ? Énonce la relation utilisée.",
              r: "32 − 2,5 = [[29,5 kg]]. Relation : [[masse brute = masse nette + tare]]." },
            { pts: 2, c: "Le chargement occupe un espace de 12 m³ dans une remorque de 20 m³. Quel pourcentage de la remorque est occupé ?",
              r: "12 ÷ 20 × 100 = [[60 %]]. La remorque est donc remplie à [[60 %]]." },
          ],
        },
      ],
    },
  ],
};
