// Séance de révision et sujet d'examen — un jeu par période.
// Conforme a manuel-structure.md section 7 : titre « Sujet d'examen 6e »,
// duree indiquee, bareme total, corrige complet.

module.exports = {
  P1: {
    revision: {
      titre: "Révision de la Période I",
      intro: "Cette séance récapitule les notions étudiées au cours de la première période : les nombres entiers naturels, les nombres décimaux, l'addition, la soustraction et la multiplication.",
      notions: [
        ["Nombre entier naturel", "Nombre sans virgule, écrit avec les dix chiffres groupés par classes de trois : unités, mille, millions."],
        ["Valeur de position", "Quantité représentée par un chiffre selon la colonne qu'il occupe. Dans 3 254 108, le 5 vaut 50 000."],
        ["Arrondi", "Valeur approchée obtenue en observant le chiffre situé juste à droite du rang choisi : de 0 à 4 on descend, de 5 à 9 on monte."],
        ["Nombre décimal", "Nombre formé d'une partie entière et d'une partie décimale séparées par une virgule."],
        ["Rangs décimaux", "Après la virgule : dixièmes, centièmes, millièmes. Chaque rang vaut dix fois moins que le précédent."],
        ["Écritures équivalentes", "Les zéros inutiles, à gauche du nombre ou tout à droite après la virgule, ne changent pas sa valeur : 3,5 = 3,50 = 03,5."],
        ["Comparaison de décimaux", "On compare d'abord les parties entières, puis les décimales rang par rang, en complétant si besoin par des zéros."],
        ["Troncature et arrondi", "Tronquer, c'est couper après le rang choisi ; arrondir, c'est tenir compte du chiffre suivant."],
        ["Addition et soustraction", "On aligne les virgules, on complète par des zéros, on calcule en partant de la droite."],
        ["Multiplication", "On calcule sans les virgules, puis le produit reçoit autant de décimales que les deux facteurs réunis."],
        ["Multiplier par 10, 100, 1 000", "La virgule se déplace vers la droite d'autant de rangs qu'il y a de zéros ; le nombre augmente."],
        ["Multiplier par 0,1 ; 0,01 ; 0,001", "La virgule se déplace vers la gauche ; le nombre diminue. Multiplier par 0,1 revient à diviser par 10."],
        ["Ordre de grandeur", "Calcul approché servant à prévoir un résultat et à vérifier qu'il est vraisemblable."],
      ],
      questions: [
        ["Quelle est la valeur du chiffre 7 dans 4 738 ?", "700, car il occupe la colonne des centaines."],
        ["Arrondis 6 482 à la centaine.", "6 500, car le chiffre des dizaines est 8."],
        ["Quelle est la partie décimale de 12,406 ?", "406."],
        ["Range dans l'ordre croissant : 5,7 ; 5,07 ; 5,77.", "5,07 < 5,7 < 5,77."],
        ["Calcule 12,5 + 3,75.", "16,25."],
        ["Calcule 20 − 7,25.", "12,75."],
        ["Calcule 2,5 × 4.", "10."],
        ["Calcule 8,4 × 10.", "84."],
        ["Calcule 350 × 0,01.", "3,5."],
        ["Donne un ordre de grandeur de 198 + 403.", "Environ 200 + 400, soit 600."],
        ["Combien de décimales comporte le produit 1,2 × 3,45 ?", "Trois décimales."],
        ["Que devient 4,900 après suppression des zéros inutiles ?", "4,9."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période I",
      duree: "1 heure",
      consigne: "Toutes les réponses doivent être justifiées par un calcul. Le soin et la présentation sont pris en compte.",
      parties: [
        {
          nom: "Première partie — Les nombres",
          exos: [
            { pts: 3, c: "Écris en chiffres : trois millions quarante mille sept cents. Puis donne la valeur du chiffre 4 dans ce nombre.",
              r: "Le nombre s'écrit [[3 040 700]]. Le chiffre 4 occupe la colonne des dizaines de mille : il vaut [[40 000]]." },
            { pts: 3, c: "Range dans l'ordre croissant : 8,7 ; 8,07 ; 8,77 ; 8,707.",
              r: "En complétant par des zéros — 8,700 ; 8,070 ; 8,770 ; 8,707 — on obtient [[8,07 < 8,7 < 8,707 < 8,77]]." },
            { pts: 2, c: "Donne la troncature puis l'arrondi de 9,368 au dixième.",
              r: "Troncature : [[9,3]]. Arrondi : [[9,4]], car le chiffre suivant est 6, supérieur à 5." },
            { pts: 2, c: "Décompose 47,05 en somme faisant apparaître la valeur de chaque chiffre.",
              r: "47,05 = [[40 + 7 + 0,05]]. Il n'y a pas de dixième, d'où le zéro à ce rang." },
          ],
        },
        {
          nom: "Deuxième partie — Calculs",
          exos: [
            { pts: 2, c: "Pose et calcule 45,8 + 12,75.",
              r: "En alignant les virgules : 45,80 + 12,75 = [[58,55]]." },
            { pts: 2, c: "Pose et calcule 50 − 18,25.",
              r: "En écrivant 50,00 − 18,25 : le résultat est [[31,75]]. Vérification : 31,75 + 18,25 = 50." },
            { pts: 2, c: "Calcule 3,5 × 12.",
              r: "35 × 12 = 420 ; le facteur 3,5 a une décimale, donc le produit est [[42]]." },
            { pts: 2, c: "Calcule astucieusement 2,5 × 7,8 × 4 en regroupant les facteurs.",
              r: "On regroupe 2,5 et 4 qui font 10 : 10 × 7,8 = [[78]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème",
          exos: [
            { pts: 2, c: "Un commerçant achète 12 sacs de riz de 25 kg chacun. Quelle masse totale a-t-il achetée ?",
              r: "12 × 25 = [[300 kg]]. « Le commerçant a acheté 300 kilogrammes de riz. »" },
            { pts: 2, c: "Il paie ce riz 2 400 ariary le kilogramme. Quelle somme dépense-t-il ?",
              r: "300 × 2 400 = [[720 000 ariary]]. Un ordre de grandeur, 300 × 2 000 = 600 000, confirme la vraisemblance." },
            { pts: 2, c: "Il revend l'ensemble pour 900 000 ariary. Quel bénéfice réalise-t-il ?",
              r: "900 000 − 720 000 = [[180 000 ariary]]. « Le commerçant réalise un bénéfice de 180 000 ariary. »" },
            { pts: 2, c: "Vérifie la vraisemblance de ta réponse précédente par un ordre de grandeur.",
              r: "On estime 900 000 − 700 000 = [[200 000 ariary]], proche du résultat exact de 180 000 ariary : le calcul est donc [[vraisemblable]]." },
          ],
        },
      ],
    },
  },
  P2: {
    revision: {
      titre: "Révision de la Période II",
      intro: "Cette séance récapitule les notions étudiées au cours de la deuxième période : la division euclidienne, la division décimale, les droites parallèles et perpendiculaires, ainsi que la mesure des longueurs et des périmètres.",
      notions: [
        ["Division euclidienne", "Partage d'un nombre entier par un autre : dividende = diviseur × quotient + reste, avec un reste toujours inférieur au diviseur."],
        ["Multiple et diviseur", "Si la division de a par b tombe juste, alors a est un multiple de b et b est un diviseur de a."],
        ["Critères par 2, 5 et 10", "Un nombre est divisible par 2 s'il se termine par 0, 2, 4, 6 ou 8 ; par 5 s'il se termine par 0 ou 5 ; par 10 s'il se termine par 0."],
        ["Critères par 3 et 9", "Un nombre est divisible par 3 si la somme de ses chiffres l'est ; par 9 si cette somme est un multiple de 9."],
        ["Division d'un décimal par un entier", "On divise comme pour les entiers et l'on place la virgule au quotient dès que l'on abaisse le premier chiffre décimal."],
        ["Division par un décimal", "On multiplie le dividende et le diviseur par 10, 100 ou 1 000 pour rendre le diviseur entier ; le quotient reste inchangé."],
        ["Quotient exact et valeur approchée", "Quand la division ne se termine pas, on arrête au rang demandé et l'on donne une valeur approchée."],
        ["Diviser par 10, 100, 1 000", "La virgule se déplace vers la gauche d'autant de rangs qu'il y a de zéros ; le nombre diminue."],
        ["Droites sécantes et perpendiculaires", "Deux droites sécantes se coupent en un point ; elles sont perpendiculaires si elles forment un angle droit."],
        ["Droites parallèles", "Deux droites parallèles ne se coupent jamais ; elles conservent partout le même écartement."],
        ["Mesurer et reporter", "Mesurer donne un nombre à la règle graduée ; reporter reproduit une longueur au compas sans en connaître la valeur."],
        ["Unités de longueur", "Du kilomètre au millimètre, chaque unité vaut dix fois la suivante. On multiplie vers les petites unités, on divise vers les grandes."],
        ["Périmètres", "Rectangle : 2 × (Longueur + largeur). Carré : 4 × côté. Cercle : 2 × π × rayon, avec π environ égal à 3,14."],
      ],
      questions: [
        ["Effectue la division euclidienne de 847 par 12.", "Quotient 70 et reste 7, car 12 × 70 + 7 = 847."],
        ["96 est-il un multiple de 6 ?", "Oui, car 96 = 6 × 16."],
        ["4 528 est-il divisible par 9 ?", "Non : 4 + 5 + 2 + 8 = 19, qui n'est pas un multiple de 9."],
        ["Calcule 2 024 ÷ 8.", "253."],
        ["Calcule 31,5 ÷ 2,5.", "12,6, après avoir multiplié les deux nombres par 10."],
        ["Calcule 45,6 ÷ 10.", "4,56."],
        ["Que signifie le symbole ⊥ ?", "Que deux droites sont perpendiculaires."],
        ["Deux droites parallèles peuvent-elles se couper ?", "Non, jamais."],
        ["Convertis 3,5 km en mètres.", "3 500 m."],
        ["Convertis 640 cm en mètres.", "6,4 m."],
        ["Quel est le périmètre d'un rectangle de 35 m sur 22 m ?", "2 × (35 + 22) = 114 m."],
        ["Quelle est la circonférence d'un cercle de rayon 8 cm ?", "2 × 3,14 × 8 = 50,24 cm."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période II",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties. Toutes les réponses doivent être justifiées par un calcul ou une phrase.",
      parties: [
        {
          nom: "Première partie — Divisions",
          exos: [
            { pts: 2, c: "Effectue la division euclidienne de 1 236 par 4 et écris l'égalité correspondante.",
              r: "1 236 ÷ 4 = [[309]], reste [[0]]. Égalité : 4 × 309 + 0 = 1 236." },
            { pts: 2, c: "Effectue la division euclidienne de 847 par 12 : donne le quotient et le reste.",
              r: "Quotient [[70]], reste [[7]], car 12 × 70 = 840 et 840 + 7 = 847. Le reste est bien [[inférieur au diviseur]]." },
            { pts: 2, c: "Parmi 135, 250, 4 528 et 981, lesquels sont divisibles par 9 ?",
              r: "135 (1+3+5 = 9) et 981 (9+8+1 = 18) sont [[divisibles par 9]]. 250 et 4 528 ne le sont pas." },
            { pts: 2, c: "Calcule 31,5 ÷ 2,5 en expliquant ta démarche.",
              r: "On multiplie les deux nombres par 10 : 315 ÷ 25 = [[12,6]]. Le quotient ne change pas." },
          ],
        },
        {
          nom: "Deuxième partie — Géométrie et conversions",
          exos: [
            { pts: 2, c: "Explique la différence entre deux droites parallèles et deux droites perpendiculaires.",
              r: "Deux droites [[parallèles]] ne se coupent jamais et gardent le même écartement. Deux droites [[perpendiculaires]] se coupent en formant un [[angle droit]]." },
            { pts: 2, c: "Convertis : 3,5 km en mètres ; 640 cm en mètres ; 8,25 m en centimètres ; 4 500 mm en mètres.",
              r: "[[3 500 m]] ; [[6,4 m]] ; [[825 cm]] ; [[4,5 m]]." },
            { pts: 2, c: "Calcule le périmètre d'un triangle de côtés 8,5 cm, 6,2 cm et 7,3 cm.",
              r: "8,5 + 6,2 + 7,3 = [[22 cm]]." },
            { pts: 2, c: "Un cercle a pour rayon 8 cm. Calcule son diamètre et sa circonférence.",
              r: "Diamètre : [[16 cm]]. Circonférence : 2 × 3,14 × 8 = [[50,24 cm]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème",
          exos: [
            { pts: 2, c: "Un champ rectangulaire mesure 52 m de long et 38 m de large. Calcule son périmètre.",
              r: "2 × (52 + 38) = 2 × 90 = [[180 m]]." },
            { pts: 2, c: "On entoure ce champ d'une seule rangée de fil vendu 750 ariary le mètre. Quel est le coût ?",
              r: "180 × 750 = [[135 000 ariary]]. « La clôture coûtera 135 000 ariary. »" },
            { pts: 2, c: "Le propriétaire dispose de 1 000 m de fil. Combien de rangées complètes peut-il poser ?",
              r: "1 000 ÷ 180 donne un quotient de [[5]] et un reste de [[100]] : il peut poser [[5 rangées]] complètes." },
            { pts: 2, c: "Il partage sa récolte de 1 236 kg de riz en sacs de 4 kg. Combien de sacs obtient-il ?",
              r: "1 236 ÷ 4 = [[309 sacs]], sans reste. « Il obtient 309 sacs de riz. »" },
          ],
        },
      ],
    },
  },
  P3: {
    revision: {
      titre: "Révision de la Période III",
      intro: "Cette séance récapitule les notions étudiées au cours de la troisième période : le cercle, les triangles et les quadrilatères, la symétrie axiale et les fractions.",
      notions: [
        ["Cercle et disque", "Le cercle est le contour, l'ensemble des points à égale distance du centre ; le disque est la surface qu'il délimite."],
        ["Corde, diamètre, arc", "Une corde joint deux points du cercle ; le diamètre est la corde passant par le centre ; l'arc est une portion de cercle."],
        ["Classification des triangles", "Isocèle si deux côtés sont égaux, équilatéral si les trois le sont, rectangle s'il possède un angle droit."],
        ["Condition de construction", "Un triangle n'existe que si son plus grand côté est inférieur à la somme des deux autres."],
        ["Quadrilatères usuels", "Le parallélogramme a ses côtés opposés parallèles ; le rectangle y ajoute quatre angles droits, le losange quatre côtés égaux, le carré les deux."],
        ["Périmètres", "Carré et losange : 4 × côté. Rectangle : 2 × (Longueur + largeur). Cercle : 2 × π × rayon."],
        ["Symétrie axiale", "Deux figures sont symétriques lorsqu'un pliage le long de l'axe les superpose exactement ; la symétrie conserve longueurs et angles."],
        ["Symétrique d'un point", "On trace la perpendiculaire à l'axe passant par le point, puis on reporte la même distance de l'autre côté."],
        ["Médiatrice", "Droite perpendiculaire à un segment en son milieu ; tout point de la médiatrice est à égale distance des extrémités."],
        ["Axes de symétrie", "Rectangle 2, losange 2, carré 4, triangle équilatéral 3, triangle isocèle 1, cercle une infinité, parallélogramme quelconque aucun."],
        ["Fraction", "Le dénominateur indique en combien de parts égales on partage, le numérateur combien de parts on prend."],
        ["Simplifier", "On divise le numérateur et le dénominateur par un même nombre sans changer la valeur de la fraction."],
        ["Fraction d'une quantité", "On divise la quantité par le dénominateur, puis on multiplie par le numérateur."],
      ],
      questions: [
        ["Quelle est la plus longue corde d'un cercle ?", "Le diamètre."],
        ["Peut-on construire un triangle de côtés 3, 3 et 7 cm ?", "Non, car 3 + 3 = 6, inférieur à 7."],
        ["Quel est le périmètre d'un rectangle de 18 m sur 11 m ?", "58 m."],
        ["Un carré a 52 cm de périmètre : quel est son côté ?", "13 cm."],
        ["Quelle est la circonférence d'un cercle de rayon 9 cm ?", "56,52 cm."],
        ["Combien d'axes de symétrie a un losange ?", "Deux, ses diagonales."],
        ["Que devient un point situé sur l'axe de symétrie ?", "Il reste à sa place."],
        ["Simplifie <<18/24>>.", "Trois quarts."],
        ["Calcule <<3/8>> de 480.", "180."],
        ["Calcule <<1/4>> + <<3/8>>.", "Cinq huitièmes."],
        ["Calcule <<5/6>> − <<1/3>>.", "Un demi."],
        ["Écris <<5/8>> en nombre décimal.", "0,625."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période III",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties. Les constructions doivent laisser apparaître les traits de construction.",
      parties: [
        {
          nom: "Première partie — Figures et périmètres",
          exos: [
            { pts: 2, c: "Calcule le périmètre d'un rectangle de 18 cm sur 11 cm et d'un triangle équilatéral de 7,5 cm de côté.",
              r: "Rectangle : 2 × (18 + 11) = [[58 cm]]. Triangle : 3 × 7,5 = [[22,5 cm]]." },
            { pts: 2, c: "Un cercle a pour rayon 9 cm. Calcule son diamètre et sa circonférence.",
              r: "Diamètre : [[18 cm]]. Circonférence : 2 × 3,14 × 9 = [[56,52 cm]]." },
            { pts: 2, c: "Peut-on construire un triangle de côtés 3 cm, 3 cm et 7 cm ? Justifie ta réponse.",
              r: "[[Non]] : 3 + 3 = 6, ce qui est [[inférieur à 7]]. Les arcs ne se croisent pas." },
            { pts: 2, c: "Un triangle isocèle a un périmètre de 22 cm et une base de 8 cm. Combien mesurent ses côtés égaux ?",
              r: "22 − 8 = 14, puis 14 ÷ 2 = [[7 cm]] chacun." },
          ],
        },
        {
          nom: "Deuxième partie — Symétrie",
          exos: [
            { pts: 2, c: "Décris la construction du symétrique d'un point A par rapport à une droite (d).",
              r: "On trace la [[perpendiculaire]] à (d) passant par A, qui coupe (d) en H, puis on reporte [[HA]] de l'autre côté pour obtenir A'." },
            { pts: 2, c: "Donne le nombre d'axes de symétrie du carré, du rectangle, du triangle équilatéral et du cercle.",
              r: "[[4]] ; [[2]] ; [[3]] ; une [[infinité]]." },
            { pts: 2, c: "Un triangle de côtés 5 cm, 6 cm et 7 cm a pour symétrique un triangle. Quel est le périmètre de ce dernier ?",
              r: "[[18 cm]], car la symétrie [[conserve les longueurs]]." },
            { pts: 2, c: "Énonce la propriété de la médiatrice d'un segment.",
              r: "Tout point de la [[médiatrice]] d'un segment est à [[égale distance]] de ses deux extrémités." },
          ],
        },
        {
          nom: "Troisième partie — Fractions",
          exos: [
            { pts: 2, c: "Simplifie <<18/24>> et <<30/45>>.",
              r: "[[<<3/4>>]] et [[<<2/3>>]]." },
            { pts: 2, c: "Calcule <<1/4>> + <<3/8>> et <<5/6>> − <<1/3>>.",
              r: "[[<<5/8>>]] et [[<<1/2>>]]." },
            { pts: 2, c: "Écris <<2/5>> et <<5/8>> en nombres décimaux.",
              r: "[[0,4]] et [[0,625]]." },
            { pts: 2, c: "Un producteur récolte 1 200 kg de manioc et en vend <<3/4>>. Quelle masse a-t-il vendue et quelle masse lui reste-t-il ?",
              r: "1 200 ÷ 4 = 300, puis 300 × 3 = [[900 kg]] vendus. Il lui reste [[300 kg]]." },
          ],
        },
      ],
    },
  },
  P4: {
    revision: {
      titre: "Révision de la Période IV",
      intro: "Cette séance récapitule les notions étudiées au cours de la quatrième période : la proportionnalité et les pourcentages, les aires, les angles et l'organisation de données.",
      notions: [
        ["Proportionnalité", "Deux grandeurs sont proportionnelles lorsqu'on passe de l'une à l'autre en multipliant toujours par un même nombre, le coefficient."],
        ["Règle de trois", "Méthode permettant de trouver une quatrième valeur : on calcule la valeur pour une unité, puis on multiplie."],
        ["Échelle", "Rapport entre les longueurs du plan et les longueurs réelles ; du plan au réel on multiplie, du réel au plan on divise."],
        ["Pourcentage", "Part rapportée à cent : 25 % équivaut à un quart. Pour calculer p % d'une quantité, on multiplie par p et l'on divise par 100."],
        ["Remise et hausse", "Une remise se soustrait du prix, une hausse s'y ajoute ; une remise de 20 % laisse 80 % à payer."],
        ["Aire", "Mesure de la surface occupée, exprimée en unités carrées, à ne pas confondre avec le périmètre."],
        ["Aires usuelles", "Rectangle : Longueur × largeur. Carré : côté × côté. Triangle : (base × hauteur) ÷ 2. Disque : π × rayon × rayon."],
        ["Unités d'aire", "Chaque unité vaut cent fois la suivante : 1 m² = 100 dm² = 10 000 cm². L'are vaut 100 m², l'hectare 10 000 m²."],
        ["Sortes d'angles", "Nul, aigu, droit à 90 degrés, obtus, plat à 180 degrés ; le tour complet vaut 360 degrés."],
        ["Somme des angles d'un triangle", "Elle vaut toujours 180 degrés ; chaque angle d'un triangle équilatéral mesure 60 degrés."],
        ["Complémentaires et supplémentaires", "Deux angles sont complémentaires si leur somme vaut 90 degrés, supplémentaires si elle vaut 180 degrés."],
        ["Tableaux et diagrammes", "Un tableau associe à chaque catégorie son effectif ; le diagramme en bâtons en donne une image comparable d'un coup d'œil."],
        ["Fréquence et moyenne", "La fréquence est l'effectif divisé par l'effectif total, en pourcentage ; la moyenne est la somme divisée par le nombre de termes."],
      ],
      questions: [
        ["Trois kilogrammes de riz coûtent 7 500 ariary. Combien coûtent 8 kg ?", "20 000 ariary."],
        ["Que signifie une échelle 1/250 ?", "Un centimètre sur le plan représente 250 cm en réalité."],
        ["Calcule 12 % de 87 500 ariary.", "10 500 ariary."],
        ["Quelle est l'aire d'un rectangle de 25 m sur 14 m ?", "350 m²."],
        ["Quelle est l'aire d'un triangle de base 9 cm et de hauteur 6 cm ?", "27 cm²."],
        ["Quelle est l'aire d'un disque de rayon 7 cm ?", "153,86 cm²."],
        ["Convertis 2,5 m² en centimètres carrés.", "25 000 cm²."],
        ["Combien de mètres carrés dans 4,5 hectares ?", "45 000 m²."],
        ["Un triangle a deux angles de 55 et 65 degrés : que vaut le troisième ?", "60 degrés."],
        ["Quel est le complémentaire de 28 degrés ?", "62 degrés."],
        ["Calcule la moyenne de 9, 13, 11 et 15.", "12."],
        ["Sur 50 personnes, 21 préfèrent le riz : quelle est la fréquence ?", "42 pour cent."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période IV",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties. Toutes les réponses doivent être justifiées par un calcul et accompagnées de leur unité.",
      parties: [
        {
          nom: "Première partie — Proportionnalité et pourcentages",
          exos: [
            { pts: 2, c: "Le riz vaut 2 500 ariary le kilogramme. Quel est le prix de 35 kg ?",
              r: "35 × 2 500 = [[87 500 ariary]]." },
            { pts: 2, c: "Sur cet achat, le client obtient 12 % de remise. Quel prix paie-t-il ?",
              r: "Remise : 87 500 × 12 ÷ 100 = [[10 500 Ar]]. Prix payé : [[77 000 ariary]]." },
            { pts: 2, c: "Que signifie une échelle de 1/250 ? Quelle longueur réelle représente 4 cm sur un tel plan ?",
              r: "[[1 cm]] du plan représente [[250 cm]] réels. 4 × 250 = 1 000 cm, soit [[10 m]]." },
            { pts: 2, c: "Sur 50 élèves, 21 préfèrent le riz. Quel pourcentage cela représente-t-il ?",
              r: "21 ÷ 50 × 100 = [[42 %]]." },
          ],
        },
        {
          nom: "Deuxième partie — Aires et angles",
          exos: [
            { pts: 2, c: "Calcule l'aire d'un rectangle de 25 m sur 14 m et celle d'un carré de 8 m de côté.",
              r: "[[350 m²]] et [[64 m²]]." },
            { pts: 2, c: "Calcule l'aire d'un triangle de base 9 cm et de hauteur 6 cm, puis celle d'un disque de rayon 7 cm.",
              r: "Triangle : (9 × 6) ÷ 2 = [[27 cm²]]. Disque : 3,14 × 7 × 7 = [[153,86 cm²]]." },
            { pts: 2, c: "Convertis 2,5 m² en centimètres carrés et 4,5 hectares en mètres carrés.",
              r: "[[25 000 cm²]] et [[45 000 m²]]." },
            { pts: 2, c: "Un triangle a deux angles de 55 et 65 degrés. Calcule le troisième, puis donne le supplémentaire de 145 degrés.",
              r: "Troisième angle : 180 − 55 − 65 = [[60 degrés]]. Supplémentaire : 180 − 145 = [[35 degrés]]." },
          ],
        },
        {
          nom: "Troisième partie — Organisation de données",
          exos: [
            { pts: 2, c: "Une enquête donne : riz 14, manioc 21, maïs 7, patate 8. Quel est l'effectif total ?",
              r: "14 + 21 + 7 + 8 = [[50 personnes]]." },
            { pts: 2, c: "Quelle est la fréquence du manioc, et quel angle lui correspond sur un diagramme circulaire ?",
              r: "Fréquence : 21 ÷ 50 × 100 = [[42 %]]. Angle : 360 × 42 ÷ 100 = [[151,2 degrés]]." },
            { pts: 2, c: "Quelle est l'étendue de cette série d'effectifs ?",
              r: "21 − 7 = [[14]]." },
            { pts: 2, c: "Un élève a obtenu 9, 13, 11 et 15. Calcule sa moyenne et explique ce qu'elle représente.",
              r: "(9 + 13 + 11 + 15) ÷ 4 = [[12]]. C'est la note que l'élève aurait à chaque devoir si toutes ses notes étaient [[égales]]." },
          ],
        },
      ],
    },
  },
  P5: {
    revision: {
      titre: "Révision de la Période V",
      intro: "Cette séance récapitule les notions étudiées au cours de la cinquième période : les solides usuels, le volume du pavé droit, les capacités, les masses et les durées.",
      notions: [
        ["Solides usuels", "Le pavé droit a six faces rectangulaires, le cube six faces carrées égales, le cylindre deux bases circulaires, la sphère la forme du ballon."],
        ["Faces, arêtes et sommets", "Un pavé droit possède six faces, douze arêtes et huit sommets ; ses faces opposées sont identiques deux à deux."],
        ["Patron", "Figure plane obtenue en dépliant un solide ; six rectangles pour le pavé, six carrés pour le cube, deux disques et un rectangle pour le cylindre."],
        ["Perspective", "La face avant se dessine en vraie grandeur, les fuyantes sont parallèles, les arêtes cachées en pointillés."],
        ["Aire totale", "Somme des aires des six faces : 2 × (L × l + L × h + l × h) pour le pavé, 6 × côté × côté pour le cube."],
        ["Volume", "Mesure de la place occupée dans l'espace, exprimée en unités cubiques."],
        ["Volume du pavé", "Longueur × largeur × hauteur, ou aire de la base multipliée par la hauteur ; pour le cube, arête × arête × arête."],
        ["Unités de volume", "Chaque unité vaut mille fois la suivante : 1 m³ = 1 000 dm³ = 1 000 000 cm³."],
        ["Volume et capacité", "Un décimètre cube vaut un litre ; un mètre cube vaut mille litres ; un centimètre cube vaut un millilitre."],
        ["Unités de masse", "Chaque unité vaut dix fois la suivante ; le kilogramme vaut mille grammes et la tonne mille kilogrammes."],
        ["Brute, nette et tare", "Masse brute égale masse nette augmentée de la tare ; c'est la masse nette qui est facturée."],
        ["Unités de durée", "Une minute vaut soixante secondes, une heure soixante minutes, un jour vingt-quatre heures ; la retenue vaut soixante."],
        ["Vitesse moyenne", "Distance divisée par la durée ; la distance s'obtient en multipliant la vitesse par la durée."],
      ],
      questions: [
        ["Combien de faces, d'arêtes et de sommets possède un pavé droit ?", "Six faces, douze arêtes et huit sommets."],
        ["Calcule le volume d'un pavé de 9 cm sur 5 cm sur 4 cm.", "180 cm³."],
        ["Calcule le volume d'un cube de 7 cm d'arête.", "343 cm³."],
        ["Calcule l'aire totale d'un cube de 7 cm d'arête.", "294 cm²."],
        ["De quoi se compose le patron d'un cylindre ?", "De deux disques et d'un rectangle."],
        ["Quelle est l'aire d'une base de rayon 5 cm ?", "78,5 cm²."],
        ["Convertis 4,2 m³ en litres.", "4 200 litres."],
        ["Convertis 2,4 tonnes en kilogrammes.", "2 400 kg."],
        ["Une caisse pèse 26 kg brut et la tare vaut 1,5 kg : quelle est la masse nette ?", "24,5 kg."],
        ["Calcule 6 h 40 + 3 h 35.", "10 h 15."],
        ["Calcule 15 h 10 − 9 h 25.", "5 h 45."],
        ["Un car parcourt 450 km à 75 km par heure : quelle est la durée du trajet ?", "6 heures."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période V",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties. Chaque résultat doit être accompagné de son unité et justifié par un calcul.",
      parties: [
        {
          nom: "Première partie — Solides et volumes",
          exos: [
            { pts: 2, c: "Combien de faces, d'arêtes et de sommets possède un pavé droit ? De quoi se compose son patron ?",
              r: "[[6 faces]], [[12 arêtes]], [[8 sommets]]. Son patron se compose de [[six rectangles]] identiques deux à deux." },
            { pts: 2, c: "Calcule le volume d'un pavé de 9 cm sur 5 cm sur 4 cm, puis celui d'un cube de 7 cm d'arête.",
              r: "Pavé : 9 × 5 × 4 = [[180 cm³]]. Cube : 7 × 7 × 7 = [[343 cm³]]." },
            { pts: 2, c: "Calcule l'aire totale des faces de ce pavé et de ce cube.",
              r: "Pavé : 2 × (45 + 36 + 20) = [[202 cm²]]. Cube : 6 × 49 = [[294 cm²]]." },
            { pts: 2, c: "Un cylindre a 5 cm de rayon. Calcule l'aire d'une base et la circonférence de cette base.",
              r: "Aire : 3,14 × 5 × 5 = [[78,5 cm²]]. Circonférence : 2 × 3,14 × 5 = [[31,4 cm]]." },
          ],
        },
        {
          nom: "Deuxième partie — Capacités et masses",
          exos: [
            { pts: 2, c: "Une citerne mesure 3 m sur 2 m sur 1,5 m. Quel est son volume en mètres cubes puis en litres ?",
              r: "3 × 2 × 1,5 = [[9 m³]], soit [[9 000 litres]]." },
            { pts: 2, c: "Combien de bidons de 25 litres peut-on remplir avec cette citerne ?",
              r: "9 000 ÷ 25 = [[360 bidons]]." },
            { pts: 2, c: "Un camion charge 36 sacs de 40 kg. Quelle masse totale, en kilogrammes puis en tonnes ?",
              r: "36 × 40 = [[1 440 kg]], soit [[1,44 tonne]]." },
            { pts: 2, c: "Une caisse pèse 26 kg brut, la tare étant de 1,5 kg. Quelle est la masse nette ? Énonce la relation utilisée.",
              r: "26 − 1,5 = [[24,5 kg]]. Relation : [[masse brute = masse nette + tare]]." },
          ],
        },
        {
          nom: "Troisième partie — Durées",
          exos: [
            { pts: 2, c: "Calcule 6 h 40 + 3 h 35 en expliquant la retenue.",
              r: "9 h 75 ; comme 75 dépasse 60, on convertit 60 minutes en une heure : [[10 h 15]]." },
            { pts: 2, c: "Un atelier ouvre à 9 h 25 et ferme à 15 h 10. Quelle est la durée d'ouverture ?",
              r: "15 h 10 − 9 h 25 = [[5 h 45]], soit 345 minutes." },
            { pts: 2, c: "Un car parcourt 450 km à la vitesse moyenne de 75 km par heure. Quelle est la durée du trajet ?",
              r: "450 ÷ 75 = [[6 heures]]." },
            { pts: 2, c: "Ce car part à 5 h 30. À quelle heure arrive-t-il, et quelle distance aurait-il parcourue en 8 heures ?",
              r: "Arrivée : 5 h 30 + 6 h = [[11 h 30]]. En 8 heures : 75 × 8 = [[600 km]]." },
          ],
        },
      ],
    },
  },
};
