// Séance de révision et sujet d'examen — un jeu par période.
// Conforme a manuel-structure.md section 7 : titre « Sujet d'examen 6e »,
// duree indiquee, bareme total, corrige complet.

module.exports = {
  P1: {
    revision: {
      titre: "Révision de la Période I",
      intro: "Cette séance récapitule les notions étudiées au cours de la première période : les nombres entiers naturels, les nombres décimaux, l'addition, la soustraction et la multiplication.",
      notions: [
        ["Nombre entier naturel", "Nombre sans virgule, écrit avec les dix chiffres groupés par classes de trois : unités, mille, millions."],
        ["Valeur de position", "Quantité représentée par un chiffre selon la colonne qu'il occupe. Dans 3 254 108, le 5 vaut 50 000."],
        ["Arrondi", "Valeur approchée obtenue en observant le chiffre situé juste à droite du rang choisi : de 0 à 4 on descend, de 5 à 9 on monte."],
        ["Nombre décimal", "Nombre formé d'une partie entière et d'une partie décimale séparées par une virgule."],
        ["Rangs décimaux", "Après la virgule : dixièmes, centièmes, millièmes. Chaque rang vaut dix fois moins que le précédent."],
        ["Écritures équivalentes", "Les zéros inutiles, à gauche du nombre ou tout à droite après la virgule, ne changent pas sa valeur : 3,5 = 3,50 = 03,5."],
        ["Comparaison de décimaux", "On compare d'abord les parties entières, puis les décimales rang par rang, en complétant si besoin par des zéros."],
        ["Troncature et arrondi", "Tronquer, c'est couper après le rang choisi ; arrondir, c'est tenir compte du chiffre suivant."],
        ["Addition et soustraction", "On aligne les virgules, on complète par des zéros, on calcule en partant de la droite."],
        ["Multiplication", "On calcule sans les virgules, puis le produit reçoit autant de décimales que les deux facteurs réunis."],
        ["Multiplier par 10, 100, 1 000", "La virgule se déplace vers la droite d'autant de rangs qu'il y a de zéros ; le nombre augmente."],
        ["Multiplier par 0,1 ; 0,01 ; 0,001", "La virgule se déplace vers la gauche ; le nombre diminue. Multiplier par 0,1 revient à diviser par 10."],
        ["Ordre de grandeur", "Calcul approché servant à prévoir un résultat et à vérifier qu'il est vraisemblable."],
      ],
      questions: [
        ["Quelle est la valeur du chiffre 7 dans 4 738 ?", "700, car il occupe la colonne des centaines."],
        ["Arrondis 6 482 à la centaine.", "6 500, car le chiffre des dizaines est 8."],
        ["Quelle est la partie décimale de 12,406 ?", "406."],
        ["Range dans l'ordre croissant : 5,7 ; 5,07 ; 5,77.", "5,07 < 5,7 < 5,77."],
        ["Calcule 12,5 + 3,75.", "16,25."],
        ["Calcule 20 − 7,25.", "12,75."],
        ["Calcule 2,5 × 4.", "10."],
        ["Calcule 8,4 × 10.", "84."],
        ["Calcule 350 × 0,01.", "3,5."],
        ["Donne un ordre de grandeur de 198 + 403.", "Environ 200 + 400, soit 600."],
        ["Combien de décimales comporte le produit 1,2 × 3,45 ?", "Trois décimales."],
        ["Que devient 4,900 après suppression des zéros inutiles ?", "4,9."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période I",
      duree: "1 heure",
      consigne: "Toutes les réponses doivent être justifiées par un calcul. Le soin et la présentation sont pris en compte.",
      parties: [
        {
          nom: "Première partie — Les nombres",
          exos: [
            { pts: 3, c: "Écris en chiffres : trois millions quarante mille sept cents. Puis donne la valeur du chiffre 4 dans ce nombre.",
              r: "Le nombre s'écrit [[3 040 700]]. Le chiffre 4 occupe la colonne des dizaines de mille : il vaut [[40 000]]." },
            { pts: 3, c: "Range dans l'ordre croissant : 8,7 ; 8,07 ; 8,77 ; 8,707.",
              r: "En complétant par des zéros — 8,700 ; 8,070 ; 8,770 ; 8,707 — on obtient [[8,07 < 8,7 < 8,707 < 8,77]]." },
            { pts: 2, c: "Donne la troncature puis l'arrondi de 9,368 au dixième.",
              r: "Troncature : [[9,3]]. Arrondi : [[9,4]], car le chiffre suivant est 6, supérieur à 5." },
            { pts: 2, c: "Décompose 47,05 en somme faisant apparaître la valeur de chaque chiffre.",
              r: "47,05 = [[40 + 7 + 0,05]]. Il n'y a pas de dixième, d'où le zéro à ce rang." },
          ],
        },
        {
          nom: "Deuxième partie — Calculs",
          exos: [
            { pts: 2, c: "Pose et calcule 45,8 + 12,75.",
              r: "En alignant les virgules : 45,80 + 12,75 = [[58,55]]." },
            { pts: 2, c: "Pose et calcule 50 − 18,25.",
              r: "En écrivant 50,00 − 18,25 : le résultat est [[31,75]]. Vérification : 31,75 + 18,25 = 50." },
            { pts: 2, c: "Calcule 3,5 × 12.",
              r: "35 × 12 = 420 ; le facteur 3,5 a une décimale, donc le produit est [[42]]." },
            { pts: 2, c: "Calcule astucieusement 2,5 × 7,8 × 4 en regroupant les facteurs.",
              r: "On regroupe 2,5 et 4 qui font 10 : 10 × 7,8 = [[78]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème",
          exos: [
            { pts: 2, c: "Un commerçant achète 12 sacs de riz de 25 kg chacun. Quelle masse totale a-t-il achetée ?",
              r: "12 × 25 = [[300 kg]]. « Le commerçant a acheté 300 kilogrammes de riz. »" },
            { pts: 2, c: "Il paie ce riz 2 400 ariary le kilogramme. Quelle somme dépense-t-il ?",
              r: "300 × 2 400 = [[720 000 ariary]]. Un ordre de grandeur, 300 × 2 000 = 600 000, confirme la vraisemblance." },
            { pts: 2, c: "Il revend l'ensemble pour 900 000 ariary. Quel bénéfice réalise-t-il ?",
              r: "900 000 − 720 000 = [[180 000 ariary]]. « Le commerçant réalise un bénéfice de 180 000 ariary. »" },
            { pts: 2, c: "Vérifie la vraisemblance de ta réponse précédente par un ordre de grandeur.",
              r: "On estime 900 000 − 700 000 = [[200 000 ariary]], proche du résultat exact de 180 000 ariary : le calcul est donc [[vraisemblable]]." },
          ],
        },
      ],
    },
  },
  P2: {
    revision: {
      titre: "Révision de la Période II",
      intro: "Cette séance récapitule les notions étudiées au cours de la deuxième période : la division euclidienne, la division décimale, les droites parallèles et perpendiculaires, ainsi que la mesure des longueurs et des périmètres.",
      notions: [
        ["Division euclidienne", "Partage d'un nombre entier par un autre : dividende = diviseur × quotient + reste, avec un reste toujours inférieur au diviseur."],
        ["Multiple et diviseur", "Si la division de a par b tombe juste, alors a est un multiple de b et b est un diviseur de a."],
        ["Critères par 2, 5 et 10", "Un nombre est divisible par 2 s'il se termine par 0, 2, 4, 6 ou 8 ; par 5 s'il se termine par 0 ou 5 ; par 10 s'il se termine par 0."],
        ["Critères par 3 et 9", "Un nombre est divisible par 3 si la somme de ses chiffres l'est ; par 9 si cette somme est un multiple de 9."],
        ["Division d'un décimal par un entier", "On divise comme pour les entiers et l'on place la virgule au quotient dès que l'on abaisse le premier chiffre décimal."],
        ["Division par un décimal", "On multiplie le dividende et le diviseur par 10, 100 ou 1 000 pour rendre le diviseur entier ; le quotient reste inchangé."],
        ["Quotient exact et valeur approchée", "Quand la division ne se termine pas, on arrête au rang demandé et l'on donne une valeur approchée."],
        ["Diviser par 10, 100, 1 000", "La virgule se déplace vers la gauche d'autant de rangs qu'il y a de zéros ; le nombre diminue."],
        ["Droites sécantes et perpendiculaires", "Deux droites sécantes se coupent en un point ; elles sont perpendiculaires si elles forment un angle droit."],
        ["Droites parallèles", "Deux droites parallèles ne se coupent jamais ; elles conservent partout le même écartement."],
        ["Mesurer et reporter", "Mesurer donne un nombre à la règle graduée ; reporter reproduit une longueur au compas sans en connaître la valeur."],
        ["Unités de longueur", "Du kilomètre au millimètre, chaque unité vaut dix fois la suivante. On multiplie vers les petites unités, on divise vers les grandes."],
        ["Périmètres", "Rectangle : 2 × (Longueur + largeur). Carré : 4 × côté. Cercle : 2 × π × rayon, avec π environ égal à 3,14."],
      ],
      questions: [
        ["Effectue la division euclidienne de 847 par 12.", "Quotient 70 et reste 7, car 12 × 70 + 7 = 847."],
        ["96 est-il un multiple de 6 ?", "Oui, car 96 = 6 × 16."],
        ["4 528 est-il divisible par 9 ?", "Non : 4 + 5 + 2 + 8 = 19, qui n'est pas un multiple de 9."],
        ["Calcule 2 024 ÷ 8.", "253."],
        ["Calcule 31,5 ÷ 2,5.", "12,6, après avoir multiplié les deux nombres par 10."],
        ["Calcule 45,6 ÷ 10.", "4,56."],
        ["Que signifie le symbole ⊥ ?", "Que deux droites sont perpendiculaires."],
        ["Deux droites parallèles peuvent-elles se couper ?", "Non, jamais."],
        ["Convertis 3,5 km en mètres.", "3 500 m."],
        ["Convertis 640 cm en mètres.", "6,4 m."],
        ["Quel est le périmètre d'un rectangle de 35 m sur 22 m ?", "2 × (35 + 22) = 114 m."],
        ["Quelle est la circonférence d'un cercle de rayon 8 cm ?", "2 × 3,14 × 8 = 50,24 cm."],
      ],
    },
    examen: {
      titre: "Sujet d'examen 6e — Période II",
      duree: "2 heures",
      consigne: "Le sujet comporte trois parties. Toutes les réponses doivent être justifiées par un calcul ou une phrase.",
      parties: [
        {
          nom: "Première partie — Divisions",
          exos: [
            { pts: 2, c: "Effectue la division euclidienne de 1 236 par 4 et écris l'égalité correspondante.",
              r: "1 236 ÷ 4 = [[309]], reste [[0]]. Égalité : 4 × 309 + 0 = 1 236." },
            { pts: 2, c: "Effectue la division euclidienne de 847 par 12 : donne le quotient et le reste.",
              r: "Quotient [[70]], reste [[7]], car 12 × 70 = 840 et 840 + 7 = 847. Le reste est bien [[inférieur au diviseur]]." },
            { pts: 2, c: "Parmi 135, 250, 4 528 et 981, lesquels sont divisibles par 9 ?",
              r: "135 (1+3+5 = 9) et 981 (9+8+1 = 18) sont [[divisibles par 9]]. 250 et 4 528 ne le sont pas." },
            { pts: 2, c: "Calcule 31,5 ÷ 2,5 en expliquant ta démarche.",
              r: "On multiplie les deux nombres par 10 : 315 ÷ 25 = [[12,6]]. Le quotient ne change pas." },
          ],
        },
        {
          nom: "Deuxième partie — Géométrie et conversions",
          exos: [
            { pts: 2, c: "Explique la différence entre deux droites parallèles et deux droites perpendiculaires.",
              r: "Deux droites [[parallèles]] ne se coupent jamais et gardent le même écartement. Deux droites [[perpendiculaires]] se coupent en formant un [[angle droit]]." },
            { pts: 2, c: "Convertis : 3,5 km en mètres ; 640 cm en mètres ; 8,25 m en centimètres ; 4 500 mm en mètres.",
              r: "[[3 500 m]] ; [[6,4 m]] ; [[825 cm]] ; [[4,5 m]]." },
            { pts: 2, c: "Calcule le périmètre d'un triangle de côtés 8,5 cm, 6,2 cm et 7,3 cm.",
              r: "8,5 + 6,2 + 7,3 = [[22 cm]]." },
            { pts: 2, c: "Un cercle a pour rayon 8 cm. Calcule son diamètre et sa circonférence.",
              r: "Diamètre : [[16 cm]]. Circonférence : 2 × 3,14 × 8 = [[50,24 cm]]." },
          ],
        },
        {
          nom: "Troisième partie — Problème",
          exos: [
            { pts: 2, c: "Un champ rectangulaire mesure 52 m de long et 38 m de large. Calcule son périmètre.",
              r: "2 × (52 + 38) = 2 × 90 = [[180 m]]." },
            { pts: 2, c: "On entoure ce champ d'une seule rangée de fil vendu 750 ariary le mètre. Quel est le coût ?",
              r: "180 × 750 = [[135 000 ariary]]. « La clôture coûtera 135 000 ariary. »" },
            { pts: 2, c: "Le propriétaire dispose de 1 000 m de fil. Combien de rangées complètes peut-il poser ?",
              r: "1 000 ÷ 180 donne un quotient de [[5]] et un reste de [[100]] : il peut poser [[5 rangées]] complètes." },
            { pts: 2, c: "Il partage sa récolte de 1 236 kg de riz en sacs de 4 kg. Combien de sacs obtient-il ?",
              r: "1 236 ÷ 4 = [[309 sacs]], sans reste. « Il obtient 309 sacs de riz. »" },
          ],
        },
      ],
    },
  },
};
