// Période II — 20 séances. Division euclidienne et décimale, droites, longueurs.
module.exports = [
{
  ch: "La division euclidienne",
  titre: "Découvrir la division euclidienne",
  objectif: "À la fin de la séance, l'élève est capable de poser une division euclidienne et d'identifier le dividende, le diviseur, le quotient et le reste.",
  materiel: "Jetons de comptage, cahier à carreaux, ardoises",
  rev: [["Calcule 12 × 25.", "300."],
        ["Calcule 4,5 × 10.", "45."],
        ["Quel est le quart de 80 ?", "20."]],
  mise: { q: "Un commerçant veut ranger 423 œufs dans des plateaux de 18. Combien de plateaux remplira-t-il complètement ?", ra: "Il faut partager 423 par 18." },
  obs: "Observez la division posée au tableau : 423 divisé par 18. Le quotient 23 est inscrit à droite, et le nombre 9 apparaît en bas du calcul.",
  ana: [
    ["Quel nombre partage-t-on ?", "423 ; on l'appelle le dividende."],
    ["Par quel nombre le partage-t-on ?", "Par 18, qui est le diviseur."],
    ["Combien de fois 18 tient-il dans 423 ?", "23 fois ; c'est le quotient."],
    ["Que représente le nombre 9 ?", "Ce qui reste après le partage : le reste."],
    ["Vérifions : combien font 18 × 23 ?", "414."],
    ["Et 414 + 9 ?", "423, c'est-à-dire le dividende."],
    ["Le reste 9 est-il plus petit que le diviseur 18 ?", "Oui, et c'est obligatoire."],
    ["Que se passerait-il si le reste valait 20 ?", "On pourrait encore retirer un 18, donc le quotient serait faux."],
  ],
  syn: "Donc, effectuer la division euclidienne d'un entier par un autre, c'est trouver le quotient et le reste tels que dividende égale diviseur multiplié par quotient, plus le reste. Le reste est toujours strictement inférieur au diviseur.",
  attention: "Le reste doit toujours être plus petit que le diviseur. Un reste égal ou supérieur au diviseur signale que le quotient a été sous-estimé : il faut recommencer.",
  astuce: "Vérifiez toujours par la multiplication : diviseur × quotient + reste doit redonner exactement le dividende.",
  app: [
    { c: "Effectue les divisions euclidiennes et donne le quotient et le reste :\n1. 423 par 18\n2. 157 par 12\n3. 500 par 7\n4. 96 par 8",
      r: "1. Quotient [[23]], reste [[9]]\n2. Quotient [[13]], reste [[1]]\n3. Quotient [[71]], reste [[3]]\n4. Quotient [[12]], reste [[0]]" },
    { c: "Écris l'égalité de la division de 245 par 15, puis vérifie-la.\n1. Quel est le quotient ?\n2. Quel est le reste ?\n3. Écris l'égalité.\n4. Vérifie le calcul.",
      r: "1. [[16]]\n2. [[5]]\n3. [[245 = 15 × 16 + 5]]\n4. 15 × 16 = 240, puis 240 + 5 = [[245]] : l'égalité est vérifiée" },
  ],
  evalx: [
    { c: "Donne le quotient et le reste :\n1. 89 par 6\n2. 144 par 12\n3. 205 par 20\n4. 77 par 9",
      r: "1. Quotient [[14]], reste [[5]]\n2. Quotient [[12]], reste [[0]]\n3. Quotient [[10]], reste [[5]]\n4. Quotient [[8]], reste [[5]]" },
    { c: "On partage 250 cahiers entre 8 classes, de façon égale.\n1. Combien chaque classe reçoit-elle ?\n2. Combien de cahiers restent-ils ?\n3. Écris l'égalité de la division.\n4. Que faire des cahiers restants ?",
      r: "1. [[31 cahiers]]\n2. [[2 cahiers]]\n3. [[250 = 8 × 31 + 2]]\n4. Ils restent en réserve, car [[on ne peut pas les partager également]]" },
  ],
  lecon: [
    ["1. Le vocabulaire", "Effectuer la {{division euclidienne}} d'un entier par un autre, c'est chercher combien de fois le second est contenu dans le premier, et ce qui reste.\nQuatre mots sont à connaître : le {{dividende}} est le nombre que l'on partage, le {{diviseur}} celui par lequel on partage, le {{quotient}} le résultat du partage, et le {{reste}} ce qui n'a pas pu être partagé."],
    ["2. L'égalité fondamentale", "Toute division euclidienne se résume par une égalité :\ndividende = diviseur × quotient + reste.\nPour 423 partagé par 18 : 423 = 18 × 23 + 9.\nCette égalité sert à {{vérifier}} tout calcul de division."],
    ["3. La condition sur le reste", "Le reste doit toujours être {{strictement inférieur}} au diviseur.\nDans notre exemple, 9 est bien plus petit que 18. Si l'on avait trouvé un reste de 20, cela signifierait qu'un 18 supplémentaire pouvait encore être retiré : le quotient serait alors erroné."],
    ["4. Quand le reste est nul", "Lorsque le reste vaut zéro, le partage tombe juste. On dit alors que le dividende est {{divisible}} par le diviseur, ou qu'il en est un {{multiple}}.\nAinsi 96 = 8 × 12 + 0 : 96 est divisible par 8, et 96 est un multiple de 8."],
  ],
  exos: [
    { pts: 4, c: "Donne le quotient et le reste de la division de 347 par 25.",
      r: "Quotient [[13]], reste [[22]], car 25 × 13 = 325 et 347 − 325 = 22." },
    { pts: 4, c: "Écris l'égalité de la division de 1 000 par 30 et vérifie-la.",
      r: "[[1 000 = 30 × 33 + 10]]. Vérification : 30 × 33 = 990, puis 990 + 10 = 1 000." },
    { pts: 4, c: "Un carton contient 12 bouteilles. Combien de cartons complets remplit-on avec 150 bouteilles ? Combien en reste-t-il ?",
      r: "150 ÷ 12 donne quotient [[12]] et reste [[6]] : on remplit [[12 cartons complets]] et il reste [[6 bouteilles]]." },
    { pts: 4, c: "Dans une division par 9, quels restes sont possibles ?",
      r: "Les restes possibles vont de [[0 à 8]], car le reste est toujours strictement inférieur au diviseur." },
    { pts: 4, c: "Vrai ou faux ? 1. Le reste peut être égal au diviseur. 2. 45 = 7 × 6 + 3. 3. Un reste nul signifie que la division tombe juste. 4. Le quotient est toujours plus grand que le dividende.",
      r: "1. [[Faux]] : il est toujours plus petit. 2. [[Vrai]] : 42 + 3 = 45. 3. [[Vrai]]. 4. [[Faux]] : il est plus petit dès que le diviseur dépasse 1." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Multiples et diviseurs",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître un multiple et un diviseur d'un nombre, et d'employer correctement les quatre formulations équivalentes.",
  materiel: "Tableau des multiples, jetons, ardoises",
  rev: [["Quel est le reste de 96 divisé par 8 ?", "Zéro."],
        ["Écris l'égalité de 50 divisé par 7.", "50 = 7 × 7 + 1."],
        ["Le reste peut-il dépasser le diviseur ?", "Non, jamais."]],
  mise: { q: "Peut-on ranger exactement 12 chaises en rangées de 3, sans qu'il en reste ?", ra: "Oui, cela fait 4 rangées complètes." },
  obs: "Observez le tableau au tableau : la première ligne donne les multiples de 3 — 3, 6, 9, 12, 15, 18 — et la deuxième les diviseurs de 12 — 1, 2, 3, 4, 6, 12.",
  ana: [
    ["Comment obtient-on les multiples de 3 ?", "En multipliant 3 par 1, par 2, par 3, et ainsi de suite."],
    ["Combien y a-t-il de multiples de 3 ?", "Une infinité."],
    ["Le nombre 12 figure-t-il dans cette liste ?", "Oui, car 12 = 3 × 4."],
    ["Que peut-on dire alors de 3 par rapport à 12 ?", "3 est un diviseur de 12."],
    ["Combien 12 a-t-il de diviseurs ?", "Six : 1, 2, 3, 4, 6 et 12."],
    ["La liste des diviseurs est-elle infinie ?", "Non, elle est toujours limitée."],
    ["Quel est le reste de 12 divisé par 3 ?", "Zéro."],
    ["Comment dire cela de quatre façons ?", "12 est un multiple de 3 ; 3 est un diviseur de 12 ; 12 est divisible par 3 ; 3 divise 12."],
  ],
  syn: "Donc, lorsque le reste d'une division est nul, quatre formulations équivalentes existent : le dividende est un multiple du diviseur, le diviseur est un diviseur du dividende, le dividende est divisible par le diviseur, et le diviseur divise le dividende.",
  attention: "Ne confondez pas multiple et diviseur. Les multiples d'un nombre sont plus grands que lui et forment une liste infinie ; ses diviseurs sont plus petits ou égaux et forment une liste limitée.",
  app: [
    { c: "Écris les six premiers multiples de :\n1. 4\n2. 7\n3. 10\n4. 25",
      r: "1. [[4, 8, 12, 16, 20, 24]]\n2. [[7, 14, 21, 28, 35, 42]]\n3. [[10, 20, 30, 40, 50, 60]]\n4. [[25, 50, 75, 100, 125, 150]]" },
    { c: "Donne tous les diviseurs de :\n1. 12\n2. 20\n3. 15\n4. 7",
      r: "1. [[1, 2, 3, 4, 6, 12]]\n2. [[1, 2, 4, 5, 10, 20]]\n3. [[1, 3, 5, 15]]\n4. [[1 et 7]] seulement" },
  ],
  evalx: [
    { c: "Complète par « multiple » ou « diviseur » :\n1. 24 est un …… de 6.\n2. 6 est un …… de 24.\n3. 100 est un …… de 25.\n4. 5 est un …… de 45.",
      r: "1. [[multiple]]\n2. [[diviseur]]\n3. [[multiple]]\n4. [[diviseur]]" },
    { c: "Vrai ou faux ?\n1. 1 est diviseur de tous les nombres.\n2. Un nombre a une infinité de diviseurs.\n3. 18 est un multiple de 4.\n4. Tout nombre est multiple de lui-même.",
      r: "1. [[Vrai]].\n2. [[Faux]] : la liste des diviseurs est toujours limitée.\n3. [[Faux]] : 18 ÷ 4 laisse un reste de 2.\n4. [[Vrai]] : car il s'obtient en le multipliant par 1." },
  ],
  lecon: [
    ["1. Les multiples", "Les {{multiples}} d'un nombre s'obtiennent en le multipliant successivement par 1, 2, 3, 4…\nLes multiples de 3 sont 3, 6, 9, 12, 15, 18, et ainsi de suite : la liste est {{infinie}}.\nUn multiple d'un nombre est toujours supérieur ou égal à ce nombre."],
    ["2. Les diviseurs", "Un {{diviseur}} d'un nombre est un entier qui le divise sans laisser de reste.\nLes diviseurs de 12 sont 1, 2, 3, 4, 6 et 12 : la liste est toujours {{limitée}}.\nTout nombre admet au moins deux diviseurs : 1 et lui-même."],
    ["3. Quatre façons de dire la même chose", "Lorsque le reste de la division de 12 par 3 est nul, on peut écrire indifféremment :\n— 12 est un multiple de 3 ;\n— 3 est un diviseur de 12 ;\n— 12 est divisible par 3 ;\n— 3 divise 12.\nCes quatre phrases ont exactement le même sens."],
    ["4. Ne pas confondre", "Les multiples vont vers le {{haut}}, les diviseurs vers le {{bas}}. Dans la phrase « 12 est un multiple de 3 », le grand nombre est cité en premier ; dans « 3 est un diviseur de 12 », c'est le petit.\nRepérer lequel des deux nombres est le plus grand évite l'erreur."],
  ],
  exos: [
    { pts: 4, c: "Écris les cinq premiers multiples de 9 et de 15.",
      r: "Multiples de 9 : [[9, 18, 27, 36, 45]]. Multiples de 15 : [[15, 30, 45, 60, 75]]." },
    { pts: 4, c: "Donne tous les diviseurs de 30.",
      r: "[[1, 2, 3, 5, 6, 10, 15, 30]] : huit diviseurs en tout." },
    { pts: 4, c: "Le nombre 48 est-il un multiple de 6 ? Justifie par un calcul.",
      r: "[[Oui]], car 48 = 6 × 8 et le reste est nul : 48 est donc [[divisible par 6]]." },
    { pts: 4, c: "Trouve un nombre qui soit à la fois multiple de 4 et de 6.",
      r: "Par exemple [[12]], car 12 = 4 × 3 et 12 = 6 × 2. On peut aussi citer [[24]] ou [[36]]." },
    { pts: 4, c: "Complète : 56 est un …… de 8 et 8 est un …… de 56.",
      r: "56 est un [[multiple]] de 8 ; 8 est un [[diviseur]] de 56." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Les critères de divisibilité par 2, 5 et 10",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître sans calcul si un nombre est divisible par 2, par 5 ou par 10.",
  materiel: "Étiquettes-nombres, tableau, ardoises",
  rev: [["Cite trois multiples de 7.", "7, 14 et 21."],
        ["Donne les diviseurs de 10.", "1, 2, 5 et 10."],
        ["48 est-il divisible par 6 ?", "Oui, car 48 = 6 × 8."]],
  mise: { q: "Comment savoir très vite si l'on peut partager 3 476 bonbons entre deux enfants, sans reste ?", ra: "En regardant le dernier chiffre du nombre." },
  obs: "Observez ces deux colonnes au tableau : à gauche 18, 40, 56, 72, 134 ; à droite 35, 80, 125, 60, 205. L'enseignant souligne le dernier chiffre de chaque nombre.",
  ana: [
    ["Par quels chiffres se terminent les nombres de gauche ?", "Par 8, 0, 6, 2 et 4."],
    ["Ces nombres sont-ils tous divisibles par 2 ?", "Oui, tous."],
    ["Quelle règle peut-on en tirer ?", "Un nombre est divisible par 2 s'il se termine par 0, 2, 4, 6 ou 8."],
    ["Comment nomme-t-on ces nombres ?", "Des nombres pairs."],
    ["Par quels chiffres se terminent ceux de droite ?", "Par 5 ou par 0."],
    ["De quoi sont-ils tous divisibles ?", "De 5."],
    ["Lesquels sont aussi divisibles par 10 ?", "Ceux qui se terminent par 0 : 80 et 60."],
    ["Un nombre divisible par 10 l'est-il aussi par 2 et par 5 ?", "Oui, toujours."],
  ],
  syn: "Donc, un nombre est divisible par 2 s'il se termine par 0, 2, 4, 6 ou 8 ; il est divisible par 5 s'il se termine par 0 ou 5 ; il est divisible par 10 s'il se termine par 0. Un nombre divisible par 10 est nécessairement divisible par 2 et par 5.",
  astuce: "Un seul chiffre suffit : celui des unités. Nul besoin de poser la division pour ces trois critères.",
  app: [
    { c: "Ces nombres sont-ils divisibles par 2 ?\n1. 3 476\n2. 891\n3. 1 250\n4. 7 003",
      r: "1. [[Oui]], il se termine par 6\n2. [[Non]], il se termine par 1\n3. [[Oui]], il se termine par 0\n4. [[Non]], il se termine par 3" },
    { c: "Classe ces nombres selon qu'ils sont divisibles par 5, par 10, ou par aucun des deux : 45 ; 120 ; 83 ; 500.",
      r: "Divisibles par 5 seulement : [[45]]. Divisibles par 5 et par 10 : [[120 et 500]]. Par aucun des deux : [[83]]." },
  ],
  evalx: [
    { c: "Réponds par oui ou non :\n1. 2 340 est-il divisible par 10 ?\n2. 675 est-il divisible par 2 ?\n3. 675 est-il divisible par 5 ?\n4. 1 002 est-il divisible par 5 ?",
      r: "1. [[Oui]]\n2. [[Non]]\n3. [[Oui]]\n4. [[Non]]" },
    { c: "Complète le nombre 47… pour qu'il soit :\n1. divisible par 2\n2. divisible par 5\n3. divisible par 10\n4. divisible par 2 mais pas par 5",
      r: "1. Par exemple [[470, 472, 474, 476 ou 478]]\n2. [[470 ou 475]]\n3. [[470]]\n4. Par exemple [[472]]" },
  ],
  lecon: [
    ["1. Pourquoi des critères", "Poser une division pour savoir si un partage tombe juste prend du temps. Les {{critères de divisibilité}} permettent de répondre immédiatement, en observant seulement l'écriture du nombre."],
    ["2. Divisibilité par 2", "Un nombre est divisible par {{2}} lorsqu'il se termine par 0, 2, 4, 6 ou 8. On dit alors qu'il est {{pair}} ; sinon il est {{impair}}.\nExemples : 18, 40, 56, 72 et 134 sont pairs ; 891 et 7 003 sont impairs."],
    ["3. Divisibilité par 5 et par 10", "Un nombre est divisible par {{5}} lorsqu'il se termine par 0 ou par 5 : 35, 80, 125, 205.\nIl est divisible par {{10}} lorsqu'il se termine par 0 : 80, 120, 500.\nTout nombre divisible par 10 l'est aussi par 2 et par 5, puisque 10 = 2 × 5."],
    ["4. Une aide au quotidien", "Ces critères servent chaque fois qu'un partage doit tomber juste : répartir des élèves en deux groupes, échanger des pièces de 5 ariary, compter par dizaines.\nIls s'appliquent aussi bien aux petits qu'aux très grands nombres, car seul le chiffre des unités compte."],
  ],
  exos: [
    { pts: 4, c: "Parmi 234 ; 405 ; 1 000 ; 777, lesquels sont divisibles par 2 ?",
      r: "[[234 et 1 000]], car ils se terminent par 4 et par 0." },
    { pts: 4, c: "Parmi 65 ; 132 ; 900 ; 48, lesquels sont divisibles par 5 ?",
      r: "[[65 et 900]], car ils se terminent par 5 et par 0." },
    { pts: 4, c: "Quel est le plus petit nombre de trois chiffres divisible à la fois par 2, par 5 et par 10 ?",
      r: "[[100]] : il se termine par 0, donc il est divisible par les trois." },
    { pts: 4, c: "Un commerçant veut ranger 1 245 œufs par paquets de 10. Est-ce possible sans reste ? Justifie.",
      r: "[[Non]] : 1 245 se termine par 5, il n'est donc pas divisible par 10. Il restera [[5 œufs]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Tout nombre pair est divisible par 2. 2. 305 est divisible par 10. 3. Un nombre divisible par 10 est pair. 4. 0 est un nombre pair.",
      r: "1. [[Vrai]] : c'est la définition. 2. [[Faux]] : il se termine par 5, non par 0. 3. [[Vrai]]. 4. [[Vrai]] : il se termine par 0." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Les critères de divisibilité par 3 et par 9",
  objectif: "À la fin de la séance, l'élève est capable d'appliquer le critère de la somme des chiffres pour reconnaître un nombre divisible par 3 ou par 9.",
  materiel: "Étiquettes-nombres, tableau, ardoises",
  rev: [["3 476 est-il divisible par 2 ?", "Oui, il se termine par 6."],
        ["Quel critère pour la divisibilité par 5 ?", "Le nombre se termine par 0 ou par 5."],
        ["Cite deux multiples de 10.", "20 et 130."]],
  mise: { q: "Le nombre 432 est-il divisible par 3 ? Le dernier chiffre suffit-il pour répondre ?", ra: "Non, le dernier chiffre ne suffit pas ici." },
  obs: "Observez au tableau : sous chaque nombre, l'enseignant a écrit la somme de ses chiffres. Pour 432, il a écrit 4 + 3 + 2 = 9 ; pour 7 281, il a écrit 7 + 2 + 8 + 1 = 18.",
  ana: [
    ["Que vaut la somme des chiffres de 432 ?", "Neuf."],
    ["Ce nombre 9 est-il un multiple de 3 ?", "Oui, car 9 = 3 × 3."],
    ["Et 432 est-il divisible par 3 ?", "Oui, car 432 = 3 × 144."],
    ["Que vaut la somme des chiffres de 7 281 ?", "Dix-huit."],
    ["18 est-il multiple de 9 ?", "Oui, car 18 = 9 × 2."],
    ["Que peut-on en déduire pour 7 281 ?", "Il est divisible par 9."],
    ["Un nombre divisible par 9 l'est-il par 3 ?", "Oui, toujours, car 9 est lui-même multiple de 3."],
    ["La réciproque est-elle vraie ?", "Non : 12 est divisible par 3 mais pas par 9."],
  ],
  syn: "Donc, un nombre est divisible par 3 lorsque la somme de ses chiffres est un multiple de 3, et divisible par 9 lorsque cette somme est un multiple de 9. Tout nombre divisible par 9 est aussi divisible par 3, mais l'inverse est faux.",
  attention: "Pour 3 et 9, le dernier chiffre ne renseigne sur rien : il faut additionner tous les chiffres. Le nombre 20 se termine par 0 mais n'est divisible ni par 3 ni par 9.",
  astuce: "Si la somme obtenue reste grande, recommencez : pour 7 281, on trouve 18, puis 1 + 8 = 9. Le résultat final indique aussitôt la réponse.",
  app: [
    { c: "Calcule la somme des chiffres et dis si le nombre est divisible par 3 :\n1. 432\n2. 1 234\n3. 936\n4. 507",
      r: "1. Somme 9 : [[oui]]\n2. Somme 10 : [[non]]\n3. Somme 18 : [[oui]]\n4. Somme 12 : [[oui]]" },
    { c: "Ces nombres sont-ils divisibles par 9 ?\n1. 7 281\n2. 630\n3. 4 506\n4. 8 100",
      r: "1. Somme 18 : [[oui]]\n2. Somme 9 : [[oui]]\n3. Somme 15 : [[non]]\n4. Somme 9 : [[oui]]" },
  ],
  evalx: [
    { c: "Pour chaque nombre, indique s'il est divisible par 3, par 9, ou par les deux :\n1. 27\n2. 51\n3. 891\n4. 100",
      r: "1. [[Par 3 et par 9]] : somme 9\n2. [[Par 3 seulement]] : somme 6\n3. [[Par 3 et par 9]] : somme 18\n4. [[Par aucun]] : somme 1" },
    { c: "Complète le nombre 4…2 pour qu'il soit divisible par 3.\n1. Quelle est la somme des chiffres connus ?\n2. Quel chiffre peut convenir ?\n3. Donne deux solutions.\n4. Cette solution est-elle unique ?",
      r: "1. [[6]]\n2. Un chiffre tel que la somme soit multiple de 3 : [[0, 3, 6 ou 9]]\n3. Par exemple [[402 et 432]]\n4. [[Non]], plusieurs chiffres conviennent" },
  ],
  lecon: [
    ["1. Un critère différent", "Pour 2, 5 et 10, le chiffre des unités suffisait. Pour 3 et 9, il faut au contraire tenir compte de {{tous les chiffres}} du nombre."],
    ["2. Divisibilité par 3", "Un nombre est divisible par {{3}} lorsque la {{somme de ses chiffres}} est un multiple de 3.\nExemple : pour 432, on calcule 4 + 3 + 2 = 9. Comme 9 est multiple de 3, le nombre 432 est divisible par 3. On vérifie : 432 = 3 × 144."],
    ["3. Divisibilité par 9", "Un nombre est divisible par {{9}} lorsque la somme de ses chiffres est un multiple de 9.\nExemple : pour 7 281, on calcule 7 + 2 + 8 + 1 = 18. Comme 18 est multiple de 9, le nombre 7 281 est divisible par 9."],
    ["4. Le lien entre 3 et 9", "Tout nombre divisible par {{9}} est aussi divisible par {{3}}, puisque 9 est lui-même un multiple de 3.\nLa réciproque est fausse : 12 est divisible par 3, car 1 + 2 = 3, mais pas par 9.\nSi la somme obtenue reste grande, on peut recommencer l'opération : pour 7 281, on passe de 18 à 1 + 8 = 9."],
  ],
  exos: [
    { pts: 4, c: "Parmi 123 ; 450 ; 682 ; 999, lesquels sont divisibles par 3 ?",
      r: "[[123]] (somme 6), [[450]] (somme 9) et [[999]] (somme 27) le sont. [[682]] ne l'est pas, sa somme vaut 16." },
    { pts: 4, c: "Parmi 279 ; 405 ; 511 ; 720, lesquels sont divisibles par 9 ?",
      r: "[[279]] (somme 18), [[405]] (somme 9) et [[720]] (somme 9) le sont. [[511]] ne l'est pas, sa somme vaut 7." },
    { pts: 4, c: "Le nombre 1 458 est-il divisible par 3 ? par 9 ? Justifie.",
      r: "La somme de ses chiffres vaut 1 + 4 + 5 + 8 = 18. Il est donc divisible [[par 3 et par 9]]." },
    { pts: 4, c: "Trouve le chiffre manquant pour que 5…4 soit divisible par 9.",
      r: "La somme connue est 5 + 4 = 9 ; il faut atteindre un multiple de 9. Le chiffre [[0]] convient (somme 9), de même que [[9]] (somme 18)." },
    { pts: 4, c: "Vrai ou faux ? 1. 20 est divisible par 3. 2. Tout nombre divisible par 9 l'est par 3. 3. Tout nombre divisible par 3 l'est par 9. 4. La somme des chiffres de 636 est 15.",
      r: "1. [[Faux]] : sa somme vaut 2. 2. [[Vrai]]. 3. [[Faux]] : 12 en est un contre-exemple. 4. [[Vrai]] : 6 + 3 + 6 = 15, donc 636 est divisible par 3." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Problèmes de partage",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème de partage en interprétant correctement le quotient et le reste selon la question posée.",
  materiel: "Énoncés au tableau, jetons, cahier de recherche",
  rev: [["936 est-il divisible par 3 ?", "Oui, la somme de ses chiffres vaut 18."],
        ["Quel est le reste de 50 divisé par 8 ?", "Deux."],
        ["Cite un critère de divisibilité par 5.", "Le nombre se termine par 0 ou 5."]],
  mise: { q: "Cinquante élèves doivent monter dans des taxis-brousse de 12 places. Combien de véhicules faut-il ?", ra: "Cinq, car quatre ne suffiraient pas pour tout le monde." },
  obs: "Observez au tableau la division de 50 par 12 : le quotient est 4 et le reste 2. À côté, trois questions différentes sont écrites sur cette même situation.",
  ana: [
    ["Combien de taxis-brousse sont pleins ?", "Quatre."],
    ["Combien d'élèves ne sont pas encore placés ?", "Deux."],
    ["Combien de véhicules faut-il en tout ?", "Cinq, car il faut un véhicule pour les deux derniers."],
    ["Pourquoi la réponse n'est-elle pas 4 ?", "Parce que le reste doit aussi être transporté."],
    ["Si la question portait sur les véhicules complets, que répondrait-on ?", "Quatre."],
    ["La division est-elle la même dans les deux cas ?", "Oui, seule l'interprétation change."],
    ["Que faut-il donc lire avec attention ?", "La question posée."],
  ],
  syn: "Donc, dans un problème de partage, la division donne toujours le même quotient et le même reste, mais la réponse dépend de la question. Si l'on cherche un nombre de parts complètes, on retient le quotient ; si tout doit être pris en charge, on ajoute une part supplémentaire pour le reste.",
  attention: "Ne répondez jamais mécaniquement par le quotient. Pour transporter 50 élèves dans des véhicules de 12 places, la réponse est 5 et non 4 : les deux élèves restants ont aussi besoin d'une place.",
  app: [
    { c: "Cinquante élèves voyagent dans des taxis-brousse de 12 places.\n1. Quel est le quotient de 50 par 12 ?\n2. Quel est le reste ?\n3. Combien de véhicules sont pleins ?\n4. Combien de véhicules faut-il en tout ?",
      r: "1. [[4]]\n2. [[2]]\n3. [[4 véhicules pleins]]\n4. [[5 véhicules]], car les 2 élèves restants doivent aussi voyager" },
    { c: "On partage 250 kg de riz dans des sacs de 30 kg.\n1. Combien de sacs pleins obtient-on ?\n2. Quelle masse reste-t-il ?\n3. Combien de sacs faut-il pour tout ranger ?\n4. Écris l'égalité de la division.",
      r: "1. [[8 sacs pleins]]\n2. [[10 kg]]\n3. [[9 sacs]]\n4. [[250 = 30 × 8 + 10]]" },
  ],
  evalx: [
    { c: "Une école de 148 élèves forme des groupes de 6.\n1. Combien de groupes complets ?\n2. Combien d'élèves restent-ils ?\n3. Combien de groupes si personne n'est laissé de côté ?\n4. Écris l'égalité de la division.",
      r: "1. [[24 groupes]]\n2. [[4 élèves]]\n3. [[25 groupes]]\n4. [[148 = 6 × 24 + 4]]" },
    { c: "On dispose de 500 ariary en pièces de 50 ariary.\n1. Combien de pièces obtient-on ?\n2. Reste-t-il de la monnaie ?\n3. La division tombe-t-elle juste ?\n4. Que peut-on dire de 500 par rapport à 50 ?",
      r: "1. [[10 pièces]]\n2. [[Non]]\n3. [[Oui]], le reste est nul\n4. [[500 est un multiple de 50]]" },
  ],
  lecon: [
    ["1. Reconnaître un partage", "On divise lorsqu'il faut {{répartir}} une quantité en parts égales, ou chercher combien de fois une quantité est contenue dans une autre.\nRanger 250 kg de riz dans des sacs de 30 kg, répartir 148 élèves en groupes de 6 : ce sont des divisions."],
    ["2. Interpréter le quotient", "Le {{quotient}} indique le nombre de parts complètes obtenues.\nPour 50 élèves et des véhicules de 12 places, le quotient 4 signifie que quatre véhicules seront pleins."],
    ["3. Interpréter le reste", "Le {{reste}} représente ce qui n'entre pas dans une part complète.\nIci, 2 élèves restent sans véhicule. Selon la question, ce reste conduit à des réponses différentes :\n— « combien de véhicules pleins ? » → 4 ;\n— « combien de véhicules faut-il ? » → 5, car les deux derniers élèves doivent voyager."],
    ["4. Lire la question jusqu'au bout", "Une même division peut donc mener à deux réponses correctes selon ce qui est demandé. C'est la {{question}}, et non le calcul, qui décide.\nOn termine toujours par une phrase réponse précisant l'unité : « Il faut 5 taxis-brousse. »"],
  ],
  exos: [
    { pts: 4, c: "On range 200 livres sur des étagères de 18 livres. Combien d'étagères sont pleines ? Combien de livres restent-ils ?",
      r: "200 ÷ 18 donne quotient [[11]] et reste [[2]] : [[11 étagères pleines]] et [[2 livres restants]]." },
    { pts: 4, c: "Combien d'étagères faut-il pour ranger la totalité de ces 200 livres ?",
      r: "[[12 étagères]] : les 11 pleines, plus une douzième pour les 2 livres restants." },
    { pts: 4, c: "On partage 96 bonbons entre 8 enfants. Chacun reçoit combien ? Reste-t-il des bonbons ?",
      r: "Chacun reçoit [[12 bonbons]] et il ne reste [[rien]] : 96 est un multiple de 8." },
    { pts: 4, c: "Un car de 45 places doit transporter 130 personnes. Combien de voyages faut-il ?",
      r: "130 ÷ 45 donne quotient 2 et reste 40 : il faut [[3 voyages]], car les 40 personnes restantes doivent être transportées." },
    { pts: 4, c: "Explique pourquoi la réponse à un problème de partage n'est pas toujours le quotient.",
      r: "Parce que le [[reste]] doit parfois être pris en charge lui aussi. Si tout doit être transporté ou rangé, on ajoute [[une part supplémentaire]] au quotient." },
  ],
},

// ───────────────────────────────── Ch. 6 — La division décimale
{
  ch: "La division décimale",
  titre: "Diviser un décimal par un entier",
  objectif: "À la fin de la séance, l'élève est capable de poser et d'effectuer la division d'un nombre décimal par un entier en plaçant correctement la virgule au quotient.",
  materiel: "Cahier à carreaux, tableau, ardoises",
  rev: [["Quel est le reste de 96 divisé par 8 ?", "Zéro."],
        ["Écris l'égalité de 50 divisé par 7.", "50 = 7 × 7 + 1."],
        ["Calcule 12,5 × 2.", "25."]],
  mise: { q: "On partage également 134,25 kg de riz entre 3 coopératives. Quelle masse chacune reçoit-elle ?", ra: "Il faut diviser 134,25 par 3." },
  obs: "Observez la division posée au tableau : 134,25 divisé par 3. Une flèche signale le moment où l'on abaisse le chiffre 2, juste après la virgule du dividende.",
  ana: [
    ["Combien de fois 3 tient-il dans 13 ?", "Quatre fois, avec un reste de 1."],
    ["On abaisse le 4 : combien de fois 3 tient-il dans 14 ?", "Quatre fois, avec un reste de 2."],
    ["Quel chiffre doit-on abaisser ensuite ?", "Le chiffre 2, qui suit la virgule."],
    ["Que fait-on au quotient à ce moment précis ?", "On place la virgule."],
    ["Pourquoi la placer justement là ?", "Parce qu'on quitte les unités pour entrer dans les dixièmes."],
    ["Quel est le quotient complet ?", "44,75."],
    ["Comment vérifier ce résultat ?", "En multipliant : 44,75 × 3 = 134,25."],
  ],
  syn: "Donc, pour diviser un décimal par un entier, on effectue la division comme pour des entiers, et l'on place la virgule au quotient au moment précis où l'on abaisse le premier chiffre situé après la virgule du dividende.",
  attention: "Oublier de placer la virgule au bon moment donne un quotient dix ou cent fois trop grand. Dès que vous abaissez le premier chiffre décimal, écrivez la virgule au quotient avant de poursuivre.",
  astuce: "Un ordre de grandeur protège de l'erreur : 134,25 partagé en 3, c'est environ 135 ÷ 3 = 45. Un quotient de 4,475 ou de 447,5 serait aussitôt suspect.",
  app: [
    { c: "Pose et calcule :\n1. 134,25 ÷ 3\n2. 45 ÷ 4\n3. 7 ÷ 8\n4. 100 ÷ 8",
      r: "1. [[44,75]]\n2. [[11,25]]\n3. [[0,875]]\n4. [[12,5]]" },
    { c: "On partage 593,46 ariary de bénéfice entre 42 vendeurs.\n1. Quelle opération faut-il faire ?\n2. Quel ordre de grandeur ?\n3. Quel est le quotient exact ?\n4. Vérifie ton résultat.",
      r: "1. [[Une division]] : 593,46 ÷ 42\n2. Environ [[600 ÷ 40 = 15]]\n3. [[14,13]]\n4. 14,13 × 42 = [[593,46]] : le calcul est juste" },
  ],
  evalx: [
    { c: "Calcule :\n1. 25,6 ÷ 4\n2. 9 ÷ 5\n3. 73,5 ÷ 7\n4. 1,44 ÷ 12",
      r: "1. [[6,4]]\n2. [[1,8]]\n3. [[10,5]]\n4. [[0,12]]" },
    { c: "Six amis se partagent équitablement une facture de 82,5 ariary de charges.\n1. Quelle opération ?\n2. Quelle part chacun paie-t-il ?\n3. Vérifie par une multiplication.\n4. Rédige la phrase réponse.",
      r: "1. [[Une division par 6]]\n2. [[13,75 ariary]]\n3. 13,75 × 6 = [[82,5]]\n4. « [[Chacun paie 13,75 ariary.]] »" },
  ],
  lecon: [
    ["1. Une division qui ne s'arrête pas au reste", "La division euclidienne s'arrêtait dès que le reste devenait plus petit que le diviseur. La {{division décimale}} va plus loin : elle poursuit le calcul après la virgule pour obtenir un quotient exact ou une valeur approchée."],
    ["2. La méthode", "On divise d'abord la partie entière comme pour des entiers. Au moment où l'on abaisse le premier chiffre situé {{après la virgule}} du dividende, on place la {{virgule}} au quotient, puis on continue normalement.\nExemple : 134,25 ÷ 3. On trouve 44 pour la partie entière, puis on abaisse le 2 en plaçant la virgule : le quotient est 44,75."],
    ["3. Quand le dividende est plus petit", "Si le dividende est inférieur au diviseur, le quotient commence par un zéro suivi de la virgule.\nAinsi 7 ÷ 8 = 0,875 : on écrit d'abord 0, puis la virgule, avant de poursuivre le calcul en ajoutant des zéros au dividende."],
    ["4. Vérifier son résultat", "Toute division se vérifie par une {{multiplication}} : le quotient multiplié par le diviseur doit redonner le dividende.\nPour 134,25 ÷ 3 = 44,75, on contrôle que 44,75 × 3 = 134,25. C'est exact.\nUn {{ordre de grandeur}} calculé au départ permet en outre de repérer immédiatement une virgule mal placée."],
  ],
  exos: [
    { pts: 4, c: "Pose et calcule 78,4 ÷ 8.",
      r: "[[9,8]]. Vérification : 9,8 × 8 = 78,4." },
    { pts: 4, c: "Pose et calcule 3 ÷ 4 et 9 ÷ 2.",
      r: "3 ÷ 4 = [[0,75]] ; 9 ÷ 2 = [[4,5]]." },
    { pts: 4, c: "Quatre personnes partagent 57 ariary. Quelle part chacune reçoit-elle ?",
      r: "57 ÷ 4 = [[14,25 ariary]]. « Chacune reçoit 14,25 ariary. »" },
    { pts: 4, c: "Donne un ordre de grandeur de 402,6 ÷ 5, puis le résultat exact.",
      r: "Environ 400 ÷ 5 = [[80]] ; résultat exact [[80,52]]." },
    { pts: 4, c: "Vrai ou faux ? 1. On place la virgule au quotient dès le début. 2. 7 ÷ 8 est inférieur à 1. 3. Une division se vérifie par une multiplication. 4. 12,5 ÷ 5 = 2,5.",
      r: "1. [[Faux]] : on la place quand on abaisse le premier chiffre décimal. 2. [[Vrai]] : le résultat est 0,875. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "La division décimale",
  titre: "Diviser par un nombre décimal",
  objectif: "À la fin de la séance, l'élève est capable de transformer une division par un décimal en division par un entier, en multipliant les deux termes par 10, 100 ou 1 000.",
  materiel: "Cahier à carreaux, tableau, ardoises",
  rev: [["Calcule 45 ÷ 4.", "11,25."],
        ["Calcule 12,76 × 10.", "127,6."],
        ["Calcule 8,8 × 10.", "88."]],
  mise: { q: "Combien de bouteilles de 0,5 L peut-on remplir avec 12 L d'eau ?", ra: "Vingt-quatre bouteilles." },
  obs: "Observez au tableau la division 12,76 ÷ 8,8, écrite sous forme de fraction. En dessous, le numérateur et le dénominateur ont tous deux été multipliés par 10.",
  ana: [
    ["Le diviseur 8,8 est-il un entier ?", "Non, il comporte une décimale."],
    ["Peut-on poser directement cette division ?", "Non, la méthode habituelle exige un diviseur entier."],
    ["Par combien a-t-on multiplié le dénominateur ?", "Par 10, ce qui donne 88."],
    ["Qu'a-t-on fait au numérateur ?", "On l'a aussi multiplié par 10 : 12,76 devient 127,6."],
    ["Pourquoi multiplier les deux ?", "Pour que le quotient ne change pas."],
    ["Quelle division doit-on maintenant effectuer ?", "127,6 divisé par 88."],
    ["Quel est le résultat ?", "1,45."],
    ["Ce résultat est-il celui de la division de départ ?", "Oui, il est identique."],
  ],
  syn: "Donc, pour diviser par un nombre décimal, on multiplie le dividende et le diviseur par 10, 100 ou 1 000 afin de rendre le diviseur entier. Le quotient reste inchangé, et l'on effectue ensuite la division comme d'habitude.",
  attention: "Il faut multiplier les deux termes par le même nombre. Multiplier seulement le diviseur donnerait un quotient faux : c'est l'erreur la plus courante de ce chapitre.",
  astuce: "Regardez uniquement le diviseur : autant de décimales, autant de zéros. Le diviseur 8,8 a une décimale, donc on multiplie tout par 10.",
  app: [
    { c: "Transforme en division par un entier, sans calculer :\n1. 12,76 ÷ 8,8\n2. 45 ÷ 1,5\n3. 6,3 ÷ 0,7\n4. 2,5 ÷ 0,25",
      r: "1. [[127,6 ÷ 88]]\n2. [[450 ÷ 15]]\n3. [[63 ÷ 7]]\n4. [[250 ÷ 25]]" },
    { c: "Calcule maintenant chacun de ces quotients.\n1. 127,6 ÷ 88\n2. 450 ÷ 15\n3. 63 ÷ 7\n4. 250 ÷ 25",
      r: "1. [[1,45]]\n2. [[30]]\n3. [[9]]\n4. [[10]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. 7,2 ÷ 0,9\n2. 15 ÷ 2,5\n3. 0,48 ÷ 0,6\n4. 100 ÷ 0,4",
      r: "1. [[8]]\n2. [[6]]\n3. [[0,8]]\n4. [[250]]" },
    { c: "On remplit des bidons de 2,5 L avec 60 L d'huile.\n1. Quelle division faut-il poser ?\n2. Transforme-la en division par un entier.\n3. Combien de bidons obtient-on ?\n4. Rédige la phrase réponse.",
      r: "1. [[60 ÷ 2,5]]\n2. [[600 ÷ 25]]\n3. [[24 bidons]]\n4. « [[On peut remplir 24 bidons.]] »" },
  ],
  lecon: [
    ["1. Le problème posé", "La méthode de la division ne fonctionne que si le {{diviseur}} est un nombre entier. Or on doit souvent diviser par un décimal : combien de bouteilles de 0,5 L dans 12 L, combien de bidons de 2,5 L dans 60 L."],
    ["2. La transformation", "On écrit d'abord la division sous forme de {{fraction}}, puis on multiplie le {{numérateur}} et le {{dénominateur}} par 10, 100 ou 1 000, jusqu'à ce que le diviseur devienne entier.\nCette opération ne change pas le quotient, car on agrandit les deux termes dans la même proportion."],
    ["3. Combien de zéros", "Le nombre de décimales du {{diviseur}} indique par quoi multiplier :\n— une décimale, on multiplie par 10 : 12,76 ÷ 8,8 devient 127,6 ÷ 88 ;\n— deux décimales, on multiplie par 100 : 2,5 ÷ 0,25 devient 250 ÷ 25.\nLe dividende suit toujours le même traitement, même s'il est déjà entier."],
    ["4. Un quotient parfois plus grand", "Diviser par un nombre {{inférieur à 1}} donne un quotient plus grand que le dividende : 100 ÷ 0,4 = 250.\nCela paraît surprenant, mais c'est logique : on cherche combien de fois 0,4 tient dans 100, et une petite quantité y tient de nombreuses fois."],
  ],
  exos: [
    { pts: 4, c: "Transforme puis calcule 8,4 ÷ 1,2.",
      r: "On multiplie par 10 : [[84 ÷ 12]] = [[7]]." },
    { pts: 4, c: "Calcule 3 ÷ 0,25 et 5,6 ÷ 0,8.",
      r: "3 ÷ 0,25 = 300 ÷ 25 = [[12]] ; 5,6 ÷ 0,8 = 56 ÷ 8 = [[7]]." },
    { pts: 4, c: "Combien de bouteilles de 0,75 L peut-on remplir avec 15 L de jus ?",
      r: "15 ÷ 0,75 = 1 500 ÷ 75 = [[20 bouteilles]]." },
    { pts: 4, c: "Explique pourquoi 20 ÷ 0,5 est plus grand que 20.",
      r: "Parce qu'on cherche combien de fois [[0,5 tient dans 20]] : une petite quantité y tient de nombreuses fois. Le résultat est [[40]]." },
    { pts: 4, c: "Vrai ou faux ? 1. On multiplie seulement le diviseur. 2. 6 ÷ 0,2 = 30. 3. Diviser par 0,1 revient à multiplier par 10. 4. Le quotient change quand on multiplie les deux termes.",
      r: "1. [[Faux]] : il faut multiplier les deux termes. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : le quotient reste identique." },
  ],
},
{
  ch: "La division décimale",
  titre: "Quotient exact et valeur approchée",
  objectif: "À la fin de la séance, l'élève est capable de distinguer un quotient exact d'un quotient approché et de donner un arrondi du quotient au rang demandé.",
  materiel: "Cahier à carreaux, tableau, ardoises",
  rev: [["Calcule 6,3 ÷ 0,7.", "9."],
        ["Calcule 9 ÷ 4.", "2,25."],
        ["Arrondis 3,47 au dixième.", "3,5."]],
  mise: { q: "On partage 10 ariary entre 3 personnes. Le partage tombe-t-il juste ?", ra: "Non, la division ne se termine pas." },
  obs: "Observez au tableau deux divisions posées côte à côte : 9 ÷ 4, qui s'arrête sur un reste nul, et 10 ÷ 3, dont le quotient s'écrit 3,333 et se poursuit encore.",
  ana: [
    ["Que vaut le quotient de 9 par 4 ?", "2,25 exactement."],
    ["Quel est le reste à la fin de ce calcul ?", "Zéro."],
    ["Et pour 10 divisé par 3 ?", "On obtient 3,333 et le calcul continue."],
    ["Le reste devient-il nul un jour ?", "Non, jamais."],
    ["Peut-on écrire le quotient exact de 10 par 3 avec une virgule ?", "Non, il faudrait une infinité de chiffres."],
    ["Que fait-on dans ce cas ?", "On donne une valeur approchée, par exemple 3,3 au dixième."],
    ["Quel signe utilise-t-on alors ?", "Le signe ≈, et non le signe =."],
  ],
  syn: "Donc, une division donne un quotient exact lorsque le reste finit par devenir nul. Sinon, le calcul ne s'arrête pas et l'on doit donner une valeur approchée du quotient, arrondie au rang demandé et notée avec le signe ≈.",
  attention: "Ne jamais écrire 10 ÷ 3 = 3,33. C'est faux : le quotient exact n'est pas 3,33. Il faut écrire 10 ÷ 3 ≈ 3,33, avec le signe d'approximation.",
  app: [
    { c: "Ces divisions donnent-elles un quotient exact ? Réponds par oui ou non.\n1. 9 ÷ 4\n2. 10 ÷ 3\n3. 7 ÷ 8\n4. 5 ÷ 6",
      r: "1. [[Oui]] : 2,25\n2. [[Non]]\n3. [[Oui]] : 0,875\n4. [[Non]]" },
    { c: "Donne le quotient de 10 ÷ 3 :\n1. arrondi à l'unité\n2. arrondi au dixième\n3. arrondi au centième\n4. Écris la relation avec le bon signe.",
      r: "1. [[3]]\n2. [[3,3]]\n3. [[3,33]]\n4. [[10 ÷ 3 ≈ 3,33]]" },
  ],
  evalx: [
    { c: "Donne une valeur approchée au centième :\n1. 22 ÷ 7\n2. 5 ÷ 3\n3. 1 ÷ 6\n4. 100 ÷ 9",
      r: "1. [[3,14]]\n2. [[1,67]]\n3. [[0,17]]\n4. [[11,11]]" },
    { c: "On partage 100 ariary entre 6 personnes.\n1. Le partage tombe-t-il juste ?\n2. Quelle est la part arrondie au centième ?\n3. Quel signe employer ?\n4. Combien reçoit-on en pratique, à l'ariary près ?",
      r: "1. [[Non]]\n2. [[16,67 ariary]]\n3. Le signe [[≈]]\n4. [[16 ariary]], le reste ne pouvant être partagé" },
  ],
  lecon: [
    ["1. Le quotient exact", "Une division donne un {{quotient exact}} lorsque le reste finit par devenir nul.\nAinsi 9 ÷ 4 = 2,25 : le calcul s'arrête, l'égalité est parfaite et l'on écrit le signe =."],
    ["2. Quand la division ne s'arrête pas", "Pour certaines divisions, le reste ne devient jamais nul. C'est le cas de 10 ÷ 3 : le quotient s'écrit 3,3333… et les chiffres se répètent indéfiniment.\nIl est alors impossible d'écrire le quotient exact avec un nombre fini de décimales."],
    ["3. La valeur approchée", "On donne alors une {{valeur approchée}}, arrondie au rang demandé :\n— à l'unité : 10 ÷ 3 ≈ 3 ;\n— au dixième : ≈ 3,3 ;\n— au centième : ≈ 3,33.\nOn emploie obligatoirement le signe {{≈}}, jamais le signe =."],
    ["4. Choisir le bon rang", "Le rang dépend de l'usage. Pour un prix en ariary, l'unité suffit ; pour une mesure de longueur, le centième est souvent utile.\nDans un problème concret, il faut aussi se demander si le résultat a un sens : on ne partage pas 16,67 ariary si la plus petite pièce vaut 1 ariary."],
  ],
  exos: [
    { pts: 4, c: "Parmi 12 ÷ 5 ; 7 ÷ 3 ; 18 ÷ 4 ; 2 ÷ 7, lesquelles ont un quotient exact ?",
      r: "[[12 ÷ 5 = 2,4]] et [[18 ÷ 4 = 4,5]] ont un quotient exact. Les deux autres n'en ont pas." },
    { pts: 4, c: "Donne 22 ÷ 7 arrondi au dixième puis au centième.",
      r: "Au dixième : [[≈ 3,1]]. Au centième : [[≈ 3,14]]." },
    { pts: 4, c: "Écris correctement le résultat de 4 ÷ 3 arrondi au centième.",
      r: "[[4 ÷ 3 ≈ 1,33]] : on emploie le signe d'approximation, car la division ne s'arrête pas." },
    { pts: 4, c: "Sept amis partagent 50 ariary. Quelle part chacun reçoit-il, arrondie au centième ?",
      r: "50 ÷ 7 [[≈ 7,14 ariary]]. En pratique chacun recevrait [[7 ariary]], le reste étant indivisible." },
    { pts: 4, c: "Vrai ou faux ? 1. Toute division a un quotient exact. 2. On écrit 10 ÷ 3 = 3,33. 3. Le signe ≈ signifie « est environ égal à ». 4. 9 ÷ 4 a un quotient exact.",
      r: "1. [[Faux]] : certaines ne s'arrêtent jamais. 2. [[Faux]] : il faut le signe ≈. 3. [[Vrai]]. 4. [[Vrai]] : il vaut 2,25." },
  ],
},
{
  ch: "La division décimale",
  titre: "Diviser par 10, 100 et 1 000",
  objectif: "À la fin de la séance, l'élève est capable de diviser un nombre par 10, 100 ou 1 000 et d'utiliser cette règle dans les conversions d'unités.",
  materiel: "Tableau de numération, tableau de conversion, ardoises",
  rev: [["Calcule 22 ÷ 7 au dixième près.", "Environ 3,1."],
        ["Calcule 4,8 ÷ 4.", "1,2."],
        ["Calcule 3,5 × 100.", "350."]],
  mise: { q: "Un sac de 2 500 g de sucre : combien cela fait-il de kilogrammes ?", ra: "2,5 kg." },
  obs: "Observez le tableau de numération : le nombre 52,8 y est écrit. L'enseignant déplace chaque étiquette-chiffre d'une colonne vers la droite.",
  ana: [
    ["Où se trouvait le chiffre 5 ?", "Dans la colonne des dizaines."],
    ["Où se trouve-t-il maintenant ?", "Dans celle des unités."],
    ["Sa valeur a-t-elle augmenté ou diminué ?", "Elle a été divisée par dix."],
    ["Quel nombre lit-on à présent ?", "5,28."],
    ["Par combien a-t-on donc divisé 52,8 ?", "Par 10."],
    ["Quel geste plus simple donne le même résultat ?", "Déplacer la virgule d'un rang vers la gauche."],
    ["Et pour diviser par 1 000 ?", "On déplace la virgule de trois rangs vers la gauche."],
    ["Que faire si les chiffres manquent ?", "On complète par des zéros devant le nombre."],
  ],
  syn: "Donc, pour diviser un nombre par 10, 100 ou 1 000, on déplace la virgule vers la gauche d'autant de rangs qu'il y a de zéros, en complétant si nécessaire par des zéros. Le nombre obtenu est toujours plus petit que celui de départ.",
  astuce: "Pour les conversions, retenez le sens : d'une petite unité vers une grande, on divise ; d'une grande vers une petite, on multiplie. Des grammes vers les kilogrammes, on divise par 1 000.",
  app: [
    { c: "Calcule :\n1. 52,8 ÷ 10\n2. 9 ÷ 100\n3. 1 250 ÷ 1 000\n4. 4,5 ÷ 10",
      r: "1. [[5,28]]\n2. [[0,09]]\n3. [[1,25]]\n4. [[0,45]]" },
    { c: "Convertis :\n1. 2 500 g en kilogrammes\n2. 450 cm en mètres\n3. 3 200 m en kilomètres\n4. 75 mm en centimètres",
      r: "1. [[2,5 kg]]\n2. [[4,5 m]]\n3. [[3,2 km]]\n4. [[7,5 cm]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. 84 ÷ 10\n2. 6,5 ÷ 100\n3. 920 ÷ 1 000\n4. 3 ÷ 10",
      r: "1. [[8,4]]\n2. [[0,065]]\n3. [[0,92]]\n4. [[0,3]]" },
    { c: "Complète :\n1. 340 ÷ …… = 34\n2. 78 ÷ …… = 0,78\n3. 5 ÷ …… = 0,005\n4. 12,5 ÷ …… = 1,25",
      r: "1. [[10]]\n2. [[100]]\n3. [[1 000]]\n4. [[10]]" },
  ],
  lecon: [
    ["1. La règle", "Pour diviser un nombre par 10, 100 ou 1 000, on déplace la {{virgule}} vers la {{gauche}} d'autant de rangs qu'il y a de zéros au diviseur.\n52,8 ÷ 10 = 5,28 ; 52,8 ÷ 100 = 0,528 ; 52,8 ÷ 1 000 = 0,0528."],
    ["2. Compléter par des zéros", "Lorsque les chiffres manquent pour déplacer la virgule, on ajoute des {{zéros}} devant le nombre.\n9 ÷ 100 : il faut reculer de deux rangs, on écrit donc 0,09.\n5 ÷ 1 000 = 0,005."],
    ["3. Le lien avec la multiplication", "Diviser par 10 revient exactement à multiplier par 0,1 ; diviser par 100 revient à multiplier par 0,01.\nCes deux opérations sont {{inverses}} : multiplier par 100 puis diviser par 100 ramène au nombre de départ."],
    ["4. L'usage dans les conversions", "Cette règle sert constamment pour changer d'unité :\n— des grammes aux kilogrammes, on divise par 1 000 : 2 500 g = 2,5 kg ;\n— des centimètres aux mètres, on divise par 100 : 450 cm = 4,5 m ;\n— des mètres aux kilomètres, on divise par 1 000 : 3 200 m = 3,2 km.\nOn divise en passant d'une {{petite}} unité à une {{grande}}."],
  ],
  exos: [
    { pts: 4, c: "Calcule : 630 ÷ 10 ; 45 ÷ 100 ; 8 ÷ 1 000 ; 27,5 ÷ 10.",
      r: "[[63]] ; [[0,45]] ; [[0,008]] ; [[2,75]]." },
    { pts: 4, c: "Convertis 4 750 g en kilogrammes et 620 cm en mètres.",
      r: "4 750 g = [[4,75 kg]] ; 620 cm = [[6,2 m]]." },
    { pts: 4, c: "Complète : 1 500 ÷ …… = 1,5 et 92 ÷ …… = 9,2.",
      r: "1 500 ÷ [[1 000]] = 1,5 ; 92 ÷ [[10]] = 9,2." },
    { pts: 4, c: "Une corde de 12,5 m est partagée en 100 morceaux égaux. Quelle est la longueur d'un morceau ?",
      r: "12,5 ÷ 100 = [[0,125 m]], soit [[12,5 cm]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Diviser par 10 agrandit le nombre. 2. 7 ÷ 100 = 0,07. 3. Diviser par 100 revient à multiplier par 0,01. 4. 2 000 g valent 2 kg.",
      r: "1. [[Faux]] : le nombre diminue. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "La division décimale",
  titre: "Problèmes de division",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème mêlant division, multiplication et soustraction, et d'interpréter le quotient selon le contexte.",
  materiel: "Énoncés au tableau, cahier de recherche, ardoises",
  rev: [["Calcule 84 ÷ 10.", "8,4."],
        ["Calcule 15 ÷ 2,5.", "6."],
        ["Convertis 3 000 g en kilogrammes.", "3 kg."]],
  mise: { q: "Comment calcule-t-on le prix d'un seul kilogramme quand on connaît le prix de plusieurs ?", ra: "On divise le prix total par le nombre de kilogrammes." },
  obs: "Lisez l'énoncé au tableau : « Une coopérative vend 45 kg de vanille pour 1 890 000 ariary. Un concurrent propose 32 kg pour 1 408 000 ariary. Quelle offre est la plus avantageuse ? »",
  ana: [
    ["Peut-on comparer directement les deux prix totaux ?", "Non, car les masses sont différentes."],
    ["Que faut-il calculer pour comparer ?", "Le prix d'un kilogramme dans chaque cas."],
    ["Quelle opération donne ce prix unitaire ?", "Une division du prix par la masse."],
    ["Combien vaut le kilogramme chez la coopérative ?", "42 000 ariary."],
    ["Et chez le concurrent ?", "44 000 ariary."],
    ["Quelle offre est la plus avantageuse ?", "Celle de la coopérative."],
    ["Qu'a permis la division ici ?", "De ramener les deux offres à une même unité de comparaison."],
  ],
  syn: "Donc, la division sert à partager en parts égales, mais aussi à calculer une valeur unitaire pour comparer des offres. On divise la grandeur totale par le nombre d'unités, puis on interprète le résultat en tenant compte du contexte.",
  attention: "Comparer deux prix totaux n'a aucun sens si les quantités diffèrent. Il faut toujours ramener à une même unité — le prix d'un kilogramme, d'un litre ou d'une pièce — avant de conclure.",
  app: [
    { c: "Une coopérative vend 45 kg de vanille pour 1 890 000 ariary ; un concurrent 32 kg pour 1 408 000 ariary.\n1. Quel est le prix du kilogramme chez la coopérative ?\n2. Et chez le concurrent ?\n3. Quelle offre est la plus avantageuse ?\n4. Quel écart au kilogramme ?",
      r: "1. [[42 000 ariary]]\n2. [[44 000 ariary]]\n3. [[Celle de la coopérative]]\n4. [[2 000 ariary]] de moins par kilogramme" },
    { c: "Un taxi-brousse parcourt 240 km en consommant 20 L de carburant.\n1. Quelle distance parcourt-il avec 1 L ?\n2. Combien de litres pour 360 km ?\n3. Quelle opération à la question 1 ?\n4. Et à la question 2 ?",
      r: "1. [[12 km]]\n2. [[30 L]]\n3. [[Une division]]\n4. [[Une division de 360 par 12]]" },
  ],
  evalx: [
    { c: "On partage équitablement 156,8 kg de riz entre 8 familles.\n1. Quelle masse par famille ?\n2. Quelle opération ?\n3. Vérifie par une multiplication.\n4. Rédige la phrase réponse.",
      r: "1. [[19,6 kg]]\n2. [[Une division par 8]]\n3. 19,6 × 8 = [[156,8]]\n4. « [[Chaque famille reçoit 19,6 kilogrammes de riz.]] »" },
    { c: "Un commerçant achète 60 kg de tomates pour 108 000 ariary et les revend 2 200 ariary le kilogramme.\n1. Quel est son prix d'achat au kilogramme ?\n2. Quel bénéfice par kilogramme ?\n3. Quel bénéfice total ?\n4. L'opération est-elle rentable ?",
      r: "1. [[1 800 ariary]]\n2. [[400 ariary]]\n3. [[24 000 ariary]]\n4. [[Oui]], le prix de vente dépasse le prix d'achat" },
  ],
  lecon: [
    ["1. Les deux sens de la division", "La division répond à deux questions différentes :\n— {{partager}} une quantité en parts égales : 156,8 kg entre 8 familles ;\n— chercher {{combien de fois}} une quantité est contenue dans une autre : combien de bidons de 2,5 L dans 60 L.\nDans les deux cas, l'opération est la même."],
    ["2. Calculer une valeur unitaire", "Diviser une grandeur totale par le nombre d'unités donne la {{valeur unitaire}} : le prix d'un kilogramme, la distance parcourue avec un litre, la part d'une personne.\n1 890 000 ÷ 45 = 42 000 ariary le kilogramme."],
    ["3. Comparer grâce à l'unité", "On ne peut pas comparer 1 890 000 ariary pour 45 kg et 1 408 000 ariary pour 32 kg : les quantités diffèrent.\nEn ramenant chaque offre au prix d'un {{kilogramme}}, la comparaison devient possible : 42 000 contre 44 000. La première offre est plus avantageuse."],
    ["4. Interpréter selon le contexte", "Le quotient doit toujours être relu à la lumière de la situation. Une part de 16,67 ariary n'a pas de sens si la plus petite pièce vaut 1 ariary.\nDe même, un nombre de véhicules ou de sacs doit être un {{entier}} : on arrondit alors au supérieur pour que rien ne soit oublié."],
  ],
  exos: [
    { pts: 4, c: "Douze cahiers coûtent 15 000 ariary. Quel est le prix d'un cahier ?",
      r: "15 000 ÷ 12 = [[1 250 ariary]]. « Un cahier coûte 1 250 ariary. »" },
    { pts: 4, c: "Une voiture parcourt 350 km avec 25 L. Quelle distance parcourt-elle avec 1 L ?",
      r: "350 ÷ 25 = [[14 km]] par litre." },
    { pts: 4, c: "Un lot A propose 5 kg pour 11 000 ariary, un lot B 8 kg pour 18 400 ariary. Lequel est le plus avantageux ?",
      r: "Lot A : 11 000 ÷ 5 = [[2 200 ariary/kg]]. Lot B : 18 400 ÷ 8 = [[2 300 ariary/kg]]. Le [[lot A]] est plus avantageux." },
    { pts: 4, c: "On partage 87,5 L d'huile dans des bidons de 2,5 L. Combien de bidons obtient-on ?",
      r: "87,5 ÷ 2,5 = 875 ÷ 25 = [[35 bidons]]." },
    { pts: 4, c: "Explique pourquoi il faut calculer un prix unitaire pour comparer deux offres.",
      r: "Parce que les [[quantités sont différentes]] : comparer deux prix totaux ne dit rien. En ramenant chaque offre au prix d'[[une même unité]], la comparaison devient possible." },
  ],
},

];
