// Période II — 20 séances. Division euclidienne et décimale, droites, longueurs.
module.exports = [
{
  ch: "La division euclidienne",
  titre: "Découvrir la division euclidienne",
  objectif: "À la fin de la séance, l'élève est capable de poser une division euclidienne et d'identifier le dividende, le diviseur, le quotient et le reste.",
  materiel: "Jetons de comptage, cahier à carreaux, ardoises",
  rev: [["Calcule 12 × 25.", "300."],
        ["Calcule 4,5 × 10.", "45."],
        ["Quel est le quart de 80 ?", "20."]],
  mise: { q: "Un commerçant veut ranger 423 œufs dans des plateaux de 18. Combien de plateaux remplira-t-il complètement ?", ra: "Il faut partager 423 par 18." },
  obs: "Observez la division posée au tableau : 423 divisé par 18. Le quotient 23 est inscrit à droite, et le nombre 9 apparaît en bas du calcul.",
  ana: [
    ["Quel nombre partage-t-on ?", "423 ; on l'appelle le dividende."],
    ["Par quel nombre le partage-t-on ?", "Par 18, qui est le diviseur."],
    ["Combien de fois 18 tient-il dans 423 ?", "23 fois ; c'est le quotient."],
    ["Que représente le nombre 9 ?", "Ce qui reste après le partage : le reste."],
    ["Vérifions : combien font 18 × 23 ?", "414."],
    ["Et 414 + 9 ?", "423, c'est-à-dire le dividende."],
    ["Le reste 9 est-il plus petit que le diviseur 18 ?", "Oui, et c'est obligatoire."],
    ["Que se passerait-il si le reste valait 20 ?", "On pourrait encore retirer un 18, donc le quotient serait faux."],
  ],
  syn: "Donc, effectuer la division euclidienne d'un entier par un autre, c'est trouver le quotient et le reste tels que dividende égale diviseur multiplié par quotient, plus le reste. Le reste est toujours strictement inférieur au diviseur.",
  attention: "Le reste doit toujours être plus petit que le diviseur. Un reste égal ou supérieur au diviseur signale que le quotient a été sous-estimé : il faut recommencer.",
  astuce: "Vérifiez toujours par la multiplication : diviseur × quotient + reste doit redonner exactement le dividende.",
  app: [
    { c: "Effectue les divisions euclidiennes et donne le quotient et le reste :\n1. 423 par 18\n2. 157 par 12\n3. 500 par 7\n4. 96 par 8",
      r: "1. Quotient [[23]], reste [[9]]\n2. Quotient [[13]], reste [[1]]\n3. Quotient [[71]], reste [[3]]\n4. Quotient [[12]], reste [[0]]" },
    { c: "Écris l'égalité de la division de 245 par 15, puis vérifie-la.\n1. Quel est le quotient ?\n2. Quel est le reste ?\n3. Écris l'égalité.\n4. Vérifie le calcul.",
      r: "1. [[16]]\n2. [[5]]\n3. [[245 = 15 × 16 + 5]]\n4. 15 × 16 = 240, puis 240 + 5 = [[245]] : l'égalité est vérifiée" },
  ],
  evalx: [
    { c: "Donne le quotient et le reste :\n1. 89 par 6\n2. 144 par 12\n3. 205 par 20\n4. 77 par 9",
      r: "1. Quotient [[14]], reste [[5]]\n2. Quotient [[12]], reste [[0]]\n3. Quotient [[10]], reste [[5]]\n4. Quotient [[8]], reste [[5]]" },
    { c: "On partage 250 cahiers entre 8 classes, de façon égale.\n1. Combien chaque classe reçoit-elle ?\n2. Combien de cahiers restent-ils ?\n3. Écris l'égalité de la division.\n4. Que faire des cahiers restants ?",
      r: "1. [[31 cahiers]]\n2. [[2 cahiers]]\n3. [[250 = 8 × 31 + 2]]\n4. Ils restent en réserve, car [[on ne peut pas les partager également]]" },
  ],
  lecon: [
    ["1. Le vocabulaire", "Effectuer la {{division euclidienne}} d'un entier par un autre, c'est chercher combien de fois le second est contenu dans le premier, et ce qui reste.\nQuatre mots sont à connaître : le {{dividende}} est le nombre que l'on partage, le {{diviseur}} celui par lequel on partage, le {{quotient}} le résultat du partage, et le {{reste}} ce qui n'a pas pu être partagé."],
    ["2. L'égalité fondamentale", "Toute division euclidienne se résume par une égalité :\ndividende = diviseur × quotient + reste.\nPour 423 partagé par 18 : 423 = 18 × 23 + 9.\nCette égalité sert à {{vérifier}} tout calcul de division."],
    ["3. La condition sur le reste", "Le reste doit toujours être {{strictement inférieur}} au diviseur.\nDans notre exemple, 9 est bien plus petit que 18. Si l'on avait trouvé un reste de 20, cela signifierait qu'un 18 supplémentaire pouvait encore être retiré : le quotient serait alors erroné."],
    ["4. Quand le reste est nul", "Lorsque le reste vaut zéro, le partage tombe juste. On dit alors que le dividende est {{divisible}} par le diviseur, ou qu'il en est un {{multiple}}.\nAinsi 96 = 8 × 12 + 0 : 96 est divisible par 8, et 96 est un multiple de 8."],
  ],
  exos: [
    { pts: 4, c: "Donne le quotient et le reste de la division de 347 par 25.",
      r: "Quotient [[13]], reste [[22]], car 25 × 13 = 325 et 347 − 325 = 22." },
    { pts: 4, c: "Écris l'égalité de la division de 1 000 par 30 et vérifie-la.",
      r: "[[1 000 = 30 × 33 + 10]]. Vérification : 30 × 33 = 990, puis 990 + 10 = 1 000." },
    { pts: 4, c: "Un carton contient 12 bouteilles. Combien de cartons complets remplit-on avec 150 bouteilles ? Combien en reste-t-il ?",
      r: "150 ÷ 12 donne quotient [[12]] et reste [[6]] : on remplit [[12 cartons complets]] et il reste [[6 bouteilles]]." },
    { pts: 4, c: "Dans une division par 9, quels restes sont possibles ?",
      r: "Les restes possibles vont de [[0 à 8]], car le reste est toujours strictement inférieur au diviseur." },
    { pts: 4, c: "Vrai ou faux ? 1. Le reste peut être égal au diviseur. 2. 45 = 7 × 6 + 3. 3. Un reste nul signifie que la division tombe juste. 4. Le quotient est toujours plus grand que le dividende.",
      r: "1. [[Faux]] : il est toujours plus petit. 2. [[Vrai]] : 42 + 3 = 45. 3. [[Vrai]]. 4. [[Faux]] : il est plus petit dès que le diviseur dépasse 1." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Multiples et diviseurs",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître un multiple et un diviseur d'un nombre, et d'employer correctement les quatre formulations équivalentes.",
  materiel: "Tableau des multiples, jetons, ardoises",
  rev: [["Quel est le reste de 96 divisé par 8 ?", "Zéro."],
        ["Écris l'égalité de 50 divisé par 7.", "50 = 7 × 7 + 1."],
        ["Le reste peut-il dépasser le diviseur ?", "Non, jamais."]],
  mise: { q: "Peut-on ranger exactement 12 chaises en rangées de 3, sans qu'il en reste ?", ra: "Oui, cela fait 4 rangées complètes." },
  obs: "Observez le tableau au tableau : la première ligne donne les multiples de 3 — 3, 6, 9, 12, 15, 18 — et la deuxième les diviseurs de 12 — 1, 2, 3, 4, 6, 12.",
  ana: [
    ["Comment obtient-on les multiples de 3 ?", "En multipliant 3 par 1, par 2, par 3, et ainsi de suite."],
    ["Combien y a-t-il de multiples de 3 ?", "Une infinité."],
    ["Le nombre 12 figure-t-il dans cette liste ?", "Oui, car 12 = 3 × 4."],
    ["Que peut-on dire alors de 3 par rapport à 12 ?", "3 est un diviseur de 12."],
    ["Combien 12 a-t-il de diviseurs ?", "Six : 1, 2, 3, 4, 6 et 12."],
    ["La liste des diviseurs est-elle infinie ?", "Non, elle est toujours limitée."],
    ["Quel est le reste de 12 divisé par 3 ?", "Zéro."],
    ["Comment dire cela de quatre façons ?", "12 est un multiple de 3 ; 3 est un diviseur de 12 ; 12 est divisible par 3 ; 3 divise 12."],
  ],
  syn: "Donc, lorsque le reste d'une division est nul, quatre formulations équivalentes existent : le dividende est un multiple du diviseur, le diviseur est un diviseur du dividende, le dividende est divisible par le diviseur, et le diviseur divise le dividende.",
  attention: "Ne confondez pas multiple et diviseur. Les multiples d'un nombre sont plus grands que lui et forment une liste infinie ; ses diviseurs sont plus petits ou égaux et forment une liste limitée.",
  app: [
    { c: "Écris les six premiers multiples de :\n1. 4\n2. 7\n3. 10\n4. 25",
      r: "1. [[4, 8, 12, 16, 20, 24]]\n2. [[7, 14, 21, 28, 35, 42]]\n3. [[10, 20, 30, 40, 50, 60]]\n4. [[25, 50, 75, 100, 125, 150]]" },
    { c: "Donne tous les diviseurs de :\n1. 12\n2. 20\n3. 15\n4. 7",
      r: "1. [[1, 2, 3, 4, 6, 12]]\n2. [[1, 2, 4, 5, 10, 20]]\n3. [[1, 3, 5, 15]]\n4. [[1 et 7]] seulement" },
  ],
  evalx: [
    { c: "Complète par « multiple » ou « diviseur » :\n1. 24 est un …… de 6.\n2. 6 est un …… de 24.\n3. 100 est un …… de 25.\n4. 5 est un …… de 45.",
      r: "1. [[multiple]]\n2. [[diviseur]]\n3. [[multiple]]\n4. [[diviseur]]" },
    { c: "Vrai ou faux ?\n1. 1 est diviseur de tous les nombres.\n2. Un nombre a une infinité de diviseurs.\n3. 18 est un multiple de 4.\n4. Tout nombre est multiple de lui-même.",
      r: "1. [[Vrai]].\n2. [[Faux]] : la liste des diviseurs est toujours limitée.\n3. [[Faux]] : 18 ÷ 4 laisse un reste de 2.\n4. [[Vrai]] : car il s'obtient en le multipliant par 1." },
  ],
  lecon: [
    ["1. Les multiples", "Les {{multiples}} d'un nombre s'obtiennent en le multipliant successivement par 1, 2, 3, 4…\nLes multiples de 3 sont 3, 6, 9, 12, 15, 18, et ainsi de suite : la liste est {{infinie}}.\nUn multiple d'un nombre est toujours supérieur ou égal à ce nombre."],
    ["2. Les diviseurs", "Un {{diviseur}} d'un nombre est un entier qui le divise sans laisser de reste.\nLes diviseurs de 12 sont 1, 2, 3, 4, 6 et 12 : la liste est toujours {{limitée}}.\nTout nombre admet au moins deux diviseurs : 1 et lui-même."],
    ["3. Quatre façons de dire la même chose", "Lorsque le reste de la division de 12 par 3 est nul, on peut écrire indifféremment :\n— 12 est un multiple de 3 ;\n— 3 est un diviseur de 12 ;\n— 12 est divisible par 3 ;\n— 3 divise 12.\nCes quatre phrases ont exactement le même sens."],
    ["4. Ne pas confondre", "Les multiples vont vers le {{haut}}, les diviseurs vers le {{bas}}. Dans la phrase « 12 est un multiple de 3 », le grand nombre est cité en premier ; dans « 3 est un diviseur de 12 », c'est le petit.\nRepérer lequel des deux nombres est le plus grand évite l'erreur."],
  ],
  exos: [
    { pts: 4, c: "Écris les cinq premiers multiples de 9 et de 15.",
      r: "Multiples de 9 : [[9, 18, 27, 36, 45]]. Multiples de 15 : [[15, 30, 45, 60, 75]]." },
    { pts: 4, c: "Donne tous les diviseurs de 30.",
      r: "[[1, 2, 3, 5, 6, 10, 15, 30]] : huit diviseurs en tout." },
    { pts: 4, c: "Le nombre 48 est-il un multiple de 6 ? Justifie par un calcul.",
      r: "[[Oui]], car 48 = 6 × 8 et le reste est nul : 48 est donc [[divisible par 6]]." },
    { pts: 4, c: "Trouve un nombre qui soit à la fois multiple de 4 et de 6.",
      r: "Par exemple [[12]], car 12 = 4 × 3 et 12 = 6 × 2. On peut aussi citer [[24]] ou [[36]]." },
    { pts: 4, c: "Complète : 56 est un …… de 8 et 8 est un …… de 56.",
      r: "56 est un [[multiple]] de 8 ; 8 est un [[diviseur]] de 56." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Les critères de divisibilité par 2, 5 et 10",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître sans calcul si un nombre est divisible par 2, par 5 ou par 10.",
  materiel: "Étiquettes-nombres, tableau, ardoises",
  rev: [["Cite trois multiples de 7.", "7, 14 et 21."],
        ["Donne les diviseurs de 10.", "1, 2, 5 et 10."],
        ["48 est-il divisible par 6 ?", "Oui, car 48 = 6 × 8."]],
  mise: { q: "Comment savoir très vite si l'on peut partager 3 476 bonbons entre deux enfants, sans reste ?", ra: "En regardant le dernier chiffre du nombre." },
  obs: "Observez ces deux colonnes au tableau : à gauche 18, 40, 56, 72, 134 ; à droite 35, 80, 125, 60, 205. L'enseignant souligne le dernier chiffre de chaque nombre.",
  ana: [
    ["Par quels chiffres se terminent les nombres de gauche ?", "Par 8, 0, 6, 2 et 4."],
    ["Ces nombres sont-ils tous divisibles par 2 ?", "Oui, tous."],
    ["Quelle règle peut-on en tirer ?", "Un nombre est divisible par 2 s'il se termine par 0, 2, 4, 6 ou 8."],
    ["Comment nomme-t-on ces nombres ?", "Des nombres pairs."],
    ["Par quels chiffres se terminent ceux de droite ?", "Par 5 ou par 0."],
    ["De quoi sont-ils tous divisibles ?", "De 5."],
    ["Lesquels sont aussi divisibles par 10 ?", "Ceux qui se terminent par 0 : 80 et 60."],
    ["Un nombre divisible par 10 l'est-il aussi par 2 et par 5 ?", "Oui, toujours."],
  ],
  syn: "Donc, un nombre est divisible par 2 s'il se termine par 0, 2, 4, 6 ou 8 ; il est divisible par 5 s'il se termine par 0 ou 5 ; il est divisible par 10 s'il se termine par 0. Un nombre divisible par 10 est nécessairement divisible par 2 et par 5.",
  astuce: "Un seul chiffre suffit : celui des unités. Nul besoin de poser la division pour ces trois critères.",
  app: [
    { c: "Ces nombres sont-ils divisibles par 2 ?\n1. 3 476\n2. 891\n3. 1 250\n4. 7 003",
      r: "1. [[Oui]], il se termine par 6\n2. [[Non]], il se termine par 1\n3. [[Oui]], il se termine par 0\n4. [[Non]], il se termine par 3" },
    { c: "Classe ces nombres selon qu'ils sont divisibles par 5, par 10, ou par aucun des deux : 45 ; 120 ; 83 ; 500.",
      r: "Divisibles par 5 seulement : [[45]]. Divisibles par 5 et par 10 : [[120 et 500]]. Par aucun des deux : [[83]]." },
  ],
  evalx: [
    { c: "Réponds par oui ou non :\n1. 2 340 est-il divisible par 10 ?\n2. 675 est-il divisible par 2 ?\n3. 675 est-il divisible par 5 ?\n4. 1 002 est-il divisible par 5 ?",
      r: "1. [[Oui]]\n2. [[Non]]\n3. [[Oui]]\n4. [[Non]]" },
    { c: "Complète le nombre 47… pour qu'il soit :\n1. divisible par 2\n2. divisible par 5\n3. divisible par 10\n4. divisible par 2 mais pas par 5",
      r: "1. Par exemple [[470, 472, 474, 476 ou 478]]\n2. [[470 ou 475]]\n3. [[470]]\n4. Par exemple [[472]]" },
  ],
  lecon: [
    ["1. Pourquoi des critères", "Poser une division pour savoir si un partage tombe juste prend du temps. Les {{critères de divisibilité}} permettent de répondre immédiatement, en observant seulement l'écriture du nombre."],
    ["2. Divisibilité par 2", "Un nombre est divisible par {{2}} lorsqu'il se termine par 0, 2, 4, 6 ou 8. On dit alors qu'il est {{pair}} ; sinon il est {{impair}}.\nExemples : 18, 40, 56, 72 et 134 sont pairs ; 891 et 7 003 sont impairs."],
    ["3. Divisibilité par 5 et par 10", "Un nombre est divisible par {{5}} lorsqu'il se termine par 0 ou par 5 : 35, 80, 125, 205.\nIl est divisible par {{10}} lorsqu'il se termine par 0 : 80, 120, 500.\nTout nombre divisible par 10 l'est aussi par 2 et par 5, puisque 10 = 2 × 5."],
    ["4. Une aide au quotidien", "Ces critères servent chaque fois qu'un partage doit tomber juste : répartir des élèves en deux groupes, échanger des pièces de 5 ariary, compter par dizaines.\nIls s'appliquent aussi bien aux petits qu'aux très grands nombres, car seul le chiffre des unités compte."],
  ],
  exos: [
    { pts: 4, c: "Parmi 234 ; 405 ; 1 000 ; 777, lesquels sont divisibles par 2 ?",
      r: "[[234 et 1 000]], car ils se terminent par 4 et par 0." },
    { pts: 4, c: "Parmi 65 ; 132 ; 900 ; 48, lesquels sont divisibles par 5 ?",
      r: "[[65 et 900]], car ils se terminent par 5 et par 0." },
    { pts: 4, c: "Quel est le plus petit nombre de trois chiffres divisible à la fois par 2, par 5 et par 10 ?",
      r: "[[100]] : il se termine par 0, donc il est divisible par les trois." },
    { pts: 4, c: "Un commerçant veut ranger 1 245 œufs par paquets de 10. Est-ce possible sans reste ? Justifie.",
      r: "[[Non]] : 1 245 se termine par 5, il n'est donc pas divisible par 10. Il restera [[5 œufs]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Tout nombre pair est divisible par 2. 2. 305 est divisible par 10. 3. Un nombre divisible par 10 est pair. 4. 0 est un nombre pair.",
      r: "1. [[Vrai]] : c'est la définition. 2. [[Faux]] : il se termine par 5, non par 0. 3. [[Vrai]]. 4. [[Vrai]] : il se termine par 0." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Les critères de divisibilité par 3 et par 9",
  objectif: "À la fin de la séance, l'élève est capable d'appliquer le critère de la somme des chiffres pour reconnaître un nombre divisible par 3 ou par 9.",
  materiel: "Étiquettes-nombres, tableau, ardoises",
  rev: [["3 476 est-il divisible par 2 ?", "Oui, il se termine par 6."],
        ["Quel critère pour la divisibilité par 5 ?", "Le nombre se termine par 0 ou par 5."],
        ["Cite deux multiples de 10.", "20 et 130."]],
  mise: { q: "Le nombre 432 est-il divisible par 3 ? Le dernier chiffre suffit-il pour répondre ?", ra: "Non, le dernier chiffre ne suffit pas ici." },
  obs: "Observez au tableau : sous chaque nombre, l'enseignant a écrit la somme de ses chiffres. Pour 432, il a écrit 4 + 3 + 2 = 9 ; pour 7 281, il a écrit 7 + 2 + 8 + 1 = 18.",
  ana: [
    ["Que vaut la somme des chiffres de 432 ?", "Neuf."],
    ["Ce nombre 9 est-il un multiple de 3 ?", "Oui, car 9 = 3 × 3."],
    ["Et 432 est-il divisible par 3 ?", "Oui, car 432 = 3 × 144."],
    ["Que vaut la somme des chiffres de 7 281 ?", "Dix-huit."],
    ["18 est-il multiple de 9 ?", "Oui, car 18 = 9 × 2."],
    ["Que peut-on en déduire pour 7 281 ?", "Il est divisible par 9."],
    ["Un nombre divisible par 9 l'est-il par 3 ?", "Oui, toujours, car 9 est lui-même multiple de 3."],
    ["La réciproque est-elle vraie ?", "Non : 12 est divisible par 3 mais pas par 9."],
  ],
  syn: "Donc, un nombre est divisible par 3 lorsque la somme de ses chiffres est un multiple de 3, et divisible par 9 lorsque cette somme est un multiple de 9. Tout nombre divisible par 9 est aussi divisible par 3, mais l'inverse est faux.",
  attention: "Pour 3 et 9, le dernier chiffre ne renseigne sur rien : il faut additionner tous les chiffres. Le nombre 20 se termine par 0 mais n'est divisible ni par 3 ni par 9.",
  astuce: "Si la somme obtenue reste grande, recommencez : pour 7 281, on trouve 18, puis 1 + 8 = 9. Le résultat final indique aussitôt la réponse.",
  app: [
    { c: "Calcule la somme des chiffres et dis si le nombre est divisible par 3 :\n1. 432\n2. 1 234\n3. 936\n4. 507",
      r: "1. Somme 9 : [[oui]]\n2. Somme 10 : [[non]]\n3. Somme 18 : [[oui]]\n4. Somme 12 : [[oui]]" },
    { c: "Ces nombres sont-ils divisibles par 9 ?\n1. 7 281\n2. 630\n3. 4 506\n4. 8 100",
      r: "1. Somme 18 : [[oui]]\n2. Somme 9 : [[oui]]\n3. Somme 15 : [[non]]\n4. Somme 9 : [[oui]]" },
  ],
  evalx: [
    { c: "Pour chaque nombre, indique s'il est divisible par 3, par 9, ou par les deux :\n1. 27\n2. 51\n3. 891\n4. 100",
      r: "1. [[Par 3 et par 9]] : somme 9\n2. [[Par 3 seulement]] : somme 6\n3. [[Par 3 et par 9]] : somme 18\n4. [[Par aucun]] : somme 1" },
    { c: "Complète le nombre 4…2 pour qu'il soit divisible par 3.\n1. Quelle est la somme des chiffres connus ?\n2. Quel chiffre peut convenir ?\n3. Donne deux solutions.\n4. Cette solution est-elle unique ?",
      r: "1. [[6]]\n2. Un chiffre tel que la somme soit multiple de 3 : [[0, 3, 6 ou 9]]\n3. Par exemple [[402 et 432]]\n4. [[Non]], plusieurs chiffres conviennent" },
  ],
  lecon: [
    ["1. Un critère différent", "Pour 2, 5 et 10, le chiffre des unités suffisait. Pour 3 et 9, il faut au contraire tenir compte de {{tous les chiffres}} du nombre."],
    ["2. Divisibilité par 3", "Un nombre est divisible par {{3}} lorsque la {{somme de ses chiffres}} est un multiple de 3.\nExemple : pour 432, on calcule 4 + 3 + 2 = 9. Comme 9 est multiple de 3, le nombre 432 est divisible par 3. On vérifie : 432 = 3 × 144."],
    ["3. Divisibilité par 9", "Un nombre est divisible par {{9}} lorsque la somme de ses chiffres est un multiple de 9.\nExemple : pour 7 281, on calcule 7 + 2 + 8 + 1 = 18. Comme 18 est multiple de 9, le nombre 7 281 est divisible par 9."],
    ["4. Le lien entre 3 et 9", "Tout nombre divisible par {{9}} est aussi divisible par {{3}}, puisque 9 est lui-même un multiple de 3.\nLa réciproque est fausse : 12 est divisible par 3, car 1 + 2 = 3, mais pas par 9.\nSi la somme obtenue reste grande, on peut recommencer l'opération : pour 7 281, on passe de 18 à 1 + 8 = 9."],
  ],
  exos: [
    { pts: 4, c: "Parmi 123 ; 450 ; 682 ; 999, lesquels sont divisibles par 3 ?",
      r: "[[123]] (somme 6), [[450]] (somme 9) et [[999]] (somme 27) le sont. [[682]] ne l'est pas, sa somme vaut 16." },
    { pts: 4, c: "Parmi 279 ; 405 ; 511 ; 720, lesquels sont divisibles par 9 ?",
      r: "[[279]] (somme 18), [[405]] (somme 9) et [[720]] (somme 9) le sont. [[511]] ne l'est pas, sa somme vaut 7." },
    { pts: 4, c: "Le nombre 1 458 est-il divisible par 3 ? par 9 ? Justifie.",
      r: "La somme de ses chiffres vaut 1 + 4 + 5 + 8 = 18. Il est donc divisible [[par 3 et par 9]]." },
    { pts: 4, c: "Trouve le chiffre manquant pour que 5…4 soit divisible par 9.",
      r: "La somme connue est 5 + 4 = 9 ; il faut atteindre un multiple de 9. Le chiffre [[0]] convient (somme 9), de même que [[9]] (somme 18)." },
    { pts: 4, c: "Vrai ou faux ? 1. 20 est divisible par 3. 2. Tout nombre divisible par 9 l'est par 3. 3. Tout nombre divisible par 3 l'est par 9. 4. La somme des chiffres de 636 est 15.",
      r: "1. [[Faux]] : sa somme vaut 2. 2. [[Vrai]]. 3. [[Faux]] : 12 en est un contre-exemple. 4. [[Vrai]] : 6 + 3 + 6 = 15, donc 636 est divisible par 3." },
  ],
},
{
  ch: "La division euclidienne",
  titre: "Problèmes de partage",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème de partage en interprétant correctement le quotient et le reste selon la question posée.",
  materiel: "Énoncés au tableau, jetons, cahier de recherche",
  rev: [["936 est-il divisible par 3 ?", "Oui, la somme de ses chiffres vaut 18."],
        ["Quel est le reste de 50 divisé par 8 ?", "Deux."],
        ["Cite un critère de divisibilité par 5.", "Le nombre se termine par 0 ou 5."]],
  mise: { q: "Cinquante élèves doivent monter dans des taxis-brousse de 12 places. Combien de véhicules faut-il ?", ra: "Cinq, car quatre ne suffiraient pas pour tout le monde." },
  obs: "Observez au tableau la division de 50 par 12 : le quotient est 4 et le reste 2. À côté, trois questions différentes sont écrites sur cette même situation.",
  ana: [
    ["Combien de taxis-brousse sont pleins ?", "Quatre."],
    ["Combien d'élèves ne sont pas encore placés ?", "Deux."],
    ["Combien de véhicules faut-il en tout ?", "Cinq, car il faut un véhicule pour les deux derniers."],
    ["Pourquoi la réponse n'est-elle pas 4 ?", "Parce que le reste doit aussi être transporté."],
    ["Si la question portait sur les véhicules complets, que répondrait-on ?", "Quatre."],
    ["La division est-elle la même dans les deux cas ?", "Oui, seule l'interprétation change."],
    ["Que faut-il donc lire avec attention ?", "La question posée."],
  ],
  syn: "Donc, dans un problème de partage, la division donne toujours le même quotient et le même reste, mais la réponse dépend de la question. Si l'on cherche un nombre de parts complètes, on retient le quotient ; si tout doit être pris en charge, on ajoute une part supplémentaire pour le reste.",
  attention: "Ne répondez jamais mécaniquement par le quotient. Pour transporter 50 élèves dans des véhicules de 12 places, la réponse est 5 et non 4 : les deux élèves restants ont aussi besoin d'une place.",
  app: [
    { c: "Cinquante élèves voyagent dans des taxis-brousse de 12 places.\n1. Quel est le quotient de 50 par 12 ?\n2. Quel est le reste ?\n3. Combien de véhicules sont pleins ?\n4. Combien de véhicules faut-il en tout ?",
      r: "1. [[4]]\n2. [[2]]\n3. [[4 véhicules pleins]]\n4. [[5 véhicules]], car les 2 élèves restants doivent aussi voyager" },
    { c: "On partage 250 kg de riz dans des sacs de 30 kg.\n1. Combien de sacs pleins obtient-on ?\n2. Quelle masse reste-t-il ?\n3. Combien de sacs faut-il pour tout ranger ?\n4. Écris l'égalité de la division.",
      r: "1. [[8 sacs pleins]]\n2. [[10 kg]]\n3. [[9 sacs]]\n4. [[250 = 30 × 8 + 10]]" },
  ],
  evalx: [
    { c: "Une école de 148 élèves forme des groupes de 6.\n1. Combien de groupes complets ?\n2. Combien d'élèves restent-ils ?\n3. Combien de groupes si personne n'est laissé de côté ?\n4. Écris l'égalité de la division.",
      r: "1. [[24 groupes]]\n2. [[4 élèves]]\n3. [[25 groupes]]\n4. [[148 = 6 × 24 + 4]]" },
    { c: "On dispose de 500 ariary en pièces de 50 ariary.\n1. Combien de pièces obtient-on ?\n2. Reste-t-il de la monnaie ?\n3. La division tombe-t-elle juste ?\n4. Que peut-on dire de 500 par rapport à 50 ?",
      r: "1. [[10 pièces]]\n2. [[Non]]\n3. [[Oui]], le reste est nul\n4. [[500 est un multiple de 50]]" },
  ],
  lecon: [
    ["1. Reconnaître un partage", "On divise lorsqu'il faut {{répartir}} une quantité en parts égales, ou chercher combien de fois une quantité est contenue dans une autre.\nRanger 250 kg de riz dans des sacs de 30 kg, répartir 148 élèves en groupes de 6 : ce sont des divisions."],
    ["2. Interpréter le quotient", "Le {{quotient}} indique le nombre de parts complètes obtenues.\nPour 50 élèves et des véhicules de 12 places, le quotient 4 signifie que quatre véhicules seront pleins."],
    ["3. Interpréter le reste", "Le {{reste}} représente ce qui n'entre pas dans une part complète.\nIci, 2 élèves restent sans véhicule. Selon la question, ce reste conduit à des réponses différentes :\n— « combien de véhicules pleins ? » → 4 ;\n— « combien de véhicules faut-il ? » → 5, car les deux derniers élèves doivent voyager."],
    ["4. Lire la question jusqu'au bout", "Une même division peut donc mener à deux réponses correctes selon ce qui est demandé. C'est la {{question}}, et non le calcul, qui décide.\nOn termine toujours par une phrase réponse précisant l'unité : « Il faut 5 taxis-brousse. »"],
  ],
  exos: [
    { pts: 4, c: "On range 200 livres sur des étagères de 18 livres. Combien d'étagères sont pleines ? Combien de livres restent-ils ?",
      r: "200 ÷ 18 donne quotient [[11]] et reste [[2]] : [[11 étagères pleines]] et [[2 livres restants]]." },
    { pts: 4, c: "Combien d'étagères faut-il pour ranger la totalité de ces 200 livres ?",
      r: "[[12 étagères]] : les 11 pleines, plus une douzième pour les 2 livres restants." },
    { pts: 4, c: "On partage 96 bonbons entre 8 enfants. Chacun reçoit combien ? Reste-t-il des bonbons ?",
      r: "Chacun reçoit [[12 bonbons]] et il ne reste [[rien]] : 96 est un multiple de 8." },
    { pts: 4, c: "Un car de 45 places doit transporter 130 personnes. Combien de voyages faut-il ?",
      r: "130 ÷ 45 donne quotient 2 et reste 40 : il faut [[3 voyages]], car les 40 personnes restantes doivent être transportées." },
    { pts: 4, c: "Explique pourquoi la réponse à un problème de partage n'est pas toujours le quotient.",
      r: "Parce que le [[reste]] doit parfois être pris en charge lui aussi. Si tout doit être transporté ou rangé, on ajoute [[une part supplémentaire]] au quotient." },
  ],
},
];
