// Période I — 20 séances. Contenu entièrement rédigé pour la Collection J-Learn.
// Contexte malgache, séparateur décimal = virgule, aucune date calendaire.
// Champs : rev, mise, obs, ana[[Q,RA]], syn, app[], evalx[], lecon[], exos[]

const DOC = "Programme officiel de Mathématiques, classe de 6e — RAPS 6e";

module.exports = [
// ─────────────────────────────────────────── Ch. 1 — Les nombres entiers naturels
{
  ch: "Les nombres entiers naturels",
  titre: "Lire et écrire les nombres entiers naturels",
  objectif: "À la fin de la séance, l'élève est capable de lire et d'écrire correctement un nombre entier naturel jusqu'à la classe des millions, en chiffres et en lettres.",
  materiel: "Tableau de numération tracé au tableau, ardoises, étiquettes-chiffres",
  rev: [["Combien de chiffres utilise-t-on pour écrire tous les nombres ?", "Dix chiffres : 0, 1, 2, 3, 4, 5, 6, 7, 8 et 9."],
        ["Écris le nombre trois cent quarante-deux.", "342."],
        ["Quel est le chiffre des dizaines dans 87 ?", "Le chiffre 8."]],
  mise: { q: "Le recensement annonce que la population d'Antananarivo dépasse un million d'habitants. Comment écrit-on ce nombre en chiffres ?", ra: "1 000 000." },
  obs: "Regardez bien le tableau de numération affiché : il comporte les classes des millions, des mille et des unités, chacune divisée en centaines, dizaines et unités. Le nombre 3 254 108 y est placé, un chiffre par colonne.",
  ana: [
    ["Combien de classes voyez-vous dans ce tableau ?", "Trois classes : les millions, les mille et les unités simples."],
    ["Combien de colonnes contient chaque classe ?", "Trois colonnes : centaines, dizaines et unités."],
    ["Dans 3 254 108, quel chiffre occupe la colonne des millions ?", "Le chiffre 3."],
    ["Que représente le chiffre 5 dans ce nombre ?", "Il représente 5 dizaines de mille, c'est-à-dire 50 000."],
    ["Pourquoi laisse-t-on un espace entre les groupes de trois chiffres ?", "Pour séparer les classes et rendre le nombre plus facile à lire."],
    ["Comment lit-on ce nombre à voix haute ?", "Trois millions deux cent cinquante-quatre mille cent huit."],
  ],
  syn: "Donc, un nombre entier naturel s'écrit avec les dix chiffres, groupés par tranches de trois à partir de la droite. Chaque tranche forme une classe : unités, mille, millions. La position d'un chiffre indique sa valeur.",
  app: [
    { c: "Écris en chiffres les nombres suivants :\n1. Quatre-vingt-douze mille trois cents\n2. Sept millions cinq cent mille\n3. Deux cent six mille quatorze\n4. Un million un",
      r: "1. [[92 300]]\n2. [[7 500 000]]\n3. [[206 014]]\n4. [[1 000 001]]" },
    { c: "Dans le nombre 8 407 165, indique la valeur du chiffre demandé :\n1. le chiffre 8\n2. le chiffre 4\n3. le chiffre 7\n4. le chiffre 6",
      r: "1. [[8 millions]], soit 8 000 000\n2. [[4 centaines de mille]], soit 400 000\n3. [[7 unités de mille]], soit 7 000\n4. [[6 dizaines]], soit 60" },
  ],
  evalx: [
    { c: "Écris en lettres :\n1. 5 060\n2. 340 000\n3. 1 200 500\n4. 90 009",
      r: "1. [[Cinq mille soixante]]\n2. [[Trois cent quarante mille]]\n3. [[Un million deux cent mille cinq cents]]\n4. [[Quatre-vingt-dix mille neuf]]" },
    { c: "Recopie et complète par le mot qui convient (classe, chiffre, position) :\n1. Un nombre s'écrit à l'aide de dix ……\n2. La valeur d'un chiffre dépend de sa ……\n3. Les millions forment une ……\n4. On sépare les …… par un espace.",
      r: "1. [[chiffres]]\n2. [[position]]\n3. [[classe]]\n4. [[classes]]" },
  ],
  lecon: [
    ["1. Les dix chiffres", "Tout nombre entier naturel s'écrit à l'aide des dix {{chiffres}} : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9. Il ne faut pas confondre un {{chiffre}}, qui est un signe d'écriture, et un {{nombre}}, qui exprime une quantité. Ainsi 47 est un nombre écrit avec deux chiffres."],
    ["2. Le tableau de numération", "Les chiffres se rangent par {{classes}} de trois colonnes : la classe des unités, celle des mille, celle des millions. Dans chaque classe on trouve les centaines (C), les dizaines (D) et les unités (U).\nPour le nombre 3 254 108 : 3 est le chiffre des millions, 2 celui des centaines de mille, 5 celui des dizaines de mille, 4 celui des unités de mille, 1 celui des centaines, 0 celui des dizaines et 8 celui des unités."],
    ["3. La valeur de position", "La {{position}} d'un chiffre indique la quantité qu'il représente. Dans 3 254 108, le chiffre 5 ne vaut pas 5 mais 50 000, car il occupe la colonne des dizaines de mille. C'est ce que l'on appelle la {{valeur de position}}."],
    ["4. Lire et écrire", "On lit un nombre classe par classe, en partant de la gauche. On écrit un espace entre les classes, jamais un point ni une virgule : on écrit 1 250 000, et non 1.250.000.\nExemple : la commune de Toamasina compte 326 289 habitants ; on lit « trois cent vingt-six mille deux cent quatre-vingt-neuf »."],
  ],
  exos: [
    { pts: 4, c: "Écris en chiffres : quatre cent mille sept ; douze millions ; soixante-quinze mille quatre-vingts ; neuf cent neuf.",
      r: "[[400 007]] ; [[12 000 000]] ; [[75 080]] ; [[909]]." },
    { pts: 4, c: "Dans 6 703 480, donne la valeur du chiffre 7, puis celle du chiffre 3.",
      r: "Le chiffre 7 vaut [[700 000]] car il occupe la colonne des centaines de mille. Le chiffre 3 vaut [[3 000]] car il occupe celle des unités de mille." },
    { pts: 4, c: "Écris en lettres 2 040 600.",
      r: "[[Deux millions quarante mille six cents]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 45 est un chiffre. 2. Dans 508, le 0 ne sert à rien. 3. On sépare les classes par un espace. 4. Le chiffre des unités de 3 271 est 1.",
      r: "1. [[Faux]] : 45 est un nombre écrit avec deux chiffres. 2. [[Faux]] : le 0 marque l'absence de dizaines et maintient le 5 dans la colonne des centaines. 3. [[Vrai]]. 4. [[Vrai]]." },
    { pts: 4, c: "Range dans l'ordre croissant : 90 100 ; 9 100 ; 901 000 ; 91 000.",
      r: "[[9 100 < 90 100 < 91 000 < 901 000]]." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Comparer et ranger les nombres entiers",
  objectif: "À la fin de la séance, l'élève est capable de comparer deux entiers naturels et de ranger une liste de nombres dans l'ordre croissant ou décroissant.",
  materiel: "Étiquettes portant des nombres, ardoises, tableau de numération",
  rev: [["Quelle est la valeur du chiffre 4 dans 34 800 ?", "4 000, car il occupe la colonne des unités de mille."],
        ["Écris en chiffres : deux cent mille dix.", "200 010."],
        ["Combien de classes compte 5 400 000 ?", "Trois : millions, mille et unités."]],
  mise: { q: "Deux communes déclarent 12 480 et 12 840 habitants. Laquelle est la plus peuplée ?", ra: "Celle de 12 840 habitants." },
  obs: "Observez ces deux nombres écrits l'un sous l'autre dans le tableau de numération, chiffre sous chiffre : 12 480 et 12 840.",
  ana: [
    ["Ces deux nombres ont-ils le même nombre de chiffres ?", "Oui, cinq chiffres chacun."],
    ["Par où commence-t-on alors la comparaison ?", "Par la gauche, c'est-à-dire par le chiffre le plus fort."],
    ["Les chiffres des dizaines de mille sont-ils différents ?", "Non, c'est 1 dans les deux nombres."],
    ["Et ceux des unités de mille ?", "Non plus, c'est 2 dans les deux cas."],
    ["Quel est le premier rang où les chiffres diffèrent ?", "Le rang des centaines : 4 pour le premier, 8 pour le second."],
    ["Quelle conclusion tire-t-on ?", "Comme 8 est plus grand que 4, on écrit 12 840 > 12 480."],
    ["Et si deux nombres n'ont pas le même nombre de chiffres ?", "Le plus grand est celui qui a le plus de chiffres."],
  ],
  syn: "Donc, pour comparer deux entiers, on compte d'abord les chiffres : celui qui en a le plus est le plus grand. À nombre de chiffres égal, on compare rang par rang en partant de la gauche, jusqu'au premier rang où les chiffres diffèrent.",
  app: [
    { c: "Complète par < ou > :\n1. 7 205 … 7 502\n2. 48 000 … 9 999\n3. 130 400 … 130 040\n4. 999 … 1 000",
      r: "1. 7 205 [[<]] 7 502\n2. 48 000 [[>]] 9 999\n3. 130 400 [[>]] 130 040\n4. 999 [[<]] 1 000" },
    { c: "Range dans l'ordre croissant : 5 060 ; 5 600 ; 5 006 ; 5 660.",
      r: "[[5 006 < 5 060 < 5 600 < 5 660]]" },
  ],
  evalx: [
    { c: "Range dans l'ordre décroissant : 87 090 ; 87 900 ; 8 790 ; 87 009.",
      r: "[[87 900 > 87 090 > 87 009 > 8 790]]" },
    { c: "Encadre chaque nombre entre deux centaines consécutives :\n1. 347\n2. 1 208\n3. 5 099\n4. 660",
      r: "1. [[300 < 347 < 400]]\n2. [[1 200 < 1 208 < 1 300]]\n3. [[5 000 < 5 099 < 5 100]]\n4. [[600 < 660 < 700]]" },
  ],
  lecon: [
    ["1. Comparer deux nombres", "{{Comparer}} deux nombres, c'est dire s'ils sont égaux, ou lequel est le plus grand. On utilise les signes {{<}} (« est inférieur à »), {{>}} (« est supérieur à ») et {{=}} (« est égal à »).\nLa pointe du signe est toujours tournée vers le plus petit nombre : 7 < 12 se lit « 7 est inférieur à 12 »."],
    ["2. La méthode", "a) On compare le nombre de chiffres : celui qui en a le plus est le plus grand. Ainsi 1 000 > 999.\nb) Si les deux nombres ont autant de chiffres, on compare rang par rang en partant de la gauche. Au premier rang où les chiffres diffèrent, le plus grand chiffre donne le plus grand nombre.\nExemple : 12 840 et 12 480 ont les mêmes chiffres de gauche jusqu'aux centaines, où 8 > 4 ; donc 12 840 > 12 480."],
    ["3. Ranger une liste", "{{Ranger}} des nombres dans l'ordre {{croissant}}, c'est les écrire du plus petit au plus grand. Dans l'ordre {{décroissant}}, c'est l'inverse.\nExemple croissant : 405 < 450 < 504 < 540."],
    ["4. Encadrer un nombre", "{{Encadrer}} un nombre, c'est trouver un nombre plus petit et un nombre plus grand que lui. Pour encadrer 3 472 entre deux milliers : 3 000 < 3 472 < 4 000."],
  ],
  exos: [
    { pts: 4, c: "Complète par < ou > : 6 090 … 6 900 ; 24 000 … 8 999 ; 501 … 510 ; 100 000 … 99 999.",
      r: "6 090 [[<]] 6 900 ; 24 000 [[>]] 8 999 ; 501 [[<]] 510 ; 100 000 [[>]] 99 999." },
    { pts: 4, c: "Range dans l'ordre croissant : 4 007 ; 4 700 ; 4 070 ; 4 077.",
      r: "[[4 007 < 4 070 < 4 077 < 4 700]]." },
    { pts: 4, c: "Range dans l'ordre décroissant : 32 100 ; 3 210 ; 321 000 ; 32 010.",
      r: "[[321 000 > 32 100 > 32 010 > 3 210]]." },
    { pts: 4, c: "Encadre 7 845 entre deux milliers consécutifs, puis entre deux centaines consécutives.",
      r: "[[7 000 < 7 845 < 8 000]] et [[7 800 < 7 845 < 7 900]]." },
    { pts: 4, c: "Écris le plus grand et le plus petit nombre de quatre chiffres différents que l'on peut former avec 3, 0, 7 et 5.",
      r: "Le plus grand est [[7 530]] ; le plus petit est [[3 057]] (un nombre ne peut pas commencer par 0)." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "La demi-droite graduée et l'abscisse",
  objectif: "À la fin de la séance, l'élève est capable de placer un entier sur une demi-droite graduée et de lire l'abscisse d'un point.",
  materiel: "Règle graduée, double décimètre, demi-droite tracée au tableau",
  rev: [["Complète : 4 500 … 4 050.", "4 500 > 4 050."],
        ["Range dans l'ordre croissant : 12 ; 21 ; 2.", "2 < 12 < 21."],
        ["Quel est le plus petit entier naturel ?", "Zéro."]],
  mise: { q: "Sur la règle graduée de votre trousse, que représentent les petits traits régulièrement espacés ?", ra: "Les graduations, qui servent à mesurer." },
  obs: "Observez la droite tracée au tableau : elle part d'un point marqué O, porte des traits régulièrement espacés, et les points A et B y sont placés. Sous O est écrit 0, sous le trait suivant 1.",
  ana: [
    ["Quel nombre est écrit sous le point O ?", "Le nombre 0 ; on l'appelle l'origine."],
    ["Quelle distance sépare deux traits voisins ?", "Toujours la même : c'est l'unité de longueur."],
    ["Combien d'unités séparent O du point A ?", "Trois unités."],
    ["Quel nombre associe-t-on alors au point A ?", "Le nombre 3."],
    ["Comment appelle-t-on ce nombre ?", "L'abscisse du point A ; on écrit A(3)."],
    ["Deux points différents peuvent-ils avoir la même abscisse ?", "Non, chaque point de la droite a une seule abscisse."],
  ],
  syn: "Donc, graduer une demi-droite, c'est choisir une origine associée à 0 et une unité que l'on reporte régulièrement. Le nombre associé à un point s'appelle son abscisse et s'écrit entre parenthèses après le nom du point.",
  app: [
    { c: "Trace une demi-droite graduée d'origine O avec 1 cm pour unité, puis place les points A(2), B(5) et C(7).",
      r: "Après avoir reporté sept fois 1 cm : [[A est au 2e trait, B au 5e, C au 7e]]. Le point C est le plus éloigné de l'origine." },
    { c: "Sur une demi-droite graduée, un point M est situé 9 unités après l'origine. 1. Quelle est son abscisse ? 2. Écris-la correctement. 3. Quel point est plus proche de O : M ou N(4) ? 4. Combien d'unités séparent M de N ?",
      r: "1. [[9]]\n2. [[M(9)]]\n3. [[N(4)]]\n4. [[5 unités]], car 9 − 4 = 5." },
  ],
  evalx: [
    { c: "Lis les abscisses : sur une demi-droite d'unité 1, le point P est au 6e trait, Q au 11e, R au 0e, S au 15e.",
      r: "[[P(6)]], [[Q(11)]], [[R(0)]] qui est l'origine, [[S(15)]]." },
    { c: "Complète : 1. L'origine a pour abscisse …… 2. Le nombre associé à un point s'appelle son …… 3. Les graduations sont …… espacées. 4. Le point d'abscisse 8 est plus …… de l'origine que celui d'abscisse 3.",
      r: "1. [[0]]\n2. [[abscisse]]\n3. [[régulièrement]]\n4. [[éloigné]]" },
  ],
  lecon: [
    ["1. Graduer une demi-droite", "{{Graduer}} une demi-droite, c'est choisir sur elle un point appelé {{origine}}, auquel on associe le nombre 0, puis une {{unité}} de longueur que l'on reporte régulièrement à partir de cette origine."],
    ["2. L'abscisse d'un point", "À chaque graduation correspond un nombre entier. Le nombre associé à un point s'appelle son {{abscisse}}. On l'écrit entre parenthèses juste après le nom du point : A(3) se lit « A a pour abscisse 3 ».\nL'origine O a pour abscisse 0."],
    ["3. Lire et placer", "Pour lire l'abscisse d'un point, on compte le nombre d'unités qui le séparent de l'origine. Pour placer un point d'abscisse donnée, on reporte ce nombre d'unités à partir de l'origine.\nPlus l'abscisse est grande, plus le point est éloigné de l'origine : c'est pourquoi la demi-droite graduée permet aussi de comparer les nombres."],
    ["4. Une lecture utile", "La demi-droite graduée se retrouve partout : sur la règle de la trousse, sur le mètre-ruban du menuisier, sur la graduation d'un thermomètre. Dans chaque cas, l'origine et l'unité sont fixées d'avance."],
  ],
  exos: [
    { pts: 4, c: "Trace une demi-droite graduée d'unité 1 cm et place A(4), B(7) et C(10).",
      r: "On reporte 1 cm dix fois depuis O : [[A au 4e trait, B au 7e, C au 10e]]." },
    { pts: 4, c: "Un point D est placé 12 unités après l'origine. Écris son abscisse et compare-la à celle de E(12).",
      r: "[[D(12)]] ; D et E ont [[la même abscisse]], ils sont donc confondus." },
    { pts: 4, c: "Combien d'unités séparent les points d'abscisses 15 et 6 ?",
      r: "[[9 unités]], car 15 − 6 = 9." },
    { pts: 4, c: "Vrai ou faux ? 1. L'origine a pour abscisse 1. 2. Les graduations peuvent être inégales. 3. Un point d'abscisse 0 est l'origine. 4. L'abscisse s'écrit entre parenthèses.",
      r: "1. [[Faux]] : elle a pour abscisse 0. 2. [[Faux]] : elles sont régulièrement espacées. 3. [[Vrai]]. 4. [[Vrai]]." },
    { pts: 4, c: "Sur une demi-droite d'unité 2 cm, à quelle distance de l'origine se trouve le point d'abscisse 5 ?",
      r: "À [[10 cm]] de l'origine, car 5 × 2 cm = 10 cm." },
  ],
},

// ─────────────────── Ch. 1 (suite) — arrondi, multiples, problèmes
{
  ch: "Les nombres entiers naturels",
  titre: "Valeur approchée et arrondi d'un entier",
  objectif: "À la fin de la séance, l'élève est capable de donner l'arrondi d'un entier à la dizaine, à la centaine ou au millier le plus proche.",
  materiel: "Demi-droite graduée au tableau, ardoises, étiquettes-nombres",
  rev: [["Quelle est l'abscisse de l'origine ?", "Zéro."],
        ["Range dans l'ordre croissant : 806 ; 860 ; 68.", "68 < 806 < 860."],
        ["Encadre 512 entre deux centaines.", "500 < 512 < 600."]],
  mise: { q: "Un commerçant annonce « environ 3 500 ariary » pour un article vendu 3 472 ariary. Pourquoi ne donne-t-il pas le prix exact ?", ra: "Pour donner un ordre d'idée, plus simple à retenir." },
  obs: "Observez la demi-droite graduée de 3 400 à 3 500, de 10 en 10. Le nombre 3 472 y est repéré par une croix, entre 3 470 et 3 480.",
  ana: [
    ["Entre quelles dizaines se trouve 3 472 ?", "Entre 3 470 et 3 480."],
    ["De laquelle est-il le plus proche ?", "De 3 470, car il n'en est éloigné que de 2 unités."],
    ["Quel est alors son arrondi à la dizaine ?", "3 470."],
    ["Entre quelles centaines se trouve-t-il ?", "Entre 3 400 et 3 500."],
    ["De laquelle est-il le plus proche ?", "De 3 500, car il en est éloigné de 28, contre 72 de l'autre côté."],
    ["Quel chiffre a-t-on regardé pour décider ?", "Le chiffre des dizaines, 7, qui est supérieur ou égal à 5."],
    ["Que fait-on quand ce chiffre est 5 ?", "On arrondit au nombre supérieur."],
  ],
  syn: "Donc, pour arrondir un entier à un rang donné, on regarde le chiffre situé immédiatement à droite de ce rang. S'il vaut 0, 1, 2, 3 ou 4, on garde le nombre inférieur ; s'il vaut 5, 6, 7, 8 ou 9, on prend le nombre supérieur. Les chiffres à droite du rang deviennent des zéros.",
  attention: "L'erreur la plus fréquente est de regarder tous les chiffres de droite au lieu du seul chiffre qui suit le rang choisi. Pour arrondir 3 472 à la centaine, on ne regarde que le 7 des dizaines, pas le 2 des unités.",
  astuce: "« 5 fait monter » : dès que le chiffre observé atteint 5, on monte à la valeur supérieure ; en dessous, on reste en bas.",
  app: [
    { c: "Arrondis à la centaine la plus proche :\n1. 3 472\n2. 8 650\n3. 749\n4. 2 038",
      r: "1. [[3 500]] car le chiffre des dizaines est 7\n2. [[8 700]] car le chiffre des dizaines est 5\n3. [[700]] car le chiffre des dizaines est 4\n4. [[2 000]] car le chiffre des dizaines est 3" },
    { c: "Arrondis au millier le plus proche :\n1. 12 489\n2. 45 678\n3. 7 500\n4. 9 210",
      r: "1. [[12 000]]\n2. [[46 000]]\n3. [[8 000]] : le chiffre des centaines est 5, on monte\n4. [[9 000]]" },
  ],
  evalx: [
    { c: "Complète le tableau pour 6 384 :\n1. arrondi à la dizaine\n2. arrondi à la centaine\n3. arrondi au millier\n4. Quel chiffre a-t-on observé pour la question 2 ?",
      r: "1. [[6 380]]\n2. [[6 400]]\n3. [[6 000]]\n4. [[Le chiffre des dizaines, 8]]" },
    { c: "Vrai ou faux ?\n1. L'arrondi de 450 à la centaine est 400.\n2. L'arrondi de 2 999 au millier est 3 000.\n3. Arrondir change toujours le nombre.\n4. Pour arrondir au millier, on observe le chiffre des centaines.",
      r: "1. [[Faux]] : le chiffre des dizaines est 5, donc on monte à 500.\n2. [[Vrai]].\n3. [[Faux]] : l'arrondi de 700 à la centaine est 700 lui-même.\n4. [[Vrai]]." },
  ],
  lecon: [
    ["1. Pourquoi arrondir", "Dans la vie courante, on n'a pas toujours besoin du nombre exact. On dit « le stade contient environ 20 000 places » plutôt que 19 847. Donner une {{valeur approchée}}, c'est remplacer un nombre par un autre, plus simple, qui en est très proche."],
    ["2. La règle de l'arrondi", "Pour {{arrondir}} un nombre à un rang donné (dizaine, centaine, millier), on observe le chiffre placé {{immédiatement à droite}} de ce rang :\n— s'il vaut 0, 1, 2, 3 ou 4, on garde la valeur inférieure ;\n— s'il vaut 5, 6, 7, 8 ou 9, on prend la valeur supérieure.\nDans les deux cas, tous les chiffres situés à droite du rang deviennent des zéros."],
    ["3. Un exemple détaillé", "Arrondissons 3 472.\nÀ la dizaine : le chiffre à droite des dizaines est 2, inférieur à 5, donc l'arrondi est 3 470.\nÀ la centaine : le chiffre à droite des centaines est 7, supérieur à 5, donc l'arrondi est 3 500.\nAu millier : le chiffre à droite des milliers est 4, inférieur à 5, donc l'arrondi est 3 000."],
    ["4. Le signe ≈", "On note l'arrondi avec le signe {{≈}}, qui se lit « est environ égal à » : 3 472 ≈ 3 500 à la centaine près. Ce signe ne remplace jamais le signe =, car les deux nombres ne sont pas égaux."],
  ],
  exos: [
    { pts: 4, c: "Arrondis 5 847 à la dizaine, à la centaine, puis au millier.",
      r: "À la dizaine : [[5 850]]. À la centaine : [[5 800]]. Au millier : [[6 000]]." },
    { pts: 4, c: "Arrondis à la centaine : 1 250 ; 9 949 ; 380 ; 4 051.",
      r: "[[1 300]] ; [[9 900]] ; [[400]] ; [[4 100]]." },
    { pts: 4, c: "Un marché a accueilli 8 736 visiteurs. Donne ce nombre arrondi au millier, puis explique pourquoi ce chiffre est plus facile à retenir.",
      r: "[[9 000 visiteurs]], car le chiffre des centaines est 7, supérieur à 5. Ce nombre est plus simple à mémoriser et suffit pour donner un ordre de grandeur." },
    { pts: 4, c: "Trouve un nombre dont l'arrondi à la centaine est 600 et l'arrondi au millier est 1 000.",
      r: "Par exemple [[620]] : à la centaine on obtient 600, et au millier 1 000. Toute réponse comprise entre [[550 et 649]] convient." },
    { pts: 4, c: "Vrai ou faux ? 1. 4 500 arrondi au millier donne 4 000. 2. Le signe ≈ signifie « est égal à ». 3. 999 arrondi à la centaine donne 1 000. 4. Arrondir donne toujours un nombre plus grand.",
      r: "1. [[Faux]] : le chiffre des centaines est 5, donc on monte à 5 000. 2. [[Faux]] : il signifie « est environ égal à ». 3. [[Vrai]]. 4. [[Faux]] : on peut aussi descendre, comme 320 qui donne 300." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Doubles, moitiés, triples et quarts",
  objectif: "À la fin de la séance, l'élève est capable de calculer mentalement le double, la moitié, le triple et le quart d'un entier naturel.",
  materiel: "Bâtonnets de comptage, ardoises, jetons",
  rev: [["Arrondis 4 380 à la centaine.", "4 400."],
        ["Quel chiffre observe-t-on pour arrondir au millier ?", "Le chiffre des centaines."],
        ["Arrondis 92 à la dizaine.", "90."]],
  mise: { q: "Soa achète deux paniers identiques de 1 250 ariary chacun. Combien dépense-t-elle en tout ?", ra: "2 500 ariary." },
  obs: "Observez ces 12 bâtonnets posés sur la table. L'enseignant les sépare en deux tas égaux, puis regroupe deux paquets de 12.",
  ana: [
    ["Combien de bâtonnets dans chaque tas après le partage en deux ?", "Six bâtonnets."],
    ["Comment appelle-t-on ce résultat ?", "La moitié de 12."],
    ["Par quelle opération l'obtient-on ?", "En divisant par 2 : 12 ÷ 2 = 6."],
    ["Et si l'on réunit deux paquets de 12 ?", "On obtient 24, le double de 12."],
    ["Par quelle opération ?", "En multipliant par 2 : 12 × 2 = 24."],
    ["Que serait le triple de 12 ?", "36, car 12 × 3 = 36."],
    ["Et son quart ?", "3, car 12 ÷ 4 = 3."],
    ["Tout nombre a-t-il une moitié entière ?", "Non : 7 ÷ 2 ne donne pas un entier."],
  ],
  syn: "Donc, le double s'obtient en multipliant par 2 et la moitié en divisant par 2 ; le triple en multipliant par 3 et le quart en divisant par 4. Double et moitié sont deux opérations inverses, de même que triple et tiers.",
  astuce: "Pour doubler un nombre, on double séparément chaque tranche : le double de 1 250, c'est le double de 1 000 plus le double de 250, soit 2 000 + 500 = 2 500.",
  app: [
    { c: "Calcule mentalement :\n1. le double de 1 250\n2. la moitié de 4 600\n3. le triple de 320\n4. le quart de 800",
      r: "1. [[2 500]]\n2. [[2 300]]\n3. [[960]]\n4. [[200]]" },
    { c: "Complète :\n1. Le double de …… est 90.\n2. La moitié de …… est 35.\n3. Le triple de …… est 150.\n4. Le quart de …… est 25.",
      r: "1. [[45]]\n2. [[70]]\n3. [[50]]\n4. [[100]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. le double de 375\n2. la moitié de 1 800\n3. le triple de 41\n4. le quart de 2 400",
      r: "1. [[750]]\n2. [[900]]\n3. [[123]]\n4. [[600]]" },
    { c: "Hery récolte 640 kg de riz. Il en vend la moitié, puis le quart de ce qui reste.\n1. Quelle quantité vend-il d'abord ?\n2. Que lui reste-t-il alors ?\n3. Quelle quantité vend-il ensuite ?\n4. Que lui reste-t-il à la fin ?",
      r: "1. [[320 kg]], car 640 ÷ 2 = 320.\n2. [[320 kg]].\n3. [[80 kg]], car 320 ÷ 4 = 80.\n4. [[240 kg]], car 320 − 80 = 240." },
  ],
  lecon: [
    ["1. Le double et la moitié", "Le {{double}} d'un nombre s'obtient en le multipliant par 2. La {{moitié}} s'obtient en le divisant par 2.\nCes deux opérations sont {{inverses}} l'une de l'autre : le double de 18 est 36, et la moitié de 36 est bien 18."],
    ["2. Le triple et le quart", "Le {{triple}} s'obtient en multipliant par 3, le {{quart}} en divisant par 4. De même, le tiers s'obtient en divisant par 3.\nExemple : le triple de 25 est 75 ; le quart de 100 est 25."],
    ["3. Calculer de tête", "Pour aller vite, on décompose le nombre. Le double de 1 250 se calcule ainsi : double de 1 000 = 2 000, double de 250 = 500, total 2 500.\nPour la moitié de 4 600 : moitié de 4 000 = 2 000, moitié de 600 = 300, total 2 300."],
    ["4. Tous les nombres n'ont pas de moitié entière", "La moitié de 7 n'est pas un entier naturel. Un nombre dont la moitié est entière est un nombre {{pair}} ; les autres sont {{impairs}}. Un nombre est pair lorsqu'il se termine par 0, 2, 4, 6 ou 8."],
  ],
  exos: [
    { pts: 4, c: "Calcule le double de 145, de 2 300, de 78 et de 1 000.",
      r: "[[290]] ; [[4 600]] ; [[156]] ; [[2 000]]." },
    { pts: 4, c: "Calcule la moitié de 96, de 250, de 1 400 et de 3 000.",
      r: "[[48]] ; [[125]] ; [[700]] ; [[1 500]]." },
    { pts: 4, c: "Calcule le triple de 60, puis le quart de 480.",
      r: "Le triple de 60 est [[180]]. Le quart de 480 est [[120]]." },
    { pts: 4, c: "Nivo a 1 600 ariary. Elle dépense la moitié au marché, puis le quart du reste pour le transport. Combien lui reste-t-il ?",
      r: "Elle dépense d'abord [[800 ariary]] et il lui reste 800. Elle dépense ensuite [[200 ariary]], car 800 ÷ 4 = 200. Il lui reste donc [[600 ariary]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Le double de 0 est 0. 2. Tout nombre a une moitié entière. 3. Le quart de 20 est 5. 4. Le triple de 11 est 33.",
      r: "1. [[Vrai]]. 2. [[Faux]] : la moitié de 9 n'est pas entière. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Résoudre un problème avec des entiers naturels",
  objectif: "À la fin de la séance, l'élève est capable de repérer les données utiles d'un énoncé, de choisir l'opération convenable et de rédiger une réponse complète.",
  materiel: "Énoncés écrits au tableau, cahier de recherche, ardoises",
  rev: [["Quelle est la moitié de 500 ?", "250."],
        ["Quel est le double de 340 ?", "680."],
        ["Arrondis 2 470 à la centaine.", "2 500."]],
  mise: { q: "Quand vous faites une course au marché, comment savez-vous combien on doit vous rendre ?", ra: "On soustrait le prix de la somme donnée." },
  obs: "Lisez silencieusement l'énoncé écrit au tableau : « Un commerçant reçoit 12 sacs de riz contenant chacun 25 kg. Il en vend 180 kg. Quelle masse de riz lui reste-t-il ? »",
  ana: [
    ["Quelles sont les données de cet énoncé ?", "12 sacs, 25 kg par sac, et 180 kg vendus."],
    ["Que cherche-t-on exactement ?", "La masse de riz restante."],
    ["Peut-on répondre directement ?", "Non, il faut d'abord connaître la masse totale reçue."],
    ["Comment obtient-on cette masse totale ?", "En multipliant : 12 × 25 = 300 kg."],
    ["Quelle opération donne ensuite le reste ?", "Une soustraction : 300 − 180 = 120 kg."],
    ["Combien d'étapes comporte donc ce problème ?", "Deux étapes : une multiplication puis une soustraction."],
    ["Comment rédige-t-on la réponse ?", "Par une phrase complète : « Il lui reste 120 kg de riz. »"],
  ],
  syn: "Donc, pour résoudre un problème, on lit l'énoncé attentivement, on relève les données utiles, on identifie la question posée, on choisit la ou les opérations nécessaires, on effectue les calculs, puis on rédige la réponse par une phrase complète avec son unité.",
  attention: "Un mot de l'énoncé ne désigne pas toujours l'opération à faire. « De plus » n'appelle pas forcément une addition : dans « Koto a 12 zébus de plus que Rova qui en a 30 », c'est bien une addition, mais dans « Koto a 12 zébus de moins que Rova qui en a 30 », il faut soustraire. Il faut comprendre la situation, pas repérer un mot.",
  app: [
    { c: "Un car transporte 52 passagers. Six cars font le trajet Antananarivo–Antsirabe.\n1. Quelle opération choisis-tu ?\n2. Combien de passagers en tout ?\n3. Si 40 descendent en route, combien reste-t-il de passagers ?\n4. Rédige la réponse finale.",
      r: "1. [[Une multiplication]], car on répète 52 six fois.\n2. [[312 passagers]], car 6 × 52 = 312.\n3. [[272 passagers]], car 312 − 40 = 272.\n4. « [[Il reste 272 passagers dans les cars.]] »" },
    { c: "Fara possède 4 500 ariary et sa sœur 3 800 ariary. Elles achètent ensemble un cadeau à 7 250 ariary.\n1. Quelle somme ont-elles au total ?\n2. Leur reste-t-il de l'argent ?\n3. Combien ?\n4. Écris la phrase réponse.",
      r: "1. [[8 300 ariary]], car 4 500 + 3 800 = 8 300.\n2. [[Oui]], car 8 300 est supérieur à 7 250.\n3. [[1 050 ariary]], car 8 300 − 7 250 = 1 050.\n4. « [[Il leur reste 1 050 ariary.]] »" },
  ],
  evalx: [
    { c: "Une école reçoit 15 cartons de 40 cahiers. Elle en distribue 380.\n1. Combien de cahiers reçoit-elle ?\n2. Combien lui en reste-t-il ?\n3. Quelles opérations as-tu utilisées ?\n4. Rédige la phrase réponse.",
      r: "1. [[600 cahiers]], car 15 × 40 = 600.\n2. [[220 cahiers]], car 600 − 380 = 220.\n3. [[Une multiplication puis une soustraction]].\n4. « [[Il reste 220 cahiers à l'école.]] »" },
    { c: "Remets dans l'ordre les étapes de la résolution d'un problème :\na. effectuer les calculs — b. lire l'énoncé — c. rédiger la réponse — d. choisir l'opération",
      r: "L'ordre correct est [[b, d, a, c]] : on lit d'abord l'énoncé, on choisit ensuite l'opération, on effectue les calculs, puis on rédige la réponse." },
  ],
  lecon: [
    ["1. Lire et comprendre", "Un problème se lit au moins deux fois. La première lecture fait comprendre la situation ; la seconde permet de relever les {{données}}, c'est-à-dire les nombres utiles, et de repérer la {{question}} posée.\nAttention : un énoncé peut contenir une donnée inutile, placée là pour vérifier que l'on réfléchit."],
    ["2. Choisir l'opération", "On {{additionne}} pour réunir deux quantités, on {{soustrait}} pour retirer ou comparer, on {{multiplie}} pour répéter une même quantité, on {{divise}} pour partager en parts égales.\nCe n'est pas un mot de l'énoncé qui décide, mais le sens de la situation."],
    ["3. Les problèmes à deux étapes", "Beaucoup de problèmes ne se résolvent pas d'un seul calcul. Il faut alors trouver une {{étape intermédiaire}}.\nExemple : 12 sacs de 25 kg dont on vend 180 kg. On calcule d'abord le total, 12 × 25 = 300 kg, puis le reste, 300 − 180 = 120 kg."],
    ["4. Rédiger la réponse", "Un résultat seul ne suffit pas. On écrit une {{phrase réponse}} complète, qui reprend les termes de la question et précise l'{{unité}} : « Il reste 120 kg de riz », et non simplement « 120 »."],
  ],
  exos: [
    { pts: 4, c: "Un planteur récolte 24 paniers de 15 kg de litchis. Quelle masse a-t-il récoltée ?",
      r: "Il faut multiplier : 24 × 15 = [[360]]. « [[Le planteur a récolté 360 kg de litchis.]] »" },
    { pts: 4, c: "Aina avait 9 000 ariary. Elle a dépensé 3 450 ariary puis 2 200 ariary. Combien lui reste-t-il ?",
      r: "Total dépensé : 3 450 + 2 200 = [[5 650 ariary]]. Reste : 9 000 − 5 650 = [[3 350 ariary]]. « [[Il lui reste 3 350 ariary.]] »" },
    { pts: 4, c: "Une classe de 45 élèves part en sortie. Chaque élève verse 800 ariary. Quelle somme est réunie ?",
      r: "45 × 800 = [[36 000]]. « [[La classe a réuni 36 000 ariary.]] »" },
    { pts: 4, c: "Dans l'énoncé suivant, relève la donnée inutile : « Lanto part à 6 heures. Il achète 3 kg de tomates à 2 000 ariary le kilogramme. Combien paie-t-il ? »",
      r: "La donnée inutile est [[l'heure de départ, 6 heures]] : elle n'intervient pas dans le calcul. Le prix payé est 3 × 2 000 = [[6 000 ariary]]." },
    { pts: 4, c: "Écris un problème dont la résolution est 5 × 12 = 60, puis rédige sa phrase réponse.",
      r: "Par exemple : « [[Un marchand range 12 œufs par plateau. Combien d'œufs contiennent 5 plateaux ?]] » Réponse : « [[Les 5 plateaux contiennent 60 œufs.]] »" },
  ],
},


// ─────────────────────────────────── Ch. 2 — Les nombres décimaux
{
  ch: "Les nombres décimaux",
  titre: "Découvrir le nombre décimal",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître un nombre décimal, d'en nommer la partie entière et la partie décimale, et de lire les rangs après la virgule.",
  materiel: "Tableau de numération étendu aux décimales, règle graduée en millimètres, ardoises",
  rev: [["Quelle est la valeur du chiffre 6 dans 4 615 ?", "600, car il occupe la colonne des centaines."],
        ["Arrondis 2 380 à la centaine.", "2 400."],
        ["Quel est le double de 45 ?", "90."]],
  mise: { q: "Sur votre règle, entre les traits marqués 3 cm et 4 cm, il y a de petits traits. Comment nommer la longueur qui s'arrête au cinquième petit trait ?", ra: "3 centimètres et demi, soit 3,5 cm." },
  obs: "Observez le tableau de numération au tableau : à droite de la colonne des unités, une virgule a été tracée, puis trois nouvelles colonnes intitulées dixièmes, centièmes et millièmes. Le nombre 24,63 y est placé.",
  ana: [
    ["Que sépare la virgule dans ce tableau ?", "Elle sépare la partie entière de la partie décimale."],
    ["Quelle est la partie entière de 24,63 ?", "24."],
    ["Quelle est sa partie décimale ?", "63, c'est-à-dire les chiffres après la virgule."],
    ["Comment s'appelle la première colonne après la virgule ?", "La colonne des dixièmes."],
    ["Que représente le chiffre 6 dans 24,63 ?", "6 dixièmes, c'est-à-dire 6 divisé par 10."],
    ["Et le chiffre 3 ?", "3 centièmes, c'est-à-dire 3 divisé par 100."],
    ["Comment lit-on ce nombre à voix haute ?", "Vingt-quatre virgule soixante-trois, ou vingt-quatre unités et soixante-trois centièmes."],
  ],
  syn: "Donc, un nombre décimal comporte une partie entière et une partie décimale, séparées par une virgule. Après la virgule viennent, dans l'ordre, les dixièmes, les centièmes et les millièmes. Chaque rang vaut dix fois moins que le précédent.",
  attention: "La virgule n'est pas un simple séparateur décoratif : elle fixe la place de chaque chiffre. Dans 5,2 et 5,02, le chiffre 2 ne vaut pas la même chose — 2 dixièmes dans le premier, 2 centièmes dans le second.",
  app: [
    { c: "Pour chaque nombre, donne la partie entière et la partie décimale :\n1. 7,25\n2. 130,8\n3. 0,45\n4. 9,006",
      r: "1. Partie entière [[7]], partie décimale [[25]]\n2. Partie entière [[130]], partie décimale [[8]]\n3. Partie entière [[0]], partie décimale [[45]]\n4. Partie entière [[9]], partie décimale [[006]]" },
    { c: "Dans le nombre 38,417, indique le rang de chaque chiffre après la virgule :\n1. le chiffre 4\n2. le chiffre 1\n3. le chiffre 7\n4. Que vaut le chiffre 4 ?",
      r: "1. [[Les dixièmes]]\n2. [[Les centièmes]]\n3. [[Les millièmes]]\n4. Il vaut [[4 dixièmes]], soit 4 divisé par 10" },
  ],
  evalx: [
    { c: "Écris en chiffres :\n1. cinq unités et trois dixièmes\n2. douze unités et huit centièmes\n3. zéro unité et sept dixièmes\n4. cent unités et vingt-cinq centièmes",
      r: "1. [[5,3]]\n2. [[12,08]]\n3. [[0,7]]\n4. [[100,25]]" },
    { c: "Complète :\n1. La virgule sépare la partie …… de la partie ……\n2. Le premier rang après la virgule est celui des ……\n3. Un centième vaut …… fois moins qu'un dixième.\n4. Dans 6,04, le chiffre 4 est le chiffre des ……",
      r: "1. [[entière]] / [[décimale]]\n2. [[dixièmes]]\n3. [[dix]]\n4. [[centièmes]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'un nombre décimal", "Les entiers naturels ne suffisent pas pour tout mesurer. Entre 3 cm et 4 cm, il existe des longueurs intermédiaires. Pour les écrire, on utilise un {{nombre décimal}}, composé d'une {{partie entière}} et d'une {{partie décimale}}, séparées par une {{virgule}}.\nDans 24,63 : la partie entière est 24, la partie décimale est 63."],
    ["2. Les rangs après la virgule", "À droite de la virgule, les colonnes se poursuivent :\n— le premier rang est celui des {{dixièmes}} : un dixième, c'est une unité partagée en 10 parts égales ;\n— le deuxième est celui des {{centièmes}} : une unité partagée en 100 parts ;\n— le troisième est celui des {{millièmes}} : une unité partagée en 1 000 parts.\nChaque rang vaut dix fois moins que celui qui le précède, exactement comme pour la partie entière."],
    ["3. Lire un nombre décimal", "On lit d'abord la partie entière, puis le mot « virgule », puis la partie décimale.\n24,63 se lit « vingt-quatre virgule soixante-trois ». On peut aussi dire « vingt-quatre unités et soixante-trois centièmes », en nommant le rang du dernier chiffre."],
    ["4. Le rôle de la virgule", "La virgule fixe la {{valeur de position}} de chaque chiffre. Déplacer la virgule change complètement le nombre : 5,2 vaut cinq unités et deux dixièmes, tandis que 52 vaut cinquante-deux unités, soit dix fois plus.\nEn mathématiques, on écrit toujours une virgule et jamais un point : on note 3,14 et non 3.14."],
  ],
  exos: [
    { pts: 4, c: "Donne la partie entière et la partie décimale de 45,7 ; de 0,308 ; de 12,05 ; de 200,4.",
      r: "45,7 : [[45]] et [[7]]. 0,308 : [[0]] et [[308]]. 12,05 : [[12]] et [[05]]. 200,4 : [[200]] et [[4]]." },
    { pts: 4, c: "Dans 73,596, quel est le chiffre des dixièmes ? des centièmes ? des millièmes ?",
      r: "Le chiffre des dixièmes est [[5]], celui des centièmes est [[9]], celui des millièmes est [[6]]." },
    { pts: 4, c: "Écris en chiffres : huit unités et quatre dixièmes ; zéro unité et douze centièmes ; trente unités et cinq millièmes.",
      r: "[[8,4]] ; [[0,12]] ; [[30,005]]." },
    { pts: 4, c: "Écris en toutes lettres 6,09 en nommant le rang du dernier chiffre.",
      r: "[[Six unités et neuf centièmes]] (on peut aussi lire « six virgule zéro neuf »)." },
    { pts: 4, c: "Vrai ou faux ? 1. Dans 4,7 la partie entière est 7. 2. Un dixième vaut dix centièmes. 3. On peut écrire 3.5 en mathématiques. 4. La virgule sépare deux parties du nombre.",
      r: "1. [[Faux]] : la partie entière est 4. 2. [[Vrai]]. 3. [[Faux]] : on écrit 3,5 avec une virgule. 4. [[Vrai]]." },
  ],
},
{
  ch: "Les nombres décimaux",
  titre: "Les différentes écritures d'un nombre décimal",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître des écritures équivalentes d'un même décimal et de décomposer un décimal en somme.",
  materiel: "Étiquettes-nombres, tableau de numération, ardoises",
  rev: [["Quelle est la partie décimale de 15,08 ?", "08."],
        ["Quel est le chiffre des dixièmes dans 4,26 ?", "Le chiffre 2."],
        ["Écris en chiffres : trois unités et cinq dixièmes.", "3,5."]],
  mise: { q: "Un commerçant écrit le prix « 7,50 » et un autre « 7,5 » pour le même article. Ont-ils écrit le même nombre ?", ra: "Oui, c'est le même nombre." },
  obs: "Observez ces quatre écritures alignées au tableau : 3,5 — 3,50 — 3,500 — 03,5. L'enseignant place chacune dans le tableau de numération.",
  ana: [
    ["Dans le tableau, les chiffres 3 et 5 occupent-ils les mêmes colonnes à chaque fois ?", "Oui, 3 aux unités et 5 aux dixièmes."],
    ["Que représentent alors les zéros ajoutés à droite ?", "Zéro centième et zéro millième, c'est-à-dire rien du tout."],
    ["Ces zéros changent-ils la valeur du nombre ?", "Non, la valeur reste la même."],
    ["Et le zéro placé devant, dans 03,5 ?", "Il ne change rien non plus, car il n'y a pas de dizaine."],
    ["Peut-on supprimer le zéro de 3,05 ?", "Non, car il maintient le 5 au rang des centièmes."],
    ["Comment décomposer 24,63 en somme ?", "24,63 = 20 + 4 + 0,6 + 0,03."],
    ["Peut-on l'écrire avec des fractions ?", "Oui : 24 + 6 dixièmes + 3 centièmes."],
  ],
  syn: "Donc, un même nombre décimal admet plusieurs écritures. Les zéros inutiles, placés à gauche de la partie entière ou tout à droite de la partie décimale, ne changent pas sa valeur et peuvent être supprimés. En revanche, un zéro situé entre la virgule et un autre chiffre est indispensable.",
  attention: "Supprimer un zéro utile est une erreur grave : 3,05 et 3,5 sont deux nombres différents. On ne peut effacer que les zéros situés tout à la fin de la partie décimale.",
  astuce: "Un zéro ne se supprime que s'il est « en bout de ligne » : tout à gauche du nombre ou tout à droite après la virgule. Coincé entre deux chiffres, il reste.",
  app: [
    { c: "Ces écritures désignent-elles le même nombre ? Réponds par oui ou non.\n1. 6,4 et 6,40\n2. 0,7 et 0,07\n3. 12,300 et 12,3\n4. 05,9 et 5,9",
      r: "1. [[Oui]]\n2. [[Non]] : 0,07 vaut dix fois moins que 0,7\n3. [[Oui]]\n4. [[Oui]]" },
    { c: "Simplifie l'écriture en supprimant les zéros inutiles :\n1. 08,70\n2. 3,400\n3. 0,050\n4. 120,00",
      r: "1. [[8,7]]\n2. [[3,4]]\n3. [[0,05]] : le premier zéro est utile, seul celui de droite disparaît\n4. [[120]]" },
  ],
  evalx: [
    { c: "Décompose comme dans l'exemple 12,45 = 10 + 2 + 0,4 + 0,05 :\n1. 24,63\n2. 105,4\n3. 7,08\n4. 30,52",
      r: "1. [[20 + 4 + 0,6 + 0,03]]\n2. [[100 + 5 + 0,4]]\n3. [[7 + 0,08]]\n4. [[30 + 0,5 + 0,02]]" },
    { c: "Vrai ou faux ?\n1. 9,10 est égal à 9,1.\n2. On peut supprimer le zéro de 4,03.\n3. 0,60 et 0,6 sont égaux.\n4. Ajouter un zéro à droite après la virgule change le nombre.",
      r: "1. [[Vrai]]\n2. [[Faux]] : ce zéro maintient le 3 au rang des centièmes\n3. [[Vrai]]\n4. [[Faux]] : cela ne change pas sa valeur" },
  ],
  lecon: [
    ["1. Plusieurs écritures, un seul nombre", "Un nombre décimal peut s'écrire de plusieurs façons sans changer de valeur :\n3,5 = 3,50 = 3,500 = 03,5.\nDans tous les cas, le 3 occupe le rang des unités et le 5 celui des dixièmes ; seuls des {{zéros inutiles}} ont été ajoutés."],
    ["2. Quels zéros peut-on supprimer", "On peut supprimer :\n— les zéros placés {{à gauche}} de la partie entière : 07,2 = 7,2 ;\n— les zéros placés {{tout à droite}} de la partie décimale : 4,900 = 4,9.\nOn ne peut jamais supprimer un zéro {{encadré}} par la virgule et un chiffre : 3,05 n'est pas égal à 3,5, car le zéro maintient le 5 au rang des centièmes."],
    ["3. Un entier est un décimal particulier", "Tout entier naturel peut s'écrire avec une virgule suivie de zéros : 37 = 37,0 = 37,00. Les {{entiers naturels}} font donc partie des nombres décimaux — ce sont ceux dont la partie décimale est nulle."],
    ["4. Décomposer un décimal", "{{Décomposer}} un nombre, c'est l'écrire comme une somme faisant apparaître la valeur de chaque chiffre :\n24,63 = 20 + 4 + 0,6 + 0,03.\nOn peut aussi l'exprimer en fractions décimales : 24,63 = 24 + 6 dixièmes + 3 centièmes. Cette écriture montre clairement le rôle de chaque rang."],
  ],
  exos: [
    { pts: 4, c: "Supprime les zéros inutiles : 06,30 ; 15,000 ; 0,904 ; 020,10.",
      r: "[[6,3]] ; [[15]] ; [[0,904]] — aucun zéro n'est supprimable ici — ; [[20,1]]." },
    { pts: 4, c: "Décompose 58,27 puis 6,405.",
      r: "58,27 = [[50 + 8 + 0,2 + 0,07]]. 6,405 = [[6 + 0,4 + 0,005]]." },
    { pts: 4, c: "Écris 45 sous trois écritures décimales différentes.",
      r: "Par exemple [[45]] ; [[45,0]] ; [[45,00]] — ce sont trois écritures du même nombre." },
    { pts: 4, c: "Parmi 2,5 ; 2,05 ; 2,50 ; 2,500, lesquels sont égaux entre eux ?",
      r: "[[2,5 ; 2,50 et 2,500 sont égaux]]. [[2,05 est différent]] : son chiffre 5 est au rang des centièmes." },
    { pts: 4, c: "Recompose le nombre : 300 + 7 + 0,09.",
      r: "Le nombre est [[307,09]] : il n'y a pas de dixième, d'où le zéro à ce rang." },
  ],
},
{
  ch: "Les nombres décimaux",
  titre: "Comparer et ranger les nombres décimaux",
  objectif: "À la fin de la séance, l'élève est capable de comparer deux décimaux et de ranger une liste de décimaux dans l'ordre croissant ou décroissant.",
  materiel: "Tableau de numération, étiquettes-nombres, ardoises",
  rev: [["6,70 est-il égal à 6,7 ?", "Oui, le zéro final est inutile."],
        ["Décompose 8,25.", "8 + 0,2 + 0,05."],
        ["Quelle est la partie décimale de 3,406 ?", "406."]],
  mise: { q: "Deux sacs de riz pèsent 12,5 kg et 12,45 kg. Lequel est le plus lourd ?", ra: "Celui de 12,5 kg." },
  obs: "Observez 12,5 et 12,45 placés l'un sous l'autre dans le tableau de numération, chaque chiffre dans sa colonne, virgule sous virgule.",
  ana: [
    ["Les parties entières sont-elles différentes ?", "Non, elles valent 12 toutes les deux."],
    ["Que compare-t-on alors ?", "Les parties décimales, rang par rang."],
    ["Quel est le chiffre des dixièmes de chacun ?", "5 pour le premier, 4 pour le second."],
    ["Lequel est donc le plus grand ?", "12,5, car 5 dixièmes valent plus que 4 dixièmes."],
    ["Pourtant 45 est plus grand que 5 : pourquoi ce raisonnement est-il faux ?", "Parce qu'on ne compare pas les parties décimales comme des entiers, mais rang par rang."],
    ["Quelle astuce facilite la comparaison ?", "Compléter avec des zéros pour avoir autant de chiffres après la virgule : 12,50 et 12,45."],
    ["Que constate-t-on alors ?", "50 centièmes valent plus que 45 centièmes, donc 12,5 > 12,45."],
  ],
  syn: "Donc, pour comparer deux décimaux, on compare d'abord les parties entières ; si elles sont égales, on compare les parties décimales rang par rang, en partant des dixièmes. On peut compléter par des zéros à droite pour avoir le même nombre de décimales.",
  attention: "L'erreur la plus répandue consiste à comparer les parties décimales comme des entiers et à conclure que 12,45 dépasse 12,5 parce que 45 dépasse 5. C'est faux : 12,45 vaut 12,45 et 12,5 vaut 12,50.",
  astuce: "Complétez toujours par des zéros pour égaliser le nombre de décimales : la comparaison devient alors aussi simple qu'entre deux entiers.",
  app: [
    { c: "Complète par < ou > :\n1. 4,7 … 4,68\n2. 0,3 … 0,25\n3. 6,07 … 6,7\n4. 15,20 … 15,2",
      r: "1. 4,7 [[>]] 4,68\n2. 0,3 [[>]] 0,25\n3. 6,07 [[<]] 6,7\n4. 15,20 [[=]] 15,2" },
    { c: "Range dans l'ordre croissant : 4,5 ; 4,05 ; 4,55 ; 4,5.",
      r: "[[4,05 < 4,5 = 4,5 < 4,55]]" },
  ],
  evalx: [
    { c: "Range dans l'ordre décroissant : 9,8 ; 9,08 ; 9,88 ; 9,801.",
      r: "[[9,88 > 9,801 > 9,8 > 9,08]]" },
    { c: "Encadre chaque décimal entre deux entiers consécutifs :\n1. 7,4\n2. 0,9\n3. 15,03\n4. 99,7",
      r: "1. [[7 < 7,4 < 8]]\n2. [[0 < 0,9 < 1]]\n3. [[15 < 15,03 < 16]]\n4. [[99 < 99,7 < 100]]" },
  ],
  lecon: [
    ["1. Comparer les parties entières", "Pour comparer deux décimaux, on regarde d'abord les {{parties entières}}. Le plus grand nombre est celui dont la partie entière est la plus grande, quelle que soit la partie décimale.\nAinsi 8,1 > 7,99, car 8 est supérieur à 7."],
    ["2. Comparer les parties décimales", "Si les parties entières sont égales, on compare les parties décimales {{rang par rang}}, en commençant par les dixièmes, puis les centièmes, puis les millièmes.\nPour 12,5 et 12,45 : les dixièmes valent 5 et 4, donc 12,5 > 12,45."],
    ["3. La méthode des zéros", "Pour éviter toute erreur, on complète par des {{zéros}} à droite afin que les deux nombres aient le même nombre de décimales :\n12,5 devient 12,50, et l'on compare 50 centièmes à 45 centièmes.\nCe procédé est autorisé car ces zéros ne changent pas la valeur du nombre."],
    ["4. Encadrer un décimal", "{{Encadrer}} un décimal entre deux entiers consécutifs, c'est trouver l'entier juste en dessous et l'entier juste au-dessus :\n7 < 7,4 < 8.\nLa partie entière donne directement l'entier inférieur, sauf lorsque la partie décimale est nulle."],
  ],
  exos: [
    { pts: 4, c: "Complète par < , > ou = : 3,9 … 3,89 ; 0,50 … 0,5 ; 14,2 … 14,20 ; 6,1 … 6,099.",
      r: "3,9 [[>]] 3,89 ; 0,50 [[=]] 0,5 ; 14,2 [[=]] 14,20 ; 6,1 [[>]] 6,099." },
    { pts: 4, c: "Range dans l'ordre croissant : 5,6 ; 5,06 ; 5,66 ; 5,606.",
      r: "[[5,06 < 5,6 < 5,606 < 5,66]]." },
    { pts: 4, c: "Range dans l'ordre décroissant : 0,7 ; 0,07 ; 0,77 ; 0,707.",
      r: "[[0,77 > 0,707 > 0,7 > 0,07]]." },
    { pts: 4, c: "Trois sacs pèsent 25,4 kg, 25,04 kg et 25,44 kg. Range-les du plus léger au plus lourd.",
      r: "[[25,04 kg < 25,4 kg < 25,44 kg]] : le plus léger est le sac de 25,04 kg." },
    { pts: 4, c: "Trouve un décimal compris entre 3,2 et 3,3.",
      r: "Par exemple [[3,25]], car 3,20 < 3,25 < 3,30. Toute réponse strictement comprise entre les deux convient." },
  ],
},
{
  ch: "Les nombres décimaux",
  titre: "Placer un décimal sur une demi-droite graduée",
  objectif: "À la fin de la séance, l'élève est capable de placer un nombre décimal sur une demi-droite graduée et de lire l'abscisse décimale d'un point.",
  materiel: "Demi-droite graduée en dixièmes tracée au tableau, règle graduée, ardoises",
  rev: [["Complète : 8,3 … 8,29.", "8,3 > 8,29."],
        ["Encadre 6,7 entre deux entiers.", "6 < 6,7 < 7."],
        ["Quelle est l'abscisse de l'origine ?", "Zéro."]],
  mise: { q: "Sur votre règle, où se trouve exactement la longueur 4,5 cm ?", ra: "À mi-chemin entre les traits 4 cm et 5 cm." },
  obs: "Observez la demi-droite tracée au tableau : l'unité entre 0 et 1 a été partagée en dix intervalles égaux. Les points A et B sont placés sur deux de ces graduations.",
  ana: [
    ["En combien de parts égales l'unité est-elle partagée ?", "En dix parts."],
    ["Que représente donc chaque petit intervalle ?", "Un dixième, soit 0,1."],
    ["Le point A est au troisième trait après 0 : quelle est son abscisse ?", "0,3."],
    ["Le point B est au septième trait après 2 : quelle est son abscisse ?", "2,7."],
    ["Comment placer 1,5 sur cette droite ?", "Au cinquième trait après 1, à mi-chemin entre 1 et 2."],
    ["Comment placerait-on 0,25 ?", "Il faudrait partager chaque dixième en dix, pour obtenir des centièmes."],
    ["Que peut-on dire de deux points dont l'un est plus à droite ?", "Celui de droite a la plus grande abscisse."],
  ],
  syn: "Donc, pour placer un décimal sur une demi-droite graduée, on partage chaque unité en dix intervalles égaux qui représentent les dixièmes. La position d'un point sur la droite traduit directement l'ordre des nombres : plus un point est à droite, plus son abscisse est grande.",
  app: [
    { c: "Sur une demi-droite graduée en dixièmes, donne l'abscisse du point situé :\n1. au 4e trait après 0\n2. au 9e trait après 1\n3. au 2e trait après 3\n4. exactement sur le trait 5",
      r: "1. [[0,4]]\n2. [[1,9]]\n3. [[3,2]]\n4. [[5]] ou 5,0" },
    { c: "Trace une demi-droite d'unité 10 cm graduée en dixièmes, puis place A(0,6), B(1,3) et C(2,0).",
      r: "Chaque dixième mesure 1 cm. [[A est à 6 cm de l'origine]], [[B à 13 cm]], [[C à 20 cm]]." },
  ],
  evalx: [
    { c: "Quel décimal se trouve exactement au milieu de :\n1. 2 et 3\n2. 0 et 1\n3. 4,2 et 4,4\n4. 7 et 7,2",
      r: "1. [[2,5]]\n2. [[0,5]]\n3. [[4,3]]\n4. [[7,1]]" },
    { c: "Vrai ou faux ?\n1. Entre 3 et 4 il n'y a aucun nombre.\n2. 0,5 se place au milieu de 0 et 1.\n3. Un point plus à droite a une abscisse plus petite.\n4. Chaque unité peut se partager en dix dixièmes.",
      r: "1. [[Faux]] : il existe une infinité de décimaux, comme 3,1 ou 3,47.\n2. [[Vrai]].\n3. [[Faux]] : son abscisse est plus grande.\n4. [[Vrai]]." },
  ],
  lecon: [
    ["1. Graduer en dixièmes", "Sur une demi-droite graduée, on partage chaque unité en {{dix intervalles égaux}}. Chaque intervalle représente alors un {{dixième}}, c'est-à-dire 0,1.\nLe troisième trait après 0 correspond ainsi à l'abscisse 0,3."],
    ["2. Lire une abscisse décimale", "Pour lire l'abscisse d'un point, on repère d'abord l'unité qui le précède, puis on compte les dixièmes.\nUn point situé au septième trait après 2 a pour abscisse 2,7 ; on écrit B(2,7)."],
    ["3. Aller plus loin que le dixième", "Pour placer un nombre comme 0,25, on partage chaque dixième en dix nouveaux intervalles : on obtient alors des {{centièmes}}. Ce partage peut se poursuivre indéfiniment.\nC'est pourquoi il existe une {{infinité}} de nombres décimaux entre deux entiers consécutifs."],
    ["4. Lire l'ordre sur la droite", "La demi-droite graduée donne une image visuelle de la comparaison : de deux points, celui qui est le plus à {{droite}} a la plus grande abscisse.\nPlacer 12,45 et 12,5 sur une droite graduée en centièmes montre immédiatement que 12,5 est situé plus à droite."],
  ],
  exos: [
    { pts: 4, c: "Sur une droite graduée en dixièmes, donne l'abscisse du 8e trait après 4, puis du 1er trait après 0.",
      r: "Le 8e trait après 4 a pour abscisse [[4,8]]. Le 1er trait après 0 a pour abscisse [[0,1]]." },
    { pts: 4, c: "Quel nombre se trouve au milieu de 5,4 et 5,6 ?",
      r: "[[5,5]], car il est à un dixième de chacun des deux." },
    { pts: 4, c: "Trace une demi-droite d'unité 10 cm graduée en dixièmes et place M(0,8) et N(1,5).",
      r: "Un dixième vaut 1 cm : [[M est à 8 cm de l'origine]] et [[N à 15 cm]]." },
    { pts: 4, c: "Cite trois nombres décimaux compris entre 6 et 7.",
      r: "Par exemple [[6,1 ; 6,5 et 6,94]]. Il en existe une infinité." },
    { pts: 4, c: "Deux points ont pour abscisses 3,07 et 3,7. Lequel est le plus proche de l'origine ?",
      r: "[[Le point d'abscisse 3,07]], car 3,07 < 3,70 : il est situé plus à gauche sur la droite." },
  ],
},
{
  ch: "Les nombres décimaux",
  titre: "Multiplier et diviser un décimal par 10, 100 et 1 000",
  objectif: "À la fin de la séance, l'élève est capable de multiplier ou de diviser un nombre décimal par 10, 100 ou 1 000 en déplaçant la virgule.",
  materiel: "Tableau de numération, étiquettes-chiffres mobiles, ardoises",
  rev: [["Quelle est l'abscisse du 5e trait après 2, sur une droite graduée en dixièmes ?", "2,5."],
        ["Complète : 0,8 … 0,75.", "0,8 > 0,75."],
        ["Décompose 3,04.", "3 + 0,04."]],
  mise: { q: "Un kilogramme de tomates coûte 3 450 ariary. Combien coûtent dix kilogrammes ?", ra: "34 500 ariary." },
  obs: "Observez le tableau de numération : le nombre 3,45 y est écrit. L'enseignant déplace chaque étiquette-chiffre d'une colonne vers la gauche, sans toucher à la virgule.",
  ana: [
    ["Où se trouvait le chiffre 3 au départ ?", "Dans la colonne des unités."],
    ["Où se trouve-t-il après le déplacement ?", "Dans la colonne des dizaines."],
    ["Sa valeur a-t-elle changé ?", "Oui, elle a été multipliée par 10."],
    ["Quel nombre lit-on maintenant ?", "34,5."],
    ["Par combien a-t-on donc multiplié 3,45 ?", "Par 10."],
    ["Que peut-on faire plutôt que déplacer tous les chiffres ?", "Déplacer la virgule d'un rang vers la droite."],
    ["Et pour diviser par 10 ?", "On déplace la virgule d'un rang vers la gauche."],
    ["Combien de rangs pour multiplier par 1 000 ?", "Trois rangs vers la droite, autant que de zéros."],
  ],
  syn: "Donc, pour multiplier un décimal par 10, 100 ou 1 000, on déplace la virgule vers la droite d'autant de rangs qu'il y a de zéros. Pour diviser, on la déplace vers la gauche du même nombre de rangs. Si les chiffres manquent, on complète par des zéros.",
  attention: "Multiplier par 10 ne consiste pas à « ajouter un zéro » : cette règle ne vaut que pour les entiers. Pour 3,45, ajouter un zéro donnerait 3,450, c'est-à-dire le même nombre. Il faut bien déplacer la virgule.",
  astuce: "Comptez les zéros : autant de zéros, autant de rangs. Vers la droite pour multiplier — le nombre grandit ; vers la gauche pour diviser — le nombre diminue.",
  app: [
    { c: "Calcule :\n1. 3,45 × 10\n2. 3,45 × 100\n3. 0,7 × 1 000\n4. 12,8 × 10",
      r: "1. [[34,5]]\n2. [[345]]\n3. [[700]]\n4. [[128]]" },
    { c: "Calcule :\n1. 52,8 ÷ 10\n2. 9 ÷ 100\n3. 1 250 ÷ 1 000\n4. 4,5 ÷ 10",
      r: "1. [[5,28]]\n2. [[0,09]]\n3. [[1,25]]\n4. [[0,45]]" },
  ],
  evalx: [
    { c: "Complète :\n1. 6,3 × …… = 630\n2. 45 ÷ …… = 4,5\n3. 0,08 × …… = 8\n4. 720 ÷ …… = 0,72",
      r: "1. [[100]]\n2. [[10]]\n3. [[100]]\n4. [[1 000]]" },
    { c: "Un sac de riz coûte 2 350 ariary.\n1. Combien coûtent 10 sacs ?\n2. Combien coûtent 100 sacs ?\n3. Si 10 sacs coûtent 23 500 ariary, combien coûte un sac ?\n4. Quelle opération as-tu faite à la question 3 ?",
      r: "1. [[23 500 ariary]]\n2. [[235 000 ariary]]\n3. [[2 350 ariary]]\n4. [[Une division par 10]]" },
  ],
  lecon: [
    ["1. Multiplier par 10, 100, 1 000", "Multiplier un décimal par 10 revient à faire passer chaque chiffre dans la colonne immédiatement à gauche : sa valeur est multipliée par dix. En pratique, on déplace simplement la {{virgule}} d'un rang vers la {{droite}}.\n3,45 × 10 = 34,5.\nPar 100, on déplace de deux rangs ; par 1 000, de trois rangs : autant de rangs que de {{zéros}}."],
    ["2. Diviser par 10, 100, 1 000", "Diviser revient à l'inverse : on déplace la virgule vers la {{gauche}} d'autant de rangs qu'il y a de zéros.\n52,8 ÷ 10 = 5,28 ; 52,8 ÷ 100 = 0,528."],
    ["3. Compléter par des zéros", "Quand les chiffres manquent pour déplacer la virgule, on ajoute des zéros.\n0,7 × 1 000 : il faut trois rangs à droite, or il n'y a qu'un chiffre après la virgule ; on complète : 0,7 × 1 000 = 700.\nDe même 9 ÷ 100 = 0,09, en ajoutant un zéro devant le 9."],
    ["4. Une règle utile au quotidien", "Ces déplacements servent surtout dans les {{conversions}} d'unités : passer des mètres aux centimètres revient à multiplier par 100, et des grammes aux kilogrammes à diviser par 1 000.\nAinsi 2,5 m = 250 cm, et 1 500 g = 1,5 kg."],
  ],
  exos: [
    { pts: 4, c: "Calcule : 7,2 × 10 ; 0,45 × 100 ; 3,8 × 1 000 ; 15,06 × 10.",
      r: "[[72]] ; [[45]] ; [[3 800]] ; [[150,6]]." },
    { pts: 4, c: "Calcule : 84 ÷ 10 ; 6,5 ÷ 100 ; 920 ÷ 1 000 ; 3 ÷ 10.",
      r: "[[8,4]] ; [[0,065]] ; [[0,92]] ; [[0,3]]." },
    { pts: 4, c: "Complète : 2,7 × …… = 2 700 et 56 ÷ …… = 0,56.",
      r: "2,7 × [[1 000]] = 2 700 ; 56 ÷ [[100]] = 0,56." },
    { pts: 4, c: "Convertis : 3,4 m en centimètres, puis 2 500 g en kilogrammes.",
      r: "3,4 m = [[340 cm]], car on multiplie par 100. 2 500 g = [[2,5 kg]], car on divise par 1 000." },
    { pts: 4, c: "Vrai ou faux ? 1. Multiplier par 10 revient à ajouter un zéro à droite. 2. 0,5 × 100 = 50. 3. Diviser par 100 déplace la virgule de deux rangs à gauche. 4. 8 ÷ 1 000 = 0,08.",
      r: "1. [[Faux]] : cette règle ne vaut que pour les entiers ; pour un décimal on déplace la virgule. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : le résultat est 0,008." },
  ],
},
{
  ch: "Les nombres décimaux",
  titre: "Valeur approchée d'un nombre décimal",
  objectif: "À la fin de la séance, l'élève est capable de donner la troncature et l'arrondi d'un décimal à l'unité, au dixième ou au centième.",
  materiel: "Tableau à double entrée au tableau, ardoises, étiquettes-nombres",
  rev: [["Calcule 4,5 × 100.", "450."],
        ["Calcule 30 ÷ 1 000.", "0,03."],
        ["Arrondis l'entier 4 380 à la centaine.", "4 400."]],
  mise: { q: "Une balance affiche 7,368 kg. Le vendeur annonce « 7,4 kg ». A-t-il triché ?", ra: "Non, il a donné une valeur approchée." },
  obs: "Observez le tableau à double entrée au tableau : la première colonne indique le rang choisi, la deuxième la troncature de 7,368, la troisième son arrondi.",
  ana: [
    ["Que signifie tronquer un nombre ?", "Couper l'écriture après le rang choisi, sans rien changer d'autre."],
    ["Quelle est la troncature de 7,368 au dixième ?", "7,3, car on coupe après le premier chiffre décimal."],
    ["Quel est l'arrondi au dixième ?", "7,4."],
    ["Pourquoi la troncature et l'arrondi diffèrent-ils ici ?", "Parce que le chiffre suivant est 6, supérieur ou égal à 5, donc on monte."],
    ["Quelle est la troncature au centième ?", "7,36."],
    ["Et l'arrondi au centième ?", "7,37, car le chiffre suivant est 8."],
    ["Quand troncature et arrondi sont-ils identiques ?", "Quand le chiffre qui suit est 0, 1, 2, 3 ou 4."],
  ],
  syn: "Donc, tronquer un décimal consiste à couper son écriture après le rang choisi. L'arrondir consiste à regarder le chiffre suivant : s'il vaut 0 à 4, on garde la troncature ; s'il vaut 5 à 9, on ajoute une unité au dernier rang conservé.",
  attention: "Troncature et arrondi ne se confondent pas. La troncature de 7,368 au dixième est 7,3 ; son arrondi est 7,4. Les deux coïncident seulement quand le chiffre suivant est inférieur à 5.",
  astuce: "Tronquer, c'est « couper » sans réfléchir. Arrondir, c'est couper puis regarder le chiffre juste après : s'il atteint 5, on monte d'un cran.",
  app: [
    { c: "Pour le nombre 7,368, donne :\n1. la troncature à l'unité\n2. l'arrondi à l'unité\n3. la troncature au dixième\n4. l'arrondi au centième",
      r: "1. [[7]]\n2. [[7]], car le chiffre suivant est 3\n3. [[7,3]]\n4. [[7,37]], car le chiffre suivant est 8" },
    { c: "Arrondis au dixième :\n1. 12,45\n2. 3,99\n3. 0,62\n4. 8,05",
      r: "1. [[12,5]]\n2. [[4,0]] soit 4\n3. [[0,6]]\n4. [[8,1]]" },
  ],
  evalx: [
    { c: "Complète pour 5,872 :\n1. troncature au dixième\n2. arrondi au dixième\n3. troncature au centième\n4. arrondi au centième",
      r: "1. [[5,8]]\n2. [[5,9]]\n3. [[5,87]]\n4. [[5,87]]" },
    { c: "Vrai ou faux ?\n1. La troncature est toujours égale à l'arrondi.\n2. Arrondir 2,96 au dixième donne 3.\n3. Tronquer, c'est couper l'écriture.\n4. L'arrondi de 0,449 à l'unité est 1.",
      r: "1. [[Faux]] : elles diffèrent dès que le chiffre suivant atteint 5.\n2. [[Vrai]] : on obtient 3,0, c'est-à-dire 3.\n3. [[Vrai]].\n4. [[Faux]] : le chiffre des dixièmes est 4, donc l'arrondi est 0." },
  ],
  lecon: [
    ["1. Pourquoi une valeur approchée", "Certaines mesures donnent beaucoup de décimales : une balance affiche 7,368 kg. Dans la vie courante, on préfère annoncer 7,4 kg. On remplace alors le nombre exact par une {{valeur approchée}}."],
    ["2. La troncature", "{{Tronquer}} un décimal à un rang donné, c'est couper son écriture juste après ce rang, sans modifier les chiffres conservés.\nPour 7,368 : la troncature à l'unité est 7 ; au dixième, 7,3 ; au centième, 7,36.\nLa troncature est toujours {{inférieure ou égale}} au nombre de départ."],
    ["3. L'arrondi", "{{Arrondir}} demande d'observer le chiffre situé juste après le rang conservé :\n— s'il vaut 0, 1, 2, 3 ou 4, l'arrondi est égal à la troncature ;\n— s'il vaut 5, 6, 7, 8 ou 9, on ajoute une unité au dernier rang conservé.\nPour 7,368 au dixième : le chiffre suivant est 6, donc l'arrondi est 7,4."],
    ["4. Comparer les deux", "Le tableau ci-dessous résume le cas de 7,368 :\n— à l'unité : troncature 7, arrondi 7 ;\n— au dixième : troncature 7,3, arrondi 7,4 ;\n— au centième : troncature 7,36, arrondi 7,37.\nOn note ces valeurs avec le signe {{≈}} : 7,368 ≈ 7,4 au dixième près."],
  ],
  exos: [
    { pts: 4, c: "Donne la troncature et l'arrondi de 9,547 au dixième.",
      r: "Troncature : [[9,5]]. Arrondi : [[9,5]], car le chiffre suivant est 4, inférieur à 5." },
    { pts: 4, c: "Donne la troncature et l'arrondi de 3,286 au centième.",
      r: "Troncature : [[3,28]]. Arrondi : [[3,29]], car le chiffre suivant est 6." },
    { pts: 4, c: "Arrondis à l'unité : 4,7 ; 12,3 ; 0,5 ; 99,8.",
      r: "[[5]] ; [[12]] ; [[1]] ; [[100]]." },
    { pts: 4, c: "Un article coûte 12 486 ariary. Donne une valeur approchée au millier près et explique son intérêt.",
      r: "[[12 000 ariary]], car le chiffre des centaines est 4, inférieur à 5. Cette valeur suffit pour estimer rapidement une dépense." },
    { pts: 4, c: "Trouve un décimal dont la troncature au dixième est 6,2 et l'arrondi au dixième est 6,3.",
      r: "Par exemple [[6,27]] : on coupe à 6,2, mais le chiffre suivant, 7, fait monter l'arrondi à 6,3. Toute réponse entre [[6,25 et 6,29]] convient." },
  ],
},

];
