// Période V — séances rédigées.
module.exports = [
{
  ch: "Pavé droit et cylindre",
  titre: "Découvrir les solides usuels",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître et de nommer les solides usuels du programme.",
  materiel: "Boîtes, briques, boîtes de conserve, ballons, solides en carton",
  rev: [["Combien de côtés a un rectangle ?", "Quatre."],
        ["Qu'est-ce qu'un carré ?", "Un quadrilatère à quatre côtés égaux et quatre angles droits."],
        ["Qu'est-ce qu'un disque ?", "La surface délimitée par un cercle."]],
  mise: { q: "Une boîte d'allumettes et une boîte de conserve occupent toutes deux de la place. Ont-elles la même forme ?", ra: "Non, l'une est un pavé, l'autre un cylindre." },
  obs: "Observez les objets disposés sur la table : une boîte d'allumettes, un dé, une boîte de conserve, un ballon. Chacun occupe un volume dans l'espace.",
  ana: [
    ["Ces objets sont-ils plats ?", "Non, ils occupent de la place dans l'espace."],
    ["Comment nomme-t-on de tels objets en géométrie ?", "Des solides."],
    ["Quelle est la forme de la boîte d'allumettes ?", "Un pavé droit."],
    ["Quelles sont ses faces ?", "Des rectangles."],
    ["Et celle du dé ?", "Un cube."],
    ["Qu'a-t-il de particulier ?", "Toutes ses faces sont des carrés égaux."],
    ["Quelle est la forme de la boîte de conserve ?", "Un cylindre."],
    ["Et celle du ballon ?", "Une sphère."],
  ],
  syn: "Donc, un solide est un objet qui occupe un volume dans l'espace. Le pavé droit a six faces rectangulaires ; le cube est un pavé dont toutes les faces sont des carrés égaux ; le cylindre possède deux bases circulaires ; la sphère est la forme du ballon.",
  attention: "Ne confondez pas les figures planes et les solides. Un carré est une figure plane, un cube est un solide ; un cercle est plan, une sphère est un solide.",
  astuce: "Pour reconnaître un solide, comptez ses faces et observez leur forme : six rectangles donnent un pavé, six carrés un cube, deux disques et une surface courbe un cylindre.",
  app: [
    { c: "Nomme le solide :\n1. une boîte d'allumettes\n2. un dé à jouer\n3. une boîte de conserve\n4. un ballon",
      r: "1. Un [[pavé droit]]\n2. Un [[cube]]\n3. Un [[cylindre]]\n4. Une [[sphère]]" },
    { c: "Figure plane ou solide ?\n1. un carré\n2. un cube\n3. un cercle\n4. un cylindre",
      r: "1. Figure [[plane]]\n2. [[Solide]]\n3. Figure [[plane]]\n4. [[Solide]]" },
  ],
  evalx: [
    { c: "Complète :\n1. Un solide occupe un …… dans l'espace.\n2. Les faces d'un pavé droit sont des ……\n3. Les faces d'un cube sont des ……\n4. Les bases d'un cylindre sont des ……",
      r: "1. [[volume]]\n2. [[rectangles]]\n3. [[carrés]]\n4. [[disques]]" },
    { c: "Cite un objet de la vie courante ayant la forme :\n1. d'un pavé droit\n2. d'un cube\n3. d'un cylindre\n4. d'une sphère",
      r: "1. Une [[brique]] ou un cahier\n2. Un [[dé]]\n3. Une [[boîte de conserve]]\n4. Un [[ballon]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'un solide", "Un {{solide}} est un objet qui occupe un {{volume}} dans l'espace, à la différence d'une figure plane qui se dessine entièrement sur une feuille.\nUn carré est une figure plane ; un cube est un solide."],
    ["2. Le pavé droit", "Le {{pavé droit}} est le solide le plus courant : boîte, brique, cahier, pièce d'habitation.\nIl possède {{six faces}} qui sont toutes des {{rectangles}}. Ses faces opposées sont identiques."],
    ["3. Le cube", "Le {{cube}} est un pavé droit particulier dont les six faces sont des {{carrés}} égaux.\nToutes ses arêtes ont la même longueur. Un dé à jouer en est l'exemple le plus familier."],
    ["4. Le cylindre et la sphère", "Le {{cylindre}} possède deux {{bases}} circulaires identiques reliées par une surface courbe : c'est la forme d'une boîte de conserve ou d'un tuyau.\nLa {{sphère}} est la forme du ballon : tous ses points sont à égale distance de son centre."],
  ],
  exos: [
    { pts: 4, c: "Nomme le solide correspondant : une boîte d'allumettes, un dé, une boîte de conserve, un ballon.",
      r: "[[Pavé droit]] ; [[cube]] ; [[cylindre]] ; [[sphère]]." },
    { pts: 4, c: "Quelle est la différence entre une figure plane et un solide ?",
      r: "Une figure [[plane]] se dessine entièrement sur une feuille ; un [[solide]] occupe un [[volume]] dans l'espace." },
    { pts: 4, c: "Décris les faces d'un pavé droit et celles d'un cube.",
      r: "Le pavé droit a six faces [[rectangulaires]] ; le cube a six faces [[carrées égales]]." },
    { pts: 4, c: "Décris le cylindre.",
      r: "Il possède deux [[bases circulaires]] identiques reliées par une [[surface courbe]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Un cube est un pavé droit particulier. 2. Un cercle est un solide. 3. Le cylindre a deux bases disques. 4. Les faces opposées d'un pavé sont identiques.",
      r: "1. [[Vrai]]. 2. [[Faux]] : c'est une figure plane. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Faces, arêtes et sommets du pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de dénombrer et de nommer les faces, arêtes et sommets d'un pavé droit.",
  materiel: "Pavés en carton, boîtes, règle, ardoises",
  rev: [["Combien de faces a un pavé droit ?", "Six."],
        ["De quelle forme sont ces faces ?", "Des rectangles."],
        ["Qu'est-ce qu'un cube ?", "Un pavé dont les faces sont des carrés égaux."]],
  mise: { q: "Combien de coups de crayon faut-il pour repasser toutes les arêtes d'une boîte ?", ra: "Douze." },
  obs: "Observez le pavé en carton que manipule l'enseignant : il compte à voix haute les faces, puis les segments qui les séparent, puis les coins.",
  ana: [
    ["Combien de faces compte-t-on ?", "Six."],
    ["Comment nomme-t-on les segments séparant deux faces ?", "Des arêtes."],
    ["Combien y en a-t-il ?", "Douze."],
    ["Comment nomme-t-on les coins ?", "Des sommets."],
    ["Combien y en a-t-il ?", "Huit."],
    ["Les faces opposées sont-elles identiques ?", "Oui, deux à deux."],
    ["Combien de dimensions décrivent un pavé ?", "Trois : longueur, largeur, hauteur."],
    ["Et pour un cube ?", "Une seule, car les trois sont égales."],
  ],
  syn: "Donc, un pavé droit possède six faces rectangulaires, douze arêtes et huit sommets. Ses faces opposées sont identiques deux à deux, et trois dimensions suffisent à le décrire : la longueur, la largeur et la hauteur. Dans un cube, ces trois dimensions sont égales.",
  attention: "Une arête n'est pas une face. L'arête est un segment, la face une surface : on compte douze arêtes mais seulement six faces.",
  astuce: "Les douze arêtes se répartissent en trois groupes de quatre, un par dimension. C'est pourquoi la somme des arêtes vaut quatre fois la somme des trois dimensions.",
  app: [
    { c: "Pour un pavé droit :\n1. Combien de faces ?\n2. Combien d'arêtes ?\n3. Combien de sommets ?\n4. Combien de dimensions le décrivent ?",
      r: "1. [[Six]]\n2. [[Douze]]\n3. [[Huit]]\n4. [[Trois]]" },
    { c: "Un pavé mesure 8 cm, 5 cm et 3 cm.\n1. Combien d'arêtes de 8 cm ?\n2. Combien de 5 cm ?\n3. Combien de 3 cm ?\n4. Quelle est la somme de toutes les arêtes ?",
      r: "1. [[Quatre]]\n2. [[Quatre]]\n3. [[Quatre]]\n4. 4 × (8 + 5 + 3) = [[64 cm]]" },
  ],
  evalx: [
    { c: "Un cube a 5 cm d'arête.\n1. Combien d'arêtes possède-t-il ?\n2. Quelle est la somme de leurs longueurs ?\n3. Quelle est l'aire d'une face ?\n4. Quelle est l'aire totale de ses faces ?",
      r: "1. [[Douze]]\n2. [[60 cm]]\n3. [[25 cm²]]\n4. [[150 cm²]]" },
    { c: "Complète :\n1. Un segment séparant deux faces est une ……\n2. Un coin est un ……\n3. Les faces opposées sont ……\n4. Dans un cube, les trois dimensions sont ……",
      r: "1. [[arête]]\n2. [[sommet]]\n3. [[identiques]]\n4. [[égales]]" },
  ],
  lecon: [
    ["1. Les faces", "Le pavé droit possède {{six faces}}, toutes rectangulaires.\nElles sont identiques {{deux à deux}} : la face du dessus est identique à celle du dessous, la face avant à la face arrière, la face gauche à la face droite."],
    ["2. Les arêtes", "Une {{arête}} est le segment le long duquel deux faces se rencontrent.\nUn pavé droit compte {{douze}} arêtes, réparties en trois groupes de quatre : quatre longueurs, quatre largeurs et quatre hauteurs."],
    ["3. Les sommets", "Un {{sommet}} est un coin du solide, point de rencontre de trois arêtes.\nUn pavé droit possède {{huit}} sommets."],
    ["4. Les dimensions", "Trois nombres suffisent à décrire un pavé droit : sa {{longueur}}, sa {{largeur}} et sa {{hauteur}}.\nLa somme de toutes ses arêtes vaut 4 × (Longueur + largeur + hauteur). Pour 8 cm, 5 cm et 3 cm : 4 × 16 = 64 cm.\nDans un {{cube}}, les trois dimensions sont égales."],
  ],
  exos: [
    { pts: 4, c: "Combien de faces, d'arêtes et de sommets possède un pavé droit ?",
      r: "[[6 faces]], [[12 arêtes]] et [[8 sommets]]." },
    { pts: 4, c: "Un pavé mesure 8 cm, 5 cm et 3 cm. Quelle est la somme des longueurs de toutes ses arêtes ?",
      r: "4 × (8 + 5 + 3) = 4 × 16 = [[64 cm]]." },
    { pts: 4, c: "Un cube a 5 cm d'arête. Quelle est la somme des longueurs de ses arêtes ?",
      r: "12 × 5 = [[60 cm]]." },
    { pts: 4, c: "Explique la différence entre une face, une arête et un sommet.",
      r: "La [[face]] est une surface, l'[[arête]] un segment séparant deux faces, le [[sommet]] un coin où se rencontrent trois arêtes." },
    { pts: 4, c: "Vrai ou faux ? 1. Un pavé a huit arêtes. 2. Ses faces opposées sont identiques. 3. Un cube a douze arêtes égales. 4. Trois dimensions décrivent un pavé.",
      r: "1. [[Faux]] : douze. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Le patron du pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître et de tracer un patron de pavé droit ou de cube.",
  materiel: "Boîtes à découper, papier quadrillé, ciseaux, ruban adhésif",
  rev: [["Combien de faces a un pavé droit ?", "Six."],
        ["De quelle forme sont-elles ?", "Des rectangles."],
        ["Combien de faces a un cube ?", "Six carrés égaux."]],
  mise: { q: "Si l'on découpe une boîte le long de certaines arêtes et qu'on l'aplatit, qu'obtient-on ?", ra: "Une figure plane formée de six rectangles." },
  obs: "Observez la manipulation : l'enseignant découpe une boîte le long de sept arêtes, puis l'aplatit sur la table. Six rectangles apparaissent, reliés entre eux.",
  ana: [
    ["Combien de rectangles obtient-on ?", "Six."],
    ["Que représentent-ils ?", "Les six faces de la boîte."],
    ["Comment nomme-t-on cette figure à plat ?", "Le patron du solide."],
    ["Les six rectangles sont-ils quelconques ?", "Non, ils sont identiques deux à deux."],
    ["Peut-on les disposer n'importe comment ?", "Non, il faut pouvoir replier le patron."],
    ["Comment vérifier un patron ?", "En le découpant et en le pliant."],
    ["Combien de carrés dans le patron d'un cube ?", "Six carrés égaux."],
  ],
  syn: "Donc, le patron d'un solide est la figure plane obtenue en le dépliant. Le patron d'un pavé droit se compose de six rectangles identiques deux à deux, et celui d'un cube de six carrés égaux. Leur disposition doit permettre de replier la figure sans recouvrement ni manque.",
  attention: "Six rectangles convenables ne forment pas nécessairement un patron : la disposition compte autant que les dimensions. Deux faces qui se superposeraient au pliage rendent le patron faux.",
  astuce: "Avant de découper, vérifiez par la pensée le pliage face par face, ou marquez d'une même couleur les faces qui doivent se retrouver opposées.",
  app: [
    { c: "Un pavé mesure 6 cm, 4 cm et 3 cm.\n1. Combien de rectangles dans son patron ?\n2. Quelles dimensions pour deux d'entre eux ?\n3. Combien de rectangles de 6 sur 4 ?\n4. Et de 4 sur 3 ?",
      r: "1. [[Six]]\n2. [[6 cm sur 4 cm]], par exemple\n3. [[Deux]]\n4. [[Deux]]" },
    { c: "Réponds :\n1. Qu'est-ce qu'un patron ?\n2. Combien de carrés pour un cube ?\n3. Comment vérifier un patron ?\n4. Six rectangles suffisent-ils toujours ?",
      r: "1. La figure [[plane]] obtenue en dépliant le solide\n2. [[Six carrés égaux]]\n3. En le [[découpant et le pliant]]\n4. [[Non]], la disposition compte" },
  ],
  evalx: [
    { c: "Un cube a 4 cm d'arête.\n1. Quelle est l'aire d'une face ?\n2. Combien de faces ?\n3. Quelle est l'aire totale du patron ?\n4. Que représente cette aire ?",
      r: "1. [[16 cm²]]\n2. [[Six]]\n3. [[96 cm²]]\n4. La [[surface de carton]] nécessaire" },
    { c: "Complète :\n1. Un patron est une figure ……\n2. Il comporte autant de parties que le solide a de ……\n3. Le patron du cube comporte six ……\n4. On le vérifie en le ……",
      r: "1. [[plane]]\n2. [[faces]]\n3. [[carrés égaux]]\n4. [[pliant]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'un patron", "Le {{patron}} d'un solide est la figure {{plane}} que l'on obtient en le dépliant, après l'avoir découpé le long de certaines arêtes.\nReplié, le patron reconstitue exactement le solide."],
    ["2. Le patron du pavé droit", "Il se compose de {{six rectangles}}, identiques {{deux à deux}}.\nPour un pavé de 6 cm sur 4 cm sur 3 cm, on trouve deux rectangles de 6 sur 4, deux de 6 sur 3 et deux de 4 sur 3."],
    ["3. Le patron du cube", "Il se compose de {{six carrés}} égaux.\nPlusieurs dispositions différentes conviennent, mais toutes ne sont pas valables : il faut pouvoir replier la figure sans {{recouvrement}} ni manque."],
    ["4. Vérifier et utiliser un patron", "La vérification la plus sûre consiste à {{découper}} le patron et à le {{plier}}.\nL'aire totale du patron donne la {{surface}} de carton nécessaire à la fabrication du solide : pour un cube de 4 cm d'arête, 6 × 16 = 96 cm²."],
  ],
  exos: [
    { pts: 4, c: "Qu'est-ce que le patron d'un solide ?",
      r: "C'est la figure [[plane]] obtenue en [[dépliant]] le solide, et qui permet de le reconstituer par pliage." },
    { pts: 4, c: "De combien de rectangles se compose le patron d'un pavé droit, et comment sont-ils appariés ?",
      r: "De [[six rectangles]], identiques [[deux à deux]]." },
    { pts: 4, c: "Un cube a 4 cm d'arête. Quelle est l'aire totale de son patron ?",
      r: "Une face : 16 cm². Six faces : [[96 cm²]]." },
    { pts: 4, c: "Un pavé mesure 6 cm sur 4 cm sur 3 cm. Quelle est l'aire totale de son patron ?",
      r: "2 × (24 + 18 + 12) = [[108 cm²]]." },
    { pts: 4, c: "Pourquoi six rectangles de bonnes dimensions ne forment-ils pas toujours un patron ?",
      r: "Parce que leur [[disposition]] doit permettre le pliage : deux faces qui se [[superposeraient]] rendent le patron faux." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Représenter un pavé en perspective",
  objectif: "À la fin de la séance, l'élève est capable de lire et de tracer la représentation en perspective d'un pavé droit.",
  materiel: "Papier quadrillé, règle, pavés en carton",
  rev: [["Combien d'arêtes a un pavé ?", "Douze."],
        ["Qu'est-ce qu'un patron ?", "La figure plane obtenue en dépliant le solide."],
        ["Que signifie le symbole // ?", "Parallèle."]],
  mise: { q: "Comment dessiner une boîte sur une feuille plate de façon qu'on la reconnaisse en trois dimensions ?", ra: "En la dessinant en perspective." },
  obs: "Observez le dessin au tableau : la face avant du pavé est un rectangle en trait plein, des segments obliques partent de ses sommets, et certaines arêtes du fond sont tracées en pointillés.",
  ana: [
    ["Comment est dessinée la face avant ?", "En vraie grandeur, en trait plein."],
    ["Que représentent les segments obliques ?", "Les arêtes qui s'éloignent vers le fond."],
    ["Sont-ils parallèles entre eux ?", "Oui, tous."],
    ["Pourquoi certaines arêtes sont-elles en pointillés ?", "Parce qu'elles sont cachées par le solide."],
    ["Combien d'arêtes sont cachées ?", "Trois, celles qui aboutissent au sommet arrière."],
    ["Les angles droits sont-ils tous respectés ?", "Non, certains apparaissent obliques."],
    ["Les longueurs sont-elles toutes exactes ?", "Non, les fuyantes sont souvent raccourcies."],
  ],
  syn: "Donc, la perspective permet de représenter un solide sur une feuille plane. La face avant se dessine en vraie grandeur, les arêtes fuyantes sont parallèles entre elles, et les arêtes cachées se tracent en pointillés. Angles droits et longueurs ne sont pas tous conservés.",
  attention: "Un dessin en perspective déforme la réalité : les angles droits du fond n'apparaissent pas droits, et les fuyantes sont raccourcies. Il ne faut donc jamais mesurer une longueur sur un tel dessin.",
  astuce: "Le papier quadrillé facilite le tracé : la face avant suit les lignes du quadrillage, et les fuyantes suivent régulièrement les diagonales des carreaux.",
  app: [
    { c: "Sur un dessin en perspective d'un pavé :\n1. Comment est tracée la face avant ?\n2. Comment sont les fuyantes entre elles ?\n3. Comment trace-t-on les arêtes cachées ?\n4. Combien y en a-t-il ?",
      r: "1. En [[vraie grandeur]]\n2. [[Parallèles]]\n3. En [[pointillés]]\n4. [[Trois]]" },
    { c: "Réponds :\n1. La perspective conserve-t-elle les angles droits ?\n2. Conserve-t-elle les longueurs ?\n3. Peut-on y mesurer une arête ?\n4. À quoi sert-elle alors ?",
      r: "1. [[Non]], pas tous\n2. [[Non]], les fuyantes sont raccourcies\n3. [[Non]]\n4. À [[représenter]] le solide et à comprendre sa forme" },
  ],
  evalx: [
    { c: "Un pavé est dessiné en perspective.\n1. Combien d'arêtes au total ?\n2. Combien visibles ?\n3. Combien cachées ?\n4. Combien de sommets sont cachés ?",
      r: "1. [[Douze]]\n2. [[Neuf]]\n3. [[Trois]]\n4. [[Un seul]]" },
    { c: "Complète :\n1. La face avant est en …… grandeur.\n2. Les fuyantes sont ……\n3. Les arêtes cachées sont en ……\n4. La perspective …… la réalité.",
      r: "1. [[vraie]]\n2. [[parallèles]]\n3. [[pointillés]]\n4. [[déforme]]" },
  ],
  lecon: [
    ["1. Pourquoi la perspective", "Une feuille est {{plane}}, un solide occupe l'{{espace}}. Pour représenter l'un sur l'autre, on emploie un dessin en {{perspective}}, qui donne l'illusion du relief."],
    ["2. Les règles du tracé", "— La {{face avant}} se dessine en vraie grandeur, avec ses angles droits.\n— Les arêtes {{fuyantes}}, qui s'éloignent vers le fond, se tracent {{parallèles}} entre elles et souvent raccourcies.\n— La face arrière est identique à la face avant et lui est parallèle."],
    ["3. Les arêtes cachées", "Les arêtes que le solide dissimule au regard se tracent en {{pointillés}}.\nDans un pavé, {{trois}} arêtes sont cachées : celles qui aboutissent au sommet arrière, lui-même caché."],
    ["4. Les limites du dessin", "La perspective {{déforme}} : les angles droits du fond apparaissent obliques, et les fuyantes sont plus courtes qu'en réalité.\nIl ne faut donc jamais {{mesurer}} une longueur sur un dessin en perspective : seules les indications chiffrées font foi."],
  ],
  exos: [
    { pts: 4, c: "Énonce les trois règles du tracé d'un pavé en perspective.",
      r: "Face avant en [[vraie grandeur]] ; fuyantes [[parallèles]] entre elles ; arêtes cachées en [[pointillés]]." },
    { pts: 4, c: "Combien d'arêtes d'un pavé sont cachées sur un dessin en perspective, et combien sont visibles ?",
      r: "[[Trois]] cachées et [[neuf]] visibles, sur un total de douze." },
    { pts: 4, c: "Pourquoi ne peut-on pas mesurer une longueur sur un dessin en perspective ?",
      r: "Parce que les [[fuyantes]] sont [[raccourcies]] et que le dessin déforme la réalité." },
    { pts: 4, c: "Quelle est la différence entre un patron et une perspective ?",
      r: "Le [[patron]] se plie pour reconstituer le solide et conserve les vraies dimensions ; la [[perspective]] est un dessin qui donne l'illusion du [[relief]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Les fuyantes sont parallèles. 2. Les arêtes cachées sont en trait plein. 3. La face avant est en vraie grandeur. 4. Un pavé a un seul sommet caché.",
      r: "1. [[Vrai]]. 2. [[Faux]] : en pointillés. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "L'aire totale d'un pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de calculer l'aire totale des faces d'un pavé droit et d'un cube.",
  materiel: "Patrons, pavés en carton, règle, ardoises",
  rev: [["Quelle est l'aire d'un rectangle de 6 cm sur 4 cm ?", "24 cm²."],
        ["Quelle est l'aire d'un carré de 4 cm ?", "16 cm²."],
        ["Combien de faces a un pavé ?", "Six."]],
  mise: { q: "Combien de carton faut-il pour fabriquer une boîte sans couvercle manquant ?", ra: "Autant que l'aire totale de ses six faces." },
  obs: "Observez le patron déplié d'un pavé de 6 cm sur 4 cm sur 3 cm : on y lit deux rectangles de 6 sur 4, deux de 6 sur 3 et deux de 4 sur 3.",
  ana: [
    ["Quelle est l'aire d'un rectangle de 6 sur 4 ?", "Vingt-quatre centimètres carrés."],
    ["Combien y en a-t-il ?", "Deux."],
    ["Quelle est l'aire d'un rectangle de 6 sur 3 ?", "Dix-huit centimètres carrés."],
    ["Et celle d'un rectangle de 4 sur 3 ?", "Douze centimètres carrés."],
    ["Comment obtenir l'aire totale ?", "En additionnant les six aires."],
    ["Combien vaut-elle ?", "Cent huit centimètres carrés."],
    ["Quelle écriture plus courte peut-on employer ?", "Deux fois la somme des trois produits."],
    ["Et pour un cube d'arête 4 ?", "Six fois seize, soit quatre-vingt-seize."],
  ],
  syn: "Donc, l'aire totale d'un pavé droit est la somme des aires de ses six faces. Comme elles sont identiques deux à deux, on calcule deux fois la somme des trois produits des dimensions prises deux à deux. Pour un cube, l'aire totale vaut six fois l'aire d'une face.",
  attention: "L'aire totale s'exprime en unités carrées, jamais en unités cubiques. Elle mesure une surface de carton, non la place occupée dans l'espace.",
  astuce: "Vérifiez sur le patron : le nombre de rectangles doit toujours être six, et l'aire totale du patron est exactement l'aire totale du solide.",
  app: [
    { c: "Un pavé mesure 6 cm, 4 cm et 3 cm.\n1. Aire des deux faces de 6 sur 4 ?\n2. Des deux faces de 6 sur 3 ?\n3. Des deux faces de 4 sur 3 ?\n4. Aire totale ?",
      r: "1. [[48 cm²]]\n2. [[36 cm²]]\n3. [[24 cm²]]\n4. [[108 cm²]]" },
    { c: "Calcule l'aire totale :\n1. d'un cube de 4 cm d'arête\n2. d'un cube de 5 cm d'arête\n3. d'un cube de 10 cm d'arête\n4. Quelle formule emploies-tu ?",
      r: "1. [[96 cm²]]\n2. [[150 cm²]]\n3. [[600 cm²]]\n4. [[6 × côté × côté]]" },
  ],
  evalx: [
    { c: "Une boîte mesure 20 cm, 15 cm et 10 cm.\n1. Aire des deux plus grandes faces ?\n2. Aire des deux faces de 20 sur 10 ?\n3. Aire des deux faces de 15 sur 10 ?\n4. Aire totale ?",
      r: "1. [[600 cm²]]\n2. [[400 cm²]]\n3. [[300 cm²]]\n4. [[1 300 cm²]]" },
    { c: "Complète :\n1. L'aire totale est la somme des aires des …… faces.\n2. Elle s'exprime en unités ……\n3. Pour un cube, elle vaut …… fois l'aire d'une face.\n4. Elle correspond à l'aire du ……",
      r: "1. [[six]]\n2. [[carrées]]\n3. [[six]]\n4. [[patron]]" },
  ],
  lecon: [
    ["1. Le principe", "L'{{aire totale}} d'un pavé droit est la somme des aires de ses {{six faces}}.\nElle correspond exactement à l'aire de son {{patron}}, c'est-à-dire à la surface de carton nécessaire pour le fabriquer."],
    ["2. Le calcul pour un pavé", "Les faces étant identiques deux à deux, on calcule trois produits et l'on double la somme :\nAire totale = 2 × (L × l + L × h + l × h).\nPour 6 cm, 4 cm et 3 cm : 2 × (24 + 18 + 12) = 2 × 54 = 108 cm²."],
    ["3. Le cas du cube", "Toutes les faces d'un cube étant des carrés {{égaux}} :\nAire totale = {{6 × côté × côté}}.\nPour un cube de 4 cm d'arête : 6 × 16 = 96 cm²."],
    ["4. Les unités", "L'aire totale mesure une {{surface}} : elle s'exprime en cm², en m², jamais en unités cubiques.\nComme toujours, les trois dimensions doivent être exprimées dans la {{même unité}} avant le calcul."],
  ],
  exos: [
    { pts: 4, c: "Calcule l'aire totale d'un pavé de 6 cm sur 4 cm sur 3 cm.",
      r: "2 × (24 + 18 + 12) = [[108 cm²]]." },
    { pts: 4, c: "Calcule l'aire totale d'un cube de 5 cm d'arête.",
      r: "6 × 25 = [[150 cm²]]." },
    { pts: 4, c: "Une boîte mesure 20 cm, 15 cm et 10 cm. Quelle surface de carton faut-il pour la fabriquer ?",
      r: "2 × (300 + 200 + 150) = [[1 300 cm²]]." },
    { pts: 4, c: "Un cube a 10 cm d'arête. Quelle est l'aire totale de ses faces ?",
      r: "6 × 100 = [[600 cm²]]." },
    { pts: 4, c: "Vrai ou faux ? 1. L'aire totale s'exprime en cm³. 2. Elle égale l'aire du patron. 3. Pour un cube, elle vaut 6 fois l'aire d'une face. 4. Les faces d'un pavé sont identiques deux à deux.",
      r: "1. [[Faux]] : en cm². 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Le cylindre et son patron",
  objectif: "À la fin de la séance, l'élève est capable de décrire un cylindre, d'en reconnaître le patron et d'en calculer l'aire de base.",
  materiel: "Boîtes de conserve, étiquettes, compas, ciseaux",
  rev: [["Quelle est l'aire d'un disque de rayon 3 cm ?", "28,26 cm²."],
        ["Quelle est la circonférence d'un cercle de rayon 3 cm ?", "18,84 cm."],
        ["Qu'est-ce qu'un patron ?", "La figure plane obtenue en dépliant le solide."]],
  mise: { q: "Si l'on décolle l'étiquette d'une boîte de conserve et qu'on l'aplatit, quelle forme obtient-on ?", ra: "Un rectangle." },
  obs: "Observez la manipulation : l'enseignant décolle l'étiquette d'une boîte de conserve, l'aplatit — c'est un rectangle — puis découpe les deux fonds, qui sont deux disques.",
  ana: [
    ["Combien de bases a le cylindre ?", "Deux."],
    ["Quelle est leur forme ?", "Des disques identiques."],
    ["Que devient la surface courbe une fois aplatie ?", "Un rectangle."],
    ["Que représente la longueur de ce rectangle ?", "La circonférence de la base."],
    ["Et sa largeur ?", "La hauteur du cylindre."],
    ["De quoi se compose donc le patron ?", "De deux disques et d'un rectangle."],
    ["Quelle est l'aire d'une base de rayon 3 cm ?", "28,26 centimètres carrés."],
  ],
  syn: "Donc, un cylindre possède deux bases circulaires identiques reliées par une surface courbe. Son patron se compose de deux disques et d'un rectangle dont la longueur est la circonférence de la base et la largeur la hauteur du cylindre. L'aire d'une base se calcule par pi multiplié deux fois par le rayon.",
  attention: "La longueur du rectangle du patron n'est pas le diamètre mais la circonférence de la base. Une étiquette trop courte ne ferait pas le tour de la boîte.",
  astuce: "Pour tracer le patron, calculez d'abord la circonférence : c'est elle qui fixe la longueur du rectangle et donc la réussite du collage.",
  app: [
    { c: "Un cylindre a un rayon de 3 cm et une hauteur de 10 cm.\n1. Quelle est l'aire d'une base ?\n2. Quelle est la circonférence de la base ?\n3. Quelles sont les dimensions du rectangle du patron ?\n4. Combien de disques dans le patron ?",
      r: "1. [[28,26 cm²]]\n2. [[18,84 cm]]\n3. [[18,84 cm sur 10 cm]]\n4. [[Deux]]" },
    { c: "Réponds :\n1. Combien de bases a un cylindre ?\n2. De quelle forme ?\n3. Que devient la surface courbe aplatie ?\n4. Que représente sa longueur ?",
      r: "1. [[Deux]]\n2. Des [[disques identiques]]\n3. Un [[rectangle]]\n4. La [[circonférence]] de la base" },
  ],
  evalx: [
    { c: "Une boîte de conserve a 4 cm de rayon et 12 cm de hauteur.\n1. Circonférence de la base ?\n2. Longueur de l'étiquette ?\n3. Largeur de l'étiquette ?\n4. Aire de l'étiquette ?",
      r: "1. [[25,12 cm]]\n2. [[25,12 cm]]\n3. [[12 cm]]\n4. [[301,44 cm²]]" },
    { c: "Complète :\n1. Le cylindre a deux bases en forme de ……\n2. Son patron comporte …… disques et un ……\n3. La longueur du rectangle est la ……\n4. Sa largeur est la ……",
      r: "1. [[disques]]\n2. [[deux]] ; [[rectangle]]\n3. [[circonférence de la base]]\n4. [[hauteur du cylindre]]" },
  ],
  lecon: [
    ["1. Décrire le cylindre", "Un {{cylindre}} est formé de deux {{bases}} circulaires identiques et parallèles, reliées par une surface {{courbe}}.\nLa distance entre les deux bases est sa {{hauteur}}. C'est la forme d'une boîte de conserve, d'un tuyau ou d'un bidon."],
    ["2. Le patron du cylindre", "En dépliant le cylindre, on obtient :\n— {{deux disques}} identiques, les deux bases ;\n— un {{rectangle}}, la surface courbe aplatie, comme l'étiquette d'une boîte de conserve."],
    ["3. Les dimensions du rectangle", "La {{longueur}} du rectangle est égale à la {{circonférence}} de la base, soit 2 × π × rayon : c'est elle qui permet de faire le tour.\nSa {{largeur}} est égale à la {{hauteur}} du cylindre.\nPour un rayon de 3 cm et une hauteur de 10 cm : 18,84 cm sur 10 cm."],
    ["4. L'aire de la base", "L'aire d'une base se calcule comme celle d'un {{disque}} : π × rayon × rayon.\nPour un rayon de 3 cm : 3,14 × 3 × 3 = 28,26 cm²."],
  ],
  exos: [
    { pts: 4, c: "Décris le patron d'un cylindre.",
      r: "Il comporte [[deux disques]] identiques, les bases, et un [[rectangle]] correspondant à la surface courbe." },
    { pts: 4, c: "Un cylindre a 3 cm de rayon et 10 cm de hauteur. Quelles sont les dimensions du rectangle de son patron ?",
      r: "Longueur : 2 × 3,14 × 3 = [[18,84 cm]]. Largeur : [[10 cm]]." },
    { pts: 4, c: "Calcule l'aire d'une base de ce cylindre.",
      r: "3,14 × 3 × 3 = [[28,26 cm²]]." },
    { pts: 4, c: "Une boîte de conserve a 4 cm de rayon et 12 cm de hauteur. Quelle est l'aire de son étiquette ?",
      r: "Circonférence : 25,12 cm. Aire : 25,12 × 12 = [[301,44 cm²]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Le cylindre a deux bases carrées. 2. La longueur du rectangle est la circonférence. 3. Sa largeur est la hauteur. 4. Le patron comporte trois parties.",
      r: "1. [[Faux]] : circulaires. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]] : deux disques et un rectangle." },
  ],
},
];
