// Période III — séances rédigées.
module.exports = [
{
  ch: "Cercles, triangles et quadrilatères",
  titre: "Le cercle : vocabulaire et constructions",
  objectif: "À la fin de la séance, l'élève est capable d'employer le vocabulaire du cercle et de construire un cercle passant par des points donnés.",
  materiel: "Compas, règle graduée, cahier de géométrie",
  rev: [["Que vaut le diamètre d'un cercle de rayon 5 cm ?", "10 cm."],
        ["Quelle formule donne la circonférence ?", "Deux fois pi fois le rayon."],
        ["De combien ouvre-t-on le compas ?", "Du rayon."]],
  mise: { q: "Sur un cercle tracé au tableau, tous les segments joignant deux points du cercle sont-ils des diamètres ?", ra: "Non, seuls ceux qui passent par le centre." },
  obs: "Observez au tableau un cercle de centre O. Un segment [AB] joint deux points du cercle sans passer par O ; un segment [CD] passe par O ; un arc est repassé en couleur entre A et B.",
  ana: [
    ["Comment nomme-t-on le segment [AB] ?", "Une corde."],
    ["Et le segment [CD] qui passe par O ?", "Un diamètre."],
    ["Le diamètre est-il une corde ?", "Oui, c'est la plus longue de toutes."],
    ["Comment nomme-t-on la portion de cercle colorée ?", "Un arc de cercle."],
    ["Quelle différence entre le cercle et le disque ?", "Le cercle est le contour, le disque est la surface intérieure."],
    ["Que faut-il connaître pour tracer un cercle ?", "Son centre et son rayon."],
    ["Comment tracer un cercle passant par deux points donnés ?", "En choisissant un centre à égale distance des deux points."],
  ],
  syn: "Donc, dans un cercle de centre O, une corde joint deux points du cercle, un diamètre est une corde passant par le centre, et un arc est une portion du cercle. Le cercle désigne le contour, le disque la surface qu'il délimite. Un cercle est entièrement déterminé par son centre et son rayon.",
  attention: "Cercle et disque ne se confondent pas. Un point situé à l'intérieur appartient au disque mais non au cercle : seuls les points du contour sont sur le cercle.",
  astuce: "Pour vérifier qu'un point appartient au cercle, mesurez sa distance au centre : elle doit être exactement égale au rayon.",
  app: [
    { c: "Trace un cercle de centre O et de rayon 4 cm.\n1. Trace une corde [AB].\n2. Trace un diamètre [CD].\n3. Que vaut CD ?\n4. Colorie un arc d'extrémités A et B.",
      r: "1. Une [[corde]] joint deux points du cercle\n2. Le [[diamètre]] passe par O\n3. [[8 cm]]\n4. L'[[arc]] est la portion de cercle entre A et B" },
    { c: "Complète :\n1. Le contour se nomme ……\n2. La surface intérieure se nomme ……\n3. La plus longue corde est ……\n4. Un point du disque est-il toujours sur le cercle ?",
      r: "1. le [[cercle]]\n2. le [[disque]]\n3. le [[diamètre]]\n4. [[Non]], seulement s'il est sur le contour" },
  ],
  evalx: [
    { c: "Un cercle a pour rayon 4,5 cm.\n1. Quel est son diamètre ?\n2. Quelle est sa circonférence ?\n3. Une corde peut-elle mesurer 10 cm ?\n4. Justifie.",
      r: "1. [[9 cm]]\n2. 2 × 3,14 × 4,5 = [[28,26 cm]]\n3. [[Non]]\n4. Car aucune corde ne dépasse le [[diamètre]], qui vaut 9 cm" },
    { c: "Vrai ou faux ?\n1. Tout diamètre est une corde.\n2. Toute corde est un diamètre.\n3. Un arc est une portion de cercle.\n4. Le disque est le contour du cercle.",
      r: "1. [[Vrai]]\n2. [[Faux]], seulement si elle passe par le centre\n3. [[Vrai]]\n4. [[Faux]], le disque est la surface" },
  ],
  lecon: [
    ["1. Le cercle et le disque", "Le {{cercle}} de centre O et de rayon r est l'ensemble des points situés à la distance r du point O : c'est un contour.\nLe {{disque}} est la surface délimitée par ce cercle, contour compris. Un point intérieur appartient au disque mais non au cercle."],
    ["2. Cordes et diamètres", "Une {{corde}} est un segment joignant deux points du cercle.\nUn {{diamètre}} est une corde particulière : celle qui passe par le centre. C'est la plus longue de toutes les cordes, et elle vaut deux fois le rayon."],
    ["3. Les arcs", "Un {{arc de cercle}} est une portion du cercle comprise entre deux de ses points. Deux points d'un cercle déterminent toujours deux arcs, l'un plus court, l'autre plus long."],
    ["4. Construire un cercle", "Un cercle est entièrement déterminé par son {{centre}} et son {{rayon}}. Pour le tracer, on pique le compas sur le centre, on l'ouvre du rayon, puis on fait un tour complet.\nPour tracer un cercle passant par un point A donné et de centre O connu, on ouvre simplement le compas de O jusqu'à A."],
  ],
  exos: [
    { pts: 4, c: "Trace un cercle de centre O et de rayon 3,5 cm, puis une corde [AB] et un diamètre [MN]. Que vaut MN ?",
      r: "MN = 2 × 3,5 = [[7 cm]]. La corde [AB] joint deux points du cercle sans passer par O." },
    { pts: 4, c: "Un cercle a pour diamètre 9 cm. Calcule son rayon et sa circonférence.",
      r: "Rayon : [[4,5 cm]]. Circonférence : 3,14 × 9 = [[28,26 cm]]." },
    { pts: 4, c: "Explique la différence entre un cercle et un disque.",
      r: "Le [[cercle]] est le contour, la ligne courbe elle-même. Le [[disque]] est la [[surface]] délimitée par ce contour." },
    { pts: 4, c: "Dans un cercle de rayon 6 cm, quelle est la plus longue corde possible ?",
      r: "Le [[diamètre]], qui mesure [[12 cm]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Le rayon est une corde. 2. Deux points d'un cercle déterminent deux arcs. 3. Le diamètre passe par le centre. 4. Tous les rayons d'un même cercle sont égaux.",
      r: "1. [[Faux]] : une corde joint deux points du cercle, or le centre n'est pas sur le cercle. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Cercles, triangles et quadrilatères",
  titre: "Les triangles et leur classification",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître et de nommer un triangle quelconque, isocèle, équilatéral ou rectangle.",
  materiel: "Règle graduée, équerre, compas, triangles découpés",
  rev: [["Quelle est la plus longue corde d'un cercle ?", "Le diamètre."],
        ["Qu'est-ce qu'un arc de cercle ?", "Une portion de cercle entre deux points."],
        ["Que code un petit carré sur une figure ?", "Un angle droit."]],
  mise: { q: "Tous les triangles se ressemblent-ils ? Qu'est-ce qui permet de les distinguer ?", ra: "La longueur de leurs côtés et la présence d'un angle droit." },
  obs: "Observez au tableau quatre triangles : le premier a trois côtés de longueurs différentes, le deuxième deux côtés égaux codés d'un même trait, le troisième trois côtés égaux, le quatrième porte un petit carré à l'un de ses sommets.",
  ana: [
    ["Combien de côtés et de sommets a un triangle ?", "Trois de chaque."],
    ["Comment nommer le premier triangle ?", "Un triangle quelconque."],
    ["Que signifie le codage du deuxième ?", "Que deux de ses côtés sont égaux."],
    ["Comment se nomme un tel triangle ?", "Un triangle isocèle."],
    ["Et celui dont les trois côtés sont égaux ?", "Un triangle équilatéral."],
    ["Que signale le petit carré du quatrième ?", "Un angle droit."],
    ["Comment se nomme ce triangle ?", "Un triangle rectangle."],
    ["Un triangle peut-il être à la fois isocèle et rectangle ?", "Oui, s'il a un angle droit et deux côtés égaux."],
  ],
  syn: "Donc, un triangle possède trois côtés et trois sommets. Il est isocèle lorsque deux côtés sont égaux, équilatéral lorsque les trois le sont, et rectangle lorsqu'il possède un angle droit. Un triangle sans particularité est dit quelconque.",
  attention: "Un triangle équilatéral est aussi isocèle, puisqu'il possède bien deux côtés égaux parmi ses trois. L'inverse est faux : un triangle isocèle n'a pas forcément trois côtés égaux.",
  astuce: "Pour reconnaître un triangle rectangle, posez l'angle droit de votre équerre sur chacun des trois sommets : s'il coïncide en l'un d'eux, le triangle est rectangle.",
  app: [
    { c: "Nomme chaque triangle :\n1. côtés 3 cm, 4 cm et 5 cm\n2. côtés 4 cm, 4 cm et 6 cm\n3. côtés 5 cm, 5 cm et 5 cm\n4. un triangle portant un petit carré",
      r: "1. [[Quelconque]]\n2. [[Isocèle]]\n3. [[Équilatéral]]\n4. [[Rectangle]]" },
    { c: "Calcule le périmètre :\n1. d'un triangle équilatéral de côté 5 cm\n2. d'un triangle isocèle de côtés 4 cm, 4 cm et 6 cm\n3. d'un triangle de côtés 3 cm, 4 cm et 5 cm\n4. Lequel a le plus grand périmètre ?",
      r: "1. [[15 cm]]\n2. [[14 cm]]\n3. [[12 cm]]\n4. Le triangle [[équilatéral]]" },
  ],
  evalx: [
    { c: "Complète :\n1. Un triangle a …… côtés.\n2. Deux côtés égaux : triangle ……\n3. Trois côtés égaux : triangle ……\n4. Un angle droit : triangle ……",
      r: "1. [[trois]]\n2. [[isocèle]]\n3. [[équilatéral]]\n4. [[rectangle]]" },
    { c: "Un triangle équilatéral a un périmètre de 21 cm.\n1. Que sais-tu de ses côtés ?\n2. Quelle opération donne un côté ?\n3. Combien mesure-t-il ?\n4. Un triangle isocèle de base 5 cm a un périmètre de 19 cm : combien mesurent ses deux côtés égaux ?",
      r: "1. Ils sont [[tous égaux]]\n2. Une [[division par 3]]\n3. [[7 cm]]\n4. [[7 cm]] chacun, car 19 − 5 = 14 puis 14 ÷ 2 = 7" },
  ],
  lecon: [
    ["1. Le triangle", "Un {{triangle}} est un polygone à trois côtés et trois sommets. On le nomme par ses trois sommets : le triangle ABC.\nSon {{périmètre}} est la somme de ses trois côtés."],
    ["2. Triangle isocèle et équilatéral", "Un triangle {{isocèle}} possède deux côtés de même longueur ; on les code d'un même trait sur la figure.\nUn triangle {{équilatéral}} possède trois côtés de même longueur. Son périmètre vaut donc 3 × côté."],
    ["3. Le triangle rectangle", "Un triangle {{rectangle}} possède un {{angle droit}}, signalé par un petit carré au sommet concerné. On le vérifie avec l'{{équerre}}.\nUn triangle peut être à la fois rectangle et isocèle."],
    ["4. Construire un triangle", "Connaissant les trois côtés, on trace d'abord le plus long, puis on reporte au {{compas}} les deux autres longueurs depuis chaque extrémité : leur intersection donne le troisième sommet.\nAttention : la construction n'est possible que si le plus grand côté est {{inférieur}} à la somme des deux autres. Ainsi 3 cm, 4 cm et 5 cm conviennent, car 3 + 4 = 7 est supérieur à 5, mais 2 cm, 3 cm et 6 cm ne conviennent pas."],
  ],
  exos: [
    { pts: 4, c: "Calcule le périmètre d'un triangle équilatéral de 6,5 cm de côté.",
      r: "3 × 6,5 = [[19,5 cm]]." },
    { pts: 4, c: "Un triangle isocèle a deux côtés de 7 cm et une base de 4,5 cm. Quel est son périmètre ?",
      r: "7 + 7 + 4,5 = [[18,5 cm]]." },
    { pts: 4, c: "Peut-on construire un triangle de côtés 2 cm, 3 cm et 6 cm ? Justifie.",
      r: "[[Non]] : 2 + 3 = 5, ce qui est [[inférieur à 6]]. Les deux petits côtés ne peuvent pas se rejoindre." },
    { pts: 4, c: "Un triangle équilatéral a un périmètre de 24 cm. Combien mesure chaque côté ?",
      r: "24 ÷ 3 = [[8 cm]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Un triangle équilatéral est isocèle. 2. Un triangle isocèle est équilatéral. 3. Un triangle rectangle a un angle droit. 4. Un triangle a quatre sommets.",
      r: "1. [[Vrai]]. 2. [[Faux]]. 3. [[Vrai]]. 4. [[Faux]] : il en a trois." },
  ],
},
{
  ch: "Cercles, triangles et quadrilatères",
  titre: "Construire un triangle",
  objectif: "À la fin de la séance, l'élève est capable de construire un triangle connaissant ses trois côtés, et de vérifier qu'une construction est possible.",
  materiel: "Règle graduée, compas, équerre, cahier de géométrie",
  rev: [["Comment nomme-t-on un triangle à trois côtés égaux ?", "Équilatéral."],
        ["Quel instrument reporte une longueur ?", "Le compas."],
        ["Quel est le périmètre d'un triangle de côtés 3, 4 et 5 cm ?", "12 cm."]],
  mise: { q: "Avec trois baguettes de 2 cm, 3 cm et 6 cm, peut-on former un triangle ?", ra: "Non, les deux petites ne se rejoignent pas." },
  obs: "Observez la construction au tableau : l'enseignant trace [AB] de 5 cm, ouvre le compas de 4 cm et pique en A, puis l'ouvre de 3 cm et pique en B. Les deux arcs se croisent en C.",
  ana: [
    ["Par quel côté commence-t-on ?", "Par le plus long."],
    ["Quel instrument reporte les deux autres longueurs ?", "Le compas."],
    ["Où pique-t-on la pointe pour le côté de 4 cm ?", "En A."],
    ["Que représente le point d'intersection des arcs ?", "Le troisième sommet."],
    ["Y a-t-il un ou deux points d'intersection ?", "Deux, situés de part et d'autre de [AB]."],
    ["Pourquoi 2 cm, 3 cm et 6 cm échouent-ils ?", "Parce que les arcs ne se croisent pas."],
    ["Quelle condition faut-il vérifier ?", "Le plus grand côté doit être inférieur à la somme des deux autres."],
  ],
  syn: "Donc, pour construire un triangle dont on connaît les trois côtés, on trace d'abord le plus long, puis on reporte au compas les deux autres longueurs depuis chaque extrémité. Le point d'intersection des arcs est le troisième sommet. La construction n'est possible que si le plus grand côté est inférieur à la somme des deux autres.",
  attention: "Ne modifiez jamais l'écartement du compas entre le moment où vous le réglez sur la règle et celui où vous tracez l'arc : la moindre variation fausse la construction.",
  astuce: "Laissez les arcs de construction visibles sur votre figure : ils prouvent la méthode employée et sont attendus dans une évaluation.",
  app: [
    { c: "Construis un triangle ABC tel que AB = 5 cm, AC = 4 cm et BC = 3 cm.\n1. Quel côté traces-tu en premier ?\n2. Où piques-tu pour reporter 4 cm ?\n3. Où piques-tu pour reporter 3 cm ?\n4. Quel est son périmètre ?",
      r: "1. [[AB]], le plus long\n2. En [[A]]\n3. En [[B]]\n4. [[12 cm]]" },
    { c: "Ces triangles sont-ils constructibles ?\n1. 4 cm, 5 cm, 6 cm\n2. 2 cm, 3 cm, 6 cm\n3. 7 cm, 7 cm, 7 cm\n4. 1 cm, 2 cm, 5 cm",
      r: "1. [[Oui]], car 4 + 5 = 9 > 6\n2. [[Non]], car 2 + 3 = 5 < 6\n3. [[Oui]], triangle équilatéral\n4. [[Non]], car 1 + 2 = 3 < 5" },
  ],
  evalx: [
    { c: "Décris en quatre étapes la construction d'un triangle équilatéral de 6 cm de côté.\n1. Première étape ?\n2. Deuxième ?\n3. Troisième ?\n4. Quatrième ?",
      r: "1. Tracer [[[AB] = 6 cm]]\n2. Ouvrir le compas de [[6 cm]] et piquer en A\n3. Sans changer l'écartement, piquer en [[B]]\n4. Nommer [[C]] l'intersection des arcs et tracer [AC] et [BC]" },
    { c: "Un triangle isocèle a une base de 4 cm et deux côtés de 6 cm.\n1. Est-il constructible ?\n2. Justifie.\n3. Quel est son périmètre ?\n4. Comment coder l'égalité des côtés ?",
      r: "1. [[Oui]]\n2. Car 4 + 6 = 10, [[supérieur à 6]]\n3. [[16 cm]]\n4. Par un [[même trait]] sur les deux côtés égaux" },
  ],
  lecon: [
    ["1. La méthode", "Pour construire un triangle dont les trois côtés sont donnés :\n— on trace le côté le plus {{long}}, par exemple [AB] ;\n— on ouvre le {{compas}} de la deuxième longueur et l'on pique en A pour tracer un arc ;\n— on ouvre le compas de la troisième longueur et l'on pique en B ;\n— le point d'{{intersection}} des deux arcs est le troisième sommet C."],
    ["2. La condition de construction", "Un triangle n'existe que si le plus grand côté est {{inférieur}} à la somme des deux autres.\nAvec 4 cm, 5 cm et 6 cm : 4 + 5 = 9, supérieur à 6, le triangle existe.\nAvec 2 cm, 3 cm et 6 cm : 2 + 3 = 5, inférieur à 6, les arcs ne se croisent jamais."],
    ["3. Les cas particuliers", "Pour un triangle {{équilatéral}}, on garde le même écartement de compas pour les deux arcs.\nPour un triangle {{isocèle}}, on utilise deux écartements : celui de la base, puis celui, identique, des deux côtés égaux."],
    ["4. Soigner la figure", "Les {{arcs de construction}} se laissent apparents : ils montrent la démarche suivie.\nOn nomme ensuite chaque sommet par une lettre majuscule et l'on {{code}} les côtés de même longueur par un même symbole."],
  ],
  exos: [
    { pts: 4, c: "Construis un triangle de côtés 6 cm, 5 cm et 4 cm, puis calcule son périmètre.",
      r: "On trace [AB] = 6 cm, puis des arcs de 5 cm depuis A et de 4 cm depuis B. Périmètre : [[15 cm]]." },
    { pts: 4, c: "Un triangle a-t-il pu être construit avec des côtés de 3 cm, 3 cm et 7 cm ? Justifie.",
      r: "[[Non]] : 3 + 3 = 6, [[inférieur à 7]]." },
    { pts: 4, c: "Décris la construction d'un triangle équilatéral de 5 cm de côté.",
      r: "Tracer [AB] = 5 cm, ouvrir le compas de [[5 cm]], piquer en A puis en B [[sans changer l'écartement]], et joindre le point d'intersection C à A et à B." },
    { pts: 4, c: "Un triangle isocèle a un périmètre de 20 cm et une base de 6 cm. Combien mesurent ses côtés égaux ?",
      r: "20 − 6 = 14, puis 14 ÷ 2 = [[7 cm]] chacun." },
    { pts: 4, c: "Vrai ou faux ? 1. On commence par le plus petit côté. 2. Les arcs se croisent en deux points. 3. 5, 5 et 12 cm forment un triangle. 4. Le compas sert à reporter les longueurs.",
      r: "1. [[Faux]] : on commence par le plus long. 2. [[Vrai]]. 3. [[Faux]] : 5 + 5 = 10 < 12. 4. [[Vrai]]." },
  ],
},
{
  ch: "Cercles, triangles et quadrilatères",
  titre: "Les quadrilatères usuels",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître et de décrire un carré, un rectangle, un losange et un parallélogramme.",
  materiel: "Règle graduée, équerre, quadrilatères découpés, ardoises",
  rev: [["Combien de côtés a un triangle ?", "Trois."],
        ["Que signifie le symbole ⊥ ?", "Perpendiculaire."],
        ["Que signifie le symbole // ?", "Parallèle."]],
  mise: { q: "Une porte, un carreau de sol, un cerf-volant : quel point commun ont ces formes ?", ra: "Elles ont toutes quatre côtés." },
  obs: "Observez au tableau quatre figures à quatre côtés : un carré, un rectangle, un losange et un parallélogramme, avec les codages d'angles droits et de côtés égaux.",
  ana: [
    ["Combien de côtés ont ces figures ?", "Quatre."],
    ["Comment les nomme-t-on ?", "Des quadrilatères."],
    ["Que possède le parallélogramme ?", "Deux paires de côtés parallèles."],
    ["Qu'ajoute le rectangle ?", "Quatre angles droits."],
    ["Qu'ajoute le losange ?", "Quatre côtés égaux."],
    ["Et le carré ?", "Quatre angles droits et quatre côtés égaux."],
    ["Un carré est-il un rectangle ?", "Oui, un rectangle particulier."],
    ["Combien de diagonales a un quadrilatère ?", "Deux."],
  ],
  syn: "Donc, un quadrilatère est un polygone à quatre côtés. Le parallélogramme a ses côtés opposés parallèles deux à deux ; le rectangle y ajoute quatre angles droits ; le losange y ajoute quatre côtés égaux ; le carré possède à la fois les quatre angles droits et les quatre côtés égaux.",
  attention: "Le carré n'est pas une figure à part : c'est à la fois un rectangle et un losange. Tout ce qui est vrai pour l'un et pour l'autre l'est donc pour le carré.",
  astuce: "Pour identifier un quadrilatère, posez-vous deux questions dans l'ordre : les angles sont-ils droits ? les côtés sont-ils tous égaux ? Les réponses donnent immédiatement le nom.",
  app: [
    { c: "Nomme la figure :\n1. quatre angles droits, côtés égaux deux à deux\n2. quatre côtés égaux et quatre angles droits\n3. quatre côtés égaux sans angle droit\n4. côtés opposés parallèles seulement",
      r: "1. Un [[rectangle]]\n2. Un [[carré]]\n3. Un [[losange]]\n4. Un [[parallélogramme]]" },
    { c: "Calcule le périmètre :\n1. d'un carré de 9,2 cm\n2. d'un rectangle de 7 cm sur 4,5 cm\n3. d'un losange de 6,5 cm de côté\n4. d'un rectangle de 12,5 m sur 7,5 m",
      r: "1. [[36,8 cm]]\n2. [[23 cm]]\n3. [[26 cm]]\n4. [[40 m]]" },
  ],
  evalx: [
    { c: "Vrai ou faux ?\n1. Un carré est un rectangle.\n2. Un rectangle est un carré.\n3. Un carré est un losange.\n4. Un losange a quatre angles droits.",
      r: "1. [[Vrai]]\n2. [[Faux]], sauf si ses côtés sont égaux\n3. [[Vrai]]\n4. [[Faux]], pas nécessairement" },
    { c: "Un rectangle a un périmètre de 34 cm et une longueur de 11 cm.\n1. Que vaut le demi-périmètre ?\n2. Quelle est sa largeur ?\n3. Un losange a un périmètre de 38 cm : quel est son côté ?\n4. Quelle opération as-tu utilisée ?",
      r: "1. [[17 cm]]\n2. [[6 cm]]\n3. [[9,5 cm]]\n4. Une [[division par 4]], car les quatre côtés sont égaux" },
  ],
  lecon: [
    ["1. Le quadrilatère", "Un {{quadrilatère}} est un polygone à quatre côtés et quatre sommets. Ses {{diagonales}} sont les deux segments joignant les sommets opposés."],
    ["2. Le parallélogramme", "Un {{parallélogramme}} est un quadrilatère dont les côtés opposés sont {{parallèles}} deux à deux. Ces côtés opposés sont alors également de même longueur."],
    ["3. Rectangle, losange, carré", "Le {{rectangle}} est un parallélogramme ayant quatre {{angles droits}}. Son périmètre vaut 2 × (Longueur + largeur).\nLe {{losange}} est un parallélogramme ayant quatre {{côtés égaux}}. Son périmètre vaut 4 × côté.\nLe {{carré}} possède les deux propriétés : quatre angles droits et quatre côtés égaux. C'est donc à la fois un rectangle et un losange."],
    ["4. Reconnaître et coder", "Sur une figure, un petit {{carré}} signale un angle droit, et un même {{trait}} signale des côtés de même longueur. Les flèches identiques indiquent des côtés parallèles.\nCes codages permettent de nommer la figure sans avoir à la mesurer."],
  ],
  exos: [
    { pts: 4, c: "Calcule le périmètre d'un carré de 7,5 cm et d'un losange de 8 cm de côté.",
      r: "Carré : 4 × 7,5 = [[30 cm]]. Losange : 4 × 8 = [[32 cm]]." },
    { pts: 4, c: "Un rectangle mesure 14 cm sur 9 cm. Quel est son périmètre ?",
      r: "2 × (14 + 9) = [[46 cm]]." },
    { pts: 4, c: "Explique pourquoi un carré est un losange particulier.",
      r: "Parce qu'il a [[quatre côtés égaux]], ce qui est la définition du losange ; il possède en plus [[quatre angles droits]]." },
    { pts: 4, c: "Un losange a un périmètre de 26 cm. Quelle est la longueur d'un côté ?",
      r: "26 ÷ 4 = [[6,5 cm]]." },
    { pts: 4, c: "Un rectangle a un périmètre de 40 m et une largeur de 8 m. Calcule sa longueur.",
      r: "40 ÷ 2 = 20, puis 20 − 8 = [[12 m]]." },
  ],
},
{
  ch: "Cercles, triangles et quadrilatères",
  titre: "Construire un rectangle et un carré",
  objectif: "À la fin de la séance, l'élève est capable de construire un rectangle et un carré à la règle et à l'équerre.",
  materiel: "Règle graduée, équerre, compas, cahier de géométrie",
  rev: [["Combien d'angles droits a un rectangle ?", "Quatre."],
        ["Quel est le périmètre d'un carré de 5 cm ?", "20 cm."],
        ["Quel instrument trace un angle droit ?", "L'équerre."]],
  mise: { q: "Un maçon veut tracer les fondations rectangulaires d'une maison. Comment s'assure-t-il que les angles sont droits ?", ra: "En utilisant une équerre." },
  obs: "Observez la construction au tableau : l'enseignant trace [AB] de 6 cm, puis élève en A et en B deux perpendiculaires à l'équerre, y reporte 4 cm et joint les deux points obtenus.",
  ana: [
    ["Par quoi commence la construction ?", "Par un côté, ici la longueur."],
    ["Quel instrument pour les perpendiculaires ?", "L'équerre."],
    ["Combien de perpendiculaires élève-t-on ?", "Deux, une à chaque extrémité."],
    ["Quelle longueur reporte-t-on dessus ?", "La largeur, soit 4 cm."],
    ["Comment achever la figure ?", "En joignant les deux derniers points."],
    ["Combien d'angles droits a-t-on tracés ?", "Deux ; les deux autres se forment d'eux-mêmes."],
    ["Comment construire un carré par cette méthode ?", "En reportant la même longueur partout."],
  ],
  syn: "Donc, pour construire un rectangle, on trace un premier côté, on élève à ses deux extrémités des perpendiculaires à l'équerre, on y reporte la seconde dimension, puis on joint les deux points obtenus. Le carré se construit de la même façon en reportant partout la même longueur.",
  attention: "L'équerre doit être appliquée bien à plat contre la droite tracée : un léger décalage suffit à produire un angle qui n'est pas droit et une figure fausse.",
  astuce: "Vérifiez votre rectangle en mesurant ses deux diagonales : dans un rectangle correctement tracé, elles ont exactement la même longueur.",
  app: [
    { c: "Construis un rectangle de 6 cm sur 4 cm.\n1. Quel côté traces-tu d'abord ?\n2. Quel instrument ensuite ?\n3. Quelle longueur reportes-tu ?\n4. Quel est le périmètre ?",
      r: "1. La [[longueur]] de 6 cm\n2. L'[[équerre]], pour les perpendiculaires\n3. La [[largeur]] de 4 cm\n4. [[20 cm]]" },
    { c: "Construis un carré de 5,5 cm de côté.\n1. Combien de perpendiculaires élèves-tu ?\n2. Quelle longueur reportes-tu ?\n3. Quel est son périmètre ?\n4. Comment vérifier la figure ?",
      r: "1. [[Deux]]\n2. [[5,5 cm]], la même partout\n3. [[22 cm]]\n4. En vérifiant que les [[diagonales]] sont égales" },
  ],
  evalx: [
    { c: "Complète :\n1. Un rectangle a …… angles droits.\n2. On les trace à l'……\n3. Dans un rectangle, les diagonales sont ……\n4. Un carré est un rectangle dont ……",
      r: "1. [[quatre]]\n2. [[équerre]]\n3. [[égales]]\n4. les [[quatre côtés sont égaux]]" },
    { c: "Un carré et un rectangle ont le même périmètre de 36 cm. Le rectangle mesure 12 cm de long.\n1. Quel est le côté du carré ?\n2. Quel est le demi-périmètre du rectangle ?\n3. Quelle est sa largeur ?\n4. Les deux figures sont-elles identiques ?",
      r: "1. [[9 cm]]\n2. [[18 cm]]\n3. [[6 cm]]\n4. [[Non]] : même périmètre, mais des formes différentes" },
  ],
  lecon: [
    ["1. Construire un rectangle", "On procède en quatre temps :\n— tracer le premier côté, par exemple [AB] = 6 cm ;\n— élever en A une {{perpendiculaire}} à (AB) à l'équerre, et y reporter 4 cm pour obtenir D ;\n— élever de même en B une perpendiculaire, et y reporter 4 cm pour obtenir C ;\n— joindre D et C."],
    ["2. Construire un carré", "La méthode est identique, mais l'on reporte partout la {{même longueur}}. Un carré de 5 cm de côté s'obtient en traçant [AB] = 5 cm puis en reportant 5 cm sur les deux perpendiculaires."],
    ["3. Vérifier la construction", "Dans un rectangle, les deux {{diagonales}} ont la même longueur. Les mesurer constitue un excellent contrôle : si elles diffèrent, un angle n'est pas droit.\nOn vérifie aussi que les côtés opposés sont bien de même longueur."],
    ["4. Coder la figure", "On termine en plaçant un petit {{carré}} à chaque angle droit et un même {{trait}} sur les côtés de même longueur.\nUne figure bien codée se lit sans avoir besoin d'être mesurée."],
  ],
  exos: [
    { pts: 4, c: "Construis un rectangle de 7 cm sur 3 cm et calcule son périmètre.",
      r: "2 × (7 + 3) = [[20 cm]]. Les angles droits sont tracés à l'[[équerre]]." },
    { pts: 4, c: "Décris en trois étapes la construction d'un carré de 4,5 cm de côté.",
      r: "Tracer [AB] = 4,5 cm ; élever deux [[perpendiculaires]] en A et B et y reporter [[4,5 cm]] ; joindre les deux points obtenus." },
    { pts: 4, c: "Comment vérifier qu'un rectangle est correctement construit ?",
      r: "En mesurant ses deux [[diagonales]] : elles doivent être [[égales]]." },
    { pts: 4, c: "Un carré a un périmètre de 36,8 cm. Quelle est la longueur de son côté ?",
      r: "36,8 ÷ 4 = [[9,2 cm]]." },
    { pts: 4, c: "Vrai ou faux ? 1. On trace les angles droits au compas. 2. Les diagonales d'un rectangle sont égales. 3. Un carré a quatre angles droits. 4. On commence par tracer les diagonales.",
      r: "1. [[Faux]] : à l'équerre. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : on commence par un côté." },
  ],
},
{
  ch: "Cercles, triangles et quadrilatères",
  titre: "Problèmes de figures et de périmètres",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème mettant en jeu la reconnaissance d'une figure et le calcul de son périmètre.",
  materiel: "Énoncés au tableau, règle, compas, cahier de recherche",
  rev: [["Quel est le périmètre d'un losange de 5 cm de côté ?", "20 cm."],
        ["Quelle est la circonférence d'un cercle de rayon 10 cm ?", "62,8 cm."],
        ["Quel est le périmètre d'un triangle équilatéral de 4 cm ?", "12 cm."]],
  mise: { q: "Pour border un napperon rond et une nappe carrée, calcule-t-on la même chose ?", ra: "Le tour dans les deux cas, mais avec des formules différentes." },
  obs: "Lisez l'énoncé au tableau : « Une table circulaire de 1,4 m de diamètre et une table carrée de 1,1 m de côté doivent recevoir un ruban tout autour. Le ruban coûte 3 000 ariary le mètre. »",
  ana: [
    ["Quelle formule pour la table ronde ?", "Pi fois le diamètre."],
    ["Quelle longueur de ruban pour cette table ?", "4,396 mètres."],
    ["Quelle formule pour la table carrée ?", "Quatre fois le côté."],
    ["Quelle longueur pour celle-ci ?", "4,4 mètres."],
    ["Laquelle demande le plus de ruban ?", "La table carrée, de très peu."],
    ["Quelle longueur totale faut-il ?", "Environ 8,8 mètres."],
    ["Comment obtenir le coût ?", "En multipliant la longueur par 3 000."],
    ["Pourquoi arrondir au mètre supérieur ?", "Parce que le ruban se vend au mètre entier."],
  ],
  syn: "Donc, résoudre un problème de figures suppose de reconnaître d'abord la forme, de choisir la formule qui lui correspond, de vérifier les unités, puis d'enchaîner les calculs. Le résultat se relit toujours à la lumière du contexte concret.",
  attention: "Une même question peut cacher deux figures différentes. Lisez l'énoncé jusqu'au bout avant de choisir une formule, et traitez chaque figure séparément avant d'additionner.",
  app: [
    { c: "Une table ronde de 1,4 m de diamètre et une table carrée de 1,1 m de côté reçoivent un ruban.\n1. Quelle longueur pour la ronde ?\n2. Quelle longueur pour la carrée ?\n3. Quel total ?\n4. Quel coût à 3 000 ariary le mètre, en arrondissant au mètre supérieur ?",
      r: "1. 3,14 × 1,4 = [[4,396 m]]\n2. 4 × 1,1 = [[4,4 m]]\n3. [[8,796 m]]\n4. On achète [[9 m]], soit [[27 000 ariary]]" },
    { c: "Un jardin est formé d'un carré de 12 m de côté accolé à un triangle équilatéral de 12 m de côté.\n1. Quel est le périmètre du carré seul ?\n2. Combien de côtés du triangle sont extérieurs ?\n3. Quel est le périmètre de la figure entière ?\n4. Explique ta démarche.",
      r: "1. [[48 m]]\n2. [[Deux]], le troisième étant collé au carré\n3. [[60 m]]\n4. On ajoute les [[trois côtés libres du carré]] et les [[deux côtés libres du triangle]], soit 5 × 12" },
  ],
  evalx: [
    { c: "Un terrain a la forme d'un losange de 45 m de côté.\n1. Quel est son périmètre ?\n2. On veut deux rangées de fil : quelle longueur ?\n3. Le fil coûte 900 ariary le mètre : quel coût ?\n4. Rédige la phrase réponse.",
      r: "1. [[180 m]]\n2. [[360 m]]\n3. [[324 000 ariary]]\n4. « [[La clôture coûtera 324 000 ariary.]] »" },
    { c: "Un bassin circulaire de 5 m de rayon est entouré d'une allée dont le bord extérieur est un cercle de 6 m de rayon.\n1. Quelle est la circonférence du bassin ?\n2. Celle du bord extérieur ?\n3. Quelle différence entre les deux ?\n4. Que représente cette différence ?",
      r: "1. 2 × 3,14 × 5 = [[31,4 m]]\n2. 2 × 3,14 × 6 = [[37,68 m]]\n3. [[6,28 m]]\n4. La [[longueur supplémentaire]] du contour extérieur par rapport au bassin" },
  ],
  lecon: [
    ["1. Reconnaître la figure", "La première étape consiste toujours à identifier la {{forme}} décrite : cercle, triangle, carré, rectangle ou losange. Les mots de l'énoncé y suffisent le plus souvent : « rond », « à quatre côtés égaux », « deux côtés égaux »."],
    ["2. Choisir la formule", "À chaque figure sa formule :\ntriangle, somme des trois côtés ; carré, 4 × côté ; losange, 4 × côté ; rectangle, 2 × (Longueur + largeur) ; cercle, 2 × π × rayon ou π × diamètre."],
    ["3. Les figures composées", "Lorsqu'une figure est formée de plusieurs autres, seul compte le {{contour extérieur}}. Les côtés communs, situés à l'intérieur, ne font pas partie du périmètre.\nPour un carré de 12 m accolé à un triangle équilatéral de même côté, le périmètre vaut 5 × 12 = 60 m et non 48 + 36."],
    ["4. Interpréter le résultat", "Un ruban vendu au mètre entier oblige à {{arrondir au supérieur}} : pour 8,796 m, il faut acheter 9 m.\nOn termine par une {{phrase réponse}} qui reprend la question posée et donne l'unité."],
  ],
  exos: [
    { pts: 4, c: "Une nappe carrée de 1,6 m de côté doit être bordée d'un galon. Quelle longueur faut-il ?",
      r: "4 × 1,6 = [[6,4 m]] de galon." },
    { pts: 4, c: "Un napperon circulaire a 40 cm de diamètre. Quelle longueur de dentelle faut-il pour en faire le tour ?",
      r: "3,14 × 40 = [[125,6 cm]], soit environ [[1,26 m]]." },
    { pts: 4, c: "Un terrain en forme de losange a 38 m de périmètre. Combien mesure chacun de ses côtés ?",
      r: "38 ÷ 4 = [[9,5 m]]." },
    { pts: 4, c: "Un enclos rectangulaire de 25 m sur 18 m est entouré de trois rangées de fil à 800 ariary le mètre. Quel est le coût ?",
      r: "Périmètre : 2 × (25 + 18) = 86 m. Fil : 3 × 86 = 258 m. Coût : 258 × 800 = [[206 400 ariary]]." },
    { pts: 4, c: "Une figure est formée d'un carré de 10 m de côté accolé à un triangle équilatéral de 10 m de côté. Quel est son périmètre ?",
      r: "Cinq côtés libres de 10 m : 5 × 10 = [[50 m]]. Le côté commun n'est [[pas compté]]." },
  ],
},
];
