// Période I — 20 séances. Contenu entièrement rédigé pour la Collection J-Learn.
// Contexte malgache, séparateur décimal = virgule, aucune date calendaire.
// Champs : rev, mise, obs, ana[[Q,RA]], syn, app[], evalx[], lecon[], exos[]

const DOC = "Programme officiel de Mathématiques, classe de 6e — RAPS 6e";

module.exports = [
// ─────────────────────────────────────────── Ch. 1 — Les nombres entiers naturels
{
  ch: "Les nombres entiers naturels",
  titre: "Lire et écrire les nombres entiers naturels",
  objectif: "À la fin de la séance, l'élève est capable de lire et d'écrire correctement un nombre entier naturel jusqu'à la classe des millions, en chiffres et en lettres.",
  materiel: "Tableau de numération tracé au tableau, ardoises, étiquettes-chiffres",
  rev: [["Combien de chiffres utilise-t-on pour écrire tous les nombres ?", "Dix chiffres : 0, 1, 2, 3, 4, 5, 6, 7, 8 et 9."],
        ["Écris le nombre trois cent quarante-deux.", "342."],
        ["Quel est le chiffre des dizaines dans 87 ?", "Le chiffre 8."]],
  mise: { q: "Le recensement annonce que la population d'Antananarivo dépasse un million d'habitants. Comment écrit-on ce nombre en chiffres ?", ra: "1 000 000." },
  obs: "Regardez bien le tableau de numération affiché : il comporte les classes des millions, des mille et des unités, chacune divisée en centaines, dizaines et unités. Le nombre 3 254 108 y est placé, un chiffre par colonne.",
  ana: [
    ["Combien de classes voyez-vous dans ce tableau ?", "Trois classes : les millions, les mille et les unités simples."],
    ["Combien de colonnes contient chaque classe ?", "Trois colonnes : centaines, dizaines et unités."],
    ["Dans 3 254 108, quel chiffre occupe la colonne des millions ?", "Le chiffre 3."],
    ["Que représente le chiffre 5 dans ce nombre ?", "Il représente 5 dizaines de mille, c'est-à-dire 50 000."],
    ["Pourquoi laisse-t-on un espace entre les groupes de trois chiffres ?", "Pour séparer les classes et rendre le nombre plus facile à lire."],
    ["Comment lit-on ce nombre à voix haute ?", "Trois millions deux cent cinquante-quatre mille cent huit."],
  ],
  syn: "Donc, un nombre entier naturel s'écrit avec les dix chiffres, groupés par tranches de trois à partir de la droite. Chaque tranche forme une classe : unités, mille, millions. La position d'un chiffre indique sa valeur.",
  app: [
    { c: "Écris en chiffres les nombres suivants :\n1. Quatre-vingt-douze mille trois cents\n2. Sept millions cinq cent mille\n3. Deux cent six mille quatorze\n4. Un million un",
      r: "1. [[92 300]]\n2. [[7 500 000]]\n3. [[206 014]]\n4. [[1 000 001]]" },
    { c: "Dans le nombre 8 407 165, indique la valeur du chiffre demandé :\n1. le chiffre 8\n2. le chiffre 4\n3. le chiffre 7\n4. le chiffre 6",
      r: "1. [[8 millions]], soit 8 000 000\n2. [[4 centaines de mille]], soit 400 000\n3. [[7 unités de mille]], soit 7 000\n4. [[6 dizaines]], soit 60" },
  ],
  evalx: [
    { c: "Écris en lettres :\n1. 5 060\n2. 340 000\n3. 1 200 500\n4. 90 009",
      r: "1. [[Cinq mille soixante]]\n2. [[Trois cent quarante mille]]\n3. [[Un million deux cent mille cinq cents]]\n4. [[Quatre-vingt-dix mille neuf]]" },
    { c: "Recopie et complète par le mot qui convient (classe, chiffre, position) :\n1. Un nombre s'écrit à l'aide de dix ……\n2. La valeur d'un chiffre dépend de sa ……\n3. Les millions forment une ……\n4. On sépare les …… par un espace.",
      r: "1. [[chiffres]]\n2. [[position]]\n3. [[classe]]\n4. [[classes]]" },
  ],
  lecon: [
    ["1. Les dix chiffres", "Tout nombre entier naturel s'écrit à l'aide des dix {{chiffres}} : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9. Il ne faut pas confondre un {{chiffre}}, qui est un signe d'écriture, et un {{nombre}}, qui exprime une quantité. Ainsi 47 est un nombre écrit avec deux chiffres."],
    ["2. Le tableau de numération", "Les chiffres se rangent par {{classes}} de trois colonnes : la classe des unités, celle des mille, celle des millions. Dans chaque classe on trouve les centaines (C), les dizaines (D) et les unités (U).\nPour le nombre 3 254 108 : 3 est le chiffre des millions, 2 celui des centaines de mille, 5 celui des dizaines de mille, 4 celui des unités de mille, 1 celui des centaines, 0 celui des dizaines et 8 celui des unités."],
    ["3. La valeur de position", "La {{position}} d'un chiffre indique la quantité qu'il représente. Dans 3 254 108, le chiffre 5 ne vaut pas 5 mais 50 000, car il occupe la colonne des dizaines de mille. C'est ce que l'on appelle la {{valeur de position}}."],
    ["4. Lire et écrire", "On lit un nombre classe par classe, en partant de la gauche. On écrit un espace entre les classes, jamais un point ni une virgule : on écrit 1 250 000, et non 1.250.000.\nExemple : la commune de Toamasina compte 326 289 habitants ; on lit « trois cent vingt-six mille deux cent quatre-vingt-neuf »."],
  ],
  exos: [
    { pts: 4, c: "Écris en chiffres : quatre cent mille sept ; douze millions ; soixante-quinze mille quatre-vingts ; neuf cent neuf.",
      r: "[[400 007]] ; [[12 000 000]] ; [[75 080]] ; [[909]]." },
    { pts: 4, c: "Dans 6 703 480, donne la valeur du chiffre 7, puis celle du chiffre 3.",
      r: "Le chiffre 7 vaut [[700 000]] car il occupe la colonne des centaines de mille. Le chiffre 3 vaut [[3 000]] car il occupe celle des unités de mille." },
    { pts: 4, c: "Écris en lettres 2 040 600.",
      r: "[[Deux millions quarante mille six cents]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 45 est un chiffre. 2. Dans 508, le 0 ne sert à rien. 3. On sépare les classes par un espace. 4. Le chiffre des unités de 3 271 est 1.",
      r: "1. [[Faux]] : 45 est un nombre écrit avec deux chiffres. 2. [[Faux]] : le 0 marque l'absence de dizaines et maintient le 5 dans la colonne des centaines. 3. [[Vrai]]. 4. [[Vrai]]." },
    { pts: 4, c: "Range dans l'ordre croissant : 90 100 ; 9 100 ; 901 000 ; 91 000.",
      r: "[[9 100 < 90 100 < 91 000 < 901 000]]." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Comparer et ranger les nombres entiers",
  objectif: "À la fin de la séance, l'élève est capable de comparer deux entiers naturels et de ranger une liste de nombres dans l'ordre croissant ou décroissant.",
  materiel: "Étiquettes portant des nombres, ardoises, tableau de numération",
  rev: [["Quelle est la valeur du chiffre 4 dans 34 800 ?", "4 000, car il occupe la colonne des unités de mille."],
        ["Écris en chiffres : deux cent mille dix.", "200 010."],
        ["Combien de classes compte 5 400 000 ?", "Trois : millions, mille et unités."]],
  mise: { q: "Deux communes déclarent 12 480 et 12 840 habitants. Laquelle est la plus peuplée ?", ra: "Celle de 12 840 habitants." },
  obs: "Observez ces deux nombres écrits l'un sous l'autre dans le tableau de numération, chiffre sous chiffre : 12 480 et 12 840.",
  ana: [
    ["Ces deux nombres ont-ils le même nombre de chiffres ?", "Oui, cinq chiffres chacun."],
    ["Par où commence-t-on alors la comparaison ?", "Par la gauche, c'est-à-dire par le chiffre le plus fort."],
    ["Les chiffres des dizaines de mille sont-ils différents ?", "Non, c'est 1 dans les deux nombres."],
    ["Et ceux des unités de mille ?", "Non plus, c'est 2 dans les deux cas."],
    ["Quel est le premier rang où les chiffres diffèrent ?", "Le rang des centaines : 4 pour le premier, 8 pour le second."],
    ["Quelle conclusion tire-t-on ?", "Comme 8 est plus grand que 4, on écrit 12 840 > 12 480."],
    ["Et si deux nombres n'ont pas le même nombre de chiffres ?", "Le plus grand est celui qui a le plus de chiffres."],
  ],
  syn: "Donc, pour comparer deux entiers, on compte d'abord les chiffres : celui qui en a le plus est le plus grand. À nombre de chiffres égal, on compare rang par rang en partant de la gauche, jusqu'au premier rang où les chiffres diffèrent.",
  app: [
    { c: "Complète par < ou > :\n1. 7 205 … 7 502\n2. 48 000 … 9 999\n3. 130 400 … 130 040\n4. 999 … 1 000",
      r: "1. 7 205 [[<]] 7 502\n2. 48 000 [[>]] 9 999\n3. 130 400 [[>]] 130 040\n4. 999 [[<]] 1 000" },
    { c: "Range dans l'ordre croissant : 5 060 ; 5 600 ; 5 006 ; 5 660.",
      r: "[[5 006 < 5 060 < 5 600 < 5 660]]" },
  ],
  evalx: [
    { c: "Range dans l'ordre décroissant : 87 090 ; 87 900 ; 8 790 ; 87 009.",
      r: "[[87 900 > 87 090 > 87 009 > 8 790]]" },
    { c: "Encadre chaque nombre entre deux centaines consécutives :\n1. 347\n2. 1 208\n3. 5 099\n4. 660",
      r: "1. [[300 < 347 < 400]]\n2. [[1 200 < 1 208 < 1 300]]\n3. [[5 000 < 5 099 < 5 100]]\n4. [[600 < 660 < 700]]" },
  ],
  lecon: [
    ["1. Comparer deux nombres", "{{Comparer}} deux nombres, c'est dire s'ils sont égaux, ou lequel est le plus grand. On utilise les signes {{<}} (« est inférieur à »), {{>}} (« est supérieur à ») et {{=}} (« est égal à »).\nLa pointe du signe est toujours tournée vers le plus petit nombre : 7 < 12 se lit « 7 est inférieur à 12 »."],
    ["2. La méthode", "a) On compare le nombre de chiffres : celui qui en a le plus est le plus grand. Ainsi 1 000 > 999.\nb) Si les deux nombres ont autant de chiffres, on compare rang par rang en partant de la gauche. Au premier rang où les chiffres diffèrent, le plus grand chiffre donne le plus grand nombre.\nExemple : 12 840 et 12 480 ont les mêmes chiffres de gauche jusqu'aux centaines, où 8 > 4 ; donc 12 840 > 12 480."],
    ["3. Ranger une liste", "{{Ranger}} des nombres dans l'ordre {{croissant}}, c'est les écrire du plus petit au plus grand. Dans l'ordre {{décroissant}}, c'est l'inverse.\nExemple croissant : 405 < 450 < 504 < 540."],
    ["4. Encadrer un nombre", "{{Encadrer}} un nombre, c'est trouver un nombre plus petit et un nombre plus grand que lui. Pour encadrer 3 472 entre deux milliers : 3 000 < 3 472 < 4 000."],
  ],
  exos: [
    { pts: 4, c: "Complète par < ou > : 6 090 … 6 900 ; 24 000 … 8 999 ; 501 … 510 ; 100 000 … 99 999.",
      r: "6 090 [[<]] 6 900 ; 24 000 [[>]] 8 999 ; 501 [[<]] 510 ; 100 000 [[>]] 99 999." },
    { pts: 4, c: "Range dans l'ordre croissant : 4 007 ; 4 700 ; 4 070 ; 4 077.",
      r: "[[4 007 < 4 070 < 4 077 < 4 700]]." },
    { pts: 4, c: "Range dans l'ordre décroissant : 32 100 ; 3 210 ; 321 000 ; 32 010.",
      r: "[[321 000 > 32 100 > 32 010 > 3 210]]." },
    { pts: 4, c: "Encadre 7 845 entre deux milliers consécutifs, puis entre deux centaines consécutives.",
      r: "[[7 000 < 7 845 < 8 000]] et [[7 800 < 7 845 < 7 900]]." },
    { pts: 4, c: "Écris le plus grand et le plus petit nombre de quatre chiffres différents que l'on peut former avec 3, 0, 7 et 5.",
      r: "Le plus grand est [[7 530]] ; le plus petit est [[3 057]] (un nombre ne peut pas commencer par 0)." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "La demi-droite graduée et l'abscisse",
  objectif: "À la fin de la séance, l'élève est capable de placer un entier sur une demi-droite graduée et de lire l'abscisse d'un point.",
  materiel: "Règle graduée, double décimètre, demi-droite tracée au tableau",
  rev: [["Complète : 4 500 … 4 050.", "4 500 > 4 050."],
        ["Range dans l'ordre croissant : 12 ; 21 ; 2.", "2 < 12 < 21."],
        ["Quel est le plus petit entier naturel ?", "Zéro."]],
  mise: { q: "Sur la règle graduée de votre trousse, que représentent les petits traits régulièrement espacés ?", ra: "Les graduations, qui servent à mesurer." },
  obs: "Observez la droite tracée au tableau : elle part d'un point marqué O, porte des traits régulièrement espacés, et les points A et B y sont placés. Sous O est écrit 0, sous le trait suivant 1.",
  ana: [
    ["Quel nombre est écrit sous le point O ?", "Le nombre 0 ; on l'appelle l'origine."],
    ["Quelle distance sépare deux traits voisins ?", "Toujours la même : c'est l'unité de longueur."],
    ["Combien d'unités séparent O du point A ?", "Trois unités."],
    ["Quel nombre associe-t-on alors au point A ?", "Le nombre 3."],
    ["Comment appelle-t-on ce nombre ?", "L'abscisse du point A ; on écrit A(3)."],
    ["Deux points différents peuvent-ils avoir la même abscisse ?", "Non, chaque point de la droite a une seule abscisse."],
  ],
  syn: "Donc, graduer une demi-droite, c'est choisir une origine associée à 0 et une unité que l'on reporte régulièrement. Le nombre associé à un point s'appelle son abscisse et s'écrit entre parenthèses après le nom du point.",
  app: [
    { c: "Trace une demi-droite graduée d'origine O avec 1 cm pour unité, puis place les points A(2), B(5) et C(7).",
      r: "Après avoir reporté sept fois 1 cm : [[A est au 2e trait, B au 5e, C au 7e]]. Le point C est le plus éloigné de l'origine." },
    { c: "Sur une demi-droite graduée, un point M est situé 9 unités après l'origine. 1. Quelle est son abscisse ? 2. Écris-la correctement. 3. Quel point est plus proche de O : M ou N(4) ? 4. Combien d'unités séparent M de N ?",
      r: "1. [[9]]\n2. [[M(9)]]\n3. [[N(4)]]\n4. [[5 unités]], car 9 − 4 = 5." },
  ],
  evalx: [
    { c: "Lis les abscisses : sur une demi-droite d'unité 1, le point P est au 6e trait, Q au 11e, R au 0e, S au 15e.",
      r: "[[P(6)]], [[Q(11)]], [[R(0)]] qui est l'origine, [[S(15)]]." },
    { c: "Complète : 1. L'origine a pour abscisse …… 2. Le nombre associé à un point s'appelle son …… 3. Les graduations sont …… espacées. 4. Le point d'abscisse 8 est plus …… de l'origine que celui d'abscisse 3.",
      r: "1. [[0]]\n2. [[abscisse]]\n3. [[régulièrement]]\n4. [[éloigné]]" },
  ],
  lecon: [
    ["1. Graduer une demi-droite", "{{Graduer}} une demi-droite, c'est choisir sur elle un point appelé {{origine}}, auquel on associe le nombre 0, puis une {{unité}} de longueur que l'on reporte régulièrement à partir de cette origine."],
    ["2. L'abscisse d'un point", "À chaque graduation correspond un nombre entier. Le nombre associé à un point s'appelle son {{abscisse}}. On l'écrit entre parenthèses juste après le nom du point : A(3) se lit « A a pour abscisse 3 ».\nL'origine O a pour abscisse 0."],
    ["3. Lire et placer", "Pour lire l'abscisse d'un point, on compte le nombre d'unités qui le séparent de l'origine. Pour placer un point d'abscisse donnée, on reporte ce nombre d'unités à partir de l'origine.\nPlus l'abscisse est grande, plus le point est éloigné de l'origine : c'est pourquoi la demi-droite graduée permet aussi de comparer les nombres."],
    ["4. Une lecture utile", "La demi-droite graduée se retrouve partout : sur la règle de la trousse, sur le mètre-ruban du menuisier, sur la graduation d'un thermomètre. Dans chaque cas, l'origine et l'unité sont fixées d'avance."],
  ],
  exos: [
    { pts: 4, c: "Trace une demi-droite graduée d'unité 1 cm et place A(4), B(7) et C(10).",
      r: "On reporte 1 cm dix fois depuis O : [[A au 4e trait, B au 7e, C au 10e]]." },
    { pts: 4, c: "Un point D est placé 12 unités après l'origine. Écris son abscisse et compare-la à celle de E(12).",
      r: "[[D(12)]] ; D et E ont [[la même abscisse]], ils sont donc confondus." },
    { pts: 4, c: "Combien d'unités séparent les points d'abscisses 15 et 6 ?",
      r: "[[9 unités]], car 15 − 6 = 9." },
    { pts: 4, c: "Vrai ou faux ? 1. L'origine a pour abscisse 1. 2. Les graduations peuvent être inégales. 3. Un point d'abscisse 0 est l'origine. 4. L'abscisse s'écrit entre parenthèses.",
      r: "1. [[Faux]] : elle a pour abscisse 0. 2. [[Faux]] : elles sont régulièrement espacées. 3. [[Vrai]]. 4. [[Vrai]]." },
    { pts: 4, c: "Sur une demi-droite d'unité 2 cm, à quelle distance de l'origine se trouve le point d'abscisse 5 ?",
      r: "À [[10 cm]] de l'origine, car 5 × 2 cm = 10 cm." },
  ],
},

// ─────────────────── Ch. 1 (suite) — arrondi, multiples, problèmes
{
  ch: "Les nombres entiers naturels",
  titre: "Valeur approchée et arrondi d'un entier",
  objectif: "À la fin de la séance, l'élève est capable de donner l'arrondi d'un entier à la dizaine, à la centaine ou au millier le plus proche.",
  materiel: "Demi-droite graduée au tableau, ardoises, étiquettes-nombres",
  rev: [["Quelle est l'abscisse de l'origine ?", "Zéro."],
        ["Range dans l'ordre croissant : 806 ; 860 ; 68.", "68 < 806 < 860."],
        ["Encadre 512 entre deux centaines.", "500 < 512 < 600."]],
  mise: { q: "Un commerçant annonce « environ 3 500 ariary » pour un article vendu 3 472 ariary. Pourquoi ne donne-t-il pas le prix exact ?", ra: "Pour donner un ordre d'idée, plus simple à retenir." },
  obs: "Observez la demi-droite graduée de 3 400 à 3 500, de 10 en 10. Le nombre 3 472 y est repéré par une croix, entre 3 470 et 3 480.",
  ana: [
    ["Entre quelles dizaines se trouve 3 472 ?", "Entre 3 470 et 3 480."],
    ["De laquelle est-il le plus proche ?", "De 3 470, car il n'en est éloigné que de 2 unités."],
    ["Quel est alors son arrondi à la dizaine ?", "3 470."],
    ["Entre quelles centaines se trouve-t-il ?", "Entre 3 400 et 3 500."],
    ["De laquelle est-il le plus proche ?", "De 3 500, car il en est éloigné de 28, contre 72 de l'autre côté."],
    ["Quel chiffre a-t-on regardé pour décider ?", "Le chiffre des dizaines, 7, qui est supérieur ou égal à 5."],
    ["Que fait-on quand ce chiffre est 5 ?", "On arrondit au nombre supérieur."],
  ],
  syn: "Donc, pour arrondir un entier à un rang donné, on regarde le chiffre situé immédiatement à droite de ce rang. S'il vaut 0, 1, 2, 3 ou 4, on garde le nombre inférieur ; s'il vaut 5, 6, 7, 8 ou 9, on prend le nombre supérieur. Les chiffres à droite du rang deviennent des zéros.",
  attention: "L'erreur la plus fréquente est de regarder tous les chiffres de droite au lieu du seul chiffre qui suit le rang choisi. Pour arrondir 3 472 à la centaine, on ne regarde que le 7 des dizaines, pas le 2 des unités.",
  astuce: "« 5 fait monter » : dès que le chiffre observé atteint 5, on monte à la valeur supérieure ; en dessous, on reste en bas.",
  app: [
    { c: "Arrondis à la centaine la plus proche :\n1. 3 472\n2. 8 650\n3. 749\n4. 2 038",
      r: "1. [[3 500]] car le chiffre des dizaines est 7\n2. [[8 700]] car le chiffre des dizaines est 5\n3. [[700]] car le chiffre des dizaines est 4\n4. [[2 000]] car le chiffre des dizaines est 3" },
    { c: "Arrondis au millier le plus proche :\n1. 12 489\n2. 45 678\n3. 7 500\n4. 9 210",
      r: "1. [[12 000]]\n2. [[46 000]]\n3. [[8 000]] : le chiffre des centaines est 5, on monte\n4. [[9 000]]" },
  ],
  evalx: [
    { c: "Complète le tableau pour 6 384 :\n1. arrondi à la dizaine\n2. arrondi à la centaine\n3. arrondi au millier\n4. Quel chiffre a-t-on observé pour la question 2 ?",
      r: "1. [[6 380]]\n2. [[6 400]]\n3. [[6 000]]\n4. [[Le chiffre des dizaines, 8]]" },
    { c: "Vrai ou faux ?\n1. L'arrondi de 450 à la centaine est 400.\n2. L'arrondi de 2 999 au millier est 3 000.\n3. Arrondir change toujours le nombre.\n4. Pour arrondir au millier, on observe le chiffre des centaines.",
      r: "1. [[Faux]] : le chiffre des dizaines est 5, donc on monte à 500.\n2. [[Vrai]].\n3. [[Faux]] : l'arrondi de 700 à la centaine est 700 lui-même.\n4. [[Vrai]]." },
  ],
  lecon: [
    ["1. Pourquoi arrondir", "Dans la vie courante, on n'a pas toujours besoin du nombre exact. On dit « le stade contient environ 20 000 places » plutôt que 19 847. Donner une {{valeur approchée}}, c'est remplacer un nombre par un autre, plus simple, qui en est très proche."],
    ["2. La règle de l'arrondi", "Pour {{arrondir}} un nombre à un rang donné (dizaine, centaine, millier), on observe le chiffre placé {{immédiatement à droite}} de ce rang :\n— s'il vaut 0, 1, 2, 3 ou 4, on garde la valeur inférieure ;\n— s'il vaut 5, 6, 7, 8 ou 9, on prend la valeur supérieure.\nDans les deux cas, tous les chiffres situés à droite du rang deviennent des zéros."],
    ["3. Un exemple détaillé", "Arrondissons 3 472.\nÀ la dizaine : le chiffre à droite des dizaines est 2, inférieur à 5, donc l'arrondi est 3 470.\nÀ la centaine : le chiffre à droite des centaines est 7, supérieur à 5, donc l'arrondi est 3 500.\nAu millier : le chiffre à droite des milliers est 4, inférieur à 5, donc l'arrondi est 3 000."],
    ["4. Le signe ≈", "On note l'arrondi avec le signe {{≈}}, qui se lit « est environ égal à » : 3 472 ≈ 3 500 à la centaine près. Ce signe ne remplace jamais le signe =, car les deux nombres ne sont pas égaux."],
  ],
  exos: [
    { pts: 4, c: "Arrondis 5 847 à la dizaine, à la centaine, puis au millier.",
      r: "À la dizaine : [[5 850]]. À la centaine : [[5 800]]. Au millier : [[6 000]]." },
    { pts: 4, c: "Arrondis à la centaine : 1 250 ; 9 949 ; 380 ; 4 051.",
      r: "[[1 300]] ; [[9 900]] ; [[400]] ; [[4 100]]." },
    { pts: 4, c: "Un marché a accueilli 8 736 visiteurs. Donne ce nombre arrondi au millier, puis explique pourquoi ce chiffre est plus facile à retenir.",
      r: "[[9 000 visiteurs]], car le chiffre des centaines est 7, supérieur à 5. Ce nombre est plus simple à mémoriser et suffit pour donner un ordre de grandeur." },
    { pts: 4, c: "Trouve un nombre dont l'arrondi à la centaine est 600 et l'arrondi au millier est 1 000.",
      r: "Par exemple [[620]] : à la centaine on obtient 600, et au millier 1 000. Toute réponse comprise entre [[550 et 649]] convient." },
    { pts: 4, c: "Vrai ou faux ? 1. 4 500 arrondi au millier donne 4 000. 2. Le signe ≈ signifie « est égal à ». 3. 999 arrondi à la centaine donne 1 000. 4. Arrondir donne toujours un nombre plus grand.",
      r: "1. [[Faux]] : le chiffre des centaines est 5, donc on monte à 5 000. 2. [[Faux]] : il signifie « est environ égal à ». 3. [[Vrai]]. 4. [[Faux]] : on peut aussi descendre, comme 320 qui donne 300." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Doubles, moitiés, triples et quarts",
  objectif: "À la fin de la séance, l'élève est capable de calculer mentalement le double, la moitié, le triple et le quart d'un entier naturel.",
  materiel: "Bâtonnets de comptage, ardoises, jetons",
  rev: [["Arrondis 4 380 à la centaine.", "4 400."],
        ["Quel chiffre observe-t-on pour arrondir au millier ?", "Le chiffre des centaines."],
        ["Arrondis 92 à la dizaine.", "90."]],
  mise: { q: "Soa achète deux paniers identiques de 1 250 ariary chacun. Combien dépense-t-elle en tout ?", ra: "2 500 ariary." },
  obs: "Observez ces 12 bâtonnets posés sur la table. L'enseignant les sépare en deux tas égaux, puis regroupe deux paquets de 12.",
  ana: [
    ["Combien de bâtonnets dans chaque tas après le partage en deux ?", "Six bâtonnets."],
    ["Comment appelle-t-on ce résultat ?", "La moitié de 12."],
    ["Par quelle opération l'obtient-on ?", "En divisant par 2 : 12 ÷ 2 = 6."],
    ["Et si l'on réunit deux paquets de 12 ?", "On obtient 24, le double de 12."],
    ["Par quelle opération ?", "En multipliant par 2 : 12 × 2 = 24."],
    ["Que serait le triple de 12 ?", "36, car 12 × 3 = 36."],
    ["Et son quart ?", "3, car 12 ÷ 4 = 3."],
    ["Tout nombre a-t-il une moitié entière ?", "Non : 7 ÷ 2 ne donne pas un entier."],
  ],
  syn: "Donc, le double s'obtient en multipliant par 2 et la moitié en divisant par 2 ; le triple en multipliant par 3 et le quart en divisant par 4. Double et moitié sont deux opérations inverses, de même que triple et tiers.",
  astuce: "Pour doubler un nombre, on double séparément chaque tranche : le double de 1 250, c'est le double de 1 000 plus le double de 250, soit 2 000 + 500 = 2 500.",
  app: [
    { c: "Calcule mentalement :\n1. le double de 1 250\n2. la moitié de 4 600\n3. le triple de 320\n4. le quart de 800",
      r: "1. [[2 500]]\n2. [[2 300]]\n3. [[960]]\n4. [[200]]" },
    { c: "Complète :\n1. Le double de …… est 90.\n2. La moitié de …… est 35.\n3. Le triple de …… est 150.\n4. Le quart de …… est 25.",
      r: "1. [[45]]\n2. [[70]]\n3. [[50]]\n4. [[100]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. le double de 375\n2. la moitié de 1 800\n3. le triple de 41\n4. le quart de 2 400",
      r: "1. [[750]]\n2. [[900]]\n3. [[123]]\n4. [[600]]" },
    { c: "Hery récolte 640 kg de riz. Il en vend la moitié, puis le quart de ce qui reste.\n1. Quelle quantité vend-il d'abord ?\n2. Que lui reste-t-il alors ?\n3. Quelle quantité vend-il ensuite ?\n4. Que lui reste-t-il à la fin ?",
      r: "1. [[320 kg]], car 640 ÷ 2 = 320.\n2. [[320 kg]].\n3. [[80 kg]], car 320 ÷ 4 = 80.\n4. [[240 kg]], car 320 − 80 = 240." },
  ],
  lecon: [
    ["1. Le double et la moitié", "Le {{double}} d'un nombre s'obtient en le multipliant par 2. La {{moitié}} s'obtient en le divisant par 2.\nCes deux opérations sont {{inverses}} l'une de l'autre : le double de 18 est 36, et la moitié de 36 est bien 18."],
    ["2. Le triple et le quart", "Le {{triple}} s'obtient en multipliant par 3, le {{quart}} en divisant par 4. De même, le tiers s'obtient en divisant par 3.\nExemple : le triple de 25 est 75 ; le quart de 100 est 25."],
    ["3. Calculer de tête", "Pour aller vite, on décompose le nombre. Le double de 1 250 se calcule ainsi : double de 1 000 = 2 000, double de 250 = 500, total 2 500.\nPour la moitié de 4 600 : moitié de 4 000 = 2 000, moitié de 600 = 300, total 2 300."],
    ["4. Tous les nombres n'ont pas de moitié entière", "La moitié de 7 n'est pas un entier naturel. Un nombre dont la moitié est entière est un nombre {{pair}} ; les autres sont {{impairs}}. Un nombre est pair lorsqu'il se termine par 0, 2, 4, 6 ou 8."],
  ],
  exos: [
    { pts: 4, c: "Calcule le double de 145, de 2 300, de 78 et de 1 000.",
      r: "[[290]] ; [[4 600]] ; [[156]] ; [[2 000]]." },
    { pts: 4, c: "Calcule la moitié de 96, de 250, de 1 400 et de 3 000.",
      r: "[[48]] ; [[125]] ; [[700]] ; [[1 500]]." },
    { pts: 4, c: "Calcule le triple de 60, puis le quart de 480.",
      r: "Le triple de 60 est [[180]]. Le quart de 480 est [[120]]." },
    { pts: 4, c: "Nivo a 1 600 ariary. Elle dépense la moitié au marché, puis le quart du reste pour le transport. Combien lui reste-t-il ?",
      r: "Elle dépense d'abord [[800 ariary]] et il lui reste 800. Elle dépense ensuite [[200 ariary]], car 800 ÷ 4 = 200. Il lui reste donc [[600 ariary]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Le double de 0 est 0. 2. Tout nombre a une moitié entière. 3. Le quart de 20 est 5. 4. Le triple de 11 est 33.",
      r: "1. [[Vrai]]. 2. [[Faux]] : la moitié de 9 n'est pas entière. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Résoudre un problème avec des entiers naturels",
  objectif: "À la fin de la séance, l'élève est capable de repérer les données utiles d'un énoncé, de choisir l'opération convenable et de rédiger une réponse complète.",
  materiel: "Énoncés écrits au tableau, cahier de recherche, ardoises",
  rev: [["Quelle est la moitié de 500 ?", "250."],
        ["Quel est le double de 340 ?", "680."],
        ["Arrondis 2 470 à la centaine.", "2 500."]],
  mise: { q: "Quand vous faites une course au marché, comment savez-vous combien on doit vous rendre ?", ra: "On soustrait le prix de la somme donnée." },
  obs: "Lisez silencieusement l'énoncé écrit au tableau : « Un commerçant reçoit 12 sacs de riz contenant chacun 25 kg. Il en vend 180 kg. Quelle masse de riz lui reste-t-il ? »",
  ana: [
    ["Quelles sont les données de cet énoncé ?", "12 sacs, 25 kg par sac, et 180 kg vendus."],
    ["Que cherche-t-on exactement ?", "La masse de riz restante."],
    ["Peut-on répondre directement ?", "Non, il faut d'abord connaître la masse totale reçue."],
    ["Comment obtient-on cette masse totale ?", "En multipliant : 12 × 25 = 300 kg."],
    ["Quelle opération donne ensuite le reste ?", "Une soustraction : 300 − 180 = 120 kg."],
    ["Combien d'étapes comporte donc ce problème ?", "Deux étapes : une multiplication puis une soustraction."],
    ["Comment rédige-t-on la réponse ?", "Par une phrase complète : « Il lui reste 120 kg de riz. »"],
  ],
  syn: "Donc, pour résoudre un problème, on lit l'énoncé attentivement, on relève les données utiles, on identifie la question posée, on choisit la ou les opérations nécessaires, on effectue les calculs, puis on rédige la réponse par une phrase complète avec son unité.",
  attention: "Un mot de l'énoncé ne désigne pas toujours l'opération à faire. « De plus » n'appelle pas forcément une addition : dans « Koto a 12 zébus de plus que Rova qui en a 30 », c'est bien une addition, mais dans « Koto a 12 zébus de moins que Rova qui en a 30 », il faut soustraire. Il faut comprendre la situation, pas repérer un mot.",
  app: [
    { c: "Un car transporte 52 passagers. Six cars font le trajet Antananarivo–Antsirabe.\n1. Quelle opération choisis-tu ?\n2. Combien de passagers en tout ?\n3. Si 40 descendent en route, combien reste-t-il de passagers ?\n4. Rédige la réponse finale.",
      r: "1. [[Une multiplication]], car on répète 52 six fois.\n2. [[312 passagers]], car 6 × 52 = 312.\n3. [[272 passagers]], car 312 − 40 = 272.\n4. « [[Il reste 272 passagers dans les cars.]] »" },
    { c: "Fara possède 4 500 ariary et sa sœur 3 800 ariary. Elles achètent ensemble un cadeau à 7 250 ariary.\n1. Quelle somme ont-elles au total ?\n2. Leur reste-t-il de l'argent ?\n3. Combien ?\n4. Écris la phrase réponse.",
      r: "1. [[8 300 ariary]], car 4 500 + 3 800 = 8 300.\n2. [[Oui]], car 8 300 est supérieur à 7 250.\n3. [[1 050 ariary]], car 8 300 − 7 250 = 1 050.\n4. « [[Il leur reste 1 050 ariary.]] »" },
  ],
  evalx: [
    { c: "Une école reçoit 15 cartons de 40 cahiers. Elle en distribue 380.\n1. Combien de cahiers reçoit-elle ?\n2. Combien lui en reste-t-il ?\n3. Quelles opérations as-tu utilisées ?\n4. Rédige la phrase réponse.",
      r: "1. [[600 cahiers]], car 15 × 40 = 600.\n2. [[220 cahiers]], car 600 − 380 = 220.\n3. [[Une multiplication puis une soustraction]].\n4. « [[Il reste 220 cahiers à l'école.]] »" },
    { c: "Remets dans l'ordre les étapes de la résolution d'un problème :\na. effectuer les calculs — b. lire l'énoncé — c. rédiger la réponse — d. choisir l'opération",
      r: "L'ordre correct est [[b, d, a, c]] : on lit d'abord l'énoncé, on choisit ensuite l'opération, on effectue les calculs, puis on rédige la réponse." },
  ],
  lecon: [
    ["1. Lire et comprendre", "Un problème se lit au moins deux fois. La première lecture fait comprendre la situation ; la seconde permet de relever les {{données}}, c'est-à-dire les nombres utiles, et de repérer la {{question}} posée.\nAttention : un énoncé peut contenir une donnée inutile, placée là pour vérifier que l'on réfléchit."],
    ["2. Choisir l'opération", "On {{additionne}} pour réunir deux quantités, on {{soustrait}} pour retirer ou comparer, on {{multiplie}} pour répéter une même quantité, on {{divise}} pour partager en parts égales.\nCe n'est pas un mot de l'énoncé qui décide, mais le sens de la situation."],
    ["3. Les problèmes à deux étapes", "Beaucoup de problèmes ne se résolvent pas d'un seul calcul. Il faut alors trouver une {{étape intermédiaire}}.\nExemple : 12 sacs de 25 kg dont on vend 180 kg. On calcule d'abord le total, 12 × 25 = 300 kg, puis le reste, 300 − 180 = 120 kg."],
    ["4. Rédiger la réponse", "Un résultat seul ne suffit pas. On écrit une {{phrase réponse}} complète, qui reprend les termes de la question et précise l'{{unité}} : « Il reste 120 kg de riz », et non simplement « 120 »."],
  ],
  exos: [
    { pts: 4, c: "Un planteur récolte 24 paniers de 15 kg de litchis. Quelle masse a-t-il récoltée ?",
      r: "Il faut multiplier : 24 × 15 = [[360]]. « [[Le planteur a récolté 360 kg de litchis.]] »" },
    { pts: 4, c: "Aina avait 9 000 ariary. Elle a dépensé 3 450 ariary puis 2 200 ariary. Combien lui reste-t-il ?",
      r: "Total dépensé : 3 450 + 2 200 = [[5 650 ariary]]. Reste : 9 000 − 5 650 = [[3 350 ariary]]. « [[Il lui reste 3 350 ariary.]] »" },
    { pts: 4, c: "Une classe de 45 élèves part en sortie. Chaque élève verse 800 ariary. Quelle somme est réunie ?",
      r: "45 × 800 = [[36 000]]. « [[La classe a réuni 36 000 ariary.]] »" },
    { pts: 4, c: "Dans l'énoncé suivant, relève la donnée inutile : « Lanto part à 6 heures. Il achète 3 kg de tomates à 2 000 ariary le kilogramme. Combien paie-t-il ? »",
      r: "La donnée inutile est [[l'heure de départ, 6 heures]] : elle n'intervient pas dans le calcul. Le prix payé est 3 × 2 000 = [[6 000 ariary]]." },
    { pts: 4, c: "Écris un problème dont la résolution est 5 × 12 = 60, puis rédige sa phrase réponse.",
      r: "Par exemple : « [[Un marchand range 12 œufs par plateau. Combien d'œufs contiennent 5 plateaux ?]] » Réponse : « [[Les 5 plateaux contiennent 60 œufs.]] »" },
  ],
},

];
