// Période IV — séances rédigées.
module.exports = [
{
  ch: "Proportionnalité et pourcentages",
  titre: "Reconnaître une situation de proportionnalité",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître un tableau de proportionnalité et d'en déterminer le coefficient.",
  materiel: "Tableaux au tableau noir, ardoises, étiquettes de prix",
  rev: [["Calcule 7 500 ÷ 3.", "2 500."],
        ["Calcule 2 500 × 5.", "12 500."],
        ["Que signifie « le double » ?", "Deux fois plus."]],
  mise: { q: "Si 3 kg de riz coûtent 7 500 ariary, combien coûtent 6 kg au même prix ?", ra: "15 000 ariary, le double." },
  obs: "Observez le tableau au tableau noir : masse de riz 1, 3, 5 et 8 kg ; prix correspondants 2 500, 7 500, 12 500 et 20 000 ariary.",
  ana: [
    ["Que coûte un kilogramme ?", "2 500 ariary."],
    ["Que coûtent trois kilogrammes ?", "7 500 ariary."],
    ["Quel calcul relie 3 et 7 500 ?", "Une multiplication par 2 500."],
    ["Et pour 5 kilogrammes ?", "Encore une multiplication par 2 500."],
    ["Ce nombre est-il toujours le même ?", "Oui, pour toutes les colonnes."],
    ["Comment le nomme-t-on ?", "Le coefficient de proportionnalité."],
    ["Si l'on double la masse, que devient le prix ?", "Il double aussi."],
    ["Comment reconnaître un tel tableau ?", "En vérifiant que le quotient est constant."],
  ],
  syn: "Donc, deux grandeurs sont proportionnelles lorsque l'on passe de l'une à l'autre en multipliant toujours par un même nombre, appelé coefficient de proportionnalité. Dans un tel tableau, si l'une des grandeurs double ou triple, l'autre double ou triple aussi.",
  attention: "Toutes les situations ne sont pas proportionnelles. L'âge d'une personne et sa taille ne le sont pas : un enfant de dix ans ne mesure pas le double d'un enfant de cinq ans.",
  astuce: "Pour tester la proportionnalité, divisez chaque valeur de la seconde ligne par celle du dessus : si vous obtenez toujours le même nombre, le tableau est proportionnel.",
  app: [
    { c: "Trois kilogrammes de riz coûtent 7 500 ariary.\n1. Quel est le prix d'un kilogramme ?\n2. Celui de 5 kg ?\n3. Celui de 8 kg ?\n4. Quel est le coefficient ?",
      r: "1. [[2 500 ariary]]\n2. [[12 500 ariary]]\n3. [[20 000 ariary]]\n4. [[2 500]]" },
    { c: "Ces situations sont-elles proportionnelles ?\n1. Le prix payé et le nombre de cahiers achetés\n2. L'âge d'un enfant et sa taille\n3. La distance parcourue à vitesse constante et la durée\n4. Le nombre d'élèves et la note obtenue",
      r: "1. [[Oui]]\n2. [[Non]]\n3. [[Oui]]\n4. [[Non]]" },
  ],
  evalx: [
    { c: "Un cahier coûte 1 500 ariary.\n1. Prix de 4 cahiers ?\n2. Prix de 12 cahiers ?\n3. Quel est le coefficient ?\n4. Combien de cahiers pour 9 000 ariary ?",
      r: "1. [[6 000 ariary]]\n2. [[18 000 ariary]]\n3. [[1 500]]\n4. [[6 cahiers]]" },
    { c: "Complète :\n1. Deux grandeurs proportionnelles sont liées par un ……\n2. Si l'une double, l'autre ……\n3. Le coefficient s'obtient par une ……\n4. Un tableau est proportionnel si le quotient est ……",
      r: "1. [[coefficient de proportionnalité]]\n2. [[double]]\n3. [[division]]\n4. [[constant]]" },
  ],
  lecon: [
    ["1. Définition", "Deux grandeurs sont {{proportionnelles}} lorsque l'on obtient les valeurs de la seconde en multipliant celles de la première par un {{même nombre}}.\nCe nombre s'appelle le {{coefficient de proportionnalité}}."],
    ["2. Le tableau de proportionnalité", "On présente ces situations dans un tableau à deux lignes.\nPour du riz à 2 500 ariary le kilogramme : 1 kg vaut 2 500 Ar, 3 kg valent 7 500 Ar, 5 kg valent 12 500 Ar, 8 kg valent 20 000 Ar.\nLe coefficient est ici de 2 500."],
    ["3. Reconnaître la proportionnalité", "On divise chaque valeur de la seconde ligne par celle qui lui correspond : 7 500 ÷ 3 = 2 500, 12 500 ÷ 5 = 2 500.\nLe quotient étant {{constant}}, le tableau est bien proportionnel.\nSi l'un des quotients diffère, la situation ne l'est {{pas}}."],
    ["4. Les situations non proportionnelles", "Beaucoup de situations ne relèvent pas de la proportionnalité : l'âge et la taille d'une personne, le nombre d'élèves et la note obtenue.\nUn abonnement comportant une part fixe n'est pas non plus proportionnel à la durée."],
  ],
  exos: [
    { pts: 4, c: "Un cahier coûte 1 500 ariary. Quel est le prix de 12 cahiers ?",
      r: "12 × 1 500 = [[18 000 ariary]]." },
    { pts: 4, c: "Cinq kilogrammes de riz coûtent 12 500 ariary. Quel est le prix d'un kilogramme, puis de 8 kg ?",
      r: "Un kilogramme : [[2 500 ariary]]. Huit kilogrammes : [[20 000 ariary]]." },
    { pts: 4, c: "Comment vérifier qu'un tableau est un tableau de proportionnalité ?",
      r: "En [[divisant]] chaque valeur de la seconde ligne par celle du dessus : le quotient doit être [[constant]]." },
    { pts: 4, c: "Donne un exemple de situation proportionnelle et un exemple de situation qui ne l'est pas.",
      r: "Proportionnelle : le [[prix payé et la quantité achetée]]. Non proportionnelle : l'[[âge et la taille]] d'une personne." },
    { pts: 4, c: "Vrai ou faux ? 1. Le coefficient change d'une colonne à l'autre. 2. Si la quantité double, le prix double. 3. Toutes les situations sont proportionnelles. 4. Le coefficient s'obtient par division.",
      r: "1. [[Faux]]. 2. [[Vrai]]. 3. [[Faux]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "La règle de trois",
  objectif: "À la fin de la séance, l'élève est capable d'appliquer la règle de trois pour calculer une quatrième proportionnelle.",
  materiel: "Tableaux de proportionnalité, ardoises, cahier",
  rev: [["Que vaut le coefficient si 3 kg coûtent 7 500 Ar ?", "2 500."],
        ["Calcule 4 500 ÷ 6.", "750."],
        ["Calcule 750 × 10.", "7 500."]],
  mise: { q: "Six bidons d'huile coûtent 4 500 ariary. Combien coûtent dix bidons ?", ra: "7 500 ariary." },
  obs: "Observez la démarche écrite au tableau : 6 bidons pour 4 500 Ar, donc 1 bidon pour 4 500 ÷ 6 = 750 Ar, donc 10 bidons pour 750 × 10 = 7 500 Ar.",
  ana: [
    ["Quelle est la première étape ?", "Chercher le prix d'un seul bidon."],
    ["Quelle opération ?", "Une division."],
    ["Combien coûte un bidon ?", "750 ariary."],
    ["Comment nomme-t-on ce passage par l'unité ?", "Le retour à l'unité."],
    ["Quelle est la deuxième étape ?", "Multiplier par 10."],
    ["Quel est le résultat ?", "7 500 ariary."],
    ["Pourrait-on procéder autrement ?", "Oui, en multipliant d'abord par 10 puis en divisant par 6."],
    ["Comment nomme-t-on cette méthode ?", "La règle de trois."],
  ],
  syn: "Donc, la règle de trois permet de calculer une quatrième valeur à partir de trois valeurs connues d'un tableau de proportionnalité. On passe généralement par la valeur de l'unité : on divise, puis on multiplie. On peut aussi multiplier d'abord et diviser ensuite.",
  attention: "Vérifiez toujours la vraisemblance du résultat. Si l'on achète davantage, le prix doit augmenter : un résultat inférieur signale une inversion entre la division et la multiplication.",
  astuce: "Disposez les données en tableau avant de calculer. La quatrième case, celle que l'on cherche, apparaît alors clairement en face de la valeur connue.",
  app: [
    { c: "Six bidons coûtent 4 500 ariary.\n1. Quel est le prix d'un bidon ?\n2. Celui de 10 bidons ?\n3. Celui de 15 bidons ?\n4. Combien de bidons pour 3 000 ariary ?",
      r: "1. [[750 ariary]]\n2. [[7 500 ariary]]\n3. [[11 250 ariary]]\n4. [[4 bidons]]" },
    { c: "Un taxi-brousse parcourt 240 km en 4 heures à vitesse constante.\n1. Quelle distance en 1 heure ?\n2. En 7 heures ?\n3. En 2 heures ?\n4. Combien d'heures pour 480 km ?",
      r: "1. [[60 km]]\n2. [[420 km]]\n3. [[120 km]]\n4. [[8 heures]]" },
  ],
  evalx: [
    { c: "Quatre sacs de ciment coûtent 96 000 ariary.\n1. Prix d'un sac ?\n2. Prix de 7 sacs ?\n3. Prix de 12 sacs ?\n4. Combien de sacs pour 240 000 ariary ?",
      r: "1. [[24 000 ariary]]\n2. [[168 000 ariary]]\n3. [[288 000 ariary]]\n4. [[10 sacs]]" },
    { c: "Complète :\n1. La règle de trois utilise …… valeurs connues.\n2. On passe souvent par la valeur de l'……\n3. On divise puis on ……\n4. Si la quantité augmente, le prix ……",
      r: "1. [[trois]]\n2. [[unité]]\n3. [[multiplie]]\n4. [[augmente]]" },
  ],
  lecon: [
    ["1. Le principe", "La {{règle de trois}} permet de trouver une quatrième valeur lorsque trois sont connues dans une situation de proportionnalité.\nOn l'appelle aussi recherche de la {{quatrième proportionnelle}}."],
    ["2. Le retour à l'unité", "La méthode la plus sûre consiste à chercher d'abord la valeur pour {{une}} unité.\nSi 6 bidons coûtent 4 500 Ar, alors 1 bidon coûte 4 500 ÷ 6 = 750 Ar.\nOn multiplie ensuite : 10 bidons coûtent 750 × 10 = 7 500 Ar."],
    ["3. L'autre disposition", "On peut aussi multiplier d'abord puis diviser : 4 500 × 10 = 45 000, puis 45 000 ÷ 6 = 7 500 Ar.\nLe résultat est le {{même}} ; on choisit l'ordre qui simplifie les calculs."],
    ["4. Le problème inverse", "La règle de trois s'utilise dans les deux sens. Pour savoir combien de bidons l'on obtient avec 3 000 Ar, on divise : 3 000 ÷ 750 = {{4 bidons}}.\nOn vérifie enfin la {{vraisemblance}} : plus d'argent doit donner plus de bidons."],
  ],
  exos: [
    { pts: 4, c: "Six bidons d'huile coûtent 4 500 ariary. Quel est le prix de 10 bidons ?",
      r: "Un bidon : 4 500 ÷ 6 = 750 Ar. Dix bidons : [[7 500 ariary]]." },
    { pts: 4, c: "Un taxi-brousse parcourt 240 km en 4 heures. Quelle distance parcourt-il en 7 heures à la même allure ?",
      r: "240 ÷ 4 = 60 km par heure, puis 60 × 7 = [[420 km]]." },
    { pts: 4, c: "Quatre sacs de ciment coûtent 96 000 ariary. Combien de sacs peut-on acheter avec 240 000 ariary ?",
      r: "Un sac : 24 000 Ar. 240 000 ÷ 24 000 = [[10 sacs]]." },
    { pts: 4, c: "Trois mètres de tissu coûtent 21 000 ariary. Quel est le prix de 8 mètres ?",
      r: "Un mètre : 7 000 Ar. Huit mètres : [[56 000 ariary]]." },
    { pts: 4, c: "Explique en quoi consiste le retour à l'unité.",
      r: "Il consiste à calculer d'abord la valeur correspondant à [[une seule unité]], par une [[division]], avant de multiplier par la quantité voulue." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Échelles et représentations",
  objectif: "À la fin de la séance, l'élève est capable d'utiliser une échelle pour passer d'une distance sur le plan à une distance réelle.",
  materiel: "Plans, cartes, règle graduée, ardoises",
  rev: [["Convertis 600 cm en mètres.", "6 m."],
        ["Calcule 3 × 200.", "600."],
        ["Qu'est-ce qu'un coefficient de proportionnalité ?", "Le nombre par lequel on multiplie."]],
  mise: { q: "Sur un plan, une salle de classe mesure 4 cm. Comment connaître sa longueur réelle ?", ra: "En utilisant l'échelle du plan." },
  obs: "Observez le plan affiché : il porte la mention « échelle 1/200 ». Une pièce y mesure 3 cm de long.",
  ana: [
    ["Que signifie l'écriture 1/200 ?", "Que 1 cm sur le plan représente 200 cm en réalité."],
    ["Combien font 200 cm en mètres ?", "2 mètres."],
    ["Quelle longueur réelle pour 3 cm ?", "600 cm."],
    ["Soit combien de mètres ?", "6 mètres."],
    ["Quelle opération a-t-on faite ?", "Une multiplication par 200."],
    ["Et pour passer du réel au plan ?", "Une division par 200."],
    ["S'agit-il d'une proportionnalité ?", "Oui, l'échelle est le coefficient."],
  ],
  syn: "Donc, l'échelle d'un plan indique par quel nombre il faut multiplier une longueur mesurée sur le plan pour obtenir la longueur réelle. Une échelle de un deux-centième signifie que un centimètre sur le plan représente deux cents centimètres dans la réalité. Le passage inverse se fait par une division.",
  attention: "Le résultat obtenu est d'abord exprimé dans l'unité de la mesure faite sur le plan. Une longueur de 600 obtenue à partir de centimètres est en centimètres, et doit être convertie en mètres.",
  astuce: "Plus le nombre du dénominateur est grand, plus la réduction est forte : une carte au un millionième montre un pays entier, un plan au centième une seule maison.",
  app: [
    { c: "Un plan est à l'échelle 1/200.\n1. Que représente 1 cm sur le plan ?\n2. Quelle longueur réelle pour 3 cm ?\n3. Exprime-la en mètres.\n4. Quelle longueur sur le plan pour 10 m réels ?",
      r: "1. [[200 cm]], soit 2 m\n2. [[600 cm]]\n3. [[6 m]]\n4. [[5 cm]]" },
    { c: "Une carte est à l'échelle 1/100 000.\n1. Que représente 1 cm ?\n2. Exprime-le en kilomètres.\n3. Quelle distance réelle pour 4 cm ?\n4. Et pour 12 cm ?",
      r: "1. [[100 000 cm]]\n2. [[1 km]]\n3. [[4 km]]\n4. [[12 km]]" },
  ],
  evalx: [
    { c: "Sur un plan au 1/50, une table mesure 3 cm.\n1. Quelle est sa longueur réelle en centimètres ?\n2. En mètres ?\n3. Une armoire réelle de 2 m mesure combien sur le plan ?\n4. Quelle opération as-tu utilisée ?",
      r: "1. [[150 cm]]\n2. [[1,5 m]]\n3. [[4 cm]]\n4. Une [[division par 50]]" },
    { c: "Complète :\n1. L'échelle est un ……\n2. Du plan au réel, on ……\n3. Du réel au plan, on ……\n4. Une échelle 1/1 000 signifie que 1 cm représente ……",
      r: "1. [[coefficient de proportionnalité]]\n2. [[multiplie]]\n3. [[divise]]\n4. [[1 000 cm]], soit 10 m" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'une échelle", "L'{{échelle}} d'un plan ou d'une carte indique le rapport entre les longueurs représentées et les longueurs réelles.\nUne échelle de 1/200 signifie que {{1 cm}} sur le plan représente {{200 cm}} dans la réalité, soit 2 mètres."],
    ["2. Du plan à la réalité", "Pour obtenir une longueur réelle, on {{multiplie}} la longueur mesurée sur le plan par le nombre de l'échelle.\nUne pièce de 3 cm sur un plan au 1/200 mesure 3 × 200 = 600 cm, soit 6 m."],
    ["3. De la réalité au plan", "Pour représenter une longueur réelle sur le plan, on {{divise}} par le nombre de l'échelle.\nUne pièce réelle de 10 m, soit 1 000 cm, se dessine sur 1 000 ÷ 200 = 5 cm."],
    ["4. Choisir une échelle", "Plus le dénominateur est {{grand}}, plus la réduction est importante.\nUn plan de maison s'établit au 1/100, un plan de quartier au 1/2 000, une carte régionale au 1/100 000.\nL'échelle est un {{coefficient de proportionnalité}} : les longueurs du plan et les longueurs réelles sont proportionnelles."],
  ],
  exos: [
    { pts: 4, c: "Sur un plan au 1/200, une salle mesure 3 cm. Quelle est sa longueur réelle en mètres ?",
      r: "3 × 200 = 600 cm, soit [[6 m]]." },
    { pts: 4, c: "Sur une carte au 1/100 000, deux villages sont distants de 7 cm. Quelle est la distance réelle en kilomètres ?",
      r: "7 × 100 000 = 700 000 cm, soit [[7 km]]." },
    { pts: 4, c: "Un terrain réel de 30 m doit figurer sur un plan au 1/500. Quelle longueur le représentera ?",
      r: "30 m = 3 000 cm ; 3 000 ÷ 500 = [[6 cm]]." },
    { pts: 4, c: "Que signifie l'échelle 1/50 ?",
      r: "Que [[1 cm]] sur le plan représente [[50 cm]] dans la réalité, soit 0,5 m." },
    { pts: 4, c: "Vrai ou faux ? 1. Du plan au réel, on divise. 2. L'échelle est un coefficient de proportionnalité. 3. Au 1/1 000, 1 cm vaut 10 m. 4. Plus le dénominateur est grand, plus la réduction est faible.",
      r: "1. [[Faux]] : on multiplie. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : la réduction est plus forte." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Découvrir les pourcentages",
  objectif: "À la fin de la séance, l'élève est capable de comprendre la notion de pourcentage et de calculer un pourcentage simple d'une quantité.",
  materiel: "Grilles de cent cases, ardoises, étiquettes",
  rev: [["Que vaut <<1/4>> de 400 ?", "100."],
        ["Calcule 3 500 ÷ 10.", "350."],
        ["Que vaut la moitié de 96 ?", "48."]],
  mise: { q: "Une affiche annonce « 25 % de remise ». Que signifie exactement ce nombre ?", ra: "Vingt-cinq ariary de moins sur cent ariary." },
  obs: "Observez la grille de cent cases affichée au tableau : vingt-cinq cases sont coloriées en bleu, dix en jaune, et le reste demeure blanc.",
  ana: [
    ["Combien de cases compte la grille ?", "Cent."],
    ["Combien sont bleues ?", "Vingt-cinq."],
    ["Quelle fraction cela représente-t-il ?", "Vingt-cinq centièmes."],
    ["Comment l'écrire en pourcentage ?", "25 pour cent."],
    ["Que vaut cette fraction simplifiée ?", "Un quart."],
    ["Que vaut alors 25 % de 400 ?", "100."],
    ["Combien de cases jaunes ?", "Dix, soit 10 %."],
    ["Que vaut 10 % de 3 500 ?", "350."],
  ],
  syn: "Donc, un pourcentage exprime une part rapportée à cent. Écrire vingt-cinq pour cent revient à écrire vingt-cinq centièmes, c'est-à-dire un quart. Pour calculer un pourcentage d'une quantité, on multiplie cette quantité par le pourcentage puis on divise par cent.",
  attention: "Un pourcentage ne signifie rien à lui seul : il porte toujours sur une quantité. Dix pour cent de 1 000 ariary et dix pour cent de 100 000 ariary ne représentent pas la même somme.",
  astuce: "Retenez les pourcentages courants : 50 % c'est la moitié, 25 % le quart, 10 % le dixième, 20 % le cinquième. Ils permettent de calculer de tête.",
  app: [
    { c: "Calcule :\n1. 25 % de 400\n2. 10 % de 3 500\n3. 50 % de 96\n4. 20 % de 1 500",
      r: "1. [[100]]\n2. [[350]]\n3. [[48]]\n4. [[300]]" },
    { c: "Écris sous forme de fraction simplifiée :\n1. 50 %\n2. 25 %\n3. 10 %\n4. 20 %",
      r: "1. [[<<1/2>>]]\n2. [[<<1/4>>]]\n3. [[<<1/10>>]]\n4. [[<<1/5>>]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. 15 % de 2 000\n2. 75 % de 800\n3. 30 % de 250\n4. 5 % de 4 000",
      r: "1. [[300]]\n2. [[600]]\n3. [[75]]\n4. [[200]]" },
    { c: "Une classe de 40 élèves compte 25 % de redoublants.\n1. Combien de redoublants ?\n2. Combien de non-redoublants ?\n3. Quel pourcentage cela représente-t-il ?\n4. Quelle fraction vaut 25 % ?",
      r: "1. [[10]]\n2. [[30]]\n3. [[75 %]]\n4. [[<<1/4>>]]" },
  ],
  lecon: [
    ["1. Le sens du pourcentage", "Un {{pourcentage}} exprime une part rapportée à {{cent}}.\nDire que 25 % d'une grille de cent cases sont coloriées signifie que 25 cases le sont.\nAinsi, 25 % s'écrit aussi <<25/100>>."],
    ["2. Pourcentage et fraction", "Tout pourcentage est une fraction de dénominateur 100, que l'on peut {{simplifier}} :\n50 % = <<50/100>> = <<1/2>> ; 25 % = <<1/4>> ; 20 % = <<1/5>> ; 10 % = <<1/10>>."],
    ["3. Calculer un pourcentage", "Pour calculer p % d'une quantité, on {{multiplie}} cette quantité par p puis on {{divise}} par 100.\n25 % de 400 : 400 × 25 = 10 000, puis 10 000 ÷ 100 = 100.\nOn peut aussi utiliser la fraction : <<1/4>> de 400 = 100."],
    ["4. Une quantité de référence", "Un pourcentage porte toujours sur une {{quantité de référence}}.\n10 % de 3 500 ariary font 350 ariary, tandis que 10 % de 100 000 ariary font 10 000 ariary : le même pourcentage donne des sommes très différentes."],
  ],
  exos: [
    { pts: 4, c: "Calcule 25 % de 400 et 10 % de 3 500.",
      r: "[[100]] et [[350]]." },
    { pts: 4, c: "Écris 50 %, 20 % et 75 % sous forme de fractions simplifiées.",
      r: "[[<<1/2>>]] ; [[<<1/5>>]] ; [[<<3/4>>]]." },
    { pts: 4, c: "Une classe de 40 élèves compte 25 % de filles. Combien y a-t-il de filles et de garçons ?",
      r: "Filles : [[10]]. Garçons : [[30]]." },
    { pts: 4, c: "Calcule 15 % de 2 000 ariary et 75 % de 800 ariary.",
      r: "[[300 ariary]] et [[600 ariary]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 50 % est la moitié. 2. 25 % vaut <<1/5>>. 3. Un pourcentage porte sur une quantité. 4. 10 % de 3 500 font 350.",
      r: "1. [[Vrai]]. 2. [[Faux]] : c'est <<1/4>>. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Remises, hausses et proportions",
  objectif: "À la fin de la séance, l'élève est capable de calculer un prix après remise ou après hausse, et d'exprimer une part en pourcentage.",
  materiel: "Étiquettes de prix, affiches de promotion, ardoises",
  rev: [["Calcule 20 % de 45 000.", "9 000."],
        ["Calcule 10 % de 8 000.", "800."],
        ["Calcule 45 000 − 9 000.", "36 000."]],
  mise: { q: "Un article à 45 000 ariary bénéficie d'une remise de 20 %. Quel prix paie-t-on ?", ra: "36 000 ariary." },
  obs: "Observez au tableau les deux calculs : 45 000 × 20 ÷ 100 = 9 000 puis 45 000 − 9 000 = 36 000 ; et 8 000 × 10 ÷ 100 = 800 puis 8 000 + 800 = 8 800.",
  ana: [
    ["Que représente le nombre 9 000 ?", "Le montant de la remise."],
    ["Que fait-on ensuite ?", "On le soustrait du prix initial."],
    ["Quel est le prix payé ?", "36 000 ariary."],
    ["Dans le second calcul, que représente 800 ?", "Le montant de la hausse."],
    ["Que fait-on de ce montant ?", "On l'ajoute."],
    ["Quel est le nouveau prix ?", "8 800 ariary."],
    ["Comment exprimer 12 sur 48 en pourcentage ?", "On calcule 12 ÷ 48 × 100, soit 25 %."],
  ],
  syn: "Donc, pour appliquer une remise, on calcule le montant de la remise puis on le soustrait du prix initial ; pour une hausse, on l'ajoute. Réciproquement, pour exprimer une part en pourcentage, on divise la part par le total puis on multiplie par cent.",
  attention: "Une remise de vingt pour cent ne signifie pas que l'on paie vingt pour cent du prix, mais que l'on en retranche vingt pour cent : il reste donc quatre-vingts pour cent à payer.",
  astuce: "Pour une remise de 20 %, calculez directement 80 % du prix : 45 000 × 80 ÷ 100 = 36 000. Cela évite la soustraction.",
  app: [
    { c: "Un article coûte 45 000 ariary avec une remise de 20 %.\n1. Quel est le montant de la remise ?\n2. Quel prix paie-t-on ?\n3. Quel pourcentage du prix paie-t-on ?\n4. Vérifie par un autre calcul.",
      r: "1. [[9 000 ariary]]\n2. [[36 000 ariary]]\n3. [[80 %]]\n4. [[45 000 × 80 ÷ 100 = 36 000]]" },
    { c: "Un produit à 8 000 ariary augmente de 10 %.\n1. Quel est le montant de la hausse ?\n2. Quel est le nouveau prix ?\n3. Quel pourcentage de l'ancien prix représente-t-il ?\n4. Rédige la phrase réponse.",
      r: "1. [[800 ariary]]\n2. [[8 800 ariary]]\n3. [[110 %]]\n4. « [[Le nouveau prix est de 8 800 ariary.]] »" },
  ],
  evalx: [
    { c: "Exprime en pourcentage :\n1. 12 sur 48\n2. 18 sur 25\n3. 60 sur 240\n4. 30 sur 50",
      r: "1. [[25 %]]\n2. [[72 %]]\n3. [[25 %]]\n4. [[60 %]]" },
    { c: "Un commerçant achète un sac 30 000 ariary et le revend avec 20 % de bénéfice.\n1. Quel est le bénéfice ?\n2. Quel est le prix de vente ?\n3. S'il accorde ensuite 10 % de remise sur ce prix, quelle est la remise ?\n4. Quel prix final ?",
      r: "1. [[6 000 ariary]]\n2. [[36 000 ariary]]\n3. [[3 600 ariary]]\n4. [[32 400 ariary]]" },
  ],
  lecon: [
    ["1. Calculer une remise", "Une {{remise}} est une diminution du prix exprimée en pourcentage.\nOn calcule d'abord son montant, puis on le {{soustrait}} du prix initial.\nRemise de 20 % sur 45 000 Ar : 45 000 × 20 ÷ 100 = 9 000 Ar, d'où un prix payé de 36 000 Ar."],
    ["2. La méthode directe", "Une remise de 20 % laisse {{80 %}} du prix à payer.\nOn peut donc calculer directement 45 000 × 80 ÷ 100 = 36 000 Ar, en une seule opération."],
    ["3. Calculer une hausse", "Une {{hausse}} s'ajoute au prix initial.\nHausse de 10 % sur 8 000 Ar : 8 000 × 10 ÷ 100 = 800 Ar, d'où un nouveau prix de 8 800 Ar.\nOn peut aussi calculer directement 110 % du prix."],
    ["4. Exprimer une part en pourcentage", "Pour savoir quel pourcentage une part représente, on la {{divise}} par le total puis on multiplie par {{100}}.\n12 élèves absents sur 48 : 12 ÷ 48 = 0,25, soit 25 %."],
  ],
  exos: [
    { pts: 4, c: "Un article coûte 45 000 ariary. Avec une remise de 20 %, quel prix paie-t-on ?",
      r: "Remise : 9 000 Ar. Prix payé : [[36 000 ariary]]." },
    { pts: 4, c: "Un produit à 8 000 ariary augmente de 10 %. Quel est son nouveau prix ?",
      r: "Hausse : 800 Ar. Nouveau prix : [[8 800 ariary]]." },
    { pts: 4, c: "Sur 48 élèves, 12 sont absents. Quel pourcentage cela représente-t-il ?",
      r: "12 ÷ 48 × 100 = [[25 %]]." },
    { pts: 4, c: "Un commerçant achète un sac 30 000 ariary et réalise 20 % de bénéfice. À quel prix le revend-il ?",
      r: "Bénéfice : 6 000 Ar. Prix de vente : [[36 000 ariary]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Une remise de 20 % laisse 80 % à payer. 2. Une hausse se soustrait. 3. 18 sur 25 font 72 %. 4. On divise la part par le total pour obtenir le pourcentage.",
      r: "1. [[Vrai]]. 2. [[Faux]] : elle s'ajoute. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Problèmes de proportionnalité",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème concret mêlant proportionnalité et pourcentage.",
  materiel: "Énoncés au tableau, cahier de recherche",
  rev: [["Calcule 25 % de 400.", "100."],
        ["Six bidons coûtent 4 500 Ar : combien pour dix ?", "7 500 ariary."],
        ["Que signifie une échelle 1/200 ?", "Un centimètre représente deux cents centimètres."]],
  mise: { q: "Une coopérative vend du riz au kilogramme et accorde une remise aux gros acheteurs. Comment calculer la facture ?", ra: "En calculant d'abord le prix, puis la remise." },
  obs: "Lisez l'énoncé au tableau : « Une coopérative vend le riz 2 500 ariary le kilogramme. Un client achète 40 kg et bénéficie de 15 % de remise. »",
  ana: [
    ["Quelle est la première grandeur à calculer ?", "Le prix avant remise."],
    ["Combien vaut-il ?", "100 000 ariary."],
    ["Comment l'a-t-on obtenu ?", "En multipliant 40 par 2 500."],
    ["Quel est le montant de la remise ?", "15 000 ariary."],
    ["Quel calcul ?", "100 000 × 15 ÷ 100."],
    ["Quel est le prix payé ?", "85 000 ariary."],
    ["Peut-on le trouver autrement ?", "Oui, en calculant 85 % de 100 000."],
    ["Combien d'étapes ce problème comporte-t-il ?", "Trois."],
  ],
  syn: "Donc, un problème de proportionnalité se résout en repérant d'abord la grandeur proportionnelle, en appliquant la règle de trois, puis en tenant compte, s'il y a lieu, du pourcentage de remise ou de hausse. Chaque étape s'écrit avec son unité, et le résultat se contrôle par un ordre de grandeur.",
  attention: "Un pourcentage porte sur le montant qui le précède immédiatement. Une remise appliquée après une hausse ne se calcule pas sur le prix initial, mais sur le prix déjà augmenté.",
  app: [
    { c: "Le riz vaut 2 500 ariary le kilogramme. Un client achète 40 kg avec 15 % de remise.\n1. Quel est le prix avant remise ?\n2. Quel est le montant de la remise ?\n3. Quel est le prix payé ?\n4. Vérifie par le calcul direct.",
      r: "1. [[100 000 ariary]]\n2. [[15 000 ariary]]\n3. [[85 000 ariary]]\n4. [[100 000 × 85 ÷ 100 = 85 000]]" },
    { c: "Un maçon pose 12 m² de carrelage en 3 heures.\n1. Quelle surface en 1 heure ?\n2. En 7 heures ?\n3. Combien d'heures pour 48 m² ?\n4. Est-ce une situation proportionnelle ?",
      r: "1. [[4 m²]]\n2. [[28 m²]]\n3. [[12 heures]]\n4. [[Oui]], le coefficient est constant" },
  ],
  evalx: [
    { c: "Une école de 250 élèves compte 60 % de filles.\n1. Combien de filles ?\n2. Combien de garçons ?\n3. Quel pourcentage de garçons ?\n4. Vérifie ton calcul.",
      r: "1. [[150]]\n2. [[100]]\n3. [[40 %]]\n4. [[150 + 100 = 250]]" },
    { c: "Un commerçant achète 25 sacs de vanille à 80 000 ariary l'unité et les revend avec 20 % de bénéfice.\n1. Quel est le prix d'achat total ?\n2. Quel est le bénéfice total ?\n3. Quel est le prix de vente total ?\n4. Quel est le prix de vente d'un sac ?",
      r: "1. [[2 000 000 ariary]]\n2. [[400 000 ariary]]\n3. [[2 400 000 ariary]]\n4. [[96 000 ariary]]" },
  ],
  lecon: [
    ["1. Repérer la proportionnalité", "On commence par identifier les deux grandeurs {{proportionnelles}} : une quantité et un prix, une durée et une distance, une surface et une durée de travail."],
    ["2. Appliquer la règle de trois", "On calcule la valeur pour {{une}} unité, puis on multiplie par la quantité demandée.\n40 kg de riz à 2 500 Ar le kilogramme coûtent 40 × 2 500 = 100 000 Ar."],
    ["3. Tenir compte du pourcentage", "On applique ensuite la {{remise}} ou la {{hausse}} sur le montant obtenu.\nUne remise de 15 % sur 100 000 Ar vaut 15 000 Ar : le client paie 85 000 Ar.\nLe calcul direct de 85 % donne le même résultat."],
    ["4. Contrôler le résultat", "On vérifie par un {{ordre de grandeur}} : une remise de 15 % doit réduire légèrement le prix, non le diviser par deux.\nOn conclut par une {{phrase réponse}} comportant l'unité."],
  ],
  exos: [
    { pts: 4, c: "Le riz vaut 2 500 ariary le kilogramme. Combien coûtent 40 kg ?",
      r: "40 × 2 500 = [[100 000 ariary]]." },
    { pts: 4, c: "Sur cet achat, le client obtient 15 % de remise. Quel prix paie-t-il ?",
      r: "Remise : 15 000 Ar. Prix payé : [[85 000 ariary]]." },
    { pts: 4, c: "Une école de 250 élèves compte 60 % de filles. Combien y a-t-il de garçons ?",
      r: "Filles : 150. Garçons : [[100]]." },
    { pts: 4, c: "Un maçon pose 12 m² de carrelage en 3 heures. Combien de temps lui faut-il pour 48 m² ?",
      r: "4 m² par heure ; 48 ÷ 4 = [[12 heures]]." },
    { pts: 4, c: "Un commerçant achète 25 sacs à 80 000 ariary et les revend avec 20 % de bénéfice. Quel est le prix de vente total ?",
      r: "Achat : 2 000 000 Ar. Bénéfice : 400 000 Ar. Vente : [[2 400 000 ariary]]." },
  ],
},
];
