// Période IV — séances rédigées.
module.exports = [
{
  ch: "Proportionnalité et pourcentages",
  titre: "Reconnaître une situation de proportionnalité",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître un tableau de proportionnalité et d'en déterminer le coefficient.",
  materiel: "Tableaux au tableau noir, ardoises, étiquettes de prix",
  rev: [["Calcule 7 500 ÷ 3.", "2 500."],
        ["Calcule 2 500 × 5.", "12 500."],
        ["Que signifie « le double » ?", "Deux fois plus."]],
  mise: { q: "Si 3 kg de riz coûtent 7 500 ariary, combien coûtent 6 kg au même prix ?", ra: "15 000 ariary, le double." },
  obs: "Observez le tableau au tableau noir : masse de riz 1, 3, 5 et 8 kg ; prix correspondants 2 500, 7 500, 12 500 et 20 000 ariary.",
  ana: [
    ["Que coûte un kilogramme ?", "2 500 ariary."],
    ["Que coûtent trois kilogrammes ?", "7 500 ariary."],
    ["Quel calcul relie 3 et 7 500 ?", "Une multiplication par 2 500."],
    ["Et pour 5 kilogrammes ?", "Encore une multiplication par 2 500."],
    ["Ce nombre est-il toujours le même ?", "Oui, pour toutes les colonnes."],
    ["Comment le nomme-t-on ?", "Le coefficient de proportionnalité."],
    ["Si l'on double la masse, que devient le prix ?", "Il double aussi."],
    ["Comment reconnaître un tel tableau ?", "En vérifiant que le quotient est constant."],
  ],
  syn: "Donc, deux grandeurs sont proportionnelles lorsque l'on passe de l'une à l'autre en multipliant toujours par un même nombre, appelé coefficient de proportionnalité. Dans un tel tableau, si l'une des grandeurs double ou triple, l'autre double ou triple aussi.",
  attention: "Toutes les situations ne sont pas proportionnelles. L'âge d'une personne et sa taille ne le sont pas : un enfant de dix ans ne mesure pas le double d'un enfant de cinq ans.",
  astuce: "Pour tester la proportionnalité, divisez chaque valeur de la seconde ligne par celle du dessus : si vous obtenez toujours le même nombre, le tableau est proportionnel.",
  app: [
    { c: "Trois kilogrammes de riz coûtent 7 500 ariary.\n1. Quel est le prix d'un kilogramme ?\n2. Celui de 5 kg ?\n3. Celui de 8 kg ?\n4. Quel est le coefficient ?",
      r: "1. [[2 500 ariary]]\n2. [[12 500 ariary]]\n3. [[20 000 ariary]]\n4. [[2 500]]" },
    { c: "Ces situations sont-elles proportionnelles ?\n1. Le prix payé et le nombre de cahiers achetés\n2. L'âge d'un enfant et sa taille\n3. La distance parcourue à vitesse constante et la durée\n4. Le nombre d'élèves et la note obtenue",
      r: "1. [[Oui]]\n2. [[Non]]\n3. [[Oui]]\n4. [[Non]]" },
  ],
  evalx: [
    { c: "Un cahier coûte 1 500 ariary.\n1. Prix de 4 cahiers ?\n2. Prix de 12 cahiers ?\n3. Quel est le coefficient ?\n4. Combien de cahiers pour 9 000 ariary ?",
      r: "1. [[6 000 ariary]]\n2. [[18 000 ariary]]\n3. [[1 500]]\n4. [[6 cahiers]]" },
    { c: "Complète :\n1. Deux grandeurs proportionnelles sont liées par un ……\n2. Si l'une double, l'autre ……\n3. Le coefficient s'obtient par une ……\n4. Un tableau est proportionnel si le quotient est ……",
      r: "1. [[coefficient de proportionnalité]]\n2. [[double]]\n3. [[division]]\n4. [[constant]]" },
  ],
  lecon: [
    ["1. Définition", "Deux grandeurs sont {{proportionnelles}} lorsque l'on obtient les valeurs de la seconde en multipliant celles de la première par un {{même nombre}}.\nCe nombre s'appelle le {{coefficient de proportionnalité}}."],
    ["2. Le tableau de proportionnalité", "On présente ces situations dans un tableau à deux lignes.\nPour du riz à 2 500 ariary le kilogramme : 1 kg vaut 2 500 Ar, 3 kg valent 7 500 Ar, 5 kg valent 12 500 Ar, 8 kg valent 20 000 Ar.\nLe coefficient est ici de 2 500."],
    ["3. Reconnaître la proportionnalité", "On divise chaque valeur de la seconde ligne par celle qui lui correspond : 7 500 ÷ 3 = 2 500, 12 500 ÷ 5 = 2 500.\nLe quotient étant {{constant}}, le tableau est bien proportionnel.\nSi l'un des quotients diffère, la situation ne l'est {{pas}}."],
    ["4. Les situations non proportionnelles", "Beaucoup de situations ne relèvent pas de la proportionnalité : l'âge et la taille d'une personne, le nombre d'élèves et la note obtenue.\nUn abonnement comportant une part fixe n'est pas non plus proportionnel à la durée."],
  ],
  exos: [
    { pts: 4, c: "Un cahier coûte 1 500 ariary. Quel est le prix de 12 cahiers ?",
      r: "12 × 1 500 = [[18 000 ariary]]." },
    { pts: 4, c: "Cinq kilogrammes de riz coûtent 12 500 ariary. Quel est le prix d'un kilogramme, puis de 8 kg ?",
      r: "Un kilogramme : [[2 500 ariary]]. Huit kilogrammes : [[20 000 ariary]]." },
    { pts: 4, c: "Comment vérifier qu'un tableau est un tableau de proportionnalité ?",
      r: "En [[divisant]] chaque valeur de la seconde ligne par celle du dessus : le quotient doit être [[constant]]." },
    { pts: 4, c: "Donne un exemple de situation proportionnelle et un exemple de situation qui ne l'est pas.",
      r: "Proportionnelle : le [[prix payé et la quantité achetée]]. Non proportionnelle : l'[[âge et la taille]] d'une personne." },
    { pts: 4, c: "Vrai ou faux ? 1. Le coefficient change d'une colonne à l'autre. 2. Si la quantité double, le prix double. 3. Toutes les situations sont proportionnelles. 4. Le coefficient s'obtient par division.",
      r: "1. [[Faux]]. 2. [[Vrai]]. 3. [[Faux]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "La règle de trois",
  objectif: "À la fin de la séance, l'élève est capable d'appliquer la règle de trois pour calculer une quatrième proportionnelle.",
  materiel: "Tableaux de proportionnalité, ardoises, cahier",
  rev: [["Que vaut le coefficient si 3 kg coûtent 7 500 Ar ?", "2 500."],
        ["Calcule 4 500 ÷ 6.", "750."],
        ["Calcule 750 × 10.", "7 500."]],
  mise: { q: "Six bidons d'huile coûtent 4 500 ariary. Combien coûtent dix bidons ?", ra: "7 500 ariary." },
  obs: "Observez la démarche écrite au tableau : 6 bidons pour 4 500 Ar, donc 1 bidon pour 4 500 ÷ 6 = 750 Ar, donc 10 bidons pour 750 × 10 = 7 500 Ar.",
  ana: [
    ["Quelle est la première étape ?", "Chercher le prix d'un seul bidon."],
    ["Quelle opération ?", "Une division."],
    ["Combien coûte un bidon ?", "750 ariary."],
    ["Comment nomme-t-on ce passage par l'unité ?", "Le retour à l'unité."],
    ["Quelle est la deuxième étape ?", "Multiplier par 10."],
    ["Quel est le résultat ?", "7 500 ariary."],
    ["Pourrait-on procéder autrement ?", "Oui, en multipliant d'abord par 10 puis en divisant par 6."],
    ["Comment nomme-t-on cette méthode ?", "La règle de trois."],
  ],
  syn: "Donc, la règle de trois permet de calculer une quatrième valeur à partir de trois valeurs connues d'un tableau de proportionnalité. On passe généralement par la valeur de l'unité : on divise, puis on multiplie. On peut aussi multiplier d'abord et diviser ensuite.",
  attention: "Vérifiez toujours la vraisemblance du résultat. Si l'on achète davantage, le prix doit augmenter : un résultat inférieur signale une inversion entre la division et la multiplication.",
  astuce: "Disposez les données en tableau avant de calculer. La quatrième case, celle que l'on cherche, apparaît alors clairement en face de la valeur connue.",
  app: [
    { c: "Six bidons coûtent 4 500 ariary.\n1. Quel est le prix d'un bidon ?\n2. Celui de 10 bidons ?\n3. Celui de 15 bidons ?\n4. Combien de bidons pour 3 000 ariary ?",
      r: "1. [[750 ariary]]\n2. [[7 500 ariary]]\n3. [[11 250 ariary]]\n4. [[4 bidons]]" },
    { c: "Un taxi-brousse parcourt 240 km en 4 heures à vitesse constante.\n1. Quelle distance en 1 heure ?\n2. En 7 heures ?\n3. En 2 heures ?\n4. Combien d'heures pour 480 km ?",
      r: "1. [[60 km]]\n2. [[420 km]]\n3. [[120 km]]\n4. [[8 heures]]" },
  ],
  evalx: [
    { c: "Quatre sacs de ciment coûtent 96 000 ariary.\n1. Prix d'un sac ?\n2. Prix de 7 sacs ?\n3. Prix de 12 sacs ?\n4. Combien de sacs pour 240 000 ariary ?",
      r: "1. [[24 000 ariary]]\n2. [[168 000 ariary]]\n3. [[288 000 ariary]]\n4. [[10 sacs]]" },
    { c: "Complète :\n1. La règle de trois utilise …… valeurs connues.\n2. On passe souvent par la valeur de l'……\n3. On divise puis on ……\n4. Si la quantité augmente, le prix ……",
      r: "1. [[trois]]\n2. [[unité]]\n3. [[multiplie]]\n4. [[augmente]]" },
  ],
  lecon: [
    ["1. Le principe", "La {{règle de trois}} permet de trouver une quatrième valeur lorsque trois sont connues dans une situation de proportionnalité.\nOn l'appelle aussi recherche de la {{quatrième proportionnelle}}."],
    ["2. Le retour à l'unité", "La méthode la plus sûre consiste à chercher d'abord la valeur pour {{une}} unité.\nSi 6 bidons coûtent 4 500 Ar, alors 1 bidon coûte 4 500 ÷ 6 = 750 Ar.\nOn multiplie ensuite : 10 bidons coûtent 750 × 10 = 7 500 Ar."],
    ["3. L'autre disposition", "On peut aussi multiplier d'abord puis diviser : 4 500 × 10 = 45 000, puis 45 000 ÷ 6 = 7 500 Ar.\nLe résultat est le {{même}} ; on choisit l'ordre qui simplifie les calculs."],
    ["4. Le problème inverse", "La règle de trois s'utilise dans les deux sens. Pour savoir combien de bidons l'on obtient avec 3 000 Ar, on divise : 3 000 ÷ 750 = {{4 bidons}}.\nOn vérifie enfin la {{vraisemblance}} : plus d'argent doit donner plus de bidons."],
  ],
  exos: [
    { pts: 4, c: "Six bidons d'huile coûtent 4 500 ariary. Quel est le prix de 10 bidons ?",
      r: "Un bidon : 4 500 ÷ 6 = 750 Ar. Dix bidons : [[7 500 ariary]]." },
    { pts: 4, c: "Un taxi-brousse parcourt 240 km en 4 heures. Quelle distance parcourt-il en 7 heures à la même allure ?",
      r: "240 ÷ 4 = 60 km par heure, puis 60 × 7 = [[420 km]]." },
    { pts: 4, c: "Quatre sacs de ciment coûtent 96 000 ariary. Combien de sacs peut-on acheter avec 240 000 ariary ?",
      r: "Un sac : 24 000 Ar. 240 000 ÷ 24 000 = [[10 sacs]]." },
    { pts: 4, c: "Trois mètres de tissu coûtent 21 000 ariary. Quel est le prix de 8 mètres ?",
      r: "Un mètre : 7 000 Ar. Huit mètres : [[56 000 ariary]]." },
    { pts: 4, c: "Explique en quoi consiste le retour à l'unité.",
      r: "Il consiste à calculer d'abord la valeur correspondant à [[une seule unité]], par une [[division]], avant de multiplier par la quantité voulue." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Échelles et représentations",
  objectif: "À la fin de la séance, l'élève est capable d'utiliser une échelle pour passer d'une distance sur le plan à une distance réelle.",
  materiel: "Plans, cartes, règle graduée, ardoises",
  rev: [["Convertis 600 cm en mètres.", "6 m."],
        ["Calcule 3 × 200.", "600."],
        ["Qu'est-ce qu'un coefficient de proportionnalité ?", "Le nombre par lequel on multiplie."]],
  mise: { q: "Sur un plan, une salle de classe mesure 4 cm. Comment connaître sa longueur réelle ?", ra: "En utilisant l'échelle du plan." },
  obs: "Observez le plan affiché : il porte la mention « échelle 1/200 ». Une pièce y mesure 3 cm de long.",
  ana: [
    ["Que signifie l'écriture 1/200 ?", "Que 1 cm sur le plan représente 200 cm en réalité."],
    ["Combien font 200 cm en mètres ?", "2 mètres."],
    ["Quelle longueur réelle pour 3 cm ?", "600 cm."],
    ["Soit combien de mètres ?", "6 mètres."],
    ["Quelle opération a-t-on faite ?", "Une multiplication par 200."],
    ["Et pour passer du réel au plan ?", "Une division par 200."],
    ["S'agit-il d'une proportionnalité ?", "Oui, l'échelle est le coefficient."],
  ],
  syn: "Donc, l'échelle d'un plan indique par quel nombre il faut multiplier une longueur mesurée sur le plan pour obtenir la longueur réelle. Une échelle de un deux-centième signifie que un centimètre sur le plan représente deux cents centimètres dans la réalité. Le passage inverse se fait par une division.",
  attention: "Le résultat obtenu est d'abord exprimé dans l'unité de la mesure faite sur le plan. Une longueur de 600 obtenue à partir de centimètres est en centimètres, et doit être convertie en mètres.",
  astuce: "Plus le nombre du dénominateur est grand, plus la réduction est forte : une carte au un millionième montre un pays entier, un plan au centième une seule maison.",
  app: [
    { c: "Un plan est à l'échelle 1/200.\n1. Que représente 1 cm sur le plan ?\n2. Quelle longueur réelle pour 3 cm ?\n3. Exprime-la en mètres.\n4. Quelle longueur sur le plan pour 10 m réels ?",
      r: "1. [[200 cm]], soit 2 m\n2. [[600 cm]]\n3. [[6 m]]\n4. [[5 cm]]" },
    { c: "Une carte est à l'échelle 1/100 000.\n1. Que représente 1 cm ?\n2. Exprime-le en kilomètres.\n3. Quelle distance réelle pour 4 cm ?\n4. Et pour 12 cm ?",
      r: "1. [[100 000 cm]]\n2. [[1 km]]\n3. [[4 km]]\n4. [[12 km]]" },
  ],
  evalx: [
    { c: "Sur un plan au 1/50, une table mesure 3 cm.\n1. Quelle est sa longueur réelle en centimètres ?\n2. En mètres ?\n3. Une armoire réelle de 2 m mesure combien sur le plan ?\n4. Quelle opération as-tu utilisée ?",
      r: "1. [[150 cm]]\n2. [[1,5 m]]\n3. [[4 cm]]\n4. Une [[division par 50]]" },
    { c: "Complète :\n1. L'échelle est un ……\n2. Du plan au réel, on ……\n3. Du réel au plan, on ……\n4. Une échelle 1/1 000 signifie que 1 cm représente ……",
      r: "1. [[coefficient de proportionnalité]]\n2. [[multiplie]]\n3. [[divise]]\n4. [[1 000 cm]], soit 10 m" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'une échelle", "L'{{échelle}} d'un plan ou d'une carte indique le rapport entre les longueurs représentées et les longueurs réelles.\nUne échelle de 1/200 signifie que {{1 cm}} sur le plan représente {{200 cm}} dans la réalité, soit 2 mètres."],
    ["2. Du plan à la réalité", "Pour obtenir une longueur réelle, on {{multiplie}} la longueur mesurée sur le plan par le nombre de l'échelle.\nUne pièce de 3 cm sur un plan au 1/200 mesure 3 × 200 = 600 cm, soit 6 m."],
    ["3. De la réalité au plan", "Pour représenter une longueur réelle sur le plan, on {{divise}} par le nombre de l'échelle.\nUne pièce réelle de 10 m, soit 1 000 cm, se dessine sur 1 000 ÷ 200 = 5 cm."],
    ["4. Choisir une échelle", "Plus le dénominateur est {{grand}}, plus la réduction est importante.\nUn plan de maison s'établit au 1/100, un plan de quartier au 1/2 000, une carte régionale au 1/100 000.\nL'échelle est un {{coefficient de proportionnalité}} : les longueurs du plan et les longueurs réelles sont proportionnelles."],
  ],
  exos: [
    { pts: 4, c: "Sur un plan au 1/200, une salle mesure 3 cm. Quelle est sa longueur réelle en mètres ?",
      r: "3 × 200 = 600 cm, soit [[6 m]]." },
    { pts: 4, c: "Sur une carte au 1/100 000, deux villages sont distants de 7 cm. Quelle est la distance réelle en kilomètres ?",
      r: "7 × 100 000 = 700 000 cm, soit [[7 km]]." },
    { pts: 4, c: "Un terrain réel de 30 m doit figurer sur un plan au 1/500. Quelle longueur le représentera ?",
      r: "30 m = 3 000 cm ; 3 000 ÷ 500 = [[6 cm]]." },
    { pts: 4, c: "Que signifie l'échelle 1/50 ?",
      r: "Que [[1 cm]] sur le plan représente [[50 cm]] dans la réalité, soit 0,5 m." },
    { pts: 4, c: "Vrai ou faux ? 1. Du plan au réel, on divise. 2. L'échelle est un coefficient de proportionnalité. 3. Au 1/1 000, 1 cm vaut 10 m. 4. Plus le dénominateur est grand, plus la réduction est faible.",
      r: "1. [[Faux]] : on multiplie. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : la réduction est plus forte." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Découvrir les pourcentages",
  objectif: "À la fin de la séance, l'élève est capable de comprendre la notion de pourcentage et de calculer un pourcentage simple d'une quantité.",
  materiel: "Grilles de cent cases, ardoises, étiquettes",
  rev: [["Que vaut <<1/4>> de 400 ?", "100."],
        ["Calcule 3 500 ÷ 10.", "350."],
        ["Que vaut la moitié de 96 ?", "48."]],
  mise: { q: "Une affiche annonce « 25 % de remise ». Que signifie exactement ce nombre ?", ra: "Vingt-cinq ariary de moins sur cent ariary." },
  obs: "Observez la grille de cent cases affichée au tableau : vingt-cinq cases sont coloriées en bleu, dix en jaune, et le reste demeure blanc.",
  ana: [
    ["Combien de cases compte la grille ?", "Cent."],
    ["Combien sont bleues ?", "Vingt-cinq."],
    ["Quelle fraction cela représente-t-il ?", "Vingt-cinq centièmes."],
    ["Comment l'écrire en pourcentage ?", "25 pour cent."],
    ["Que vaut cette fraction simplifiée ?", "Un quart."],
    ["Que vaut alors 25 % de 400 ?", "100."],
    ["Combien de cases jaunes ?", "Dix, soit 10 %."],
    ["Que vaut 10 % de 3 500 ?", "350."],
  ],
  syn: "Donc, un pourcentage exprime une part rapportée à cent. Écrire vingt-cinq pour cent revient à écrire vingt-cinq centièmes, c'est-à-dire un quart. Pour calculer un pourcentage d'une quantité, on multiplie cette quantité par le pourcentage puis on divise par cent.",
  attention: "Un pourcentage ne signifie rien à lui seul : il porte toujours sur une quantité. Dix pour cent de 1 000 ariary et dix pour cent de 100 000 ariary ne représentent pas la même somme.",
  astuce: "Retenez les pourcentages courants : 50 % c'est la moitié, 25 % le quart, 10 % le dixième, 20 % le cinquième. Ils permettent de calculer de tête.",
  app: [
    { c: "Calcule :\n1. 25 % de 400\n2. 10 % de 3 500\n3. 50 % de 96\n4. 20 % de 1 500",
      r: "1. [[100]]\n2. [[350]]\n3. [[48]]\n4. [[300]]" },
    { c: "Écris sous forme de fraction simplifiée :\n1. 50 %\n2. 25 %\n3. 10 %\n4. 20 %",
      r: "1. [[<<1/2>>]]\n2. [[<<1/4>>]]\n3. [[<<1/10>>]]\n4. [[<<1/5>>]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. 15 % de 2 000\n2. 75 % de 800\n3. 30 % de 250\n4. 5 % de 4 000",
      r: "1. [[300]]\n2. [[600]]\n3. [[75]]\n4. [[200]]" },
    { c: "Une classe de 40 élèves compte 25 % de redoublants.\n1. Combien de redoublants ?\n2. Combien de non-redoublants ?\n3. Quel pourcentage cela représente-t-il ?\n4. Quelle fraction vaut 25 % ?",
      r: "1. [[10]]\n2. [[30]]\n3. [[75 %]]\n4. [[<<1/4>>]]" },
  ],
  lecon: [
    ["1. Le sens du pourcentage", "Un {{pourcentage}} exprime une part rapportée à {{cent}}.\nDire que 25 % d'une grille de cent cases sont coloriées signifie que 25 cases le sont.\nAinsi, 25 % s'écrit aussi <<25/100>>."],
    ["2. Pourcentage et fraction", "Tout pourcentage est une fraction de dénominateur 100, que l'on peut {{simplifier}} :\n50 % = <<50/100>> = <<1/2>> ; 25 % = <<1/4>> ; 20 % = <<1/5>> ; 10 % = <<1/10>>."],
    ["3. Calculer un pourcentage", "Pour calculer p % d'une quantité, on {{multiplie}} cette quantité par p puis on {{divise}} par 100.\n25 % de 400 : 400 × 25 = 10 000, puis 10 000 ÷ 100 = 100.\nOn peut aussi utiliser la fraction : <<1/4>> de 400 = 100."],
    ["4. Une quantité de référence", "Un pourcentage porte toujours sur une {{quantité de référence}}.\n10 % de 3 500 ariary font 350 ariary, tandis que 10 % de 100 000 ariary font 10 000 ariary : le même pourcentage donne des sommes très différentes."],
  ],
  exos: [
    { pts: 4, c: "Calcule 25 % de 400 et 10 % de 3 500.",
      r: "[[100]] et [[350]]." },
    { pts: 4, c: "Écris 50 %, 20 % et 75 % sous forme de fractions simplifiées.",
      r: "[[<<1/2>>]] ; [[<<1/5>>]] ; [[<<3/4>>]]." },
    { pts: 4, c: "Une classe de 40 élèves compte 25 % de filles. Combien y a-t-il de filles et de garçons ?",
      r: "Filles : [[10]]. Garçons : [[30]]." },
    { pts: 4, c: "Calcule 15 % de 2 000 ariary et 75 % de 800 ariary.",
      r: "[[300 ariary]] et [[600 ariary]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 50 % est la moitié. 2. 25 % vaut <<1/5>>. 3. Un pourcentage porte sur une quantité. 4. 10 % de 3 500 font 350.",
      r: "1. [[Vrai]]. 2. [[Faux]] : c'est <<1/4>>. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Remises, hausses et proportions",
  objectif: "À la fin de la séance, l'élève est capable de calculer un prix après remise ou après hausse, et d'exprimer une part en pourcentage.",
  materiel: "Étiquettes de prix, affiches de promotion, ardoises",
  rev: [["Calcule 20 % de 45 000.", "9 000."],
        ["Calcule 10 % de 8 000.", "800."],
        ["Calcule 45 000 − 9 000.", "36 000."]],
  mise: { q: "Un article à 45 000 ariary bénéficie d'une remise de 20 %. Quel prix paie-t-on ?", ra: "36 000 ariary." },
  obs: "Observez au tableau les deux calculs : 45 000 × 20 ÷ 100 = 9 000 puis 45 000 − 9 000 = 36 000 ; et 8 000 × 10 ÷ 100 = 800 puis 8 000 + 800 = 8 800.",
  ana: [
    ["Que représente le nombre 9 000 ?", "Le montant de la remise."],
    ["Que fait-on ensuite ?", "On le soustrait du prix initial."],
    ["Quel est le prix payé ?", "36 000 ariary."],
    ["Dans le second calcul, que représente 800 ?", "Le montant de la hausse."],
    ["Que fait-on de ce montant ?", "On l'ajoute."],
    ["Quel est le nouveau prix ?", "8 800 ariary."],
    ["Comment exprimer 12 sur 48 en pourcentage ?", "On calcule 12 ÷ 48 × 100, soit 25 %."],
  ],
  syn: "Donc, pour appliquer une remise, on calcule le montant de la remise puis on le soustrait du prix initial ; pour une hausse, on l'ajoute. Réciproquement, pour exprimer une part en pourcentage, on divise la part par le total puis on multiplie par cent.",
  attention: "Une remise de vingt pour cent ne signifie pas que l'on paie vingt pour cent du prix, mais que l'on en retranche vingt pour cent : il reste donc quatre-vingts pour cent à payer.",
  astuce: "Pour une remise de 20 %, calculez directement 80 % du prix : 45 000 × 80 ÷ 100 = 36 000. Cela évite la soustraction.",
  app: [
    { c: "Un article coûte 45 000 ariary avec une remise de 20 %.\n1. Quel est le montant de la remise ?\n2. Quel prix paie-t-on ?\n3. Quel pourcentage du prix paie-t-on ?\n4. Vérifie par un autre calcul.",
      r: "1. [[9 000 ariary]]\n2. [[36 000 ariary]]\n3. [[80 %]]\n4. [[45 000 × 80 ÷ 100 = 36 000]]" },
    { c: "Un produit à 8 000 ariary augmente de 10 %.\n1. Quel est le montant de la hausse ?\n2. Quel est le nouveau prix ?\n3. Quel pourcentage de l'ancien prix représente-t-il ?\n4. Rédige la phrase réponse.",
      r: "1. [[800 ariary]]\n2. [[8 800 ariary]]\n3. [[110 %]]\n4. « [[Le nouveau prix est de 8 800 ariary.]] »" },
  ],
  evalx: [
    { c: "Exprime en pourcentage :\n1. 12 sur 48\n2. 18 sur 25\n3. 60 sur 240\n4. 30 sur 50",
      r: "1. [[25 %]]\n2. [[72 %]]\n3. [[25 %]]\n4. [[60 %]]" },
    { c: "Un commerçant achète un sac 30 000 ariary et le revend avec 20 % de bénéfice.\n1. Quel est le bénéfice ?\n2. Quel est le prix de vente ?\n3. S'il accorde ensuite 10 % de remise sur ce prix, quelle est la remise ?\n4. Quel prix final ?",
      r: "1. [[6 000 ariary]]\n2. [[36 000 ariary]]\n3. [[3 600 ariary]]\n4. [[32 400 ariary]]" },
  ],
  lecon: [
    ["1. Calculer une remise", "Une {{remise}} est une diminution du prix exprimée en pourcentage.\nOn calcule d'abord son montant, puis on le {{soustrait}} du prix initial.\nRemise de 20 % sur 45 000 Ar : 45 000 × 20 ÷ 100 = 9 000 Ar, d'où un prix payé de 36 000 Ar."],
    ["2. La méthode directe", "Une remise de 20 % laisse {{80 %}} du prix à payer.\nOn peut donc calculer directement 45 000 × 80 ÷ 100 = 36 000 Ar, en une seule opération."],
    ["3. Calculer une hausse", "Une {{hausse}} s'ajoute au prix initial.\nHausse de 10 % sur 8 000 Ar : 8 000 × 10 ÷ 100 = 800 Ar, d'où un nouveau prix de 8 800 Ar.\nOn peut aussi calculer directement 110 % du prix."],
    ["4. Exprimer une part en pourcentage", "Pour savoir quel pourcentage une part représente, on la {{divise}} par le total puis on multiplie par {{100}}.\n12 élèves absents sur 48 : 12 ÷ 48 = 0,25, soit 25 %."],
  ],
  exos: [
    { pts: 4, c: "Un article coûte 45 000 ariary. Avec une remise de 20 %, quel prix paie-t-on ?",
      r: "Remise : 9 000 Ar. Prix payé : [[36 000 ariary]]." },
    { pts: 4, c: "Un produit à 8 000 ariary augmente de 10 %. Quel est son nouveau prix ?",
      r: "Hausse : 800 Ar. Nouveau prix : [[8 800 ariary]]." },
    { pts: 4, c: "Sur 48 élèves, 12 sont absents. Quel pourcentage cela représente-t-il ?",
      r: "12 ÷ 48 × 100 = [[25 %]]." },
    { pts: 4, c: "Un commerçant achète un sac 30 000 ariary et réalise 20 % de bénéfice. À quel prix le revend-il ?",
      r: "Bénéfice : 6 000 Ar. Prix de vente : [[36 000 ariary]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Une remise de 20 % laisse 80 % à payer. 2. Une hausse se soustrait. 3. 18 sur 25 font 72 %. 4. On divise la part par le total pour obtenir le pourcentage.",
      r: "1. [[Vrai]]. 2. [[Faux]] : elle s'ajoute. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Proportionnalité et pourcentages",
  titre: "Problèmes de proportionnalité",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème concret mêlant proportionnalité et pourcentage.",
  materiel: "Énoncés au tableau, cahier de recherche",
  rev: [["Calcule 25 % de 400.", "100."],
        ["Six bidons coûtent 4 500 Ar : combien pour dix ?", "7 500 ariary."],
        ["Que signifie une échelle 1/200 ?", "Un centimètre représente deux cents centimètres."]],
  mise: { q: "Une coopérative vend du riz au kilogramme et accorde une remise aux gros acheteurs. Comment calculer la facture ?", ra: "En calculant d'abord le prix, puis la remise." },
  obs: "Lisez l'énoncé au tableau : « Une coopérative vend le riz 2 500 ariary le kilogramme. Un client achète 40 kg et bénéficie de 15 % de remise. »",
  ana: [
    ["Quelle est la première grandeur à calculer ?", "Le prix avant remise."],
    ["Combien vaut-il ?", "100 000 ariary."],
    ["Comment l'a-t-on obtenu ?", "En multipliant 40 par 2 500."],
    ["Quel est le montant de la remise ?", "15 000 ariary."],
    ["Quel calcul ?", "100 000 × 15 ÷ 100."],
    ["Quel est le prix payé ?", "85 000 ariary."],
    ["Peut-on le trouver autrement ?", "Oui, en calculant 85 % de 100 000."],
    ["Combien d'étapes ce problème comporte-t-il ?", "Trois."],
  ],
  syn: "Donc, un problème de proportionnalité se résout en repérant d'abord la grandeur proportionnelle, en appliquant la règle de trois, puis en tenant compte, s'il y a lieu, du pourcentage de remise ou de hausse. Chaque étape s'écrit avec son unité, et le résultat se contrôle par un ordre de grandeur.",
  attention: "Un pourcentage porte sur le montant qui le précède immédiatement. Une remise appliquée après une hausse ne se calcule pas sur le prix initial, mais sur le prix déjà augmenté.",
  app: [
    { c: "Le riz vaut 2 500 ariary le kilogramme. Un client achète 40 kg avec 15 % de remise.\n1. Quel est le prix avant remise ?\n2. Quel est le montant de la remise ?\n3. Quel est le prix payé ?\n4. Vérifie par le calcul direct.",
      r: "1. [[100 000 ariary]]\n2. [[15 000 ariary]]\n3. [[85 000 ariary]]\n4. [[100 000 × 85 ÷ 100 = 85 000]]" },
    { c: "Un maçon pose 12 m² de carrelage en 3 heures.\n1. Quelle surface en 1 heure ?\n2. En 7 heures ?\n3. Combien d'heures pour 48 m² ?\n4. Est-ce une situation proportionnelle ?",
      r: "1. [[4 m²]]\n2. [[28 m²]]\n3. [[12 heures]]\n4. [[Oui]], le coefficient est constant" },
  ],
  evalx: [
    { c: "Une école de 250 élèves compte 60 % de filles.\n1. Combien de filles ?\n2. Combien de garçons ?\n3. Quel pourcentage de garçons ?\n4. Vérifie ton calcul.",
      r: "1. [[150]]\n2. [[100]]\n3. [[40 %]]\n4. [[150 + 100 = 250]]" },
    { c: "Un commerçant achète 25 sacs de vanille à 80 000 ariary l'unité et les revend avec 20 % de bénéfice.\n1. Quel est le prix d'achat total ?\n2. Quel est le bénéfice total ?\n3. Quel est le prix de vente total ?\n4. Quel est le prix de vente d'un sac ?",
      r: "1. [[2 000 000 ariary]]\n2. [[400 000 ariary]]\n3. [[2 400 000 ariary]]\n4. [[96 000 ariary]]" },
  ],
  lecon: [
    ["1. Repérer la proportionnalité", "On commence par identifier les deux grandeurs {{proportionnelles}} : une quantité et un prix, une durée et une distance, une surface et une durée de travail."],
    ["2. Appliquer la règle de trois", "On calcule la valeur pour {{une}} unité, puis on multiplie par la quantité demandée.\n40 kg de riz à 2 500 Ar le kilogramme coûtent 40 × 2 500 = 100 000 Ar."],
    ["3. Tenir compte du pourcentage", "On applique ensuite la {{remise}} ou la {{hausse}} sur le montant obtenu.\nUne remise de 15 % sur 100 000 Ar vaut 15 000 Ar : le client paie 85 000 Ar.\nLe calcul direct de 85 % donne le même résultat."],
    ["4. Contrôler le résultat", "On vérifie par un {{ordre de grandeur}} : une remise de 15 % doit réduire légèrement le prix, non le diviser par deux.\nOn conclut par une {{phrase réponse}} comportant l'unité."],
  ],
  exos: [
    { pts: 4, c: "Le riz vaut 2 500 ariary le kilogramme. Combien coûtent 40 kg ?",
      r: "40 × 2 500 = [[100 000 ariary]]." },
    { pts: 4, c: "Sur cet achat, le client obtient 15 % de remise. Quel prix paie-t-il ?",
      r: "Remise : 15 000 Ar. Prix payé : [[85 000 ariary]]." },
    { pts: 4, c: "Une école de 250 élèves compte 60 % de filles. Combien y a-t-il de garçons ?",
      r: "Filles : 150. Garçons : [[100]]." },
    { pts: 4, c: "Un maçon pose 12 m² de carrelage en 3 heures. Combien de temps lui faut-il pour 48 m² ?",
      r: "4 m² par heure ; 48 ÷ 4 = [[12 heures]]." },
    { pts: 4, c: "Un commerçant achète 25 sacs à 80 000 ariary et les revend avec 20 % de bénéfice. Quel est le prix de vente total ?",
      r: "Achat : 2 000 000 Ar. Bénéfice : 400 000 Ar. Vente : [[2 400 000 ariary]]." },
  ],
},
{
  ch: "Aires",
  titre: "Découvrir la notion d'aire",
  objectif: "À la fin de la séance, l'élève est capable de distinguer l'aire du périmètre et de mesurer une aire par comptage d'unités.",
  materiel: "Papier quadrillé, figures découpées, règle",
  rev: [["Quel est le périmètre d'un carré de 6 cm ?", "24 cm."],
        ["Que mesure le périmètre ?", "La longueur du contour."],
        ["Calcule 6 × 6.", "36."]],
  mise: { q: "Pour acheter du carrelage, faut-il connaître le tour de la pièce ou sa surface ?", ra: "Sa surface." },
  obs: "Observez sur le papier quadrillé deux figures : un rectangle couvrant 12 carreaux et une figure irrégulière en couvrant également 12. Chaque carreau mesure un centimètre de côté.",
  ana: [
    ["Combien de carreaux couvre le rectangle ?", "Douze."],
    ["Que mesure ce nombre ?", "La surface occupée."],
    ["Comment nomme-t-on cette mesure ?", "L'aire."],
    ["Quelle est l'unité employée ici ?", "Le centimètre carré."],
    ["Les deux figures ont-elles la même aire ?", "Oui, douze centimètres carrés."],
    ["Ont-elles le même périmètre ?", "Non, pas nécessairement."],
    ["Quelle différence entre aire et périmètre ?", "L'aire mesure la surface, le périmètre le contour."],
  ],
  syn: "Donc, l'aire d'une figure est la mesure de la surface qu'elle occupe, tandis que le périmètre mesure la longueur de son contour. On exprime une aire en unités carrées, comme le centimètre carré, et l'on peut la déterminer en comptant les unités qui recouvrent la figure.",
  attention: "Deux figures de même aire n'ont pas nécessairement le même périmètre, et réciproquement. Ce sont deux grandeurs indépendantes que l'on ne doit jamais confondre.",
  astuce: "L'unité vous renseigne : une réponse en centimètres désigne un périmètre, une réponse en centimètres carrés désigne une aire.",
  app: [
    { c: "Sur du papier quadrillé en centimètres :\n1. Que mesure une case ?\n2. Une figure couvre 12 cases : quelle est son aire ?\n3. Quelle est l'unité ?\n4. Que mesure au contraire le périmètre ?",
      r: "1. [[1 cm²]]\n2. [[12 cm²]]\n3. Le [[centimètre carré]]\n4. La longueur du [[contour]]" },
    { c: "Aire ou périmètre ?\n1. La quantité de carrelage pour une pièce\n2. La longueur de la clôture d'un champ\n3. La peinture pour un mur\n4. Le ruban autour d'un cadeau",
      r: "1. L'[[aire]]\n2. Le [[périmètre]]\n3. L'[[aire]]\n4. Le [[périmètre]]" },
  ],
  evalx: [
    { c: "Un rectangle mesure 6 cm sur 2 cm.\n1. Combien de carreaux d'un centimètre le recouvrent ?\n2. Quelle est son aire ?\n3. Quel est son périmètre ?\n4. Ces deux nombres sont-ils comparables ?",
      r: "1. [[12]]\n2. [[12 cm²]]\n3. [[16 cm]]\n4. [[Non]], les unités sont différentes" },
    { c: "Complète :\n1. L'aire mesure une ……\n2. Le périmètre mesure un ……\n3. L'aire s'exprime en unités ……\n4. Deux figures de même aire ont-elles le même périmètre ?",
      r: "1. [[surface]]\n2. [[contour]]\n3. [[carrées]]\n4. [[Pas nécessairement]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'une aire", "L'{{aire}} d'une figure est la mesure de la {{surface}} qu'elle occupe.\nElle répond à des questions concrètes : combien de carrelage pour une pièce, combien de peinture pour un mur, quelle étendue pour un champ."],
    ["2. Aire et périmètre", "Le {{périmètre}} mesure la longueur du contour et s'exprime en centimètres ou en mètres.\nL'{{aire}} mesure la surface et s'exprime en centimètres carrés ou en mètres carrés.\nCe sont deux grandeurs {{différentes}} : deux figures de même aire peuvent avoir des périmètres distincts."],
    ["3. Mesurer par comptage", "Sur un papier {{quadrillé}}, il suffit de compter les carreaux qui recouvrent la figure.\nSi chaque carreau mesure 1 cm de côté, son aire vaut 1 {{cm²}}, et une figure couvrant 12 carreaux a une aire de 12 cm²."],
    ["4. Les unités d'aire", "L'unité principale est le {{mètre carré}}, noté m² : c'est l'aire d'un carré de 1 m de côté.\nOn emploie aussi le {{centimètre carré}} (cm²) pour les petites surfaces et le {{kilomètre carré}} (km²) pour les grandes étendues."],
  ],
  exos: [
    { pts: 4, c: "Explique la différence entre l'aire et le périmètre d'une figure.",
      r: "L'[[aire]] mesure la [[surface]] occupée, en unités carrées ; le [[périmètre]] mesure la longueur du [[contour]], en unités de longueur." },
    { pts: 4, c: "Une figure couvre 18 carreaux d'un centimètre de côté. Quelle est son aire ?",
      r: "[[18 cm²]]." },
    { pts: 4, c: "Pour chacune de ces situations, dis s'il faut calculer une aire ou un périmètre : carreler une pièce, clôturer un champ, peindre un mur.",
      r: "Carreler : [[aire]]. Clôturer : [[périmètre]]. Peindre : [[aire]]." },
    { pts: 4, c: "Un rectangle de 6 cm sur 2 cm : donne son aire et son périmètre.",
      r: "Aire : [[12 cm²]]. Périmètre : [[16 cm]]." },
    { pts: 4, c: "Vrai ou faux ? 1. L'aire s'exprime en cm. 2. Deux figures de même aire ont le même périmètre. 3. Le m² est l'aire d'un carré de 1 m de côté. 4. L'aire mesure une surface.",
      r: "1. [[Faux]] : en cm². 2. [[Faux]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Aires",
  titre: "Aire du carré et du rectangle",
  objectif: "À la fin de la séance, l'élève est capable de calculer l'aire d'un carré et d'un rectangle par la formule.",
  materiel: "Papier quadrillé, règle graduée, ardoises",
  rev: [["Qu'est-ce que l'aire ?", "La mesure de la surface occupée."],
        ["Calcule 8 × 5.", "40."],
        ["Calcule 4,5 × 4,5.", "20,25."]],
  mise: { q: "Faut-il vraiment compter un à un les carreaux d'un rectangle de 8 sur 5 ?", ra: "Non, une multiplication suffit." },
  obs: "Observez au tableau un rectangle quadrillé de 8 carreaux de long sur 5 de large, et un carré quadrillé de 6 carreaux de côté.",
  ana: [
    ["Combien de carreaux sur une rangée du rectangle ?", "Huit."],
    ["Combien de rangées ?", "Cinq."],
    ["Comment obtenir le total sans compter ?", "En multipliant 8 par 5."],
    ["Quelle est donc l'aire ?", "Quarante centimètres carrés."],
    ["Quelle formule en déduire ?", "Longueur multipliée par largeur."],
    ["Et pour le carré de 6 de côté ?", "Six fois six, soit trente-six."],
    ["Quelle formule pour le carré ?", "Côté multiplié par côté."],
  ],
  syn: "Donc, l'aire d'un rectangle s'obtient en multipliant sa longueur par sa largeur, et l'aire d'un carré en multipliant son côté par lui-même. Les deux dimensions doivent être exprimées dans la même unité, et le résultat s'exprime dans l'unité carrée correspondante.",
  attention: "Ne confondez pas les deux formules du rectangle : l'aire est un produit, le périmètre une somme doublée. Pour 8 cm sur 5 cm, l'aire vaut 40 cm² et le périmètre 26 cm.",
  astuce: "Les deux dimensions doivent partager la même unité. Pour un rectangle de 2 m sur 50 cm, convertissez d'abord en 2 m sur 0,5 m.",
  app: [
    { c: "Calcule l'aire :\n1. d'un rectangle de 8 cm sur 5 cm\n2. d'un carré de 6 cm de côté\n3. d'un rectangle de 12,5 cm sur 4 cm\n4. d'un carré de 4,5 cm de côté",
      r: "1. [[40 cm²]]\n2. [[36 cm²]]\n3. [[50 cm²]]\n4. [[20,25 cm²]]" },
    { c: "Un terrain rectangulaire mesure 45 m sur 30 m.\n1. Quelle est son aire ?\n2. Quel est son périmètre ?\n3. Quelles unités emploies-tu ?\n4. Pourquoi diffèrent-elles ?",
      r: "1. [[1 350 m²]]\n2. [[150 m]]\n3. Le [[m²]] et le [[m]]\n4. Car l'une mesure une [[surface]], l'autre une [[longueur]]" },
  ],
  evalx: [
    { c: "Calcule l'aire :\n1. d'un carré de 9 cm\n2. d'un rectangle de 15 m sur 6 m\n3. d'un carré de 2,5 m\n4. d'un rectangle de 7,5 cm sur 4 cm",
      r: "1. [[81 cm²]]\n2. [[90 m²]]\n3. [[6,25 m²]]\n4. [[30 cm²]]" },
    { c: "Un rectangle a une aire de 60 cm² et une longueur de 12 cm.\n1. Quelle opération donne la largeur ?\n2. Combien vaut-elle ?\n3. Un carré a une aire de 49 cm² : quel est son côté ?\n4. Explique ta démarche.",
      r: "1. Une [[division]]\n2. [[5 cm]]\n3. [[7 cm]]\n4. On cherche le nombre qui, [[multiplié par lui-même]], donne 49" },
  ],
  lecon: [
    ["1. L'aire du rectangle", "Un rectangle de 8 carreaux de long sur 5 de large est recouvert de 5 rangées de 8 carreaux, soit 40 carreaux.\nD'où la formule :\nAire du rectangle = {{Longueur × largeur}}.\nPour 8 cm sur 5 cm : 8 × 5 = 40 cm²."],
    ["2. L'aire du carré", "Le carré étant un rectangle dont les côtés sont égaux :\nAire du carré = {{côté × côté}}.\nPour un carré de 6 cm : 6 × 6 = 36 cm²."],
    ["3. Attention aux unités", "Les deux dimensions doivent être exprimées dans la {{même unité}}.\nPour un rectangle de 2 m sur 50 cm, on écrit 2 m sur 0,5 m, d'où une aire de 1 m².\nLe résultat s'exprime dans l'unité {{carrée}} correspondante."],
    ["4. Retrouver une dimension", "Les formules se lisent dans les deux sens.\nSi un rectangle a une aire de 60 cm² et une longueur de 12 cm, sa largeur vaut 60 ÷ 12 = 5 cm.\nSi un carré a une aire de 49 cm², son côté vaut 7 cm, car 7 × 7 = 49."],
  ],
  exos: [
    { pts: 4, c: "Calcule l'aire d'un rectangle de 8 cm sur 5 cm et celle d'un carré de 6 cm de côté.",
      r: "[[40 cm²]] et [[36 cm²]]." },
    { pts: 4, c: "Un terrain rectangulaire mesure 45 m sur 30 m. Quelle est son aire ?",
      r: "45 × 30 = [[1 350 m²]]." },
    { pts: 4, c: "Un rectangle a une aire de 60 cm² et une longueur de 12 cm. Quelle est sa largeur ?",
      r: "60 ÷ 12 = [[5 cm]]." },
    { pts: 4, c: "Un carré a une aire de 49 cm². Quel est son côté, et quel est son périmètre ?",
      r: "Côté : [[7 cm]], car 7 × 7 = 49. Périmètre : [[28 cm]]." },
    { pts: 4, c: "Calcule l'aire d'un carré de 4,5 cm de côté et celle d'un rectangle de 12,5 cm sur 4 cm.",
      r: "[[20,25 cm²]] et [[50 cm²]]." },
  ],
},
{
  ch: "Aires",
  titre: "Aire du triangle et du disque",
  objectif: "À la fin de la séance, l'élève est capable de calculer l'aire d'un triangle et celle d'un disque.",
  materiel: "Papier quadrillé, ciseaux, compas, règle",
  rev: [["Quelle est l'aire d'un rectangle de 8 sur 5 ?", "40 cm²."],
        ["Quelle est la circonférence d'un cercle de rayon 3 cm ?", "18,84 cm."],
        ["Calcule 3,14 × 9.", "28,26."]],
  mise: { q: "Un rectangle coupé le long de sa diagonale donne deux triangles. Que peut-on dire de leur aire ?", ra: "Chacun a la moitié de l'aire du rectangle." },
  obs: "Observez la manipulation : un rectangle de 8 cm sur 5 cm est découpé le long d'une diagonale. Les deux triangles obtenus se superposent exactement.",
  ana: [
    ["Quelle est l'aire du rectangle de départ ?", "Quarante centimètres carrés."],
    ["Les deux triangles sont-ils identiques ?", "Oui, ils se superposent."],
    ["Quelle est donc l'aire de chacun ?", "Vingt centimètres carrés."],
    ["Quelle formule en déduire ?", "Base fois hauteur divisé par deux."],
    ["Qu'appelle-t-on la hauteur d'un triangle ?", "La distance du sommet à la base, perpendiculairement."],
    ["Quelle formule pour l'aire du disque ?", "Pi fois le rayon multiplié par lui-même."],
    ["Que vaut l'aire d'un disque de rayon 3 cm ?", "28,26 centimètres carrés."],
  ],
  syn: "Donc, l'aire d'un triangle est égale au produit de sa base par sa hauteur, divisé par deux. L'aire d'un disque est égale à pi multiplié par le rayon puis encore par le rayon, en prenant pi environ égal à 3,14. La hauteur d'un triangle est toujours perpendiculaire à la base.",
  attention: "Ne confondez pas la hauteur d'un triangle avec l'un de ses côtés obliques. La hauteur est perpendiculaire à la base : c'est cette perpendiculaire, et non le côté, qui entre dans la formule.",
  astuce: "Pour le disque, ne confondez pas l'aire et la circonférence : la circonférence emploie le rayon une seule fois, l'aire l'emploie deux fois.",
  app: [
    { c: "Calcule l'aire :\n1. d'un triangle de base 8 cm et de hauteur 5 cm\n2. d'un triangle de base 12 cm et de hauteur 7 cm\n3. d'un disque de rayon 3 cm\n4. d'un disque de rayon 10 cm",
      r: "1. [[20 cm²]]\n2. [[42 cm²]]\n3. [[28,26 cm²]]\n4. [[314 cm²]]" },
    { c: "Un disque a un diamètre de 8 cm.\n1. Quel est son rayon ?\n2. Quelle est son aire ?\n3. Quelle est sa circonférence ?\n4. Quelles unités emploies-tu ?",
      r: "1. [[4 cm]]\n2. [[50,24 cm²]]\n3. [[25,12 cm]]\n4. Le [[cm²]] pour l'aire, le [[cm]] pour la circonférence" },
  ],
  evalx: [
    { c: "Calcule l'aire :\n1. d'un triangle de base 6,4 cm et de hauteur 2,5 cm\n2. d'un triangle de base 10 cm et de hauteur 4 cm\n3. d'un disque de rayon 5 cm\n4. d'un disque de rayon 2 cm",
      r: "1. [[8 cm²]]\n2. [[20 cm²]]\n3. [[78,5 cm²]]\n4. [[12,56 cm²]]" },
    { c: "Complète :\n1. L'aire du triangle est le produit de la base par la ……, divisé par ……\n2. La hauteur est …… à la base.\n3. L'aire du disque emploie le rayon …… fois.\n4. La valeur de π est environ ……",
      r: "1. [[hauteur]] ; [[deux]]\n2. [[perpendiculaire]]\n3. [[deux]]\n4. [[3,14]]" },
  ],
  lecon: [
    ["1. L'aire du triangle", "Un rectangle coupé le long de sa {{diagonale}} donne deux triangles identiques. L'aire de chacun vaut donc la {{moitié}} de celle du rectangle.\nAire du triangle = ({{base × hauteur}}) ÷ 2.\nPour une base de 8 cm et une hauteur de 5 cm : (8 × 5) ÷ 2 = 20 cm²."],
    ["2. La hauteur d'un triangle", "La {{hauteur}} relative à une base est la distance qui sépare le sommet opposé de cette base, mesurée {{perpendiculairement}}.\nElle se trace à l'équerre et ne se confond pas avec un côté oblique."],
    ["3. L'aire du disque", "Aire du disque = {{π × rayon × rayon}}, avec π environ égal à 3,14.\nPour un rayon de 3 cm : 3,14 × 3 × 3 = 28,26 cm².\nSi l'on connaît le diamètre, on calcule d'abord le rayon en le divisant par 2."],
    ["4. Aire et circonférence", "La {{circonférence}} mesure le tour du cercle et s'exprime en cm ; l'{{aire}} mesure la surface du disque et s'exprime en cm².\nPour un rayon de 4 cm : circonférence 25,12 cm, aire 50,24 cm²."],
  ],
  exos: [
    { pts: 4, c: "Calcule l'aire d'un triangle de base 12 cm et de hauteur 7 cm.",
      r: "(12 × 7) ÷ 2 = [[42 cm²]]." },
    { pts: 4, c: "Calcule l'aire d'un disque de rayon 3 cm, puis celle d'un disque de rayon 10 cm.",
      r: "[[28,26 cm²]] et [[314 cm²]]." },
    { pts: 4, c: "Un disque a 8 cm de diamètre. Calcule son aire.",
      r: "Rayon : 4 cm. Aire : 3,14 × 4 × 4 = [[50,24 cm²]]." },
    { pts: 4, c: "Un triangle a une base de 6,4 cm et une hauteur de 2,5 cm. Quelle est son aire ?",
      r: "(6,4 × 2,5) ÷ 2 = [[8 cm²]]." },
    { pts: 4, c: "Vrai ou faux ? 1. La hauteur d'un triangle est un côté oblique. 2. L'aire du triangle se divise par deux. 3. L'aire du disque emploie le rayon deux fois. 4. π vaut environ 3,14.",
      r: "1. [[Faux]] : elle est perpendiculaire à la base. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Aires",
  titre: "Les unités d'aire et leurs conversions",
  objectif: "À la fin de la séance, l'élève est capable de convertir une aire d'une unité à une autre et d'employer l'are et l'hectare.",
  materiel: "Tableau de conversion des aires, ardoises, cahier",
  rev: [["Quelle est l'aire d'un carré de 1 m de côté ?", "1 m²."],
        ["Convertis 1 m en centimètres.", "100 cm."],
        ["Calcule 100 × 100.", "10 000."]],
  mise: { q: "Combien de carrés d'un décimètre de côté faut-il pour couvrir un carré d'un mètre de côté ?", ra: "Cent." },
  obs: "Observez au tableau un carré d'un mètre de côté, quadrillé en carrés d'un décimètre. On y compte dix rangées de dix carrés.",
  ana: [
    ["Combien de carrés par rangée ?", "Dix."],
    ["Combien de rangées ?", "Dix."],
    ["Combien de carrés au total ?", "Cent."],
    ["Que vaut donc 1 m² en dm² ?", "Cent décimètres carrés."],
    ["Et en centimètres carrés ?", "Dix mille."],
    ["Chaque unité vaut combien de fois la suivante ?", "Cent fois."],
    ["Combien de mètres carrés dans un hectare ?", "Dix mille."],
  ],
  syn: "Donc, chaque unité d'aire vaut cent fois celle qui la suit immédiatement, et non dix comme pour les longueurs. Un mètre carré vaut cent décimètres carrés et dix mille centimètres carrés. Pour les terrains, on emploie l'are, qui vaut cent mètres carrés, et l'hectare, qui en vaut dix mille.",
  attention: "Le rapport entre deux unités d'aire consécutives est de cent, non de dix. C'est l'erreur la plus fréquente : un mètre carré ne vaut pas dix décimètres carrés mais bien cent.",
  astuce: "Dans le tableau des aires, réservez deux colonnes par unité. Chaque déplacement d'une unité à la suivante fait alors bien franchir deux rangs.",
  app: [
    { c: "Convertis :\n1. 1 m² en dm²\n2. 1 m² en cm²\n3. 2,5 m² en dm²\n4. 45 000 cm² en m²",
      r: "1. [[100 dm²]]\n2. [[10 000 cm²]]\n3. [[250 dm²]]\n4. [[4,5 m²]]" },
    { c: "Convertis :\n1. 1 are en m²\n2. 1 hectare en m²\n3. 3 hectares en m²\n4. 500 m² en ares",
      r: "1. [[100 m²]]\n2. [[10 000 m²]]\n3. [[30 000 m²]]\n4. [[5 ares]]" },
  ],
  evalx: [
    { c: "Convertis :\n1. 3 m² en cm²\n2. 7 500 cm² en m²\n3. 2 ha en m²\n4. 800 m² en ares",
      r: "1. [[30 000 cm²]]\n2. [[0,75 m²]]\n3. [[20 000 m²]]\n4. [[8 ares]]" },
    { c: "Un terrain mesure 45 m sur 30 m.\n1. Quelle est son aire en m² ?\n2. En ares ?\n3. En hectares ?\n4. Quelle unité est la plus commode ici ?",
      r: "1. [[1 350 m²]]\n2. [[13,5 ares]]\n3. [[0,135 ha]]\n4. L'[[are]] ou le [[m²]]" },
  ],
  lecon: [
    ["1. Le rapport de cent", "Un carré d'un mètre de côté se découpe en {{10 × 10}} carrés d'un décimètre, soit 100.\nChaque unité d'aire vaut donc {{cent fois}} celle qui la suit, et non dix comme pour les longueurs."],
    ["2. Les principales égalités", "1 m² = 100 dm² = 10 000 cm².\n1 km² = 1 000 000 m².\nPour convertir des m² en cm², on multiplie par {{10 000}} ; pour l'inverse, on divise."],
    ["3. L'are et l'hectare", "Pour mesurer les terrains, on emploie deux unités particulières :\nl'{{are}}, qui vaut 100 m², c'est-à-dire l'aire d'un carré de 10 m de côté ;\nl'{{hectare}}, qui vaut 100 ares, soit {{10 000 m²}}."],
    ["4. En pratique", "Un terrain de 45 m sur 30 m a une aire de 1 350 m², soit 13,5 ares ou 0,135 hectare.\nOn choisit l'unité qui donne le nombre le plus {{lisible}} : les m² pour une maison, les ares pour un jardin, les hectares pour une plantation."],
  ],
  exos: [
    { pts: 4, c: "Convertis : 1 m² en dm², 1 m² en cm², 2,5 m² en dm².",
      r: "[[100 dm²]] ; [[10 000 cm²]] ; [[250 dm²]]." },
    { pts: 4, c: "Convertis 45 000 cm² en mètres carrés.",
      r: "45 000 ÷ 10 000 = [[4,5 m²]]." },
    { pts: 4, c: "Combien de mètres carrés valent 3 hectares ?",
      r: "3 × 10 000 = [[30 000 m²]]." },
    { pts: 4, c: "Un terrain de 45 m sur 30 m : donne son aire en m², puis en ares.",
      r: "[[1 350 m²]], soit [[13,5 ares]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 1 m² = 10 dm². 2. 1 hectare = 10 000 m². 3. 1 are = 100 m². 4. Chaque unité d'aire vaut cent fois la suivante.",
      r: "1. [[Faux]] : 100 dm². 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Aires",
  titre: "Problèmes d'aires",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème d'aire, y compris pour une figure composée.",
  materiel: "Énoncés au tableau, papier quadrillé, cahier de recherche",
  rev: [["Quelle est l'aire d'un carré de 3 m ?", "9 m²."],
        ["Convertis 1 m² en cm².", "10 000 cm²."],
        ["Quelle est l'aire d'un rectangle de 6 m sur 4,5 m ?", "27 m²."]],
  mise: { q: "Pour carreler une pièce, que doit-on calculer avant d'aller acheter les carreaux ?", ra: "L'aire de la pièce." },
  obs: "Lisez l'énoncé au tableau : « Une pièce rectangulaire mesure 6 m sur 4,5 m. On la carrelle avec des carreaux carrés de 30 cm de côté, vendus 4 500 ariary l'unité. »",
  ana: [
    ["Quelle est l'aire de la pièce ?", "Vingt-sept mètres carrés."],
    ["Quelle est l'aire d'un carreau ?", "900 centimètres carrés."],
    ["Combien cela fait-il en mètres carrés ?", "0,09 mètre carré."],
    ["Comment trouver le nombre de carreaux ?", "En divisant l'aire de la pièce par celle d'un carreau."],
    ["Combien en faut-il ?", "Trois cents."],
    ["Quel est le coût total ?", "1 350 000 ariary."],
    ["Que faire si le quotient ne tombe pas juste ?", "Arrondir au nombre entier supérieur."],
    ["Comment vérifier ?", "Par un ordre de grandeur."],
  ],
  syn: "Donc, un problème d'aire se résout en calculant d'abord la surface concernée, puis en la comparant à l'unité de couverture ou au prix au mètre carré. Les unités doivent être harmonisées avant tout calcul, et le nombre d'éléments s'arrondit toujours au supérieur.",
  attention: "Une figure composée se décompose en figures simples dont on additionne les aires. Si une partie est retirée, comme un bassin dans un jardin, on soustrait au lieu d'ajouter.",
  app: [
    { c: "Une pièce de 6 m sur 4,5 m est carrelée avec des carreaux de 30 cm de côté à 4 500 ariary l'unité.\n1. Quelle est l'aire de la pièce ?\n2. Quelle est l'aire d'un carreau en m² ?\n3. Combien de carreaux faut-il ?\n4. Quel est le coût ?",
      r: "1. [[27 m²]]\n2. [[0,09 m²]]\n3. [[300 carreaux]]\n4. [[1 350 000 ariary]]" },
    { c: "Une figure est formée d'un rectangle de 8 m sur 5 m et d'un carré de 3 m de côté accolé.\n1. Aire du rectangle ?\n2. Aire du carré ?\n3. Aire totale ?\n4. Quelle opération as-tu faite ?",
      r: "1. [[40 m²]]\n2. [[9 m²]]\n3. [[49 m²]]\n4. Une [[addition]] des deux aires" },
  ],
  evalx: [
    { c: "Un jardin rectangulaire de 20 m sur 15 m contient un bassin carré de 4 m de côté.\n1. Aire du jardin ?\n2. Aire du bassin ?\n3. Aire cultivable ?\n4. Quelle opération ?",
      r: "1. [[300 m²]]\n2. [[16 m²]]\n3. [[284 m²]]\n4. Une [[soustraction]]" },
    { c: "Un mur de 5 m sur 2,8 m doit être peint. Un litre de peinture couvre 7 m².\n1. Quelle est l'aire du mur ?\n2. Combien de litres faut-il ?\n3. Pourquoi arrondir ?\n4. Quel coût à 25 000 ariary le litre ?",
      r: "1. [[14 m²]]\n2. [[2 litres]]\n3. Pour [[couvrir toute la surface]]\n4. [[50 000 ariary]]" },
  ],
  lecon: [
    ["1. La démarche", "On identifie la {{figure}}, on choisit la formule, on vérifie les {{unités}}, puis on enchaîne les calculs.\nUne pièce de 6 m sur 4,5 m a une aire de 27 m²."],
    ["2. Compter des éléments", "Pour savoir combien de carreaux couvrent une surface, on {{divise}} l'aire totale par l'aire d'un carreau.\nUn carreau de 30 cm de côté a une aire de 900 cm², soit 0,09 m².\n27 ÷ 0,09 = 300 carreaux."],
    ["3. Les figures composées", "Une figure composée se {{décompose}} en figures simples.\nUn rectangle de 8 m sur 5 m accolé à un carré de 3 m de côté a une aire de 40 + 9 = 49 m².\nSi une partie est {{retirée}}, comme un bassin, on soustrait son aire."],
    ["4. Interpréter", "Le nombre d'éléments à acheter s'{{arrondit au supérieur}} : 2 litres de peinture pour 14 m² si un litre couvre 7 m², mais 3 litres s'il en fallait 2,1.\nOn termine par une {{phrase réponse}} avec l'unité."],
  ],
  exos: [
    { pts: 4, c: "Une pièce mesure 6 m sur 4,5 m. Quelle est son aire ?",
      r: "6 × 4,5 = [[27 m²]]." },
    { pts: 4, c: "On la carrelle avec des carreaux de 30 cm de côté. Combien en faut-il ?",
      r: "Un carreau : 0,09 m². 27 ÷ 0,09 = [[300 carreaux]]." },
    { pts: 4, c: "Un jardin de 20 m sur 15 m contient un bassin carré de 4 m de côté. Quelle est l'aire cultivable ?",
      r: "300 − 16 = [[284 m²]]." },
    { pts: 4, c: "Une figure est formée d'un rectangle de 8 m sur 5 m et d'un carré de 3 m accolé. Quelle est son aire totale ?",
      r: "40 + 9 = [[49 m²]]." },
    { pts: 4, c: "Un mur de 5 m sur 2,8 m est peint avec une peinture couvrant 7 m² par litre. Combien de litres faut-il ?",
      r: "Aire : 14 m². 14 ÷ 7 = [[2 litres]]." },
  ],
},

{
  ch: "Angles",
  titre: "Reconnaître et nommer les angles",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître un angle droit, aigu, obtus, plat ou nul, et de le nommer correctement.",
  materiel: "Équerre, règle, figures au tableau, ardoises",
  rev: [["Que code un petit carré sur une figure ?", "Un angle droit."],
        ["Quel instrument vérifie un angle droit ?", "L'équerre."],
        ["Que signifie le symbole ⊥ ?", "Perpendiculaire."]],
  mise: { q: "Les aiguilles d'une horloge forment-elles toujours le même angle ?", ra: "Non, l'écartement change à chaque instant." },
  obs: "Observez au tableau cinq figures : deux demi-droites confondues, un angle plus fermé que l'équerre, un angle coïncidant avec l'équerre, un angle plus ouvert, et deux demi-droites formant une droite.",
  ana: [
    ["Qu'est-ce qui forme un angle ?", "Deux demi-droites de même origine."],
    ["Comment nomme-t-on cette origine ?", "Le sommet de l'angle."],
    ["Que mesure un angle ?", "L'ouverture entre les deux demi-droites."],
    ["Comment nommer l'angle qui coïncide avec l'équerre ?", "Un angle droit."],
    ["Et celui qui est plus fermé ?", "Un angle aigu."],
    ["Celui qui est plus ouvert ?", "Un angle obtus."],
    ["Et deux demi-droites formant une droite ?", "Un angle plat."],
    ["Comment note-t-on un angle de sommet B ?", "Par les trois lettres A, B et C, le sommet au milieu."],
  ],
  syn: "Donc, un angle est formé par deux demi-droites de même origine, appelée sommet, et mesure leur ouverture. Un angle aigu est plus fermé qu'un angle droit, un angle obtus est plus ouvert, un angle plat correspond à une droite, et un angle nul à deux demi-droites confondues.",
  attention: "La longueur des demi-droites tracées ne change rien à l'angle. Deux angles peuvent avoir la même ouverture bien que l'un soit dessiné avec des traits beaucoup plus longs.",
  astuce: "L'équerre suffit à classer un angle : s'il est plus fermé que l'angle droit, il est aigu ; s'il est plus ouvert, il est obtus.",
  app: [
    { c: "Nomme l'angle :\n1. plus fermé que l'angle droit\n2. égal à l'angle droit\n3. plus ouvert que l'angle droit\n4. formé par une droite entière",
      r: "1. [[Aigu]]\n2. [[Droit]]\n3. [[Obtus]]\n4. [[Plat]]" },
    { c: "Réponds :\n1. Qu'est-ce que le sommet d'un angle ?\n2. Que mesure un angle ?\n3. La longueur des traits change-t-elle l'angle ?\n4. Comment note-t-on un angle de sommet B ?",
      r: "1. L'[[origine commune]] des deux demi-droites\n2. Son [[ouverture]]\n3. [[Non]]\n4. Par [[trois lettres]], le sommet au milieu" },
  ],
  evalx: [
    { c: "Classe ces angles :\n1. l'angle d'un coin de feuille\n2. l'angle formé par les aiguilles à trois heures\n3. un angle très fermé\n4. un angle très ouvert sans être plat",
      r: "1. [[Droit]]\n2. [[Droit]]\n3. [[Aigu]]\n4. [[Obtus]]" },
    { c: "Complète :\n1. Un angle est formé de deux ……\n2. Leur origine commune est le ……\n3. Un angle plat correspond à une ……\n4. Un angle nul a ses deux demi-droites ……",
      r: "1. [[demi-droites]]\n2. [[sommet]]\n3. [[droite]]\n4. [[confondues]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'un angle", "Un {{angle}} est la figure formée par deux {{demi-droites}} de même origine.\nCette origine commune s'appelle le {{sommet}} de l'angle, et les deux demi-droites en sont les {{côtés}}.\nUn angle mesure l'{{ouverture}} entre ces deux côtés."],
    ["2. Nommer un angle", "On désigne un angle par {{trois lettres}}, celle du sommet étant placée au {{milieu}}.\nL'angle de sommet B dont les côtés passent par A et C se note ABC."],
    ["3. Les différents angles", "L'angle {{droit}} est celui de l'équerre et du coin d'une feuille.\nL'angle {{aigu}} est plus fermé qu'un angle droit.\nL'angle {{obtus}} est plus ouvert qu'un angle droit sans être plat.\nL'angle {{plat}} correspond à une droite entière, et l'angle {{nul}} à deux demi-droites confondues."],
    ["4. Ce qui ne compte pas", "La {{longueur}} des traits tracés n'intervient pas dans la mesure d'un angle : seule compte l'{{ouverture}}.\nOn peut donc prolonger ou raccourcir les côtés sans modifier l'angle."],
  ],
  exos: [
    { pts: 4, c: "Nomme les quatre sortes d'angles étudiées, du plus fermé au plus ouvert.",
      r: "[[Nul]], [[aigu]], [[droit]], [[obtus]], puis [[plat]]." },
    { pts: 4, c: "Qu'est-ce que le sommet d'un angle et comment note-t-on un angle ?",
      r: "Le sommet est l'[[origine commune]] des deux demi-droites. On note l'angle par [[trois lettres]], le sommet au milieu." },
    { pts: 4, c: "Comment classer un angle à l'aide d'une équerre ?",
      r: "S'il est plus [[fermé]] que l'angle droit, il est aigu ; s'il est plus [[ouvert]], il est obtus ; s'il coïncide, il est droit." },
    { pts: 4, c: "Deux angles ont la même ouverture mais des côtés de longueurs différentes. Sont-ils égaux ?",
      r: "[[Oui]] : la [[longueur des côtés]] n'intervient pas dans la mesure d'un angle." },
    { pts: 4, c: "Vrai ou faux ? 1. Un angle plat est une droite. 2. Un angle obtus est plus fermé qu'un angle droit. 3. Le sommet est l'origine commune. 4. La longueur des côtés change l'angle.",
      r: "1. [[Vrai]]. 2. [[Faux]] : il est plus ouvert. 3. [[Vrai]]. 4. [[Faux]]." },
  ],
},
{
  ch: "Angles",
  titre: "Mesurer un angle avec le rapporteur",
  objectif: "À la fin de la séance, l'élève est capable de mesurer un angle en degrés à l'aide d'un rapporteur.",
  materiel: "Rapporteur, règle, angles tracés, ardoises",
  rev: [["Comment nomme-t-on un angle plus fermé que l'angle droit ?", "Aigu."],
        ["Qu'est-ce que le sommet d'un angle ?", "L'origine commune des deux demi-droites."],
        ["Que vaut la moitié de 180 ?", "90."]],
  mise: { q: "L'équerre dit si un angle est aigu ou obtus, mais comment connaître exactement son ouverture ?", ra: "Avec un rapporteur, en degrés." },
  obs: "Observez le rapporteur au tableau : il porte deux graduations allant de 0 à 180, un centre marqué et une ligne de base. L'enseignant y place un angle et lit 55.",
  ana: [
    ["Quelle est l'unité de mesure des angles ?", "Le degré."],
    ["Où place-t-on le centre du rapporteur ?", "Sur le sommet de l'angle."],
    ["Sur quoi aligne-t-on la ligne de base ?", "Sur un côté de l'angle."],
    ["Où lit-on la mesure ?", "Là où le second côté croise la graduation."],
    ["Pourquoi deux séries de nombres ?", "Pour pouvoir mesurer dans les deux sens."],
    ["Laquelle choisir ?", "Celle qui commence à zéro sur le premier côté."],
    ["Combien mesure un angle droit ?", "Quatre-vingt-dix degrés."],
    ["Et un angle plat ?", "Cent quatre-vingts degrés."],
  ],
  syn: "Donc, on mesure un angle en degrés à l'aide d'un rapporteur. On place son centre sur le sommet, on aligne la ligne de base sur un côté, puis on lit la graduation traversée par le second côté, en choisissant la série qui commence à zéro. Un angle droit mesure quatre-vingt-dix degrés et un angle plat cent quatre-vingts.",
  attention: "Le rapporteur porte deux séries de graduations. Choisissez toujours celle dont le zéro se trouve sur le côté que vous avez aligné, sinon vous lirez le complément à cent quatre-vingts.",
  astuce: "Avant de lire, estimez : un angle visiblement aigu doit donner un nombre inférieur à quatre-vingt-dix. Si vous lisez cent trente, c'est que vous avez pris la mauvaise graduation.",
  app: [
    { c: "Complète :\n1. L'unité de mesure des angles est le ……\n2. On place le centre du rapporteur sur le ……\n3. Un angle droit mesure ……\n4. Un angle plat mesure ……",
      r: "1. [[degré]]\n2. [[sommet]]\n3. [[90 degrés]]\n4. [[180 degrés]]" },
    { c: "Classe ces angles d'après leur mesure :\n1. 35 degrés\n2. 90 degrés\n3. 120 degrés\n4. 180 degrés",
      r: "1. [[Aigu]]\n2. [[Droit]]\n3. [[Obtus]]\n4. [[Plat]]" },
  ],
  evalx: [
    { c: "Un angle mesure 62 degrés.\n1. Est-il aigu ou obtus ?\n2. Combien lui manque-t-il pour un angle droit ?\n3. Combien pour un angle plat ?\n4. Justifie tes calculs.",
      r: "1. [[Aigu]]\n2. [[28 degrés]]\n3. [[118 degrés]]\n4. Par [[soustraction]] à 90 puis à 180" },
    { c: "Quelle est la mesure de l'angle ?\n1. le quart d'un tour complet\n2. le tiers d'un tour complet\n3. la moitié d'un angle plat\n4. un tour complet",
      r: "1. [[90 degrés]]\n2. [[120 degrés]]\n3. [[90 degrés]]\n4. [[360 degrés]]" },
  ],
  lecon: [
    ["1. Le degré", "L'unité de mesure des angles est le {{degré}}.\nUn tour complet vaut {{360}} degrés, un angle plat {{180}} degrés et un angle droit {{90}} degrés."],
    ["2. Utiliser le rapporteur", "Le {{rapporteur}} porte un centre, une ligne de base et deux séries de graduations.\nPour mesurer un angle :\n— placer le {{centre}} sur le sommet ;\n— aligner la {{ligne de base}} sur l'un des côtés ;\n— lire la graduation traversée par l'autre côté."],
    ["3. Choisir la bonne graduation", "Les deux séries permettent de mesurer dans les deux sens. On retient celle dont le {{zéro}} se trouve sur le côté aligné.\nUne estimation préalable évite l'erreur : un angle aigu donne moins de 90 degrés, un angle obtus davantage."],
    ["4. Classer par la mesure", "Un angle {{nul}} mesure 0 degré, un angle {{aigu}} entre 0 et 90, un angle {{droit}} exactement 90, un angle {{obtus}} entre 90 et 180, un angle {{plat}} exactement 180."],
  ],
  exos: [
    { pts: 4, c: "Quelle est la mesure d'un angle droit, d'un angle plat et d'un tour complet ?",
      r: "[[90 degrés]] ; [[180 degrés]] ; [[360 degrés]]." },
    { pts: 4, c: "Classe ces angles : 35°, 90°, 120°, 180°.",
      r: "[[Aigu]] ; [[droit]] ; [[obtus]] ; [[plat]]." },
    { pts: 4, c: "Décris les trois étapes de la mesure d'un angle au rapporteur.",
      r: "Placer le [[centre]] sur le sommet ; aligner la [[ligne de base]] sur un côté ; lire la [[graduation]] traversée par l'autre côté." },
    { pts: 4, c: "Un angle mesure 62°. Combien lui manque-t-il pour former un angle droit ?",
      r: "90 − 62 = [[28 degrés]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Un tour complet vaut 180°. 2. Un angle obtus dépasse 90°. 3. On place le centre du rapporteur sur un côté. 4. Le degré est l'unité des angles.",
      r: "1. [[Faux]] : 360°. 2. [[Vrai]]. 3. [[Faux]] : sur le sommet. 4. [[Vrai]]." },
  ],
},
{
  ch: "Angles",
  titre: "Construire un angle de mesure donnée",
  objectif: "À la fin de la séance, l'élève est capable de construire un angle de mesure donnée au rapporteur.",
  materiel: "Rapporteur, règle graduée, cahier de géométrie",
  rev: [["Combien mesure un angle droit ?", "90 degrés."],
        ["Où place-t-on le centre du rapporteur ?", "Sur le sommet."],
        ["Un angle de 120 degrés est-il aigu ou obtus ?", "Obtus."]],
  mise: { q: "Comment tracer un angle de exactement 55 degrés, sans en connaître aucun modèle ?", ra: "Avec un rapporteur, en marquant la graduation." },
  obs: "Observez la construction : l'enseignant trace une demi-droite d'origine A, y pose le rapporteur, marque un point à la graduation 55, puis joint A à ce point.",
  ana: [
    ["Que trace-t-on d'abord ?", "Une demi-droite qui servira de côté."],
    ["Où place-t-on le rapporteur ?", "Le centre sur l'origine A."],
    ["Sur quoi aligne-t-on la base ?", "Sur la demi-droite tracée."],
    ["Que fait-on ensuite ?", "On marque un point à la graduation voulue."],
    ["Comment achever la construction ?", "En joignant A au point marqué."],
    ["Comment vérifier son tracé ?", "En mesurant l'angle obtenu."],
    ["Quel angle se construit sans rapporteur ?", "L'angle droit, avec l'équerre."],
  ],
  syn: "Donc, pour construire un angle de mesure donnée, on trace une demi-droite, on place le centre du rapporteur sur son origine et sa base sur cette demi-droite, on marque un point à la graduation voulue, puis on joint l'origine à ce point. On vérifie ensuite en mesurant l'angle obtenu.",
  attention: "Marquez le point du côté correspondant à la graduation choisie. Un point placé de l'autre côté produit l'angle supplémentaire au lieu de l'angle demandé.",
  astuce: "L'angle droit se construit plus vite à l'équerre qu'au rapporteur ; réservez le rapporteur aux mesures qui ne sont pas des multiples simples.",
  app: [
    { c: "Construis un angle de 55 degrés.\n1. Que traces-tu d'abord ?\n2. Où places-tu le centre ?\n3. Où marques-tu le point ?\n4. Comment termines-tu ?",
      r: "1. Une [[demi-droite]]\n2. Sur son [[origine]]\n3. À la graduation [[55]]\n4. En [[joignant]] l'origine au point marqué" },
    { c: "Quel instrument choisis-tu pour construire :\n1. un angle de 90 degrés\n2. un angle de 47 degrés\n3. un angle de 135 degrés\n4. un angle plat",
      r: "1. L'[[équerre]]\n2. Le [[rapporteur]]\n3. Le [[rapporteur]]\n4. La [[règle]] seule, c'est une droite" },
  ],
  evalx: [
    { c: "On veut construire un triangle dont un angle mesure 40 degrés et un autre 70 degrés.\n1. Quelle est la somme de ces deux angles ?\n2. Que vaut le troisième ?\n3. Quelle propriété as-tu utilisée ?\n4. Le triangle est-il rectangle ?",
      r: "1. [[110 degrés]]\n2. [[70 degrés]]\n3. La somme des angles d'un triangle vaut [[180 degrés]]\n4. [[Non]]" },
    { c: "Complète :\n1. On trace d'abord une ……\n2. Le centre du rapporteur va sur l'……\n3. On marque un point à la ……\n4. On vérifie en …… l'angle obtenu.",
      r: "1. [[demi-droite]]\n2. [[origine]]\n3. [[graduation voulue]]\n4. [[mesurant]]" },
  ],
  lecon: [
    ["1. La méthode", "Pour construire un angle de mesure donnée :\n— tracer une {{demi-droite}} d'origine A, qui sera le premier côté ;\n— poser le {{centre}} du rapporteur sur A et sa base sur cette demi-droite ;\n— repérer la {{graduation}} voulue et y marquer un point ;\n— tracer la demi-droite joignant A à ce point."],
    ["2. Choisir la bonne graduation", "Le rapporteur portant deux séries de nombres, on marque le point du côté où le {{zéro}} coïncide avec la demi-droite tracée.\nDans le cas contraire, on obtiendrait l'angle {{supplémentaire}}."],
    ["3. Vérifier", "Une fois l'angle tracé, on le {{mesure}} à nouveau pour contrôler la construction.\nOn peut aussi l'estimer : un angle de 55 degrés doit apparaître nettement plus {{fermé}} qu'un angle droit."],
    ["4. Les angles remarquables", "L'angle {{droit}} se construit plus commodément à l'{{équerre}}.\nL'angle {{plat}} ne demande qu'une règle, puisqu'il s'agit d'une droite.\nLe rapporteur reste indispensable pour toutes les autres mesures."],
  ],
  exos: [
    { pts: 4, c: "Décris la construction d'un angle de 55 degrés.",
      r: "Tracer une [[demi-droite]], poser le [[centre]] du rapporteur sur son origine, marquer un point à [[55]], puis joindre." },
    { pts: 4, c: "Quel instrument emploies-tu pour un angle de 90 degrés et pour un angle de 47 degrés ?",
      r: "L'[[équerre]] pour 90 degrés ; le [[rapporteur]] pour 47 degrés." },
    { pts: 4, c: "Pourquoi faut-il choisir la graduation dont le zéro est sur le côté tracé ?",
      r: "Sinon on obtient l'angle [[supplémentaire]], c'est-à-dire le [[complément à 180 degrés]]." },
    { pts: 4, c: "Un triangle a deux angles de 40 et 70 degrés. Que vaut le troisième ?",
      r: "180 − 40 − 70 = [[70 degrés]]." },
    { pts: 4, c: "Vrai ou faux ? 1. On commence par tracer une demi-droite. 2. Le centre va sur le sommet. 3. On ne peut pas vérifier son tracé. 4. L'équerre suffit pour un angle de 47 degrés.",
      r: "1. [[Vrai]]. 2. [[Vrai]]. 3. [[Faux]] : on remesure. 4. [[Faux]]." },
  ],
},
{
  ch: "Angles",
  titre: "Angles particuliers et somme des angles",
  objectif: "À la fin de la séance, l'élève est capable d'utiliser la somme des angles d'un triangle et de calculer un angle complémentaire ou supplémentaire.",
  materiel: "Rapporteur, triangles découpés, ciseaux, ardoises",
  rev: [["Combien mesure un angle plat ?", "180 degrés."],
        ["Calcule 180 − 120.", "60."],
        ["Calcule 90 − 35.", "55."]],
  mise: { q: "Les trois angles d'un triangle découpés puis mis bout à bout : quelle figure forment-ils ?", ra: "Un angle plat." },
  obs: "Observez la manipulation : les trois coins d'un triangle en papier sont découpés puis assemblés par leurs sommets. Ils forment exactement une droite.",
  ana: [
    ["Quelle figure forment les trois angles réunis ?", "Une droite, donc un angle plat."],
    ["Combien mesure un angle plat ?", "Cent quatre-vingts degrés."],
    ["Que vaut donc la somme des angles d'un triangle ?", "Cent quatre-vingts degrés."],
    ["Si deux angles valent 50 et 60, que vaut le troisième ?", "Soixante-dix degrés."],
    ["Dans un triangle équilatéral, que vaut chaque angle ?", "Soixante degrés."],
    ["Comment nomme-t-on deux angles dont la somme vaut 90 ?", "Des angles complémentaires."],
    ["Et deux angles dont la somme vaut 180 ?", "Des angles supplémentaires."],
  ],
  syn: "Donc, la somme des trois angles d'un triangle vaut toujours cent quatre-vingts degrés, quelle que soit sa forme. Deux angles sont complémentaires si leur somme vaut quatre-vingt-dix degrés, et supplémentaires si elle vaut cent quatre-vingts. Chaque angle d'un triangle équilatéral mesure soixante degrés.",
  attention: "Un triangle ne peut pas comporter deux angles droits : leur somme atteindrait déjà cent quatre-vingts degrés, sans place pour le troisième.",
  astuce: "Dans un triangle isocèle, les deux angles à la base sont égaux : connaître l'angle au sommet suffit à calculer les deux autres.",
  app: [
    { c: "Calcule le troisième angle :\n1. 50 et 60 degrés\n2. 90 et 35 degrés\n3. 45 et 45 degrés\n4. 100 et 30 degrés",
      r: "1. [[70 degrés]]\n2. [[55 degrés]]\n3. [[90 degrés]]\n4. [[50 degrés]]" },
    { c: "Calcule :\n1. le complémentaire de 35 degrés\n2. le complémentaire de 62 degrés\n3. le supplémentaire de 120 degrés\n4. le supplémentaire de 45 degrés",
      r: "1. [[55 degrés]]\n2. [[28 degrés]]\n3. [[60 degrés]]\n4. [[135 degrés]]" },
  ],
  evalx: [
    { c: "Un triangle isocèle a un angle au sommet de 40 degrés.\n1. Que sait-on des deux autres angles ?\n2. Quelle est leur somme ?\n3. Combien mesure chacun ?\n4. Quelle propriété as-tu utilisée ?",
      r: "1. Ils sont [[égaux]]\n2. [[140 degrés]]\n3. [[70 degrés]]\n4. La somme des angles vaut [[180 degrés]]" },
    { c: "Vrai ou faux ?\n1. Un triangle peut avoir deux angles droits.\n2. Chaque angle d'un triangle équilatéral vaut 60 degrés.\n3. Deux angles complémentaires font 180 degrés.\n4. La somme des angles d'un triangle vaut toujours 180 degrés.",
      r: "1. [[Faux]]\n2. [[Vrai]]\n3. [[Faux]], ils font 90 degrés\n4. [[Vrai]]" },
  ],
  lecon: [
    ["1. La somme des angles d'un triangle", "En découpant les trois coins d'un triangle et en les assemblant, on obtient un angle {{plat}}.\nLa somme des trois angles d'un triangle vaut donc toujours {{180 degrés}}, quelle que soit sa forme."],
    ["2. Calculer un angle manquant", "Connaissant deux angles, on obtient le troisième par {{soustraction}}.\nPour 50 et 60 degrés : 180 − 50 − 60 = 70 degrés."],
    ["3. Les triangles particuliers", "Dans un triangle {{équilatéral}}, les trois angles sont égaux : chacun mesure 180 ÷ 3 = {{60 degrés}}.\nDans un triangle {{isocèle}}, les deux angles à la base sont égaux. Si l'angle au sommet vaut 40 degrés, chacun des deux autres vaut (180 − 40) ÷ 2 = 70 degrés.\nUn triangle {{rectangle}} possède un angle de 90 degrés ; les deux autres, réunis, en font également 90."],
    ["4. Angles complémentaires et supplémentaires", "Deux angles sont {{complémentaires}} lorsque leur somme vaut 90 degrés : 35 et 55 degrés.\nIls sont {{supplémentaires}} lorsque leur somme vaut 180 degrés : 120 et 60 degrés."],
  ],
  exos: [
    { pts: 4, c: "Un triangle a deux angles de 50 et 60 degrés. Que vaut le troisième ?",
      r: "180 − 50 − 60 = [[70 degrés]]." },
    { pts: 4, c: "Combien mesure chaque angle d'un triangle équilatéral ? Justifie.",
      r: "[[60 degrés]], car les trois angles sont égaux et 180 ÷ 3 = 60." },
    { pts: 4, c: "Calcule le complémentaire de 35 degrés et le supplémentaire de 120 degrés.",
      r: "[[55 degrés]] et [[60 degrés]]." },
    { pts: 4, c: "Un triangle isocèle a un angle au sommet de 40 degrés. Combien mesurent les angles à la base ?",
      r: "(180 − 40) ÷ 2 = [[70 degrés]] chacun." },
    { pts: 4, c: "Pourquoi un triangle ne peut-il pas avoir deux angles droits ?",
      r: "Parce que leur somme ferait déjà [[180 degrés]], ne laissant [[aucune place]] au troisième angle." },
  ],
},
{
  ch: "Organisation de données",
  titre: "Lire et construire un tableau de données",
  objectif: "À la fin de la séance, l'élève est capable de lire un tableau à double entrée et d'y organiser des données.",
  materiel: "Tableaux au tableau noir, relevés chiffrés, ardoises",
  rev: [["Calcule 12 + 8 + 15 + 5.", "40."],
        ["Que signifie un effectif ?", "Un nombre d'individus."],
        ["Calcule 40 − 12.", "28."]],
  mise: { q: "Une liste de cent résultats en désordre est-elle facile à exploiter ?", ra: "Non, il faut l'organiser." },
  obs: "Observez le tableau au tableau noir : quatre moyens de transport en première ligne — marche, taxi-brousse, vélo, voiture — et les effectifs correspondants en seconde ligne : 12, 8, 15 et 5.",
  ana: [
    ["Que contient la première ligne ?", "Les catégories étudiées."],
    ["Que contient la seconde ?", "Les effectifs correspondants."],
    ["Combien d'élèves viennent à vélo ?", "Quinze."],
    ["Quel est le total des élèves ?", "Quarante."],
    ["Quel moyen est le plus utilisé ?", "Le vélo."],
    ["Quel est le moins utilisé ?", "La voiture."],
    ["À quoi sert d'organiser ainsi les données ?", "À les lire et à les comparer rapidement."],
  ],
  syn: "Donc, un tableau organise des données en associant à chaque catégorie son effectif, c'est-à-dire le nombre d'individus concernés. Le total des effectifs donne l'effectif total. Cette présentation permet de comparer les catégories d'un seul coup d'œil.",
  attention: "Un tableau doit porter un titre et le nom de chaque ligne ou colonne. Des nombres présentés sans indication de ce qu'ils désignent ne veulent rien dire.",
  astuce: "Vérifiez toujours que la somme des effectifs correspond bien à l'effectif total annoncé : c'est le contrôle le plus simple d'une erreur de relevé.",
  app: [
    { c: "Le tableau indique : marche 12, taxi-brousse 8, vélo 15, voiture 5.\n1. Quel est l'effectif total ?\n2. Quel moyen est le plus utilisé ?\n3. Le moins utilisé ?\n4. Combien viennent autrement qu'à pied ?",
      r: "1. [[40]]\n2. Le [[vélo]]\n3. La [[voiture]]\n4. [[28]]" },
    { c: "Réponds :\n1. Que désigne un effectif ?\n2. Que donne la somme des effectifs ?\n3. Que doit porter tout tableau ?\n4. Pourquoi organiser les données ?",
      r: "1. Un [[nombre d'individus]] d'une catégorie\n2. L'[[effectif total]]\n3. Un [[titre]] et le nom des lignes\n4. Pour les [[comparer]] rapidement" },
  ],
  evalx: [
    { c: "Une enquête donne : riz 18, manioc 12, maïs 6, patate 4.\n1. Effectif total ?\n2. Aliment le plus cité ?\n3. Combien citent le manioc ou le maïs ?\n4. Combien ne citent pas le riz ?",
      r: "1. [[40]]\n2. Le [[riz]]\n3. [[18]]\n4. [[22]]" },
    { c: "Complète :\n1. La ligne des catégories indique ce que l'on ……\n2. L'effectif est un ……\n3. La somme des effectifs donne l'……\n4. Un tableau doit porter un ……",
      r: "1. [[étudie]]\n2. [[nombre]]\n3. [[effectif total]]\n4. [[titre]]" },
  ],
  lecon: [
    ["1. Pourquoi organiser les données", "Un relevé brut, présenté en désordre, est difficile à exploiter.\nOn le range donc dans un {{tableau}}, qui permet de lire et de comparer les résultats d'un seul coup d'œil."],
    ["2. Catégories et effectifs", "La première ligne du tableau donne les {{catégories}} étudiées : les moyens de transport, les aliments, les matières préférées.\nLa seconde donne l'{{effectif}} de chacune, c'est-à-dire le nombre d'individus concernés."],
    ["3. L'effectif total", "La somme de tous les effectifs donne l'{{effectif total}} de l'enquête.\nPour 12, 8, 15 et 5 élèves : 12 + 8 + 15 + 5 = 40 élèves interrogés.\nCette addition sert aussi de {{vérification}}."],
    ["4. Présenter correctement", "Tout tableau doit porter un {{titre}} indiquant ce qu'il représente, ainsi que le nom de chaque ligne ou colonne.\nDes nombres isolés, sans légende, ne signifient rien."],
  ],
  exos: [
    { pts: 4, c: "Un tableau donne : marche 12, taxi-brousse 8, vélo 15, voiture 5. Quel est l'effectif total ?",
      r: "12 + 8 + 15 + 5 = [[40 élèves]]." },
    { pts: 4, c: "Dans ce tableau, quel moyen de transport est le plus utilisé et quel est le moins utilisé ?",
      r: "Le plus utilisé : le [[vélo]] (15). Le moins utilisé : la [[voiture]] (5)." },
    { pts: 4, c: "Combien d'élèves ne viennent pas à pied ?",
      r: "40 − 12 = [[28 élèves]]." },
    { pts: 4, c: "Que doit obligatoirement comporter un tableau de données ?",
      r: "Un [[titre]] et le [[nom]] de chaque ligne ou colonne, sans quoi les nombres n'ont pas de sens." },
    { pts: 4, c: "Vrai ou faux ? 1. L'effectif est un nombre d'individus. 2. La somme des effectifs donne l'effectif total. 3. Un tableau n'a pas besoin de titre. 4. Un tableau facilite la comparaison.",
      r: "1. [[Vrai]]. 2. [[Vrai]]. 3. [[Faux]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Organisation de données",
  titre: "Le diagramme en bâtons",
  objectif: "À la fin de la séance, l'élève est capable de lire et de construire un diagramme en bâtons à partir d'un tableau.",
  materiel: "Papier quadrillé, règle, crayons de couleur",
  rev: [["Que donne la somme des effectifs ?", "L'effectif total."],
        ["Quel est l'effectif total de 12, 8, 15 et 5 ?", "40."],
        ["Quelle catégorie a l'effectif 15 ?", "Celle qui a le plus grand nombre ici."]],
  mise: { q: "Peut-on voir immédiatement, sur un tableau de nombres, quelle catégorie l'emporte ?", ra: "Pas aussi vite que sur un dessin." },
  obs: "Observez au tableau le diagramme construit à partir du tableau précédent : quatre bâtons de hauteurs 12, 8, 15 et 5, tracés sur un axe gradué de deux en deux.",
  ana: [
    ["Que représente chaque bâton ?", "Une catégorie."],
    ["Que représente sa hauteur ?", "L'effectif de cette catégorie."],
    ["Quel bâton est le plus haut ?", "Celui du vélo."],
    ["Pourquoi les bâtons ont-ils la même largeur ?", "Pour que seule la hauteur soit comparée."],
    ["Que porte l'axe vertical ?", "Les effectifs, avec une graduation régulière."],
    ["Que porte l'axe horizontal ?", "Les catégories."],
    ["Quel est l'avantage du diagramme ?", "Il rend la comparaison immédiate."],
  ],
  syn: "Donc, un diagramme en bâtons représente chaque catégorie par un bâton dont la hauteur est proportionnelle à son effectif. Tous les bâtons ont la même largeur et le même écartement, et l'axe des effectifs porte une graduation régulière. Le diagramme rend la comparaison immédiate.",
  attention: "La graduation de l'axe vertical doit être régulière et commencer à zéro. Une graduation irrégulière fausse complètement la comparaison des hauteurs.",
  astuce: "Choisissez l'échelle en fonction du plus grand effectif : pour un maximum de 15, une graduation de deux en deux tient sur une hauteur raisonnable.",
  app: [
    { c: "À partir du tableau marche 12, taxi-brousse 8, vélo 15, voiture 5 :\n1. Combien de bâtons ?\n2. Quelle est la hauteur du plus grand ?\n3. Du plus petit ?\n4. Que porte l'axe vertical ?",
      r: "1. [[Quatre]]\n2. [[15]]\n3. [[5]]\n4. Les [[effectifs]]" },
    { c: "Réponds :\n1. Que représente la hauteur d'un bâton ?\n2. Pourquoi la même largeur pour tous ?\n3. Où commence la graduation ?\n4. Quel est l'intérêt du diagramme ?",
      r: "1. L'[[effectif]] de la catégorie\n2. Pour ne comparer que les [[hauteurs]]\n3. À [[zéro]]\n4. Rendre la comparaison [[immédiate]]" },
  ],
  evalx: [
    { c: "Un diagramme montre les ventes : lundi 20, mardi 35, mercredi 15, jeudi 30.\n1. Quel jour la vente est-elle la plus forte ?\n2. La plus faible ?\n3. Quel est le total ?\n4. Quelle est la différence entre le maximum et le minimum ?",
      r: "1. [[Mardi]]\n2. [[Mercredi]]\n3. [[100]]\n4. [[20]]" },
    { c: "Complète :\n1. Les bâtons ont tous la même ……\n2. Leur hauteur représente l'……\n3. La graduation doit être ……\n4. L'axe horizontal porte les ……",
      r: "1. [[largeur]]\n2. [[effectif]]\n3. [[régulière]]\n4. [[catégories]]" },
  ],
  lecon: [
    ["1. Le principe", "Un {{diagramme en bâtons}} traduit un tableau en image.\nChaque catégorie y est représentée par un {{bâton}} vertical dont la {{hauteur}} correspond à son effectif."],
    ["2. Construire le diagramme", "On trace deux axes : l'axe {{horizontal}} porte les catégories, l'axe {{vertical}} les effectifs.\nOn choisit une {{graduation}} régulière adaptée au plus grand effectif, puis on trace chaque bâton à la hauteur voulue."],
    ["3. Les règles à respecter", "Tous les bâtons ont la même {{largeur}} et le même écartement, afin que seule leur hauteur soit comparée.\nLa graduation commence à {{zéro}} et progresse régulièrement, faute de quoi la comparaison serait faussée."],
    ["4. Lire un diagramme", "La lecture est immédiate : le bâton le plus {{haut}} désigne la catégorie la plus représentée, le plus bas la moins représentée.\nOn peut aussi calculer des différences ou un total à partir des hauteurs lues."],
  ],
  exos: [
    { pts: 4, c: "Que représente la hauteur d'un bâton dans un diagramme en bâtons ?",
      r: "Elle représente l'[[effectif]] de la catégorie correspondante." },
    { pts: 4, c: "Pourquoi tous les bâtons doivent-ils avoir la même largeur ?",
      r: "Pour que seule la [[hauteur]] intervienne dans la comparaison des effectifs." },
    { pts: 4, c: "Un diagramme donne : lundi 20, mardi 35, mercredi 15, jeudi 30. Quel est le total des ventes ?",
      r: "20 + 35 + 15 + 30 = [[100]]." },
    { pts: 4, c: "Quelle est la différence entre le jour le plus fort et le jour le plus faible ?",
      r: "35 − 15 = [[20]]." },
    { pts: 4, c: "Vrai ou faux ? 1. La graduation peut être irrégulière. 2. L'axe vertical porte les effectifs. 3. Le bâton le plus haut est la catégorie la plus représentée. 4. La graduation commence à zéro.",
      r: "1. [[Faux]]. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Organisation de données",
  titre: "Fréquences et diagramme circulaire",
  objectif: "À la fin de la séance, l'élève est capable de calculer une fréquence en pourcentage et de déterminer l'angle d'un secteur circulaire.",
  materiel: "Compas, rapporteur, ardoises, données chiffrées",
  rev: [["Calcule 12 ÷ 40 × 100.", "30."],
        ["Combien de degrés dans un tour complet ?", "360."],
        ["Calcule 30 % de 360.", "108."]],
  mise: { q: "Comment représenter des parts d'un ensemble sur un disque ?", ra: "En partageant le disque en secteurs proportionnels." },
  obs: "Observez au tableau les données : sur 40 élèves, 12 viennent à pied, 8 en taxi-brousse, 15 à vélo et 5 en voiture, avec les pourcentages calculés en dessous.",
  ana: [
    ["Quelle part représentent les 12 élèves à pied ?", "Douze quarantièmes."],
    ["Quel pourcentage cela fait-il ?", "Trente pour cent."],
    ["Comment nomme-t-on cette part ?", "La fréquence."],
    ["Que vaut la fréquence du taxi-brousse ?", "Vingt pour cent."],
    ["Quelle est la somme de toutes les fréquences ?", "Cent pour cent."],
    ["À quoi correspond le disque entier ?", "À trois cent soixante degrés."],
    ["Quel angle pour trente pour cent ?", "Cent huit degrés."],
    ["Comment l'a-t-on obtenu ?", "En multipliant 360 par 30 et en divisant par 100."],
  ],
  syn: "Donc, la fréquence d'une catégorie est la part qu'elle représente dans l'ensemble, exprimée en pourcentage. On l'obtient en divisant l'effectif par l'effectif total puis en multipliant par cent. Dans un diagramme circulaire, chaque secteur reçoit un angle proportionnel à sa fréquence, le disque entier valant trois cent soixante degrés.",
  attention: "La somme des fréquences doit toujours valoir cent pour cent, et celle des angles trois cent soixante degrés. Si ce n'est pas le cas, un calcul est faux.",
  astuce: "Un quart de l'effectif correspond à un secteur de quatre-vingt-dix degrés, la moitié à cent quatre-vingts : ces repères permettent de contrôler le tracé.",
  app: [
    { c: "Sur 40 élèves : 12 à pied, 8 en taxi-brousse, 15 à vélo, 5 en voiture.\n1. Fréquence de la marche ?\n2. Fréquence du taxi-brousse ?\n3. Quelle est la somme des fréquences ?\n4. Quel angle pour la marche ?",
      r: "1. [[30 %]]\n2. [[20 %]]\n3. [[100 %]]\n4. [[108 degrés]]" },
    { c: "Calcule l'angle du secteur :\n1. pour 25 %\n2. pour 50 %\n3. pour 10 %\n4. pour 100 %",
      r: "1. [[90 degrés]]\n2. [[180 degrés]]\n3. [[36 degrés]]\n4. [[360 degrés]]" },
  ],
  evalx: [
    { c: "Sur 200 personnes, 50 préfèrent le riz.\n1. Quelle est la fréquence ?\n2. Quel angle sur le diagramme ?\n3. Combien ne préfèrent pas le riz ?\n4. Quelle fréquence pour ces dernières ?",
      r: "1. [[25 %]]\n2. [[90 degrés]]\n3. [[150]]\n4. [[75 %]]" },
    { c: "Complète :\n1. La fréquence s'exprime en ……\n2. On divise l'effectif par l'……\n3. Le disque entier vaut …… degrés.\n4. La somme des fréquences vaut ……",
      r: "1. [[pourcentage]]\n2. [[effectif total]]\n3. [[360]]\n4. [[100 %]]" },
  ],
  lecon: [
    ["1. La fréquence", "La {{fréquence}} d'une catégorie est la part qu'elle représente dans l'ensemble étudié.\nOn l'obtient en {{divisant}} son effectif par l'effectif total, puis en multipliant par {{100}}.\n12 élèves sur 40 : 12 ÷ 40 × 100 = 30 %."],
    ["2. La somme des fréquences", "Toutes les fréquences réunies représentent l'ensemble : leur somme vaut donc {{100 %}}.\nCette vérification permet de repérer une erreur de calcul."],
    ["3. Le diagramme circulaire", "Un {{diagramme circulaire}} partage un disque en {{secteurs}} proportionnels aux effectifs.\nLe disque entier correspond à {{360 degrés}}, qui représentent la totalité, soit 100 %."],
    ["4. Calculer l'angle d'un secteur", "Pour une fréquence de p %, l'angle du secteur vaut {{360 × p ÷ 100}}.\nPour 30 % : 360 × 30 ÷ 100 = 108 degrés.\nQuelques repères utiles : 25 % donnent 90 degrés, 50 % donnent 180 degrés, 10 % donnent 36 degrés."],
  ],
  exos: [
    { pts: 4, c: "Sur 40 élèves, 12 viennent à pied. Quelle est la fréquence en pourcentage ?",
      r: "12 ÷ 40 × 100 = [[30 %]]." },
    { pts: 4, c: "Quel angle représente cette catégorie sur un diagramme circulaire ?",
      r: "360 × 30 ÷ 100 = [[108 degrés]]." },
    { pts: 4, c: "Calcule l'angle du secteur correspondant à 25 % puis à 50 %.",
      r: "[[90 degrés]] et [[180 degrés]]." },
    { pts: 4, c: "Sur 200 personnes, 50 préfèrent le riz. Donne la fréquence et l'angle du secteur.",
      r: "Fréquence : [[25 %]]. Angle : [[90 degrés]]." },
    { pts: 4, c: "Vrai ou faux ? 1. La somme des fréquences vaut 100 %. 2. Le disque entier vaut 180 degrés. 3. 10 % correspondent à 36 degrés. 4. La fréquence s'obtient par une division.",
      r: "1. [[Vrai]]. 2. [[Faux]] : 360 degrés. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Organisation de données",
  titre: "La moyenne d'une série",
  objectif: "À la fin de la séance, l'élève est capable de calculer la moyenne d'une série de nombres et d'en interpréter le résultat.",
  materiel: "Relevés de notes, ardoises, cahier",
  rev: [["Calcule 12 + 14 + 16 + 18.", "60."],
        ["Calcule 60 ÷ 4.", "15."],
        ["Que donne la somme des effectifs ?", "L'effectif total."]],
  mise: { q: "Quatre élèves obtiennent 12, 14, 16 et 18. Quelle note unique résumerait le mieux ces résultats ?", ra: "Quinze, leur moyenne." },
  obs: "Observez au tableau les quatre notes 12, 14, 16 et 18, leur somme égale à 60, et le quotient de cette somme par 4.",
  ana: [
    ["Quelle est la somme des quatre notes ?", "Soixante."],
    ["Combien y a-t-il de notes ?", "Quatre."],
    ["Quelle opération fait-on ensuite ?", "Une division par quatre."],
    ["Quel est le résultat ?", "Quinze."],
    ["Comment nomme-t-on ce nombre ?", "La moyenne."],
    ["La moyenne figure-t-elle parmi les notes ?", "Non, pas nécessairement."],
    ["Que représente-t-elle alors ?", "La note que chacun aurait si toutes étaient égales."],
    ["Comment nomme-t-on l'écart entre le maximum et le minimum ?", "L'étendue."],
  ],
  syn: "Donc, la moyenne d'une série de nombres s'obtient en additionnant tous les nombres puis en divisant la somme par leur quantité. Elle représente la valeur que prendrait chaque terme si tous étaient égaux. L'étendue, différence entre la plus grande et la plus petite valeur, complète cette information.",
  attention: "La moyenne ne fait pas toujours partie des valeurs de la série et ne résume pas tout : deux séries très différentes peuvent avoir la même moyenne.",
  astuce: "La moyenne est toujours comprise entre la plus petite et la plus grande valeur. Un résultat en dehors de cet intervalle signale une erreur de calcul.",
  app: [
    { c: "Calcule la moyenne :\n1. de 12, 14, 16 et 18\n2. de 8, 12, 10, 14 et 6\n3. de 20 et 10\n4. de 15, 15 et 15",
      r: "1. [[15]]\n2. [[10]]\n3. [[15]]\n4. [[15]]" },
    { c: "Une série est 6, 9, 12 et 18.\n1. Quelle est la somme ?\n2. Combien de termes ?\n3. Quelle est la moyenne ?\n4. Quelle est l'étendue ?",
      r: "1. [[45]]\n2. [[Quatre]]\n3. [[11,25]]\n4. [[12]]" },
  ],
  evalx: [
    { c: "Un élève a obtenu 12, 8, 14 et 10.\n1. Quelle est la somme ?\n2. Quelle est la moyenne ?\n3. Quelle est l'étendue ?\n4. La moyenne figure-t-elle parmi les notes ?",
      r: "1. [[44]]\n2. [[11]]\n3. [[6]]\n4. [[Non]]" },
    { c: "La moyenne de quatre notes est 15.\n1. Quelle est la somme des notes ?\n2. Si trois notes valent 12, 16 et 18, que vaut la quatrième ?\n3. Quelle opération as-tu faite ?\n4. Vérifie ton résultat.",
      r: "1. [[60]]\n2. [[14]]\n3. Une [[soustraction]] : 60 − 46\n4. [[12 + 16 + 18 + 14 = 60]], et 60 ÷ 4 = 15" },
  ],
  lecon: [
    ["1. Calculer une moyenne", "La {{moyenne}} d'une série de nombres s'obtient en {{additionnant}} tous les termes, puis en {{divisant}} la somme par leur nombre.\nPour 12, 14, 16 et 18 : la somme vaut 60, et 60 ÷ 4 = 15."],
    ["2. Ce que représente la moyenne", "La moyenne est la valeur que prendrait {{chaque}} terme si tous étaient {{égaux}}, la somme restant la même.\nElle ne figure pas nécessairement parmi les valeurs de la série."],
    ["3. Les limites de la moyenne", "Deux séries très différentes peuvent avoir la même moyenne : 15 et 15 d'une part, 10 et 20 d'autre part.\nLa moyenne ne renseigne donc pas sur la {{dispersion}} des valeurs."],
    ["4. L'étendue", "L'{{étendue}} d'une série est la différence entre la plus {{grande}} et la plus {{petite}} valeur.\nPour 6, 9, 12 et 18, elle vaut 18 − 6 = 12.\nMoyenne et étendue, ensemble, décrivent bien mieux une série."],
  ],
  exos: [
    { pts: 4, c: "Calcule la moyenne de 12, 14, 16 et 18.",
      r: "(12 + 14 + 16 + 18) ÷ 4 = 60 ÷ 4 = [[15]]." },
    { pts: 4, c: "Calcule la moyenne de 8, 12, 10, 14 et 6.",
      r: "50 ÷ 5 = [[10]]." },
    { pts: 4, c: "Une série est 6, 9, 12 et 18. Donne sa moyenne et son étendue.",
      r: "Moyenne : 45 ÷ 4 = [[11,25]]. Étendue : 18 − 6 = [[12]]." },
    { pts: 4, c: "La moyenne de quatre notes est 15 et trois d'entre elles valent 12, 16 et 18. Quelle est la quatrième ?",
      r: "Somme totale : 60. 60 − 46 = [[14]]." },
    { pts: 4, c: "Vrai ou faux ? 1. La moyenne fait toujours partie de la série. 2. Elle est comprise entre le minimum et le maximum. 3. L'étendue est une différence. 4. Deux séries différentes peuvent avoir la même moyenne.",
      r: "1. [[Faux]]. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},

];
