// Période I — 20 séances. Contenu entièrement rédigé pour la Collection J-Learn.
// Contexte malgache, séparateur décimal = virgule, aucune date calendaire.
// Champs : rev, mise, obs, ana[[Q,RA]], syn, app[], evalx[], lecon[], exos[]

const DOC = "Programme officiel de Mathématiques, classe de 6e — RAPS 6e";

module.exports = [
// ─────────────────────────────────────────── Ch. 1 — Les nombres entiers naturels
{
  ch: "Les nombres entiers naturels",
  titre: "Lire et écrire les nombres entiers naturels",
  objectif: "À la fin de la séance, l'élève est capable de lire et d'écrire correctement un nombre entier naturel jusqu'à la classe des millions, en chiffres et en lettres.",
  materiel: "Tableau de numération tracé au tableau, ardoises, étiquettes-chiffres",
  rev: [["Combien de chiffres utilise-t-on pour écrire tous les nombres ?", "Dix chiffres : 0, 1, 2, 3, 4, 5, 6, 7, 8 et 9."],
        ["Écris le nombre trois cent quarante-deux.", "342."],
        ["Quel est le chiffre des dizaines dans 87 ?", "Le chiffre 8."]],
  mise: { q: "Le recensement annonce que la population d'Antananarivo dépasse un million d'habitants. Comment écrit-on ce nombre en chiffres ?", ra: "1 000 000." },
  obs: "Regardez bien le tableau de numération affiché : il comporte les classes des millions, des mille et des unités, chacune divisée en centaines, dizaines et unités. Le nombre 3 254 108 y est placé, un chiffre par colonne.",
  ana: [
    ["Combien de classes voyez-vous dans ce tableau ?", "Trois classes : les millions, les mille et les unités simples."],
    ["Combien de colonnes contient chaque classe ?", "Trois colonnes : centaines, dizaines et unités."],
    ["Dans 3 254 108, quel chiffre occupe la colonne des millions ?", "Le chiffre 3."],
    ["Que représente le chiffre 5 dans ce nombre ?", "Il représente 5 dizaines de mille, c'est-à-dire 50 000."],
    ["Pourquoi laisse-t-on un espace entre les groupes de trois chiffres ?", "Pour séparer les classes et rendre le nombre plus facile à lire."],
    ["Comment lit-on ce nombre à voix haute ?", "Trois millions deux cent cinquante-quatre mille cent huit."],
  ],
  syn: "Donc, un nombre entier naturel s'écrit avec les dix chiffres, groupés par tranches de trois à partir de la droite. Chaque tranche forme une classe : unités, mille, millions. La position d'un chiffre indique sa valeur.",
  app: [
    { c: "Écris en chiffres les nombres suivants :\n1. Quatre-vingt-douze mille trois cents\n2. Sept millions cinq cent mille\n3. Deux cent six mille quatorze\n4. Un million un",
      r: "1. [[92 300]]\n2. [[7 500 000]]\n3. [[206 014]]\n4. [[1 000 001]]" },
    { c: "Dans le nombre 8 407 165, indique la valeur du chiffre demandé :\n1. le chiffre 8\n2. le chiffre 4\n3. le chiffre 7\n4. le chiffre 6",
      r: "1. [[8 millions]], soit 8 000 000\n2. [[4 centaines de mille]], soit 400 000\n3. [[7 unités de mille]], soit 7 000\n4. [[6 dizaines]], soit 60" },
  ],
  evalx: [
    { c: "Écris en lettres :\n1. 5 060\n2. 340 000\n3. 1 200 500\n4. 90 009",
      r: "1. [[Cinq mille soixante]]\n2. [[Trois cent quarante mille]]\n3. [[Un million deux cent mille cinq cents]]\n4. [[Quatre-vingt-dix mille neuf]]" },
    { c: "Recopie et complète par le mot qui convient (classe, chiffre, position) :\n1. Un nombre s'écrit à l'aide de dix ……\n2. La valeur d'un chiffre dépend de sa ……\n3. Les millions forment une ……\n4. On sépare les …… par un espace.",
      r: "1. [[chiffres]]\n2. [[position]]\n3. [[classe]]\n4. [[classes]]" },
  ],
  lecon: [
    ["1. Les dix chiffres", "Tout nombre entier naturel s'écrit à l'aide des dix {{chiffres}} : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9. Il ne faut pas confondre un {{chiffre}}, qui est un signe d'écriture, et un {{nombre}}, qui exprime une quantité. Ainsi 47 est un nombre écrit avec deux chiffres."],
    ["2. Le tableau de numération", "Les chiffres se rangent par {{classes}} de trois colonnes : la classe des unités, celle des mille, celle des millions. Dans chaque classe on trouve les centaines (C), les dizaines (D) et les unités (U).\nPour le nombre 3 254 108 : 3 est le chiffre des millions, 2 celui des centaines de mille, 5 celui des dizaines de mille, 4 celui des unités de mille, 1 celui des centaines, 0 celui des dizaines et 8 celui des unités."],
    ["3. La valeur de position", "La {{position}} d'un chiffre indique la quantité qu'il représente. Dans 3 254 108, le chiffre 5 ne vaut pas 5 mais 50 000, car il occupe la colonne des dizaines de mille. C'est ce que l'on appelle la {{valeur de position}}."],
    ["4. Lire et écrire", "On lit un nombre classe par classe, en partant de la gauche. On écrit un espace entre les classes, jamais un point ni une virgule : on écrit 1 250 000, et non 1.250.000.\nExemple : la commune de Toamasina compte 326 289 habitants ; on lit « trois cent vingt-six mille deux cent quatre-vingt-neuf »."],
  ],
  exos: [
    { pts: 4, c: "Écris en chiffres : quatre cent mille sept ; douze millions ; soixante-quinze mille quatre-vingts ; neuf cent neuf.",
      r: "[[400 007]] ; [[12 000 000]] ; [[75 080]] ; [[909]]." },
    { pts: 4, c: "Dans 6 703 480, donne la valeur du chiffre 7, puis celle du chiffre 3.",
      r: "Le chiffre 7 vaut [[700 000]] car il occupe la colonne des centaines de mille. Le chiffre 3 vaut [[3 000]] car il occupe celle des unités de mille." },
    { pts: 4, c: "Écris en lettres 2 040 600.",
      r: "[[Deux millions quarante mille six cents]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 45 est un chiffre. 2. Dans 508, le 0 ne sert à rien. 3. On sépare les classes par un espace. 4. Le chiffre des unités de 3 271 est 1.",
      r: "1. [[Faux]] : 45 est un nombre écrit avec deux chiffres. 2. [[Faux]] : le 0 marque l'absence de dizaines et maintient le 5 dans la colonne des centaines. 3. [[Vrai]]. 4. [[Vrai]]." },
    { pts: 4, c: "Range dans l'ordre croissant : 90 100 ; 9 100 ; 901 000 ; 91 000.",
      r: "[[9 100 < 90 100 < 91 000 < 901 000]]." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "Comparer et ranger les nombres entiers",
  objectif: "À la fin de la séance, l'élève est capable de comparer deux entiers naturels et de ranger une liste de nombres dans l'ordre croissant ou décroissant.",
  materiel: "Étiquettes portant des nombres, ardoises, tableau de numération",
  rev: [["Quelle est la valeur du chiffre 4 dans 34 800 ?", "4 000, car il occupe la colonne des unités de mille."],
        ["Écris en chiffres : deux cent mille dix.", "200 010."],
        ["Combien de classes compte 5 400 000 ?", "Trois : millions, mille et unités."]],
  mise: { q: "Deux communes déclarent 12 480 et 12 840 habitants. Laquelle est la plus peuplée ?", ra: "Celle de 12 840 habitants." },
  obs: "Observez ces deux nombres écrits l'un sous l'autre dans le tableau de numération, chiffre sous chiffre : 12 480 et 12 840.",
  ana: [
    ["Ces deux nombres ont-ils le même nombre de chiffres ?", "Oui, cinq chiffres chacun."],
    ["Par où commence-t-on alors la comparaison ?", "Par la gauche, c'est-à-dire par le chiffre le plus fort."],
    ["Les chiffres des dizaines de mille sont-ils différents ?", "Non, c'est 1 dans les deux nombres."],
    ["Et ceux des unités de mille ?", "Non plus, c'est 2 dans les deux cas."],
    ["Quel est le premier rang où les chiffres diffèrent ?", "Le rang des centaines : 4 pour le premier, 8 pour le second."],
    ["Quelle conclusion tire-t-on ?", "Comme 8 est plus grand que 4, on écrit 12 840 > 12 480."],
    ["Et si deux nombres n'ont pas le même nombre de chiffres ?", "Le plus grand est celui qui a le plus de chiffres."],
  ],
  syn: "Donc, pour comparer deux entiers, on compte d'abord les chiffres : celui qui en a le plus est le plus grand. À nombre de chiffres égal, on compare rang par rang en partant de la gauche, jusqu'au premier rang où les chiffres diffèrent.",
  app: [
    { c: "Complète par < ou > :\n1. 7 205 … 7 502\n2. 48 000 … 9 999\n3. 130 400 … 130 040\n4. 999 … 1 000",
      r: "1. 7 205 [[<]] 7 502\n2. 48 000 [[>]] 9 999\n3. 130 400 [[>]] 130 040\n4. 999 [[<]] 1 000" },
    { c: "Range dans l'ordre croissant : 5 060 ; 5 600 ; 5 006 ; 5 660.",
      r: "[[5 006 < 5 060 < 5 600 < 5 660]]" },
  ],
  evalx: [
    { c: "Range dans l'ordre décroissant : 87 090 ; 87 900 ; 8 790 ; 87 009.",
      r: "[[87 900 > 87 090 > 87 009 > 8 790]]" },
    { c: "Encadre chaque nombre entre deux centaines consécutives :\n1. 347\n2. 1 208\n3. 5 099\n4. 660",
      r: "1. [[300 < 347 < 400]]\n2. [[1 200 < 1 208 < 1 300]]\n3. [[5 000 < 5 099 < 5 100]]\n4. [[600 < 660 < 700]]" },
  ],
  lecon: [
    ["1. Comparer deux nombres", "{{Comparer}} deux nombres, c'est dire s'ils sont égaux, ou lequel est le plus grand. On utilise les signes {{<}} (« est inférieur à »), {{>}} (« est supérieur à ») et {{=}} (« est égal à »).\nLa pointe du signe est toujours tournée vers le plus petit nombre : 7 < 12 se lit « 7 est inférieur à 12 »."],
    ["2. La méthode", "a) On compare le nombre de chiffres : celui qui en a le plus est le plus grand. Ainsi 1 000 > 999.\nb) Si les deux nombres ont autant de chiffres, on compare rang par rang en partant de la gauche. Au premier rang où les chiffres diffèrent, le plus grand chiffre donne le plus grand nombre.\nExemple : 12 840 et 12 480 ont les mêmes chiffres de gauche jusqu'aux centaines, où 8 > 4 ; donc 12 840 > 12 480."],
    ["3. Ranger une liste", "{{Ranger}} des nombres dans l'ordre {{croissant}}, c'est les écrire du plus petit au plus grand. Dans l'ordre {{décroissant}}, c'est l'inverse.\nExemple croissant : 405 < 450 < 504 < 540."],
    ["4. Encadrer un nombre", "{{Encadrer}} un nombre, c'est trouver un nombre plus petit et un nombre plus grand que lui. Pour encadrer 3 472 entre deux milliers : 3 000 < 3 472 < 4 000."],
  ],
  exos: [
    { pts: 4, c: "Complète par < ou > : 6 090 … 6 900 ; 24 000 … 8 999 ; 501 … 510 ; 100 000 … 99 999.",
      r: "6 090 [[<]] 6 900 ; 24 000 [[>]] 8 999 ; 501 [[<]] 510 ; 100 000 [[>]] 99 999." },
    { pts: 4, c: "Range dans l'ordre croissant : 4 007 ; 4 700 ; 4 070 ; 4 077.",
      r: "[[4 007 < 4 070 < 4 077 < 4 700]]." },
    { pts: 4, c: "Range dans l'ordre décroissant : 32 100 ; 3 210 ; 321 000 ; 32 010.",
      r: "[[321 000 > 32 100 > 32 010 > 3 210]]." },
    { pts: 4, c: "Encadre 7 845 entre deux milliers consécutifs, puis entre deux centaines consécutives.",
      r: "[[7 000 < 7 845 < 8 000]] et [[7 800 < 7 845 < 7 900]]." },
    { pts: 4, c: "Écris le plus grand et le plus petit nombre de quatre chiffres différents que l'on peut former avec 3, 0, 7 et 5.",
      r: "Le plus grand est [[7 530]] ; le plus petit est [[3 057]] (un nombre ne peut pas commencer par 0)." },
  ],
},
{
  ch: "Les nombres entiers naturels",
  titre: "La demi-droite graduée et l'abscisse",
  objectif: "À la fin de la séance, l'élève est capable de placer un entier sur une demi-droite graduée et de lire l'abscisse d'un point.",
  materiel: "Règle graduée, double décimètre, demi-droite tracée au tableau",
  rev: [["Complète : 4 500 … 4 050.", "4 500 > 4 050."],
        ["Range dans l'ordre croissant : 12 ; 21 ; 2.", "2 < 12 < 21."],
        ["Quel est le plus petit entier naturel ?", "Zéro."]],
  mise: { q: "Sur la règle graduée de votre trousse, que représentent les petits traits régulièrement espacés ?", ra: "Les graduations, qui servent à mesurer." },
  obs: "Observez la droite tracée au tableau : elle part d'un point marqué O, porte des traits régulièrement espacés, et les points A et B y sont placés. Sous O est écrit 0, sous le trait suivant 1.",
  ana: [
    ["Quel nombre est écrit sous le point O ?", "Le nombre 0 ; on l'appelle l'origine."],
    ["Quelle distance sépare deux traits voisins ?", "Toujours la même : c'est l'unité de longueur."],
    ["Combien d'unités séparent O du point A ?", "Trois unités."],
    ["Quel nombre associe-t-on alors au point A ?", "Le nombre 3."],
    ["Comment appelle-t-on ce nombre ?", "L'abscisse du point A ; on écrit A(3)."],
    ["Deux points différents peuvent-ils avoir la même abscisse ?", "Non, chaque point de la droite a une seule abscisse."],
  ],
  syn: "Donc, graduer une demi-droite, c'est choisir une origine associée à 0 et une unité que l'on reporte régulièrement. Le nombre associé à un point s'appelle son abscisse et s'écrit entre parenthèses après le nom du point.",
  app: [
    { c: "Trace une demi-droite graduée d'origine O avec 1 cm pour unité, puis place les points A(2), B(5) et C(7).",
      r: "Après avoir reporté sept fois 1 cm : [[A est au 2e trait, B au 5e, C au 7e]]. Le point C est le plus éloigné de l'origine." },
    { c: "Sur une demi-droite graduée, un point M est situé 9 unités après l'origine. 1. Quelle est son abscisse ? 2. Écris-la correctement. 3. Quel point est plus proche de O : M ou N(4) ? 4. Combien d'unités séparent M de N ?",
      r: "1. [[9]]\n2. [[M(9)]]\n3. [[N(4)]]\n4. [[5 unités]], car 9 − 4 = 5." },
  ],
  evalx: [
    { c: "Lis les abscisses : sur une demi-droite d'unité 1, le point P est au 6e trait, Q au 11e, R au 0e, S au 15e.",
      r: "[[P(6)]], [[Q(11)]], [[R(0)]] qui est l'origine, [[S(15)]]." },
    { c: "Complète : 1. L'origine a pour abscisse …… 2. Le nombre associé à un point s'appelle son …… 3. Les graduations sont …… espacées. 4. Le point d'abscisse 8 est plus …… de l'origine que celui d'abscisse 3.",
      r: "1. [[0]]\n2. [[abscisse]]\n3. [[régulièrement]]\n4. [[éloigné]]" },
  ],
  lecon: [
    ["1. Graduer une demi-droite", "{{Graduer}} une demi-droite, c'est choisir sur elle un point appelé {{origine}}, auquel on associe le nombre 0, puis une {{unité}} de longueur que l'on reporte régulièrement à partir de cette origine."],
    ["2. L'abscisse d'un point", "À chaque graduation correspond un nombre entier. Le nombre associé à un point s'appelle son {{abscisse}}. On l'écrit entre parenthèses juste après le nom du point : A(3) se lit « A a pour abscisse 3 ».\nL'origine O a pour abscisse 0."],
    ["3. Lire et placer", "Pour lire l'abscisse d'un point, on compte le nombre d'unités qui le séparent de l'origine. Pour placer un point d'abscisse donnée, on reporte ce nombre d'unités à partir de l'origine.\nPlus l'abscisse est grande, plus le point est éloigné de l'origine : c'est pourquoi la demi-droite graduée permet aussi de comparer les nombres."],
    ["4. Une lecture utile", "La demi-droite graduée se retrouve partout : sur la règle de la trousse, sur le mètre-ruban du menuisier, sur la graduation d'un thermomètre. Dans chaque cas, l'origine et l'unité sont fixées d'avance."],
  ],
  exos: [
    { pts: 4, c: "Trace une demi-droite graduée d'unité 1 cm et place A(4), B(7) et C(10).",
      r: "On reporte 1 cm dix fois depuis O : [[A au 4e trait, B au 7e, C au 10e]]." },
    { pts: 4, c: "Un point D est placé 12 unités après l'origine. Écris son abscisse et compare-la à celle de E(12).",
      r: "[[D(12)]] ; D et E ont [[la même abscisse]], ils sont donc confondus." },
    { pts: 4, c: "Combien d'unités séparent les points d'abscisses 15 et 6 ?",
      r: "[[9 unités]], car 15 − 6 = 9." },
    { pts: 4, c: "Vrai ou faux ? 1. L'origine a pour abscisse 1. 2. Les graduations peuvent être inégales. 3. Un point d'abscisse 0 est l'origine. 4. L'abscisse s'écrit entre parenthèses.",
      r: "1. [[Faux]] : elle a pour abscisse 0. 2. [[Faux]] : elles sont régulièrement espacées. 3. [[Vrai]]. 4. [[Vrai]]." },
    { pts: 4, c: "Sur une demi-droite d'unité 2 cm, à quelle distance de l'origine se trouve le point d'abscisse 5 ?",
      r: "À [[10 cm]] de l'origine, car 5 × 2 cm = 10 cm." },
  ],
},
];
