// Période V — séances rédigées.
module.exports = [
{
  ch: "Pavé droit et cylindre",
  titre: "Découvrir les solides usuels",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître et de nommer les solides usuels du programme.",
  materiel: "Boîtes, briques, boîtes de conserve, ballons, solides en carton",
  rev: [["Combien de côtés a un rectangle ?", "Quatre."],
        ["Qu'est-ce qu'un carré ?", "Un quadrilatère à quatre côtés égaux et quatre angles droits."],
        ["Qu'est-ce qu'un disque ?", "La surface délimitée par un cercle."]],
  mise: { q: "Une boîte d'allumettes et une boîte de conserve occupent toutes deux de la place. Ont-elles la même forme ?", ra: "Non, l'une est un pavé, l'autre un cylindre." },
  obs: "Observez les objets disposés sur la table : une boîte d'allumettes, un dé, une boîte de conserve, un ballon. Chacun occupe un volume dans l'espace.",
  ana: [
    ["Ces objets sont-ils plats ?", "Non, ils occupent de la place dans l'espace."],
    ["Comment nomme-t-on de tels objets en géométrie ?", "Des solides."],
    ["Quelle est la forme de la boîte d'allumettes ?", "Un pavé droit."],
    ["Quelles sont ses faces ?", "Des rectangles."],
    ["Et celle du dé ?", "Un cube."],
    ["Qu'a-t-il de particulier ?", "Toutes ses faces sont des carrés égaux."],
    ["Quelle est la forme de la boîte de conserve ?", "Un cylindre."],
    ["Et celle du ballon ?", "Une sphère."],
  ],
  syn: "Donc, un solide est un objet qui occupe un volume dans l'espace. Le pavé droit a six faces rectangulaires ; le cube est un pavé dont toutes les faces sont des carrés égaux ; le cylindre possède deux bases circulaires ; la sphère est la forme du ballon.",
  attention: "Ne confondez pas les figures planes et les solides. Un carré est une figure plane, un cube est un solide ; un cercle est plan, une sphère est un solide.",
  astuce: "Pour reconnaître un solide, comptez ses faces et observez leur forme : six rectangles donnent un pavé, six carrés un cube, deux disques et une surface courbe un cylindre.",
  app: [
    { c: "Nomme le solide :\n1. une boîte d'allumettes\n2. un dé à jouer\n3. une boîte de conserve\n4. un ballon",
      r: "1. Un [[pavé droit]]\n2. Un [[cube]]\n3. Un [[cylindre]]\n4. Une [[sphère]]" },
    { c: "Figure plane ou solide ?\n1. un carré\n2. un cube\n3. un cercle\n4. un cylindre",
      r: "1. Figure [[plane]]\n2. [[Solide]]\n3. Figure [[plane]]\n4. [[Solide]]" },
  ],
  evalx: [
    { c: "Complète :\n1. Un solide occupe un …… dans l'espace.\n2. Les faces d'un pavé droit sont des ……\n3. Les faces d'un cube sont des ……\n4. Les bases d'un cylindre sont des ……",
      r: "1. [[volume]]\n2. [[rectangles]]\n3. [[carrés]]\n4. [[disques]]" },
    { c: "Cite un objet de la vie courante ayant la forme :\n1. d'un pavé droit\n2. d'un cube\n3. d'un cylindre\n4. d'une sphère",
      r: "1. Une [[brique]] ou un cahier\n2. Un [[dé]]\n3. Une [[boîte de conserve]]\n4. Un [[ballon]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'un solide", "Un {{solide}} est un objet qui occupe un {{volume}} dans l'espace, à la différence d'une figure plane qui se dessine entièrement sur une feuille.\nUn carré est une figure plane ; un cube est un solide."],
    ["2. Le pavé droit", "Le {{pavé droit}} est le solide le plus courant : boîte, brique, cahier, pièce d'habitation.\nIl possède {{six faces}} qui sont toutes des {{rectangles}}. Ses faces opposées sont identiques."],
    ["3. Le cube", "Le {{cube}} est un pavé droit particulier dont les six faces sont des {{carrés}} égaux.\nToutes ses arêtes ont la même longueur. Un dé à jouer en est l'exemple le plus familier."],
    ["4. Le cylindre et la sphère", "Le {{cylindre}} possède deux {{bases}} circulaires identiques reliées par une surface courbe : c'est la forme d'une boîte de conserve ou d'un tuyau.\nLa {{sphère}} est la forme du ballon : tous ses points sont à égale distance de son centre."],
  ],
  exos: [
    { pts: 4, c: "Nomme le solide correspondant : une boîte d'allumettes, un dé, une boîte de conserve, un ballon.",
      r: "[[Pavé droit]] ; [[cube]] ; [[cylindre]] ; [[sphère]]." },
    { pts: 4, c: "Quelle est la différence entre une figure plane et un solide ?",
      r: "Une figure [[plane]] se dessine entièrement sur une feuille ; un [[solide]] occupe un [[volume]] dans l'espace." },
    { pts: 4, c: "Décris les faces d'un pavé droit et celles d'un cube.",
      r: "Le pavé droit a six faces [[rectangulaires]] ; le cube a six faces [[carrées égales]]." },
    { pts: 4, c: "Décris le cylindre.",
      r: "Il possède deux [[bases circulaires]] identiques reliées par une [[surface courbe]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Un cube est un pavé droit particulier. 2. Un cercle est un solide. 3. Le cylindre a deux bases disques. 4. Les faces opposées d'un pavé sont identiques.",
      r: "1. [[Vrai]]. 2. [[Faux]] : c'est une figure plane. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Faces, arêtes et sommets du pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de dénombrer et de nommer les faces, arêtes et sommets d'un pavé droit.",
  materiel: "Pavés en carton, boîtes, règle, ardoises",
  rev: [["Combien de faces a un pavé droit ?", "Six."],
        ["De quelle forme sont ces faces ?", "Des rectangles."],
        ["Qu'est-ce qu'un cube ?", "Un pavé dont les faces sont des carrés égaux."]],
  mise: { q: "Combien de coups de crayon faut-il pour repasser toutes les arêtes d'une boîte ?", ra: "Douze." },
  obs: "Observez le pavé en carton que manipule l'enseignant : il compte à voix haute les faces, puis les segments qui les séparent, puis les coins.",
  ana: [
    ["Combien de faces compte-t-on ?", "Six."],
    ["Comment nomme-t-on les segments séparant deux faces ?", "Des arêtes."],
    ["Combien y en a-t-il ?", "Douze."],
    ["Comment nomme-t-on les coins ?", "Des sommets."],
    ["Combien y en a-t-il ?", "Huit."],
    ["Les faces opposées sont-elles identiques ?", "Oui, deux à deux."],
    ["Combien de dimensions décrivent un pavé ?", "Trois : longueur, largeur, hauteur."],
    ["Et pour un cube ?", "Une seule, car les trois sont égales."],
  ],
  syn: "Donc, un pavé droit possède six faces rectangulaires, douze arêtes et huit sommets. Ses faces opposées sont identiques deux à deux, et trois dimensions suffisent à le décrire : la longueur, la largeur et la hauteur. Dans un cube, ces trois dimensions sont égales.",
  attention: "Une arête n'est pas une face. L'arête est un segment, la face une surface : on compte douze arêtes mais seulement six faces.",
  astuce: "Les douze arêtes se répartissent en trois groupes de quatre, un par dimension. C'est pourquoi la somme des arêtes vaut quatre fois la somme des trois dimensions.",
  app: [
    { c: "Pour un pavé droit :\n1. Combien de faces ?\n2. Combien d'arêtes ?\n3. Combien de sommets ?\n4. Combien de dimensions le décrivent ?",
      r: "1. [[Six]]\n2. [[Douze]]\n3. [[Huit]]\n4. [[Trois]]" },
    { c: "Un pavé mesure 8 cm, 5 cm et 3 cm.\n1. Combien d'arêtes de 8 cm ?\n2. Combien de 5 cm ?\n3. Combien de 3 cm ?\n4. Quelle est la somme de toutes les arêtes ?",
      r: "1. [[Quatre]]\n2. [[Quatre]]\n3. [[Quatre]]\n4. 4 × (8 + 5 + 3) = [[64 cm]]" },
  ],
  evalx: [
    { c: "Un cube a 5 cm d'arête.\n1. Combien d'arêtes possède-t-il ?\n2. Quelle est la somme de leurs longueurs ?\n3. Quelle est l'aire d'une face ?\n4. Quelle est l'aire totale de ses faces ?",
      r: "1. [[Douze]]\n2. [[60 cm]]\n3. [[25 cm²]]\n4. [[150 cm²]]" },
    { c: "Complète :\n1. Un segment séparant deux faces est une ……\n2. Un coin est un ……\n3. Les faces opposées sont ……\n4. Dans un cube, les trois dimensions sont ……",
      r: "1. [[arête]]\n2. [[sommet]]\n3. [[identiques]]\n4. [[égales]]" },
  ],
  lecon: [
    ["1. Les faces", "Le pavé droit possède {{six faces}}, toutes rectangulaires.\nElles sont identiques {{deux à deux}} : la face du dessus est identique à celle du dessous, la face avant à la face arrière, la face gauche à la face droite."],
    ["2. Les arêtes", "Une {{arête}} est le segment le long duquel deux faces se rencontrent.\nUn pavé droit compte {{douze}} arêtes, réparties en trois groupes de quatre : quatre longueurs, quatre largeurs et quatre hauteurs."],
    ["3. Les sommets", "Un {{sommet}} est un coin du solide, point de rencontre de trois arêtes.\nUn pavé droit possède {{huit}} sommets."],
    ["4. Les dimensions", "Trois nombres suffisent à décrire un pavé droit : sa {{longueur}}, sa {{largeur}} et sa {{hauteur}}.\nLa somme de toutes ses arêtes vaut 4 × (Longueur + largeur + hauteur). Pour 8 cm, 5 cm et 3 cm : 4 × 16 = 64 cm.\nDans un {{cube}}, les trois dimensions sont égales."],
  ],
  exos: [
    { pts: 4, c: "Combien de faces, d'arêtes et de sommets possède un pavé droit ?",
      r: "[[6 faces]], [[12 arêtes]] et [[8 sommets]]." },
    { pts: 4, c: "Un pavé mesure 8 cm, 5 cm et 3 cm. Quelle est la somme des longueurs de toutes ses arêtes ?",
      r: "4 × (8 + 5 + 3) = 4 × 16 = [[64 cm]]." },
    { pts: 4, c: "Un cube a 5 cm d'arête. Quelle est la somme des longueurs de ses arêtes ?",
      r: "12 × 5 = [[60 cm]]." },
    { pts: 4, c: "Explique la différence entre une face, une arête et un sommet.",
      r: "La [[face]] est une surface, l'[[arête]] un segment séparant deux faces, le [[sommet]] un coin où se rencontrent trois arêtes." },
    { pts: 4, c: "Vrai ou faux ? 1. Un pavé a huit arêtes. 2. Ses faces opposées sont identiques. 3. Un cube a douze arêtes égales. 4. Trois dimensions décrivent un pavé.",
      r: "1. [[Faux]] : douze. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Le patron du pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de reconnaître et de tracer un patron de pavé droit ou de cube.",
  materiel: "Boîtes à découper, papier quadrillé, ciseaux, ruban adhésif",
  rev: [["Combien de faces a un pavé droit ?", "Six."],
        ["De quelle forme sont-elles ?", "Des rectangles."],
        ["Combien de faces a un cube ?", "Six carrés égaux."]],
  mise: { q: "Si l'on découpe une boîte le long de certaines arêtes et qu'on l'aplatit, qu'obtient-on ?", ra: "Une figure plane formée de six rectangles." },
  obs: "Observez la manipulation : l'enseignant découpe une boîte le long de sept arêtes, puis l'aplatit sur la table. Six rectangles apparaissent, reliés entre eux.",
  ana: [
    ["Combien de rectangles obtient-on ?", "Six."],
    ["Que représentent-ils ?", "Les six faces de la boîte."],
    ["Comment nomme-t-on cette figure à plat ?", "Le patron du solide."],
    ["Les six rectangles sont-ils quelconques ?", "Non, ils sont identiques deux à deux."],
    ["Peut-on les disposer n'importe comment ?", "Non, il faut pouvoir replier le patron."],
    ["Comment vérifier un patron ?", "En le découpant et en le pliant."],
    ["Combien de carrés dans le patron d'un cube ?", "Six carrés égaux."],
  ],
  syn: "Donc, le patron d'un solide est la figure plane obtenue en le dépliant. Le patron d'un pavé droit se compose de six rectangles identiques deux à deux, et celui d'un cube de six carrés égaux. Leur disposition doit permettre de replier la figure sans recouvrement ni manque.",
  attention: "Six rectangles convenables ne forment pas nécessairement un patron : la disposition compte autant que les dimensions. Deux faces qui se superposeraient au pliage rendent le patron faux.",
  astuce: "Avant de découper, vérifiez par la pensée le pliage face par face, ou marquez d'une même couleur les faces qui doivent se retrouver opposées.",
  app: [
    { c: "Un pavé mesure 6 cm, 4 cm et 3 cm.\n1. Combien de rectangles dans son patron ?\n2. Quelles dimensions pour deux d'entre eux ?\n3. Combien de rectangles de 6 sur 4 ?\n4. Et de 4 sur 3 ?",
      r: "1. [[Six]]\n2. [[6 cm sur 4 cm]], par exemple\n3. [[Deux]]\n4. [[Deux]]" },
    { c: "Réponds :\n1. Qu'est-ce qu'un patron ?\n2. Combien de carrés pour un cube ?\n3. Comment vérifier un patron ?\n4. Six rectangles suffisent-ils toujours ?",
      r: "1. La figure [[plane]] obtenue en dépliant le solide\n2. [[Six carrés égaux]]\n3. En le [[découpant et le pliant]]\n4. [[Non]], la disposition compte" },
  ],
  evalx: [
    { c: "Un cube a 4 cm d'arête.\n1. Quelle est l'aire d'une face ?\n2. Combien de faces ?\n3. Quelle est l'aire totale du patron ?\n4. Que représente cette aire ?",
      r: "1. [[16 cm²]]\n2. [[Six]]\n3. [[96 cm²]]\n4. La [[surface de carton]] nécessaire" },
    { c: "Complète :\n1. Un patron est une figure ……\n2. Il comporte autant de parties que le solide a de ……\n3. Le patron du cube comporte six ……\n4. On le vérifie en le ……",
      r: "1. [[plane]]\n2. [[faces]]\n3. [[carrés égaux]]\n4. [[pliant]]" },
  ],
  lecon: [
    ["1. Qu'est-ce qu'un patron", "Le {{patron}} d'un solide est la figure {{plane}} que l'on obtient en le dépliant, après l'avoir découpé le long de certaines arêtes.\nReplié, le patron reconstitue exactement le solide."],
    ["2. Le patron du pavé droit", "Il se compose de {{six rectangles}}, identiques {{deux à deux}}.\nPour un pavé de 6 cm sur 4 cm sur 3 cm, on trouve deux rectangles de 6 sur 4, deux de 6 sur 3 et deux de 4 sur 3."],
    ["3. Le patron du cube", "Il se compose de {{six carrés}} égaux.\nPlusieurs dispositions différentes conviennent, mais toutes ne sont pas valables : il faut pouvoir replier la figure sans {{recouvrement}} ni manque."],
    ["4. Vérifier et utiliser un patron", "La vérification la plus sûre consiste à {{découper}} le patron et à le {{plier}}.\nL'aire totale du patron donne la {{surface}} de carton nécessaire à la fabrication du solide : pour un cube de 4 cm d'arête, 6 × 16 = 96 cm²."],
  ],
  exos: [
    { pts: 4, c: "Qu'est-ce que le patron d'un solide ?",
      r: "C'est la figure [[plane]] obtenue en [[dépliant]] le solide, et qui permet de le reconstituer par pliage." },
    { pts: 4, c: "De combien de rectangles se compose le patron d'un pavé droit, et comment sont-ils appariés ?",
      r: "De [[six rectangles]], identiques [[deux à deux]]." },
    { pts: 4, c: "Un cube a 4 cm d'arête. Quelle est l'aire totale de son patron ?",
      r: "Une face : 16 cm². Six faces : [[96 cm²]]." },
    { pts: 4, c: "Un pavé mesure 6 cm sur 4 cm sur 3 cm. Quelle est l'aire totale de son patron ?",
      r: "2 × (24 + 18 + 12) = [[108 cm²]]." },
    { pts: 4, c: "Pourquoi six rectangles de bonnes dimensions ne forment-ils pas toujours un patron ?",
      r: "Parce que leur [[disposition]] doit permettre le pliage : deux faces qui se [[superposeraient]] rendent le patron faux." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Représenter un pavé en perspective",
  objectif: "À la fin de la séance, l'élève est capable de lire et de tracer la représentation en perspective d'un pavé droit.",
  materiel: "Papier quadrillé, règle, pavés en carton",
  rev: [["Combien d'arêtes a un pavé ?", "Douze."],
        ["Qu'est-ce qu'un patron ?", "La figure plane obtenue en dépliant le solide."],
        ["Que signifie le symbole // ?", "Parallèle."]],
  mise: { q: "Comment dessiner une boîte sur une feuille plate de façon qu'on la reconnaisse en trois dimensions ?", ra: "En la dessinant en perspective." },
  obs: "Observez le dessin au tableau : la face avant du pavé est un rectangle en trait plein, des segments obliques partent de ses sommets, et certaines arêtes du fond sont tracées en pointillés.",
  ana: [
    ["Comment est dessinée la face avant ?", "En vraie grandeur, en trait plein."],
    ["Que représentent les segments obliques ?", "Les arêtes qui s'éloignent vers le fond."],
    ["Sont-ils parallèles entre eux ?", "Oui, tous."],
    ["Pourquoi certaines arêtes sont-elles en pointillés ?", "Parce qu'elles sont cachées par le solide."],
    ["Combien d'arêtes sont cachées ?", "Trois, celles qui aboutissent au sommet arrière."],
    ["Les angles droits sont-ils tous respectés ?", "Non, certains apparaissent obliques."],
    ["Les longueurs sont-elles toutes exactes ?", "Non, les fuyantes sont souvent raccourcies."],
  ],
  syn: "Donc, la perspective permet de représenter un solide sur une feuille plane. La face avant se dessine en vraie grandeur, les arêtes fuyantes sont parallèles entre elles, et les arêtes cachées se tracent en pointillés. Angles droits et longueurs ne sont pas tous conservés.",
  attention: "Un dessin en perspective déforme la réalité : les angles droits du fond n'apparaissent pas droits, et les fuyantes sont raccourcies. Il ne faut donc jamais mesurer une longueur sur un tel dessin.",
  astuce: "Le papier quadrillé facilite le tracé : la face avant suit les lignes du quadrillage, et les fuyantes suivent régulièrement les diagonales des carreaux.",
  app: [
    { c: "Sur un dessin en perspective d'un pavé :\n1. Comment est tracée la face avant ?\n2. Comment sont les fuyantes entre elles ?\n3. Comment trace-t-on les arêtes cachées ?\n4. Combien y en a-t-il ?",
      r: "1. En [[vraie grandeur]]\n2. [[Parallèles]]\n3. En [[pointillés]]\n4. [[Trois]]" },
    { c: "Réponds :\n1. La perspective conserve-t-elle les angles droits ?\n2. Conserve-t-elle les longueurs ?\n3. Peut-on y mesurer une arête ?\n4. À quoi sert-elle alors ?",
      r: "1. [[Non]], pas tous\n2. [[Non]], les fuyantes sont raccourcies\n3. [[Non]]\n4. À [[représenter]] le solide et à comprendre sa forme" },
  ],
  evalx: [
    { c: "Un pavé est dessiné en perspective.\n1. Combien d'arêtes au total ?\n2. Combien visibles ?\n3. Combien cachées ?\n4. Combien de sommets sont cachés ?",
      r: "1. [[Douze]]\n2. [[Neuf]]\n3. [[Trois]]\n4. [[Un seul]]" },
    { c: "Complète :\n1. La face avant est en …… grandeur.\n2. Les fuyantes sont ……\n3. Les arêtes cachées sont en ……\n4. La perspective …… la réalité.",
      r: "1. [[vraie]]\n2. [[parallèles]]\n3. [[pointillés]]\n4. [[déforme]]" },
  ],
  lecon: [
    ["1. Pourquoi la perspective", "Une feuille est {{plane}}, un solide occupe l'{{espace}}. Pour représenter l'un sur l'autre, on emploie un dessin en {{perspective}}, qui donne l'illusion du relief."],
    ["2. Les règles du tracé", "— La {{face avant}} se dessine en vraie grandeur, avec ses angles droits.\n— Les arêtes {{fuyantes}}, qui s'éloignent vers le fond, se tracent {{parallèles}} entre elles et souvent raccourcies.\n— La face arrière est identique à la face avant et lui est parallèle."],
    ["3. Les arêtes cachées", "Les arêtes que le solide dissimule au regard se tracent en {{pointillés}}.\nDans un pavé, {{trois}} arêtes sont cachées : celles qui aboutissent au sommet arrière, lui-même caché."],
    ["4. Les limites du dessin", "La perspective {{déforme}} : les angles droits du fond apparaissent obliques, et les fuyantes sont plus courtes qu'en réalité.\nIl ne faut donc jamais {{mesurer}} une longueur sur un dessin en perspective : seules les indications chiffrées font foi."],
  ],
  exos: [
    { pts: 4, c: "Énonce les trois règles du tracé d'un pavé en perspective.",
      r: "Face avant en [[vraie grandeur]] ; fuyantes [[parallèles]] entre elles ; arêtes cachées en [[pointillés]]." },
    { pts: 4, c: "Combien d'arêtes d'un pavé sont cachées sur un dessin en perspective, et combien sont visibles ?",
      r: "[[Trois]] cachées et [[neuf]] visibles, sur un total de douze." },
    { pts: 4, c: "Pourquoi ne peut-on pas mesurer une longueur sur un dessin en perspective ?",
      r: "Parce que les [[fuyantes]] sont [[raccourcies]] et que le dessin déforme la réalité." },
    { pts: 4, c: "Quelle est la différence entre un patron et une perspective ?",
      r: "Le [[patron]] se plie pour reconstituer le solide et conserve les vraies dimensions ; la [[perspective]] est un dessin qui donne l'illusion du [[relief]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Les fuyantes sont parallèles. 2. Les arêtes cachées sont en trait plein. 3. La face avant est en vraie grandeur. 4. Un pavé a un seul sommet caché.",
      r: "1. [[Vrai]]. 2. [[Faux]] : en pointillés. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "L'aire totale d'un pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de calculer l'aire totale des faces d'un pavé droit et d'un cube.",
  materiel: "Patrons, pavés en carton, règle, ardoises",
  rev: [["Quelle est l'aire d'un rectangle de 6 cm sur 4 cm ?", "24 cm²."],
        ["Quelle est l'aire d'un carré de 4 cm ?", "16 cm²."],
        ["Combien de faces a un pavé ?", "Six."]],
  mise: { q: "Combien de carton faut-il pour fabriquer une boîte sans couvercle manquant ?", ra: "Autant que l'aire totale de ses six faces." },
  obs: "Observez le patron déplié d'un pavé de 6 cm sur 4 cm sur 3 cm : on y lit deux rectangles de 6 sur 4, deux de 6 sur 3 et deux de 4 sur 3.",
  ana: [
    ["Quelle est l'aire d'un rectangle de 6 sur 4 ?", "Vingt-quatre centimètres carrés."],
    ["Combien y en a-t-il ?", "Deux."],
    ["Quelle est l'aire d'un rectangle de 6 sur 3 ?", "Dix-huit centimètres carrés."],
    ["Et celle d'un rectangle de 4 sur 3 ?", "Douze centimètres carrés."],
    ["Comment obtenir l'aire totale ?", "En additionnant les six aires."],
    ["Combien vaut-elle ?", "Cent huit centimètres carrés."],
    ["Quelle écriture plus courte peut-on employer ?", "Deux fois la somme des trois produits."],
    ["Et pour un cube d'arête 4 ?", "Six fois seize, soit quatre-vingt-seize."],
  ],
  syn: "Donc, l'aire totale d'un pavé droit est la somme des aires de ses six faces. Comme elles sont identiques deux à deux, on calcule deux fois la somme des trois produits des dimensions prises deux à deux. Pour un cube, l'aire totale vaut six fois l'aire d'une face.",
  attention: "L'aire totale s'exprime en unités carrées, jamais en unités cubiques. Elle mesure une surface de carton, non la place occupée dans l'espace.",
  astuce: "Vérifiez sur le patron : le nombre de rectangles doit toujours être six, et l'aire totale du patron est exactement l'aire totale du solide.",
  app: [
    { c: "Un pavé mesure 6 cm, 4 cm et 3 cm.\n1. Aire des deux faces de 6 sur 4 ?\n2. Des deux faces de 6 sur 3 ?\n3. Des deux faces de 4 sur 3 ?\n4. Aire totale ?",
      r: "1. [[48 cm²]]\n2. [[36 cm²]]\n3. [[24 cm²]]\n4. [[108 cm²]]" },
    { c: "Calcule l'aire totale :\n1. d'un cube de 4 cm d'arête\n2. d'un cube de 5 cm d'arête\n3. d'un cube de 10 cm d'arête\n4. Quelle formule emploies-tu ?",
      r: "1. [[96 cm²]]\n2. [[150 cm²]]\n3. [[600 cm²]]\n4. [[6 × côté × côté]]" },
  ],
  evalx: [
    { c: "Une boîte mesure 20 cm, 15 cm et 10 cm.\n1. Aire des deux plus grandes faces ?\n2. Aire des deux faces de 20 sur 10 ?\n3. Aire des deux faces de 15 sur 10 ?\n4. Aire totale ?",
      r: "1. [[600 cm²]]\n2. [[400 cm²]]\n3. [[300 cm²]]\n4. [[1 300 cm²]]" },
    { c: "Complète :\n1. L'aire totale est la somme des aires des …… faces.\n2. Elle s'exprime en unités ……\n3. Pour un cube, elle vaut …… fois l'aire d'une face.\n4. Elle correspond à l'aire du ……",
      r: "1. [[six]]\n2. [[carrées]]\n3. [[six]]\n4. [[patron]]" },
  ],
  lecon: [
    ["1. Le principe", "L'{{aire totale}} d'un pavé droit est la somme des aires de ses {{six faces}}.\nElle correspond exactement à l'aire de son {{patron}}, c'est-à-dire à la surface de carton nécessaire pour le fabriquer."],
    ["2. Le calcul pour un pavé", "Les faces étant identiques deux à deux, on calcule trois produits et l'on double la somme :\nAire totale = 2 × (L × l + L × h + l × h).\nPour 6 cm, 4 cm et 3 cm : 2 × (24 + 18 + 12) = 2 × 54 = 108 cm²."],
    ["3. Le cas du cube", "Toutes les faces d'un cube étant des carrés {{égaux}} :\nAire totale = {{6 × côté × côté}}.\nPour un cube de 4 cm d'arête : 6 × 16 = 96 cm²."],
    ["4. Les unités", "L'aire totale mesure une {{surface}} : elle s'exprime en cm², en m², jamais en unités cubiques.\nComme toujours, les trois dimensions doivent être exprimées dans la {{même unité}} avant le calcul."],
  ],
  exos: [
    { pts: 4, c: "Calcule l'aire totale d'un pavé de 6 cm sur 4 cm sur 3 cm.",
      r: "2 × (24 + 18 + 12) = [[108 cm²]]." },
    { pts: 4, c: "Calcule l'aire totale d'un cube de 5 cm d'arête.",
      r: "6 × 25 = [[150 cm²]]." },
    { pts: 4, c: "Une boîte mesure 20 cm, 15 cm et 10 cm. Quelle surface de carton faut-il pour la fabriquer ?",
      r: "2 × (300 + 200 + 150) = [[1 300 cm²]]." },
    { pts: 4, c: "Un cube a 10 cm d'arête. Quelle est l'aire totale de ses faces ?",
      r: "6 × 100 = [[600 cm²]]." },
    { pts: 4, c: "Vrai ou faux ? 1. L'aire totale s'exprime en cm³. 2. Elle égale l'aire du patron. 3. Pour un cube, elle vaut 6 fois l'aire d'une face. 4. Les faces d'un pavé sont identiques deux à deux.",
      r: "1. [[Faux]] : en cm². 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Pavé droit et cylindre",
  titre: "Le cylindre et son patron",
  objectif: "À la fin de la séance, l'élève est capable de décrire un cylindre, d'en reconnaître le patron et d'en calculer l'aire de base.",
  materiel: "Boîtes de conserve, étiquettes, compas, ciseaux",
  rev: [["Quelle est l'aire d'un disque de rayon 3 cm ?", "28,26 cm²."],
        ["Quelle est la circonférence d'un cercle de rayon 3 cm ?", "18,84 cm."],
        ["Qu'est-ce qu'un patron ?", "La figure plane obtenue en dépliant le solide."]],
  mise: { q: "Si l'on décolle l'étiquette d'une boîte de conserve et qu'on l'aplatit, quelle forme obtient-on ?", ra: "Un rectangle." },
  obs: "Observez la manipulation : l'enseignant décolle l'étiquette d'une boîte de conserve, l'aplatit — c'est un rectangle — puis découpe les deux fonds, qui sont deux disques.",
  ana: [
    ["Combien de bases a le cylindre ?", "Deux."],
    ["Quelle est leur forme ?", "Des disques identiques."],
    ["Que devient la surface courbe une fois aplatie ?", "Un rectangle."],
    ["Que représente la longueur de ce rectangle ?", "La circonférence de la base."],
    ["Et sa largeur ?", "La hauteur du cylindre."],
    ["De quoi se compose donc le patron ?", "De deux disques et d'un rectangle."],
    ["Quelle est l'aire d'une base de rayon 3 cm ?", "28,26 centimètres carrés."],
  ],
  syn: "Donc, un cylindre possède deux bases circulaires identiques reliées par une surface courbe. Son patron se compose de deux disques et d'un rectangle dont la longueur est la circonférence de la base et la largeur la hauteur du cylindre. L'aire d'une base se calcule par pi multiplié deux fois par le rayon.",
  attention: "La longueur du rectangle du patron n'est pas le diamètre mais la circonférence de la base. Une étiquette trop courte ne ferait pas le tour de la boîte.",
  astuce: "Pour tracer le patron, calculez d'abord la circonférence : c'est elle qui fixe la longueur du rectangle et donc la réussite du collage.",
  app: [
    { c: "Un cylindre a un rayon de 3 cm et une hauteur de 10 cm.\n1. Quelle est l'aire d'une base ?\n2. Quelle est la circonférence de la base ?\n3. Quelles sont les dimensions du rectangle du patron ?\n4. Combien de disques dans le patron ?",
      r: "1. [[28,26 cm²]]\n2. [[18,84 cm]]\n3. [[18,84 cm sur 10 cm]]\n4. [[Deux]]" },
    { c: "Réponds :\n1. Combien de bases a un cylindre ?\n2. De quelle forme ?\n3. Que devient la surface courbe aplatie ?\n4. Que représente sa longueur ?",
      r: "1. [[Deux]]\n2. Des [[disques identiques]]\n3. Un [[rectangle]]\n4. La [[circonférence]] de la base" },
  ],
  evalx: [
    { c: "Une boîte de conserve a 4 cm de rayon et 12 cm de hauteur.\n1. Circonférence de la base ?\n2. Longueur de l'étiquette ?\n3. Largeur de l'étiquette ?\n4. Aire de l'étiquette ?",
      r: "1. [[25,12 cm]]\n2. [[25,12 cm]]\n3. [[12 cm]]\n4. [[301,44 cm²]]" },
    { c: "Complète :\n1. Le cylindre a deux bases en forme de ……\n2. Son patron comporte …… disques et un ……\n3. La longueur du rectangle est la ……\n4. Sa largeur est la ……",
      r: "1. [[disques]]\n2. [[deux]] ; [[rectangle]]\n3. [[circonférence de la base]]\n4. [[hauteur du cylindre]]" },
  ],
  lecon: [
    ["1. Décrire le cylindre", "Un {{cylindre}} est formé de deux {{bases}} circulaires identiques et parallèles, reliées par une surface {{courbe}}.\nLa distance entre les deux bases est sa {{hauteur}}. C'est la forme d'une boîte de conserve, d'un tuyau ou d'un bidon."],
    ["2. Le patron du cylindre", "En dépliant le cylindre, on obtient :\n— {{deux disques}} identiques, les deux bases ;\n— un {{rectangle}}, la surface courbe aplatie, comme l'étiquette d'une boîte de conserve."],
    ["3. Les dimensions du rectangle", "La {{longueur}} du rectangle est égale à la {{circonférence}} de la base, soit 2 × π × rayon : c'est elle qui permet de faire le tour.\nSa {{largeur}} est égale à la {{hauteur}} du cylindre.\nPour un rayon de 3 cm et une hauteur de 10 cm : 18,84 cm sur 10 cm."],
    ["4. L'aire de la base", "L'aire d'une base se calcule comme celle d'un {{disque}} : π × rayon × rayon.\nPour un rayon de 3 cm : 3,14 × 3 × 3 = 28,26 cm²."],
  ],
  exos: [
    { pts: 4, c: "Décris le patron d'un cylindre.",
      r: "Il comporte [[deux disques]] identiques, les bases, et un [[rectangle]] correspondant à la surface courbe." },
    { pts: 4, c: "Un cylindre a 3 cm de rayon et 10 cm de hauteur. Quelles sont les dimensions du rectangle de son patron ?",
      r: "Longueur : 2 × 3,14 × 3 = [[18,84 cm]]. Largeur : [[10 cm]]." },
    { pts: 4, c: "Calcule l'aire d'une base de ce cylindre.",
      r: "3,14 × 3 × 3 = [[28,26 cm²]]." },
    { pts: 4, c: "Une boîte de conserve a 4 cm de rayon et 12 cm de hauteur. Quelle est l'aire de son étiquette ?",
      r: "Circonférence : 25,12 cm. Aire : 25,12 × 12 = [[301,44 cm²]]." },
    { pts: 4, c: "Vrai ou faux ? 1. Le cylindre a deux bases carrées. 2. La longueur du rectangle est la circonférence. 3. Sa largeur est la hauteur. 4. Le patron comporte trois parties.",
      r: "1. [[Faux]] : circulaires. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]] : deux disques et un rectangle." },
  ],
},
{
  ch: "Volume du pavé",
  titre: "Découvrir la notion de volume",
  objectif: "À la fin de la séance, l'élève est capable de distinguer le volume de l'aire et de mesurer un volume par comptage de cubes unités.",
  materiel: "Petits cubes emboîtables, boîtes, ardoises",
  rev: [["Qu'est-ce que l'aire d'une figure ?", "La mesure de la surface occupée."],
        ["Quelle est l'aire d'un carré de 3 cm ?", "9 cm²."],
        ["Combien de faces a un pavé ?", "Six."]],
  mise: { q: "Deux boîtes ont la même surface de carton. Contiennent-elles forcément la même quantité de riz ?", ra: "Non, pas nécessairement." },
  obs: "Observez la boîte que remplit l'enseignant avec de petits cubes d'un centimètre d'arête : il en place quatre par rangée, trois rangées par couche, et deux couches.",
  ana: [
    ["Combien de cubes par rangée ?", "Quatre."],
    ["Combien de rangées par couche ?", "Trois."],
    ["Combien de cubes par couche ?", "Douze."],
    ["Combien de couches ?", "Deux."],
    ["Combien de cubes en tout ?", "Vingt-quatre."],
    ["Que mesure ce nombre ?", "La place occupée à l'intérieur."],
    ["Comment nomme-t-on cette mesure ?", "Le volume."],
    ["Quelle est l'unité employée ?", "Le centimètre cube."],
  ],
  syn: "Donc, le volume d'un solide est la mesure de la place qu'il occupe dans l'espace. On l'exprime en unités cubiques, comme le centimètre cube, qui est le volume d'un cube d'un centimètre d'arête. On peut le déterminer en comptant les cubes unités qui remplissent le solide.",
  attention: "Ne confondez pas l'aire et le volume. L'aire mesure une surface, en centimètres carrés ; le volume mesure une place occupée, en centimètres cubes. Deux boîtes de même aire totale peuvent avoir des volumes différents.",
  astuce: "L'unité vous renseigne à coup sûr : cm désigne une longueur, cm² une aire, cm³ un volume.",
  app: [
    { c: "Une boîte contient 4 cubes par rangée, 3 rangées par couche et 2 couches.\n1. Combien de cubes par couche ?\n2. Combien en tout ?\n3. Quel est le volume ?\n4. Quelle unité ?",
      r: "1. [[12]]\n2. [[24]]\n3. [[24 cm³]]\n4. Le [[centimètre cube]]" },
    { c: "Longueur, aire ou volume ?\n1. la hauteur d'un mur\n2. la peinture pour ce mur\n3. l'eau dans une citerne\n4. le grillage autour d'un champ",
      r: "1. Une [[longueur]]\n2. Une [[aire]]\n3. Un [[volume]]\n4. Une [[longueur]]" },
  ],
  evalx: [
    { c: "Complète :\n1. Le volume mesure la …… occupée.\n2. Il s'exprime en unités ……\n3. Le cm³ est le volume d'un cube de …… d'arête.\n4. L'aire s'exprime en unités ……",
      r: "1. [[place]]\n2. [[cubiques]]\n3. [[1 cm]]\n4. [[carrées]]" },
    { c: "Un empilement compte 5 cubes de long, 4 de large et 3 de haut.\n1. Combien de cubes par couche ?\n2. Combien de couches ?\n3. Combien de cubes en tout ?\n4. Quel est le volume ?",
      r: "1. [[20]]\n2. [[3]]\n3. [[60]]\n4. [[60 cm³]]" },
  ],
  lecon: [
    ["1. Qu'est-ce que le volume", "Le {{volume}} d'un solide est la mesure de la {{place}} qu'il occupe dans l'espace, ou de la quantité qu'il peut contenir.\nIl répond à des questions concrètes : combien de riz dans un sac, combien d'eau dans une citerne, combien de terre à déplacer."],
    ["2. L'unité de volume", "L'unité principale est le {{mètre cube}}, noté m³ : c'est le volume d'un cube d'un mètre d'arête.\nPour les petits volumes, on emploie le {{centimètre cube}} (cm³), volume d'un cube d'un centimètre d'arête."],
    ["3. Mesurer par comptage", "On peut mesurer un volume en comptant les {{cubes unités}} qui remplissent le solide.\nUne boîte contenant 4 cubes par rangée, 3 rangées par couche et 2 couches en contient 4 × 3 × 2 = {{24}}, soit un volume de 24 cm³."],
    ["4. Ne pas confondre", "La {{longueur}} se mesure en cm, l'{{aire}} en cm², le {{volume}} en cm³.\nDeux boîtes de même aire totale peuvent avoir des volumes différents : ce sont deux grandeurs indépendantes."],
  ],
  exos: [
    { pts: 4, c: "Explique la différence entre l'aire et le volume.",
      r: "L'[[aire]] mesure une [[surface]], en cm² ; le [[volume]] mesure la [[place occupée]] dans l'espace, en cm³." },
    { pts: 4, c: "Une boîte contient 4 cubes par rangée, 3 rangées et 2 couches. Quel est son volume ?",
      r: "4 × 3 × 2 = [[24 cm³]]." },
    { pts: 4, c: "Un empilement compte 5 cubes de long, 4 de large et 3 de haut. Combien de cubes contient-il ?",
      r: "5 × 4 × 3 = [[60 cubes]], soit un volume de [[60 cm³]]." },
    { pts: 4, c: "Pour chacune de ces grandeurs, indique l'unité : la hauteur d'un mur, la peinture pour le couvrir, l'eau d'une citerne.",
      r: "Hauteur : [[m]]. Peinture : [[m²]]. Eau : [[m³]] ou litres." },
    { pts: 4, c: "Vrai ou faux ? 1. Le volume s'exprime en cm². 2. Le m³ est le volume d'un cube de 1 m d'arête. 3. Aire et volume sont la même chose. 4. On peut mesurer un volume en comptant des cubes.",
      r: "1. [[Faux]] : en cm³. 2. [[Vrai]]. 3. [[Faux]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Volume du pavé",
  titre: "Calculer le volume d'un pavé droit",
  objectif: "À la fin de la séance, l'élève est capable de calculer le volume d'un pavé droit et d'un cube par la formule.",
  materiel: "Cubes emboîtables, boîtes, règle graduée, ardoises",
  rev: [["Qu'est-ce que le volume ?", "La mesure de la place occupée."],
        ["Calcule 8 × 5 × 3.", "120."],
        ["Calcule 5 × 5 × 5.", "125."]],
  mise: { q: "Faut-il vraiment empiler des cubes un à un pour connaître le volume d'une boîte de 8 sur 5 sur 3 ?", ra: "Non, une multiplication suffit." },
  obs: "Observez au tableau le pavé dessiné : 8 cubes de long, 5 de large et 3 de haut. Une couche entière est mise en évidence en couleur.",
  ana: [
    ["Combien de cubes dans une couche ?", "Quarante."],
    ["Comment l'a-t-on trouvé ?", "En multipliant 8 par 5."],
    ["Que représente ce produit ?", "L'aire de la base."],
    ["Combien de couches ?", "Trois."],
    ["Comment obtenir le total ?", "En multipliant 40 par 3."],
    ["Quel est le volume ?", "Cent vingt centimètres cubes."],
    ["Quelle formule en déduire ?", "Longueur fois largeur fois hauteur."],
    ["Et pour un cube d'arête 5 ?", "Cinq fois cinq fois cinq, soit cent vingt-cinq."],
  ],
  syn: "Donc, le volume d'un pavé droit s'obtient en multipliant sa longueur par sa largeur puis par sa hauteur. On peut aussi multiplier l'aire de sa base par sa hauteur. Le volume d'un cube vaut son arête multipliée trois fois par elle-même. Les trois dimensions doivent être exprimées dans la même unité.",
  attention: "Les trois dimensions doivent partager la même unité. Pour une boîte de 2 m sur 50 cm sur 30 cm, convertissez d'abord en 2 m sur 0,5 m sur 0,3 m.",
  astuce: "La formule se lit dans les deux sens : connaissant le volume et l'aire de la base, on obtient la hauteur en divisant.",
  app: [
    { c: "Calcule le volume :\n1. d'un pavé de 8 cm, 5 cm et 3 cm\n2. d'un cube de 5 cm d'arête\n3. d'un pavé de 12 cm, 6 cm et 4 cm\n4. d'un pavé de 2,5 m, 2 m et 1,5 m",
      r: "1. [[120 cm³]]\n2. [[125 cm³]]\n3. [[288 cm³]]\n4. [[7,5 m³]]" },
    { c: "Un pavé a un volume de 120 cm³ et une base de 8 cm sur 5 cm.\n1. Quelle est l'aire de la base ?\n2. Quelle opération donne la hauteur ?\n3. Combien vaut-elle ?\n4. Vérifie ton résultat.",
      r: "1. [[40 cm²]]\n2. Une [[division]]\n3. [[3 cm]]\n4. [[8 × 5 × 3 = 120]]" },
  ],
  evalx: [
    { c: "Calcule le volume :\n1. d'un cube de 3 cm\n2. d'un cube de 10 cm\n3. d'un pavé de 20 cm, 10 cm et 5 cm\n4. d'un pavé de 6 m, 4 m et 2 m",
      r: "1. [[27 cm³]]\n2. [[1 000 cm³]]\n3. [[1 000 cm³]]\n4. [[48 m³]]" },
    { c: "Une pièce mesure 5 m sur 4 m et 2,5 m de hauteur.\n1. Quelle est l'aire du sol ?\n2. Quel est le volume d'air ?\n3. Quelle unité emploies-tu pour chacun ?\n4. Pourquoi diffèrent-elles ?",
      r: "1. [[20 m²]]\n2. [[50 m³]]\n3. Le [[m²]] et le [[m³]]\n4. L'une mesure une [[surface]], l'autre un [[volume]]" },
  ],
  lecon: [
    ["1. La formule", "Un pavé de 8 cubes de long, 5 de large et 3 de haut contient 8 × 5 = 40 cubes par couche, et compte 3 couches, soit 120 cubes.\nD'où la formule :\nVolume du pavé droit = {{Longueur × largeur × hauteur}}."],
    ["2. Par l'aire de la base", "Le produit de la longueur par la largeur donne l'{{aire de la base}}.\nOn peut donc écrire : Volume = {{aire de la base × hauteur}}.\nPour une base de 40 cm² et une hauteur de 3 cm : 40 × 3 = 120 cm³."],
    ["3. Le cas du cube", "Toutes les arêtes d'un cube étant égales :\nVolume du cube = {{arête × arête × arête}}.\nPour un cube de 5 cm : 5 × 5 × 5 = 125 cm³."],
    ["4. Retrouver une dimension", "La formule se lit dans les deux sens. Connaissant le volume et l'aire de la base, on obtient la {{hauteur}} par une division :\n120 ÷ 40 = 3 cm.\nLes trois dimensions doivent toujours être exprimées dans la {{même unité}}."],
  ],
  exos: [
    { pts: 4, c: "Calcule le volume d'un pavé de 8 cm sur 5 cm sur 3 cm.",
      r: "8 × 5 × 3 = [[120 cm³]]." },
    { pts: 4, c: "Calcule le volume d'un cube de 5 cm d'arête et d'un cube de 10 cm d'arête.",
      r: "[[125 cm³]] et [[1 000 cm³]]." },
    { pts: 4, c: "Une pièce mesure 5 m sur 4 m sur 2,5 m de hauteur. Quel est son volume ?",
      r: "5 × 4 × 2,5 = [[50 m³]]." },
    { pts: 4, c: "Un pavé a un volume de 120 cm³ et une base de 40 cm². Quelle est sa hauteur ?",
      r: "120 ÷ 40 = [[3 cm]]." },
    { pts: 4, c: "Calcule le volume d'un pavé de 12 cm sur 6 cm sur 4 cm.",
      r: "12 × 6 × 4 = [[288 cm³]]." },
  ],
},
{
  ch: "Volume du pavé",
  titre: "Les unités de volume",
  objectif: "À la fin de la séance, l'élève est capable de convertir une mesure de volume d'une unité à une autre.",
  materiel: "Cube d'un décimètre, tableau de conversion, ardoises",
  rev: [["Quel est le volume d'un cube de 10 cm ?", "1 000 cm³."],
        ["Combien de cm dans 1 dm ?", "10."],
        ["Calcule 10 × 10 × 10.", "1 000."]],
  mise: { q: "Combien de petits cubes d'un centimètre faut-il pour remplir un cube d'un décimètre ?", ra: "Mille." },
  obs: "Observez le cube d'un décimètre d'arête posé sur la table, entièrement rempli de petits cubes d'un centimètre : dix par rangée, dix rangées, dix couches.",
  ana: [
    ["Combien de petits cubes par couche ?", "Cent."],
    ["Combien de couches ?", "Dix."],
    ["Combien de cubes en tout ?", "Mille."],
    ["Que vaut donc 1 dm³ en cm³ ?", "Mille centimètres cubes."],
    ["Chaque unité vaut combien de fois la suivante ?", "Mille fois."],
    ["Que vaut 1 m³ en dm³ ?", "Mille décimètres cubes."],
    ["Combien de litres dans un décimètre cube ?", "Un seul."],
    ["Que vaut alors 1 m³ en litres ?", "Mille litres."],
  ],
  syn: "Donc, chaque unité de volume vaut mille fois celle qui la suit, et non dix comme pour les longueurs ni cent comme pour les aires. Un mètre cube vaut mille décimètres cubes et un décimètre cube vaut mille centimètres cubes. Un décimètre cube contient exactement un litre, si bien qu'un mètre cube vaut mille litres.",
  attention: "Le rapport entre deux unités de volume consécutives est de mille. C'est l'erreur la plus fréquente : un mètre cube ne vaut ni dix ni cent décimètres cubes, mais bien mille.",
  astuce: "Retenez l'égalité fondamentale : un décimètre cube égale un litre. Elle relie les mesures de volume à celles de capacité et suffit à la plupart des conversions.",
  app: [
    { c: "Convertis :\n1. 1 dm³ en cm³\n2. 1 m³ en dm³\n3. 1 m³ en litres\n4. 2,5 m³ en litres",
      r: "1. [[1 000 cm³]]\n2. [[1 000 dm³]]\n3. [[1 000 litres]]\n4. [[2 500 litres]]" },
    { c: "Convertis :\n1. 1 dm³ en litres\n2. 5 000 cm³ en dm³\n3. 3 m³ en litres\n4. 750 litres en m³",
      r: "1. [[1 litre]]\n2. [[5 dm³]]\n3. [[3 000 litres]]\n4. [[0,75 m³]]" },
  ],
  evalx: [
    { c: "Complète :\n1. Chaque unité de volume vaut …… fois la suivante.\n2. 1 m³ = …… dm³\n3. 1 dm³ = …… litre\n4. 1 m³ = …… litres",
      r: "1. [[mille]]\n2. [[1 000]]\n3. [[1]]\n4. [[1 000]]" },
    { c: "Une citerne mesure 2 m sur 1,5 m sur 1 m.\n1. Quel est son volume en m³ ?\n2. En dm³ ?\n3. En litres ?\n4. Combien de bidons de 20 litres peut-on remplir ?",
      r: "1. [[3 m³]]\n2. [[3 000 dm³]]\n3. [[3 000 litres]]\n4. [[150 bidons]]" },
  ],
  lecon: [
    ["1. Le rapport de mille", "Un cube d'un décimètre d'arête se remplit de 10 × 10 × 10 = {{1 000}} cubes d'un centimètre.\nChaque unité de volume vaut donc {{mille fois}} celle qui la suit — contre dix pour les longueurs et cent pour les aires."],
    ["2. Les principales égalités", "1 m³ = 1 000 dm³ = 1 000 000 cm³.\n1 dm³ = 1 000 cm³.\nPour convertir des m³ en dm³, on multiplie par 1 000 ; pour l'inverse, on divise."],
    ["3. Volume et capacité", "Le {{litre}} mesure une capacité, c'est-à-dire ce qu'un récipient peut contenir.\nL'égalité fondamentale est : {{1 dm³ = 1 litre}}.\nIl en découle que 1 m³ = 1 000 litres, et que 1 cm³ = 1 millilitre."],
    ["4. En pratique", "Une citerne de 2 m sur 1,5 m sur 1 m a un volume de 3 m³, soit {{3 000 litres}}.\nOn choisit l'unité la plus {{parlante}} : les litres pour un bidon, les mètres cubes pour un réservoir ou un camion."],
  ],
  exos: [
    { pts: 4, c: "Convertis : 1 dm³ en cm³, 1 m³ en dm³, 1 m³ en litres.",
      r: "[[1 000 cm³]] ; [[1 000 dm³]] ; [[1 000 litres]]." },
    { pts: 4, c: "Convertis 2,5 m³ en litres.",
      r: "2,5 × 1 000 = [[2 500 litres]]." },
    { pts: 4, c: "Une citerne mesure 2 m sur 1,5 m sur 1 m. Quel est son volume en litres ?",
      r: "Volume : 3 m³, soit [[3 000 litres]]." },
    { pts: 4, c: "Combien de bidons de 20 litres peut-on remplir avec cette citerne ?",
      r: "3 000 ÷ 20 = [[150 bidons]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 1 m³ = 100 dm³. 2. 1 dm³ = 1 litre. 3. Chaque unité de volume vaut mille fois la suivante. 4. 1 cm³ = 1 millilitre.",
      r: "1. [[Faux]] : 1 000 dm³. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Volume du pavé",
  titre: "Volume et capacité",
  objectif: "À la fin de la séance, l'élève est capable de passer d'une mesure de volume à une mesure de capacité et d'employer les unités de capacité.",
  materiel: "Bidons, bouteilles, seaux gradués, ardoises",
  rev: [["Combien de litres dans 1 dm³ ?", "Un litre."],
        ["Combien de litres dans 1 m³ ?", "Mille litres."],
        ["Calcule 3 × 1 000.", "3 000."]],
  mise: { q: "Un bidon porte l'indication « 20 L ». Que mesure exactement ce nombre ?", ra: "Ce que le bidon peut contenir." },
  obs: "Observez les récipients alignés : une bouteille de 1,5 litre, un bidon de 20 litres, un seau gradué. L'enseignant verse le contenu d'un cube d'un décimètre dans une bouteille d'un litre : elle se remplit exactement.",
  ana: [
    ["Que mesure-t-on avec les litres ?", "Ce qu'un récipient peut contenir."],
    ["Comment nomme-t-on cette grandeur ?", "La capacité."],
    ["Le cube d'un décimètre remplit-il la bouteille ?", "Oui, exactement un litre."],
    ["Quelle égalité en tirer ?", "Un décimètre cube égale un litre."],
    ["Que vaut un centilitre ?", "Un centième de litre."],
    ["Et un millilitre ?", "Un millième de litre."],
    ["Combien de millilitres dans un litre ?", "Mille."],
    ["À quel volume correspond un millilitre ?", "Un centimètre cube."],
  ],
  syn: "Donc, la capacité d'un récipient est ce qu'il peut contenir. Elle se mesure en litres, et l'égalité fondamentale un décimètre cube égale un litre relie capacité et volume. Le centilitre vaut un centième de litre, le millilitre un millième, et un millilitre correspond à un centimètre cube.",
  attention: "Le volume et la capacité désignent la même réalité mesurée autrement : les mètres cubes conviennent aux grands réservoirs, les litres aux récipients courants. On ne les additionne jamais sans conversion préalable.",
  astuce: "Une bouteille d'eau ordinaire contient 1,5 litre, soit 1 500 cm³ : c'est un bon repère pour estimer un volume sans calcul.",
  app: [
    { c: "Convertis :\n1. 1 dm³ en litres\n2. 1 m³ en litres\n3. 1 litre en millilitres\n4. 1 cm³ en millilitres",
      r: "1. [[1 litre]]\n2. [[1 000 litres]]\n3. [[1 000 mL]]\n4. [[1 mL]]" },
    { c: "Un réservoir mesure 1,2 m sur 1 m sur 0,5 m.\n1. Quel est son volume en m³ ?\n2. En litres ?\n3. Combien de bidons de 20 litres ?\n4. Combien de bouteilles de 1,5 litre ?",
      r: "1. [[0,6 m³]]\n2. [[600 litres]]\n3. [[30 bidons]]\n4. [[400 bouteilles]]" },
  ],
  evalx: [
    { c: "Convertis :\n1. 2 500 mL en litres\n2. 3,5 L en millilitres\n3. 4 m³ en litres\n4. 750 mL en cm³",
      r: "1. [[2,5 L]]\n2. [[3 500 mL]]\n3. [[4 000 litres]]\n4. [[750 cm³]]" },
    { c: "Une citerne de 2 000 litres est remplie aux trois quarts.\n1. Combien de litres contient-elle ?\n2. Combien manque-t-il ?\n3. Exprime son contenu en m³.\n4. Combien de seaux de 10 litres pour la remplir ?",
      r: "1. [[1 500 litres]]\n2. [[500 litres]]\n3. [[1,5 m³]]\n4. [[50 seaux]]" },
  ],
  lecon: [
    ["1. La capacité", "La {{capacité}} d'un récipient est la quantité de liquide ou de matière qu'il peut contenir.\nSon unité principale est le {{litre}}, noté L."],
    ["2. Le lien avec le volume", "Volume et capacité mesurent la même réalité. L'égalité fondamentale est :\n{{1 dm³ = 1 litre}}.\nIl en découle : 1 m³ = 1 000 litres et 1 cm³ = 1 millilitre."],
    ["3. Les sous-multiples", "Le {{centilitre}} (cL) vaut un centième de litre ; le {{millilitre}} (mL) vaut un millième de litre.\nUne bouteille de 1,5 litre contient donc 1 500 mL, soit 1 500 cm³."],
    ["4. Choisir l'unité", "On emploie les {{litres}} pour les récipients courants — bidon, seau, bouteille — et les {{mètres cubes}} pour les grands volumes : citerne, réservoir, camion.\nUn réservoir de 1,2 m sur 1 m sur 0,5 m contient 0,6 m³, soit 600 litres."],
  ],
  exos: [
    { pts: 4, c: "Convertis : 1 dm³ en litres, 1 m³ en litres, 1 cm³ en millilitres.",
      r: "[[1 litre]] ; [[1 000 litres]] ; [[1 mL]]." },
    { pts: 4, c: "Un réservoir mesure 1,2 m sur 1 m sur 0,5 m. Quelle est sa capacité en litres ?",
      r: "Volume : 0,6 m³, soit [[600 litres]]." },
    { pts: 4, c: "Combien de bidons de 20 litres peut-on remplir avec ce réservoir ?",
      r: "600 ÷ 20 = [[30 bidons]]." },
    { pts: 4, c: "Une citerne de 2 000 litres est remplie aux trois quarts. Combien contient-elle, et combien manque-t-il ?",
      r: "Elle contient [[1 500 litres]] ; il manque [[500 litres]]." },
    { pts: 4, c: "Convertis 2 500 mL en litres et 3,5 L en millilitres.",
      r: "[[2,5 L]] et [[3 500 mL]]." },
  ],
},
{
  ch: "Volume du pavé",
  titre: "Problèmes de volumes",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème concret faisant intervenir un volume ou une capacité.",
  materiel: "Énoncés au tableau, cahier de recherche",
  rev: [["Quel est le volume d'un pavé de 2 m sur 1,5 m sur 1 m ?", "3 m³."],
        ["Combien de litres dans 3 m³ ?", "3 000 litres."],
        ["Calcule 3 000 ÷ 20.", "150."]],
  mise: { q: "Un camion-citerne doit livrer de l'eau dans un village. Que doit-on calculer avant le départ ?", ra: "Le volume que la citerne peut contenir." },
  obs: "Lisez l'énoncé au tableau : « Une citerne rectangulaire mesure 2,5 m de long, 1,8 m de large et 1,2 m de haut. Elle est remplie aux deux tiers. L'eau se vend 3 ariary le litre. »",
  ana: [
    ["Quel est le volume total de la citerne ?", "Cinq mètres cubes et quatre cents litres."],
    ["Comment l'a-t-on calculé ?", "En multipliant les trois dimensions."],
    ["Combien cela fait-il de litres ?", "Cinq mille quatre cents."],
    ["Quelle quantité d'eau contient-elle ?", "Trois mille six cents litres."],
    ["Comment l'a-t-on obtenu ?", "En prenant les deux tiers."],
    ["Quel est le prix de cette eau ?", "Dix mille huit cents ariary."],
    ["Combien d'étapes ce problème comporte-t-il ?", "Trois."],
    ["Comment vérifier ?", "Par un ordre de grandeur."],
  ],
  syn: "Donc, un problème de volume se résout en calculant d'abord le volume par la formule appropriée, en le convertissant si nécessaire en litres, puis en enchaînant les opérations demandées. Les trois dimensions doivent être dans la même unité, et le résultat se contrôle par un ordre de grandeur.",
  attention: "Vérifiez les unités avant de multiplier. Un énoncé donnant une longueur en mètres et une hauteur en centimètres exige une conversion, faute de quoi le volume obtenu n'a aucun sens.",
  app: [
    { c: "Une citerne mesure 2,5 m sur 1,8 m sur 1,2 m, remplie aux deux tiers, l'eau valant 3 ariary le litre.\n1. Quel est son volume en m³ ?\n2. En litres ?\n3. Quelle quantité contient-elle ?\n4. Quel est le prix de cette eau ?",
      r: "1. [[5,4 m³]]\n2. [[5 400 litres]]\n3. [[3 600 litres]]\n4. [[10 800 ariary]]" },
    { c: "Une piscine mesure 8 m sur 4 m et 1,5 m de profondeur.\n1. Quel est son volume ?\n2. En litres ?\n3. Combien de temps pour la remplir à 500 litres par minute ?\n4. Exprime cette durée en heures.",
      r: "1. [[48 m³]]\n2. [[48 000 litres]]\n3. [[96 minutes]]\n4. [[1 h 36 min]]" },
  ],
  evalx: [
    { c: "Une caisse mesure 60 cm sur 40 cm sur 30 cm.\n1. Quel est son volume en cm³ ?\n2. En dm³ ?\n3. En litres ?\n4. Combien de boîtes cubiques de 10 cm d'arête peut-on y ranger ?",
      r: "1. [[72 000 cm³]]\n2. [[72 dm³]]\n3. [[72 litres]]\n4. [[72 boîtes]]" },
    { c: "Un grenier mesure 6 m sur 4 m sur 2,5 m.\n1. Quel est son volume ?\n2. On y entrepose des sacs occupant 0,05 m³ chacun : combien en tient-il ?\n3. Chaque sac pèse 50 kg : quelle masse totale ?\n4. Exprime-la en tonnes.",
      r: "1. [[60 m³]]\n2. [[1 200 sacs]]\n3. [[60 000 kg]]\n4. [[60 tonnes]]" },
  ],
  lecon: [
    ["1. Identifier le solide", "On repère d'abord la {{forme}} du récipient ou du local : caisse, citerne, pièce, grenier sont le plus souvent des {{pavés droits}}.\nOn applique alors la formule Longueur × largeur × hauteur."],
    ["2. Uniformiser les unités", "Les trois dimensions doivent être exprimées dans la {{même unité}}.\nUne caisse de 60 cm sur 40 cm sur 30 cm a un volume de 72 000 cm³, soit 72 dm³ ou 72 litres."],
    ["3. Convertir en litres", "Pour les liquides, on convertit le volume en {{litres}} grâce à l'égalité 1 dm³ = 1 litre.\nUne citerne de 5,4 m³ contient 5 400 litres."],
    ["4. Enchaîner les étapes", "Un problème comporte souvent plusieurs étapes : une {{fraction}} du contenu, un {{prix}} au litre, un {{nombre}} de récipients.\nOn calcule chacune séparément, puis on vérifie par un {{ordre de grandeur}} et l'on rédige une phrase réponse."],
  ],
  exos: [
    { pts: 4, c: "Une citerne mesure 2,5 m sur 1,8 m sur 1,2 m. Quel est son volume en litres ?",
      r: "2,5 × 1,8 × 1,2 = 5,4 m³, soit [[5 400 litres]]." },
    { pts: 4, c: "Elle est remplie aux deux tiers. Quelle quantité d'eau contient-elle ?",
      r: "5 400 ÷ 3 = 1 800 ; 1 800 × 2 = [[3 600 litres]]." },
    { pts: 4, c: "Une caisse mesure 60 cm sur 40 cm sur 30 cm. Quel est son volume en litres ?",
      r: "72 000 cm³ = 72 dm³ = [[72 litres]]." },
    { pts: 4, c: "Une piscine de 8 m sur 4 m sur 1,5 m se remplit à 500 litres par minute. Combien de temps faut-il ?",
      r: "48 m³ = 48 000 litres ; 48 000 ÷ 500 = [[96 minutes]], soit 1 h 36 min." },
    { pts: 4, c: "Un grenier de 6 m sur 4 m sur 2,5 m reçoit des sacs de 0,05 m³. Combien en tient-il ?",
      r: "Volume : 60 m³. 60 ÷ 0,05 = [[1 200 sacs]]." },
  ],
},

{
  ch: "Masses et durées",
  titre: "Les unités de masse",
  objectif: "À la fin de la séance, l'élève est capable de convertir une masse d'une unité à une autre et d'employer la tonne.",
  materiel: "Balance, poids, sacs, tableau de conversion",
  rev: [["Calcule 2,5 × 1 000.", "2 500."],
        ["Calcule 450 ÷ 1 000.", "0,45."],
        ["Quelle est l'unité principale de longueur ?", "Le mètre."]],
  mise: { q: "Un sac de riz de 50 kg et un camion de 3 tonnes : comment comparer ces deux masses ?", ra: "En les exprimant dans la même unité." },
  obs: "Observez le tableau de conversion des masses : kilogramme, hectogramme, décagramme, gramme, décigramme, centigramme, milligramme, avec 2,5 placé dans la colonne des kilogrammes.",
  ana: [
    ["Quelle est l'unité principale de masse ?", "Le gramme."],
    ["Quelle unité emploie-t-on couramment ?", "Le kilogramme."],
    ["Combien de grammes dans un kilogramme ?", "Mille."],
    ["Chaque unité vaut combien de fois la suivante ?", "Dix fois."],
    ["Que vaut 2,5 kg en grammes ?", "Deux mille cinq cents grammes."],
    ["Quelle unité pour les grandes masses ?", "La tonne."],
    ["Combien de kilogrammes dans une tonne ?", "Mille."],
    ["Que vaut 2,5 tonnes en kilogrammes ?", "Deux mille cinq cents kilogrammes."],
  ],
  syn: "Donc, l'unité principale de masse est le gramme, et chaque unité du tableau vaut dix fois la suivante. Le kilogramme vaut mille grammes et la tonne mille kilogrammes. Pour convertir vers une unité plus petite on multiplie, vers une unité plus grande on divise.",
  attention: "Ne confondez pas la tonne et le kilogramme. Une tonne vaut mille kilogrammes : un camion de trois tonnes transporte trois mille kilogrammes, non trois mille grammes.",
  astuce: "Pour les produits du marché, retenez les repères : un sac de riz pèse 50 kg, un litre d'eau pèse 1 kg, une tablette de chocolat environ 100 g.",
  app: [
    { c: "Convertis en kilogrammes :\n1. 1 tonne\n2. 2,5 tonnes\n3. 450 g\n4. 3 500 g",
      r: "1. [[1 000 kg]]\n2. [[2 500 kg]]\n3. [[0,45 kg]]\n4. [[3,5 kg]]" },
    { c: "Convertis :\n1. 1 kg en grammes\n2. 2,4 kg en grammes\n3. 750 g en kilogrammes\n4. 0,3 t en kilogrammes",
      r: "1. [[1 000 g]]\n2. [[2 400 g]]\n3. [[0,75 kg]]\n4. [[300 kg]]" },
  ],
  evalx: [
    { c: "Range dans l'ordre croissant : 1,5 kg ; 900 g ; 0,8 kg ; 1 200 g.\n1. Convertis tout en grammes.\n2. Range les valeurs.\n3. Quelle est la plus grande masse ?\n4. La plus petite ?",
      r: "1. [[1 500 g ; 900 g ; 800 g ; 1 200 g]]\n2. [[800 < 900 < 1 200 < 1 500]]\n3. [[1,5 kg]]\n4. [[0,8 kg]]" },
    { c: "Un camion transporte 12 sacs de riz de 25 kg chacun.\n1. Quelle masse totale ?\n2. Exprime-la en tonnes.\n3. Le camion peut porter 2 tonnes : est-ce suffisant ?\n4. Combien de sacs au maximum ?",
      r: "1. [[300 kg]]\n2. [[0,3 tonne]]\n3. [[Oui]], largement\n4. [[80 sacs]]" },
  ],
  lecon: [
    ["1. Le gramme et le kilogramme", "L'unité principale de masse est le {{gramme}}, noté g.\nDans la vie courante, on emploie surtout le {{kilogramme}} : 1 kg = {{1 000 g}}."],
    ["2. Le tableau de conversion", "Les unités se rangent dans l'ordre décroissant : kilogramme, hectogramme, décagramme, gramme, décigramme, centigramme, milligramme.\nChaque unité vaut {{dix fois}} celle qui la suit.\nOn {{multiplie}} vers les petites unités, on {{divise}} vers les grandes."],
    ["3. La tonne", "Pour les grandes masses — camions, récoltes, marchandises — on emploie la {{tonne}}, notée t :\n{{1 t = 1 000 kg}}.\nUn camion de 2,5 tonnes transporte 2 500 kg."],
    ["4. Comparer des masses", "Deux masses ne se comparent qu'exprimées dans la {{même unité}}.\nPour classer 1,5 kg, 900 g, 0,8 kg et 1 200 g, on convertit tout en grammes : 1 500, 900, 800 et 1 200."],
  ],
  exos: [
    { pts: 4, c: "Convertis en kilogrammes : 1 tonne, 2,5 tonnes, 450 g, 3 500 g.",
      r: "[[1 000 kg]] ; [[2 500 kg]] ; [[0,45 kg]] ; [[3,5 kg]]." },
    { pts: 4, c: "Convertis 2,4 kg en grammes et 750 g en kilogrammes.",
      r: "[[2 400 g]] et [[0,75 kg]]." },
    { pts: 4, c: "Un camion transporte 12 sacs de riz de 25 kg. Quelle masse totale, en kilogrammes puis en tonnes ?",
      r: "12 × 25 = [[300 kg]], soit [[0,3 tonne]]." },
    { pts: 4, c: "Range dans l'ordre croissant : 1,5 kg ; 900 g ; 0,8 kg ; 1 200 g.",
      r: "[[0,8 kg < 900 g < 1 200 g < 1,5 kg]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 1 t = 100 kg. 2. 1 kg = 1 000 g. 3. 450 g valent 0,45 kg. 4. On divise pour passer des grammes aux kilogrammes.",
      r: "1. [[Faux]] : 1 000 kg. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Masses et durées",
  titre: "Masse nette, masse brute et tare",
  objectif: "À la fin de la séance, l'élève est capable de distinguer masse brute, masse nette et tare, et de calculer l'une à partir des deux autres.",
  materiel: "Balance, caisses vides, marchandises, ardoises",
  rev: [["Combien de grammes dans 1 kg ?", "Mille."],
        ["Convertis 2,5 t en kilogrammes.", "2 500 kg."],
        ["Calcule 45 − 3,5.", "41,5."]],
  mise: { q: "Quand on pèse une caisse de tomates, pèse-t-on seulement les tomates ?", ra: "Non, la caisse compte aussi." },
  obs: "Observez la pesée : la caisse vide marque 3,5 kg sur la balance ; remplie de tomates, elle marque 45 kg.",
  ana: [
    ["Que marque la balance avec la caisse pleine ?", "Quarante-cinq kilogrammes."],
    ["Comment nomme-t-on cette masse ?", "La masse brute."],
    ["Que marque la caisse vide ?", "Trois kilogrammes et demi."],
    ["Comment nomme-t-on cette masse ?", "La tare."],
    ["Quelle est la masse des tomates seules ?", "Quarante et un kilogrammes et demi."],
    ["Comment l'a-t-on obtenue ?", "Par une soustraction."],
    ["Comment nomme-t-on cette masse ?", "La masse nette."],
    ["Quelle relation lie les trois ?", "La brute est la somme de la nette et de la tare."],
  ],
  syn: "Donc, la masse brute est celle de la marchandise avec son emballage ; la tare est la masse de l'emballage seul ; la masse nette est celle de la marchandise seule. La masse brute est égale à la masse nette augmentée de la tare, et la masse nette s'obtient par soustraction.",
  attention: "C'est la masse nette que l'on paie, non la masse brute. Un commerçant honnête déduit toujours la tare de la pesée.",
  astuce: "Retenez la relation sous forme d'une seule égalité : brute égale nette plus tare. Les deux autres formules s'en déduisent par soustraction.",
  app: [
    { c: "Une caisse pleine pèse 45 kg et la caisse vide 3,5 kg.\n1. Quelle est la masse brute ?\n2. Quelle est la tare ?\n3. Quelle est la masse nette ?\n4. Quelle opération as-tu faite ?",
      r: "1. [[45 kg]]\n2. [[3,5 kg]]\n3. [[41,5 kg]]\n4. Une [[soustraction]]" },
    { c: "Complète :\n1. Masse brute = nette + ……\n2. Masse nette = brute − ……\n3. Tare = brute − ……\n4. Laquelle paie-t-on ?",
      r: "1. [[tare]]\n2. [[tare]]\n3. [[nette]]\n4. La masse [[nette]]" },
  ],
  evalx: [
    { c: "Un sac de riz brut pèse 51 kg, la toile pesant 1 kg.\n1. Quelle est la masse nette ?\n2. Pour 10 sacs, quelle masse nette ?\n3. Quelle masse brute ?\n4. Quelle tare totale ?",
      r: "1. [[50 kg]]\n2. [[500 kg]]\n3. [[510 kg]]\n4. [[10 kg]]" },
    { c: "Un camion vide pèse 3,2 tonnes ; chargé, il pèse 8 tonnes.\n1. Quelle est la masse brute ?\n2. Quelle est la tare ?\n3. Quelle est la masse nette du chargement ?\n4. Exprime-la en kilogrammes.",
      r: "1. [[8 tonnes]]\n2. [[3,2 tonnes]]\n3. [[4,8 tonnes]]\n4. [[4 800 kg]]" },
  ],
  lecon: [
    ["1. Les trois masses", "Lorsqu'on pèse une marchandise emballée, on distingue trois masses :\n— la masse {{brute}}, celle de la marchandise avec son emballage ;\n— la {{tare}}, celle de l'emballage seul ;\n— la masse {{nette}}, celle de la marchandise seule."],
    ["2. La relation fondamentale", "Ces trois masses sont liées par une seule égalité :\n{{masse brute = masse nette + tare}}.\nOn en déduit : masse nette = brute − tare, et tare = brute − nette."],
    ["3. Un exemple", "Une caisse de tomates pèse 45 kg pleine et 3,5 kg vide.\nLa masse brute vaut 45 kg, la tare 3,5 kg, et la masse nette 45 − 3,5 = {{41,5 kg}}."],
    ["4. Dans le commerce", "C'est la masse {{nette}} qui est facturée, car le client n'achète pas l'emballage.\nUn commerçant qui vend un sac de 51 kg brut, dont 1 kg de toile, ne facture que {{50 kg}} de riz."],
  ],
  exos: [
    { pts: 4, c: "Une caisse pleine pèse 45 kg, la caisse vide 3,5 kg. Quelle est la masse nette ?",
      r: "45 − 3,5 = [[41,5 kg]]." },
    { pts: 4, c: "Énonce la relation entre masse brute, masse nette et tare.",
      r: "[[Masse brute = masse nette + tare]]." },
    { pts: 4, c: "Un sac de riz brut pèse 51 kg, la toile 1 kg. Quelle masse nette pour 10 sacs ?",
      r: "Un sac : 50 kg net. Dix sacs : [[500 kg]]." },
    { pts: 4, c: "Un camion vide pèse 3,2 t ; chargé, 8 t. Quelle est la masse nette du chargement en kilogrammes ?",
      r: "8 − 3,2 = 4,8 t, soit [[4 800 kg]]." },
    { pts: 4, c: "Vrai ou faux ? 1. On paie la masse brute. 2. La tare est l'emballage. 3. Brute = nette + tare. 4. La masse nette est toujours la plus grande.",
      r: "1. [[Faux]] : on paie la nette. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : la brute est la plus grande." },
  ],
},
{
  ch: "Masses et durées",
  titre: "Les unités de durée",
  objectif: "À la fin de la séance, l'élève est capable de convertir une durée d'une unité à une autre.",
  materiel: "Horloge, chronomètre, ardoises",
  rev: [["Combien de minutes dans une heure ?", "Soixante."],
        ["Calcule 2 × 60.", "120."],
        ["Calcule 150 ÷ 60.", "2 et il reste 30."]],
  mise: { q: "Pourquoi ne convertit-on pas les heures en minutes en multipliant par cent ?", ra: "Parce qu'une heure vaut soixante minutes, non cent." },
  obs: "Observez l'horloge au tableau et les égalités écrites à côté : une heure vaut soixante minutes, une minute soixante secondes, un jour vingt-quatre heures.",
  ana: [
    ["Combien de secondes dans une minute ?", "Soixante."],
    ["Combien de minutes dans une heure ?", "Soixante."],
    ["Combien d'heures dans un jour ?", "Vingt-quatre."],
    ["Ces nombres sont-ils des puissances de dix ?", "Non, ce sont soixante et vingt-quatre."],
    ["Que vaut 2 h 30 en minutes ?", "Cent cinquante minutes."],
    ["Comment l'a-t-on calculé ?", "Deux fois soixante, plus trente."],
    ["Que vaut 90 minutes en heures ?", "Une heure et demie."],
    ["Comment nomme-t-on ce système ?", "Le système sexagésimal."],
  ],
  syn: "Donc, les durées ne suivent pas le système décimal. Une minute vaut soixante secondes, une heure soixante minutes et un jour vingt-quatre heures. Pour convertir des heures en minutes on multiplie par soixante, et l'opération inverse se fait par une division euclidienne dont le reste donne les minutes.",
  attention: "Deux heures et demie s'écrivent 2 h 30, non 2,5 h dans un calcul de durée. Écrire 2,50 h et le traiter comme 250 minutes serait une erreur.",
  astuce: "Pour convertir des minutes en heures, faites une division euclidienne par soixante : le quotient donne les heures et le reste les minutes.",
  app: [
    { c: "Convertis en minutes :\n1. 1 heure\n2. 2 h 30\n3. 3 h 45\n4. 4 heures",
      r: "1. [[60 min]]\n2. [[150 min]]\n3. [[225 min]]\n4. [[240 min]]" },
    { c: "Convertis :\n1. 90 minutes en heures\n2. 120 minutes en heures\n3. 200 minutes en heures et minutes\n4. 1 jour en heures",
      r: "1. [[1 h 30]]\n2. [[2 heures]]\n3. [[3 h 20]]\n4. [[24 heures]]" },
  ],
  evalx: [
    { c: "Convertis :\n1. 2 minutes en secondes\n2. 180 secondes en minutes\n3. 5 h 15 en minutes\n4. 400 minutes en heures et minutes",
      r: "1. [[120 s]]\n2. [[3 minutes]]\n3. [[315 min]]\n4. [[6 h 40]]" },
    { c: "Complète :\n1. 1 minute = …… secondes\n2. 1 heure = …… minutes\n3. 1 jour = …… heures\n4. Les durées suivent-elles le système décimal ?",
      r: "1. [[60]]\n2. [[60]]\n3. [[24]]\n4. [[Non]]" },
  ],
  lecon: [
    ["1. Un système particulier", "Contrairement aux longueurs et aux masses, les durées ne suivent pas le système {{décimal}}.\nLes égalités fondamentales sont :\n1 minute = {{60}} secondes ; 1 heure = {{60}} minutes ; 1 jour = {{24}} heures."],
    ["2. Des heures aux minutes", "Pour convertir une durée en minutes, on {{multiplie}} le nombre d'heures par 60 et l'on ajoute les minutes restantes.\n2 h 30 = 2 × 60 + 30 = 150 minutes.\n3 h 45 = 180 + 45 = 225 minutes."],
    ["3. Des minutes aux heures", "On effectue une {{division euclidienne}} par 60 : le {{quotient}} donne les heures et le {{reste}} les minutes.\n200 ÷ 60 donne 3 et il reste 20 : 200 minutes valent 3 h 20."],
    ["4. Écrire correctement une durée", "Une durée s'écrit 2 h 30 et non 2,5 h dans les calculs.\nLa forme {{décimale}} prête à confusion : 2,50 traité comme 250 minutes conduirait à une erreur grossière."],
  ],
  exos: [
    { pts: 4, c: "Convertis en minutes : 2 h 30 et 3 h 45.",
      r: "[[150 minutes]] et [[225 minutes]]." },
    { pts: 4, c: "Convertis 200 minutes en heures et minutes.",
      r: "200 ÷ 60 = 3 reste 20, soit [[3 h 20]]." },
    { pts: 4, c: "Combien de secondes dans 2 minutes, et combien de minutes dans 180 secondes ?",
      r: "[[120 secondes]] et [[3 minutes]]." },
    { pts: 4, c: "Convertis 400 minutes en heures et minutes.",
      r: "400 ÷ 60 = 6 reste 40, soit [[6 h 40]]." },
    { pts: 4, c: "Vrai ou faux ? 1. 1 heure vaut 100 minutes. 2. 1 jour vaut 24 heures. 3. 90 minutes valent 1 h 30. 4. On écrit 2,5 h dans un calcul de durée.",
      r: "1. [[Faux]] : 60 minutes. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Faux]] : on écrit 2 h 30." },
  ],
},
{
  ch: "Masses et durées",
  titre: "Additionner et soustraire des durées",
  objectif: "À la fin de la séance, l'élève est capable d'additionner et de soustraire des durées exprimées en heures et minutes.",
  materiel: "Horloge, horaires de transport, ardoises",
  rev: [["Convertis 2 h 30 en minutes.", "150 minutes."],
        ["Convertis 90 minutes en heures.", "1 h 30."],
        ["Combien de minutes dans une heure ?", "Soixante."]],
  mise: { q: "Un trajet de 7 h 15 suivi d'une pause de 2 h 50 : combien de temps en tout ?", ra: "Dix heures et cinq minutes." },
  obs: "Observez la pose au tableau : 7 h 15 additionné à 2 h 50 donne d'abord 9 h 65, que l'enseignant transforme ensuite en 10 h 05.",
  ana: [
    ["Que donne l'addition des heures ?", "Neuf heures."],
    ["Et celle des minutes ?", "Soixante-cinq minutes."],
    ["Ce résultat est-il correct tel quel ?", "Non, il dépasse soixante."],
    ["Que faut-il faire ?", "Convertir soixante minutes en une heure."],
    ["Quel est le résultat final ?", "Dix heures et cinq minutes."],
    ["Comment nomme-t-on cette opération ?", "Une retenue."],
    ["Pour une soustraction, que faire si les minutes manquent ?", "Emprunter une heure, soit soixante minutes."],
  ],
  syn: "Donc, pour additionner des durées, on additionne séparément les heures et les minutes ; si les minutes dépassent soixante, on convertit soixante minutes en une heure. Pour soustraire, si les minutes du premier terme sont insuffisantes, on emprunte une heure que l'on convertit en soixante minutes.",
  attention: "La retenue vaut soixante, non dix. Une addition donnant 9 h 65 doit être corrigée en 10 h 05 : oublier cette conversion est l'erreur la plus fréquente.",
  astuce: "Une autre méthode consiste à tout convertir en minutes, à calculer, puis à reconvertir. Elle est plus longue mais évite toute erreur de retenue.",
  app: [
    { c: "Calcule :\n1. 7 h 15 + 2 h 50\n2. 3 h 40 + 1 h 35\n3. 2 h 20 + 4 h 45\n4. 1 h 50 + 2 h 10",
      r: "1. [[10 h 05]]\n2. [[5 h 15]]\n3. [[7 h 05]]\n4. [[4 heures]]" },
    { c: "Un bus part à 8 h 45 et arrive à 14 h 20.\n1. Convertis chaque horaire en minutes.\n2. Quelle est la différence ?\n3. Exprime-la en heures et minutes.\n4. Combien de temps si le retour dure 30 minutes de plus ?",
      r: "1. [[525 min]] et [[860 min]]\n2. [[335 minutes]]\n3. [[5 h 35]]\n4. [[6 h 05]]" },
  ],
  evalx: [
    { c: "Calcule :\n1. 5 h 30 − 2 h 45\n2. 9 h 10 − 3 h 25\n3. 6 h − 1 h 40\n4. 4 h 15 − 1 h 15",
      r: "1. [[2 h 45]]\n2. [[5 h 45]]\n3. [[4 h 20]]\n4. [[3 heures]]" },
    { c: "Un élève travaille 1 h 45 le matin et 2 h 30 l'après-midi.\n1. Quelle durée totale ?\n2. Exprime-la en minutes.\n3. Combien lui manque-t-il pour 5 heures ?\n4. Rédige la phrase réponse.",
      r: "1. [[4 h 15]]\n2. [[255 minutes]]\n3. [[45 minutes]]\n4. « [[Il a travaillé 4 h 15 au total.]] »" },
  ],
  lecon: [
    ["1. Additionner des durées", "On additionne séparément les {{heures}} entre elles et les {{minutes}} entre elles.\n7 h 15 + 2 h 50 donne d'abord 9 h 65."],
    ["2. La retenue", "Un résultat comportant plus de {{60}} minutes doit être corrigé : on retranche 60 minutes et l'on ajoute {{une heure}}.\n9 h 65 devient donc 10 h 05.\nLa retenue vaut ici {{soixante}} et non dix."],
    ["3. Soustraire des durées", "On soustrait de même les heures et les minutes.\nSi les minutes du premier terme sont insuffisantes, on {{emprunte}} une heure, que l'on convertit en 60 minutes.\n5 h 30 − 2 h 45 : on écrit 4 h 90 − 2 h 45 = 2 h 45."],
    ["4. L'autre méthode", "On peut aussi convertir les deux durées en {{minutes}}, effectuer l'opération, puis reconvertir.\nDe 8 h 45 à 14 h 20 : 860 − 525 = 335 minutes, soit 5 h 35."],
  ],
  exos: [
    { pts: 4, c: "Calcule 7 h 15 + 2 h 50.",
      r: "9 h 65, soit [[10 h 05]] après conversion de la retenue." },
    { pts: 4, c: "Calcule 5 h 30 − 2 h 45.",
      r: "On emprunte une heure : 4 h 90 − 2 h 45 = [[2 h 45]]." },
    { pts: 4, c: "Un bus part à 8 h 45 et arrive à 14 h 20. Quelle est la durée du trajet ?",
      r: "860 − 525 = 335 minutes, soit [[5 h 35]]." },
    { pts: 4, c: "Un élève travaille 1 h 45 puis 2 h 30. Quelle est la durée totale ?",
      r: "3 h 75, soit [[4 h 15]]." },
    { pts: 4, c: "Vrai ou faux ? 1. La retenue vaut 10. 2. 9 h 65 s'écrit 10 h 05. 3. On peut tout convertir en minutes. 4. 6 h − 1 h 40 = 4 h 20.",
      r: "1. [[Faux]] : elle vaut 60. 2. [[Vrai]]. 3. [[Vrai]]. 4. [[Vrai]]." },
  ],
},
{
  ch: "Masses et durées",
  titre: "Horaires, durées et vitesse",
  objectif: "À la fin de la séance, l'élève est capable de calculer une durée à partir de deux horaires et de relier distance, durée et vitesse.",
  materiel: "Horaires de taxi-brousse, horloge, ardoises",
  rev: [["Calcule 14 h 20 − 8 h 45.", "5 h 35."],
        ["Calcule 240 ÷ 4.", "60."],
        ["Calcule 60 × 7.", "420."]],
  mise: { q: "Un taxi-brousse part à 6 h et parcourt 240 km en 4 heures. Quelle distance parcourt-il en une heure ?", ra: "Soixante kilomètres." },
  obs: "Observez au tableau les données du trajet : départ 6 h, arrivée 10 h, distance 240 km, et le calcul 240 divisé par 4.",
  ana: [
    ["Quelle est la durée du trajet ?", "Quatre heures."],
    ["Comment l'a-t-on obtenue ?", "Par une soustraction des horaires."],
    ["Quelle distance en une heure ?", "Soixante kilomètres."],
    ["Comment nomme-t-on cette grandeur ?", "La vitesse moyenne."],
    ["En quelle unité s'exprime-t-elle ?", "En kilomètres par heure."],
    ["Quelle distance en sept heures ?", "Quatre cent vingt kilomètres."],
    ["S'agit-il d'une proportionnalité ?", "Oui, à vitesse constante."],
    ["Comment trouver la durée d'un trajet de 300 km ?", "En divisant 300 par 60."],
  ],
  syn: "Donc, la durée d'un trajet s'obtient en soustrayant l'horaire de départ de l'horaire d'arrivée. La vitesse moyenne est la distance parcourue en une heure : on l'obtient en divisant la distance par la durée. À vitesse constante, distance et durée sont proportionnelles.",
  attention: "La vitesse s'exprime en kilomètres par heure : la durée doit donc être en heures. Une durée de 90 minutes doit d'abord être convertie en 1,5 heure.",
  astuce: "Trois questions, trois opérations : la vitesse par une division, la distance par une multiplication, la durée par une division. L'unité du résultat indique si l'on ne s'est pas trompé.",
  app: [
    { c: "Un taxi-brousse part à 6 h et arrive à 10 h après 240 km.\n1. Quelle est la durée ?\n2. Quelle est la vitesse moyenne ?\n3. Quelle distance en 7 heures ?\n4. Quelle durée pour 300 km ?",
      r: "1. [[4 heures]]\n2. [[60 km par heure]]\n3. [[420 km]]\n4. [[5 heures]]" },
    { c: "Un cycliste roule à 15 km par heure.\n1. Quelle distance en 2 heures ?\n2. En 3 h 30 ?\n3. Quelle durée pour 45 km ?\n4. Pour 60 km ?",
      r: "1. [[30 km]]\n2. [[52,5 km]]\n3. [[3 heures]]\n4. [[4 heures]]" },
  ],
  evalx: [
    { c: "Un train part de la gare à 7 h 30 et arrive à 11 h 15.\n1. Quelle est la durée du trajet ?\n2. Exprime-la en minutes.\n3. Il a parcouru 150 km : quelle est sa vitesse moyenne ?\n4. Arrondis au kilomètre par heure.",
      r: "1. [[3 h 45]]\n2. [[225 minutes]]\n3. [[150 ÷ 3,75]]\n4. [[40 km par heure]]" },
    { c: "Complète :\n1. La vitesse s'obtient en …… la distance par la durée.\n2. La distance s'obtient en …… la vitesse par la durée.\n3. La vitesse s'exprime en ……\n4. La durée doit être en ……",
      r: "1. [[divisant]]\n2. [[multipliant]]\n3. [[km par heure]]\n4. [[heures]]" },
  ],
  lecon: [
    ["1. Calculer une durée", "La {{durée}} d'un trajet s'obtient en {{soustrayant}} l'horaire de départ de l'horaire d'arrivée.\nD'un départ à 6 h à une arrivée à 10 h, la durée est de 4 heures."],
    ["2. La vitesse moyenne", "La {{vitesse moyenne}} est la distance parcourue en {{une heure}}.\nOn l'obtient en {{divisant}} la distance par la durée :\n240 km en 4 heures donnent 240 ÷ 4 = 60 km par heure."],
    ["3. Calculer une distance", "Connaissant la vitesse et la durée, on obtient la distance en les {{multipliant}}.\nÀ 60 km par heure pendant 7 heures : 60 × 7 = 420 km."],
    ["4. Calculer une durée à partir de la vitesse", "Connaissant la distance et la vitesse, on obtient la durée par une {{division}} :\n300 km à 60 km par heure demandent 300 ÷ 60 = 5 heures.\nÀ vitesse constante, distance et durée sont {{proportionnelles}}."],
  ],
  exos: [
    { pts: 4, c: "Un taxi-brousse parcourt 240 km en 4 heures. Quelle est sa vitesse moyenne ?",
      r: "240 ÷ 4 = [[60 km par heure]]." },
    { pts: 4, c: "À cette vitesse, quelle distance parcourt-il en 7 heures ?",
      r: "60 × 7 = [[420 km]]." },
    { pts: 4, c: "Un train part à 7 h 30 et arrive à 11 h 15. Quelle est la durée du trajet ?",
      r: "11 h 15 − 7 h 30 = [[3 h 45]], soit 225 minutes." },
    { pts: 4, c: "Un cycliste roule à 15 km par heure. Combien de temps pour parcourir 45 km ?",
      r: "45 ÷ 15 = [[3 heures]]." },
    { pts: 4, c: "Vrai ou faux ? 1. La vitesse est une division. 2. La distance est une multiplication. 3. La durée peut rester en minutes. 4. À vitesse constante, distance et durée sont proportionnelles.",
      r: "1. [[Vrai]]. 2. [[Vrai]]. 3. [[Faux]] : il faut convertir en heures. 4. [[Vrai]]." },
  ],
},
{
  ch: "Masses et durées",
  titre: "Problèmes de masses et de durées",
  objectif: "À la fin de la séance, l'élève est capable de résoudre un problème concret faisant intervenir des masses ou des durées.",
  materiel: "Énoncés au tableau, cahier de recherche",
  rev: [["Convertis 2,5 t en kilogrammes.", "2 500 kg."],
        ["Calcule 7 h 15 + 2 h 50.", "10 h 05."],
        ["Qu'est-ce que la masse nette ?", "La masse de la marchandise seule."]],
  mise: { q: "Un transporteur doit livrer du riz avant la fermeture du marché. Que doit-il calculer ?", ra: "La masse à charger et la durée du trajet." },
  obs: "Lisez l'énoncé au tableau : « Un camion charge 45 sacs de riz de 50 kg. Il part à 5 h 30 et roule 320 km à 80 km par heure. »",
  ana: [
    ["Quelle est la masse totale chargée ?", "Deux mille deux cent cinquante kilogrammes."],
    ["Exprime-la en tonnes.", "Deux virgule vingt-cinq tonnes."],
    ["Quelle est la durée du trajet ?", "Quatre heures."],
    ["Comment l'a-t-on calculée ?", "En divisant 320 par 80."],
    ["À quelle heure arrive-t-il ?", "À neuf heures trente."],
    ["Comment l'a-t-on obtenu ?", "En ajoutant la durée à l'horaire de départ."],
    ["Combien d'étapes ce problème comporte-t-il ?", "Trois."],
    ["Comment vérifier la vraisemblance ?", "Par un ordre de grandeur."],
  ],
  syn: "Donc, un problème de masses ou de durées se résout étape par étape : on calcule d'abord la grandeur demandée dans son unité propre, on convertit si nécessaire, puis on enchaîne les opérations. Les durées se traitent en heures et minutes, jamais en écriture décimale, et le résultat se contrôle par un ordre de grandeur.",
  attention: "N'additionnez jamais des grandeurs de natures différentes. Une masse et une durée ne s'additionnent pas : chaque calcul se mène séparément, dans son unité.",
  app: [
    { c: "Un camion charge 45 sacs de 50 kg, part à 5 h 30 et roule 320 km à 80 km par heure.\n1. Quelle masse totale ?\n2. En tonnes ?\n3. Quelle durée de trajet ?\n4. À quelle heure arrive-t-il ?",
      r: "1. [[2 250 kg]]\n2. [[2,25 tonnes]]\n3. [[4 heures]]\n4. À [[9 h 30]]" },
    { c: "Une commerçante achète 8 caisses de tomates. Chaque caisse pèse 22 kg brut, la tare étant de 2 kg.\n1. Masse nette d'une caisse ?\n2. Masse nette totale ?\n3. Masse brute totale ?\n4. Prix à 1 800 ariary le kilogramme net ?",
      r: "1. [[20 kg]]\n2. [[160 kg]]\n3. [[176 kg]]\n4. [[288 000 ariary]]" },
  ],
  evalx: [
    { c: "Un atelier ouvre à 7 h 45 et ferme à 17 h 15, avec une pause de 1 h 30.\n1. Quelle amplitude entre l'ouverture et la fermeture ?\n2. Quelle durée de travail effectif ?\n3. Exprime-la en minutes.\n4. Rédige la phrase réponse.",
      r: "1. [[9 h 30]]\n2. [[8 heures]]\n3. [[480 minutes]]\n4. « [[La durée de travail effectif est de 8 heures.]] »" },
    { c: "Un producteur récolte 1,8 tonne de manioc et en vend les trois quarts.\n1. Convertis la récolte en kilogrammes.\n2. Quelle masse vendue ?\n3. Quelle masse restante ?\n4. Prix de la vente à 900 ariary le kilogramme ?",
      r: "1. [[1 800 kg]]\n2. [[1 350 kg]]\n3. [[450 kg]]\n4. [[1 215 000 ariary]]" },
  ],
  lecon: [
    ["1. Repérer la grandeur", "On identifie d'abord la {{nature}} de ce qui est demandé : une masse, une durée, un horaire ou un prix.\nChaque grandeur se calcule dans son unité propre et ne s'additionne qu'avec une grandeur de même nature."],
    ["2. Les problèmes de masse", "On calcule la masse totale par une {{multiplication}}, puis on convertit si besoin en tonnes.\n45 sacs de 50 kg pèsent 2 250 kg, soit 2,25 tonnes.\nLorsqu'un emballage intervient, on distingue masse {{brute}}, {{tare}} et masse {{nette}}."],
    ["3. Les problèmes de durée", "On calcule la durée par une {{soustraction}} d'horaires, ou par une division de la distance par la vitesse.\nUn trajet de 320 km à 80 km par heure dure 4 heures.\nL'heure d'arrivée s'obtient en {{ajoutant}} la durée à l'horaire de départ : 5 h 30 + 4 h = 9 h 30."],
    ["4. Contrôler et conclure", "On vérifie par un {{ordre de grandeur}} : une arrivée avant le départ ou une masse de plusieurs milliers de tonnes doivent alerter.\nOn termine par une {{phrase réponse}} portant l'unité."],
  ],
  exos: [
    { pts: 4, c: "Un camion charge 45 sacs de 50 kg. Quelle masse totale, en kilogrammes puis en tonnes ?",
      r: "45 × 50 = [[2 250 kg]], soit [[2,25 tonnes]]." },
    { pts: 4, c: "Il part à 5 h 30 et roule 320 km à 80 km par heure. À quelle heure arrive-t-il ?",
      r: "Durée : 320 ÷ 80 = 4 heures. Arrivée : [[9 h 30]]." },
    { pts: 4, c: "Huit caisses pèsent 22 kg brut chacune, la tare étant de 2 kg. Quelle est la masse nette totale ?",
      r: "20 kg net par caisse ; 8 × 20 = [[160 kg]]." },
    { pts: 4, c: "Un atelier ouvre à 7 h 45 et ferme à 17 h 15, avec 1 h 30 de pause. Quelle est la durée de travail effectif ?",
      r: "Amplitude : 9 h 30. Travail effectif : 9 h 30 − 1 h 30 = [[8 heures]]." },
    { pts: 4, c: "Un producteur récolte 1,8 tonne de manioc et en vend les trois quarts. Quelle masse a-t-il vendue ?",
      r: "1 800 kg ; les trois quarts font [[1 350 kg]]." },
  ],
},

];
