// Sary faha-2 isaky ny seho (apetraka ao amin'ny LESONA, aorian'ny votoaty)
module.exports = {
  1:  { image: "images/img2_s01.png", legende: "Ny dingana mankany amin'ny fahalalana ara-tantara" },
  2:  { image: "images/img2_s02.png", legende: "Nahoana isika no mianatra Tantara ? Ireo tanjona efatra" },
  3:  { image: "images/img2_s03.png", legende: "Ohatra : frizin'ny fiainan'ny mpianatra iray" },
  4:  { image: "images/img2_s04.png", legende: "Ireo fanontaniana dinihina rehefa mandalina loharano" },
  5:  { image: "images/img2_s05.png", legende: "Fampitahana : loharano mivantana sy loharano tsy mivantana" },
  7:  { image: "images/img2_s07.png", legende: "Ireo Repoblika efatra sy ny filoha voalohany tamin'izy ireo" },
  8:  { image: "images/img2_s08.png", legende: "Frizy : ny Repoblika voalohany (1958-1972)" },
  9:  { image: "images/img2_s09.png", legende: "Ireo mpitondra miaramila nifandimby (1972-1975)" },
  10: { image: "images/img2_s10.png", legende: "Ireo singa nampiavaka ny Repoblika faharoa" },
  11: { image: "images/img2_s11.png", legende: "Ireo filoha nifandimby tamin'ny Repoblika fahatelo" },
  12: { image: "images/img2_s12.png", legende: "Ny zava-nitranga tamin'ny volana oktobra 2025" },
  13: { image: "images/img2_s13.png", legende: "Ohatra amin'ireo andrim-panjakana fototra" },
  14: { image: "images/img2_s14.png", legende: "Ny filamatra (devise) nifandimbiasan'ireo Repoblika" },
  15: { image: "images/img2_s15.png", legende: "Ohatra : politika ara-tsosialy sy ara-toekarena nifandimby" },
  16: { image: "images/img2_s16.png", legende: "Ny vokatry ny krizy politika teo amin'ny fiainam-pirenena" },
  18: { image: "images/img2_s18.png", legende: "Ireo endri-pifandraisana efatra amin'ny firenena hafa" },
  19: { image: "images/img2_s19.png", legende: "Frizy : ny fidiran'i Madagasikara tamin'ireo fikambanana" },
  20: { image: "images/img2_s20.png", legende: "Ny tombony sy ny fetran'ny fidirana amin'ny fikambanana" },
  22: { image: "images/img2_s22.png", legende: "Ireo karazam-bakoka telo" },
  23: { image: "images/img2_s23.png", legende: "Ireo fomba efatra hiarovana ny vakoka" },
  24: { image: "images/img2_s24.png", legende: "Ny sokajin'ny harem-pirenena" },
  25: { image: "images/img2_s25.png", legende: "Ny anjara birikin'ny tsirairay amin'ny fiarovana ny harem-pirenena" },
};
