// UNITÉ 3 — Le monde depuis 1945 (5 séances : 21 à 25)
const THEME = "Le monde depuis 1945";
const DOC_PROG = "Programme scolaire de la classe de 3ème, Histoire (MEN/DCI, édition 2015)";

module.exports = [
// =====================================================================
{
  num: 21, theme: THEME,
  titre: "La guerre froide (1) : la constitution des blocs et les affrontements (1947-1962)",
  objectif: "expliquer la constitution des deux blocs (doctrines Truman et Jdanov, plan Marshall, OTAN et pacte de Varsovie) et de décrire les principaux affrontements de la guerre froide : blocus de Berlin, guerre de Corée, mur de Berlin, crise de Cuba",
  documentation: `${DOC_PROG} ; A. Fontaine, Histoire de la guerre froide (1965-1967) ; G.-H. Soutou, La Guerre de Cinquante Ans (2001) ; P. Milza et S. Berstein, Histoire du XXe siècle, t. 2 ; discours de Truman (12 mars 1947) et rapport Jdanov (septembre 1947).`,
  image: { file: "blocs_guerre_froide.png", legende: "Carte schématique du monde bipolaire vers 1960 : bloc de l'Ouest, bloc de l'Est, principales crises de la guerre froide", widthCm: 14, source: "réalisation J-Learn d'après l'Atlas historique Duby et Milza-Berstein" },
  revision: [
    ["Quel est le bilan humain de la Deuxième Guerre mondiale ?", "50 à 60 millions de morts, dont une majorité de civils ; génocide de 5 à 6 millions de juifs."],
    ["Quand et pourquoi l'ONU a-t-elle été créée ?", "Le 26 juin 1945 (Charte de San Francisco), pour maintenir la paix."],
    ["Quelles sont les deux superpuissances en 1945 ?", "Les États-Unis et l'URSS."],
    ["Qu'ont décidé les conférences de Yalta et Potsdam pour l'Allemagne ?", "Sa division en quatre zones d'occupation."],
  ],
  miseEnSituation: {
    enseignant: [
      "Berlin, juin 1948. Staline coupe toutes les routes et voies ferrées menant aux secteurs occidentaux de la ville, enclavés dans la zone soviétique. Deux millions d'habitants risquent de mourir de faim. Pendant onze mois, les avions américains et britanniques se relaient jour et nuit, un atterrissage toutes les trois minutes, pour apporter charbon, farine et lait. Il y a trois ans, ces mêmes Alliés combattaient ensemble contre Hitler.",
      "Pourquoi les vainqueurs de 1945 sont-ils devenus ennemis si vite ? Pourquoi ne se font-ils pas directement la guerre ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : parce qu'ils ont des idées opposées, capitalisme contre communisme, et veulent chacun dominer l'Europe ; parce que la bombe atomique rendrait une guerre trop destructrice."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| | Bloc de l'Ouest | Bloc de l'Est |", "| Chef de file | États-Unis | URSS |", "| Idéologie | Démocratie libérale, capitalisme, libertés individuelles | Communisme, parti unique, économie planifiée |", "| Doctrine (1947) | Doctrine Truman (12 mars 1947) : « endiguement » (containment) du communisme ; aide aux « peuples libres » | Doctrine Jdanov (septembre 1947) : le monde est divisé en deux camps, « impérialiste » (États-Unis) et « anti-impérialiste » (URSS) |", "| Économie | Plan Marshall (juin 1947) : 13 milliards de dollars d'aide à la reconstruction de l'Europe occidentale (16 pays) | Refus du plan Marshall imposé aux pays de l'Est ; Kominform (1947) ; CAEM ou Comecon (1949) |", "| Alliance militaire | OTAN (4 avril 1949) : États-Unis, Canada, Europe de l'Ouest | Pacte de Varsovie (14 mai 1955) : URSS et démocraties populaires |", "| Territoires | Europe occidentale, Amérique, Japon, Australie ; réseau d'alliances (OTASE, pacte de Bagdad) | Europe de l'Est (Pologne, Tchécoslovaquie, Hongrie, Roumanie, Bulgarie, RDA), Chine (1949), Corée du Nord, Vietnam du Nord, Cuba (1961) |", "| Les grandes crises | | |", "| 1948-1949 | Blocus de Berlin (juin 1948-mai 1949) : pont aérien occidental ; 1949 : deux Allemagnes (RFA à l'Ouest, RDA à l'Est) | |", "| 1950-1953 | Guerre de Corée : la Corée du Nord communiste envahit le Sud ; intervention de l'ONU (États-Unis) puis de la Chine ; armistice de 1953 sur le 38e parallèle ; 2 à 3 millions de morts | |", "| 1961 | Construction du mur de Berlin (13 août 1961) pour arrêter la fuite des Allemands de l'Est vers l'Ouest | |", "| 1962 | Crise des fusées de Cuba (octobre 1962) : missiles soviétiques installés à Cuba ; blocus américain ; le monde au bord de la guerre nucléaire ; Khrouchtchev retire les fusées | |"],
    support: "Tableau noir (tableau comparatif recopié)",
    note: "Le programme demande un tableau récapitulatif des relations Est-Ouest de 1945 à 1985 : commencer ce tableau ici (colonnes : période, événements, type de relation) et le compléter à la séance 22.",
  },
  analyse: [
    ["Pourquoi les Alliés de 1945 deviennent-ils rivaux ?", "Parce que leurs systèmes sont opposés : démocratie libérale et capitalisme aux États-Unis, communisme et parti unique en URSS ; parce que Staline impose des régimes communistes en Europe de l'Est (1945-1948) malgré les promesses de Yalta, ce que Churchill dénonce en 1946 comme un « rideau de fer » ; et parce que chacun craint l'expansion de l'autre."],
    ["Qu'est-ce que la doctrine Truman ? Et le plan Marshall ?", "Le 12 mars 1947, le président américain Truman annonce que les États-Unis aideront tous les « peuples libres » menacés par le communisme : c'est l'endiguement (containment) ; en juin 1947, le plan Marshall offre 13 milliards de dollars pour reconstruire l'Europe, afin d'éviter la misère qui favorise le communisme et d'ouvrir des marchés aux produits américains ; seize pays de l'Ouest acceptent."],
    ["Comment l'URSS répond-elle ?", "Par la doctrine Jdanov (septembre 1947), qui divise le monde en deux camps irréconciliables, le camp « impérialiste » mené par les États-Unis et le camp « anti-impérialiste » mené par l'URSS ; elle interdit aux pays de l'Est d'accepter le plan Marshall, crée le Kominform pour diriger les partis communistes et, en 1949, le Comecon pour organiser l'économie du bloc."],
    ["Qu'est-ce que la guerre froide ? Pourquoi « froide » ?", "L'affrontement, de 1947 à 1991, entre les deux blocs, par tous les moyens sauf la guerre directe entre les deux Grands : propagande, espionnage, course aux armements, conquête spatiale, guerres locales par pays interposés ; « froide » parce que la possession de la bombe atomique par les deux (URSS dès 1949) rend une guerre directe suicidaire : c'est l'« équilibre de la terreur »."],
    ["Quelles alliances militaires structurent les deux blocs ?", "À l'Ouest, l'OTAN (Organisation du traité de l'Atlantique Nord), créée le 4 avril 1949 entre les États-Unis, le Canada et l'Europe occidentale ; à l'Est, le pacte de Varsovie (14 mai 1955) entre l'URSS et les démocraties populaires ; les États-Unis tissent aussi des alliances en Asie et au Moyen-Orient."],
    ["Racontez le blocus de Berlin. Quelle en est la conséquence ?", "En juin 1948, pour chasser les Occidentaux de Berlin, Staline bloque tous les accès terrestres aux secteurs ouest ; les Américains et les Britanniques organisent un pont aérien de onze mois, 275 000 vols, pour ravitailler deux millions d'habitants ; Staline cède en mai 1949 ; la même année, l'Allemagne est coupée en deux États : la RFA à l'Ouest, la RDA à l'Est."],
    ["Quelle est la première guerre chaude de la guerre froide ?", "La guerre de Corée (1950-1953) : la Corée du Nord communiste, soutenue par l'URSS et la Chine devenue communiste en 1949, envahit la Corée du Sud ; les États-Unis interviennent sous drapeau de l'ONU, puis la Chine envoie ses « volontaires » ; après trois ans et 2 à 3 millions de morts, l'armistice de 1953 rétablit la frontière sur le 38e parallèle, qui existe toujours."],
    ["Que se passe-t-il à Berlin en 1961 et à Cuba en 1962 ?", "Le 13 août 1961, la RDA construit le mur de Berlin pour arrêter la fuite de ses habitants vers l'Ouest (3 millions depuis 1949) ; il devient le symbole du « rideau de fer ». En octobre 1962, les Américains découvrent des fusées nucléaires soviétiques à Cuba, devenue communiste avec Fidel Castro ; le président Kennedy impose un blocus de l'île ; pendant treize jours, le monde frôle la guerre nucléaire, jusqu'à ce que Khrouchtchev retire les fusées contre la promesse de ne pas envahir Cuba."],
  ],
  analyseTechnique: "Lecture de tableau comparatif et de carte, construction d'un tableau récapitulatif, questions-réponses",
  synthese: "Donc, dès 1947, les vainqueurs de 1945 se divisent en deux blocs opposés par leur idéologie : le bloc de l'Ouest, capitaliste et démocratique, dirigé par les États-Unis, qui pratiquent l'endiguement avec la doctrine Truman, le plan Marshall et l'OTAN ; le bloc de l'Est, communiste, dirigé par l'URSS, avec la doctrine Jdanov, le Kominform et le pacte de Varsovie. Leur affrontement, la guerre froide, reste indirect à cause de l'arme atomique, mais il provoque de graves crises : le blocus de Berlin en 1948-1949, qui aboutit à la division de l'Allemagne, la guerre de Corée de 1950 à 1953, le mur de Berlin en 1961 et la crise des fusées de Cuba en 1962, où le monde frôle la guerre nucléaire.",
  application: [
    { consigne: "Classez les éléments suivants dans le bloc de l'Ouest ou le bloc de l'Est.", pts: 4, items: [
      "1. Plan Marshall — 2. Pacte de Varsovie",
      "3. Doctrine Jdanov — 4. OTAN",
      "5. Kominform — 6. Doctrine Truman",
      "7. RDA — 8. RFA",
    ], corrige: [
      "1. **Ouest** — 2. **Est**.",
      "3. **Est** — 4. **Ouest**.",
      "5. **Est** — 6. **Ouest**.",
      "7. **Est** — 8. **Ouest**.",
    ]},
    { consigne: "Datez les événements suivants et indiquez le lieu (ville ou pays).", pts: 4, items: [
      "1. Le blocus et le pont aérien.",
      "2. La guerre entre le Nord communiste et le Sud soutenu par l'ONU.",
      "3. La construction d'un mur séparant une ville en deux.",
      "4. La crise des fusées nucléaires soviétiques.",
    ], corrige: [
      "1. **1948-1949**, **Berlin**.",
      "2. **1950-1953**, **Corée**.",
      "3. **13 août 1961**, **Berlin**.",
      "4. **Octobre 1962**, **Cuba**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) La guerre froide a opposé directement les armées américaine et soviétique sur un champ de bataille.",
      "b) Le plan Marshall a été accepté par les pays d'Europe de l'Est.",
      "c) Le pacte de Varsovie est l'alliance militaire du bloc de l'Est.",
      "d) La crise de Cuba a failli déclencher une guerre nucléaire.",
    ], corrige: [
      "a) **Faux** : l'affrontement est resté **indirect** (pays interposés) à cause de l'arme atomique.",
      "b) **Faux** : Staline le leur a **interdit**.",
      "c) **Vrai** : créé en 1955.",
      "d) **Vrai** : octobre 1962, treize jours de tension extrême.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Définissez la guerre froide et expliquez pourquoi elle est restée « froide ».",
      "2. Présentez les doctrines Truman et Jdanov.",
      "3. Racontez le blocus de Berlin et sa conséquence pour l'Allemagne.",
      "4. Complétez le tableau des relations Est-Ouest pour la période 1947-1962 (événements et type de relation).",
    ], corrige: [
      "1. L'affrontement **indirect** entre les blocs américain et soviétique (1947-1991) par la propagande, l'espionnage, la course aux armements et des guerres locales ; « froide » car l'**arme atomique** rend une guerre directe suicidaire (**équilibre de la terreur**).",
      "2. Truman (mars 1947) : les États-Unis aident les « peuples libres » pour **endiguer** le communisme ; Jdanov (septembre 1947) : le monde est divisé en **deux camps**, impérialiste et anti-impérialiste, et l'URSS dirige le second.",
      "3. Juin 1948 : Staline **coupe les accès** à Berlin-Ouest ; les Occidentaux organisent un **pont aérien** de onze mois ; Staline cède en mai 1949 ; conséquence : naissance de **deux Allemagnes**, RFA et RDA.",
      "4. 1947-1962 : **tension maximale** — doctrines Truman/Jdanov (1947), blocus de Berlin (1948-1949), OTAN (1949), guerre de Corée (1950-1953), pacte de Varsovie (1955), mur de Berlin (1961), Cuba (1962) : relations d'**affrontement**.",
    ]},
  ],
  lecon: [
    { t: "p", x: "À peine la guerre finie, les vainqueurs se divisent. De 1947 à 1991, le monde vit sous le régime de la **guerre froide** : un affrontement global entre deux blocs, l'un dirigé par les États-Unis, l'autre par l'URSS, qui ne dégénère jamais en guerre directe entre les deux Grands." },
    { t: "h", x: "1. La rupture de 1947 et la constitution des blocs" },
    { t: "p", x: "Les deux superpuissances s'opposent par leurs **idéologies** : démocratie libérale et capitalisme d'un côté, communisme, parti unique et économie planifiée de l'autre. Entre 1945 et 1948, Staline impose des régimes communistes (« démocraties populaires ») dans les pays d'Europe de l'Est occupés par l'Armée rouge, malgré les promesses de Yalta ; dès 1946, Churchill dénonce le **« rideau de fer »** qui coupe l'Europe. La rupture se consomme en **1947**. Le 12 mars, la **doctrine Truman** engage les États-Unis à soutenir les « peuples libres » menacés par le communisme : c'est l'**endiguement** (*containment*). En juin, le **plan Marshall** offre 13 milliards de dollars pour reconstruire l'Europe ; seize pays de l'Ouest acceptent, mais Staline interdit à ses satellites d'y participer. En septembre, la **doctrine Jdanov** proclame que le monde est divisé en deux camps, « impérialiste » et « anti-impérialiste », et le **Kominform** reprend en main les partis communistes." },
    { t: "p", x: "Chaque bloc s'organise. À l'Ouest : l'**OTAN** (Organisation du traité de l'Atlantique Nord, 4 avril 1949) unit militairement les États-Unis, le Canada et l'Europe occidentale ; le Japon et l'Australie rejoignent le camp américain. À l'Est : le **Comecon** (1949) organise l'économie et le **pacte de Varsovie** (14 mai 1955) l'armée du bloc soviétique, que rejoignent la **Chine** devenue communiste en 1949, la Corée du Nord et le Vietnam du Nord." },
    { t: "h", x: "2. La guerre froide : un affrontement indirect" },
    { t: "p", x: "La **guerre froide** oppose les deux blocs par tous les moyens sauf la guerre directe : **propagande**, espionnage, **course aux armements** (bombe H, missiles), conquête spatiale (Spoutnik 1957, Gagarine 1961, Apollo 1969), rivalité économique et sportive, et **guerres locales** par pays interposés. Les deux Grands ne s'affrontent jamais directement, car depuis que l'URSS possède la bombe atomique (1949), une guerre serait suicidaire : c'est l'**équilibre de la terreur**." },
    { t: "h", x: "3. Les grandes crises (1948-1962)" },
    { t: "ul", x: [
      "**Le blocus de Berlin (juin 1948-mai 1949).** Pour chasser les Occidentaux de Berlin, enclavée dans la zone soviétique, Staline coupe tous les accès terrestres. Américains et Britanniques ravitaillent deux millions d'habitants par un **pont aérien** de onze mois (275 000 vols). Staline cède, mais l'Allemagne est coupée en deux États en 1949 : la **RFA** à l'Ouest, la **RDA** à l'Est.",
      "**La guerre de Corée (1950-1953).** La Corée du Nord communiste envahit le Sud ; les États-Unis interviennent sous le drapeau de l'ONU, puis la Chine envoie ses « volontaires ». Après trois ans et 2 à 3 millions de morts, l'armistice de 1953 rétablit la frontière sur le **38e parallèle**, qui sépare toujours les deux Corées.",
      "**Le mur de Berlin (13 août 1961).** Pour arrêter la fuite de ses habitants vers l'Ouest (3 millions depuis 1949), la RDA construit un mur qui coupe la ville en deux : il devient le symbole du rideau de fer jusqu'en 1989.",
      "**La crise de Cuba (octobre 1962).** Les Américains découvrent des **fusées nucléaires soviétiques** à Cuba, devenue communiste sous **Fidel Castro**. Le président **Kennedy** impose un blocus de l'île ; pendant treize jours, le monde frôle la guerre nucléaire. **Khrouchtchev** retire les fusées contre la promesse américaine de ne pas envahir Cuba.",
    ]},
    { t: "p", x: "La peur ressentie en 1962 pousse les deux Grands à s'entendre pour éviter le pire : c'est le début de la **détente**, que nous étudierons à la séance suivante." },
  ],
},
// =====================================================================
{
  num: 22, theme: THEME,
  titre: "La guerre froide (2) : la détente et la fin de la guerre froide (1962-1991)",
  objectif: "caractériser la période de détente (1962-1975), la « guerre fraîche » (1975-1985), puis la nouvelle détente et la fin de la guerre froide avec Gorbatchev (perestroïka, glasnost, chute du mur de Berlin en 1989, éclatement de l'URSS en 1991), et de compléter le tableau des relations Est-Ouest",
  documentation: `${DOC_PROG} ; G.-H. Soutou, La Guerre de Cinquante Ans (2001) ; H. Carrère d'Encausse, La Gloire des nations (1990) ; P. Milza et S. Berstein, Histoire du XXe siècle, t. 2 et 3 ; M. Gorbatchev, Perestroïka (1987).`,
  image: null,
  revision: [
    ["Qu'est-ce que la guerre froide ?", "L'affrontement indirect entre les blocs américain et soviétique de 1947 à 1991."],
    ["Citez les alliances militaires des deux blocs.", "L'OTAN (1949) à l'Ouest, le pacte de Varsovie (1955) à l'Est."],
    ["Que s'est-il passé en octobre 1962 ?", "La crise des fusées de Cuba : le monde a frôlé la guerre nucléaire."],
    ["Quand le mur de Berlin a-t-il été construit ?", "Le 13 août 1961."],
  ],
  miseEnSituation: {
    enseignant: [
      "Berlin, soir du 9 novembre 1989. À la télévision, un porte-parole du gouvernement est-allemand annonce, presque par erreur, que les voyages à l'Ouest sont désormais libres. En quelques heures, des dizaines de milliers de Berlinois de l'Est se pressent aux postes-frontières ; les gardes, débordés, ouvrent les barrières. Des jeunes escaladent le mur, dansent dessus, l'attaquent à coups de pioche. Vingt-huit ans de séparation s'achèvent dans la nuit, sans un coup de feu.",
      "Comment un empire aussi puissant que l'URSS a-t-il pu s'effondrer sans guerre ? Que s'était-il passé depuis 1962 ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : l'URSS était ruinée par la course aux armements ; Gorbatchev a lancé des réformes et a refusé d'envoyer les chars ; les peuples voulaient la liberté."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau récapitulatif des relations Est-Ouest que j'écris au tableau noir :", "| Période | Événements | Type de relations |", "| 1945-1947 | Yalta, Potsdam, ONU ; désaccords sur l'Europe de l'Est | De l'alliance à la méfiance |", "| 1947-1962 | Doctrines Truman et Jdanov, plan Marshall, blocus de Berlin, OTAN, Corée, pacte de Varsovie, mur de Berlin, Cuba | Guerre froide : affrontement, tension maximale |", "| 1962-1975 | Détente : « téléphone rouge » Washington-Moscou (1963) ; traité de non-prolifération nucléaire (1968) ; accords SALT 1 sur la limitation des armements (1972) ; Ostpolitik de Willy Brandt (reconnaissance RFA-RDA, 1972) ; conférence d'Helsinki (1975) : frontières et droits de l'homme ; mais guerre du Vietnam (1964-1975), Printemps de Prague écrasé (1968) | Détente : dialogue et coexistence pacifique |", "| 1975-1985 | « Guerre fraîche » : URSS en Afghanistan (1979-1989), euromissiles SS-20 et Pershing, boycott des Jeux olympiques (1980, 1984), Reagan : « empire du mal », « guerre des étoiles » (IDS, 1983), Solidarność en Pologne (1980) | Regain de tension |", "| 1985-1991 | Gorbatchev (mars 1985) : perestroïka (restructuration économique) et glasnost (transparence, liberté d'expression) ; traité de Washington sur les euromissiles (1987) ; retrait d'Afghanistan (1989) ; révolutions pacifiques en Europe de l'Est ; chute du mur de Berlin (9 novembre 1989) ; réunification allemande (3 octobre 1990) ; dissolution du pacte de Varsovie (juillet 1991) ; putsch manqué (août 1991) ; indépendance des républiques ; dissolution de l'URSS (25 décembre 1991) | Nouvelle détente puis fin de la guerre froide |"],
    support: "Tableau noir (tableau récapitulatif recopié)",
    note: "Ce tableau achève celui commencé à la séance 21 (le programme demande un tableau 1945-1985 : le prolonger jusqu'en 1991). Faire recopier le tableau dans le cahier.",
  },
  analyse: [
    ["Pourquoi les deux Grands entrent-ils en détente après 1962 ?", "Parce que la crise de Cuba leur a fait peur : ils veulent éviter une guerre nucléaire accidentelle ; parce que la course aux armements coûte très cher ; parce que chacun a des problèmes dans son camp : les États-Unis s'enlisent au Vietnam et la France du général de Gaulle prend ses distances avec l'OTAN, tandis que l'URSS se brouille avec la Chine et fait face aux révoltes en Europe de l'Est."],
    ["Quelles sont les manifestations de la détente ?", "Le « téléphone rouge » entre Washington et Moscou (1963), le traité de non-prolifération nucléaire (1968), les accords SALT 1 limitant les armements stratégiques (1972), l'Ostpolitik du chancelier Willy Brandt qui fait se reconnaître les deux Allemagnes (1972), et la conférence d'Helsinki (1975) où 35 États reconnaissent les frontières européennes et s'engagent à respecter les droits de l'homme."],
    ["La détente signifie-t-elle la fin des conflits ?", "Non : les États-Unis mènent la guerre du Vietnam (1964-1975), qu'ils perdent ; l'URSS écrase le Printemps de Prague (1968), au nom de la « souveraineté limitée » ; les deux Grands s'affrontent par alliés interposés au Moyen-Orient et en Afrique ; la détente est une coexistence pacifique, pas une amitié."],
    ["Qu'est-ce que la « guerre fraîche » (1975-1985) ?", "Un regain de tension : l'URSS envahit l'Afghanistan (décembre 1979) et installe des missiles SS-20 en Europe, ce à quoi l'OTAN répond par des Pershing ; les Jeux olympiques de Moscou (1980) et de Los Angeles (1984) sont boycottés ; le président Reagan dénonce l'« empire du mal » et lance la « guerre des étoiles » (IDS, 1983), un programme de défense spatiale très coûteux que l'URSS ne peut pas suivre."],
    ["Qui est Gorbatchev et que sont la perestroïka et la glasnost ?", "Mikhaïl Gorbatchev devient secrétaire général du parti communiste soviétique en mars 1985 ; constatant que l'URSS est en faillite (économie stagnante, pénuries, course aux armements insoutenable), il lance la perestroïka (« restructuration » : introduction d'une part de marché et d'autonomie dans l'économie) et la glasnost (« transparence » : liberté d'expression, révélation des crimes de Staline, élections plus libres)."],
    ["Comment Gorbatchev met-il fin à la guerre froide ?", "Par une « nouvelle détente » : il rencontre Reagan et signe le traité de Washington (1987) qui supprime les euromissiles, retire les troupes d'Afghanistan (1989), réduit les armements et annonce qu'il n'interviendra plus dans les pays de l'Est : la « doctrine Brejnev » est abandonnée."],
    ["Que se passe-t-il en Europe de l'Est en 1989 ?", "Libérés de la menace des chars soviétiques, les peuples renversent pacifiquement les régimes communistes : élections libres en Pologne (Solidarność), ouverture de la frontière hongroise, chute du mur de Berlin le 9 novembre 1989, « révolution de velours » en Tchécoslovaquie, chute de Ceausescu en Roumanie (seule révolution sanglante) ; l'Allemagne est réunifiée le 3 octobre 1990 ; le pacte de Varsovie est dissous en 1991."],
    ["Comment l'URSS disparaît-elle ?", "Les réformes libèrent les nationalités : les pays baltes proclament leur indépendance (1990-1991) ; en août 1991, des communistes conservateurs tentent un putsch contre Gorbatchev, mis en échec par Boris Eltsine, président de la Russie ; le parti communiste est interdit, les républiques deviennent indépendantes et, le 25 décembre 1991, Gorbatchev démissionne : l'URSS est dissoute et remplacée par quinze États, dont la Russie ; la guerre froide est finie et les États-Unis restent la seule superpuissance."],
  ],
  analyseTechnique: "Lecture et complétion d'un tableau récapitulatif, questions-réponses",
  synthese: "Donc, après la peur de Cuba, les deux Grands entrent dans la détente : téléphone rouge, accords de limitation des armements, Ostpolitik et conférence d'Helsinki, même si des conflits comme le Vietnam et Prague continuent. De 1975 à 1985, la « guerre fraîche » ravive les tensions avec l'Afghanistan, les euromissiles et la guerre des étoiles de Reagan. Arrivé au pouvoir en 1985, Gorbatchev tente de sauver une URSS épuisée par la perestroïka et la glasnost, et négocie une nouvelle détente. Mais ses réformes libèrent les peuples : le mur de Berlin tombe le 9 novembre 1989, l'Europe de l'Est se libère, l'Allemagne se réunifie, et l'URSS se dissout le 25 décembre 1991. La guerre froide s'achève par la victoire du bloc occidental.",
  application: [
    { consigne: "Associez chaque événement à sa période : détente (D), guerre fraîche (F) ou fin de la guerre froide (G).", pts: 4, items: [
      "1. Invasion soviétique de l'Afghanistan (1979).",
      "2. Accords SALT 1 (1972).",
      "3. Chute du mur de Berlin (1989).",
      "4. « Guerre des étoiles » de Reagan (1983).",
      "5. Dissolution de l'URSS (1991).",
      "6. Conférence d'Helsinki (1975).",
    ], corrige: [
      "1. **F**.",
      "2. **D**.",
      "3. **G**.",
      "4. **F**.",
      "5. **G**.",
      "6. **D**.",
    ]},
    { consigne: "Complétez le texte avec les mots proposés : glasnost – 1985 – perestroïka – 9 novembre 1989 – 25 décembre 1991.", pts: 4, items: [
      "Gorbatchev arrive au pouvoir en URSS en ……… (1).",
      "Il lance la ……… (2), réforme de l'économie, et la ……… (3), liberté d'expression.",
      "Le mur de Berlin tombe le ……… (4).",
      "L'URSS est dissoute le ……… (5).",
    ], corrige: [
      "(1) **mars 1985**.",
      "(2) **perestroïka** ; (3) **glasnost**.",
      "(4) **9 novembre 1989**.",
      "(5) **25 décembre 1991**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) La détente a mis fin à toutes les guerres entre les deux blocs.",
      "b) Gorbatchev a envoyé les chars soviétiques pour empêcher la chute du mur de Berlin.",
      "c) L'Allemagne a été réunifiée le 3 octobre 1990.",
      "d) Après 1991, les États-Unis restent la seule superpuissance.",
    ], corrige: [
      "a) **Faux** : guerre du **Vietnam**, **Prague** 1968, conflits par alliés interposés.",
      "b) **Faux** : il a **refusé d'intervenir**, ce qui a permis les révolutions pacifiques.",
      "c) **Vrai** : la RDA a rejoint la RFA.",
      "d) **Vrai** : l'URSS a disparu ; on parle d'« hyperpuissance » américaine.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Pourquoi et comment les deux Grands sont-ils entrés en détente après 1962 ?",
      "2. Qu'est-ce que la « guerre fraîche » ? Donnez trois exemples.",
      "3. Présentez les réformes de Gorbatchev et leurs conséquences en URSS.",
      "4. Racontez la fin de la guerre froide de 1989 à 1991.",
    ], corrige: [
      "1. Par **peur** du nucléaire après Cuba et à cause du **coût** des armements ; par le **téléphone rouge** (1963), le traité de **non-prolifération** (1968), **SALT 1** (1972), l'**Ostpolitik** et **Helsinki** (1975).",
      "2. Un **regain de tension** de 1975 à 1985 : **Afghanistan** (1979), **euromissiles**, boycott des **JO**, « **guerre des étoiles** » de Reagan (1983), Solidarność en Pologne.",
      "3. **Perestroïka** (restructuration de l'économie) et **glasnost** (transparence, libertés) pour sauver une URSS en **faillite** ; conséquences : réveil des **nationalités**, contestation du parti, **effondrement** du système.",
      "4. **1989** : révolutions pacifiques à l'Est, **chute du mur** (9 novembre) ; **1990** : **réunification** allemande ; **1991** : dissolution du pacte de Varsovie, **putsch** manqué d'août, indépendance des républiques, **dissolution de l'URSS** (25 décembre).",
    ]},
  ],
  lecon: [
    { t: "p", x: "Après avoir frôlé la catastrophe nucléaire en 1962, les deux Grands apprennent à coexister. Mais l'affrontement reprend à la fin des années 1970, avant que les réformes de Gorbatchev n'entraînent, en quelques années, la fin de la guerre froide et la disparition de l'URSS." },
    { t: "h", x: "1. La détente (1962-1975)" },
    { t: "p", x: "La peur ressentie lors de la crise de Cuba, le coût écrasant de la course aux armements et les difficultés internes de chaque bloc (les États-Unis s'enlisent au **Vietnam** de 1964 à 1975 et la France de de Gaulle quitte le commandement de l'OTAN ; l'URSS se brouille avec la Chine et doit écraser le **Printemps de Prague** en 1968) poussent les deux Grands au dialogue. Le **« téléphone rouge »** relie Washington et Moscou (1963) ; le traité de **non-prolifération nucléaire** (1968) et les accords **SALT 1** (1972) limitent les armements ; l'**Ostpolitik** du chancelier Willy Brandt fait se reconnaître la RFA et la RDA (1972) ; la conférence d'**Helsinki** (1975) consacre les frontières de l'Europe et le respect des droits de l'homme. La détente n'est pas la paix : les deux blocs continuent de s'affronter par alliés interposés au Vietnam, au Moyen-Orient et en Afrique." },
    { t: "h", x: "2. La « guerre fraîche » (1975-1985)" },
    { t: "p", x: "À la fin des années 1970, la tension remonte. L'URSS envahit l'**Afghanistan** (décembre 1979) et installe des missiles **SS-20** pointés sur l'Europe ; l'OTAN riposte par les **Pershing** (crise des euromissiles). Les Jeux olympiques de Moscou (1980) et de Los Angeles (1984) sont boycottés. Le président américain **Reagan** dénonce l'« empire du mal » et lance en 1983 l'**Initiative de défense stratégique** (« guerre des étoiles »), un bouclier spatial que l'URSS, économiquement épuisée, ne peut pas suivre. En Pologne, le syndicat libre **Solidarność** (1980) défie le régime communiste." },
    { t: "h", x: "3. Gorbatchev et la nouvelle détente (1985-1989)" },
    { t: "p", x: "En **mars 1985**, **Mikhaïl Gorbatchev** prend la tête de l'URSS. Il constate que le pays est en faillite : économie stagnante, pénuries, technologies dépassées, course aux armements insoutenable. Il lance la **perestroïka** (« restructuration » : autonomie des entreprises, part de marché) et la **glasnost** (« transparence » : liberté d'expression et de la presse, révélation des crimes de Staline, élections plus libres). À l'extérieur, il négocie une **nouvelle détente** : traité de Washington avec Reagan supprimant les euromissiles (1987), retrait d'Afghanistan (1989), réduction des armées, et surtout renoncement à intervenir dans les pays de l'Est : la « doctrine Brejnev » de souveraineté limitée est abandonnée." },
    { t: "h", x: "4. La chute du mur et l'éclatement de l'URSS (1989-1991)" },
    { t: "p", x: "Libérés de la menace des chars soviétiques, les peuples d'Europe de l'Est renversent pacifiquement les régimes communistes en **1989** : élections libres en Pologne, ouverture de la frontière hongroise, **chute du mur de Berlin le 9 novembre 1989**, « révolution de velours » en Tchécoslovaquie, chute sanglante de Ceausescu en Roumanie. L'**Allemagne est réunifiée** le 3 octobre 1990 ; le pacte de Varsovie est dissous en juillet 1991. En URSS même, les réformes réveillent les **nationalités** : les pays baltes proclament leur indépendance. En **août 1991**, des communistes conservateurs tentent un putsch contre Gorbatchev ; il échoue grâce à la résistance de **Boris Eltsine**, président de la Russie, mais il précipite la fin : le parti communiste est interdit, les républiques se déclarent indépendantes et, le **25 décembre 1991**, Gorbatchev démissionne. L'**URSS est dissoute** et remplacée par quinze États, dont la Russie. La guerre froide s'achève, sans guerre, par la victoire du bloc occidental : les **États-Unis** restent la seule superpuissance." },
  ],
},
// =====================================================================
{
  num: 23, theme: THEME,
  titre: "La décolonisation et l'émergence du Tiers-Monde",
  objectif: "expliquer les facteurs de la décolonisation, d'en décrire les grandes étapes (Asie 1945-1955, Afrique 1956-1975) et les formes (négociée ou violente), et de présenter la naissance du Tiers-Monde avec la conférence de Bandoeng (1955) et le non-alignement",
  documentation: `${DOC_PROG} ; B. Droz, Histoire de la décolonisation au XXe siècle (2006) ; H. Grimal, La Décolonisation de 1919 à nos jours (1985) ; P. Milza et S. Berstein, Histoire du XXe siècle, t. 2 ; communiqué final de la conférence de Bandoeng (24 avril 1955).`,
  image: { file: "decolonisation.png", legende: "Frise chronologique des indépendances en Asie et en Afrique (1945-1975), avec la place de Madagascar (1960)", widthCm: 15, source: "réalisation J-Learn d'après B. Droz (2006) et l'Atlas historique Duby" },
  revision: [
    ["Que sont la perestroïka et la glasnost ?", "Les réformes économique et politique de Gorbatchev en URSS à partir de 1985."],
    ["Quand le mur de Berlin est-il tombé ? Quand l'URSS a-t-elle disparu ?", "Le 9 novembre 1989 ; le 25 décembre 1991."],
    ["Pourquoi la Deuxième Guerre mondiale a-t-elle ébranlé les empires coloniaux ?", "Prestige des métropoles ruiné, promesses aux colonisés, hostilité des deux Grands et de l'ONU."],
    ["Quand Madagascar est-elle devenue indépendante ?", "Le 26 juin 1960."],
  ],
  miseEnSituation: {
    enseignant: [
      "Bandoeng, Indonésie, avril 1955. Pour la première fois dans l'histoire, les dirigeants de 29 pays d'Asie et d'Afrique se réunissent sans les Européens : Nehru pour l'Inde, Nasser pour l'Égypte, Zhou Enlai pour la Chine, Soekarno pour l'Indonésie. Ils représentent plus de la moitié de l'humanité, mais presque rien de sa richesse. Ils condamnent le colonialisme « sous toutes ses formes » et refusent de choisir entre Washington et Moscou. Cinq ans plus tard, dix-sept pays africains, dont Madagascar, deviennent indépendants.",
      "Pourquoi les empires coloniaux, si puissants en 1939, s'effondrent-ils en trente ans ? Que veulent les nouveaux États ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : parce que les peuples colonisés se sont révoltés, que les métropoles étaient affaiblies par la guerre et que l'ONU et les deux Grands étaient contre la colonisation ; ils veulent la liberté, le développement et rester neutres."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| La décolonisation (1945-1975) | |", "| Facteurs internes | Naissance de mouvements nationalistes menés par des élites formées à l'école occidentale (Gandhi, Nehru, Hô Chi Minh, Bourguiba, Nkrumah, Senghor, Tsiranana) ; souvenirs des révoltes (Menalamba, VVS, 1947) ; misère, indigénat, travail forcé rejetés ; participation aux deux guerres |", "| Facteurs externes | Affaiblissement des métropoles par la guerre de 1939-1945 ; défaites des Européens face au Japon (1942) ; hostilité des États-Unis (Charte de l'Atlantique 1941) et de l'URSS au colonialisme ; Charte de l'ONU : droit des peuples à disposer d'eux-mêmes ; soutien des pays déjà indépendants (Bandoeng) |", "| 1re étape : l'Asie (1945-1955) | Indonésie (1945-1949, guerre contre les Pays-Bas) ; Inde et Pakistan (1947, négociation avec le Royaume-Uni, non-violence de Gandhi, mais partition sanglante) ; Birmanie, Ceylan (1948) ; Indochine : guerre contre la France 1946-1954, Diên Biên Phu, accords de Genève (1954) : Vietnam, Laos, Cambodge |", "| 2e étape : l'Afrique (1956-1975) | Tunisie et Maroc (1956, négociation) ; Ghana (1957, premier pays d'Afrique noire) ; Guinée (1958, « non » au référendum) ; 1960, « année de l'Afrique » : 17 indépendances dont Madagascar (26 juin), Sénégal, Côte d'Ivoire, Congo belge, Nigeria ; Algérie : guerre 1954-1962, accords d'Évian (1962) ; Kenya (1963) ; colonies portugaises (Angola, Mozambique, 1975) après des guerres |", "| Deux formes | Décolonisation négociée (Inde, Ghana, Afrique noire française, Madagascar) ou violente (Indonésie, Indochine, Algérie, Kenya, colonies portugaises) |", "| Bandoeng (18-24 avril 1955) | 29 pays d'Asie et d'Afrique (Nehru, Nasser, Soekarno, Zhou Enlai) : condamnation du colonialisme et du racisme, droit des peuples à l'indépendance, coexistence pacifique, refus des blocs ; naissance du Tiers-Monde |", "| Le Tiers-Monde | Expression d'Alfred Sauvy (1952) : les pays pauvres, ni Ouest ni Est, comme le tiers état de 1789 ; mouvement des non-alignés (Belgrade, 1961 : Tito, Nehru, Nasser) ; « Groupe des 77 » à l'ONU (1964) ; revendication d'un nouvel ordre économique international |"],
    support: "Tableau noir (tableau récapitulatif recopié)",
    note: "Faire le lien avec l'Unité 1 : replacer les événements malgaches (1946, 1947, 1956, 1958, 1960) dans la chronologie mondiale.",
  },
  analyse: [
    ["Qu'est-ce que la décolonisation ?", "Le processus par lequel les colonies d'Asie et d'Afrique accèdent à l'indépendance, pour l'essentiel entre 1945 et 1975 ; les empires coloniaux européens (britannique, français, néerlandais, belge, portugais), constitués aux XIXe siècle, disparaissent en trente ans."],
    ["Quels sont les facteurs internes de la décolonisation ?", "La naissance de mouvements nationalistes conduits par des élites instruites à l'école européenne, qui retournent contre les colonisateurs leurs propres valeurs de liberté et d'égalité (Gandhi et Nehru en Inde, Hô Chi Minh au Vietnam, Bourguiba en Tunisie, Nkrumah au Ghana, Senghor au Sénégal, Ravoahangy et Tsiranana à Madagascar) ; le rejet de l'indigénat, du travail forcé et de la misère ; la mémoire des révoltes ; et la participation des colonisés aux deux guerres mondiales, qui ont montré que les Européens n'étaient pas invincibles."],
    ["Quels sont les facteurs externes ?", "L'affaiblissement des métropoles ruinées et humiliées par la guerre (défaites devant le Japon en 1942) ; l'hostilité au colonialisme des deux superpuissances, les États-Unis (Charte de l'Atlantique, 1941) et l'URSS ; la Charte de l'ONU qui proclame le droit des peuples à disposer d'eux-mêmes et offre une tribune aux colonisés ; et la solidarité des pays déjà indépendants, affirmée à Bandoeng."],
    ["Décrivez la première étape : la décolonisation de l'Asie.", "Elle commence dès 1945 : l'Indonésie proclame son indépendance et l'arrache aux Pays-Bas après quatre ans de guerre (1949) ; l'Inde, guidée par la non-violence de Gandhi, obtient par négociation son indépendance du Royaume-Uni en 1947, mais elle est divisée entre Inde et Pakistan dans des massacres ; la Birmanie et Ceylan suivent en 1948 ; en Indochine, la France refuse l'indépendance proclamée par Hô Chi Minh et mène une guerre de huit ans (1946-1954) qui s'achève par la défaite de Diên Biên Phu et les accords de Genève : Vietnam (divisé), Laos et Cambodge deviennent indépendants."],
    ["Décrivez la seconde étape : la décolonisation de l'Afrique.", "Elle commence au Maghreb avec la Tunisie et le Maroc (1956) et s'accélère en Afrique noire : Ghana (1957), Guinée (1958), puis l'« année de l'Afrique », 1960, avec 17 indépendances dont Madagascar (26 juin), le Sénégal, la Côte d'Ivoire, le Nigeria, le Congo belge ; l'Algérie, où vivent un million de colons, n'est libérée qu'après une guerre de huit ans (1954-1962, accords d'Évian) ; les colonies portugaises (Angola, Mozambique) attendent 1975 et des guerres de libération."],
    ["Quelles sont les deux formes de décolonisation ?", "La décolonisation négociée, quand la métropole accepte de discuter : Inde, Ghana, Tunisie, Afrique noire française grâce à la Loi-cadre de 1956 et à la Communauté de 1958, Madagascar ; et la décolonisation violente, quand elle refuse : Indonésie, Indochine, Algérie, Kenya (Mau-Mau), colonies portugaises ; le choix dépend de la présence de colons, des richesses en jeu et de la puissance des mouvements nationalistes."],
    ["Qu'est-ce que la conférence de Bandoeng ? Pourquoi est-elle importante ?", "Du 18 au 24 avril 1955, 29 États d'Asie et d'Afrique nouvellement indépendants se réunissent à Bandoeng, en Indonésie, autour de Nehru, Nasser, Soekarno et Zhou Enlai ; ils condamnent le colonialisme « sous toutes ses formes » et le racisme, affirment le droit des peuples à l'indépendance, la coexistence pacifique et leur refus de s'aligner sur les blocs ; c'est la première fois que les anciens colonisés parlent d'une seule voix : Bandoeng encourage les indépendances africaines et fait naître le Tiers-Monde."],
    ["Qu'est-ce que le Tiers-Monde et le non-alignement ?", "Le Tiers-Monde, mot du démographe Alfred Sauvy (1952), désigne les pays pauvres qui, comme le tiers état de 1789, « veulent être quelque chose » et n'appartiennent ni à l'Ouest ni à l'Est ; le mouvement des non-alignés, fondé à Belgrade en 1961 par Tito, Nehru et Nasser, refuse les alliances militaires avec les blocs ; à l'ONU, le Groupe des 77 (1964) réclame un nouvel ordre économique international plus juste ; mais le Tiers-Monde est vite divisé et reste dépendant économiquement (néocolonialisme)."],
  ],
  analyseTechnique: "Lecture de tableau et de frise chronologique, mise en relation avec l'histoire de Madagascar, questions-réponses",
  synthese: "Donc, entre 1945 et 1975, les empires coloniaux disparaissent sous l'effet de facteurs internes, l'essor des mouvements nationalistes dirigés par des élites instruites, et externes, l'affaiblissement des métropoles par la guerre, l'hostilité des deux Grands et de l'ONU au colonialisme. La décolonisation touche d'abord l'Asie, de l'Indonésie et de l'Inde en 1945-1947 à l'Indochine en 1954, puis l'Afrique, du Maghreb en 1956 à l'année de l'Afrique en 1960, dont Madagascar, et aux colonies portugaises en 1975 ; elle est négociée ou violente selon les cas. En 1955, la conférence de Bandoeng réunit les nouveaux États d'Asie et d'Afrique, condamne le colonialisme et refuse les blocs : c'est la naissance du Tiers-Monde et du non-alignement.",
  application: [
    { consigne: "Classez les faits suivants en facteurs internes (I) ou externes (E) de la décolonisation.", pts: 4, items: [
      "1. Les élites formées à l'école européenne créent des partis nationalistes.",
      "2. La Charte de l'ONU proclame le droit des peuples à disposer d'eux-mêmes.",
      "3. Les anciens combattants colonisés ont vu que les Européens pouvaient être vaincus.",
      "4. Les États-Unis et l'URSS sont hostiles au colonialisme.",
    ], corrige: [
      "1. **I**.",
      "2. **E**.",
      "3. **I**.",
      "4. **E**.",
    ]},
    { consigne: "Pour chaque pays, indiquez la date de l'indépendance et la forme de la décolonisation (négociée ou violente).", pts: 4, items: [
      "1. Inde.",
      "2. Algérie.",
      "3. Madagascar.",
      "4. Indochine (Vietnam).",
    ], corrige: [
      "1. **1947**, **négociée** (mais partition sanglante).",
      "2. **1962**, **violente** (guerre 1954-1962).",
      "3. **26 juin 1960**, **négociée** (après l'insurrection de 1947, Loi-cadre 1956, référendum 1958).",
      "4. **1954**, **violente** (guerre 1946-1954, Diên Biên Phu).",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) La décolonisation a commencé par l'Afrique.",
      "b) L'année 1960 est appelée « année de l'Afrique » car 17 pays sont devenus indépendants.",
      "c) La conférence de Bandoeng a réuni les pays européens et leurs colonies.",
      "d) Les pays non alignés refusent d'appartenir aux blocs américain ou soviétique.",
    ], corrige: [
      "a) **Faux** : par l'**Asie** (Indonésie 1945, Inde 1947).",
      "b) **Vrai** : dont Madagascar le 26 juin.",
      "c) **Faux** : elle a réuni **29 pays d'Asie et d'Afrique**, sans les Européens.",
      "d) **Vrai** : mouvement fondé à Belgrade en 1961.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Expliquez deux facteurs internes et deux facteurs externes de la décolonisation.",
      "2. Présentez les deux grandes étapes de la décolonisation avec des exemples datés.",
      "3. Pourquoi certaines décolonisations ont-elles été violentes et d'autres négociées ?",
      "4. Présentez la conférence de Bandoeng et expliquez ce qu'est le Tiers-Monde.",
    ], corrige: [
      "1. Internes : **mouvements nationalistes** d'élites instruites, rejet de l'**indigénat** et de la misère, expérience des **guerres**. Externes : **affaiblissement** des métropoles, hostilité des **États-Unis** et de l'**URSS**, **ONU**, solidarité de **Bandoeng**.",
      "2. **Asie (1945-1955)** : Indonésie 1945-1949, Inde 1947, Indochine 1954. **Afrique (1956-1975)** : Tunisie-Maroc 1956, Ghana 1957, année de l'Afrique **1960** (Madagascar), Algérie 1962, colonies portugaises 1975.",
      "3. Violentes quand la métropole **refuse** de négocier, qu'il y a de nombreux **colons** (Algérie, Kenya) ou des **richesses** stratégiques (Indochine, Angola) ; négociées quand la métropole **accepte** le dialogue (Inde, Loi-cadre de 1956 pour l'Afrique française, Madagascar).",
      "4. **Avril 1955**, en Indonésie : **29 pays** d'Asie et d'Afrique condamnent le **colonialisme** et le **racisme** et refusent les **blocs**. Le **Tiers-Monde** (Sauvy, 1952) désigne les pays **pauvres** ni de l'Ouest ni de l'Est, unis dans le **non-alignement** (Belgrade 1961) et la revendication d'un ordre économique plus juste.",
    ]},
  ],
  lecon: [
    { t: "p", x: "En 1939, les empires coloniaux européens couvraient un tiers des terres émergées. Trente ans plus tard, ils ont presque disparu : c'est la **décolonisation**, l'un des bouleversements majeurs du XXe siècle, dont Madagascar fait partie." },
    { t: "h", x: "1. Les facteurs de la décolonisation" },
    { t: "p", x: "**Les facteurs internes.** Dans les colonies naissent des **mouvements nationalistes**, dirigés par des élites formées à l'école européenne qui retournent contre les colonisateurs leurs propres valeurs de liberté et d'égalité : **Gandhi** et **Nehru** en Inde, **Hô Chi Minh** au Vietnam, **Bourguiba** en Tunisie, **Nkrumah** au Ghana, **Senghor** au Sénégal, Ravoahangy, Raseta et **Tsiranana** à Madagascar. Les populations rejettent l'indigénat, le travail forcé, la misère, et gardent la mémoire des révoltes (Menalamba, 1947). Les colonisés qui ont combattu dans les deux guerres mondiales ont vu que les Européens n'étaient pas invincibles." },
    { t: "p", x: "**Les facteurs externes.** La Deuxième Guerre mondiale a **ruiné et humilié** les métropoles, battues par le Japon en Asie en 1942. Les deux superpuissances sont hostiles au colonialisme : les **États-Unis** au nom de la liberté (Charte de l'Atlantique, 1941), l'**URSS** au nom de l'anti-impérialisme. La **Charte de l'ONU** proclame le droit des peuples à disposer d'eux-mêmes et offre une tribune aux colonisés. Enfin, les pays déjà indépendants soutiennent les autres, comme l'affirme la conférence de Bandoeng." },
    { t: "h", x: "2. Les étapes de la décolonisation" },
    { t: "p", x: "**L'Asie d'abord (1945-1955).** L'**Indonésie** proclame son indépendance en 1945 et l'arrache aux Pays-Bas après quatre ans de guerre (1949). L'**Inde**, guidée par la non-violence de Gandhi, l'obtient par négociation du Royaume-Uni en **1947**, mais se divise dans les massacres entre Inde et Pakistan ; Birmanie et Ceylan suivent en 1948. En **Indochine**, la France refuse l'indépendance proclamée par Hô Chi Minh et s'enlise dans une guerre de huit ans (1946-1954) qui s'achève par la défaite de **Diên Biên Phu** et les accords de Genève : Vietnam, Laos et Cambodge deviennent indépendants." },
    { t: "p", x: "**L'Afrique ensuite (1956-1975).** La **Tunisie** et le **Maroc** obtiennent l'indépendance en 1956. En Afrique noire, le **Ghana** ouvre la voie en 1957, la Guinée dit « non » à de Gaulle en 1958 ; la **Loi-cadre** de 1956 et la Communauté de 1958 préparent les indépendances de l'Afrique française. **1960** est l'« **année de l'Afrique** » : 17 pays deviennent indépendants, dont **Madagascar** le 26 juin, le Sénégal, la Côte d'Ivoire, le Nigeria et le Congo belge. L'**Algérie**, où vivent un million de colons, n'est libérée qu'au terme d'une guerre atroce (1954-1962, accords d'Évian). Le Kenya (1963) et les colonies portugaises, Angola et Mozambique (1975), doivent aussi se battre." },
    { t: "p", x: "La décolonisation prend donc deux formes : **négociée** lorsque la métropole accepte de discuter (Inde, Ghana, Afrique noire française, Madagascar après le choc de 1947), **violente** lorsqu'elle s'y refuse, surtout là où vivent de nombreux colons ou se trouvent des richesses stratégiques (Indonésie, Indochine, Algérie, Kenya, colonies portugaises)." },
    { t: "h", x: "3. Bandoeng et la naissance du Tiers-Monde" },
    { t: "p", x: "Du **18 au 24 avril 1955**, 29 États d'Asie et d'Afrique se réunissent à **Bandoeng**, en Indonésie, autour de **Nehru** (Inde), **Nasser** (Égypte), **Soekarno** (Indonésie) et **Zhou Enlai** (Chine). Pour la première fois, les anciens colonisés parlent d'une seule voix : ils condamnent le **colonialisme** « sous toutes ses formes » et le racisme, affirment le droit de tous les peuples à l'indépendance, prônent la coexistence pacifique et refusent de s'aligner sur les blocs. Bandoeng encourage les indépendances africaines et donne naissance au **Tiers-Monde**, expression du démographe Alfred Sauvy (1952) désignant les pays pauvres qui, comme le tiers état de 1789, « veulent être quelque chose » et n'appartiennent ni à l'Ouest ni à l'Est. Le mouvement des **non-alignés**, fondé à Belgrade en 1961 par Tito, Nehru et Nasser, refuse les alliances militaires ; à l'ONU, le Groupe des 77 (1964) réclame un **nouvel ordre économique international**. Mais le Tiers-Monde reste divisé et économiquement dépendant des anciennes métropoles : on parle de **néocolonialisme**. Politiquement libres, les nouveaux États, dont Madagascar, doivent relever le défi du développement." },
  ],
},
// =====================================================================
{
  num: 24, theme: THEME,
  titre: "Le monde d'aujourd'hui : de l'après-guerre froide à la mondialisation",
  objectif: "présenter le monde issu de la fin de la guerre froide : la suprématie américaine et le rôle de « gendarme du monde » des États-Unis, les nouveaux conflits, la mondialisation économique et ses limites, et l'émergence de nouvelles puissances, à l'aide d'un tableau synoptique",
  documentation: `${DOC_PROG} ; P. Milza et S. Berstein, Histoire du XXe siècle, t. 3 et 4 ; P. Boniface, Atlas des relations internationales (2023) ; L. Carroué, Géographie de la mondialisation (2019) ; rapports de l'ONU et de la Banque mondiale (2023-2024).`,
  image: null,
  revision: [
    ["Citez deux facteurs de la décolonisation.", "Les mouvements nationalistes, l'affaiblissement des métropoles, l'hostilité des deux Grands et de l'ONU."],
    ["Qu'est-ce que la conférence de Bandoeng ?", "La réunion de 29 pays d'Asie et d'Afrique en avril 1955 qui condamne le colonialisme et refuse les blocs."],
    ["Qu'est-ce que le Tiers-Monde ?", "L'ensemble des pays pauvres n'appartenant ni au bloc de l'Ouest ni au bloc de l'Est."],
    ["Quand l'URSS a-t-elle disparu et qui reste la seule superpuissance ?", "Le 25 décembre 1991 ; les États-Unis."],
  ],
  miseEnSituation: {
    enseignant: [
      "Janvier 1991. Sous mandat de l'ONU, une coalition de 35 pays conduite par les États-Unis chasse l'armée irakienne du Koweït en quelques semaines ; le président Bush annonce un « nouvel ordre mondial ». Dix ans plus tard, le 11 septembre 2001, deux avions détournés s'écrasent sur les tours du World Trade Center à New York : près de 3 000 morts. Aujourd'hui, un téléphone assemblé en Chine avec des composants de dix pays est vendu à Antananarivo, tandis que la vanille de la Sava est achetée par des industriels américains.",
      "Qui dirige le monde depuis 1991 ? Pourquoi les guerres n'ont-elles pas cessé ? Qu'est-ce qui relie Madagascar au reste du monde ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : les États-Unis dominent mais sont contestés ; il y a de nouveaux conflits (nationalismes, terrorisme) ; le commerce, Internet, les migrations relient tous les pays : c'est la mondialisation."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau synoptique que j'écris au tableau noir :", "| Domaine | Le monde depuis 1991 |", "| Politique : la suprématie américaine | Seule superpuissance (« hyperpuissance ») : première économie, première armée, domination culturelle ; « gendarme du monde » : guerre du Golfe (1991, mandat ONU), Somalie (1992), Bosnie (1995), Kosovo (1999) ; après le 11 septembre 2001 : « guerre contre le terrorisme », Afghanistan (2001-2021), Irak (2003, sans mandat ONU) ; limites : échecs, coût, contestation |", "| Nouveaux conflits | Guerres nationalistes et ethniques : éclatement de la Yougoslavie (1991-1999), génocide au Rwanda (1994 : 800 000 morts), guerres en Afrique (Congo, Soudan, Sahel) ; terrorisme islamiste (Al-Qaïda, Daech) ; Moyen-Orient : conflit israélo-palestinien, guerres en Syrie (2011-) ; retour des rivalités de puissances : Russie en Ukraine (2014, invasion 2022), tensions Chine-États-Unis |", "| L'ONU et la coopération | Casques bleus (plus de 70 opérations), Cour pénale internationale (2002), Objectifs du millénaire puis de développement durable (2015), accord de Paris sur le climat (2015) ; mais blocages du Conseil de sécurité (vetos) |", "| Mondialisation économique | Libre-échange (OMC, 1995), firmes multinationales, délocalisations, conteneurs, Internet (années 1990), flux financiers ; commerce mondial multiplié par 4 depuis 1990 ; recul de la pauvreté extrême en Asie (Chine : 800 millions de personnes sorties de la pauvreté) |", "| Nouvelles puissances | Chine : 2e économie mondiale (2010), « nouvelles routes de la soie » (2013), présente en Afrique et à Madagascar ; Inde, Brésil, Afrique du Sud (BRICS, 2009) ; Union européenne (euro 1999-2002, 27 membres) ; monde multipolaire |", "| Limites et défis | Inégalités entre pays et à l'intérieur des pays ; crises financières (1997, 2008) ; pandémie de Covid-19 (2020) ; réchauffement climatique ; migrations ; Afrique et Madagascar : croissance mais pauvreté persistante (Madagascar : environ 75 % de la population sous le seuil de pauvreté, IDH 177e sur 193 en 2022) |"],
    support: "Tableau noir (tableau synoptique recopié)",
    note: "Le programme demande un tableau synoptique du monde d'aujourd'hui : le faire recopier. Insister sur les liens avec la Géographie de 3ème (Madagascar dans le monde) et l'Éducation civique (ONU, coopération internationale).",
  },
  analyse: [
    ["Pourquoi parle-t-on d'hyperpuissance américaine après 1991 ?", "Parce que, l'URSS disparue, les États-Unis sont la seule superpuissance : première économie, première armée (près de 40 % des dépenses militaires mondiales), domination technologique (Internet, informatique) et culturelle (cinéma, musique, mode de vie) ; le mot « hyperpuissance » est du ministre français Hubert Védrine (1998)."],
    ["Que signifie « gendarme du monde » ? Donnez des exemples.", "Les États-Unis interviennent militairement pour faire respecter l'ordre international, avec ou sans l'ONU : guerre du Golfe (1991) pour libérer le Koweït envahi par l'Irak, sous mandat de l'ONU ; Somalie (1992), Bosnie (1995), Kosovo (1999) ; après les attentats du 11 septembre 2001, ils lancent la « guerre contre le terrorisme » en Afghanistan (2001-2021) et en Irak (2003, sans mandat), deux guerres longues et coûteuses qui finissent par des échecs et affaiblissent leur autorité."],
    ["La fin de la guerre froide a-t-elle apporté la paix ?", "Non : les nationalismes libérés font éclater la Yougoslavie dans des guerres sanglantes (1991-1999) ; le génocide des Tutsi au Rwanda fait 800 000 morts en 1994 ; des guerres ravagent le Congo, le Soudan, le Sahel ; le terrorisme islamiste (Al-Qaïda, Daech) frappe partout ; le Moyen-Orient reste en guerre (Israël-Palestine, Syrie) ; et les rivalités de puissances reviennent : la Russie annexe la Crimée (2014) et envahit l'Ukraine (2022), la Chine et les États-Unis s'affrontent économiquement."],
    ["Quel rôle joue l'ONU dans ce monde ?", "Elle multiplie les opérations de maintien de la paix (casques bleus), crée la Cour pénale internationale (2002), fixe les Objectifs du millénaire puis les Objectifs de développement durable (2015), organise l'accord de Paris sur le climat (2015) ; mais elle est souvent paralysée par les vetos au Conseil de sécurité et dépend de la volonté des grandes puissances."],
    ["Qu'est-ce que la mondialisation ?", "La mise en relation de toutes les régions du monde par la multiplication des échanges de marchandises, de capitaux, d'informations et de personnes : libre-échange organisé par l'OMC (1995), firmes multinationales qui délocalisent leur production, transport par conteneurs, Internet et téléphonie mobile depuis les années 1990, marchés financiers connectés en permanence ; le commerce mondial a été multiplié par quatre depuis 1990."],
    ["Quelles nouvelles puissances émergent ?", "La Chine surtout, devenue l'« atelier du monde » puis la deuxième économie mondiale (2010), qui investit en Afrique et à Madagascar avec ses « nouvelles routes de la soie » ; l'Inde, le Brésil, l'Afrique du Sud, réunis avec la Russie dans les BRICS (2009) ; l'Union européenne, qui compte 27 membres et une monnaie commune, l'euro ; le monde devient multipolaire, la domination américaine est contestée."],
    ["Quelles sont les limites de la mondialisation ?", "Elle a fait reculer la pauvreté extrême en Asie mais creusé les inégalités entre pays et à l'intérieur des pays ; elle propage les crises financières (1997, 2008) et sanitaires (Covid-19, 2020) ; elle accélère le réchauffement climatique et les migrations ; l'Afrique reste en marge : Madagascar, malgré ses exportations de vanille, de nickel et de textile, compte environ 75 % de pauvres et se classe 177e sur 193 pays pour l'IDH (2022)."],
    ["Quelle place Madagascar occupe-t-elle dans ce monde ?", "Une place marginale mais connectée : membre de l'ONU depuis 1960, de l'Union africaine, de la SADC et de la Commission de l'océan Indien, elle exporte vanille, girofle, nickel, crevettes et textile vers la France, les États-Unis et la Chine, importe riz et produits manufacturés d'Asie, reçoit l'aide internationale (Banque mondiale, FMI, Union européenne) et les investissements chinois, mais subit la pauvreté, les cyclones et l'instabilité politique."],
  ],
  analyseTechnique: "Lecture de tableau synoptique, mise en relation avec la géographie et l'éducation civique, questions-réponses",
  synthese: "Donc, depuis la fin de la guerre froide en 1991, les États-Unis sont la seule superpuissance et jouent le rôle de gendarme du monde, de la guerre du Golfe à la guerre contre le terrorisme après le 11 septembre 2001, mais leurs interventions en Afghanistan et en Irak montrent les limites de leur puissance. La paix n'est pas revenue : guerres nationalistes, génocide au Rwanda, terrorisme et retour des rivalités entre grandes puissances marquent le monde d'aujourd'hui. La mondialisation relie tous les pays par le commerce, les capitaux et Internet, fait émerger la Chine et les BRICS et crée un monde multipolaire, mais elle creuse les inégalités et laisse à l'écart une grande partie de l'Afrique, dont Madagascar, qui reste l'un des pays les plus pauvres de la planète.",
  application: [
    { consigne: "Placez chaque événement dans la bonne ligne du tableau synoptique : suprématie américaine (S), nouveaux conflits (C), mondialisation (M), nouvelles puissances (P).", pts: 4, items: [
      "1. Création de l'OMC en 1995.",
      "2. Guerre du Golfe (1991) conduite par les États-Unis.",
      "3. La Chine devient la deuxième économie mondiale en 2010.",
      "4. Génocide au Rwanda (1994).",
    ], corrige: [
      "1. **M**.",
      "2. **S**.",
      "3. **P**.",
      "4. **C**.",
    ]},
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. Les attentats du World Trade Center ont eu lieu le : A) 9 novembre 1989 — B) 11 septembre 2001 — C) 25 décembre 1991.",
      "2. L'expression « gendarme du monde » désigne : A) l'ONU — B) les États-Unis — C) la Chine.",
      "3. Les BRICS regroupent notamment : A) Brésil, Russie, Inde, Chine, Afrique du Sud — B) France, Allemagne, Italie — C) Japon et Australie.",
      "4. La mondialisation a surtout fait reculer la pauvreté : A) en Afrique — B) en Asie — C) en Europe.",
    ], corrige: [
      "1. **B)** 11 septembre 2001.",
      "2. **B)** les États-Unis.",
      "3. **A)**.",
      "4. **B)** en Asie (Chine, Inde, Vietnam).",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Depuis 1991, le monde n'a plus connu de guerre.",
      "b) La guerre d'Irak de 2003 a été menée sans mandat de l'ONU.",
      "c) La mondialisation a réduit toutes les inégalités.",
      "d) Madagascar fait partie des pays les plus pauvres du monde malgré ses exportations.",
    ], corrige: [
      "a) **Faux** : Yougoslavie, Rwanda, Afghanistan, Irak, Syrie, Ukraine…",
      "b) **Vrai** : ce qui a été très contesté.",
      "c) **Faux** : elle a réduit la pauvreté en **Asie** mais **creusé** les inégalités ailleurs.",
      "d) **Vrai** : environ 75 % de pauvres, IDH 177e sur 193 (2022).",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Pourquoi les États-Unis sont-ils appelés « gendarme du monde » et quelles sont les limites de ce rôle ?",
      "2. Citez et expliquez trois types de conflits du monde d'aujourd'hui.",
      "3. Définissez la mondialisation et donnez trois de ses manifestations.",
      "4. Quelles sont les nouvelles puissances et quelle est la place de Madagascar dans le monde actuel ?",
    ], corrige: [
      "1. Seule **superpuissance**, ils interviennent pour faire respecter l'ordre international (**Golfe** 1991, Kosovo, **Afghanistan**, **Irak**) ; limites : **échecs** en Afghanistan et en Irak, **coût**, contestation par la Chine, la Russie et une partie du monde.",
      "2. Guerres **nationalistes et ethniques** (Yougoslavie, Rwanda), **terrorisme** islamiste (11 septembre, Daech), **rivalités de puissances** (Ukraine 2022, Chine-États-Unis), conflits du **Moyen-Orient**.",
      "3. Mise en relation de toutes les régions du monde par les **échanges** ; manifestations : **libre-échange** (OMC), **multinationales** et délocalisations, **Internet**, **conteneurs**, flux financiers, migrations.",
      "4. **Chine** (2e économie), **Inde**, **Brésil**, **BRICS**, **Union européenne** : monde **multipolaire**. Madagascar : membre de l'**ONU**, de l'UA et de la SADC, exporte **vanille**, **nickel**, textile, reçoit l'aide et les investissements, mais reste **très pauvre** et en marge de la mondialisation.",
    ]},
  ],
  lecon: [
    { t: "p", x: "La disparition de l'URSS en 1991 met fin au monde bipolaire. Un nouvel ordre s'installe, dominé par les États-Unis et transformé par la mondialisation, mais traversé de nouveaux conflits et d'inégalités persistantes. C'est le monde dans lequel vit Madagascar aujourd'hui." },
    { t: "h", x: "1. Les États-Unis, « gendarme du monde »" },
    { t: "p", x: "Seule superpuissance après 1991, les **États-Unis** sont une « **hyperpuissance** » : première économie, première armée (près de 40 % des dépenses militaires mondiales), domination technologique (Internet, informatique) et culturelle (cinéma, musique, mode de vie). Ils jouent le rôle de **gendarme du monde** : en **1991**, sous mandat de l'ONU, ils conduisent la coalition qui libère le Koweït envahi par l'Irak (guerre du Golfe) ; ils interviennent en Somalie (1992), en Bosnie (1995), au Kosovo (1999). Les attentats du **11 septembre 2001** contre New York et Washington (près de 3 000 morts), commis par Al-Qaïda, ouvrent la « **guerre contre le terrorisme** » : invasion de l'**Afghanistan** (2001-2021) puis de l'**Irak** (2003), cette fois sans mandat de l'ONU. Ces guerres longues, coûteuses et finalement perdues montrent les **limites** de la puissance américaine, de plus en plus contestée." },
    { t: "h", x: "2. Un monde toujours en guerre" },
    { t: "p", x: "La fin de la guerre froide n'a pas apporté la paix. Les **nationalismes** libérés font éclater la **Yougoslavie** dans des guerres sanglantes (1991-1999) ; au **Rwanda**, le génocide des Tutsi fait 800 000 morts en 1994 ; des guerres ravagent le Congo, le Soudan, le Sahel. Le **terrorisme** islamiste (Al-Qaïda, puis Daech) frappe l'Amérique, l'Europe, l'Afrique et l'Asie. Le **Moyen-Orient** reste déchiré par le conflit israélo-palestinien et la guerre de Syrie. Enfin, les **rivalités de puissances** reviennent : la Russie de Poutine annexe la Crimée (2014) et envahit l'**Ukraine** (2022) ; la Chine et les États-Unis s'affrontent commercialement et militairement en Asie. L'**ONU** multiplie les opérations de casques bleus, crée la Cour pénale internationale (2002), fixe les **Objectifs de développement durable** (2015) et organise l'accord de Paris sur le climat (2015), mais elle est souvent paralysée par les vetos." },
    { t: "h", x: "3. La mondialisation et les nouvelles puissances" },
    { t: "p", x: "La **mondialisation** met en relation toutes les régions du monde par la multiplication des échanges de marchandises, de capitaux, d'informations et de personnes. Elle repose sur le **libre-échange** organisé par l'**OMC** (1995), sur les **firmes multinationales** qui délocalisent leur production vers les pays à bas salaires, sur le transport par **conteneurs**, sur **Internet** et la téléphonie mobile, apparus dans les années 1990, et sur des marchés financiers connectés en permanence. Le commerce mondial a été multiplié par quatre depuis 1990. La mondialisation a fait émerger de **nouvelles puissances** : la **Chine**, « atelier du monde » devenue deuxième économie mondiale en 2010, qui investit en Afrique et à Madagascar (« nouvelles routes de la soie ») ; l'**Inde**, le **Brésil**, l'Afrique du Sud, réunis avec la Russie dans les **BRICS** (2009) ; l'**Union européenne**, forte de 27 membres et de l'euro. Le monde est devenu **multipolaire**." },
    { t: "h", x: "4. Les limites : inégalités et défis" },
    { t: "p", x: "La mondialisation a sorti de la pauvreté extrême des centaines de millions d'Asiatiques, mais elle a **creusé les inégalités** entre pays et à l'intérieur des pays. Elle propage les **crises** financières (1997, 2008) et sanitaires (**Covid-19**, 2020), accélère le **réchauffement climatique** et provoque des **migrations** massives. L'Afrique reste largement en marge. **Madagascar**, membre de l'ONU depuis 1960, de l'Union africaine, de la SADC et de la Commission de l'océan Indien, exporte vanille, girofle, nickel, crevettes et textile vers la France, les États-Unis et la Chine, importe le riz et les produits manufacturés d'Asie, reçoit l'aide de la Banque mondiale, du FMI et de l'Union européenne ; mais environ **75 % de ses habitants** vivent sous le seuil de pauvreté et le pays se classe **177e sur 193** pour l'indice de développement humain (2022). Le défi du développement, posé dès l'indépendance, reste entier." },
  ],
},
// =====================================================================
{
  num: 25, theme: THEME,
  titre: "Madagascar depuis 1960 : les Républiques successives, les événements majeurs et les institutions",
  objectif: "établir la chronologie de Madagascar depuis 1960 (Première, Deuxième, Troisième et Quatrième Républiques, transitions), d'identifier les événements majeurs et les principaux dirigeants, et de présenter les institutions de la République à l'aide d'une frise et d'un organigramme",
  documentation: `${DOC_PROG} ; S. Randrianja et S. Ellis, Madagascar. A Short History (2009) ; F. Rajaonah (dir.), Histoire de Madagascar (2016) ; D. Galibert, Les Gens du pouvoir à Madagascar (2009) ; Constitutions de 1959, 1975, 1992, 2010 (Journal officiel) ; presse et communiqués officiels 2025-2026.`,
  image: { file: "frise_madagascar_1960_2025.png", legende: "Frise chronologique de Madagascar de 1960 à 2025 : Républiques, transitions et présidents", widthCm: 15, source: "réalisation J-Learn d'après Randrianja & Ellis (2009), Rajaonah (2016) et les textes constitutionnels" },
  revision: [
    ["Qui sont les États-Unis dans le monde depuis 1991 ?", "La seule superpuissance, « gendarme du monde »."],
    ["Qu'est-ce que la mondialisation ?", "La mise en relation de toutes les régions du monde par les échanges de marchandises, capitaux, informations et personnes."],
    ["Quand et qui a proclamé l'indépendance de Madagascar ?", "Le 26 juin 1960, Philibert Tsiranana."],
    ["Quelle est la place de Madagascar dans le monde actuel ?", "Un pays connecté par ses exportations mais parmi les plus pauvres (IDH 177e)."],
  ],
  miseEnSituation: {
    enseignant: [
      "Mai 1972, Antananarivo. Des milliers d'étudiants et de lycéens occupent la place de l'Indépendance pour réclamer la « malgachisation » de l'enseignement et la fin de la coopération avec la France. Le 13 mai, la police tire : plusieurs dizaines de morts. Cinq jours plus tard, le président Tsiranana remet le pouvoir au général Ramanantsoa. Cette scène se répétera : en 1991, en 2002, en 2009, et encore en septembre-octobre 2025, la rue a fait tomber le pouvoir.",
      "Comment le pays est-il gouverné depuis 1960 ? Pourquoi les crises politiques reviennent-elles si souvent ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : le pays a connu plusieurs Républiques et plusieurs présidents ; les crises viennent de la pauvreté, des élections contestées et du non-respect des institutions."],
  },
  observation: {
    enseignant: ["Regardez et observez bien cette frise chronologique et cet organigramme que j'écris au tableau noir :", "| Période | Régime | Dirigeants et événements majeurs |", "| 1960-1972 | Première République (Constitution de 1959, régime présidentiel) | Philibert Tsiranana (PSD) : liens étroits avec la France (accords de coopération, bases militaires), stabilité, « socialisme malgache » modéré ; révolte paysanne du Sud (avril 1971) ; mai 1972 : grève des étudiants, répression du 13 mai, Tsiranana remet le pouvoir au général Gabriel Ramanantsoa |", "| 1972-1975 | Transition militaire | Ramanantsoa : malgachisation, sortie de la zone franc, départ des troupes françaises (1973) ; février 1975 : colonel Richard Ratsimandrava, assassiné après 6 jours ; Directoire militaire |", "| 1975-1992 | Deuxième République (Constitution du 21 décembre 1975, « République démocratique de Madagascar ») | Didier Ratsiraka (AREMA) : révolution socialiste, Charte de la Révolution (« Boky Mena »), nationalisations, fokonolona, rapprochement avec l'URSS ; crise économique, dette, ajustement structurel (FMI, années 1980) ; 1991 : grèves générales des Forces vives, marche du 10 août sur Iavoloha (morts), convention du Panorama (31 octobre 1991) |", "| 1992-2010 | Troisième République (Constitution du 18 septembre 1992, régime parlementaire puis présidentiel après 1998) | Albert Zafy (1993-1996), empêché par l'Assemblée ; retour de Ratsiraka (1997-2002) ; crise post-électorale de 2002 (six mois, barrages) : Marc Ravalomanana (2002-2009), Madagascar Action Plan, routes, mais tensions ; janvier-mars 2009 : manifestations d'Andry Rajoelina, fusillade du 7 février, Ravalomanana remet le pouvoir à un directoire militaire qui le transmet à Rajoelina (17 mars 2009) |", "| 2009-2014 | Transition (Haute Autorité de la Transition) | Andry Rajoelina : isolement international (suspension UA, SADC), feuille de route de la SADC (2011) ; Constitution de la Quatrième République adoptée par référendum le 17 novembre 2010 (promulguée le 11 décembre 2010) |", "| 2014-2025 | Quatrième République | Hery Rajaonarimampianina (2014-2018) ; Andry Rajoelina élu (décembre 2018) et réélu (novembre 2023, scrutin boycotté par l'opposition) ; septembre 2025 : manifestations de la jeunesse (« Gen Z ») contre les coupures d'eau et d'électricité et la corruption ; 14 octobre 2025 : l'Assemblée nationale destitue Rajoelina ; 17 octobre 2025 : le colonel Michaël Randrianirina investi président de la Refondation ; Constitution suspendue, transition de 24 mois annoncée vers une nouvelle constitution et des élections |", "| Institutions (Constitution de 2010) | Président de la République (élu au suffrage universel pour 5 ans, chef de l'État, nomme le Premier ministre) ; Gouvernement (Premier ministre et ministres) ; Parlement : Assemblée nationale (députés élus) et Sénat ; Haute Cour constitutionnelle ; justice indépendante ; collectivités : provinces, régions, communes, fokontany |"],
    support: "Tableau noir (frise chronologique et organigramme recopiés)",
    note: "Le programme demande une frise des Républiques et un organigramme des institutions selon les constitutions : faire tracer la frise (1960-2025) et l'organigramme (Président – Gouvernement – Parlement – HCC) dans le cahier. Actualiser la fin de la frise selon l'évolution de la transition en cours.",
  },
  analyse: [
    ["Caractérisez la Première République (1960-1972).", "Fondée sur la Constitution de 1959, c'est un régime présidentiel dominé par Philibert Tsiranana et son parti, le PSD ; elle garde des liens très étroits avec la France (accords de coopération, bases militaires, monnaie liée au franc, coopérants) et connaît une relative stabilité et un « socialisme malgache » modéré, mais l'opposition (AKFM, MONIMA) dénonce une « indépendance de façade »."],
    ["Pourquoi et comment la Première République prend-elle fin ?", "La révolte paysanne du Sud (avril 1971) puis, en mai 1972, la grève des étudiants et des lycéens réclamant la malgachisation de l'enseignement et la fin de la dépendance, rejoints par les ouvriers et les habitants d'Antananarivo ; la répression du 13 mai fait des dizaines de morts ; le 18 mai, Tsiranana remet les pleins pouvoirs au général Gabriel Ramanantsoa."],
    ["Que fait la transition militaire de 1972-1975 ?", "Ramanantsoa engage la malgachisation, renégocie les accords avec la France, quitte la zone franc et obtient le départ des troupes françaises (1973) ; en février 1975, il cède le pouvoir au colonel Richard Ratsimandrava, assassiné six jours plus tard ; un Directoire militaire choisit alors Didier Ratsiraka."],
    ["Caractérisez la Deuxième République (1975-1992).", "La République démocratique de Madagascar, fondée par la Constitution du 21 décembre 1975, engage sous Didier Ratsiraka une révolution socialiste inspirée par la Charte de la Révolution (« Boky Mena ») : nationalisation des banques et des grandes entreprises, décentralisation par les fokonolona, rapprochement avec l'URSS et les pays socialistes ; mais l'économie s'effondre dans les années 1980 : dette, pénuries, ajustement structurel imposé par le FMI et la Banque mondiale."],
    ["Comment passe-t-on à la Troisième République ?", "En 1991, les Forces vives, coalition d'opposition menée par Albert Zafy, organisent des grèves générales et d'immenses manifestations pour réclamer la démocratie ; la marche du 10 août sur le palais d'Iavoloha est réprimée dans le sang ; la convention du Panorama (31 octobre 1991) ouvre une transition qui aboutit à la Constitution du 18 septembre 1992 et à l'élection de Zafy en 1993."],
    ["Quels sont les événements majeurs de la Troisième République (1992-2010) ?", "L'empêchement du président Zafy par l'Assemblée (1996) et le retour de Ratsiraka (1997) ; la crise post-électorale de 2002 entre Ratsiraka et Marc Ravalomanana (six mois de blocage, barrages, deux gouvernements), dénouée par la reconnaissance de Ravalomanana ; ses années de croissance et de grands travaux mais aussi d'autoritarisme ; enfin la crise de 2009 : manifestations du maire d'Antananarivo Andry Rajoelina, fusillade du 7 février devant le palais d'Ambohitsorohitra, démission de Ravalomanana et transfert du pouvoir à Rajoelina par un directoire militaire (17 mars 2009), condamné par la communauté internationale comme un coup d'État."],
    ["Comment naît la Quatrième République et quels en sont les événements majeurs ?", "Après une longue transition (Haute Autorité de la Transition, 2009-2014), sous la pression de la SADC, une nouvelle Constitution est adoptée par référendum le 17 novembre 2010 et des élections ont lieu en 2013 : Hery Rajaonarimampianina (2014-2018), puis Andry Rajoelina élu en 2018 et réélu en 2023 lors d'un scrutin boycotté par l'opposition ; en septembre 2025, des manifestations de la jeunesse contre les coupures d'eau et d'électricité et la corruption dégénèrent en crise politique : l'Assemblée nationale destitue Rajoelina le 14 octobre 2025 et le colonel Michaël Randrianirina est investi président de la Refondation le 17 octobre 2025 ; la Constitution est suspendue et une transition de 24 mois est annoncée."],
    ["Quelles sont les institutions de la République selon la Constitution de 2010 ?", "Le président de la République, élu au suffrage universel pour cinq ans, chef de l'État, qui nomme le Premier ministre ; le gouvernement, dirigé par le Premier ministre, qui conduit la politique de la nation ; le Parlement, formé de l'Assemblée nationale (députés élus) et du Sénat, qui vote les lois et le budget ; la Haute Cour constitutionnelle, qui veille au respect de la Constitution et proclame les résultats des élections ; une justice indépendante ; et des collectivités territoriales décentralisées : provinces, régions, communes et fokontany."],
  ],
  analyseTechnique: "Lecture de frise chronologique et d'organigramme, questions-réponses, construction d'une frise et d'un organigramme par les élèves",
  synthese: "Donc, depuis 1960, Madagascar a connu quatre Républiques séparées par des transitions nées de crises populaires. La Première République de Tsiranana (1960-1972), proche de la France, tombe après les événements de mai 1972 ; la Deuxième République de Ratsiraka (1975-1992) tente une révolution socialiste qui s'achève dans la crise économique et les manifestations de 1991 ; la Troisième République (1992-2010), marquée par Zafy, Ratsiraka et Ravalomanana, est emportée par la crise de 2009 ; la Quatrième République (2010-2025), avec Rajaonarimampianina puis Rajoelina, s'interrompt en octobre 2025 avec la destitution du président et l'ouverture d'une transition sous le colonel Randrianirina. Les institutions reposent sur un président élu, un gouvernement, un Parlement et une Haute Cour constitutionnelle, mais leur fragilité et la pauvreté expliquent la répétition des crises.",
  application: [
    { consigne: "Associez chaque président à sa République ou à sa période (recopiez les couples).", pts: 4, items: [
      "1. Philibert Tsiranana — 2. Didier Ratsiraka — 3. Marc Ravalomanana — 4. Andry Rajoelina",
      "A. Deuxième République (1975-1992) et fin de la Troisième (1997-2002)",
      "B. Troisième République (2002-2009)",
      "C. Première République (1960-1972)",
      "D. Transition (2009-2014) puis Quatrième République (2019-2025)",
    ], corrige: [
      "1 → **C** ; 2 → **A** ; 3 → **B** ; 4 → **D**.",
      "(A : **Ratsiraka**.)",
      "(B : **Ravalomanana**.)",
      "(C : **Tsiranana** ; D : **Rajoelina**.)",
    ]},
    { consigne: "Datez les événements suivants et indiquez quelle République ils ont fait tomber ou fondée.", pts: 4, items: [
      "1. Répression de la grève des étudiants et remise du pouvoir au général Ramanantsoa.",
      "2. Marche des Forces vives sur Iavoloha.",
      "3. Référendum adoptant la Constitution de la Quatrième République.",
      "4. Destitution du président Rajoelina par l'Assemblée nationale.",
    ], corrige: [
      "1. **13-18 mai 1972** — fin de la **Première République**.",
      "2. **10 août 1991** — fin de la **Deuxième République**.",
      "3. **17 novembre 2010** — fondation de la **Quatrième République**.",
      "4. **14 octobre 2025** — interruption de la **Quatrième République**, début d'une transition.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) La Première République avait rompu tous les liens avec la France.",
      "b) La Deuxième République a mené une politique socialiste inspirée du « Boky Mena ».",
      "c) La crise de 2002 a opposé Ratsiraka et Ravalomanana après une élection contestée.",
      "d) Selon la Constitution de 2010, le président de la République est élu pour sept ans.",
    ], corrige: [
      "a) **Faux** : elle gardait des liens **très étroits** (coopération, bases, monnaie).",
      "b) **Vrai** : nationalisations, fokonolona, rapprochement avec l'URSS.",
      "c) **Vrai** : six mois de blocage du pays.",
      "d) **Faux** : pour **cinq ans**, au suffrage universel.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Présentez la Première République : dirigeant, orientation, fin.",
      "2. Comparez la Deuxième et la Troisième République (orientation politique et économique, fin).",
      "3. Décrivez les institutions de la République selon la Constitution de 2010 sous forme d'organigramme commenté.",
      "4. À partir de la frise 1960-2025, expliquez pourquoi les crises politiques se répètent à Madagascar.",
    ], corrige: [
      "1. **Tsiranana** (PSD), régime **présidentiel** proche de la **France**, « socialisme malgache » modéré ; fin après la révolte de **1971** et les **événements de mai 1972**.",
      "2. Deuxième République (**Ratsiraka**) : **socialiste**, nationalisations, proche de l'**URSS**, fin dans la **crise économique** et les manifestations de **1991**. Troisième République (**Zafy, Ratsiraka, Ravalomanana**) : **libérale** et démocratique, ouverture au marché, crises de **2002** et de **2009** qui l'emportent.",
      "3. **Président** (élu 5 ans, chef de l'État) → nomme le **Premier ministre** et le **gouvernement** ; **Parlement** (Assemblée nationale + Sénat) vote les lois ; **Haute Cour constitutionnelle** contrôle la Constitution et les élections ; **justice** indépendante ; **collectivités** (provinces, régions, communes, fokontany).",
      "4. Toutes les crises (1972, 1991, 2002, 2009, 2025) naissent de **mécontentements populaires** (pauvreté, coût de la vie, services défaillants), d'**élections contestées** et du **non-respect des institutions** ; elles se règlent dans la **rue** et par des **transitions**, ce qui affaiblit l'État et le développement.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Depuis le 26 juin 1960, Madagascar a connu quatre Républiques, plusieurs transitions et huit chefs d'État. Cette histoire mouvementée, marquée par des crises politiques récurrentes, éclaire les institutions et les défis du pays d'aujourd'hui." },
    { t: "h", x: "1. La Première République (1960-1972)" },
    { t: "p", x: "Fondée sur la Constitution de 1959, la **Première République** est un régime présidentiel dominé par **Philibert Tsiranana** et son parti, le **PSD**. Elle conserve des liens très étroits avec la **France** : accords de coopération, bases militaires (Diego-Suarez, Ivato), monnaie liée au franc, nombreux coopérants ; l'opposition (AKFM, MONIMA) dénonce une « indépendance de façade ». Le régime prône un « socialisme malgache » modéré et apporte une relative stabilité. Mais la **révolte paysanne du Sud** (avril 1971), durement réprimée, puis les **événements de mai 1972**, grève des étudiants et des lycéens pour la malgachisation de l'enseignement, rejoints par les travailleurs de la capitale, et fusillade du **13 mai**, l'emportent : le 18 mai 1972, Tsiranana remet les pleins pouvoirs au général **Gabriel Ramanantsoa**." },
    { t: "h", x: "2. La transition militaire et la Deuxième République (1972-1992)" },
    { t: "p", x: "Ramanantsoa engage la **malgachisation**, renégocie les accords avec la France, quitte la zone franc et obtient le départ des troupes françaises (1973). En février 1975, il cède le pouvoir au colonel **Richard Ratsimandrava**, assassiné six jours plus tard ; un Directoire militaire choisit le capitaine de frégate **Didier Ratsiraka**. La Constitution du 21 décembre 1975 fonde la **République démocratique de Madagascar**, la **Deuxième République**. Guidée par la **Charte de la Révolution** (le « **Boky Mena** »), elle engage une révolution socialiste : nationalisation des banques et des grandes entreprises, décentralisation par les **fokonolona**, parti dominant (AREMA), rapprochement avec l'URSS et les pays socialistes. Mais dans les années 1980, l'économie s'effondre : dette, pénuries, chute des revenus ; le FMI et la Banque mondiale imposent l'**ajustement structurel**. En 1991, les **Forces vives** d'Albert Zafy lancent des grèves générales et d'immenses manifestations ; la marche du **10 août 1991** sur le palais d'Iavoloha est réprimée dans le sang ; la **convention du Panorama** (31 octobre 1991) ouvre une transition démocratique." },
    { t: "h", x: "3. La Troisième République (1992-2010)" },
    { t: "p", x: "La Constitution du **18 septembre 1992** instaure un régime parlementaire, devenu présidentiel après la révision de 1998. **Albert Zafy** (1993-1996) est empêché par l'Assemblée nationale ; **Didier Ratsiraka** revient au pouvoir (1997-2002). L'élection présidentielle de décembre 2001 débouche sur la **crise de 2002** : pendant six mois, deux présidents, deux capitales, des barrages coupent le pays, jusqu'à la reconnaissance de **Marc Ravalomanana** (2002-2009). Son mandat apporte croissance, routes et Madagascar Action Plan, mais aussi des tensions avec l'opposition et les milieux d'affaires. En janvier 2009, le maire d'Antananarivo **Andry Rajoelina** soulève la capitale ; la fusillade du **7 février** devant le palais d'Ambohitsorohitra fait des dizaines de morts ; le 17 mars 2009, Ravalomanana remet le pouvoir à un directoire militaire qui le transmet à Rajoelina. La communauté internationale condamne ce coup d'État et suspend Madagascar de l'Union africaine et de la SADC." },
    { t: "h", x: "4. La Quatrième République (2010-2025) et la transition actuelle" },
    { t: "p", x: "Après la **Haute Autorité de la Transition** (2009-2014), la Constitution de la **Quatrième République** est adoptée par référendum le **17 novembre 2010**. **Hery Rajaonarimampianina** (2014-2018), puis **Andry Rajoelina**, élu en décembre 2018 et réélu en novembre 2023 lors d'un scrutin boycotté par l'opposition, la dirigent. En septembre 2025, des manifestations de la jeunesse (« Gen Z ») contre les coupures d'eau et d'électricité et la corruption s'étendent au pays ; le **14 octobre 2025**, l'Assemblée nationale destitue le président Rajoelina et, le **17 octobre 2025**, le colonel **Michaël Randrianirina** est investi **président de la Refondation** ; la Constitution est suspendue et une transition de 24 mois est annoncée vers une nouvelle constitution et des élections." },
    { t: "h", x: "5. Les institutions de la République" },
    { t: "p", x: "Selon la Constitution de 2010, le **président de la République**, élu au suffrage universel pour cinq ans, est le chef de l'État ; il nomme le **Premier ministre**, qui dirige le **gouvernement** et conduit la politique de la nation. Le **Parlement**, composé de l'**Assemblée nationale** (députés élus) et du **Sénat**, vote les lois et le budget et contrôle le gouvernement. La **Haute Cour constitutionnelle** veille au respect de la Constitution et proclame les résultats des élections. La **justice** est indépendante. Les **collectivités territoriales décentralisées** (provinces, régions, communes) et les **fokontany** administrent la vie locale. Ce schéma, hérité des constitutions de 1959, 1975 et 1992, a été chaque fois ébranlé par les crises de 1972, 1991, 2002, 2009 et 2025, nées de la pauvreté, des élections contestées et du non-respect des règles : construire des institutions solides et respectées reste le grand défi de la nation malgache." },
  ],
},
];
