// ============================================================
// Unité III — Maladies infectieuses (20 h)
// ============================================================
const U = {
  num: "III",
  titre: "Maladies infectieuses",
  ras: "Analyser les caractéristiques des microorganismes · Participer à la lutte contre les maladies infectieuses",
  valeurs: "Esprit de curiosité, culture de l'excellence",
  topics: [
    {
      type: "cours",
      titre: "Découverte des microorganismes",
      theme: "Maladies infectieuses",
      ras: "Analyser les caractéristiques des microorganismes",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "identifier les groupes de microorganismes et leurs caractéristiques générales",
      supportMeta: "Schémas de microorganismes, loupe, documents, éventuellement microscope",
      revision: [
        ["Qu'est-ce qu'une maladie infectieuse ?", "Une maladie causée par un être vivant microscopique qui entre dans le corps."],
        ["Peut-on toujours voir les microbes à l'œil nu ?", "Non, la plupart des microbes sont invisibles sans microscope."],
      ],
      mise: ["Pourquoi se lave-t-on les mains avant de manger ?", "Pour éliminer les microbes invisibles qui peuvent provoquer des maladies."],
      observation: "les schémas de microorganismes (bactéries, champignons, virus, parasites)",
      observationSupport: "Schémas de microorganismes",
      technAna: "Observation et questionnement",
      qa: [
        ["Que sont les microorganismes ?", "Ce sont des êtres vivants microscopiques : bactéries, champignons, virus et parasites."],
        ["Tous les microbes sont-ils dangereux ?", "Non, certains sont utiles ; seuls les microbes pathogènes (nuisibles) provoquent des maladies."],
        ["Quels sont les quatre groupes cités ?", "Les bactéries, les champignons, les virus et les parasites."],
        ["Comment observe-t-on les microorganismes ?", "Avec un microscope, ou sur des schémas et photos."],
      ],
      synthese: "Donc, les microorganismes sont des êtres vivants invisibles à l'œil nu ; certains sont utiles, d'autres pathogènes (nuisibles) et ils comprennent les bactéries, les champignons, les virus et les parasites.",
      motsCles: ["microorganismes", "bactéries", "champignons", "virus", "parasites"],
      contenu: [
        { sousTitre: "1. Définition", texte: "Un microorganisme est un être vivant très petit, généralement invisible à l'œil nu, qui est observable au microscope." },
        { sousTitre: "2. Les grands groupes", liste: ["Les bactéries : cellules simples.", "Les champignons : comme les levures ou les moisissures.", "Les virus : très petits, ils se multiplient dans les cellules.", "Les parasites : plus grands que les bactéries, ils vivent aux dépens d'un hôte."] },
        { sousTitre: "3. Utiles ou nuisibles", texte: "Les microorganismes non pathogènes sont utiles (fermentation du yaourt, du pain, décomposition des déchets). Les microorganismes pathogènes sont nuisibles et provoquent des maladies infectieuses." },
        { sousTitre: "4. Caractéristiques générales", liste: ["Ils se multiplient souvent très vite.", "Ils ont un cycle de vie.", "Ils peuvent être contaminés par l'eau, les aliments, l'air ou le contact."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Les bactéries, champignons, virus et parasites sont des…", opts: ["microorganismes", "animaux", "minéraux"], ok: 0, expl: "Ce sont les grands groupes de microorganismes." },
          { q: "Un microorganisme pathogène est…", opts: ["utile", "nuisible", "neutre"], ok: 1, expl: "Pathogène signifie nuisible pour la santé." },
          { q: "Les microorganismes s'observent…", opts: ["à l'œil nu", "au microscope", "avec une boussole"], ok: 1, expl: "Ils sont généralement invisibles à l'œil nu." },
          { q: "Le yaourt est fabriqué grâce à…", opts: ["des bactéries utiles", "des virus", "des parasites"], ok: 0, expl: "La fermentation lactique fait intervenir des bactéries." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Tous les microbes sont dangereux.", rep: false, expl: "Beaucoup sont utiles." },
          { txt: "Les virus se multiplient à l'intérieur des cellules.", rep: true, expl: "C'est une caractéristique des virus." },
          { txt: "Les champignons peuvent être des microorganismes.", rep: true, expl: "Les levures et moisissures en sont." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "Un être vivant microscopique s'appelle un", suite: "microorganisme" },
          { debut: "Les bactéries, champignons, virus et parasites sont les quatre groupes de", suite: "microorganismes" },
          { debut: "Un microbe qui provoque une maladie est dit", suite: "pathogène" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les bactéries",
      theme: "Maladies infectieuses",
      ras: "Analyser les caractéristiques des microorganismes",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "décrire la structure et le cycle de vie des bactéries",
      supportMeta: "Schéma d'une bactérie, photos, documents",
      revision: [
        ["Cite les quatre groupes de microorganismes.", "Bactéries, champignons, virus, parasites."],
        ["Que signifie « pathogène » ?", "Nuisible, qui peut provoquer une maladie."],
      ],
      mise: ["Pourquoi certains aliments aigrissent-ils ?", "Parce que des bactéries (non pathogènes) les transforment."],
      observation: "le schéma d'une bactérie",
      observationSupport: "Schéma d'une bactérie",
      technAna: "Observation guidée",
      qa: [
        ["Comment est une bactérie ?", "C'est une cellule simple, souvent en bâtonnet, en coque ou en spirale, entourée d'une membrane."],
        ["Comment se reproduisent-elles ?", "Elles se divisent en deux (division cellulaire)."],
        ["Cite des bactéries utiles.", "Les bactéries du yaourt, du fromage, et celles qui décomposent les déchets."],
        ["Cite des bactéries nuisibles.", "Cellules qui provoquent le choléra, la tuberculose, certaines infections."],
      ],
      synthese: "Donc, les bactéries sont des cellules simples qui se multiplient par division ; certaines sont utiles (fermentation), d'autres pathogènes (maladies).",
      motsCles: ["bactérie", "cellule", "division", "fermentation", "pathogène"],
      contenu: [
        { sousTitre: "1. Structure", liste: ["Une bactérie est une cellule simple.", "Elle possède une membrane et du cytoplasme.", "Elle n'a pas de noyau organisé."] },
        { sousTitre: "2. Formes", liste: ["En bâtonnet (bacilles).", "En coque (cocci).", "En spirale (spirilles)."] },
        { sousTitre: "3. Cycle de vie", texte: "Les bactéries se reproduisent par division : une cellule donne deux cellules. Ce processus peut être très rapide." },
        { sousTitre: "4. Rôle dans la santé", liste: ["Utiles : fermentation (yaourt, fromage), décomposition des déchets, équilibre intestinal.", "Nuisibles : provoquent des maladies infectieuses comme le choléra, les infections de la peau, la tuberculose."] },
      ],
      appExos: [
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Une bactérie est une cellule simple.", rep: true, expl: "C'est une cellule procaryote." },
          { txt: "Les bactéries se reproduisent par division en deux.", rep: true, expl: "C'est leur mode de reproduction." },
          { txt: "Toutes les bactéries provoquent des maladies.", rep: false, expl: "Beaucoup sont utiles." },
          { txt: "Les bactéries du yaourt sont utiles.", rep: true, expl: "Elles permettent la fermentation." },
        ]},
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Cite deux rôles utiles des bactéries.", r: "La fermentation des aliments (yaourt) et la décomposition des déchets." },
          { q: "Comment une bactérie se reproduit-elle ?", r: "Par division : une cellule donne deux cellules." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "Une bactérie est une cellule", suite: "simple" },
          { debut: "Le fermenteur qui devient du yaourt est une", suite: "bactérie" },
          { debut: "Une bactérie provoquant une maladie est", suite: "pathogène" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les champignons",
      theme: "Maladies infectieuses",
      ras: "Analyser les caractéristiques des microorganismes",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "décrire la structure et le cycle de vie des champignons",
      supportMeta: "Schéma d'un champignon microscopique, photos",
      revision: [
        ["Quelle est la forme d'une bactérie ?", "Elle peut être en bâtonnet, en coque ou en spirale."],
        ["Que deviennent les bactéries utiles ?", "Elles fermentent les aliments et décomposent les déchets."],
      ],
      mise: ["Pourquoi le pain lève-t-il ?", "Grâce à la levure, un champignon microscopique qui produit du gaz."],
      observation: "le schéma d'un champignon microscopique",
      observationSupport: "Schéma champignon",
      technAna: "Observation questionnée",
      qa: [
        ["Comment est un champignon microscopique ?", "Il peut être formé de filaments (moisissures) ou d'une cellule (levure)."],
        ["Comment se reproduit-il ?", "Par spores, ou par bourgeonnement pour les levures."],
        ["Cite des champignons utiles.", "Les levures du pain, celles du fromage, la moisissure du fromage (roquefort)."],
        ["Cite des champignons nuisibles.", "Les champignons qui provoquent les mycoses ou des infections de la peau."],
      ],
      synthese: "Donc, les champignons microscopiques sont des levures ou des moisissures ; ils se reproduisent par spores ou bourgeonnement et peuvent être utiles (pain, fromage) ou pathogènes (mycoses).",
      motsCles: ["champignon", "levure", "moisissure", "spores", "mycoses"],
      contenu: [
        { sousTitre: "1. Structure", liste: ["Les champignons unicellulaires (levures) sont des cellules rondes.", "Les champignons filamenteux (moisissures) forment des filaments."] },
        { sousTitre: "2. Cycle de vie", liste: ["Les levures se reproduisent par bourgeonnement.", "Les moisissures produisent des spores qui donnent de nouveaux champignons."] },
        { sousTitre: "3. Rôle dans la santé", liste: ["Utiles : levure du pain, fermentation du vin, fromage, décomposition des matières organiques.", "Nuisibles : mycoses, infections de la peau, moisissures toxiques sur les aliments."] },
        { sousTitre: "4. Exemple", texte: "La levure de boulanger est un champignon utilisé pour faire lever le pain en produisant du dioxyde de carbone." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "La levure est un…", opts: ["champignon", "virus", "parasite"], ok: 0, expl: "La levure est un champignon microscopique." },
          { q: "Les moisissures se reproduisent par…", opts: ["spores", "division en 2", "virus"], ok: 0, expl: "Les moisissures produisent des spores." },
          { q: "Les champignons pathogènes peuvent causer…", opts: ["des mycoses", "le choléra", "le paludisme"], ok: 0, expl: "Les mycoses sont des infections fongiques." },
          { q: "Le pain lève grâce à…", opts: ["des levures", "des virus", "des parasites"], ok: 0, expl: "Les levures produisent du gaz." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Les levures sont des champignons microscopiques.", rep: true, expl: "Ce sont des champignons unicellulaires." },
          { txt: "Tous les champignons sont nuisibles.", rep: false, expl: "Beaucoup sont utiles." },
          { txt: "Les moisissures forment des filaments.", rep: true, expl: "Ce sont des champignons filamenteux." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "La levure de boulanger est un", suite: "champignon" },
          { debut: "Le champignon qui provoque une infection de la peau est dit", suite: "pathogène" },
          { debut: "Pour faire lever le pain, on utilise de la", suite: "levure" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les virus et les parasites",
      theme: "Maladies infectieuses",
      ras: "Analyser les caractéristiques des microorganismes",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "différencier les virus, les parasites et les autres microbes",
      supportMeta: "Schémas de virus et de parasites",
      revision: [
        ["Quels sont les deux types de champignons ?", "Les levures et les moisissures."],
        ["Qu'est-ce qu'une spore ?", "Une particule qui permet à un champignon de se reproduire."],
      ],
      mise: ["Comment les virus sont-ils différents d'une bactérie ?", "Le virus est très petit et ne peut se multiplier que dans une cellule."],
      observation: "les schémas de virus et de parasites",
      observationSupport: "Schémas virus et parasites",
      technAna: "Comparaison guidée",
      qa: [
        ["Comment est un virus ?", "C'est une particule très petite, parfois enveloppée, qui se multiplie à l'intérieur des cellules."],
        ["Cite des maladies à virus.", "La grippe, la rougeole, le VIH (SIDA)."],
        ["Que sont les parasites ?", "Ce sont des êtres vivants qui vivent aux dépens d'un autre organisme (l'hôte)."],
        ["Cite des maladies à parasites.", "Le paludisme, les vers intestinaux."],
      ],
      synthese: "Donc, les virus sont de très petites particules qui se multiplient dans les cellules, tandis que les parasites sont des organismes qui vivent aux dépens d'un hôte ; les deux peuvent provoquer des maladies.",
      motsCles: ["virus", "parasites", "hôte", "paludisme", "grippe"],
      contenu: [
        { sousTitre: "1. Les virus", liste: ["Très petits, plus petits que les bactéries.", "Ils ne peuvent pas vivre seuls.", "Ils se multiplient à l'intérieur des cellules.", "Exemples de maladies : grippe, rougeole, hépatite, VIH."] },
        { sousTitre: "2. Les parasites", liste: ["Ce sont des organismes vivants.", "Ils vivent aux dépens d'un hôte.", "Ils peuvent être unicellulaires ou plus grands.", "Exemples : le parasite du paludisme, les vers intestinaux."] },
        { sousTitre: "3. Différences", texte: "Les virus ne sont pas des cellules et dépendent des cellules vivantes ; les parasites sont des organismes indépendants qui exploitent un hôte." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Un virus se multiplie…", opts: ["dans une cellule", "dans l'air", "dans le sol"], ok: 0, expl: "Les virus se multiplient à l'intérieur des cellules." },
          { q: "Le paludisme est une maladie causée par…", opts: ["un virus", "un parasite", "une bactérie"], ok: 1, expl: "Le paludisme est causé par un parasite transmis par le moustique." },
          { q: "La grippe est provoquée par…", opts: ["un virus", "un champignon", "un parasite"], ok: 0, expl: "La grippe est une maladie virale." },
          { q: "Un parasite vit…", opts: ["aux dépens d'un hôte", "autonome dans l'eau", "dans le sol"], ok: 0, expl: "Il exploite un organisme hôte." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Les virus sont plus petits que les bactéries.", rep: true, expl: "Ils sont très petits." },
          { txt: "Les parasites ne peuvent pas provoquer de maladie.", rep: false, expl: "Ils provoquent par exemple le paludisme." },
          { txt: "Les virus peuvent se reproduire seuls.", rep: false, expl: "Ils ont besoin d'une cellule." },
        ]},
      ],
      evalExos: [
        { type: "appariement", consigne: "Associe.", pointsPar: 1, items: [{ g: ["Virus", "Parasite", "Bactérie"], d: ["Paludisme", "Grippe", "Tuberculose"], pairs: [[0,1],[1,0],[2,2]] }] },
      ],
    },
    {
      type: "cours",
      titre: "L'infection microbienne et l'immunité",
      theme: "Maladies infectieuses",
      ras: "Participer à la lutte contre les maladies infectieuses",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "décrire les étapes d'une infection et le rôle des cellules immunitaires et des anticorps",
      supportMeta: "Schéma infection / immunité, documents",
      revision: [
        ["Qu'est-ce qu'un microbe pathogène ?", "Un microbe qui peut provoquer une maladie."],
        ["Cite une maladie causée par un virus.", "La grippe ou la rougeole."],
      ],
      mise: ["Comment ton corps se défend-il quand tu attrapes une infection ?", "Il reconnaît le germe comme étranger et produit des défenses (cellules et anticorps)."],
      observation: "le schéma de l'infection et de la réponse immunitaire",
      observationSupport: "Schéma infection/immunité",
      technAna: "Analyse de schéma",
      qa: [
        ["Quelles sont les étapes d'une infection ?", "Entrée du microbe, multiplication, manifestation des signes (fièvre, douleur), puis défense du corps."],
        ["Qu'est-ce que le « soi » et le « non-soi » ?", "Le soi regroupe les cellules de l'organisme ; le non-soi regroupe les microorganismes étrangers."],
        ["Quel est le rôle des cellules immunitaires ?", "Elles attaquent ou détruisent les microbes."],
        ["Quel est le rôle des anticorps ?", "Ils se fixent sur les microbes et aident à les neutraliser."],
      ],
      synthese: "Donc, au cours d'une infection, le corps reconnaît les éléments étrangers (non-soi) et déclenche une réponse immunitaire avec des cellules et des anticorps qui détruisent les microbes.",
      motsCles: ["infection", "immunité", "soi", "non-soi", "anticorps"],
      contenu: [
        { sousTitre: "1. Les étapes d'une infection", liste: ["Entrée du microbe dans le corps.", "Multiplication.", "Réaction du corps : fièvre, inflammation, douleur.", "Défense : cellules immunitaires et anticorps."] },
        { sousTitre: "2. Le soi et le non-soi", texte: "Le corps sait reconnaître ses propres cellules (le soi) et les éléments étrangers (le non-soi, comme les microbes)." },
        { sousTitre: "3. Les cellules immunitaires", liste: ["Globules blancs : détruisent les microbes.", "Cellules qui reconnaissent le microbe.", "Production d'anticorps."] },
        { sousTitre: "4. Les anticorps", texte: "Les anticorps sont des protéines produites par le corps qui se fixent sur les microbes et facilitent leur destruction, préparant la guérison." },
      ],
      appExos: [
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Quelles sont les grandes étapes d'une infection ?", r: "Entrée du microbe, multiplication, réaction de l'organisme (fièvre, inflammation), puis défense et guérison." },
          { q: "Quel est le rôle des anticorps ?", r: "Ils se fixent sur les microbes et aident à les neutraliser et à les détruire." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Le « soi » correspond aux cellules de l'organisme.", rep: true, expl: "Le soi regroupe les cellules du corps." },
          { txt: "Les microbes sont toujours reconnus comme du « soi ».", rep: false, expl: "Ils sont reconnus comme du « non-soi »." },
          { txt: "Les cellules immunitaires participent à la défense.", rep: true, expl: "Ce sont les globules blancs et leurs défenses." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "Les cellules étrangères au corps sont appelées le", suite: "non-soi" },
          { debut: "Les protéines qui neutralisent les microbes sont les", suite: "anticorps" },
          { debut: "La défense du corps contre les microbes s'appelle l'", suite: "immunité" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Antisepsie, asepsie, antibiotiques, vaccins, sérums",
      theme: "Maladies infectieuses",
      ras: "Participer à la lutte contre les maladies infectieuses",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "expliquer les notions d'antisepsie, d'asepsie, d'antibiotiques, de vaccins et de sérums",
      supportMeta: "Affiches, schémas, documents",
      revision: [
        ["Qu'est-ce qu'une infection microbienne ?", "La multiplication de microbes pathogènes dans le corps."],
        ["Comment le corps se défend-il ?", "Avec les cellules immunitaires et les anticorps."],
      ],
      mise: ["Pourquoi se désinfecte-t-on une plaie ?", "Pour éliminer les microbes et éviter l'infection."],
      observation: "les affiches et schémas",
      observationSupport: "Affiches antisepsie/asepsie/vaccins",
      technAna: "Lecture d'affiches",
      qa: [
        ["Qu'est-ce que l'asepsie ?", "C'est l'ensemble de mesures pour empêcher les microbes d'entrer dans le corps (matériel stérile, hygiène)."],
        ["Qu'est-ce que l'antisepsie ?", "C'est l'action de détruire les microbes sur une surface vivante (peau, plaie) avec un antiseptique."],
        ["À quoi servent les antibiotiques ?", "Ils luttent contre les bactéries. Ils sont inutiles contre les virus."],
        ["Quelle est la différence entre un vaccin et un sérum ?", "Le vaccin prépare le corps à se défendre (protection longue) ; le sérum apporte des anticorps immédiats (protection courte)."],
      ],
      synthese: "Donc, l'asepsie évite l'entrée des microbes, l'antisepsie les détruit sur les surfaces, les antibiotiques agissent sur les bactéries, les vaccins entrenent l'immunité et les sérums apportent des anticorps immédiats.",
      motsCles: ["asepsie", "antisepsie", "antibiotique", "vaccin", "sérum"],
      contenu: [
        { sousTitre: "1. L'asepsie", texte: "C'est l'élimination ou l'absence de microbes sur un objet, une surface ou dans un milieu (ex. matériel médical stérile)." },
        { sousTitre: "2. L'antisepsie", texte: "C'est l'application d'un antiseptique sur un tissu vivant (peau, plaie) pour détruire les microbes et prévenir l'infection." },
        { sousTitre: "3. Les antibiotiques", liste: ["Ils agissent contre les bactéries.", "Ils sont souvent prescrits par un médecin.", "Ils ne sont pas efficaces contre les virus."] },
        { sousTitre: "4. Le vaccin et le sérum", texte: "Le vaccin prépare l'organisme à se défendre contre un microbe donné (immunité durable). Le sérum contient des anticorps déjà formés et donne une protection immédiate mais de courte durée." },
        { sousTitre: "5. Médicaments complémentaires", liste: ["Antiparasitaires : contre les parasites.", "Antifongiques : contre les champignons."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "L'asepsie consiste à…", opts: ["éviter l'entrée des microbes", "détruire les microbes sur une plaie", "produire des anticorps"], ok: 0, expl: "L'asepsie empêche la contamination." },
          { q: "On utilise un antiseptique pour…", opts: ["désinfecter une plaie", "fabriquer un vaccin", "cuire les aliments"], ok: 0, expl: "L'antisepsie désinfecte la peau/plaie." },
          { q: "Les antibiotiques sont efficaces contre…", opts: ["les bactéries", "les virus", "les champignons"], ok: 0, expl: "Ils agissent sur les bactéries." },
          { q: "Le vaccin sert à…", opts: ["préparer le corps à se défendre", "apporter des anticorps immédiats", "tuer les parasites rapidement"], ok: 0, expl: "Le vaccin entraîne une immunité." },
        ]},
        { type: "appariement", consigne: "Associe.", pointsPar: 1, items: [{ g: ["Antiseptique", "Vaccin", "Sérum", "Antibiotique"], d: ["Contre les bactéries", "Désinfecte une plaie", "Prépare l'immunité", "Apporte des anticorps immédiats"], pairs: [[3,0],[1,2],[2,3],[0,1]] }] },
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Quelle est la différence entre un vaccin et un sérum ?", r: "Le vaccin prépare l'organisme à se défendre et donne une protection longue ; le sérum apporte des anticorps déjà formés et donne une protection immédiate mais courte." },
          { q: "Pourquoi les antibiotiques ne soignent-ils pas la grippe ?", r: "Parce que la grippe est causée par un virus, et les antibiotiques agissent sur les bactéries." },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Prévention et lutte contre les maladies infectieuses",
      theme: "Maladies infectieuses",
      ras: "Participer à la lutte contre les maladies infectieuses",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "appliquer les mesures individuelles et collectives de protection contre les maladies infectieuses",
      supportMeta: "Affiches d'hygiène, schémas, documents",
      revision: [
        ["Que fait le vaccin ?", "Il prépare le corps à se défendre contre un microbe."],
        ["Les antibiotiques sont-ils efficaces contre les virus ?", "Non."],
      ],
      mise: ["Quelles mesures prendre pour éviter qu'une maladie infectieuse se répande dans une école ?", "Se laver les mains, ne pas partager les verres, consulter un soignant, isoler les cas."],
      observation: "les affiches d'hygiène et les schémas de prévention",
      observationSupport: "Affiches hygiène + schémas",
      technAna: "Analyse documentaire et débat",
      qa: [
        ["Quelles sont les mesures individuelles ?", "Bien se laver les mains, boire de l'eau propre, bien cuire les aliments, se faire vacciner, consulter en cas de signes."],
        ["Quelles sont les mesures collectives ?", "Assainir l'eau, gérer les déchets, isoler les malades, vaccination collective, information de la communauté."],
        ["Pourquoi faut-il se vacciner ?", "Pour protéger son corps et la communauté contre les microbes."],
        ["Que faire en cas d'épidémie ?", "Suivre les consignes des autorités sanitaires, respecter l'hygiène, signaler les cas, éviter les rassemblements."],
      ],
      synthese: "Donc, la prévention des maladies infectieuses repose sur des mesures individuelles (hygiène, eau propre, cuisson, vaccination) et collectives (assainissement, gestion des déchets, vaccination de masse, information).",
      motsCles: ["prévention", "hygiène", "vaccination", "épidémie", "assainissement"],
      contenu: [
        { sousTitre: "1. Mesures individuelles", liste: ["Se laver les mains à l'eau et au savon.", "Boire de l'eau propre.", "Bien cuire les aliments.", "Se faire vacciner.", "Consulter tôt en cas de fièvre ou de signes de maladie."] },
        { sousTitre: "2. Mesures collectives", liste: ["Assainir l'eau et les milieux.", "Gérer les déchets correctement.", "Isoler les personnes malades.", "Vacciner la population.", "Informer la communauté."] },
        { sousTitre: "3. En cas d'épidémie", texte: "Il faut suivre les consignes du personnel de santé, garder les gestes d'hygiène, signaler les cas et éviter les rassemblements inutiles." },
      ],
      appExos: [
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Se laver les mains est une mesure individuelle contre les infections.", rep: true, expl: "C'est un geste d'hygiène essentiel." },
          { txt: "L'assainissement de l'eau est une mesure collective.", rep: true, expl: "Il protège toute la communauté." },
          { txt: "Il est inutile de se faire vacciner.", rep: false, expl: "Le vaccin protège l'individu et la communauté." },
          { txt: "En cas d'épidémie, il faut cacher les malades.", rep: false, expl: "Il faut les signaler et suivre les consignes sanitaires." },
        ]},
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Cite deux mesures individuelles contre les maladies infectieuses.", r: "Se laver les mains à l'eau et au savon, et boire de l'eau propre." },
          { q: "Cite deux mesures collectives.", r: "Assainir l'eau et vacciner la population." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "Se protéger des maladies infectieuses par une injection s'appelle", suite: "vaccination" },
          { debut: "En cas de maladie, on consulte un", suite: "personnel de santé" },
          { debut: "L'accès à une eau propre et le traitement des déchets sont des mesures", suite: "collectives" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les maladies infectieuses à Madagascar",
      theme: "Maladies infectieuses",
      ras: "Participer à la lutte contre les maladies infectieuses",
      valeurs: "Esprit de curiosité, culture de l'excellence",
      objectif: "identifier les principales maladies infectieuses rencontrées à Madagascar et les moyens de lutte",
      supportMeta: "Documents sur les maladies courantes, cartes, affiches de santé communautaire",
      revision: [
        ["Quelles sont les mesures individuelles de protection ?", "Se laver les mains, boire de l'eau propre, bien cuire les aliments, se faire vacciner, consulter tôt."],
        ["Quelle est la différence entre vaccin et sérum ?", "Le vaccin prépare l'immunité (protection longue) ; le sérum apporte des anticorps immédiats (protection courte)."],
      ],
      mise: ["Quelles maladies infectieuses voit-on souvent dans nos villages et nos villes ?", "Le paludisme, la tuberculose, le choléra, les vers intestinaux, la grippe et d'autres infections."],
      observation: "les documents et affiches de santé communautaire",
      observationSupport: "Documents maladies à Madagascar + affiches",
      technAna: "Analyse documentaire et travail de groupe",
      qa: [
        ["Quelles maladies infectieuses sont courantes à Madagascar ?", "Le paludisme, la tuberculose, le choléra, les infections respiratoires, les vers intestinaux, la peste et d'autres maladies microbiennes."],
        ["Comment se transmet le paludisme ?", "Par la piqûre d'un moustique (anophèle) qui transporte le parasite."],
        ["Comment se transmet le choléra ?", "Par l'eau ou les aliments contaminés par des bactéries."],
        ["Comment lutter contre ces maladies dans la communauté ?", "Par la prévention individuelle et collective : assainir l'eau, gérer les déchets, se protéger des moustiques, vacciner, consulter tôt et suivre les consignes sanitaires."],
      ],
      synthese: "Donc, à Madagascar, les maladies infectieuses comme le paludisme, le choléra, la tuberculose et les vers intestinaux sont fréquentes ; leur lutte repose sur la prévention (eau propre, hygiène, assainissement, protection contre les moustiques, vaccination) et sur un traitement précoce.",
      motsCles: ["paludisme", "choléra", "tuberculose", "vers intestinaux", "santé communautaire"],
      contenu: [
        { sousTitre: "1. Le paludisme", liste: ["Maladie transmise par la piqûre de moustiques.", "Causée par un parasite.", "Signes : fièvre, frissons, maux de tête, fatigue.", "Prévention : moustiquaires, assainissement, élimination des eaux stagnantes."] },
        { sousTitre: "2. Le choléra", liste: ["Maladie bactérienne.", "Transmise par l'eau ou les aliments souillés.", "Signes : diarrhée intense, vomissements, déshydratation.", "Prévention : eau propre, hygiène des mains, cuisson des aliments, assainissement."] },
        { sousTitre: "3. La tuberculose", liste: ["Maladie bactérienne des poumons.", "Transmise par la toux et les gouttelettes.", "Signes : toux prolongée, fièvre, amaigrissement.", "Lutte : vaccination (BCG), dépistage et traitement complet."] },
        { sousTitre: "4. Les vers intestinaux", liste: ["Maladie parasitaire liée à l'eau ou aux aliments souillés.", "Peut provoquer l'anémie et la fatigue.", "Prévention : hygiène toilette, eau propre, cuisson, chaussures."] },
        { sousTitre: "5. La lutte communautaire", liste: ["Assainir l'eau et les milieux.", "Gérer les déchets et les eaux usées.", "Éliminer les eaux stagnantes et utiliser la moustiquaire.", "Vacciner et dépister tôt.", "Informer la population et suivre les consignes sanitaires."] },
        { sousTitre: "Exemple", texte: "Dans un village, si les familles utilisent des moustiquaires, filtrent ou font bouillir l'eau et se rendent au centre de santé dès les premiers signes, le nombre de cas de paludisme et de choléra diminue." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Le paludisme est transmis par…", opts: ["la piqûre d'un moustique", "l'eau de pluie", "le vent"], ok: 0, expl: "Le moustique anophèle transporte le parasite." },
          { q: "Le choléra est causé par…", opts: ["des bactéries", "un virus", "un champignon"], ok: 0, expl: "C'est une maladie bactérienne." },
          { q: "Une bonne prévention du paludisme est…", opts: ["utiliser la moustiquaire", "manger du riz", "boire du lait chaud"], ok: 0, expl: "La moustiquaire protège contre les piqûres." },
          { q: "Pour éviter le choléra, il faut…", opts: ["boire de l'eau propre", "marcher pieds nus", "se coucher tôt"], ok: 0, expl: "L'eau propre évite la contamination." },
        ]},
        { type: "qr", consigne: "Réponds par une phrase.", pointsPar: 2, items: [
          { q: "Cite deux maladies infectieuses courantes à Madagascar.", r: "Le paludisme et le choléra (ou la tuberculose, les vers intestinaux)." },
          { q: "Comment la communauté peut-elle lutter contre les maladies infectieuses ?", r: "En assainissant l'eau, en éliminant les eaux stagnantes, en gérant les déchets, en vaccinant et en informant la population." },
        ]},
      ],
      evalExos: [
        { type: "appariement", consigne: "Associe la maladie à son mode de transmission.", pointsPar: 1, items: [{ g: ["Paludisme", "Choléra", "Tuberculose", "Vers intestinaux"], d: ["Eau ou aliments souillés", "Piqûre de moustique", "Toux et gouttelettes", "Eau ou aliments souillés"], pairs: [[1,1],[0,0],[2,2],[3,3]] }] },
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Le paludisme est une maladie parasitaire.", rep: true, expl: "Il est causé par un parasite transmis par le moustique." },
          { txt: "Le choléra se transmet par l'eau souillée.", rep: true, expl: "C'est une contamination bactérienne." },
          { txt: "Il est inutile d'éliminer les eaux stagnantes.", rep: false, expl: "Elles abritent les moustiques vecteurs." },
        ]},
      ],
    },
  ],
};
module.exports = U;
