// ============================================================
// Unité IV — Organisation des êtres vivants : écosystèmes (16 h)
// ============================================================
const U = {
  num: "IV",
  titre: "Organisation des êtres vivants",
  ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
  valeurs: "Respect de toute vie, altruisme",
  topics: [
    {
      type: "cours",
      titre: "Qu'est-ce qu'un écosystème ?",
      theme: "Organisation des êtres vivants",
      ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
      valeurs: "Respect de toute vie, altruisme",
      objectif: "définir un écosystème et identifier ses éléments",
      supportMeta: "Photos d'écosystèmes (forêt, rizière, étang, bord de mer), schéma",
      revision: [
        ["Qu'est-ce qu'un milieu naturel ?", "Un milieu où vivent des êtres vivants (ex. forêt, rivière, champ)."],
        ["Cites un être vivant et son milieu.", "Le poisson vit dans l'eau ; l'oiseau vit dans les arbres."],
      ],
      mise: ["Pourquoi la forêt ne contient-elle pas seulement des arbres ?", "Elle contient aussi des animaux, des plantes, de la terre, de l'eau, de l'air : tout forme un écosystème."],
      observation: "les photos d'écosystèmes",
      observationSupport: "Photos d'écosystèmes",
      technAna: "Observation et questionnement",
      qa: [
        ["Comment définir un écosystème ?", "Un ensemble formé par les êtres vivants et leur milieu, avec leurs interactions."],
        ["Quels sont les éléments non vivants ?", "L'eau, la lumière, la température, le sol, l'air, l'altitude."],
        ["Quels sont les éléments vivants ?", "Les plantes, animaux, champignons, microorganismes."],
        ["À Madagascar, cite un écosystème.", "La forêt de l'Est, la rizière, l'étang, le littoral."],
      ],
      synthese: "Donc, un écosystème est un ensemble d'êtres vivants (plantes, animaux, microbes) et de leur milieu physique (eau, sol, air, lumière) avec leurs interactions.",
      motsCles: ["écosystème", "milieu", "êtres vivants", "interactions", "équilibre"],
      contenu: [
        { sousTitre: "1. Définition", texte: "Un écosystème est l'ensemble des êtres vivants et de leur milieu naturel qui interagissent entre eux." },
        { sousTitre: "2. Les éléments vivants", liste: ["Plantes (producteurs).", "Animaux (consommateurs).", "Champignons et bactéries (décomposeurs)."] },
        { sousTitre: "3. Les éléments non vivants", liste: ["Eau.", "Air.", "Lumière.", "Température.", "Sol.", "Altitude."] },
        { sousTitre: "4. Exemples d'écosystèmes", liste: ["Forêt tropicale humide de l'Est.", "Rizière.", "Étang ou lac.", "Mangrove.", "Bord de mer."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Un écosystème comprend…", opts: ["seulement des plantes", "les êtres vivants et leur milieu", "seulement l'eau"], ok: 1, expl: "Il comprend le vivant et le milieu." },
          { q: "L'eau, le sol et la lumière sont…", opts: ["des êtres vivants", "des éléments non vivants", "des décomposeurs"], ok: 1, expl: "Ce sont les éléments du milieu." },
          { q: "Les plantes sont généralement…", opts: ["producteurs", "consommateurs", "décomposeurs"], ok: 0, expl: "Elles produisent leur propre matière par photosynthèse." },
          { q: "Une rizière est un exemple de…", opts: ["écosystème", "minéral", "roche"], ok: 0, expl: "C'est un milieu où vivent plantes et animaux." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "Les êtres vivants d'un écosystème sont indépendants du milieu.", rep: false, expl: "Ils dépendent du milieu." },
          { txt: "La lumière est un élément du milieu.", rep: true, expl: "Elle est nécessaire à la vie." },
          { txt: "Les champignons sont des êtres vivants.", rep: true, expl: "Ce sont des organismes vivants." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "L'ensemble des êtres vivants et de leur milieu s'appelle un", suite: "écosystème" },
          { debut: "Les éléments comme l'eau, l'air et le sol sont des éléments", suite: "non vivants" },
          { debut: "Les plantes sont des", suite: "producteurs" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les conditions physiques d'un milieu",
      theme: "Organisation des êtres vivants",
      ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
      valeurs: "Respect de toute vie, altruisme",
      objectif: "exposer les conditions physiques d'un milieu et leur influence sur la vie",
      supportMeta: "Schémas, tableau température/humidité/lumière/sol/altitude",
      revision: [
        ["Qu'est-ce qu'un écosystème ?", "Un ensemble d'êtres vivants et de leur milieu."],
        ["Cite trois éléments non vivants.", "Eau, lumière, température (ou sol, air, altitude)."],
      ],
      mise: ["Pourquoi les poissons ne vivent-ils pas dans un champ sec ?", "Parce que les conditions physiques du milieu ne leur conviennent pas."],
      observation: "le tableau des conditions physiques",
      observationSupport: "Tableau conditions du milieu",
      technAna: "Analyse de tableau",
      qa: [
        ["Quelles sont les conditions physiques d'un milieu ?", "La température, l'humidité, la luminosité, la nature du sol, l'altitude."],
        ["Comment la température influence-t-elle la vie ?", "Elle détermine quelles espèces peuvent vivre : espèces de zone chaude ou froide."],
        ["Comment l'eau influence-t-elle la vie ?", "L'eau est indispensable ; les milieux humides sont plus riches en espèces que les milieux secs."],
        ["Pourquoi certaines plantes vivent-elles en altitude ?", "Parce qu'elles sont adaptées au froid, au vent et au sol de haute montagne."],
      ],
      synthese: "Donc, chaque milieu possède des conditions physiques (température, humidité, lumière, sol, altitude) qui déterminent quelles espèces peuvent y vivre.",
      motsCles: ["conditions physiques", "température", "humidité", "luminosité", "altitude"],
      contenu: [
        { sousTitre: "1. Les conditions physiques", liste: ["Température : chaude, tempérée ou froide.", "Humidité : humide ou sec.", "Luminosité : forte ou faible.", "Sol : sableux, argileux, riche.", "Altitude : plaine, colline, montagne."] },
        { sousTitre: "2. Influence sur le vivant", texte: "Chaque espèce est adaptée à des conditions précises. Le riz aime les milieux humides, le cactus les milieux secs ; certaines plantes poussent en altitude, d'autres sur le littoral." },
        { sousTitre: "3. Exemple malgache", liste: ["Forêt de l'Est : humide, chaude, très riche.", "Hauts Plateaux : tempéré, altitude élevée.", "Sud : plus sec, saison sèche marquée."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "L'humidité est une condition…", opts: ["physique", "morale", "sociale"], ok: 0, expl: "Elle caractérise le milieu." },
          { q: "Le riz se développe surtout en milieu…", opts: ["humide", "désertique", "rocheux"], ok: 0, expl: "Le riz aime des milieux humides." },
          { q: "L'altitude influence…", opts: ["les espèces qui peuvent vivre", "la couleur du ciel", "la nourriture humaine seule"], ok: 0, expl: "Elle modifie les conditions du milieu." },
          { q: "Une plante de zone sèche est…", opts: ["adaptée à peu d'eau", "adaptée à beaucoup d'eau", "incapable de vivre sans neige"], ok: 0, expl: "Elle résiste à la sécheresse." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "La luminosité est une condition physique du milieu.", rep: true, expl: "Elle fait partie du milieu." },
          { txt: "Toutes les espèces vivent dans les mêmes conditions.", rep: false, expl: "Elles sont adaptées à des milieux différents." },
          { txt: "Le sol n'influence pas la vie des plantes.", rep: false, expl: "Le sol apporte eau et éléments minéraux." },
        ]},
      ],
      evalExos: [
        { type: "completion", consigne: "Complète.", pointsPar: 1, items: [
          { debut: "La température, l'humidité et la lumière sont des conditions", suite: "physiques" },
          { debut: "Un milieu très humide conviendra au", suite: "riz" },
          { debut: "Les plantes de haute montagne sont adaptées au", suite: "froid" },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les modes de vie et l'adaptation des êtres vivants",
      theme: "Organisation des êtres vivants",
      ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
      valeurs: "Respect de toute vie, altruisme",
      objectif: "analyser les modes de vie et l'adaptation des êtres vivants",
      supportMeta: "Photos d'animaux et plantes, schémas",
      revision: [
        ["Cite deux conditions physiques d'un milieu.", "La température et l'humidité."],
        ["Pourquoi un écosystème abrite-t-il plusieurs espèces ?", "Parce que chaque espèce est adaptée à une partie du milieu."],
      ],
      mise: ["Comment un poisson peut-il se déplacer dans l'eau ?", "Grâce à son corps et à ses nageoires adaptés à la nage."],
      observation: "les photos d'animaux et de plantes",
      observationSupport: "Photos et schémas",
      technAna: "Observation et comparaison",
      qa: [
        ["Comment se déplacent les animaux ?", "Les poissons nagent, les oiseaux volent, les mammifères marchent ou courent."],
        ["Comment respirent les êtres vivants ?", "Les poissons respirent par les branchies ; les humains et les mammifères par les poumons ; les plantes respirent et absorbent des gaz."],
        ["Comment les plantes s'adaptent-elles ?", "Par leurs racines, feuilles et tiges : certaines résistent à la sécheresse, d'autres vivent dans l'eau."],
        ["Quel est le lien entre le mode de vie et le milieu ?", "Le mode de vie est adapté au milieu : il permet à l'espèce de se nourrir, se déplacer, respirer et se reproduire."],
      ],
      synthese: "Donc, chaque espèce possède des modes de vie (déplacement, respiration, alimentation, reproduction) adaptés à son milieu.",
      motsCles: ["adaptation", "déplacement", "respiration", "mode de vie", "milieu"],
      contenu: [
        { sousTitre: "1. Modes de déplacement", liste: ["Nager : poisson, tortue marine.", "Voler : oiseau, chauve-souris.", "Marcher/courir : zébu, chien.", "Se déplacer en rampant : serpent."] },
        { sousTitre: "2. Modes de respiration", liste: ["Branchies : poissons.", "Poumons : mammifères, oiseaux.", "Trachées : insectes.", "Stomates et surface : plantes."] },
        { sousTitre: "3. Adaptation des plantes", liste: ["Racines profondes en zone sèche.", "Feuilles larges en forêt humide.", "Tiges aquatiques pour les plantes de l'eau.", "Réserves dans les racines ou tubercules."] },
        { sousTitre: "4. Exemple", texte: "Le caméléon se déplace lentement et vit dans les arbres ; ses couleurs lui permettent de se cacher. Le riz est adapté aux rizières humides." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Le poisson respire avec…", opts: ["ses branchies", "ses poumons", "sa peau"], ok: 0, expl: "Les poissons respirent par les branchies." },
          { q: "Une plante de zone sèche a souvent…", opts: ["des racines profondes", "des feuilles énormes", "toujours besoin d'eau abondante"], ok: 0, expl: "Elle doit aller chercher l'eau en profondeur." },
          { q: "Un oiseau se déplace en…", opts: ["volant", "nageant", "rampant"], ok: 0, expl: "Les oiseaux volent." },
          { q: "Le caméléon vit surtout…", opts: ["dans les arbres", "dans l'eau", "sous terre"], ok: 0, expl: "Il vit principalement dans les arbres." },
        ]},
        { type: "appariement", consigne: "Associe.", pointsPar: 1, items: [{ g: ["Poisson", "Oiseau", "Zébu", "Serpent"], d: ["Voler", "Nager", "Rampir", "Marcher"], pairs: [[0,1],[1,0],[2,3],[3,2]] }] },
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Comment un poisson respire-t-il ?", r: "Il respire par les branchies." },
          { q: "Donne un exemple d'adaptation d'une plante à la sécheresse.", r: "Des racines profondes qui vont chercher l'eau en profondeur." },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Les interactions entre les êtres vivants",
      theme: "Organisation des êtres vivants",
      ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
      valeurs: "Respect de toute vie, altruisme",
      objectif: "analyser les interactions entre les êtres vivants d'un écosystème",
      supportMeta: "Schémas d'interactions (symbiose, parasitisme, prédation, commensalisme, mutualisme)",
      revision: [
        ["Qu'est-ce qu'un mode de vie ?", "La façon dont une espèce se déplace, respire, se nourrit et se reproduit."],
        ["Pourquoi les espèces sont-elles adaptées à leur milieu ?", "Pour pouvoir vivre et remplir leurs besoins."],
      ],
      mise: ["Comment les plantes, les animaux et les microbes peuvent-ils dépendre les uns des autres ?", "Par des relations comme la prédation, le parasitisme, la symbiose, le mutualisme et le commensalisme."],
      observation: "les schémas d'interactions",
      observationSupport: "Schémas interactions",
      technAna: "Analyse de schémas",
      qa: [
        ["Qu'est-ce que la prédation ?", "Une relation où un animal chasse et mange un autre."],
        ["Qu'est-ce que le parasitisme ?", "Une relation où un organisme vit aux dépens d'un hôte, sans profit pour celui-ci."],
        ["Qu'est-ce que le mutualisme ?", "Une relation où les deux organismes profitent l'un de l'autre."],
        ["Qu'est-ce que le commensalisme et la symbiose ?", "Le commensalisme : un profite sans nuire à l'autre. La symbiose : association étroite/profit mutuel souvent."],
      ],
      synthese: "Donc, les êtres vivants d'un écosystème sont liés par des interactions : prédation, parasitisme, commensalisme, mutualisme, symbiose — qui maintiennent l'équilibre du milieu.",
      motsCles: ["prédation", "parasitisme", "commensalisme", "mutualisme", "symbiose"],
      contenu: [
        { sousTitre: "1. La prédation", texte: "Le prédateur chasse et mange sa proie. Exemple : le lion mange l'antilope, le serpent mange le rat." },
        { sousTitre: "2. Le parasitisme", texte: "Le parasite vit sur ou dans son hôte et le nuit. Exemple : le ver dans le tube digestif, la tique sur la peau." },
        { sousTitre: "3. Le commensalisme", texte: "Un organisme profite de l'autre sans l'aider ni lui nuire. Exemple : le petit poisson sous le requin." },
        { sousTitre: "4. Le mutualisme et la symbiose", texte: "Les deux organismes profitent de l'association. Exemple : les abeilles et les fleurs ; les lichens (champignon + algue)." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Le serpent qui mange un rat est un exemple de…", opts: ["prédation", "mutualisme", "commensalisme"], ok: 0, expl: "Le serpent est le prédateur du rat." },
          { q: "La relation où les deux espèces profitent est…", opts: ["le mutualisme", "le parasitisme", "la prédation"], ok: 0, expl: "Dans le mutualisme, les deux gagnent." },
          { q: "Le parasitisme nuit…", opts: ["à l'hôte", "au parasite", "au milieu"], ok: 0, expl: "Le parasite profite, l'hôte est lésé." },
          { q: "Un poisson qui suit un requin sans le gêner illustre…", opts: ["le commensalisme", "le parasitisme", "la symbiose"], ok: 0, expl: "Le poisson profite, le requin n'est pas gêné." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "La tique vivant sur la peau d'un chien est un parasite.", rep: true, expl: "Elle vit aux dépens du chien." },
          { txt: "Dans le commensalisme, les deux organismes profitent.", rep: false, expl: "Un seul profite, l'autre n'est pas gêné." },
          { txt: "Les abeilles et les fleurs forment une relation de mutualisme.", rep: true, expl: "Chacune profite de l'autre." },
        ]},
      ],
      evalExos: [
        { type: "appariement", consigne: "Associe.", pointsPar: 1, items: [{ g: ["Prédation", "Parasitisme", "Mutualisme"], d: ["Lion mange l'antilope", "Ver dans l'intestin", "Abeilles et fleurs"], pairs: [[0,0],[1,1],[2,2]] }] },
      ],
    },
    {
      type: "cours",
      titre: "La chaîne alimentaire",
      theme: "Organisation des êtres vivants",
      ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
      valeurs: "Respect de toute vie, altruisme",
      objectif: "illustrer une chaîne alimentaire et distinguer producteurs, consommateurs, décomposeurs",
      supportMeta: "Schéma de chaîne alimentaire, photos",
      revision: [
        ["Qu'est-ce qu'une interaction entre les êtres vivants ?", "Une relation comme la prédation, le parasitisme, le mutualisme."],
        ["Quel organisme est le prédateur dans « serpent mange rat » ?", "Le serpent."],
      ],
      mise: ["Comment l'herbe qu'on voit dans un champ peut-elle nourrir un zébu, puis un léopard ?", "Par une chaîne alimentaire : herbe → zébu → léopard."],
      observation: "le schéma d'une chaîne alimentaire",
      observationSupport: "Schéma chaîne alimentaire",
      technAna: "Observation et questionnement",
      qa: [
        ["Qu'est-ce qu'une chaîne alimentaire ?", "Une suite de relations où chaque être vivant est mangé par le suivant."],
        ["Qui sont les producteurs ?", "Les plantes vertes, qui fabriquent leur nourriture grâce à la lumière."],
        ["Qui sont les consommateurs ?", "Les animaux herbivores, carnivores et omnivores."],
        ["Qui sont les décomposeurs ?", "Les bactéries et champignons qui transforment les matières mortes en éléments du sol."],
      ],
      synthese: "Donc, une chaîne alimentaire montre comment la matière et l'énergie passent des producteurs (plantes) aux consommateurs (animaux) et sont recyclées par les décomposeurs.",
      motsCles: ["chaîne alimentaire", "producteurs", "consommateurs", "décomposeurs", "régime alimentaire"],
      contenu: [
        { sousTitre: "1. Les producteurs", texte: "Les plantes vertes sont les producteurs : elles fabriquent leur nourriture (matière organique) grâce à la lumière, à l'eau et au dioxyde de carbone." },
        { sousTitre: "2. Les consommateurs", liste: ["Consommateurs primaires (herbivores) : mangent les plantes.", "Consommateurs secondaires (carnivores) : mangent les herbivores.", "Consommateurs supérieurs : mangent les carnivores."] },
        { sousTitre: "3. Les décomposeurs", texte: "Les décomposeurs (bactéries, champignons) transforment les déchets et les organismes morts en éléments minéraux réutilisés par les plantes." },
        { sousTitre: "4. Exemple de chaîne alimentaire", texte: "Herbe → sauterelle → grenouille → serpent → épervier. Dans une rizière : riz → criquet → oiseau → serpent." },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "Les producteurs sont…", opts: ["les plantes vertes", "les lions", "les bactéries"], ok: 0, expl: "Les plantes fabriquent leur nourriture." },
          { q: "L'herbivore est un…", opts: ["consommateur primaire", "producteur", "décomposeur"], ok: 0, expl: "Il mange les plantes." },
          { q: "Les décomposeurs transforment…", opts: ["les déchets en éléments du sol", "l'eau en air", "le soleil en électricité"], ok: 0, expl: "Ils recyclent la matière." },
          { q: "Dans « riz → criquet → oiseau », l'oiseau est…", opts: ["le consommateur secondaire", "le producteur", "le décomposeur"], ok: 0, expl: "Il mange le criquet, consommateur primaire." },
        ]},
        { type: "appariement", consigne: "Associe.", pointsPar: 1, items: [{ g: ["Plante", "Herbivore", "Bactérie"], d: ["Producteur", "Décomposeur", "Consommateur primaire"], pairs: [[0,0],[2,1],[1,2]] }] },
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Qu'est-ce qu'une chaîne alimentaire ?", r: "C'est une suite d'organismes où chaque être est mangé par le suivant." },
          { q: "Donne un exemple de chaîne alimentaire de rizière.", r: "Riz → criquet → oiseau → serpent (ou une réponse équivalente)." },
        ]},
      ],
    },
    {
      type: "cours",
      titre: "Modification de l'environnement et menace d'extinction des espèces",
      theme: "Organisation des êtres vivants",
      ras: "Participer à la préservation de chaque espèce et son interaction avec d'autres espèces pour le maintien de l'équilibre d'un écosystème",
      valeurs: "Respect de toute vie, altruisme",
      objectif: "identifier les facteurs et conséquences des modifications d'un écosystème",
      supportMeta: "Photos de déforestation, animaux menacés, schémas",
      revision: [
        ["Quel est le rôle des décomposeurs ?", "Recycler les matières mortes en éléments du sol."],
        ["Cite une chaîne alimentaire.", "Riz → criquet → oiseau → serpent."],
      ],
      mise: ["Que devient la forêt quand on coupe trop d'arbres ?", "Les animaux perdent leur habitat, le sol se dégrade et certaines espèces disparaissent."],
      observation: "les photos de la déforestation et des espèces menacées",
      observationSupport: "Photos déforestation, espèces menacées",
      technAna: "Analyse de documents et débat",
      qa: [
        ["Quelles sont les causes de modification d'un écosystème ?", "La déforestation, la pollution, la surexploitation, l'incendie, l'extension des cultures."],
        ["Quelles sont les conséquences ?", "Perte d'habitat, raréfaction des ressources, déséquilibre, disparition d'espèces."],
        ["Qu'est-ce qu'une espèce menacée d'extinction ?", "Une espèce qui risque de disparaître du milieu."],
        ["Comment protéger l'équilibre des écosystèmes ?", "Protéger les forêts, limiter la pollution, éviter la surexploitation, créer des réserves, sensibiliser."],
      ],
      synthese: "Donc, la modification de l'environnement (déforestation, pollution, surexploitation) déséquilibre les écosystèmes et peut entraîner l'extinction d'espèces.",
      motsCles: ["déforestation", "pollution", "extinction", "espèce menacée", "équilibre écologique"],
      contenu: [
        { sousTitre: "1. Facteurs de modification", liste: ["Déforestation.", "Pollution (eau, air, sol).", "Surexploitation (chasse, pêche excessive).", "Incendies.", "Expansion des cultures et des villes."] },
        { sousTitre: "2. Conséquences", liste: ["Perte de l'habitat.", "Raréfaction de la nourriture.", "Déséquilibre de la chaîne alimentaire.", "Risque de surpopulation ou de disparition.", "Extinction d'espèces."] },
        { sousTitre: "3. Exemples à Madagascar", texte: "La déforestation menace les lémuriens et de nombreuses espèces endémiques. La pollution des cours d'eau affecte les poissons et les villages." },
        { sousTitre: "4. Comment agir", liste: ["Planter des arbres.", "Aider à créer des aires protégées.", "Réduire les déchets.", "Sensibiliser la communauté.", "Préserver l'eau et le sol."] },
      ],
      appExos: [
        { type: "qcm", consigne: "Encercle la bonne réponse.", pointsPar: 1, items: [
          { q: "La déforestation menace surtout…", opts: ["les habitats des animaux", "l'air", "le climat mondial uniquement"], ok: 0, expl: "Elle détruit les habitats." },
          { q: "Une espèce menacée d'extinction est une espèce qui…", opts: ["risque de disparaître", "va se multiplier", "ne vit plus nulle part"], ok: 0, expl: "Elle risque de disparaître." },
          { q: "Une action de protection est…", opts: ["planter des arbres", "couper plus d'arbres", "jeter des déchets dans la rivière"], ok: 0, expl: "Le reboisement protège le milieu." },
          { q: "La pollution de l'eau affecte…", opts: ["les êtres vivants et les usagers", "seulement les roches", "aucun être vivant"], ok: 0, expl: "Elle nuit à toute la chaîne." },
        ]},
        { type: "vf", consigne: "Vrai ou faux ?", pointsPar: 1, items: [
          { txt: "La surexploitation de la pêche peut déséquilibrer un écosystème.", rep: true, expl: "Elle réduit les populations." },
          { txt: "La déforestation augmente l'habitat des animaux.", rep: false, expl: "Elle réduit les habitats." },
          { txt: "Les aires protégées aident à préserver les espèces.", rep: true, expl: "Elles protègent les milieux." },
        ]},
      ],
      evalExos: [
        { type: "qr", consigne: "Réponds.", pointsPar: 2, items: [
          { q: "Cite deux conséquences de la modification d'un écosystème.", r: "La perte d'habitat et la diminution des ressources (ou le déséquilibre et la disparition d'espèces)." },
          { q: "Comment peut-on préserver l'équilibre d'un écosystème ?", r: "En plantant des arbres, en réduisant la pollution et en respectant les aires protégées." },
        ]},
      ],
    },
  ],
};
module.exports = U;
