// Sary faha-2 isaky ny seho (apetraka ao amin'ny LESONA, aorian'ny votoaty)
module.exports = {
  1:  { image: "images/img2_s01.png", legende: "Ny dingana enina amin'ny fanadihadiana am-bava" },
  2:  { image: "images/img2_s02.png", legende: "Ny famokarana ny loharano am-bava : olan-kevitra, fitsikerana, fandrafetana" },
  4:  { image: "images/img2_s04.png", legende: "Frizy : ny Andro Maoderina (1492-1789)" },
  5:  { image: "images/img2_s05.png", legende: "Frizy : ireo mpikaroka lehibe (1488-1522)" },
  6:  { image: "images/img2_s06.png", legende: "Ny varotra andevo : antony, fizotra, vokany" },
  7:  { image: "images/img2_s07.png", legende: "Ny Renaissance : zavakanto, siansa, toe-tsaina" },
  8:  { image: "images/img2_s08.png", legende: "Ny Réforme : antony, mpitarika, vokany" },
  9:  { image: "images/img2_s09.png", legende: "Frizy : Madagasikara tamin'ny Andro Maoderina" },
  11: { image: "images/img2_s11.png", legende: "Ny sokajy telo tamin'ny Ancien Régime" },
  12: { image: "images/img2_s12.png", legende: "Ireo mpahay siansa sy filozofan'ny Fahazavana" },
  13: { image: "images/img2_s13.png", legende: "Frizy : ny revolisiona roa (1776-1792)" },
  14: { image: "images/img2_s14.png", legende: "Fampitahana : ny revolisiona indostrialy roa" },
  15: { image: "images/img2_s15.png", legende: "Ny anton'ny fananganana ny empira mpanjanaka" },
  17: { image: "images/img2_s17.png", legende: "Sari-tany : ireo fanjakana malagasy (taonjato XVI-XVIII)" },
  18: { image: "images/img2_s18.png", legende: "Ny ambaratongan'ny fiaraha-monina malagasy fahiny" },
  20: { image: "images/img2_s20.png", legende: "Frizy : ireo mpanjaka nifandimby (1810-1896)" },
  21: { image: "images/img2_s21.png", legende: "Ny fanavaozana nataon-dRadama I" },
  22: { image: "images/img2_s22.png", legende: "Ny fandaminan'ny fitondrana hova (1864-1895)" },
  24: { image: "images/img2_s24.png", legende: "Ny anton'ny fanjanahana : anatiny sy ivelany" },
  25: { image: "images/img2_s25.png", legende: "Ny rafi-pitondrana mpanjanaka" },
  26: { image: "images/img2_s26.png", legende: "Frizy : ireo hetsika nasionalista (1895-1947)" },
  27: { image: "images/img2_s27.png", legende: "Frizy : ny dia mankany amin'ny fahaleovantena (1947-1960)" },
  29: { image: "images/img2_s29.png", legende: "Ny karazana vakoka roa : hita maso sy tsy hita maso" },
  30: { image: "images/img2_s30.png", legende: "Ny fiarovana sy ny fampitana ny vakoka" },
};
