// UNIT 7 — SCHOOL ENVIRONMENT (8 séances + révision + test) — Sessions 30 à 39 / 57
const B = require("./builders");
const { C, SZ, run, p, pr, kw, pAns, fp, fiche, sectionRow, stepRow,
        unitBanner, audioBox, img, pageBreak, lessonTitle, sub, iCan, cell } = B;
const { Table, TableRow, WidthType, VerticalAlign } = require("docx");

const COLOR = "2E74B5"; // bleu
const TOTAL = 57;
const AUDIO = {
  things: "https://drive.google.com/uc?export=download&id=1Ke_-Z2ijndvgIYnGdVhU3UNxem42MLLJ",
  colours: "https://drive.google.com/uc?export=download&id=1SfYtpKehemqRv37UbgrEOehq8bZFGHrD",
  need: "https://drive.google.com/uc?export=download&id=1jj4X8OACeOxSUxkNxS5oT1dQ7_FToj9v",
};
const META = (title, slo, session, materials) => ({
  theme: "UNIT 7 — SCHOOL ENVIRONMENT", title, slo,
  values: "self-confidence, respect", session, materials,
});
const THINGS = [
  ["a schoolbag", "e skoulbag"], ["a copy-book", "e kopibouk"], ["a book", "e bouk"],
  ["a pen", "e pène"], ["a pencil", "e pènsil"], ["coloured pencils", "keuleurd pènsilz"],
  ["a pencil case", "e pènsil kéis"], ["a sharpener", "e charpeneur"], ["a slate", "e sléit"],
  ["a sponge", "e speundj"], ["chalk", "tchôk"], ["a ruler", "e rouleur"],
  ["a rubber", "e reubeur"], ["glue", "glou"], ["scissors", "sizeurz"],
];
function thingsGrid() {
  const perRow = 3, rows = [];
  for (let i = 0; i < THINGS.length; i += perRow) {
    const chunk = THINGS.slice(i, i + perRow);
    rows.push(new TableRow({ children: chunk.map(([w, pn]) =>
      cell([p([run(w, { bold: true, color: C.BLUE, size: 28 })], { center: true, after: 10 }),
            p([run(`[${pn}]`, { italic: true, color: C.GRAY, size: 20 })], { center: true, after: 20 })],
        { w: Math.floor(10400 / perRow), vAlign: VerticalAlign.CENTER }),
    ) }));
  }
  return new Table({ width: { size: 10400, type: WidthType.DXA }, rows });
}
const COLOURS = [["red", "rèd", "FF0000"], ["blue", "blou", "0000CC"],
                 ["black", "blak", "000000"], ["green", "grine", "008000"]];

function opening() {
  return [
    unitBanner("UNIT 7 — SCHOOL ENVIRONMENT", COLOR, "unit7"),
    p("", { after: 100 }),
    p([run("My schoolbag, my pencil, my book!", { bold: true, color: COLOR, size: 40 })], { center: true, after: 120 }),
    img("u7_school_things.png", 340, 768 / 1376),
    p([run("In this unit, I will learn to:", { bold: true })], { after: 60 }),
    p("• say the school things in English;"),
    p("• answer: What is this? — This is a book;"),
    p("• say the colours: red, blue, black, green;"),
    p("• say what I need: I need one blue pen.", { after: 140 }),
    pr([run("Values: ", { bold: true }), run("self-confidence, respect.")], { after: 160 }),
    new Table({
      width: { size: 10400, type: WidthType.DXA },
      rows: [
        new TableRow({ children: [cell(
          [p([run("DO YOU REMEMBER? (Unit 6)", { bold: true, color: COLOR, size: SZ.BODY })], { center: true, after: 40 })],
          { shade: "E3EDF7" })] }),
        new TableRow({ children: [cell([
          p("1. Say the seven days of the week."),
          p("2. What is your favourite day?", { after: 40 }),
        ])] }),
      ],
    }),
    p("", { after: 100 }),
    audioBox([{ qr: "qr_u7_things.png", label: "School things — listen and repeat", url: AUDIO.things }], COLOR),
  ];
}

// S30 — School things (1)
function ficheS30() {
  const meta = META("School things (1)",
    "By the end of the lesson, learners will be able to say the words: schoolbag, copy-book, book, pen, pencil, slate, chalk.",
    "1 / 8", "real school things, Picture dictionary 1, pages 48–49");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. Say the seven days of the week."),
       fp("2. What is your favourite day?"),
       fp("3. Count from 1 to 10.")],
      [fp("Answer."),
       fp("E.A.: 1. Monday … Sunday."),
       fp("2. My favourite day is …"),
       fp("3. one … ten.")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look inside my schoolbag! (The teacher takes out a book, a pen…) What can you see?")],
      [fp("Look. Answer."), fp("E.A.: pupils name the objects in their own words; the teacher gives the English words.")],
      "Whole-class work", "Schoolbag with objects"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « School things (1) ». By the end of this lesson, you will be able to say: schoolbag, copy-book, book, pen, pencil, slate, chalk.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at each object. Listen: “Repeat after me: a schoolbag… a copy-book… a book… a pen… a pencil… a slate… chalk.”")],
      [fp("Look. Listen.")], "Modelling", "Real school things"),
    stepRow(["4. Analysis"],
      [fp("Repeat each word all together, then group by group, then one by one."),
       fp("Some words are like Malagasy words! Listen: boky → book; tsaoka → chalk; pensilihazo → pencil. Which English words do you recognise?"),
       fp("I show an object: say the word.")],
      [fp("Repeat. Answer."),
       fp("E.A.: book, chalk, pencil (close to the Malagasy words)."),
       fp("E.A.: the object is named correctly.")],
      "Repetition drill / “Language transfer”", "Real school things, Picture dictionary p. 48–49"),
    stepRow(["5. Synthesis"],
      [fp("So, the first school things are: a schoolbag, a copy-book, a book, a pen, a pencil, a slate, chalk. We say “a” before the object: a pen, a book.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("I show an object: the class says the word with “a”."),
       fp("Work in pairs: one shows an object of the bench, the friend says the word. Change roles."),
       fp("Put on the table what I say: “a pencil!” — “a book!” — “a slate!”")],
      [fp("Say. Show."),
       pAns("E.A.: a schoolbag, a copy-book, a book, a pen, a pencil, a slate, chalk — with “a”.",
        ["a schoolbag", "a copy-book", "a book", "a pen", "a pencil", "a slate", "chalk"], { size: SZ.FICHE })],
      "In pairs / Whole-class work", "Real school things"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. I show five objects: say the words."),
       fp("2. Show me a pencil! Show me a book!"),
       fp("3. Say all the words of today.")],
      [fp("Say. Show."),
       pAns("E.A.: the seven words are said correctly, with “a”.", ["seven words"], { size: SZ.FICHE })],
      "Individual work", "Real school things"),
  ];
  return fiche(30, TOTAL, meta, rows, "s30");
}

// S31 — School things (2)
function ficheS31() {
  const meta = META("School things (2)",
    "By the end of the lesson, learners will be able to say the words: pencil case, sharpener, ruler, rubber, sponge, glue, scissors, coloured pencils.",
    "2 / 8", "real school things, Picture dictionary 1, pages 48–49");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. I show objects (book, pen, slate): say the words."),
       fp("2. Show me a pencil!"),
       fp("3. Which English word is like “boky”?")],
      [fp("Answer. Show."),
       fp("E.A.: 1. a book, a pen, a slate."),
       fp("2. The pupil shows a pencil."),
       fp("3. Book.")],
      "Individual work", "School things"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look at my pencil case. Many things are inside! Do you know their names in English?")],
      [fp("Look. Answer."), fp("E.A.: Not yet! (Pupils name some objects in their own words.)")],
      "Whole-class work", "Pencil case"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « School things (2) ». By the end of this lesson, you will be able to say: pencil case, sharpener, ruler, rubber, sponge, glue, scissors, coloured pencils.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at each object. Listen: “Repeat after me: a pencil case… a sharpener… a ruler… a rubber… a sponge… glue… scissors… coloured pencils.”")],
      [fp("Look. Listen.")], "Modelling", "Real school things"),
    stepRow(["4. Analysis"],
      [fp("Repeat each word all together, then group by group, then one by one."),
       fp("I show an object: say the word."),
       fp("Which object cuts the paper?"),
       fp("Which object cleans the slate?")],
      [fp("Repeat. Answer."),
       fp("E.A.: the objects are named."),
       fp("E.A.: Scissors."),
       fp("E.A.: A sponge.")],
      "Repetition drill / Brainstorming", "Real school things, Picture dictionary p. 48–49"),
    stepRow(["5. Synthesis"],
      [fp("So, the other school things are: a pencil case, a sharpener, a ruler, a rubber, a sponge, glue, scissors, coloured pencils. Now we know fifteen school things!")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("I show an object: the class says the word."),
       fp("Work in pairs with the fifteen words: one shows, one says. Change roles."),
       fp("Game: I say a word, touch the object on your bench as fast as you can!")],
      [fp("Say. Play."),
       pAns("E.A.: a pencil case, a sharpener, a ruler, a rubber, a sponge, glue, scissors, coloured pencils.",
        ["a pencil case", "a sharpener", "a ruler", "a rubber", "a sponge", "glue", "scissors", "coloured pencils"], { size: SZ.FICHE })],
      "Game / In pairs", "Real school things"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. I show six objects: say the words."),
       fp("2. Show me a ruler! Show me scissors!"),
       fp("3. Say all the school things you know.")],
      [fp("Say. Show."),
       pAns("E.A.: the words of the two lessons are said correctly.", ["two lessons"], { size: SZ.FICHE })],
      "Individual work", "Real school things"),
  ];
  return fiche(31, TOTAL, meta, rows, "s31");
}

// S32 — What is this? This is a book.
function ficheS32() {
  const meta = META("What is this? — This is a book",
    "By the end of the lesson, learners will be able to answer the question “What is this?” with “A …” or “This is a …”.",
    "3 / 8", "real school things");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. I show objects: say the words."),
       fp("2. Which object cuts the paper?"),
       fp("3. Say five school things.")],
      [fp("Answer."),
       fp("E.A.: 1. The objects are named."),
       fp("2. Scissors."),
       fp("3. Five words are said.")],
      "Individual work", "School things"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("(The teacher hides a book behind the back, then shows it.) I have a question for you: “What is this?”")],
      [fp("Listen. Answer."), fp("E.A.: A book!")],
      "Whole-class work", "Book"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « What is this? ». By the end of this lesson, you will be able to answer with “A …” or “This is a …”.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Listen and look. I show a book: “What is this?” — “This is a book.” I show a pen: “What is this?” — “This is a pen.”")],
      [fp("Look. Listen.")], "Modelling", "School things"),
    stepRow(["4. Analysis"],
      [fp("What is my question?"),
       fp("What are the two ways to answer?"),
       fp("I show a slate: What is this?"),
       fp("I show a ruler: What is this?")],
      [fp("Answer."),
       fp("E.A.: What is this?"),
       fp("E.A.: “A book.” or “This is a book.”"),
       fp("E.A.: This is a slate."),
       fp("E.A.: This is a ruler.")],
      "Brainstorming / Modelling", "School things"),
    stepRow(["5. Synthesis"],
      [fp("So, the question is: “What is this?”. The answer is: “A …” or “This is a …”: This is a book. This is a pen.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Work in pairs: one shows an object and asks “What is this?”; the friend answers “This is a …”. Change roles."),
       fp("Miming game in two teams: a pupil mimes an object (writing with a pen, cutting with scissors…); the team guesses: “A pen!” “Scissors!”."),
       fp("One point for the right answer. The team with more points wins!")],
      [fp("Ask and answer. Play."),
       pAns("E.A.: “What is this?” — “This is a …” ; the mimed object is guessed in English.",
        ["What is this?", "This is a"], { size: SZ.FICHE })],
      "Game (miming) / In pairs", "School things"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. I show four objects: What is this?"),
       fp("2. Ask your friend with an object of your bench."),
       fp("3. Mime an object for the class.")],
      [fp("Answer. Play."),
       pAns("E.A.: This is a … (the four objects are named); the question is asked correctly.",
        ["This is a"], { size: SZ.FICHE })],
      "Individual work / In pairs", "School things"),
  ];
  return fiche(32, TOTAL, meta, rows, "s32");
}

// S33 — Kim's game (memory)
function ficheS33() {
  const meta = META("The memory game (Kim’s game)",
    "By the end of the lesson, learners will be able to use the school things vocabulary in a spontaneous scene.",
    "4 / 8", "six to eight school things, one table");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. I show an object: What is this?"),
       fp("2. Say eight school things."),
       fp("3. Mime an object; the class guesses.")],
      [fp("Answer. Play."),
       fp("E.A.: 1. This is a …"),
       fp("2. Eight words are said."),
       fp("3. The object is guessed.")],
      "Individual work", "School things"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look at my table: there are six objects on it. Can you remember all of them? Let’s see!")],
      [fp("Look. Answer."), fp("E.A.: Yes! / We can try!")],
      "Whole-class work", "Objects on the table"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to play « the memory game ». By the end of this lesson, you will be able to use the words of the school things without help.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at the objects on the table: a pen, a pencil, a rubber, a ruler, a book, chalk. Say them with me. Try to remember all of them!")],
      [fp("Look. Say. Remember.")], "Whole-class work", "Objects on the table"),
    stepRow(["4. Analysis"],
      [fp("Close your eyes! (The teacher takes one object away.) Open your eyes!"),
       fp("Look at the table. What is missing?"),
       fp("How do you know?")],
      [fp("Play. Answer."),
       fp("E.A.: The rubber! (the missing object, in English)"),
       fp("E.A.: We remember the objects.")],
      "Game", "Objects on the table"),
    stepRow(["5. Synthesis"],
      [fp("So, we can play the memory game: we look, we close the eyes, one object goes away, and we say the missing object in English.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["6. Practice"],
      [fp("Play again several times: change the objects, take away one object, sometimes two!"),
       fp("Then play in groups: one pupil is the teacher and takes an object away; the group says the missing object."),
       fp("The pupil who answers first becomes the new “teacher”.")],
      [fp("Play. Answer in English."),
       pAns("E.A.: the missing object is named correctly in English each time.",
        ["missing object"], { size: SZ.FICHE })],
      "Game (Kim’s game) / Group work", "Objects on the table"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. Look at five objects. I take one away: what is missing?"),
       fp("2. Say the five objects of the table."),
       fp("3. What is this? (I show the missing object.)")],
      [fp("Answer."),
       pAns("E.A.: the missing object and the five words are said correctly; This is a …",
        ["missing object", "This is a"], { size: SZ.FICHE })],
      "Individual work", "Objects on the table"),
  ];
  return fiche(33, TOTAL, meta, rows, "s33");
}

// S34 — Colours (1)
function ficheS34() {
  const meta = META("Colours (1): red, blue, black, green",
    "By the end of the lesson, learners will be able to say the four colours and follow the commands “Take / Show me / Put your red pencil”.",
    "5 / 8", "coloured pencils (red, blue, black, green), drawing copy-books");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. I show objects: What is this?"),
       fp("2. Play one round of the memory game."),
       fp("3. Say the school things of your pencil case.")],
      [fp("Answer. Play."),
       fp("E.A.: 1. This is a …"),
       fp("2. The missing object is named."),
       fp("3. The objects are named.")],
      "Individual work", "School things"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look at the coloured pencils. They are not the same! What is different?")],
      [fp("Look. Answer."), fp("E.A.: The colours. (Pupils answer in their own words; the teacher gives the English word: colours.)")],
      "Whole-class work", "Coloured pencils"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Colours ». By the end of this lesson, you will be able to say: red, blue, black, green.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Draw a schoolbag in your drawing copy-book. You will colour it!"),
       fp("Now listen and do: “Take your red pencil!” (I take my red pencil.) “Show me your red pencil!” “Put your red pencil on the table!”")],
      [fp("Draw. Listen. Do.")], "Drawing / Modelling with gestures", "Coloured pencils, copy-books"),
    stepRow(["4. Analysis"],
      [fp("Which pencil did we take first? Say the colour."),
       fp("Now the same with: blue! black! green! (Take… Show me… Put…)"),
       fp("I show a pencil: say its colour.")],
      [fp("Do. Answer."),
       fp("E.A.: Red."),
       fp("E.A.: pupils take, show and put each pencil."),
       fp("E.A.: red / blue / black / green.")],
      "Modelling with gestures / Repetition drill", "Coloured pencils"),
    stepRow(["5. Synthesis"],
      [fp("So, the four colours are: red, blue, black, green. To ask the colour: “What colour is …?”")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Colour your schoolbag drawing with the colour YOU like."),
       fp("Show your drawing and say the colour you chose."),
       fp("I show a pencil or chalk: say the colour."),
       fp("What colour is the schoolbag of your friend?")],
      [fp("Colour. Show. Say."),
       pAns("E.A.: “Red!” / “My schoolbag is blue.” — the colour matches the drawing.",
        ["Red!", "blue"], { size: SZ.FICHE })],
      "Drawing / Whole-class work", "Coloured pencils, copy-books"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. I show four pencils: say the colours."),
       fp("2. Take your green pencil! Show me your black pencil!"),
       fp("3. What colour is your pen?")],
      [fp("Say. Do."),
       pAns("E.A.: red, blue, black, green ; the commands are done ; the colour of the pen is said.",
        ["red, blue, black, green"], { size: SZ.FICHE })],
      "Individual work", "Coloured pencils"),
  ];
  return fiche(34, TOTAL, meta, rows, "s34");
}

// S35 — Colours (2): find something red
function ficheS35() {
  const meta = META("Colours (2): find something red!",
    "By the end of the lesson, learners will be able to say the colour of the things around them.",
    "6 / 8", "coloured pencils, chalk, things of the classroom");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. Say the four colours."),
       fp("2. I show a pencil: say its colour."),
       fp("3. Take your blue pencil!")],
      [fp("Answer. Do."),
       fp("E.A.: 1. red, blue, black, green."),
       fp("2. The colour is said."),
       fp("3. The command is done.")],
      "Individual work", "Coloured pencils"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look around the classroom. Can you see something red?")],
      [fp("Look. Answer."), fp("E.A.: pupils point to red things.")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to play with the colours in the classroom. By the end of this lesson, you will be able to say the colour of the things around you.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Listen and look. I point to a red dress: “red”. I point to a green wall: “green”. I point to a black slate: “black”.")],
      [fp("Look. Listen.")], "Modelling", "Things of the classroom"),
    stepRow(["4. Analysis"],
      [fp("Game: “Find something red and say: red!”"),
       fp("Now: find something blue! something black! something green!"),
       fp("What colour is the board?"),
       fp("What colour is your copy-book?")],
      [fp("Find. Say."),
       fp("E.A.: pupils point to a thing of the right colour and say the colour."),
       fp("E.A.: Black."),
       fp("E.A.: the colour is said.")],
      "Game / Whole-class work", "Things of the classroom"),
    stepRow(["5. Synthesis"],
      [fp("So, everything has a colour! We can say the colour of the things around us: the board is black, the leaf is green… The question is: “What colour is …?”")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Go to the schoolyard (or stay in class). Find and say: something red, something green, something blue, something black."),
       fp("Work in pairs: one asks “What colour is the …?” (an object of the bench); the friend answers. Change roles.")],
      [fp("Find. Ask and answer."),
       pAns("E.A.: “What colour is the pen?” — “Blue!” — the colour matches the object.",
        ["What colour is", "Blue!"], { size: SZ.FICHE })],
      "Game / In pairs", "Things of the classroom or the yard"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. Find something green!"),
       fp("2. What colour is the chalk?"),
       fp("3. What colour is your schoolbag?"),
       fp("4. Ask your friend a colour question.")],
      [fp("Find. Answer."),
       pAns("E.A.: the colours are said correctly; the question “What colour is …?” is asked.",
        ["What colour is"], { size: SZ.FICHE })],
      "Individual work / In pairs", "----"),
  ];
  return fiche(35, TOTAL, meta, rows, "s35");
}

// S36 — What do you need? I need…
function ficheS36() {
  const meta = META("What do you need? — I need …",
    "By the end of the lesson, learners will be able to say the school things they need with “I need …”.",
    "7 / 8", "school things");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. Say the four colours."),
       fp("2. What colour is the board?"),
       fp("3. I show objects: say the words."),
       fp("4. Count from 1 to 10.")],
      [fp("Answer."),
       fp("E.A.: 1. red, blue, black, green."),
       fp("2. Black."),
       fp("3. The objects are named."),
       fp("4. one … ten.")],
      "Individual work", "School things"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("I want to write, but I have no pen! Listen: “I need one pen.” (A pupil gives a pen.) Thank you!")],
      [fp("Listen. Give."), fp("E.A.: a pupil gives a pen.")],
      "Whole-class work", "Pen"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « What do you need? ». By the end of this lesson, you will be able to say the things you need with “I need …”.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Listen. “I need one pen.” “I need two pencils.” “I need one blue pen.” Then I ask a pupil: “What do you need?”")],
      [fp("Listen. Answer.")], "Modelling", "School things"),
    stepRow(["4. Analysis"],
      [fp("What do I say when I want something?"),
       fp("What is my question?"),
       fp("Answer me: What do you need? (to 3 or 4 pupils)"),
       fp("Can we add a number and a colour? Listen: “I need one blue pen.”")],
      [fp("Answer."),
       fp("E.A.: I need …"),
       fp("E.A.: What do you need?"),
       fp("E.A.: I need one pencil. / I need a rubber…"),
       fp("E.A.: Yes! number + colour + object.")],
      "Brainstorming / Modelling", "School things"),
    stepRow(["5. Synthesis"],
      [fp("So, the question is: “What do you need?”. The answer is: “I need …” with the number, the colour and the object: I need one blue pen. I need two red pencils.")],
      [fp("Listen. Repeat “I need …”.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Work in pairs: one asks “What do you need?”; the friend answers “I need …” and the first one gives the object. Change roles."),
       fp("Say it with a number and a colour: “I need one black pencil.”"),
       fp("Then choose the right answer:"),
       fp("1. I want a ruler. I say: I need a ruler. / This is a ruler."),
       fp("2. The question is: What is this? / What do you need?"),
       fp("3. “I need two pens” = pens: 2 / 10")],
      [fp("Ask and answer. Do the exercise."),
       pAns("E.A.: 1. I need a ruler.  2. What do you need?  3. 2",
        ["I need a ruler.", "What do you need?", "2"], { size: SZ.FICHE })],
      "In pairs", "School things"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. You want a rubber. What do you say?"),
       fp("2. What do you need? (with number and colour)"),
       fp("3. Ask your friend the question.")],
      [fp("Answer."),
       pAns("E.A.: 1. I need a rubber.  2. I need one blue pen…  3. What do you need?",
        ["I need a rubber.", "I need one blue pen", "What do you need?"], { size: SZ.FICHE })],
      "Individual work / In pairs", "----"),
  ];
  return fiche(36, TOTAL, meta, rows, "s36");
}

// S37 — The shop (role play)
function ficheS37() {
  const meta = META("At the shop (role play)",
    "By the end of the lesson, learners will be able to buy school things in a role play, using “What do you need?” and “I need …”.",
    "8 / 8", "one big table (the shop), school things, picture lists with numbers");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. You want a pencil. What do you say?"),
       fp("2. What is the question of the seller?"),
       fp("3. Say the four colours."),
       fp("4. Count from 1 to 5.")],
      [fp("Answer."),
       fp("E.A.: 1. I need a pencil."),
       fp("2. What do you need?"),
       fp("3. red, blue, black, green."),
       fp("4. one … five.")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look at this table: it is a shop! Pens, pencils, rulers… Today, we buy school things in English!")],
      [fp("Look. Listen.")], "Whole-class work", "The shop table"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to play « At the shop ». By the end of this lesson, you will be able to buy school things in English with “I need …”.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Listen and look. I am the seller, a pupil is the buyer. Seller: “What do you need?”. Buyer (with the picture list): “I need one blue pen.”. The seller gives the pen. Buyer: “Thank you!” — Seller: “You’re welcome!”")],
      [fp("Look. Listen.")], "Modelling / Role play", "The shop table, picture list"),
    stepRow(["4. Analysis"],
      [fp("What does the seller ask?"),
       fp("What does the buyer say?"),
       fp("What do we say at the end?"),
       fp("What is on the picture list?")],
      [fp("Answer."),
       fp("E.A.: What do you need?"),
       fp("E.A.: I need … (number + colour + object)."),
       fp("E.A.: Thank you! — You’re welcome!"),
       fp("E.A.: pictures of school things with the numbers to buy.")],
      "Brainstorming", "Picture list"),
    stepRow(["5. Synthesis"],
      [fp("So, at the shop: the seller asks “What do you need?”; the buyer says “I need …” and reads the picture list; we finish with “Thank you!” — “You’re welcome!”.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Role play in pairs at the shop table: one seller, one buyer with a picture list."),
       fp("The buyer asks all the things of the list: “I need two red pencils.”…"),
       fp("The seller listens and gives the right things."),
       fp("Change roles. Change the lists. Everybody plays!")],
      [fp("Play the roles."),
       pAns("E.A.: “What do you need?” — “I need one blue pen.” — the given objects match the list; “Thank you!” — “You’re welcome!”.",
        ["What do you need?", "I need one blue pen.", "Thank you!"], { size: SZ.FICHE })],
      "Role play / In pairs", "The shop table, picture lists"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("1. Play the buyer with this list: 1 pen, 2 pencils."),
       fp("2. Play the seller: ask the question and give the things."),
       fp("3. Finish the scene with the polite words.")],
      [fp("Play."),
       pAns("E.A.: the scene is played with the question, “I need …”, the right objects and “Thank you!” — “You’re welcome!”.",
        ["I need", "Thank you!", "You’re welcome!"], { size: SZ.FICHE })],
      "Individual work / In pairs", "The shop table"),
  ];
  return fiche(37, TOTAL, meta, rows, "s37");
}

function lesson() {
  return [
    p([run("LESSON — UNIT 7", { bold: true, size: 30 })], { center: true, after: 120 }),
    lessonTitle("SCHOOL ENVIRONMENT"),
    sub("1. My school things"),
    img("u7_school_things.png", 320, 768 / 1376),
    thingsGrid(),
    p("", { after: 80 }),
    pr([run("We say "), ...kw("a", "e"), run(" before the object: "),
        run("a pen, a book, a ruler.", { bold: true })], { after: 120 }),
    sub("2. What is this?"),
    pr([run("The question: "), ...kw("What is this?", "ouot iz zis")]),
    pr([run("The answer: "), ...kw("This is a book.", "zis iz e bouk"), run("  or simply:  "), ...kw("A book.", "e bouk")], { after: 120 }),
    sub("3. The colours"),
    new Table({ width: { size: 10400, type: WidthType.DXA }, rows: [
      new TableRow({ children: COLOURS.map(([w, pn, hex]) =>
        cell([p([run("■ ", { color: hex, size: 44 }), run(w, { bold: true, color: hex, size: 32 })], { center: true, after: 10 }),
              p([run(`[${pn}]`, { italic: true, color: C.GRAY, size: 20 })], { center: true, after: 20 })],
          { w: 2600, vAlign: VerticalAlign.CENTER })) }),
    ]}),
    p("", { after: 80 }),
    img("u7_colours.png", 300, 768 / 1408),
    pr([run("The question: "), ...kw("What colour is the pen?", "ouot keuleur iz ze pène"),
        run("  →  "), ...kw("It is blue.", "it iz blou")]),
    pr([run("The game: "), run("Find something red and say: red!", { bold: true, color: C.BLUE })], { after: 120 }),
    sub("4. I need …"),
    pr([run("The question: "), ...kw("What do you need?", "ouot dou iou nide")]),
    pr([run("The answer: "), ...kw("I need one blue pen.", "aï nide ouane blou pène"),
        run("  (number + colour + object)")]),
    p("At the shop, we finish with: Thank you! — You’re welcome!", { after: 140 }),
    audioBox([
      { qr: "qr_u7_things.png", label: "School things — listen and repeat", url: AUDIO.things },
      { qr: "qr_u7_colours.png", label: "Colours — listen and repeat", url: AUDIO.colours },
      { qr: "qr_u7_need.png", label: "At the shop — listen and repeat", url: AUDIO.need },
    ], COLOR),
  ];
}

function exercises() {
  return [
    p([run("EXERCISES", { bold: true, size: 30 })], { center: true, after: 140 }),
    pr([run("Exercise 1 (5 points). ", { bold: true }), run("The teacher shows five objects; answer: What is this?")]),
    p("", { after: 120 }),
    pr([run("Exercise 2 (5 points). ", { bold: true }), run("Say the right word:")]),
    p("1. It cuts the paper. → ……"),
    p("2. It cleans the slate. → ……"),
    p("3. We write on it with chalk. → ……"),
    p("4. It makes the pencil sharp. → ……"),
    p("5. The pencils live inside it. → ……", { after: 120 }),
    pr([run("Exercise 3 (4 points). ", { bold: true }), run("Say the colour:")]),
    p("1. What colour is the chalkboard?"),
    p("2. What colour is the leaf of the tree?"),
    p("3. What colour is your pen?"),
    p("4. Find something red in the class!", { after: 120 }),
    pr([run("Exercise 4 (6 points). ", { bold: true }), run("At the shop! Say “I need …” with:")]),
    p("1. (1 pen, blue)   2. (2 pencils, red)   3. (1 ruler)"),
    p("Then play the seller: ask the question.", { after: 140 }),
    p([run("Total: 20 points", { bold: true })], { after: 160 }),
    p([run("ANSWER KEY", { bold: true, size: SZ.SUB, color: C.PINK })], { center: true, after: 120 }),
    pAns("Exercise 1: This is a … (the five objects are named, 1 point each).", ["This is a"]),
    pAns("Exercise 2: 1. scissors  2. a sponge  3. a slate  4. a sharpener  5. a pencil case",
      ["scissors", "a sponge", "a slate", "a sharpener", "a pencil case"]),
    pAns("Exercise 3: 1. It is black.  2. It is green.  3. the colour of the pen  4. a red thing is shown",
      ["It is black.", "It is green."]),
    pAns("Exercise 4: 1. I need one blue pen.  2. I need two red pencils.  3. I need a ruler. — What do you need? (the question, 3 points)",
      ["I need one blue pen.", "I need two red pencils.", "I need a ruler.", "What do you need?"]),
  ];
}

function revision() {
  const t = (a, b) => new TableRow({ children: [
    cell([fp([run(a, { bold: true, size: SZ.FICHE })])], { w: 4200 }),
    cell([fp(b)], { w: 6200 }),
  ]});
  return [
    B.bookmarkTitle("s38", "SESSION 38 / 57", { bold: true, size: 28, after: 60 }),
    p([run("REVISION — UNIT 7: SCHOOL ENVIRONMENT", { bold: true, size: 26 })], { center: true, after: 140 }),
    p("Remember the words of Unit 7:", { after: 100 }),
    new Table({ width: { size: 10400, type: WidthType.DXA }, rows: [
      new TableRow({ children: [
        cell([fp([run("We say…", { bold: true, size: SZ.FICHE })])], { w: 4200, shade: C.HDR1 }),
        cell([fp([run("When…", { bold: true, size: SZ.FICHE })])], { w: 6200, shade: C.HDR1 }),
      ]}),
      t("a schoolbag, a book, a pen, a pencil…", "the fifteen school things"),
      t("What is this? — This is a book.", "we ask about an object"),
      t("red, blue, black, green", "the four colours"),
      t("What colour is …? — It is blue.", "we ask the colour"),
      t("What do you need? — I need …", "we buy or ask for things"),
      t("Thank you! — You’re welcome!", "the polite words of the shop"),
    ]}),
    p("", { after: 120 }),
    p([run("Now answer:", { bold: true })], { after: 80 }),
    p("1. Say ten school things."),
    pAns("E.A.: ten words are said with “a” (a pen, a book, a ruler…).", ["ten words"]),
    p("2. I show an object: What is this?"),
    pAns("E.A.: This is a …", ["This is a"]),
    p("3. Say the four colours."),
    pAns("E.A.: red, blue, black, green.", ["red, blue, black, green."]),
    p("4. What colour is the board?"),
    pAns("E.A.: It is black.", ["It is black."]),
    p("5. You want two green pencils. What do you say?"),
    pAns("E.A.: I need two green pencils.", ["I need two green pencils."]),
    p("6. Play the shop with your friend."),
    pAns("E.A.: the scene is played with the question and the polite words.", ["polite words"]),
  ];
}

function testPaper() {
  return [
    B.bookmarkTitle("s39", "SESSION 39 / 57", { bold: true, size: 28, after: 60 }),
    p([run("T4 TEST PAPER — UNIT 7: SCHOOL ENVIRONMENT", { bold: true, size: 26 })], { center: true, after: 100 }),
    pr([run("Duration: ………        ", { bold: true }), run("Total: 20 points", { bold: true })], { center: true, after: 160 }),
    pr([run("Exercise 1 (6 points). ", { bold: true }), run("The teacher shows six objects; answer: What is this?")]),
    p("", { after: 120 }),
    pr([run("Exercise 2 (4 points). ", { bold: true }), run("Say the right word:")]),
    p("1. It cuts the paper. → ……"),
    p("2. We write on the board with it. → ……"),
    p("3. It makes the pencil sharp. → ……"),
    p("4. It cleans the slate. → ……", { after: 120 }),
    pr([run("Exercise 3 (4 points). ", { bold: true }), run("The teacher shows four coloured pencils; say the colours.")]),
    p("", { after: 120 }),
    pr([run("Exercise 4 (6 points). ", { bold: true }), run("At the shop! Play the buyer with this list: 1 blue pen, 2 pencils, 1 rubber. Finish with the polite words.")]),
    p("", { after: 140 }),
    p([run("ANSWER KEY", { bold: true, size: SZ.SUB, color: C.PINK })], { center: true, after: 120 }),
    pAns("Exercise 1: This is a … (1 point per object).", ["This is a"]),
    pAns("Exercise 2: 1. scissors  2. chalk  3. a sharpener  4. a sponge (1 point each)",
      ["scissors", "chalk", "a sharpener", "a sponge"]),
    pAns("Exercise 3: red, blue, black, green (1 point each).", ["red, blue, black, green"]),
    pAns("Exercise 4: I need one blue pen. I need two pencils. I need a rubber. (1,5 point each) + Thank you! — You’re welcome! (1,5 point)",
      ["I need one blue pen.", "I need two pencils.", "I need a rubber.", "Thank you!"]),
  ];
}

module.exports = function unit7() {
  return [
    ...opening(), pageBreak(),
    ...ficheS30(), pageBreak(),
    ...ficheS31(), pageBreak(),
    ...ficheS32(), pageBreak(),
    ...ficheS33(), pageBreak(),
    ...ficheS34(), pageBreak(),
    ...ficheS35(), pageBreak(),
    ...ficheS36(), pageBreak(),
    ...ficheS37(), pageBreak(),
    ...lesson(), pageBreak(),
    ...exercises(), pageBreak(),
    ...revision(), pageBreak(),
    ...testPaper(), pageBreak(),
    ...iCan("UNIT 7", COLOR, [
      "I can say fifteen school things.",
      "I can answer: What is this? — This is a book.",
      "I can play the memory game in English.",
      "I can say the colours: red, blue, black, green.",
      "I can find something red and say: red!",
      "I can say: I need one blue pen.",
      "I can buy school things at the shop.",
    ], "Well done! See you in Unit 8: MEALS!"),
  ];
};
module.exports.COLOR = COLOR;
