// UNIT 1 — SOCIALISING (6 séances + révision + test) — Sessions 1 à 8 / 57
const B = require("./builders");
const { C, SZ, run, p, pr, kw, pAns, fp, fiche, sectionRow, stepRow,
        unitBanner, audioBox, img, pageBreak, lessonTitle, sub, iCan, cell } = B;
const { Table, TableRow, WidthType } = require("docx");

const COLOR = "E36C0A"; // orange — couleur de l'Unit 1
const TOTAL = 57;
const AUDIO = {
  greetings: "https://drive.google.com/uc?export=download&id=1Cj2Eo5iy6RFNWcsOS0vjvaDfvI2dHbTU",
  goodbye: "https://drive.google.com/uc?export=download&id=1qhkZYU77a17c5VzOww2vzeRAp2cd6Seb",
  introducing: "https://drive.google.com/uc?export=download&id=1hxmqC72FkUDo5YmKeTHJwnhjWgalrSKr",
  age: "https://drive.google.com/uc?export=download&id=1XyySqGahy3hQOoKHNAFlfkulmMm1v0DB",
  thanking: "https://drive.google.com/uc?export=download&id=1AjrG6fPVkbUTJYRpK5QLU4uYij6tCErH",
};
const META = (title, slo, session, materials) => ({
  theme: "UNIT 1 — SOCIALISING", title, slo,
  values: "respect, self-confidence", session, materials,
});

// ---------- page d'ouverture ----------
function opening() {
  return [
    unitBanner("UNIT 1 — SOCIALISING", COLOR, "unit1"),
    p("", { after: 100 }),
    p([run("Hello!   Hi!   Good morning!", { bold: true, color: COLOR, size: 44 })], { center: true, after: 120 }),
    img("koto_soa.png", 340, 768 / 1416),
    p([run("In this unit, I will learn to:", { bold: true })], { after: 60 }),
    p("• greet my friends and say goodbye;"),
    p("• say my name and my age;"),
    p("• thank my friends and say sorry.", { after: 140 }),
    pr([run("Values: ", { bold: true }), run("respect, self-confidence.")], { after: 160 }),
    new Table({
      width: { size: 10400, type: WidthType.DXA },
      rows: [
        new TableRow({ children: [cell(
          [p([run("MY FIRST ENGLISH WORDS!", { bold: true, color: COLOR, size: SZ.BODY })], { center: true, after: 40 })],
          { shade: "FCEEDF" })] }),
        new TableRow({ children: [cell([
          p("English is spoken all over the world."),
          p("This year, you start English. Welcome!", { after: 40 }),
        ])] }),
      ],
    }),
    p("", { after: 100 }),
    audioBox([{ qr: "qr_u1_greetings.png", label: "Greetings — listen and repeat", url: AUDIO.greetings }], COLOR),
  ];
}

// ---------- FICHES ----------
function ficheS1() {
  const meta = META("Greetings",
    "By the end of the lesson, learners will be able to greet a friend in English and answer the question “How are you?”.",
    "1 / 6", "picture of two children greeting, blackboard");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("This is the first English lesson."),
       fp("Greet the class. Then ask:"),
       fp("1. Wave your hand like me."),
       fp("2. Do you know one English word? Say it.")],
      [fp("Wave. Answer."),
       fp("E.A.: pupils wave and say words they know (hello, OK, goal…).")],
      "Whole-class work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Koto waves his hand and says: “Hello!”. What does Koto say?")],
      [fp("Listen. Answer."), fp("E.A.: Hello!")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Greetings ». By the end of this lesson, you will be able to greet a friend in English and answer the question “How are you?”.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at this picture of two children.")],
      [fp("Look.")], "Whole-class work", "Picture of two children greeting"),
    stepRow(["4. Analysis"],
      [fp("What do the children do with their hands?"),
       fp("What does the boy say?"),
       fp("What does the girl say?"),
       fp("When do we say “Good morning”?")],
      [fp("Answer."),
       fp("E.A.: They wave."),
       fp("E.A.: Hello! I’m Koto."),
       fp("E.A.: Hi! I’m Soa."),
       fp("E.A.: In the morning.")],
      "Brainstorming / Whole-class work", "Picture of two children greeting"),
    stepRow(["5. Synthesis"],
      [fp("So, to greet a friend, we say: “Hello!” or “Hi!”. In the morning, we say: “Good morning!”. To ask about a friend, we say: “How are you?”. The answer is: “I’m fine, thank you.”")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Stand in two lines, face a friend."),
       fp("Greet the friend in front of you: “Hello!” or “Hi!”."),
       fp("Ask: “How are you?”. The friend answers: “I’m fine, thank you.”."),
       fp("Move one step to the left. Start again with a new friend."),
       fp("Then choose the right answer:"),
       fp("1. In the morning we say: Bye! / Good morning!"),
       fp("2. “How are you?” → I’m fine, thank you. / Hello!"),
       fp("3. A friend says “Hi!”. You say: Hi! / Sorry!"),
       fp("4. To greet, we say: Hello! / Goodbye!")],
      [fp("Speak with a friend. Do the exercise."),
       pAns("E.A.: 1. Good morning!  2. I’m fine, thank you.  3. Hi!  4. Hello!",
        ["Good morning!", "I’m fine, thank you.", "Hi!", "Hello!"], { size: SZ.FICHE })],
      "“Speed-chat” / In pairs", "----"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("Answer your teacher:"),
       fp("1. Hello!"),
       fp("2. Good morning!"),
       fp("3. How are you?"),
       fp("4. Greet your friend.")],
      [fp("Answer."),
       pAns("E.A.: 1. Hello! / Hi!  2. Good morning!  3. I’m fine, thank you.  4. Hello! / Hi! / Good morning!",
        ["Hello! / Hi!", "Good morning!", "I’m fine, thank you."], { size: SZ.FICHE })],
      "Individual work", "----"),
  ];
  return fiche(1, TOTAL, meta, rows, "s1");
}

function ficheS2() {
  const meta = META("Saying goodbye",
    "By the end of the lesson, learners will be able to say goodbye in English.",
    "2 / 6", "blackboard");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. Greet your friend."),
       fp("2. In the morning, what do we say?"),
       fp("3. How are you?"),
       fp("4. A friend says “Hello!”. What do you say?")],
      [fp("Answer."),
       fp("E.A.: 1. Hello! / Hi!"),
       fp("2. Good morning!"),
       fp("3. I’m fine, thank you."),
       fp("4. Hello! / Hi!")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("The lesson is finished. Soa goes home. She waves and says a word. What does she say?")],
      [fp("Listen. Answer."), fp("E.A.: Goodbye! / Bye!")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Saying goodbye ». By the end of this lesson, you will be able to say goodbye in English.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at me. I walk to the door. I wave my hand and I say: “Goodbye!”.")],
      [fp("Look.")], "Whole-class work", "Classroom door"),
    stepRow(["4. Analysis"],
      [fp("What do I do with my hand?"),
       fp("What do I say?"),
       fp("When do we say “Goodbye”?"),
       fp("Do you know a short word for “Goodbye”?")],
      [fp("Answer."),
       fp("E.A.: You wave."),
       fp("E.A.: Goodbye!"),
       fp("E.A.: When we leave. / When we go home."),
       fp("E.A.: Bye! / Bye-bye!")],
      "Brainstorming / Whole-class work", "Classroom door"),
    stepRow(["5. Synthesis"],
      [fp("So, when we leave, we say: “Goodbye!”. We can also say: “Bye!” or “Bye-bye!”.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Stand in two lines, face a friend."),
       fp("Say the full chat: “Hello!” – “Hi!” – “How are you?” – “I’m fine, thank you.” – “Goodbye!” – “Bye-bye!”."),
       fp("Move one step to the left. Start again and change the words."),
       fp("Then choose the right answer:"),
       fp("1. We leave. We say: Hello! / Goodbye!"),
       fp("2. A friend says “Goodbye!”. You say: Bye! / Good morning!"),
       fp("3. The short word for Goodbye is: Bye! / Hi!"),
       fp("4. “Bye-bye!” means: goodbye / hello")],
      [fp("Speak with a friend. Do the exercise."),
       pAns("E.A.: 1. Goodbye!  2. Bye!  3. Bye!  4. goodbye",
        ["Goodbye!", "Bye!", "goodbye"], { size: SZ.FICHE })],
      "“Speed-chat” / In pairs", "----"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("Answer your teacher:"),
       fp("1. Goodbye!"),
       fp("2. You go home. What do you say?"),
       fp("3. Say goodbye in two ways."),
       fp("4. Say the full chat with me: hello → how are you → goodbye.")],
      [fp("Answer."),
       pAns("E.A.: 1. Goodbye! / Bye!  2. Goodbye! / Bye-bye!  3. Bye! and Bye-bye!  4. Hello! – How are you? – I’m fine, thank you. – Goodbye!",
        ["Goodbye! / Bye!", "Bye! and Bye-bye!"], { size: SZ.FICHE })],
      "Individual work", "----"),
  ];
  return fiche(2, TOTAL, meta, rows, "s2");
}

function ficheS3() {
  const meta = META("Introducing yourself: What’s your name?",
    "By the end of the lesson, learners will be able to say their name and answer “Nice to meet you”.",
    "3 / 6", "ball, “What’s your name?” song");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. Greet your friend."),
       fp("2. How are you?"),
       fp("3. You go home. What do you say?"),
       fp("4. Say goodbye in two ways.")],
      [fp("Answer."),
       fp("E.A.: 1. Hello! / Hi! / Good morning!"),
       fp("2. I’m fine, thank you."),
       fp("3. Goodbye! / Bye!"),
       fp("4. Bye! and Bye-bye!")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("A new pupil comes to our school. You want to know him. What do you ask him?")],
      [fp("Listen. Answer."), fp("E.A.: His name. / Who are you?")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Introducing yourself: What’s your name? ». By the end of this lesson, you will be able to say your name and answer “Nice to meet you”.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Listen to me. My name is …… (the teacher says his/her name). What’s your name, …… ? (the teacher asks 3 or 4 pupils).")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["4. Analysis"],
      [fp("What is my question?"),
       fp("What is the answer?"),
       fp("After the name, I say: “Nice to meet you”. What is the answer?"),
       fp("Now ask me: “What’s your name?”.")],
      [fp("Answer."),
       fp("E.A.: What’s your name?"),
       fp("E.A.: My name is ……"),
       fp("E.A.: Nice to meet you too."),
       fp("E.A.: pupils ask the question, the teacher answers.")],
      "Brainstorming / Whole-class work", "----"),
    stepRow(["5. Synthesis"],
      [fp("So, to ask a name, we say: “What’s your name?”. The answer is: “My name is ……”. Then we say: “Nice to meet you.” and the friend answers: “Nice to meet you too.”.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Sing the “What’s your name?” song with me."),
       fp("Ball game: I throw the ball to a pupil and the class sings: “Hello, hello, hello, what’s your name?”."),
       fp("The pupil with the ball sings: “My name is ……, my name is ……”."),
       fp("The class answers: “Nice to meet you, ……!”."),
       fp("The pupil throws the ball to a friend. Start again.")],
      [fp("Sing. Play. Answer."),
       pAns("E.A.: each pupil says “My name is ……” with his/her real name; the class answers “Nice to meet you” + the name.",
        ["My name is", "Nice to meet you"], { size: SZ.FICHE })],
      "Game / “Repetition drill”", "Ball, “What’s your name?” song"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("Answer your teacher:"),
       fp("1. What’s your name?"),
       fp("2. Nice to meet you."),
       fp("3. Ask your friend’s name."),
       fp("4. Your friend answers. Say “Nice to meet you” with his/her name.")],
      [fp("Answer."),
       pAns("E.A.: 1. My name is …… (real name)  2. Nice to meet you too.  3. What’s your name?  4. Nice to meet you, ……!",
        ["My name is", "Nice to meet you too.", "What’s your name?"], { size: SZ.FICHE })],
      "Individual work / In pairs", "----"),
  ];
  return fiche(3, TOTAL, meta, rows, "s3");
}

function ficheS4() {
  const meta = META("Introducing yourself: How old are you?",
    "By the end of the lesson, learners will be able to say their age in English.",
    "4 / 6", "pictures of two children, blackboard");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. What’s your name?"),
       fp("2. Ask my name."),
       fp("3. Nice to meet you."),
       fp("4. Greet your friend and ask his/her name.")],
      [fp("Answer."),
       fp("E.A.: 1. My name is ……"),
       fp("2. What’s your name?"),
       fp("3. Nice to meet you too."),
       fp("4. Hello! What’s your name?")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Look at Soa. She is not big, she is not small. Do you know her age?")],
      [fp("Listen. Answer."), fp("E.A.: No. / Eight? Nine?")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Introducing yourself: How old are you? ». By the end of this lesson, you will be able to say your age in English.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at these two pictures of children.")],
      [fp("Look.")], "Whole-class work", "Pictures of two children"),
    stepRow(["4. Analysis"],
      [fp("The first child asks a question: “How old are you?”. What does he want to know?"),
       fp("The second child answers: “I’m 8”. What does it mean?"),
       fp("How do you ask the age of a friend?"),
       fp("How do you answer?")],
      [fp("Answer."),
       fp("E.A.: The age."),
       fp("E.A.: He is 8 years old."),
       fp("E.A.: How old are you?"),
       fp("E.A.: I’m …… (age).")],
      "Brainstorming / Whole-class work", "Pictures of two children"),
    stepRow(["5. Synthesis"],
      [fp("So, to ask the age, we say: “How old are you?”. The answer is: “I’m ……” with the age: I’m 8. I’m 9. I’m 10. We can also say only the age: “8”, “9”, “10”.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Stand in two lines, face a friend."),
       fp("Ask: “How old are you?”. The friend answers: “I’m ……”."),
       fp("Change roles. Move one step to the left. Start again."),
       fp("Then choose the right answer:"),
       fp("1. “How old are you?” asks about: the name / the age"),
       fp("2. The answer is: I’m 9. / My name is Soa."),
       fp("3. “I’m 8” means: 8 years old / 8 pencils"),
       fp("4. To ask the age: How are you? / How old are you?")],
      [fp("Speak with a friend. Do the exercise."),
       pAns("E.A.: 1. the age  2. I’m 9.  3. 8 years old  4. How old are you?",
        ["the age", "I’m 9.", "8 years old", "How old are you?"], { size: SZ.FICHE })],
      "“Speed-chat” / In pairs", "----"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("Answer your teacher:"),
       fp("1. How old are you?"),
       fp("2. Ask the age of your friend."),
       fp("3. What’s your name and how old are you?"),
       fp("4. Say the chat: greet → name → age.")],
      [fp("Answer."),
       pAns("E.A.: 1. I’m …… (real age)  2. How old are you?  3. My name is ……, I’m ……  4. Hello! – What’s your name? – My name is …… – How old are you? – I’m ……",
        ["I’m", "How old are you?", "My name is"], { size: SZ.FICHE })],
      "Individual work / In pairs", "----"),
  ];
  return fiche(4, TOTAL, meta, rows, "s4");
}

function ficheS5() {
  const meta = META("Thanking",
    "By the end of the lesson, learners will be able to thank a friend and answer in English.",
    "5 / 6", "pens, books");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. What’s your name?"),
       fp("2. How old are you?"),
       fp("3. Ask my name and my age."),
       fp("4. Nice to meet you.")],
      [fp("Answer."),
       fp("E.A.: 1. My name is ……"),
       fp("2. I’m ……"),
       fp("3. What’s your name? How old are you?"),
       fp("4. Nice to meet you too.")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Soa gives a pencil to Koto. Koto is happy. What can Koto say?")],
      [fp("Listen. Answer."), fp("E.A.: Thank you. (Pupils may answer in their own words; the teacher gives the English word.)")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Thanking ». By the end of this lesson, you will be able to thank a friend and answer in English.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at me. I give a pen to …… (a pupil). I say: “Thank you!” when he/she gives it back.")],
      [fp("Look.")], "Whole-class work", "Pen"),
    stepRow(["4. Analysis"],
      [fp("I take the pen. What do I say?"),
       fp("When do we say “Thank you!”?"),
       fp("A friend says “Thank you!”. What is the answer?"),
       fp("Now give your pen to a friend. What does he/she say?")],
      [fp("Answer."),
       fp("E.A.: Thank you!"),
       fp("E.A.: When a friend gives or helps."),
       fp("E.A.: You’re welcome!"),
       fp("E.A.: Thank you!")],
      "Brainstorming / Whole-class work", "Pen"),
    stepRow(["5. Synthesis"],
      [fp("So, when a friend gives something or helps us, we say: “Thank you!”. The friend answers: “You’re welcome!”.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Give your pen to your friend. The friend says: “Thank you!”. You answer: “You’re welcome!”. Change roles."),
       fp("Then choose the right answer:"),
       fp("1. A friend gives you a book. You say: Thank you! / Sorry!"),
       fp("2. The answer to “Thank you!” is: You’re welcome! / Bye!"),
       fp("3. We say “Thank you!” when a friend: helps us / sleeps"),
       fp("4. “You’re welcome!” answers: Thank you! / How are you?")],
      [fp("Play with a friend. Do the exercise."),
       pAns("E.A.: 1. Thank you!  2. You’re welcome!  3. helps us  4. Thank you!",
        ["Thank you!", "You’re welcome!", "helps us"], { size: SZ.FICHE })],
      "“Simulation” / In pairs", "Pens, books"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("Answer your teacher:"),
       fp("1. I give you a pencil. What do you say?"),
       fp("2. Thank you!"),
       fp("3. Play the scene with your friend: give → thank → answer."),
       fp("4. When do we say “You’re welcome!”?")],
      [fp("Answer."),
       pAns("E.A.: 1. Thank you!  2. You’re welcome!  3. “Thank you!” – “You’re welcome!”  4. After “Thank you!”.",
        ["Thank you!", "You’re welcome!"], { size: SZ.FICHE })],
      "Individual work / In pairs", "----"),
  ];
  return fiche(5, TOTAL, meta, rows, "s5");
}

function ficheS6() {
  const meta = META("Apologizing",
    "By the end of the lesson, learners will be able to say sorry and answer in English.",
    "6 / 6", "blackboard");
  const rows = [
    stepRow(["I. Review", "Duration: ………"],
      [fp("Answer these questions:"),
       fp("1. I give you a book. What do you say?"),
       fp("2. Thank you!"),
       fp("3. Greet your friend and ask his/her name."),
       fp("4. How old are you?")],
      [fp("Answer."),
       fp("E.A.: 1. Thank you!"),
       fp("2. You’re welcome!"),
       fp("3. Hello! What’s your name?"),
       fp("4. I’m ……")],
      "Individual work", "----"),
    sectionRow("II. NEW LESSON — Duration: ………"),
    stepRow(["1. Warm-up"],
      [fp("Koto runs. He bumps into Soa. It is not nice. What can Koto say?")],
      [fp("Listen. Answer."), fp("E.A.: Sorry. (Pupils may answer in their own words; the teacher gives the English word.)")],
      "Whole-class work", "----"),
    stepRow(["2. Presentation"],
      [fp("Today we are going to learn a new lesson called: « Apologizing ». By the end of this lesson, you will be able to say sorry and answer in English.")],
      [fp("Listen.")], "Whole-class work", "----"),
    stepRow(["3. Observation"],
      [fp("Look at me and …… (a pupil). I bump into him/her softly. I say: “I’m sorry!”. He/she answers: “It’s OK!”.")],
      [fp("Look.")], "Whole-class work", "----"),
    stepRow(["4. Analysis"],
      [fp("I bump into a friend. What do I say?"),
       fp("What is the short word for “I’m sorry”?"),
       fp("The friend answers. What does he/she say?"),
       fp("When do we say “Sorry”?")],
      [fp("Answer."),
       fp("E.A.: I’m sorry!"),
       fp("E.A.: Sorry!"),
       fp("E.A.: It’s OK!"),
       fp("E.A.: When we do something bad. / When we bump into a friend.")],
      "Brainstorming / Whole-class work", "----"),
    stepRow(["5. Synthesis"],
      [fp("So, when we do something bad, we say: “I’m sorry!” or “Sorry!”. The friend answers: “It’s OK!”.")],
      [fp("Listen.")], "Whole-class work", "Blackboard"),
    stepRow(["6. Practice"],
      [fp("Play the scene with a friend: bump softly → say “Sorry!” → answer “It’s OK!”. Change roles."),
       fp("Then choose the right answer:"),
       fp("1. You bump into a friend. You say: Sorry! / Thank you!"),
       fp("2. The answer to “I’m sorry!” is: It’s OK! / You’re welcome!"),
       fp("3. The short word for “I’m sorry” is: Sorry! / Bye!"),
       fp("4. We say “Sorry!” when we: do something bad / sing")],
      [fp("Play with a friend. Do the exercise."),
       pAns("E.A.: 1. Sorry!  2. It’s OK!  3. Sorry!  4. do something bad",
        ["Sorry!", "It’s OK!", "do something bad"], { size: SZ.FICHE })],
      "“Simulation” / In pairs", "----"),
    stepRow(["III. Evaluation", "Duration: ………"],
      [fp("Answer your teacher:"),
       fp("1. You step on my foot. What do you say?"),
       fp("2. I’m sorry!"),
       fp("3. Play the scene with your friend: bump → sorry → answer."),
       fp("4. Say all the words of Unit 1 that you remember.")],
      [fp("Answer."),
       pAns("E.A.: 1. I’m sorry! / Sorry!  2. It’s OK!  3. “Sorry!” – “It’s OK!”  4. Hello, Hi, Good morning, How are you, I’m fine, Goodbye, Bye, My name is, Nice to meet you, How old are you, Thank you, You’re welcome, Sorry, It’s OK…",
        ["I’m sorry! / Sorry!", "It’s OK!"], { size: SZ.FICHE })],
      "Individual work / In pairs", "----"),
  ];
  return fiche(6, TOTAL, meta, rows, "s6");
}

// ---------- LEÇON fusionnée ----------
function lesson() {
  return [
    p([run("LESSON — UNIT 1", { bold: true, size: 30 })], { center: true, after: 120 }),
    lessonTitle("SOCIALISING"),

    sub("1. Greetings"),
    pr([run("To greet a friend, we say: "), ...kw("Hello!", "hèlôou"), run(" or "), ...kw("Hi!", "haï")]),
    pr([run("In the morning, we say: "), ...kw("Good morning!", "goud môrning")]),
    pr([run("To ask about a friend: "), ...kw("How are you?", "haou âr iou")]),
    pr([run("The answer is: "), ...kw("I’m fine, thank you.", "aïm faïn, tenk iou")], { after: 120 }),
    img("koto_soa.png", 300, 768 / 1416),

    sub("2. Saying goodbye"),
    pr([run("When we leave, we say: "), ...kw("Goodbye!", "goudbaï"),
        run(" or "), ...kw("Bye!", "baï"), run(" or "), ...kw("Bye-bye!", "baï-baï")], { after: 120 }),

    sub("3. Introducing yourself"),
    pr([run("To ask a name: "), ...kw("What’s your name?", "ouots iôr néim")]),
    pr([run("The answer: "), ...kw("My name is ……", "maï néim iz")]),
    pr([run("Then we say: "), ...kw("Nice to meet you.", "naïs tou mit iou")]),
    pr([run("The friend answers: "), ...kw("Nice to meet you too.", "naïs tou mit iou tou")]),
    pr([run("To ask the age: "), ...kw("How old are you?", "haou ôould âr iou")]),
    pr([run("The answer: "), ...kw("I’m 8.", "aïm éit"), run("  /  I’m 9.  /  I’m 10.")], { after: 120 }),
    img("u1_introducing.png", 300, 768 / 1416),

    sub("4. Thanking"),
    pr([run("A friend gives or helps. We say: "), ...kw("Thank you!", "tenk iou")]),
    pr([run("The friend answers: "), ...kw("You’re welcome!", "iôr ouèlkeum")], { after: 120 }),
    img("u1_thanking.png", 300, 768 / 1416),

    sub("5. Apologizing"),
    pr([run("We do something bad. We say: "), ...kw("I’m sorry!", "aïm sori"),
        run(" or "), ...kw("Sorry!", "sori")]),
    pr([run("The friend answers: "), ...kw("It’s OK!", "its ôou-kéi")], { after: 140 }),

    audioBox([
      { qr: "qr_u1_greetings.png", label: "Greetings — listen and repeat", url: AUDIO.greetings },
      { qr: "qr_u1_goodbye.png", label: "Saying goodbye — listen and repeat", url: AUDIO.goodbye },
      { qr: "qr_u1_introducing.png", label: "What’s your name? — listen and repeat", url: AUDIO.introducing },
      { qr: "qr_u1_age.png", label: "How old are you? — listen and repeat", url: AUDIO.age },
      { qr: "qr_u1_thanking_apologizing.png", label: "Thank you! I’m sorry! — listen and repeat", url: AUDIO.thanking },
    ], COLOR),
  ];
}

// ---------- EXERCICES ----------
function exercises() {
  return [
    p([run("EXERCISES", { bold: true, size: 30 })], { center: true, after: 140 }),
    pr([run("Exercise 1 (4 points). ", { bold: true }), run("Match the sentence to the answer:")]),
    p("1. Hello!                         a. It’s OK!"),
    p("2. How are you?             b. You’re welcome!"),
    p("3. Thank you!                 c. Hi!"),
    p("4. I’m sorry!                    d. I’m fine, thank you.", { after: 120 }),
    pr([run("Exercise 2 (4 points). ", { bold: true }), run("Circle the right answer:")]),
    p("1. In the morning we say: Bye! / Good morning! / It’s OK!"),
    p("2. To ask a name: How old are you? / What’s your name? / How are you?"),
    p("3. We leave the class. We say: Goodbye! / Hello! / You’re welcome!"),
    p("4. A friend gives you a book. You say: Sorry! / Thank you! / Nice to meet you.", { after: 120 }),
    pr([run("Exercise 3 (6 points). ", { bold: true }), run("Complete the chat with: "),
        run("name – fine – old – meet – Hi – Bye", { bold: true })]),
    p("Koto: Hello! How are you?"),
    p("Fara: I’m ………, thank you."),
    p("Koto: What’s your ………?"),
    p("Fara: My name is Fara. Nice to ……… you."),
    p("Koto: Nice to meet you too. How ……… are you?"),
    p("Fara: I’m 9. Goodbye!"),
    p("Koto: ………-bye!", { after: 120 }),
    pr([run("Exercise 4 (6 points). ", { bold: true }), run("Put the chat in the right order (write 1, 2, 3, 4):")]),
    p("…… Nice to meet you too."),
    p("…… What’s your name?"),
    p("…… My name is Hery."),
    p("…… Nice to meet you.", { after: 140 }),
    p([run("Total: 20 points", { bold: true })], { after: 160 }),
    p([run("ANSWER KEY", { bold: true, size: SZ.SUB, color: C.PINK })], { center: true, after: 120 }),
    pAns("Exercise 1: 1–c ; 2–d ; 3–b ; 4–a", ["1–c", "2–d", "3–b", "4–a"]),
    pAns("Exercise 2: 1. Good morning!  2. What’s your name?  3. Goodbye!  4. Thank you!",
      ["Good morning!", "What’s your name?", "Goodbye!", "Thank you!"]),
    pAns("Exercise 3: fine ; name ; meet ; old ; Bye", ["fine", "name", "meet", "old", "Bye"]),
    pAns("Exercise 4: 4 – 1 – 2 – 3 (What’s your name? → My name is Hery. → Nice to meet you. → Nice to meet you too.)",
      ["4 – 1 – 2 – 3"]),
  ];
}

// ---------- SESSION 7 : RÉVISION ----------
function revision() {
  const t = (a, b) => new TableRow({ children: [
    cell([fp([run(a, { bold: true, size: SZ.FICHE })])], { w: 4200 }),
    cell([fp(b)], { w: 6200 }),
  ]});
  return [
    B.bookmarkTitle("s7", "SESSION 7 / 57", { bold: true, size: 28, after: 60 }),
    p([run("REVISION — UNIT 1: SOCIALISING", { bold: true, size: 26 })], { center: true, after: 140 }),
    p("Remember the words of Unit 1:", { after: 100 }),
    new Table({ width: { size: 10400, type: WidthType.DXA }, rows: [
      new TableRow({ children: [
        cell([fp([run("We say…", { bold: true, size: SZ.FICHE })])], { w: 4200, shade: C.HDR1 }),
        cell([fp([run("When…", { bold: true, size: SZ.FICHE })])], { w: 6200, shade: C.HDR1 }),
      ]}),
      t("Hello! / Hi! / Good morning!", "we meet a friend"),
      t("How are you? — I’m fine, thank you.", "we ask about a friend"),
      t("Goodbye! / Bye! / Bye-bye!", "we leave"),
      t("What’s your name? — My name is ……", "we ask a name"),
      t("Nice to meet you. — Nice to meet you too.", "we meet a new friend"),
      t("How old are you? — I’m ……", "we ask the age"),
      t("Thank you! — You’re welcome!", "a friend gives or helps"),
      t("I’m sorry! / Sorry! — It’s OK!", "we do something bad"),
    ]}),
    p("", { after: 120 }),
    p([run("Now answer:", { bold: true })], { after: 80 }),
    p("1. Greet your friend."),
    pAns("E.A.: Hello! / Hi! / Good morning!", ["Hello!", "Hi!", "Good morning!"]),
    p("2. How are you?"),
    pAns("E.A.: I’m fine, thank you.", ["I’m fine, thank you."]),
    p("3. What’s your name? How old are you?"),
    pAns("E.A.: My name is ……, I’m ……", ["My name is", "I’m"]),
    p("4. Your friend gives you a pen. What do you say? What does he answer?"),
    pAns("E.A.: Thank you! — You’re welcome!", ["Thank you!", "You’re welcome!"]),
    p("5. You bump into a friend. What do you say? What does he answer?"),
    pAns("E.A.: I’m sorry! / Sorry! — It’s OK!", ["Sorry!", "It’s OK!"]),
    p("6. Say a full chat with your friend: greet → name → age → goodbye."),
    pAns("E.A.: Hello! – Hi! – What’s your name? – My name is …… – How old are you? – I’m …… – Goodbye! – Bye!",
      ["Hello!", "What’s your name?", "How old are you?", "Goodbye!"]),
  ];
}

// ---------- SESSION 8 : TEST PAPER ----------
function testPaper() {
  return [
    B.bookmarkTitle("s8", "SESSION 8 / 57", { bold: true, size: 28, after: 60 }),
    p([run("T4 TEST PAPER — UNIT 1: SOCIALISING", { bold: true, size: 26 })], { center: true, after: 100 }),
    pr([run("Duration: ………        ", { bold: true }), run("Total: 20 points", { bold: true })], { center: true, after: 160 }),
    pr([run("Exercise 1 (6 points). ", { bold: true }), run("Match the sentence to the answer:")]),
    p("1. Good morning!            a. I’m fine, thank you."),
    p("2. What’s your name?     b. It’s OK!"),
    p("3. How are you?              c. Good morning!"),
    p("4. Thank you!                  d. My name is Nivo."),
    p("5. Sorry!                          e. Nice to meet you too."),
    p("6. Nice to meet you.        f. You’re welcome!", { after: 120 }),
    pr([run("Exercise 2 (4 points). ", { bold: true }), run("Circle the right answer:")]),
    p("1. You leave the class: Hello! / Goodbye! / It’s OK!"),
    p("2. You ask the age: How old are you? / How are you? / What’s your name?"),
    p("3. A friend helps you: Sorry! / Thank you! / Bye!"),
    p("4. A friend says “Hi!”: Hi! / You’re welcome! / I’m 9.", { after: 120 }),
    pr([run("Exercise 3 (6 points). ", { bold: true }), run("Complete the chat with: "),
        run("meet – name – morning – fine – old – Goodbye", { bold: true })]),
    p("Lanto: Good ………! How are you?"),
    p("Tiana: I’m ………, thank you."),
    p("Lanto: What’s your ………?"),
    p("Tiana: My name is Tiana. Nice to ……… you."),
    p("Lanto: How ……… are you?"),
    p("Tiana: I’m 9. ………! — Bye!", { after: 120 }),
    pr([run("Exercise 4 (4 points). ", { bold: true }), run("Act with your teacher: greet, say your name, say your age, say goodbye.")]),
    p("", { after: 140 }),
    p([run("ANSWER KEY", { bold: true, size: SZ.SUB, color: C.PINK })], { center: true, after: 120 }),
    pAns("Exercise 1: 1–c ; 2–d ; 3–a ; 4–f ; 5–b ; 6–e (1 point each)",
      ["1–c", "2–d", "3–a", "4–f", "5–b", "6–e"]),
    pAns("Exercise 2: 1. Goodbye!  2. How old are you?  3. Thank you!  4. Hi! (1 point each)",
      ["Goodbye!", "How old are you?", "Thank you!", "Hi!"]),
    pAns("Exercise 3: morning ; fine ; name ; meet ; old ; Goodbye (1 point each)",
      ["morning", "fine", "name", "meet", "old", "Goodbye"]),
    pAns("Exercise 4: the pupil says: Hello! / Good morning! — My name is …… — I’m …… — Goodbye! (1 point per sentence)",
      ["Hello!", "My name is", "I’m", "Goodbye!"]),
  ];
}

module.exports = function unit1() {
  return [
    ...opening(), pageBreak(),
    ...ficheS1(), pageBreak(),
    ...ficheS2(), pageBreak(),
    ...ficheS3(), pageBreak(),
    ...ficheS4(), pageBreak(),
    ...ficheS5(), pageBreak(),
    ...ficheS6(), pageBreak(),
    ...lesson(), pageBreak(),
    ...exercises(), pageBreak(),
    ...revision(), pageBreak(),
    ...testPaper(), pageBreak(),
    ...iCan("UNIT 1", COLOR, [
      "I can greet my friends: Hello! Hi! Good morning!",
      "I can answer: How are you? — I’m fine, thank you.",
      "I can say goodbye: Goodbye! Bye! Bye-bye!",
      "I can say my name and my age.",
      "I can say: Thank you! — You’re welcome!",
      "I can say: I’m sorry! — It’s OK!",
    ], "Well done! See you in Unit 2: THE ALPHABET!"),
  ];
};
module.exports.COLOR = COLOR;
