function fig(file,legende){return {file,legende,place:'lecon'};}
const F={ration:'gen/ration-alimentaire.jpg',nutriments:'gen/nutriments.jpg',energie:'gen/besoins-energetiques.jpg',menu:'gen/menu-madagascar.jpg',mal:'gen/malnutrition.jpg',plante:'gen/besoins-plante.jpg',absorption:'gen/absorption-plante.jpg',protection:'gen/protection-plantes.jpg',chimique:'gen/protection-chimique.jpg',elevage:'gen/elevage-madagascar.jpg',animal:'gen/besoins-animaux.jpg',nerveux:'gen/systeme-nerveux.jpg',reflexe:'gen/arc-reflexe.jpg',reactions:'gen/reactions-reflexes.jpg',psycho:'gen/substances-psychoactives.jpg',effets:'gen/effets-psychoactifs.jpg',sante:'gen/sante-femmes.jpg',fistule:'gen/fistule-prevention.jpg',gemme:'gen/pierres-gemmes-madagascar.jpg',props:'gen/proprietes-gemmes.jpg',menus:'gen/menus-malnutrition.jpg',soins:'gen/soins-plantes.jpg',vaccin:'gen/vaccination-elevage.jpg',volontaire:'gen/mouvement-volontaire.jpg',categories:'gen/categories-psychoactives.jpg',cancer:'gen/cancer-col-prevention.jpg',carte:'gen/carte-gemmes.jpg',usages:'gen/usages-gemmes.jpg',impacts:'gen/impacts-miniers.jpg',examen:'gen/examen-t9-svt.jpg'};
const L={ration:'Ration alimentaire et menu équilibré.',nutriments:'Les nutriments et leurs rôles.',energie:'Besoins énergétiques.',menu:'Menu varié à Madagascar.',mal:'Formes de malnutrition et prévention.',plante:'Besoins et soins des plantes locales.',absorption:'Absorption de l’eau et des sels minéraux.',protection:'Protection naturelle contre les bio-agresseurs.',chimique:'Protection chimique et sécurité.',elevage:'Techniques d’élevage à Madagascar.',animal:'Besoins des animaux.',nerveux:'Organisation du système nerveux.',reflexe:'Arc réflexe.',reactions:'Réactions réflexes et volontaires.',psycho:'Substances psychoactives et prévention.',effets:'Effets des substances psychoactives.',sante:'Prévention et soins de santé reproductive.',fistule:'Prévention de la fistule obstétricale.',gemme:'Pierres gemmes de Madagascar.',props:'Propriétés physiques des gemmes.',menus:'Menus d’appoint et malnutrition.',soins:'Entretien des plantes.',vaccin:'Vaccination et soins des animaux.',volontaire:'Mouvement volontaire.',categories:'Catégories de substances psychoactives.',cancer:'Prévention du cancer du col.',carte:'Répartition des gemmes à Madagascar.',usages:'Utilisations des pierres gemmes.',impacts:'Impacts environnementaux de l’exploitation.',examen:'Documents d’examen SVT T9.'};
const map={};const add=(u,arr)=>arr.forEach((k,i)=>map[`${u}:${i}`]=[fig(F[k],L[k])]);
add('I',['ration','nutriments','nutriments','energie','energie','menu','menu','ration','mal','menus']);
add('II',['plante','absorption','soins','protection','protection','chimique','animal','elevage','vaccin','elevage']);
add('III',['nerveux','nerveux','reflexe','reactions','volontaire','reflexe','categories','effets','psycho']);
add('IV',['fistule','fistule','fistule','cancer','cancer','sante']);
add('V',['gemme','props','carte','usages','impacts','examen']);
const REVISION_IMAGES={I:fig(F.ration,'Bilan de l’alimentation et de la malnutrition.'),II:fig(F.plante,'Bilan des plantes et de l’élevage.'),III:fig(F.nerveux,'Bilan du système nerveux et des substances psychoactives.'),IV:fig(F.sante,'Bilan de la prévention et de la santé reproductive.'),V:fig(F.gemme,'Bilan des pierres gemmes de Madagascar.')};
const EXAM_IMAGES={I:[REVISION_IMAGES.I],II:[REVISION_IMAGES.II],III:[REVISION_IMAGES.III],IV:[REVISION_IMAGES.IV],V:[REVISION_IMAGES.V]};
const ANNEXE_IMAGES=[REVISION_IMAGES.V];
function apply(n,t){t.forEach((x,i)=>{if(map[`${n}:${i}`]){x.images=map[`${n}:${i}`];x.exoImage=x.images[0];x.corrigeImage=x.images[0];}});return t;}
module.exports={IMG:map,REVISION_IMAGES,EXAM_IMAGES,ANNEXE_IMAGES,apply};
