// Contenu spécifique des 41 leçons du PE T9. Chaque entrée évite la réutilisation d'un gabarit générique.
const C={
'Alimentation de l’homme':[
{rev:['Quels sont les trois grands rôles des aliments ?','Les aliments sont énergétiques, constructeurs ou protecteurs.'],mise:'Rova décrit son petit-déjeuner composé de riz, lait et fruit.',obs:'un petit-déjeuner malgache et une pyramide alimentaire',synth:'La ration alimentaire est l’ensemble des aliments consommés en une journée. Elle doit fournir une quantité adaptée d’aliments énergétiques, constructeurs et protecteurs.',details:['Les aliments énergétiques fournissent l’énergie nécessaire aux activités et au fonctionnement du corps.','Les aliments constructeurs participent à la croissance et à la réparation des tissus.','Les aliments protecteurs apportent des vitamines, des sels minéraux et de l’eau.'],q1:'Quels rôles les aliments du petit-déjeuner de Rova peuvent-ils jouer ?'},
{rev:['Qu’est-ce qu’un nutriment ?','Un nutriment est une substance utilisable par l’organisme.'],mise:'Nivo classe du riz, des haricots, de l’huile et des brèdes selon leur rôle.',obs:'des aliments locaux et un tableau de leurs nutriments',synth:'Les glucides fournissent principalement de l’énergie, les protéines construisent et réparent, les lipides fournissent de l’énergie. Les vitamines, les sels minéraux et l’eau permettent le bon fonctionnement du corps.',details:['Les glucides sont présents dans le riz, le manioc et les céréales.','Les protéines sont présentes dans les haricots, les œufs, le lait, la viande et le poisson.','Les lipides sont présents dans l’huile, l’arachide et certaines graines.','Les vitamines, sels minéraux et l’eau ont surtout des rôles protecteurs et régulateurs.'],q1:'Quel nutriment principal trouve-t-on dans le riz et dans les haricots ?'},
{rev:['Quel est le rôle des glucides, des protéines et des lipides ?','Les glucides et lipides fournissent de l’énergie ; les protéines construisent et réparent.'],mise:'Soa compare une mangue, des brèdes, du lait et des haricots.',obs:'des aliments riches en vitamines, sels minéraux et eau',synth:'Les vitamines et les sels minéraux sont nécessaires en petites quantités. L’eau est indispensable aux réactions et aux échanges de l’organisme.',details:['La vitamine A participe notamment au fonctionnement de la vision et des tissus.','La vitamine C intervient dans la protection de l’organisme.','Le calcium participe à la solidité des os et des dents.','L’eau transporte des substances et participe à la régulation de la température.'],q1:'Pourquoi les fruits, les légumes et l’eau sont-ils indispensables ?'},
{rev:['Quels sont les rôles des vitamines, des sels minéraux et de l’eau ?','Ils protègent et régulent le fonctionnement de l’organisme.'],mise:'Un tableau indique l’énergie apportée par un gramme de glucide, de protéine ou de lipide.',obs:'un tableau de valeurs énergétiques des nutriments',synth:'La valeur énergétique correspond à l’énergie libérée par un aliment lors de son utilisation par l’organisme. Elle s’exprime généralement en kilojoules ou en kilocalories.',details:['Les glucides et les protéines apportent environ 4 kcal par gramme.','Les lipides apportent environ 9 kcal par gramme.','La valeur énergétique d’un repas dépend des quantités de chaque nutriment.'],q1:'Quel nutriment apporte le plus d’énergie par gramme : un glucide ou un lipide ?'},
{rev:['Que signifie valeur énergétique ?','C’est la quantité d’énergie libérée par l’utilisation d’un aliment.'],mise:'Un adolescent dépense de l’énergie au repos puis pendant une activité sportive.',obs:'un schéma du métabolisme de base et des dépenses quotidiennes',synth:'Le métabolisme de base est l’énergie minimale nécessaire au fonctionnement du corps au repos. Les besoins augmentent avec la croissance et l’activité physique.',details:['Le cœur, la respiration et le maintien de la température consomment de l’énergie même au repos.','Marcher, travailler et faire du sport augmentent les dépenses énergétiques.','Les besoins doivent être comparés aux apports alimentaires.'],q1:'Pourquoi les besoins énergétiques d’un adolescent sportif sont-ils plus élevés ?'},
{rev:['De quoi dépendent les besoins énergétiques ?','Ils dépendent notamment de l’âge, de la croissance et de l’activité physique.'],mise:'Nivo calcule les apports d’une journée à partir des quantités d’aliments consommées.',obs:'un exemple de calcul de besoins énergétiques',synth:'Pour estimer un besoin énergétique, on additionne l’énergie nécessaire au métabolisme de base et celle dépensée pendant les activités.',details:['On identifie les aliments consommés et leurs quantités.','On utilise la valeur énergétique de chaque nutriment.','On compare ensuite les apports aux dépenses de la journée.'],q1:'Quelles données faut-il connaître pour calculer l’énergie d’un menu ?'},
{rev:['Comment compare-t-on les apports et les besoins énergétiques ?','On estime l’énergie des aliments puis on la compare aux dépenses du corps.'],mise:'Une famille prépare le menu d’une journée avec riz, haricots, légumes, poisson, fruit et eau.',obs:'un menu malgache réparti en trois repas',synth:'Un menu varié associe plusieurs groupes d’aliments au cours de la journée. Les quantités sont adaptées à l’âge, à l’activité et aux besoins de chacun.',details:['Le petit-déjeuner, le déjeuner et le dîner doivent être complémentaires.','Les légumineuses et les céréales peuvent se compléter.','Les légumes, les fruits et l’eau complètent les aliments énergétiques et constructeurs.'],q1:'Quels aliments peut-on associer au riz pour rendre un repas plus varié ?'},
{rev:['Qu’est-ce qu’un menu varié ?','C’est un menu qui associe des aliments différents et complémentaires.'],mise:'Rova compare un menu équilibré avec un menu composé presque uniquement de riz et de boissons sucrées.',obs:'deux menus quotidiens à comparer',synth:'Une alimentation équilibrée favorise la croissance, l’énergie, les apprentissages et la santé. Elle associe variété, quantité adaptée et hygiène alimentaire.',details:['La variété évite les carences.','L’équilibre doit être recherché sur l’ensemble de la journée.','L’eau potable est préférable aux boissons très sucrées.'],q1:'Quel menu favorise le mieux la croissance et pourquoi ?'},
{rev:['Pourquoi faut-il varier les aliments ?','Pour apporter les différents nutriments nécessaires à l’organisme.'],mise:'Deux études de cas présentent un enfant carencé et un adolescent en surpoids.',obs:'des situations de carence, de malnutrition aiguë et d’excès',synth:'La malnutrition peut être due à un manque, à un excès ou à un déséquilibre alimentaire. Elle peut avoir des conséquences physiques et psychologiques.',details:['La carence correspond à un apport insuffisant d’un ou plusieurs nutriments.','La malnutrition aiguë peut être liée à une insuffisance alimentaire ou à une maladie.','Le surpoids et l’obésité résultent d’un déséquilibre durable entre apports et dépenses.'],q1:'Quelles différences observe-t-on entre une carence et un excès alimentaire ?'},
{rev:['Quelles sont les formes de malnutrition ?','On distingue notamment les carences, la malnutrition aiguë, le surpoids et l’obésité.'],mise:'Un centre de santé propose un menu d’appoint adapté à la situation d’un enfant.',obs:'des menus d’appoint pour différentes situations nutritionnelles',synth:'La prise en charge de la malnutrition dépend de sa cause et de sa forme. Elle doit être accompagnée par un professionnel de santé.',details:['Un menu d’appoint augmente progressivement les apports d’un enfant carencé.','Un excès alimentaire demande une alimentation équilibrée et une activité adaptée.','Un suivi médical est nécessaire lorsque la malnutrition est importante.'],q1:'Pourquoi un même menu ne convient-il pas à toutes les situations de malnutrition?'}],
'Organisation des êtres vivants':[
{rev:['De quoi une plante verte a-t-elle besoin pour vivre ?','Elle a besoin notamment d’eau, de sels minéraux, de lumière et de dioxyde de carbone.'],mise:'Soa compare une plante de rizière bien développée avec une plante cultivée dans un sol pauvre.',obs:'des plantes locales et leurs milieux de vie',synth:'Les plantes ont des besoins nutritifs différents selon l’espèce et le milieu. Elles prélèvent l’eau et les sels minéraux dans le sol et utilisent la lumière pour fabriquer leur matière organique.',details:['Les racines prélèvent l’eau et les sels minéraux.','Les feuilles captent la lumière et les échanges gazeux se font avec l’air.','Le sol, l’eau, la lumière et la température influencent la croissance.'],q1:'Quels éléments du milieu expliquent la différence entre les deux plantes ?'},
{rev:['Quel est le rôle des racines ?','Elles fixent la plante et absorbent principalement l’eau et les sels minéraux.'],mise:'Une expérience compare une racine avec et sans poils absorbants.',obs:'une racine et ses poils absorbants',synth:'Les poils absorbants augmentent la surface de contact entre la racine et le sol. Ils facilitent l’entrée de l’eau et des sels minéraux.',details:['Les poils absorbants sont de très fins prolongements des cellules de la racine.','L’eau et les sels minéraux passent ensuite vers les vaisseaux conducteurs.','Une racine abîmée absorbe moins efficacement.'],q1:'Pourquoi les poils absorbants facilitent-ils l’alimentation de la plante ?'},
{rev:['Comment une plante prélève-t-elle l’eau du sol ?','L’eau entre principalement au niveau des poils absorbants.'],mise:'Un élève observe une parcelle et propose un calendrier d’entretien.',obs:'un potager avec arrosage, sarclage, désherbage et éclaircissage',synth:'L’entretien d’une plante comprend des soins adaptés à ses besoins : arrosage, désherbage, sarclage, éclaircissage et apport d’éléments nutritifs.',details:['L’arrosage apporte l’eau nécessaire sans détremper le sol.','Le désherbage limite la concurrence entre les plantes.','L’éclaircissage laisse suffisamment d’espace à chaque plant.'],q1:'Quel soin faut-il choisir si les jeunes plants sont trop rapprochés ?'},
{rev:['Quels soins favorisent la croissance d’une plante ?','L’arrosage, le désherbage, le sarclage et l’éclaircissage peuvent être nécessaires.'],mise:'Une feuille de riz présente des taches et des insectes sont observés sur une plante.',obs:'des pucerons, des criquets et une maladie fongique',synth:'Un bio-agresseur est un organisme qui cause des dommages à une plante. Il peut s’agir d’un insecte, d’un champignon ou d’un autre organisme.',details:['Les pucerons prélèvent la sève.','Les criquets consomment les feuilles et les jeunes pousses.','Les champignons peuvent provoquer des taches ou le dépérissement.'],q1:'Quels indices permettent d’identifier un bio-agresseur ?'},
{rev:['Qu’est-ce qu’un bio-agresseur ?','C’est un organisme qui peut endommager une plante.'],mise:'Des élèves préparent une solution à base de neem ou de piment pour protéger un potager.',obs:'des méthodes naturelles contre les bio-agresseurs',synth:'Les méthodes naturelles utilisent des moyens biologiques ou des préparations végétales pour limiter les bio-agresseurs.',details:['Le neem et le piment peuvent repousser ou limiter certains insectes.','La surveillance régulière permet d’intervenir tôt.','La diversité des plantes peut réduire la propagation de certains ravageurs.'],q1:'Pourquoi vaut-il mieux intervenir dès les premiers signes d’attaque ?'},
{rev:['Cite une méthode naturelle de protection des plantes.','On peut utiliser notamment le neem, le piment ou une surveillance régulière.'],mise:'Un agriculteur doit choisir un produit et protéger ses mains, ses yeux et l’eau.',obs:'une étiquette de produit phytosanitaire et des règles de sécurité',synth:'Une méthode chimique utilise un produit destiné à détruire un bio-agresseur. Elle doit être choisie, dosée et appliquée avec prudence.',details:['Un insecticide agit contre certains insectes et un fongicide contre certains champignons.','Les gants, le masque et le respect du dosage protègent l’utilisateur.','Les produits ne doivent pas contaminer les sources d’eau.'],q1:'Quelles précautions faut-il prendre avant d’utiliser un produit chimique ?'},
{rev:['Quelle différence existe entre protection naturelle et protection chimique ?','La première utilise des moyens biologiques ou végétaux ; la seconde utilise un produit spécifique.'],mise:'Rova établit la fiche des besoins d’un zébu ou d’une volaille de son village.',obs:'un animal d’élevage et son environnement',synth:'Chaque animal possède des besoins particuliers en nourriture, eau, air, espace, habitat et soins.',details:['Les besoins varient selon l’espèce, l’âge et l’usage de l’animal.','Un habitat propre, aéré et protégé réduit les maladies.','L’observation permet de repérer un manque de nourriture, d’eau ou de soins.'],q1:'Quels besoins faut-il noter dans la fiche d’un animal d’élevage ?'},
{rev:['Quels sont les besoins essentiels d’un animal ?','Il a besoin d’aliments, d’eau, d’air, d’un habitat adapté et de soins.'],mise:'Une éleveuse compare un abri propre et un abri mal entretenu.',obs:'des habitats et des rations destinés aux animaux',synth:'L’alimentation et l’habitat doivent être adaptés à l’espèce. Ils influencent la croissance, la santé et la production.',details:['L’eau doit être disponible et propre.','L’animal doit recevoir une nourriture adaptée à son âge et à son espèce.','L’abri protège des intempéries, des parasites et des blessures.'],q1:'Comment l’habitat influence-t-il la santé d’un animal ?'},
{rev:['Comment améliorer l’habitat d’un animal ?','On peut le rendre propre, aéré, sûr et adapté à l’espèce.'],mise:'Un vétérinaire vaccine des volailles et explique les soins réguliers.',obs:'un calendrier de vaccination et une scène de soins',synth:'La prévention des maladies animales repose sur l’hygiène, la vaccination, l’observation et les soins rapides.',details:['La vaccination prépare l’organisme à se défendre contre certaines maladies.','Un animal malade doit être isolé et soigné selon les conseils du vétérinaire.','L’hygiène des mangeoires et des abris limite les contaminations.'],q1:'Pourquoi la vaccination fait-elle partie des techniques d’élevage ?'},
{rev:['À quoi sert la vaccination d’un animal ?','Elle aide à le protéger contre certaines maladies.'],mise:'Une éleveuse choisit des reproducteurs sains et adaptés à son milieu.',obs:'un tableau de caractères d’animaux d’élevage',synth:'La sélection consiste à choisir des reproducteurs présentant des caractères recherchés, tout en préservant la santé et la diversité des animaux.',details:['On peut rechercher une bonne résistance, une croissance adaptée ou une production régulière.','La sélection doit respecter les besoins et le bien-être de l’animal.','Elle s’associe toujours à une bonne alimentation, un habitat adapté et des soins.'],q1:'Quels caractères peut-on prendre en compte pour sélectionner un animal ?'}],
'Santé et bien-être':[],
'Reproduction humaine':[],
'Géologie':[]
};
module.exports={C};
