# -*- coding: utf-8 -*-
"""Contenu Bimestre 2 — Séances 7 à 12 (Blocs 3-4) + Révision + Examen."""

SEANCES_B = [
{
"n": 7, "titre": "Pourquoi se brosser les dents", "theme": "L'hygiène des dents",
"objectif": "comprendre pourquoi il faut se brosser les dents",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "une brosse à dents apportée en classe",
"image": None,
"revision": [
    ("Que sont les dents de lait ?", "Ce sont les premières dents de l'enfant."),
    ("Pourquoi protéger les dents définitives ?", "Parce qu'elles ne repoussent pas si elles tombent."),
],
"situation": "Fara mange beaucoup de bonbons. Un jour, elle a mal à une dent. Le dentiste regarde dans sa bouche : la dent a un trou noir. Pourquoi faut-il se brosser les dents ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre pourquoi il faut se brosser les dents.",
    "Je lis le titre au tableau : Pourquoi se brosser les dents.",
],
"observation": [
    "Regardez cette brosse à dents : à quoi sert-elle ?",
    "Passez votre langue sur vos dents : sentez-vous des restes d'aliments ?",
],
"analyse": [
    ("Que reste-t-il sur les dents après le repas ?", "Après le repas, il reste des morceaux d'aliments sur les dents."),
    ("Que font les microbes sur ces restes ?", "Les microbes attaquent la dent et creusent un trou : c'est la carie."),
    ("Comment enlever ces restes ?", "On enlève ces restes en se brossant les dents."),
],
"synthese": "Les restes d'aliments attirent les microbes qui creusent des trous dans les dents : ce sont les caries. Le brossage enlève les restes et protège les dents.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les restes d'aliments restent sur les dents.", "2. Les microbes creusent des trous dans les dents.", "3. Un trou dans la dent s'appelle une carie.", "4. Le brossage ne sert à rien."],
     "cor": ["1. **Vrai** : les restes restent sur les dents.", "2. **Vrai** : les microbes creusent des trous.", "3. **Vrai** : ce trou s'appelle une carie.", "4. **Faux** : le brossage enlève les restes."]},
    {"c": "Complète avec les mots suivants : brosser, carie, microbes, aliments.",
     "items": ["1. Après le repas, il reste des ... sur les dents.", "2. Les ... attaquent les dents.", "3. Le trou dans la dent s'appelle la ...", "4. Pour protéger les dents, il faut se les ...."],
     "cor": ["1. Il reste des **aliments** sur les dents.", "2. Les **microbes** attaquent les dents.", "3. Le trou s'appelle la **carie**.", "4. Il faut se les **brosser**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que reste-t-il sur les dents après manger ? A. Rien B. Des restes d'aliments C. De l'eau", "2. Que font les microbes ? A. Ils nettoient les dents B. Ils creusent des trous C. Ils blanchissent les dents", "3. Comment s'appelle le trou dans la dent ? A. Une carie B. Une bosse C. Une ride", "4. Qu'est-ce qui protège les dents ? A. Le sucre B. Le brossage C. Les bonbons"],
     "cor": ["1. **B. Des restes d'aliments**.", "2. **B. Ils creusent des trous**.", "3. **A. Une carie**.", "4. **B. Le brossage**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce qu'une carie ?", "2. Qu'est-ce qui provoque la carie ?", "3. Pourquoi faut-il se brosser les dents ?", "4. Que se passe-t-il si on ne soigne pas une carie ?"],
     "cor": ["1. Une **carie** est un **trou** creusé dans la dent.", "2. Ce sont les **microbes** qui se nourrissent des **restes d'aliments**.", "3. Pour **enlever les restes** et **protéger les dents**.", "4. La **dent fait mal** et peut **tomber**."]},
],
"lecon": [
    (None, ["Après le repas, des **restes d'aliments** restent collés sur les **dents**. Les **microbes** les aiment beaucoup."]),
    ("1. La carie", ["Les **microbes** attaquent la dent et **creusent un trou** : c'est la **carie**. La dent fait mal, surtout en mangeant. Une carie non soignée peut faire tomber la dent."]),
    ("2. Le brossage protège les dents", ["Le **brossage** enlève les **restes d'aliments**. Sans restes, les microbes ne peuvent plus attaquer les dents. C'est pourquoi il faut se **brosser les dents** après les repas."]),
],
"mots_cles": ["brossage", "carie", "microbes", "restes d'aliments"],
},
{
"n": 8, "titre": "Comment bien se brosser les dents", "theme": "L'hygiène des dents",
"objectif": "bien se brosser les dents",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "l'image de l'enfant qui se brosse les dents, affichée au tableau",
"image": ("svt9e_brossage_dents.png", "Image : Koto se brosse les dents avec une brosse à dents et du dentifrice."),
"revision": [
    ("Qu'est-ce qu'une carie ?", "C'est un trou creusé dans la dent par les microbes."),
    ("Pourquoi se brosser les dents ?", "Pour enlever les restes d'aliments et protéger les dents."),
],
"situation": "Chaque matin, Soa se brosse les dents. Sa maman lui montre comment faire : du haut vers le bas, puis du bas vers le haut. Comment bien se brosser les dents ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à bien se brosser les dents.",
    "Je lis le titre au tableau : Comment bien se brosser les dents.",
],
"observation": [
    "Regardez l'image de l'enfant qui se brosse les dents.",
    "Avec votre doigt, faites le geste du brossage : haut, bas, avant, arrière.",
],
"analyse": [
    ("Avec quoi se brosse-t-on les dents ?", "On se brosse les dents avec une brosse à dents propre et du dentifrice."),
    ("Quand faut-il se brosser les dents ?", "Il faut se brosser les dents le matin et le soir."),
    ("Comment brosse-t-on les dents du haut ?", "On brosse les dents du haut de haut en bas."),
],
"synthese": "Je me brosse les dents matin et soir avec une brosse propre et du dentifrice : les dents du haut de haut en bas, les dents du bas de bas en haut.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. On se brosse les dents avec du dentifrice.", "2. Il faut se brosser les dents une fois par semaine.", "3. On brosse les dents du haut de haut en bas.", "4. La brosse à dents se prête aux amis."],
     "cor": ["1. **Vrai** : on utilise du dentifrice.", "2. **Faux** : il faut se brosser les dents matin et soir.", "3. **Vrai** : de haut en bas.", "4. **Faux** : la brosse à dents est personnelle."]},
    {"c": "Complète avec les mots suivants : matin, soir, dentifrice, brosse.",
     "items": ["1. Je me brosse les dents le ... et le ...", "2. Je mets du ... sur la brosse.", "3. Ma ... à dents est à moi seul.", "4. Je me brosse les dents du haut de ... en bas."],
     "cor": ["1. Le **matin** et le **soir**.", "2. Je mets du **dentifrice** sur la brosse.", "3. Ma **brosse** à dents est à moi seul.", "4. De **haut** en bas."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quand faut-il se brosser les dents ? A. Le matin et le soir B. Une fois par mois C. Jamais", "2. Comment brosse-t-on les dents du bas ? A. De bas en haut B. De haut en bas C. En rond seulement", "3. Que met-on sur la brosse ? A. Du savon B. Du dentifrice C. De l'huile", "4. Peut-on prêter sa brosse à dents ? A. Oui B. Non C. Parfois"],
     "cor": ["1. **A. Le matin et le soir**.", "2. **A. De bas en haut**.", "3. **B. Du dentifrice**.", "4. **B. Non** : chacun sa brosse."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quand faut-il se brosser les dents ?", "2. Avec quoi ?", "3. Comment brosse-t-on les dents du haut ?", "4. Pourquoi ne prête-t-on pas sa brosse à dents ?"],
     "cor": ["1. Le **matin** et le **soir**.", "2. Avec une **brosse à dents** propre et du **dentifrice**.", "3. De **haut en bas**.", "4. Pour ne pas échanger les **microbes**."]},
],
"lecon": [
    (None, ["Pour garder des **dents saines**, il ne suffit pas de se brosser les dents : il faut **bien** le faire."]),
    ("1. Le matériel et le moment", ["J'utilise ma **brosse à dents** personnelle et du **dentifrice**. Je me brosse les dents le **matin** et le **soir**, et après les repas si je peux."]),
    ("2. Les bons gestes", ["Je brosse les dents du **haut** de **haut en bas**, et les dents du **bas** de **bas en haut**. Je brosse devant et derrière, sans oublier le fond de la bouche. Après, je rince ma bouche et ma brosse."]),
],
"mots_cles": ["brosse à dents", "dentifrice", "matin", "soir", "brosser"],
},
{
"n": 9, "titre": "Prendre soin de ses dents", "theme": "L'hygiène des dents",
"objectif": "connaître les mesures pour garder des dents saines",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "un fruit et un bonbon apportés en classe",
"image": None,
"revision": [
    ("Quand faut-il se brosser les dents ?", "Le matin et le soir."),
    ("Comment brosse-t-on les dents du haut ?", "De haut en bas."),
],
"situation": "Hery adore les bonbons et le soda. Le dentiste lui dit : « Mange moins de sucre et croque des fruits. » Comment garder des dents saines ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à prendre soin de nos dents.",
    "Je lis le titre au tableau : Prendre soin de ses dents.",
],
"observation": [
    "Regardez ce fruit et ce bonbon : lequel est bon pour les dents ?",
    "Dites ce que vous mangez d'habitude au goûter.",
],
"analyse": [
    ("Quels aliments sont mauvais pour les dents ?", "Les bonbons, le sucre et le soda sont mauvais pour les dents."),
    ("Quels aliments sont bons pour les dents ?", "Les fruits et les légumes sont bons pour les dents."),
    ("Qui soigne les dents malades ?", "C'est le dentiste qui soigne les dents malades."),
],
"synthese": "Pour garder des dents saines, j'évite trop de sucre, je mange des fruits et je vais voir le dentiste.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les bonbons sont bons pour les dents.", "2. Les fruits sont bons pour les dents.", "3. Il faut visiter le dentiste.", "4. Le soda protège les dents."],
     "cor": ["1. **Faux** : les bonbons donnent des caries.", "2. **Vrai** : les fruits sont bons.", "3. **Vrai** : le dentiste soigne les dents.", "4. **Faux** : le soda attaque les dents."]},
    {"c": "Complète avec les mots suivants : sucre, fruits, dentiste, dents.",
     "items": ["1. Je mange peu de ...", "2. Je croque des ...", "3. Je vais voir le ...", "4. Ainsi, mes ... restent saines."],
     "cor": ["1. Je mange peu de **sucre**.", "2. Je croque des **fruits**.", "3. Je vais voir le **dentiste**.", "4. Mes **dents** restent saines."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel aliment est mauvais pour les dents ? A. Le fruit B. Le bonbon C. Le légume", "2. Quel aliment est bon pour les dents ? A. La pomme B. Le soda C. Le caramel", "3. Qui soigne les dents ? A. Le maçon B. Le dentiste C. Le pêcheur", "4. Que faire quand une dent fait mal ? A. Attendre B. Aller voir le dentiste C. Manger des bonbons"],
     "cor": ["1. **B. Le bonbon**.", "2. **A. La pomme**.", "3. **B. Le dentiste**.", "4. **B. Aller voir le dentiste**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite deux aliments mauvais pour les dents.", "2. Cite deux aliments bons pour les dents.", "3. Qui soigne les dents malades ?", "4. Cite deux mesures pour garder des dents saines."],
     "cor": ["1. Les **bonbons** et le **soda**.", "2. Les **fruits** et les **légumes**.", "3. C'est le **dentiste**.", "4. **Brosser** les dents matin et soir et **éviter le sucre**."]},
],
"lecon": [
    (None, ["Nos **dents définitives** doivent durer toute la vie : il faut bien s'en occuper."]),
    ("1. Bien manger", ["Je **mange peu de sucre** : bonbons, caramel et soda attaquent les dents. Je **croque des fruits** et des légumes : ils font travailler les dents et les gardent propres."]),
    ("2. Voir le dentiste", ["Je visite le **dentiste** régulièrement. Il regarde mes dents et soigne les **caries**. Si une dent fait mal, il ne faut pas attendre : je le dis à mes parents."]),
],
"mots_cles": ["sucre", "fruits", "dentiste", "carie"],
},
{
"n": 10, "titre": "Les parties de l'œil", "theme": "L'œil",
"objectif": "énumérer les différentes parties de l'œil",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": ("svt9e_oeil_parties.png", "Schéma : les parties de l'œil : le sourcil, la paupière, les cils et la pupille."),
"revision": [
    ("Cite deux aliments mauvais pour les dents.", "Les bonbons et le soda."),
    ("Qui soigne les dents ?", "Le dentiste."),
],
"situation": "Rova se regarde dans le miroir et observe ses yeux : il y a des poils au-dessus, d'autres au bord, et un rond noir au milieu. Quelles sont les parties de l'œil ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les parties de l'œil.",
    "Je lis le titre au tableau : Les parties de l'œil.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Observez l'œil de votre voisin : le sourcil, la paupière, les cils, la pupille.",
],
"analyse": [
    ("Quels poils se trouvent au-dessus de l'œil ?", "Au-dessus de l'œil, il y a les poils du sourcil."),
    ("Comment s'appelle la peau qui ferme l'œil ?", "La peau qui ferme l'œil s'appelle la paupière."),
    ("Que voit-on au milieu de l'œil ?", "Au milieu de l'œil, on voit le rond noir appelé pupille."),
],
"synthese": "L'œil a plusieurs parties : le sourcil, la paupière, les cils et la pupille.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le sourcil est au-dessus de l'œil.", "2. La paupière ferme l'œil.", "3. Les cils sont au bord de la paupière.", "4. La pupille est le rond noir au milieu de l'œil."],
     "cor": ["1. **Vrai** : le sourcil est au-dessus.", "2. **Vrai** : la paupière ferme l'œil.", "3. **Vrai** : les cils sont au bord.", "4. **Vrai** : la pupille est le rond noir."]},
    {"c": "Complète avec les mots suivants : sourcil, paupière, cils, pupille.",
     "items": ["1. Au-dessus de l'œil, il y a le ...", "2. La peau qui ferme l'œil est la ...", "3. Les poils du bord sont les ...", "4. Le rond noir du milieu est la ...."],
     "cor": ["1. Au-dessus de l'œil, il y a le **sourcil**.", "2. La peau qui ferme l'œil est la **paupière**.", "3. Les poils du bord sont les **cils**.", "4. Le rond noir du milieu est la **pupille**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que trouve-t-on au-dessus de l'œil ? A. Le sourcil B. La pupille C. Les cils", "2. Comment s'appelle la peau qui ferme l'œil ? A. La joue B. La paupière C. Le front", "3. Où sont les cils ? A. Au bord de la paupière B. Au-dessus du sourcil C. Dans la pupille", "4. Que voit-on au milieu de l'œil ? A. Le sourcil B. La pupille C. La paupière"],
     "cor": ["1. **A. Le sourcil**.", "2. **B. La paupière**.", "3. **A. Au bord de la paupière**.", "4. **B. La pupille**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quelles sont les quatre parties de l'œil apprises ?", "2. Où se trouve le sourcil ?", "3. Où se trouvent les cils ?", "4. Qu'est-ce que la pupille ?"],
     "cor": ["1. Le **sourcil**, la **paupière**, les **cils** et la **pupille**.", "2. Le **sourcil** est **au-dessus de l'œil**.", "3. Les **cils** sont **au bord de la paupière**.", "4. La **pupille** est le **rond noir** au milieu de l'œil."]},
],
"lecon": [
    (None, ["L'**œil** est l'organe de la vue. Autour et au milieu de l'œil, on trouve plusieurs parties."]),
    ("1. Le tour de l'œil", ["Au-dessus de l'œil, il y a le **sourcil**, une ligne de poils. La **paupière** est la peau qui **ferme** l'œil. Au bord de la paupière, il y a les **cils**, de petits poils."]),
    ("2. Le milieu de l'œil", ["Au milieu de l'œil, on voit un **rond noir** : c'est la **pupille**. Autour de la pupille, la partie colorée s'appelle l'**iris**. C'est par la pupille que la lumière entre dans l'œil."]),
],
"mots_cles": ["sourcil", "paupière", "cils", "pupille", "iris"],
},
{
"n": 11, "titre": "Le rôle de l'œil et de ses parties", "theme": "L'œil",
"objectif": "énumérer les rôles de l'œil et de ses différentes parties",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": None,
"revision": [
    ("Quelles sont les parties de l'œil ?", "Le sourcil, la paupière, les cils et la pupille."),
    ("Où se trouve la pupille ?", "La pupille est le rond noir au milieu de l'œil."),
],
"situation": "Les yeux fermés, Nivo essaie d'attraper un crayon : elle n'y arrive pas. Puis un rayon de soleil l'éblouit et elle plisse les paupières. À quoi servent l'œil et ses parties ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre le rôle de l'œil et de ses parties.",
    "Je lis le titre au tableau : Le rôle de l'œil et de ses parties.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Fermez les yeux, puis ouvrez-les : que voyez-vous ?",
],
"analyse": [
    ("À quoi sert l'œil ?", "L'œil sert à voir."),
    ("Que fait la paupière quand la lumière est forte ?", "La paupière se ferme pour protéger l'œil de la lumière forte."),
    ("Que fait la pupille ?", "La pupille laisse entrer la lumière dans l'œil."),
],
"synthese": "L'œil sert à voir. Le sourcil arrête la sueur, la paupière et les cils protègent l'œil, et la pupille laisse entrer la lumière.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'œil sert à voir.", "2. La paupière protège l'œil.", "3. Le sourcil laisse passer la sueur dans l'œil.", "4. La pupille laisse entrer la lumière."],
     "cor": ["1. **Vrai** : l'œil sert à voir.", "2. **Vrai** : elle se ferme pour protéger.", "3. **Faux** : le sourcil arrête la sueur.", "4. **Vrai** : la pupille laisse entrer la lumière."]},
    {"c": "Complète avec les mots suivants : voir, lumière, sueur, poussière.",
     "items": ["1. L'œil sert à ...", "2. Le sourcil arrête la ... du front.", "3. Les cils arrêtent la ...", "4. La pupille laisse entrer la ...."],
     "cor": ["1. L'œil sert à **voir**.", "2. Le sourcil arrête la **sueur** du front.", "3. Les cils arrêtent la **poussière**.", "4. La pupille laisse entrer la **lumière**."]},
],
"evaluation": [
    {"c": "Relie chaque partie à son rôle.",
     "items": ["1. L'œil — a. arrêter la sueur", "2. Le sourcil — b. laisser entrer la lumière", "3. La paupière — c. voir", "4. La pupille — d. fermer et protéger l'œil"],
     "cor": ["1. L'**œil** : **c**. voir.", "2. Le **sourcil** : **a**. arrêter la sueur.", "3. La **paupière** : **d**. fermer et protéger l'œil.", "4. La **pupille** : **b**. laisser entrer la lumière."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quel est le rôle de l'œil ?", "2. Quel est le rôle du sourcil ?", "3. Quel est le rôle des cils ?", "4. Par où la lumière entre-t-elle dans l'œil ?"],
     "cor": ["1. L'**œil** sert à **voir**.", "2. Le **sourcil** **arrête la sueur** du front.", "3. Les **cils** **arrêtent la poussière**.", "4. Par la **pupille**."]},
],
"lecon": [
    (None, ["L'**œil** et ses **parties** travaillent ensemble pour que nous puissions **voir**."]),
    ("1. Voir", ["L'**œil** est l'organe de la **vue**. Grâce à lui, nous voyons les personnes, les objets et les couleurs. La **pupille** laisse entrer la **lumière** dans l'œil."]),
    ("2. Protéger", ["Le **sourcil** **arrête la sueur** du front. La **paupière** se ferme pour **protéger** l'œil de la lumière forte et des chocs. Les **cils** **arrêtent la poussière**."]),
],
"mots_cles": ["voir", "lumière", "protéger", "poussière"],
},
{
"n": 12, "titre": "La protection des yeux", "theme": "L'œil",
"objectif": "connaître les mesures de protection des yeux",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": None,
"revision": [
    ("Quel est le rôle de l'œil ?", "L'œil sert à voir."),
    ("Quel est le rôle des cils ?", "Les cils arrêtent la poussière."),
],
"situation": "Voahangy joue avec un bâton pointu. Sa maîtresse l'arrête : « Attention à tes yeux ! » Comment protéger nos yeux ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à protéger nos yeux.",
    "Je lis le titre au tableau : La protection des yeux.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Mettez la main devant vos yeux, sans les toucher : c'est comme ça qu'on les protège.",
],
"analyse": [
    ("Avec quels objets ne faut-il pas jouer ?", "Il ne faut pas jouer avec les bâtons pointus, les couteaux et les pierres lancées."),
    ("Que faire quand une poussière entre dans l'œil ?", "Il ne faut pas frotter avec les mains sales : on prévient un adulte et on rince l'œil avec de l'eau propre."),
    ("Que ne faut-il jamais regarder ?", "Il ne faut jamais regarder le soleil en face."),
],
"synthese": "Je ne joue pas avec les objets pointus, je ne me frotte pas les yeux avec les mains sales et je ne regarde jamais le soleil.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. On peut jouer avec un bâton pointu.", "2. Il ne faut pas frotter ses yeux avec les mains sales.", "3. On ne regarde jamais le soleil en face.", "4. En cas de poussière dans l'œil, on prévient un adulte."],
     "cor": ["1. **Faux** : c'est dangereux pour les yeux.", "2. **Vrai** : les mains sales portent des microbes.", "3. **Vrai** : le soleil abîme les yeux.", "4. **Vrai** : on prévient un adulte."]},
    {"c": "Complète avec les mots suivants : pointus, soleil, eau, mains.",
     "items": ["1. Je ne joue pas avec les objets ...", "2. Je ne regarde pas le ... en face.", "3. Je ne frotte pas mes yeux avec les ... sales.", "4. Je rince mes yeux avec de l'... propre."],
     "cor": ["1. Je ne joue pas avec les objets **pointus**.", "2. Je ne regarde pas le **soleil** en face.", "3. Avec les **mains** sales.", "4. Avec de l'**eau** propre."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel jeu est dangereux pour les yeux ? A. Le ballon B. Le bâton pointu C. La marelle", "2. Que faire si une poussière entre dans l'œil ? A. Frotter fort B. Prévenir un adulte C. Rien", "3. Que ne faut-il pas regarder ? A. Le tableau B. Le livre C. Le soleil", "4. Avec quoi rince-t-on l'œil ? A. De l'eau propre B. De l'eau sale C. Du savon"],
     "cor": ["1. **B. Le bâton pointu**.", "2. **B. Prévenir un adulte**.", "3. **C. Le soleil**.", "4. **A. De l'eau propre**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite deux objets dangereux pour les yeux.", "2. Pourquoi ne frotte-t-on pas ses yeux avec les mains sales ?", "3. Que fait-on si une poussière entre dans l'œil ?", "4. Pourquoi ne faut-il pas regarder le soleil ?"],
     "cor": ["1. Les **bâtons pointus** et les **couteaux**.", "2. Parce que les **mains sales portent des microbes**.", "3. Je **préviens un adulte** et je **rince l'œil** avec de l'eau propre.", "4. Parce que le **soleil abîme les yeux**."]},
],
"lecon": [
    (None, ["Nos **yeux** sont fragiles : il faut bien les **protéger**."]),
    ("1. Les dangers pour les yeux", ["Je ne joue pas avec les **bâtons pointus**, les **couteaux** et les **pierres lancées**. Je ne regarde jamais le **soleil** en face : sa lumière est trop forte et abîme les yeux."]),
    ("2. Les bons gestes", ["Je ne me **frotte** pas les yeux avec les **mains sales**. Si une **poussière** entre dans l'œil, je **préviens un adulte** et je rince l'œil avec de l'**eau propre**. Si les yeux font mal ou voient flou, il faut aller au **centre de santé**."]),
],
"mots_cles": ["protéger", "soleil", "poussière", "mains sales", "eau propre"],
},
]

REVISION_B2 = {
"titre": "Révision — Bimestre 2",
"tableau": [
    ("La gale", "Maladie de la peau : petits boutons rouges qui grattent, surtout la nuit."),
    ("Les poux", "Petits parasites qui vivent dans les cheveux et piquent la tête."),
    ("L'hygiène de la peau", "Se laver avec eau et savon ; laver les vêtements ; ne pas échanger les habits."),
    ("Les sortes de dents", "Les incisives (devant), les canines (pointues) et les molaires (au fond)."),
    ("Le rôle des dents", "Les incisives coupent, les canines déchirent, les molaires broient."),
    ("Les dents de lait", "Premières dents de l'enfant ; elles tombent vers six ans."),
    ("Les dents définitives", "Elles remplacent les dents de lait et ne repoussent pas."),
    ("La carie", "Trou creusé dans la dent par les microbes."),
    ("Le brossage des dents", "Matin et soir, avec brosse et dentifrice, de haut en bas et de bas en haut."),
    ("Les aliments", "Éviter le sucre et le soda ; croquer des fruits et des légumes."),
    ("Les parties de l'œil", "Le sourcil, la paupière, les cils et la pupille."),
    ("La protection des yeux", "Pas d'objets pointus, pas de soleil en face, ne pas frotter avec les mains sales."),
],
"questions": [
    ("Qu'est-ce que la gale ?", "Une maladie de la peau qui donne des boutons rouges et des démangeaisons."),
    ("Où vivent les poux ?", "Dans les cheveux."),
    ("Comment garder une peau saine ?", "Se laver avec de l'eau propre et du savon, et laver ses vêtements."),
    ("Quelles sont les trois sortes de dents ?", "Les incisives, les canines et les molaires."),
    ("Quel est le rôle des molaires ?", "Les molaires broient les aliments."),
    ("À quel âge tombent les dents de lait ?", "Vers six ans."),
    ("Qu'est-ce qu'une carie ?", "Un trou creusé dans la dent par les microbes."),
    ("Quand faut-il se brosser les dents ?", "Le matin et le soir."),
    ("Quelles sont les parties de l'œil ?", "Le sourcil, la paupière, les cils et la pupille."),
    ("Que faire si une poussière entre dans l'œil ?", "Prévenir un adulte et rincer l'œil avec de l'eau propre."),
],
}

EXAMEN_B2 = {
"titre": "Sujet d'examen 9e — Bimestre 2",
"duree": "30 min",
"total": 20,
"parties": [
    {"c": "Réponds par Vrai (V) ou Faux (F). (4 points)",
     "items": ["1. La gale est causée par un petit parasite.", "2. Les incisives broient les aliments.", "3. La carie est un trou dans la dent.", "4. La pupille laisse entrer la lumière dans l'œil."],
     "cor": ["1. **Vrai** (1 pt) : c'est le sarcopte.", "2. **Faux** (1 pt) : les incisives coupent ; les molaires broient.", "3. **Vrai** (1 pt) : creusée par les microbes.", "4. **Vrai** (1 pt) : la pupille est le rond noir du milieu."]},
    {"c": "Complète avec les mots suivants : poux, canines, dentifrice, sourcil. (4 points)",
     "items": ["1. Les ... vivent dans les cheveux.", "2. Les dents pointues s'appellent les ...", "3. Je me brosse les dents avec du ...", "4. Au-dessus de l'œil, il y a le ...."],
     "cor": ["1. Les **poux** (1 pt).", "2. Les **canines** (1 pt).", "3. Du **dentifrice** (1 pt).", "4. Le **sourcil** (1 pt)."]},
    {"c": "Entoure la bonne réponse. (4 points)",
     "items": ["1. Quelles dents broient les aliments ? A. Les incisives B. Les molaires C. Les canines", "2. Quand se brosse-t-on les dents ? A. Une fois par mois B. Le matin et le soir C. Jamais", "3. Qui soigne les dents malades ? A. Le dentiste B. Le maçon C. Le pêcheur", "4. Que ne faut-il jamais regarder en face ? A. Le tableau B. Le soleil C. Le livre"],
     "cor": ["1. **B. Les molaires** (1 pt).", "2. **B. Le matin et le soir** (1 pt).", "3. **A. Le dentiste** (1 pt).", "4. **B. Le soleil** (1 pt)."]},
    {"c": "Réponds par une phrase complète. (8 points)",
     "items": ["1. Comment la gale se transmet-elle ?", "2. Pourquoi faut-il se brosser les dents ?", "3. Quelles sont les parties de l'œil ?", "4. Cite deux mesures pour protéger ses yeux."],
     "cor": ["1. En touchant un **malade**, en portant ses **habits** ou en dormant dans son **lit** (2 pts).", "2. Pour **enlever les restes d'aliments** et éviter les **caries** (2 pts).", "3. Le **sourcil**, la **paupière**, les **cils** et la **pupille** (2 pts).", "4. Ne pas jouer avec les **objets pointus** et ne pas regarder le **soleil** (2 pts)."]},
],
}
