# -*- coding: utf-8 -*-
"""Contenu Bimestre 5 — Séances 1 à 6 (Blocs 1-2). Manuel SVT 9e J-Learn.
Conventions : **mot** = mot clé (bleu+gras dans la leçon, bordeaux dans les corrigés).
Niveau : 9e (~8 ans), phrases courtes, vocabulaire simple. Aucune date calendaire.
Dernier bimestre du programme officiel : 15 séances (digestif, paludisme, vers,
maladies infantiles, habitat, poule, zébu, arbre, air, eau).
"""

SEANCES_A = [
{
"n": 1, "titre": "Le trajet des aliments", "theme": "L'appareil digestif",
"objectif": "décrire le chemin parcouru par les aliments",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma de l'appareil digestif affiché au tableau",
"image": ("svt9e_appareil_digestif.png", "Schéma : le trajet des aliments : la bouche, l'œsophage, l'estomac et l'intestin."),
"revision": [
    ("Par où l'air entre-t-il ?", "L'air entre par le nez et la bouche."),
    ("Où l'air arrive-t-il ?", "L'air arrive dans les deux poumons."),
],
"situation": "Au repas, Koto avale une bouchée de riz. Elle entre dans sa bouche, puis elle descend... Où va la bouchée de riz dans le corps ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre le chemin des aliments.",
    "Je lis le titre au tableau : Le trajet des aliments.",
],
"observation": [
    "Regardez le schéma de l'appareil digestif affiché au tableau.",
    "Avalez une bouchée de pain ou une gorgée d'eau : par où passe-t-elle ?",
],
"analyse": [
    ("Où les aliments entrent-ils ?", "Les aliments entrent par la bouche."),
    ("Par quel tuyau la bouchée descend-elle ?", "La bouchée descend par un tuyau appelé œsophage."),
    ("Où la bouchée arrive-t-elle ensuite ?", "Elle arrive dans l'estomac, puis dans l'intestin."),
],
"synthese": "Les aliments entrent par la bouche, descendent par l'œsophage, arrivent dans l'estomac puis dans l'intestin.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les aliments entrent par la bouche.", "2. L'œsophage est un tuyau.", "3. L'estomac est dans la tête.", "4. L'intestin reçoit les aliments après l'estomac."],
     "cor": ["1. **Vrai** : les aliments entrent par la bouche.", "2. **Vrai** : c'est le tuyau des aliments.", "3. **Faux** : l'estomac est dans le ventre.", "4. **Vrai** : après l'estomac, c'est l'intestin."]},
    {"c": "Complète avec les mots suivants : bouche, œsophage, estomac, intestin.",
     "items": ["1. Les aliments entrent par la ...", "2. Ils descendent par l'...", "3. Ils arrivent dans l'...", "4. Puis ils passent dans l'..."],
     "cor": ["1. Par la **bouche**.", "2. Par l'**œsophage**.", "3. Dans l'**estomac**.", "4. Dans l'**intestin**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Où les aliments entrent-ils ? A. Par le nez B. Par la bouche C. Par l'oreille", "2. Quel est le tuyau des aliments ? A. L'œsophage B. Le bras C. La jambe", "3. Où arrive la bouchée après l'œsophage ? A. Dans la tête B. Dans l'estomac C. Dans le pied", "4. Quel est l'ordre du trajet ? A. Estomac, bouche, intestin B. Bouche, œsophage, estomac, intestin C. Intestin, bouche, estomac"],
     "cor": ["1. **B. Par la bouche**.", "2. **A. L'œsophage**.", "3. **B. Dans l'estomac**.", "4. **B. Bouche, œsophage, estomac, intestin**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Par où les aliments entrent-ils ?", "2. Qu'est-ce que l'œsophage ?", "3. Où la bouchée arrive-t-elle après l'estomac ?", "4. Décris le trajet des aliments."],
     "cor": ["1. Par la **bouche**.", "2. L'**œsophage** est le **tuyau** qui conduit les aliments.", "3. Dans l'**intestin**.", "4. **Bouche**, **œsophage**, **estomac**, **intestin**."]},
],
"lecon": [
    (None, ["Ce que nous mangeons suit un **trajet** dans notre corps : c'est le travail de l'**appareil digestif**."]),
    ("1. Le début du trajet", ["Les **aliments** entrent par la **bouche**. Les dents les coupent, puis la bouchée descend par l'**œsophage**, un tuyau qui va vers le ventre."]),
    ("2. La fin du trajet", ["La bouchée arrive dans l'**estomac**, une poche dans le ventre. Puis elle passe dans l'**intestin**, un long tuyau plié. Les restes que le corps ne garde pas sortent par le bas."]),
],
"mots_cles": ["bouche", "œsophage", "estomac", "intestin", "trajet"],
},
{
"n": 2, "titre": "Le rôle des organes de la digestion", "theme": "L'appareil digestif",
"objectif": "mentionner le rôle de chaque organe de l'appareil digestif",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma de l'appareil digestif affiché au tableau",
"image": None,
"revision": [
    ("Par où les aliments entrent-ils ?", "Les aliments entrent par la bouche."),
    ("Où la bouchée arrive-t-elle après l'estomac ?", "Dans l'intestin."),
],
"situation": "Après le repas, Aina se demande : « Que devient le riz que j'ai mangé ? » Chaque organe de la digestion fait un travail. Quel est le travail de chacun ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre le rôle des organes de la digestion.",
    "Je lis le titre au tableau : Le rôle des organes de la digestion.",
],
"observation": [
    "Regardez le schéma de l'appareil digestif affiché au tableau.",
    "Mâchez lentement une petite bouchée : que fait votre bouche ?",
],
"analyse": [
    ("Que fait la bouche ?", "La bouche coupe et écrase les aliments, et la salive les ramollit."),
    ("Que fait l'estomac ?", "L'estomac brasse les aliments et les transforme en bouillie."),
    ("Que fait l'intestin ?", "L'intestin fait passer les éléments utiles dans le sang."),
],
"synthese": "La bouche écrase les aliments, l'estomac les brasse en bouillie, et l'intestin fait passer les éléments utiles dans le sang.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La bouche écrase les aliments.", "2. La salive ramollit les aliments.", "3. L'estomac brasse les aliments.", "4. L'intestin ne sert à rien."],
     "cor": ["1. **Vrai** : les dents écrasent.", "2. **Vrai** : la salive ramollit.", "3. **Vrai** : il transforme en bouillie.", "4. **Faux** : il fait passer les éléments utiles dans le sang."]},
    {"c": "Complète avec les mots suivants : salive, bouillie, sang, intestin.",
     "items": ["1. La ... ramollit les aliments dans la bouche.", "2. L'estomac transforme les aliments en ...", "3. Les éléments utiles passent dans le ...", "4. C'est l'... qui les fait passer."],
     "cor": ["1. La **salive** ramollit.", "2. En **bouillie**.", "3. Dans le **sang**.", "4. C'est l'**intestin**."]},
],
"evaluation": [
    {"c": "Relie chaque organe à son rôle.",
     "items": ["1. La bouche — a. brasser en bouillie", "2. L'œsophage — b. faire passer les éléments utiles", "3. L'estomac — c. écraser les aliments", "4. L'intestin — d. conduire les aliments"],
     "cor": ["1. La **bouche** : **c**. écraser les aliments.", "2. L'**œsophage** : **d**. conduire les aliments.", "3. L'**estomac** : **a**. brasser en bouillie.", "4. L'**intestin** : **b**. faire passer les éléments utiles."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que fait la bouche ?", "2. Que fait l'estomac ?", "3. Que fait l'intestin ?", "4. Où vont les éléments utiles des aliments ?"],
     "cor": ["1. La **bouche** **écrase** les aliments et la salive les ramollit.", "2. L'**estomac** **brasse** les aliments en **bouillie**.", "3. L'**intestin** fait passer les éléments utiles dans le sang.", "4. Dans le **sang**, qui nourrit tout le corps."]},
],
"lecon": [
    (None, ["Chaque **organe** de l'appareil digestif a son **rôle** pour transformer les aliments."]),
    ("1. La bouche et l'estomac", ["Dans la **bouche**, les dents **coupent** et **écrasent** les aliments ; la **salive** les ramollit. L'**œsophage** conduit la bouchée vers l'**estomac**, qui **brasse** les aliments et les transforme en **bouillie**."]),
    ("2. L'intestin", ["La bouillie arrive dans l'**intestin**. L'intestin fait passer les **éléments utiles** dans le **sang** : c'est ce qui nourrit notre corps et le fait grandir."]),
],
"mots_cles": ["salive", "brasser", "bouillie", "sang", "intestin"],
},
{
"n": 3, "titre": "L'hygiène alimentaire", "theme": "L'appareil digestif",
"objectif": "respecter l'hygiène alimentaire",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "un fruit propre et un fruit sale apportés en classe",
"image": None,
"revision": [
    ("Que fait l'estomac ?", "L'estomac brasse les aliments en bouillie."),
    ("Où vont les éléments utiles ?", "Dans le sang, qui nourrit le corps."),
],
"situation": "Fara mange une mangue sans la laver. Le soir, elle a mal au ventre. Sa maman lui dit : « Il faut toujours laver les fruits ! » Pourquoi faut-il faire attention à ce que l'on mange ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'hygiène alimentaire.",
    "Je lis le titre au tableau : L'hygiène alimentaire.",
],
"observation": [
    "Observez ce fruit propre et ce fruit sale.",
    "Lequel peut-on manger sans danger ?",
],
"analyse": [
    ("Que faut-il faire avant de manger ?", "Il faut se laver les mains avec de l'eau et du savon."),
    ("Que fait-on aux fruits avant de les manger ?", "On lave les fruits et les légumes avec de l'eau propre."),
    ("Pourquoi couvre-t-on les aliments ?", "On couvre les aliments pour que les mouches et la poussière ne les salissent pas."),
],
"synthese": "Je me lave les mains, je lave les fruits, je couvre les aliments et je bois de l'eau propre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut se laver les mains avant de manger.", "2. On lave les fruits avant de les manger.", "3. On peut laisser les aliments découverts.", "4. Les aliments sales donnent mal au ventre."],
     "cor": ["1. **Vrai** : mains propres avant de manger.", "2. **Vrai** : à l'eau propre.", "3. **Faux** : il faut les couvrir.", "4. **Vrai** : ils transportent des microbes."]},
    {"c": "Complète avec les mots suivants : mains, fruits, couvrir, eau.",
     "items": ["1. Je me lave les ... avant de manger.", "2. Je lave les ... et les légumes.", "3. Je fais ... les aliments.", "4. Je bois de l'... propre."],
     "cor": ["1. Les **mains**.", "2. Les **fruits** et les légumes.", "3. **Couvrir** les aliments.", "4. De l'**eau** propre."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que fait-on avant de manger ? A. Rien B. Se laver les mains C. Courir", "2. Avec quoi lave-t-on les fruits ? A. De l'eau propre B. De l'eau sale C. Du sable", "3. Pourquoi couvre-t-on les aliments ? A. Pour les cacher B. Pour les protéger des mouches C. Pour les réchauffer", "4. Quelle eau boit-on ? A. L'eau de la rivière B. L'eau potable C. L'eau sale"],
     "cor": ["1. **B. Se laver les mains**.", "2. **A. De l'eau propre**.", "3. **B. Pour les protéger des mouches**.", "4. **B. L'eau potable**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faut-il faire avant de manger ?", "2. Pourquoi lave-t-on les fruits ?", "3. Pourquoi couvre-t-on les aliments ?", "4. Cite deux règles d'hygiène alimentaire."],
     "cor": ["1. **Se laver les mains** avec de l'eau et du savon.", "2. Pour **enlever les microbes** et la saleté.", "3. Pour que les **mouches** et la **poussière** ne les salissent pas.", "4. **Laver les fruits** et **boire de l'eau potable**."]},
],
"lecon": [
    (None, ["Une bonne **hygiène alimentaire** protège notre ventre et notre santé."]),
    ("1. Avant de manger", ["Je me **lave les mains** avec de l'**eau** et du **savon**. Je **lave les fruits** et les légumes avec de l'eau propre. Je mange dans des assiettes propres."]),
    ("2. Protéger les aliments", ["Je **couvre les aliments** : les **mouches** et la **poussière** ne doivent pas les salir. Je bois de l'**eau potable**. Un aliment sale transporte des **microbes** qui donnent mal au ventre."]),
],
"mots_cles": ["hygiène", "mains", "fruits", "couvrir", "eau potable"],
},
{
"n": 4, "titre": "Le paludisme : une maladie grave", "theme": "Le paludisme",
"objectif": "reconnaître les symptômes du paludisme",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma du cycle du paludisme affiché au tableau",
"image": ("paludisme_cycle.png", "Schéma : le cycle du paludisme : l'anophèle pique l'homme et transmet le parasite."),
"revision": [
    ("Que faut-il faire avant de manger ?", "Se laver les mains avec de l'eau et du savon."),
    ("Pourquoi couvre-t-on les aliments ?", "Pour les protéger des mouches et de la poussière."),
],
"situation": "Hery a très chaud, puis il tremble de froid. Il a mal à la tête. Sa maman le conduit vite au centre de santé : c'est le paludisme. Qu'est-ce que le paludisme ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à reconnaître le paludisme.",
    "Je lis le titre au tableau : Le paludisme : une maladie grave.",
],
"observation": [
    "Regardez le schéma du cycle du paludisme affiché au tableau.",
    "Avez-vous déjà vu un moustique piquer quelqu'un la nuit ?",
],
"analyse": [
    ("Quels sont les symptômes du paludisme ?", "Les symptômes sont la fièvre, les frissons, les maux de tête et les courbatures."),
    ("Qui transmet le paludisme ?", "C'est le moustique appelé anophèle qui transmet le paludisme."),
    ("Que fait le moustique quand il pique ?", "En piquant, le moustique fait entrer un parasite dans le sang."),
],
"synthese": "Le paludisme donne la fièvre, les frissons et les maux de tête. Il est transmis par la piqûre du moustique anophèle.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le paludisme donne la fièvre.", "2. Le paludisme est transmis par une mouche.", "3. L'anophèle est un moustique.", "4. Le paludisme est une maladie grave."],
     "cor": ["1. **Vrai** : la fièvre monte.", "2. **Faux** : c'est le moustique anophèle.", "3. **Vrai** : c'est le moustique du paludisme.", "4. **Vrai** : il faut le soigner vite."]},
    {"c": "Complète avec les mots suivants : fièvre, anophèle, frissons, sang.",
     "items": ["1. Le paludisme donne la ...", "2. Le malade a des ...", "3. Le moustique s'appelle l'...", "4. Le parasite entre dans le ..."],
     "cor": ["1. La **fièvre**.", "2. Des **frissons**.", "3. L'**anophèle**.", "4. Dans le **sang**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quels sont les symptômes du paludisme ? A. Fièvre et frissons B. Mal aux dents C. Mal au pied", "2. Qui transmet le paludisme ? A. La mouche B. L'anophèle C. L'abeille", "3. Que transmet l'anophèle en piquant ? A. Un parasite B. Une plante C. Un os", "4. Quand pique l'anophèle ? A. Le midi B. La nuit C. Le matin seulement"],
     "cor": ["1. **A. Fièvre et frissons**.", "2. **B. L'anophèle**.", "3. **A. Un parasite**.", "4. **B. La nuit** : c'est un moustique de nuit."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quels sont les symptômes du paludisme ?", "2. Qui transmet le paludisme ?", "3. Que fait le moustique quand il pique ?", "4. Que faire si on a la fièvre et des frissons ?"],
     "cor": ["1. La **fièvre**, les **frissons**, les **maux de tête** et les **courbatures**.", "2. Le moustique **anophèle**.", "3. Il fait entrer un **parasite** dans le **sang**.", "4. Aller **vite au centre de santé**."]},
],
"lecon": [
    (None, ["Le **paludisme** est une **maladie grave**, très fréquente à Madagascar. Il faut savoir la reconnaître."]),
    ("1. Les symptômes", ["Le paludisme donne une **fièvre** forte, des **frissons** (on tremble de froid), des **maux de tête** et des **courbatures**. Le malade se sent très fatigué."]),
    ("2. Le moustique anophèle", ["Le paludisme est transmis par la **piqûre** du moustique **anophèle**, qui pique surtout la **nuit**. En piquant, il fait entrer un **parasite** dans le **sang** du malade."]),
],
"mots_cles": ["paludisme", "fièvre", "frissons", "anophèle", "parasite"],
},
{
"n": 5, "titre": "La transmission et la prévention du paludisme", "theme": "Le paludisme",
"objectif": "prendre toutes les dispositions pour éviter la propagation du paludisme",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma du cycle du paludisme affiché au tableau",
"image": None,
"revision": [
    ("Quels sont les symptômes du paludisme ?", "La fièvre, les frissons, les maux de tête et les courbatures."),
    ("Qui transmet le paludisme ?", "Le moustique anophèle."),
],
"situation": "Près de la maison de Soa, un vieux pneu rempli d'eau et une flaque attirent les moustiques. Le soir, elle dort sans moustiquaire. Que faut-il changer pour éviter le paludisme ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à éviter la propagation du paludisme.",
    "Je lis le titre au tableau : La transmission et la prévention du paludisme.",
],
"observation": [
    "Regardez le schéma du cycle du paludisme affiché au tableau.",
    "Cherchez dans la cour de l'école : y a-t-il des eaux stagnantes ?",
],
"analyse": [
    ("Où l'anophèle pond-il ses œufs ?", "Il pond dans les eaux stagnantes : flaques, vieux pneus et boîtes remplies d'eau."),
    ("Comment éviter les piqûres la nuit ?", "On dort sous une moustiquaire, de préférence imprégnée."),
    ("Que faut-il faire des eaux stagnantes ?", "Il faut vider ou recouvrir les eaux stagnantes."),
],
"synthese": "Je dors sous une moustiquaire, je vide les eaux stagnantes et je garde la cour propre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'anophèle pond dans les eaux stagnantes.", "2. La moustiquaire protège la nuit.", "3. Les eaux stagnantes attirent les moustiques.", "4. Une cour sale n'attire pas les moustiques."],
     "cor": ["1. **Vrai** : flaques et vieux pneus.", "2. **Vrai** : elle empêche les piqûres.", "3. **Vrai** : les moustiques y pondent.", "4. **Faux** : il faut garder la cour propre."]},
    {"c": "Complète avec les mots suivants : moustiquaire, stagnantes, vider, cour.",
     "items": ["1. Je dors sous une ...", "2. Le moustique pond dans les eaux ...", "3. Je fais ... les flaques et les vieux pneus.", "4. Je garde la ... propre."],
     "cor": ["1. Sous une **moustiquaire**.", "2. Les eaux **stagnantes**.", "3. **Vider** les flaques.", "4. La **cour** propre."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Où l'anophèle pond-il ? A. Dans le sable B. Dans les eaux stagnantes C. Sur les feuilles", "2. Comment dormir pour éviter les piqûres ? A. Sous une moustiquaire B. Dehors C. Près de l'eau", "3. Que faire d'un vieux pneu rempli d'eau ? A. Le laisser B. Le vider C. Le remplir encore", "4. Quand l'anophèle pique-t-il ? A. La nuit B. Le midi C. Jamais"],
     "cor": ["1. **B. Dans les eaux stagnantes**.", "2. **A. Sous une moustiquaire**.", "3. **B. Le vider**.", "4. **A. La nuit**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Où le moustique anophèle pond-il ?", "2. Comment se protéger des piqûres la nuit ?", "3. Que faire des eaux stagnantes ?", "4. Cite deux mesures pour éviter le paludisme."],
     "cor": ["1. Dans les **eaux stagnantes**.", "2. En dormant sous une **moustiquaire imprégnée**.", "3. Les **vider** ou les **recouvrir**.", "4. **Dormir sous une moustiquaire** et **assainir les eaux stagnantes**."]},
],
"lecon": [
    (None, ["Pour éviter le **paludisme**, il faut empêcher l'**anophèle** de piquer et de pondre."]),
    ("1. Les gîtes du moustique", ["L'**anophèle** pond dans les **eaux stagnantes** : flaques, vieux pneus, boîtes remplies d'eau. Je **vide** ou je **recouvre** ces eaux, et je garde la **cour propre**."]),
    ("2. Se protéger la nuit", ["L'anophèle pique la **nuit** : je dors sous une **moustiquaire imprégnée**, et je rentre avant la tombée de la nuit. Toute la famille protège ainsi sa santé."]),
],
"mots_cles": ["moustiquaire", "eaux stagnantes", "assainir", "prévention"],
},
{
"n": 6, "titre": "Le traitement du paludisme", "theme": "Le paludisme",
"objectif": "faire traiter efficacement le paludisme",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma du cycle du paludisme affiché au tableau",
"image": None,
"revision": [
    ("Où l'anophèle pond-il ?", "Dans les eaux stagnantes."),
    ("Comment éviter les piqûres la nuit ?", "En dormant sous une moustiquaire imprégnée."),
],
"situation": "Nivo a la fièvre et des frissons. Son papa veut acheter des médicaments au marché. Sa maman dit : « Allons d'abord au centre de santé ! » Pourquoi faut-il aller au centre de santé ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment soigner le paludisme.",
    "Je lis le titre au tableau : Le traitement du paludisme.",
],
"observation": [
    "Regardez le schéma du cycle du paludisme affiché au tableau.",
    "Racontez : que fait votre famille quand quelqu'un a la fièvre ?",
],
"analyse": [
    ("Que faut-il faire dès les premiers signes ?", "Il faut aller vite au centre de santé, sans attendre."),
    ("Comment sait-on que c'est le paludisme ?", "L'agent de santé fait un test avec une petite goutte de sang."),
    ("Comment prend-on les médicaments ?", "On prend les médicaments comme l'a dit l'agent de santé, jusqu'au bout."),
],
"synthese": "Dès la fièvre, je vais vite au centre de santé : test, puis médicaments pris jusqu'au bout.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut aller vite au centre de santé.", "2. Le test du paludisme se fait avec une goutte de sang.", "3. On arrête les médicaments quand on se sent mieux.", "4. Les médicaments du marché guérissent toujours."],
     "cor": ["1. **Vrai** : sans attendre.", "2. **Vrai** : une petite goutte de sang.", "3. **Faux** : on les prend jusqu'au bout.", "4. **Faux** : il faut le conseil de l'agent de santé."]},
    {"c": "Complète avec les mots suivants : centre de santé, test, médicaments, bout.",
     "items": ["1. Je vais vite au ...", "2. L'agent de santé fait un ...", "3. Je prends les ...", "4. Je les prends jusqu'au ..."],
     "cor": ["1. Au **centre de santé**.", "2. Un **test**.", "3. Les **médicaments**.", "4. Jusqu'au **bout**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que faire dès les premiers signes ? A. Attendre B. Aller au centre de santé C. Jouer", "2. Avec quoi fait-on le test ? A. Une goutte de sang B. De la salive C. Un cheveu", "3. Comment prendre les médicaments ? A. Jusqu'au bout B. Un jour seulement C. Jamais", "4. Le paludisme non soigné est-il dangereux ? A. Non B. Oui C. Parfois"],
     "cor": ["1. **B. Aller au centre de santé**.", "2. **A. Une goutte de sang**.", "3. **A. Jusqu'au bout**.", "4. **B. Oui** : il peut être mortel."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faut-il faire dès les premiers signes du paludisme ?", "2. Comment sait-on que c'est le paludisme ?", "3. Comment prend-on les médicaments ?", "4. Pourquoi ne faut-il pas attendre pour se soigner ?"],
     "cor": ["1. Aller **vite au centre de santé**.", "2. L'**agent de santé** fait un **test** avec une goutte de sang.", "3. **Comme l'agent l'a dit**, **jusqu'au bout**.", "4. Parce que le paludisme non soigné est **très dangereux**."]},
],
"lecon": [
    (None, ["Le **paludisme** se soigne bien si on va **vite** au **centre de santé**. Il ne faut jamais attendre."]),
    ("1. Le test", ["Devant la **fièvre**, on va au **centre de santé**. L'**agent de santé** fait un **test** avec une petite **goutte de sang** pour savoir si c'est le paludisme."]),
    ("2. Le traitement", ["Si c'est le paludisme, l'agent donne des **médicaments**. On les prend **comme il l'a dit**, **jusqu'au bout**, même si on se sent mieux. Un paludisme mal soigné peut être mortel."]),
],
"mots_cles": ["centre de santé", "test", "médicaments", "traitement"],
},
]
