# -*- coding: utf-8 -*-
"""Contenu Bimestre 2 — Séances 1 à 6 (Blocs 1-2). Manuel SVT 9e J-Learn.
Conventions : **mot** = mot clé (bleu+gras dans la leçon, bordeaux dans les corrigés).
Niveau : 9e (~8 ans), phrases courtes, vocabulaire simple. Aucune date calendaire.
"""

SEANCES_A = [
{
"n": 1, "titre": "La gale, une maladie de la peau", "theme": "Les maladies de la peau",
"objectif": "connaître les parasites de la peau",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "l'image de l'enfant qui se gratte le bras, affichée au tableau",
"image": ("svt9e_gale.png", "Image : Aina se gratte le bras, car sa peau la démange."),
"revision": [
    ("Quelles sont les trois couches de la peau ?", "Les trois couches sont l'épiderme, le derme et l'hypoderme."),
    ("À quoi sert la sueur ?", "La sueur refroidit le corps quand il fait chaud."),
],
"situation": "Depuis trois jours, Aina se gratte tout le temps. Sa peau la démange, surtout la nuit. Sa maman regarde son bras : il y a des petits boutons rouges. Qu'est-ce qui gratte comme ça ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre une maladie de la peau : la gale.",
    "Je lis le titre au tableau : La gale, une maladie de la peau.",
],
"observation": [
    "Regardez l'image de l'enfant qui se gratte le bras.",
    "Observez la peau de vos mains : est-elle lisse ou pleine de boutons ?",
],
"analyse": [
    ("Quels sont les signes de la gale ?", "Les signes de la gale sont des petits boutons rouges et des démangeaisons, surtout la nuit."),
    ("Qu'est-ce qui provoque la gale ?", "La gale est provoquée par un tout petit parasite appelé sarcopte, invisible à l'œil."),
    ("Comment la gale se transmet-elle ?", "La gale se transmet en touchant un malade, ou en portant ses habits et en dormant dans son lit."),
],
"synthese": "La gale est une maladie de la peau causée par un petit parasite invisible. Elle donne des boutons rouges qui grattent beaucoup, surtout la nuit.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La gale est une maladie de la peau.", "2. La gale est causée par un gros animal.", "3. La gale fait des boutons rouges.", "4. La gale ne gratte pas."],
     "cor": ["1. **Vrai** : la gale est une maladie de la peau.", "2. **Faux** : elle est causée par un petit parasite invisible.", "3. **Vrai** : elle fait des boutons rouges.", "4. **Faux** : la gale gratte beaucoup, surtout la nuit."]},
    {"c": "Complète avec les mots suivants : gale, boutons, nuit, parasite.",
     "items": ["1. La ... est une maladie de la peau.", "2. Elle donne des petits ... rouges.", "3. Les démangeaisons sont fortes la ...", "4. Elle est causée par un petit ...."],
     "cor": ["1. La **gale** est une maladie de la peau.", "2. Elle donne des **boutons** rouges.", "3. Les démangeaisons sont fortes la **nuit**.", "4. Elle est causée par un petit **parasite**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. La gale est causée par quoi ? A. Un microbe de l'air B. Un petit parasite de la peau C. Le froid", "2. Quel est le signe de la gale ? A. La fièvre B. Des boutons qui grattent C. Des maux de tête", "3. Quand la gale gratte-t-elle le plus ? A. Le matin B. À midi C. La nuit", "4. Comment la gale se transmet-elle ? A. En touchant un malade B. En buvant de l'eau C. En courant vite"],
     "cor": ["1. **B. Un petit parasite de la peau** : le sarcopte.", "2. **B. Des boutons qui grattent**.", "3. **C. La nuit**.", "4. **A. En touchant un malade**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce que la gale ?", "2. Quels sont les signes de la gale ?", "3. Comment s'appelle le parasite de la gale ?", "4. Que faut-il faire quand on se gratte beaucoup ?"],
     "cor": ["1. La **gale** est une **maladie de la peau**.", "2. Les signes sont des **boutons rouges** et des **démangeaisons**.", "3. Le parasite s'appelle le **sarcopte**.", "4. Il faut **le dire aux parents** et **aller au centre de santé**."]},
],
"lecon": [
    (None, ["La **gale** est une **maladie de la peau**. Elle est causée par un tout petit **parasite** qui creuse la peau."]),
    ("1. Les signes de la gale", ["La gale donne des petits **boutons** rouges sur la peau, surtout entre les doigts et sur les bras. La peau **démange** beaucoup, surtout la **nuit**."]),
    ("2. Comment la gale se transmet", ["La gale se transmet en touchant un **malade**, en portant ses **habits** ou en dormant dans son **lit**. Pour guérir, il faut aller au **centre de santé** et laver les habits avec de l'eau chaude."]),
],
"mots_cles": ["gale", "maladie", "parasite", "boutons", "démangeaisons"],
},
{
"n": 2, "titre": "Les poux, des parasites de la tête", "theme": "Les maladies de la peau",
"objectif": "connaître les poux et leurs effets",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "un peigne fin apporté en classe",
"image": None,
"revision": [
    ("Qu'est-ce que la gale ?", "La gale est une maladie de la peau causée par un petit parasite."),
    ("Quels sont les signes de la gale ?", "Des boutons rouges et des démangeaisons, surtout la nuit."),
],
"situation": "Soa se gratte la tête depuis ce matin. La maîtresse écarte ses cheveux : de petites bêtes blanches marchent dessus ! Quelles sont ces petites bêtes ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à connaître les poux.",
    "Je lis le titre au tableau : Les poux, des parasites de la tête.",
],
"observation": [
    "Observez ce peigne fin : il sert à chercher les poux.",
    "Regardez les cheveux de votre voisin : y a-t-il des petites bêtes blanches ?",
],
"analyse": [
    ("Où vivent les poux ?", "Les poux vivent dans les cheveux, sur la tête."),
    ("Que font les poux sur la tête ?", "Les poux piquent la peau de la tête pour boire le sang, et ça gratte."),
    ("Comment éviter les poux ?", "Pour éviter les poux, il ne faut pas échanger son peigne, ni son bonnet, et il faut se peigner souvent."),
],
"synthese": "Les poux sont de petits parasites qui vivent dans les cheveux. Ils piquent la tête pour boire le sang et la tête gratte.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les poux vivent dans les cheveux.", "2. Les poux volent comme des mouches.", "3. Les poux piquent la tête.", "4. On peut échanger son peigne sans danger."],
     "cor": ["1. **Vrai** : les poux vivent dans les cheveux.", "2. **Faux** : les poux ne volent pas, ils marchent.", "3. **Vrai** : ils piquent pour boire le sang.", "4. **Faux** : il ne faut pas échanger son peigne."]},
    {"c": "Complète avec les mots suivants : poux, cheveux, peigne, sang.",
     "items": ["1. Les ... sont de petites bêtes blanches.", "2. Ils vivent dans les ...", "3. Pour les chercher, on utilise un ... fin.", "4. Ils piquent la tête pour boire le ...."],
     "cor": ["1. Les **poux** sont de petites bêtes blanches.", "2. Ils vivent dans les **cheveux**.", "3. On utilise un **peigne** fin.", "4. Ils boivent le **sang**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Où vivent les poux ? A. Sur les pieds B. Dans les cheveux C. Dans le ventre", "2. Que font les poux sur la tête ? A. Ils chantent B. Ils piquent et boivent le sang C. Ils dorment seulement", "3. Que ressent-on quand on a des poux ? A. La tête gratte B. La tête grossit C. Rien du tout", "4. Que faut-il faire si on a des poux ? A. Rien B. Se laver la tête et prévenir les parents C. Se cacher"],
     "cor": ["1. **B. Dans les cheveux**.", "2. **B. Ils piquent et boivent le sang**.", "3. **A. La tête gratte**.", "4. **B. Se laver la tête et prévenir les parents**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que sont les poux ?", "2. Où vivent les poux ?", "3. Pourquoi la tête gratte-t-elle ?", "4. Cite deux moyens d'éviter les poux."],
     "cor": ["1. Les **poux** sont de petits **parasites** de la tête.", "2. Ils vivent dans les **cheveux**.", "3. La tête gratte parce que les poux **piquent la peau**.", "4. Ne pas échanger son **peigne** ni son **bonnet** et se peigner souvent."]},
],
"lecon": [
    (None, ["Les **poux** sont de petits **parasites** qui vivent dans les **cheveux**, surtout derrière les oreilles et sur la nuque."]),
    ("1. Ce que font les poux", ["Les **poux** piquent la peau de la tête pour boire le **sang**. La tête **démange** alors beaucoup. Les poux pondent des œufs appelés **lentes**."]),
    ("2. Se protéger des poux", ["Pour éviter les poux, je ne **prête** pas mon **peigne**, ni mon **bonnet**, ni ma serviette. Je me lave les cheveux avec de l'eau propre et du savon, et je me **peigne** souvent avec un peigne fin."]),
],
"mots_cles": ["poux", "parasite", "cheveux", "peigne", "lentes"],
},
{
"n": 3, "titre": "L'hygiène de la peau", "theme": "Les maladies de la peau",
"objectif": "connaître l'hygiène de la peau pour éviter les maladies",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "un savon et une serviette propre apportés en classe",
"image": None,
"revision": [
    ("Où vivent les poux ?", "Les poux vivent dans les cheveux."),
    ("Comment éviter les poux ?", "Ne pas échanger son peigne ni son bonnet, et se peigner souvent."),
],
"situation": "Hery rentre de l'école tout sale : ses jambes sont couvertes de poussière. Sa grande sœur lui dit : « Va te laver ! Une peau sale attire les maladies. » Pourquoi faut-il garder sa peau propre ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'hygiène de la peau.",
    "Je lis le titre au tableau : L'hygiène de la peau.",
],
"observation": [
    "Regardez ce savon et cette serviette propre.",
    "Montrez vos mains et vos jambes : sont-elles propres ?",
],
"analyse": [
    ("Pourquoi faut-il laver sa peau ?", "Il faut laver sa peau pour enlever la saleté, la sueur et les microbes."),
    ("Avec quoi lave-t-on sa peau ?", "On lave sa peau avec de l'eau propre et du savon."),
    ("Pourquoi ne faut-il pas partager les habits d'un malade ?", "Parce que les habits d'un malade portent les parasites et les microbes."),
],
"synthese": "Pour garder une peau saine, je me lave avec de l'eau propre et du savon. Je lave mes vêtements et je ne partage pas les habits d'un malade.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut laver sa peau avec du savon.", "2. Une peau sale attire les microbes.", "3. On peut porter les habits d'un malade.", "4. Il faut laver ses vêtements souvent."],
     "cor": ["1. **Vrai** : on lave sa peau avec de l'eau et du savon.", "2. **Vrai** : une peau sale attire les microbes.", "3. **Faux** : il ne faut pas porter les habits d'un malade.", "4. **Vrai** : il faut laver ses vêtements souvent."]},
    {"c": "Complète avec les mots suivants : savon, eau, vêtements, microbes.",
     "items": ["1. Je me lave avec de l'... propre et du ...", "2. La peau sale attire les ...", "3. Je lave mes ... souvent.", "4. Les habits d'un malade portent des ...."],
     "cor": ["1. De l'**eau** propre et du **savon**.", "2. La peau sale attire les **microbes**.", "3. Je lave mes **vêtements** souvent.", "4. Les habits d'un malade portent des **microbes**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Pourquoi laver sa peau ? A. Pour enlever les microbes B. Pour être mouillé C. Pour s'amuser", "2. Avec quoi ? A. De l'eau sale B. De l'eau propre et du savon C. Du sable", "3. Quand faut-il se laver ? A. Une fois par an B. Tous les jours C. Jamais", "4. Que faire des habits d'un malade ? A. Les porter B. Les laver à part C. Les donner à un ami"],
     "cor": ["1. **A. Pour enlever les microbes**.", "2. **B. De l'eau propre et du savon**.", "3. **B. Tous les jours**.", "4. **B. Les laver à part**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Pourquoi faut-il garder sa peau propre ?", "2. Avec quoi lave-t-on sa peau ?", "3. Pourquoi lave-t-on ses vêtements ?", "4. Que faire si un camarade a la gale ?"],
     "cor": ["1. Pour **enlever les microbes** qui rendent malade.", "2. Avec de l'**eau propre** et du **savon**.", "3. Pour **enlever les microbes** et rester en bonne santé.", "4. Il faut **ne pas toucher ses boutons** et **prévenir un adulte**."]},
],
"lecon": [
    (None, ["Une **peau** propre est une peau en bonne **santé**. L'**hygiène** de la peau évite les maladies."]),
    ("1. Se laver la peau", ["Je me lave tout le corps tous les jours avec de l'**eau propre** et du **savon**. J'essuie ma peau avec une **serviette** propre. Je lave mes **vêtements** souvent et je ne les échange pas."]),
    ("2. Éviter la contagion", ["Les maladies comme la **gale** et les **poux** se transmettent par les habits et la literie. Je ne porte pas les **habits** d'un malade et je ne dors pas dans son **lit**. Un enfant qui se gratte beaucoup doit aller au **centre de santé**."]),
],
"mots_cles": ["hygiène", "savon", "serviette", "vêtements", "contagion"],
},
{
"n": 4, "titre": "Les différentes sortes de dents", "theme": "Les dents",
"objectif": "reconnaître les différentes sortes de dents",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "le schéma des dents affiché au tableau",
"image": ("svt9e_dents.png", "Schéma : les différentes sortes de dents : les incisives, les canines et les molaires."),
"revision": [
    ("Pourquoi faut-il laver sa peau ?", "Pour enlever la saleté, la sueur et les microbes."),
    ("Comment éviter la contagion des maladies de la peau ?", "Ne pas échanger les habits, le peigne ni la literie d'un malade."),
],
"situation": "En mangeant, Koto croque le pain avec ses dents de devant, puis il mâche avec ses dents du fond. Toutes les dents se ressemblent-elles ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les différentes sortes de dents.",
    "Je lis le titre au tableau : Les différentes sortes de dents.",
],
"observation": [
    "Regardez le schéma des dents affiché au tableau.",
    "Passez votre langue sur vos dents : celles de devant, puis celles du fond.",
],
"analyse": [
    ("Comment sont les dents de devant ?", "Les dents de devant sont plates et coupantes : ce sont les incisives."),
    ("Quelles dents sont pointues, à côté des incisives ?", "À côté des incisives, les dents pointues sont les canines."),
    ("Quelles dents sont larges, au fond de la bouche ?", "Au fond de la bouche, les dents larges sont les molaires."),
],
"synthese": "Nous avons trois sortes de dents : les incisives plates devant, les canines pointues sur les côtés et les molaires larges au fond.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Nous avons trois sortes de dents.", "2. Les incisives sont au fond de la bouche.", "3. Les canines sont pointues.", "4. Les molaires sont larges."],
     "cor": ["1. **Vrai** : nous avons trois sortes de dents.", "2. **Faux** : les incisives sont devant.", "3. **Vrai** : les canines sont pointues.", "4. **Vrai** : les molaires sont larges."]},
    {"c": "Complète avec les mots suivants : incisives, canines, molaires.",
     "items": ["1. Les dents plates de devant sont les ...", "2. Les dents pointues sont les ...", "3. Les dents larges du fond sont les ...", "4. Incisives, canines et molaires sont trois sortes de ...."],
     "cor": ["1. Les dents plates de devant sont les **incisives**.", "2. Les dents pointues sont les **canines**.", "3. Les dents larges du fond sont les **molaires**.", "4. Ce sont trois sortes de **dents**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Combien de sortes de dents avons-nous ? A. Une B. Deux C. Trois", "2. Quelles dents sont devant ? A. Les molaires B. Les incisives C. Les canines", "3. Quelles dents sont pointues ? A. Les canines B. Les incisives C. Les molaires", "4. Quelles dents sont au fond ? A. Les incisives B. Les canines C. Les molaires"],
     "cor": ["1. **C. Trois** : incisives, canines et molaires.", "2. **B. Les incisives**.", "3. **A. Les canines**.", "4. **C. Les molaires**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quelles sont les trois sortes de dents ?", "2. Où se trouvent les incisives ?", "3. Où se trouvent les molaires ?", "4. Comment sont les canines ?"],
     "cor": ["1. Les trois sortes sont les **incisives**, les **canines** et les **molaires**.", "2. Les **incisives** sont devant la bouche.", "3. Les **molaires** sont au fond de la bouche.", "4. Les **canines** sont **pointues**."]},
],
"lecon": [
    (None, ["Dans notre bouche, toutes les **dents** ne se ressemblent pas. Nous avons trois sortes de dents."]),
    ("1. Les incisives et les canines", ["Les **incisives** sont les dents plates de devant. Elles sont coupantes. À côté des incisives, les **canines** sont des dents pointues."]),
    ("2. Les molaires", ["Les **molaires** sont les dents larges du fond de la bouche. Elles écrasent les aliments. L'adulte a en tout 32 dents : 8 incisives, 4 canines et 20 molaires."]),
],
"mots_cles": ["incisives", "canines", "molaires", "dents"],
},
{
"n": 5, "titre": "Le rôle des dents", "theme": "Les dents",
"objectif": "reconnaître les rôles des différentes sortes de dents",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "un morceau de pain et un fruit apportés en classe",
"image": None,
"revision": [
    ("Quelles sont les trois sortes de dents ?", "Les incisives, les canines et les molaires."),
    ("Où se trouvent les molaires ?", "Les molaires sont au fond de la bouche."),
],
"situation": "Au repas, Nivo coupe la viande avec ses dents de devant, la déchire avec ses dents pointues et l'écrase avec ses dents du fond. À quoi sert chaque sorte de dents ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre le rôle des dents.",
    "Je lis le titre au tableau : Le rôle des dents.",
],
"observation": [
    "Regardez ce morceau de pain et ce fruit.",
    "Faites semblant de les croquer, de les déchirer et de les écraser.",
],
"analyse": [
    ("Que font les incisives quand on croque ?", "Les incisives coupent les aliments."),
    ("Que font les canines quand on mange de la viande ?", "Les canines déchirent les aliments."),
    ("Que font les molaires quand on mâche ?", "Les molaires broient et écrasent les aliments."),
],
"synthese": "Les incisives coupent les aliments, les canines les déchirent et les molaires les broient.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les incisives coupent les aliments.", "2. Les canines déchirent les aliments.", "3. Les molaires broient les aliments.", "4. Les dents ne servent pas à manger."],
     "cor": ["1. **Vrai** : les incisives coupent.", "2. **Vrai** : les canines déchirent.", "3. **Vrai** : les molaires broient.", "4. **Faux** : les dents servent à manger."]},
    {"c": "Complète avec les mots suivants : coupent, déchirent, broient.",
     "items": ["1. Les incisives ... les aliments.", "2. Les canines ... les aliments.", "3. Les molaires ... les aliments.", "4. Couper, déchirer et broyer : voilà le ... des dents."],
     "cor": ["1. Les incisives **coupent** les aliments.", "2. Les canines **déchirent** les aliments.", "3. Les molaires **broient** les aliments.", "4. Voilà le **rôle** des dents."]},
],
"evaluation": [
    {"c": "Relie chaque dent à son rôle.",
     "items": ["1. Les incisives — a. broyer les aliments", "2. Les canines — b. couper les aliments", "3. Les molaires — c. déchirer les aliments", "4. Les dents — d. mâcher les aliments"],
     "cor": ["1. Les **incisives** : **b**. couper les aliments.", "2. Les **canines** : **c**. déchirer les aliments.", "3. Les **molaires** : **a**. broyer les aliments.", "4. Les **dents** : **d**. mâcher les aliments."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quel est le rôle des incisives ?", "2. Quel est le rôle des canines ?", "3. Quel est le rôle des molaires ?", "4. Pourquoi faut-il bien mâcher les aliments ?"],
     "cor": ["1. Les **incisives** **coupent** les aliments.", "2. Les **canines** **déchirent** les aliments.", "3. Les **molaires** **broient** les aliments.", "4. Pour **les écraser** et faciliter la digestion."]},
],
"lecon": [
    (None, ["Chaque sorte de **dent** a son **travail** dans la bouche. Ensemble, les dents transforment les aliments."]),
    ("1. Couper et déchirer", ["Les **incisives** **coupent** les aliments, comme des ciseaux. Les **canines** **déchirent** les aliments durs, comme la viande."]),
    ("2. Broyer", ["Les **molaires** **broient** et **écrasent** les aliments pour les rendre tout petits. Bien **mâcher** aide le ventre à digérer."]),
],
"mots_cles": ["couper", "déchirer", "broyer", "mâcher"],
},
{
"n": 6, "titre": "Les dents de lait et les dents définitives", "theme": "Les dents",
"objectif": "connaître les dents de lait et les dents définitives",
"doc": "Répartition annuelle 9e, SVT, Bimestre 2",
"support_obs": "le schéma des dents affiché au tableau",
"image": None,
"revision": [
    ("Quel est le rôle des incisives ?", "Les incisives coupent les aliments."),
    ("Quel est le rôle des molaires ?", "Les molaires broient les aliments."),
],
"situation": "Mamy a huit ans. Une de ses dents bouge ! Sa grande sœur lui dit : « Ne t'inquiète pas, une nouvelle dent va pousser à la place. » Pourquoi les dents tombent-elles ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre pourquoi les dents tombent.",
    "Je lis le titre au tableau : Les dents de lait et les dents définitives.",
],
"observation": [
    "Regardez le schéma des dents affiché au tableau.",
    "Comptez vos dents : y en a-t-il une qui bouge ?",
],
"analyse": [
    ("Comment s'appellent les premières dents de l'enfant ?", "Les premières dents de l'enfant s'appellent les dents de lait."),
    ("Que se passe-t-il vers six ou sept ans ?", "Vers six ou sept ans, les dents de lait tombent, une à une."),
    ("Par quoi les dents de lait sont-elles remplacées ?", "Les dents de lait sont remplacées par les dents définitives."),
],
"synthese": "Les premières dents sont les dents de lait. Elles tombent vers six ans et sont remplacées par les dents définitives qui ne repoussent plus.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les premières dents sont les dents de lait.", "2. Les dents de lait tombent vers six ans.", "3. Les dents définitives repoussent si elles tombent.", "4. Les dents de lait sont remplacées."],
     "cor": ["1. **Vrai** : ce sont les dents de lait.", "2. **Vrai** : elles tombent vers six ans.", "3. **Faux** : les dents définitives ne repoussent pas.", "4. **Vrai** : elles sont remplacées par les dents définitives."]},
    {"c": "Complète avec les mots suivants : lait, définitives, tombent, poussent.",
     "items": ["1. Les premières dents sont les dents de ...", "2. Vers six ans, elles ...", "3. À leur place, ... les dents définitives.", "4. Les dents ... restent toute la vie."],
     "cor": ["1. Les premières dents sont les dents de **lait**.", "2. Vers six ans, elles **tombent**.", "3. À leur place, **poussent** les dents définitives.", "4. Les dents **définitives** restent toute la vie."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Comment s'appellent les premières dents ? A. Dents de lait B. Dents d'or C. Dents de pierre", "2. Quand tombent-elles ? A. Vers trois ans B. Vers six ans C. Vers vingt ans", "3. Par quoi sont-elles remplacées ? A. Par rien B. Par les dents définitives C. Par les molaires de lait", "4. Une dent définitive tombée repousse-t-elle ? A. Oui B. Non C. Parfois"],
     "cor": ["1. **A. Dents de lait**.", "2. **B. Vers six ans**.", "3. **B. Par les dents définitives**.", "4. **B. Non** : il faut bien les protéger."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que sont les dents de lait ?", "2. À quel âge tombent-elles ?", "3. Que sont les dents définitives ?", "4. Pourquoi faut-il protéger les dents définitives ?"],
     "cor": ["1. Les **dents de lait** sont les **premières dents** de l'enfant.", "2. Elles tombent vers **six ou sept ans**.", "3. Ce sont les dents qui **remplacent** les dents de lait.", "4. Parce qu'elles **ne repoussent pas** si elles tombent."]},
],
"lecon": [
    (None, ["L'enfant a d'abord des **dents de lait**. Elles **tombent** et sont remplacées par les **dents définitives**."]),
    ("1. Les dents de lait", ["Les **dents de lait** poussent quand l'enfant est petit : il en a 20. Vers **six ans**, elles commencent à **tomber**, une à une, souvent en commençant par les incisives."]),
    ("2. Les dents définitives", ["Les **dents définitives** poussent à la place des dents de lait : l'adulte en a 32. Elles **ne repoussent pas** : il faut donc en prendre grand soin."]),
],
"mots_cles": ["dents de lait", "dents définitives", "tomber", "pousser"],
},
]
