# -*- coding: utf-8 -*-
"""Contenu Bimestre 3 — Séances 7 à 12 (Blocs 3-4) + Révision + Examen."""

SEANCES_B = [
{
"n": 7, "titre": "Les parties de l'oreille", "theme": "L'oreille",
"objectif": "énumérer les différentes parties de l'oreille",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de l'oreille affiché au tableau",
"image": ("svt9e_oreille_parties.png", "Schéma : les parties de l'oreille : le pavillon, le conduit auditif et le tympan."),
"revision": [
    ("Que faut-il pour bien lire ?", "Il faut une bonne lumière."),
    ("Comment protéger ses yeux du soleil ?", "Avec un chapeau et en restant à l'ombre."),
],
"situation": "Le matin, Koto entend le chant du coq. Il se touche l'oreille : une partie visible, puis un petit trou. Quelles sont les parties de l'oreille ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les parties de l'oreille.",
    "Je lis le titre au tableau : Les parties de l'oreille.",
],
"observation": [
    "Regardez le schéma de l'oreille affiché au tableau.",
    "Touchez doucement votre oreille : la partie visible, puis le petit trou.",
],
"analyse": [
    ("Comment s'appelle la partie visible de l'oreille ?", "La partie visible s'appelle le pavillon."),
    ("Comment s'appelle le petit couloir à l'intérieur ?", "Le petit couloir s'appelle le conduit auditif."),
    ("Que trouve-t-on au fond du conduit auditif ?", "Au fond du conduit, on trouve le tympan, une petite peau fine."),
],
"synthese": "L'oreille a trois parties : le pavillon, le conduit auditif et le tympan.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'oreille a trois parties.", "2. Le pavillon est la partie visible.", "3. Le conduit auditif est un petit couloir.", "4. Le tympan est un os dur."],
     "cor": ["1. **Vrai** : trois parties.", "2. **Vrai** : le pavillon est visible.", "3. **Vrai** : c'est un petit couloir.", "4. **Faux** : le tympan est une petite peau fine."]},
    {"c": "Complète avec les mots suivants : pavillon, conduit auditif, tympan.",
     "items": ["1. La partie visible s'appelle le ...", "2. Le petit couloir s'appelle le ...", "3. La petite peau fine du fond s'appelle le ...", "4. Le ..., le ... et le ... sont les parties de l'oreille."],
     "cor": ["1. Le **pavillon**.", "2. Le **conduit auditif**.", "3. Le **tympan**.", "4. Le **pavillon**, le **conduit auditif** et le **tympan**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Combien l'oreille a-t-elle de parties ? A. Une B. Trois C. Cinq", "2. Quelle est la partie visible ? A. Le tympan B. Le pavillon C. Le conduit", "3. Qu'est-ce que le conduit auditif ? A. Un petit couloir B. Une peau fine C. Un os", "4. Qu'est-ce que le tympan ? A. Une petite peau fine B. Un muscle C. Un poil"],
     "cor": ["1. **B. Trois**.", "2. **B. Le pavillon**.", "3. **A. Un petit couloir**.", "4. **A. Une petite peau fine**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quelles sont les trois parties de l'oreille ?", "2. Qu'est-ce que le pavillon ?", "3. Où se trouve le tympan ?", "4. Qu'est-ce que le conduit auditif ?"],
     "cor": ["1. Le **pavillon**, le **conduit auditif** et le **tympan**.", "2. Le **pavillon** est la **partie visible** de l'oreille.", "3. Le **tympan** se trouve **au fond du conduit auditif**.", "4. Le **conduit auditif** est le **petit couloir** à l'intérieur."]},
],
"lecon": [
    (None, ["L'**oreille** est l'organe de l'ouïe. Elle a trois **parties**."]),
    ("1. Le pavillon et le conduit auditif", ["Le **pavillon** est la partie visible de l'oreille : il attrape les sons. Le **conduit auditif** est le petit **couloir** qui entre dans la tête."]),
    ("2. Le tympan", ["Au fond du **conduit auditif**, il y a le **tympan** : une **petite peau fine** qui **vibre** quand le son arrive, comme la peau d'un tambour."]),
],
"mots_cles": ["pavillon", "conduit auditif", "tympan", "oreille"],
},
{
"n": 8, "titre": "Le fonctionnement de l'oreille", "theme": "L'oreille",
"objectif": "expliquer le fonctionnement de l'oreille",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "un petit tambour apporté en classe",
"image": None,
"revision": [
    ("Quelles sont les trois parties de l'oreille ?", "Le pavillon, le conduit auditif et le tympan."),
    ("Qu'est-ce que le tympan ?", "C'est une petite peau fine au fond du conduit auditif."),
],
"situation": "Rova frappe doucement sur un petit tambour : la peau vibre et on entend le son. Son oreille a aussi une peau qui vibre : le tympan. Comment l'oreille entend-elle ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment l'oreille fonctionne.",
    "Je lis le titre au tableau : Le fonctionnement de l'oreille.",
],
"observation": [
    "Frappez doucement sur le petit tambour et touchez sa peau : elle vibre.",
    "Écoutez les bruits de la classe, les yeux fermés : d'où viennent-ils ?",
],
"analyse": [
    ("Que fait le pavillon quand un son arrive ?", "Le pavillon attrape le son."),
    ("Par où le son passe-t-il ensuite ?", "Le son passe par le conduit auditif."),
    ("Que fait le tympan quand le son arrive ?", "Le tympan vibre et envoie le son au cerveau, qui le comprend."),
],
"synthese": "Le pavillon attrape le son, le son passe par le conduit auditif, le tympan vibre, et le cerveau comprend le son.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le pavillon attrape les sons.", "2. Le son passe par le conduit auditif.", "3. Le tympan vibre.", "4. C'est la main qui comprend les sons."],
     "cor": ["1. **Vrai** : le pavillon attrape les sons.", "2. **Vrai** : le son passe par le conduit.", "3. **Vrai** : le tympan vibre.", "4. **Faux** : c'est le cerveau qui comprend."]},
    {"c": "Complète avec les mots suivants : pavillon, conduit auditif, tympan, cerveau.",
     "items": ["1. Le ... attrape le son.", "2. Le son passe par le ...", "3. Le ... vibre.", "4. Le ... comprend le son."],
     "cor": ["1. Le **pavillon** attrape le son.", "2. Par le **conduit auditif**.", "3. Le **tympan** vibre.", "4. Le **cerveau** comprend."]},
],
"evaluation": [
    {"c": "Relie chaque partie à son rôle.",
     "items": ["1. Le pavillon — a. vibrer", "2. Le conduit auditif — b. comprendre le son", "3. Le tympan — c. attrapper le son", "4. Le cerveau — d. laisser passer le son"],
     "cor": ["1. Le **pavillon** : **c**. attraper le son.", "2. Le **conduit auditif** : **d**. laisser passer le son.", "3. Le **tympan** : **a**. vibrer.", "4. Le **cerveau** : **b**. comprendre le son."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que fait le pavillon ?", "2. Par où passe le son ?", "3. Que fait le tympan ?", "4. Qui comprend le son ?"],
     "cor": ["1. Le **pavillon** **attrape le son**.", "2. Le son passe par le **conduit auditif**.", "3. Le **tympan** **vibre**.", "4. C'est le **cerveau** qui comprend le son."]},
],
"lecon": [
    (None, ["L'**oreille** sert à **entendre**. Voici le chemin du **son** dans l'oreille."]),
    ("1. Le chemin du son", ["Le **pavillon** attrape le **son**. Le son entre dans le **conduit auditif** et arrive au **tympan**. Le **tympan** **vibre**, comme la peau d'un tambour."]),
    ("2. Entendre et tenir debout", ["La vibration du tympan est envoyée au **cerveau**, qui **comprend** le son. L'oreille sert aussi à garder l'**équilibre** : grâce à elle, nous tenons debout sans tomber."]),
],
"mots_cles": ["son", "vibrer", "entendre", "cerveau", "équilibre"],
},
{
"n": 9, "titre": "Les maladies et l'hygiène des oreilles", "theme": "L'oreille",
"objectif": "connaître les maladies des oreilles et les faire soigner",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de l'oreille affiché au tableau",
"image": None,
"revision": [
    ("Que fait le pavillon ?", "Le pavillon attrape le son."),
    ("Que fait le tympan quand le son arrive ?", "Le tympan vibre."),
],
"situation": "Depuis hier, Koto a mal à l'oreille et un peu de fièvre. Son grand frère veut nettoyer l'oreille avec un bâton pointu. La maman l'arrête : « Jamais d'objet dans l'oreille ! » Que faut-il faire ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les maladies et l'hygiène des oreilles.",
    "Je lis le titre au tableau : Les maladies et l'hygiène des oreilles.",
],
"observation": [
    "Regardez le schéma de l'oreille affiché au tableau.",
    "Touchez doucement le pavillon de votre oreille : est-il propre ?",
],
"analyse": [
    ("Quels sont les signes de l'otite ?", "Les signes de l'otite sont un mal à l'oreille et la fièvre."),
    ("Que ne faut-il jamais mettre dans l'oreille ?", "Il ne faut jamais mettre de bâton ni d'objet pointu dans l'oreille."),
    ("Que faut-il faire quand l'oreille fait mal ?", "Quand l'oreille fait mal, il faut prévenir les parents et aller au centre de santé."),
],
"synthese": "L'otite fait mal à l'oreille et donne la fièvre. On ne met jamais d'objet dans l'oreille, et on soigne l'otite au centre de santé.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'otite fait mal à l'oreille.", "2. On peut mettre un bâton dans l'oreille.", "3. L'otite donne parfois la fièvre.", "4. Une oreille malade se soigne au centre de santé."],
     "cor": ["1. **Vrai** : l'otite fait mal.", "2. **Faux** : jamais d'objet dans l'oreille.", "3. **Vrai** : elle donne la fièvre.", "4. **Vrai** : au centre de santé."]},
    {"c": "Complète avec les mots suivants : otite, bâton, santé, pavillon.",
     "items": ["1. Le mal à l'oreille s'appelle l'...", "2. Je ne mets jamais de ... dans l'oreille.", "3. Je vais au centre de ...", "4. Je lave doucement le ... de l'oreille."],
     "cor": ["1. L'**otite**.", "2. De **bâton** dans l'oreille.", "3. Centre de **santé**.", "4. Le **pavillon** de l'oreille."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quels sont les signes de l'otite ? A. Mal à l'oreille et fièvre B. Mal au ventre C. Mal aux dents", "2. Que ne faut-il jamais faire ? A. Laver le pavillon B. Mettre un bâton dans l'oreille C. Écouter", "3. Que faire si l'oreille fait mal ? A. Attendre un an B. Aller au centre de santé C. Mettre un objet dedans", "4. Comment lave-t-on l'oreille ? A. Doucement, le pavillon B. Avec un bâton C. Jamais"],
     "cor": ["1. **A. Mal à l'oreille et fièvre**.", "2. **B. Mettre un bâton dans l'oreille**.", "3. **B. Aller au centre de santé**.", "4. **A. Doucement, le pavillon**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quels sont les signes de l'otite ?", "2. Pourquoi ne met-on rien dans l'oreille ?", "3. Que faire si l'oreille fait mal ?", "4. Comment garder des oreilles propres ?"],
     "cor": ["1. Un **mal à l'oreille** et la **fièvre**.", "2. Pour ne pas **blesser le tympan**.", "3. **Prévenir les parents** et aller au **centre de santé**.", "4. Laver **doucement le pavillon** avec de l'eau propre et l'essuyer."]},
],
"lecon": [
    (None, ["L'**oreille** peut tomber malade. La maladie la plus fréquente est l'**otite**."]),
    ("1. L'otite", ["L'**otite** donne un **mal à l'oreille**, parfois avec la **fièvre**. Il faut **prévenir les parents** et aller au **centre de santé** pour la soigner."]),
    ("2. L'hygiène des oreilles", ["Je ne mets **jamais** de **bâton**, de **crayon** ni d'**objet pointu** dans l'oreille : cela peut **blesser le tympan**. Je lave **doucement** le **pavillon** avec de l'eau propre et je l'essuie avec ma serviette."]),
],
"mots_cles": ["otite", "fièvre", "tympan", "pavillon", "centre de santé"],
},
{
"n": 10, "titre": "Décrire la langue", "theme": "La langue",
"objectif": "décrire la langue",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de la langue affiché au tableau",
"image": ("svt9e_langue.png", "Schéma : la langue et les quatre saveurs : sucré, salé, acide, amer."),
"revision": [
    ("Quels sont les signes de l'otite ?", "Un mal à l'oreille et la fièvre."),
    ("Que ne met-on jamais dans l'oreille ?", "Jamais de bâton ni d'objet pointu."),
],
"situation": "Devant le miroir, Soa tire la langue : elle est rose, un peu humide, et couverte de petits points. À quoi ressemble la langue ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à décrire la langue.",
    "Je lis le titre au tableau : Décrire la langue.",
],
"observation": [
    "Regardez le schéma de la langue affiché au tableau.",
    "Tirez doucement la langue devant le miroir : comment est-elle ?",
],
"analyse": [
    ("Où se trouve la langue ?", "La langue se trouve dans la bouche."),
    ("Comment est la langue ?", "La langue est rose, humide et souple."),
    ("Que voit-on sur la langue ?", "Sur la langue, on voit de petits points appelés papilles."),
],
"synthese": "La langue est un organe de la bouche : rose, humide et souple, couverte de petits points appelés papilles.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La langue est dans la bouche.", "2. La langue est sèche et dure.", "3. La langue est couverte de papilles.", "4. La langue est un organe du goût."],
     "cor": ["1. **Vrai** : la langue est dans la bouche.", "2. **Faux** : elle est humide et souple.", "3. **Vrai** : elle a des papilles.", "4. **Vrai** : c'est l'organe du goût."]},
    {"c": "Complète avec les mots suivants : bouche, rose, humide, papilles.",
     "items": ["1. La langue se trouve dans la ...", "2. Elle est ... et souple.", "3. Elle est ...", "4. Elle est couverte de petits points : les ...."],
     "cor": ["1. Dans la **bouche**.", "2. **Rose** et souple.", "3. **Humide**.", "4. Les **papilles**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Où se trouve la langue ? A. Dans le nez B. Dans la bouche C. Dans l'oreille", "2. Comment est la langue ? A. Rose et humide B. Verte et sèche C. Dure et froide", "3. Que trouve-t-on sur la langue ? A. Des dents B. Des papilles C. Des cheveux", "4. De quel sens la langue est-elle l'organe ? A. La vue B. Le goût C. L'ouïe"],
     "cor": ["1. **B. Dans la bouche**.", "2. **A. Rose et humide**.", "3. **B. Des papilles**.", "4. **B. Le goût**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Où se trouve la langue ?", "2. Comment est la langue ?", "3. Que sont les papilles ?", "4. De quel sens la langue est-elle l'organe ?"],
     "cor": ["1. La langue se trouve dans la **bouche**.", "2. Elle est **rose**, **humide** et **souple**.", "3. Les **papilles** sont les **petits points** de la langue.", "4. Elle est l'organe du **goût**."]},
],
"lecon": [
    (None, ["La **langue** est un organe qui se trouve dans la **bouche**. Elle aide à manger et à parler."]),
    ("1. Comment est la langue ?", ["La langue est **rose**, **humide** et **souple**. Elle bouge dans tous les sens."]),
    ("2. Les papilles", ["Sur la langue, on voit de **petits points** : ce sont les **papilles**. Ce sont les **papilles** qui sentent le goût des aliments."]),
],
"mots_cles": ["langue", "bouche", "rose", "papilles"],
},
{
"n": 11, "titre": "Les rôles de la langue", "theme": "La langue",
"objectif": "énumérer les rôles de la langue",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "des petits morceaux à goûter : sucre, sel, citron",
"image": None,
"revision": [
    ("Où se trouve la langue ?", "La langue se trouve dans la bouche."),
    ("Que sont les papilles ?", "Ce sont les petits points de la langue qui sentent le goût."),
],
"situation": "Au goûter, Nivo goûte un fruit sucré, puis un citron bien acide. Avec sa langue, elle sent les goûts. La langue ne fait-elle que goûter ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les rôles de la langue.",
    "Je lis le titre au tableau : Les rôles de la langue.",
],
"observation": [
    "Goûtez ces petits morceaux : le sucre, le sel, le citron.",
    "Dites ce que vous sentez avec votre langue : sucré, salé, acide ?",
],
"analyse": [
    ("Que sent la langue ?", "La langue sent les saveurs : le sucré, le salé, l'acide et l'amer."),
    ("Que fait la langue quand on parle ?", "La langue bouge et aide à prononcer les mots."),
    ("Que fait la langue quand on mange ?", "La langue mélange les aliments et aide à avaler."),
],
"synthese": "La langue a trois rôles : elle sent les saveurs, elle aide à parler et elle aide à avaler.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La langue sent les saveurs.", "2. Il y a quatre saveurs.", "3. La langue aide à parler.", "4. La langue ne sert pas à manger."],
     "cor": ["1. **Vrai** : la langue sent les saveurs.", "2. **Vrai** : sucré, salé, acide, amer.", "3. **Vrai** : elle aide à prononcer.", "4. **Faux** : elle aide à avaler."]},
    {"c": "Complète avec les mots suivants : saveurs, parler, avaler, langue.",
     "items": ["1. La ... sent les saveurs.", "2. Le sucré, le salé, l'acide et l'amer sont des ...", "3. La langue aide à ...", "4. La langue aide à ... les aliments."],
     "cor": ["1. La **langue** sent les saveurs.", "2. Ce sont des **saveurs**.", "3. À **parler**.", "4. À **avaler** les aliments."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Combien de saveurs la langue sent-elle ? A. Deux B. Quatre C. Six", "2. Quelle saveur a le sucre ? A. Sucrée B. Salée C. Amère", "3. Que fait la langue quand on parle ? A. Elle dort B. Elle aide à prononcer C. Elle avale", "4. Quel goût a le citron ? A. Sucré B. Acide C. Salé"],
     "cor": ["1. **B. Quatre**.", "2. **A. Sucrée**.", "3. **B. Elle aide à prononcer**.", "4. **B. Acide**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quelles sont les quatre saveurs ?", "2. Que fait la langue quand on parle ?", "3. Que fait la langue quand on mange ?", "4. Quels sont les trois rôles de la langue ?"],
     "cor": ["1. Le **sucré**, le **salé**, l'**acide** et l'**amer**.", "2. Elle **aide à prononcer les mots**.", "3. Elle **mélange les aliments** et **aide à avaler**.", "4. **Sentir les saveurs**, **aider à parler** et **aider à avaler**."]},
],
"lecon": [
    (None, ["La **langue** a trois **rôles** importants."]),
    ("1. Sentir les saveurs", ["La **langue** est l'organe du **goût**. Elle sent quatre **saveurs** : le **sucré**, le **salé**, l'**acide** et l'**amer**. Ce sont les **papilles** qui sentent le goût."]),
    ("2. Parler et avaler", ["La **langue** bouge dans la bouche et **aide à prononcer** les mots. En mangeant, elle **mélange** les aliments avec la salive et **aide à avaler**."]),
],
"mots_cles": ["saveurs", "sucré", "salé", "acide", "amer", "goût"],
},
{
"n": 12, "titre": "L'hygiène et la protection de la langue", "theme": "La langue",
"objectif": "connaître l'hygiène de la langue et les mesures contre les risques d'accident",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "une brosse à dents apportée en classe",
"image": None,
"revision": [
    ("Quelles sont les quatre saveurs ?", "Le sucré, le salé, l'acide et l'amer."),
    ("Quels sont les rôles de la langue ?", "Sentir les saveurs, aider à parler et aider à avaler."),
],
"situation": "Nivo boit son thé encore bouillant : elle se brûle la langue ! Son petit frère, lui, mord son crayon pointu. Quels dangers guettent la langue, et comment la protéger ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'hygiène et la protection de la langue.",
    "Je lis le titre au tableau : L'hygiène et la protection de la langue.",
],
"observation": [
    "Regardez cette brosse à dents : elle sert aussi à nettoyer la langue.",
    "Tirez la langue : est-elle propre et rose ?",
],
"analyse": [
    ("Que faut-il faire avant de boire ou de manger chaud ?", "Il faut attendre que la nourriture et la boisson refroidissent."),
    ("Que ne faut-il jamais mettre dans la bouche ?", "Il ne faut jamais mettre d'objets pointus dans la bouche."),
    ("Comment nettoie-t-on sa langue ?", "On nettoie sa langue en la brossant doucement avec la brosse à dents."),
],
"synthese": "J'attends que les aliments refroidissent, je ne mets rien de pointu dans ma bouche et je brosse doucement ma langue.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut attendre que le thé refroidisse.", "2. On peut mordre un crayon pointu.", "3. On brosse doucement sa langue.", "4. Les objets pointus blessent la langue."],
     "cor": ["1. **Vrai** : sinon on se brûle.", "2. **Faux** : c'est dangereux.", "3. **Vrai** : avec la brosse à dents.", "4. **Vrai** : ils peuvent la couper."]},
    {"c": "Complète avec les mots suivants : refroidir, pointus, brosse, eau.",
     "items": ["1. J'attends que la soupe ...", "2. Je ne mets pas d'objets ... dans la bouche.", "3. Je nettoie ma langue avec la ... à dents.", "4. Après manger, je rince ma bouche avec de l'... propre."],
     "cor": ["1. Que la soupe **refroidisse**.", "2. D'objets **pointus**.", "3. Avec la **brosse** à dents.", "4. De l'**eau** propre."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que faut-il faire avant de boire un thé chaud ? A. Boire vite B. Attendre qu'il refroidisse C. Souffler fort", "2. Que ne faut-il pas mettre dans la bouche ? A. Un aliment B. De l'eau C. Un objet pointu", "3. Avec quoi nettoie-t-on la langue ? A. La brosse à dents B. Un bâton C. Les ongles", "4. Que faire si la langue est blessée ? A. Rien B. Prévenir un adulte C. Manger piquant"],
     "cor": ["1. **B. Attendre qu'il refroidisse**.", "2. **C. Un objet pointu**.", "3. **A. La brosse à dents**.", "4. **B. Prévenir un adulte**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Pourquoi attend-on que les aliments refroidissent ?", "2. Que ne met-on jamais dans la bouche ?", "3. Comment nettoie-t-on sa langue ?", "4. Que faire si la langue est brûlée ou coupée ?"],
     "cor": ["1. Pour **ne pas se brûler la langue**.", "2. **Jamais d'objets pointus**.", "3. En la **brossant doucement** avec la **brosse à dents**.", "4. **Prévenir un adulte** et aller au **centre de santé**."]},
],
"lecon": [
    (None, ["La **langue** est fragile : il faut la **protéger** et la garder **propre**."]),
    ("1. Les dangers pour la langue", ["Je n'avale jamais un aliment ou une boisson **trop chauds** : j'attends qu'ils **refroidissent**. Je ne mets **jamais** d'**objets pointus** dans la bouche : ils peuvent couper la langue."]),
    ("2. L'hygiène de la langue", ["Je **brosse doucement** ma **langue** avec ma **brosse à dents**. Après manger, je **rince** ma bouche avec de l'**eau propre**. Si ma langue est brûlée ou coupée, je **préviens un adulte**."]),
],
"mots_cles": ["brûler", "pointus", "brosser", "rincer", "protéger"],
},
]

REVISION_B3 = {
"titre": "Révision — Bimestre 3",
"tableau": [
    ("Voir", "Il faut de la lumière : elle entre dans l'œil par la pupille."),
    ("La pupille et l'iris", "Petite en pleine lumière, grande dans le noir ; c'est l'iris qui règle."),
    ("L'œil et le cerveau", "L'œil forme une image ; le cerveau la comprend."),
    ("L'hygiène des yeux", "Laver le visage matin et soir ; mains propres ; sa propre serviette."),
    ("La conjonctivite", "Yeux rouges qui collent ; contagieuse ; à soigner au centre de santé."),
    ("Protéger ses yeux", "Bonne lumière pour lire, télévision de loin, chapeau et ombre au soleil."),
    ("Les parties de l'oreille", "Le pavillon, le conduit auditif et le tympan."),
    ("Le fonctionnement de l'oreille", "Le pavillon attrape le son, le tympan vibre, le cerveau comprend."),
    ("Les maladies de l'oreille", "L'otite fait mal et donne la fièvre ; jamais d'objet dans l'oreille."),
    ("La langue", "Organe de la bouche, rose et humide, couverte de papilles."),
    ("Les rôles de la langue", "Sentir les saveurs (sucré, salé, acide, amer), parler, avaler."),
    ("L'hygiène de la langue", "Attendre que ça refroidisse, pas d'objets pointus, brosser doucement."),
    ("Rappel : les dents (B2)", "Incisives coupent, canines déchirent, molaires broient ; brossage matin et soir."),
    ("Rappel : le membre supérieur (B1)", "Épaule, bras, coude, avant-bras, main et doigts ; articulations pour bouger."),
],
"questions": [
    ("Par où la lumière entre-t-elle dans l'œil ?", "Par la pupille."),
    ("Comment est la pupille dans le noir ?", "Grande, pour laisser entrer plus de lumière."),
    ("Qui comprend ce que l'œil voit ?", "Le cerveau."),
    ("Quand faut-il se laver le visage ?", "Le matin et le soir."),
    ("Quels sont les signes de la conjonctivite ?", "Des yeux rouges qui collent et qui grattent."),
    ("Quelles sont les trois parties de l'oreille ?", "Le pavillon, le conduit auditif et le tympan."),
    ("Que fait le tympan ?", "Il vibre quand le son arrive."),
    ("Que ne met-on jamais dans l'oreille ?", "Jamais de bâton ni d'objet pointu."),
    ("Quelles sont les quatre saveurs ?", "Le sucré, le salé, l'acide et l'amer."),
    ("Quels sont les trois rôles de la langue ?", "Sentir les saveurs, aider à parler, aider à avaler."),
],
}

EXAMEN_B3 = {
"titre": "Sujet d'examen 9e — Bimestre 3",
"duree": "30 min",
"total": 20,
"parties": [
    {"c": "Réponds par Vrai (V) ou Faux (F). (4 points)",
     "items": ["1. La lumière entre dans l'œil par la pupille.", "2. Dans le noir, la pupille est toute petite.", "3. Le tympan est une petite peau fine qui vibre.", "4. La langue sent quatre saveurs."],
     "cor": ["1. **Vrai** (1 pt) : la pupille laisse entrer la lumière.", "2. **Faux** (1 pt) : dans le noir, la pupille est grande.", "3. **Vrai** (1 pt) : il vibre comme la peau d'un tambour.", "4. **Vrai** (1 pt) : sucré, salé, acide, amer."]},
    {"c": "Complète avec les mots suivants : cerveau, iris, otite, papilles. (4 points)",
     "items": ["1. C'est l'... qui fait changer la taille de la pupille.", "2. L'œil forme une image, et le ... la comprend.", "3. Le mal à l'oreille avec la fièvre s'appelle l'...", "4. Les petits points de la langue sont les ...."],
     "cor": ["1. L'**iris** (1 pt).", "2. Le **cerveau** (1 pt).", "3. L'**otite** (1 pt).", "4. Les **papilles** (1 pt)."]},
    {"c": "Entoure la bonne réponse. (4 points)",
     "items": ["1. Quelle partie de l'oreille attrape le son ? A. Le tympan B. Le pavillon C. Le conduit", "2. Que faut-il pour bien lire ? A. Le noir B. Une bonne lumière C. La télévision", "3. Quel goût a le citron ? A. Sucré B. Acide C. Salé", "4. Que ne met-on jamais dans l'oreille ? A. Un bâton B. De l'eau propre C. Rien"],
     "cor": ["1. **B. Le pavillon** (1 pt).", "2. **B. Une bonne lumière** (1 pt).", "3. **B. Acide** (1 pt).", "4. **A. Un bâton** (1 pt)."]},
    {"c": "Réponds par une phrase complète. (8 points)",
     "items": ["1. Que fait le cerveau avec l'image formée par l'œil ?", "2. Quels sont les signes de la conjonctivite ?", "3. Que fait-on si l'oreille fait mal ?", "4. Cite deux mesures pour protéger sa langue."],
     "cor": ["1. Le **cerveau** **comprend l'image** et reconnaît les objets (2 pts).", "2. Des **yeux rouges** qui **collent** et qui **grattent** (2 pts).", "3. **Prévenir les parents** et aller au **centre de santé** (2 pts).", "4. **Attendre que les aliments refroidissent** et **ne pas mettre d'objets pointus** dans la bouche (2 pts)."]},
],
}
