# -*- coding: utf-8 -*-
"""Contenu Bimestre 1 — Séances 7 à 12 (Blocs 3-4) + Révision + Examen."""

SEANCES_B = [
{
"n": 7, "titre": "Les parties du membre supérieur", "theme": "Les membres supérieurs",
"objectif": "décrire ses membres supérieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 1",
"support_obs": "le schéma du membre supérieur affiché au tableau",
"image": ("svt9e_membre_superieur.png", "Schéma : le membre supérieur : épaule, bras, coude, avant-bras, main et doigts."),
"revision": [
    ("Quel est le rôle du cœur ?", "Le cœur envoie le sang dans tout le corps."),
    ("Quel est le rôle des poumons ?", "Les poumons servent à respirer."),
],
"situation": "Mamy porte un seau d'eau avec son bras. De l'épaule jusqu'aux doigts, son bras a plusieurs parties. Quelles sont les parties du membre supérieur ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les parties du membre supérieur.",
    "Je lis le titre au tableau : Les parties du membre supérieur.",
],
"observation": [
    "Regardez le schéma du membre supérieur affiché au tableau.",
    "Levez votre bras et touchez : l'épaule, le bras, le coude, l'avant-bras, la main, les doigts.",
],
"analyse": [
    ("Par quoi le bras est-il attaché au tronc ?", "Le bras est attaché au tronc par l'épaule."),
    ("Que trouvez-vous entre le bras et l'avant-bras ?", "Entre le bras et l'avant-bras, on trouve le coude."),
    ("Par quoi se termine le membre supérieur ?", "Le membre supérieur se termine par la main et les cinq doigts."),
],
"synthese": "Le membre supérieur comprend l'épaule, le bras, le coude, l'avant-bras, la main et les cinq doigts.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le bras est attaché au tronc par l'épaule.", "2. Le coude est entre le bras et l'avant-bras.", "3. La main a quatre doigts.", "4. Le poignet est entre l'avant-bras et la main."],
     "cor": ["1. **Vrai** : le bras est attaché par l'épaule.", "2. **Vrai** : le coude est entre les deux.", "3. **Faux** : la main a cinq doigts.", "4. **Vrai** : le poignet relie la main."]},
    {"c": "Complète avec les mots suivants : épaule, coude, main, doigts.",
     "items": ["1. Le bras est attaché au tronc par l'...", "2. Entre le bras et l'avant-bras, il y a le ...", "3. Le membre supérieur se termine par la ...", "4. La main porte cinq ...."],
     "cor": ["1. Le bras est attaché par l'**épaule**.", "2. Entre les deux, il y a le **coude**.", "3. Il se termine par la **main**.", "4. La main porte cinq **doigts**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Par quoi le bras est-il attaché ? A. Le coude B. L'épaule C. Le poignet", "2. Qu'y a-t-il entre le bras et l'avant-bras ? A. Le coude B. La main C. L'épaule", "3. Combien la main a-t-elle de doigts ? A. Quatre B. Cinq C. Six", "4. Quel est l'ordre du haut vers le bas ? A. Main, coude, épaule B. Épaule, bras, coude, avant-bras, main C. Coude, épaule, main"],
     "cor": ["1. **B. L'épaule** : elle attache le bras.", "2. **A. Le coude** : il est entre les deux.", "3. **B. Cinq** : la main a cinq doigts.", "4. **B. Épaule, bras, coude, avant-bras, main**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite les parties du membre supérieur.", "2. Où se trouve le coude ?", "3. Où se trouve le poignet ?", "4. À quoi sert la main ?"],
     "cor": ["1. Le membre supérieur comprend l'**épaule**, le **bras**, le **coude**, l'**avant-bras**, la **main** et les **doigts**.", "2. Le **coude** est entre le bras et l'avant-bras.", "3. Le **poignet** est entre l'avant-bras et la main.", "4. La **main** sert à tenir et à porter."]},
],
"lecon": [
    (None, ["Le **membre supérieur** est le bras. Il a plusieurs parties, de l'épaule jusqu'aux doigts."]),
    ("1. Le haut du membre supérieur", ["Le bras est attaché au tronc par l'**épaule**. Après l'épaule vient le **bras**, puis le **coude** qui plie."]),
    ("2. Le bas du membre supérieur", ["Après le coude vient l'**avant-bras**, puis le **poignet**. Le membre se termine par la **main** qui porte cinq **doigts**."]),
],
"mots_cles": ["épaule", "bras", "coude", "avant-bras", "poignet", "main", "doigts"],
},
{
"n": 8, "titre": "Le fonctionnement du membre supérieur", "theme": "Les membres supérieurs",
"objectif": "comprendre le fonctionnement de ses membres supérieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 1",
"support_obs": "le schéma du membre supérieur affiché au tableau",
"image": None,
"revision": [
    ("Cite les parties du membre supérieur.", "Le membre supérieur comprend l'épaule, le bras, le coude, l'avant-bras, la main et les doigts."),
    ("Où se trouve le coude ?", "Le coude est entre le bras et l'avant-bras."),
],
"situation": "Voahangy lance une balle à son frère : son épaule tourne, son coude plie et sa main s'ouvre. Comment notre bras bouge-t-il ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment le membre supérieur bouge.",
    "Je lis le titre au tableau : Le fonctionnement du membre supérieur.",
],
"observation": [
    "Regardez le schéma du membre supérieur affiché au tableau.",
    "Faites ces mouvements : levez le bras, pliez le coude, tournez la main.",
],
"analyse": [
    ("Que fait l'épaule quand on lève le bras ?", "L'épaule tourne et permet de lever le bras."),
    ("Que fait le coude quand on porte la main à la bouche ?", "Le coude plie pour rapprocher la main."),
    ("Que fait la main quand on attrape un crayon ?", "La main se ferme et les doigts serrent le crayon."),
],
"synthese": "L'épaule, le coude et le poignet sont des articulations : elles permettent au bras de bouger dans tous les sens.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'épaule permet de lever le bras.", "2. Le coude ne plie pas.", "3. Le poignet permet à la main de tourner.", "4. L'épaule, le coude et le poignet sont des articulations."],
     "cor": ["1. **Vrai** : l'épaule permet de lever le bras.", "2. **Faux** : le coude plie.", "3. **Vrai** : le poignet fait tourner la main.", "4. **Vrai** : ce sont des articulations."]},
    {"c": "Complète avec les mots suivants : épaule, coude, poignet, articulations.",
     "items": ["1. Pour lever le bras, j'utilise mon ...", "2. Pour plier le bras, j'utilise mon ...", "3. Pour tourner la main, j'utilise mon ...", "4. L'épaule, le coude et le poignet sont des ...."],
     "cor": ["1. Pour lever le bras, j'utilise mon **épaule**.", "2. Pour plier le bras, j'utilise mon **coude**.", "3. Pour tourner la main, j'utilise mon **poignet**.", "4. Ce sont des **articulations**."]},
],
"evaluation": [
    {"c": "Relie chaque articulation à son mouvement.",
     "items": ["1. L'épaule — a. plier le bras", "2. Le coude — b. lever le bras", "3. Le poignet — c. tourner la main", "4. Les doigts — d. serrer un objet"],
     "cor": ["1. L'**épaule** : **b**. lever le bras.", "2. Le **coude** : **a**. plier le bras.", "3. Le **poignet** : **c**. tourner la main.", "4. Les **doigts** : **d**. serrer un objet."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce qu'une articulation ?", "2. Cite trois articulations du membre supérieur.", "3. Que permet de faire le coude ?", "4. Que permettent de faire les doigts ?"],
     "cor": ["1. Une **articulation** est un endroit où le corps plie et bouge.", "2. Trois articulations sont l'**épaule**, le **coude** et le **poignet**.", "3. Le **coude** permet de plier le bras.", "4. Les **doigts** permettent de tenir et de serrer."]},
],
"lecon": [
    (None, ["Le **membre supérieur** bouge grâce aux **articulations**. Une articulation est un endroit où le corps plie."]),
    ("1. Les articulations du bras", ["L'**épaule** permet de lever et de tourner le bras. Le **coude** permet de plier le bras. Le **poignet** permet à la **main** de tourner."]),
    ("2. Les mouvements de la main", ["La **main** s'ouvre et se ferme. Les cinq **doigts** permettent de tenir un crayon, de porter un seau et d'attraper un ballon."]),
],
"mots_cles": ["articulation", "mouvement", "épaule", "coude", "poignet"],
},
{
"n": 9, "titre": "L'hygiène et la sécurité des membres supérieurs", "theme": "Les membres supérieurs",
"objectif": "connaître les mesures d'hygiène et de sécurité des membres supérieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 1",
"support_obs": "l'image de l'enfant qui se lave les mains, affichée au tableau",
"image": ("svt9e_hygiene_mains.png", "Image : Koto se lave les mains avec du savon avant de manger."),
"revision": [
    ("Cite trois articulations du membre supérieur.", "Trois articulations sont l'épaule, le coude et le poignet."),
    ("Que permet de faire le coude ?", "Le coude permet de plier le bras."),
],
"situation": "Avant de manger, Rova se lave les mains avec du savon. Son frère joue avec un couteau et se coupe le doigt. Comment protéger nos bras et nos mains ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'hygiène et la sécurité des membres supérieurs.",
    "Je lis le titre au tableau : L'hygiène et la sécurité des membres supérieurs.",
],
"observation": [
    "Regardez l'image de l'enfant qui se lave les mains.",
    "Montrez vos mains : sont-elles propres ? Vos ongles sont-ils coupés ?",
],
"analyse": [
    ("Quand faut-il se laver les mains ?", "Il faut se laver les mains avant de manger et après être allé aux toilettes."),
    ("Avec quoi se lave-t-on les mains ?", "On se lave les mains avec de l'eau propre et du savon."),
    ("Quels objets dangereux ne doit-on pas toucher ?", "On ne doit pas jouer avec les couteaux, les lames et le feu."),
],
"synthese": "Je me lave les mains avec de l'eau propre et du savon. Je ne joue pas avec les objets qui coupent ni avec le feu.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut se laver les mains avant de manger.", "2. On se lave les mains avec du savon.", "3. On peut jouer avec un couteau.", "4. Il faut couper ses ongles courts et propres."],
     "cor": ["1. **Vrai** : on se lave les mains avant de manger.", "2. **Vrai** : on utilise de l'eau et du savon.", "3. **Faux** : on ne joue pas avec un couteau.", "4. **Vrai** : les ongles doivent être courts et propres."]},
    {"c": "Complète avec les mots suivants : savon, manger, couteaux, ongles.",
     "items": ["1. Je me lave les mains avant de ...", "2. Je me lave les mains avec de l'eau et du ...", "3. Je ne joue pas avec les ...", "4. Je coupe mes ... courts."],
     "cor": ["1. Je me lave les mains avant de **manger**.", "2. Avec de l'eau et du **savon**.", "3. Je ne joue pas avec les **couteaux**.", "4. Je coupe mes **ongles** courts."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quand faut-il se laver les mains ? A. Après manger seulement B. Avant de manger et après les toilettes C. Jamais", "2. Avec quoi ? A. Eau propre et savon B. Sable C. Huile", "3. Que faire en cas de coupure ? A. Rien B. Laver la plaie et prévenir un adulte C. Cacher la plaie", "4. Quel jeu est dangereux ? A. Le ballon B. La marelle C. Le couteau"],
     "cor": ["1. **B. Avant de manger et après les toilettes**.", "2. **A. Eau propre et savon**.", "3. **B. Laver la plaie et prévenir un adulte**.", "4. **C. Le couteau** : il coupe."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quand faut-il se laver les mains ?", "2. Pourquoi se lave-t-on les mains ?", "3. Cite deux objets dangereux pour les mains.", "4. Que faire si tu te coupes le doigt ?"],
     "cor": ["1. Je me lave les mains **avant de manger** et **après les toilettes**.", "2. Pour enlever les **microbes** qui rendent malade.", "3. Deux objets dangereux sont les **couteaux** et le **feu**.", "4. Je **lave la plaie** et je **préviens un adulte**."]},
],
"lecon": [
    (None, ["Nos **bras** et nos **mains** travaillent beaucoup : il faut les garder propres et les protéger."]),
    ("1. L'hygiène des mains", ["Je me lave les mains avec de l'**eau propre** et du **savon** : avant de manger et après être allé aux toilettes. Je coupe mes **ongles** courts et je les garde propres. Les mains sales portent des **microbes** qui rendent malade."]),
    ("2. La sécurité des membres supérieurs", ["Je ne joue pas avec les **couteaux**, les **lames** et le **feu**. Si je me coupe ou si je me brûle, je lave la plaie et je **préviens un adulte**."]),
],
"mots_cles": ["hygiène", "savon", "microbes", "sécurité", "ongles"],
},
{
"n": 10, "titre": "La constitution de la peau", "theme": "La peau",
"objectif": "connaître la constitution de la peau",
"doc": "Répartition annuelle 9e, SVT, Bimestre 1",
"support_obs": "le schéma de la coupe de la peau affiché au tableau",
"image": ("svt9e_peau_coupe.png", "Schéma : la coupe de la peau : l'épiderme, le derme et l'hypoderme."),
"revision": [
    ("Quand faut-il se laver les mains ?", "Il faut se laver les mains avant de manger et après être allé aux toilettes."),
    ("Cite deux objets dangereux pour les mains.", "Deux objets dangereux sont les couteaux et le feu."),
],
"situation": "Hery regarde sa main de très près : il voit des poils et des petits trous. La peau est-elle la même partout ? De quoi est-elle faite ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre de quoi la peau est faite.",
    "Je lis le titre au tableau : La constitution de la peau.",
],
"observation": [
    "Regardez le schéma de la coupe de la peau affiché au tableau.",
    "Touchez la peau de votre main : sentez les poils et les petits trous.",
],
"analyse": [
    ("Comment s'appelle la couche du dessus de la peau ?", "La couche du dessus s'appelle l'épiderme."),
    ("Comment s'appelle la couche du milieu ?", "La couche du milieu s'appelle le derme."),
    ("Que trouve-t-on sur la peau ?", "Sur la peau, on trouve des poils et des petits trous appelés pores."),
],
"synthese": "La peau a trois couches : l'épiderme, le derme et l'hypoderme. On y voit des poils et des pores.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La peau a trois couches.", "2. L'épiderme est la couche du dessus.", "3. Le derme est la couche du milieu.", "4. Il n'y a pas de poils sur la peau."],
     "cor": ["1. **Vrai** : la peau a trois couches.", "2. **Vrai** : l'épiderme est au-dessus.", "3. **Vrai** : le derme est au milieu.", "4. **Faux** : il y a des poils sur la peau."]},
    {"c": "Complète avec les mots suivants : épiderme, derme, hypoderme, poils.",
     "items": ["1. La couche du dessus s'appelle l'...", "2. La couche du milieu s'appelle le ...", "3. La couche du dessous s'appelle l'...", "4. Sur la peau, on trouve des ... et des pores."],
     "cor": ["1. La couche du dessus : l'**épiderme**.", "2. La couche du milieu : le **derme**.", "3. La couche du dessous : l'**hypoderme**.", "4. On trouve des **poils** et des pores."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Combien la peau a-t-elle de couches ? A. Une B. Deux C. Trois", "2. Quelle couche est au-dessus ? A. Le derme B. L'épiderme C. L'hypoderme", "3. Quelle couche est au milieu ? A. Le derme B. L'épiderme C. L'hypoderme", "4. Que sont les pores ? A. Des os B. Des petits trous de la peau C. Des muscles"],
     "cor": ["1. **C. Trois** : la peau a trois couches.", "2. **B. L'épiderme** : il est au-dessus.", "3. **A. Le derme** : il est au milieu.", "4. **B. Des petits trous** de la peau."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quelles sont les trois couches de la peau ?", "2. Où se trouve l'épiderme ?", "3. Où se trouve l'hypoderme ?", "4. Que trouve-t-on sur la peau ?"],
     "cor": ["1. Les trois couches sont l'**épiderme**, le **derme** et l'**hypoderme**.", "2. L'**épiderme** est la couche du dessus.", "3. L'**hypoderme** est la couche du dessous.", "4. Sur la peau, on trouve des **poils** et des **pores**."]},
],
"lecon": [
    (None, ["La **peau** recouvre tout notre corps. Elle est formée de trois **couches**."]),
    ("1. Les trois couches de la peau", ["La couche du dessus s'appelle l'**épiderme**. La couche du milieu s'appelle le **derme**. La couche du dessous s'appelle l'**hypoderme**."]),
    ("2. Ce que l'on voit sur la peau", ["Sur la peau, on voit des **poils** et des petits trous appelés **pores**. C'est par les pores que sort la sueur."]),
],
"mots_cles": ["peau", "épiderme", "derme", "hypoderme", "poils", "pores"],
},
{
"n": 11, "titre": "Les rôles de la peau : protection et toucher", "theme": "La peau",
"objectif": "définir le rôle de protection et de toucher de la peau",
"doc": "Répartition annuelle 9e, SVT, Bimestre 1",
"support_obs": "des objets de la classe à toucher (crayon, gomme, caillou)",
"image": None,
"revision": [
    ("Quelles sont les trois couches de la peau ?", "Les trois couches sont l'épiderme, le derme et l'hypoderme."),
    ("Que trouve-t-on sur la peau ?", "Sur la peau, on trouve des poils et des pores."),
],
"situation": "Les yeux bandés, Soa touche un objet : c'est doux, c'est une gomme. Puis elle se pique avec une épine : sa peau la prévient. À quoi sert la peau ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre deux rôles de la peau : la protection et le toucher.",
    "Je lis le titre au tableau : Les rôles de la peau : protection et toucher.",
],
"observation": [
    "Touchez ces objets les yeux fermés : un crayon, une gomme, un caillou.",
    "Dites ce que vous sentez : c'est dur, doux, froid ou chaud ?",
],
"analyse": [
    ("Que sent la peau quand on touche un objet ?", "La peau sent si l'objet est dur, doux, froid ou chaud."),
    ("Que fait la peau contre les microbes et le soleil ?", "La peau nous protège contre les microbes et le soleil."),
    ("Pourquoi a-t-on mal quand on se pique ?", "On a mal parce que la peau sent la piqûre et prévient le corps."),
],
"synthese": "La peau nous protège contre les microbes, le soleil et les coups. La peau est aussi l'organe du toucher.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La peau nous protège contre les microbes.", "2. La peau sent le chaud et le froid.", "3. La peau est l'organe du toucher.", "4. La peau ne sent pas la douleur."],
     "cor": ["1. **Vrai** : la peau protège des microbes.", "2. **Vrai** : elle sent chaud et froid.", "3. **Vrai** : c'est l'organe du toucher.", "4. **Faux** : la peau sent la douleur."]},
    {"c": "Complète avec les mots suivants : protège, toucher, microbes, chaud.",
     "items": ["1. La peau nous ... contre les coups.", "2. La peau est l'organe du ...", "3. La peau nous protège contre les ...", "4. Avec la peau, je sens le froid et le ...."],
     "cor": ["1. La peau nous **protège** contre les coups.", "2. L'organe du **toucher**.", "3. Contre les **microbes**.", "4. Je sens le froid et le **chaud**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Contre quoi la peau nous protège-t-elle ? A. Rien B. Les microbes, le soleil et les coups C. L'eau seulement", "2. Quel sens donne la peau ? A. La vue B. Le toucher C. L'odorat", "3. Que sent-on avec la peau ? A. Les couleurs B. Le dur, le doux, le chaud, le froid C. Les sons", "4. Pourquoi mettre un chapeau au soleil ? A. Pour être beau B. Pour protéger la peau du soleil C. Pour avoir chaud"],
     "cor": ["1. **B. Les microbes, le soleil et les coups**.", "2. **B. Le toucher**.", "3. **B. Le dur, le doux, le chaud, le froid**.", "4. **B. Pour protéger la peau du soleil**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quels sont les deux rôles de la peau appris aujourd'hui ?", "2. Contre quoi la peau nous protège-t-elle ?", "3. Que sens-tu quand tu touches un glaçon ?", "4. Comment protéger ta peau du soleil ?"],
     "cor": ["1. La peau **protège** le corps et elle sert au **toucher**.", "2. Elle protège contre les **microbes**, le **soleil** et les **coups**.", "3. Je sens que c'est **froid**.", "4. Je mets un **chapeau** et je reste à l'**ombre**."]},
],
"lecon": [
    (None, ["La **peau** a plusieurs rôles importants pour notre corps."]),
    ("1. La peau nous protège", ["La **peau** recouvre tout le corps et le **protège** : contre les **microbes** qui rendent malade, contre le **soleil** qui brûle et contre les petits **coups**."]),
    ("2. La peau sert à toucher", ["La **peau** est l'organe du **toucher**. Avec la peau des mains, on sent si un objet est **dur** ou **doux**, **chaud** ou **froid**. La peau sent aussi la **douleur** quand on se pique."]),
],
"mots_cles": ["protection", "toucher", "microbes", "soleil", "douleur"],
},
{
"n": 12, "titre": "La peau, la sueur et la chaleur", "theme": "La peau",
"objectif": "définir le rôle de la peau contre la chaleur et connaître la sueur",
"doc": "Répartition annuelle 9e, SVT, Bimestre 1",
"support_obs": "le schéma de la coupe de la peau affiché au tableau",
"image": None,
"revision": [
    ("Quels sont les deux rôles de la peau appris ?", "La peau protège le corps et elle sert au toucher."),
    ("Contre quoi la peau nous protège-t-elle ?", "Elle protège contre les microbes, le soleil et les coups."),
],
"situation": "Après avoir joué au ballon sous le soleil, Nivo est tout mouillé : de l'eau sort de sa peau. D'où vient cette eau ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre d'où vient la sueur et comment la peau lutte contre la chaleur.",
    "Je lis le titre au tableau : La peau, la sueur et la chaleur.",
],
"observation": [
    "Regardez le schéma de la coupe de la peau affiché au tableau.",
    "Après quelques mouvements, touchez votre front : est-il mouillé ?",
],
"analyse": [
    ("Que sort-il de la peau quand il fait chaud ?", "Quand il fait chaud, la sueur sort de la peau."),
    ("Par où sort la sueur ?", "La sueur sort par les petits trous appelés pores."),
    ("Que faut-il faire quand on a transpiré ?", "Quand on a transpiré, il faut boire de l'eau et se laver."),
],
"synthese": "Quand il fait chaud, la peau fait sortir la sueur par les pores pour refroidir le corps. Il faut boire de l'eau et garder sa peau propre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La sueur sort de la peau quand il fait chaud.", "2. La sueur sort par les pores.", "3. La sueur refroidit le corps.", "4. Quand on transpire, il ne faut pas boire."],
     "cor": ["1. **Vrai** : la sueur sort quand il fait chaud.", "2. **Vrai** : elle sort par les pores.", "3. **Vrai** : elle refroidit le corps.", "4. **Faux** : il faut boire de l'eau."]},
    {"c": "Complète avec les mots suivants : sueur, pores, eau, propre.",
     "items": ["1. Quand il fait chaud, la ... sort de la peau.", "2. La sueur sort par les ...", "3. Quand on transpire, il faut boire de l'...", "4. Il faut garder sa peau ...."],
     "cor": ["1. La **sueur** sort de la peau.", "2. Elle sort par les **pores**.", "3. Il faut boire de l'**eau**.", "4. Garder sa peau **propre**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quand la peau fait-elle sortir la sueur ? A. Quand il fait froid B. Quand il fait chaud C. Quand on dort seulement", "2. Par où sort la sueur ? A. Par les os B. Par les pores C. Par les cheveux", "3. Que faut-il boire quand on transpire ? A. De l'eau B. Du pétrole C. Rien", "4. Comment garder sa peau propre ? A. En se lavant avec eau et savon B. En restant sale C. En se cachant du soleil"],
     "cor": ["1. **B. Quand il fait chaud**.", "2. **B. Par les pores**.", "3. **A. De l'eau**.", "4. **A. En se lavant avec eau et savon**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce que la sueur ?", "2. Par où sort la sueur ?", "3. À quoi sert la sueur ?", "4. Que dois-tu faire après avoir transpiré ?"],
     "cor": ["1. La **sueur** est l'eau qui sort de la peau.", "2. Elle sort par les **pores**.", "3. Elle **refroidit** le corps.", "4. Je **bois de l'eau** et je **me lave**."]},
],
"lecon": [
    (None, ["Quand il fait **chaud** ou quand on court, la **peau** fait sortir de l'eau : c'est la **sueur**."]),
    ("1. La sueur", ["La **sueur** est l'eau salée qui sort de la peau. Elle sort par les petits trous appelés **pores**. En séchant, la sueur **refroidit** le corps."]),
    ("2. Prendre soin de sa peau", ["Quand on a **transpiré**, il faut **boire de l'eau** et **se laver** avec de l'eau propre et du **savon**. Une peau propre nous protège bien contre les microbes."]),
],
"mots_cles": ["sueur", "pores", "chaleur", "transpirer", "savon"],
},
]

REVISION_B1 = {
"titre": "Révision — Bimestre 1",
"tableau": [
    ("Le corps humain", "La tête, le tronc et les membres."),
    ("La tête", "Le front, les yeux, le nez, la bouche, les oreilles et les cheveux."),
    ("Le tronc", "La poitrine, le ventre et le dos."),
    ("Les membres", "Les deux bras et les deux jambes."),
    ("Les composantes", "La peau, les os, les muscles et les organes."),
    ("Les organes", "Le cœur, les poumons et l'estomac."),
    ("Le membre supérieur", "L'épaule, le bras, le coude, l'avant-bras, la main et les doigts."),
    ("Les articulations", "L'épaule, le coude et le poignet permettent de bouger."),
    ("L'hygiène", "Se laver les mains avec eau et savon ; couper les ongles."),
    ("La sécurité", "Ne pas jouer avec les couteaux, les lames et le feu."),
    ("La peau", "Trois couches : l'épiderme, le derme et l'hypoderme."),
    ("Les rôles de la peau", "Protection, toucher, sueur contre la chaleur."),
],
"questions": [
    ("Quelles sont les trois parties du corps ?", "La tête, le tronc et les membres."),
    ("Cite trois parties de la tête.", "Le front, les yeux et le nez (ou la bouche, les oreilles, les cheveux)."),
    ("Quelles sont les quatre composantes du corps ?", "La peau, les os, les muscles et les organes."),
    ("Où se trouve le cœur ?", "Le cœur se trouve dans la poitrine, à gauche."),
    ("Quel est le rôle des poumons ?", "Les poumons servent à respirer."),
    ("Cite les parties du membre supérieur.", "L'épaule, le bras, le coude, l'avant-bras, la main et les doigts."),
    ("Qu'est-ce qu'une articulation ?", "C'est un endroit où le corps plie et bouge."),
    ("Quand faut-il se laver les mains ?", "Avant de manger et après être allé aux toilettes."),
    ("Quelles sont les trois couches de la peau ?", "L'épiderme, le derme et l'hypoderme."),
    ("À quoi sert la sueur ?", "La sueur refroidit le corps quand il fait chaud."),
],
}

EXAMEN_B1 = {
"titre": "Sujet d'examen 9e — Bimestre 1",
"duree": "30 min",
"total": 20,
"parties": [
    {"c": "Réponds par Vrai (V) ou Faux (F). (4 points)",
     "items": ["1. Le corps a trois parties.", "2. Les poumons sont dans la tête.", "3. Le coude est entre le bras et l'avant-bras.", "4. La peau a trois couches."],
     "cor": ["1. **Vrai** (1 pt) : tête, tronc et membres.", "2. **Faux** (1 pt) : les poumons sont dans la poitrine.", "3. **Vrai** (1 pt) : le coude plie le bras.", "4. **Vrai** (1 pt) : épiderme, derme et hypoderme."]},
    {"c": "Complète avec les mots suivants : tronc, cœur, savon, pores. (4 points)",
     "items": ["1. Au milieu du corps, il y a le ...", "2. L'organe qui bat dans la poitrine, c'est le ...", "3. On se lave les mains avec de l'eau et du ...", "4. La sueur sort par les ...."],
     "cor": ["1. Le **tronc** (1 pt).", "2. Le **cœur** (1 pt).", "3. Du **savon** (1 pt).", "4. Par les **pores** (1 pt)."]},
    {"c": "Entoure la bonne réponse. (4 points)",
     "items": ["1. Où se trouve l'estomac ? A. Dans la tête B. Dans le ventre C. Dans le bras", "2. Combien la main a-t-elle de doigts ? A. Quatre B. Cinq C. Six", "3. Quelle couche est au-dessus de la peau ? A. Le derme B. L'épiderme C. L'hypoderme", "4. Quel sens donne la peau ? A. La vue B. Le toucher C. L'ouïe"],
     "cor": ["1. **B. Dans le ventre** (1 pt).", "2. **B. Cinq** (1 pt).", "3. **B. L'épiderme** (1 pt).", "4. **B. Le toucher** (1 pt)."]},
    {"c": "Réponds par une phrase complète. (8 points)",
     "items": ["1. Quelles sont les quatre composantes du corps ?", "2. Quel est le rôle du cœur ?", "3. Cite deux règles d'hygiène des mains.", "4. Contre quoi la peau nous protège-t-elle ?"],
     "cor": ["1. La **peau**, les **os**, les **muscles** et les **organes** (2 pts).", "2. Le **cœur** envoie le **sang** dans tout le corps (2 pts).", "3. Se laver avec **eau et savon** ; couper les **ongles** (2 pts).", "4. Contre les **microbes**, le **soleil** et les **coups** (2 pts)."]},
],
}
