# -*- coding: utf-8 -*-
"""Contenu Bimestre 5 — Séances 7 à 15 (Blocs 3-5) + Révision générale + Examen."""

SEANCES_B = [
{
"n": 7, "titre": "Les vers intestinaux", "theme": "Les vers intestinaux",
"objectif": "énumérer les différentes sortes de vers intestinaux",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma des vers intestinaux affiché au tableau",
"image": ("svt9e_vers_intestinaux.png", "Schéma : deux vers intestinaux : l'ascaris, long et rond, et le ténia, long et plat."),
"revision": [
    ("Que faut-il faire dès les premiers signes du paludisme ?", "Aller vite au centre de santé."),
    ("Comment prend-on les médicaments ?", "Comme l'a dit l'agent de santé, jusqu'au bout."),
],
"situation": "Mamy a souvent mal au ventre et il est fatigué. Au centre de santé, l'agent de santé lui dit : « Ce sont des vers dans ton ventre. » Quels vers peuvent vivre dans notre ventre ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les vers intestinaux.",
    "Je lis le titre au tableau : Les vers intestinaux.",
],
"observation": [
    "Regardez le schéma des vers intestinaux affiché au tableau.",
    "Comparez les deux vers : l'un est rond, l'autre est plat.",
],
"analyse": [
    ("Quels vers peuvent vivre dans l'intestin ?", "L'ascaris, le ténia et les oxyures peuvent vivre dans l'intestin."),
    ("Comment est l'ascaris ?", "L'ascaris est un ver long, rond et rose."),
    ("Comment est le ténia ?", "Le ténia est un ver long, plat et blanc, fait de petits anneaux."),
],
"synthese": "Les vers intestinaux sont l'ascaris, long et rond ; le ténia, long et plat ; et les oxyures, petits et blancs.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les vers peuvent vivre dans l'intestin.", "2. L'ascaris est un ver plat.", "3. Le ténia est fait d'anneaux.", "4. Les oxyures sont de gros vers."],
     "cor": ["1. **Vrai** : c'est leur maison.", "2. **Faux** : l'ascaris est rond.", "3. **Vrai** : de petits anneaux.", "4. **Faux** : ils sont petits et blancs."]},
    {"c": "Complète avec les mots suivants : ascaris, ténia, oxyures, vers.",
     "items": ["1. Le ver long et rond s'appelle l'...", "2. Le ver long et plat s'appelle le ...", "3. Les petits vers blancs sont les ...", "4. Ce sont des ... intestinaux."],
     "cor": ["1. L'**ascaris**.", "2. Le **ténia**.", "3. Les **oxyures**.", "4. Des **vers** intestinaux."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Où vivent les vers intestinaux ? A. Dans l'œil B. Dans l'intestin C. Dans l'oreille", "2. Comment est l'ascaris ? A. Long et rond B. Court et plat C. Carré", "3. Comment est le ténia ? A. Rond et rose B. Plat et blanc C. Petit et bleu", "4. Quels sont les petits vers blancs ? A. Les oxyures B. Les ascariis C. Les ténias"],
     "cor": ["1. **B. Dans l'intestin**.", "2. **A. Long et rond**.", "3. **B. Plat et blanc**.", "4. **A. Les oxyures**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite trois sortes de vers intestinaux.", "2. Comment est l'ascaris ?", "3. Comment est le ténia ?", "4. Que ressent un enfant qui a des vers ?"],
     "cor": ["1. L'**ascaris**, le **ténia** et les **oxyures**.", "2. **Long**, **rond** et **rose**.", "3. **Long**, **plat** et **blanc**, fait d'anneaux.", "4. Il a **mal au ventre** et il est **fatigué**."]},
],
"lecon": [
    (None, ["Des **vers** peuvent vivre dans notre **intestin** : ce sont les **vers intestinaux**. Ils volent la nourriture du corps."]),
    ("1. Les trois sortes de vers", ["L'**ascaris** est un ver **long** et **rond**, rose. Le **ténia** est un ver **long** et **plat**, blanc, fait de petits **anneaux**. Les **oxyures** sont de **petits vers blancs**."]),
    ("2. Les signes", ["Un enfant qui a des vers a souvent **mal au ventre** et il est **fatigué**. Il faut aller au **centre de santé** : des médicaments font sortir les vers."]),
],
"mots_cles": ["vers", "ascaris", "ténia", "oxyures", "intestin"],
},
{
"n": 8, "titre": "Éviter les vers intestinaux", "theme": "Les vers intestinaux",
"objectif": "connaître les mesures pour ne pas attraper de vers intestinaux",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "un fruit propre apporté en classe",
"image": None,
"revision": [
    ("Cite trois sortes de vers intestinaux.", "L'ascaris, le ténia et les oxyures."),
    ("Comment est le ténia ?", "Long, plat et blanc, fait d'anneaux."),
],
"situation": "Koto marche pieds nus près de la maison et mange des fruits sans les laver. Comment les vers entrent-ils dans le corps ? Et comment les éviter ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à éviter les vers intestinaux.",
    "Je lis le titre au tableau : Éviter les vers intestinaux.",
],
"observation": [
    "Regardez ce fruit propre : il est bon à manger.",
    "Regardez vos pieds : portez-vous des chaussures ?",
],
"analyse": [
    ("Comment les vers entrent-ils dans le corps ?", "Par la bouche, avec les aliments ou les mains sales, et par la peau des pieds nus."),
    ("Que faut-il faire avant de manger ?", "Il faut se laver les mains et laver les fruits et les légumes."),
    ("Pourquoi porter des chaussures ?", "Les chaussures empêchent les vers de passer par la peau des pieds."),
],
"synthese": "Je me lave les mains, je lave les fruits, je porte des chaussures et je vais aux latrines.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Les vers entrent par la bouche.", "2. Les fruits sales transportent des œufs de vers.", "3. On peut marcher pieds nus sans danger.", "4. Il faut se laver les mains avant de manger."],
     "cor": ["1. **Vrai** : avec les aliments ou les mains sales.", "2. **Vrai** : il faut les laver.", "3. **Faux** : les vers passent par la peau des pieds nus.", "4. **Vrai** : avec de l'eau et du savon."]},
    {"c": "Complète avec les mots suivants : mains, fruits, chaussures, latrines.",
     "items": ["1. Je me lave les ... avant de manger.", "2. Je lave les ... et les légumes.", "3. Je porte des ...", "4. Je vais aux ... propres."],
     "cor": ["1. Les **mains**.", "2. Les **fruits** et les légumes.", "3. Des **chaussures**.", "4. Aux **latrines** propres."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Par où les vers entrent-ils ? A. Par la bouche et la peau des pieds B. Par les oreilles C. Par les yeux", "2. Que lave-t-on avant de manger ? A. Rien B. Les mains et les fruits C. Les pieds seulement", "3. Que portent les pieds ? A. Des chaussures B. Rien C. Des feuilles", "4. Où fait-on ses besoins ? A. N'importe où B. Dans les latrines C. Près du puits"],
     "cor": ["1. **A. Par la bouche et la peau des pieds**.", "2. **B. Les mains et les fruits**.", "3. **A. Des chaussures**.", "4. **B. Dans les latrines**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Comment les vers entrent-ils dans le corps ?", "2. Pourquoi lave-t-on les fruits ?", "3. Pourquoi porte-t-on des chaussures ?", "4. Cite deux mesures pour éviter les vers."],
     "cor": ["1. Par la **bouche** et par la **peau des pieds nus**.", "2. Pour **enlever les œufs de vers** et la saleté.", "3. Pour **empêcher les vers** de passer par la peau.", "4. **Se laver les mains** et **aller aux latrines propres**."]},
],
"lecon": [
    (None, ["Les **vers intestinaux** s'attrapent facilement. De bons gestes simples les **évitent**."]),
    ("1. Comment les vers entrent", ["Les **œufs de vers** entrent par la **bouche** : avec les **aliments** ou les **mains sales**. Les vers peuvent aussi passer par la **peau des pieds nus**."]),
    ("2. Les bons gestes", ["Je me **lave les mains** avant de manger et après les latrines. Je **lave les fruits** et les légumes. Je porte des **chaussures**. Je vais aux **latrines propres** : les vers ne doivent pas salir la terre de la cour."]),
],
"mots_cles": ["œufs de vers", "mains sales", "fruits", "chaussures", "latrines"],
},
{
"n": 9, "titre": "La rougeole, la varicelle et la coqueluche", "theme": "Les maladies infantiles",
"objectif": "faire la distinction entre la rougeole, la varicelle et la coqueluche",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "l'image de l'enfant qui a des boutons, affichée au tableau",
"image": ("svt9e_varicelle.png", "Image : Rova a des boutons sur tout le corps : c'est la varicelle."),
"revision": [
    ("Comment les vers entrent-ils dans le corps ?", "Par la bouche et par la peau des pieds nus."),
    ("Pourquoi porte-t-on des chaussures ?", "Pour empêcher les vers de passer par la peau."),
],
"situation": "Rova a des boutons rouges partout sur le corps. Son cousin a une grosse toux qui fait « coq, coq ! ». Quelles sont ces maladies des enfants ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre trois maladies des enfants.",
    "Je lis le titre au tableau : La rougeole, la varicelle et la coqueluche.",
],
"observation": [
    "Regardez l'image de l'enfant qui a des boutons.",
    "Dites ce que vous voyez sur sa peau.",
],
"analyse": [
    ("Quels sont les signes de la rougeole ?", "La rougeole donne la fièvre et des boutons rouges sur tout le corps."),
    ("Quels sont les signes de la varicelle ?", "La varicelle donne des boutons remplis d'eau qui grattent."),
    ("Quel est le signe de la coqueluche ?", "La coqueluche donne une grosse toux qui fait « coq, coq ! »"),
],
"synthese": "La rougeole donne fièvre et boutons rouges, la varicelle des boutons d'eau qui grattent, la coqueluche une toux qui fait « coq ».",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La rougeole donne des boutons rouges.", "2. La varicelle donne des boutons remplis d'eau.", "3. La coqueluche donne mal au pied.", "4. Ces maladies sont contagieuses."],
     "cor": ["1. **Vrai** : des boutons rouges.", "2. **Vrai** : des boutons d'eau qui grattent.", "3. **Faux** : elle donne une grosse toux.", "4. **Vrai** : elles se transmettent vite."]},
    {"c": "Complète avec les mots suivants : rougeole, varicelle, coqueluche, toux.",
     "items": ["1. La fièvre et les boutons rouges, c'est la ...", "2. Les boutons d'eau qui grattent, c'est la ...", "3. La grosse toux « coq, coq ! », c'est la ...", "4. La coqueluche fait tousser, avec une grosse ..."],
     "cor": ["1. La **rougeole**.", "2. La **varicelle**.", "3. La **coqueluche**.", "4. Une grosse **toux**."]},
],
"evaluation": [
    {"c": "Relie chaque maladie à son signe.",
     "items": ["1. La rougeole — a. boutons remplis d'eau", "2. La varicelle — b. toux qui fait « coq, coq ! »", "3. La coqueluche — c. fièvre et boutons rouges", "4. Les trois maladies — d. maladies contagieuses des enfants"],
     "cor": ["1. La **rougeole** : **c**. fièvre et boutons rouges.", "2. La **varicelle** : **a**. boutons remplis d'eau.", "3. La **coqueluche** : **b**. toux qui fait « coq, coq ! ».", "4. Ce sont des **maladies contagieuses** : **d**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quels sont les signes de la rougeole ?", "2. Quels sont les signes de la varicelle ?", "3. Quel est le signe de la coqueluche ?", "4. Que faut-il faire quand un enfant a ces signes ?"],
     "cor": ["1. La **fièvre** et des **boutons rouges** partout.", "2. Des **boutons remplis d'eau** qui **grattent**.", "3. Une **grosse toux** qui fait « **coq, coq !** ».", "4. **Prévenir les parents** et aller au **centre de santé**."]},
],
"lecon": [
    (None, ["La **rougeole**, la **varicelle** et la **coqueluche** sont des **maladies contagieuses** des enfants. Il faut savoir les distinguer."]),
    ("1. Les trois maladies", ["La **rougeole** donne la **fièvre** et des **boutons rouges** sur tout le corps. La **varicelle** donne des **boutons remplis d'eau** qui **grattent**. La **coqueluche** donne une **grosse toux** qui fait « **coq, coq !** »."]),
    ("2. Que faire ?", ["Ces maladies se **transmettent** très vite, surtout entre enfants. Devant ces signes, on **prévient les parents** et on va au **centre de santé**. Le malade reste à la maison pour ne pas transmettre la maladie."]),
],
"mots_cles": ["rougeole", "varicelle", "coqueluche", "boutons", "contagieuse"],
},
{
"n": 10, "titre": "Les vaccins protègent les enfants", "theme": "Les maladies infantiles",
"objectif": "connaître les vaccins à faire",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "l'image de la vaccination affichée au tableau",
"image": ("svt9e_vaccination.png", "Image : l'infirmière vaccine un enfant au centre de santé."),
"revision": [
    ("Quels sont les signes de la rougeole ?", "La fièvre et des boutons rouges partout."),
    ("Que faire devant ces signes ?", "Prévenir les parents et aller au centre de santé."),
],
"situation": "Au centre de santé, l'infirmière vaccine le petit frère de Soa. « C'est pour le protéger contre les maladies », dit la maman. Contre quoi les vaccins protègent-ils ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à quoi servent les vaccins.",
    "Je lis le titre au tableau : Les vaccins protègent les enfants.",
],
"observation": [
    "Regardez l'image de la vaccination affichée au tableau.",
    "Dites : avez-vous déjà été vaccinés ? Où ?",
],
"analyse": [
    ("Qu'est-ce qu'un vaccin ?", "Un vaccin est un médicament qui protège le corps contre une maladie."),
    ("Contre quelles maladies vaccine-t-on les enfants ?", "Contre la rougeole, la coqueluche, la poliomyélite et d'autres maladies."),
    ("Quand faut-il vacciner les enfants ?", "Dès le plus jeune âge, selon le calendrier du centre de santé."),
],
"synthese": "Le vaccin protège le corps contre les maladies. Les enfants doivent être vaccinés selon le calendrier du centre de santé.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le vaccin protège contre les maladies.", "2. On vaccine contre la rougeole.", "3. Les enfants n'ont pas besoin de vaccins.", "4. Il faut suivre le calendrier du centre de santé."],
     "cor": ["1. **Vrai** : il protège le corps.", "2. **Vrai** : aussi contre la coqueluche.", "3. **Faux** : les vaccins les protègent.", "4. **Vrai** : dès le plus jeune âge."]},
    {"c": "Complète avec les mots suivants : vaccin, rougeole, calendrier, centre de santé.",
     "items": ["1. Le ... protège le corps.", "2. On vaccine contre la ...", "3. On suit le ... des vaccinations.", "4. On va au ... pour se faire vacciner."],
     "cor": ["1. Le **vaccin** protège.", "2. Contre la **rougeole**.", "3. Le **calendrier**.", "4. Au **centre de santé**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que fait le vaccin ? A. Il rend malade B. Il protège contre la maladie C. Rien", "2. Contre quoi vaccine-t-on les enfants ? A. La rougeole B. Le paludisme seulement C. Rien", "3. Qui vaccine les enfants ? A. L'infirmière B. Le maçon C. Le pêcheur", "4. Où va-t-on pour se faire vacciner ? A. Au marché B. Au centre de santé C. À l'école seulement"],
     "cor": ["1. **B. Il protège contre la maladie**.", "2. **A. La rougeole** (et la coqueluche, la poliomyélite).", "3. **A. L'infirmière**.", "4. **B. Au centre de santé**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce qu'un vaccin ?", "2. Contre quelles maladies vaccine-t-on les enfants ?", "3. Qui vaccine les enfants ?", "4. Pourquoi faut-il vacciner les enfants ?"],
     "cor": ["1. Un **médicament** qui **protège** contre une maladie.", "2. Contre la **rougeole**, la **coqueluche**, la **poliomyélite** et d'autres.", "3. L'**infirmière**, au centre de santé.", "4. Pour **protéger leur corps** contre les maladies graves."]},
],
"lecon": [
    (None, ["Les **vaccins** sont une grande protection pour les enfants. Un enfant vacciné est un enfant protégé."]),
    ("1. Qu'est-ce qu'un vaccin ?", ["Un **vaccin** est un **médicament** qui apprend au corps à se **défendre** contre une **maladie**. Il se donne par une petite **piqûre**."]),
    ("2. Le calendrier des vaccins", ["On vaccine les enfants contre la **rougeole**, la **coqueluche**, la **poliomyélite** et d'autres maladies. Il faut suivre le **calendrier** du **centre de santé**, dès le plus jeune âge."]),
],
"mots_cles": ["vaccin", "protéger", "piqûre", "calendrier", "centre de santé"],
},
{
"n": 11, "titre": "L'habitat : les pièces et les accessoires", "theme": "L'habitat",
"objectif": "énumérer les pièces et les accessoires nécessaires d'une maison",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma de la maison affiché au tableau",
"image": ("svt9e_habitat.png", "Schéma : la maison et ses accessoires : toit, mur, porte, fenêtre, latrines et puits."),
"revision": [
    ("Qu'est-ce qu'un vaccin ?", "Un médicament qui protège contre une maladie."),
    ("Où va-t-on pour se faire vacciner ?", "Au centre de santé."),
],
"situation": "La famille de Hery construit une nouvelle maison. Que faut-il prévoir pour que la maison soit confortable et saine ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre ce qu'il faut dans une bonne maison.",
    "Je lis le titre au tableau : L'habitat : les pièces et les accessoires.",
],
"observation": [
    "Regardez le schéma de la maison affiché au tableau.",
    "Nommez ce que vous voyez sur la maison et autour d'elle.",
],
"analyse": [
    ("Quelles pièces une maison doit-elle avoir ?", "Une pièce pour dormir, une cuisine et un endroit pour se laver."),
    ("Quels accessoires faut-il prévoir ?", "Il faut une porte, une fenêtre et un toit solide."),
    ("Où installe-t-on les latrines et le puits ?", "On les installe loin l'un de l'autre, pour que l'eau reste propre."),
],
"synthese": "Une bonne maison a une pièce pour dormir, une cuisine, une fenêtre, un toit solide, des latrines et un puits éloignés l'un de l'autre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La maison doit avoir une pièce pour dormir.", "2. La fenêtre laisse entrer l'air et la lumière.", "3. Le toit ne sert à rien.", "4. Les latrines se mettent loin du puits."],
     "cor": ["1. **Vrai** : pour se reposer.", "2. **Vrai** : l'air et la lumière sont bons.", "3. **Faux** : il protège de la pluie.", "4. **Vrai** : pour garder l'eau propre."]},
    {"c": "Complète avec les mots suivants : fenêtre, toit, latrines, puits.",
     "items": ["1. La ... laisse entrer l'air et la lumière.", "2. Le ... protège de la pluie et du soleil.", "3. Les ... sont éloignées de la maison.", "4. Le ... donne de l'eau propre."],
     "cor": ["1. La **fenêtre**.", "2. Le **toit**.", "3. Les **latrines**.", "4. Le **puits**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quelle pièce sert à dormir ? A. La cuisine B. La chambre C. Le poulailler", "2. Qu'est-ce qui laisse entrer l'air ? A. Le mur B. La fenêtre C. Le sol", "3. Où met-on les latrines ? A. Près du puits B. Loin du puits C. Dans la chambre", "4. À quoi sert le toit ? A. À protéger de la pluie B. À dormir C. À cuisiner"],
     "cor": ["1. **B. La chambre**.", "2. **B. La fenêtre**.", "3. **B. Loin du puits**.", "4. **A. À protéger de la pluie**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite les pièces d'une maison.", "2. À quoi sert la fenêtre ?", "3. Pourquoi les latrines sont-elles loin du puits ?", "4. Pourquoi garder la maison propre ?"],
     "cor": ["1. La **chambre** (pour dormir), la **cuisine** et un endroit pour **se laver**.", "2. À laisser entrer l'**air** et la **lumière**.", "3. Pour que l'**eau du puits reste propre**.", "4. Pour **éviter les microbes** et les maladies."]},
],
"lecon": [
    (None, ["Notre **maison** protège la famille : il faut qu'elle soit **confortable** et **saine**."]),
    ("1. Les pièces et les accessoires", ["Une bonne maison a une **chambre** pour dormir, une **cuisine** pour préparer les repas et un endroit pour **se laver**. La **fenêtre** laisse entrer l'**air** et la **lumière** ; le **toit** protège de la pluie et du soleil."]),
    ("2. Une maison saine", ["Les **latrines** sont installées **loin du puits**, pour que l'**eau reste propre**. On garde la **cour propre**, on balaie la maison et on sort les ordures : une maison propre éloigne les **microbes** et les moustiques."]),
],
"mots_cles": ["chambre", "fenêtre", "toit", "latrines", "puits"],
},
{
"n": 12, "titre": "La poule et ses variétés", "theme": "La poule",
"objectif": "décrire la poule et élever des poules convenablement",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma de la poule affiché au tableau",
"image": ("svt9e_poule.png", "Schéma : la poule : la crête, le bec, les ailes, les pattes et la queue."),
"revision": [
    ("Cite les pièces d'une maison.", "La chambre, la cuisine et un endroit pour se laver."),
    ("Pourquoi les latrines sont-elles loin du puits ?", "Pour que l'eau du puits reste propre."),
],
"situation": "Dans la cour, Nivo observe les poules : une noire, une rousse, une blanche. Comment reconnaît-on une poule ? Comment bien l'élever ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à connaître la poule.",
    "Je lis le titre au tableau : La poule et ses variétés.",
],
"observation": [
    "Regardez le schéma de la poule affiché au tableau.",
    "Nommez ses parties : la crête, le bec, les ailes, les pattes, la queue.",
],
"analyse": [
    ("Comment reconnaît-on une poule ?", "La poule a deux pattes, deux ailes, un bec et une crête sur la tête."),
    ("Quelles sont les variétés de poules ?", "Les variétés se reconnaissent à la couleur des plumes : noires, rousses, blanches."),
    ("Comment élève-t-on bien les poules ?", "On leur donne de l'eau, des graines, un abri propre et on les vaccine."),
],
"synthese": "La poule a deux pattes, deux ailes, un bec et une crête. On l'élève bien avec de l'eau, des graines et un abri propre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La poule a deux pattes.", "2. La crête est sur la tête de la poule.", "3. La poule n'a pas d'ailes.", "4. Les poules se reconnaissent par la couleur des plumes."],
     "cor": ["1. **Vrai** : deux pattes.", "2. **Vrai** : la crête est rouge.", "3. **Faux** : elle a deux ailes.", "4. **Vrai** : noires, rousses ou blanches."]},
    {"c": "Complète avec les mots suivants : crête, bec, graines, abri.",
     "items": ["1. La ... est rouge, sur la tête.", "2. La poule mange avec son ...", "3. On lui donne de l'eau et des ...", "4. La poule dort dans un ... propre."],
     "cor": ["1. La **crête** est rouge.", "2. Avec son **bec**.", "3. Des **graines**.", "4. Un **abri** propre."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Combien la poule a-t-elle de pattes ? A. Deux B. Quatre C. Six", "2. Qu'est-ce qui est rouge sur sa tête ? A. Le bec B. La crête C. La queue", "3. Que mange la poule ? A. Des graines B. Des pierres C. Des clous", "4. Où dort la poule ? A. Dans un abri propre B. Dans la boue C. Dans la maison"],
     "cor": ["1. **A. Deux**.", "2. **B. La crête**.", "3. **A. Des graines**.", "4. **A. Dans un abri propre**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Comment reconnaît-on une poule ?", "2. Comment distingue-t-on les variétés de poules ?", "3. Que mange la poule ?", "4. Cite deux soins à donner aux poules."],
     "cor": ["1. À ses **deux pattes**, ses **deux ailes**, son **bec** et sa **crête**.", "2. Par la **couleur des plumes** : noires, rousses, blanches.", "3. Des **graines**, des **restes** et des **insectes**.", "4. Donner de l'**eau propre** et un **abri propre**, et la **vacciner**."]},
],
"lecon": [
    (None, ["La **poule** est un oiseau de la basse-cour, très utile pour la famille."]),
    ("1. Décrire la poule", ["La poule a **deux pattes**, **deux ailes**, un **bec** et une **crête** rouge sur la tête. Les **variétés** se distinguent par la **couleur des plumes** : noires, rousses, blanches."]),
    ("2. Bien l'élever", ["La poule mange des **graines**, des **restes** de cuisine et des **insectes**. Il faut lui donner de l'**eau propre**, un **abri propre** et la **vacciner** contre les maladies. La poule donne des **œufs** et de la viande."]),
],
"mots_cles": ["crête", "bec", "ailes", "variétés", "abri", "œufs"],
},
{
"n": 13, "titre": "Le zébu", "theme": "Le zébu",
"objectif": "décrire un zébu et connaître son utilité",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma du zébu affiché au tableau",
"image": ("svt9e_zebu.png", "Schéma : le zébu : la bosse, les cornes, le fanon, la queue et les sabots."),
"revision": [
    ("Comment reconnaît-on une poule ?", "À ses deux pattes, deux ailes, son bec et sa crête."),
    ("Que donne la poule ?", "Des œufs et de la viande."),
],
"situation": "Le papa de Mamy possède un troupeau de zébus. Le zébu est l'animal préféré des Malgaches. Pourquoi ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à connaître le zébu.",
    "Je lis le titre au tableau : Le zébu.",
],
"observation": [
    "Regardez le schéma du zébu affiché au tableau.",
    "Nommez ses parties : la bosse, les cornes, le fanon, la queue, les sabots.",
],
"analyse": [
    ("Comment reconnaît-on le zébu ?", "Le zébu a une bosse sur le dos, des cornes et un fanon sous le cou."),
    ("À quoi sert le zébu ?", "Il donne sa viande et son lait, et il tire la charrette."),
    ("Comment s'occupe-t-on du zébu ?", "On lui donne de l'eau, de l'herbe et un abri, et on le vaccine."),
],
"synthese": "Le zébu a une bosse, des cornes et un fanon. Il donne viande et lait et tire la charrette. Il faut bien s'en occuper.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Le zébu a une bosse sur le dos.", "2. Le fanon est sous le cou du zébu.", "3. Le zébu ne sert à rien.", "4. Le zébu tire la charrette."],
     "cor": ["1. **Vrai** : c'est sa marque.", "2. **Vrai** : sous le cou.", "3. **Faux** : il donne viande et lait.", "4. **Vrai** : il aide aux travaux."]},
    {"c": "Complète avec les mots suivants : bosse, cornes, lait, eau.",
     "items": ["1. Le zébu a une ... sur le dos.", "2. Il a des ... sur la tête.", "3. Il donne du ...", "4. On lui donne de l'... et de l'herbe."],
     "cor": ["1. Une **bosse** sur le dos.", "2. Des **cornes** sur la tête.", "3. Du **lait**.", "4. De l'**eau** et de l'herbe."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Qu'est-ce qui est sur le dos du zébu ? A. La bosse B. Le fanon C. La crête", "2. Que donne le zébu ? A. Des œufs B. De la viande et du lait C. Des fruits", "3. Que tire le zébu ? A. La charrette B. L'avion C. Le bateau", "4. Comment s'occupe-t-on du zébu ? A. On le laisse seul B. Eau, herbe et vaccins C. On le chasse"],
     "cor": ["1. **A. La bosse**.", "2. **B. De la viande et du lait**.", "3. **A. La charrette**.", "4. **B. Eau, herbe et vaccins**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Comment reconnaît-on le zébu ?", "2. À quoi sert le zébu ?", "3. Que mange le zébu ?", "4. Pourquoi le zébu est-il important à Madagascar ?"],
     "cor": ["1. À sa **bosse**, ses **cornes** et son **fanon**.", "2. Il donne la **viande** et le **lait** et tire la **charrette**.", "3. De l'**herbe**, et il boit de l'**eau**.", "4. Il aide la famille dans les **travaux** et la **nourrit**."]},
],
"lecon": [
    (None, ["Le **zébu** est un grand animal à cornes. C'est l'animal le plus important de l'élevage à Madagascar."]),
    ("1. Décrire le zébu", ["Le zébu a une **bosse** sur le dos, des **cornes** sur la tête et un **fanon** sous le cou. Il marche sur ses **sabots**."]),
    ("2. Son utilité et ses soins", ["Le zébu donne la **viande** et le **lait**, et il tire la **charrette**. On lui donne de l'**eau**, de l'**herbe** et un **abri**, et on le **vaccine** contre les maladies."]),
],
"mots_cles": ["bosse", "cornes", "fanon", "lait", "charrette"],
},
{
"n": 14, "titre": "L'arbre et l'air", "theme": "L'arbre et l'air",
"objectif": "connaître l'utilité de l'arbre et prouver l'existence de l'air",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "le schéma de l'arbre affiché au tableau",
"image": ("svt9e_arbre.png", "Schéma : l'arbre : les feuilles, les branches, le tronc et les racines."),
"revision": [
    ("Comment reconnaît-on le zébu ?", "À sa bosse, ses cornes et son fanon."),
    ("À quoi sert le zébu ?", "Il donne viande et lait et tire la charrette."),
],
"situation": "Il fait chaud. Aina s'assoit à l'ombre du grand manguier. Les feuilles bougent : le vent souffle. À quoi sert l'arbre ? Et qu'est-ce que l'air ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'utilité de l'arbre et l'existence de l'air.",
    "Je lis le titre au tableau : L'arbre et l'air.",
],
"observation": [
    "Regardez le schéma de l'arbre affiché au tableau.",
    "Soufflez sur votre main : sentez-vous l'air qui sort de votre bouche ?",
],
"analyse": [
    ("Comment prouve-t-on que l'air existe ?", "L'air existe : il fait bouger les feuilles et les drapeaux, et nous le respirons."),
    ("À quoi sert l'arbre ?", "L'arbre donne des fruits, du bois et de l'ombre."),
    ("Que fait l'arbre pour l'air et le sol ?", "L'arbre purifie l'air et ses racines retiennent le sol."),
],
"synthese": "L'air existe : on le sent et on le respire. L'arbre donne fruits, bois et ombre, purifie l'air et retient le sol.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'air fait bouger les feuilles.", "2. L'arbre donne des fruits.", "3. L'arbre purifie l'air.", "4. Les racines ne servent à rien."],
     "cor": ["1. **Vrai** : c'est le vent.", "2. **Vrai** : et du bois.", "3. **Vrai** : il rend l'air pur.", "4. **Faux** : elles retiennent le sol."]},
    {"c": "Complète avec les mots suivants : air, fruits, racines, bois.",
     "items": ["1. Le vent, c'est de l'... qui bouge.", "2. L'arbre donne des ...", "3. L'arbre donne du ... pour construire.", "4. Les ... retiennent le sol."],
     "cor": ["1. De l'**air** qui bouge.", "2. Des **fruits**.", "3. Du **bois** pour construire.", "4. Les **racines** retiennent le sol."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Comment sait-on que l'air existe ? A. On le voit dans un sac B. Il fait bouger les feuilles C. Il a une couleur", "2. Que donne l'arbre ? A. Des fruits et du bois B. Des pierres C. De l'huile", "3. Que fait l'arbre pour l'air ? A. Il le salit B. Il le purifie C. Rien", "4. Que font les racines ? A. Elles retiennent le sol B. Elles volent C. Elles chantent"],
     "cor": ["1. **B. Il fait bouger les feuilles**.", "2. **A. Des fruits et du bois**.", "3. **B. Il le purifie**.", "4. **A. Elles retiennent le sol**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Comment prouve-t-on que l'air existe ?", "2. À quoi sert l'arbre ?", "3. Que fait l'arbre pour l'air ?", "4. Pourquoi faut-il planter des arbres ?"],
     "cor": ["1. L'**air fait bouger les feuilles** et on le **respire**.", "2. Il donne des **fruits**, du **bois** et de l'**ombre**.", "3. Il **purifie l'air** et donne de l'oxygène.", "4. Pour **purifier l'air** et **retenir le sol**."]},
],
"lecon": [
    (None, ["L'**arbre** est une plante précieuse. Il travaille en silence pour notre santé et pour la terre."]),
    ("1. L'air existe", ["L'**air** est partout autour de nous, même si on ne le voit pas : il **fait bouger les feuilles**, les drapeaux, et nous le **respirons**. L'air pur est bon pour la santé."]),
    ("2. L'utilité de l'arbre", ["L'**arbre** donne des **fruits** pour manger, du **bois** pour construire et de l'**ombre** pour se reposer. Il **purifie l'air**. Ses **racines retiennent le sol** : elles empêchent la terre de partir avec les pluies."]),
],
"mots_cles": ["air", "vent", "fruits", "bois", "racines", "sol"],
},
{
"n": 15, "titre": "L'eau potable", "theme": "L'eau",
"objectif": "obtenir de l'eau potable et gérer rationnellement l'eau",
"doc": "Répartition annuelle 9e, SVT, Bimestre 5",
"support_obs": "l'image de l'eau potable affichée au tableau",
"image": ("svt9e_eau_potable.png", "Image : l'eau propre du puits, que l'on filtre et que l'on fait bouillir."),
"revision": [
    ("Comment prouve-t-on que l'air existe ?", "Il fait bouger les feuilles et on le respire."),
    ("À quoi sert l'arbre ?", "Il donne fruits, bois et ombre et purifie l'air."),
],
"situation": "Voahangy a soif. Elle veut boire l'eau de la rivière. Sa maman l'arrête : « Il faut d'abord la rendre potable ! » Comment obtenir de l'eau potable ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à obtenir de l'eau potable.",
    "Je lis le titre au tableau : L'eau potable.",
],
"observation": [
    "Regardez l'image de l'eau potable affichée au tableau.",
    "Comparez : un verre d'eau claire et un verre d'eau trouble.",
],
"analyse": [
    ("Qu'est-ce que l'eau potable ?", "L'eau potable est l'eau propre que l'on peut boire sans tomber malade."),
    ("Comment rendre l'eau potable ?", "On filtre l'eau, puis on la fait bouillir."),
    ("Comment économiser l'eau ?", "On ferme le robinet et on ne gaspille pas l'eau."),
],
"synthese": "L'eau potable est propre à boire : je la filtre et je la fais bouillir. Et je ne gaspille pas l'eau.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'eau potable est bonne à boire.", "2. Il faut faire bouillir l'eau pour la rendre potable.", "3. On peut boire l'eau de la rivière directement.", "4. Il faut économiser l'eau."],
     "cor": ["1. **Vrai** : sans danger.", "2. **Vrai** : la chaleur tue les microbes.", "3. **Faux** : il faut la filtrer et la bouillir.", "4. **Vrai** : l'eau est précieuse."]},
    {"c": "Complète avec les mots suivants : potable, filtrer, bouillir, gaspiller.",
     "items": ["1. L'eau bonne à boire est l'eau ...", "2. On fait ... l'eau pour enlever les saletés.", "3. On fait ... l'eau pour tuer les microbes.", "4. Il ne faut pas ... l'eau."],
     "cor": ["1. L'eau **potable**.", "2. **Filtrer** l'eau.", "3. **Bouillir** l'eau.", "4. **Gaspiller** l'eau."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Qu'est-ce que l'eau potable ? A. L'eau sale B. L'eau bonne à boire C. L'eau de la flaque", "2. Que fait-on d'abord à l'eau ? A. On la filtre B. On la jette C. On la boit", "3. Pourquoi fait-on bouillir l'eau ? A. Pour la refroidir B. Pour tuer les microbes C. Pour la saler", "4. Comment économiser l'eau ? A. En la gaspillant B. En fermant le robinet C. En la versant par terre"],
     "cor": ["1. **B. L'eau bonne à boire**.", "2. **A. On la filtre**.", "3. **B. Pour tuer les microbes**.", "4. **B. En fermant le robinet**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Qu'est-ce que l'eau potable ?", "2. Comment rend-on l'eau potable ?", "3. Pourquoi fait-on bouillir l'eau ?", "4. Comment économiser l'eau ?"],
     "cor": ["1. L'**eau potable** est l'eau propre qu'on peut **boire sans danger**.", "2. On la **filtre**, puis on la fait **bouillir**.", "3. Pour **tuer les microbes**.", "4. En **fermant le robinet** et en ne **gaspillant pas** l'eau."]},
],
"lecon": [
    (None, ["L'**eau potable** est l'eau propre que l'on peut **boire sans danger**. Toute l'eau n'est pas potable !"]),
    ("1. Rendre l'eau potable", ["L'eau de la rivière ou du puits peut porter des **microbes**. On la **filtre** pour enlever les saletés, puis on la fait **bouillir** : la chaleur **tue les microbes**. On garde l'eau dans un récipient **couvert** et propre."]),
    ("2. Économiser l'eau", ["L'**eau** est précieuse : je **ferme le robinet** quand je ne m'en sers pas, et je ne **gaspille** pas l'eau. Une eau bien gérée, c'est une famille en bonne santé."]),
],
"mots_cles": ["eau potable", "filtrer", "bouillir", "microbes", "économiser"],
},
]

REVISION_B5 = {
"titre": "Révision générale — Fin d'année",
"tableau": [
    ("B1 — Le corps humain", "Trois parties : tête, tronc, membres ; composantes : peau, os, muscles, organes."),
    ("B1 — Le membre supérieur et la peau", "Épaule, bras, coude, avant-bras, main, doigts ; la peau protège, touche et refroidit par la sueur."),
    ("B2 — Les maladies de la peau", "La gale et les poux : parasites ; hygiène : eau, savon, habits propres."),
    ("B2 — Les dents", "Incisives coupent, canines déchirent, molaires broient ; brossage matin et soir."),
    ("B2 — L'œil", "Sourcil, paupière, cils, pupille ; protéger ses yeux du soleil et des objets pointus."),
    ("B3 — Voir et entendre", "La lumière entre par la pupille ; le pavillon attrape le son, le tympan vibre."),
    ("B3 — La langue", "Organe du goût : sucré, salé, acide, amer ; aide à parler et à avaler."),
    ("B4 — Les membres inférieurs", "Cuisse, genou, mollet, cheville, pied, orteils ; hygiène des pieds."),
    ("B4 — La respiration", "Nez, bouche, gorge, poumons ; inspirer et expirer ; air pur."),
    ("B5 — La digestion", "Bouche, œsophage, estomac, intestin ; hygiène alimentaire."),
    ("B5 — Le paludisme", "Fièvre, frissons ; transmis par l'anophèle ; moustiquaire, centre de santé."),
    ("B5 — Les vers et les maladies infantiles", "Ascaris, ténia, oxyures ; rougeole, varicelle, coqueluche ; vaccins."),
    ("B5 — Habitat, poule, zébu", "Maison saine : fenêtre, latrines, puits ; la poule donne des œufs, le zébu le lait."),
    ("B5 — L'arbre, l'air et l'eau", "L'arbre purifie l'air et retient le sol ; l'eau potable : filtrer et bouillir."),
],
"questions": [
    ("Quelles sont les trois parties du corps ?", "La tête, le tronc et les membres."),
    ("Quelles sont les trois sortes de dents ?", "Les incisives, les canines et les molaires."),
    ("Par où la lumière entre-t-elle dans l'œil ?", "Par la pupille."),
    ("Quelles sont les quatre saveurs ?", "Le sucré, le salé, l'acide et l'amer."),
    ("Par où l'air entre-t-il quand on respire ?", "Par le nez et la bouche."),
    ("Quel est le trajet des aliments ?", "Bouche, œsophage, estomac, intestin."),
    ("Qui transmet le paludisme ?", "Le moustique anophèle."),
    ("Comment éviter les vers intestinaux ?", "Se laver les mains, laver les fruits, porter des chaussures."),
    ("À quoi servent les vaccins ?", "À protéger le corps contre les maladies."),
    ("Comment rendre l'eau potable ?", "La filtrer, puis la faire bouillir."),
],
}

EXAMEN_B5 = {
"titre": "Sujet d'examen 9e — Bimestre 5",
"duree": "30 min",
"total": 20,
"parties": [
    {"c": "Réponds par Vrai (V) ou Faux (F). (4 points)",
     "items": ["1. Le paludisme est transmis par le moustique anophèle.", "2. L'ascaris est un ver plat.", "3. Le vaccin protège contre les maladies.", "4. On boit l'eau de la rivière sans la faire bouillir."],
     "cor": ["1. **Vrai** (1 pt) : l'anophèle pique la nuit.", "2. **Faux** (1 pt) : l'ascaris est rond ; le ténia est plat.", "3. **Vrai** (1 pt) : contre la rougeole, la coqueluche.", "4. **Faux** (1 pt) : il faut la filtrer et la bouillir."]},
    {"c": "Complète avec les mots suivants : moustiquaire, œsophage, latrines, bouillir. (4 points)",
     "items": ["1. La nuit, je dors sous une ...", "2. Les aliments descendent par l'...", "3. On fait ses besoins dans les ...", "4. Pour rendre l'eau potable, on la fait ..."],
     "cor": ["1. Une **moustiquaire** (1 pt).", "2. L'**œsophage** (1 pt).", "3. Les **latrines** (1 pt).", "4. On la fait **bouillir** (1 pt)."]},
    {"c": "Entoure la bonne réponse. (4 points)",
     "items": ["1. Quels sont les symptômes du paludisme ? A. Fièvre et frissons B. Mal aux dents C. Mal au pied", "2. Quels vers sont petits et blancs ? A. Les ténias B. Les oxyures C. Les ascariis", "3. Que donne le zébu ? A. Des œufs B. Du lait et de la viande C. Des fruits", "4. Que fait l'arbre pour l'air ? A. Il le purifie B. Il le salit C. Rien"],
     "cor": ["1. **A. Fièvre et frissons** (1 pt).", "2. **B. Les oxyures** (1 pt).", "3. **B. Du lait et de la viande** (1 pt).", "4. **A. Il le purifie** (1 pt)."]},
    {"c": "Réponds par une phrase complète. (8 points)",
     "items": ["1. Décris le trajet des aliments.", "2. Comment éviter le paludisme ?", "3. Que faut-il faire dès les premiers signes du paludisme ?", "4. Cite deux mesures pour éviter les vers intestinaux."],
     "cor": ["1. **Bouche**, **œsophage**, **estomac**, **intestin** (2 pts).", "2. **Dormir sous une moustiquaire** et **vider les eaux stagnantes** (2 pts).", "3. Aller **vite au centre de santé** pour le test et le traitement (2 pts).", "4. **Se laver les mains** et **laver les fruits** (2 pts)."]},
],
}
