# -*- coding: utf-8 -*-
"""Contenu Bimestre 4 — Séances 1 à 6 (Blocs 1-2). Manuel SVT 9e J-Learn.
Conventions : **mot** = mot clé (bleu+gras dans la leçon, bordeaux dans les corrigés).
Niveau : 9e (~8 ans), phrases courtes, vocabulaire simple. Aucune date calendaire.
Bimestre court du programme officiel : 9 séances (membres supérieurs en santé,
membres inférieurs, appareil respiratoire).
"""

SEANCES_A = [
{
"n": 1, "titre": "Des mouvements simples pour la santé des bras", "theme": "Le membre supérieur en mouvement",
"objectif": "faire des mouvements simples pour la santé de ses membres supérieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 4",
"support_obs": "l'image de l'enfant qui fait des mouvements de bras, affichée au tableau",
"image": ("svt9e_mouvements_bras.png", "Image : Koto lève les bras et plie les coudes pour garder ses bras en bonne santé."),
"revision": [
    ("Que ne met-on jamais dans la bouche ?", "Jamais d'objets pointus."),
    ("Comment nettoie-t-on sa langue ?", "En la brossant doucement avec la brosse à dents."),
],
"situation": "Chaque matin avant la classe, Koto fait de petits mouvements avec ses bras : il les lève, les écarte, plie ses coudes et tourne ses poignets. Sa maîtresse dit que ces exercices gardent les bras en bonne santé. Quels mouvements pouvons-nous faire ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre des mouvements simples pour la santé des bras.",
    "Je lis le titre au tableau : Des mouvements simples pour la santé des bras.",
],
"observation": [
    "Regardez l'image de l'enfant qui fait des mouvements de bras.",
    "Debout, faites ces mouvements : levez les bras, écartez-les, pliez les coudes, tournez les poignets.",
],
"analyse": [
    ("Quels mouvements fait l'épaule ?", "L'épaule permet de lever et d'écarter les bras."),
    ("Quels mouvements fait le coude ?", "Le coude permet de plier et de tendre le bras."),
    ("Pourquoi bouger ses bras chaque jour ?", "Bouger chaque jour rend les muscles forts et les articulations souples."),
],
"synthese": "Pour garder des bras en bonne santé, je fais chaque jour des mouvements simples : lever, écarter, plier, tendre et tourner.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Lever les bras est bon pour la santé.", "2. Le coude permet de plier le bras.", "3. Bouger rend les muscles faibles.", "4. Il faut bouger ses bras chaque jour."],
     "cor": ["1. **Vrai** : lever les bras fait travailler l'épaule.", "2. **Vrai** : le coude plie le bras.", "3. **Faux** : bouger rend les muscles forts.", "4. **Vrai** : chaque jour, un peu."]},
    {"c": "Complète avec les mots suivants : lever, plier, tourner, muscles.",
     "items": ["1. Avec l'épaule, je peux ... les bras.", "2. Avec le coude, je peux ... le bras.", "3. Avec le poignet, je peux ... la main.", "4. Les mouvements rendent les ... forts."],
     "cor": ["1. **Lever** les bras.", "2. **Plier** le bras.", "3. **Tourner** la main.", "4. Les **muscles** forts."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel mouvement fait l'épaule ? A. Plier le bras B. Lever le bras C. Fermer la main", "2. Quel mouvement fait le coude ? A. Plier le bras B. Lever le bras C. Tourner le pied", "3. Que font les mouvements aux muscles ? A. Ils les rendent forts B. Ils les rendent faibles C. Rien", "4. Quand faire ces exercices ? A. Une fois par an B. Chaque jour C. Jamais"],
     "cor": ["1. **B. Lever le bras**.", "2. **A. Plier le bras**.", "3. **A. Ils les rendent forts**.", "4. **B. Chaque jour**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite deux mouvements simples des bras.", "2. Que permet de faire le coude ?", "3. Pourquoi bouger ses bras chaque jour ?", "4. Que permet de faire le poignet ?"],
     "cor": ["1. **Lever les bras** et **plier les coudes**.", "2. Le **coude** permet de **plier le bras**.", "3. Pour rendre les **muscles forts** et les **articulations souples**.", "4. Le **poignet** permet de **tourner la main**."]},
],
"lecon": [
    (None, ["Nos **bras** travaillent mieux quand ils bougent chaque jour. Les **mouvements** simples gardent les bras en bonne **santé**."]),
    ("1. Les bons mouvements", ["Avec l'**épaule**, je **lève** et j'**écarte** les bras. Avec le **coude**, je **plie** et je tends le bras. Avec le **poignet**, je **tourne** la main. J'ouvre et je ferme les **mains**."]),
    ("2. Bouger chaque jour", ["Je fais ces mouvements **chaque jour**, le matin avant la classe. Bouger rend les **muscles forts** et les **articulations souples**."]),
],
"mots_cles": ["mouvement", "lever", "plier", "tourner", "muscles"],
},
{
"n": 2, "titre": "Prendre soin de ses bras", "theme": "Le membre supérieur en mouvement",
"objectif": "connaître les soins à donner aux membres supérieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 4",
"support_obs": "un pansement propre apporté en classe",
"image": None,
"revision": [
    ("Quel mouvement fait l'épaule ?", "L'épaule permet de lever le bras."),
    ("Pourquoi bouger ses bras chaque jour ?", "Pour garder des muscles forts et des articulations souples."),
],
"situation": "En jouant, Mamy est tombé et s'est fait une petite plaie au coude. Sa maman lave la plaie avec de l'eau propre, puis elle met un pansement propre. Comment soigner et protéger nos bras ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à prendre soin de nos bras.",
    "Je lis le titre au tableau : Prendre soin de ses bras.",
],
"observation": [
    "Regardez ce pansement propre : à quoi sert-il ?",
    "Regardez vos coudes et vos mains : y a-t-il une petite plaie ?",
],
"analyse": [
    ("Que faut-il faire pour une petite plaie ?", "Il faut laver la plaie avec de l'eau propre, mettre un pansement propre et prévenir un adulte."),
    ("Que ne faut-il pas porter ?", "Il ne faut pas porter de charges trop lourdes."),
    ("Que faut-il faire quand le bras a mal ?", "Quand le bras a mal, il faut se reposer et prévenir un adulte."),
],
"synthese": "Je lave les petites plaies à l'eau propre, je mets un pansement propre et je préviens un adulte. Je ne porte pas trop lourd.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Une petite plaie se lave à l'eau propre.", "2. Le pansement protège la plaie.", "3. On peut porter des charges trop lourdes.", "4. Si le bras a mal, il faut prévenir un adulte."],
     "cor": ["1. **Vrai** : à l'eau propre.", "2. **Vrai** : il protège des microbes.", "3. **Faux** : cela fait mal aux bras.", "4. **Vrai** : il faut le dire à un adulte."]},
    {"c": "Complète avec les mots suivants : plaie, pansement, lourdes, reposer.",
     "items": ["1. Je lave la ... avec de l'eau propre.", "2. Je mets un ... propre.", "3. Je ne porte pas de charges ...", "4. Si le bras a mal, je me ..."],
     "cor": ["1. Je lave la **plaie**.", "2. Un **pansement** propre.", "3. De charges **lourdes**.", "4. Je me **repose**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Avec quoi lave-t-on une plaie ? A. De l'eau sale B. De l'eau propre C. De la boue", "2. Que met-on sur la plaie ? A. Un pansement propre B. Un chiffon sale C. Rien", "3. Que ne faut-il pas porter ? A. Un crayon B. Un cahier C. Une charge trop lourde", "4. Que faire si le bras a mal ? A. Continuer à jouer B. Se reposer et prévenir un adulte C. Cacher la douleur"],
     "cor": ["1. **B. De l'eau propre**.", "2. **A. Un pansement propre**.", "3. **C. Une charge trop lourde**.", "4. **B. Se reposer et prévenir un adulte**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faire pour une petite plaie au bras ?", "2. À quoi sert le pansement ?", "3. Pourquoi ne porte-t-on pas trop lourd ?", "4. Que faire si le bras fait très mal ?"],
     "cor": ["1. **Laver la plaie** à l'eau propre, mettre un **pansement** et **prévenir un adulte**.", "2. Il **protège la plaie** des microbes.", "3. Pour **ne pas faire mal aux bras** et au dos.", "4. **Prévenir un adulte** et aller au **centre de santé**."]},
],
"lecon": [
    (None, ["Nos **bras** peuvent se blesser : il faut savoir **prendre soin** d'eux."]),
    ("1. Les petites plaies", ["Pour une **petite plaie**, je la **lave** avec de l'**eau propre**, puis je mets un **pansement propre**. Le pansement protège la plaie des **microbes**. Je **préviens un adulte**."]),
    ("2. Ne pas forcer", ["Je ne porte pas de **charges trop lourdes** : cela fait mal aux bras et au dos. Si le **bras a mal**, je me **repose**. Si la douleur est forte, je le dis à mes parents et je vais au **centre de santé**."]),
],
"mots_cles": ["plaie", "pansement", "microbes", "charges", "reposer"],
},
{
"n": 3, "titre": "La sécurité des membres supérieurs", "theme": "Le membre supérieur en mouvement",
"objectif": "connaître les mesures de sécurité des membres supérieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 4",
"support_obs": "le schéma du membre supérieur affiché au tableau",
"image": None,
"revision": [
    ("Que faire pour une petite plaie ?", "La laver à l'eau propre et mettre un pansement propre."),
    ("Pourquoi ne porte-t-on pas trop lourd ?", "Pour ne pas faire mal aux bras et au dos."),
],
"situation": "Voahangy monte sur un arbre pour attraper un fruit. La branche casse et elle tombe sur son bras. Sa grande sœur court chercher un adulte. Quels dangers menacent nos bras ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre la sécurité des membres supérieurs.",
    "Je lis le titre au tableau : La sécurité des membres supérieurs.",
],
"observation": [
    "Regardez le schéma du membre supérieur affiché au tableau.",
    "Dites quels jeux de la cour sont dangereux pour les bras.",
],
"analyse": [
    ("Quels dangers menacent les bras ?", "Les chutes, les objets qui coupent et le feu menacent les bras."),
    ("Comment porter un seau d'eau sans se blesser ?", "On porte le seau près du corps, sans le remplir trop."),
    ("Que faire si un camarade tombe sur son bras ?", "Il ne faut pas bouger le bras qui fait très mal : on prévient un adulte."),
],
"synthese": "Je ne grimpe pas aux arbres, je ne joue pas avec les objets coupants ni le feu, et je porte les charges près du corps.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Grimper aux arbres est dangereux pour les bras.", "2. On peut jouer avec les couteaux.", "3. Le feu peut brûler les bras.", "4. Un seau trop lourd peut faire mal au bras."],
     "cor": ["1. **Vrai** : on peut tomber.", "2. **Faux** : les couteaux coupent.", "3. **Vrai** : le feu brûle.", "4. **Vrai** : il faut le porter près du corps."]},
    {"c": "Complète avec les mots suivants : chutes, couteaux, feu, corps.",
     "items": ["1. Les ... sont dangereuses pour les bras.", "2. Je ne joue pas avec les ...", "3. Je ne touche pas le ...", "4. Je porte les charges près du ..."],
     "cor": ["1. Les **chutes** sont dangereuses.", "2. Avec les **couteaux**.", "3. Le **feu**.", "4. Près du **corps**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quel jeu est dangereux pour les bras ? A. La marelle B. Grimper aux arbres C. Le ballon", "2. Que fait le feu aux bras ? A. Il les brûle B. Il les lave C. Rien", "3. Comment porte-t-on un seau ? A. Loin du corps B. Près du corps C. Sur la tête", "4. Que faire si un camarade tombe sur son bras ? A. Bouger son bras B. Prévenir un adulte C. Rire"],
     "cor": ["1. **B. Grimper aux arbres**.", "2. **A. Il les brûle**.", "3. **B. Près du corps**.", "4. **B. Prévenir un adulte**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite deux dangers pour les bras.", "2. Comment porte-t-on une charge ?", "3. Que faire en cas de chute sur le bras ?", "4. Pourquoi ne joue-t-on pas avec le feu ?"],
     "cor": ["1. Les **chutes** et les **objets qui coupent**.", "2. **Près du corps**, sans la remplir trop.", "3. **Ne pas bouger le bras** et **prévenir un adulte**.", "4. Parce que le **feu brûle** les bras et les mains."]},
],
"lecon": [
    (None, ["Les **bras** et les **mains** sont précieux : il faut les **protéger** des accidents."]),
    ("1. Éviter les accidents", ["Je ne **grimpe pas aux arbres** et je ne joue pas près des endroits qui glissent. Je ne joue pas avec les **couteaux**, les **lames** et le **feu**. Je porte les **charges près du corps**, jamais trop lourdes."]),
    ("2. Si l'accident arrive", ["Si un camarade **tombe sur son bras**, on ne **bouge pas** le bras qui fait très mal : on **prévient un adulte** et on va au **centre de santé**. Le bras cassé doit être soigné par un médecin."]),
],
"mots_cles": ["chute", "coupure", "brûlure", "charges", "médecin"],
},
{
"n": 4, "titre": "Les parties du membre inférieur", "theme": "Les membres inférieurs",
"objectif": "décrire ses membres inférieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 4",
"support_obs": "le schéma du membre inférieur affiché au tableau",
"image": ("svt9e_membre_inferieur.png", "Schéma : le membre inférieur : la cuisse, le genou, le mollet, la cheville, le pied et les orteils."),
"revision": [
    ("Cite deux dangers pour les bras.", "Les chutes et les objets qui coupent."),
    ("Que faire en cas de chute sur le bras ?", "Ne pas bouger le bras et prévenir un adulte."),
],
"situation": "Hery regarde sa jambe du haut en bas : la cuisse, le genou, le mollet, puis le pied avec ses orteils. Quelles sont les parties du membre inférieur ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les parties du membre inférieur.",
    "Je lis le titre au tableau : Les parties du membre inférieur.",
],
"observation": [
    "Regardez le schéma du membre inférieur affiché au tableau.",
    "Debout, touchez votre jambe : la cuisse, le genou, le mollet, la cheville, le pied.",
],
"analyse": [
    ("Comment s'appelle le haut de la jambe ?", "Le haut de la jambe s'appelle la cuisse."),
    ("Qu'est-ce qui plie au milieu de la jambe ?", "Le genou plie au milieu de la jambe."),
    ("Par quoi la jambe se termine-t-elle ?", "La jambe se termine par la cheville, le pied et les cinq orteils."),
],
"synthese": "Le membre inférieur comprend la cuisse, le genou, le mollet, la cheville, le pied et les cinq orteils.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La cuisse est le haut de la jambe.", "2. Le genou plie la jambe.", "3. Le mollet est devant la jambe.", "4. Le pied porte cinq orteils."],
     "cor": ["1. **Vrai** : la cuisse est en haut.", "2. **Vrai** : le genou plie.", "3. **Faux** : le mollet est derrière la jambe.", "4. **Vrai** : le pied a cinq orteils."]},
    {"c": "Complète avec les mots suivants : cuisse, genou, mollet, orteils.",
     "items": ["1. Le haut de la jambe s'appelle la ...", "2. Ce qui plie s'appelle le ...", "3. Derrière la jambe, il y a le ...", "4. Le pied porte cinq ..."],
     "cor": ["1. La **cuisse**.", "2. Le **genou**.", "3. Le **mollet**.", "4. Cinq **orteils**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Comment s'appelle le haut de la jambe ? A. Le mollet B. La cuisse C. Le pied", "2. Qu'est-ce qui plie la jambe ? A. Le genou B. La cheville C. Les orteils", "3. Où se trouve le mollet ? A. Devant la jambe B. Derrière la jambe C. Sur le pied", "4. Combien le pied a-t-il d'orteils ? A. Quatre B. Cinq C. Six"],
     "cor": ["1. **B. La cuisse**.", "2. **A. Le genou**.", "3. **B. Derrière la jambe**.", "4. **B. Cinq**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite les parties du membre inférieur.", "2. Où se trouve la cuisse ?", "3. Où se trouve le mollet ?", "4. Par quoi la jambe se termine-t-elle ?"],
     "cor": ["1. La **cuisse**, le **genou**, le **mollet**, la **cheville**, le **pied** et les **orteils**.", "2. La **cuisse** est le **haut** de la jambe.", "3. Le **mollet** est **derrière la jambe**.", "4. Par la **cheville**, le **pied** et les **orteils**."]},
],
"lecon": [
    (None, ["Le **membre inférieur** est la jambe. Il a plusieurs **parties**, de la cuisse jusqu'aux orteils."]),
    ("1. Le haut de la jambe", ["Le haut de la jambe s'appelle la **cuisse**. Au milieu, le **genou** plie la jambe."]),
    ("2. Le bas de la jambe", ["Derrière la jambe, il y a le **mollet**. En bas, la **cheville** attache le **pied**. Le pied porte **cinq orteils**."]),
],
"mots_cles": ["cuisse", "genou", "mollet", "cheville", "pied", "orteils"],
},
{
"n": 5, "titre": "Le fonctionnement du membre inférieur", "theme": "Les membres inférieurs",
"objectif": "comprendre le fonctionnement de ses membres inférieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 4",
"support_obs": "le schéma du membre inférieur affiché au tableau",
"image": None,
"revision": [
    ("Cite les parties du membre inférieur.", "La cuisse, le genou, le mollet, la cheville, le pied et les orteils."),
    ("Où se trouve le mollet ?", "Le mollet est derrière la jambe."),
],
"situation": "Nivo saute à la corde : ses genoux plient, ses chevilles bougent et ses pieds poussent le sol. Comment nos jambes nous font-elles marcher, courir et sauter ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment le membre inférieur fonctionne.",
    "Je lis le titre au tableau : Le fonctionnement du membre inférieur.",
],
"observation": [
    "Regardez le schéma du membre inférieur affiché au tableau.",
    "Marchez sur place, puis levez les genoux : qu'est-ce qui plie ?",
],
"analyse": [
    ("Quelles articulations font bouger la jambe ?", "La hanche, le genou et la cheville font bouger la jambe."),
    ("Que font les muscles de la jambe ?", "Les muscles tirent sur les os et font bouger la jambe."),
    ("À quoi servent les jambes ?", "Les jambes servent à marcher, courir et sauter."),
],
"synthese": "La hanche, le genou et la cheville sont des articulations. Les muscles font bouger la jambe pour marcher, courir et sauter.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La hanche est une articulation.", "2. Le genou plie la jambe.", "3. Les muscles ne servent pas à bouger.", "4. Les jambes servent à courir."],
     "cor": ["1. **Vrai** : la hanche est une articulation.", "2. **Vrai** : le genou plie.", "3. **Faux** : les muscles font bouger la jambe.", "4. **Vrai** : elles servent à courir."]},
    {"c": "Complète avec les mots suivants : hanche, genou, cheville, muscles.",
     "items": ["1. La ... attache la jambe au tronc.", "2. Le ... plie la jambe.", "3. La ... attache le pied.", "4. Les ... font bouger la jambe."],
     "cor": ["1. La **hanche** attache la jambe au tronc.", "2. Le **genou** plie la jambe.", "3. La **cheville** attache le pied.", "4. Les **muscles** font bouger la jambe."]},
],
"evaluation": [
    {"c": "Relie chaque articulation à sa place.",
     "items": ["1. La hanche — a. au milieu de la jambe", "2. Le genou — b. entre la jambe et le pied", "3. La cheville — c. entre le tronc et la jambe", "4. Le pied — d. en bas de la jambe"],
     "cor": ["1. La **hanche** : **c**. entre le tronc et la jambe.", "2. Le **genou** : **a**. au milieu de la jambe.", "3. La **cheville** : **b**. entre la jambe et le pied.", "4. Le **pied** : **d**. en bas de la jambe."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Cite trois articulations de la jambe.", "2. Que font les muscles de la jambe ?", "3. À quoi servent les jambes ?", "4. Que se passe-t-il quand on plie le genou ?"],
     "cor": ["1. La **hanche**, le **genou** et la **cheville**.", "2. Ils **font bouger la jambe**.", "3. À **marcher**, **courir** et **sauter**.", "4. La **jambe se plie** au niveau du genou."]},
],
"lecon": [
    (None, ["Le **membre inférieur** bouge grâce aux **articulations** et aux **muscles**."]),
    ("1. Les articulations de la jambe", ["La **hanche** attache la jambe au tronc. Le **genou** plie la jambe. La **cheville** fait bouger le **pied**. Ce sont des **articulations**."]),
    ("2. Marcher, courir, sauter", ["Les **muscles** de la jambe tirent sur les os et font bouger la jambe. Grâce à eux, nous pouvons **marcher**, **courir** et **sauter**. Les pieds **soutiennent** tout le corps."]),
],
"mots_cles": ["hanche", "articulation", "muscles", "marcher", "courir", "sauter"],
},
{
"n": 6, "titre": "L'hygiène et la sécurité des membres inférieurs", "theme": "Les membres inférieurs",
"objectif": "connaître les mesures d'hygiène et de sécurité des membres inférieurs",
"doc": "Répartition annuelle 9e, SVT, Bimestre 4",
"support_obs": "l'image de l'enfant qui se lave les pieds, affichée au tableau",
"image": ("svt9e_pieds_propres.png", "Image : Soa lave ses pieds avec de l'eau propre et du savon."),
"revision": [
    ("Cite trois articulations de la jambe.", "La hanche, le genou et la cheville."),
    ("À quoi servent les jambes ?", "À marcher, courir et sauter."),
],
"situation": "Après avoir joué pieds nus, Rova a les pieds pleins de boue. Sa maman lui donne de l'eau propre et du savon. Comment garder des jambes et des pieds en bonne santé ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'hygiène et la sécurité des membres inférieurs.",
    "Je lis le titre au tableau : L'hygiène et la sécurité des membres inférieurs.",
],
"observation": [
    "Regardez l'image de l'enfant qui se lave les pieds.",
    "Regardez vos pieds et vos ongles : sont-ils propres et coupés ?",
],
"analyse": [
    ("Quand faut-il laver ses pieds ?", "Il faut laver ses pieds chaque jour, surtout après avoir joué."),
    ("Pourquoi couper les ongles des orteils ?", "Des ongles courts et propres évitent les blessures et les microbes."),
    ("Pourquoi porter des chaussures ?", "Les chaussures protègent les pieds des épines, des cailloux et des clous."),
],
"synthese": "Je lave mes pieds chaque jour, je coupe mes ongles et je porte des chaussures pour protéger mes pieds.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. On lave ses pieds chaque jour.", "2. Les ongles des orteils doivent rester longs.", "3. Les chaussures protègent les pieds.", "4. Marcher pieds nus sur les cailloux est sans danger."],
     "cor": ["1. **Vrai** : chaque jour.", "2. **Faux** : ils doivent être courts et propres.", "3. **Vrai** : elles protègent des épines.", "4. **Faux** : les cailloux peuvent blesser."]},
    {"c": "Complète avec les mots suivants : laver, ongles, chaussures, épines.",
     "items": ["1. Je ... mes pieds chaque jour.", "2. Je coupe mes ... courts.", "3. Je porte des ...", "4. Les chaussures protègent des ... et des clous."],
     "cor": ["1. Je **lave** mes pieds chaque jour.", "2. Mes **ongles** courts.", "3. Des **chaussures**.", "4. Des **épines** et des clous."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quand lave-t-on ses pieds ? A. Une fois par an B. Chaque jour C. Jamais", "2. Comment garder les ongles des orteils ? A. Longs et sales B. Courts et propres C. Peints", "3. Que protègent les chaussures ? A. Les pieds B. Les mains C. La tête", "4. Où ne faut-il pas courir ? A. Sur l'herbe B. Sur un sol glissant C. Dans la cour"],
     "cor": ["1. **B. Chaque jour**.", "2. **B. Courts et propres**.", "3. **A. Les pieds**.", "4. **B. Sur un sol glissant**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quand faut-il laver ses pieds ?", "2. Pourquoi coupe-t-on les ongles des orteils ?", "3. Contre quoi les chaussures protègent-elles ?", "4. Que faire si un clou perce le pied ?"],
     "cor": ["1. **Chaque jour**, avec de l'eau propre et du savon.", "2. Pour **éviter les blessures** et les **microbes**.", "3. Contre les **épines**, les **cailloux** et les **clous**.", "4. **Prévenir un adulte** et aller au **centre de santé**."]},
],
"lecon": [
    (None, ["Nos **jambes** et nos **pieds** nous portent toute la journée : il faut bien s'en occuper."]),
    ("1. L'hygiène des pieds", ["Je **lave mes pieds** chaque jour avec de l'**eau propre** et du **savon**, surtout après avoir joué. Je coupe mes **ongles** courts et propres, et je les essuie avec ma **serviette**."]),
    ("2. La sécurité", ["Je porte des **chaussures** : elles protègent les pieds des **épines**, des **cailloux** et des **clous**. Je ne cours pas sur les **sols glissants** pour ne pas tomber et me tordre la cheville."]),
],
"mots_cles": ["laver", "ongles", "chaussures", "épines", "sol glissant"],
},
]
