# -*- coding: utf-8 -*-
"""Contenu Bimestre 3 — Séances 1 à 6 (Blocs 1-2). Manuel SVT 9e J-Learn.
Conventions : **mot** = mot clé (bleu+gras dans la leçon, bordeaux dans les corrigés).
Niveau : 9e (~8 ans), phrases courtes, vocabulaire simple. Aucune date calendaire.
"""

SEANCES_A = [
{
"n": 1, "titre": "Comment l'œil voit", "theme": "Le fonctionnement de l'œil",
"objectif": "expliquer le fonctionnement de l'œil",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": ("svt9e_oeil_fonctionnement.png", "Schéma : la lumière entre dans l'œil par la pupille."),
"revision": [
    ("Quelles sont les parties de l'œil ?", "Le sourcil, la paupière, les cils et la pupille."),
    ("Quel est le rôle de l'œil ?", "L'œil sert à voir."),
],
"situation": "Le soir, Nivo entre dans sa chambre toute noire : elle ne voit rien. Sa maman allume la lampe, et aussitôt Nivo voit son lit et ses jouets. Comment l'œil fait-il pour voir ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment l'œil voit.",
    "Je lis le titre au tableau : Comment l'œil voit.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Fermez les yeux, puis ouvrez-les : d'où vient la lumière qui vous permet de voir ?",
],
"analyse": [
    ("Sans lumière, peut-on voir ?", "Sans lumière, on ne voit rien : il fait tout noir."),
    ("Par où la lumière entre-t-elle dans l'œil ?", "La lumière entre dans l'œil par la pupille."),
    ("Que fait le cerveau avec ce que l'œil voit ?", "Le cerveau comprend ce que l'œil voit."),
],
"synthese": "Pour voir, il faut de la lumière. La lumière entre dans l'œil par la pupille, puis le cerveau comprend ce que l'œil voit.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Pour voir, il faut de la lumière.", "2. La lumière entre par le sourcil.", "3. Le cerveau comprend ce que l'œil voit.", "4. Dans le noir, on voit très bien."],
     "cor": ["1. **Vrai** : sans lumière, pas de vue.", "2. **Faux** : la lumière entre par la pupille.", "3. **Vrai** : le cerveau comprend les images.", "4. **Faux** : dans le noir, on ne voit rien."]},
    {"c": "Complète avec les mots suivants : lumière, pupille, cerveau.",
     "items": ["1. Pour voir, il faut de la ...", "2. La lumière entre par la ...", "3. Le ... comprend ce que l'œil voit.", "4. Sans ..., on ne voit rien."],
     "cor": ["1. Il faut de la **lumière**.", "2. Elle entre par la **pupille**.", "3. Le **cerveau** comprend.", "4. Sans **lumière**, on ne voit rien."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que faut-il pour voir ? A. De la lumière B. Du bruit C. Du vent", "2. Par où entre la lumière ? A. Par le nez B. Par la pupille C. Par l'oreille", "3. Qui comprend ce que voit l'œil ? A. La main B. Le cerveau C. Le pied", "4. Que voit-on dans une chambre noire ? A. Tout B. Rien C. Les couleurs seulement"],
     "cor": ["1. **A. De la lumière**.", "2. **B. Par la pupille**.", "3. **B. Le cerveau**.", "4. **B. Rien** : sans lumière, on ne voit pas."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faut-il pour voir ?", "2. Par où la lumière entre-t-elle dans l'œil ?", "3. Que fait le cerveau ?", "4. Pourquoi ne voit-on rien dans le noir ?"],
     "cor": ["1. Pour voir, il faut de la **lumière**.", "2. Par la **pupille**.", "3. Le **cerveau** comprend ce que l'œil voit.", "4. Parce que **sans lumière**, l'œil ne reçoit rien."]},
],
"lecon": [
    (None, ["L'**œil** est l'organe de la vue. Pour voir, l'œil a besoin de **lumière**."]),
    ("1. La lumière entre dans l'œil", ["La **lumière** entre dans l'œil par la **pupille**, le rond noir du milieu. L'**iris**, la partie colorée, règle la quantité de lumière qui entre."]),
    ("2. Le cerveau comprend", ["À l'intérieur de l'œil, la lumière forme une **image**. Cette image est envoyée au **cerveau**. C'est le **cerveau** qui comprend ce que nous voyons : les personnes, les objets et les couleurs."]),
],
"mots_cles": ["lumière", "pupille", "iris", "cerveau", "image"],
},
{
"n": 2, "titre": "La pupille et l'iris au travail", "theme": "Le fonctionnement de l'œil",
"objectif": "expliquer le fonctionnement des différentes parties de l'œil",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": None,
"revision": [
    ("Par où la lumière entre-t-elle dans l'œil ?", "La lumière entre par la pupille."),
    ("Qui comprend ce que l'œil voit ?", "Le cerveau comprend ce que l'œil voit."),
],
"situation": "En plein soleil, Rova plisse les yeux et sa pupille devient toute petite. Le soir, dans la maison sombre, ses yeux s'ouvrent grands et sa pupille s'agrandit. Pourquoi la pupille change-t-elle de taille ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment la pupille et l'iris travaillent.",
    "Je lis le titre au tableau : La pupille et l'iris au travail.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Regardez les yeux de votre voisin dans la classe, puis près de la fenêtre : la pupille change-t-elle ?",
],
"analyse": [
    ("Comment est la pupille quand la lumière est forte ?", "Quand la lumière est forte, la pupille est petite."),
    ("Comment est la pupille quand il fait sombre ?", "Quand il fait sombre, la pupille est grande."),
    ("Qui fait changer la taille de la pupille ?", "C'est l'iris qui fait changer la taille de la pupille."),
],
"synthese": "L'iris agrandit ou rétrécit la pupille : petite quand la lumière est forte, grande quand il fait sombre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La pupille est petite en pleine lumière.", "2. La pupille est grande dans le noir.", "3. C'est le sourcil qui fait changer la pupille.", "4. L'iris règle la quantité de lumière."],
     "cor": ["1. **Vrai** : la pupille rétrécit en pleine lumière.", "2. **Vrai** : elle s'agrandit dans le noir.", "3. **Faux** : c'est l'iris.", "4. **Vrai** : l'iris règle la lumière."]},
    {"c": "Complète avec les mots suivants : iris, petite, grande, pupille.",
     "items": ["1. En pleine lumière, la pupille est ...", "2. Dans le noir, la pupille est ...", "3. C'est l'... qui fait changer la pupille.", "4. La ... laisse entrer la lumière."],
     "cor": ["1. La pupille est **petite**.", "2. Elle est **grande**.", "3. C'est l'**iris**.", "4. La **pupille** laisse entrer la lumière."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Comment est la pupille au soleil ? A. Grande B. Petite C. Carrée", "2. Comment est la pupille dans le noir ? A. Petite B. Grande C. Ronde", "3. Qui fait changer la pupille ? A. Les cils B. L'iris C. La paupière", "4. Pourquoi la pupille rétrécit-elle au soleil ? A. Pour laisser entrer moins de lumière B. Pour dormir C. Pour pleurer"],
     "cor": ["1. **B. Petite**.", "2. **B. Grande**.", "3. **B. L'iris**.", "4. **A. Pour laisser entrer moins de lumière**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Comment est la pupille quand la lumière est forte ?", "2. Comment est-elle quand il fait sombre ?", "3. Qui fait changer la taille de la pupille ?", "4. Pourquoi la pupille s'agrandit-elle dans le noir ?"],
     "cor": ["1. La **pupille** est **petite**.", "2. Elle est **grande**.", "3. C'est l'**iris**.", "4. Pour **laisser entrer plus de lumière**."]},
],
"lecon": [
    (None, ["La **pupille** et l'**iris** travaillent ensemble pour régler la lumière qui entre dans l'œil."]),
    ("1. En pleine lumière", ["Quand la **lumière** est forte, l'**iris** rétrécit la **pupille**. Ainsi, il ne laisse entrer qu'un peu de lumière pour ne pas abîmer l'œil."]),
    ("2. Dans le noir", ["Quand il fait **sombre**, l'**iris** agrandit la **pupille** pour laisser entrer plus de lumière. C'est pourquoi nos yeux s'habituent petit à petit à l'obscurité."]),
],
"mots_cles": ["pupille", "iris", "lumière", "rétrécir", "agrandir"],
},
{
"n": 3, "titre": "L'œil et le cerveau", "theme": "Le fonctionnement de l'œil",
"objectif": "comprendre que le cerveau reçoit et comprend ce que l'œil voit",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "un foulard pour bander les yeux",
"image": None,
"revision": [
    ("Comment est la pupille en pleine lumière ?", "En pleine lumière, la pupille est petite."),
    ("Qui fait changer la taille de la pupille ?", "C'est l'iris."),
],
"situation": "Pendant le jeu, la maîtresse bande les yeux de Koto. Il avance doucement, les bras en avant, et se cogne presque contre la table. Sans ses yeux, il ne sait plus où aller ! Qui aide l'œil à comprendre le monde ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre comment l'œil et le cerveau travaillent ensemble.",
    "Je lis le titre au tableau : L'œil et le cerveau.",
],
"observation": [
    "Un élève volontaire avance les yeux bandés, puis les yeux ouverts.",
    "Comparez : quand avance-t-on le mieux ?",
],
"analyse": [
    ("Que reçoit l'œil quand on regarde ?", "L'œil reçoit la lumière et forme une image."),
    ("Où l'image est-elle envoyée ?", "L'image est envoyée au cerveau."),
    ("Que fait le cerveau avec cette image ?", "Le cerveau comprend l'image : il reconnaît les objets, les personnes et les couleurs."),
],
"synthese": "L'œil reçoit la lumière et forme une image. Le cerveau reçoit cette image et la comprend : c'est lui qui nous dit ce que nous voyons.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. L'œil forme une image.", "2. L'image reste dans l'œil.", "3. Le cerveau reçoit l'image.", "4. Le cerveau reconnaît les objets."],
     "cor": ["1. **Vrai** : l'œil forme une image.", "2. **Faux** : l'image est envoyée au cerveau.", "3. **Vrai** : le cerveau reçoit l'image.", "4. **Vrai** : il reconnaît les objets."]},
    {"c": "Complète avec les mots suivants : image, cerveau, yeux, reconnaître.",
     "items": ["1. L'œil forme une ...", "2. L'image est envoyée au ...", "3. Les ... reçoivent la lumière.", "4. Le cerveau sert à ... les objets."],
     "cor": ["1. L'œil forme une **image**.", "2. Elle est envoyée au **cerveau**.", "3. Les **yeux** reçoivent la lumière.", "4. À **reconnaître** les objets."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Que forme l'œil ? A. Un son B. Une image C. Une odeur", "2. Où l'image est-elle envoyée ? A. Au cœur B. Au cerveau C. Au ventre", "3. Qui reconnaît les couleurs ? A. La main B. Le cerveau C. L'oreille", "4. Que fait l'enfant qui a les yeux bandés ? A. Il avance très bien B. Il hésite et se cogne C. Il court vite"],
     "cor": ["1. **B. Une image**.", "2. **B. Au cerveau**.", "3. **B. Le cerveau**.", "4. **B. Il hésite et se cogne**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que forme l'œil avec la lumière ?", "2. Où l'image est-elle envoyée ?", "3. Qui nous dit ce que nous voyons ?", "4. Pourquoi est-ce difficile de marcher les yeux bandés ?"],
     "cor": ["1. L'œil forme une **image**.", "2. L'image est envoyée au **cerveau**.", "3. C'est le **cerveau**.", "4. Parce que le **cerveau** ne reçoit plus les images des yeux."]},
],
"lecon": [
    (None, ["L'**œil** et le **cerveau** travaillent ensemble : l'œil voit, et le cerveau comprend."]),
    ("1. Le travail de l'œil", ["L'**œil** reçoit la **lumière** et forme une **image**, comme un appareil photo."]),
    ("2. Le travail du cerveau", ["L'**image** est envoyée au **cerveau**. Le cerveau **comprend** l'image : il reconnaît les **objets**, les **personnes** et les **couleurs**. C'est lui qui nous dit ce que nous voyons."]),
],
"mots_cles": ["œil", "cerveau", "image", "reconnaître"],
},
{
"n": 4, "titre": "L'hygiène des yeux", "theme": "La protection et l'hygiène de l'œil",
"objectif": "pratiquer l'hygiène appropriée à l'œil",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "l'image de l'enfant qui se lave le visage, affichée au tableau",
"image": ("svt9e_oeil_hygiene.png", "Image : Soa se lave le visage avec de l'eau propre, matin et soir."),
"revision": [
    ("Que forme l'œil avec la lumière ?", "L'œil forme une image."),
    ("Qui comprend ce que l'œil voit ?", "Le cerveau comprend ce que l'œil voit."),
],
"situation": "Chaque matin, Soa se lave le visage avec de l'eau propre. Son petit frère, lui, se frotte les yeux avec les mains pleines de terre. Lequel des deux gardera des yeux en bonne santé ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre l'hygiène des yeux.",
    "Je lis le titre au tableau : L'hygiène des yeux.",
],
"observation": [
    "Regardez l'image de l'enfant qui se lave le visage.",
    "Regardez vos mains : sont-elles propres pour toucher vos yeux ?",
],
"analyse": [
    ("Quand faut-il se laver le visage ?", "Il faut se laver le visage le matin et le soir."),
    ("Avec quelles mains ne faut-il pas toucher ses yeux ?", "Il ne faut pas toucher ses yeux avec les mains sales."),
    ("Pourquoi chacun doit-il avoir sa serviette ?", "Parce que la serviette d'un autre peut porter des microbes."),
],
"synthese": "Je lave mon visage matin et soir, je ne touche pas mes yeux avec les mains sales et j'utilise ma propre serviette.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. On lave son visage matin et soir.", "2. On peut toucher ses yeux avec les mains sales.", "3. Chacun a sa serviette.", "4. Une serviette partagée porte des microbes."],
     "cor": ["1. **Vrai** : matin et soir.", "2. **Faux** : les mains sales portent des microbes.", "3. **Vrai** : chacun sa serviette.", "4. **Vrai** : elle peut porter des microbes."]},
    {"c": "Complète avec les mots suivants : visage, mains, serviette, eau.",
     "items": ["1. Je lave mon ... matin et soir.", "2. Je ne touche pas mes yeux avec les ... sales.", "3. J'utilise ma propre ...", "4. Je lave mon visage avec de l'... propre."],
     "cor": ["1. Je lave mon **visage** matin et soir.", "2. Avec les **mains** sales.", "3. Ma propre **serviette**.", "4. De l'**eau** propre."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quand lave-t-on son visage ? A. Une fois par mois B. Matin et soir C. Jamais", "2. Peut-on frotter ses yeux avec les mains sales ? A. Oui B. Non C. Parfois", "3. Quelle serviette utiliser ? A. Celle du voisin B. Sa propre serviette C. Un chiffon sale", "4. Pourquoi garder les yeux propres ? A. Pour éviter les maladies B. Pour être beau C. Pour mieux dormir"],
     "cor": ["1. **B. Matin et soir**.", "2. **B. Non** : les mains sales portent des microbes.", "3. **B. Sa propre serviette**.", "4. **A. Pour éviter les maladies**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quand faut-il se laver le visage ?", "2. Pourquoi ne touche-t-on pas ses yeux avec les mains sales ?", "3. Pourquoi chacun a-t-il sa serviette ?", "4. Que faire avant de toucher ses yeux ?"],
     "cor": ["1. Le **matin** et le **soir**.", "2. Parce que les **mains sales portent des microbes**.", "3. Pour **ne pas échanger les microbes**.", "4. **Se laver les mains** avec de l'eau et du savon."]},
],
"lecon": [
    (None, ["Des **yeux propres** sont des yeux en bonne **santé**. L'**hygiène** des yeux est simple, mais très importante."]),
    ("1. Les bons gestes", ["Je lave mon **visage** le **matin** et le **soir** avec de l'**eau propre**. Je me lave les **mains** avant de toucher mes yeux. J'utilise ma propre **serviette** propre."]),
    ("2. Ce qu'il ne faut pas faire", ["Je ne **frotte** jamais mes yeux avec les **mains sales**. Je ne prête pas ma **serviette** et je n'utilise pas celle des autres."]),
],
"mots_cles": ["hygiène", "visage", "serviette", "mains sales"],
},
{
"n": 5, "titre": "Les maladies des yeux", "theme": "La protection et l'hygiène de l'œil",
"objectif": "connaître les maladies des yeux et les faire soigner",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": None,
"revision": [
    ("Quand faut-il se laver le visage ?", "Le matin et le soir."),
    ("Pourquoi chacun a-t-il sa serviette ?", "Pour ne pas échanger les microbes."),
],
"situation": "Depuis deux jours, Aina a les yeux rouges et ils collent le matin. La maîtresse dit : « Ne touche pas tes yeux, et va au centre de santé. » Quelle est cette maladie des yeux ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre les maladies des yeux.",
    "Je lis le titre au tableau : Les maladies des yeux.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Regardez les yeux de votre voisin : sont-ils blancs et clairs, ou rouges et collés ?",
],
"analyse": [
    ("Quels sont les signes de la conjonctivite ?", "Les signes sont des yeux rouges qui collent et qui grattent."),
    ("Comment la conjonctivite se transmet-elle ?", "Elle se transmet par les mains sales et les serviettes partagées."),
    ("Que faut-il faire si les yeux sont rouges ?", "Il faut prévenir les parents et aller au centre de santé."),
],
"synthese": "La conjonctivite rend les yeux rouges et collés. Elle se transmet par les mains et les serviettes. Il faut la soigner au centre de santé.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. La conjonctivite rend les yeux rouges.", "2. Elle se transmet par les serviettes partagées.", "3. Il ne faut pas la soigner.", "4. Un œil malade doit être soigné au centre de santé."],
     "cor": ["1. **Vrai** : les yeux sont rouges.", "2. **Vrai** : par les serviettes et les mains.", "3. **Faux** : il faut la soigner vite.", "4. **Vrai** : au centre de santé."]},
    {"c": "Complète avec les mots suivants : rouges, serviette, santé, mains.",
     "items": ["1. La conjonctivite rend les yeux ...", "2. On ne partage pas sa ...", "3. Il faut aller au centre de ...", "4. On ne frotte pas ses yeux avec les ... sales."],
     "cor": ["1. Les yeux **rouges**.", "2. Sa **serviette**.", "3. Centre de **santé**.", "4. Les **mains** sales."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Quels sont les signes de la conjonctivite ? A. Yeux rouges et collés B. Yeux bleus C. Yeux fermés", "2. Comment se transmet-elle ? A. Par le vent B. Par les serviettes partagées C. Par la pluie", "3. Que faire si les yeux sont rouges ? A. Rien B. Aller au centre de santé C. Attendre un mois", "4. Que ne faut-il pas partager ? A. Le cahier B. La serviette C. Le crayon"],
     "cor": ["1. **A. Yeux rouges et collés**.", "2. **B. Par les serviettes partagées**.", "3. **B. Aller au centre de santé**.", "4. **B. La serviette**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Quels sont les signes de la conjonctivite ?", "2. Comment se transmet la conjonctivite ?", "3. Que faut-il faire quand les yeux sont rouges ?", "4. Comment éviter la conjonctivite ?"],
     "cor": ["1. Des **yeux rouges** qui **collent** et qui **grattent**.", "2. Par les **mains sales** et les **serviettes partagées**.", "3. **Prévenir les parents** et aller au **centre de santé**.", "4. En **se lavant les mains** et en **gardant sa serviette** pour soi."]},
],
"lecon": [
    (None, ["L'**œil** peut tomber malade. La maladie des yeux la plus fréquente est la **conjonctivite**."]),
    ("1. Les signes de la conjonctivite", ["L'œil devient **rouge**, il **colle** le matin et il **gratte**. Parfois, l'œil pleure beaucoup."]),
    ("2. Soigner et éviter la contagion", ["Il faut **prévenir les parents** et aller au **centre de santé**. La conjonctivite se transmet par les **mains** et les **serviettes** : je garde mes mains propres et ma serviette pour moi."]),
],
"mots_cles": ["conjonctivite", "rouge", "coller", "contagion", "serviette"],
},
{
"n": 6, "titre": "Protéger ses yeux en toutes circonstances", "theme": "La protection et l'hygiène de l'œil",
"objectif": "connaître les mesures de protection nécessaires des yeux",
"doc": "Répartition annuelle 9e, SVT, Bimestre 3",
"support_obs": "le schéma de l'œil affiché au tableau",
"image": None,
"revision": [
    ("Quels sont les signes de la conjonctivite ?", "Des yeux rouges qui collent et qui grattent."),
    ("Que faire si les yeux sont rouges ?", "Prévenir les parents et aller au centre de santé."),
],
"situation": "Le soir, Hery lit son livre dans le noir. Sa sœur regarde la télévision de tout près. Leur grand frère leur dit : « Arrêtez, vous allez abîmer vos yeux ! » Comment bien protéger ses yeux tous les jours ?",
"presentation": [
    "Aujourd'hui, nous allons apprendre à protéger nos yeux tous les jours.",
    "Je lis le titre au tableau : Protéger ses yeux en toutes circonstances.",
],
"observation": [
    "Regardez le schéma de l'œil affiché au tableau.",
    "Regardez la classe : la lumière est-elle bonne pour lire et écrire ?",
],
"analyse": [
    ("Que faut-il pour bien lire et écrire ?", "Pour bien lire et écrire, il faut une bonne lumière."),
    ("À quelle distance regarde-t-on la télévision ?", "On regarde la télévision de loin, jamais de tout près."),
    ("Comment protéger ses yeux du soleil ?", "On protège ses yeux du soleil avec un chapeau et en restant à l'ombre."),
],
"synthese": "Je lis à la bonne lumière, je regarde la télévision de loin, et je protège mes yeux du soleil avec un chapeau et l'ombre.",
"application": [
    {"c": "Réponds par Vrai (V) ou Faux (F).",
     "items": ["1. Il faut une bonne lumière pour lire.", "2. On peut lire dans le noir.", "3. On regarde la télévision de loin.", "4. Le chapeau protège les yeux du soleil."],
     "cor": ["1. **Vrai** : il faut une bonne lumière.", "2. **Faux** : lire dans le noir fatigue les yeux.", "3. **Vrai** : de loin, jamais de tout près.", "4. **Vrai** : le chapeau protège du soleil."]},
    {"c": "Complète avec les mots suivants : lumière, loin, chapeau, ombre.",
     "items": ["1. Je lis à la bonne ...", "2. Je regarde la télévision de ...", "3. Au soleil, je porte un ...", "4. Je joue à l'... quand le soleil est fort."],
     "cor": ["1. À la bonne **lumière**.", "2. De **loin**.", "3. Un **chapeau**.", "4. À l'**ombre**."]},
],
"evaluation": [
    {"c": "Entoure la bonne réponse.",
     "items": ["1. Pour lire, il faut... A. Le noir B. Une bonne lumière C. Une bougie trop petite", "2. Comment regarde-t-on la télévision ? A. De tout près B. De loin C. Les yeux fermés", "3. Au soleil fort, que fait-on ? A. On regarde le soleil B. On reste à l'ombre C. On ouvre grand les yeux", "4. Qu'est-ce qui protège les yeux du soleil ? A. Le chapeau B. Le cahier C. Le ballon"],
     "cor": ["1. **B. Une bonne lumière**.", "2. **B. De loin**.", "3. **B. On reste à l'ombre**.", "4. **A. Le chapeau**."]},
    {"c": "Réponds par une phrase complète.",
     "items": ["1. Que faut-il pour bien lire ?", "2. Comment regarde-t-on la télévision ?", "3. Comment protéger ses yeux du soleil ?", "4. Pourquoi ne lit-on pas dans le noir ?"],
     "cor": ["1. Une **bonne lumière**.", "2. De **loin**.", "3. Avec un **chapeau** et en restant à l'**ombre**.", "4. Parce que le **noir fatigue les yeux**."]},
],
"lecon": [
    (None, ["Nos **yeux** sont précieux : il faut les **protéger** tous les jours, dans toutes les situations."]),
    ("1. À l'école et à la maison", ["Je **lis** et j'**écris** à la **bonne lumière**, jamais dans le noir. Je regarde la **télévision** de **loin**, jamais de tout près, pour ne pas fatiguer mes yeux."]),
    ("2. Dehors", ["Au **soleil**, je porte un **chapeau** et je joue à l'**ombre**. Je ne regarde jamais le **soleil** en face. Je ne joue pas avec les **objets pointus** qui peuvent blesser les yeux."]),
],
"mots_cles": ["lumière", "loin", "chapeau", "ombre", "soleil"],
},
]
