const fs = require('fs');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, BorderStyle, ShadingType, PageBreak,
  Header, Footer, PageNumber, Bookmark, InternalHyperlink,
  ImageRun, Math: DocxMath, MathFraction, MathRun
} = require('docx');

const OUT = 'Manuel_Mathematiques_T6_V1_UNITE6.docx';
const C = { red:'C00000', green:'1E7B34', blue:'1F4E79', wine:'C2185B', pale:'EAF2F8', paleGreen:'E9F5EC', gray:'E7E6E6', black:'000000', white:'FFFFFF' };
const noBorders = {top:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},bottom:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},left:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},right:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideHorizontal:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideVertical:{style:BorderStyle.NONE,size:0,color:'FFFFFF'}};
const borders = {top:{style:BorderStyle.SINGLE,size:4,color:'808080'},bottom:{style:BorderStyle.SINGLE,size:4,color:'808080'},left:{style:BorderStyle.SINGLE,size:4,color:'808080'},right:{style:BorderStyle.SINGLE,size:4,color:'808080'},insideHorizontal:{style:BorderStyle.SINGLE,size:4,color:'B0B0B0'},insideVertical:{style:BorderStyle.SINGLE,size:4,color:'B0B0B0'}};
const tr = (text,opt={}) => new TextRun({text, font:'Times New Roman', size:opt.size||22, bold:!!opt.bold, color:opt.color||C.black, italics:!!opt.italics});
// Convert every numeric a/b expression to a native Word OMML fraction.
const rich = (text,opt={}) => {
  const out=[]; let last=0; const re=/(\d[\d ]*)\/(\d[\d ]*)/g; let m;
  while((m=re.exec(text))){
    if(m.index>last) out.push(tr(text.slice(last,m.index),opt));
    out.push(new DocxMath({children:[new MathFraction({numerator:[new MathRun(m[1].trim())],denominator:[new MathRun(m[2].trim())]})]}));
    last=re.lastIndex;
  }
  if(last<text.length) out.push(tr(text.slice(last),opt));
  return out.length?out:[tr(text,opt)];
};
const p = (text,opt={}) => new Paragraph({alignment:opt.align||AlignmentType.JUSTIFIED, spacing:{after:opt.after??100,line:276}, indent:opt.indent?{left:opt.indent}:undefined, children:rich(text,opt)});
const title = (text, level=1, bookmark) => {
 const run = tr(text,{bold:true,color:level===1?C.red:C.green,size:level===1?32:26});
 const children = bookmark ? [new Bookmark({id:bookmark, children:[run]})] : [run];
 return new Paragraph({alignment:level===1?AlignmentType.CENTER:AlignmentType.LEFT, spacing:{before:180,after:140}, children});
};
const cell = (text,opt={}) => new TableCell({width:opt.width?{size:opt.width,type:WidthType.PERCENTAGE}:undefined, columnSpan:opt.span, rowSpan:opt.rowSpan, shading:opt.fill?{type:ShadingType.CLEAR,fill:opt.fill}:undefined, margins:{top:80,bottom:80,left:80,right:80}, children:[new Paragraph({alignment:opt.align||AlignmentType.LEFT,children:rich(text,{bold:opt.bold,color:opt.color||C.black,size:opt.size||18})})]});
const table = rows => new Table({width:{size:100,type:WidthType.PERCENTAGE},borders,rows});
const bullet = text => new Paragraph({bullet:{level:0},spacing:{after:70},children:rich(text)});
const labelPara = (label,text) => new Paragraph({spacing:{after:90},children:[tr(label,{bold:true,color:C.blue}),...rich(text)]});
const correction = (label,text) => new Paragraph({spacing:{after:70},children:[tr(label,{bold:true,color:C.wine}),...rich(text)]});
const page = () => new Paragraph({children:[new PageBreak()]});

function svgPng(name, svg) {
 const dir='assets/math-t6'; fs.mkdirSync(dir,{recursive:true});
 fs.writeFileSync(`${dir}/${name}.svg`,svg);
 require('child_process').execFileSync(process.execPath,['-e',`require('sharp')('${dir}/${name}.svg').png().toFile('${dir}/${name}.png')`]);
 return fs.readFileSync(`${dir}/${name}.png`);
}
const fractionBars = svgPng('fractions-equivalentes',`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="360"><rect width="100%" height="100%" fill="white"/><text x="40" y="55" font-family="serif" font-size="34">Une même quantité représentée de trois façons</text><g stroke="#1F4E79" stroke-width="4"><rect x="80" y="100" width="800" height="55" fill="white"/><rect x="80" y="100" width="400" height="55" fill="#79B6E3"/><line x1="480" y1="100" x2="480" y2="155"/><rect x="80" y="185" width="800" height="55" fill="white"/><rect x="80" y="185" width="400" height="55" fill="#79B6E3"/><line x1="280" y1="185" x2="280" y2="240"/><line x1="480" y1="185" x2="480" y2="240"/><line x1="680" y1="185" x2="680" y2="240"/><rect x="80" y="270" width="800" height="55" fill="white"/><rect x="80" y="270" width="400" height="55" fill="#79B6E3"/>${[180,280,380,480,580,680,780].map(x=>`<line x1="${x}" y1="270" x2="${x}" y2="325"/>`).join('')}</g><text x="900" y="140" font-size="30">1/2</text><text x="900" y="225" font-size="30">2/4</text><text x="900" y="310" font-size="30">4/8</text></svg>`);
const numberLine = svgPng('droite-fractions',`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="260"><rect width="100%" height="100%" fill="white"/><text x="40" y="48" font-family="serif" font-size="34">Droite numérique partagée en huitièmes</text><line x1="80" y1="140" x2="920" y2="140" stroke="#1F4E79" stroke-width="5"/>${[0,1,2,3,4,5,6,7,8].map((n,i)=>`<line x1="${80+i*105}" y1="115" x2="${80+i*105}" y2="165" stroke="#1F4E79" stroke-width="4"/><text x="${70+i*105}" y="205" font-size="26">${n===0?'0':n===8?'1':n+'/8'}</text>`).join('')}</svg>`);
const grid100 = svgPng('grille-pourcentage',`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="700"><rect width="100%" height="100%" fill="white"/><text x="50" y="45" font-size="30">35 cases sur 100 = 35 % = 0,35</text>${Array.from({length:100},(_,k)=>{let x=50+(k%10)*55,y=80+Math.floor(k/10)*55;return `<rect x="${x}" y="${y}" width="55" height="55" fill="${k<35?'#79B6E3':'white'}" stroke="#777"/>`}).join('')}</svg>`);

const sessions = [
 {t:"Formuler une question ou une hypothèse",goal:"formuler une question adaptée à une expérience",concept:"Une question statistique admet plusieurs réponses et nécessite des données. Une hypothèse est une réponse provisoire que l’expérience permettra de vérifier.",example:"Question : « Quel moyen de transport les élèves utilisent-ils ? » Hypothèse : « La marche est le moyen le plus fréquent. »",app:["Distingue question statistique et question à réponse unique : âge des élèves ; résultat de 8 × 7 ; temps de trajet ; couleur préférée.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["Statistiques : âge, temps de trajet, couleur préférée. Réponse unique : 8 × 7.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Préparer un sondage quantitatif",goal:"rédiger des questions claires et mesurables",concept:"Une question quantitative produit une réponse numérique. Elle doit préciser la population, l’unité et la période si nécessaire, sans orienter la réponse.",example:"« Combien de minutes mets-tu pour venir à l’école ? » produit une durée mesurable.",app:["Améliore : Fais-tu beaucoup de sport ? Lis-tu souvent ? Ta famille est-elle grande ? Bois-tu assez d’eau ?", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["Exemples : combien de minutes de sport par semaine ? combien de livres par mois ? combien de personnes dans ta famille ? combien de verres d’eau par jour ?", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Choisir une stratégie de collecte",goal:"choisir entre questionnaire, observation, entretien et données secondaires",concept:"Le choix dépend de la question, du temps et des personnes interrogées. Le questionnaire recueille beaucoup de réponses ; l’observation compte des faits ; l’entretien approfondit ; les données secondaires existent déjà.",example:"Pour compter les véhicules devant l’école, l’observation directe est adaptée.",app:["Choisis : opinions de 200 élèves ; nombre d’oiseaux dans une cour ; raisons d’une absence ; population d’une commune déjà recensée.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["Questionnaire ; observation ; entretien ; données secondaires.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Organiser les données dans un tableau",goal:"construire un tableau d’effectifs",concept:"Un tableau indique le titre, les catégories, les effectifs et le total. Les marques de comptage facilitent l’enregistrement avant le calcul des effectifs.",example:"Effectifs 8, 12, 5 et 15 : l’effectif total est 40.",app:["Calcule les totaux : 6, 9, 10, 5 ; 12, 8, 7, 13 ; 25, 15, 20, 10 ; 4, 11, 9, 6.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["30 ; 40 ; 70 ; 30.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Construire pictogramme et diagramme à bandes",goal:"représenter des effectifs avec une échelle",concept:"Un pictogramme utilise des symboles avec une légende. Un diagramme à bandes utilise des rectangles de même largeur ; leur hauteur suit une échelle régulière.",example:"Si une image représente 5 élèves, 4 images représentent 20 élèves.",app:["Avec 1 symbole pour 4 objets, donne les effectifs de 2, 5, 7 et 10 symboles. Puis donne le nombre de symboles pour 12, 24, 32 et 40 objets.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["8, 20, 28, 40 objets ; 3, 6, 8, 10 symboles.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Construire un diagramme à ligne brisée",goal:"représenter une évolution dans le temps",concept:"Un diagramme à ligne brisée place les valeurs dans l’ordre du temps puis relie les points. Le titre, les axes, les unités et l’échelle sont indispensables.",example:"Les températures 18, 20, 23 et 21 °C donnent une hausse puis une baisse.",app:["Décris l’évolution : 10, 14, 18, 16 ; 30, 25, 20, 15 ; 5, 5, 8, 8 ; 12, 17, 15, 20.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["Hausse puis baisse ; baisse continue ; stabilité, hausse, stabilité ; hausse, baisse, hausse.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Lire un diagramme à tige et à feuilles",goal:"organiser une série en conservant chaque valeur",concept:"Dans un diagramme à tige et à feuilles, la tige porte les dizaines et la feuille les unités. Une clé explique la lecture, par exemple 2 | 7 signifie 27.",example:"Pour 21, 24, 24, 28 : tige 2 et feuilles 1, 4, 4, 8.",app:["Écris tiges et feuilles pour 12, 15, 18, 21 ; puis 23, 27, 31, 35 ; puis 40, 42, 46, 49 ; puis 54, 55, 55, 58.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["1 | 2 5 8 et 2 | 1 ; 2 | 3 7 et 3 | 1 5 ; 4 | 0 2 6 9 ; 5 | 4 5 5 8.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Interpréter moyenne, médiane et mode",goal:"calculer et choisir un indicateur central",concept:"La moyenne est la somme divisée par l’effectif. La médiane partage la série ordonnée en deux groupes. Le mode est la valeur la plus fréquente.",example:"Pour 2, 3, 3, 4, 8 : moyenne 4, médiane 3 et mode 3.",app:["Calcule moyenne, médiane et mode : 2, 4, 4, 6 ; 5, 5, 7, 7, 7, 11 ; 3, 6, 6, 9 ; 10, 12, 12, 14.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["4, 4, 4 ; 7, 7, 7 ; 6, 6, 6 ; 12, 12, 12.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Comparer probabilité théorique et expérimentale",goal:"distinguer prévision et fréquence observée",concept:"La probabilité théorique repose sur les résultats possibles supposés équiprobables. La probabilité expérimentale est le rapport entre succès observés et nombre d’essais ; elle se rapproche souvent de la théorie quand les essais augmentent.",example:"Pour une pièce équilibrée, P(pile) = 1/2. Si pile sort 47 fois en 100 essais, la fréquence est 47/100 = 47 %.",app:["Donne la probabilité : obtenir pile ; obtenir 6 avec un dé ; obtenir un nombre pair avec un dé ; tirer une boule rouge parmi 3 rouges et 2 bleues.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["1/2 ; 1/6 ; 3/6 = 1/2 ; 3/5.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Utiliser arbre et tableau de probabilités",goal:"énumérer tous les résultats possibles",concept:"Un diagramme en arbre montre les choix successifs. Chaque chemin représente un résultat. Un tableau peut également croiser les résultats de deux expériences.",example:"Deux lancers de pièce donnent PP, PF, FP et FF : quatre résultats équiprobables.",app:["Deux pièces : probabilité de deux piles, d’une pile exactement, d’au moins une pile, d’aucune pile.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["1/4 ; 2/4 = 1/2 ; 3/4 ; 1/4.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]},
 {t:"Exprimer et comparer des probabilités",goal:"passer entre fraction, décimal et pourcentage",concept:"Une probabilité est comprise entre 0 et 1, soit entre 0 % et 100 %. 0 signifie impossible, 1 certain. On peut l’écrire en fraction, nombre décimal ou pourcentage.",example:"3/4 = 0,75 = 75 % est plus probable que 1/2 = 0,5 = 50 %.",app:["Convertis et classe : 1/4 ; 0,6 ; 80 % ; 1/2.", "Explique les quatre réponses et indique le tableau, diagramme ou calcul utilisé."],ans:["1/4 = 0,25 = 25 % ; 1/2 = 0,5 = 50 % ; 0,6 = 60 % ; 80 % = 0,8. Ordre croissant : 1/4, 1/2, 0,6, 80 %.", "Chaque justification doit citer les données pertinentes et conduire clairement à la conclusion."]}
];

const geoQuadrilaterals = svgPng('quadrilateres-t6', `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="360"><rect width="100%" height="100%" fill="white"/><text x="35" y="42" font-size="30">Familles de quadrilatères</text><g fill="#DCEEFF" stroke="#1F4E79" stroke-width="5"><rect x="70" y="90" width="180" height="180"/><rect x="310" y="110" width="240" height="140"/><polygon points="680,80 800,180 680,280 560,180"/><polygon points="820,110 960,110 920,260 780,260"/></g><g font-size="25"><text x="115" y="320">Carré</text><text x="370" y="300">Rectangle</text><text x="630" y="320">Losange</text><text x="820" y="300">Trapèze</text></g></svg>`);
const geoAxes = svgPng('repere-t6', `<svg xmlns="http://www.w3.org/2000/svg" width="700" height="600"><rect width="100%" height="100%" fill="white"/><text x="30" y="38" font-size="28">Premier quadrant</text><g stroke="#B0B0B0">${[100,180,260,340,420,500,580].map(x=>`<line x1="${x}" y1="60" x2="${x}" y2="540"/>`).join('')}${[60,140,220,300,380,460,540].map(y=>`<line x1="100" y1="${y}" x2="620" y2="${y}"/>`).join('')}</g><g stroke="#1F4E79" stroke-width="4"><line x1="100" y1="540" x2="650" y2="540"/><line x1="100" y1="560" x2="100" y2="45"/></g><circle cx="340" cy="220" r="10" fill="#C00000"/><text x="355" y="210" font-size="25">A(3 ; 4)</text><text x="625" y="575" font-size="24">x</text><text x="65" y="65" font-size="24">y</text></svg>`);
const geoSolids = svgPng('prismes-t6', `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="400"><rect width="100%" height="100%" fill="white"/><text x="30" y="40" font-size="28">Prismes et patrons</text><g fill="#E9F5EC" stroke="#1F4E79" stroke-width="5"><polygon points="90,120 260,120 310,80 140,80"/><polygon points="90,120 90,290 260,290 260,120"/><polygon points="260,120 310,80 310,250 260,290"/><polygon points="470,120 560,70 650,120"/><polygon points="470,120 470,280 650,280 650,120"/><polygon points="650,120 740,70 740,230 650,280"/></g><text x="130" y="340" font-size="25">Pavé droit</text><text x="510" y="340" font-size="25">Prisme triangulaire</text></svg>`);
sessions.forEach((s,i)=>{ s.img = i < 8 ? geoAxes : geoSolids; });

// Independent assertions for all simple numerical answers used above.
console.assert(11/4===2.75 && 13/5===2.6 && 17/6>2.83 && 17/6<2.84);
console.assert((2/3)===(8/12) && 5/6>3/4);
console.assert(3/5===0.6 && 7/20===0.35 && 9/25===0.36 && 7/8===0.875);
console.assert(12===12 && 24===24 && 36===36);

function meta(s,n){ return new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[
 new TableRow({children:[cell(`Discipline : Mathématiques\nComposante : Traitement de données\nTitre : ${s.t}`,{width:68,bold:true}),cell(`Classe : T6\nSéance : ${n} / 13`,{width:32,bold:true})]}),
 new TableRow({children:[cell(`Objectif : À la fin de la séance, l’apprenant est capable de ${s.goal}.`,{span:2})]})
]}); }
function prep(s,n){
 const heads=[new TableRow({tableHeader:true,children:[cell('Étapes',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:13,align:AlignmentType.CENTER}),cell('Déroulement de la leçon',{span:2,fill:C.blue,color:C.white,bold:true,width:45,align:AlignmentType.CENTER}),cell('Technique et stratégie',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:15}),cell('Support et matériel',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:15}),cell('Observation',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:12})]}),new TableRow({tableHeader:true,children:[cell('Enseignant',{fill:C.pale,bold:true}),cell('Apprenants',{fill:C.pale,bold:true})]})];
 const rows=[
  ['I. Révision','Que retenez-vous de la notion précédente ? Donnez un exemple numérique.','Répondent oralement et justifient leur exemple.','Questions-réponses','Tableau, ardoises','Acquis à consolider'],
  ['II. NOUVELLE LEÇON','Annonce : « Aujourd’hui, nous allons apprendre à '+s.goal+'. »','Écoutent.','Présentation guidée','Tableau',''],
  ['1. Mise en situation',`Rova rencontre la situation suivante : ${s.example} Que remarquez-vous ?`,'Écoutent, observent et proposent des réponses.','Situation-problème','Illustration, tableau','Participation'],
  ['2. Présentation',`Présente le titre « ${s.t} » et précise l’objectif.`,'Écoutent.','Explication brève','Tableau',''],
  ['3. Observation',s.example,'Observent l’exemple résolu.','Observation dirigée',s.img?'Figure imprimée':'Tableau et ardoises','Compréhension'],
  ['4. Analyse',`Guide l’analyse : ${s.concept} Demande aux apprenants d’expliquer chaque étape.`,'Expliquent la démarche et vérifient le résultat.','Recherche en binômes','Ardoises, règle si nécessaire','Raisonnement'],
  ['5. Synthèse',s.concept,'Écoutent et reformulent la règle.','Synthèse guidée','Cahier, tableau','Trace écrite'],
  ['6. Application',s.app[0]+' '+s.app[1],s.ans[0]+' '+s.ans[1],'Travail individuel puis correction collective','Cahier, ardoises','Remédiation'],
  ['III. Évaluation',`Résous sans modèle : ${s.app[0]} Puis explique une réponse de ton choix.`,s.ans[0]+' Une justification correcte utilise la règle de la leçon.','Travail individuel','Feuille, cahier','Maîtrise de l’objectif']
 ].map((r,i)=>new TableRow({children:r.map((x,j)=>cell(x,{fill:i===1?C.paleGreen:undefined,bold:j===0,size:16}))}));
 return table([...heads,...rows]);
}
function lesson(s,n){
 const a=[]; a.push(page(),title(`LEÇON — ${s.t}`,1,`u6_l${n}`));
 a.push(title('1. Notion essentielle',2),labelPara('Définition. ',s.concept));
 a.push(title('2. Méthode pas à pas',2));
 a.push(bullet('Lire attentivement les données et identifier les nombres ou représentations utilisés.'));
 a.push(bullet('Choisir la règle adaptée à la situation.'));
 a.push(bullet('Effectuer chaque étape dans l’ordre et écrire les transformations intermédiaires.'));
 a.push(bullet('Vérifier que le résultat répond à la question et qu’il est cohérent.'));
 a.push(title('3. Exemple expliqué',2),labelPara('Exemple. ',s.example));
 if(s.img) a.push(new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:s.img,transformation:{width:500,height:s.img===grid100?500:180},type:'png'})]}));
 a.push(title('4. Erreurs à éviter',2));
 a.push(bullet('Modifier un nombre sans appliquer la même transformation à toute l’écriture.'));
 a.push(bullet('Oublier la valeur de position d’un chiffre ou le sens d’un symbole de comparaison.'));
 a.push(title('EXERCICES — Total : 20 points',1));
 a.push(p('Exercice 1 — 8 points. '+s.app[0]));
 a.push(p('Exercice 2 — 8 points. '+s.app[1]));
 a.push(p('Exercice 3 — 4 points. Rédige une phrase qui explique la méthode utilisée dans un item de ton choix.'));
 a.push(title('CORRIGÉ DÉTAILLÉ',2));
 a.push(correction('Exercice 1. ',s.ans[0]+' Chaque réponse correcte vaut 2 points.'));
 a.push(correction('Exercice 2. ',s.ans[1]+' Chaque réponse correcte vaut 2 points.'));
 a.push(correction('Exercice 3. ','La phrase doit citer la règle appropriée, montrer au moins une étape et conclure par le résultat. Une démarche cohérente et correctement formulée vaut 4 points.'));
 return a;
}
function revision(){return [page(),title('SÉANCE 12 / 13 — RÉVISION DE L’UNITÉ VI',1,'u6_l12'),title('Synthèse',2),p('Révise collecte, tableaux, diagrammes, moyenne, médiane, mode et probabilités.'),p('1. Quelle stratégie permet de compter les véhicules ? 2. Calcule la moyenne de 4, 6, 8, 10. 3. Donne la médiane et le mode de 2, 3, 3, 7, 9. 4. Donne P(nombre pair) avec un dé. 5. Convertis 0,35 en pourcentage.'),title('Réponses attendues',2),correction('1. ','L’observation directe.'),correction('2. ','7.'),correction('3. ','Médiane 3 et mode 3.'),correction('4. ','3/6 = 1/2 = 50 %.'),correction('5. ','35 %.')];}
function exam(){return [page(),title('SÉANCE 13 / 13 — SUJET D’EXAMEN T6 — UNITÉ VI',1,'u6_l13'),p('Barème : 20 points.'),p('Exercice 1 — 4 points. Pour étudier le trajet vers l’école, formule une question statistique, une hypothèse, une question quantitative et choisis une méthode de collecte.'),p('Exercice 2 — 4 points. Les effectifs des moyens de transport sont 18, 12, 7 et 3. Calcule le total et les pourcentages correspondants.'),p('Exercice 3 — 4 points. Pour la série 4, 6, 6, 8, 11, calcule moyenne, médiane, mode et étendue.'),p('Exercice 4 — 4 points. Deux pièces sont lancées. Construis la liste des résultats et calcule les probabilités d’obtenir deux piles, exactement une pile et au moins une pile.'),p('Exercice 5 — 4 points. Classe du moins probable au plus probable : 1/5, 0,45, 70 %, 3/4. Exprime chaque valeur en pourcentage.'),title('CORRIGÉ ET BARÈME',2),correction('Exercice 1. ','Exemple valide : « Quel moyen de transport utilises-tu ? » ; hypothèse : « la marche domine » ; durée du trajet en minutes ; questionnaire. Un point par élément.'),correction('Exercice 2. ','Total 40. Pourcentages : 45 %, 30 %, 17,5 % et 7,5 %. Un point pour le total et trois points pour les taux.'),correction('Exercice 3. ','Moyenne 7 ; médiane 6 ; mode 6 ; étendue 7. Un point par indicateur.'),correction('Exercice 4. ','PP, PF, FP, FF. P(deux piles) = 1/4 ; P(exactement une pile) = 1/2 ; P(au moins une pile) = 3/4.'),correction('Exercice 5. ','1/5 = 20 % < 0,45 = 45 % < 70 % < 3/4 = 75 %. Un point par conversion et classement cohérent.')];}

const children=[];
children.push(title('MANUEL DE MATHÉMATIQUES — CLASSE DE T6',1,'cover'),new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:250,after:200},children:[tr('Collection J-Learn',{bold:true,size:34,color:C.blue})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[tr('Programme officiel malgache — Version 1',{size:26})]}),new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:600},children:[tr('Unité VI — Traitement de données',{bold:true,size:30,color:C.green})]}));
children.push(page(),title('AVANT-PROPOS',1,'avant'),p('Ce manuel accompagne l’enseignant dans la mise en œuvre du programme officiel de Mathématiques T6. Il met l’apprenant au centre des activités : observation, manipulation, raisonnement, formulation d’une méthode, application et résolution de problèmes.'),p('Chaque séance associe une fiche de préparation directement exploitable, une leçon structurée, des exemples contextualisés, des exercices avec barème et un corrigé détaillé. Les situations mobilisent des repères familiers de Madagascar tout en développant la rigueur, la persévérance et l’autonomie.'));
children.push(title('MODE D’EMPLOI',1,'mode'),p('La fiche suit trois grandes étapes : I. Révision ; II. Nouvelle leçon, comprenant mise en situation, présentation, observation, analyse, synthèse et application ; III. Évaluation. À la demande de l’utilisateur, aucune durée chiffrée n’est affichée.'),p('Code couleur : titre de leçon en rouge ; sous-titres en vert ; mots-clés en bleu et en gras ; mots-clés des corrigés en bordeaux ; texte courant en noir.'));
children.push(title('SOMMAIRE INTERACTIF',1,'toc'));
children.push(new Paragraph({children:[new InternalHyperlink({anchor:'u6',children:[tr('Unité VI — Traitement de données',{bold:true,color:C.blue})]})]}));
sessions.forEach((s,i)=>children.push(new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:`u6_l${i+1}`,children:[tr(`Séance ${i+1} — ${s.t}`,{color:C.blue})]})]})));
children.push(new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:'u6_l12',children:[tr('Séance 12 — Révision de l’unité I',{color:C.blue})]})]}),new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:'u6_l13',children:[tr('Séance 13 — Sujet d’examen',{color:C.blue})]})]}));
children.push(page(),title('UNITÉ VI — TRAITEMENT DE DONNÉES',1,'u6'),p('Résultat d’apprentissage général : recueillir et traiter des données statistiques ou probabilistes pour faire des prédictions et prendre des décisions éclairées.'),p('Valeurs à véhiculer : goût de l’effort et rigueur.'),title('Tableau de bord',2),table([new TableRow({children:[cell('Séances',{bold:true,fill:C.blue,color:C.white}),cell('Apprentissages',{bold:true,fill:C.blue,color:C.white}),cell('Révision',{bold:true,fill:C.blue,color:C.white}),cell('Examen',{bold:true,fill:C.blue,color:C.white})]}),new TableRow({children:[cell('13'),cell('11'),cell('1'),cell('1')]})]));
sessions.forEach((s,i)=>{children.push(page(),title(`SÉANCE ${i+1} / 15 — ${s.t.toUpperCase()}`,1,`u6_s${i+1}`),title('FICHE DE PRÉPARATION',2),meta(s,i+1),prep(s,i+1),...lesson(s,i+1));});
children.push(...revision(),...exam());

const doc=new Document({styles:{default:{document:{run:{font:'Times New Roman',size:22},paragraph:{spacing:{line:276}}}}},sections:[{properties:{page:{margin:{top:900,right:720,bottom:900,left:720}}},headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[tr('J-Learn — Mathématiques T6 — Unité VI',{size:18,color:'666666'})]})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[tr('Page ',{size:18}),new TextRun({children:[PageNumber.CURRENT],font:'Times New Roman',size:18})]})]})},children}]});
Packer.toBuffer(doc).then(buf=>{fs.writeFileSync(OUT,buf);console.log(`${OUT}: ${buf.length} octets`);});
