const fs = require('fs');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, BorderStyle, ShadingType, PageBreak,
  Header, Footer, PageNumber, Bookmark, InternalHyperlink,
  ImageRun, Math: DocxMath, MathFraction, MathRun
} = require('docx');

const OUT = 'Manuel_Mathematiques_T6_V1_UNITE4.docx';
const C = { red:'C00000', green:'1E7B34', blue:'1F4E79', wine:'C2185B', pale:'EAF2F8', paleGreen:'E9F5EC', gray:'E7E6E6', black:'000000', white:'FFFFFF' };
const noBorders = {top:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},bottom:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},left:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},right:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideHorizontal:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideVertical:{style:BorderStyle.NONE,size:0,color:'FFFFFF'}};
const borders = {top:{style:BorderStyle.SINGLE,size:4,color:'808080'},bottom:{style:BorderStyle.SINGLE,size:4,color:'808080'},left:{style:BorderStyle.SINGLE,size:4,color:'808080'},right:{style:BorderStyle.SINGLE,size:4,color:'808080'},insideHorizontal:{style:BorderStyle.SINGLE,size:4,color:'B0B0B0'},insideVertical:{style:BorderStyle.SINGLE,size:4,color:'B0B0B0'}};
const tr = (text,opt={}) => new TextRun({text, font:'Times New Roman', size:opt.size||22, bold:!!opt.bold, color:opt.color||C.black, italics:!!opt.italics});
// Convert every numeric a/b expression to a native Word OMML fraction.
const rich = (text,opt={}) => {
  const out=[]; let last=0; const re=/(\d[\d ]*)\/(\d[\d ]*)/g; let m;
  while((m=re.exec(text))){
    if(m.index>last) out.push(tr(text.slice(last,m.index),opt));
    out.push(new DocxMath({children:[new MathFraction({numerator:[new MathRun(m[1].trim())],denominator:[new MathRun(m[2].trim())]})]}));
    last=re.lastIndex;
  }
  if(last<text.length) out.push(tr(text.slice(last),opt));
  return out.length?out:[tr(text,opt)];
};
const p = (text,opt={}) => new Paragraph({alignment:opt.align||AlignmentType.JUSTIFIED, spacing:{after:opt.after??100,line:276}, indent:opt.indent?{left:opt.indent}:undefined, children:rich(text,opt)});
const title = (text, level=1, bookmark) => {
 const run = tr(text,{bold:true,color:level===1?C.red:C.green,size:level===1?32:26});
 const children = bookmark ? [new Bookmark({id:bookmark, children:[run]})] : [run];
 return new Paragraph({alignment:level===1?AlignmentType.CENTER:AlignmentType.LEFT, spacing:{before:180,after:140}, children});
};
const cell = (text,opt={}) => new TableCell({width:opt.width?{size:opt.width,type:WidthType.PERCENTAGE}:undefined, columnSpan:opt.span, rowSpan:opt.rowSpan, shading:opt.fill?{type:ShadingType.CLEAR,fill:opt.fill}:undefined, margins:{top:80,bottom:80,left:80,right:80}, children:[new Paragraph({alignment:opt.align||AlignmentType.LEFT,children:rich(text,{bold:opt.bold,color:opt.color||C.black,size:opt.size||18})})]});
const table = rows => new Table({width:{size:100,type:WidthType.PERCENTAGE},borders,rows});
const bullet = text => new Paragraph({bullet:{level:0},spacing:{after:70},children:rich(text)});
const labelPara = (label,text) => new Paragraph({spacing:{after:90},children:[tr(label,{bold:true,color:C.blue}),...rich(text)]});
const correction = (label,text) => new Paragraph({spacing:{after:70},children:[tr(label,{bold:true,color:C.wine}),...rich(text)]});
const page = () => new Paragraph({children:[new PageBreak()]});

function svgPng(name, svg) {
 const dir='assets/math-t6'; fs.mkdirSync(dir,{recursive:true});
 fs.writeFileSync(`${dir}/${name}.svg`,svg);
 require('child_process').execFileSync(process.execPath,['-e',`require('sharp')('${dir}/${name}.svg').png().toFile('${dir}/${name}.png')`]);
 return fs.readFileSync(`${dir}/${name}.png`);
}
const fractionBars = svgPng('fractions-equivalentes',`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="360"><rect width="100%" height="100%" fill="white"/><text x="40" y="55" font-family="serif" font-size="34">Une même quantité représentée de trois façons</text><g stroke="#1F4E79" stroke-width="4"><rect x="80" y="100" width="800" height="55" fill="white"/><rect x="80" y="100" width="400" height="55" fill="#79B6E3"/><line x1="480" y1="100" x2="480" y2="155"/><rect x="80" y="185" width="800" height="55" fill="white"/><rect x="80" y="185" width="400" height="55" fill="#79B6E3"/><line x1="280" y1="185" x2="280" y2="240"/><line x1="480" y1="185" x2="480" y2="240"/><line x1="680" y1="185" x2="680" y2="240"/><rect x="80" y="270" width="800" height="55" fill="white"/><rect x="80" y="270" width="400" height="55" fill="#79B6E3"/>${[180,280,380,480,580,680,780].map(x=>`<line x1="${x}" y1="270" x2="${x}" y2="325"/>`).join('')}</g><text x="900" y="140" font-size="30">1/2</text><text x="900" y="225" font-size="30">2/4</text><text x="900" y="310" font-size="30">4/8</text></svg>`);
const numberLine = svgPng('droite-fractions',`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="260"><rect width="100%" height="100%" fill="white"/><text x="40" y="48" font-family="serif" font-size="34">Droite numérique partagée en huitièmes</text><line x1="80" y1="140" x2="920" y2="140" stroke="#1F4E79" stroke-width="5"/>${[0,1,2,3,4,5,6,7,8].map((n,i)=>`<line x1="${80+i*105}" y1="115" x2="${80+i*105}" y2="165" stroke="#1F4E79" stroke-width="4"/><text x="${70+i*105}" y="205" font-size="26">${n===0?'0':n===8?'1':n+'/8'}</text>`).join('')}</svg>`);
const grid100 = svgPng('grille-pourcentage',`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="700"><rect width="100%" height="100%" fill="white"/><text x="50" y="45" font-size="30">35 cases sur 100 = 35 % = 0,35</text>${Array.from({length:100},(_,k)=>{let x=50+(k%10)*55,y=80+Math.floor(k/10)*55;return `<rect x="${x}" y="${y}" width="55" height="55" fill="${k<35?'#79B6E3':'white'}" stroke="#777"/>`}).join('')}</svg>`);

const sessions = [
 {t:"Reconnaître les familles de quadrilatères",goal:"nommer les principales familles de quadrilatères",concept:"Un quadrilatère est un polygone à quatre côtés. Le carré, le rectangle, le losange, le parallélogramme et le trapèze se distinguent par leurs côtés et leurs angles.",example:"Un carré possède quatre côtés égaux et quatre angles droits.",app:["Nomme : quatre côtés égaux et quatre angles droits ; côtés opposés égaux et quatre angles droits ; quatre côtés égaux sans angle droit ; une seule paire de côtés parallèles.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Carré ; rectangle ; losange ; trapèze.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Décrire les côtés et les angles des quadrilatères",goal:"décrire les côtés et les angles avec un vocabulaire précis",concept:"Des côtés peuvent être parallèles, perpendiculaires ou de même longueur. Un angle peut être droit, aigu ou obtus. Les codages permettent de lire ces propriétés.",example:"Dans un rectangle, les côtés opposés sont parallèles et égaux, et les quatre angles sont droits.",app:["Décris les côtés et angles d’un carré, d’un rectangle, d’un losange et d’un parallélogramme.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Carré : quatre côtés égaux et quatre angles droits ; rectangle : côtés opposés égaux et quatre angles droits ; losange : quatre côtés égaux et angles opposés égaux ; parallélogramme : côtés opposés parallèles et égaux.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Étudier les diagonales et les axes de symétrie",goal:"comparer diagonales et axes de symétrie",concept:"Une diagonale relie deux sommets non consécutifs. Un axe de symétrie partage une figure en deux parties superposables.",example:"Le carré possède deux diagonales égales, perpendiculaires et qui se coupent en leur milieu ; il possède quatre axes de symétrie.",app:["Donne le nombre d’axes de symétrie du carré, du rectangle non carré, du losange non carré et du parallélogramme quelconque.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["4 ; 2 ; 2 ; 0.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Classer les quadrilatères",goal:"classer les quadrilatères à partir de plusieurs critères",concept:"Une figure peut appartenir à plusieurs familles. Tout carré est aussi un rectangle, un losange et un parallélogramme, mais la réciproque est fausse.",example:"Un carré vérifie les propriétés du rectangle et du losange.",app:["Indique si c’est toujours vrai : tout carré est rectangle ; tout rectangle est carré ; tout losange est parallélogramme ; tout parallélogramme est losange.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Vrai ; faux ; vrai ; faux.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Comparer les propriétés des quadrilatères",goal:"utiliser un tableau de propriétés pour identifier une figure",concept:"On identifie un quadrilatère en croisant plusieurs propriétés : parallélisme, égalité des côtés, angles droits, diagonales et symétries.",example:"Quatre angles droits suffisent pour identifier un rectangle ; quatre côtés égaux et quatre angles droits identifient un carré.",app:["Identifie : quatre angles droits ; quatre côtés égaux ; côtés opposés parallèles ; quatre côtés égaux et quatre angles droits.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Rectangle ; losange ; parallélogramme ; carré.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Calculer un angle manquant dans un triangle",goal:"utiliser la somme des angles d’un triangle",concept:"La somme des trois angles intérieurs d’un triangle est égale à 180°. L’angle manquant vaut 180° moins la somme des deux angles connus.",example:"Dans un triangle, deux angles mesurent 50° et 65° : le troisième vaut 180° − 115° = 65°.",app:["Calcule l’angle manquant : 40° et 70° ; 90° et 35° ; 55° et 55° ; 25° et 105°.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["70° ; 55° ; 70° ; 50°.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Calculer des angles dans un quadrilatère",goal:"utiliser la somme des angles d’un quadrilatère",concept:"La somme des angles intérieurs d’un quadrilatère est 360°, car une diagonale le partage en deux triangles.",example:"Trois angles valent 80°, 95° et 110° : le quatrième vaut 360° − 285° = 75°.",app:["Calcule le quatrième angle : 90°, 90°, 90° ; 70°, 110°, 85° ; 120°, 60°, 100° ; 45°, 135°, 90°.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["90° ; 95° ; 80° ; 90°.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Construire des quadrilatères",goal:"tracer un quadrilatère avec des instruments",concept:"Une construction exacte suit un programme : tracer une base, mesurer les angles ou perpendiculaires, reporter les longueurs puis vérifier les propriétés.",example:"Pour un rectangle de 6 cm sur 4 cm, on trace la base de 6 cm puis deux perpendiculaires de 4 cm.",app:["Rédige les étapes pour construire un carré de 5 cm, un rectangle de 7 cm sur 3 cm, un losange de côté 4 cm et un parallélogramme de côtés 6 cm et 4 cm.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Les programmes doivent préciser la base, les longueurs, les parallèles ou perpendiculaires et la fermeture de la figure.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Construire des triangles",goal:"construire des triangles à partir de mesures",concept:"Un triangle est constructible lorsque la longueur du plus grand côté est inférieure à la somme des deux autres. On utilise règle, compas et rapporteur selon les données.",example:"Les longueurs 4 cm, 5 cm et 6 cm permettent une construction car 6 < 4 + 5.",app:["Indique si les triangles sont constructibles : 3, 4, 5 cm ; 2, 3, 6 cm ; 5, 5, 8 cm ; 4, 7, 10 cm.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Oui ; non ; oui ; oui.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Construire cercle et polygones",goal:"construire cercle, pentagone, hexagone et octogone",concept:"Un cercle est défini par son centre et son rayon. Un polygone régulier a tous ses côtés et tous ses angles égaux.",example:"Dans un hexagone régulier inscrit, la longueur d’un côté est égale au rayon du cercle.",app:["Donne le nombre de côtés et de sommets du pentagone, de l’hexagone, de l’octogone et du décagone.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["5 et 5 ; 6 et 6 ; 8 et 8 ; 10 et 10.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Composer et décomposer des figures",goal:"former une figure à partir de figures connues",concept:"Composer consiste à assembler des figures sans chevauchement ; décomposer consiste à partager une figure en figures plus simples pour étudier ses propriétés.",example:"Une diagonale décompose un parallélogramme en deux triangles superposables.",app:["Donne une décomposition possible d’un rectangle, d’un carré, d’un trapèze et d’un hexagone.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Deux triangles ; deux rectangles ou deux triangles ; un rectangle et deux triangles ; plusieurs triangles.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Distinguer prismes et non-prismes",goal:"comparer prismes et autres solides",concept:"Un prisme possède deux bases polygonales parallèles et superposables, reliées par des faces latérales. Une pyramide, un cône, un cylindre et une boule ne sont pas des prismes polygonaux.",example:"Un pavé droit est un prisme à base rectangulaire.",app:["Classe : cube, pavé droit, prisme triangulaire, pyramide, cylindre, cône, boule, prisme pentagonal.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Prismes : cube, pavé droit, prisme triangulaire, prisme pentagonal. Non-prismes : pyramide, cylindre, cône, boule.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Construire des patrons de prismes",goal:"reconnaître et construire un patron de prisme",concept:"Un patron est une figure plane qui permet d’obtenir un solide par pliage. Toutes les faces doivent être présentes et correctement reliées.",example:"Le patron d’un cube contient six carrés égaux.",app:["Donne les faces d’un cube, d’un pavé droit, d’un prisme triangulaire et d’un prisme pentagonal.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["6 carrés ; 6 rectangles ; 2 triangles et 3 rectangles ; 2 pentagones et 5 rectangles.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Se repérer dans le premier quadrant",goal:"identifier origine, axes, abscisse et ordonnée",concept:"Dans le premier quadrant, les coordonnées sont positives. Un point s’écrit (abscisse ; ordonnée) : on se déplace d’abord horizontalement puis verticalement.",example:"A(3 ; 5) est à 3 unités sur l’axe des abscisses puis 5 unités vers le haut.",app:["Pour A(2 ; 4), B(5 ; 1), C(0 ; 6), D(7 ; 0), donne abscisse et ordonnée.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["A : 2 et 4 ; B : 5 et 1 ; C : 0 et 6 ; D : 7 et 0.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Placer et lire des coordonnées",goal:"placer des points et lire leurs coordonnées",concept:"Pour lire des coordonnées, on projette le point sur chaque axe. L’ordre abscisse puis ordonnée ne doit jamais être inversé.",example:"B(6 ; 2) et C(2 ; 6) sont deux points différents.",app:["Place mentalement A(1 ; 3), B(4 ; 2), C(5 ; 5), D(0 ; 4), puis donne les coordonnées après un déplacement de 2 unités à droite.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["A’(3 ; 3), B’(6 ; 2), C’(7 ; 5), D’(2 ; 4).", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]},
 {t:"Effectuer des transformations successives",goal:"reconnaître translation, réflexion et rotation",concept:"Une translation déplace sans tourner, une réflexion retourne par rapport à un axe et une rotation tourne autour d’un centre. Elles conservent longueurs et angles.",example:"Une rotation de 90° autour de O conserve la forme et la taille mais change l’orientation.",app:["Nomme la transformation : glissement de 4 cases ; retournement sur un axe ; quart de tour ; demi-tour. Indique ce qui est conservé.", "Explique la règle utilisée dans chacun des quatre cas et vérifie les réponses obtenues."],ans:["Translation ; réflexion ; rotation de 90° ; rotation de 180°. Les longueurs, angles, forme et aire sont conservés.", "La vérification doit reprendre la propriété de la leçon et montrer qu’elle est satisfaite pour chaque cas."]}
];

const geoQuadrilaterals = svgPng('quadrilateres-t6', `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="360"><rect width="100%" height="100%" fill="white"/><text x="35" y="42" font-size="30">Familles de quadrilatères</text><g fill="#DCEEFF" stroke="#1F4E79" stroke-width="5"><rect x="70" y="90" width="180" height="180"/><rect x="310" y="110" width="240" height="140"/><polygon points="680,80 800,180 680,280 560,180"/><polygon points="820,110 960,110 920,260 780,260"/></g><g font-size="25"><text x="115" y="320">Carré</text><text x="370" y="300">Rectangle</text><text x="630" y="320">Losange</text><text x="820" y="300">Trapèze</text></g></svg>`);
const geoAxes = svgPng('repere-t6', `<svg xmlns="http://www.w3.org/2000/svg" width="700" height="600"><rect width="100%" height="100%" fill="white"/><text x="30" y="38" font-size="28">Premier quadrant</text><g stroke="#B0B0B0">${[100,180,260,340,420,500,580].map(x=>`<line x1="${x}" y1="60" x2="${x}" y2="540"/>`).join('')}${[60,140,220,300,380,460,540].map(y=>`<line x1="100" y1="${y}" x2="620" y2="${y}"/>`).join('')}</g><g stroke="#1F4E79" stroke-width="4"><line x1="100" y1="540" x2="650" y2="540"/><line x1="100" y1="560" x2="100" y2="45"/></g><circle cx="340" cy="220" r="10" fill="#C00000"/><text x="355" y="210" font-size="25">A(3 ; 4)</text><text x="625" y="575" font-size="24">x</text><text x="65" y="65" font-size="24">y</text></svg>`);
const geoSolids = svgPng('prismes-t6', `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="400"><rect width="100%" height="100%" fill="white"/><text x="30" y="40" font-size="28">Prismes et patrons</text><g fill="#E9F5EC" stroke="#1F4E79" stroke-width="5"><polygon points="90,120 260,120 310,80 140,80"/><polygon points="90,120 90,290 260,290 260,120"/><polygon points="260,120 310,80 310,250 260,290"/><polygon points="470,120 560,70 650,120"/><polygon points="470,120 470,280 650,280 650,120"/><polygon points="650,120 740,70 740,230 650,280"/></g><text x="130" y="340" font-size="25">Pavé droit</text><text x="510" y="340" font-size="25">Prisme triangulaire</text></svg>`);
sessions.forEach((s,i)=>{ s.img = i < 8 ? geoQuadrilaterals : (i < 13 ? geoSolids : geoAxes); });

// Independent assertions for all simple numerical answers used above.
console.assert(11/4===2.75 && 13/5===2.6 && 17/6>2.83 && 17/6<2.84);
console.assert((2/3)===(8/12) && 5/6>3/4);
console.assert(3/5===0.6 && 7/20===0.35 && 9/25===0.36 && 7/8===0.875);
console.assert(12===12 && 24===24 && 36===36);

function meta(s,n){ return new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[
 new TableRow({children:[cell(`Discipline : Mathématiques\nComposante : Géométrie\nTitre : ${s.t}`,{width:68,bold:true}),cell(`Classe : T6\nSéance : ${n} / 18`,{width:32,bold:true})]}),
 new TableRow({children:[cell(`Objectif : À la fin de la séance, l’apprenant est capable de ${s.goal}.`,{span:2})]})
]}); }
function prep(s,n){
 const heads=[new TableRow({tableHeader:true,children:[cell('Étapes',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:13,align:AlignmentType.CENTER}),cell('Déroulement de la leçon',{span:2,fill:C.blue,color:C.white,bold:true,width:45,align:AlignmentType.CENTER}),cell('Technique et stratégie',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:15}),cell('Support et matériel',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:15}),cell('Observation',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:12})]}),new TableRow({tableHeader:true,children:[cell('Enseignant',{fill:C.pale,bold:true}),cell('Apprenants',{fill:C.pale,bold:true})]})];
 const rows=[
  ['I. Révision','Que retenez-vous de la notion précédente ? Donnez un exemple numérique.','Répondent oralement et justifient leur exemple.','Questions-réponses','Tableau, ardoises','Acquis à consolider'],
  ['II. NOUVELLE LEÇON','Annonce : « Aujourd’hui, nous allons apprendre à '+s.goal+'. »','Écoutent.','Présentation guidée','Tableau',''],
  ['1. Mise en situation',`Rova rencontre la situation suivante : ${s.example} Que remarquez-vous ?`,'Écoutent, observent et proposent des réponses.','Situation-problème','Illustration, tableau','Participation'],
  ['2. Présentation',`Présente le titre « ${s.t} » et précise l’objectif.`,'Écoutent.','Explication brève','Tableau',''],
  ['3. Observation',s.example,'Observent l’exemple résolu.','Observation dirigée',s.img?'Figure imprimée':'Tableau et ardoises','Compréhension'],
  ['4. Analyse',`Guide l’analyse : ${s.concept} Demande aux apprenants d’expliquer chaque étape.`,'Expliquent la démarche et vérifient le résultat.','Recherche en binômes','Ardoises, règle si nécessaire','Raisonnement'],
  ['5. Synthèse',s.concept,'Écoutent et reformulent la règle.','Synthèse guidée','Cahier, tableau','Trace écrite'],
  ['6. Application',s.app[0]+' '+s.app[1],s.ans[0]+' '+s.ans[1],'Travail individuel puis correction collective','Cahier, ardoises','Remédiation'],
  ['III. Évaluation',`Résous sans modèle : ${s.app[0]} Puis explique une réponse de ton choix.`,s.ans[0]+' Une justification correcte utilise la règle de la leçon.','Travail individuel','Feuille, cahier','Maîtrise de l’objectif']
 ].map((r,i)=>new TableRow({children:r.map((x,j)=>cell(x,{fill:i===1?C.paleGreen:undefined,bold:j===0,size:16}))}));
 return table([...heads,...rows]);
}
function lesson(s,n){
 const a=[]; a.push(page(),title(`LEÇON — ${s.t}`,1,`u4_l${n}`));
 a.push(title('1. Notion essentielle',2),labelPara('Définition. ',s.concept));
 a.push(title('2. Méthode pas à pas',2));
 a.push(bullet('Lire attentivement les données et identifier les nombres ou représentations utilisés.'));
 a.push(bullet('Choisir la règle adaptée à la situation.'));
 a.push(bullet('Effectuer chaque étape dans l’ordre et écrire les transformations intermédiaires.'));
 a.push(bullet('Vérifier que le résultat répond à la question et qu’il est cohérent.'));
 a.push(title('3. Exemple expliqué',2),labelPara('Exemple. ',s.example));
 if(s.img) a.push(new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:s.img,transformation:{width:500,height:s.img===grid100?500:180},type:'png'})]}));
 a.push(title('4. Erreurs à éviter',2));
 a.push(bullet('Modifier un nombre sans appliquer la même transformation à toute l’écriture.'));
 a.push(bullet('Oublier la valeur de position d’un chiffre ou le sens d’un symbole de comparaison.'));
 a.push(title('EXERCICES — Total : 20 points',1));
 a.push(p('Exercice 1 — 8 points. '+s.app[0]));
 a.push(p('Exercice 2 — 8 points. '+s.app[1]));
 a.push(p('Exercice 3 — 4 points. Rédige une phrase qui explique la méthode utilisée dans un item de ton choix.'));
 a.push(title('CORRIGÉ DÉTAILLÉ',2));
 a.push(correction('Exercice 1. ',s.ans[0]+' Chaque réponse correcte vaut 2 points.'));
 a.push(correction('Exercice 2. ',s.ans[1]+' Chaque réponse correcte vaut 2 points.'));
 a.push(correction('Exercice 3. ','La phrase doit citer la règle appropriée, montrer au moins une étape et conclure par le résultat. Une démarche cohérente et correctement formulée vaut 4 points.'));
 return a;
}
function revision(){return [page(),title('SÉANCE 17 / 18 — RÉVISION DE L’UNITÉ IV',1,'u4_l17'),title('Synthèse',2),p('Révise les quadrilatères, les angles, les constructions, les prismes, le repérage et les transformations.'),p('1. Quelle est la somme des angles d’un quadrilatère ? 2. Cite les propriétés d’un carré. 3. Décris un prisme triangulaire. 4. Lis A(4 ; 7). 5. Distingue translation, réflexion et rotation.'),title('Réponses attendues',2),correction('1. ','360°.'),correction('2. ','Quatre côtés égaux et quatre angles droits.'),correction('3. ','Deux bases triangulaires et trois faces latérales rectangulaires.'),correction('4. ','Abscisse 4 et ordonnée 7.'),correction('5. ','La translation glisse, la réflexion retourne et la rotation tourne autour d’un centre.')];}
function exam(){return [page(),title('SÉANCE 18 / 18 — SUJET D’EXAMEN T6 — UNITÉ IV',1,'u4_l18'),p('Barème : 20 points.'),p('Exercice 1 — 4 points. Décris les côtés, angles et diagonales du carré et du rectangle.'),p('Exercice 2 — 4 points. Calcule les angles manquants : triangle 45° et 70° ; triangle 90° et 28° ; quadrilatère 80°, 90°, 100° ; quadrilatère 65°, 115°, 75°.'),p('Exercice 3 — 4 points. Rédige le programme de construction d’un rectangle de 6 cm sur 4 cm et d’un triangle de côtés 4 cm, 5 cm et 6 cm.'),p('Exercice 4 — 4 points. Donne les faces d’un prisme triangulaire et d’un pavé droit, puis explique ce qu’est un patron.'),p('Exercice 5 — 4 points. Place A(2 ; 3), B(5 ; 1), C(4 ; 6), D(0 ; 2), puis donne leurs images par une translation de 3 unités à droite.'),title('CORRIGÉ ET BARÈME',2),correction('Exercice 1. ','Carré : quatre côtés égaux, quatre angles droits, diagonales égales et perpendiculaires. Rectangle : côtés opposés égaux, quatre angles droits, diagonales égales. Deux points par figure.'),correction('Exercice 2. ','65° ; 62° ; 90° ; 105°. Un point par réponse.'),correction('Exercice 3. ','Les programmes indiquent les mesures, les instruments, l’ordre des tracés et la vérification. Deux points par construction.'),correction('Exercice 4. ','Prisme triangulaire : deux triangles et trois rectangles. Pavé : six rectangles. Un patron contient toutes les faces reliées pour former le solide par pliage.'),correction('Exercice 5. ','A’(5 ; 3), B’(8 ; 1), C’(7 ; 6), D’(3 ; 2). Un point par point.')];}

const children=[];
children.push(title('MANUEL DE MATHÉMATIQUES — CLASSE DE T6',1,'cover'),new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:250,after:200},children:[tr('Collection J-Learn',{bold:true,size:34,color:C.blue})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[tr('Programme officiel malgache — Version 1',{size:26})]}),new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:600},children:[tr('Unité IV — Géométrie',{bold:true,size:30,color:C.green})]}));
children.push(page(),title('AVANT-PROPOS',1,'avant'),p('Ce manuel accompagne l’enseignant dans la mise en œuvre du programme officiel de Mathématiques T6. Il met l’apprenant au centre des activités : observation, manipulation, raisonnement, formulation d’une méthode, application et résolution de problèmes.'),p('Chaque séance associe une fiche de préparation directement exploitable, une leçon structurée, des exemples contextualisés, des exercices avec barème et un corrigé détaillé. Les situations mobilisent des repères familiers de Madagascar tout en développant la rigueur, la persévérance et l’autonomie.'));
children.push(title('MODE D’EMPLOI',1,'mode'),p('La fiche suit trois grandes étapes : I. Révision ; II. Nouvelle leçon, comprenant mise en situation, présentation, observation, analyse, synthèse et application ; III. Évaluation. À la demande de l’utilisateur, aucune durée chiffrée n’est affichée.'),p('Code couleur : titre de leçon en rouge ; sous-titres en vert ; mots-clés en bleu et en gras ; mots-clés des corrigés en bordeaux ; texte courant en noir.'));
children.push(title('SOMMAIRE INTERACTIF',1,'toc'));
children.push(new Paragraph({children:[new InternalHyperlink({anchor:'u4',children:[tr('Unité IV — Géométrie',{bold:true,color:C.blue})]})]}));
sessions.forEach((s,i)=>children.push(new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:`u4_l${i+1}`,children:[tr(`Séance ${i+1} — ${s.t}`,{color:C.blue})]})]})));
children.push(new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:'u4_l17',children:[tr('Séance 17 — Révision de l’unité I',{color:C.blue})]})]}),new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:'u4_l18',children:[tr('Séance 18 — Sujet d’examen',{color:C.blue})]})]}));
children.push(page(),title('UNITÉ IV — GÉOMÉTRIE',1,'u4'),p('Résultat d’apprentissage général : décrire, comparer et analyser les figures géométriques pour comprendre les structures du monde réel et en créer de nouvelles.'),p('Valeurs à véhiculer : persévérance et sens de la responsabilité.'),title('Tableau de bord',2),table([new TableRow({children:[cell('Séances',{bold:true,fill:C.blue,color:C.white}),cell('Apprentissages',{bold:true,fill:C.blue,color:C.white}),cell('Révision',{bold:true,fill:C.blue,color:C.white}),cell('Examen',{bold:true,fill:C.blue,color:C.white})]}),new TableRow({children:[cell('18'),cell('16'),cell('1'),cell('1')]})]));
sessions.forEach((s,i)=>{children.push(page(),title(`SÉANCE ${i+1} / 15 — ${s.t.toUpperCase()}`,1,`u4_s${i+1}`),title('FICHE DE PRÉPARATION',2),meta(s,i+1),prep(s,i+1),...lesson(s,i+1));});
children.push(...revision(),...exam());

const doc=new Document({styles:{default:{document:{run:{font:'Times New Roman',size:22},paragraph:{spacing:{line:276}}}}},sections:[{properties:{page:{margin:{top:900,right:720,bottom:900,left:720}}},headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[tr('J-Learn — Mathématiques T6 — Unité IV',{size:18,color:'666666'})]})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[tr('Page ',{size:18}),new TextRun({children:[PageNumber.CURRENT],font:'Times New Roman',size:18})]})]})},children}]});
Packer.toBuffer(doc).then(buf=>{fs.writeFileSync(OUT,buf);console.log(`${OUT}: ${buf.length} octets`);});
