const fs = require('fs');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, BorderStyle, ShadingType, PageBreak,
  Header, Footer, PageNumber, Bookmark, InternalHyperlink,
  ImageRun, Math: DocxMath, MathFraction, MathRun
} = require('docx');

const OUT = 'Manuel_Mathematiques_T6_V1_UNITE3.docx';
const C = { red:'C00000', green:'1E7B34', blue:'1F4E79', wine:'C2185B', pale:'EAF2F8', paleGreen:'E9F5EC', gray:'E7E6E6', black:'000000', white:'FFFFFF' };
const noBorders = {top:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},bottom:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},left:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},right:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideHorizontal:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideVertical:{style:BorderStyle.NONE,size:0,color:'FFFFFF'}};
const borders = {top:{style:BorderStyle.SINGLE,size:4,color:'808080'},bottom:{style:BorderStyle.SINGLE,size:4,color:'808080'},left:{style:BorderStyle.SINGLE,size:4,color:'808080'},right:{style:BorderStyle.SINGLE,size:4,color:'808080'},insideHorizontal:{style:BorderStyle.SINGLE,size:4,color:'B0B0B0'},insideVertical:{style:BorderStyle.SINGLE,size:4,color:'B0B0B0'}};
const tr = (text,opt={}) => new TextRun({text, font:'Times New Roman', size:opt.size||22, bold:!!opt.bold, color:opt.color||C.black, italics:!!opt.italics});
// Convert every numeric a/b expression to a native Word OMML fraction.
const rich = (text,opt={}) => {
  const out=[]; let last=0; const re=/(\d[\d ]*)\/(\d[\d ]*)/g; let m;
  while((m=re.exec(text))){
    if(m.index>last) out.push(tr(text.slice(last,m.index),opt));
    out.push(new DocxMath({children:[new MathFraction({numerator:[new MathRun(m[1].trim())],denominator:[new MathRun(m[2].trim())]})]}));
    last=re.lastIndex;
  }
  if(last<text.length) out.push(tr(text.slice(last),opt));
  return out.length?out:[tr(text,opt)];
};
const p = (text,opt={}) => new Paragraph({alignment:opt.align||AlignmentType.JUSTIFIED, spacing:{after:opt.after??100,line:276}, indent:opt.indent?{left:opt.indent}:undefined, children:rich(text,opt)});
const title = (text, level=1, bookmark) => {
 const run = tr(text,{bold:true,color:level===1?C.red:C.green,size:level===1?32:26});
 const children = bookmark ? [new Bookmark({id:bookmark, children:[run]})] : [run];
 return new Paragraph({alignment:level===1?AlignmentType.CENTER:AlignmentType.LEFT, spacing:{before:180,after:140}, children});
};
const cell = (text,opt={}) => new TableCell({width:opt.width?{size:opt.width,type:WidthType.PERCENTAGE}:undefined, columnSpan:opt.span, rowSpan:opt.rowSpan, shading:opt.fill?{type:ShadingType.CLEAR,fill:opt.fill}:undefined, margins:{top:80,bottom:80,left:80,right:80}, children:[new Paragraph({alignment:opt.align||AlignmentType.LEFT,children:rich(text,{bold:opt.bold,color:opt.color||C.black,size:opt.size||18})})]});
const table = rows => new Table({width:{size:100,type:WidthType.PERCENTAGE},borders,rows});
const bullet = text => new Paragraph({bullet:{level:0},spacing:{after:70},children:rich(text)});
const labelPara = (label,text) => new Paragraph({spacing:{after:90},children:[tr(label,{bold:true,color:C.blue}),...rich(text)]});
const correction = (label,text) => new Paragraph({spacing:{after:70},children:[tr(label,{bold:true,color:C.wine}),...rich(text)]});
const page = () => new Paragraph({children:[new PageBreak()]});

function svgPng(name, svg) {
 const dir='assets/math-t6'; fs.mkdirSync(dir,{recursive:true});
 fs.writeFileSync(`${dir}/${name}.svg`,svg);
 require('child_process').execFileSync(process.execPath,['-e',`require('sharp')('${dir}/${name}.svg').png().toFile('${dir}/${name}.png')`]);
 return fs.readFileSync(`${dir}/${name}.png`);
}
const fractionBars = svgPng('fractions-equivalentes',`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="360"><rect width="100%" height="100%" fill="white"/><text x="40" y="55" font-family="serif" font-size="34">Une même quantité représentée de trois façons</text><g stroke="#1F4E79" stroke-width="4"><rect x="80" y="100" width="800" height="55" fill="white"/><rect x="80" y="100" width="400" height="55" fill="#79B6E3"/><line x1="480" y1="100" x2="480" y2="155"/><rect x="80" y="185" width="800" height="55" fill="white"/><rect x="80" y="185" width="400" height="55" fill="#79B6E3"/><line x1="280" y1="185" x2="280" y2="240"/><line x1="480" y1="185" x2="480" y2="240"/><line x1="680" y1="185" x2="680" y2="240"/><rect x="80" y="270" width="800" height="55" fill="white"/><rect x="80" y="270" width="400" height="55" fill="#79B6E3"/>${[180,280,380,480,580,680,780].map(x=>`<line x1="${x}" y1="270" x2="${x}" y2="325"/>`).join('')}</g><text x="900" y="140" font-size="30">1/2</text><text x="900" y="225" font-size="30">2/4</text><text x="900" y="310" font-size="30">4/8</text></svg>`);
const numberLine = svgPng('droite-fractions',`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="260"><rect width="100%" height="100%" fill="white"/><text x="40" y="48" font-family="serif" font-size="34">Droite numérique partagée en huitièmes</text><line x1="80" y1="140" x2="920" y2="140" stroke="#1F4E79" stroke-width="5"/>${[0,1,2,3,4,5,6,7,8].map((n,i)=>`<line x1="${80+i*105}" y1="115" x2="${80+i*105}" y2="165" stroke="#1F4E79" stroke-width="4"/><text x="${70+i*105}" y="205" font-size="26">${n===0?'0':n===8?'1':n+'/8'}</text>`).join('')}</svg>`);
const grid100 = svgPng('grille-pourcentage',`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="700"><rect width="100%" height="100%" fill="white"/><text x="50" y="45" font-size="30">35 cases sur 100 = 35 % = 0,35</text>${Array.from({length:100},(_,k)=>{let x=50+(k%10)*55,y=80+Math.floor(k/10)*55;return `<rect x="${x}" y="${y}" width="55" height="55" fill="${k<35?'#79B6E3':'white'}" stroke="#777"/>`}).join('')}</svg>`);

const sessions = [
 {t:'Reconnaître une situation de proportionnalité',goal:'vérifier si deux quantités sont proportionnelles',concept:'Deux quantités sont proportionnelles lorsque l’on passe de l’une à l’autre en multipliant toujours par le même nombre, appelé coefficient de proportionnalité.',example:'Si 1 cahier coûte 2 000 ariary, 2 cahiers coûtent 4 000 ariary et 3 cahiers coûtent 6 000 ariary : le prix est toujours le nombre de cahiers multiplié par 2 000.',app:['Indique les situations proportionnelles : 2 kg coûtent 6 000 ariary et 5 kg coûtent 15 000 ariary ; un enfant mesure 120 cm à 8 ans et 150 cm à 10 ans ; 3 cahiers coûtent 4 500 ariary et 7 cahiers 10 500 ariary ; un carré de côté 2 cm a une aire de 4 cm² et un carré de côté 4 cm une aire de 16 cm².','Trouve le coefficient : 3 → 12 et 5 → 20 ; 4 → 10 et 8 → 20 ; 6 → 42 et 9 → 63 ; 2,5 → 15 et 4 → 24.'],ans:['Les première et troisième situations sont proportionnelles. L’âge et la taille, ainsi que le côté et l’aire d’un carré, ne sont pas proportionnels.','Les coefficients sont 4 ; 2,5 ; 7 ; 6.']},
 {t:'Comprendre la relation y = ax',goal:'identifier et utiliser le coefficient de proportionnalité dans y = ax',concept:'La relation y = ax signifie que la valeur y s’obtient en multipliant x par une constante a. Le nombre a est le coefficient de proportionnalité.',example:'Pour y = 3x, si x = 5, alors y = 3 × 5 = 15.',app:['Calcule y pour x = 2, 4, 7 et 10 dans y = 5x.','Trouve a : y = ax avec (x ; y) égal à (3 ; 12), (5 ; 35), (8 ; 20) et (2,5 ; 15).'],ans:['10 ; 20 ; 35 ; 50.','a = 4 ; a = 7 ; a = 2,5 ; a = 6.']},
 {t:'Compléter un tableau de proportionnalité',goal:'calculer des valeurs manquantes dans un tableau proportionnel',concept:'Dans un tableau de proportionnalité, toutes les valeurs d’une ligne s’obtiennent à partir de l’autre ligne avec un même coefficient. On peut multiplier, diviser ou utiliser le passage à l’unité.',example:'Si 4 mangues coûtent 6 000 ariary, une mangue coûte 1 500 ariary et 10 mangues coûtent 15 000 ariary.',app:['Complète les prix pour 1, 3, 7 et 12 cahiers si un cahier coûte 1 800 ariary.','Complète les distances parcourues en 1 h, 2 h, 3,5 h et 6 h à la vitesse constante de 60 km/h.'],ans:['1 800 ; 5 400 ; 12 600 ; 21 600 ariary.','60 ; 120 ; 210 ; 360 km.']},
 {t:'Représenter une proportionnalité dans un graphique',goal:'placer les couples de valeurs d’une proportionnalité dans un repère',concept:'Les couples (x ; y) d’une situation de proportionnalité se placent sur une droite passant par l’origine du repère. Les axes doivent être nommés et gradués régulièrement.',example:'Pour y = 2x, les points (0 ; 0), (1 ; 2), (2 ; 4) et (3 ; 6) sont alignés avec l’origine.',app:['Donne les points à placer pour y = 3x lorsque x vaut 0, 1, 2 et 4.','Indique si les séries de points représentent une proportionnalité : A(0 ; 0), B(2 ; 6), C(4 ; 12), D(6 ; 18) ; puis E(0 ; 1), F(2 ; 5), G(4 ; 9), H(6 ; 13).'],ans:['(0 ; 0), (1 ; 3), (2 ; 6), (4 ; 12).','La première série représente y = 3x. La deuxième ne représente pas une proportionnalité, car elle ne passe pas par l’origine.']},
 {t:'Résoudre un problème de proportionnalité',goal:'choisir entre coefficient et passage à l’unité',concept:'Pour résoudre un problème de proportionnalité, on vérifie la proportionnalité, on organise les données, puis on utilise le coefficient ou le passage à l’unité.',example:'5 litres d’huile coûtent 45 000 ariary. Un litre coûte 9 000 ariary ; 8 litres coûtent donc 72 000 ariary.',app:['Six mètres de tissu coûtent 54 000 ariary. Calcule le prix de 4 m, 9 m, 12 m et 15 m.','Une recette pour 4 personnes demande 300 g de riz. Calcule la quantité pour 2, 6, 10 et 12 personnes.'],ans:['36 000 ; 81 000 ; 108 000 ; 135 000 ariary.','150 g ; 450 g ; 750 g ; 900 g.']},
 {t:'Identifier une relation entre deux quantités',goal:'décrire comment une quantité dépend d’une autre',concept:'Une relation associe à chaque valeur d’une première quantité une valeur d’une seconde quantité. Elle peut être décrite par des mots, une règle, une table ou un graphique sans être nécessairement proportionnelle.',example:'Le périmètre P d’un carré de côté c suit P = 4c. Pour un taxi avec prise en charge fixe, le prix peut suivre P = 2 000 + 1 500d : cette relation n’est pas proportionnelle.',app:['Écris la relation : le périmètre P d’un triangle équilatéral de côté c ; le prix y de x stylos à 800 ariary ; le nombre y obtenu en ajoutant 5 à x ; l’aire A d’un carré de côté c.','Indique les relations proportionnelles : P = 3c ; y = 800x ; y = x + 5 ; A = c × c.'],ans:['P = 3c ; y = 800x ; y = x + 5 ; A = c × c.','P = 3c et y = 800x sont proportionnelles. Les deux autres ne le sont pas.']},
 {t:'Représenter une relation par manipulation ou dessin',goal:'passer d’un motif concret à une règle numérique',concept:'Un motif permet d’observer une régularité. On compte les éléments à chaque rang, on compare les nombres et on formule une règle reliant le rang à la quantité.',example:'Une suite de figures contient 3, 5, 7, 9 bâtonnets : on ajoute 2 à chaque rang. La règle est y = 2x + 1.',app:['Prolonge de quatre termes : 4, 7, 10, 13 ; puis 2, 6, 10, 14.','Trouve la règle en fonction du rang x : 5, 8, 11, 14 ; 4, 8, 12, 16 ; 3, 7, 11, 15 ; 10, 15, 20, 25.'],ans:['16, 19, 22, 25 ; puis 18, 22, 26, 30.','y = 3x + 2 ; y = 4x ; y = 4x − 1 ; y = 5x + 5.']},
 {t:'Représenter une relation dans un tableau de valeurs',goal:'organiser et prolonger des couples de valeurs',concept:'Une table de valeurs présente dans deux lignes ou colonnes les valeurs associées de x et de y. Chaque couple doit respecter la même règle.',example:'Pour y = 2x + 3 : x = 0, 1, 2, 3 donne y = 3, 5, 7, 9.',app:['Complète pour x = 0, 1, 3 et 5 : y = 4x + 1.','Retrouve la règle : x vaut 0, 1, 2, 3 et y vaut respectivement 2, 5, 8, 11 ; puis y vaut 0, 5, 10, 15.'],ans:['y = 1, 5, 13, 21.','La première règle est y = 3x + 2. La deuxième est y = 5x.']},
 {t:'Représenter une relation dans un graphique',goal:'lire, placer et interpréter les points d’une relation',concept:'Pour représenter une relation, on place chaque couple (x ; y) dans un repère. Le graphique permet de lire une valeur, comparer des variations et repérer si les points sont alignés.',example:'La relation y = x + 2 donne les points (0 ; 2), (1 ; 3), (2 ; 4) et (3 ; 5).',app:['Donne les points pour y = 2x + 1 lorsque x vaut 0, 1, 2 et 4.','Lis la règle correspondant aux points (0 ; 0), (1 ; 4), (2 ; 8), (3 ; 12), puis aux points (0 ; 3), (1 ; 5), (2 ; 7), (3 ; 9).'],ans:['(0 ; 1), (1 ; 3), (2 ; 5), (4 ; 9).','y = 4x ; puis y = 2x + 3.']},
 {t:'Utiliser une lettre pour une quantité inconnue',goal:'traduire une phrase par une expression avec une lettre',concept:'Une lettre peut représenter une quantité inconnue ou variable. On choisit une lettre, on traduit les opérations dans leur ordre et on précise ce qu’elle représente.',example:'Si n représente le prix d’un cahier, le prix de 5 cahiers est 5n et le prix de 5 cahiers plus un stylo à 1 000 ariary est 5n + 1 000.',app:['Traduis avec x : le double d’un nombre ; ce nombre augmenté de 7 ; son triple diminué de 4 ; la moitié de ce nombre.','Calcule pour x = 6 : 3x ; x + 9 ; 5x − 2 ; 24 ÷ x.'],ans:['2x ; x + 7 ; 3x − 4 ; x ÷ 2.','18 ; 15 ; 28 ; 4.']},
 {t:'Comprendre le signe d’égalité',goal:'reconnaître l’équivalence des deux membres d’une égalité',concept:'Le signe égal signifie que les deux membres ont la même valeur. Une égalité reste vraie si l’on effectue la même opération sur ses deux membres.',example:'7 + 5 = 3 × 4 est vraie car chaque membre vaut 12. À partir de x + 3 = 10, enlever 3 aux deux membres donne x = 7.',app:['Indique si l’égalité est vraie : 8 + 4 = 3 × 4 ; 18 ÷ 3 = 9 − 3 ; 5 × 7 = 40 − 5 ; 24 − 9 = 3 × 6.','Complète : 7 + … = 20 ; 4 × … = 36 ; … − 8 = 15 ; … ÷ 5 = 6.'],ans:['Vraie ; vraie ; vraie ; fausse, car 15 ≠ 18.','13 ; 9 ; 23 ; 30.']},
 {t:'Résoudre une équation par déduction',goal:'trouver une inconnue à l’aide des opérations inverses',concept:'Résoudre une équation consiste à trouver la valeur qui rend l’égalité vraie. On isole l’inconnue en utilisant l’opération inverse et en conservant l’équilibre.',example:'3x + 5 = 26 ; on enlève 5 : 3x = 21 ; on divise par 3 : x = 7. Vérification : 3 × 7 + 5 = 26.',app:['Résous : x + 8 = 21 ; x − 6 = 15 ; 4x = 36 ; x ÷ 5 = 7.','Résous : 2x + 3 = 17 ; 5x − 4 = 31 ; x ÷ 3 + 2 = 6 ; 4(x + 1) = 28.'],ans:['x = 13 ; x = 21 ; x = 9 ; x = 35.','x = 7 ; x = 7 ; x = 12 ; x = 6.']},
 {t:'Résoudre une équation par essais systématiques',goal:'organiser des essais et vérifier une solution',concept:'Les essais systématiques consistent à tester des valeurs dans un ordre organisé, calculer chaque résultat et comparer avec le membre attendu. La solution doit toujours être vérifiée.',example:'Pour 4x + 1 = 29, on teste x = 5, 6, 7 : les résultats sont 21, 25, 29. La solution est x = 7.',app:['Résous par essais : 3x + 2 = 20 ; 5x − 1 = 34 ; 2x + 7 = 25 ; 4x − 3 = 29.','Un nombre multiplié par 6 puis augmenté de 5 donne 47. Un nombre doublé puis diminué de 3 donne 19. Un nombre triplé augmenté de 4 donne 40. Un nombre multiplié par 5 diminué de 2 donne 43. Trouve chaque nombre.'],ans:['x = 6 ; x = 7 ; x = 9 ; x = 8.','7 ; 11 ; 12 ; 9.']},
];

// Independent assertions for all simple numerical answers used above.
console.assert(11/4===2.75 && 13/5===2.6 && 17/6>2.83 && 17/6<2.84);
console.assert((2/3)===(8/12) && 5/6>3/4);
console.assert(3/5===0.6 && 7/20===0.35 && 9/25===0.36 && 7/8===0.875);
console.assert(12===12 && 24===24 && 36===36);

function meta(s,n){ return new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[
 new TableRow({children:[cell(`Discipline : Mathématiques\nComposante : Algèbre\nTitre : ${s.t}`,{width:68,bold:true}),cell(`Classe : T6\nSéance : ${n} / 15`,{width:32,bold:true})]}),
 new TableRow({children:[cell(`Objectif : À la fin de la séance, l’apprenant est capable de ${s.goal}.`,{span:2})]})
]}); }
function prep(s,n){
 const heads=[new TableRow({tableHeader:true,children:[cell('Étapes',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:13,align:AlignmentType.CENTER}),cell('Déroulement de la leçon',{span:2,fill:C.blue,color:C.white,bold:true,width:45,align:AlignmentType.CENTER}),cell('Technique et stratégie',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:15}),cell('Support et matériel',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:15}),cell('Observation',{rowSpan:2,fill:C.blue,color:C.white,bold:true,width:12})]}),new TableRow({tableHeader:true,children:[cell('Enseignant',{fill:C.pale,bold:true}),cell('Apprenants',{fill:C.pale,bold:true})]})];
 const rows=[
  ['I. Révision','Que retenez-vous de la notion précédente ? Donnez un exemple numérique.','Répondent oralement et justifient leur exemple.','Questions-réponses','Tableau, ardoises','Acquis à consolider'],
  ['II. NOUVELLE LEÇON','Annonce : « Aujourd’hui, nous allons apprendre à '+s.goal+'. »','Écoutent.','Présentation guidée','Tableau',''],
  ['1. Mise en situation',`Rova rencontre la situation suivante : ${s.example} Que remarquez-vous ?`,'Écoutent, observent et proposent des réponses.','Situation-problème','Illustration, tableau','Participation'],
  ['2. Présentation',`Présente le titre « ${s.t} » et précise l’objectif.`,'Écoutent.','Explication brève','Tableau',''],
  ['3. Observation',s.example,'Observent l’exemple résolu.','Observation dirigée',s.img?'Figure imprimée':'Tableau et ardoises','Compréhension'],
  ['4. Analyse',`Guide l’analyse : ${s.concept} Demande aux apprenants d’expliquer chaque étape.`,'Expliquent la démarche et vérifient le résultat.','Recherche en binômes','Ardoises, règle si nécessaire','Raisonnement'],
  ['5. Synthèse',s.concept,'Écoutent et reformulent la règle.','Synthèse guidée','Cahier, tableau','Trace écrite'],
  ['6. Application',s.app[0]+' '+s.app[1],s.ans[0]+' '+s.ans[1],'Travail individuel puis correction collective','Cahier, ardoises','Remédiation'],
  ['III. Évaluation',`Résous sans modèle : ${s.app[0]} Puis explique une réponse de ton choix.`,s.ans[0]+' Une justification correcte utilise la règle de la leçon.','Travail individuel','Feuille, cahier','Maîtrise de l’objectif']
 ].map((r,i)=>new TableRow({children:r.map((x,j)=>cell(x,{fill:i===1?C.paleGreen:undefined,bold:j===0,size:16}))}));
 return table([...heads,...rows]);
}
function lesson(s,n){
 const a=[]; a.push(page(),title(`LEÇON — ${s.t}`,1,`u3_l${n}`));
 a.push(title('1. Notion essentielle',2),labelPara('Définition. ',s.concept));
 a.push(title('2. Méthode pas à pas',2));
 a.push(bullet('Lire attentivement les données et identifier les nombres ou représentations utilisés.'));
 a.push(bullet('Choisir la règle adaptée à la situation.'));
 a.push(bullet('Effectuer chaque étape dans l’ordre et écrire les transformations intermédiaires.'));
 a.push(bullet('Vérifier que le résultat répond à la question et qu’il est cohérent.'));
 a.push(title('3. Exemple expliqué',2),labelPara('Exemple. ',s.example));
 if(s.img) a.push(new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({data:s.img,transformation:{width:500,height:s.img===grid100?500:180},type:'png'})]}));
 a.push(title('4. Erreurs à éviter',2));
 a.push(bullet('Modifier un nombre sans appliquer la même transformation à toute l’écriture.'));
 a.push(bullet('Oublier la valeur de position d’un chiffre ou le sens d’un symbole de comparaison.'));
 a.push(title('EXERCICES — Total : 20 points',1));
 a.push(p('Exercice 1 — 8 points. '+s.app[0]));
 a.push(p('Exercice 2 — 8 points. '+s.app[1]));
 a.push(p('Exercice 3 — 4 points. Rédige une phrase qui explique la méthode utilisée dans un item de ton choix.'));
 a.push(title('CORRIGÉ DÉTAILLÉ',2));
 a.push(correction('Exercice 1. ',s.ans[0]+' Chaque réponse correcte vaut 2 points.'));
 a.push(correction('Exercice 2. ',s.ans[1]+' Chaque réponse correcte vaut 2 points.'));
 a.push(correction('Exercice 3. ','La phrase doit citer la règle appropriée, montrer au moins une étape et conclure par le résultat. Une démarche cohérente et correctement formulée vaut 4 points.'));
 return a;
}
function revision(){return [page(),title('SÉANCE 14 / 15 — RÉVISION DE L’UNITÉ III',1,'u3_l14'),title('Tableau de synthèse',2),table([
 new TableRow({children:[cell('Notion',{bold:true,fill:C.blue,color:C.white}),cell('Idée essentielle',{bold:true,fill:C.blue,color:C.white}),cell('Compétence',{bold:true,fill:C.blue,color:C.white})]}),
 ...[['Proportionnalité','y = ax et coefficient constant','Compléter table et graphique'],['Relations','Associer x à y selon une règle','Passer entre règle, table et graphique'],['Inconnue','Une lettre représente une quantité','Traduire une phrase'],['Égalité','Les deux membres ont même valeur','Conserver l’équilibre'],['Équation','Trouver puis vérifier l’inconnue','Déduire ou essayer systématiquement']].map(r=>new TableRow({children:r.map(x=>cell(x))}))
 ]),title('Questions de révision',2),p('1. Calcule y pour y = 4x et x = 7. 2. La relation y = 3x + 2 est-elle proportionnelle ? 3. Complète 5x = 45. 4. Résous 3x + 4 = 25. 5. Donne quatre points de y = 2x.'),title('Réponses attendues',2),correction('1. ','y = 28.'),correction('2. ','Non, car elle ne passe pas par l’origine.'),correction('3. ','x = 9.'),correction('4. ','x = 7.'),correction('5. ','Par exemple : (0 ; 0), (1 ; 2), (2 ; 4), (3 ; 6).')];}
function exam(){return [page(),title('SÉANCE 15 / 15 — SUJET D’EXAMEN T6 — UNITÉ III',1,'u3_l15'),p('Barème : 20 points. Justifie chaque démarche.'),p('Exercice 1 — 4 points. Pour y = 6x, calcule y lorsque x vaut 0, 2, 5 et 8.'),p('Exercice 2 — 4 points. Un kilogramme de haricots coûte 4 800 ariary. Calcule le prix de 3 kg, 5 kg, 7,5 kg et 12 kg.'),p('Exercice 3 — 4 points. Pour y = 3x + 1 : complète la table pour x = 0, 1, 3 et 6, puis indique si la relation est proportionnelle.'),p('Exercice 4 — 4 points. Résous : a) x + 15 = 38 ; b) 5x = 45 ; c) 3x + 2 = 26 ; d) 4(x − 1) = 28.'),p('Exercice 5 — 4 points. Une excursion coûte 5 000 ariary de frais fixes et 2 500 ariary par participant. Écris la relation entre le nombre x de participants et le coût y. Calcule le coût pour 18 participants et explique pourquoi cette relation n’est pas proportionnelle.'),title('CORRIGÉ ET BARÈME',2),correction('Exercice 1. ','0 ; 12 ; 30 ; 48. Un point par valeur.'),correction('Exercice 2. ','14 400 ; 24 000 ; 36 000 ; 57 600 ariary. Un point par réponse.'),correction('Exercice 3. ','1 ; 4 ; 10 ; 19. La relation n’est pas proportionnelle, car y vaut 1 lorsque x vaut 0. Trois points pour la table et un point pour la justification.'),correction('Exercice 4. ','x = 23 ; x = 9 ; x = 8 ; x = 8. Un point par solution vérifiée.'),correction('Exercice 5. ','y = 2 500x + 5 000. Pour 18 participants : y = 50 000 ariary. La relation n’est pas proportionnelle à cause des frais fixes : pour x = 0, y = 5 000. Deux points pour la relation, un pour le calcul et un pour l’explication.')];}

const children=[];
children.push(title('MANUEL DE MATHÉMATIQUES — CLASSE DE T6',1,'cover'),new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:250,after:200},children:[tr('Collection J-Learn',{bold:true,size:34,color:C.blue})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[tr('Programme officiel malgache — Version 1',{size:26})]}),new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:600},children:[tr('Unité III — Algèbre',{bold:true,size:30,color:C.green})]}));
children.push(page(),title('AVANT-PROPOS',1,'avant'),p('Ce manuel accompagne l’enseignant dans la mise en œuvre du programme officiel de Mathématiques T6. Il met l’apprenant au centre des activités : observation, manipulation, raisonnement, formulation d’une méthode, application et résolution de problèmes.'),p('Chaque séance associe une fiche de préparation directement exploitable, une leçon structurée, des exemples contextualisés, des exercices avec barème et un corrigé détaillé. Les situations mobilisent des repères familiers de Madagascar tout en développant la rigueur, la persévérance et l’autonomie.'));
children.push(title('MODE D’EMPLOI',1,'mode'),p('La fiche suit trois grandes étapes : I. Révision ; II. Nouvelle leçon, comprenant mise en situation, présentation, observation, analyse, synthèse et application ; III. Évaluation. À la demande de l’utilisateur, aucune durée chiffrée n’est affichée.'),p('Code couleur : titre de leçon en rouge ; sous-titres en vert ; mots-clés en bleu et en gras ; mots-clés des corrigés en bordeaux ; texte courant en noir.'));
children.push(title('SOMMAIRE INTERACTIF',1,'toc'));
children.push(new Paragraph({children:[new InternalHyperlink({anchor:'u3',children:[tr('Unité III — Algèbre',{bold:true,color:C.blue})]})]}));
sessions.forEach((s,i)=>children.push(new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:`u3_l${i+1}`,children:[tr(`Séance ${i+1} — ${s.t}`,{color:C.blue})]})]})));
children.push(new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:'u3_l14',children:[tr('Séance 14 — Révision de l’unité I',{color:C.blue})]})]}),new Paragraph({indent:{left:360},children:[new InternalHyperlink({anchor:'u3_l15',children:[tr('Séance 15 — Sujet d’examen',{color:C.blue})]})]}));
children.push(page(),title('UNITÉ III — ALGÈBRE',1,'u3'),p('Résultat d’apprentissage général : exploiter les relations mathématiques pour analyser des situations diverses, faire des prédictions et prendre des décisions éclairées.'),p('Valeurs à véhiculer : estime de soi et sens de la responsabilité.'),title('Tableau de bord',2),table([new TableRow({children:[cell('Séances',{bold:true,fill:C.blue,color:C.white}),cell('Apprentissages',{bold:true,fill:C.blue,color:C.white}),cell('Révision',{bold:true,fill:C.blue,color:C.white}),cell('Examen',{bold:true,fill:C.blue,color:C.white})]}),new TableRow({children:[cell('15'),cell('13'),cell('1'),cell('1')]})]));
sessions.forEach((s,i)=>{children.push(page(),title(`SÉANCE ${i+1} / 15 — ${s.t.toUpperCase()}`,1,`u3_s${i+1}`),title('FICHE DE PRÉPARATION',2),meta(s,i+1),prep(s,i+1),...lesson(s,i+1));});
children.push(...revision(),...exam());

const doc=new Document({styles:{default:{document:{run:{font:'Times New Roman',size:22},paragraph:{spacing:{line:276}}}}},sections:[{properties:{page:{margin:{top:900,right:720,bottom:900,left:720}}},headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[tr('J-Learn — Mathématiques T6 — Unité III',{size:18,color:'666666'})]})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[tr('Page ',{size:18}),new TextRun({children:[PageNumber.CURRENT],font:'Times New Roman',size:18})]})]})},children}]});
Packer.toBuffer(doc).then(buf=>{fs.writeFileSync(OUT,buf);console.log(`${OUT}: ${buf.length} octets`);});
