// Sary faha-2 isaky ny seho (apetraka ao amin'ny LESONA, aorian'ny votoaty)
module.exports = {
  1:  { image: "images/img2_s01.png", legende: "Ny dingana enina amin'ny tetikasa fanadihadiana am-bava" },
  2:  { image: "images/img2_s02.png", legende: "Ny fanadihadiana am-bava mahomby : toe-tsaina, fitaovana, fitandremana" },
  4:  { image: "images/img2_s04.png", legende: "Frizy : ireo vanim-potoana lehiben'ny Tantara" },
  5:  { image: "images/img2_s05.png", legende: "Ny dingana lehibe tamin'ny fivoaran'ny olombelona" },
  7:  { image: "images/img2_s07.png", legende: "Mezopotamia : sivilizasiona voalohany sy ny soratra" },
  8:  { image: "images/img2_s08.png", legende: "Frizy : ireo empira telo nifandimby tany Ejipta" },
  9:  { image: "images/img2_s09.png", legende: "Ny fahefan'ny farao : ara-politika, ara-pivavahana, ara-miaramila" },
  10: { image: "images/img2_s10.png", legende: "Fampitahana : Sparta sy Atena" },
  11: { image: "images/img2_s11.png", legende: "Frizy : ireo fitondrana telo nifandimby tany Roma" },
  12: { image: "images/img2_s12.png", legende: "Ny lova antika hita eto Madagasikara" },
  14: { image: "images/img2_s14.png", legende: "Frizy : ny Andro Antenatenany (476-1492)" },
  15: { image: "images/img2_s15.png", legende: "Ny piramidan'ny rafitra feodaly" },
  16: { image: "images/img2_s16.png", legende: "Ny fandaminan'ny Eglizy tamin'ny Andro Antenatenany" },
  17: { image: "images/img2_s17.png", legende: "Frizy : ny fahaterahan'ny Silamo (taonjato VII)" },
  18: { image: "images/img2_s18.png", legende: "Frizy : ny fandresen'ny Silamo (630-750)" },
  19: { image: "images/img2_s19.png", legende: "Fampitahana : sivilizasiona tandrefana sy silamo" },
  21: { image: "images/img2_s21.png", legende: "Frizy : ireo onjam-pifindra-monina nankany Madagasikara" },
  22: { image: "images/img2_s22.png", legende: "Ny arkeolojia sy ny toeram-ponenana voalohany" },
  23: { image: "images/img2_s23.png", legende: "Vahoaka iray ny Malagasy : fitoviana sy fahasamihafana" },
  25: { image: "images/img2_s25.png", legende: "Ny lova aostronezianina sy afrikanina" },
  26: { image: "images/img2_s26.png", legende: "Ny lova arabo-silamo" },
  27: { image: "images/img2_s27.png", legende: "Ny lova tandrefana" },
  29: { image: "images/img2_s29.png", legende: "Frizy : ny fivoaran'ny fandaminana ara-politika teto Madagasikara" },
  30: { image: "images/img2_s30.png", legende: "Vondrom-poko 18, vahoaka iray" },
};
