// seances-lecture.js — une séance « Lecture + Expression écrite » par thème.
// Clés = numéro de thème. La numérotation continue est assignée par assemble.js.
// Chaque séance suit le schéma de l'assembleur : n(auto), titre, titreFiche, sd,
// objectif, support, lecon, deroulement, exercices, corrige.

const lec = (num, titre, titreFiche, objectif, support,
  lecon, rev, mes, pres, obs, ana, syn, app, eva, ex, cor) => ({
  n: 0, titre, titreFiche, sd: "Lecture", objectif, support, lecon,
  revision: rev, miseEnSituation: mes, presentation: pres, observation: obs,
  analyse: ana, synthese: syn, application: app, evaluation: eva,
  exercices: ex, corrige: cor,
});
const st = (ens, app, tech) => ({ ens, app, technique: tech || { sous: "", points: [] } });
const T = (sous, points) => ({ sous, points });

module.exports = {
  1: [lec(1, "Lire et écrire un menu", "Lire un menu et rédiger le menu d'un repas.",
    "Lire un menu simple et rédiger le menu d'un repas malgache",
    "Menu écrit au tableau (riz, ravitoto, fruits), cahiers.",
    { titre: "Le menu d'un repas", blocs: [
      { st: "A. Lire un menu", txt: "un menu donne la liste des plats : entrée, plat, boisson, fruit." },
      { st: "B. Écrire un menu", txt: "on écrit un plat par ligne, avec une majuscule au début." },
    ], aretenir: "Un menu est une liste de plats ; on l'écrit ligne par ligne avec des majuscules." },
    st(["« Que mangeons-nous à midi ? » - Révision du lexique des aliments.", "Le professeur fait rappeler trois aliments."],
       ["Les élèves citent trois aliments."], T("I. Révision", ["Rappel du lexique des aliments."])),
    st(["Le professeur écrit un menu au tableau et demande : « Que va manger cette famille ? »"],
       ["Les élèves lisent le menu et répondent."], ),
    st(["Le professeur annonce que l'on va lire un menu puis en écrire un."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire le menu à voix haute.", "Menu : riz — ravitoto — banane — eau."],
       ["Les élèves lisent et relèvent les plats."]),
    st(["Le professeur fait dégager la structure du menu."],
       ["Les élèves relèvent : un plat par ligne, des majuscules."],
       T("I. La structure du menu", ["Un menu est une liste.", "Un plat par ligne.", "Une majuscule au début de chaque ligne."])),
    st(["Le professeur fait récapituler comment écrire un menu."],
       ["Un élève énonce les règles."],
       T("II. Écrire un menu", ["On choisit les plats.", "On écrit un plat par ligne.", "On met une majuscule et on termine par un point."])),
    st(["Le professeur fait écrire un menu."],
       ["Les élèves rédigent un menu de trois plats."],
       T("III. Application", ["Lis le menu du tableau.", "Écris le menu de ton repas de midi.", "Souligne les majuscules."])),
    st(["Le professeur vérifie la lecture et l'écriture."],
       ["Chaque élève lit et écrit un menu correct."],
       T("IV. Évaluation", ["Lis un menu de trois plats.", "Écris le menu d'un repas malgache."])),
    [ { t: "Exercice 1 (10 pts)", q: "Lis le menu : riz — ravitoto — banane. Quels sont les trois plats ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Écris le menu de ton repas de midi en trois lignes, avec des majuscules.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "le riz, le ravitoto, la banane", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : Riz. Romazava. Banane.", r: true }, "."] ])],

  2: [lec(2, "Lire un arbre généalogique et présenter sa famille", "Lire un arbre généalogique et rédiger la présentation de sa famille.",
    "Lire un arbre généalogique et présenter sa famille par écrit",
    "Arbre généalogique dessiné au tableau, cahiers.",
    { titre: "L'arbre généalogique", blocs: [
      { st: "A. Lire l'arbre", txt: "en haut les grands-parents, au milieu les parents, en bas les enfants." },
      { st: "B. Présenter sa famille", txt: "on nomme chaque personne et son lien : mon grand-père, ma mère, mon frère." },
    ], aretenir: "L'arbre généalogique montre les générations ; on présente chaque membre avec son lien de parenté." },
    st(["« Qui vit avec toi à la maison ? » - Révision du lexique de la famille.", "Le professeur fait rappeler trois liens de parenté."],
       ["Les élèves citent trois liens de parenté."], T("I. Révision", ["Rappel : grand-père, mère, frère…"])),
    st(["Le professeur montre l'arbre et demande : « Qui est en haut ? »"],
       ["Les élèves répondent : les grands-parents."]),
    st(["Le professeur annonce que l'on va lire un arbre généalogique et présenter sa famille."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire l'arbre : noms et liens."],
       ["Les élèves lisent chaque personne et son lien."]),
    st(["Le professeur fait dégager l'ordre des générations."],
       ["Les élèves classent : grands-parents, parents, enfants."],
       T("I. Les générations", ["En haut : les grands-parents.", "Au milieu : les parents.", "En bas : les enfants."])),
    st(["Le professeur fait récapituler la présentation écrite."],
       ["Un élève présente sa famille à voix haute."],
       T("II. Présenter sa famille", ["Je m'appelle …", "Mon grand-père s'appelle …", "Ma mère s'appelle …", "J'ai … frères et sœurs."])),
    st(["Le professeur fait écrire la présentation."],
       ["Les élèves rédigent trois phrases."],
       T("III. Application", ["Lis l'arbre du tableau.", "Écris trois phrases pour présenter ta famille.", "Utilise mon, ma, mes."])),
    st(["Le professeur vérifie la lecture et l'écriture."],
       ["Chaque élève lit et écrit correctement."],
       T("IV. Évaluation", ["Nomme deux personnes de l'arbre.", "Présente ta famille en trois phrases."])),
    [ { t: "Exercice 1 (10 pts)", q: "Sur l'arbre, qui est en haut et qui est en bas ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Présente ta famille en trois phrases avec mon, ma, mes.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "en haut les grands-parents, en bas les enfants", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : Mon grand-père s'appelle Koto. Ma mère s'appelle Voahangy. J'ai deux frères.", r: true }, "."] ])],

  3: [lec(3, "Lire un emploi du temps et raconter sa journée", "Lire un emploi du temps et rédiger le récit de sa journée.",
    "Lire un emploi du temps et rédiger le récit de sa journée dans l'ordre",
    "Emploi du temps de la classe au tableau, cahiers.",
    { titre: "L'emploi du temps", blocs: [
      { st: "A. Lire l'emploi du temps", txt: "des colonnes pour les jours, des lignes pour les heures." },
      { st: "B. Raconter sa journée", txt: "on utilise d'abord, ensuite, après, enfin et les moments le matin, le soir." },
    ], aretenir: "L'emploi du temps se lit en croisant le jour et l'heure ; le récit de la journée suit l'ordre chronologique." },
    st(["« Que fais-tu le matin ? » - Révision du lexique du temps.", "Le professeur fait rappeler d'abord, ensuite, enfin."],
       ["Les élèves rappellent les connecteurs."], T("I. Révision", ["Rappel : d'abord, ensuite, après, enfin."])),
    st(["Le professeur montre l'emploi du temps et demande : « Que faisons-nous le lundi à huit heures ? »"],
       ["Les élèves lisent la case et répondent."]),
    st(["Le professeur annonce que l'on va lire un emploi du temps et raconter sa journée."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire quelques cases de l'emploi du temps."],
       ["Les élèves lisent les cases à voix haute."]),
    st(["Le professeur fait dégager comment lire le tableau."],
       ["Les élèves croisent jour et heure."],
       T("I. Lire le tableau", ["Les colonnes = les jours.", "Les lignes = les heures.", "La case = l'activité."])),
    st(["Le professeur fait récapituler le récit chronologique."],
       ["Un élève raconte sa journée."],
       T("II. Raconter sa journée", ["Le matin, je me lève.", "Ensuite, je vais à l'école.", "Le soir, je fais mes devoirs.", "Enfin, je me couche."])),
    st(["Le professeur fait écrire le récit."],
       ["Les élèves rédigent trois phrases dans l'ordre."],
       T("III. Application", ["Lis l'emploi du temps du lundi.", "Raconte ta journée en trois phrases.", "Utilise d'abord, ensuite, enfin."])),
    st(["Le professeur vérifie la lecture et le récit."],
       ["Chaque élève lit et raconte correctement."],
       T("IV. Évaluation", ["Lis deux cases de l'emploi du temps.", "Raconte ta journée en trois phrases."])),
    [ { t: "Exercice 1 (10 pts)", q: "Lis l'emploi du temps : que faisons-nous le lundi à huit heures ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Raconte ta journée en trois phrases dans l'ordre.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "réponse selon le tableau, ex. : nous faisons la lecture", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : D'abord, je me lève. Ensuite, je vais à l'école. Enfin, je fais mes devoirs.", r: true }, "."] ])],

  4: [lec(4, "Lire et écrire la description d'une maison", "Lire une description et rédiger la description de sa maison.",
    "Lire une description de maison et rédiger la sienne",
    "Court texte descriptif au tableau, cahiers.",
    { titre: "Décrire une maison", blocs: [
      { st: "A. Lire une description", txt: "le texte nomme l'ensemble, les pièces, puis les objets." },
      { st: "B. Écrire une description", txt: "on commence par le nombre de pièces, puis on dit ce qu'il y a dedans." },
    ], aretenir: "Une description part de l'ensemble pour aller vers les détails, avec il y a." },
    st(["« Combien de pièces a ta maison ? » - Révision du lexique de la maison.", "Le professeur fait rappeler trois pièces."],
       ["Les élèves citent trois pièces."], T("I. Révision", ["Rappel : chambre, cuisine, salon…"])),
    st(["Le professeur lit un court texte : « Ma maison a deux pièces. Il y a une chambre et une cuisine. »"],
       ["Les élèves écoutent puis relèvent les pièces."]),
    st(["Le professeur annonce que l'on va lire une description et écrire la sienne."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire le texte à voix haute."],
       ["Les élèves lisent et relèvent les pièces et les objets."]),
    st(["Le professeur fait dégager l'ordre de la description."],
       ["Les élèves relèvent : ensemble, pièces, objets."],
       T("I. L'ordre de la description", ["Le nombre de pièces.", "Le nom des pièces.", "Ce qu'il y a dans chaque pièce."])),
    st(["Le professeur fait récapituler la méthode d'écriture."],
       ["Un élève décrit sa maison à voix haute."],
       T("II. Écrire sa description", ["Ma maison a … pièces.", "Il y a …", "Dans la cuisine, il y a …"])),
    st(["Le professeur fait écrire la description."],
       ["Les élèves rédigent trois phrases."],
       T("III. Application", ["Lis le texte du tableau.", "Décris ta maison en trois phrases.", "Utilise il y a."])),
    st(["Le professeur vérifie la lecture et l'écriture."],
       ["Chaque élève lit et décrit correctement."],
       T("IV. Évaluation", ["Relève deux pièces du texte.", "Décris ta maison en trois phrases."])),
    [ { t: "Exercice 1 (10 pts)", q: "Dans le texte, combien de pièces a la maison et quelles sont-elles ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Décris ta maison en trois phrases avec il y a.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "deux pièces : une chambre et une cuisine", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : Ma maison a trois pièces. Il y a une chambre et une cuisine. Dans la cuisine, il y a une marmite.", r: true }, "."] ])],

  5: [lec(5, "Lire un plan de village et le décrire", "Lire un plan et rédiger la description de son village.",
    "Lire un plan de village et décrire son village par écrit",
    "Plan simplifié du village au tableau, cahiers.",
    { titre: "Le plan du village", blocs: [
      { st: "A. Lire le plan", txt: "le plan montre les lieux et leur position : à côté de, en face de, derrière." },
      { st: "B. Décrire son village", txt: "on nomme les lieux et on les situe les uns par rapport aux autres." },
    ], aretenir: "Un plan se lit avec les mots de situation ; la description situe chaque lieu." },
    st(["« Quels lieux y a-t-il dans ton village ? » - Révision du lexique du village.", "Le professeur fait rappeler trois lieux."],
       ["Les élèves citent trois lieux."], T("I. Révision", ["Rappel : école, marché, église…"])),
    st(["Le professeur montre le plan et demande : « Où est le marché par rapport à l'école ? »"],
       ["Les élèves répondent avec à côté de, en face de…."]),
    st(["Le professeur annonce que l'on va lire un plan et décrire son village."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire le plan : chaque lieu et sa position."],
       ["Les élèves lisent les lieux et leurs positions."]),
    st(["Le professeur fait dégager les mots de situation."],
       ["Les élèves relèvent : à côté de, en face de, derrière."],
       T("I. Les mots de situation", ["à côté de — en face de — devant — derrière — au bord de."])),
    st(["Le professeur fait récapituler la description du village."],
       ["Un élève décrit le village du plan."],
       T("II. Décrire son village", ["Dans mon village, il y a …", "L'école est à côté du marché.", "Le puits est derrière l'église."])),
    st(["Le professeur fait écrire la description."],
       ["Les élèves rédigent trois phrases."],
       T("III. Application", ["Lis le plan du tableau.", "Décris ton village en trois phrases.", "Situe deux lieux."])),
    st(["Le professeur vérifie la lecture et l'écriture."],
       ["Chaque élève lit et décrit correctement."],
       T("IV. Évaluation", ["Situe deux lieux du plan.", "Décris ton village en trois phrases."])),
    [ { t: "Exercice 1 (10 pts)", q: "Sur le plan, où est le marché par rapport à l'école ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Décris ton village en trois phrases en situant deux lieux.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "réponse selon le plan, ex. : le marché est à côté de l'école", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : Dans mon village, il y a une école et un marché. L'école est à côté du marché. Le puits est derrière l'église.", r: true }, "."] ])],

  6: [lec(6, "Lire un récit de la ferme et en écrire un", "Lire un court récit et rédiger un récit de la ferme.",
    "Lire un court récit de la ferme et en rédiger un dans l'ordre",
    "Court récit au tableau, cahiers.",
    { titre: "Le récit de la ferme", blocs: [
      { st: "A. Lire le récit", txt: "le récit raconte les travaux dans l'ordre, avec d'abord, ensuite, enfin." },
      { st: "B. Écrire un récit", txt: "on raconte ce que l'on fait à la ferme, étape par étape." },
    ], aretenir: "Un récit se lit et s'écrit dans l'ordre, avec des connecteurs de temps." },
    st(["« Que fait-on à la ferme le matin ? » - Révision du lexique de la ferme.", "Le professeur fait rappeler trois travaux."],
       ["Les élèves citent trois travaux."], T("I. Révision", ["Rappel : nourrir, nettoyer, ramasser…"])),
    st(["Le professeur lit : « D'abord, Rabe nourrit les poules. Ensuite, il nettoie l'étable. Enfin, il ramasse les œufs. »"],
       ["Les élèves écoutent puis relèvent les travaux."]),
    st(["Le professeur annonce que l'on va lire un récit et en écrire un."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire le récit à voix haute."],
       ["Les élèves lisent et relèvent les travaux et les connecteurs."]),
    st(["Le professeur fait dégager l'ordre du récit."],
       ["Les élèves relèvent d'abord, ensuite, enfin."],
       T("I. L'ordre du récit", ["d'abord : nourrir les poules", "ensuite : nettoyer l'étable", "enfin : ramasser les œufs"])),
    st(["Le professeur fait récapituler l'écriture du récit."],
       ["Un élève raconte un récit à voix haute."],
       T("II. Écrire un récit", ["On choisit trois travaux.", "On les met dans l'ordre.", "On utilise d'abord, ensuite, enfin."])),
    st(["Le professeur fait écrire le récit."],
       ["Les élèves rédigent trois phrases."],
       T("III. Application", ["Lis le récit du tableau.", "Écris un récit de trois travaux de la ferme.", "Utilise d'abord, ensuite, enfin."])),
    st(["Le professeur vérifie la lecture et l'écriture."],
       ["Chaque élève lit et écrit correctement."],
       T("IV. Évaluation", ["Relève les trois travaux du récit.", "Écris un récit de trois travaux."])),
    [ { t: "Exercice 1 (10 pts)", q: "Relève les trois travaux du récit, dans l'ordre.", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Écris un récit de trois travaux de la ferme avec d'abord, ensuite, enfin.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "nourrir les poules, nettoyer l'étable, ramasser les œufs", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : D'abord, je donne la provende. Ensuite, je nettoie l'étable. Enfin, je ramasse les œufs.", r: true }, "."] ])],

  7: [lec(7, "Lire une fiche de santé et donner un conseil", "Lire une fiche de santé et rédiger un conseil.",
    "Lire une fiche de santé et rédiger un conseil simple",
    "Fiche de santé simplifiée au tableau, cahiers.",
    { titre: "La fiche de santé", blocs: [
      { st: "A. Lire la fiche", txt: "la fiche donne le mal (fièvre, toux) et le soin (consulter, se reposer)." },
      { st: "B. Donner un conseil", txt: "on utilise il faut + infinitif : il faut consulter l'infirmier." },
    ], aretenir: "Une fiche de santé associe un mal et un soin ; le conseil s'exprime avec il faut." },
    st(["« Que fais-tu quand tu as de la fièvre ? » - Révision du lexique des maladies.", "Le professeur fait rappeler deux maladies."],
       ["Les élèves citent deux maladies."], T("I. Révision", ["Rappel : fièvre, toux, paludisme…"])),
    st(["Le professeur lit la fiche : « Mal : fièvre. Soin : consulter et se reposer. »"],
       ["Les élèves écoutent puis relèvent le mal et le soin."]),
    st(["Le professeur annonce que l'on va lire une fiche de santé et donner un conseil."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire la fiche à voix haute."],
       ["Les élèves lisent le mal et le soin."]),
    st(["Le professeur fait dégager le lien mal/soin."],
       ["Les élèves associent chaque mal à un soin."],
       T("I. Mal et soin", ["fièvre → consulter, se reposer", "toux → boire de l'eau tiède", "paludisme → aller au dispensaire"])),
    st(["Le professeur fait récapituler la forme du conseil."],
       ["Un élève donne un conseil avec il faut."],
       T("II. Donner un conseil", ["Il faut consulter l'infirmier.", "Il faut se reposer.", "Il faut boire de l'eau propre."])),
    st(["Le professeur fait écrire un conseil."],
       ["Les élèves rédigent deux conseils."],
       T("III. Application", ["Lis la fiche du tableau.", "Donne deux conseils avec il faut.", "Écris-les avec une majuscule."])),
    st(["Le professeur vérifie la lecture et le conseil."],
       ["Chaque élève lit et conseille correctement."],
       T("IV. Évaluation", ["Relève le soin de la fièvre.", "Donne deux conseils avec il faut."])),
    [ { t: "Exercice 1 (10 pts)", q: "Sur la fiche, quel est le soin pour la fièvre ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Donne deux conseils avec il faut pour un enfant malade.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "consulter et se reposer", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : Il faut consulter l'infirmier. Il faut se reposer.", r: true }, "."] ])],

  8: [lec(8, "Lire une liste de prix et écrire un dialogue", "Lire une liste de prix et rédiger un dialogue de marché.",
    "Lire une liste de prix et rédiger un dialogue de marché",
    "Liste de prix au tableau, cahiers.",
    { titre: "La liste de prix", blocs: [
      { st: "A. Lire la liste", txt: "la liste associe une marchandise et un prix : tomate, deux mille ariary le kilo." },
      { st: "B. Écrire un dialogue", txt: "le client demande le prix, le marchand répond, on marchande, on achète." },
    ], aretenir: "Une liste de prix associe marchandise et prix ; le dialogue de marché suit quatre étapes." },
    st(["« Combien coûte un kilo de riz ? » - Révision du lexique du marché.", "Le professeur fait rappeler deux marchandises."],
       ["Les élèves citent deux marchandises."], T("I. Révision", ["Rappel : tomate, riz, huile…"])),
    st(["Le professeur lit la liste : « Tomate : deux mille ariary le kilo. Riz : mille cinq cents. »"],
       ["Les élèves écoutent puis relèvent les prix."]),
    st(["Le professeur annonce que l'on va lire une liste de prix et écrire un dialogue."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire la liste à voix haute."],
       ["Les élèves lisent les marchandises et les prix."]),
    st(["Le professeur fait dégager les étapes du dialogue."],
       ["Les élèves relèvent : question, réponse, marchandage, achat."],
       T("I. Les étapes du dialogue", ["Le client demande le prix.", "Le marchand répond.", "On marchande.", "On achète avec s'il vous plaît."])),
    st(["Le professeur fait récapituler l'écriture du dialogue."],
       ["Deux élèves jouent le dialogue."],
       T("II. Écrire le dialogue", ["« Combien coûte … ? »", "« … ariary le kilo. »", "« C'est trop cher. »", "« Je prends un kilo, s'il vous plaît. »"])),
    st(["Le professeur fait écrire le dialogue."],
       ["Les élèves rédigent quatre répliques."],
       T("III. Application", ["Lis la liste de prix.", "Écris un dialogue de quatre répliques.", "Termine par s'il vous plaît."])),
    st(["Le professeur vérifie la lecture et le dialogue."],
       ["Chaque élève lit et écrit correctement."],
       T("IV. Évaluation", ["Relève deux prix de la liste.", "Écris un dialogue de quatre répliques."])),
    [ { t: "Exercice 1 (10 pts)", q: "Relève le prix de la tomate et du riz.", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Écris un dialogue de marché de quatre répliques.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "tomate : deux mille ariary le kilo ; riz : mille cinq cents", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : « Combien coûte la tomate ? — Deux mille. — C'est trop cher. — Je vous la laisse à mille huit cents, s'il vous plaît. »", r: true }, "."] ])],

  9: [lec(9, "Lire une fiche métier et écrire son projet", "Lire une fiche métier et rédiger son projet professionnel.",
    "Lire une fiche métier et rédiger son projet professionnel",
    "Fiche métier au tableau, cahiers.",
    { titre: "La fiche métier", blocs: [
      { st: "A. Lire la fiche", txt: "la fiche donne le métier, le lieu de travail et l'activité." },
      { st: "B. Écrire son projet", txt: "on dit le métier voulu, le lieu, et ce que l'on fera, au futur." },
    ], aretenir: "Une fiche métier associe métier, lieu et activité ; le projet s'écrit au futur simple." },
    st(["« Que fait le maçon ? » - Révision du lexique des métiers.", "Le professeur fait rappeler deux métiers."],
       ["Les élèves citent deux métiers."], T("I. Révision", ["Rappel : maçon, infirmier, menuisier…"])),
    st(["Le professeur lit la fiche : « Métier : maçon. Lieu : chantier. Activité : construire des maisons. »"],
       ["Les élèves écoutent puis relèvent les trois éléments."]),
    st(["Le professeur annonce que l'on va lire une fiche métier et écrire son projet."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire la fiche à voix haute."],
       ["Les élèves lisent le métier, le lieu, l'activité."]),
    st(["Le professeur fait dégager les trois éléments de la fiche."],
       ["Les élèves relèvent métier, lieu, activité."],
       T("I. Les trois éléments", ["le métier : maçon", "le lieu : le chantier", "l'activité : construire des maisons"])),
    st(["Le professeur fait récapituler l'écriture du projet au futur."],
       ["Un élève dit son projet au futur."],
       T("II. Écrire son projet", ["Je serai …", "Je travaillerai à …", "Je ferai …"])),
    st(["Le professeur fait écrire le projet."],
       ["Les élèves rédigent trois phrases au futur."],
       T("III. Application", ["Lis la fiche du tableau.", "Écris ton projet en trois phrases.", "Utilise le futur simple."])),
    st(["Le professeur vérifie la lecture et le projet."],
       ["Chaque élève lit et écrit correctement."],
       T("IV. Évaluation", ["Relève le lieu et l'activité du maçon.", "Écris ton projet en trois phrases au futur."])),
    [ { t: "Exercice 1 (10 pts)", q: "Sur la fiche, où travaille le maçon et que fait-il ?", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Écris ton projet professionnel en trois phrases au futur simple.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "il travaille sur un chantier et il construit des maisons", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : Je serai infirmier. Je travaillerai au dispensaire. Je soignerai les malades.", r: true }, "."] ])],

  10: [lec(10, "Lire un récit de voyage et en écrire un", "Lire un récit de voyage et en rédiger un au passé composé.",
    "Lire un récit de voyage et en rédiger un au passé composé",
    "Court récit de voyage au tableau, cahiers.",
    { titre: "Le récit de voyage", blocs: [
      { st: "A. Lire le récit", txt: "le récit raconte le voyage au passé composé, dans l'ordre." },
      { st: "B. Écrire un récit", txt: "on raconte les étapes avec d'abord, ensuite, enfin, au passé composé." },
    ], aretenir: "Un récit de voyage se lit et s'écrit au passé composé, dans l'ordre des étapes." },
    st(["« Comment es-tu venu à l'école ? » - Révision des transports.", "Le professeur fait rappeler deux transports."],
       ["Les élèves citent deux transports."], T("I. Révision", ["Rappel : taxi-brousse, vélo, pirogue…"])),
    st(["Le professeur lit : « D'abord, nous avons acheté le billet. Ensuite, nous avons pris le taxi-brousse. Enfin, nous sommes arrivés. »"],
       ["Les élèves écoutent puis relèvent les étapes."]),
    st(["Le professeur annonce que l'on va lire un récit de voyage et en écrire un."],
       ["Un élève lit l'objectif."]),
    st(["Le professeur fait lire le récit à voix haute."],
       ["Les élèves lisent et relèvent les étapes et les verbes au passé composé."]),
    st(["Le professeur fait dégager l'ordre et le temps du récit."],
       ["Les élèves relèvent d'abord, ensuite, enfin et le passé composé."],
       T("I. L'ordre et le temps", ["d'abord : acheter le billet", "ensuite : prendre le taxi-brousse", "enfin : arriver — au passé composé"])),
    st(["Le professeur fait récapituler l'écriture du récit."],
       ["Un élève raconte un voyage au passé composé."],
       T("II. Écrire un récit", ["On choisit trois étapes.", "On les met dans l'ordre.", "On conjugue au passé composé."])),
    st(["Le professeur fait écrire le récit."],
       ["Les élèves rédigent trois phrases au passé composé."],
       T("III. Application", ["Lis le récit du tableau.", "Écris un récit de voyage en trois phrases.", "Utilise le passé composé."])),
    st(["Le professeur vérifie la lecture et l'écriture."],
       ["Chaque élève lit et écrit correctement."],
       T("IV. Évaluation", ["Relève les trois étapes du récit.", "Écris un récit de voyage en trois phrases."])),
    [ { t: "Exercice 1 (10 pts)", q: "Relève les trois étapes du récit, dans l'ordre.", pts: 10 },
      { t: "Exercice 2 (10 pts)", q: "Écris un récit de voyage en trois phrases au passé composé.", pts: 10 } ],
    [ ["Ex. 1 — ", { t: "acheter le billet, prendre le taxi-brousse, arriver", r: true }, "."],
      ["Ex. 2 — ", { t: "réponse libre, ex. : D'abord, nous avons acheté le billet. Ensuite, nous avons pris le taxi-brousse. Enfin, nous sommes arrivés chez ma grand-mère.", r: true }, "."] ])],
};
