// UNITÉ 4 — Les transports, le commerce et le tourisme (6 séances : 21 à 26)
const THEME = "Les transports, le commerce et le tourisme";
const DOC_PROG = "Programme scolaire de la classe de 3ème, Géographie (MEN/DCI, édition 2015)";

module.exports = [
// =====================================================================
{
  num: 21, theme: THEME,
  titre: "Les transports terrestres : la route et le chemin de fer",
  objectif: "décrire le réseau routier et le réseau ferroviaire de Madagascar (grands axes, longueur, état), d'expliquer leurs faiblesses et de montrer leur rôle dans l'économie",
  documentation: `${DOC_PROG} ; Ministère des Travaux Publics, Autorité Routière de Madagascar (2021) ; Madarail ; Banque mondiale, Projet de connectivité des transports (2023) ; FTM, Atlas de Madagascar.`,
  image: null,
  revision: [
    ["Citez les cinq problèmes de l'industrie malgache.", "Les matières premières, la main-d'œuvre, les capitaux, les débouchés, les communications et l'énergie."],
    ["Pourquoi les routes sont-elles un problème pour l'industrie ?", "Le transport des matières premières et des produits est lent et coûteux."],
    ["Quel port assure l'essentiel du commerce extérieur ?", "Toamasina."],
    ["Quelle part du PIB représente l'industrie manufacturière ?", "Environ 10 %."],
  ],
  miseEnSituation: {
    enseignant: [
      "Pour aller d'Antananarivo à Toamasina, le taxi-brousse de Soa met 8 heures sur la RN2, une route goudronnée mais encombrée de camions. Pour aller de Toliara à Morondava, à peine 400 km, sa cousine met deux jours de piste en saison sèche… et ne peut plus passer du tout en saison des pluies. Quant au train de Fianarantsoa à Manakara, il ne circule que quelques jours par semaine.",
      "Pourquoi ces trajets sont-ils si différents ? Quelles conséquences pour les habitants et pour les marchandises ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : certaines routes sont goudronnées, d'autres sont des pistes ; les régions isolées vendent mal leurs produits et paient tout plus cher."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Réseau | Longueur et état | Grands axes | Rôle |", "| Routes | environ 31 600 km de routes classées, dont à peine 6 000 km bitumés ; moins de 15 % en bon état ; plus de 60 % des communes inaccessibles en saison des pluies | RN1 (Tana-Tsiroanomandidy), RN2 (Tana-Toamasina, 353 km), RN4 (Tana-Mahajanga, 570 km), RN6 (Ambondromamy-Antsiranana), RN7 (Tana-Toliara, 930 km), RN13 (Ihosy-Taolagnaro) | plus de 90 % des transports de voyageurs et de marchandises (taxis-brousse, camions) |", "| Chemin de fer | 877 km, construits entre 1901 et 1936 ; voie unique, matériel ancien | Réseau Nord (Madarail) : Tana-Toamasina (TCE, 371 km), Moramanga-Alaotra (MLA, 167 km), Tana-Antsirabe (TA, 153 km) ; Réseau Sud : Fianarantsoa-Côte Est (FCE, 163 km) | fret (carburant, ciment, riz, chrome) surtout sur le TCE ; FCE : désenclavement des villages |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Si une carte murale existe, faire suivre les RN avec le doigt ; sinon, dessiner au tableau un croquis de l'île avec l'étoile des routes autour d'Antananarivo.",
  },
  analyse: [
    ["Quel est le principal moyen de transport à Madagascar ? Quelle part du trafic assure-t-il ?", "La route, avec plus de 90 % des voyageurs et des marchandises : taxis-brousse, camions, charrettes."],
    ["Comment le réseau routier est-il organisé ?", "En étoile autour d'Antananarivo : les routes nationales partent de la capitale vers les ports et les chefs-lieux de province (RN2 vers Toamasina, RN4 vers Mahajanga, RN7 vers Toliara, RN1, RN6 vers Antsiranana)."],
    ["Quelles sont les faiblesses du réseau routier ?", "Il est court pour un pays si grand (31 600 km, dont moins de 6 000 km goudronnés), dégradé (moins de 15 % en bon état), coupé pendant la saison des pluies ; de nombreuses régions (Ouest, Sud, Nord-Est) sont enclavées."],
    ["Pourquoi les routes se dégradent-elles si vite ?", "À cause des pluies violentes et des cyclones, des camions surchargés, du manque d'entretien et de moyens financiers, et parfois de la mauvaise qualité des travaux."],
    ["Quelle est la longueur du réseau ferroviaire ? Quand a-t-il été construit ?", "877 km seulement, construits pendant la colonisation entre 1901 et 1936 ; il n'a pas été étendu depuis."],
    ["Quelles lignes existent ? Laquelle est la plus importante et pourquoi ?", "Le réseau Nord (Tana-Toamasina, Moramanga-Alaotra, Tana-Antsirabe), exploité par Madarail, et la ligne Fianarantsoa-Côte Est. La plus importante est Tana-Toamasina (TCE), qui relie la capitale au grand port et transporte le carburant, le ciment et le riz."],
    ["Pourquoi le train est-il utile bien qu'il soit vieux ?", "Il transporte des charges lourdes à moindre coût et soulage les routes ; la ligne FCE désenclave des villages de la falaise Est qui n'ont aucune route."],
    ["Quel est le lien entre transports terrestres et développement ?", "Sans routes, les paysans ne peuvent pas vendre leurs récoltes ni acheter d'engrais, les prix sont plus élevés, les malades n'atteignent pas l'hôpital ; améliorer les routes est indispensable au développement."],
  ],
  analyseTechnique: "Lecture de tableau et de carte, questions-réponses, croquis au tableau noir",
  synthese: "Donc, à Madagascar, la route est le premier moyen de transport : elle assure plus de 90 % des déplacements grâce aux taxis-brousse et aux camions. Le réseau, organisé en étoile autour d'Antananarivo, est cependant court (environ 31 600 km dont moins de 6 000 km bitumés), dégradé et coupé en saison des pluies, ce qui enclave de nombreuses régions. Le chemin de fer, hérité de la colonisation, ne compte que 877 km sur deux réseaux séparés ; il reste utile pour le fret lourd entre Antananarivo et le port de Toamasina et pour désenclaver la falaise de l'Est. Améliorer et entretenir ces réseaux est une condition du développement économique.",
  application: [
    { consigne: "Reliez chaque route nationale à la ville qu'elle relie à Antananarivo (recopiez les couples).", pts: 4, items: [
      "1. RN2 — 2. RN4 — 3. RN7 — 4. RN1",
      "A. Toliara — B. Toamasina — C. Tsiroanomandidy — D. Mahajanga",
      "Laquelle de ces routes est la plus longue ? Quelle est sa longueur approximative ?",
      "Laquelle est la plus importante pour le commerce extérieur ? Pourquoi ?",
    ], corrige: [
      "1 → **B** ; 2 → **D** ; 3 → **A** ; 4 → **C**.",
      "(Voir les couples ci-dessus.)",
      "La **RN7** (Antananarivo-Toliara), environ **930 km**.",
      "La **RN2**, parce qu'elle relie la capitale au **port de Toamasina**, par où passe 80 % du commerce extérieur.",
    ]},
    { consigne: "Complétez le texte avec les mots proposés : 877 – Toamasina – colonisation – Madarail – FCE.", pts: 4, items: [
      "Le chemin de fer malgache compte …… (1) km construits pendant la …… (2).",
      "Le réseau Nord, exploité par …… (3), relie Antananarivo au port de …… (4).",
      "La ligne …… (5) relie Fianarantsoa à Manakara.",
      "Citez deux marchandises transportées par le train.",
    ], corrige: [
      "(1) **877** ; (2) **colonisation** (1901-1936).",
      "(3) **Madarail** ; (4) **Toamasina**.",
      "(5) **FCE** (Fianarantsoa-Côte Est).",
      "Le **carburant**, le **ciment**, le **riz**, le **chrome**, les conteneurs.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Le réseau routier malgache est organisé en étoile autour d'Antananarivo.",
      "b) La majorité des routes malgaches sont goudronnées.",
      "c) Le chemin de fer relie toutes les provinces de Madagascar.",
      "d) Plus de la moitié des communes sont inaccessibles en saison des pluies.",
    ], corrige: [
      "a) **Vrai** : les RN partent de la capitale vers les ports et les provinces.",
      "b) **Faux** : moins de **6 000 km** sur 31 600 sont bitumés ; la plupart sont des **pistes**.",
      "c) **Faux** : il n'y a que **deux réseaux séparés** (Nord et FCE), ni Mahajanga, ni Toliara, ni Antsiranana ne sont desservies.",
      "d) **Vrai** : plus de 60 % des communes sont coupées plusieurs mois par an.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Décrivez le réseau routier malgache (longueur, organisation, état).",
      "2. Donnez trois causes de la dégradation des routes.",
      "3. Présentez le réseau ferroviaire (longueur, lignes, rôle).",
      "4. Expliquez, avec deux exemples, pourquoi l'enclavement freine le développement.",
    ], corrige: [
      "1. Environ **31 600 km** de routes classées, dont moins de 6 000 km **bitumés**, organisées en **étoile** autour d'Antananarivo ; moins de **15 %** sont en bon état et beaucoup sont **coupées** en saison des pluies.",
      "2. Les **pluies** et les **cyclones**, les camions **surchargés**, le manque d'**entretien** et de moyens financiers, la mauvaise **qualité** de certains travaux.",
      "3. **877 km** construits entre 1901 et 1936 : réseau Nord (**Tana-Toamasina**, Moramanga-Alaotra, Tana-Antsirabe) exploité par Madarail, et ligne **Fianarantsoa-Côte Est** ; il transporte surtout des **marchandises lourdes** (carburant, ciment, riz) et désenclave la falaise Est.",
      "4. Les paysans enclavés **ne peuvent pas vendre** leurs récoltes (le riz pourrit ou se vend très bas) ; les produits importés (sel, pétrole, médicaments) coûtent **beaucoup plus cher** ; les **malades** et les **élèves** n'atteignent pas l'hôpital ou le lycée.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Les **transports** permettent de déplacer les personnes et les marchandises ; ils relient les régions entre elles et le pays au reste du monde. Dans une grande île de près de 1 600 km de long, au relief accidenté et au climat violent, ils sont à la fois indispensables et difficiles. Nous étudions d'abord les transports terrestres : la route et le chemin de fer." },
    { t: "h", x: "1. La route : le premier moyen de transport" },
    { t: "p", x: "La route assure plus de **90 %** des transports de voyageurs et de marchandises : **taxis-brousse**, camions, bus urbains, charrettes à zébus et pousse-pousse dans les villes. Le réseau est organisé en **étoile** autour d'**Antananarivo** : les grandes **routes nationales** relient la capitale aux ports et aux chefs-lieux de province. La **RN2** (353 km) mène à Toamasina, premier port ; la **RN4** (570 km) à Mahajanga ; la **RN7** (930 km) à Fianarantsoa puis Toliara ; la **RN6** prolonge la RN4 vers Antsiranana ; la **RN1** va vers Tsiroanomandidy et l'Ouest ; la **RN13** relie Ihosy à Taolagnaro." },
    { t: "p", x: "Mais ce réseau est **insuffisant** : environ **31 600 km** de routes classées, dont moins de **6 000 km bitumés**, pour un pays plus grand que la France. Il est très **dégradé** : moins de 15 % des routes sont en bon état, et plus de 60 % des communes sont inaccessibles pendant la saison des pluies. Les causes sont les **pluies** et les **cyclones**, les camions **surchargés**, le manque d'**entretien** et de moyens financiers. De vastes régions de l'Ouest, du Sud et du Nord-Est sont **enclavées** : leurs habitants vendent mal leurs récoltes et paient plus cher les produits importés." },
    { t: "fig", file: "carte_transports.png", legende: "Carte schématique des grands axes de transport de Madagascar (routes nationales, voies ferrées, ports, aéroports)", widthCm: 11, source: "réalisation J-Learn d'après l'Autorité Routière, Madarail et l'Atlas de Madagascar (FTM)" },
    { t: "h", x: "2. Le chemin de fer : un réseau ancien et réduit" },
    { t: "p", x: "Le réseau ferroviaire ne compte que **877 km**, construits pendant la **colonisation** entre 1901 et 1936, et jamais prolongés depuis. Il est formé de deux réseaux séparés :" },
    { t: "ul", x: [
      "le **réseau Nord**, exploité depuis 2003 par la société **Madarail** : la ligne **Tananarive-Côte Est** (TCE, 371 km) entre Antananarivo et Toamasina, la ligne **Moramanga-Lac Alaotra** (MLA, 167 km) et la ligne **Tananarive-Antsirabe** (TA, 153 km) ;",
      "le réseau Sud : la ligne **Fianarantsoa-Côte Est** (FCE, 163 km) jusqu'à Manakara, qui franchit la falaise par 48 tunnels et dessert des villages sans route.",
    ]},
    { t: "p", x: "La voie est unique, étroite et le matériel ancien, si bien que le trafic est faible. Le train reste pourtant utile : il transporte à moindre coût les **marchandises lourdes** (carburant, ciment, riz, chrome, conteneurs) entre le port de Toamasina et les Hautes Terres, et il **désenclave** la région de la falaise Est." },
    { t: "h", x: "3. Transports terrestres et développement" },
    { t: "p", x: "L'état des transports terrestres explique en partie les difficultés de l'économie : coût élevé des marchandises, isolement des campagnes, industries concentrées près de la capitale et du port. L'État et ses partenaires (Banque mondiale, Union européenne, Chine, Japon) réhabilitent les routes nationales, construisent de nouveaux axes (autoroute Antananarivo-Toamasina en projet) et entretiennent les pistes rurales grâce au Fonds routier, mais l'effort reste insuffisant face aux besoins." },
  ],
},
// =====================================================================
{
  num: 22, theme: THEME,
  titre: "Les transports aériens, maritimes et fluviaux ; les télécommunications",
  objectif: "présenter les transports aériens, maritimes et fluviaux de Madagascar (aéroports, ports, canal des Pangalanes) et les télécommunications (téléphone mobile, internet), en montrant leur rôle et leurs limites",
  documentation: `${DOC_PROG} ; Aviation Civile de Madagascar ; Agence Portuaire, Maritime et Fluviale (APMF) ; Société du Port à gestion Autonome de Toamasina (SPAT) ; ARTEC, observatoire des télécommunications (2023) ; Banque mondiale, indicateurs numériques.`,
  image: null,
  revision: [
    ["Quel est le premier moyen de transport à Madagascar ? Quelle part du trafic assure-t-il ?", "La route, plus de 90 %."],
    ["Comment le réseau routier est-il organisé ?", "En étoile autour d'Antananarivo."],
    ["Quelle est la longueur du réseau ferroviaire ? Citez deux lignes.", "877 km ; Tana-Toamasina (TCE), Fianarantsoa-Côte Est (FCE), Tana-Antsirabe, Moramanga-Alaotra."],
    ["Pourquoi les routes se dégradent-elles vite ?", "Pluies et cyclones, camions surchargés, manque d'entretien."],
  ],
  miseEnSituation: {
    enseignant: [
      "La famille de Nirina, à Antananarivo, attend un colis envoyé par un oncle de France : il arrive par avion à Ivato en deux jours. Le riz que vend l'épicier du quartier est arrivé du Pakistan par bateau au port de Toamasina, puis par camion. Et ce soir, Nirina appelle sa grand-mère de Sambava avec le téléphone portable, en payant avec le mobile money.",
      "Combien de moyens de transport et de communication reconnaissez-vous dans cette histoire ? Lesquels sont rapides, lesquels transportent de grandes quantités ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : l'avion (rapide, petites quantités), le bateau (lent, grandes quantités), le camion, le téléphone mobile et internet."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Moyen | Équipements | Trafic et rôle | Limites |", "| Aérien | aéroport international d'Ivato (Antananarivo, nouveau terminal 2021), Nosy Be (Fascene), Toamasina, Mahajanga, Antsiranana, Toliara, Taolagnaro ; plus de 50 aérodromes | voyageurs (touristes, hommes d'affaires), fret léger (litchis, crevettes, vanille) ; compagnies Madagascar Airlines, Air France, Ethiopian, Air Austral, Turkish | billets très chers, retards, réseau intérieur réduit |", "| Maritime | Toamasina (environ 80 % du trafic, extension en cours avec le Japon), Mahajanga, Antsiranana, Toliara, Ehoala (Taolagnaro), Nosy Be ; cabotage par boutres et goélettes | tout le commerce extérieur (riz, pétrole, ciment importés ; nickel, vanille, crevettes exportés) | ports peu profonds et encombrés, cabotage lent |", "| Fluvial | canal des Pangalanes (665 km le long de la côte Est, dont environ 430 navigables), fleuves Betsiboka et Tsiribihina en partie | pirogues, chalands ; transport local de produits agricoles | ensablement, entretien insuffisant |", "| Télécommunications | 3 opérateurs mobiles (Telma, Orange, Airtel), câbles sous-marins (EASSy, LION, METISS), fibre optique | plus de 60 % de la population a un téléphone mobile ; mobile money (MVola, Orange Money, Airtel Money) ; internet : environ 20 % de la population | couverture rurale incomplète, coût élevé par rapport aux revenus |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire comparer les deux colonnes « rôle » et « limites » pour chaque moyen ; insister sur le port de Toamasina.",
  },
  analyse: [
    ["Quel est le principal aéroport du pays ? Quels autres aéroports reçoivent des vols internationaux ?", "L'aéroport international d'Ivato à Antananarivo, agrandi en 2021 ; Nosy Be (Fascene), et pour la région Toamasina, Mahajanga, Antsiranana, Toliara, Taolagnaro."],
    ["Que transporte l'avion ? Quels sont ses avantages et ses limites ?", "Des voyageurs (touristes, hommes d'affaires, Malgaches de la diaspora) et du fret léger et précieux (litchis, crevettes, vanille). Il est rapide et franchit l'enclavement, mais il est très cher et transporte peu."],
    ["Pourquoi le transport maritime est-il vital pour Madagascar ?", "Parce que Madagascar est une île : tout le commerce extérieur passe par les ports, importations (riz, pétrole, ciment, machines) comme exportations (nickel, vanille, crevettes, vêtements)."],
    ["Quel est le premier port ? Pourquoi ? Que fait-on pour l'améliorer ?", "Toamasina, avec environ 80 % du trafic : il est relié à la capitale par la RN2 et le chemin de fer et dispose d'eaux profondes ; le Japon finance son extension (nouveau quai à conteneurs, brise-lames)."],
    ["Qu'est-ce que le cabotage ?", "C'est le transport par mer le long des côtes, d'un port à l'autre, par boutres, goélettes et petits cargos ; il dessert les régions sans route de l'Ouest et du Nord-Est."],
    ["Qu'est-ce que le canal des Pangalanes ? À quoi sert-il ?", "Une suite de lagunes et de canaux creusés pendant la colonisation le long de la côte Est, sur 665 km, entre Toamasina et Farafangana ; les pirogues et chalands y transportent les produits agricoles (bananes, café, litchis) et les voyageurs."],
    ["Quelle a été la grande évolution des télécommunications depuis vingt ans ?", "Le téléphone mobile : plus de 60 % des Malgaches en ont un, contre presque personne en 2000 ; il permet le mobile money, qui remplace la banque pour des millions de personnes."],
    ["Quelles sont les limites des télécommunications ?", "Internet ne touche qu'environ 20 % de la population, la couverture des campagnes est incomplète, le prix des appareils et des forfaits reste élevé pour les revenus malgaches."],
  ],
  analyseTechnique: "Lecture de tableau, questions-réponses, exemples vécus",
  synthese: "Donc, à côté de la route et du rail, Madagascar dispose de transports aériens, maritimes et fluviaux. L'avion, autour de l'aéroport international d'Ivato, transporte les voyageurs et le fret précieux, mais il est cher. Le transport maritime est vital pour une île : tout le commerce extérieur passe par les ports, surtout Toamasina (80 % du trafic), et le cabotage dessert les côtes enclavées. Le canal des Pangalanes assure un transport local sur la côte Est. Enfin, les télécommunications ont été bouleversées par le téléphone mobile, que possèdent plus de 60 % des Malgaches, et par le mobile money ; mais internet ne touche encore qu'environ un Malgache sur cinq.",
  application: [
    { consigne: "Indiquez le moyen de transport le plus adapté à chaque situation et justifiez en quelques mots.", pts: 4, items: [
      "1. Exporter 30 000 tonnes de nickel vers la Corée.",
      "2. Envoyer 2 tonnes de litchis frais en France en 24 heures.",
      "3. Transporter des régimes de bananes d'un village de la côte Est jusqu'à Toamasina.",
      "4. Faire venir un touriste italien à Nosy Be.",
    ], corrige: [
      "1. Le **bateau** (port de Toamasina) : grandes quantités, coût faible.",
      "2. L'**avion** (fret aérien depuis Ivato) : rapidité pour un produit périssable et cher.",
      "3. La **pirogue** ou le **chaland** sur le **canal des Pangalanes**.",
      "4. L'**avion** (aéroport de Fascene, Nosy Be).",
    ]},
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. Le principal aéroport international de Madagascar est : A) Toamasina — B) Ivato — C) Nosy Be.",
      "2. Le port de Toamasina assure environ : A) 20 % — B) 50 % — C) 80 % du trafic maritime.",
      "3. Le canal des Pangalanes se trouve : A) sur la côte Ouest — B) sur la côte Est — C) sur les Hautes Terres.",
      "4. La part des Malgaches utilisant internet est d'environ : A) 20 % — B) 50 % — C) 80 %.",
    ], corrige: [
      "1. **B)** Ivato, à Antananarivo.",
      "2. **C)** environ 80 %.",
      "3. **B)** sur la côte Est, entre Toamasina et Farafangana.",
      "4. **A)** environ 20 % (un sur cinq).",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Le transport aérien est le moyen le moins cher pour les Malgaches.",
      "b) Le commerce extérieur de Madagascar passe presque entièrement par la mer.",
      "c) Le cabotage est le transport de marchandises par avion.",
      "d) Le téléphone mobile est plus répandu qu'internet à Madagascar.",
    ], corrige: [
      "a) **Faux** : c'est le plus **cher** ; le moins cher est le taxi-brousse ou le bateau.",
      "b) **Vrai** : Madagascar est une île ; environ 80 % passe par Toamasina.",
      "c) **Faux** : c'est le transport **par mer le long des côtes**, d'un port à l'autre.",
      "d) **Vrai** : plus de 60 % contre environ 20 %.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Quels sont les avantages et les limites du transport aérien à Madagascar ?",
      "2. Pourquoi le port de Toamasina est-il le premier du pays ? Citez trois produits qui y transitent.",
      "3. Qu'est-ce que le canal des Pangalanes et quel est son rôle ?",
      "4. Montrez comment le téléphone mobile a changé la vie économique des Malgaches.",
    ], corrige: [
      "1. Avantages : **rapidité**, franchit l'**enclavement**, indispensable au **tourisme** et au fret précieux. Limites : **prix** très élevé, faibles quantités, retards et réseau intérieur réduit.",
      "2. Parce qu'il est relié à la **capitale** par la RN2 et le rail, qu'il a des **eaux profondes** et qu'il a été agrandi ; il reçoit le **riz**, le **pétrole**, le **ciment** importés et expédie le **nickel**, la **vanille**, les **girofles**.",
      "3. Une suite de **lagunes et de canaux** de 665 km le long de la **côte Est** ; les pirogues et chalands y transportent les **produits agricoles** et les voyageurs des villages sans route.",
      "4. Il permet de **communiquer** avec la famille et les clients, de connaître les **prix** des marchés, d'**envoyer et recevoir de l'argent** par mobile money (MVola, Orange Money, Airtel Money) sans banque, et de développer de petits **commerces**.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Île immense et aux routes difficiles, Madagascar a besoin d'autres moyens de transport pour relier ses régions et s'ouvrir au monde : l'avion, le bateau et la voie d'eau. Les télécommunications, elles, ont connu une véritable révolution depuis vingt ans." },
    { t: "h", x: "1. Le transport aérien" },
    { t: "p", x: "L'**aéroport international d'Ivato**, à Antananarivo, doté d'un nouveau terminal depuis 2021, concentre l'essentiel du trafic. **Nosy Be** (Fascene) reçoit les vols charters touristiques ; Toamasina, Mahajanga, Antsiranana, Toliara et Taolagnaro accueillent des vols régionaux, et plus de 50 aérodromes desservent l'intérieur. La compagnie nationale **Madagascar Airlines** (ex-Air Madagascar) assure les liaisons intérieures ; Air France, Ethiopian Airlines, Air Austral, Turkish Airlines et Kenya Airways relient l'île à l'Europe, à l'Afrique et à l'océan Indien. L'avion transporte les **voyageurs** (touristes, hommes d'affaires) et le **fret précieux ou périssable** (litchis, crevettes, vanille, fleurs). Il franchit l'enclavement, mais il est **très cher** et ne transporte que de faibles quantités." },
    { t: "h", x: "2. Le transport maritime : la porte du commerce extérieur" },
    { t: "p", x: "Pour une île, la mer est la seule voie pour les échanges de masse : la totalité du commerce extérieur passe par les **ports**. **Toamasina**, sur la côte Est, assure environ **80 %** du trafic : il est relié à la capitale par la RN2 et le chemin de fer, et le Japon finance son **extension** (nouveau quai à conteneurs, prolongement du brise-lames). Les autres ports sont **Mahajanga** (Ouest, crevettes, ciment), **Antsiranana** (Nord, l'une des plus belles baies du monde), **Toliara** (Sud-Ouest), **Ehoala** près de Taolagnaro (ilménite) et Nosy Be. Le **cabotage**, transport par boutres, goélettes et petits cargos le long des côtes, relie les régions sans route de l'Ouest et du Nord-Est. Les ports restent peu profonds, encombrés et coûteux." },
    { t: "h", x: "3. Le transport fluvial : le canal des Pangalanes" },
    { t: "p", x: "Les fleuves malgaches, coupés de rapides et ensablés, sont peu navigables, sauf la basse Betsiboka et la Tsiribihina. Le principal axe fluvial est le **canal des Pangalanes**, suite de lagunes reliées par des canaux creusés pendant la colonisation sur **665 km** le long de la côte Est, de Toamasina à Farafangana. Pirogues et chalands y transportent les produits agricoles (bananes, café, litchis, girofle) et les voyageurs ; l'ensablement limite la navigation à environ 430 km." },
    { t: "h", x: "4. Les télécommunications : la révolution du mobile" },
    { t: "p", x: "Le téléphone fixe n'a jamais dépassé quelques dizaines de milliers d'abonnés. En revanche, le **téléphone mobile**, apparu vers 2000, est aujourd'hui utilisé par plus de **60 % des Malgaches** grâce à trois opérateurs (**Telma**, **Orange**, **Airtel**). Il a transformé l'économie : les paysans connaissent les prix des marchés, les commerçants passent commande, et le **mobile money** (MVola, Orange Money, Airtel Money) permet d'envoyer et de recevoir de l'argent sans compte bancaire. Madagascar est reliée au monde par des **câbles sous-marins** à fibre optique (EASSy, LION, METISS) et dispose d'un internet parmi les plus rapides d'Afrique, mais seulement **20 % environ** de la population l'utilise : la couverture des campagnes est incomplète et les appareils et forfaits restent chers pour les revenus des ménages." },
  ],
},
// =====================================================================
{
  num: 23, theme: THEME,
  titre: "Le commerce intérieur",
  objectif: "décrire l'organisation du commerce intérieur malgache (marchés, épiceries, grossistes, grandes surfaces, secteur informel), d'expliquer le rôle du pouvoir d'achat et de présenter les problèmes de la distribution",
  documentation: `${DOC_PROG} ; INSTAT, Enquête permanente auprès des ménages (EPM 2021-2022) ; INSTAT, indice des prix à la consommation (2023-2024) ; Ministère de l'Industrialisation, du Commerce et de la Consommation ; Banque mondiale, Note sur la pauvreté (2024).`,
  image: null,
  revision: [
    ["Quel est le principal port de Madagascar ? Quelle part du trafic assure-t-il ?", "Toamasina, environ 80 %."],
    ["Où se trouve le canal des Pangalanes ?", "Le long de la côte Est, entre Toamasina et Farafangana."],
    ["Quelle proportion de Malgaches possède un téléphone mobile ?", "Plus de 60 %."],
    ["Qu'est-ce que le mobile money ?", "Un service qui permet d'envoyer et de recevoir de l'argent avec un téléphone portable."],
  ],
  miseEnSituation: {
    enseignant: [
      "Chaque vendredi, c'est le jour de marché à Ambohimahasoa. Dès l'aube, les paysans arrivent avec des paniers de tomates, des poulets et des sacs de riz. Des collecteurs achètent le riz pour le revendre à Fianarantsoa. Un marchand ambulant vend des savons, des piles et des vêtements venus de Chine. Et Madame Rasoa, avec ses 5 000 ariary, hésite : un kapoaka de riz, un morceau de viande, ou le cahier de son fils ?",
      "Qui vend et qui achète sur ce marché ? Pourquoi Madame Rasoa doit-elle choisir ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : les paysans, les collecteurs, les marchands ambulants ; parce que son argent ne suffit pas pour tout acheter : son pouvoir d'achat est faible."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Élément | Données et exemples |", "| Lieux du commerce | marchés hebdomadaires (tsena) des villages ; grands marchés urbains (Analakely, Anosibe, Andravoahangy à Antananarivo) ; épiceries de quartier ; marchands ambulants ; supermarchés (Shoprite, Leader Price, Supermaki) dans les grandes villes |", "| Acteurs | producteurs (paysans, artisans), collecteurs, grossistes, détaillants, transporteurs, consommateurs |", "| Prix du riz au détail | environ 2 500 à 3 200 ariary le kilo en 2024 (soit environ 900 ariary le kapoaka) contre 1 600 à 2 000 ariary en 2019 |", "| Budget des ménages | l'alimentation représente environ 60 à 70 % des dépenses des ménages pauvres ; salaire minimum : environ 250 000 ariary par mois (2024) |", "| Inflation | hausse des prix de 8 à 10 % par an entre 2022 et 2024 |", "| Secteur informel | plus de 90 % des emplois du commerce ne sont pas déclarés |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire calculer : avec 250 000 ariary par mois, combien de kilos de riz à 3 000 ariary peut-on acheter ? (environ 83 kg).",
  },
  analyse: [
    ["Qu'est-ce que le commerce intérieur ?", "C'est l'ensemble des échanges de marchandises à l'intérieur du pays, entre producteurs et consommateurs, par l'intermédiaire des commerçants."],
    ["Où se fait le commerce à Madagascar ?", "Surtout sur les marchés : le tsena hebdomadaire des villages et les grands marchés permanents des villes (Analakely, Anosibe) ; puis les épiceries de quartier, les marchands ambulants et, dans les grandes villes, quelques supermarchés."],
    ["Quel est le circuit d'un sac de riz du paysan au consommateur ?", "Le paysan vend au collecteur, qui vend au grossiste de la ville, qui vend au détaillant (épicier), qui vend au consommateur ; chaque intermédiaire prend une marge, ce qui fait monter le prix."],
    ["Qu'est-ce que le pouvoir d'achat ?", "C'est la quantité de biens et de services qu'une personne peut acheter avec son revenu ; il baisse quand les prix montent plus vite que les revenus."],
    ["Pourquoi le pouvoir d'achat des Malgaches est-il faible ? Quelle en est la conséquence pour le commerce ?", "Parce que les revenus sont très bas (salaire minimum d'environ 250 000 ariary) et que l'inflation atteint 8 à 10 % par an ; les ménages consacrent 60 à 70 % de leurs dépenses à l'alimentation et achètent peu d'autres produits : le marché intérieur est étroit."],
    ["Pourquoi le prix du riz varie-t-il selon les saisons et les régions ?", "Il est bas à la récolte (avril-juin) et élevé pendant la période de soudure (décembre-mars) ; il est plus cher dans les régions enclavées à cause du coût du transport."],
    ["Qu'est-ce que le secteur informel dans le commerce ? Quels problèmes pose-t-il ?", "Les petits commerces non déclarés (marchands ambulants, épiceries, revendeurs), qui représentent plus de 90 % des emplois du commerce ; ils font vivre des millions de familles mais ne paient pas d'impôts et échappent aux contrôles de qualité."],
    ["Quels sont les problèmes de la distribution à Madagascar ?", "Trop d'intermédiaires qui font monter les prix, mauvaises routes, stockage insuffisant (pertes après récolte), spéculation des collecteurs, poids de l'informel, produits importés ou de contrebande qui concurrencent la production locale."],
  ],
  analyseTechnique: "Lecture de tableau, calcul simple, questions-réponses",
  synthese: "Donc, le commerce intérieur est l'ensemble des échanges de marchandises à l'intérieur du pays. À Madagascar, il s'organise surtout autour des marchés (tsena de village, grands marchés urbains), des épiceries et des marchands ambulants, avec quelques supermarchés dans les grandes villes ; il est dominé par le secteur informel. Les produits passent par de nombreux intermédiaires (collecteurs, grossistes, détaillants) qui font monter les prix. Le pouvoir d'achat, c'est-à-dire ce qu'un revenu permet d'acheter, est très faible : les ménages dépensent 60 à 70 % de leur budget pour se nourrir, et l'inflation aggrave la situation. Le marché intérieur reste donc étroit et la distribution souffre des mauvaises routes, du manque de stockage et de la spéculation.",
  application: [
    { consigne: "Remettez dans l'ordre les étapes du circuit du riz, de la rizière au consommateur, puis répondez.", pts: 4, items: [
      "Étapes en désordre : détaillant (épicier) – paysan – grossiste de la ville – collecteur.",
      "Combien d'intermédiaires y a-t-il entre le paysan et le consommateur ?",
      "Quel effet ces intermédiaires ont-ils sur le prix ?",
      "Que pourrait-on faire pour que le paysan gagne plus et que le consommateur paie moins ?",
    ], corrige: [
      "**Paysan → collecteur → grossiste → détaillant → consommateur**.",
      "**Trois** intermédiaires (collecteur, grossiste, détaillant).",
      "Chacun prend une **marge** : le prix **augmente** à chaque étape (il peut doubler entre le paysan et le consommateur).",
      "Créer des **coopératives** de paysans qui vendent directement, améliorer les **routes** et les **greniers** de stockage, informer les paysans des **prix** (téléphone mobile).",
    ]},
    { consigne: "Calculez et répondez. En 2019, un ouvrier gagnait 200 000 ariary par mois et le riz coûtait 2 000 ariary le kilo. En 2024, il gagne 250 000 ariary et le riz coûte 3 000 ariary.", pts: 4, items: [
      "1. Combien de kilos de riz pouvait-il acheter avec tout son salaire en 2019 ?",
      "2. Combien de kilos peut-il acheter en 2024 ?",
      "3. Son salaire a-t-il augmenté ? Son pouvoir d'achat a-t-il augmenté ?",
      "4. Comment appelle-t-on la hausse générale des prix ?",
    ], corrige: [
      "1. 200 000 ÷ 2 000 = **100 kg**.",
      "2. 250 000 ÷ 3 000 ≈ **83 kg**.",
      "3. Son **salaire** a augmenté (+25 %) mais son **pouvoir d'achat** a **baissé** : il achète 17 kg de moins, car les prix ont augmenté plus vite (+50 %).",
      "4. L'**inflation**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Le commerce intérieur malgache se fait surtout dans les supermarchés.",
      "b) Le pouvoir d'achat augmente quand les prix montent plus vite que les salaires.",
      "c) Les ménages pauvres dépensent la plus grande partie de leur budget pour se nourrir.",
      "d) Le prix du riz est le plus bas pendant la période de soudure.",
    ], corrige: [
      "a) **Faux** : surtout sur les **marchés**, dans les épiceries et par les marchands ambulants ; les supermarchés sont rares.",
      "b) **Faux** : il **baisse** ; il augmente quand les revenus montent plus vite que les prix.",
      "c) **Vrai** : 60 à 70 % de leurs dépenses.",
      "d) **Faux** : il est le plus **élevé** pendant la soudure (décembre-mars) et le plus bas à la **récolte**.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Définissez le commerce intérieur et citez ses principaux lieux à Madagascar.",
      "2. Qu'est-ce que le pouvoir d'achat ? Pourquoi est-il faible à Madagascar ?",
      "3. Quels sont les avantages et les inconvénients du commerce informel ?",
      "4. Citez trois problèmes de la distribution et une solution pour chacun.",
    ], corrige: [
      "1. Ensemble des **échanges de marchandises à l'intérieur du pays** ; lieux : **marchés** (tsena, Analakely, Anosibe), **épiceries** de quartier, **marchands ambulants**, quelques **supermarchés**.",
      "2. C'est la **quantité de biens** qu'un revenu permet d'acheter ; il est faible parce que les **revenus** sont très bas (80 % de pauvres), que l'**inflation** est forte et que l'**alimentation** absorbe la majorité du budget.",
      "3. Avantages : il fait **vivre** des millions de familles, offre des produits **bon marché** et proches des clients. Inconvénients : pas d'**impôts** pour l'État, pas de **protection sociale** pour les travailleurs, pas de contrôle de la **qualité**.",
      "4. Trop d'**intermédiaires** → coopératives et vente directe ; mauvaises **routes** → réhabilitation des pistes rurales ; manque de **stockage** → greniers communautaires ; **spéculation** → contrôle des prix et information par téléphone mobile.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Le **commerce intérieur** est l'ensemble des échanges de marchandises à l'intérieur du pays, entre les producteurs (paysans, artisans, industriels) et les consommateurs, par l'intermédiaire des commerçants. Il occupe une grande partie des Malgaches, surtout dans le secteur informel." },
    { t: "h", x: "1. L'organisation du commerce intérieur" },
    { t: "p", x: "Le cœur du commerce malgache est le **marché** (tsena). Dans les campagnes, le marché hebdomadaire réunit chaque semaine paysans, collecteurs et marchands ambulants. Dans les villes, de grands marchés permanents comme **Analakely**, **Anosibe** (marché de gros des produits agricoles) ou Andravoahangy à Antananarivo, et les marchés de chaque quartier, fournissent l'essentiel des produits. S'y ajoutent les **épiceries** de quartier, les boutiques des commerçants d'origine indienne (karana) ou chinoise, les **marchands ambulants** et, dans les grandes villes, quelques **supermarchés** (Shoprite, Leader Price, Supermaki) fréquentés par les ménages aisés." },
    { t: "p", x: "Entre le producteur et le consommateur interviennent plusieurs **acteurs** : le **collecteur** achète les récoltes dans les villages, le **grossiste** les stocke en ville, le **détaillant** les vend au consommateur, et les **transporteurs** relient les uns aux autres. Chaque intermédiaire prend une marge : le prix du riz peut doubler entre la rizière et l'épicerie. Plus de 90 % des emplois du commerce appartiennent au **secteur informel** : ces petits commerces non déclarés font vivre des millions de familles mais ne paient pas d'impôts et échappent aux contrôles." },
    { t: "h", x: "2. Le pouvoir d'achat" },
    { t: "p", x: "Le **pouvoir d'achat** est la quantité de biens et de services qu'un revenu permet d'acheter. Il dépend des **revenus** et des **prix**. À Madagascar, il est très faible : le salaire minimum est d'environ **250 000 ariary** par mois (2024), la majorité des paysans gagnent moins, et l'**inflation** (hausse générale des prix) a atteint 8 à 10 % par an entre 2022 et 2024. Le kilo de riz, qui coûtait 1 600 à 2 000 ariary en 2019, dépasse 3 000 ariary en 2024. Les ménages pauvres consacrent **60 à 70 %** de leurs dépenses à l'**alimentation**, et il leur reste peu pour l'habillement, la santé, l'école ou les produits manufacturés. Le **marché intérieur** est donc étroit, ce qui freine l'industrie locale." },
    { t: "h", x: "3. Les problèmes de la distribution" },
    { t: "ul", x: [
      "les **routes** dégradées et l'enclavement : les produits circulent mal, les prix varient fortement d'une région à l'autre (le riz est plus cher dans le Sud enclavé que dans l'Alaotra) ;",
      "les **intermédiaires** trop nombreux et la **spéculation** des collecteurs, qui achètent bas à la récolte et revendent cher pendant la **soudure** (décembre-mars) ;",
      "le manque de **stockage** et de conservation : une partie des récoltes se perd ;",
      "la concurrence des produits **importés** et de la **contrebande**, souvent moins chers que les produits locaux ;",
      "la faiblesse des **contrôles** (poids, qualité, prix) et le poids de l'informel.",
    ]},
    { t: "p", x: "Pour améliorer la distribution, l'État et ses partenaires encouragent les **coopératives** paysannes, les **greniers communautaires**, la réhabilitation des pistes rurales, l'information sur les prix par téléphone mobile et la promotion des produits **vita malagasy**." },
  ],
},
// =====================================================================
{
  num: 24, theme: THEME,
  titre: "Le commerce extérieur",
  objectif: "présenter les exportations et les importations de Madagascar, de calculer et d'interpréter la balance commerciale, d'identifier les principaux partenaires et acteurs et d'expliquer les difficultés du commerce extérieur",
  documentation: `${DOC_PROG} ; Banque mondiale, World Integrated Trade Solution (WITS), profil Madagascar 2023 ; INSTAT, statistiques du commerce extérieur (2023) ; Douanes malgaches ; Organisation mondiale du commerce, profil commercial 2023.`,
  image: null,
  revision: [
    ["Qu'est-ce que le commerce intérieur ?", "L'ensemble des échanges de marchandises à l'intérieur du pays."],
    ["Qu'est-ce que le pouvoir d'achat ?", "La quantité de biens et de services qu'un revenu permet d'acheter."],
    ["Citez les intermédiaires entre le paysan et le consommateur.", "Le collecteur, le grossiste, le détaillant."],
    ["Quelle part de leur budget les ménages pauvres consacrent-ils à l'alimentation ?", "60 à 70 %."],
  ],
  miseEnSituation: {
    enseignant: [
      "Au port de Toamasina, deux navires sont à quai. Le premier décharge des sacs de riz du Pakistan, des voitures d'occasion du Japon et des tissus de Chine. Le second charge des conteneurs de nickel pour la Corée, des sacs de girofle pour Singapour et des cartons de vanille pour les États-Unis.",
      "Que vend Madagascar et qu'achète-t-elle ? Selon vous, lequel des deux navires transporte le plus de valeur ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : elle vend des minerais et des produits agricoles, elle achète des produits alimentaires et manufacturés ; le navire des importations vaut plus cher."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Le commerce extérieur de Madagascar en 2023 | Données |", "| Valeur des exportations | environ 3,2 milliards de dollars |", "| Valeur des importations | environ 4,7 milliards de dollars |", "| Principaux produits exportés (% de la valeur) | nickel 25 % ; vanille 8 % ; girofle 8 % ; vêtements (zones franches) environ 15 % ; titane (ilménite) 5 % ; or 4 % ; crevettes, cobalt, litchis, huiles essentielles |", "| Principaux produits importés (% de la valeur) | produits pétroliers 19 % ; riz 4 % ; machines et véhicules ; médicaments ; tissus ; ciment ; huile alimentaire ; sucre |", "| Principaux clients | France 14,5 % ; États-Unis 12,6 % ; Japon 8 % ; Corée du Sud 8 % ; Chine 8 % |", "| Principaux fournisseurs | Chine 17 % ; Oman (pétrole) 13,5 % ; France 11 % ; Inde 9 % ; Émirats arabes unis |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire calculer au tableau la différence exportations − importations avant de donner le mot « balance commerciale ».",
  },
  analyse: [
    ["Qu'est-ce que le commerce extérieur ? Que sont les exportations et les importations ?", "Ce sont les échanges de marchandises avec les autres pays : les exportations sont les produits vendus à l'étranger, les importations les produits achetés à l'étranger."],
    ["Que vend Madagascar à l'étranger ? Quelle est la nature de ces produits ?", "Du nickel, de la vanille, du girofle, des vêtements, de l'ilménite, de l'or, des crevettes, des litchis : des matières premières brutes ou peu transformées et des vêtements cousus par les zones franches."],
    ["Qu'achète Madagascar à l'étranger ?", "Des produits pétroliers, du riz, des machines, des véhicules, des médicaments, des tissus, du ciment, de l'huile et du sucre : de l'énergie, des aliments et des produits manufacturés."],
    ["Calculez la balance commerciale de 2023. Que constatez-vous ?", "3,2 − 4,7 = −1,5 milliard de dollars : la balance commerciale est déficitaire, Madagascar achète plus qu'elle ne vend."],
    ["Pourquoi la balance commerciale est-elle toujours déficitaire ?", "Parce que le pays exporte des produits bruts dont les prix sont bas et variables, et importe des produits manufacturés et du pétrole dont les prix sont élevés ; c'est la détérioration des termes de l'échange."],
    ["Qui sont les principaux partenaires commerciaux ? Que remarquez-vous ?", "Clients : France, États-Unis, Japon, Corée, Chine ; fournisseurs : Chine, Oman, France, Inde. La France reste un partenaire majeur (ancienne colonie), mais la Chine est devenue le premier fournisseur et l'Asie domine les échanges."],
    ["Qui sont les acteurs du commerce extérieur ?", "Les grandes sociétés minières et franches, les exportateurs de vanille et de girofle (collecteurs, sociétés d'Antalaha et de Toamasina), les importateurs (souvent d'origine indienne ou chinoise), les Douanes, le port de Toamasina, les banques et l'État qui négocie les accords (AGOA, Union européenne, SADC, COMESA)."],
    ["Quelles sont les difficultés du commerce extérieur malgache ?", "La dépendance envers quelques produits dont les cours varient (nickel, vanille), le déficit permanent, le manque de devises, la faible transformation des produits, la concurrence, la contrebande (bois de rose, or) et la lourdeur des procédures portuaires et douanières."],
  ],
  analyseTechnique: "Lecture de tableau et de graphique, calcul, questions-réponses",
  synthese: "Donc, le commerce extérieur de Madagascar repose sur l'exportation de matières premières brutes ou peu transformées (nickel, vanille, girofle, ilménite, or, crevettes) et de vêtements des zones franches, et sur l'importation de pétrole, de riz, de machines, de véhicules et de produits manufacturés. En 2023, les exportations (3,2 milliards de dollars) sont inférieures aux importations (4,7 milliards) : la balance commerciale est déficitaire d'environ 1,5 milliard. Les principaux partenaires sont la France, les États-Unis, la Chine, le Japon, la Corée, l'Inde et Oman. Ce commerce est fragile : il dépend de quelques produits aux prix instables et creuse la dette du pays.",
  application: [
    { consigne: "Classez les produits suivants en exportations ou importations de Madagascar : nickel – produits pétroliers – vanille – riz – vêtements – machines – girofle – médicaments.", pts: 4, items: [
      "Exportations : ……………",
      "Importations : ……………",
      "Quel est le premier produit exporté en valeur ? Vers quels pays ?",
      "Quel est le premier produit importé ? D'où vient-il ?",
    ], corrige: [
      "Exportations : **nickel**, **vanille**, **vêtements**, **girofle**.",
      "Importations : **produits pétroliers**, **riz**, **machines**, **médicaments**.",
      "Le **nickel** (25 %), vers la **Corée du Sud**, le **Japon** et la Chine.",
      "Les **produits pétroliers** (19 %), venus surtout d'**Oman**, des Émirats et d'Inde.",
    ]},
    { consigne: "Calculez et interprétez. En 2022, Madagascar a exporté pour 3,7 milliards de dollars et importé pour 5,4 milliards.", pts: 4, items: [
      "1. Calculez le solde de la balance commerciale de 2022.",
      "2. Cette balance est-elle excédentaire ou déficitaire ?",
      "3. Comparez avec 2023 (3,2 et 4,7 milliards) : le déficit a-t-il augmenté ou diminué ?",
      "4. Comment le pays paie-t-il la différence ?",
    ], corrige: [
      "1. 3,7 − 5,4 = **−1,7 milliard de dollars**.",
      "2. **Déficitaire** : les importations dépassent les exportations.",
      "3. En 2023 : 3,2 − 4,7 = −1,5 milliard ; le déficit a légèrement **diminué**, mais les exportations ont aussi baissé (chute du cours du nickel).",
      "4. Grâce aux **devises** envoyées par la diaspora, aux recettes du **tourisme**, aux **aides** et surtout aux **emprunts**, qui augmentent la **dette**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Madagascar exporte surtout des produits manufacturés.",
      "b) La balance commerciale de Madagascar est excédentaire.",
      "c) La Chine est le premier fournisseur de Madagascar.",
      "d) La vanille est le premier produit exporté en valeur.",
    ], corrige: [
      "a) **Faux** : surtout des **matières premières** (nickel, vanille, girofle) et des vêtements.",
      "b) **Faux** : elle est **déficitaire** d'environ 1,5 milliard de dollars.",
      "c) **Vrai** : environ 17 % des importations.",
      "d) **Faux** : c'est le **nickel** (25 %) ; la vanille vient ensuite (8 %).",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Définissez la balance commerciale et expliquez pourquoi celle de Madagascar est déficitaire.",
      "2. Citez trois clients et trois fournisseurs de Madagascar.",
      "3. Qu'est-ce que la détérioration des termes de l'échange ? Donnez un exemple.",
      "4. Proposez trois mesures pour améliorer le commerce extérieur malgache.",
    ], corrige: [
      "1. C'est la **différence entre la valeur des exportations et celle des importations**. Elle est déficitaire parce que Madagascar exporte des produits **bruts** peu chers et importe des produits **manufacturés** et du **pétrole** chers.",
      "2. Clients : **France**, **États-Unis**, **Japon**, Corée du Sud, Chine. Fournisseurs : **Chine**, **Oman**, **France**, Inde, Émirats.",
      "3. C'est la **baisse du prix** des produits bruts exportés par rapport au prix des produits manufacturés importés : il faut vendre **toujours plus de vanille ou de nickel** pour acheter le même tracteur.",
      "4. **Transformer** sur place les produits (chocolat, huiles essentielles, métaux raffinés) ; **diversifier** les produits et les partenaires ; produire le **riz** et le **ciment** pour réduire les importations ; lutter contre la **contrebande** ; améliorer le **port** et les **douanes**.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Le **commerce extérieur** est l'ensemble des échanges de marchandises entre Madagascar et les autres pays. Les **exportations** sont les produits vendus à l'étranger ; les **importations** sont les produits achetés à l'étranger. Ce commerce passe presque entièrement par le port de Toamasina." },
    { t: "h", x: "1. Les exportations : des produits bruts" },
    { t: "p", x: "En 2023, Madagascar a exporté pour environ **3,2 milliards de dollars**. Le premier produit est le **nickel** d'Ambatovy (25 % de la valeur), suivi des **vêtements** des zones franches (environ 15 %), de la **vanille** (8 %), du **girofle** (8 %), de l'**ilménite** (5 %), de l'**or** (4 %), du cobalt, des **crevettes**, des litchis, du café, du cacao et des huiles essentielles. Ce sont presque tous des **matières premières** brutes ou peu transformées, dont les prix, fixés sur les marchés mondiaux, varient beaucoup d'une année à l'autre : la chute du cours du nickel ou de la vanille suffit à faire baisser les recettes du pays." },
    { t: "h", x: "2. Les importations : énergie, aliments et produits manufacturés" },
    { t: "p", x: "La même année, les importations ont atteint environ **4,7 milliards de dollars**. En tête viennent les **produits pétroliers** (19 %), puis le **riz** (4 %, entre 400 000 et 750 000 tonnes par an), les **machines** et équipements, les **véhicules**, les **médicaments**, les **tissus** des zones franches, le ciment, l'huile alimentaire, le sucre, le blé et les produits électroniques. Madagascar achète donc cher des produits **fabriqués** et de l'**énergie**, et vend bon marché des produits **bruts**." },
    { t: "fig", file: "commerce_exterieur.png", legende: "Le commerce extérieur de Madagascar en 2023 : principaux produits exportés et importés (en % de la valeur)", widthCm: 13, source: "réalisation J-Learn d'après Banque mondiale/WITS et INSTAT (2023, valeurs arrondies)" },
    { t: "h", x: "3. Une balance commerciale déficitaire" },
    { t: "p", x: "La **balance commerciale** est la différence entre la valeur des exportations et celle des importations. En 2023 : 3,2 − 4,7 = **−1,5 milliard de dollars**. Elle est **déficitaire**, comme chaque année depuis l'indépendance. Ce déficit s'explique par la **détérioration des termes de l'échange** : les prix des produits bruts montent moins vite que ceux des produits manufacturés, si bien qu'il faut exporter toujours plus pour importer autant. Le pays comble la différence par les envois de la diaspora, le tourisme, l'aide internationale et surtout les **emprunts**, qui alourdissent la dette." },
    { t: "h", x: "4. Les partenaires et les acteurs" },
    { t: "p", x: "Les principaux **clients** sont la **France** (14,5 %), les **États-Unis** (12,6 %, vêtements et vanille), le **Japon** et la **Corée du Sud** (nickel), la **Chine** et l'Allemagne. Les principaux **fournisseurs** sont la **Chine** (17 %), **Oman** (pétrole, 13,5 %), la **France** (11 %), l'**Inde** (riz, médicaments) et les Émirats arabes unis. L'Asie domine désormais les échanges. Les **acteurs** sont les grandes sociétés minières et franches, les exportateurs de vanille et de girofle, les importateurs, les Douanes, le port de Toamasina, les banques et l'État, qui négocie les accords commerciaux (AGOA avec les États-Unis, accord de partenariat avec l'Union européenne, SADC et COMESA en Afrique)." },
    { t: "h", x: "5. Les difficultés" },
    { t: "p", x: "Le commerce extérieur malgache est fragile : **dépendance** envers quelques produits et quelques partenaires, **déficit** permanent et manque de **devises**, faible **transformation** des produits, **contrebande** (bois de rose, or, pierres précieuses, tortues) qui prive l'État de recettes, lenteur et coût des procédures portuaires et douanières. Les solutions passent par la transformation sur place, la diversification, la production locale de riz et de ciment et la lutte contre les trafics." },
  ],
},
// =====================================================================
{
  num: 25, theme: THEME,
  titre: "Le tourisme (1) : les ressources et les flux touristiques",
  objectif: "présenter les ressources touristiques de Madagascar (nature, plages, culture), de décrire les flux de touristes (nombre, origine, destinations) et d'expliquer les facteurs qui les limitent",
  documentation: `${DOC_PROG} ; Ministère du Tourisme et de l'Artisanat, statistiques des arrivées (2019-2023) ; Office National du Tourisme de Madagascar (ONTM) ; Madagascar National Parks ; UNESCO, Liste du patrimoine mondial ; Banque mondiale, Note sur le tourisme (2022).`,
  image: null,
  revision: [
    ["Quel est le premier produit exporté par Madagascar ?", "Le nickel (25 % de la valeur des exportations)."],
    ["Qu'est-ce que la balance commerciale ? Est-elle excédentaire ou déficitaire à Madagascar ?", "La différence entre exportations et importations ; déficitaire (environ −1,5 milliard de dollars en 2023)."],
    ["Citez deux clients et deux fournisseurs de Madagascar.", "Clients : France, États-Unis, Japon ; fournisseurs : Chine, Oman, France, Inde."],
    ["Pourquoi le pays importe-t-il du riz ?", "Parce que la production ne couvre pas les besoins, surtout pendant la soudure."],
  ],
  miseEnSituation: {
    enseignant: [
      "Un couple de touristes français débarque à Ivato en juillet. Pendant trois semaines, ils descendent la RN7 : les lémuriens du parc d'Andasibe, les rizières en terrasse du pays betsileo, le parc de l'Isalo, l'allée des Baobabs de Morondava, puis les plages d'Ifaty. À chaque étape, ils dorment à l'hôtel, mangent au restaurant, paient un guide et achètent des objets artisanaux.",
      "Qu'est-ce qui attire ces touristes à Madagascar ? Qui gagne de l'argent grâce à leur voyage ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : la nature unique (lémuriens, baobabs), les paysages, les plages, la culture ; les hôtels, restaurants, guides, chauffeurs, artisans, l'État."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Le tourisme à Madagascar | Données |", "| Arrivées de touristes étrangers | 2015 : 244 000 ; 2019 : 375 000 (record) ; 2020 : 63 000 (Covid-19) ; 2022 : 132 000 ; 2023 : 260 000 |", "| Origine des touristes (2023) | France 37 % ; Italie 13 % ; Réunion et Maurice ; Allemagne ; États-Unis ; Chine ; Royaume-Uni |", "| Ressources naturelles | 5 % des espèces du monde, dont 80 % ne vivent qu'à Madagascar (lémuriens, caméléons, baobabs) ; 43 parcs nationaux et réserves gérés par Madagascar National Parks ; Tsingy de Bemaraha et forêts de l'Atsinanana classés par l'UNESCO ; 5 000 km de côtes, récifs, baleines à Sainte-Marie |", "| Ressources culturelles | Colline royale d'Ambohimanga (UNESCO), pays zafimaniry, famadihana, marchés, artisanat, musique |", "| Principaux sites visités | Andasibe, Isalo, Ranomafana, Nosy Be, Sainte-Marie, allée des Baobabs, Tsingy, Ifaty, Anakao, Antananarivo |", "| Recettes et emplois | environ 700 à 900 millions de dollars en 2019 ; environ 45 000 emplois directs ; objectif de l'État : 1 million de touristes vers 2028 |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire tracer sur un croquis de l'île le circuit de la RN7 et placer Nosy Be et Sainte-Marie.",
  },
  analyse: [
    ["Qu'est-ce que le tourisme ?", "C'est l'ensemble des activités liées aux voyages que font les personnes hors de leur lieu de vie habituel, pour le plaisir, la découverte ou le repos, pendant au moins une nuit."],
    ["Quelle est la première richesse touristique de Madagascar ? Pourquoi est-elle unique ?", "La nature : 80 % des espèces animales et végétales de l'île n'existent nulle part ailleurs (endémisme) : lémuriens, caméléons, baobabs, orchidées ; on parle d'écotourisme."],
    ["Citez les principaux parcs et sites naturels visités.", "Andasibe-Mantadia (indri), Ranomafana, Isalo, l'allée des Baobabs de Morondava, les Tsingy de Bemaraha, Ankarafantsika, la Montagne d'Ambre, Masoala."],
    ["Quelles ressources offrent les côtes ?", "5 000 km de côtes : plages et plongée à Nosy Be, Sainte-Marie (baleines à bosse de juillet à septembre), Ifaty et Anakao (récif de Toliara), Diego-Suarez (mer d'Émeraude)."],
    ["Quelles sont les ressources culturelles ?", "La colline royale d'Ambohimanga (patrimoine mondial), le Rova d'Antananarivo, l'art zafimaniry, les traditions comme le famadihana, les marchés, l'artisanat, la musique et la gastronomie."],
    ["Comment ont évolué les arrivées de touristes ? Pourquoi ?", "Elles ont progressé jusqu'au record de 375 000 en 2019, se sont effondrées en 2020 avec la fermeture des frontières (Covid-19) et remontent depuis : 260 000 en 2023."],
    ["D'où viennent les touristes ? Comment l'expliquer ?", "Surtout de France (37 %) et d'Italie (13 %), puis de la Réunion, de Maurice, d'Allemagne, des États-Unis et de Chine ; les liens historiques et linguistiques avec la France et les vols directs expliquent cette domination."],
    ["Pourquoi Madagascar reçoit-elle si peu de touristes par rapport à Maurice (1,3 million) ou au Kenya (2 millions) ?", "À cause du prix élevé et de la rareté des vols, de l'état des routes, du manque d'hôtels de qualité, de l'insécurité, des crises politiques et des épidémies, et d'une promotion insuffisante."],
  ],
  analyseTechnique: "Lecture de tableau et de graphique, questions-réponses, croquis",
  synthese: "Donc, le tourisme est l'ensemble des activités liées aux voyages d'agrément et de découverte. Madagascar possède des ressources touristiques exceptionnelles : une nature unique au monde (lémuriens, baobabs, tsingy, parcs nationaux), 5 000 km de côtes avec des plages et des récifs (Nosy Be, Sainte-Marie, Ifaty) et un riche patrimoine culturel (Ambohimanga, art zafimaniry). Pourtant, les flux restent faibles : 375 000 touristes en 2019, 260 000 en 2023 après la crise du Covid-19, venus surtout de France et d'Italie. Le prix des vols, l'état des routes, le manque d'hôtels et l'insécurité limitent ces flux, alors que l'État vise un million de visiteurs.",
  application: [
    { consigne: "Classez les ressources touristiques suivantes en trois groupes (nature, plages et mer, culture) : lémuriens d'Andasibe – plages de Nosy Be – colline d'Ambohimanga – Tsingy de Bemaraha – baleines de Sainte-Marie – sculptures zafimaniry – allée des Baobabs – récif d'Ifaty.", pts: 4, items: [
      "Nature (écotourisme) : ……………",
      "Plages et mer (tourisme balnéaire) : ……………",
      "Culture : ……………",
      "Laquelle de ces ressources est classée au patrimoine mondial de l'UNESCO ?",
    ], corrige: [
      "Nature : **lémuriens d'Andasibe**, **Tsingy de Bemaraha**, **allée des Baobabs**.",
      "Plages et mer : **Nosy Be**, **baleines de Sainte-Marie**, **récif d'Ifaty**.",
      "Culture : **colline d'Ambohimanga**, **sculptures zafimaniry**.",
      "La **colline royale d'Ambohimanga** et les **Tsingy de Bemaraha** (ainsi que les forêts humides de l'Atsinanana).",
    ]},
    { consigne: "Lisez les données : arrivées de touristes : 2015 : 244 000 ; 2019 : 375 000 ; 2020 : 63 000 ; 2023 : 260 000.", pts: 4, items: [
      "1. Calculez l'augmentation entre 2015 et 2019.",
      "2. Que s'est-il passé en 2020 ? Pourquoi ?",
      "3. En 2023, le niveau de 2019 est-il retrouvé ?",
      "4. Quel objectif l'État s'est-il fixé ? Est-il réaliste selon vous ? Justifiez.",
    ], corrige: [
      "1. 375 000 − 244 000 = **131 000 touristes de plus** (environ +54 %).",
      "2. Une **chute** à 63 000 : la pandémie de **Covid-19** a fermé les frontières et les aéroports.",
      "3. **Non** : 260 000, soit environ 70 % du niveau de 2019.",
      "4. **1 million** de touristes vers 2028 ; c'est ambitieux : il faudrait **quadrupler** les arrivées, donc plus de **vols**, d'**hôtels**, de **routes** et de **sécurité**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) La majorité des espèces animales de Madagascar n'existent nulle part ailleurs.",
      "b) Les touristes viennent surtout de Chine.",
      "c) Madagascar reçoit plus de touristes que l'île Maurice.",
      "d) Sainte-Marie est connue pour l'observation des baleines.",
    ], corrige: [
      "a) **Vrai** : environ 80 % des espèces sont endémiques.",
      "b) **Faux** : surtout de **France** (37 %) et d'**Italie** (13 %).",
      "c) **Faux** : Maurice reçoit environ **1,3 million** de touristes, Madagascar **260 000** en 2023.",
      "d) **Vrai** : les baleines à bosse y viennent de juillet à septembre.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Définissez le tourisme et l'écotourisme.",
      "2. Présentez les trois types de ressources touristiques de Madagascar avec un exemple chacun.",
      "3. Décrivez l'évolution des arrivées de touristes depuis 2015 et expliquez-la.",
      "4. Donnez quatre raisons qui expliquent la faiblesse des flux touristiques vers Madagascar.",
    ], corrige: [
      "1. Le **tourisme** est l'ensemble des activités liées aux **voyages d'agrément** hors du lieu de vie habituel ; l'**écotourisme** est un tourisme de **découverte de la nature** qui respecte l'environnement et fait vivre les populations locales.",
      "2. **Nature** : parcs nationaux (Andasibe, Isalo, Tsingy) ; **plages et mer** : Nosy Be, Sainte-Marie, Ifaty ; **culture** : colline d'Ambohimanga, artisanat zafimaniry, traditions.",
      "3. **Hausse** de 244 000 (2015) à **375 000** (2019), **effondrement** à 63 000 en 2020 à cause du **Covid-19**, puis **reprise** progressive jusqu'à 260 000 en 2023.",
      "4. Le **prix** et la rareté des **vols** ; l'état des **routes** ; le manque d'**hôtels** de qualité ; l'**insécurité** et les **crises politiques** ; les **épidémies** (peste, Covid) ; une **promotion** insuffisante à l'étranger.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Le **tourisme** est l'ensemble des activités liées aux voyages que font les personnes hors de leur lieu de vie habituel, pour le plaisir, la découverte ou le repos. C'est un secteur du tertiaire qui fait travailler les transports, les hôtels, les restaurants, les guides et les artisans. Madagascar possède des atouts exceptionnels, mais reçoit encore peu de visiteurs." },
    { t: "h", x: "1. Des ressources touristiques exceptionnelles" },
    { t: "p", x: "La première richesse est la **nature**. Isolée depuis des millions d'années, l'île abrite environ 5 % des espèces vivantes de la planète, dont **80 % sont endémiques** : elles n'existent nulle part ailleurs. Les **lémuriens** (plus de 100 espèces), les caméléons, les **baobabs** (six espèces propres à l'île), les orchidées attirent les amateurs d'**écotourisme**. Ils se découvrent dans les **43 parcs nationaux et réserves** gérés par Madagascar National Parks : **Andasibe-Mantadia** (indri), **Ranomafana**, **Isalo** (canyons de grès), **Ankarafantsika**, Montagne d'Ambre, Masoala, et les **Tsingy de Bemaraha**, classés au patrimoine mondial de l'UNESCO avec les forêts humides de l'Atsinanana. L'**allée des Baobabs** de Morondava est l'image la plus célèbre du pays." },
    { t: "p", x: "Les **5 000 km de côtes** offrent un tourisme **balnéaire** : plages et plongée à **Nosy Be** (première destination), île **Sainte-Marie** (baleines à bosse de juillet à septembre), **Ifaty** et **Anakao** sur le grand récif de Toliara, baie de Diego-Suarez et mer d'Émeraude. Enfin, le **patrimoine culturel** est riche : la **colline royale d'Ambohimanga** (UNESCO), le Rova d'Antananarivo, l'art du bois des Zafimaniry, les rites comme le famadihana, les marchés, l'artisanat, la musique et la gastronomie." },
    { t: "h", x: "2. Des flux encore faibles" },
    { t: "p", x: "Les arrivées de touristes étrangers ont progressé de 244 000 en 2015 à un record de **375 000 en 2019**. La pandémie de **Covid-19** a fermé les frontières : 63 000 arrivées seulement en 2020. La reprise est progressive : 132 000 en 2022, environ **260 000 en 2023**. Les visiteurs viennent surtout de **France** (37 %), en raison des liens historiques et des vols directs, puis d'**Italie** (13 %), de la Réunion et de Maurice, d'Allemagne, des États-Unis, de Chine et du Royaume-Uni. Ils suivent principalement l'axe de la **RN7** (Antananarivo-Antsirabe-Fianarantsoa-Isalo-Toliara), Andasibe, Morondava, Nosy Be et Sainte-Marie. La haute saison va de juillet à octobre. Le tourisme rapportait avant la crise **700 à 900 millions de dollars** par an et emploie environ 45 000 personnes directement." },
    { t: "fig", file: "tourisme_arrivees.png", legende: "Évolution des arrivées de touristes étrangers à Madagascar (2015-2023) et origine des visiteurs en 2023", widthCm: 13, source: "réalisation J-Learn d'après le Ministère du Tourisme et l'ONTM (valeurs arrondies)" },
    { t: "h", x: "3. Pourquoi si peu de touristes ?" },
    { t: "p", x: "Madagascar reçoit cinq fois moins de touristes que l'île **Maurice** (1,3 million) et bien moins que le Kenya ou la Tanzanie. Les freins sont le **prix élevé** et le petit nombre des **vols** internationaux, l'état des **routes** qui allonge les trajets, le manque d'**hôtels** de qualité hors des grands sites, l'**insécurité** (vols, dahalo), les **crises politiques** et sanitaires (peste en 2017, Covid-19), et une **promotion** insuffisante à l'étranger. L'État s'est fixé l'objectif d'**un million de touristes** vers 2028 : il faudra pour cela ouvrir le ciel, améliorer les infrastructures et garantir la sécurité." },
  ],
},
// =====================================================================
{
  num: 26, theme: THEME,
  titre: "Le tourisme (2) : avantages et inconvénients pour Madagascar",
  objectif: "expliquer les avantages économiques, sociaux et environnementaux du tourisme pour Madagascar, d'en identifier les inconvénients et les risques, et de proposer les conditions d'un tourisme durable",
  documentation: `${DOC_PROG} ; Ministère du Tourisme et de l'Artisanat ; Madagascar National Parks, rapport sur les droits d'entrée et le partage des recettes ; Banque mondiale, Note sur le tourisme (2022) ; Organisation mondiale du tourisme, Code mondial d'éthique du tourisme.`,
  image: null,
  revision: [
    ["Quelles sont les trois types de ressources touristiques de Madagascar ?", "La nature (parcs, lémuriens, baobabs), les plages et la mer, la culture."],
    ["Combien de touristes Madagascar a-t-elle reçus en 2019 et en 2023 ?", "375 000 en 2019 ; environ 260 000 en 2023."],
    ["D'où viennent surtout les touristes ?", "De France (37 %) et d'Italie (13 %)."],
    ["Citez trois freins au tourisme malgache.", "Le prix des vols, l'état des routes, le manque d'hôtels, l'insécurité, les crises."],
  ],
  miseEnSituation: {
    enseignant: [
      "À Andasibe, depuis l'ouverture du parc aux touristes, Lalao est devenue guide et gagne mieux sa vie que dans les rizières ; son frère tient un petit hôtel et le village a reçu une école grâce aux droits d'entrée du parc. Mais à Nosy Be, les prix des terrains et de la nourriture ont beaucoup augmenté, certains jeunes ont abandonné l'école pour vendre des souvenirs sur la plage, et les récifs sont abîmés par les bateaux.",
      "Le tourisme apporte-t-il seulement des avantages ? Que faudrait-il faire pour garder les bienfaits et limiter les dégâts ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : non, il a des avantages (emplois, revenus, école) et des inconvénients (hausse des prix, abandon de l'école, dégradation) ; il faut organiser et contrôler le tourisme."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Avantages du tourisme | Inconvénients et risques |", "| Apport de devises : 700 à 900 millions de dollars par an avant 2020, deuxième source de devises après les mines | Fuite des devises : hôtels et compagnies aériennes souvent étrangers, produits importés pour les touristes |", "| Emplois : environ 45 000 emplois directs (hôtels, restaurants, guides, chauffeurs) et plus de 200 000 indirects (artisans, paysans, transporteurs) | Emplois saisonniers et souvent peu payés ; dépendance à l'égard des crises (Covid : des milliers d'emplois perdus) |", "| Recettes pour l'État et les communes : taxes, droits d'entrée des parcs (50 % reversés aux villages riverains par Madagascar National Parks) | Hausse des prix des terrains, des logements et de la nourriture dans les zones touristiques (Nosy Be) |", "| Protection de la nature : les parcs rapportent plus vivants que défrichés, les villageois deviennent gardiens de la forêt | Dégradation des sites : déchets, piétinement, récifs abîmés, dérangement des animaux |", "| Développement des infrastructures (routes, aéroports, électricité) et de l'artisanat ; ouverture culturelle, fierté du patrimoine | Atteintes sociales : tourisme sexuel, exploitation des enfants, abandon de l'école, perte des traditions, trafic d'espèces |"],
    support: "Tableau noir (tableau comparatif recopié)",
    note: "Faire lire les deux colonnes en parallèle, ligne par ligne : chaque avantage a un revers.",
  },
  analyse: [
    ["Quel est le premier avantage économique du tourisme ?", "Il apporte des devises : 700 à 900 millions de dollars par an avant la crise, ce qui en fait la deuxième source de devises du pays après les mines et aide à combler le déficit commercial."],
    ["Quels emplois le tourisme crée-t-il ?", "Des emplois directs (hôtels, restaurants, agences, guides, chauffeurs, pilotes) et de nombreux emplois indirects (artisans, paysans qui fournissent les hôtels, transporteurs, commerçants) : environ 45 000 directs et plus de 200 000 indirects."],
    ["Comment le tourisme aide-t-il à protéger la nature ?", "Les parcs nationaux rapportent de l'argent grâce aux visiteurs ; la moitié des droits d'entrée est reversée aux villages voisins pour des écoles, des puits ou des barrages : les paysans ont intérêt à protéger la forêt plutôt qu'à la brûler."],
    ["Quels autres avantages le tourisme apporte-t-il ?", "Il finance des routes, des aéroports et de l'électricité, fait vivre l'artisanat, fait connaître Madagascar dans le monde et renforce la fierté du patrimoine."],
    ["Qu'appelle-t-on la fuite des devises ?", "Une grande partie de l'argent dépensé par les touristes repart à l'étranger : compagnies aériennes, chaînes d'hôtels et agences étrangères, produits importés (boissons, aliments) consommés par les touristes."],
    ["Quels sont les inconvénients économiques et sociaux pour les habitants ?", "Les emplois sont souvent saisonniers et peu payés, les prix des terrains et de la nourriture montent, certains jeunes quittent l'école pour vivre du tourisme, et des fléaux comme le tourisme sexuel ou l'exploitation des enfants apparaissent, surtout à Nosy Be."],
    ["Quels dégâts le tourisme peut-il causer à l'environnement ?", "Déchets, piétinement des sentiers, récifs abîmés par les ancres et les plongeurs, dérangement des animaux, constructions sur le littoral, trafic d'espèces protégées (tortues, caméléons)."],
    ["Qu'est-ce qu'un tourisme durable ? Que faut-il faire pour l'atteindre ?", "Un tourisme qui profite aux populations locales sans détruire la nature ni la culture : limiter le nombre de visiteurs dans les sites fragiles, former et employer des Malgaches, acheter local, faire respecter les lois contre le tourisme sexuel, recycler les déchets, développer les hôtels appartenant aux communautés."],
  ],
  analyseTechnique: "Lecture de tableau comparatif, débat guidé, questions-réponses",
  synthese: "Donc, le tourisme est une chance pour Madagascar : il apporte des devises (deuxième source après les mines), crée des dizaines de milliers d'emplois directs et indirects, finance l'État et les communes, fait vivre l'artisanat et encourage la protection des parcs nationaux. Mais il présente aussi des inconvénients : une partie des devises repart à l'étranger, les emplois sont fragiles et saisonniers, les prix montent dans les zones touristiques, des dérives sociales apparaissent et les sites naturels peuvent se dégrader. L'avenir est un tourisme durable, qui profite aux Malgaches tout en protégeant leur nature et leur culture.",
  application: [
    { consigne: "Classez les faits suivants en avantages ou inconvénients du tourisme, puis répondez.", pts: 4, items: [
      "1. Le village d'Andasibe a reçu une école grâce aux droits d'entrée du parc.",
      "2. Les récifs d'Ifaty sont abîmés par les ancres des bateaux de touristes.",
      "3. Une brodeuse d'Antsirabe vend ses nappes aux touristes de la RN7.",
      "4. Le prix du poisson a doublé à Nosy Be car les hôtels achètent tout.",
    ], corrige: [
      "1. **Avantage** (recettes reversées aux communautés, protection de la forêt).",
      "2. **Inconvénient** (dégradation de l'environnement).",
      "3. **Avantage** (emplois indirects, artisanat).",
      "4. **Inconvénient** (hausse des prix pour les habitants).",
    ]},
    { consigne: "Pour chaque problème, proposez une mesure de tourisme durable.", pts: 4, items: [
      "1. Trop de visiteurs piétinent les sentiers des Tsingy.",
      "2. Les hôtels de Nosy Be importent leurs légumes et leurs boissons.",
      "3. Des enfants abandonnent l'école pour vendre des coquillages sur la plage.",
      "4. Les déchets plastiques s'accumulent sur les plages de Sainte-Marie.",
    ], corrige: [
      "1. **Limiter** le nombre de visiteurs par jour et baliser les sentiers.",
      "2. Créer des **coopératives** de paysans locaux qui fournissent les hôtels.",
      "3. Faire respecter l'**école obligatoire**, interdire le travail des enfants, sensibiliser les touristes à ne pas acheter aux enfants.",
      "4. Organiser la **collecte et le recyclage**, interdire les sacs plastiques, faire payer une taxe environnementale.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Le tourisme est la deuxième source de devises de Madagascar.",
      "b) Tout l'argent dépensé par les touristes reste à Madagascar.",
      "c) La moitié des droits d'entrée des parcs nationaux est reversée aux villages voisins.",
      "d) Le tourisme durable consiste à recevoir le plus de touristes possible.",
    ], corrige: [
      "a) **Vrai** : après les mines (avant la crise du Covid).",
      "b) **Faux** : une grande partie **repart à l'étranger** (compagnies aériennes, hôtels, produits importés).",
      "c) **Vrai** : pour des écoles, des puits, des pistes.",
      "d) **Faux** : c'est un tourisme qui **profite aux habitants** et **protège la nature et la culture**, même s'il faut parfois limiter les visiteurs.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Citez trois avantages économiques du tourisme pour Madagascar.",
      "2. Expliquez comment le tourisme peut contribuer à protéger la nature malgache.",
      "3. Présentez deux inconvénients sociaux et deux inconvénients environnementaux du tourisme.",
      "4. Définissez le tourisme durable et proposez trois conditions pour le réaliser à Madagascar.",
    ], corrige: [
      "1. Il apporte des **devises** (700 à 900 millions de dollars), crée des **emplois** directs et indirects, rapporte des **taxes** à l'État et aux communes, fait vivre l'**artisanat** et finance des **infrastructures**.",
      "2. Les **parcs** rapportent de l'argent grâce aux visiteurs et la **moitié des droits d'entrée** revient aux villages : les habitants ont **intérêt à protéger** la forêt et les animaux plutôt qu'à les détruire ; ils deviennent guides et gardiens.",
      "3. Sociaux : **hausse des prix** pour les habitants, **abandon de l'école**, tourisme sexuel, perte des traditions. Environnementaux : **déchets**, **récifs** abîmés, piétinement des sites, dérangement des animaux, trafic d'espèces.",
      "4. Un tourisme qui **profite aux populations locales** sans **détruire la nature ni la culture**. Conditions : **former et employer** des Malgaches, **acheter local**, **limiter** l'accès aux sites fragiles, **faire respecter** les lois, gérer les **déchets**, associer les **communautés** aux décisions et aux bénéfices.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Le tourisme est souvent présenté comme une chance pour Madagascar. Il apporte en effet de nombreux avantages, mais il comporte aussi des inconvénients et des risques qu'il faut connaître pour construire un tourisme durable." },
    { t: "h", x: "1. Les avantages du tourisme" },
    { t: "ul", x: [
      "**Des devises** : avant la crise du Covid-19, le tourisme rapportait **700 à 900 millions de dollars** par an, ce qui en faisait la **deuxième source de devises** du pays après les mines ; ces devises aident à payer les importations et à réduire le déficit commercial.",
      "**Des emplois** : environ **45 000 emplois directs** (hôtels, restaurants, agences, guides, chauffeurs) et plus de **200 000 emplois indirects** (artisans, paysans et pêcheurs qui fournissent les hôtels, transporteurs, commerçants) ; beaucoup sont occupés par des jeunes et des femmes.",
      "**Des recettes pour l'État et les communes** : taxes, visas, droits d'entrée des parcs ; Madagascar National Parks reverse **la moitié** des droits d'entrée aux villages riverains (écoles, puits, pistes, barrages).",
      "**La protection de la nature** : une forêt visitée rapporte plus qu'une forêt brûlée ; les villageois deviennent guides et gardiens des parcs, et les touristes financent la conservation des lémuriens et des récifs.",
      "**Le développement** : construction de routes, d'aéroports, d'hôtels, arrivée de l'électricité et de l'eau ; essor de l'**artisanat** ; rayonnement de Madagascar dans le monde et fierté du patrimoine.",
    ]},
    { t: "h", x: "2. Les inconvénients et les risques" },
    { t: "ul", x: [
      "**La fuite des devises** : une grande partie de l'argent dépensé par les touristes repart à l'étranger, car les compagnies aériennes, les grandes agences et de nombreux hôtels appartiennent à des étrangers et importent boissons, aliments et équipements.",
      "**Des emplois fragiles** : saisonniers (juillet-octobre), souvent peu payés, et très sensibles aux crises : en 2020, la fermeture des frontières a mis au chômage des dizaines de milliers de personnes.",
      "**La hausse des prix** des terrains, des logements et de la nourriture dans les zones touristiques (Nosy Be, Sainte-Marie), qui pénalise les habitants.",
      "**Des atteintes sociales** : tourisme sexuel et exploitation des enfants (surtout à Nosy Be), abandon de l'école par des jeunes attirés par les petits gains, mendicité, perte des traditions transformées en spectacle.",
      "**La dégradation de l'environnement** : déchets plastiques, piétinement des sentiers, récifs abîmés par les ancres et les plongeurs, dérangement des animaux, constructions illégales sur le littoral, trafic d'espèces protégées (tortues, caméléons, orchidées).",
    ]},
    { t: "h", x: "3. Vers un tourisme durable" },
    { t: "p", x: "Le **tourisme durable** est un tourisme qui profite aux populations locales sans détruire la nature ni la culture, aujourd'hui et pour les générations futures. À Madagascar, il suppose de **former et d'employer** des Malgaches à tous les niveaux, d'**acheter local** (coopératives de paysans et de pêcheurs fournissant les hôtels), de **limiter** le nombre de visiteurs dans les sites fragiles, de **faire respecter** les lois contre le tourisme sexuel et le trafic d'espèces, de gérer les **déchets**, et d'associer les **communautés** villageoises aux décisions et aux bénéfices, comme le font déjà l'écotourisme communautaire d'Anja (Ambalavao) ou les réserves gérées par les villageois. C'est à ces conditions que l'objectif d'un million de touristes pourra être une réussite pour tous les Malgaches." },
  ],
},
];
