// UNITÉ 1 — Les conditions et les caractères de l'économie malagasy (6 séances)
// Sources citées dans la bibliographie (voir data-annexes.js). Mots-clés de leçon entre **…** (bleu) ; mots-clés de corrigé entre **…** (saumon).
const THEME = "Les conditions et les caractères de l'économie malagasy";
const DOC_PROG = "Programme scolaire de la classe de 3ème, Géographie (MEN/DCI, édition 2015)";

module.exports = [
// =====================================================================
{
  num: 1, theme: THEME,
  titre: "Les régions naturelles de Madagascar : le Nord et l'Est",
  objectif: "décrire les conditions naturelles (relief, climat, végétation, cours d'eau) du Nord et de l'Est de Madagascar et de citer leurs principaux potentiels économiques",
  documentation: `${DOC_PROG} ; Atlas de Madagascar (FTM) ; Direction Générale de la Météorologie.`,
  image: { file: "carte_regions_naturelles.png", legende: "Carte schématique des cinq grandes régions naturelles de Madagascar", widthCm: 11, source: "réalisation J-Learn d'après l'Atlas de Madagascar (FTM)" },
  revision: [
    ["Dans quel océan se trouve Madagascar ?", "Madagascar se trouve dans l'océan Indien, au sud-ouest, séparée de l'Afrique par le canal de Mozambique."],
    ["Quelle est la superficie approximative de Madagascar ?", "Environ 587 000 km² : c'est la quatrième plus grande île du monde."],
    ["Citez deux types de climat que l'on peut rencontrer à Madagascar.", "Le climat tropical humide et le climat tropical sec (ou le climat semi-aride, ou le climat tropical d'altitude)."],
    ["Qu'appelle-t-on une région naturelle ?", "Un espace qui présente les mêmes caractères physiques : relief, climat, végétation, cours d'eau."],
  ],
  miseEnSituation: {
    enseignant: [
      "Hery habite à Antalaha, sur la côte Est. Chaque année, entre janvier et mars, sa famille surveille la radio : un cyclone peut arriver et détruire les plants de vanille. Sa cousine Fara, qui vit à Ambanja dans le Nord, récolte au même moment le cacao et les fleurs d'ylang-ylang.",
      "À votre avis, pourquoi ces deux régions ne produisent-elles pas les mêmes choses ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : parce que le climat, le relief et les pluies ne sont pas les mêmes ; chaque région a ses propres conditions naturelles."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Région | Relief | Pluies par an | Saison sèche | Végétation |", "| Nord | massif du Tsaratanana (2 876 m), montagne d'Ambre, plaines du Sambirano | 1 500 à 2 000 mm (plus dans le Sambirano) | 5 à 6 mois | forêt humide, savane |", "| Est | étroite plaine côtière, falaise, canal des Pangalanes | 2 000 à plus de 3 500 mm | presque aucune | forêt dense humide |"],
    support: "Tableau noir (tableau comparatif recopié)",
    note: "Faire remarquer la colonne « Pluies par an » : l'Est est la région la plus arrosée de l'île.",
  },
  analyse: [
    ["Quel est le point culminant de Madagascar et dans quelle région se trouve-t-il ?", "Le Maromokotro, dans le massif du Tsaratanana, qui culmine à 2 876 mètres, dans le Nord."],
    ["Comment se présente le relief de l'Est ?", "Une plaine côtière étroite, longue et régulière, dominée à l'ouest par une falaise abrupte qui monte vers les Hautes Terres."],
    ["Laquelle des deux régions reçoit le plus de pluie ? Pourquoi ?", "L'Est, car il est exposé toute l'année à l'alizé, un vent humide venu de l'océan Indien qui se décharge en pluie contre la falaise."],
    ["Quel phénomène climatique menace surtout la côte Est entre janvier et mars ?", "Les cyclones tropicaux, qui apportent des vents violents et des inondations."],
    ["Quelle est la végétation naturelle de l'Est ? Qu'est-ce qui la menace ?", "La forêt dense humide ; elle est menacée par le tavy (culture sur brûlis) et les coupes de bois."],
    ["Citez trois cultures d'exportation de l'Est et deux cultures du Nord.", "Est : la vanille (région SAVA), le girofle (Analanjirofo), le café et le litchi. Nord : le cacao et l'ylang-ylang du Sambirano, ainsi que le poivre et la canne à sucre."],
    ["Quel port se trouve sur la côte Est et quel est son rôle ?", "Toamasina, le premier port du pays : la majorité des importations et des exportations de Madagascar y passent."],
    ["Quels sont les atouts touristiques du Nord ?", "La baie d'Antsiranana, l'île de Nosy Be et ses plages, la montagne d'Ambre et les tsingy de l'Ankarana."],
  ],
  synthese: "Donc, le Nord est une région de montagnes (Tsaratanana) et de plaines chaudes comme le Sambirano ; son potentiel repose sur les cultures riches (cacao, ylang-ylang, canne à sucre), la pêche et le tourisme (Nosy Be, Antsiranana). L'Est est une étroite plaine côtière très arrosée, couverte de forêt dense humide et exposée aux cyclones ; c'est la grande région des cultures d'exportation (vanille, girofle, café, litchi) et elle abrite Toamasina, le premier port du pays.",
  application: [
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. Le massif du Tsaratanana se trouve : A) dans l'Est — B) dans le Nord — C) sur les Hautes Terres.",
      "2. La région la plus arrosée de Madagascar est : A) le Nord — B) l'Est — C) le Sambirano.",
      "3. Le cacao et l'ylang-ylang sont surtout cultivés : A) dans la plaine du Sambirano — B) dans la région SAVA — C) autour de Toamasina.",
      "4. Le canal des Pangalanes longe : A) la côte Nord — B) la côte Ouest — C) la côte Est.",
    ], corrige: [
      "1. **B)** dans le Nord : le Tsaratanana, avec le Maromokotro (2 876 m), est le point culminant de l'île.",
      "2. **B)** l'Est, qui reçoit de 2 000 à plus de 3 500 mm de pluie par an grâce à l'alizé.",
      "3. **A)** dans la plaine du Sambirano, près d'Ambanja, dans le Nord.",
      "4. **C)** la côte Est : c'est une suite de lagunes et de canaux parallèles à l'océan.",
    ]},
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) L'Est de Madagascar connaît une longue saison sèche de six mois.",
      "b) La vanille est surtout produite dans la région SAVA, au Nord-Est.",
      "c) Toamasina est le premier port de Madagascar.",
      "d) La forêt dense humide de l'Est n'est menacée par aucune activité humaine.",
    ], corrige: [
      "a) **Faux** : l'Est n'a presque pas de saison sèche, il pleut toute l'année.",
      "b) **Vrai** : Sambava, Antalaha, Vohémar et Andapa forment la région de la vanille.",
      "c) **Vrai** : la plus grande partie du commerce extérieur passe par Toamasina.",
      "d) **Faux** : elle est menacée par le **tavy** (culture sur brûlis) et les coupes de bois.",
    ]},
  ],
  evaluation: [
    { consigne: "Complétez le texte avec les mots proposés : alizé – cyclones – Tsaratanana – vanille – Toamasina – Nosy Be.", pts: 6, items: [
      "Le Nord de Madagascar est dominé par le massif du ……………… . L'île de ……………… attire de nombreux touristes. L'Est reçoit des pluies abondantes apportées par l'……………… et il est frappé chaque année par des ……………… . On y cultive la ……………… et le port de ……………… exporte les produits de toute l'île.",
    ], corrige: [
      "Le Nord de Madagascar est dominé par le massif du **Tsaratanana**. L'île de **Nosy Be** attire de nombreux touristes. L'Est reçoit des pluies abondantes apportées par l'**alizé** et il est frappé chaque année par des **cyclones**. On y cultive la **vanille** et le port de **Toamasina** exporte les produits de toute l'île.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Pourquoi l'Est reçoit-il plus de pluie que le Nord ?",
      "2. Citez deux conséquences des cyclones pour les habitants de la côte Est.",
      "3. Quels sont les deux principaux potentiels économiques du Nord ?",
      "4. Pourquoi peut-on dire que Toamasina est « la porte de Madagascar » ?",
    ], corrige: [
      "1. Parce que l'Est est exposé toute l'année à l'**alizé**, vent humide de l'océan Indien qui se décharge en pluie contre la **falaise** de l'Est.",
      "2. Les cyclones provoquent des **inondations**, détruisent les **maisons**, les **routes** et les **cultures** (vanille, riz, girofle).",
      "3. Les **cultures riches** de la plaine du Sambirano (cacao, ylang-ylang, canne à sucre) et le **tourisme** (Nosy Be, baie d'Antsiranana), auxquels s'ajoute la pêche.",
      "4. Parce que c'est le **premier port** du pays : la majorité des marchandises importées et exportées passent par Toamasina.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Madagascar s'étend sur environ 1 600 km du nord au sud et présente des paysages très variés. On distingue **cinq grandes régions naturelles** : le Nord, l'Est, l'Ouest, le Sud et les Hautes Terres Centrales. Une **région naturelle** est un espace dont le relief, le climat, la végétation et les cours d'eau présentent les mêmes caractères. Cette séance étudie le Nord et l'Est." },
    { t: "h", x: "1. La région Nord" },
    { t: "hh", x: "a) Les conditions naturelles" },
    { t: "p", x: "Le Nord est une région de **montagnes** : le massif du **Tsaratanana** porte le point culminant de l'île, le **Maromokotro** (2 876 m), et la **montagne d'Ambre**, ancien volcan, domine la ville d'Antsiranana. Entre les massifs s'ouvrent des plaines chaudes et bien arrosées comme la plaine du **Sambirano**, autour d'Ambanja. Le climat est tropical avec une saison sèche de cinq à six mois ; les pluies (1 500 à 2 000 mm par an) sont plus abondantes dans le Sambirano, protégé des vents secs. La végétation va de la forêt humide sur les montagnes à la savane dans les plaines. Les côtes sont découpées : la **baie d'Antsiranana** est l'une des plus belles rades du monde." },
    { t: "hh", x: "b) Les potentiels économiques" },
    { t: "ul", x: [
      "Des **cultures riches** : le **cacao**, l'**ylang-ylang** (fleur utilisée en parfumerie), le café, le poivre et la canne à sucre du Sambirano et de Nosy Be.",
      "La **pêche** en mer (poissons, crevettes) et l'élevage dans les plaines.",
      "Le **tourisme** : l'île de **Nosy Be**, la baie d'Antsiranana, la montagne d'Ambre et les **tsingy** de l'Ankarana.",
      "Le port d'Antsiranana, qui possède un chantier naval.",
    ]},
    { t: "h", x: "2. La région Est" },
    { t: "hh", x: "a) Les conditions naturelles" },
    { t: "p", x: "L'Est est une **étroite plaine côtière**, longue et régulière, large de 20 à 50 km seulement. Elle est dominée à l'ouest par une **falaise** abrupte qui monte vers les Hautes Terres. Le long de la côte, une suite de lagunes forme le **canal des Pangalanes**, voie navigable de plus de 600 km. L'Est reçoit toute l'année l'**alizé**, vent humide venu de l'océan Indien : c'est la région la plus arrosée de Madagascar (2 000 à plus de 3 500 mm de pluie par an, sans véritable saison sèche). Le climat est chaud et humide. Entre janvier et mars, la côte est frappée par des **cyclones** qui provoquent inondations et destructions. La végétation naturelle est la **forêt dense humide**, riche en espèces rares, mais menacée par le **tavy** (culture sur brûlis) et les coupes de bois." },
    { t: "hh", x: "b) Les potentiels économiques" },
    { t: "ul", x: [
      "Les **cultures d'exportation** : la **vanille** de la région SAVA (Sambava, Antalaha, Vohémar, Andapa), le **girofle** de la région Analanjirofo (Fénérive-Est), le **café**, le **litchi** et le poivre.",
      "Les cultures vivrières : riz, manioc, banane, fruits.",
      "Le **port de Toamasina**, premier port du pays, relié à Antananarivo par la route nationale 2 et le chemin de fer : la majorité du commerce extérieur y transite.",
      "Les ressources de la forêt (bois précieux, plantes médicinales) et le tourisme (île Sainte-Marie, parc d'Andasibe).",
    ]},
    { t: "h", x: "3. Des atouts et des contraintes" },
    { t: "p", x: "Le Nord et l'Est possèdent des **atouts** : des pluies abondantes, des sols fertiles, des produits recherchés sur le marché mondial. Mais ils connaissent aussi des **contraintes** : l'enclavement de nombreuses zones (routes coupées pendant la saison des pluies), la violence des cyclones, l'érosion et le recul de la forêt. Le développement de ces régions dépend donc de la protection de leur milieu naturel et de l'amélioration des voies de communication." },
  ],
},
// =====================================================================
{
  num: 2, theme: THEME,
  titre: "Les régions naturelles de Madagascar : l'Ouest et le Sud",
  objectif: "décrire les conditions naturelles de l'Ouest et du Sud de Madagascar, d'expliquer le problème de la sécheresse dans le Sud et de citer les potentiels économiques de ces deux régions",
  documentation: `${DOC_PROG} ; Atlas de Madagascar (FTM) ; BNGRC et PAM, rapports sur la sécheresse dans le Grand Sud.`,
  image: null,
  revision: [
    ["Quelle est la région la plus arrosée de Madagascar ?", "L'Est, qui reçoit plus de 2 000 mm de pluie par an."],
    ["Quel vent apporte la pluie sur la côte Est ?", "L'alizé, vent humide venu de l'océan Indien."],
    ["Citez deux produits d'exportation de l'Est et deux du Nord.", "Est : vanille, girofle (ou café, litchi). Nord : cacao, ylang-ylang."],
    ["Quel est le premier port de Madagascar ?", "Toamasina, sur la côte Est."],
  ],
  miseEnSituation: {
    enseignant: [
      "Dans le Sud, à Ambovombe, la famille de Soa a dû vendre deux zébus pour acheter du maïs et de l'eau, car il n'a presque pas plu depuis deux ans : c'est le kere, la famine causée par la sécheresse. Au même moment, dans l'Ouest, à Morondava, les rizières de la plaine sont inondées par la crue du fleuve.",
      "À votre avis, quelle est la grande différence entre l'Ouest et le Sud de Madagascar ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : la quantité de pluie ; l'Ouest a une saison des pluies avec de grands fleuves, le Sud manque d'eau."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Région | Relief | Pluies par an | Saison sèche | Végétation | Grands cours d'eau |", "| Ouest | vastes plaines et plateaux sédimentaires | 500 à 1 500 mm | 6 à 8 mois | savane, baobabs, mangroves | Betsiboka, Tsiribihina, Mangoky |", "| Sud | plateaux calcaires, plaine côtière du Mahafaly et de l'Androy | moins de 500 mm | 9 à 11 mois | bush épineux (fourré xérophile) | Onilahy, Mandrare (souvent à sec) |"],
    support: "Tableau noir (tableau comparatif recopié)",
    note: "Insister sur la ligne « Sud » : moins de 500 mm et des fleuves souvent à sec — c'est la cause du kere.",
  },
  analyse: [
    ["Comment se présente le relief de l'Ouest ?", "De vastes plaines et de larges plateaux en pente douce vers le canal de Mozambique, formés de roches sédimentaires (grès, calcaires)."],
    ["Quels sont les grands fleuves de l'Ouest ? Que déposent-ils à leur embouchure ?", "La Betsiboka, la Tsiribihina et le Mangoky ; ils déposent des alluvions rouges (la latérite arrachée aux Hautes Terres) qui forment des deltas fertiles."],
    ["Décrivez le climat de l'Ouest.", "Un climat tropical sec : une saison des pluies courte (novembre à mars) et une longue saison sèche de six à huit mois."],
    ["Quelle végétation caractérise l'Ouest ?", "La savane à hautes herbes, parsemée de baobabs et de palmiers, et les mangroves le long des côtes."],
    ["Pourquoi le Sud reçoit-il si peu de pluie ?", "Parce qu'il est protégé de l'alizé par les Hautes Terres et qu'il se trouve loin des zones de passage des cyclones : les masses d'air y arrivent déjà sèches."],
    ["Qu'est-ce que le kere ?", "C'est la famine qui frappe le Grand Sud quand les pluies manquent plusieurs années de suite : les récoltes de maïs et de manioc sont perdues."],
    ["Quelle végétation s'est adaptée à la sécheresse du Sud ?", "Le bush épineux ou fourré xérophile : plantes grasses, didiereas, euphorbes, cactus, qui stockent l'eau."],
    ["Citez deux richesses économiques de l'Ouest et deux du Sud.", "Ouest : l'élevage bovin, le riz de la plaine de Marovoay, le coton, le tabac, la pêche à Mahajanga. Sud : l'élevage de zébus et de chèvres, le sisal d'Amboasary, la pêche des Vezo, les mines (ilménite de Taolagnaro, saphirs d'Ilakaka)."],
  ],
  synthese: "Donc, l'Ouest est une région de vastes plaines sédimentaires au climat tropical sec, traversée par de grands fleuves (Betsiboka, Tsiribihina, Mangoky) qui fertilisent des deltas : c'est le pays de la savane, des baobabs, de l'élevage bovin et du riz de Marovoay. Le Sud est la région la plus sèche de Madagascar (moins de 500 mm) : son bush épineux, ses élevages de zébus et de chèvres, son sisal, sa pêche et ses mines coexistent avec la menace permanente du kere, la famine due à la sécheresse.",
  application: [
    { consigne: "Reliez chaque élément de la colonne A à l'élément qui lui correspond dans la colonne B.", pts: 4, items: [
      "Colonne A : 1. Betsiboka ; 2. Bush épineux ; 3. Marovoay ; 4. Kere ; 5. Baobab",
      "Colonne B : a) famine causée par la sécheresse ; b) grande plaine rizicole de l'Ouest ; c) arbre typique de la savane de l'Ouest ; d) fleuve de l'Ouest aux eaux rouges ; e) végétation adaptée au Sud sec",
    ], corrige: [
      "1 → **d)** la Betsiboka est le grand fleuve de l'Ouest, qui se jette près de Mahajanga.",
      "2 → **e)** le bush épineux est la végétation du Sud adaptée au manque d'eau.",
      "3 → **b)** Marovoay est la grande plaine rizicole de l'Ouest, près de Mahajanga.",
      "4 → **a)** le kere est la famine du Grand Sud due à la sécheresse.",
      "5 → **c)** le baobab est l'arbre typique de la savane de l'Ouest (allée des baobabs de Morondava).",
    ]},
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. La saison sèche de l'Ouest dure : A) 2 à 3 mois — B) 6 à 8 mois — C) toute l'année.",
      "2. Le Sud reçoit chaque année : A) moins de 500 mm de pluie — B) environ 1 500 mm — C) plus de 2 000 mm.",
      "3. Le sisal est cultivé surtout : A) autour d'Amboasary, dans le Sud — B) dans la plaine de Marovoay — C) près de Mahajanga.",
      "4. Les Vezo sont : A) des éleveurs de l'Ouest — B) des pêcheurs de la côte Sud-Ouest — C) des cultivateurs de riz.",
    ], corrige: [
      "1. **B)** 6 à 8 mois : la pluie ne tombe que de novembre à mars.",
      "2. **A)** moins de 500 mm : le Sud est la région la plus sèche de l'île.",
      "3. **A)** autour d'Amboasary, dans la vallée du Mandrare.",
      "4. **B)** des pêcheurs de la côte Sud-Ouest, autour de Toliara.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Les fleuves de l'Ouest transportent des alluvions rouges venues des Hautes Terres.",
      "b) Le Sud est protégé de la sécheresse par les cyclones.",
      "c) Les mangroves poussent le long des côtes de l'Ouest.",
      "d) Le kere touche surtout les habitants de la plaine de Marovoay.",
    ], corrige: [
      "a) **Vrai** : la Betsiboka est célèbre pour ses eaux rouges chargées de latérite.",
      "b) **Faux** : le Sud est à l'abri de l'alizé et des cyclones, c'est pour cela qu'il est **sec**.",
      "c) **Vrai** : les mangroves bordent les estuaires et les baies de la côte Ouest.",
      "d) **Faux** : le kere frappe le **Grand Sud** (Androy, Anosy, Atsimo-Andrefana), pas l'Ouest bien arrosé par ses fleuves.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Expliquez pourquoi le Sud de Madagascar est la région la plus sèche de l'île.",
      "2. Quelles sont les conséquences du kere pour les habitants du Sud ?",
      "3. Citez trois potentiels économiques de l'Ouest.",
      "4. Proposez deux solutions pour aider les habitants du Sud à lutter contre la sécheresse.",
    ], corrige: [
      "1. Le Sud est **protégé de l'alizé** par les Hautes Terres et se trouve **hors de la trajectoire des cyclones** : les masses d'air y arrivent sèches, d'où des pluies inférieures à **500 mm** par an.",
      "2. Les **récoltes** de maïs et de manioc sont perdues, les habitants souffrent de **faim** et de **malnutrition**, ils vendent leur bétail et beaucoup **migrent** vers d'autres régions.",
      "3. L'**élevage bovin** extensif, la **riziculture** des plaines (Marovoay), les cultures de **coton** et de tabac, la **pêche** et le tourisme (baobabs de Morondava, tsingy de Bemaraha).",
      "4. Construire des **puits**, des **barrages** et des canalisations d'eau ; développer des **cultures résistantes** à la sécheresse (sorgho, manioc amélioré) ; planter des arbres pour freiner l'avancée du sable.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Après le Nord et l'Est, nous étudions les deux régions de la façade occidentale de Madagascar : l'Ouest et le Sud. Elles ont en commun une longue **saison sèche**, mais le Sud souffre d'un manque d'eau bien plus grave." },
    { t: "h", x: "1. La région Ouest" },
    { t: "hh", x: "a) Les conditions naturelles" },
    { t: "p", x: "L'Ouest est formé de **vastes plaines** et de larges **plateaux sédimentaires** (grès, calcaires) qui descendent en pente douce vers le canal de Mozambique. Les côtes sont basses et bordées de **mangroves**. De grands fleuves nés sur les Hautes Terres la traversent : la **Betsiboka**, la **Tsiribihina** et le **Mangoky**. Ils charrient des alluvions rouges (la latérite arrachée aux Hautes Terres) et forment à leur embouchure des **deltas** fertiles. Le climat est **tropical sec** : la saison des pluies est courte (novembre à mars) et la saison sèche dure six à huit mois ; les pluies diminuent du nord (1 500 mm à Mahajanga) vers le sud (500 mm à Morombe). La végétation dominante est la **savane** à hautes herbes, parsemée de **baobabs** et de palmiers ; les feux de brousse la parcourent chaque année." },
    { t: "hh", x: "b) Les potentiels économiques" },
    { t: "ul", x: [
      "L'**élevage bovin extensif** : les grands troupeaux de zébus du Boina, du Menabe et du Melaky.",
      "La **riziculture** dans les plaines alluviales : la plaine de **Marovoay**, près de Mahajanga, est l'un des greniers à riz du pays.",
      "Les cultures industrielles : **coton**, **tabac**, arachide, canne à sucre.",
      "La **pêche** (crevettes, poissons) et le port de **Mahajanga**, deuxième port du pays.",
      "Le **tourisme** : l'allée des baobabs de Morondava, les **tsingy de Bemaraha**, classés au patrimoine mondial.",
      "Les ressources du sous-sol : pétrole lourd de Tsimiroro et Bemolanga, charbon de la Sakoa (encore peu exploités).",
    ]},
    { t: "h", x: "2. La région Sud" },
    { t: "hh", x: "a) Les conditions naturelles" },
    { t: "p", x: "Le Sud comprend des plateaux calcaires (plateau Mahafaly) et une plaine côtière sableuse (l'**Androy**). Il est protégé de l'alizé par les Hautes Terres et se trouve loin de la trajectoire des cyclones : c'est la région la plus **sèche** de Madagascar, avec moins de **500 mm** de pluie par an et une saison sèche de neuf à onze mois. Les cours d'eau (Onilahy, Mandrare, Menarandra) sont souvent à sec. La végétation s'est adaptée au manque d'eau : c'est le **bush épineux** ou fourré xérophile (didiereas, euphorbes, cactus, plantes grasses qui stockent l'eau)." },
    { t: "hh", x: "b) Le problème de la sécheresse : le kere" },
    { t: "p", x: "Quand les pluies manquent plusieurs années de suite, les récoltes de maïs, de manioc et de patate douce sont perdues : c'est le **kere**, la famine du Grand Sud. Les habitants vendent leurs zébus, souffrent de malnutrition et migrent vers d'autres régions. Le vent soulève aussi le sable (le tiomena) qui recouvre les champs. Les solutions passent par l'eau (puits, barrages, canalisations comme le pipeline d'Ampotaka), par des cultures résistantes (sorgho, manioc amélioré) et par le reboisement." },
    { t: "hh", x: "c) Les potentiels économiques" },
    { t: "ul", x: [
      "L'**élevage** de zébus, de chèvres et de moutons, très important dans la vie des Antandroy et des Mahafaly.",
      "Le **sisal** de la vallée du Mandrare (Amboasary), utilisé pour les cordes et les sacs.",
      "La **pêche** des **Vezo** sur la côte Sud-Ouest, autour de Toliara.",
      "Les **mines** : l'ilménite de Taolagnaro (société QMM), les saphirs d'Ilakaka.",
      "Le **tourisme** : le massif de l'Isalo, les plages d'Anakao et d'Ifaty, le récif de Toliara.",
    ]},
    { t: "h", x: "3. À retenir : deux régions, deux défis" },
    { t: "p", x: "L'Ouest dispose d'espace et d'eau grâce à ses fleuves, mais reste peu peuplé et mal desservi par les routes : son défi est la **mise en valeur** des plaines. Le Sud dispose de ressources (bétail, mines, pêche), mais son défi majeur est la **maîtrise de l'eau** pour vaincre le kere." },
  ],
},
// =====================================================================
{
  num: 3, theme: THEME,
  titre: "Les Hautes Terres Centrales et la comparaison des cinq régions naturelles",
  objectif: "décrire les conditions naturelles et les potentiels des Hautes Terres Centrales, de comparer les cinq régions naturelles à l'aide d'un tableau et d'établir le lien entre régions naturelles et découpage administratif",
  documentation: `${DOC_PROG} ; Atlas de Madagascar (FTM) ; Loi n° 2004-001 relative aux régions ; INSTAT, RGPH-3 (2020).`,
  image: { file: "carte_regions_naturelles.png", legende: "Les cinq régions naturelles et les six anciennes provinces (chefs-lieux)", widthCm: 11, source: "réalisation J-Learn d'après l'Atlas de Madagascar (FTM)" },
  revision: [
    ["Quelle est la région la plus sèche de Madagascar ?", "Le Sud, avec moins de 500 mm de pluie par an."],
    ["Citez les trois grands fleuves de l'Ouest.", "La Betsiboka, la Tsiribihina et le Mangoky."],
    ["Qu'est-ce que le kere ?", "La famine qui frappe le Grand Sud quand les pluies manquent."],
    ["Quelle est la végétation de l'Ouest ?", "La savane à baobabs et les mangroves sur la côte."],
  ],
  miseEnSituation: {
    enseignant: [
      "Au mois de juillet, Lanto, qui habite Antsirabe, met un pull le matin : il fait 5 °C et le brouillard couvre les rizières en terrasses. Son oncle, venu de Toliara, n'a jamais eu aussi froid de sa vie !",
      "Pourquoi fait-il si froid à Antsirabe alors que Madagascar est une île tropicale ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : à cause de l'altitude ; Antsirabe se trouve sur les Hautes Terres, à plus de 1 500 m."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau de comparaison des cinq régions que j'écris au tableau noir :", "| Région | Relief | Pluies par an | Climat | Végétation |", "| Nord | montagnes (Tsaratanana 2 876 m), plaines | 1 500-2 000 mm | tropical | forêt, savane |", "| Est | plaine côtière étroite, falaise | plus de 2 000 mm | chaud et humide | forêt dense |", "| Ouest | plaines et plateaux | 500-1 500 mm | tropical sec | savane, baobabs |", "| Sud | plateaux, plaine sableuse | moins de 500 mm | semi-aride | bush épineux |", "| Hautes Terres | plateaux et massifs de 1 200 à 2 600 m | 1 200-1 500 mm | tropical d'altitude, hiver frais | savane herbeuse, rizières |"],
    support: "Tableau noir (tableau comparatif recopié)",
    note: "Faire lire la ligne « Hautes Terres » en dernier : elle se distingue par l'altitude et l'hiver frais.",
  },
  analyse: [
    ["Quelle altitude atteignent les Hautes Terres Centrales ? Citez deux massifs.", "Entre 1 200 et 1 500 m en moyenne ; les massifs de l'Ankaratra (Tsiafajavona, 2 643 m) et de l'Andringitra (pic Boby, 2 658 m) dépassent 2 600 m."],
    ["Quel est le climat des Hautes Terres ?", "Un climat tropical d'altitude : un été chaud et pluvieux (novembre à avril) et un hiver frais et sec (mai à octobre) avec parfois du gel à Antsirabe."],
    ["Quel problème frappe les sols des Hautes Terres ? Comment s'appelle la forme d'érosion typique ?", "L'érosion : les sols de latérite rouge, déboisés et brûlés, sont creusés par les pluies en grandes cicatrices appelées lavaka."],
    ["Quelles sont les principales activités agricoles des Hautes Terres ?", "La riziculture irriguée dans les bas-fonds et en terrasses, les cultures sur tanety (maïs, manioc, pomme de terre, légumes), l'élevage laitier autour d'Antsirabe."],
    ["Pourquoi les Hautes Terres concentrent-elles les industries et la population ?", "Parce qu'on y trouve la capitale Antananarivo, les grandes villes (Antsirabe, Fianarantsoa), les routes et le chemin de fer, la main-d'œuvre et l'énergie hydroélectrique."],
    ["D'après le tableau, quelle région est la plus arrosée et laquelle est la plus sèche ?", "La plus arrosée est l'Est (plus de 2 000 mm), la plus sèche est le Sud (moins de 500 mm)."],
    ["Quelles étaient les six anciennes provinces de Madagascar ? En combien de régions le pays est-il divisé aujourd'hui ?", "Antananarivo, Antsiranana, Fianarantsoa, Mahajanga, Toamasina et Toliara ; le pays est aujourd'hui divisé en 23 régions."],
    ["Une province correspond-elle exactement à une région naturelle ? Donnez un exemple.", "Non : l'ancienne province de Toliara couvrait à la fois l'Ouest (Morondava) et le Sud (Toliara, Ambovombe) ; celle de Fianarantsoa allait des Hautes Terres à la côte Est (Manakara)."],
  ],
  synthese: "Donc, les Hautes Terres Centrales forment l'épine dorsale de Madagascar : des plateaux de 1 200 à 1 500 m au climat tropical d'altitude, frais en hiver, où dominent la riziculture irriguée, les cultures sur tanety et la plus forte concentration de population et d'industries autour d'Antananarivo. La comparaison des cinq régions montre que les pluies diminuent de l'Est (plus de 2 000 mm) vers le Sud (moins de 500 mm). Enfin, le découpage administratif (6 anciennes provinces, 23 régions actuelles) ne correspond pas exactement aux régions naturelles.",
  application: [
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. L'altitude moyenne des Hautes Terres Centrales est de : A) 300 à 500 m — B) 1 200 à 1 500 m — C) plus de 2 500 m.",
      "2. Le mot lavaka désigne : A) une rizière en terrasse — B) une grande cicatrice d'érosion — C) un massif volcanique.",
      "3. Le pic Boby (2 658 m) se trouve dans le massif : A) de l'Ankaratra — B) du Tsaratanana — C) de l'Andringitra.",
      "4. Madagascar est aujourd'hui divisée en : A) 6 régions — B) 22 régions — C) 23 régions.",
    ], corrige: [
      "1. **B)** 1 200 à 1 500 m d'altitude en moyenne.",
      "2. **B)** une grande cicatrice d'**érosion** creusée dans la latérite par les pluies.",
      "3. **C)** l'Andringitra, au sud de Fianarantsoa ; le Tsiafajavona (2 643 m) est dans l'Ankaratra.",
      "4. **C)** 23 régions depuis 2021 (22 auparavant), issues des 6 anciennes provinces.",
    ]},
    { consigne: "Complétez le tableau en écrivant dans votre cahier le nom de la région naturelle qui correspond à chaque description.", pts: 4, items: [
      "a) Plaine côtière étroite, plus de 2 000 mm de pluie, forêt dense humide : ……………",
      "b) Moins de 500 mm de pluie, bush épineux, kere : ……………",
      "c) Plateaux de 1 200 à 1 500 m, hiver frais, rizières en terrasses : ……………",
      "d) Vastes plaines sédimentaires, savane à baobabs, grands fleuves : ……………",
      "e) Massif du Tsaratanana, plaine du Sambirano, cacao et ylang-ylang : ……………",
    ], corrige: [
      "a) L'**Est**.", "b) Le **Sud**.", "c) Les **Hautes Terres Centrales**.", "d) L'**Ouest**.", "e) Le **Nord**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Sur les Hautes Terres, il peut geler en hiver à Antsirabe.",
      "b) Les Hautes Terres sont la région la moins peuplée de Madagascar.",
      "c) Les six anciennes provinces correspondent exactement aux cinq régions naturelles.",
      "d) Les pluies diminuent de l'Est vers le Sud de l'île.",
    ], corrige: [
      "a) **Vrai** : le climat tropical d'altitude donne un hiver frais et sec, avec du **gel** possible.",
      "b) **Faux** : c'est la région la **plus peuplée**, autour d'Antananarivo, d'Antsirabe et de Fianarantsoa.",
      "c) **Faux** : une province regroupait souvent plusieurs régions naturelles (ex. : Toliara couvrait l'Ouest et le Sud).",
      "d) **Vrai** : de plus de 2 000 mm dans l'Est à moins de 500 mm dans le Sud.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Expliquez pourquoi les Hautes Terres ont un climat plus frais que les côtes.",
      "2. Citez deux causes et une conséquence de l'érosion sur les Hautes Terres.",
      "3. Quels sont les deux types de terrains cultivés sur les Hautes Terres et que produit-on sur chacun ?",
      "4. Citez les six anciennes provinces de Madagascar et leur chef-lieu.",
    ], corrige: [
      "1. À cause de l'**altitude** : la température baisse d'environ 0,6 °C tous les 100 m ; à 1 300 m, Antananarivo est plus fraîche que Toamasina au niveau de la mer.",
      "2. Causes : le **déboisement** et les **feux de brousse** qui laissent la latérite nue sous les fortes pluies. Conséquence : les **lavaka** et la perte de terres cultivables (les alluvions rouges vont ensablir les rizières et les fleuves).",
      "3. Les **bas-fonds** et les terrasses, où l'on pratique la **riziculture irriguée** ; les **tanety** (collines), où l'on cultive maïs, manioc, pomme de terre, haricot et légumes.",
      "4. **Antananarivo** (Antananarivo), **Antsiranana** (Antsiranana), **Fianarantsoa** (Fianarantsoa), **Mahajanga** (Mahajanga), **Toamasina** (Toamasina) et **Toliara** (Toliara) : chaque province portait le nom de son chef-lieu.",
    ]},
  ],
  lecon: [
    { t: "h", x: "1. Les Hautes Terres Centrales" },
    { t: "hh", x: "a) Les conditions naturelles" },
    { t: "p", x: "Les **Hautes Terres Centrales** occupent le centre de l'île du nord au sud. Ce sont des plateaux de **1 200 à 1 500 m** d'altitude, formés de roches anciennes (granites, gneiss), dominés par des massifs volcaniques ou cristallins : l'**Ankaratra** (Tsiafajavona, 2 643 m), l'**Andringitra** (pic Boby, 2 658 m), l'Itasy et ses lacs de cratère. Le paysage est fait de collines arrondies, les **tanety**, séparées par des bas-fonds marécageux. Le climat est **tropical d'altitude** : un été chaud et pluvieux (novembre à avril, 1 200 à 1 500 mm) et un hiver frais et sec (mai à octobre) où le gel est possible à Antsirabe. La forêt a presque disparu ; elle a laissé place à une **savane herbeuse** et à des sols de **latérite** rouge. Déboisés et brûlés, ces sols sont creusés par les pluies en immenses cicatrices d'érosion : les **lavaka**." },
    { t: "hh", x: "b) Les potentiels économiques" },
    { t: "ul", x: [
      "La **riziculture irriguée** dans les bas-fonds et en **terrasses** (pays betsileo), et la cuvette du lac **Alaotra**, premier grenier à riz du pays, au nord-est des Hautes Terres.",
      "Les **cultures sur tanety** : maïs, manioc, pomme de terre, haricot, légumes et fruits tempérés (pommes, pêches) autour d'Antsirabe.",
      "L'**élevage laitier** (région d'Antsirabe) et l'élevage de porcs et de volailles.",
      "La **concentration des industries** et des services autour d'**Antananarivo**, la capitale, et d'Antsirabe : textile, agroalimentaire, brasseries, cimenteries.",
      "L'**énergie hydroélectrique** (Mandraka, Antelomita, Andekaleka sur la falaise de l'Est).",
      "Le tourisme (Antsirabe, Ambohimanga, parc de l'Andringitra) et l'artisanat (soie, vannerie, sculpture).",
    ]},
    { t: "h", x: "2. Comparaison des cinq régions naturelles" },
    { t: "table", header: ["Région", "Relief", "Pluies / an", "Saison sèche", "Végétation", "Potentiels"], widths: [1300, 1900, 1200, 1100, 1700, 2400],
      rows: [
        ["Nord", "Massifs (Tsaratanana 2 876 m), plaines du Sambirano", "1 500 à 2 000 mm", "5 à 6 mois", "Forêt humide, savane", "Cacao, ylang-ylang, canne, pêche, tourisme"],
        ["Est", "Plaine côtière étroite, falaise", "Plus de 2 000 mm", "Presque nulle", "Forêt dense humide", "Vanille, girofle, café, litchi, port de Toamasina"],
        ["Ouest", "Plaines et plateaux sédimentaires", "500 à 1 500 mm", "6 à 8 mois", "Savane, baobabs, mangroves", "Élevage bovin, riz (Marovoay), coton, pêche"],
        ["Sud", "Plateaux calcaires, plaine sableuse", "Moins de 500 mm", "9 à 11 mois", "Bush épineux", "Élevage, sisal, pêche, mines"],
        ["Hautes Terres", "Plateaux de 1 200-1 500 m, massifs à 2 600 m", "1 200 à 1 500 mm", "6 mois (hiver frais)", "Savane herbeuse, rizières", "Riz, cultures de tanety, industries, capitale"],
      ], source: "Atlas de Madagascar (FTM) ; Direction Générale de la Météorologie" },
    { t: "p", x: "Ce tableau montre que les **pluies diminuent** de l'Est vers le Sud et que l'**altitude** rafraîchit le centre de l'île. Chaque région possède des potentiels différents, ce qui explique la diversité des productions de Madagascar et la nécessité de bonnes voies de communication entre les régions." },
    { t: "h", x: "3. Régions naturelles et découpage administratif" },
    { t: "p", x: "Pendant longtemps, Madagascar a été divisée en **six provinces** (faritany) portant le nom de leur chef-lieu : **Antananarivo, Antsiranana, Fianarantsoa, Mahajanga, Toamasina et Toliara**. Depuis 2004, le pays est organisé en **régions** (22, puis **23 régions** depuis 2021 avec la division de la région Vatovavy-Fitovinany), elles-mêmes divisées en districts et en communes. Les limites administratives **ne correspondent pas exactement** aux régions naturelles : l'ancienne province de Toliara couvrait à la fois l'Ouest (Morondava) et le Sud (Toliara, Ambovombe) ; celle de Fianarantsoa s'étendait des Hautes Terres (Fianarantsoa) à la côte Est (Manakara). Connaître les régions naturelles aide donc à comprendre les différences de richesse et de population entre les régions administratives." },
  ],
},
// =====================================================================
{
  num: 4, theme: THEME,
  titre: "La population malgache : nombre, croissance, structure et répartition",
  objectif: "présenter les caractères de la population malgache (effectif, rythme de croissance, temps de doublement, structure par âge, répartition) et d'expliquer leur influence sur l'économie",
  documentation: `${DOC_PROG} ; INSTAT, Troisième Recensement Général de la Population et de l'Habitation (RGPH-3, 2018), résultats définitifs (2020-2021) ; Nations Unies Madagascar, Analyse commune de pays (2023).`,
  image: { file: "population_evolution.png", legende: "Évolution de la population de Madagascar aux trois recensements (en millions d'habitants)", widthCm: 12, source: "INSTAT, RGPH 1975, 1993 et 2018" },
  revision: [
    ["Citez les cinq régions naturelles de Madagascar.", "Le Nord, l'Est, l'Ouest, le Sud et les Hautes Terres Centrales."],
    ["Quelle région naturelle est la plus peuplée ?", "Les Hautes Terres Centrales, autour d'Antananarivo."],
    ["Combien de régions administratives compte Madagascar aujourd'hui ?", "23 régions."],
    ["Qu'est-ce que la densité de population ?", "Le nombre moyen d'habitants par kilomètre carré."],
  ],
  miseEnSituation: {
    enseignant: [
      "Quand la grand-mère de Nivo est née, en 1975, Madagascar comptait 7,6 millions d'habitants. Quand la mère de Nivo est née, en 1993, il y en avait 12,2 millions. Quand Nivo est née, en 2010, environ 21 millions. Aujourd'hui, nous sommes près de 30 millions.",
      "Que remarquez-vous ? Que va-t-il se passer si cela continue ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : la population augmente très vite, elle double en une génération ; il faudra plus d'écoles, de nourriture, de travail."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Indicateur (RGPH-3, 2018) | Valeur |", "| Population totale | 25 674 196 habitants |", "| Population en 1993 (RGPH-2) | 12 238 914 habitants |", "| Taux de croissance annuel moyen 1993-2018 | 3,0 % par an |", "| Densité moyenne | 43 habitants par km² |", "| Moins de 15 ans | 44 % de la population |", "| 60 ans et plus | 4,5 % |", "| Population rurale | 81 % |", "| Nombre moyen d'enfants par femme | 4 à 5 |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire comparer les deux premières lignes : la population a plus que doublé en 25 ans.",
  },
  analyse: [
    ["Combien d'habitants comptait Madagascar au recensement de 2018 ? Et aujourd'hui ?", "25,7 millions en 2018 ; les estimations donnent environ 30 millions d'habitants en 2023-2024."],
    ["Comparez la population de 1993 et celle de 2018. Que constatez-vous ?", "Elle est passée de 12,2 à 25,7 millions : elle a plus que doublé en 25 ans."],
    ["Qu'est-ce que le temps de doublement ? Comment le calcule-t-on ?", "C'est le nombre d'années nécessaires pour que la population double. On l'estime en divisant 70 par le taux de croissance : 70 ÷ 3 ≈ 23 ans."],
    ["Pourquoi la population malgache augmente-t-elle si vite ?", "Parce que la natalité reste forte (4 à 5 enfants par femme) alors que la mortalité a baissé grâce aux vaccins, aux soins et à l'hygiène : c'est l'accroissement naturel."],
    ["Que signifie « 44 % de moins de 15 ans » ? Quelle forme a la pyramide des âges ?", "Presque un Malgache sur deux est un enfant : la population est très jeune. La pyramide a une base très large et un sommet très étroit (4,5 % de 60 ans et plus)."],
    ["Quelles sont les conséquences économiques d'une population jeune ?", "Beaucoup de personnes à nourrir, à scolariser et à soigner pour peu d'adultes qui travaillent ; il faut créer chaque année de nombreux emplois pour les jeunes."],
    ["La population est-elle répartie régulièrement sur le territoire ?", "Non : les Hautes Terres (Analamanga, Vakinankaratra) et la côte Est sont très peuplées, tandis que l'Ouest (Melaky) et le Sud sont presque vides."],
    ["Quelle part de la population vit à la campagne ? Quelle en est la conséquence ?", "81 % des Malgaches vivent en milieu rural : la majorité travaille dans l'agriculture, souvent avec de très petites exploitations."],
  ],
  analyseTechnique: "Lecture de tableau statistique et questionnement dirigé",
  synthese: "Donc, la population malgache est nombreuse (25,7 millions en 2018, près de 30 millions aujourd'hui) et augmente très vite : avec 3 % de croissance par an, elle double tous les 23 ans environ. Elle est très jeune (44 % de moins de 15 ans), majoritairement rurale (81 %) et inégalement répartie : les Hautes Terres et l'Est sont denses, l'Ouest et le Sud presque vides. Cette croissance rapide pèse sur l'économie : il faut produire plus de nourriture, construire plus d'écoles et créer plus d'emplois.",
  application: [
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. Au recensement de 2018, Madagascar comptait : A) 12,2 millions — B) 25,7 millions — C) 35 millions d'habitants.",
      "2. Avec un taux de croissance de 3 % par an, la population double environ tous les : A) 10 ans — B) 23 ans — C) 50 ans.",
      "3. La part des moins de 15 ans dans la population malgache est d'environ : A) 20 % — B) 44 % — C) 60 %.",
      "4. La région administrative la plus densément peuplée est : A) Analamanga — B) Melaky — C) Androy.",
    ], corrige: [
      "1. **B)** 25,7 millions (25 674 196 habitants exactement).",
      "2. **B)** 23 ans : 70 ÷ 3 ≈ 23.",
      "3. **B)** 44 % : presque la moitié des Malgaches sont des enfants.",
      "4. **A)** Analamanga (région d'Antananarivo) avec plus de 200 habitants par km², contre moins de 10 dans le Melaky.",
    ]},
    { consigne: "Calculez et répondez par une phrase complète.", pts: 4, items: [
      "1. La superficie de Madagascar est d'environ 592 000 km² et sa population en 2018 était de 25,7 millions. Calculez la densité moyenne.",
      "2. Si la population croît de 3 % par an, en quelle année environ la population de 2018 aura-t-elle doublé ?",
      "3. Une classe de 3ème compte 50 élèves. Si la structure de la classe était celle du pays, combien auraient moins de 15 ans ?",
      "4. Sur 100 Malgaches, combien vivent en ville ?",
    ], corrige: [
      "1. 25 700 000 ÷ 592 000 ≈ **43 habitants par km²**.",
      "2. 70 ÷ 3 ≈ 23 ans ; 2018 + 23 = vers **2041**, la population atteindra environ 51 millions.",
      "3. 44 % de 50 = **22 élèves** auraient moins de 15 ans.",
      "4. 100 − 81 = **19 Malgaches sur 100** vivent en ville (environ un sur cinq).",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) La population malgache a plus que doublé entre 1993 et 2018.",
      "b) Les personnes de 60 ans et plus représentent un quart de la population.",
      "c) La majorité des Malgaches vit dans les villes.",
      "d) La forte croissance de la population s'explique par une natalité élevée et une mortalité en baisse.",
    ], corrige: [
      "a) **Vrai** : de 12,2 millions à 25,7 millions.",
      "b) **Faux** : ils ne représentent que **4,5 %** ; la population est très jeune.",
      "c) **Faux** : **81 %** des Malgaches vivent en milieu **rural**.",
      "d) **Vrai** : c'est l'**accroissement naturel** (naissances moins décès) qui est élevé.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Définissez le taux de croissance annuel et le temps de doublement.",
      "2. Décrivez la forme de la pyramide des âges de Madagascar et expliquez-la.",
      "3. Citez deux régions très peuplées et deux régions peu peuplées, puis donnez une raison de cette inégalité.",
      "4. Expliquez deux conséquences de la croissance rapide de la population sur l'économie malgache.",
    ], corrige: [
      "1. Le **taux de croissance annuel** est l'augmentation de la population en pourcentage chaque année (3 % à Madagascar). Le **temps de doublement** est le nombre d'années au bout duquel la population double (environ 23 ans).",
      "2. La pyramide a une **base très large** (44 % de moins de 15 ans) et un **sommet étroit** (4,5 % de 60 ans et plus) : c'est une population **jeune**, car la natalité est forte (4 à 5 enfants par femme) et l'espérance de vie encore limitée (environ 65 ans).",
      "3. Très peuplées : **Analamanga** et **Vakinankaratra** (Hautes Terres), ainsi que la côte Est. Peu peuplées : **Melaky** (Ouest) et le Sud (**Androy**, Atsimo-Andrefana). Raisons : les Hautes Terres ont des sols cultivables, de l'eau, la capitale et les emplois ; l'Ouest et le Sud sont secs, isolés et mal desservis.",
      "4. Il faut **nourrir** plus de bouches alors que la production de riz suit difficilement (importations de riz) ; il faut **scolariser** et **soigner** de nombreux enfants ; il faut créer chaque année des **emplois** pour les jeunes, sinon le chômage et la pauvreté augmentent ; la pression sur les terres accélère le déboisement.",
    ]},
  ],
  lecon: [
    { t: "p", x: "L'étude de la population est indispensable pour comprendre l'économie : les habitants sont à la fois les **producteurs** et les **consommateurs** des richesses du pays." },
    { t: "h", x: "1. Une population nombreuse qui augmente vite" },
    { t: "p", x: "Le troisième recensement général (**RGPH-3**), réalisé par l'INSTAT en 2018, a dénombré **25 674 196 habitants**. Les estimations donnent près de **30 millions** en 2023-2024. La population a plus que doublé en 25 ans : 7,6 millions en 1975, 12,2 millions en 1993, 25,7 millions en 2018. Le **taux de croissance annuel** est d'environ **3 %**, l'un des plus élevés du monde. À ce rythme, le **temps de doublement** — le nombre d'années au bout duquel la population double — est d'environ **23 ans** (on l'estime en divisant 70 par le taux de croissance : 70 ÷ 3 ≈ 23)." },
    { t: "p", x: "Cette croissance s'explique par un fort **accroissement naturel** : la **natalité** reste élevée (chaque femme a en moyenne 4 à 5 enfants) alors que la **mortalité** a baissé grâce aux vaccinations, aux soins et à l'amélioration de l'hygiène. L'espérance de vie à la naissance est passée d'environ 52 ans à la fin des années 1990 à environ 65 ans." },
    { t: "h", x: "2. Une population très jeune" },
    { t: "fig", file: "structure_age.png", legende: "Structure par âge de la population malgache en 2018 (en % de la population totale)", widthCm: 11, source: "INSTAT, RGPH-3 (2018)" },
    { t: "p", x: "La **pyramide des âges** de Madagascar a une **base très large** et un **sommet très étroit** : environ **44 %** des Malgaches ont moins de 15 ans, près de 63 % ont moins de 25 ans, et seulement **4,5 %** ont 60 ans et plus. L'âge médian est d'environ 18 ans : la moitié de la population est mineure. Cette jeunesse est une richesse pour l'avenir (main-d'œuvre nombreuse), mais elle représente aussi une lourde **charge** : pour chaque adulte qui travaille, il y a beaucoup d'enfants à nourrir, à scolariser et à soigner." },
    { t: "h", x: "3. Une répartition très inégale" },
    { t: "p", x: "La **densité moyenne** est faible : environ **43 habitants par km²**. Mais cette moyenne cache de très grandes différences :" },
    { t: "ul", x: [
      "Les **Hautes Terres Centrales** sont très peuplées : la région Analamanga (Antananarivo) dépasse 200 habitants par km², le Vakinankaratra (Antsirabe) plus de 100.",
      "La **côte Est** (Toamasina, Analanjirofo, Vatovavy, Fitovinany) et la **côte Nord-Est** (SAVA) sont bien peuplées grâce aux pluies et aux cultures d'exportation.",
      "L'**Ouest** et le **Sud** sont presque vides : le Melaky compte moins de 10 habitants par km², l'Androy et l'Atsimo-Andrefana moins de 50.",
    ]},
    { t: "p", x: "Cette inégalité s'explique par l'histoire (les royaumes des Hautes Terres), par les conditions naturelles (eau, sols) et par la localisation des villes, des routes et des emplois. La population reste très **rurale** : **81 %** des Malgaches vivent à la campagne et 83 % des ménages pratiquent l'agriculture. Les villes grandissent cependant vite : l'agglomération d'**Antananarivo** dépasse 3 millions d'habitants ; Toamasina, Antsirabe, Mahajanga et Fianarantsoa sont les autres grandes villes." },
    { t: "h", x: "4. Les conséquences sur l'économie" },
    { t: "ul", x: [
      "**Nourrir** une population qui double tous les 23 ans : la production de riz ne suit pas toujours et le pays doit en importer.",
      "**Scolariser et soigner** des millions d'enfants : construire des écoles, des centres de santé, former des enseignants et des médecins.",
      "**Créer des emplois** pour les centaines de milliers de jeunes qui arrivent chaque année sur le marché du travail.",
      "**Protéger les terres** : la pression démographique accélère le déboisement, le tavy et l'érosion.",
    ]},
    { t: "p", x: "La population est donc à la fois le premier **atout** et le premier **défi** de l'économie malgache." },
  ],
},
// =====================================================================
{
  num: 5, theme: THEME,
  titre: "Les caractères généraux de l'économie malgache : une économie sous-développée",
  objectif: "définir le sous-développement à l'aide des indicateurs (PIB par habitant, IDH, alimentation) et de montrer que Madagascar est un pays sous-développé",
  documentation: `${DOC_PROG} ; Banque mondiale, indicateurs du développement dans le monde (2023) ; PNUD, Rapport sur le développement humain 2023-2024 ; INSTAT/UNICEF, enquête MICS (2018).`,
  image: null,
  revision: [
    ["Combien d'habitants compte Madagascar aujourd'hui, environ ?", "Environ 30 millions d'habitants."],
    ["Quel est le taux de croissance annuel de la population malgache ?", "Environ 3 % par an."],
    ["Quelle part de la population a moins de 15 ans ?", "Environ 44 %."],
    ["Citez deux conséquences de cette croissance rapide sur l'économie.", "Il faut nourrir plus de personnes, construire plus d'écoles, créer plus d'emplois."],
  ],
  miseEnSituation: {
    enseignant: [
      "Koto a 13 ans. Il va à l'école le matin, mais l'après-midi il aide son père aux champs, car la famille ne mange pas toujours à sa faim. Le centre de santé le plus proche est à 15 km et il n'y a pas d'électricité au village.",
      "Quels sont les signes qui montrent que la famille de Koto vit dans la pauvreté ? Pensez-vous que la situation de Koto est rare à Madagascar ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : manque de nourriture, travail des enfants, éloignement des soins, absence d'électricité ; non, beaucoup de familles malgaches vivent ainsi."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Indicateur | Madagascar | Maurice (voisin) |", "| PIB par habitant (2023) | environ 530 dollars | environ 11 000 dollars |", "| IDH (2022) | 0,487 (177e sur 193 pays) | 0,796 (72e) |", "| Espérance de vie | environ 65 ans | environ 74 ans |", "| Population sous le seuil de pauvreté (2,15 $ par jour) | environ 75 à 80 % | moins de 1 % |", "| Enfants de moins de 5 ans en retard de croissance | environ 40 % | moins de 10 % |", "| Accès à l'électricité | environ 35 % | 100 % |"],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire lire la colonne Madagascar ligne par ligne, puis comparer avec Maurice, île voisine partie d'un niveau comparable en 1960.",
  },
  analyse: [
    ["Qu'est-ce que le PIB ? Que signifie « PIB par habitant » ?", "Le Produit Intérieur Brut est la valeur de toutes les richesses produites dans un pays en un an. Le PIB par habitant est ce total divisé par le nombre d'habitants : il mesure la richesse moyenne."],
    ["Comparez le PIB par habitant de Madagascar et de Maurice.", "Environ 530 dollars contre 11 000 : un Mauricien produit en moyenne vingt fois plus de richesses qu'un Malgache."],
    ["Quelle est la différence entre le PIB et le PNB ?", "Le PIB compte tout ce qui est produit sur le territoire ; le PNB (ou RNB) compte ce qui est produit par les nationaux, à l'intérieur ou à l'extérieur du pays."],
    ["Qu'est-ce que l'IDH ? Quels sont ses trois éléments ?", "L'Indicateur de Développement Humain, calculé par le PNUD, combine trois éléments : la santé (espérance de vie), l'éducation (années de scolarisation) et le niveau de vie (revenu par habitant). Il va de 0 à 1."],
    ["Que signifie l'IDH de Madagascar (0,487) ?", "Madagascar est classée parmi les pays à développement humain faible, au 177e rang sur 193 pays."],
    ["Quelle proportion de Malgaches vit sous le seuil de pauvreté ? Que signifie ce seuil ?", "Environ trois Malgaches sur quatre vivent avec moins de 2,15 dollars par jour, seuil international de pauvreté extrême fixé par la Banque mondiale."],
    ["Quelle est la différence entre la sous-alimentation et la malnutrition ?", "La sous-alimentation, c'est ne pas manger assez (quantité) ; la malnutrition, c'est manger de façon déséquilibrée (manque de protéines, de vitamines). Les deux provoquent le retard de croissance de 40 % des enfants."],
    ["Quel lien existe-t-il entre le développement économique et le niveau de vie ?", "Quand la production de richesses par habitant augmente, l'État et les familles peuvent mieux se nourrir, se soigner et s'instruire : le niveau de vie et l'IDH progressent."],
  ],
  analyseTechnique: "Lecture de tableau statistique et questionnement dirigé",
  synthese: "Donc, Madagascar est un pays sous-développé : son PIB par habitant est l'un des plus faibles du monde (environ 530 dollars), son IDH (0,487, 177e sur 193) le classe parmi les pays à développement humain faible, environ trois Malgaches sur quatre vivent sous le seuil de pauvreté et 40 % des enfants souffrent de malnutrition chronique. Ces indicateurs sont liés : la faible production de richesses limite l'alimentation, la santé et l'éducation, ce qui freine à son tour la croissance économique.",
  application: [
    { consigne: "Choisissez la bonne réponse.", pts: 4, items: [
      "1. Le PIB par habitant de Madagascar en 2023 est d'environ : A) 530 dollars — B) 5 300 dollars — C) 11 000 dollars.",
      "2. L'IDH est calculé par : A) la Banque mondiale — B) le PNUD — C) l'INSTAT.",
      "3. L'IDH combine la santé, l'éducation et : A) la superficie du pays — B) le niveau de vie — C) le nombre d'habitants.",
      "4. Le seuil international de pauvreté extrême est de : A) 2,15 dollars par jour — B) 21,5 dollars par jour — C) 215 dollars par mois.",
    ], corrige: [
      "1. **A)** environ 530 dollars, parmi les cinq PIB par habitant les plus faibles du monde.",
      "2. **B)** le **PNUD** (Programme des Nations Unies pour le Développement).",
      "3. **B)** le **niveau de vie**, mesuré par le revenu national brut par habitant.",
      "4. **A)** 2,15 dollars par jour et par personne (Banque mondiale).",
    ]},
    { consigne: "Reliez chaque terme à sa définition.", pts: 4, items: [
      "Colonne A : 1. PIB ; 2. IDH ; 3. Malnutrition ; 4. Sous-alimentation ; 5. Seuil de pauvreté",
      "Colonne B : a) alimentation insuffisante en quantité ; b) revenu minimum en dessous duquel on est considéré comme pauvre ; c) valeur des richesses produites dans un pays en un an ; d) alimentation déséquilibrée, manquant de certains éléments ; e) indicateur combinant santé, éducation et niveau de vie",
    ], corrige: [
      "1 → **c)** le PIB mesure la production de richesses.",
      "2 → **e)** l'IDH mesure le développement humain.",
      "3 → **d)** la malnutrition est un déséquilibre alimentaire.",
      "4 → **a)** la sous-alimentation est un manque de quantité.",
      "5 → **b)** le seuil de pauvreté est un revenu minimum (2,15 $ par jour).",
    ]},
  ],
  evaluation: [
    { consigne: "Complétez le texte avec les mots proposés : PNUD – pauvreté – 0,487 – PIB – malnutrition – faible.", pts: 6, items: [
      "Le ……………… par habitant de Madagascar est très ……………… : environ 530 dollars. L'IDH, calculé par le ……………… , est de ……………… , ce qui place le pays au 177e rang sur 193. Environ trois Malgaches sur quatre vivent sous le seuil de ……………… et 40 % des enfants souffrent de ……………… chronique.",
    ], corrige: [
      "Le **PIB** par habitant de Madagascar est très **faible** : environ 530 dollars. L'IDH, calculé par le **PNUD**, est de **0,487**, ce qui place le pays au 177e rang sur 193. Environ trois Malgaches sur quatre vivent sous le seuil de **pauvreté** et 40 % des enfants souffrent de **malnutrition** chronique.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Pourquoi le PIB par habitant est-il un meilleur indicateur que le PIB total pour comparer deux pays ?",
      "2. Citez les trois éléments de l'IDH et donnez la valeur de l'IDH de Madagascar.",
      "3. Expliquez comment la malnutrition des enfants freine le développement d'un pays.",
      "4. Montrez, à l'aide de deux exemples, le lien entre la croissance économique et le niveau de vie de la population.",
    ], corrige: [
      "1. Parce qu'il tient compte du **nombre d'habitants** : un grand pays peut avoir un PIB total élevé mais une population très pauvre. Le PIB par habitant mesure la **richesse moyenne** de chaque personne.",
      "2. La **santé** (espérance de vie), l'**éducation** (durée de scolarisation) et le **niveau de vie** (revenu par habitant). L'IDH de Madagascar est de **0,487** (177e sur 193 pays).",
      "3. Un enfant mal nourri est plus souvent **malade**, apprend **moins bien** à l'école et deviendra un adulte moins **productif** : la malnutrition réduit la qualité de la future main-d'œuvre et coûte cher en soins.",
      "4. Quand la production augmente, les **revenus** des familles montent et elles peuvent acheter plus de nourriture et de médicaments ; l'État perçoit plus d'**impôts** et peut construire des écoles, des routes et des hôpitaux. À l'inverse, la stagnation de l'économie malgache depuis 1960 explique que le revenu par habitant a même baissé.",
    ]},
  ],
  lecon: [
    { t: "p", x: "Le programme étudie maintenant les caractères généraux de l'économie malgache. Le premier est le **sous-développement** : Madagascar est classée parmi les **pays les moins avancés** (PMA) du monde. Pour le mesurer, les géographes utilisent des **indicateurs**." },
    { t: "h", x: "1. Les indicateurs de richesse : PIB et PNB" },
    { t: "p", x: "Le **Produit Intérieur Brut (PIB)** est la valeur de toutes les richesses (biens et services) produites dans un pays pendant un an. Le **Produit National Brut (PNB)**, aujourd'hui appelé Revenu National Brut (RNB), compte les richesses produites par les nationaux, dans le pays ou à l'étranger. Pour comparer des pays de taille différente, on divise ce total par le nombre d'habitants : c'est le **PIB par habitant**." },
    { t: "p", x: "Le PIB par habitant de Madagascar est d'environ **530 dollars** par an (2023), l'un des cinq plus faibles du monde. À titre de comparaison, il dépasse 11 000 dollars à Maurice et 40 000 dollars en France. Fait rare, le revenu par habitant de Madagascar est aujourd'hui **plus bas qu'en 1960** : la production a augmenté moins vite que la population." },
    { t: "h", x: "2. L'Indicateur de Développement Humain (IDH)" },
    { t: "p", x: "La richesse ne dit pas tout. Depuis 1990, le **PNUD** (Programme des Nations Unies pour le Développement) calcule l'**IDH**, qui combine trois éléments :" },
    { t: "ul", x: [
      "la **santé**, mesurée par l'espérance de vie à la naissance (environ **65 ans** à Madagascar) ;",
      "l'**éducation**, mesurée par la durée de scolarisation (environ 5 années en moyenne pour les adultes) ;",
      "le **niveau de vie**, mesuré par le revenu national brut par habitant.",
    ]},
    { t: "p", x: "L'IDH va de 0 à 1. Celui de Madagascar est de **0,487** (données 2022, rapport PNUD 2023-2024), ce qui place le pays au **177e rang sur 193** pays, dans le groupe à **développement humain faible**. Il a lentement progressé depuis 1999 (0,431), surtout grâce à l'allongement de l'espérance de vie." },
    { t: "h", x: "3. La pauvreté et l'alimentation" },
    { t: "p", x: "Selon la Banque mondiale, environ **trois Malgaches sur quatre** vivent sous le **seuil international de pauvreté** (2,15 dollars par jour et par personne). La pauvreté est plus forte dans les campagnes et dans le Sud. Elle se traduit d'abord dans l'assiette :" },
    { t: "ul", x: [
      "la **sous-alimentation** : ne pas manger en quantité suffisante (moins de 2 100 calories par jour) ; elle s'aggrave pendant la période de soudure, avant la récolte du riz, et lors du kere dans le Sud ;",
      "la **malnutrition** : manger de façon déséquilibrée (trop de riz ou de manioc, pas assez de protéines, de fruits et de légumes). Environ **40 % des enfants de moins de 5 ans** souffrent d'un retard de croissance, l'un des taux les plus élevés du monde.",
    ]},
    { t: "h", x: "4. Les autres signes du sous-développement" },
    { t: "ul", x: [
      "Un faible **accès aux services** : environ un tiers de la population a l'électricité, moins de la moitié l'eau potable ; les centres de santé et les lycées sont loin des villages.",
      "Une **forte croissance démographique** (3 % par an) qui absorbe les progrès de la production.",
      "Une économie dominée par l'**agriculture de subsistance** et le secteur informel, avec peu d'industries.",
      "Une grande **vulnérabilité** aux catastrophes naturelles (cyclones, sécheresses, invasions de criquets) et aux crises politiques (1991, 2002, 2009), qui ont chaque fois fait reculer l'économie.",
    ]},
    { t: "h", x: "5. Le lien entre développement économique et niveau de vie" },
    { t: "p", x: "Ces indicateurs forment un **cercle vicieux** : la faible production limite les revenus, donc l'alimentation, la santé et l'éducation ; une population mal nourrie et peu formée produit peu, ce qui maintient le PIB bas. Pour rompre ce cercle, il faut investir en même temps dans la production (agriculture, industrie, routes, énergie) et dans les hommes (écoles, santé, nutrition)." },
  ],
},
// =====================================================================
{
  num: 6, theme: THEME,
  titre: "Une économie dépendante : les formes de dépendance, la structure de l'économie, l'ajustement structurel et la privatisation",
  objectif: "expliquer les formes de dépendance de l'économie malgache vis-à-vis de l'étranger, de décrire sa structure par secteurs et d'expliquer simplement le Programme d'Ajustement Structurel et la privatisation",
  documentation: `${DOC_PROG} ; Banque mondiale, données par pays (2023-2024) ; FMI, rapports sur Madagascar ; Ministère de l'Économie et des Finances, Loi de finances.`,
  image: { file: "secteurs_economie.png", legende: "Structure de l'économie malgache : part de chaque secteur dans la production (PIB) et dans l'emploi", widthCm: 13, source: "Banque mondiale et INSTAT (données 2022-2024, valeurs arrondies)" },
  revision: [
    ["Qu'est-ce que le PIB par habitant ?", "La valeur des richesses produites dans le pays en un an, divisée par le nombre d'habitants."],
    ["Quels sont les trois éléments de l'IDH ?", "La santé, l'éducation et le niveau de vie."],
    ["Quel est le rang de Madagascar pour l'IDH ?", "177e sur 193 pays (IDH de 0,487)."],
    ["Quelle proportion de Malgaches vit sous le seuil de pauvreté ?", "Environ trois sur quatre."],
  ],
  miseEnSituation: {
    enseignant: [
      "À Antananarivo, Aina prend un taxi-be fabriqué à l'étranger, qui roule avec de l'essence importée. Sa mère travaille dans une usine de vêtements appartenant à une société étrangère, et l'école du quartier a été construite grâce à un prêt de la Banque mondiale.",
      "Dans cette histoire, qu'est-ce qui vient de Madagascar et qu'est-ce qui vient de l'étranger ? Que se passerait-il si l'étranger arrêtait tout ?",
    ],
    apprenants: ["Les élèves écoutent et répondent à l'oral. R.A. : presque tout vient de l'étranger (véhicule, carburant, capitaux, prêt) ; l'économie serait bloquée : Madagascar dépend de l'extérieur."],
  },
  observation: {
    enseignant: ["Regardez et observez bien ce tableau que j'écris au tableau noir :", "| Secteur | Activités | Part du PIB (environ) | Part des emplois (environ) |", "| Primaire | agriculture, élevage, pêche, forêt | 23 % | 75 % |", "| Secondaire | industrie, mines, artisanat, bâtiment | 22 % | 8 % |", "| Tertiaire | commerce, transport, administration, tourisme, banques | 45 % (+ taxes) | 17 % |", "Autres données : dette publique ≈ 55 % du PIB ; aide extérieure ≈ 40 % du budget d'investissement de l'État ; importations 4,7 milliards de dollars contre 3,2 milliards d'exportations (2023)."],
    support: "Tableau noir (tableau de données recopié)",
    note: "Faire comparer les deux colonnes de la ligne « Primaire » : trois emplois sur quatre pour moins d'un quart de la richesse.",
  },
  analyse: [
    ["Qu'est-ce qu'une économie dépendante ?", "Une économie qui ne peut pas fonctionner sans l'aide, les capitaux, les techniques ou les marchés de l'étranger."],
    ["En quoi consiste la dépendance financière ?", "Madagascar dépend des aides (dons) et des prêts (dettes) des pays riches et des institutions internationales (Banque mondiale, FMI, Union européenne, Chine) pour financer ses routes, ses écoles, ses hôpitaux et une partie de son budget."],
    ["Donnez deux exemples de dépendance technologique.", "Les machines, les véhicules, les médicaments, les ordinateurs et les téléphones sont importés ; les grandes mines (Ambatovy, QMM) et les zones franches appartiennent à des sociétés étrangères qui apportent les techniques."],
    ["En quoi consiste la dépendance commerciale ?", "Madagascar exporte des produits bruts (vanille, girofle, nickel) dont les prix sont fixés à l'étranger et achète des produits fabriqués et du pétrole plus chers : elle importe plus qu'elle n'exporte."],
    ["D'après le tableau, quel secteur emploie le plus de Malgaches ? Quel secteur produit le plus de richesses ?", "Le secteur primaire emploie environ 75 % des actifs mais ne produit que 23 % du PIB ; le secteur tertiaire produit le plus de richesses (45 %)."],
    ["Que révèle cet écart pour l'agriculture malgache ?", "Que la productivité agricole est très faible : beaucoup de paysans produisent peu, avec des outils simples et de petites parcelles."],
    ["Qu'est-ce que le Programme d'Ajustement Structurel ?", "Un ensemble de réformes imposées à partir des années 1980 par le FMI et la Banque mondiale en échange de nouveaux prêts : réduire les dépenses de l'État, libéraliser les prix et le commerce, dévaluer la monnaie, privatiser les entreprises publiques."],
    ["Qu'est-ce que la privatisation ? Citez un exemple malgache.", "C'est la vente d'une entreprise appartenant à l'État à des investisseurs privés. Exemples : la Solima (pétrole) en 2000, la Telma (téléphone) en 2004, la BTM devenue BOA (banque) en 1999."],
  ],
  analyseTechnique: "Lecture de tableau statistique et questionnement dirigé",
  synthese: "Donc, l'économie malgache est dépendante de l'étranger sous trois formes : financière (aides et dettes), technologique (machines, techniques et capitaux étrangers) et commerciale (exportation de produits bruts, importation de produits fabriqués et de pétrole). Sa structure est déséquilibrée : le secteur primaire occupe trois actifs sur quatre mais produit moins d'un quart des richesses, tandis que le tertiaire domine le PIB. Depuis les années 1980, le Programme d'Ajustement Structurel et les privatisations ont réduit le rôle de l'État, avec des résultats contrastés.",
  application: [
    { consigne: "Indiquez pour chaque situation la forme de dépendance concernée : financière, technologique ou commerciale.", pts: 4, items: [
      "a) L'État emprunte 400 millions de dollars à la Banque mondiale pour électrifier les campagnes.",
      "b) Les prix de la vanille s'effondrent sur le marché mondial et les planteurs de la SAVA perdent leurs revenus.",
      "c) La JIRAMA doit importer des groupes électrogènes et du fioul pour produire de l'électricité.",
      "d) Une société japonaise et une société coréenne exploitent le nickel d'Ambatovy.",
      "e) Madagascar importe chaque année plus de 300 000 tonnes de riz.",
    ], corrige: [
      "a) Dépendance **financière** (prêt, donc dette).",
      "b) Dépendance **commerciale** (prix fixés à l'étranger).",
      "c) Dépendance **technologique** (matériel) et commerciale (importation de carburant).",
      "d) Dépendance **technologique** et financière (capitaux et techniques étrangers).",
      "e) Dépendance **commerciale** (importation d'un produit alimentaire de base).",
    ]},
    { consigne: "Classez les activités suivantes dans le bon secteur (primaire, secondaire ou tertiaire) : riziculture – usine de textile de zone franche – taxi-brousse – pêche à la crevette – mine de nickel d'Ambatovy – hôtel de Nosy Be – élevage de zébus – brasserie Star.", pts: 4, items: [
      "Secteur primaire : ……………",
      "Secteur secondaire : ……………",
      "Secteur tertiaire : ……………",
    ], corrige: [
      "Primaire : **riziculture**, **pêche à la crevette**, **élevage de zébus**.",
      "Secondaire : **usine de textile**, **mine de nickel d'Ambatovy**, **brasserie Star**.",
      "Tertiaire : **taxi-brousse**, **hôtel de Nosy Be**.",
    ]},
  ],
  evaluation: [
    { consigne: "Répondez par Vrai ou Faux, puis corrigez les phrases fausses.", pts: 4, items: [
      "a) Le secteur primaire produit la plus grande part du PIB malgache.",
      "b) Le Programme d'Ajustement Structurel a été imposé par le FMI et la Banque mondiale en échange de prêts.",
      "c) Privatiser une entreprise, c'est la faire acheter par l'État.",
      "d) Madagascar importe plus qu'elle n'exporte.",
    ], corrige: [
      "a) **Faux** : il emploie 75 % des actifs mais ne produit que **23 %** du PIB ; c'est le **tertiaire** qui domine (45 %).",
      "b) **Vrai** : à partir des années 1980, en contrepartie de nouveaux crédits.",
      "c) **Faux** : c'est l'inverse, l'État **vend** l'entreprise à des **investisseurs privés**.",
      "d) **Vrai** : 4,7 milliards de dollars d'importations contre 3,2 milliards d'exportations en 2023 ; la balance commerciale est **déficitaire**.",
    ]},
    { consigne: "Répondez aux questions suivantes par une phrase complète.", pts: 6, items: [
      "1. Définissez les trois formes de dépendance de l'économie malgache en donnant un exemple pour chacune.",
      "2. L'aide étrangère est-elle nécessaire à Madagascar ? Donnez un avantage et un inconvénient.",
      "3. Expliquez pourquoi la structure de l'économie malgache est dite « déséquilibrée ».",
      "4. Citez deux mesures du Programme d'Ajustement Structurel et une conséquence pour la population.",
    ], corrige: [
      "1. **Financière** : Madagascar dépend des dons et des prêts (ex. : prêts de la Banque mondiale, dette publique d'environ 55 % du PIB). **Technologique** : machines, véhicules, médicaments et techniques viennent de l'étranger (ex. : mine d'Ambatovy). **Commerciale** : exportation de produits bruts aux prix instables, importation de pétrole et de produits fabriqués (ex. : vanille contre carburant).",
      "2. Oui, elle est aujourd'hui nécessaire : **avantage**, elle finance des routes, des écoles, des hôpitaux que l'État ne pourrait pas payer ; **inconvénient**, elle crée une **dette** à rembourser et les bailleurs imposent leurs conditions, ce qui limite l'indépendance du pays.",
      "3. Parce que le secteur **primaire** occupe **trois actifs sur quatre** mais produit **moins d'un quart** des richesses (faible productivité), tandis que l'**industrie** reste très petite (8 % des emplois) et que le tertiaire, souvent informel, domine le PIB.",
      "4. Mesures : **réduction des dépenses** de l'État (moins de fonctionnaires, fin des subventions), **libéralisation** des prix et du commerce, **dévaluation** du franc malgache, **privatisation** des entreprises publiques. Conséquence : hausse des prix du riz et du carburant, licenciements, dégradation des services publics, mais aussi arrivée d'investisseurs (zones franches, télécommunications).",
    ]},
  ],
  lecon: [
    { t: "p", x: "Après le sous-développement, cette séance étudie le second caractère général de l'économie malgache : sa **dépendance** vis-à-vis de l'étranger. Elle présente aussi la structure de l'économie par secteurs et les grandes réformes menées depuis les années 1980." },
    { t: "h", x: "1. Une économie dépendante" },
    { t: "p", x: "Une économie est **dépendante** quand elle ne peut pas fonctionner sans les capitaux, les techniques ou les marchés de l'extérieur. La dépendance de Madagascar prend trois formes." },
    { t: "hh", x: "a) La dépendance financière : aides et dettes" },
    { t: "p", x: "L'État malgache ne collecte pas assez d'impôts pour financer ses investissements. Il reçoit donc des **aides** (dons) et des **prêts** de pays riches (France, États-Unis, Japon, Chine) et d'institutions internationales (**Banque mondiale**, **FMI**, Union européenne, Banque africaine de développement). L'aide extérieure finance environ 40 % du budget d'investissement de l'État. Les prêts forment la **dette publique**, qui représente environ 55 % du PIB : chaque année, une partie des recettes sert à la rembourser. L'aide est nécessaire, mais elle donne aux **bailleurs de fonds** le pouvoir d'imposer leurs conditions." },
    { t: "hh", x: "b) La dépendance technologique" },
    { t: "p", x: "Madagascar fabrique très peu de machines : véhicules, groupes électrogènes, ordinateurs, téléphones, médicaments et engrais sont **importés**. Les grandes entreprises modernes — la mine de nickel et de cobalt d'**Ambatovy**, l'ilménite de **QMM** à Taolagnaro, les usines textiles des **zones franches**, les opérateurs de téléphonie — appartiennent en majorité à des sociétés étrangères qui apportent les capitaux, les techniques et les cadres." },
    { t: "hh", x: "c) La dépendance commerciale" },
    { t: "p", x: "Madagascar exporte surtout des **produits bruts** (vanille, girofle, nickel, crevettes, litchis) dont les prix sont fixés sur les marchés mondiaux et varient beaucoup. Elle importe des produits fabriqués, du **pétrole** et même du **riz**, aliment de base. En 2023, les importations (4,7 milliards de dollars) ont dépassé les exportations (3,2 milliards) : la **balance commerciale** est déficitaire, ce qui oblige à emprunter davantage." },
    { t: "h", x: "2. La structure de l'économie malgache" },
    { t: "p", x: "Les activités économiques se classent en trois **secteurs** :" },
    { t: "ul", x: [
      "le **secteur primaire** (agriculture, élevage, pêche, forêt) occupe environ **75 % des actifs** mais ne produit qu'environ **23 % du PIB** : la productivité y est très faible ;",
      "le **secteur secondaire** (industries, mines, artisanat, bâtiment) reste petit : environ 8 % des emplois et 22 % du PIB, surtout grâce aux mines et aux zones franches ;",
      "le **secteur tertiaire** (commerce, transport, administration, tourisme, banques, télécommunications) domine le PIB (environ **45 %**) avec seulement 17 % des emplois, dont beaucoup dans le **secteur informel** (petits commerces, marchands ambulants).",
    ]},
    { t: "p", x: "Cette structure est **déséquilibrée** : une masse de paysans pauvres, peu d'industries, et des services concentrés dans les villes. Une enquête dans votre commune (qui travaille où ? qui gagne quoi ?) permettrait de retrouver cette répartition à l'échelle locale." },
    { t: "h", x: "3. Le Programme d'Ajustement Structurel et la privatisation" },
    { t: "hh", x: "a) Le Programme d'Ajustement Structurel (PAS)" },
    { t: "p", x: "Dans les années 1970, l'État avait nationalisé les banques, les grandes sociétés et le commerce. Endetté et en crise au début des années 1980, Madagascar a dû accepter, en échange de nouveaux prêts du **FMI** et de la **Banque mondiale**, un **Programme d'Ajustement Structurel** : réduire les dépenses de l'État (moins de fonctionnaires, fin des subventions sur le riz et le carburant), **libéraliser** les prix et le commerce, **dévaluer** la monnaie pour favoriser les exportations, et ouvrir le pays aux investisseurs (création des **zones franches** en 1989). Ces mesures ont rétabli certains équilibres, mais elles ont d'abord fait monter les prix et reculer les services publics, aggravant la pauvreté." },
    { t: "hh", x: "b) La privatisation" },
    { t: "p", x: "**Privatiser**, c'est vendre une entreprise appartenant à l'État à des investisseurs privés, souvent étrangers, dans l'espoir de la rendre plus efficace. À partir des années 1990, Madagascar a privatisé la banque BTM (devenue **BOA**, 1999), la société pétrolière **Solima** (2000), la compagnie de téléphone **Telma** (2004), des sucreries et des sociétés de transport. L'État a gardé la **JIRAMA** (eau et électricité), Air Madagascar (devenue Madagascar Airlines) et le port de Toamasina. Le bilan est contrasté : de meilleurs services dans la téléphonie, mais des emplois perdus et une dépendance accrue envers les capitaux étrangers." },
    { t: "h", x: "4. Vers plus d'indépendance ?" },
    { t: "p", x: "Réduire la dépendance suppose de **transformer sur place** les produits bruts (chocolat plutôt que fèves de cacao, huiles essentielles plutôt que fleurs), de produire l'**énergie** localement (barrages, solaire), d'augmenter la production de **riz** pour ne plus l'importer et de mieux collecter les **impôts** pour financer le développement sans emprunter." },
  ],
},
];
