// Sujets d'examen par unité, glossaire, bibliographie
module.exports = {
  sujets: {
    1: {
      titre: "Sujet d'examen 3e — Unité 1 : Les conditions et les caractères de l'économie malagasy",
      duree: "1 heure", total: 20,
      parties: [
        { titre: "Première partie — Étude de document (8 points)",
          document: ["Document : extrait du tableau des indicateurs de la population (INSTAT, RGPH-3, 2018).", "Population totale : 25 674 196 habitants — Population en 1993 : 12 238 914 — Taux de croissance annuel moyen : 3,0 % — Densité : 43 hab./km² — Moins de 15 ans : 44 % — 60 ans et plus : 4,5 % — Population rurale : 81 %."],
          questions: [
            ["1. Présentez le document : nature, source, date. (2 pts)", "Il s'agit d'un **tableau statistique** tiré du **troisième Recensement Général de la Population et de l'Habitation (RGPH-3)**, réalisé par l'**INSTAT** en **2018**."],
            ["2. Calculez de combien la population a augmenté entre 1993 et 2018, puis expliquez ce que signifie « temps de doublement ». (3 pts)", "25 674 196 − 12 238 914 = **13 435 282 habitants** de plus : la population a plus que doublé. Le **temps de doublement** est le nombre d'années au bout duquel la population double ; avec 3 % par an, il est d'environ **23 ans** (70 ÷ 3)."],
            ["3. À l'aide du document et de vos connaissances, montrez que la population malgache est jeune et expliquez une conséquence économique de cette jeunesse. (3 pts)", "**44 %** de la population a moins de 15 ans et seulement **4,5 %** a 60 ans et plus : la pyramide des âges a une base très large. Conséquence : chaque adulte actif doit **nourrir, scolariser et soigner** de nombreux enfants ; il faut créer beaucoup d'**emplois** chaque année."],
          ]},
        { titre: "Deuxième partie — Devoir composé (12 points)",
          document: ["Sujet : « Madagascar, un pays sous-développé et dépendant ». Vous rédigerez un texte structuré (introduction, deux ou trois parties, conclusion) en vous appuyant sur des indicateurs et des exemples précis."],
          questions: [
            ["Éléments attendus du corrigé (barème : introduction 2 pts, développement 8 pts, conclusion et rédaction 2 pts)", "**Introduction** : Madagascar, grande île de près de 30 millions d'habitants, est classée parmi les pays les moins avancés ; on peut se demander quels sont les signes de ce sous-développement et de la dépendance de son économie. **1. Une économie sous-développée** : PIB par habitant d'environ **530 dollars** ; IDH de **0,487** (177e sur 193) ; environ **trois Malgaches sur quatre** sous le seuil de pauvreté ; **40 %** des enfants en retard de croissance (malnutrition) ; faible accès à l'électricité et aux soins. **2. Une économie dépendante** : dépendance **financière** (aides et dette publique ≈ 55 % du PIB), **technologique** (machines importées, grandes entreprises étrangères comme Ambatovy), **commerciale** (exportation de produits bruts, importation de pétrole et de riz, balance commerciale déficitaire). **3. Une structure déséquilibrée et des réformes** : secteur primaire = 75 % des emplois mais 23 % du PIB ; Programme d'Ajustement Structurel et privatisations (Solima, Telma) imposés par le FMI et la Banque mondiale. **Conclusion** : sous-développement et dépendance se renforcent mutuellement ; sortir de ce cercle suppose de transformer sur place les produits, de produire l'énergie localement et de mieux nourrir et former la population."],
          ]},
      ],
    },

    2: {
      titre: "Sujet d'examen 3e — Unité 2 : Les activités agricoles",
      duree: "1 heure", total: 20,
      parties: [
        { titre: "Première partie — Étude de document (8 points)",
          document: ["Document : le riz à Madagascar (Ministère de l'Agriculture, INSTAT, Observatoire du Riz, valeurs arrondies).", "Production de paddy : 2020 : 4,2 millions de t — 2021 : 4,6 millions de t — 2022 : 4,4 millions de t — 2023 : 5,1 millions de t. Importations de riz : 2020 : 480 000 t — 2021 : 630 000 t — 2022 : 745 000 t — 2023 : 424 000 t. Consommation : plus de 100 kg de riz par personne et par an. Ménages agricoles : 83 % des ménages (RGPH-3, 2018). Superficie moyenne d'une exploitation : moins de 1 hectare."],
          questions: [
            ["1. Présentez le document : nature, sources, période. (2 pts)", "Il s'agit d'un **tableau de données statistiques** sur le riz, tiré du **Ministère de l'Agriculture**, de l'**INSTAT** et de l'**Observatoire du Riz**, pour la période **2020-2023**."],
            ["2. Décrivez l'évolution de la production et des importations entre 2020 et 2023. (3 pts)", "La **production** augmente globalement de 4,2 à **5,1 millions de tonnes** (+0,9 million), malgré une baisse en 2022. Les **importations** augmentent de 480 000 à un **record de 745 000 t en 2022** (cyclones, sécheresse), puis **diminuent** à 424 000 t en 2023 grâce à la bonne récolte."],
            ["3. À l'aide du document et de vos connaissances, expliquez pourquoi Madagascar, grand pays rizicole, doit importer du riz, et proposez deux solutions. (3 pts)", "Malgré une production importante, la **population augmente de 3 % par an** et consomme beaucoup de riz ; les **rendements** sont faibles (2 à 3 t/ha) à cause des **petites exploitations** (moins de 1 ha), du manque d'**engrais**, d'**irrigation** et de crédit, des **cyclones** et des **sécheresses** ; les pertes après récolte et la **soudure** obligent à importer. Solutions : diffuser le **SRI** et les semences améliorées, réhabiliter les **canaux d'irrigation**, améliorer le **stockage** et les **routes**, faciliter le **crédit** et les **engrais**, aménager de nouvelles terres."],
          ]},
        { titre: "Deuxième partie — Devoir composé (12 points)",
          document: ["Sujet : « L'agriculture malgache : une agriculture diversifiée mais fragile ». Vous rédigerez un texte structuré (introduction, deux ou trois parties, conclusion) en vous appuyant sur des exemples précis tirés des cultures, de l'élevage, de la pêche et de la forêt."],
          questions: [
            ["Éléments attendus du corrigé (barème : introduction 2 pts, développement 8 pts, conclusion et rédaction 2 pts)", "**Introduction** : l'agriculture fait vivre trois Malgaches sur quatre et fournit 22 % du PIB ; on peut se demander pourquoi, malgré sa diversité, elle ne parvient pas à nourrir le pays. **1. Une agriculture diversifiée** : cultures **vivrières** (riz 5,1 Mt, manioc, maïs), **industrielles** (canne, coton, sisal), d'**exportation** (vanille de la SAVA, girofle, café, litchi, cacao) ; **élevage** bovin extensif (environ 10 millions de zébus), élevage laitier du Vakinankaratra ; **pêche** traditionnelle et industrielle (crevettes, thon), aquaculture ; ressources de la **forêt**. **2. Une agriculture fragile** : modes de culture traditionnels (**tavy**, angady), **petites exploitations**, faibles rendements, manque de crédit, d'engrais, d'irrigation, mauvaises routes ; **aléas** (cyclones, sécheresses du Sud, criquets) ; conséquences : **importations de riz**, malnutrition, dépendance des cours mondiaux (vanille), **déforestation**. **3. Des solutions** : intensification (SRI), irrigation, crédit rural, coopératives, routes et stockage, transformation locale, **reboisement**, protection des zones de pêche. **Conclusion** : richesse potentielle mais résultats insuffisants ; l'avenir dépend de la modernisation et de la protection des ressources naturelles."],
          ]},
      ],
    },
    3: {
      titre: "Sujet d'examen 3e — Unité 3 : Les activités industrielles",
      duree: "1 heure", total: 20,
      parties: [
        { titre: "Première partie — Étude de document (8 points)",
          document: ["Document : le secteur minier et l'énergie à Madagascar (ITIE Madagascar 2022 ; JIRAMA ; Banque mondiale 2023, valeurs arrondies).", "Part des mines dans le PIB : 4,6 % — Part des mines dans les exportations : 49 % — Premier produit exporté : le nickel (Ambatovy, environ 8 000 emplois) — Accès des ménages à l'électricité : 36 % (villes plus de 70 %, campagnes moins de 10 %) — Origine de l'électricité : thermique 55 %, hydraulique 40 %, solaire 5 % — Potentiel hydroélectrique : 7 800 MW, moins de 3 % équipés."],
          questions: [
            ["1. Présentez le document : nature, sources, date. (2 pts)", "Un **ensemble de données statistiques** sur les mines et l'énergie, tiré de l'**ITIE** (Initiative pour la Transparence dans les Industries Extractives), de la **JIRAMA** et de la **Banque mondiale**, pour les années **2022-2023**."],
            ["2. Comparez la part des mines dans le PIB et dans les exportations. Que peut-on en conclure ? (3 pts)", "Les mines ne représentent que **4,6 % du PIB** mais **49 % des exportations** : elles rapportent des **devises** mais créent **peu de richesse et d'emplois** dans le pays, car les minerais sont exportés **bruts** par des sociétés **étrangères** dont les profits sortent du pays ; l'économie est **dépendante** de quelques produits."],
            ["3. À partir du document et de vos connaissances, montrez que l'énergie est un frein à l'industrialisation et proposez deux solutions. (3 pts)", "Seuls **36 %** des ménages ont l'électricité ; plus de la moitié du courant vient de centrales **thermiques** au fioul **importé**, donc **cher** ; la JIRAMA ne suffit pas à la demande : **délestages**, groupes électrogènes, coûts de production élevés, usines découragées. Solutions : équiper le **potentiel hydroélectrique** (Sahofika, Volobe), développer le **solaire**, réformer la JIRAMA, réduire les pertes."],
          ]},
        { titre: "Deuxième partie — Devoir composé (12 points)",
          document: ["Sujet : « Pourquoi Madagascar est-elle si peu industrialisée ? » Vous rédigerez un texte structuré (introduction, deux ou trois parties, conclusion) présentant les types d'industries existants, les problèmes de l'industrie malgache et les perspectives."],
          questions: [
            ["Éléments attendus du corrigé (barème : introduction 2 pts, développement 8 pts, conclusion et rédaction 2 pts)", "**Introduction** : l'industrie ne représente qu'environ 10 % du PIB pour l'industrie manufacturière ; Madagascar importe la plupart des produits fabriqués. **1. Une industrie légère et concentrée** : **agro-alimentaire** (sucre, boissons, lait, farine), **extractive** (nickel d'Ambatovy, ilménite de QMM, chrome, or, saphirs), **textile** des zones franches (200 000 emplois, AGOA), autres industries (ciment, savon, métallurgie) ; concentration à **Antananarivo**, Antsirabe, Toamasina et dans les ports ; grandes entreprises étrangères, PME, **artisanat** (2 millions de personnes). **2. Cinq problèmes** : **matières premières** irrégulières ou importées (pétrole, acier, tissus) ; **main-d'œuvre** peu qualifiée ; **capitaux** insuffisants, crédit cher, instabilité politique ; **débouchés** étroits (faible pouvoir d'achat, concurrence des importations) ; **communications et énergie** défaillantes (routes, délestages). **3. Perspectives** : formation technique, crédit aux PME, énergie (barrages, solaire), routes et port, transformation sur place, zones industrielles en province, stabilité et lutte contre la corruption. **Conclusion** : l'industrialisation est possible grâce aux ressources et à la main-d'œuvre, mais exige des investissements de long terme dans l'énergie, l'éducation et les infrastructures."],
          ]},
      ],
    },
    4: {
      titre: "Sujet d'examen 3e — Unité 4 : Les transports, le commerce et le tourisme",
      duree: "1 heure", total: 20,
      parties: [
        { titre: "Première partie — Étude de document (8 points)",
          document: ["Document : le commerce extérieur de Madagascar en 2023 (Banque mondiale/WITS, INSTAT, valeurs arrondies).", "Exportations : 3,2 milliards de dollars (nickel 25 %, vêtements 15 %, vanille 8 %, girofle 8 %, ilménite 5 %, or 4 %). Importations : 4,7 milliards de dollars (produits pétroliers 19 %, machines 15 %, véhicules 8 %, riz 4 %, médicaments 4 %). Principaux clients : France 14,5 %, États-Unis 12,6 %, Japon 8 %, Corée du Sud 8 %. Principaux fournisseurs : Chine 17 %, Oman 13,5 %, France 11 %, Inde 9 %. Arrivées de touristes : 375 000 en 2019, 260 000 en 2023."],
          questions: [
            ["1. Présentez le document : nature, sources, date. (2 pts)", "Un **ensemble de données statistiques** sur le commerce extérieur et le tourisme de Madagascar en **2023**, tiré de la **Banque mondiale (WITS)** et de l'**INSTAT**."],
            ["2. Calculez le solde de la balance commerciale et qualifiez-le ; comparez la nature des produits exportés et importés. (3 pts)", "3,2 − 4,7 = **−1,5 milliard de dollars** : balance **déficitaire**. Madagascar **exporte des matières premières** brutes ou peu transformées (nickel, vanille, girofle, ilménite, or) et des vêtements, et **importe de l'énergie** (pétrole), des **produits manufacturés** (machines, véhicules, médicaments) et des **aliments** (riz) : c'est un échange inégal typique d'un pays sous-développé."],
            ["3. À l'aide du document et de vos connaissances, expliquez comment le tourisme peut aider à réduire ce déficit et quelles sont ses limites. (3 pts)", "Le tourisme apporte des **devises** (700 à 900 millions de dollars avant 2020, deuxième source après les mines) qui compensent une partie du déficit, et crée des emplois. Limites : les arrivées restent **faibles** (260 000 en 2023, moins qu'en 2019) à cause des vols chers, des routes, de l'insécurité et des crises ; une partie des devises **repart à l'étranger** ; le secteur est **fragile** (Covid-19)."],
          ]},
        { titre: "Deuxième partie — Devoir composé (12 points)",
          document: ["Sujet : « Les transports, un obstacle au développement de Madagascar ». Vous rédigerez un texte structuré (introduction, deux ou trois parties, conclusion) décrivant les différents réseaux de transport, leurs faiblesses et leurs conséquences sur le commerce et le tourisme."],
          questions: [
            ["Éléments attendus du corrigé (barème : introduction 2 pts, développement 8 pts, conclusion et rédaction 2 pts)", "**Introduction** : grande île de 1 600 km de long, Madagascar dépend de ses transports pour relier ses régions et s'ouvrir au monde ; or ceux-ci sont insuffisants. **1. Des réseaux variés mais faibles** : **route** (90 % du trafic, réseau en étoile autour d'Antananarivo, 31 600 km dont moins de 6 000 bitumés, moins de 15 % en bon état) ; **chemin de fer** (877 km, deux réseaux séparés, matériel ancien) ; **aérien** (Ivato, vols chers) ; **maritime** (Toamasina 80 % du trafic, cabotage) ; **fluvial** (canal des Pangalanes) ; **télécommunications** en progrès (mobile 60 %). **2. Des conséquences économiques lourdes** : **enclavement** de régions entières, produits agricoles invendus, prix élevés, industries concentrées près de la capitale et du port, coût du **commerce** intérieur et extérieur, **tourisme** freiné par les routes et les vols, régions du Sud isolées (kere). **3. Des solutions** : réhabilitation des routes nationales et pistes rurales, extension du port de Toamasina, modernisation du rail, ouverture du ciel, entretien durable (Fonds routier). **Conclusion** : sans transports fiables, ni l'agriculture, ni l'industrie, ni le tourisme ne peuvent se développer ; c'est un investissement prioritaire."],
          ]},
      ],
    },
  },

  glossaire: [
    ["Accroissement naturel", "Différence entre le nombre de naissances et le nombre de décès dans une population pendant un an."],
    ["AGOA (African Growth and Opportunity Act)", "Loi américaine qui permet aux pays africains, dont Madagascar, d'exporter sans droits de douane vers les États-Unis, notamment les vêtements."],
    ["Alizé", "Vent régulier venu de l'océan Indien qui apporte l'humidité et la pluie sur la côte Est de Madagascar."],
    ["Aquaculture", "Élevage d'animaux aquatiques (crevettes, poissons, algues) en mer, en étang ou en bassin ; la pisciculture est l'élevage des poissons."],
    ["Artisanat", "Fabrication de produits à la main ou avec des outils simples, dans de très petits ateliers, souvent familiaux."],
    ["Balance commerciale", "Différence entre la valeur des exportations et la valeur des importations d'un pays ; elle est déficitaire quand on importe plus que l'on n'exporte."],
    ["Bush épineux (fourré xérophile)", "Végétation du Sud de Madagascar adaptée à la sécheresse : plantes grasses, didiereas, euphorbes, cactus."],
    ["Cabotage", "Transport maritime le long des côtes, d'un port à l'autre du même pays."],
    ["Cultures vivrières / industrielles / d'exportation", "Cultures destinées respectivement à nourrir la population (riz, manioc), à fournir les usines (canne, coton) ou à être vendues à l'étranger (vanille, girofle)."],
    ["Débouché", "Marché sur lequel une entreprise peut vendre sa production."],
    ["Déforestation (défrichement)", "Destruction de la forêt par la culture sur brûlis, la coupe du bois ou le charbonnage."],
    ["Délestage", "Coupure d'électricité organisée par le distributeur parce que la production ne suffit pas à la demande."],
    ["Densité de population", "Nombre moyen d'habitants par kilomètre carré."],
    ["Dépendance économique", "Situation d'un pays qui ne peut pas fonctionner sans les capitaux, les techniques ou les marchés de l'étranger."],
    ["Dette publique", "Ensemble des sommes empruntées par l'État et qu'il doit rembourser."],
    ["Devises", "Monnaies étrangères (dollar, euro) que le pays obtient grâce aux exportations, au tourisme ou aux transferts, et qui servent à payer les importations."],
    ["Écotourisme", "Tourisme de découverte de la nature qui respecte l'environnement et fait participer les populations locales aux bénéfices."],
    ["Élevage extensif / intensif", "Élevage sur de grands espaces avec peu de soins et de faibles rendements (zébus de l'Ouest) ; élevage sur peu d'espace avec beaucoup de soins et d'aliments (laiteries d'Antsirabe)."],
    ["Endémique (espèce)", "Espèce animale ou végétale qui n'existe que dans une région du monde, comme les lémuriens à Madagascar."],
    ["Entreprise franche (zone franche)", "Entreprise qui exporte presque toute sa production et bénéficie en échange d'exonérations d'impôts et de droits de douane."],
    ["Exportations / importations", "Marchandises vendues à l'étranger / marchandises achetées à l'étranger."],
    ["Facteur de localisation", "Élément qui attire une industrie dans un lieu : matières premières, énergie, main-d'œuvre, marché, voies de communication, capitaux."],
    ["IDH (Indicateur de Développement Humain)", "Indicateur du PNUD, compris entre 0 et 1, qui combine la santé, l'éducation et le niveau de vie."],
    ["Industrie", "Ensemble des activités qui transforment des matières premières en produits finis dans des usines, avec des machines et de l'énergie."],
    ["Industrie extractive", "Activité qui extrait du sous-sol des minerais, des pierres ou des combustibles : le secteur des mines."],
    ["Inflation", "Hausse générale et durable des prix, qui réduit le pouvoir d'achat."],
    ["Kere", "Famine qui frappe le Grand Sud de Madagascar lorsque les pluies manquent plusieurs années de suite."],
    ["Lavaka", "Grande cicatrice d'érosion creusée par les pluies dans les sols de latérite des Hautes Terres."],
    ["Malnutrition", "Alimentation déséquilibrée, qui manque de certains éléments (protéines, vitamines), même si la quantité est suffisante."],
    ["Matière première", "Produit brut (canne à sucre, coton, minerai, bois) que l'industrie transforme."],
    ["Pêche traditionnelle / industrielle", "Pêche en pirogue près des côtes pour la consommation locale / pêche avec de grands navires équipés (chalutiers, thoniers) pour la vente et l'exportation."],
    ["PIB (Produit Intérieur Brut)", "Valeur de toutes les richesses produites dans un pays pendant une année."],
    ["PIB par habitant", "PIB divisé par le nombre d'habitants : il mesure la richesse moyenne produite par personne."],
    ["PMI-PME", "Petites et moyennes industries ou entreprises, de 10 à 200 salariés environ."],
    ["Pouvoir d'achat", "Quantité de biens et de services qu'un revenu permet d'acheter ; il dépend des revenus et des prix."],
    ["Privatisation", "Vente d'une entreprise appartenant à l'État à des investisseurs privés."],
    ["Programme d'Ajustement Structurel (PAS)", "Ensemble de réformes économiques (réduction des dépenses publiques, libéralisation, privatisation) imposées par le FMI et la Banque mondiale en échange de prêts."],
    ["Pyramide des âges", "Graphique qui représente la répartition d'une population par âge et par sexe."],
    ["Reboisement", "Plantation d'arbres pour reconstituer une forêt détruite (eucalyptus, pins, espèces locales)."],
    ["Région naturelle", "Espace dont le relief, le climat, la végétation et les cours d'eau présentent les mêmes caractères."],
    ["Rendement", "Quantité produite par unité de surface, par exemple en tonnes de riz par hectare."],
    ["Riziculture irriguée", "Culture du riz dans des rizières inondées grâce à des canaux, avec repiquage ; elle permet des rendements supérieurs au riz pluvial."],
    ["Secteur informel", "Ensemble des activités économiques non déclarées à l'État (pas d'impôts, pas de protection sociale) : petits commerces, artisans, transports."],
    ["Secteur primaire / secondaire / tertiaire", "Les trois groupes d'activités économiques : production de matières premières (agriculture, pêche, forêt) ; transformation (industrie, artisanat, bâtiment) ; services (commerce, transport, administration, tourisme)."],
    ["Seuil de pauvreté", "Revenu minimum en dessous duquel une personne est considérée comme pauvre ; le seuil international est de 2,15 dollars par jour."],
    ["Soudure (période de)", "Période entre la fin des réserves de l'ancienne récolte et la nouvelle récolte (décembre à mars pour le riz), pendant laquelle les prix montent."],
    ["Sous-alimentation", "Alimentation insuffisante en quantité (moins de 2 100 calories par jour)."],
    ["SRI (Système de Riziculture Intensive)", "Méthode mise au point à Madagascar : repiquage de très jeunes plants espacés, un par un, avec peu d'eau ; elle peut doubler les rendements."],
    ["Tanety", "Colline des Hautes Terres, cultivée en sec (maïs, manioc, légumes), par opposition aux rizières des bas-fonds."],
    ["Taux de croissance annuel", "Augmentation de la population en pourcentage au cours d'une année."],
    ["Tavy", "Culture sur brûlis pratiquée surtout dans les régions forestières de l'Est."],
    ["Temps de doublement", "Nombre d'années nécessaires pour que la population d'un pays double ; on l'estime en divisant 70 par le taux de croissance annuel."],
    ["Termes de l'échange (détérioration des)", "Baisse du prix des produits bruts exportés par rapport au prix des produits manufacturés importés : il faut exporter plus pour importer autant."],
    ["Tourisme durable", "Tourisme qui profite aux populations locales sans détruire la nature ni la culture, aujourd'hui et pour les générations futures."],
    ["Zébu", "Bœuf à bosse élevé à Madagascar (environ 10 millions de têtes), symbole de richesse et de prestige."],
  ],

  bibliographie: [
    ["Programme officiel", "Ministère de l'Éducation Nationale, Direction des Curricula et des Intrants, Programmes scolaires — Classe de 3ème, édition à partir de l'année scolaire 2015-2016 (arrêté n° 3602/99-MinESEB), pages 103 à 113 (Géographie)."],
    ["Population", "INSTAT, Troisième Recensement Général de la Population et de l'Habitation (RGPH-3, 2018), Résultats globaux, tome 1 (2020) et rapport État et structure de la population (2021) — www.instat.mg"],
    ["Population (prévisions)", "Nations Unies Madagascar, Analyse commune de pays — annexe « Peuple » (2023) — madagascar.un.org"],
    ["Développement humain", "PNUD, Rapport sur le développement humain 2023-2024, fiche pays Madagascar (IDH 0,487, 177e sur 193) — hdr.undp.org"],
    ["Économie, pauvreté", "Banque mondiale, Indicateurs du développement dans le monde et présentation du pays Madagascar (2023-2024) — donnees.banquemondiale.org ; Banque mondiale, communiqué du 7 avril 2023 (accès à l'électricité 33,7 %)."],
    ["Commerce extérieur", "Banque mondiale, World Integrated Trade Solution (WITS), profil Madagascar 2023 ; Organisation mondiale du commerce, profils commerciaux 2023 (exportations 3,2 Mds USD, importations 4,7 Mds USD)."],
    ["Secteur minier", "Initiative pour la Transparence dans les Industries Extractives (ITIE), fiche Madagascar (2022 : 4,6 % du PIB, 49 % des exportations) — eiti.org"],
    ["Milieu naturel", "Foiben-Taosarintanin'i Madagasikara (FTM), Atlas de Madagascar ; Direction Générale de la Météorologie, normales climatiques."],
    ["Alimentation", "INSTAT et UNICEF, Enquête par grappes à indicateurs multiples (MICS) Madagascar 2018 (retard de croissance des enfants de moins de 5 ans)."],
    ["Agriculture", "FAO, FAOSTAT, productions végétales et animales Madagascar (2023) — fao.org/faostat ; Ministère de l'Agriculture et de l'Élevage, Recensement général de l'agriculture ; INSTAT, RGPH-3, thème « Ménages agricoles » (2022) ; Observatoire du Riz et INSTAT, statistiques des importations de riz 2020-2023."],
    ["Élevage et pêche", "Ministère de la Pêche et de l'Économie bleue, annuaire statistique (2022) ; Groupement des Aquaculteurs et Pêcheurs de Crevettes de Madagascar (GAPCM) ; Banque mondiale, projet SWIOFish 2 (pêche durable)."],
    ["Forêt", "Vieilledent G. et al., « Combining global tree cover loss data with historical national forest cover maps to look at six decades of deforestation and forest fragmentation in Madagascar », Biological Conservation, 2018 ; Global Forest Watch, fiche Madagascar (2001-2023) — globalforestwatch.org ; Ministère de l'Environnement et du Développement Durable, campagnes de reboisement."],
    ["Industrie et mines", "ITIE Madagascar, rapport 2022 — eiti.org/madagascar ; Ministère de l'Industrialisation, du Commerce et de la Consommation ; Groupement des Entreprises Franches et Partenaires (GEFP) ; Economic Development Board of Madagascar (EDBM) ; sites d'Ambatovy et de QMM/Rio Tinto ; Loi n° 2017-047 sur le développement de l'industrie."],
    ["Énergie", "JIRAMA, rapports d'activité ; Ministère de l'Énergie et des Hydrocarbures, Nouvelle Politique de l'Énergie 2015-2030 ; Banque mondiale, Madagascar Energy Sector (2023) ; Agence internationale de l'énergie, profil Madagascar."],
    ["Transports et télécommunications", "Autorité Routière de Madagascar et Ministère des Travaux Publics (état du réseau 2021) ; Madarail ; Agence Portuaire, Maritime et Fluviale (APMF) ; Société du Port à gestion Autonome de Toamasina (SPAT) ; Aviation Civile de Madagascar ; ARTEC, observatoire des télécommunications (2023) ; Banque mondiale, Projet de connectivité des transports."],
    ["Commerce intérieur", "INSTAT, Enquête permanente auprès des ménages (EPM 2021-2022) et indice des prix à la consommation (2023-2024) ; Banque mondiale, Note sur la pauvreté Madagascar (2024)."],
    ["Tourisme", "Ministère du Tourisme et de l'Artisanat, statistiques des arrivées 2015-2023 ; Office National du Tourisme de Madagascar (ONTM) ; Madagascar National Parks ; UNESCO, Liste du patrimoine mondial (Ambohimanga, Tsingy de Bemaraha, forêts humides de l'Atsinanana) ; Banque mondiale, Note sur le tourisme (2022)."],
  ],
};
