function fig(file,legende,place='lecon'){return {file,legende,place};}
const F={resp:'gen/systeme-respiratoire.jpg',mouv:'gen/mouvements-respiratoires.jpg',gaz:'gen/echanges-gazeux.jpg',circ:'gen/systeme-circulatoire.jpg',coeur:'gen/coeur-vaisseaux.jpg',double:'gen/double-circulation.jpg',maquette:'gen/maquette-circulation.jpg',sang:'gen/constituants-sang.jpg',rolesang:'gen/roles-sang.jpg',abo:'gen/groupes-abo.jpg',ist:'gen/ist-sida.jpg',trans:'gen/transmission-ist.jpg',depist:'gen/depistage-ist.jpg',prev:'gen/prevention-ist.jpg',rocks:'gen/types-roches.jpg',mag:'gen/roche-magmatique.jpg',sed:'gen/roche-sedimentaire.jpg',cycle:'gen/cycle-roches.jpg',usages:'gen/usages-roches.jpg',mad:'gen/roches-madagascar.jpg'};
const labels={resp:'Le système respiratoire : organes.',mouv:'Les mouvements respiratoires.',gaz:'Les échanges gazeux.',circ:'Le système circulatoire.',coeur:'Le cœur et les vaisseaux.',double:'La double circulation.',maquette:'Maquette de circulation.',sang:'Les constituants du sang.',rolesang:'Les rôles des constituants du sang.',abo:'Les groupes sanguins et la compatibilité ABO.',ist:'Les IST et le VIH.',trans:'Les modes de transmission des IST.',depist:'Le dépistage et les soins.',prev:'Prévenir les IST et lutter contre les discriminations.',rocks:'Identifier les roches et leurs propriétés.',mag:'La formation des roches magmatiques.',sed:'La formation des roches sédimentaires.',cycle:'Le cycle des roches.',usages:'Les propriétés et les utilisations des roches.',mad:'Une collection de roches locales à Madagascar.'};
const map=[['I:0','resp'],['I:1','mouv'],['I:2','gaz'],['I:3','coeur'],['I:4','double'],['I:5','double'],['I:6','double'],['I:7','maquette'],['I:8','sang'],['I:9','rolesang'],['I:10','abo'],['I:11','abo'],['II:0','ist'],['II:1','ist'],['II:2','trans'],['II:3','trans'],['II:4','prev'],['II:5','depist'],['II:6','prev'],['III:0','rocks'],['III:1','mag'],['III:2','mag'],['III:3','sed'],['III:4','sed'],['III:5','rocks'],['III:6','rocks'],['III:7','cycle'],['III:8','cycle'],['III:9','usages'],['III:10','usages'],['III:11','mad']];
const IMG={};for(const [k,v] of map)IMG[k]=[fig(F[v],labels[v])];
const REVISION_IMAGES={I:fig(F.circ,'Bilan illustré : respiration, circulation et sang.'),II:fig(F.prev,'Bilan illustré : prévention des IST et solidarité.'),III:fig(F.cycle,'Bilan illustré : formation et cycle des roches.')};
const EXAM_IMAGES={I:[fig(F.abo,'Document d’examen : groupes sanguins et compatibilité.')],II:[fig(F.ist,'Document d’examen : prévention des IST.')],III:[fig(F.cycle,'Document d’examen : cycle des roches.')]};
const ANNEXE_IMAGES=[fig(F.mad,'Collection de roches locales.')];
function apply(n,topics){topics.forEach((t,i)=>{const x=IMG[n+':'+i];if(x){t.images=x;t.exoImage=x[0];t.corrigeImage=x[0];}});return topics;}
module.exports={IMG,REVISION_IMAGES,EXAM_IMAGES,ANNEXE_IMAGES,apply,fig};
