function fig(file,legende,place='lecon'){return {file,legende,place};}
const F={resp:'gen/systeme-respiratoire.jpg',circ:'gen/systeme-circulatoire.jpg',sang:'gen/constituants-sang.jpg',abo:'gen/groupes-abo.jpg',ist:'gen/ist-sida.jpg',prev:'gen/prevention-ist.jpg',rocks:'gen/types-roches.jpg',cycle:'gen/cycle-roches.jpg',usages:'gen/usages-roches.jpg',mad:'gen/roches-madagascar.jpg'};
const labels={resp:'Le système respiratoire : organes et mouvements.',circ:'Le système circulatoire : cœur, vaisseaux et double circulation.',sang:'Les constituants du sang et leurs fonctions.',abo:'Les groupes sanguins et la compatibilité ABO.',ist:'Les IST, le VIH et l’accompagnement au centre de santé.',prev:'Prévenir les IST : information, dépistage, soins et respect.',rocks:'Les trois groupes de roches et leurs modes de formation.',cycle:'Le cycle des roches.',usages:'Les propriétés et les utilisations des roches.',mad:'Une collection de roches locales à Madagascar.'};
const map=[['I:0','resp'],['I:1','resp'],['I:2','resp'],['I:3','circ'],['I:4','circ'],['I:5','circ'],['I:6','circ'],['I:7','circ'],['I:8','sang'],['I:9','sang'],['I:10','abo'],['I:11','abo'],['II:0','ist'],['II:1','ist'],['II:2','ist'],['II:3','ist'],['II:4','prev'],['II:5','prev'],['II:6','prev'],['III:0','rocks'],['III:1','rocks'],['III:2','rocks'],['III:3','rocks'],['III:4','rocks'],['III:5','cycle'],['III:6','cycle'],['III:7','cycle'],['III:8','rocks'],['III:9','usages'],['III:10','usages'],['III:11','mad']];
const IMG={};for(const [k,v] of map)IMG[k]=[fig(F[v],labels[v])];
const REVISION_IMAGES={I:fig(F.circ,'Bilan illustré : respiration, circulation et sang.'),II:fig(F.prev,'Bilan illustré : prévention des IST et solidarité.'),III:fig(F.cycle,'Bilan illustré : formation et cycle des roches.')};
const EXAM_IMAGES={I:[fig(F.abo,'Document d’examen : groupes sanguins et compatibilité.')],II:[fig(F.ist,'Document d’examen : prévention des IST.')],III:[fig(F.cycle,'Document d’examen : cycle des roches.')]};
const ANNEXE_IMAGES=[fig(F.mad,'Collection de roches locales.')];
function apply(n,topics){topics.forEach((t,i)=>{const x=IMG[n+':'+i];if(x){t.images=x;t.exoImage=x[0];t.corrigeImage=x[0];}});return topics;}
module.exports={IMG,REVISION_IMAGES,EXAM_IMAGES,ANNEXE_IMAGES,apply,fig};
