const EX={
 mad:{obj:'constituer et classer une collection de roches locales',obs:'une collection de roches locales et leurs étiquettes',synth:'Une collection de roches locales se classe avec rigueur selon l’origine, les propriétés et les usages. Chaque échantillon doit être identifié, décrit et conservé avec sécurité.',terms:['collection','roche locale','classification','propriété','usage']},
 respiratoire:{obj:'décrire les organes et le fonctionnement du système respiratoire',obs:'un schéma de l’appareil respiratoire et une situation d’effort',synth:'Le système respiratoire comprend les voies respiratoires et les poumons. Les mouvements de la cage thoracique, commandés notamment par le diaphragme, permettent les échanges de dioxygène et de dioxyde de carbone.',terms:['fosses nasales','trachée','bronches','poumons','diaphragme']},
 circulation:{obj:'décrire les organes et le fonctionnement du système circulatoire',obs:'un schéma du cœur et des vaisseaux sanguins',synth:'Le système circulatoire comprend le cœur, les artères, les veines et les capillaires. La petite circulation relie le cœur aux poumons ; la grande circulation relie le cœur à tous les organes.',terms:['cœur','artères','veines','capillaires','circulation pulmonaire']},
 sang:{obj:'identifier les constituants du sang et expliquer leurs fonctions',obs:'une image de sang séparé et un frottis sanguin schématisé',synth:'Le sang est constitué de plasma et d’éléments figurés. Les globules rouges transportent les gaz respiratoires, les globules blancs défendent l’organisme et les plaquettes participent à la coagulation.',terms:['plasma','globules rouges','globules blancs','plaquettes']},
 abo:{obj:'déterminer la compatibilité des groupes sanguins du système ABO',obs:'un tableau de compatibilité des groupes sanguins',synth:'Les groupes sanguins ABO sont A, B, AB et O. La compatibilité dépend des antigènes et des anticorps ; une transfusion doit toujours être contrôlée par un professionnel de santé.',terms:['groupe A','groupe B','groupe AB','groupe O','compatibilité']},
 ist:{obj:'identifier les caractéristiques des IST et du SIDA',obs:'des documents de prévention et une fiche d’information scientifique',synth:'Les IST sont des infections transmissibles lors de contacts sexuels. Elles peuvent être dues à des virus, des bactéries ou des parasites. Le VIH peut affaiblir progressivement les défenses immunitaires.',terms:['IST','VIH','SIDA','infection','dépistage']},
 transmission:{obj:'expliquer les modes de transmission et les facteurs de risque des IST',obs:'un schéma des voies de transmission et des situations à risque',synth:'Une IST se transmet notamment par des rapports sexuels non protégés et, pour certaines infections, par le sang ou de la mère à l’enfant. On ne reconnaît pas toujours une infection à son apparence : le dépistage est essentiel.',terms:['transmission','sang','rapport sexuel','risque','prévention']},
 prevention:{obj:'justifier les mesures individuelles et collectives de prévention des IST',obs:'des affiches de sensibilisation et des témoignages',synth:'La prévention repose sur une information fiable, l’abstinence ou des relations responsables, le préservatif, le dépistage et le recours aux soins. Les personnes vivant avec le VIH doivent être respectées et ne doivent pas être discriminées.',terms:['préservatif','dépistage','traitement','sensibilisation','respect']},
 rocks:{obj:'reconnaître et classer les roches selon leurs propriétés',obs:'des échantillons ou photographies de roches locales',synth:'Une roche est un matériau naturel formé d’un ou plusieurs minéraux. Sa texture, sa dureté, sa couleur et sa réaction à l’eau ou à l’acide peuvent aider à l’identifier, sans remplacer l’analyse scientifique.',terms:['roche','minéral','texture','dureté','propriété']},
 magmatique:{obj:'expliquer la formation des roches magmatiques',obs:'des photographies de lave, granite et basalte',synth:'Les roches magmatiques proviennent du refroidissement et de la solidification d’un magma. Un refroidissement lent en profondeur forme des cristaux visibles ; un refroidissement rapide en surface donne souvent une pâte fine.',terms:['magma','lave','refroidissement','granite','basalte']},
 sedimentaire:{obj:'expliquer la formation des roches sédimentaires',obs:'un document montrant l’érosion, le transport et les couches de sédiments',synth:'Les roches sédimentaires se forment par accumulation de sédiments, puis compaction et cimentation. Elles peuvent conserver des traces ou des fossiles et se présentent souvent en couches.',terms:['sédiment','érosion','dépôt','compaction','fossile']},
 metamorphique:{obj:'expliquer la formation des roches métamorphiques',obs:'des roches présentant des foliations ou des cristaux transformés',synth:'Les roches métamorphiques résultent de la transformation de roches préexistantes sous l’action de la pression et de la température, sans fusion complète.',terms:['métamorphisme','pression','température','transformation','foliation']},
 cycle:{obj:'reconstituer le cycle des roches',obs:'un schéma du cycle des roches',synth:'Les roches se transforment continuellement : fusion, refroidissement, altération, érosion, sédimentation, enfouissement et métamorphisme. Une même roche peut donc changer de groupe au cours du temps.',terms:['cycle des roches','fusion','altération','sédimentation','métamorphisme']},
 usages:{obj:'relier les propriétés des roches à leurs utilisations',obs:'des objets en sel, brique, ciment, pierre et matériaux locaux',synth:'Les utilisations d’une roche dépendent de ses propriétés : dureté, résistance, porosité, solubilité ou aptitude à être taillée. Les roches sont utilisées dans la construction, la poterie, la sculpture, l’industrie et parfois comme source de matières premières.',terms:['propriété','construction','poterie','ciment','matériau']}
};
function makeTopic(key,titre,unit,idx){const e=EX[key];const prev=idx?'Qu’avons-nous appris à la séance précédente ?':'Que savons-nous déjà sur ce phénomène ?';return {type:'cours',titre,theme:unit,ras:'Atteindre le résultat d’apprentissage du programme T8',valeurs:key==='ist'||key==='transmission'||key==='prevention'?'Respect de soi, responsabilité':key==='usages'?'Responsabilité, culture de l’excellence':'Estime de soi, créativité',objectif:e.obj,supportMeta:'Schéma, document scientifique, échantillon ou maquette',revision:[[prev,'Les élèves mobilisent leurs connaissances antérieures.']],mise:[`À partir de ${e.obs}, que pouvons-nous observer et expliquer ?`,'Les élèves formulent des hypothèses et les confrontent.'],observation:e.obs,observationSupport:'Document ou schéma scientifique',technAna:'Observation, questionnement et travail en groupes',qa:[['Que montre le document ?',e.synth],['Quels indices permettent de répondre ?',`Les éléments observés sont mis en relation avec les notions : ${e.terms.join(', ')}.`],['Quelle conclusion pouvons-nous tirer ?',e.synth]],synthese:e.synth,motsCles:e.terms,contenu:[{sousTitre:'1. Observation et vocabulaire',texte:e.synth,liste:e.terms.map(x=>`• ${x} : notion à retenir et à replacer dans une situation scientifique.`)},{sousTitre:'2. Démarche scientifique',texte:'Les apprenants observent, proposent une explication, recherchent des indices dans le document ou le modèle, puis justifient leur conclusion.'},{sousTitre:'À retenir',texte:e.synth}],appExos:[{type:'qcm',consigne:'Choisis la bonne réponse.',pointsPar:1,items:[{q:`La notion centrale de cette séance est liée à…`,opts:[e.terms[0], 'un phénomène sans rapport','une notion géographique'],ok:0,expl:e.synth},{q:`Quel comportement convient dans une démarche scientifique ?`,opts:['observer et justifier','deviner sans observer','recopier sans comprendre'],ok:0}]},{type:'qr',consigne:'Réponds avec une phrase scientifique.',pointsPar:2,items:[{q:`Explique brièvement : ${e.obj}.`,r:e.synth}]}],evalExos:[{type:'trous',consigne:'Complète avec les mots proposés.',mots:e.terms.slice(0,3),pointsPar:1,items:[{phrase:`La notion principale étudiée est ______.`,mot:e.terms[0]},{phrase:`Un élément important est ______.`,mot:e.terms[1]},{phrase:`On peut aussi observer ______.`,mot:e.terms[2]}]},{type:'qr',consigne:'Réponds et justifie.',pointsPar:2,items:[{q:`Donne une conséquence ou une utilisation de la notion étudiée.`,r:e.synth}]}]};}
module.exports={makeTopic};
